### ISSUE TITLE
Allow for multiple addons using badge

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#10]
And we should let users choose what addon can use the badge.
Also, what would happen if the addon the user configured to use the badge got disabled? :thinking:

**Comment by Explosion-Scratch** [comment]
Bump?

**Comment by TheColaber** [comment]
What addons would want to use the badge? If disabled, there could be a message in the popup that let's you know.

**Comment by lisa-wolfgang** [comment]
When more functionality for the badge does come around, I think it would be more straightforward to have a `select` type option bar on the message count badge addon and just have that addon get access to the badge, unless we have mutually exclusive addons in the future.

**Comment by WorldLanguages** [comment]
If another addon wants to use the badge, let's open another issue.

**Comment by return-misaPuding** [comment]
Which badge do you mean?

**Comment by RedGuy12** [comment]
The extension icon badge, currently reserved for message count


________________________________

**Comment by CST1229** [comment]
Maybe possible allow 2 max badges, one being at the top of the extension icon (the message count overrides any other addon that tries to take this spot), the other being at the bottom.
