### ISSUE TITLE
Infinite studio leaving

### ISSUE THREAD

**Issue by oof-le-oof** [ScratchAddons/ScratchAddons#1010]
**Describe the bug**
You can click "leave studio" and leave a studio as many times as you want before refreshing the page.

**To Reproduce**
1. Join a studio.
2. Click "leave studio."
3. Click "OK."
4. Repeat 1-3.

**Expected behavior**
Clicking "leave studio" should refresh the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/74682558/101953604-7731cc80-3baf-11eb-822e-70096f507d7f.png)

**Device (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 87.0.4280.88

**Comment by oof-le-oof** [comment]
ALthough... maybe don't fix it. It's fun

**Comment by Explosion-Scratch** [comment]
Cool! (I feel like that's not the intended reaction)

**Comment by oof-le-oof** [comment]
Can somebody change the label to be a feature

**Comment by Touchcreator** [comment]
I'll do it

**Comment by Touchcreator** [comment]
Ok my code isn't doing it lol
