### ISSUE TITLE
Add "Add a dropdown" to the custom block creator

### ISSUE THREAD

**Issue by Marc92020** [ScratchAddons/ScratchAddons#1012]
**Describe the new addon**
It would be cool if people could just a press "add a dropdown" button in the custom block creator instead of having to modify the JSON file so that is why I made this suggestion.

**Link to the new addon**
There is no link

**Comment by PhoenixAndStuf** [comment]
I *think* that custom hacked blocks or scratchaddons exclusive blocks are rejected/not going to be added, not sure though

**Comment by Marc92020** [comment]
OK. If it is, I will close this issue

**Comment by apple502j** [comment]
This is technically impossible.
