### ISSUE TITLE
Advanced Color Picker

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#1014]
**Hexadecimal Colors are Easier to Remember and Transport**

I wished we could edit the colour picker to add hex codes and transparency. Currently, we have to import semi-transparent images to use them with the rest of our scene. This saves space on the sprites list and code. Hex codes are also a lot easier to transport around the web and have their own way of showing semi-transparency.

Thanks, 
The Shroud Ninja

**Comment by Explosion-Scratch** [comment]
Related: #311, #400

**Comment by WorldLanguages** [comment]
Duplicate of #311
