### ISSUE TITLE
Website Dark Mode: Change or Remove Studio Frame

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#1015]
**The Studios Section on a User's Profile Has a Border that Doesn't Change After Switching to Dark Mode**

This issue makes the user's profile look a bit ugly especially when you see different colours that don't fit in place. I also realised that the transparent blue on the focused comment or reply chain has a weird double-layer transparency instead of having a uniform colour

**Comment by apple502j** [comment]
Screenshots?

**Comment by samuraininja360** [comment]
I will get them soon

**Comment by samuraininja360** [comment]
Here:
![Scratch Studio Frame Issue GitHub](https://user-images.githubusercontent.com/69609060/102004004-6c269a00-3d71-11eb-80dd-05e7bf0a908a.PNG)
