### ISSUE TITLE
mouse-pos affects the [] of [] block

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1022]
![image](https://user-images.githubusercontent.com/17484114/101994969-27353180-3ca5-11eb-91ae-0487fcfc35d5.png)

**Comment by jeffalo** [comment]
looks like theres other stuff like _costume too

**Comment by Explosion-Scratch** [comment]
Heh. That's sorta cool. Do those report mousex and mousy?

**Comment by WorldLanguages** [comment]
> looks like theres other stuff like _costume too

Yeah, no idea why that happens. Might be some other addon

**Comment by Explosion-Scratch** [comment]
> > looks like theres other stuff like _costume too
> 
> Yeah, no idea why that happens. Might be some other addon

Maybe. Try going through them and turning stuff off and on.

**Comment by apple502j** [comment]
This is not caused by ScratchAddons.
