### ISSUE TITLE
Copy contents from #940 for 1.5.0 changelog

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#1024]
This is personal opinion, but instead of having a vague summary for the 1.5.0 changelog, can we have the contents of #940 instead, just like 1.1.0 have one?

**Comment by Hans5958** [comment]
Also, #1024!

**Comment by areeq0325** [comment]
#1024 🎉

**Comment by Hans5958** [comment]
@WorldLanguages ass

**Comment by Hans5958** [comment]
Counting as resolved as I have did this on https://github.com/ScratchAddons/ScratchAddons/blob/changelog-detailed/CHANGELOG.md.
