### ISSUE TITLE
Insufficient information on the redirected localization wiki page

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#1025]
Continuation of #840

There seems to be insufficient information on the wiki page that is pointed by the redirect page on website. On the said wiki page (https://github.com/ScratchAddons/ScratchAddons/wiki/How-to-join-the-localization-team), users are only faced with an instruction of how to joining, without any other information (what is it, what's the purpose, where is it, how does it work, etc). Users should have these on their first impression, otherwise they will be confused and become discouraged.

I suggest to add the details on another page, and pointing it to that instead. Another alternative is to just point it on the general index page of the localization page, containing self-explanatory links for users to read.

I think the page would be something like this: https://github.com/LLK/scratch-l10n/wiki/Guide-for-Scratch-Translators

----

EDIT: @apple502j - Technically this is an enhancement to the docs.

**Comment by WorldLanguages** [comment]
Yeah, it was worse before I edited it ;)

**Comment by WorldLanguages** [comment]
Made it a little better so that users that get the release notification today (v1.5.0 chrome release) can better understand what Scratch Addons is, and how they can actually help by translating. Still could be enhanced but it's way better than previously.

**Comment by TheColaber** [comment]
Seems like this is resolved
