### ISSUE TITLE
Forum Color Dropdown (Forums)

### ISSUE THREAD

**Issue by PhoenixAndStuf** [ScratchAddons/ScratchAddons#1050]
**Describe the new addon.**

It would function as a tool to help users bring color to their forum posts more easily, similar to vanilla scratch's **bold tool**. Concept design for it is here:

![textpainttool (1)](https://user-images.githubusercontent.com/75099144/102306508-49ce8100-3f17-11eb-9c77-b7beb39051c3.png)

SVG for the icon can also be downloaded here:

[colorforumsicon (1).zip](https://github.com/ScratchAddons/ScratchAddons/files/5700399/colorforumsicon.1.zip)

**Why would this be helpful?**

Quality of life change! A lot of people don't know how to get color in their posts, or do know but don't have the time to look up how cause they forgot. :P

**Comment by Touchcreator** [comment]
This is really useful! I think I can get to coding this.

**Comment by GrahamSH-LLK** [comment]
> This is really useful! I think I can get to coding this.

I doubt it! 😛 Interacting with the toolbar isn't super easy.

**Comment by Explosion-Scratch** [comment]
Also SVG icons would be great, those look really outdated.

**Comment by PhoenixAndStuf** [comment]
> Also SVG icons would be great, those look really outdated.

Lucky for you, I have an svg of the icon right here.

[colortexticon.zip](https://github.com/ScratchAddons/ScratchAddons/files/5720224/colortexticon.zip)

**Comment by GrahamSH-LLK** [comment]
They meant all of the icons. I'm gonna make an addon to do that later.

**Comment by PhoenixAndStuf** [comment]
> They meant all of the icons. I'm gonna make an addon to do that later.

Well, I guess you still have it in case anyone decides to code this. Just a question, does anyone have svg's for the icons at all? If not I could make some.

**Comment by Marc92020** [comment]
I know this is off topic but what is vanilla scratch?

**Comment by Marc92020** [comment]
This sounds cool!

**Comment by YOYITsM3M8** [comment]
> I know this is off topic but what is vanilla scratch?

its the scratch forums

**Comment by RedGuy12** [comment]
added
