### ISSUE TITLE
Move thumnail setter to editor features

### ISSUE THREAD

**Issue by MasimbaTheHuman** [ScratchAddons/ScratchAddons#1057]
**Is your feature request related to a problem? Please describe.**

The problem is that the Thumbnails Setter addon is in scratch website features, when it's an editor feature.

**Describe the solution you'd like**

Move the addon to editor features

**Describe alternatives you've considered**

**Additional context**

**Comment by GrahamSH-LLK** [comment]
This was supposedly resolved in #752.

**Comment by MasimbaTheHuman** [comment]
> This was supposedly resolved in #752. Are you on the latest version?

yes.

**Comment by YOYITsM3M8** [comment]
> > This was supposedly resolved in #752. Are you on the latest version?
> 
> 
> 
> yes.

Latest dev version?
