### ISSUE TITLE
Copy and Paste Blocks Between Projects

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#1058]
**I Like the Idea of Not Having to Drag My Scripts into My Backpack and Copy Scripts by Just Using Ctrl+C Ctrl+V**

The main problem is that its a waste of time and space when I drag and drop my scripts into my large backpack. I would prefer having a temporary backpack which works like a clipboard so I can copy and paste code, costumes and sounds.

**Comment by WorldLanguages** [comment]
Duplicate of #1004
