### ISSUE TITLE
Scroll Bar Appears in the wrong place (Firefox)

### ISSUE THREAD

**Issue by RedLight-Scratch** [ScratchAddons/ScratchAddons#1076]
**Describe the bug**

The scroll bar for the About me appears on top of what I've been doing when you have the profile page banner and website dark mode on. (It disappears completely when website dark mode is off)

**To Reproduce**

1. Go to a profile where you have to scroll down to see all the about me.
2. See error

**Expected behavior**

The scroll bar should appear where it does on chrome, and not on top of the about me

**Screenshots**

![Screenshot_2020-12-20 Scratch - Imagine, Program, Share](https://user-images.githubusercontent.com/76401850/102718797-f8b7e780-429e-11eb-8f1e-4ef5d9a117d3.png)

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 84

**Additional context**

It does not happen on chrome

**Comment by thecoder876** [comment]
Well, I tried it and I didn't have the issue (both with dark mode on and off).

![Screenshot 2020-12-20 172454](https://user-images.githubusercontent.com/76265544/102719840-50c70c00-42e8-11eb-9164-b0a81d4d8e19.png)
![Screenshot 2020-12-20 172443](https://user-images.githubusercontent.com/76265544/102719842-515fa280-42e8-11eb-9f40-04f4d779aa4a.png)

**Comment by CuriousG2** [comment]
You also have to have the profile page banner on

**Comment by thecoder876** [comment]
Oh, ok.

**Comment by thecoder876** [comment]
It actually completely hides the scroll bar for About me!

![Screenshot 2020-12-20 174321](https://user-images.githubusercontent.com/76265544/102720198-e368aa80-42ea-11eb-9e75-179c719cea15.png)

**Comment by CuriousG2** [comment]
That happens to me too when I have dark mode off. But, there is also what I'm working on which goes partly on top of the scroll bar.

**Comment by thecoder876** [comment]
OK.

**Comment by Touchcreator** [comment]
Yep, valid glitch

**Comment by CuriousG2** [comment]
I think this is some type of CSS problem?

**Comment by mxmou** [comment]
@CuriousG2 Yes.

**Comment by areeq0325** [comment]
`firefox` label?

**Comment by mxmou** [comment]
> ![Screenshot_2020-12-20 Scratch - Imagine, Program, Share](https://user-images.githubusercontent.com/76401850/102718797-f8b7e780-429e-11eb-8f1e-4ef5d9a117d3.png)

But this isn't how scrollbars look like on Firefox.

**Comment by mxmou** [comment]
This could be fixed by setting `width: 285px` on the About me container.

**Comment by mxmou** [comment]
This is happening again. https://scratch.mit.edu/users/Maximouse/#comments-196239395
