### ISSUE TITLE
Port Griffpatch's Messaging Extension

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#108]
Which means I'll need to add support for popups: #16 
This will also likely require additions to the `addon.account` API to avoid duplicated work.

**For everyone reading this: there's a chance griffpatch will agree to rename the Messaging Extension to Scratch Addons, and upload this extension in its place. This would mean immediate install to 3000+ users if this addon works as supposed! This is epic, so this is a pretty important issue. Please add a tada reaction to pressure me into doing this right lol**

**Comment by easrng** [comment]
Not on gh right now, so here:
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by GrahamSH-LLK** [comment]
@griffpatch What do you think?

**Comment by Hans5958** [comment]
Correct me if I'm wrong, but isn't that by doing so, SA will be released in version other than 1.0.0? If that's the case, then it is kinda weird, don't you think?

**Comment by WorldLanguages** [comment]
@Hans5958 I guess... But that's not really a problem, it's just weird...
Actually, the Scratch Messaging Extension is on version 0.25.0 now, so we could start on 1.0
Right now the manifest says 3.0 because updating [Better3.0](https://chrome.google.com/webstore/detail/better30/gjoimmimmkpppgkhobhceblafkienddi) is also a possibility, and its currebt version number is 2.0

**Comment by Explosion-Scratch** [comment]
What if. {wait for it}


we combined Better3.0, ScratchAddons, and griffpatch's stuff, we would have a GOD LIKE POWER OVER SCRATCH lol. But seriously, wouldn't this be great?!

**Comment by WorldLanguages** [comment]
@Explosion-Scratch That's exactly what we're doing :P
But obviously, we can't merge those items in extension stores.

**Comment by Explosion-Scratch** [comment]
So are we keeping this open to wait for confirmation that griffpatch will merge those?

**Comment by WorldLanguages** [comment]
Kinda - the messaging addon is not finished yet. It's very likely he'll "merge" (actually replace) the Messaging Extension with Scratch Addons, but we can't never be sure :P
