### ISSUE TITLE
my-ocular addon makes console spam

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#1080]
**Describe the bug**

When the my-ocular status addon is enabled, it logs the color of every status to the console. This isn't really a bug, but it's a bit annoying.

**To Reproduce**

1. Enable the "Show my-ocular status" addon
2. Open any forum topic
3. Open the console

**Expected behavior**

There are no unnecessary messages.

**Comment by WorldLanguages** [comment]
cc @jeffalo

**Comment by pufferfish101007** [comment]
This got fixed yesterday in commit 3459a5a.

**Comment by YOYITsM3M8** [comment]
![image](https://user-images.githubusercontent.com/49005044/102817785-61d25480-439e-11eb-8c02-f63887216d4c.jpeg) Jeffalo and jeffalo and jeffalo committed
