### ISSUE TITLE
Better Color Picker for blocks with color inputs

### ISSUE THREAD

**Issue by Marc92020** [ScratchAddons/ScratchAddons#1086]
**Describe the new addon**
I'm not sure if its a new addon or new feature. Also is possibly impossible :(
The color picker in 3.0 is bad. The 2.0 color picker would be able to pick colors from anywhere in the editor. So this addon or feature would make the 3.0 color picker more like the 2.0 color picker

**Link to the new addon**
no link

**Comment by apple502j** [comment]
This is actually possible. Is hard to make, though.

**Comment by PhoenixAndStuf** [comment]
Cool idea, but maybe you should make the title less long. :P

**Comment by TheColaber** [comment]
Has been done in the color picker addon. Just enable that addon and you can set the color with the color picker within the popup.
![image](https://user-images.githubusercontent.com/72760579/107701916-8bfe0f80-6c87-11eb-8e59-9f53395d37c0.png)
.
