### ISSUE TITLE
[New addon] Convert forum times into own's timezone

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#110]
**Describe the new addon**

Convert the forum times so it shows time into user's timezone, instead of the timezone that Scratch runs.

<sub>*PS. Off-topic, but anyone know this guy called mundofinkyenglish? Man, I miss him. :stuck_out_tongue_winking_eye:*</sub>

**Comment by WorldLanguages** [comment]
Lol I can't understand what that PS is supposed to reference :/

**Comment by Hans5958** [comment]
> 
> 
> Lol I can't understand what that PS is supposed to reference :/

It was supposed about you, but, eh, it's been a while.

**Comment by WorldLanguages** [comment]
Lol but I mean, how is my old account related to this addon? Or was it just a random comment?

**Comment by Hans5958** [comment]
It was supposed to be random, but moving on...

**Comment by WorldLanguages** [comment]
Also the US itself has many timezones :P
