### ISSUE TITLE
"When Stop Clicked Block" In Code Category in Scratch

### ISSUE THREAD

**Issue by SkittleToucan** [ScratchAddons/ScratchAddons#1100]
Would replace the ol' timer stop click code with this block. It would instead stop the project after the code under the new block instead of keeping the project going like the timer code does. This would help very much, as it is something many people have been requesting places on Scratch like in the Scratch Forums.
A new hat block that stops the project completely (the opposite of the When Flag Clicked Block!). Found in the Events category.

Scratch Account: https://scratch.mit.edu/users/GalaxysBrother/

**Comment by TheColaber** [comment]
I like the idea... however it first of all ~~almost impossible~~ very, very hard to create a block and put it in the editor, and secondly, other users that don't have scratch addons, will have a broken block. However, good idea!

**Comment by mxmou** [comment]
> other users that don't have scratch addons, will have a broken block

It could be replaced by a workaround when saving the project and with the added block when loading.

> ~almost impossible~ very, very hard to create a block and put it in the editor

It isn't that hard.

**Comment by pufferfish101007** [comment]
> > other users that don't have scratch addons, will have a broken block
> 
> It could be replaced by a workaround when saving the project and with the added block when loading.
> 
> > ~almost impossible~ very, very hard to create a block and put it in the editor
> 
> It isn't that hard.

It may not be that hard, but it's rejected - see #927

**Comment by mxmou** [comment]
> It may not be that hard, but it's rejected - see #927

That's for entirely new blocks that can't be made in vanilla Scratch.

**Comment by Explosion-Scratch** [comment]
> > It may not be that hard, but it's rejected - see #927
> 
> That's for entirely new blocks that can't be made in vanilla Scratch.

Yes, but we should think carefully about the possible consequences of implementing rejected blocks:
1: Not many people use that hack to workaround the stop sign
2; It's supposed to _stop_ the project
3: The switching of blocks on save might be confusing or weird
4: Would this make new "When stop clicked" blocks if it detects the right broadcasts?

**Comment by WorldLanguages** [comment]
I'd say this is rejected.

**Comment by TheColaber** [comment]
Wait a minute... #1100 🎉🎉🎉🎉🎉

**Comment by SkittleToucan** [comment]
> I'd say this is rejected.

Yeah probably. I'm trying to find good ideas for addons that won't be broken for everyone else that don't have Scratch Addons. I made a whole Google Docs on it. I'll try to come up with better ideas, or just stop completely. Thank you.

**Comment by WorldLanguages** [comment]
@SkittleToucan Yeah feel free to keep suggesting, as long as you're aware the main goal of Scratch Addons is to allow users to customize their own experience on the website. Adding new blocks typically also affects other users, unless we come up with some complex workaround, but at that point we'd be making our own project editor.
