### ISSUE TITLE
A "List Category" On Scratch.

### ISSUE THREAD

**Issue by SkittleToucan** [ScratchAddons/ScratchAddons#1101]
Just like all the other categories in the menu such as, "Events, Motion, Looks", and the rest. Why doesn't the Lists have their own category 🤔? Anyway, this would show all your lists, and the list blocks that come with it. 

Adds a List category in the code menu in between the "Variables" and "My Blocks"categories showing list blocks and list value blocks.

**Comment by TheColaber** [comment]
Hey! Nice to see you on GitHub! Actually... this was already thought up and is currently as a running PR: #1097 to resolve #751. Nice Idea tho!

**Comment by Explosion-Scratch** [comment]
Yup. It used to be a (glitchy) addon by GarboMuffin.

**Comment by TheColaber** [comment]
> Yup. It used to be a (glitchy) addon by GarboMuffin.

Wasn't it made by someone else before?

**Comment by mxmou** [comment]
@TheColaber It was by towerofnix.

**Comment by Marc92020** [comment]
I remember it and it would be cool if it was back!
