### ISSUE TITLE
Block switching addon: repeat/repeat until

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1107]
> Hey, I found something for the "change block to similar block" thing... I can't change repeat until to repeat()... is it suppoed to be like that?

**Comment by mxmou** [comment]
Repeat has a number input and repeat until a Boolean input, so this is probably intentional.

**Comment by GarboMuffin** [comment]
This was intentional because the values you pass into repeat and repeat until are very different.

**Comment by Platformer444** [comment]
What about repeat until<> and wait until<>?

**Comment by mxmou** [comment]
> What about repeat until<> and wait until<>?

What would happen to the blocks inside the repeat until loop?

**Comment by GarboMuffin** [comment]
repeat until <-> wait until is already supported. Blocks inside the repeat until are split off into a separate script in the same spot where they used to be
