### ISSUE TITLE
[New addon] Forum Enhancements

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#111]
**Describe the new addon**
use some of lefty's cool api stuff to add cool stats to forum people and if possible, even view deleted posts

**Comment by Hans5958** [comment]
Was thinking about this a while ago. I would like to use ScratchDB to replace the vague number of posts into the precise (and probably accurate) results, but the idea is not exhaustive. 

However, you need to consider the traffic that SA will generate. Just to make sure that SDB is strong enough to handle those request.

**Comment by WorldLanguages** [comment]
I don't run ScratchDB but can confirm traffic won't be an issue.
What should be clear for users is that this addon will send some basic information about them to ScratchDB. Of course that means it won't be enabled by default.

**Comment by WorldLanguages** [comment]
> even view deleted posts

Also, please no 😂

**Comment by WorldLanguages** [comment]
This could also enable forum search within scratch.

**Comment by GrahamSH-LLK** [comment]
YES!!!!!!!!!!

**Comment by JeffaloBob** [comment]
YES moment indeed

**Comment by JeffaloBob** [comment]
heres a mockup for something the forums enhancements could provide

![image](https://user-images.githubusercontent.com/40470736/91644292-d45ba500-ea3a-11ea-9aea-adffaa4d4e0c.png)


some other ideas i'm thinkng about, a list of rejected suggestions searcher and a thing to inform you of if a thread was closed while you were typing/new messages since you loaded the page.

**Comment by WorldLanguages** [comment]
> a thing to inform you of if a thread was closed while you were typing/new messages since you loaded the page.

Did that ever happen to you?? lol

**Comment by JeffaloBob** [comment]
> > a thing to inform you of if a thread was closed while you were typing/new messages since you loaded the page.
> 
> Did that ever happen to you?? lol

happens if it's a spam/silly post

**Comment by Explosion-Scratch** [comment]
@WorldLanguages quite frequently actually. Also could this also incorporate the exact post count of the user into the side part by the pfp?

**Comment by JeffaloBob** [comment]
wait i was thinking this should better be done as individual addons
(eg #124)

because otherwise people would want to toggle each individually and we'd end up with an addon manager inside of an addon inside of an addon installed through an addon manager in a browser installed through a package manager inside of you get the point these should be individual addons

**Comment by Explosion-Scratch** [comment]
Yeah… I get the point lol Also who use addon managers? That's littraly wat the browser is for.

**Comment by JeffaloBob** [comment]
> Yeah… I get the point lol Also who use addon managers? That's littraly wat the browser is for.

yeah i mean the addon manager built into your browser.

**Comment by GrahamSH-LLK** [comment]
These have been seperated. We now have some of these.
