### ISSUE TITLE
Scratch Addons won't update!

### ISSUE THREAD

**Issue by Marc92020** [ScratchAddons/ScratchAddons#1111]
**Describe the bug**
So scratch addons updated today but I am still stuck on 1.5.1!

**To Reproduce**
1. Open the extension popup
2. Version is still on 1.5.1

**Expected behavior**
It should say 1.6.1

**Screenshots**
![Screenshot 2020-12-27 at 2 42 07 PM](https://user-images.githubusercontent.com/75702334/103178552-bd468b80-4851-11eb-8c1d-49b1592a4bcc.png)

**Device (please complete the following information):**

- OS: [Chrome OS]
- Browser [Chrome]
- Version [I'm not sure but I think it is Chrome 87]

**Additional context**
I want 1.6.1

**Comment by Marc92020** [comment]
Someone help

**Comment by Marc92020** [comment]
someone help

**Comment by Marc92020** [comment]
someone help

**Comment by Marc92020** [comment]
soomeone help

**Comment by Marc92020** [comment]
PLZ HELP!!!!!! :(

**Comment by TheColaber** [comment]
The Extension first must be approved by the chrome web store first, then it will update.

**Comment by Explosion-Scratch** [comment]
#1111 !!
