### ISSUE TITLE
Sora font Unicode support

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1116]
Turkish translator reported it should be "İ", not "I":
![image](https://user-images.githubusercontent.com/17484114/103241646-a4fa6d80-4932-11eb-9a77-941916e3e158.png)

**Comment by GrahamSH-LLK** [comment]
Sora won't work, it's latin only. We need a better fallback font.

**Comment by WorldLanguages** [comment]
But we've supported Japanese for a while tho...
