### ISSUE TITLE
[Bug] Denied load of library

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#112]
**Describe the bug**

my addon doesn't work and i get an error about a library it uses being denied

**To Reproduce**

1. go to the option
2. enable image uploader
3. go to forum post
4. you don't see the new button and theres an error in the console

**Expected behavior**

not

**Screenshots**

![image](https://user-images.githubusercontent.com/40470736/91330928-64df7e80-e7ca-11ea-96ca-b8361284ed5d.png)

**Device (please complete the following information):**

- OS: window
- Browser chrome
- Version 84.0.4147.135 

**Additional context**

this didn't happen last time i tried so some commit recently has done this maybe this is my fault in the way in the location of the library?

**Comment by JeffaloBob** [comment]
changing the thing in the manifest it tells me to change to add libraries fixes this
`  "web_accessible_resources": ["content-scripts/inject/*", "addon-api/*", "addons/*", "libraries/*"]`

**Comment by WorldLanguages** [comment]
You fixed this in your PR
