### ISSUE TITLE
Change Sora font to Roboto

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#1123]
### **I don't like the Sora font.**

I just don't like how it looks. Period.

My solution is **NOT** to replace it. Intsead, add an option in _More Settings_ to change the font.

This would be also good for accesibility, as Roboto is much easier to read.

**Comment by WorldLanguages** [comment]
Well, fortunately Scratch Addons is open source so it shouldn't take you long to replace the font yourself, even if we decide not to implement a setting for this.

**Comment by RedGuy12** [comment]
This would also fix #1116 right?

**Comment by Secret-chest** [comment]
Yes, we cloud change the font to one that supports Unicode. But I want to change it because Sora is somewhat unreadable, especially in Romanian, where we use ă, â, î, ș and ț.

**Comment by WorldLanguages** [comment]
@Secret-chest Can you elaborate on how those characters become unreadable?

**Comment by GrahamSH-LLK** [comment]
> Yes, we cloud change the font to one that supports Unicode. But I want to change it because Sora is somewhat unreadable, especially in Romanian, where we use ă, â, î, ș and ț.

This should be resolved by #1159

**Comment by samuraininja360** [comment]
Well Montserrat or Product Sans should be much more readable and pleasing to the eye.

**Comment by mxmou** [comment]
@samuraininja360 We can't use Product Sans because it isn't open source.

**Comment by Secret-chest** [comment]
> Well Montserrat or Product Sans should be much more readable and pleasing to the eye.

Nope. This is not what I want. We need a standard font, not one that looks very cool, so everybody is happy. I can't edit the extension because I want to get updates

**Comment by Secret-chest** [comment]
> @Secret-chest Can you elaborate on how those characters become unreadable?

They become unreadable at small sizes.

**Comment by WorldLanguages** [comment]
> I can't edit the extension because I want to get updates

Making a little script that periodically runs `git pull` and replaces the font shouldn't be that complex.

> They become unreadable at small sizes.

Can you please post screenshots as examples? Also, it's not clear enough if we're still talking about these non-English characters.

**Comment by easrng** [comment]
> Product Sans

As @jeffalo said, it is a private font, but I think what you mean is Google Sans. Product Sans is for logos only.

**Comment by Secret-chest** [comment]
![example](https://user-images.githubusercontent.com/74449186/103639194-accf9880-4f56-11eb-8f22-6f36588a3169.PNG)
This.

**Comment by samuraininja360** [comment]
Yes especially at small sizes like the Filtreaza

**Comment by GrahamSH-LLK** [comment]
> ![example](https://user-images.githubusercontent.com/74449186/103639194-accf9880-4f56-11eb-8f22-6f36588a3169.PNG)
> This.
> The font is somewhat unreadable (for me) because of the lines and it simply looks ugly.

Which lines?

**Comment by Secret-chest** [comment]
> > ![example](https://user-images.githubusercontent.com/74449186/103639194-accf9880-4f56-11eb-8f22-6f36588a3169.PNG)
> > This.
> > The font is somewhat unreadable (for me) because of the lines and it simply looks ugly.
> 
> Which lines?

1. "Credit pentru: Richie Bendall, apple502j"
2. "Mesageria Scratch"
3. "Filtrează Toate Recomandat Beta"

**Comment by GrahamSH-LLK** [comment]
I think it would be a good decision to add a second usable font. Sora is apparently hard to read in some languages.

**Comment by WorldLanguages** [comment]
> Yes, we cloud change the font to one that supports Unicode. But I want to change it because Sora is somewhat unreadable, especially in Romanian, where we use ă, â, î, ș and ț. (And 4, 7, l, a are ugly)

Was fixed
