### ISSUE TITLE
Export and Import Scratch Addons Settings

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#1132]
**Is your feature request related to a problem? Please describe.**

When using Scratch in a class it would be important that all students have the exact same settings.

**Describe the solution you'd like**

Allow the export of class settings so that each student in the class can import the settings and start on the same page

**Describe alternatives you've considered**

No alternatives

**Additional context**

No additional context

**Comment by GrahamSH-LLK** [comment]
Interesting! I've been thinking about this, and it should be a simple export of a json file, but I wonder if there could be a better way.

**Comment by TheColaber** [comment]
It could simply under _More Settings_ that allows users to copy and paste their current settings, and also load it if they wish.

**Comment by Touchcreator** [comment]
This is a good idea. But Like colaber said, put it on more settings

**Comment by GrahamSH-LLK** [comment]
Duh, it would be in more settings! Where else?
I had an idea! People could copy the setting JSON, and put it in the notes and credits of a project. 
```
// Begin Settings
{}
```
When SA sees that, it adds a button to import it under the notes and credits.

**Comment by TheColaber** [comment]
> Duh, it would be in more settings! Where else?
> I had an idea! People could copy the setting JSON, and put it in the notes and credits of a project.
> 
> ```
> // Begin Settings
> {}
> ```
> 
> When SA sees that, it adds a button to import it under the notes and credits.

But we must be alert of Scratch's Policy.

**Comment by wgyt** [comment]
>  I had an idea! People could copy the setting JSON, and put it in the notes and credits of a project.

I wouldn't do it on a projects notes and credits :|
I would just do json file.

**Comment by Touchcreator** [comment]
> 
> 
> Duh, it would be in more settings! Where else?
> I had an idea! People could copy the setting JSON, and put it in the notes and credits of a project.
> 
> ```
> // Begin Settings
> {}
> ```
> 
> When SA sees that, it adds a button to import it under the notes and credits.

This would be good if it didn't seem suspicious

**Comment by WorldLanguages** [comment]
@sfederici We'll be implementing a way to include all addon info in a single .json file (what addons are enabled, as well as their settings). All you need to do is make the students download this .json file, and upload it inside the "more settings" area of Scratch Addons settings. You'll be able to import your own settings from there to generate a .json file as well.
Expected release date for v1.7.0 is January 11th, 2021

**Comment by sfederici** [comment]
Excellent. Thanks
