### ISSUE TITLE
Better Messages

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#1151]
**Describe the new addon**

Better messages page. Will eventually include: 

- Merging messages from alternate accounts and from main
- Custom message format
- Disable certain message types
- Messages for custom actions (i.e. when someone shares a project)

**Link to the new addon**

Available soon. I almost have the first feature implemented, then I'll add the rest.

**Comment by Secret-chest** [comment]
Support.

**Comment by WorldLanguages** [comment]
> Support.

@Secret-chest Keep in mind we rarely add "new addon" suggestions to any milestones, so replying with "support" does not help much. It's better to use the thumbs up reaction so that a volunteer that's reading the issues will be able to count how many people are interested.

**Comment by RedGuy12** [comment]
Merging messages from alternate accounts and from main - can't clear them 
Custom message format - 
![image](https://user-images.githubusercontent.com/61329810/116718415-8d45fb00-a99f-11eb-9e95-f6ae2e0a56a4.png)

Disable certain message types - #1704
Messages for custom actions (i.e. when someone shares a project) - to complicated, too many api calls needed
