### ISSUE TITLE
You can't switch between project note tabs (Firefox)

### ISSUE THREAD

**Issue by CuriousG2** [ScratchAddons/ScratchAddons#1161]
**Describe the bug**

When you go to a project on Firefox, with project note tabs on, it won't let you switch between the instructions and notes and credits.

**To Reproduce**

1. Go to a project with text in the instructions and in the notes and credits
2. Click on the notes and credits tab
3. See error.

**Expected behavior**

You should be able to switch between project note tabs

**Screenshots**

![image](https://user-images.githubusercontent.com/76401850/103462225-987e6800-4cd8-11eb-9b08-b8a78b3480ed.png)

**Device (please complete the following information):**

— OS: [Windows 10]
— Browser [Firefox]
— Version [84.0.1]

**Additional context**

It is really annoying

You also can't switch to the notes and credits when you are on your own project, so you can't add text in them

**Comment by mxmou** [comment]
This will be fixed in version 1.7.

**Comment by TheColaber** [comment]
> This will be fixed in version 1.7.

Was there a PR for this?

**Comment by mxmou** [comment]
@TheColaber #1117

**Comment by TheColaber** [comment]
Ah yeah
