### ISSUE TITLE
Hex input dark mode

### ISSUE THREAD

**Issue by areeq0325** [ScratchAddons/ScratchAddons#1163]
**Describe the bug**

Hex input is unreadable

**To Reproduce**

Turn on dark mode and hex input

**Expected behavior**

It would be readable

**Screenshots**

![image](https://user-images.githubusercontent.com/69761212/103463521-eefc9e00-4cfa-11eb-8710-cf0690f85dcf.png)

**Device (please complete the following information):**

Windows, Cr-Edge 87

**Comment by apple502j** [comment]
Duplicate of #1126
