### ISSUE TITLE
Consolidate addons

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#1168]
Some small addons could do better conbined. And, that would speed up the page load as well, since fewer files have to be loaded.
### better-quoter + forum-quote-code-beatifier = forum-quotes
They are both for quotes. It makes sense to have them together.
### clones + mouse-pos + project-info = project-info
The mouse position and amount of clones are both technical information about the project and so is the information in project-info, so it makes sense to combine them all.
### confirm-actions + remove-sprite-confirm = confirm-actions
Removing a sprite is an action...remove-sprite-confirm confirms said action...confirm-actions confirms many other actions...why weren't they together in the first place? (ok, I can answer that - one is for social actions and the other isn't. but still)
### dark-www + editor-dark-mode = dark-mode
They're both dark mode... Yeah, they're for different pages but still...
### editor-colored-context-menus + editor-theme3 = editor-colors
Both help create a more colorful editor. One makes the context menus colorful and the other the blocks.
### editor-messages + msg-count-badge = message-count
They both display the message count...idk what else to say
### forum-search + search-profile = more-search
Put them both on the search page. It doesn't make sense to add a new search bar for the forums when a search bar already exists! Just add a new tab for forums!
### full-signature + infinite-scroll + search-load-more-fix = scrolling
They all have to do with scrolling.
### more-links + true-youtube-links + youtube-fullscreen = more-links
They both deal with links. And quite frankly, youtube-fullscreen is unnecessary with true-youtube-links.

**Comment by WorldLanguages** [comment]
I dislike the idea of "merging" addons, since we'd need to migrate all old users of either addon to the new mega-addon

**Comment by mxmou** [comment]
Even if it looks like some addons could be merged, they're usually used for very different purposes.

**Comment by Secret-chest** [comment]
I dislike the idea, we need to choose what addons we want, not be forced to enable clones counter if we just want mouse pos and sprite/script count.

**Comment by RedGuy12** [comment]
> I dislike the idea, we need to choose what addons we want, not be forced to enable clones counter if we just want mouse pos and sprite/script count.

Well there would be a checkbox on the settings to turn it on or off


Paul Reid

________________________________

**Comment by RedGuy12** [comment]
> Even if it looks like some addons could be merged, they're usually used for very different purposes.

Could you look at each of my suggestions individually? Some are really similar. Could you explain how they are different?

**Comment by mxmou** [comment]
> ### better-quoter + forum-quote-code-beatifier = forum-quotes
> They are both for quotes. It makes sense to have them together.

One is for making quotes, the other for displaying them. I don't think they are used by the same group of people.

> ### clones + mouse-pos + project-info = project-info
> The mouse position and amount of clones are both technical information about the project and so is the information in project-info, so it makes sense to combine them all.

The clone count and mouse position are the current state of the project and can change while the project it's running. Merging them might make sense, but they should be separate from `project-info`.

> ### confirm-actions + remove-sprite-confirm = confirm-actions
> Removing a sprite is an action...remove-sprite-confirm confirms said action...confirm-actions confirms many other actions...why weren't they together in the first place? (ok, I can answer that - one is for social actions and the other isn't. but still)

I'm not sure about this one but generally website and editor addons are separate.

> ### dark-www + editor-dark-mode = dark-mode
> They're both dark mode... Yeah, they're for different pages but still...

Same as above.

> ### editor-colored-context-menus + editor-theme3 = editor-colors
> Both help create a more colorful editor. One makes the context menus colorful and the other the blocks.

Colored context menus are purely decorative, but the block colors addon can actually be used, for example, to make it easier to distinguish between blocks.

> ### editor-messages + msg-count-badge = message-count
> They both display the message count...idk what else to say

Yes, but having the message count in the editor is useless if you have it on the extension icon.

> ### forum-search + search-profile = more-search
> Put them both on the search page. It doesn't make sense to add a new search bar for the forums when a search bar already exists! Just add a new tab for forums!

I like having direct access to forum search while on the forums though. Maybe `search-profile` could be expanded to add other tabs, while still keeping forum search the same?

> ### full-signature + infinite-scroll + search-load-more-fix = scrolling
> They all have to do with scrolling.

They do completely different things with scrolling.

> ### more-links + true-youtube-links + youtube-fullscreen = more-links
> They both deal with links. And quite frankly, youtube-fullscreen is unnecessary with true-youtube-links.

It *might* make sense to merge more links and true YouTube links, but full screen is unrelated.
