### ISSUE TITLE
Import Fonts into The Vector Editor

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#1170]
**Extended SVE Fonts**

Scratch has a limitted amount of fonts for the vector editor. It is time that developers would be able to import their own ttf's so they don't have to upload an svg document with each character. This reduces the time to make text engines that don't use peset fonts and costumes that don't use prest fonts.

I hope we could upload our ttf or otf by clicking an upload font button in the fonts dropdown.

**Comment by CuriousG2** [comment]
This would be a _very_ useful feature!

**Comment by RedGuy12** [comment]
Is it technically possible tho?

Paul Reid

________________________________

**Comment by Secret-chest** [comment]
Support.

**Comment by apple502j** [comment]
This is not possible.
