### ISSUE TITLE
Personal folders in "My Stuff"

### ISSUE THREAD

**Issue by LES-11** [ScratchAddons/ScratchAddons#1184]
**Describe the new addon**

The option to add personal folders in "My Stuff" to help  organize you projects. (The folders "All", "Shared", "Unshared", and "Trash" would stay.)
Example of possible folder titles:

- Designs
- Games
- Drafts
- Animations

etc.

You could add as many as you need and be able to change the title of the folder.

**Link to the new addon**

**Comment by D1WK** [comment]
Cool

**Comment by RedGuy12** [comment]
See also #1179
________________________________

**Comment by Cool-Scratcher** [comment]
+1, great idea. I assume that adding projects to folders can be an option that is alongside the "Add to studio" button, like a "Add to  folder" button.

**Comment by LES-11** [comment]
> +1, great idea. I assume that adding projects to folders can be an option that is alongside the "Add to studio" button, like a "Add to folder" button.

Yes, there would be an "Add to folder" button next to the "Add to studio" button

**Comment by Scratchfangs** [comment]
POG idea! +1

**Comment by thecoder876** [comment]
Good idea!

**Comment by RandomGamePlayer** [comment]
This would make organizing things in the my stuff section much more easier

**Comment by retronbv** [comment]
How would SA remember the names of the folders / remember what are in them?

**Comment by LES-11** [comment]
> How would SA remember the names of the folders / remember what are in them?

How does SA remember what you call the Discuss button? The same way?
![Capture](https://user-images.githubusercontent.com/75516401/111527076-b88cc780-871c-11eb-8c8e-9e2666d2ae56.PNG)
(tbh im not very experienced in programing/coding so idk)

**Comment by mxmou** [comment]
> How does SA remember what you call the Discuss button? The same way?
> ![Capture](https://user-images.githubusercontent.com/75516401/111527076-b88cc780-871c-11eb-8c8e-9e2666d2ae56.PNG)
> (tbh im not very experienced in programing/coding so idk)

Settings like the name of the discuss button are stored in the browser's storage. If folders are stored the same way (which is likely), they won't be available on other devices unless you're signed in to the browser.

**Comment by WorldLanguages** [comment]
Not really possible
