### ISSUE TITLE
better quoter addon doesn't auto scroll

### ISSUE THREAD

**Issue by jeffalo** [ScratchAddons/ScratchAddons#1185]
**Describe the bug**

it should autoscroll to the input, but it doesn't

**To Reproduce**

select some text, press quote 

**Expected behavior**
scrolls to the input like normal quoting

**Comment by mxmou** [comment]
Shouldn't it use `location += "#reply"` instead of `scrollIntoView()` for constistency with the normal quote button? The fix caused part of the textarea to be below the navigation bar.
