### ISSUE TITLE
default link colour is not normal

### ISSUE THREAD

**Issue by jeffalo** [ScratchAddons/ScratchAddons#1186]
with the scratch 2.0 -> 3.0 addon using default settings, in the message page, username links are light blue instead of grey
![image](https://user-images.githubusercontent.com/40470736/103515089-538c3a00-4e6e-11eb-8d40-642b877bc3cc.png)

before enabling addon:
![image](https://user-images.githubusercontent.com/40470736/103515101-5c7d0b80-4e6e-11eb-899d-4a7c57355c0f.png)

after
![image](https://user-images.githubusercontent.com/40470736/103515010-1f187e00-4e6e-11eb-96c1-0b04c32d299b.png)

**Comment by jeffalo** [comment]
cc @mxmou?

**Comment by mxmou** [comment]
I think this also happened in the original userstyle but I didn't consider it important enough to fix it. Now I probably will because it's very easy.
