### ISSUE TITLE
A question and a feature...

### ISSUE THREAD

**Issue by BoomerScratch** [ScratchAddons/ScratchAddons#119]
I'm currently creating an addon which changes the time zones to the current time zone (#110), and I have a question and a feature request:
- Question: I'm fetching scratchdb.lefty.one with addon.fetch, but the wiki page says [you should only use it for scratch.mit.edu and api.scratch.mit.edu](https://github.com/ScratchAddons/ScratchAddons/wiki/addon.*-APIs-reference#:~:text=addon.fetch%20must%20only%20be%20used%20for%20requests%20to%20api.scratch.mit.edu%20and%20scratch.mit.edu;%20don't%20try%20to%20use%20it%20with%20any%20other%20origins%20or%20subdomains.). Can I also use it for scratchdb.lefty.one? Can it be added to SA's extension manifest?
- Feature: Can `addon.auth.scratchLang` be added? It returns the language the user has chosen. You can get the language from the `scratchlanguage` cookie.

**Comment by WorldLanguages** [comment]
> Question: I'm fetching scratchdb.lefty.one with addon.fetch, but the wiki page says you should only use it for scratch.mit.edu and api.scratch.mit.edu. Can I also use it for scratchdb.lefty.one? Can it be added to SA's extension manifest?

No. ScratchDB is supposed to accept CORS requests from any origin; no need to add them to the manifest.

> Feature: Can addon.auth.scratchLang be added? It returns the language the user has chosen. You can get the language from the scratchlanguage cookie.

Sounds good.
Speaking of addon.auth, I just noticed the onchange event on it is broken because I didn't notice you removed the event that checked when scratchsessionid changed lol. Don't worry I'll fix it in an upcoming PR. Just telling you about it. This event only gets notified about changes to the cookie, not its values, so it's fine.

**Comment by WorldLanguages** [comment]
Hmm, @BoomerScratch, why edit the wiki on `addon.fetch`? I mean, technically `addon.fetch` will work if `window.fetch` works, but in those cases, there's no reason to use `addon.fetch`...

**Comment by BoomerScratch** [comment]
@WorldLanguages You can revert it if you want.

**Comment by WorldLanguages** [comment]
Ok.

**Comment by BoomerScratch** [comment]
@WorldLanguages Are you still gonna fix the thing in https://github.com/ScratchAddons/ScratchAddons/issues/119#issuecomment-683300155 and are you also gonna add `addon.auth.scratchLang`? The new addon I'm adding needs to use `addon.auth.scratchLang`, and I don't want any Git or PR conflicts.

**Comment by WorldLanguages** [comment]
Sure. Give me 5 minutes

**Comment by WorldLanguages** [comment]
Hmm actually I forgot about something. It will return `null` when logged out. That's the problem about adding it in auth (but there's really no other place, tbh). Do you want me to fix this first, or after your PR?

**Comment by BoomerScratch** [comment]
@WorldLanguages After [the PR](../pull/121).
