### ISSUE TITLE
Um... the home page projects sections have some issues.

### ISSUE THREAD

**Issue by sargent-coding** [ScratchAddons/ScratchAddons#1201]
![image](https://user-images.githubusercontent.com/65425469/103572436-8ba97200-4e9a-11eb-8136-5c946fb3e430.png)

**Comment by TheColaber** [comment]
I'm guessing an ad blocker?

**Comment by mxmou** [comment]
Are you sure this was caused by Scratch Addons?

**Comment by sargent-coding** [comment]
> I'm guessing an ad blocker?

Oh, that was the problem. Huh.

**Comment by areeq0325** [comment]
Close this issue?
