### ISSUE TITLE
Username filter in Messaging popup

### ISSUE THREAD

**Issue by oof-le-oof** [ScratchAddons/ScratchAddons#1208]
Would it be possible to add a username filter to the messages popup?
Theoretically this would work to allow the user to select a username, and only view messages from that user.

Edit: 69th star. Nice.

_Originally posted by @oof-le-oof in https://github.com/ScratchAddons/ScratchAddons/discussions/987_

**Comment by Cool-Scratcher** [comment]
Wow, this is a great idea... I can see many possibilities. +1.

**Comment by RedGuy12** [comment]
Can't be too hard
________________________________

**Comment by WorldLanguages** [comment]
Duplicate of #1038
