### ISSUE TITLE
_meow_ unaffected by better emojis or dark mode

### ISSUE THREAD

**Issue by areeq0325** [ScratchAddons/ScratchAddons#1210]
**Describe the bug**
The \_meow\_ emoji renders with a white background and as a .png, regardless of which addons enabled.
Same for \_gobo\_ and \_waffle\_.
Non-cat emojis have no background, but still are .png.

**To Reproduce**
Comment \_meow\_
See the emoji

**Expected behavior**
Vector design and no background

**Screenshots**
![image](https://user-images.githubusercontent.com/69761212/103651782-15574f00-4f30-11eb-8ac6-4291ae2f3d0d.png)

**Device (please complete the following information):**
Windows 10, Cr-Edge 87

**Comment by TheColaber** [comment]
Scratch Emojis are PNGs, not SVGs. We already have an addon for svg emojis. I don't know if there is anything we can do to remove the background

**Comment by mxmou** [comment]
> Scratch Emojis are PNGs, not SVGs. We already have an addon for svg emojis. I don't know if there is anything we can do to remove the background

I could make versions without the background and change dark mode to replace them with those versions.

**Comment by areeq0325** [comment]
> Scratch Emojis are PNGs, not SVGs. We already have an addon for svg emojis. I don't know if there is anything we can do to remove the background

Maybe update the addon in some way?

**Comment by Secret-chest** [comment]
I have the same problem.
