### ISSUE TITLE
"Collapse/expand all" button in settings page

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1211]
Moved from #1207, suggestion 2

It would be great to add this button where the search bar is currently placed. If clicked, it will collapse all addons (enabled addons are expanded by default). After being clicked once, it will now be a "expand all" button.

**Comment by RedGuy12** [comment]
See #1200

**Comment by WorldLanguages** [comment]
@RedGuy12 Please only PR one issue at once

**Comment by RedGuy12** [comment]
Wdym
________________________________

**Comment by mxmou** [comment]
This would be difficult to do properly now, and probably unnecessary.

**Comment by WorldLanguages** [comment]
Yeah, many of these issues are outdaded by now.
