### ISSUE TITLE
[Bug] Clicking on a forum notification takes you to a 404 page.

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#122]
**Describe the bug**
When someone gets a notification for a forum that they're following clicking on it does not take the user to the forum in question. Instead it takes them to a 404 error.

**To Reproduce**

1: Follow a forum
2:Wait for new activity in it.
3: You will get a notification from the addon.
4: Click on it and you will be led to a 404 error page.

**Expected behavior**

Clicking on the notification takes you to the forum in question.
**Screenshots**

**Device (please complete the following information):**

- OS: Chrome OS
- Browser: Chrome
- Version: Sorry, I don't know.

**Comment by WorldLanguages** [comment]
Nice catch! I actually fixed this locally yesterday/today (don't remember) but haven't pushed yet.

**Comment by Explosion-Scratch** [comment]
@WorldLanguages. Okay! Thanks! :)
