### ISSUE TITLE
Disable Autosave Feature

### ISSUE THREAD

**Issue by Scratchfangs** [ScratchAddons/ScratchAddons#1221]
I think there should be a "disable autosave" feature in Scratch Editor Features. It can help when a project autosaves and you made a mistake and you can't retrieve it.

**Comment by RedGuy12** [comment]
File menu -> Undo
________________________________

**Comment by TheColaber** [comment]
This was actually though in the discord server. It's a very nice idea! We'll keep this issue opened. Someone is currently working on this!

**Comment by Scratchfangs** [comment]
Ok, thanks for the support!

**Comment by Scratchfangs** [comment]
Also, can you give me a link to the server?

**Comment by TheColaber** [comment]
It's on the readme.md

**Comment by RedGuy12** [comment]
> Also, can you give me a link to the server?

I think its only got the devs
________________________________

**Comment by TheColaber** [comment]
That is correct. If you develop addons, you may help and join our discord.
