### ISSUE TITLE
"Addonify" popups

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1234]
Moved from #773

Right now, addon popups are pretty much part of the extension, instead of independent from it and simply addons.
Possible improvements are:

- [x] No need for popups to specify what strings they'll use, so that msg() calls work like in userscripts and persistent scripts
- [ ] No need for addons to set the HTML lang (could be set by the extension popup)
- [x] Shared CSS classes between settings page, extension popup and addon popups
- [ ] Way for addons to detect light mode or dark mode
- [ ] Way for popups to know if they're fullscreen through `addon.self`
- [ ] `addon.*` APIs available in popups, as well as `msg` and `safeMsg`
- [ ] Communicating to userscripts and persistent scripts
- [ ] `window.Vue` and Sora automatically available

**Comment by RedGuy12** [comment]
#1234 oooooo

**Comment by GrahamSH-LLK** [comment]
My future PR will handle 2.

**Comment by TheColaber** [comment]
> No need for addons to set the HTML lang (could be set by the extension popup)

Well, what if the addon popup was opened in a new tab? The extension popup can't do anything about that.

**Comment by WorldLanguages** [comment]
> Well, what if the addon popup was opened in a new tab? The extension popup can't do anything about that.

Good point

**Comment by WorldLanguages** [comment]
Before doing most of these @apple502j we need your help to make popups load all strings of an addon by default, instead of the popup manually having to specify what strings it needs (userscripts and persistent scripts don't have this limitation). Otherwise `msg()` wouldn't work normally.

**Comment by Hans5958** [comment]
updates?

**Comment by GrahamSH-LLK** [comment]
Not on my side. I've been putting it off, cause the next part of the CSS rewrite'll take a while.

**Comment by WorldLanguages** [comment]
> updates?

soon ™️

**Comment by retronbv** [comment]
🎉 #1234

**Comment by TheColaber** [comment]
I think this needs some discussion so let me bring up a few points. This has been moving up the milestones with not much prgress.

*  No need for addons to set the HTML lang (could be set by the extension popup)
   * Like I set before, this cannot always be the case if the addon popup was opened in a new tab.
*  `addon.*` APIs available in popups, as well as `msg` and `safeMsg`
   * This one is a bit tricky and will need the most discussion. Will it be available in the iframe's window? Will it be like addons `export default`? I think I should mention that we will need an `addon-api/popups` if that wasn't clear enough.
* Communicating to userscripts and persistent scripts
    * Shouldn't really discuss until we actually have the API I guess.
* `window.Vue` and Sora automatically available
   * Not sure about this... Would have to be added by the browser popup somehow, but as said before, this cannot always be the case if the addon popup was opened in a new tab.

**Comment by WorldLanguages** [comment]
> if the addon popup was opened in a new tab

We can simply make fullscreen popups become fullscreen iframes ¯\\_(ツ)_/¯

**Comment by TheColaber** [comment]
In that case:
Thats a browser popup... with an iframe with an iframe... this works ig...

**Comment by GrahamSH-LLK** [comment]
My pr (#1832) will allow for base styles across popups and Sora.
