### ISSUE TITLE
[New addon] Better quoter

### ISSUE THREAD

**Issue by jeffalo** [ScratchAddons/ScratchAddons#124]
**Describe the new addon**

Make quoting easier by adding a quote button when someone selects
![3piO1GSXVK](https://user-images.githubusercontent.com/40470736/91658666-724a8080-eaca-11ea-8a72-0d2c4aae6da0.gif)

**Link to the new addon**

https://github.com/JeffaloBob/ScratchAddons/tree/quote

but i messed up alot of my code and i think it would be better if someone smarter made something similar instead of merging this half functional piece of terrible code

**Comment by Explosion-Scratch** [comment]
Nice! THis would be a great addition!

**Comment by WorldLanguages** [comment]
> but i messed up alot of my code and i think it would be better if someone smarter made something similar instead of merging this half functional piece of terrible code

Why don't you do that instead lol?

**Comment by Thingyman-DEV** [comment]
This is really cool! 1 issue that I found is that it doesn't work when using it on text already in a quote box. It just shows the normal right click text.

**Comment by JeffaloBob** [comment]
> This is really cool! 1 issue that I found is that it doesn't work when using it on text already in a quote box. It just shows the normal right click text.

right now my prototype is kinda bad, there's one that does overrides the right click menu which is not ideal and another script (not enabled) that does it like on the GIF but all of them have weird quircks i can't figure out

**Comment by NoobTracker** [comment]
I know that feature from another forum. It's really neat. It could make quoting TOLORS easier (also that TOLORS script would be nice=-

**Comment by JeffaloBob** [comment]
maybe i'll try doing this again

**Comment by NoobTracker** [comment]
That would be cool (and, as far as I can tell, not tooooo hard, just create a JSON with all the quotes and then give them their numbers and then compare those numbers with the entered one and either tell the user that something went wrong or just add that quote)

**Comment by wgyt735yt** [comment]
> **Describe the new addon**
> 
> Make quoting easier by adding a quote button when someone selects
> ![3piO1GSXVK](https://user-images.githubusercontent.com/40470736/91658666-724a8080-eaca-11ea-8a72-0d2c4aae6da0.gif)
>

Nice Idea, I would love this feature because I have to edit quotes and stuff right now, but this would make my life easier
