### ISSUE TITLE
Remove Background of sprite option

### ISSUE THREAD

**Issue by SparkScratch-P** [ScratchAddons/ScratchAddons#1249]
This addon is expected to show up as a popup when the user includes a png or gif image importing in the project. When the 'clear background' button is pressed, it removed the white or black-n-white check background from the sprite.
 It should work like [this](https://onlinepngtools.com/create-transparent-png)

**Comment by TheColaber** [comment]
Can you not already use the fill tool to do this? Or is the idea to add an option to fill similar colors to achieve better results like in the example?
![image](https://user-images.githubusercontent.com/72760579/104080896-0b1ba600-51f9-11eb-8374-7cc8b231195a.png)

However even so it seems like the addon would have to go through each pixel of the custom which in turn may take a quite bit of time depending on the image size...

**Comment by maDU59** [comment]
> Can you not already use the fill tool to do this? Or is the idea to add an option to fill similar colors to achieve better results like in the example?
> ![image](https://user-images.githubusercontent.com/72760579/104080896-0b1ba600-51f9-11eb-8374-7cc8b231195a.png)
> 
> However even so it seems like the addon would have to go through each pixel of the custom which in turn may take a quite bit of time depending on the image size...

The original idea is good but this is better.

**Comment by TheColaber** [comment]
probably not suited for the context of scratch addon, but reopen if I'm wrong.
