### ISSUE TITLE
[Feature] Consider adding popup menu when the extension icon is clicked?

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#125]
Right now it's a little counterintuitive to have to click the 3 dots and click 'settings', so maybe there could be a button which leads the user to that page. Also, should clicking it show your messages?

**Comment by WorldLanguages** [comment]
Lol this is also locally, I'll push soon :P
![image](https://user-images.githubusercontent.com/17484114/91662756-d9f8cf80-eaba-11ea-8e5f-3bd85721df3a.png)
Note: popup styling is just to have something not that ugly to test with. This won't be the end result.

**Comment by Explosion-Scratch** [comment]
Okay! Also, 'pushing' means merging with this branch, right?

**Comment by Explosion-Scratch** [comment]
P.S. I'd decrease the saturation and increase the brightness on the dark orange.

**Comment by WorldLanguages** [comment]
> Okay! Also, 'pushing' means merging with this branch, right?

Yep, here on master.

**Comment by Explosion-Scratch** [comment]
Okay!
