### ISSUE TITLE
CSS Rewrite

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#1256]
I'm rewriting the CSS (no style changes, just structure) with CSS vars, imported "modules," and other changes. It's on https://github.com/ScratchAddons/ScratchAddons/tree/GrahamSH-LLK-css-redo

**Comment by Explosion-Scratch** [comment]
Cool!

**Comment by Explosion-Scratch** [comment]
Then could people customize the look completely?

**Comment by TheColaber** [comment]
No No, I think you've interpreted this wrong... this isn't an addon, it's a rewrite for our css

**Comment by Explosion-Scratch** [comment]
> No No, I think you've interpreted this wrong... this isn't an addon, it's a rewrite for our css

I understand that, but I'm saying that it would be very simple to write an addon that does this after this rewrite.

**Comment by RedGuy12** [comment]
No, the popup and settings page css
________________________________

**Comment by Hans5958** [comment]
> 
> 
> > No No, I think you've interpreted this wrong... this isn't an addon, it's a rewrite for our css
> 
> I understand that, but I'm saying that it would be very simple to write an addon that does this after this rewrite.

Do what? This issue calls for a refactor of the CSS code. Put simply, to tidy up the CSS code on this repo.

**Comment by Explosion-Scratch** [comment]
> > > No No, I think you've interpreted this wrong... this isn't an addon, it's a rewrite for our css
> > 
> > 
> > I understand that, but I'm saying that it would be very simple to write an addon that does this after this rewrite.
> 
> Do what? This issue calls for a refactor of the CSS code. Put simply, to tidy up the CSS code on this repo.

Yes, _but_, once the code is tidied it would be easy to make an addon that changes the theme of scratch addons to blue or something.

**Comment by Hans5958** [comment]
> > > > No No, I think you've interpreted this wrong... this isn't an addon, it's a rewrite for our css
> > > 
> > > 
> > > I understand that, but I'm saying that it would be very simple to write an addon that does this after this rewrite.
> > 
> > Do what? This issue calls for a refactor of the CSS code. Put simply, to tidy up the CSS code on this repo.
> 
> Yes, _but_, once the code is tidied it would be easy to make an addon that changes the theme of scratch addons to blue or something.

Well, then it should be discussed on a different issue, not here.

**Comment by GrahamSH-LLK** [comment]
> > > > No No, I think you've interpreted this wrong... this isn't an addon, it's a rewrite for our css
> > > 
> > > 
> > > I understand that, but I'm saying that it would be very simple to write an addon that does this after this rewrite.
> > 
> > 
> > Do what? This issue calls for a refactor of the CSS code. Put simply, to tidy up the CSS code on this repo.
> 
> Yes, _but_, once the code is tidied it would be easy to make an addon that changes the theme of scratch addons to blue or something.

That wouldn't be an addon, it might be a "setting". These changes _will_ make it easier to do that, though. I'm not sure _how_ easy, but still, easier. Anyway, make another issue if you want to explore this, and take a look at my current changes.

**Comment by GrahamSH-LLK** [comment]
There's going to be a part 2.

**Comment by Secret-chest** [comment]
This would also help with #1123

**Comment by GrahamSH-LLK** [comment]
> This would also help with #1123

Not really

**Comment by WorldLanguages** [comment]
@Secret-chest I'll try to tackle that with #1234 - I'll make it so popups don't need to manage fonts, or light/dark mode at all.
