### ISSUE TITLE
Dark mode and 2.0→3.0 don't run on https://scratch.mit.edu/research

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#1257]
**Describe the bug**

Related to #942

Scratch 2.0 → 3.0 and website dark mode don't run on https://scratch.mit.edu/research

**To Reproduce**

1. Enable website dark mode, or enable Scratch 2.0 → 3.0 and change the colors
2. Go to https://scratch.mit.edu/research
3. Notice that none of the themes apply

**Expected behavior**

It should be dark, or with customized colors.

**Comment by TheColaber** [comment]
Honestly, there are a couple more sites that they don't run on...

**Comment by RedGuy12** [comment]
I find they dont run on some 404 pages. Not all, however. Not uploads.scratch.mit.edu either, but that one's probably intentional.
________________________________

**Comment by mxmou** [comment]
uploads.scratch.mit.edu is intentional. I might be able to fix 404s, but that should be another issue because it's harder than just adding another match.

> Honestly, there are a couple more sites that they don't run on...

Which ones?

**Comment by TheColaber** [comment]
https://scratch.mit.edu/conference/2020
https://scratch.mit.edu/annual-report
to name just 2

**Comment by mxmou** [comment]
> https://scratch.mit.edu/conference/2020
> https://scratch.mit.edu/annual-report
> to name just 2

Also:
https://scratch.mit.edu/camp
https://scratch.mit.edu/join
https://scratch.mit.edu/starter-projects
https://scratch.mit.edu/classes/complete_registration (this one is incorrectly treated as a 2.0-styled page by scratchr2)
https://scratch.mit.edu/classes/:id/register/:token
https://scratch.mit.edu/signup/:token
https://scratch.mit.edu/educators/faq
https://scratch.mit.edu/educators/register
https://scratch.mit.edu/educators/waiting
https://scratch.mit.edu/wedo
https://scratch.mit.edu/wedo-legacy (why does this page still exist?)
https://scratch.mit.edu/ev3
https://scratch.mit.edu/microbit
https://scratch.mit.edu/vernier
https://scratch.mit.edu/boost

**Comment by RedGuy12** [comment]
sip.scratch.mit.edu/*
day.scratch.mit.edu/*<http://sip.scratch.mit.edu/*>

________________________________

**Comment by mxmou** [comment]
@RedGuy12 I don't think Scratch Addons currently runs on Scratch subdomains.

**Comment by WorldLanguages** [comment]
> I don't think Scratch Addons currently runs on Scratch subdomains.

Correct

**Comment by WorldLanguages** [comment]
Changed title for clarity - it sounded like no themes can run on those pages because of a bug in the addon loader, which is not the case.
