### ISSUE TITLE
[New addon] Scratch 2.0 --> 3.0

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#126]
**Describe the new addon**

By @mxmou, it changes pages with the scratch 2.0 theme to the scratch 3.0 theme. It also allows dark mode for the whole website and customization of the header color and other colors.

**Link to the new addon**

github.com/mxmou/customize-scratch

**Comment by WorldLanguages** [comment]
We should probably wait until the refactor on this is done, which will make it easier to port as a userstyle.

**Comment by Explosion-Scratch** [comment]
Okay! I'll close this temporarily.
