### ISSUE TITLE
Remove color setting from remix tree button

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#1262]
**Is your feature request related to a problem? Please describe.**

The remix tree button addon has a color setting. I don't think many people use it (other addons that add buttons don't have one), and it means that people who change the primary color in 2.0 → 3.0 will probably want to change the remix tree button color too.

**Describe the solution you'd like**

The addon should not have a color setting, the color would only be controlled by 2.0 → 3.0.

**Comment by mxmou** [comment]
Reopening, but needs more discussion.

**Comment by FunctionalMetatable** [comment]
maybe a checkbox that says "Default to 2.0 -> 3.0 colors"?

**Comment by mxmou** [comment]
@FunctionalMetatable The color setting should be disabled when that option is turned on, which is currently not possible.

**Comment by mxmou** [comment]
`if` now exists, so the addon could have a Boolean setting called "Change button color", which would be disabled by default, but enabled for existing users who chose a color other than the default blue. When it's enabled, the color setting would be shown.

The same feature could be added to other addons that add colored UI elements (debugger? https://github.com/ScratchAddons/ScratchAddons/pull/2161#issuecomment-846529452 - point 2).

**Comment by WorldLanguages** [comment]
Okay, we can now tackle this.
@mxmou I don't think it's that important to let users keep their old customizable color. All I think we should do is let them color the button differently to other buttons if they really want to. Do you think we could decide on a secondary button color (or maybe Scratch already has one in their palette)? Then, "use secondary color button" would be disabled by default except old users that had the color setting non-default.

**Comment by RedGuy12** [comment]
Why not just use the color from 2.0->3.0 and if that's disabled, use a setting in the addon?


________________________________

**Comment by Samq64** [comment]
I think the customizable colour option should just be removed completely and use the same colour as all the other buttons (either Scratch blue or the colour set with 2.0->3.0), because it just doesn't look good to have the one button a different color than all the rest and I don't think anyone touches the setting at all except to set it to their 2.0->3.0 color anyway.

**Comment by era2010-coder** [comment]
I agree

**Comment by WorldLanguages** [comment]
Okay, honestly we can remove the option altogether. At some point I rejected the idea and reverted a PR merged by apple502j, but because it was the same day as a release back then.
