### ISSUE TITLE
Search bar for messages

### ISSUE THREAD

**Issue by maDU59** [ScratchAddons/ScratchAddons#1269]
Add a search bar in the Scratch Addons interface for search messages (example: if I search for maDU59_, it will display the messages written by him that I have received, and those that mention it). I think it can be usefull.

**Comment by mxmou** [comment]
This sounds very similar to #1038.

**Comment by maDU59** [comment]
Oh yes, sorry.

**Comment by TheColaber** [comment]
Not a problem! Just close the issue, and we'll keep any conversations there!

**Comment by maDU59** [comment]
Ok, I will try

**Comment by TheColaber** [comment]
By the way, I saw your feedback on how to make an addon. If you know how to program in JS, then you can follow this [tutorial](https://github.com/ScratchAddons/ScratchAddons/wiki/Creating-an-addon)

**Comment by maDU59** [comment]
Ok, thank you very much
