### ISSUE TITLE
[Question] Should we invite more people to work on this?

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#127]
@apple502j @Hans5958 and @Ani-Xan ?

**Comment by WorldLanguages** [comment]
Apple is already working on some nice prototype pollution "hacks" that would hopefully let us more easily make addons that enhance the Scratch editor! :)

**Comment by Explosion-Scratch** [comment]
Cool! What about the others?

**Comment by Hans5958** [comment]
I'm trying to do #72 k

**Comment by tb148** [comment]
Note: Apple is invited.
