### ISSUE TITLE
New store screenshots

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1279]

**Comment by Marc92020** [comment]
Could you describe what this is about? I'm confused

**Comment by WorldLanguages** [comment]
@Marc92020 Making new screenshots for the extension stores, the current ones are from v1.2.1

**Comment by thecoder876** [comment]
> @Marc92020 Making new screenshots for the extension stores, the current ones are from v1.2.1

@WorldLanguages Wow, old screenshots

**Comment by Marc92020** [comment]
I made some screenshots 
![Screenshot 2021-01-16 at 11 59 14 AM](https://user-images.githubusercontent.com/75702334/104817906-5f72e700-57f2-11eb-970d-f1f894ffdb9d.png)
![Screenshot 2021-01-16 at 11 58 57 AM](https://user-images.githubusercontent.com/75702334/104817907-600b7d80-57f2-11eb-9f3e-da7a9bd80674.png)

**Comment by WorldLanguages** [comment]
@Marc92020 Thanks however don't worry about this, I'll figure it out. Chrome asks for very specific resolutions

**Comment by Marc92020** [comment]
@WorldLanguages OK

**Comment by WorldLanguages** [comment]
Moving to next milestone for lack of time, this is not urgent anymore because we now have a video in the Chrome Web Store from our YouTube channel :)
It really takes time to take some good screenshots, and don't worry I'll do it, I just want more time

**Comment by TheColaber** [comment]
WL did make new screenshots btw, which will be shown in v1.10.0

**Comment by WorldLanguages** [comment]
no, v1.9.0 stable
