### ISSUE TITLE
Scratch Stats buttons on profies 

### ISSUE THREAD

**Issue by superscratch444tre** [ScratchAddons/ScratchAddons#1284]
**Describe the new addon**

This will add quick links on profiles to ScratchStats.com and Hans5958's Scratch Stats.

**Link to the new addon**

Something like this: https://github.com/Hans5958/userscripts/blob/master/Scratch/Shorter%20Scratch%20Stats%20Links.user.js.

**Comment by RedGuy12** [comment]
why a button when you can include the information right there?

**Comment by superscratch444tre** [comment]
> why a button when you can include the information right there?

Yes, but that is harder to make.

**Comment by superscratch444tre** [comment]
> > why a button when you can include the information right there?
> 
> Yes, but that is harder to make.

And I think the links are better.

**Comment by pufferfish101007** [comment]
Including info from the scratchstats api is rejected (see https://github.com/ScratchAddons/ScratchAddons/issues/494#issuecomment-708705312), but using data from scratchstats isn't. Either way, #494 covers including information on profiles.

**Comment by mxmou** [comment]
> Including info from the scratchstats api is rejected (see [#494 (comment)](https://github.com/ScratchAddons/ScratchAddons/issues/494#issuecomment-708705312)), but using data from scratchstats isn't. Either way, #494 covers including information on profiles.

I think all important data is on ScratchDB, the only problem is that Scratch Addons can't currently access it (#1203).

**Comment by Hans5958** [comment]
Duplicate of #494

**Comment by Hans5958** [comment]
Wait, it's probably, reopening again, I guess.

**Comment by TheColaber** [comment]
duplicate of #494

**Comment by TheColaber** [comment]
Duplicate of #494
