### ISSUE TITLE
ScratchAddon YT channel

### ISSUE THREAD

**Issue by maDU59** [ScratchAddons/ScratchAddons#1285]
I think, someone can be open an YT channel for talk about new addons and featured will be out.
Maybe more peoples will use ScratchAddons. And add a button, on the scratch profile of the people who create the channel, or in the ScratchAddons interface, for go to the channel

**Comment by Marc92020** [comment]
I might, but I would have to create a new Google account which would be confusing

**Comment by jeffalo** [comment]
if this happens @WorldLanguages should make it, not anyone else

**Comment by jeffalo** [comment]
@WorldLanguages if you do make it, you can also make it as a brand channel and give account privellges to members

**Comment by maDU59** [comment]
@Marc92020 I think @jeffalo is right

**Comment by Marc92020** [comment]
ok :|

**Comment by Marc92020** [comment]
but it does make sense because he is the creator (I think) of Scratch Addons

**Comment by RedGuy12** [comment]
He is the person in charge. It was @Explosion-Scratch 's idea.
________________________________

**Comment by WorldLanguages** [comment]
> He is the person in charge. It was @Explosion-Scratch 's idea.

Bruh what's the source for that? It was my idea :P

**Comment by Cool-Scratcher** [comment]
I'm experienced with YouTube. If anyone making the channel needs help, I'm willing to assist.

**Comment by GrahamSH-LLK** [comment]
> > He is the person in charge. It was @Explosion-Scratch 's idea.
> 
> Bruh what's the source for that? It was my idea :P

Seriously! Where the heck did that come from?!?!

**Comment by jeffalo** [comment]
> I'm experienced with YouTube. If anyone making the channel needs help, I'm willing to assist.

![image](https://user-images.githubusercontent.com/40470736/104355627-3eb54380-550b-11eb-82df-e26de3f72f74.png)

**Comment by thecoder876** [comment]
> I might, but I would have to create a new Google account which would be confusing

It's not confusing.

**Comment by TheColaber** [comment]
Um guys... there's already a YT channel... https://www.youtube.com/channel/UCxS_mxVIz4iYGK3DKaupbMA

**Comment by thecoder876** [comment]
> @WorldLanguages if you do make it, you can also make it as a brand channel and give account privellges to members

It automatically creates a _brand account_ when you create a channel with a custom name. And yes, you can allow collaborators to access it.

**Comment by thecoder876** [comment]
> Um guys... there's already a YT channel... https://www.youtube.com/channel/UCxS_mxVIz4iYGK3DKaupbMA

WHAT???!!!

**Comment by TheColaber** [comment]
By us...

**Comment by thecoder876** [comment]
![image_2021-01-12_194103](https://user-images.githubusercontent.com/76265544/104364151-1bd85e80-550e-11eb-8fc6-114115ddc417.png)
Confirmed.

**Comment by TheColaber** [comment]
You may close this issue

**Comment by thecoder876** [comment]
But why was it created today @TheColaber?

**Comment by TheColaber** [comment]
It wasn't... by W_L of course... there is no other option... now please close the issue

**Comment by thecoder876** [comment]
> It wasn't... by W_L of course... there is no other option... now please close the issue

@WorldLanguages, pls review [the channel](https://www.youtube.com/channel/UCxS_mxVIz4iYGK3DKaupbMA).

**Comment by WorldLanguages** [comment]
https://www.youtube.com/channel/UCxS_mxVIz4iYGK3DKaupbMA is the official :tm: channel

**Comment by jeffalo** [comment]
i can confirm that

**Comment by Cool-Scratcher** [comment]
Here's an idea.
Anyone who makes a video for the channel publishes it to YouTube unlisted on a personal channel, then they send that link to a specified email. WL looks over the video, maybe editing it, and then uploads it. Anyone can submit a video.

**Comment by GrahamSH-LLK** [comment]
> Here's an idea.
> Anyone who makes a video for the channel publishes it to YouTube unlisted on a personal channel, then they send that link to a specified email. WL looks over the video, maybe editing it, and then uploads it. Anyone can submit a video.

Our current system is: Members can join the brand account, and upload videos.

**Comment by Cool-Scratcher** [comment]
> > Here's an idea.
> > Anyone who makes a video for the channel publishes it to YouTube unlisted on a personal channel, then they send that link to a specified email. WL looks over the video, maybe editing it, and then uploads it. Anyone can submit a video.
> 
> Our current system is: Members can join the brand account, and upload videos.

How would I join the brand account? And isn't that a bit risky (if someone uploads an inappropriate video)?

**Comment by pufferfish101007** [comment]
> How would I join the brand account? And isn't that a bit risky (if someone uploads an inappropriate video)?

I don't think it's particularly risky, as I think only trusted members who have been with the project for a long time will be/have been invited.

**Comment by GrahamSH-LLK** [comment]
> How would I join the brand account? And isn't that a bit risky (if someone uploads an inappropriate video)?

Members as in people who have commit access to the repos, etc.

**Comment by WorldLanguages** [comment]
No need to discuss about getting access to the YouTube channel, it's this simple: if you want to upload a video, send me a low quality version of it and if I approve I'll give you access to the channel so that you can upload it directly in high quality.
