### ISSUE TITLE
Donate button

### ISSUE THREAD

**Issue by maDU59** [ScratchAddons/ScratchAddons#1286]
Maybe add a donate button in ScratchAddons interface, for get money for #1285 (to buy a microphone, editing software, and more...) or for something else.

**Comment by Marc92020** [comment]
This is very confusing and what would be the purpose of donating on Scratch Addons? Its made on GitHub.

**Comment by maDU59** [comment]
Oh, ok, I don't know it

**Comment by WorldLanguages** [comment]
Only fixed cost is the domain (scratchaddons.com, ~$10 USD a year), if someone wants to help feel free to DM me on Discord :)

**Comment by RedGuy12** [comment]
Isn't tranisfex a bunch?
________________________________

**Comment by WorldLanguages** [comment]
@RedGuy12 We're on the free open source plan

**Comment by Hans5958** [comment]
Set up GitHub sponsor already

**Comment by WorldLanguages** [comment]
> Set up GitHub sponsor already

@Hans5958 I wouldn't be able to withdraw the money at the moment, I don't think Argentina is supported. Also if it has to go through a bank transaction fees will eat a huge pie of the donations (even BTC fees would be lower)
