### ISSUE TITLE
[New addon] Load more scrolling fix

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#129]
So recently @mxmou made a userstyle which fixes the 'load more' buttons on scratch. Now they do not scroll the page, I think it would be a nice thing to add to this.

**Comment by Explosion-Scratch** [comment]
Here's the link: https://github.com/mxmou/customize-scratch

**Comment by JeffaloBob** [comment]
i did it yay

**Comment by Explosion-Scratch** [comment]
Thanks Jeffalo
