### ISSUE TITLE
Add more cat block functionality

### ISSUE THREAD

**Issue by Touchcreator** [ScratchAddons/ScratchAddons#1298]
**Is your feature request related to a problem? Please describe.**

Their ears are still
**Describe the solution you'd like**

Make their ears jiggle if you touch them

**Comment by TheColaber** [comment]
I plan to do this ;)

**Comment by Touchcreator** [comment]
> 
> 
> I plan to do this ;)

Ok :)

**Comment by Marc92020** [comment]
They are also broken like their ears break sometimes

**Comment by TheColaber** [comment]
Please give this better naming :)
