### ISSUE TITLE
Weird Catblock glitch

### ISSUE THREAD

**Issue by Marc92020** [ScratchAddons/ScratchAddons#1299]
I am the #1 Bug Reporter!
(ignore the "1" link)

**Describe the bug**
When you click a cat block when there is code in it, the cat blocks yellow (or whatever color the block is) ear part is gone and it has tiny pink ears.

**To Reproduce**

1. Go to Scratch
2. Click on Create
3. Scroll down to anywhere with the cat blocks
4. Put some code in it
5. Click the block and see the error

**Expected behavior**
The cat block ears should stay normal

**Screenshots**
![Screenshot 2021-01-12 at 9 14 37 AM](https://user-images.githubusercontent.com/75702334/104325556-c2911080-54b6-11eb-8a10-28c5e0a52db8.png)
![Screenshot 2021-01-12 at 9 14 20 AM](https://user-images.githubusercontent.com/75702334/104325559-c329a700-54b6-11eb-9ea2-6f1001666810.png)

**Device (please complete the following information):**

- OS: [Chrome OS]
- Browser [Chrome]
- Version [SA: 1.7.1 Chrome: 87]

**Additional context**
none

**Comment by TheColaber** [comment]
Hmm I'm not getting the problem...
https://user-images.githubusercontent.com/72760579/104387076-62c15680-5504-11eb-8b70-fc0f51ad0f50.mp4

**Comment by TheColaber** [comment]
:o didn't relize it happened at the end... oohhh could it be a conflict with the editor stepping addon?
