### ISSUE TITLE
More methods for addon.account API?

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#13]
Currently it's only getMsgCount()

**Comment by GDUcrash** [comment]
My ideas:

`.getAccount().username`
`.getAccount().profilePicture`
`.getAccount().bio`
`.getAccount().workingon`
`.getAccount().activity`

**Comment by GDUcrash** [comment]
so when you call the `getAccount()` function it returns the object containing all the necessary info about user, something like this:
```js
{
    username: "OnMax",
    profilePicture: "https://cdn.scratch.mit.edu/assgejdh",
    bio: "Some long-ish text",
    workingOn: "Something",
    activity: [array]
}
```

**Comment by GDUcrash** [comment]
Just realized, the "username" method is already in the "auth" api... whoops

**Comment by WorldLanguages** [comment]
I'll close this for now. We'll probably have some nice ideas for this API once we start adding more addons. If that's the case, let's open a more specific issue for each method or getter.
