### ISSUE TITLE
Ability for addons to know they've been disabled

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1303]
Possible usecases:
1. Userscripts could revert their action in the page if disabled (e.g. discuss button is removed after it is disabled)
2. Could be used in persistent scripts as the proper way to unregister any event listeners.

**Comment by TheColaber** [comment]
Related: #783

**Comment by WorldLanguages** [comment]
Haven't mentioned, userscripts (but not persistent scripts) could also have a "reactivated" event (AKA revert the revert, e.g. readd the discuss button)
