### ISSUE TITLE
"More links" addon lags the page

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1304]
Linkify appears to block the main thread.

**Comment by WorldLanguages** [comment]
@Hans5958 I want to do something about this before v1.8, remember that PR? Did we find out what was blocking the main thread? Is it linkify or the addon, or both? It would be sad to remove this addon but it causes significant lag.

**Comment by RedGuy12** [comment]
> It would be sad to remove this addon but it causes significant lag.

If we can't figure it out we can add a beta tag and a notice to the addon
________________________________

**Comment by TheColaber** [comment]
>> It would be sad to remove this addon but it causes significant lag.
> If we can't figure it out we can add a beta tag and a notice to the addon

It already has a beta tag so we don't need to worry about that.

**Comment by Hans5958** [comment]
> @Hans5958 I want to do something about this before v1.8, remember that PR? Did we find out what was blocking the main thread? Is it linkify or the addon, or both? It would be sad to remove this addon but it causes significant lag.

I think we still not sure what happen. I have made it so it is specific. Probably just put a warning for now.
