### ISSUE TITLE
Forum search addon returns error

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [ScratchAddons/ScratchAddons#1307]
Whenever I try searching the forum using the forum search addon, it returns the error `Error loading from ScratchDB!`

**Comment by TheColaber** [comment]
Hey! Welcome to the ScratchAddons Repo! We are aware of this problem as notified by the pinned issue... https://github.com/ScratchAddons/ScratchAddons/issues/1203

**Comment by ego-lay-atman-bay** [comment]
oh, ok
