### ISSUE TITLE
Messages count is quite unreadable if you change the primary color in the Scratch 2.0 -> Scratch 3.0 addon to a bright color

### ISSUE THREAD

**Issue by superscratch444tre** [ScratchAddons/ScratchAddons#1320]
**Describe the bug**

The message count is quite unreadable if you change the color of the navbar in the Scratch 2.0 -> Scratch 3.0 addon to a bright color

**To Reproduce**

1. Go to the settings page and enable the Scratch 2.0 -> Scratch 3.0 addon
2. Change the primary color to a bright color
3. Go to any scratch page
4. See that the messages count is unreadable

**Expected behavior**

1. The message count number should be white
2. The background should be a color that's brighter than that dark brown (e.g. the default Scratch orange)

**Screenshots**

<img width="784" alt="error sa" src="https://user-images.githubusercontent.com/69812464/104638000-7a801280-569d-11eb-909d-0c5f14ff3bcd.png">
<img width="809" alt="sa" src="https://user-images.githubusercontent.com/69812464/104639799-bb792680-569f-11eb-8eab-60e42031d995.png">

**Device (please complete the following information):**

- OS: [Windows]
- Browser [Chrome]
- Version [87.0.4280.141]

**Additional context**

No.

**Comment by TheColaber** [comment]
That's not really our fault... that would be your fault for wanting to have color like that which probably no one would use. On a daily basis would you use that color? probably not.

**Comment by superscratch444tre** [comment]
Ok, but I look:

<img width="809" alt="sa" src="https://user-images.githubusercontent.com/69812464/104639400-49a0dd00-569f-11eb-82b0-37a17bec6c9c.png">

**Comment by superscratch444tre** [comment]
This applies to all the colors that will make the text in the navbar black

**Comment by mxmou** [comment]
@TheColaber It's still a bug. It happens with all bright colors.

I'll try to fix this.
