### ISSUE TITLE
Changes related to labels

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#1330]
Hello everyone. I created this issue to let you aware of the changes with the labels. 

As promised, I have finished with the revamp, which you can refer to again on #970, along with some other changes related to it.

- Templates have been changed to include the new labels.
- "status: needs triage" has been added for every issue template.
- PRs may be triaged automatically. (aka labeled with relevant one)
- Colors have been adjusted, hopefully, it is better.
- All open issues and PRs have been labeled/triaged.

Some general rules and recommendations for collaborators who wanted to triage the issues.
- Have at least one type and one scope on each issue, and one type on each pull request.
- Labels are flexible, so you can put more than one per label category (e.g. there can be two scopes).
- Priority may be added, but it's not mainstream yet.

For general users and contributors, you can go to https://github.com/ScratchAddons/ScratchAddons/issues/labels and click one of the labels to narrow your list or use the search feature.

If you wanted to look again at what each label meant, you can go to #970, or look at the description on each label. Hope you guys like this change, and the development of SA can be easier and more efficient. Comments can be put on this issue.

I will pin this for the next 4 days, or earlier/later if someone wanted to.

**Comment by apple502j** [comment]
Labeling workflow is disabled due to it malfunctioning.

**Comment by Hans5958** [comment]
@apple502j Ah, thanks. I wasn't sure if it will work before. Will replace it with a better action later.

**Comment by Hans5958** [comment]
In case you missed, I have added two new scopes, `scope: webpages` and `scope: extension workings`. **For `scope: extension workings`, does anyone know a shorter, alternative name, or is it okay to use that name?** I was kinda confused as this is made in hurry, because I realized how many issues of it.

Here are some that I have considered?

- `scope: extension` (not specific)
- `scope: engine` (nice, more descriptive?)
- `scope: extension engine` (nicer from above)
- `scope: behind the scenes` (may be confused with meta)
- `scope: bts` (read above)
- `scope: loader` (it's not just the loader)
- `scope: bg-cs` (not obvious)
- `scope: background and content script` (too long and not obvious)

cc @WorldLanguages

**Comment by apple502j** [comment]
Suggestion:
- remove "type: " from label name, "bug" is enough
- "scope: extension workings" -> "scope: core"
- "scope: webpages" -> "scope: settings" (popup is merged with scope:addon)
- "status: pending" -> "do not merge" or "status: do not merge"
- new label: "status: needs discussion" (for issues)
- "status: will not fix" -> "status: wontfix"

Easy-to-read labels are good but it's not nerdy enough.

**Comment by Hans5958** [comment]
> remove "type: " from label name, "bug" is enough

As I said, we have so many labels to hold so many issues, so prefixing is needed to keep it tidy.

> "scope: extension workings" -> "scope: core"

Good name, I will consider.

> "scope: webpages" -> "scope: settings" (popup is merged with scope:addon)

Too narrow to support other types of webpages. What I meant of popup is the extension popup, located on https://github.com/ScratchAddons/ScratchAddons/tree/master/webpages/popup.

> "status: pending" -> "do not merge" or "status: do not merge"

Pending is fine by WL, and this label is also to support pending issues.

> new label: "status: needs discussion" (for issues)

Can be supported by `status: pending`

> "status: will not fix" -> "status: wontfix"

I was also thinking about this one. Will consider.

> Easy-to-read labels are good but it's not nerdy enough.

Nerdy is not needed because we might attract people that new on GitHub.

**Comment by RedGuy12** [comment]
> Too narrow to support other types of webpages. What I meant of popup is the extension popup, located on https://github.com/ScratchAddons/ScratchAddons/tree/master/webpages/popup.


But that's an addon now.
________________________________

**Comment by RedGuy12** [comment]
> But that's an addon now.


Wait, the iframe in the popup is an addon, but the popup itself isn't. So `scope: webpages` is for the settings page and the page that loads the iframe. I see now!

________________________________

**Comment by Hans5958** [comment]
> 
> Too narrow to support other types of webpages. What I meant of popup is the extension popup, located on [`master`/webpages/popup](https://github.com/ScratchAddons/ScratchAddons/tree/master/webpages/popup?rgh-link-date=2021-01-16T14%3A16%3A54Z).
> But that's an addon now.

Noo.... I'm talking about this one.

![The extension pop-up](https://scratchaddons.com/assets/images/showcase/popup.png)

**Comment by apple502j** [comment]
"webpages" is just too confusing without context. We should use addon-api for popups then.

**Comment by apple502j** [comment]
@Hans5958 also the reason I added "needs discussion" was to split "pending"...

**Comment by RedGuy12** [comment]
> "webpages" is just too confusing without context. We should use addon-api for popups then.

It's about all the files in the webpages folder

Webpages isn't too confusing there
________________________________

**Comment by apple502j** [comment]
It isn't if the Issue page is used only for technical development of Scratch Addons - but there are some issues that aren't, and some are for actual Scratch Addons websites.

**Comment by Hans5958** [comment]
> "webpages" is just too confusing without context. We should use addon-api for popups then.

Technically, `scope: webpages` refers to everything on the webpages folder (RedGuy12 got it right). Generally, it means the web pages, which even outsider thinks it's the HTML files of it, which mostly exists on the webpages folder.

> also the reason I added "needs discussion" was to split "pending"...

Well, I tried to simplify things after all. On second thought it is actually similar to `status: needs info` than `status: pending`, since it's not been working on.

**Comment by RedGuy12** [comment]
> some are for actual Scratch Addons websites

Then it doesn't go here, but on ScratchAddons/website
________________________________
