### ISSUE TITLE
Removes the 'Tutorials' button

### ISSUE THREAD

**Issue by Miala-python** [ScratchAddons/ScratchAddons#1333]
Hello,
when we activate all the functions of the editor, the bar at the top is too big compared to the rest of the editor. I therefore suggest that you make an option that removes the 'Tutorials' button.
thank you,
Miala

Text translated from French by Google Translate

**Comment by WorldLanguages** [comment]
For tiny themes like this, users should make their own CSS userstyle.

**Comment by WorldLanguages** [comment]
Well sorry this is awkward but OP has a point, the button is big, takes a lot of space and is mostly unused by users, so eh, keeping open :P

**Comment by Miala-python** [comment]
Thank you because I don't know how make a extension !

**Comment by mxmou** [comment]
Fixed by #3741
