### ISSUE TITLE
Some website themes slightly affect the editor

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1354]
Cannot remember what theme it was, but it was styling inputs and textareas even in the editor.

**Comment by RedGuy12** [comment]
Wasn't this fixed in 1.7.1?
________________________________

**Comment by mxmou** [comment]
Which inputs and textareas? I have all website themes on and the editor looks normally. Website dark mode changes the border color of inputs but that's overridden by Scratch's own styles.

**Comment by mxmou** [comment]
Oh, it's the record options popup.
