### ISSUE TITLE
Transifex doesn't detect variables in Addons Translation

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#1361]
**Describe the bug**

Text in curly brackets in addons-l10n isn't detected as a variable by Transifex.

**To Reproduce**

In Transifex, go to the string `a11y/sayBubble`. Note that it shows `"{text}"` literally, not as a variable.

**Expected behavior**

It would be displayed as a variable.

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/51849865/105154534-edf4aa80-5b09-11eb-8559-cafa154013f7.png)

**Comment by apple502j** [comment]
Fixed.
