### ISSUE TITLE
Inconsistent padding in More Settings

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#1364]
**Describe the bug**

Similar to #1173, but in More Settings.

**To Reproduce**

Go to the settings page and open More Settings.

**Expected behavior**

The amount of padding on different elements should be consistent.

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/51849865/105173565-7f234b80-5b21-11eb-9aad-b53f4a92b544.png)

**Comment by mxmou** [comment]
Should probably be done after #1277

**Comment by Hans5958** [comment]
Unrelated, but I just removed your `needs triage` label from your recent issues. If you have one scope and one type then you may remove it.

**Comment by GrahamSH-LLK** [comment]
Most of these problems are from apple adding the import/export.

**Comment by mxmou** [comment]
> Most of these problems are from apple adding the import/export.

Even if you ignore the import/export part there are still a lot of different padding values.

**Comment by WorldLanguages** [comment]
> Most of these problems are from apple adding the import/export.

Bruh why blame someone

**Comment by GrahamSH-LLK** [comment]
> > Most of these problems are from apple adding the import/export.
> 
> Bruh why blame someone

Sorry, what I meant was that the buttons are implemented incorrectly, there should probably be a bit of text there.

**Comment by Hans5958** [comment]
Just came back here. I also need to mention the behavior of the buttons, one fades lightly, the other one goes too dark, sizes are also different, the text color is also different.

**Comment by mxmou** [comment]
> Just came back here. I also need to mention the behavior of the buttons, one fades lightly, the other one goes too dark, sizes are also different, the text color are also different.

Reusing classes intended for other things (the filter bar) caused this.

**Comment by mxmou** [comment]
> Just came back here. I also need to mention the behavior of the buttons, one fades lightly, the other one goes too dark, sizes are also different, the text color are also different.

Fixed in #3036.
