### ISSUE TITLE
New Featured sections.

### ISSUE THREAD

**Issue by spdblx** [ScratchAddons/ScratchAddons#1376]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Y'know how the Featured Projects/Studios sections suck? What if we had our own and featured projects that are actually good. Some examples would be Appel, Super Scratch Smash, The Mythic Game of Ur, and Ikachan ~ Full Scratch Port.

**Describe alternatives you've considered**
null

**Additional context**
null

**Comment by pufferfish101007** [comment]
I realy don't think this is likely to happen, for a couple of reasons:
- it would rewuire someone to select projects, and that someone will always be biased
- we'd either need it to be updated every release - and I think people will get bored of seeing the exact same projects for 2 weeks - ir set up a database and server, which no one wants. Or at least, most org members don't, as far as I know.
- replacing the projects that are already there with supposedly better projects would most likely offend the people who made them, and also deprive the people who made them of a couple of thousand more views potentially, whereas the projects that would be chosen for this (or at least the ones you've suggested) already have zillions of views, loves and faves - so they'll end up in the popular and trending sections of explore anyway.

**Comment by RedGuy12** [comment]
We could pull the "featured on scratchstats" projects from the studio
________________________________

**Comment by mxmou** [comment]
This might be work if the projects are from a studio and if it just adds them to the front page without removing featured projects.

**Comment by WorldLanguages** [comment]
This could work but good luck finding someone that will consistently review project suggestions.

**Comment by jeffalo** [comment]
> We could pull the "featured on scratchstats" projects from the studio

> This could work but good luck finding someone that will consistently review project suggestions.

👀

**Comment by lisa-wolfgang** [comment]
This issue will probably be closed. Managing our own list of featured addons is outside the scope of Scratch Addons, but customizing the front page to remove the existing featured projects and include another featured projects source is not rejected: https://github.com/ScratchAddons/ScratchAddons/issues/1758

**Comment by spdblx** [comment]
> This issue will probably be closed. Managing our own list of featured addons is outside the scope of Scratch Addons, but customizing the front page to remove the existing featured projects and include another featured projects source is not rejected: #1758
