### ISSUE TITLE
Addons have been glitching and not working and been turning on and off

### ISSUE THREAD

**Issue by Marc92020** [ScratchAddons/ScratchAddons#1381]
**Describe the bug**
Dark mode won't work, 2.0 to 3.0 wont work, and notes and credits tab won't work

**To Reproduce**
Go to Scratch
Addons not working

**Expected behavior**
The addons should work. I also have them enabled.

**Screenshots**
I can't without it looking confusing

**Device (please complete the following information):**

- OS: [Chrome OS]
- Browser [Chrome]
- Version [87]

**Additional context**
Addons keep turning on and off and is being really annoying

**Comment by Marc92020** [comment]
Someone help me the addons are usless and I feel like getting rid of Scratch Addons but I won't don't worry :)

**Comment by TheColaber** [comment]
Do you have any other extension enabled?

**Comment by Marc92020** [comment]
no

**Comment by Marc92020** [comment]
i mean yes but not Scratch Extensions

**Comment by TheColaber** [comment]
Reinstall scratch addons and see if it works. Make sure you also don't have 2 scratch addons running.

**Comment by Marc92020** [comment]
I think I do. I might have unpacked one by accident. I also don't wanna remove Scratch Addons because then I will forget my block colors and all the color stuff (which color to specifically put)

**Comment by TheColaber** [comment]
If you have 2, that is the problem. You can load settings by going into "More Settings" and pressing "Export Settings" then in your other ScratchAddons extension, click "Import Settings" selecting the file to your addon settings.

**Comment by WorldLanguages** [comment]
Yeah don't have more than one Scratch Addons at once.

**Comment by Marc92020** [comment]
OK I forgot that there was an option to do that. Anyway just gonna close this
