### ISSUE TITLE
curator link dosen't work

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#1388]
**Describe the bug**

the curator link addon doesn't linkify the username

I get this error:

```
Uncaught (in promise) TypeError: Cannot read property 'splash.projectsCuratedBy' of undefined
    at EventTarget.scratchMessage (Tab.js:116)
    at Module.default (script.js:14)
scratchMessage @ Tab.js:116
default @ script.js:14
async function (async)
default @ script.js:5
loadUserscript @ run-userscript.js:20
async function (async)
loadUserscript @ run-userscript.js:16
window.addEventListener.once @ run-userscript.js:30
```

**To Reproduce**

go to the front page
see error

**Expected behavior**

the text to be linked

**Comment by TheColaber** [comment]
Are you on stable version? Or on the master?

**Comment by RedGuy12** [comment]
Stable version

**Comment by TheColaber** [comment]
Hmm, I'm not getting that error... 
![image](https://user-images.githubusercontent.com/72760579/105566766-edbc0100-5cfb-11eb-8a31-e2a10a59f4d0.png)

**Comment by RedGuy12** [comment]
> Hmm, I'm not getting that error...
> ![image](https://user-images.githubusercontent.com/72760579/105566766-edbc0100-5cfb-11eb-8a31-e2a10a59f4d0.png)

huh

**Comment by Marc92020** [comment]
I'm also not getting this error. It works fine for me
![Screenshot 2021-01-23 at 12 01 51 PM](https://user-images.githubusercontent.com/75702334/105608747-d5d39400-5d72-11eb-843b-0be72c5b47e0.png)

**Comment by mxmou** [comment]
What's your browser language?

**Comment by WorldLanguages** [comment]
The error appears to be caused because `window._messages[window._locale]` is undefined, see https://github.com/ScratchAddons/ScratchAddons/blob/master/addon-api/content-script/Tab.js#L124

**Comment by RedGuy12** [comment]
hmmm working now
