### ISSUE TITLE
[Feature] Releases and beta versions?

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#139]
It would be super cool to have beta versions, with the quote thing and deleted comments thing by jeffalo and previous releases. Releases would be nice to have in case we mess up or want a previous version for something.

**Comment by WorldLanguages** [comment]
Why not just accept beta addons? The `"beta"` tag exists for a reason :P 
Maybe, we can hide beta addons from the settings page unless the user opts in.
I don't think having 2 releases is a good idea.

**Comment by Explosion-Scratch** [comment]
I think releases would still be good because the betas would have all the experimental features instead of just the one in the pr.

**Comment by JeffaloBob** [comment]
maybe add-on manifests could have a key that says that theyre hidden, so the user if they really wanted they could enable it with JavaScript

**Comment by NoobTracker** [comment]
Or that those pre-releases are just always disabled by default and have a beta tag in the manager.

**Comment by Hans5958** [comment]
Reminder that releases and pre-releases are a thing in (schematic) versioning and GitHub. If a release is not ready for general usage, set it as a pre-release.

**Comment by tb148** [comment]
> Why not just accept beta addons? The `"beta"` tag exists for a reason :P
> Maybe, we can hide beta addons from the settings page unless the user opts in.
> I don't think having 2 releases is a good idea.

@WorldLanguages But what if a stable addon added a beta feature?

**Comment by Hans5958** [comment]
> 
> 
> > Why not just accept beta addons? The `"beta"` tag exists for a reason :P
> > Maybe, we can hide beta addons from the settings page unless the user opts in.
> > I don't think having 2 releases is a good idea.
> 
> @WorldLanguages But what if a stable addon added a beta feature?

Then it is going to be a beta addon again, since it is not ready for general usage, right?

Speaking of which, should we add versions on the addons?

**Comment by tb148** [comment]
> Then it is going to be a beta addon again, since it is not ready for general usage, right?

Lets list possible changes:

1. Bug fixes. They only makes things more stable.
2. Features. They are what is not ready for general usage.

So I think we can add statuses to options: `alpha`(exists, but does not appear in menu, only configurable via "hacks"), `beta`(have notice about unstableness in the menu), and `stable`(probably the default value). So if a stable addon added a beta feature the feature can have a `beta` status.

**Comment by Hans5958** [comment]
> 
> 
> > Then it is going to be a beta addon again, since it is not ready for general usage, right?
> 
> Lets list possible changes:
> 
>     1. Bug fixes. They only makes things more stable.
> 
>     2. Features. They are what is not ready for general usage.
> 
>     3. Other "weird" changes. They don't usually change the stableness.
> 
> 
> So I think we can add statuses to options: `alpha`(exists, but does not appear in menu, only configurable via "hacks"), `beta`(have notice about unstableness in the menu), and `stable`(probably the default value). So if a stable addon added a beta feature the feature can have a `beta` status.

I'd rather have two types only, pre-releases (beta) and releases (stable). We should not make things more complicated than ever.

**Comment by Hans5958** [comment]
Related: #65

**Comment by WorldLanguages** [comment]
This is basically not going to happen for now
