### ISSUE TITLE
Release new versions in the Chrome Web Store before Mozilla FIrefox Add-ons

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#1399]
Release new versions in the Chrome Web Store before Mozilla FIrefox Add-ons because Scratch Addons has more users on Google Chrome than on Mozilla Firefox. Also I'm tired of waiting ~8 hours after a new update has just been released. Please change it.

**Comment by RedGuy12** [comment]
Extensions in the Chrome Web Store must be reviewed, but not in the Mozilla Firefox store. So nothing can be done about that.
________________________________

**Comment by Secret-chest** [comment]
Ok.

**Comment by WorldLanguages** [comment]
Yeah, Chrome is being super strict about reviewing every extension upload now
