### ISSUE TITLE
New mode for "Auto-hide block palette" addon: Hover in category

### ISSUE THREAD

**Issue by Lurux** [ScratchAddons/ScratchAddons#1404]
**Describe the bug**

Auto-hide block palette is currently useless (tested in Firefox), because an invisible element still obstructs the editor when the palette is hidden. This means you can't meaningfully use the screen space gained from the hidden sidebar:

- When in "hover" mode, the sidebar will appear on the screen as soon as you hover the space it would normally occupy
- When in "click" mode, there is a dead space on the space the sidebar is supposed to be.

**To Reproduce**

1. Enable the extension
2. Go to the editor

**Expected behavior**

I guess the sensing space of the sidebar should be update when it hidden

**Device (please complete the following information):**

- OS: Linux Mint
- Browser Firefox
- Version 84

**Additional context**

This idea is really amazing since Scratch 3 made everything so big, this is vital for people with small screens like me :smile:

**Comment by WorldLanguages** [comment]
I guess this is the bug specifically:
> When in "click" mode, there is a dead space on the space the sidebar is supposed to be.

Can you elaborate what it being dead space means? Can't you drag blocks there? Sorry I'm not very familiar with this addon.
btw cc @TheColaber

**Comment by TheColaber** [comment]
tbh I'm not sure I understand the problems...

**Comment by TheColaber** [comment]
> When in "click" mode, there is a dead space on the space the sidebar is supposed to be.

Actually, I understand this... the placeholder goes in front of the blocks so you can't drag there... I don't know a good way to fix this right now.

**Comment by TheColaber** [comment]
I'm complicating things aren't I... the plaeholder should just be hidden the entire time when in click mode.

**Comment by TheColaber** [comment]
@Lurux could you explain
> When in "hover" mode, the sidebar will appear on the screen as soon as you hover the space it would normally occupy

The other one is an easy fix.

**Comment by WorldLanguages** [comment]
@Lurux if possible get record your screen so that we can understand better

**Comment by Lurux** [comment]
@WorldLanguages @TheColaber, here is an illustration of what i mean.

In this picture I have auto-hide block palette enabled in "hover" mode, and I just moved my mouse from the right (thus, with the palette hidden) toward the left of the screen.

As you can see, the block palette appeared under the mouse pointer as soon as i entered the zone it is supposed to live in (rightmost red mark), as opposed to when I enter the category selector (leftmost red mark.

![scratch addon](https://user-images.githubusercontent.com/35870988/105756426-e475a300-5f4c-11eb-9cea-9f3b7beffde4.png)

What I describe as a dead space when in "click" mode, is a space in which mouse click aren't registered, as if they were still obstructed by the palette. In practice, this means no clicking or dragging of blocks from this zone, and no moving the view of the editor to see left / right / up / etc...

As @TheColaber said, it is likely that the placeholder of the block palette isn't hidden properly when needed, which would explain all of these problems.

Anyway, thanks for your attention ! :smile:

**Comment by TheColaber** [comment]
So is the problem that the sensing area is too small?

**Comment by WorldLanguages** [comment]
@Lurux I see what you mean, thanks for reporting!

**Comment by mxmou** [comment]
Reopening. Category click mode was fixed (can you make the palette disappear when you click outside it?), but in hover mode the palette still appears as soon as you move the mouse where it would normally be. This bug is even visible in the update notification.

**Comment by Lurux** [comment]
> So is the problem that the sensing area is too small?

If you're talking about the editor area, yes. Although as I said before, I think the problem is actually the contrary (that is, the placeholder for the block palette is too large) :smile:

**Comment by TheColaber** [comment]
Oh... so just to be clear, you guys want the placeholder smaller? That's not a bug... that's more of an "enhancement" if I were to add a setting to change the width of the placeholder, anyway, I'll work on that too.

**Comment by mxmou** [comment]
@TheColaber Ideally there would be no placeholder at all and the palette would only show when hovering the category menu. This would make it possible to interact with blocks that would normally be below the palette - I thought that was the purpose of this addon.

**Comment by TheColaber** [comment]
> @TheColaber Ideally there would be no placeholder at all and the palette would only show when hovering the category menu. This would make it possible to interact with blocks that would normally be below the palette - I thought that was the purpose of this addon.

This "hover" setting means to create a placeholder, and when it's hovered to show the real flyout. This was taken from better 3.0... now I could always go around making another setting option for that, but at this point, I would need approval from wl.

**Comment by mxmou** [comment]
> This "hover" setting means to create a placeholder, and when it's hovered to show the real flyout.

The only benefit of this is that you can see the blocks below it (which you can anyway because the palette is slightly transparent) but you can't interact with them. I think the alternative behavior is much more useful.

**Comment by TheColaber** [comment]
I see your point...

**Comment by WorldLanguages** [comment]
I see, @mxmou keep in mind this wasn't seen as a bug by us.

Let's have 3 modes then:
1. Hover (no changes from v1.8)
2. Hover in category (new - what @mxmou expected, and makes some sense)
3. Click in category (no changes from v1.8)

**Comment by RedGuy12** [comment]
But then, what's the point of hover mode?
________________________________

**Comment by mxmou** [comment]
> But then, what's the point of hover mode?

Probably to see more blocks, although it isn't really useful if you can't do anything with them.

**Comment by Lurux** [comment]
> I see, @mxmou keep in mind this wasn't seen as a bug by us.
> 
> Let's have 3 modes then:
> 
>     1. Hover (no changes from v1.8)
>     2. Hover in category (new - what @mxmou expected, and makes some sense)
>     3. Click in category (no changes from v1.8)

As was said before, i don't see the point of the first option then.

> > This "hover" setting means to create a placeholder, and when it's hovered to show the real flyout.
> 
> The only benefit of this is that you can see the blocks below it (which you can anyway because the palette is slightly transparent) but you can't interact with them. I think the alternative behavior is much more useful.

Go ahead if you prefer to have three options, but I'm afraid this would be confusing to new users...

**Comment by TheColaber** [comment]
I personally like all the options because I have a huge screen. I like the first one because whenever I feel like dragging a block, I don't need to click anything, I can just pretend like it's there already... anyway it is ScratchAddons so you don't have to have that option set to hover.

**Comment by Lurux** [comment]
Ok, I guess that makes sense...

I'm really nitpicking at this point, but in that case wouldn't it make sense to apply something like a 20% opacity to the block palette in hover mode instead of hiding completely ? Or maybe add some sort of visual indicator to the hover zone ?

**Comment by TheColaber** [comment]
I feel like applying opacity would give the sense that it's still there... but it's very possible, but I'm not sure if it's something useful to implement.

**Comment by mxmou** [comment]
@TheColaber The hover option isn't useful anyway. This addon is not useful big screens, it's meant to extend the workspace by hiding the block palette. I agree that the palette should be still visible - but transparent - in hover mode, because that's the only way to make this very unintuitive behavior less weird.

**Comment by RedGuy12** [comment]
> I feel like applying opacity would give the sense that it's still there

Well it is
________________________________

**Comment by mxmou** [comment]
> > I feel like applying opacity would give the sense that it's still there

> Well it is

Exactly - it's practically still there, but invisible.

**Comment by WorldLanguages** [comment]
I'd be OK changing the default to "category hover" for users with this addon disabled

**Comment by Lurux** [comment]
> I feel like applying opacity would give the sense that it's still there... but it's very possible, but I'm not sure if it's something useful to implement.

As was said above, this is indeed the case in "hover" mode (not the two others), sooo... Yeah.
