### ISSUE TITLE
The More Links addon turns a sequence of dots into a link

### ISSUE THREAD

**Issue by Fupicat** [ScratchAddons/ScratchAddons#1415]
**Describe the bug**

If a comment contains a sequence of dots like this: ..... they turn into a link.

**To Reproduce**

1. Have the More Links addon activated and comment a bunch of dots.
2. The dots and whatever characters are connected to them become a link.

**Expected behavior**

The addon could only turn text into a link if there are letters after a dot, not more dots.

**Screenshots**

![image](https://user-images.githubusercontent.com/36973337/105858822-85567380-5fca-11eb-91c2-d1e268a62f24.png)

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 84.0.2

**Additional context**

I think it didn't happen before the most recent update.

**Comment by Hans5958** [comment]
@apple502j

**Comment by RedGuy12** [comment]
Yes, we had to replace our linking library with a regular expression due to lag.
________________________________
