### ISSUE TITLE
Support more types of addon settings

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#142]
Right now, only supported types are `boolean` and `positive_integer`.
We should also probably provide:
`select`: allow the user to choose between multiple options.
`string`: allow the user to type up to 100 chars.

**Comment by Explosion-Scratch** [comment]
Colors too. Although this could be (rather inconveniently) be worked around with hex codes and string inputs.

**Comment by JeffaloBob** [comment]
and maybe something that returns an array of objects or something? 
![1598904301671](https://user-images.githubusercontent.com/40470736/91797292-7ab5cf00-ec22-11ea-8cc7-85d307fb4a00.png)

**Comment by NoobTracker** [comment]
Really `checkbox`? I think that in the JSONs it's `boolean`.

**Comment by NoobTracker** [comment]
I think that floats could be neat too and also signed ints.

**Comment by NoobTracker** [comment]
Also, additional options that are only available when a checkbox is checked would be great, like
- [ ] add a discuss button

and when you click that you get

- [x] add a discuss button
- [ ] replace the ideas button with the discuss button

(that's maybe not the best example but you get the point)

Also the ability to create lists would be cool, like

Additional buttons:
\+

and when you click there you can do stuff like

Additional buttons:
- URL: [https://scratch.mit.edu/discuss/1/] Description: [Suggestions] -
- URL: [https://scratch.mit.edu/discuss/5/] Description: [Announcements] -
\+

so you can add as many buttons as you want and delete them by clicking the minus. Something like that would be great, although I think that it wouldn't be that easy but still cool.

Image/File inputs would be another idea.

**Comment by NoobTracker** [comment]
So, after I now looked at the way those JSONs work and here is my idea how such a list could work:
For one thing, the type of input is `list`.
You can create a schema that can also contain lists.
Example:
```
"options": [
  {
    "name": "Added buttons:",
    "id": "addbuttons",
    "type": "list",
    "schema": [
      {
        "name": "Description: ",
        "id": "description",
        "type": "string",
        "maxlength": 30,
        "default": "",
        "placeholder": false
      },
      {
        "name": "URL: ",
        "id": "url",
        "type": "string",
        "maxlength": false,
        "default": "",
        "placeholder": "https://"
      },
      {
        "name": "Add this button? ",
        "id": "addbool",
        "type": "boolean",
        "default": true
      }
    ],
    "default": [
      {
        "description": "Discuss",
        "url": "https://scratch.mit.edu/discuss/",
        "addbool": true
      },
      {
        "description": "Suggestions",
        "url": "https://scratch.mit.edu/discuss/5/",
        "addbool": false
      }
    ]
  }
],
```
Hope that makes sense. I also added some other stuff, the `maxlength` and a `placeholder`.
You can access those objects like this:
```
addon.settings.get("addbuttons")[1].get("description") //returns "Suggestions"
```

I don't know much about JSON so I hope that makes at least enough sense so you get what I mean although it's most likely not perfect.

**Comment by JeffaloBob** [comment]
heres a better mockup for my dynamic amount of strings / objects idea
![image](https://user-images.githubusercontent.com/40470736/91872079-c050b700-ec77-11ea-84e5-3d30d683c72a.png)

**Comment by NoobTracker** [comment]
yeah exactly that's what I suggested still thanks for the mockup
I think that the + should be placed at the bottom because that's where you add items.

**Comment by NoobTracker** [comment]
But my suggestion also includes a way to set some default list items, in my example for the discuss and the suggestions button (but suggestions aren't enabled by default) so they just appear in the list. I think that a button manager is cooler then just a discuss button. So the "predifined" settings aren't a boolean input, they're just already in the list.

**Comment by NoobTracker** [comment]
Ah @JeffaloBob now i realised that your huge image is more then spam and an actual mockup of an array and not just a buncha booleans.

**Comment by NoobTracker** [comment]
Okay, could that work with the structure I explained?

**Comment by Explosion-Scratch** [comment]
Hi @NoobTracker I didn't mean to edit your post, I accidentally ticked one of the checkboxes. I undid it.

**Comment by NoobTracker** [comment]
> 
> 
> Hi @NoobTracker I didn't mean to edit your post, I accidentally ticked one of the checkboxes. I undid it.

Ah wow I didn't know you can do that now I also did it by accident :)

**Comment by NoobTracker** [comment]
Also: Radio buttons. You can only have a single one. My suggestion would be to at least add that to the array so you can use `radio `instead of `boolean`. That way you could do stuff like adding external players like forkphorus and such and select one that's used by default or something.
Also, having the option to create uneditable inputs for lists would be cool, you just add that somehow to the default list.

**Comment by WorldLanguages** [comment]
Added by latest commit - sorry, forgot to reference the issue.

**Comment by WorldLanguages** [comment]
For `color` setting type please someone open a new issue.

**Comment by NoobTracker** [comment]
@WorldLanguages Is there a `maxlength `for strings you can set in the JSON?

**Comment by NoobTracker** [comment]
> 
> 
> For `color` setting type please someone open a new issue.

And lists to I guess.

**Comment by NoobTracker** [comment]
Wouldn't it be cooler to select a maximum on your own? The discuss button's text should be shorter then 30 chars while links might need 200 chars.

**Comment by Explosion-Scratch** [comment]
I like the custom discuss input thing:
![image](https://user-images.githubusercontent.com/61319150/92807461-86bb3280-f380-11ea-8ede-b23664b2121f.png)
lol it's from SSSniperwolf on YT
