### ISSUE TITLE
Add removed blocks back

### ISSUE THREAD

**Issue by Littlehanger1234C2** [ScratchAddons/ScratchAddons#1420]
**Describe the new addon**
I WANT REMOVED SCRATCH 2.0 BLOCKS BACK

I want Thoose blocks come back like forever if <boolean>, Hide all sprites and more
**Link to the new addon**
https://en.scratch-wiki.info/wiki/List_of_Obsolete_Blocks

**Comment by apple502j** [comment]
These blocks still exist but do nothing.

**Comment by RedGuy12** [comment]
Some still work like <loud?>
But I think this is a duplicate
________________________________
