### ISSUE TITLE
"Update" Tooltip

### ISSUE THREAD

**Issue by Daniel4-Scratch** [ScratchAddons/ScratchAddons#1424]
![Update-scratchaddons-tooltip](https://user-images.githubusercontent.com/65277548/105919371-a29e4700-6089-11eb-9aa1-8c6cd35eb66c.gif)

I thought when a tool/modification gets updated recently it will show what's new in that tool/modification in a update toolotip.
Or
There also should be a update log on the tool's/modification's box.

This could allow users to pay more attention to the new feature in the tool/modification.

**Comment by TheColaber** [comment]
Related to #475. I think this is a pretty good idea! There would be many hardcoded values and also strings to translate every single update witch I guess is not ideal, but even so, very good idea.

**Comment by Daniel4-Scratch** [comment]
Thanks :), I'll look into the related topic.

**Comment by Hans5958** [comment]
Probably unrelated: If we make our general update/release notes like this, then I'm sure you don't need to put that tag in it.

https://www.github.com/ScratchAddons/ScratchAddons/tree/changelog-detailed/CHANGELOG.md

Also, those are called addons.

**Comment by Daniel4-Scratch** [comment]
I would find it nice to have the updates and update log in the actual extension. But that's my opinion <sub> (not anyone else's (: )

I'm not sure to keep this open or not, so I'll just leave it open for now

**Comment by WorldLanguages** [comment]
#3443 suggested adding a "new" tag to specific settings:
![image](https://user-images.githubusercontent.com/17484114/132361192-cca95e70-fff1-4062-83a5-31062d454eb7.png)
