### ISSUE TITLE
Clone counter displays a negitive number

### ISSUE THREAD

**Issue by CuriousG2** [ScratchAddons/ScratchAddons#1426]
**Describe the bug**

When you delete a sprite, then go into small stage mode then out of small stage mode, the clone counter decreases by one. This is exactly the same as #769, but it happens after you go in then out of small stage mode. This can also lead to negative numbers in the clone counter.

**To Reproduce**

1. Go to the project editor
2. Delete a sprite
3. Go into small stage mode
4. Go out of small stage mode
5. See error

**Expected behavior**

The clone counter should not show negative numbers

**Device (please complete the following information):**

- OS: [Windows 10]
- Browser [Firefox]
- Version [85.0]

**Additional context**

Closely Related to #769

**Comment by TheColaber** [comment]
This is a scratch bug, not scratch addons. Surely there is something at least we could do to fix this. But either way, a fix should be done in the LLK repo.

**Comment by mxmou** [comment]
> This is a scratch bug, not scratch addons. Surely there is something at least we could do to fix this. But either way, a fix should be done in the LLK repo.

The Scratch bug is that the count is negative. This bug report is about the addon showing negative numbers.

**Comment by WorldLanguages** [comment]
cc @jeffalo

**Comment by TheColaber** [comment]
> > This is a scratch bug, not scratch addons. Surely there is something at least we could do to fix this. But either way, a fix should be done in the LLK repo.
> 
> The Scratch bug is that the count is negative. This bug report is about the addon showing negative numbers.

Nope... it is a scratch bug...

https://user-images.githubusercontent.com/72760579/106008485-54874480-6085-11eb-8deb-dede302a5545.mp4

**Comment by WorldLanguages** [comment]
@TheColaber Don't get confused, this is the bug:
> This can also lead to negative numbers in the clone counter.

The fact Scratch decreases clone counts like this is not something we can easily fix, but we can fix the former. I thought we fixed this already, tho?

**Comment by TheColaber** [comment]
> @TheColaber Don't get confused, this is the bug:
> 
> > This can also lead to negative numbers in the clone counter.
> 
> The fact Scratch decreases clone counts like this is not something we can easily fix, but we can fix the former. I thought we fixed this already, tho?

No, we fixed it to not go to negative numbers, but it still decreases when you remove sprites.

**Comment by TheColaber** [comment]
I think it's part of the fact that scratch counts sprites as clones

**Comment by WorldLanguages** [comment]
@CuriousG2 Can you confirm if you've actually seen the counter go negative? The fact it goes down incorrectly is a Scratch bug, the only bug we could fix is that, but it looks like we already did?

**Comment by TheColaber** [comment]
> @CuriousG2 Can you confirm if you've actually seen the counter go negative? The fact it goes down incorrectly is a Scratch bug, the only bug we could fix is that, but it looks like we already did?

I can confirm that scratch's VM thinks it's negative, but the code hides it if the value is less than 1.

**Comment by CuriousG2** [comment]
> 
> 
> @CuriousG2 Can you confirm if you've actually seen the counter go negative? The fact it goes down incorrectly is a Scratch bug, the only bug we could fix is that, but it looks like we already did?

For some reason the code that hides the clone counter when it is negative does not hide it after you go in then out of small stage mode. It looks like this: ![image](https://user-images.githubusercontent.com/76401850/106023201-711e7f00-607b-11eb-81cc-4f6980bae449.png)

**Comment by WorldLanguages** [comment]
Ok then that's a bug
