### ISSUE TITLE
Picture of blocks in the editor with transparent BG

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#1428]
> An idea for the scratch addons could be one that can take a picture of the blocks in the editor and have a transparent background for tutorials instead of taking a screenshot and having it be just a square. By square I mean the script and the white background

Resources: 
https://scratchblocks.github.io/
https://chrome.google.com/webstore/detail/scratchblocks2svg/gaflafhcomnkjgdpkklblnjoeeegeidn/ (broken)
scratch editor: the blocks are svgs after all

**Comment by mxmou** [comment]
Resolved by #2087
