### ISSUE TITLE
cat block

### ISSUE THREAD

**Issue by jeffalo** [ScratchAddons/ScratchAddons#143]
one word:
cat blocks

**Comment by JeffaloBob** [comment]
wait maybe that was two words

**Comment by NoobTracker** [comment]
> 
> 
> wait maybe that was two words
three words:
a word counter addon

**Comment by NoobTracker** [comment]
Okay, enough sarcasm, your addon adds those cat blocks? That could be funny if that option is only there on the 4.1.

**Comment by JeffaloBob** [comment]
no i haven't made an add-on, I'm just suggesting one

**Comment by NoobTracker** [comment]
Ah okay fine. Still, could be a funny easter egg.

**Comment by NoobTracker** [comment]
I think you should have marked this as a feature request.

**Comment by NoobTracker** [comment]
@GrahamSH-LLK why did you close this?

**Comment by GrahamSH-LLK** [comment]
Because there isn't an actual clear suggestion. It's just a bunch of back-and-forth. If you really want this implemented, make a new issue with a clear suggestion, and make a PR.

**Comment by Hans5958** [comment]
> Because there isn't an actual clear suggestion. It's just a bunch of back-and-forth.

I'm not sure a discussion constitute as a reason to close this issue...
