### ISSUE TITLE
editor-devtools: update popup contents, advertise Scratch Addons if on extension

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1435]
On v1.9.0 we'll also release the [Scratch 3 Developer Tools extension](https://github.com/ScratchAddons/DevtoolsExtension) based on the addon. By then, it would be nice to update the help dialog to properly list all functions of the addon/extension.
I also believe we should add some banner that gets users from the extension aware of Scratch Addons' existence - the devtools extension still has more users than the Scratch Addons extension, even tho it has less features. Editor addons would be useful for these users, if they don't know about them.
**ADDED NOTE:** make sure to update the help docs on the outdated "show senders/receivers" functionality

**Comment by TheColaber** [comment]
On a side note: Should we be the ones writing the new features and updates? Or should we let griffpatch do this?

**Comment by WorldLanguages** [comment]
¯\_(ツ)_/¯
