### ISSUE TITLE
Scratch addons thinks ... is a link

### ISSUE THREAD

**Issue by randomscratcher** [ScratchAddons/ScratchAddons#1438]
**Describe the bug**

Scratch addons thinks ... is a link

**To Reproduce**

1. Turn on "More Links" in scratch addons.
2. Go to comments
3. Type something like " ok... "
4. Press enter/send
5. Boom, scratch addons thinks it's a link

**Expected behavior**

Something like " ok... " shouldn't be seen as a link

**Screenshots**

![image](https://user-images.githubusercontent.com/78104968/106039199-73de9b80-609e-11eb-8497-e0175f436f1e.png)

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Microsoft Edge (Chromium? Not sure if I need to say that.)
- Version: 88.0.750.50

**Additional context**

N/A

**Comment by TheColaber** [comment]
Hey this issue is known and will be fixed in the next update of Scratch Addons. Thanks for reporting!
