### ISSUE TITLE
Blank Settings page

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#1441]
**Describe the bug**

I open the popup and I only see the header that says "Scratch Addons", the extension icon, the version number, and a link to the settings page. I don't see the tabs or any tab content.

I click on the gear to get to the settings page and I just see a blank screen. Inspect element shows me that `<body>` has `style="display: none;"` on it. Removing the attribute manually brings back the regular settings page minus the addons list. 

**To Reproduce**

This might just be me...let me know if you are getting this too.

Error appears on the popup and on the settings page.

**Expected behavior**

... isn't it self-explanatory? For them to show!

**Device (please complete the following information):**

- OS: windows 10
- Browser: chrome
- Version: The 1.9.0 on this repo, the not released version

**Comment by YOYITsM3M8** [comment]
> Version: The 1.9.0 on this repo, the not released version

it means what version of your browser

**Comment by RedGuy12** [comment]
>  it means what version of your browser

The newest one
________________________________

**Comment by TheColaber** [comment]
This is not happening to me so... I would think the only reason is that you edited it? Try using it from the web store.

**Comment by RedGuy12** [comment]
Hmm... I'll run `git pull` again...
________________________________

**Comment by RedGuy12** [comment]
i jsut reloded it and it worked...

but I had already tried that multiple times...

**Comment by WorldLanguages** [comment]
If you have experienced this it's likely because of https://github.com/ScratchAddons/ScratchAddons/blob/master/background/handle-settings-page.js#L18, the ready event might never fire or might take a while to. Anything that would help us debug it should be in the background page of the extension
