### ISSUE TITLE
Random Things Considered Link

### ISSUE THREAD

**Issue by anoymousgamerhacker** [ScratchAddons/ScratchAddons#1449]
So I found an addon that turns links out of scratch.mit.edu into hyperlinks and I turned it on because I hate having to select and click "go to _____" and it worked! But the problem is that some random letters and words are considered links and it is starting to annoy me. Please fix this problem! Thanks for understanding!

OS:  Windows 10 (Sometimes I use Chrome OS and it has that issue)
Browser:  Chrome (Edge on Windows, but since you can get chrome extensions on edge, that's what I do)
Scratch Name: [anoymousgamerhacker](https://scratch.mit.edu/users/anoymousgamerhacker/)

**Comment by anoymousgamerhacker** [comment]
Also forgot to mention when you reply, please tell me with [Scratch](scratch.mit.edu) that you replied. Thanks!

**Comment by TheColaber** [comment]
This is because our last code for that addon made everything with "." into URLs. This has been fixed on the master and will be live in the next update.

**Comment by anoymousgamerhacker** [comment]
Why did @TheColaber just close this?

**Comment by TheColaber** [comment]
> Why did @TheColaber just close this?

Read my post above.

**Comment by anoymousgamerhacker** [comment]
Where? I can't see it for some reason.

**Comment by TheColaber** [comment]
> Where? I can't see it for some reason.

> This is because our last code for that addon made everything with "." into URLs. This has been fixed on the master and will be live in the next update.

**Comment by anoymousgamerhacker** [comment]
OK. Weird glitch

**Comment by anoymousgamerhacker** [comment]
With github
