### ISSUE TITLE
Hide the stage/sprites view

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#1453]
**Describe the new addon**

By clicking a button located at the right of the editor area, the element with class `gui_stage-and-target-wrapper_69KBf` would glide out of view.
When combined with the auto-hide block palette addon, there would be a HUGE amount of space:

![image](https://user-images.githubusercontent.com/43426138/106226423-c73f0f80-61ac-11eb-9db7-b940aeecc850.png)

**Comment by RedGuy12** [comment]
Maybe this could go in the auto house block palate addon
________________________________

**Comment by mxmou** [comment]
> Maybe this could go in the auto hide block palate addon

I don't think so, this would probably have a different UI than auto-hide block palette.

**Comment by stefanofederici** [comment]
> Maybe this could go in the auto hide block palate addon
> […](#)

I certainly agree that this MUST go into the auto-hide block palette, at least the part that enlarges the script area. Currently I don't see any usage for the auto-hide block palette addon, as I don't see as hiding the palette is a benefit. The only real benefit is  -at least to me- if this enlarges the script area. So, I vote a great yes.
