### ISSUE TITLE
"Auto-hide block palette" makes things disappear randomly

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#1454]
**To Reproduce**

1. Enable the "Auto-hide block palette" extension and set it to Hover mode.
2. In the project editor, go to the Code tab and lock the palette.
3. Open the Costumes tab. (The Sounds tab seems to be unaffected.)
4. Go back to the Code tab. The lock button is completely gone, but it's still in effect. There's no way to make it reappear.

ALSO

2. In the project editor, go to the Code tab and ensure that the palette is UNLOCKED.
3. Open the Costumes tab (the Sounds tab is unaffected) and quickly switch back to the Code tab.
4. Once the mouse leaves the block palette area, the palette completely disappears. The only way to get it back is by opening the Costumes or Sounds tab and switching back.

**Expected behavior**

Obviously, the above bugs shouldn't happen.

**Device:**

- OS: Windows
- Browser: Firefox 84.0.2
- Version: v.1.8.0

**Comment by TheColaber** [comment]
Fixed on master
