### ISSUE TITLE
Add More Replaceable Dropdowns

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#1455]
**Use Variables or Pass Parameters to Modify Dropdowns**

Many of you might have noticed that the switch costume to block has a round dropdown, which means you can pass variables, parameters or even strings through them. Why can't we make all dropdowns like this? Such as variable names go to sprite blocks and especially **when I receive [message1] blocks** because I am able to pass strings on broadcast (message1) blocks!

**Comment by apple502j** [comment]
Sorry, argument hacking is no more. Please use Scratch 2.0.

**Comment by areeq0325** [comment]
2.0 is Flash based, and Flash's EOL has passed.

**Comment by mxmou** [comment]
> 2.0 is Flash based, and Flash's EOL has passed.

The offline editor still works, and Scratch 3.0 doesn't have this feature.

**Comment by samuraininja360** [comment]
Too bad
