### ISSUE TITLE
Avoid flash of unstyled content/flash of default theme

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#1456]
Compared with a lot of extension that I know, Scratch Addons has a problem of having the flash of the unstyled content. This phenomenon is described as "an instance where a web page appears briefly with the browser's default styles prior to loading an external CSS stylesheet, due to the web browser engine rendering the page before all information is retrieved." This problem is present for every page and popup on Scratch Addons. 

The problem exists in both themes, due to the problem is how the styling is handled. This problem is magnified on the light theme, due to the browser need to load more stylesheets compared to the dark theme.

Firstly, look at how the styles of the Scratch Addons popup loads. You can see the theme shift, the font change, and the scrollbar style change. It's not satisfying, isn't it?

https://user-images.githubusercontent.com/11584103/106239189-c2be3980-6234-11eb-8595-cb36eeb8c026.mp4

Compare it with how the styles of the SessionBox popup loads. It hides the content, and then show it when all the fonts and style is ready.

https://user-images.githubusercontent.com/11584103/106239616-8212f000-6235-11eb-8510-5699823415f9.mp4

For the web pages, here's the settings page.

https://user-images.githubusercontent.com/11584103/106240642-35301900-6237-11eb-8380-2825688f53fb.mp4

Compare it to the uBlock Origin dashboard. Most of the styles are already loaded before the content comes on

https://user-images.githubusercontent.com/11584103/106240985-d28b4d00-6237-11eb-94cc-bc788e8610e7.mp4

One way to solve this is to hide the content until all the style loads, then it's just a simple JS to show it (whichever the method). This is what I done on the Scratch Addons website. You can also make the popup small (by not defining the size perhaps?) if you wish.

**Comment by mxmou** [comment]
The popup scrollbar appears briefly in Firefox (but not in Chrome) because of the fix for #600.

The light mode stylesheet is loaded from JavaScript, so maybe setting `color-scheme` and using media queries could solve this?

**Comment by WorldLanguages** [comment]
Two important differences between the 2 extensions you mentioned:
1. Scratch Addons' popup is different in a way to most popups, because it always has an iframe inside it taking not all, but most of the space. This is kinda painful because it can easily break with different screen resolutions and browser zoom levels. The main problem is that popup windows have a maximum height in *screen pixels*, and zoom levels change how many screen pixels a CSS pixel is, sometimes causing the popup window to overflow. To this day I have no idea how mxmou solved this double scrollbar issue. One of the side effects appears to be a scrollbar that appears for a second in Firefox, then goes out.
2. Ublock Origin's settings page is likely "hardcoded" - or if it isn't, it has to load way less data than ours. Doesn't explain flash of unstyled content, but the slowness.

**Comment by Hans5958** [comment]
None of the examples I used is hardcoded. For reference here's SessionBox's...

```html
<!DOCTYPE html>
<html><head><link href="view.css" rel="stylesheet"></head>
<head>
    <meta charset="UTF-8">
    <title>SessionBox</title>
    <link rel="stylesheet" type="text/css" href="view.css">
    <style>
        body {
            width: 350px;
            height: 550px;
            overflow: hidden !important;
            padding: 0; margin: 0;
        }
    </style>
<body>
<script type="text/javascript" src="views.js"></script></body>
</html>
```

...and here's uBlock Origin.

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
<title data-i18n="dashboardName"></title>
<link href="css/themes/default.css" rel="stylesheet" type="text/css">
<link href="css/common.css" rel="stylesheet" type="text/css">
<link href="css/dashboard.css" rel="stylesheet" type="text/css">
<link rel="shortcut icon" type="image/png" href="img/icon_16.png"/>
</head>

<body>
<div id="dashboard-nav">
    <span class="logo"><img data-i18n-title="extName" src="img/ublock.svg"></span><!--
 --><span class="tabButton" data-pane="settings.html" data-i18n="settingsPageName"></span><!--
 --><span class="tabButton" data-pane="3p-filters.html" data-i18n="3pPageName"></span><!--
 --><span class="tabButton" data-pane="1p-filters.html" data-i18n="1pPageName"></span><!--
 --><span class="tabButton" data-pane="dyna-rules.html" data-i18n="rulesPageName"></span><!--
 --><span class="tabButton" data-pane="whitelist.html" data-i18n="whitelistPageName"></span><!--
 --><span class="tabButton" data-pane="shortcuts.html" data-i18n="shortcutsPageName"></span><!--
 --><span class="tabButton" data-pane="about.html" data-i18n="aboutPageName"></span>
</div>
<div id="unsavedWarning">
    <div>
        <span data-i18n="dashboardUnsavedWarning"></span>&emsp;
        <button data-i18n="dashboardUnsavedWarningStay"></button>&emsp;
        <button data-i18n="dashboardUnsavedWarningIgnore"></button>
    </div>
    <div></div>
</div>

<iframe id="iframe" src=""></iframe>

<script src="js/vapi.js"></script>
<script src="js/vapi-common.js"></script>
<script src="js/vapi-client.js"></script>
<script src="js/udom.js"></script>
<script src="js/i18n.js"></script>
<script src="js/dashboard.js"></script>

</body>
</html>
```

Also, it does not matter if your computer runs so fast that it is negligible or if the content so large that the content that it will somehow affect the loading times of the styles. The only thing that matters is the stylesheets, and as long as the loading of the stylesheets is not handled correctly (which means the unstyled content is shown, even it's not done loading), the FOUC is going to be there, waiting to annoy people. It's not rocket science, it's logic.

Heck, I even tested this on BrowserStack and the FOUC is still there.

**Comment by TheColaber** [comment]
Don't know about you, but I only get a flash when opening the settings page because of all the transitions and a short blink.


https://user-images.githubusercontent.com/72760579/107902078-6422dc00-6f13-11eb-9191-9fa907befafc.mp4

**Comment by WorldLanguages** [comment]
@TheColaber Try emulating a slower CPU, through chrome devtools or spin up a VM that can only use one core of your CPU

**Comment by Hans5958** [comment]
> Don't know about you, but I only get a flash when opening the settings page because of all the transitions and a short blink.
> 2021-02-14.22-23-28.mp4

That's still a FOUC, and is preventable.

**Comment by WorldLanguages** [comment]
This issue is old, a new one should be opened if this is still a problem. From my personal experience, flash of unstyled content is way better now.
