### ISSUE TITLE
"Auto-hide block palette" also hides dropdowns

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#1466]
**Describe the bug**

When the block palette is hidden, dropdowns are not able to appear.

**To Reproduce**

1. Enable the "Auto-hide block palette" extension
2. Open any project
3. Drag in a set variable block (or any block with dropdowns)
4. Ensure that the palette is hidden
5. Attempt to open the dropdown

**Expected behavior**

The dropdown appears when the block palette is hidden

**Screenshots**

Normal behavior:
![image](https://user-images.githubusercontent.com/43426138/106369466-481a1a80-6317-11eb-9198-fc3a71b76324.png)

Behavior when palette is hidden:
![image](https://user-images.githubusercontent.com/43426138/106369470-58ca9080-6317-11eb-8156-53dacbdd62ad.png)

**Device:**

- OS: Windows
- Browser: Firefox 84.0.2
- Version: 1.8.1

**Comment by WorldLanguages** [comment]
cc @TheColaber

**Comment by lisa-wolfgang** [comment]
Note that this is the release version, not the master branch.

**Comment by WorldLanguages** [comment]
@lisa-wolfgang AFAIK v1.8.1 release has all of this addon's bug fixes we now have on master.

**Comment by TheColaber** [comment]
This was fixed afaik... I never had this bug
