### ISSUE TITLE
Block autohide on category click makes it hard to select categories

### ISSUE THREAD

**Issue by areeq0325** [ScratchAddons/ScratchAddons#1476]
**Describe the bug**
If you have block autohide on category click, you need 2 clicks to select a new category

**To Reproduce**
Turn on block autohide and set to category click

**Expected behavior**
When clicking the same category that you already have open, the pane should close

**Screenshots**
https://user-images.githubusercontent.com/69761212/106403965-fe0c6400-63fe-11eb-8616-1f6cdf0c5801.mp4

**Device (please complete the following information):**
Windows 10 20h2, Edge 88

**Additional context**
I was not sure whether to mark as bug or feature, but I chose bug. Might actually be a feature.

**Comment by TheColaber** [comment]
This issue was fixed.
