### ISSUE TITLE
Preview when editing a post unaffected by dark mode

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#1480]
**Describe the bug**

When clicking the preview icon while editing a forum post, the preview is not affected by dark mode.

**To Reproduce**

1. Enable website dark mode
2. Click "Edit" below your post on the forums
3. Click the preview button
4. The preview has white background.

**Expected behavior**

It would be dark. The matches for `experimental_forums_preview.js` should include `https://scratch.mit.edu/post/*/edit/`.

**Comment by TheColaber** [comment]
Dupe of #898?

**Comment by apple502j** [comment]
Duplicate of #898

**Comment by TheColaber** [comment]
It's an about:blank iframe: 
![image](https://user-images.githubusercontent.com/72760579/106472364-98f15680-6470-11eb-9d4e-99ddabc96cb8.png)

**Comment by mxmou** [comment]
Not a duplicate, the addon currently uses an userscript to work around #898. This is just a missing match pattern.

**Comment by TheColaber** [comment]
there is no pattern to match, it's an about:blank iframe

**Comment by TheColaber** [comment]
Oh I think I see... well then.
