### ISSUE TITLE
Project screen recorder makes outlines around sprites

### ISSUE THREAD

**Issue by CuriousG2** [ScratchAddons/ScratchAddons#1482]
**Describe the bug**

When you enable project screen recorder (it does not have to be recording the screen) all the images are surrounded by an outline. Happens only on Firefox.

**To Reproduce**

1. Enable Project screen recorder
2. Go to a project like appel
3. Click on the green flag

**Expected behavior**

There should not be outlines around the images

**Screenshots**

![Screenshot_2021-02-01 Scratch - Appel v1 4(1)](https://user-images.githubusercontent.com/76401850/106489675-e0281900-6469-11eb-880b-b2be6e0a9359.png)

**Device (please complete the following information):**

- OS: [Windows 10 20H2]
- Browser [Firefox]
- Version [85.0]

**Additional context**

This is really annoying.

**Comment by TheColaber** [comment]
Do you have the a11y addon enabled? If so try disabling for a sec.

**Comment by CuriousG2** [comment]
I didn't notice that I also had Project screen reader on with tab navigation on. I think it is supposed to do that.
