### ISSUE TITLE
Live animations popup (when a sprite has more than 1 costume)

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#1483]
> I have some ideas for Scratch Addons- ... Live animations popup when a sprite has more than 1 costume

**Comment by WorldLanguages** [comment]
Uhh what?

**Comment by mxmou** [comment]
> a costume has more than 1 costume

?

**Comment by TheColaber** [comment]
Sorry, I think they meant when a sprite has more than one costume.

**Comment by mxmou** [comment]
So this would show all costumes of a sprite as an animation?

**Comment by TheColaber** [comment]
> So this would show all costumes of a sprite as an animation?

I'm guessing they want to see their costumes as a gif that repeats... maybe then you could download it?
