### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#1499]
@easrng made a cool new logo, and I wanted to see if it could become the real logo.
![image](https://user-images.githubusercontent.com/64214252/106910283-10242600-66cf-11eb-8045-9b8e17671b2c.png)
![image](https://user-images.githubusercontent.com/64214252/106910297-14e8da00-66cf-11eb-8234-fb694fe7fbb7.png)

**Comment by mxmou** [comment]
I think it looks better than the current one, but it might be better without the shadow.

**Comment by RedGuy12** [comment]
How is it different
________________________________

**Comment by Secret-chest** [comment]
Don't like that the lego is rounded

**Comment by WorldLanguages** [comment]
I'd use that logo for sure... if we were a Mac OS app :P

**Comment by easrng** [comment]
> I'd use that logo for sure... if we were a Mac OS app :P

But this is a material-styled icon?

**Comment by devxan** [comment]
Here is the current logo but with amazing effects, I think we should add this to the website with a gradient that looks cool.
![Scratch Addons Server Logo](https://user-images.githubusercontent.com/57809064/107077228-68c3f380-67a1-11eb-9244-7df62c411b73.png)

**Comment by RedGuy12** [comment]
Too pale orange


What's wrong with our current logo?
________________________________

**Comment by WorldLanguages** [comment]
Keep in mind it's unlikely I'll be OK changing the logo, but I can't stop you from trying ¯\_(ツ)_/¯

**Comment by devxan** [comment]
Just an idea (^///^)

**Comment by TheColaber** [comment]
I see that this will probably never be implemented but if yall still want to post new logos here, sure go ahead.
