### ISSUE TITLE
Some addons don't work

### ISSUE THREAD

**Issue by Marc92020** [ScratchAddons/ScratchAddons#1508]
**Describe the bug**
Addons are turned off in different parts of Scratch. Mainly My Stuff

**To Reproduce**
There are no ways. Just go to different pages.

**Expected behavior**
Addons Enabled don't work

**Screenshots**
No screenshots but I have addons on and they turn off

**Device (please complete the following information):**

- OS: Chrome OS
- Browser Chrome
- Version 88

**Additional context**
I only have 1 Scratch Addons, so this is not caused by another problem I had

**Comment by WorldLanguages** [comment]
Sorry this is not very helpful... Can you try to create a new Chrome user, install Scratch Addons there and try to reproduce the issue with more precise steps

**Comment by Marc92020** [comment]
> Sorry this is not very helpful...

Yeah I need more.

> Can you create a new Chrome user, install Scratch Addons there and try to reproduce the issue with more precise steps

I don't really create new Chrome accounts but OK

**Comment by Marc92020** [comment]
Or maybe I'll just test it on my brothers computer.

**Comment by TheColaber** [comment]
@Marc92020 Updates, please.
