### ISSUE TITLE
[Feature] Way to pass settings value to userstyle

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#151]
**Is your feature request related to a problem? Please describe.**

You can't pass a settings value, for example a color, to a userstyle.
**Describe the solution you'd like**
The userstyle is parsed for settings ids, and any found are changed to the value of the setting.

**Comment by WorldLanguages** [comment]
Yeah, color settings should be accessible as CSS variables!
And maybe we could provide some hacky way to read boolean settings from @media queries as well.

**Comment by mxmou** [comment]
> And maybe we could provide some hacky way to read boolean settings from @media queries as well.

Maybe, but isn't it better to have a separate CSS files that is only loaded when the setting is enabled?

**Comment by WorldLanguages** [comment]
@mxmou Nothing stops us from having both options for userstyles (if I find a hacky way to have custom media tags)

**Comment by GrahamSH-LLK** [comment]
This should be pretty easy. Anyone want to tackle it?

**Comment by WorldLanguages** [comment]
> This should be pretty easy

Kind of... At the moment, global state is obtained after injecting the styles, that wouldn't work. I'll work on this soon (tm)

**Comment by WorldLanguages** [comment]
Together with this I'd like to make it so all the CSS doesn't end up in the data-addons HTML attribute of the "scratch-addons" <template>, that's kinda ugly
