### ISSUE TITLE
Side Navbar Anchors for Project Carousels

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#1510]
**Quick Project Carousel Navigation**
A side navbar or anchor chain on the left or right hand side of the page would greatly help users of scratchaddons to jump between featured projects, curated, top loved and remixed carousels. This would be a great addon for the Scratch Website. I would suggest `scroll-behavior:smooth;` in the CSS and probably adding an id for these carousels if they don't already have  ids. I could possibly code this in less than 10 minutes.

**Comment by samuraininja360** [comment]
Should I create a file called anchor.css and if needed another one called anchor.js

**Comment by RedGuy12** [comment]
Problem: how would you know what order to go in? Everything is randomly sorted except trending, featured projects, featured studios, and curated projects.
________________________________

**Comment by samuraininja360** [comment]
Its an anchor for carousels not individual projects!

**Comment by lisa-wolfgang** [comment]
This issue will probably be closed. The amount of scrolling required to navigate the front page is very minimal. https://github.com/ScratchAddons/ScratchAddons/issues/1758 will exist in the future for users who want to minimize the amount of carousels on the front page.
