### ISSUE TITLE
Add a collapse button in the editor sidebar for 'Auto-hide block palette' option

### ISSUE THREAD

**Issue by DroneBetter** [ScratchAddons/ScratchAddons#1514]
I want to use the additional space it creates where the palette would otherwise be, so toggle on hover doesn't work (because it makes it appear instead), and I use the category buttons to navigate to the blocks I want to insert, so toggle on category click doesn't work (because it means I have to double-click them instead).

A solution would be a third option, to have a collapse/uncollapse button above the category buttons, that separates this behaviour from them and (if ignored) makes collapsing entirely optional.

It could also be positioned below the categories, but it would then have an inconsistent location as extension libraries are added.

**Comment by WorldLanguages** [comment]
Have you tried out the new "category hover" mode available on prerelease? It should be coming to Scratch Addons stable in the following days for the v1.9.0 release.

**Comment by TheColaber** [comment]
I would also recommend category click. It has been revised.
