### ISSUE TITLE
Hide code/costumes/sounds tabs when block palette hidden, to keep the search bar on the left edge of the editor space

### ISSUE THREAD

**Issue by DroneBetter** [ScratchAddons/ScratchAddons#1516]
When the block palette is visible, the Developer tools find box is to the right of the tabs buttons, which almost line up with the palette, and going to a search result through its dropdown moves you so its top-right corner is right of the script's top-left corner. However, when the sidebar is hidden, much space to its left remains unused.

A solution would be to collapse these tab buttons with the block palette.

Alternatively, you could make the search box collapse when a result is selected, but that makes it more difficult when you want to find a specific script you're unsure of the name of. (This solution applies regardless of the palette-collapsing problem.)

This problem (of collapsing creating extra space which is poorly used) only applies if you use toggle on category click, not on hover.

**Comment by Samq64** [comment]
What would happen when the new columns addon is enabled?

**Comment by mxmou** [comment]
> When the block palette is visible, the Developer tools find box is to the right of the tabs buttons, which almost line up with the palette, and going to a search result through its dropdown moves you so its top-right corner is right of the script's top-left corner. However, when the sidebar is hidden, much space to its left remains unused.

I don't know how exactly the devtools positions the highlighted script, but it doesn't depend on the position of the dropdown, so hiding the tabs wouldn't solve this (and it would be really weird to have to open the block palette to access the tabs).
