### ISSUE TITLE
 Auto-Hide the Palette breaks drop-down menus

### ISSUE THREAD

**Issue by SirJoshi** [ScratchAddons/ScratchAddons#1517]
**Describe the bug**

Enabling Auto-Hide the Palette causes the user (me) to be unable to open block drop-down menus

**To Reproduce**

1. Enable Auto-hide block palette
2. Attempt to open a drop down in the project
3. See error

**Expected behavior**

![expected](https://user-images.githubusercontent.com/45546025/107148241-cd08c380-6917-11eb-8294-8d780f09e29b.gif)

**What actually happens**

![pain](https://user-images.githubusercontent.com/45546025/107148258-ea3d9200-6917-11eb-865f-596e68fd8a8d.gif)

**Device (please complete the following information):**

- OS: Window 10 [1909]
- Browser: Firefox
- Version: 85

**Comment by TheColaber** [comment]
What version of ScratchAddons do you have?

**Comment by SirJoshi** [comment]
1.8.1

**Comment by TheColaber** [comment]
Should be fixed in 1.9.0.
