### ISSUE TITLE
Use chrome.action instead of chrome.pageAction in JS and manifest.json

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1533]
Manifest v3 will only support `chrome.action` and the `action` property in manifest.json
Source: https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#action-api-unification

**Comment by GrahamSH-LLK** [comment]
For the manifest:
```diff
+  "action": {
-   "browser_action": {
    "default_icon": "images/icon.png",
    "default_popup": "webpages/popup/index.html",
    "default_title": "Scratch Addons"
  },
```

**Comment by GrahamSH-LLK** [comment]
And the API should be as easy as replacing ``browserAction`` with ``action``!

**Comment by WorldLanguages** [comment]
Yes?

**Comment by TheColaber** [comment]
Yes this is obvious. This is the least of our worries. But if we want to implement this, we would also have to implement all the other breaking changes at the same time to make sure the extension still works.

**Comment by GrahamSH-LLK** [comment]
> Yes this is obvious. This is the least of our worries. But if we want to implement this, we would also have to implement all the other breaking changes at the same time to make sure the extension still works.

Believe it or not, I understand that. If Firefox supported this, I would have PR'd, so I put it here. In the future, scathing comments _aren't_ necessary.

**Comment by TheColaber** [comment]
> Believe it or not, I understand that. If Firefox supported this, I would have PR'd, so I put it here. In the future, scathing comments _aren't_ necessary.

Actually, you don't understand. Even if FF supported it, you still couldn't PR without changing to manifest version to 3... which would break everything else.

**Comment by GrahamSH-LLK** [comment]
> > Believe it or not, I understand that. If Firefox supported this, I would have PR'd, so I put it here. In the future, scathing comments _aren't_ necessary.
> 
> Actually, you don't understand. Even if FF supported it, you still couldn't PR without changing to manifest version to 3... which would break everything else.

Actually, you're wrong. Next time, do your research. Looking at the chrome docs, it says
>In order to aid with the migration process, the Action API can be used in MV2 beginning with Chrome 88.

**Comment by WorldLanguages** [comment]
@GrahamSH-LLK Even tho we only "officially" support the most recent browser versions, I still decided to consider this a breaking change, even tho part of it could technically be pollyfilled for manifest v2
