### ISSUE TITLE
Manifest v3: stop using blocking webRequest

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1535]
We currently use blocking webRequest for calls to `addon.fetch`. This function is less used than I thought it would be, and AFAIK the only situation where `addon.fetch` can be used but not a call to native `fetch()` with the correct headers is calls to the Scratch 2.0 API that require a `Referer` header, which is not present in calls from the background page, like clearing the message count.
We should recheck uses of `addon.fetch` and consider alternatives. Hopefully, by the time manifest v3 is mandatory, Scratch added a Scratch 3.0 REST API method to clear messages, that does not require us to add a fake `Referer` header. Otherwise we might need to use the new `chrome.declarativeNetRequest` API, or open a new tab for a brief moment and execute JavaScript on it, then close it.

**Comment by RedGuy12** [comment]
lol there's only 2 uses
https://github.com/ScratchAddons/ScratchAddons/blob/cda419034cbe1e7662e38b292eb7a73895414bff/addons/studio-tools/mystuff.js#L11
https://github.com/ScratchAddons/ScratchAddons/blob/72b6f36b01e167d1ed8ae3389ebf0e6e1e0e4b00/addons/full-signature/happen.js#L16

**Comment by WorldLanguages** [comment]
@RedGuy12 Be aware some persistent scripts manually add the `X-ScratchAddons-Uses-Fetch` header (can't remember why but it was for a reason)

**Comment by WorldLanguages** [comment]
See https://github.com/WorldLanguages/ScratchAddons/tree/use-declarativenetrequest for a demo on using `declarativeNetRequest` instead of blocking web request. This is only for situations where Scratch expects a `Referer` header when sending a POST request to scratchr2 APIs, like clearing the message count from the background page/worker.
`addon.fetch` should now be considered deprecated, it's a better idea to require addon authors to manually add the required headers.

**Comment by WorldLanguages** [comment]
PR #1681 adds (as a comment) code to migrate to `chrome.declarativeNetRequest` and stop using blocking webRequest. No other changes should be necessary (other than changing the permissions array in manifest.json)

**Comment by WorldLanguages** [comment]
Actually, we're still using blocking webRequest on background/handle-cookie.js, which fixes logout when the user loads comments for non-existent users, unshared projects etc (e.g. https://scratch.mit.edu/site-api/comments/user/kaj/), a bug caused by Scratch. IIRC we fixed it ourselves because Scratch Messaging would fetch those when loading comments and log the user out. If we use JSON API for all comments we would be able to remove that

**Comment by WorldLanguages** [comment]
`chrome.declarativeNetRequest` rules that modify headers (`action.type: modifyHeaders`) are available in Chrome since Chrome 86, released October 2020.
We could drop the `webRequestBlocking` permission for Chrome (while staying in manifest v2) as early as October 2021 by changing the minimum supported Chrome version to 86+ (currently 80+)
If Scratch adds a JSON API for user comments before then, we can remove background/handle-cookie.js and our only declarativeNetRequest rule would be the one for `?sareferer`.
Firefox would continue to use `webRequestBlocking`.

**Comment by WorldLanguages** [comment]
Plan to drop this permission in Chrome for v1.18.0

What to do with Scratch Notifier's "mark as read" button TBD
We probably will add `declarativeNetRequest` as an optional permission for that usecase
For existing users, we can ask for the permission when the user clicks the notification
We can also just use an iframe in the background for this until we move to service workers

**Comment by WorldLanguages** [comment]
Backlogging because of https://groups.google.com/a/chromium.org/g/chromium-extensions/c/WDHR0urVV1c/m/-AGvFsinCAAJ

**Comment by apple502j** [comment]
declarativeNetRequestWithHostAccess will be supported in Chrome 96-ish?

**Comment by WorldLanguages** [comment]
Closing in favor of #3615
