### ISSUE TITLE
Do not use a persistent background page

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1536]
I honestly forgot why we're using a persistent background page. In order to make the transition to manifest v3 service workers easier, we should first migrate to a non-persistent background page, and check what breaks.

EDIT: we use non-persistent background page because of blocking webRequest (#1535) `The only occasion to keep a background script persistently active is if the extension uses chrome.webRequest API to block or modify network requests. The webRequest API is incompatible with non-persistent background pages.` (source: https://developer.chrome.com/docs/extensions/mv2/background_pages/#manifest)

Also, I believe we may be using event callbacks in APIs like `chrome.contextMenus` that are not supported by non-persistent background pages, we should make sure all these work before migrating and pushing to stable.

**Comment by WorldLanguages** [comment]
Manifest v2 does not let us use `webRequest` (blocking or not) with a non-persistent background page. Manifest v3 does let us do this, however (there's no concept such as persistent or not persistent in manifest v3 because it's a service worker). Hence, we cannot transition into a non-persistent background page.

**Comment by WorldLanguages** [comment]
Related: #1693

**Comment by DNin01** [comment]
Sounds like this was a won't-fix. Has anything changed?

Refer to https://developer.chrome.com/docs/extensions/mv2/background-migration for migration steps.

**Comment by WorldLanguages** [comment]
> Sounds like this was a won't-fix. Has anything changed?

I don't think so. I believe Chrome continues to require a persistent background page if the `webRequest` permission is requested in a Manifest V2 extension.
