### ISSUE TITLE
[New addon] more project info

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#154]
**Describe the new addon**

kinda like in the admin panel, display extra project information like how many sprites / scripts there are maybe even if the project is NFE

**Link to the new addon**

n/a

**Comment by NoobTracker** [comment]
Would be cool. I think that you kinda had problems because you told everyone to find out the NFE thing so I guess you know how. I'm currently not sure where that could be placed ... can you make a mockup?

**Comment by Explosion-Scratch** [comment]
Cool!

**Comment by Explosion-Scratch** [comment]
What about the NFE status?

**Comment by TheColaber** [comment]
I don't think that is possible to get....
________________________________

**Comment by Explosion-Scratch** [comment]
Okay.
