### ISSUE TITLE
Addons load in body tag

### ISSUE THREAD

**Issue by Touchcreator** [ScratchAddons/ScratchAddons#1542]
**Is your feature request related to a problem? Please describe.**

Add-ons load in body tab (I think)

**Describe the solution you'd like**

Load them in the had tag.

**Comment by Touchcreator** [comment]
Title is supposed to be: Addons load in body tag lol

**Comment by RedGuy12** [comment]
You can load javascript at the beginning of the body or after the page has loaded . Css is always at the beginning of t he body.
________________________________

**Comment by mxmou** [comment]
Userstyles are injected into the root element, before the body.

**Comment by WorldLanguages** [comment]
Addons aren't ran through the DOM but through dynamic `import()`
