### ISSUE TITLE
Popup box for direction partially covered when Stage to the left

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#1548]
**Describe the bug**

When the editor-stage-left addon is enabled, the popup box that allows to change the sprite direction is partially covered by the blocks categories palette

**To Reproduce**

1. Enable the editor-stage-left addon
2. In the Sprite Header Pane, click inside the direction box 
3. The popup box is not fully visible

**Expected behavior**

The popup box that allows to change the sprite direction should be over the categories pane, not below

**Screenshots**

![image](https://user-images.githubusercontent.com/2651868/107586530-64b02f80-6c00-11eb-9bcc-0de98d4d10a6.png)

**Device (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: 88

**Comment by WorldLanguages** [comment]
@mxmou Could you PR or tell us how to fix this properly, css king 👑 🙏
