### ISSUE TITLE
[Feature] analytics?

### ISSUE THREAD

**Issue by jeffalo** [ScratchAddons/ScratchAddons#155]
**Is your feature request related to a problem? Please describe.**

i want to know how many people are using my addon

**Describe the solution you'd like**

phone home anonymous data on which addons are enabled?

**Describe alternatives you've considered**

maybe something like GA

**Additional context**

this would allow us to see what's going on with users and then use the data to make a better experience

i don't know about the legalics of this though

**Comment by NoobTracker** [comment]
Well, a button you can press to enable sending anonymous data would be nice. But ... I dunno. We can just ask the people to give feedback.

**Comment by Hans5958** [comment]
I don't think we will need one, but I understand how you feel. If this somehow gets implemented, here's a simple idea from me, instead of just incrementing numbers:

### Getting data

- Extensions gets an ID number/hex
	- Extension checks if it has an ID number/hex
	- If it exists, use the ID. 
	- If not, generate a random hex ID
- Extension lists enabled addons
- Extension list OS information (optional)
- Extension sends POST request to the server
- Server receives POST request
- Server updates the data based on the request
	- Server checks if the ID is listed on the DB
	- If it exists, update the corresponding data
	- If not, create a new entry and put the data on it

### Querying data

It should be as simple as counting in each of the users. I think it is doable considering someone implemented the same somewhere.

**Comment by NoobTracker** [comment]
It should also report what exactly is enabled, like removing "ideas".

**Comment by Hans5958** [comment]
> 
> 
> It should also report what exactly is enabled, like removing "ideas".

I'd rather not make it to be that detailed, if we want to enable it by default

**Comment by NoobTracker** [comment]
> 
> 
> > It should also report what exactly is enabled, like removing "ideas".
> 
> I'd rather not to make it that detailed, just in case we want to enable it by default

I don't think that we should do it by default, or at least ask the user the first time they use the extension. 
And I think that it makes sense - when you see that everyone removes "ideas", then you can just turn that removing on by default.

**Comment by Hans5958** [comment]
> 
> 
> > > It should also report what exactly is enabled, like removing "ideas".
> > 
> > 
> > I'd rather not to make it that detailed, just in case we want to enable it by default
> 
> I don't think that we should do it by default, or at least ask the user the first time they use the extension.
> And I think that it makes sense - when you see that everyone removes "ideas", then you can just turn that removing on by default.

I'm still not sure if we can get into problems by having a very detailed analytics.

**Comment by NoobTracker** [comment]
@Hans5958 I don't think so. We don't log 99% of things you could log. Like your location and such.

**Comment by Hans5958** [comment]
Well, yeah, but there are some people who is going to be concerned. I don't know.

**Comment by NoobTracker** [comment]
Well we could also have a separate extension for removing "ideas" so I guess that's kinda not a huge problem.

**Comment by JeffaloBob** [comment]
doesn't scratch itself use Google analytics, their analytics are very detailed, but anonymous (mostly)

i think it's best to just send a list of which addons are enabled and leave it at that.

perhaps the server code should be open source too

**Comment by NoobTracker** [comment]
Making the server code open source isn't a bad idea.

Still, I think that the enabled options are also interesting to know and not really private information as long as we only log booleans and not text boxes and stuff.

**Comment by WorldLanguages** [comment]
I think that as long as the server code is open source, and information is public (and there's a way to opt out), we could do this

**Comment by WorldLanguages** [comment]
Rejected for now, per extension privacy policy. This could be moved to a discussion
