### ISSUE TITLE
Import scripts from the backpack to the location in the code they're dropped to, not to the origin

### ISSUE THREAD

**Issue by DroneBetter** [ScratchAddons/ScratchAddons#1559]
Scratch currently creates them at the top-left corner, which isn't very helpful when I drop them to the place I want them to be, I have to scroll there and drag them back, one screen-width at a time (which is multiple in large programs, even when zoomed out).

If it's difficult to put the top-left part of it where the mouse-pointer drops it, an alternative intermediate solution could be determining it with the same function that determines the hat-block goes when defining a new function (which goes to the top-left of the current screen position, not of the entire program).

**Comment by Falling10fruit** [comment]
Why is this closed?

**Comment by RedGuy12** [comment]
@Falling10fruit this isn't closed, we just closed the duplicate you made

**Comment by Falling10fruit** [comment]
Oh, okay

**Comment by Joeclinton1** [comment]
I also would like this addon to exist. If noone else does it I will do it.
