### ISSUE TITLE
[New addon] Sprite deletion confirmation

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#156]
**Describe the new addon**
Confirm when deleting sprite. Will require real redux.

**Comment by NoobTracker** [comment]
That sounds great! It would also solve the suggestion.

**Comment by apple502j** [comment]
Doesn't solve suggestion unless we can advertise the extension on Scratch, though.

**Comment by NoobTracker** [comment]
Well for us at least. Maybe, *maybe* the ST can look at the code and just insert it in the editor or we can make a PR or something.

**Comment by apple502j** [comment]
@NoobTracker I already did that, probably a year ago. Code will look very different so it's not just a copy-paste.

**Comment by NoobTracker** [comment]
mmm ....
