### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by Only-a-cat** [ScratchAddons/ScratchAddons#1566]
I try to post a thumbnail, but first he says "that it is very small" about many times. After a time it works, I don't know how it is. Then I'll look at the project, continue with a picture of a cat, it doesn't really change. And if I don't choose a thumb, he puts it for the cat. Please solve this!!

**To Reproduce**

I just change a thumbnail (or not)

**Device:**

**Comment by TheColaber** [comment]
This has been fixed and will be in the next version of ScratchAddons wheather that be 1.9.2 or 1.10.0. The problem was with scratch's thumbnail servers. All we can do is display a different message.
