### ISSUE TITLE
Option to choose default project player

### ISSUE THREAD

**Issue by FunctionalMetatable** [ScratchAddons/ScratchAddons#1574]
For laggy computers, people have to copy the project ID and go to a scratch mod, e.g TurboWarp.

There should be an option to change the default player from the scratch player to a faster scratch player/mod,  (e.g TurboWarp).

I added a bookmark that when you pressed it, it opens in TurboWarp and vice versa. It's not practical because we have to keep pressing the bookmark when we loaded in to the project page, creates lag though. (I sometimes use scratch on a laggy computer)

**Comment by RedGuy12** [comment]
PR already created for this.
________________________________

**Comment by RedGuy12** [comment]
See #1550

**Comment by TheColaber** [comment]
Duplicate of #588

**Comment by FunctionalMetatable** [comment]
> See #1550

Thanks!
