### ISSUE TITLE
Scratch AutoReply Extension

### ISSUE THREAD

**Issue by LankyBox01** [ScratchAddons/ScratchAddons#1588]
Hello, i am working on a new scratch extension called AutoReply. It is basically like QuickReply from the Forum Helpers website, but instead of going to the website, the template posts show up in your corner! Here's a small preview:
https://u.cubeupload.com/LankyBox01/01nOAi.png

Currently, i didn't publish my extension to the chrome extension store yet; you need to follow some instructions in order to add it to your browser, and i'm sharing this suggestion hoping that this could make accessing the extension easier.

**SOURCE CODE:**
https://docs.google.com/document/d/1JVQ_HrIZRgP7NMIKjmBIRselWdW9UR_80SmCvhkds4g/edit?usp=sharing

**Comment by RedGuy12** [comment]
why make it an extension? you can just put it in Scratch Addons (also there's a $5 fee for the web store)

I can't access the code, maybe put it on GH instead?
________________________________

**Comment by LankyBox01** [comment]
yeah i will
wait

**Comment by LankyBox01** [comment]
https://github.com/LankyBox01/AutoReply/tree/main
Here is the source code.

**Comment by LankyBox01** [comment]
Oh, it seems like the extension glitched. I'll try fixing it and then i'll re-publish the source code.

**Comment by LankyBox01** [comment]
[ZIPExtension.zip](https://github.com/ScratchAddons/ScratchAddons/files/5988296/ZIPExtension.zip)

**Comment by RedGuy12** [comment]
Why do you keep closing this? If you don't want to do it, keep it open and someone else will (aka me)
________________________________

**Comment by LankyBox01** [comment]
Sorry, i am still working on the extension

**Comment by RedGuy12** [comment]
You can still keep it open so people know it's happening
________________________________

**Comment by LankyBox01** [comment]
uh, wait.
Can you respond to this message
Just testing

**Comment by LankyBox01** [comment]
Oh ok
Is there any way we can chat privately

**Comment by LankyBox01** [comment]
why are you replying with reactions

**Comment by RedGuy12** [comment]
you already sent me an email...

**Comment by LankyBox01** [comment]
what email?

**Comment by LankyBox01** [comment]
jk
