### ISSUE TITLE
Implement popups

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#16]
Would allow us to port Griffpatch's messaging extension into the extension popup, and potentially let users customize what popup to use (or if we let them move between them, their order)

**Comment by pufflegamerz** [comment]
I just stumbled upon this project. Not sure if this is relevant, but my scripts at https://github.com/ScratchFormat/scratchmod may be helpful for this.

**Comment by WorldLanguages** [comment]
Hi @pufflegamerz nice to see you here. However this refers to browser extension popup - the page that appears when you click an extension icon.

**Comment by pufflegamerz** [comment]
Oh, I see. It may still be helpful if you don't already have a script for that.

**Comment by WorldLanguages** [comment]
We want to add the cloud data activity addon in v1.1 - a nice oportunity to implement addon popups for real. At the moment, scratch-messaging is a hardcoded iframe.

**Comment by TheColaber** [comment]
So this was added, right? Can we close this then?

**Comment by WorldLanguages** [comment]
No, it's still hardcoded

**Comment by WorldLanguages** [comment]
Moved to #773
