### ISSUE TITLE
Footer part missing if fixed footer

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#1600]
For the "fix footer" in "infinite scrolling" it doesn't show this part at the bottom.
![image](https://user-images.githubusercontent.com/72760579/108136876-d5d06680-7088-11eb-8b5d-384856c45d97.png)

*Note: This is because the bottom text is a different div than the footer.

**Comment by RedGuy12** [comment]
Whoo #1600!!!
________________________________
