### ISSUE TITLE
Semicolon with darkmode bug

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#1604]
![image](https://user-images.githubusercontent.com/72760579/108138444-fd74fe00-708b-11eb-9a24-ae0092a09191.png)

**Comment by RedGuy12** [comment]
What's the problem?
________________________________

**Comment by mxmou** [comment]
> What's the problem?

It has white background in dark mode.

**Comment by RedGuy12** [comment]
I made a pr for this a while back and it was rejected

#1293
#1294
#1297
________________________________
