### ISSUE TITLE
l10n.js not finding en-us causing error

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#1610]
cc @apple502j 
![image](https://user-images.githubusercontent.com/72760579/108151633-2950ad80-70a5-11eb-9dec-72926d2b2ddf.png)
It's trying to get en-us and not just en.

**Comment by apple502j** [comment]
Working as intended, not a bug.

**Comment by RedGuy12** [comment]
No, when the language is en, it tries to find en and en-us. But only en exists, so it creates errors. How can we make it not look for en?
________________________________

**Comment by WorldLanguages** [comment]
Duplicate of #814
