### ISSUE TITLE
Snap!'s keyboard editor addon

### ISSUE THREAD

**Issue by ErrorGamer2000** [ScratchAddons/ScratchAddons#1627]
Hi there! I'm ErrorGamer2000, and I am working on a new addon. It is a keyboard editor similar to Snap!'s that will allow you to add blocks by typing them. 
### Current features: 

- Multiple languages (ScratchScript[i.e. scratchblocks], JavaScript, Python)
- Syntax highlighting
- Adds [this button](https://github.com/ErrorGamer2000/randomassets/blob/main/type.svg) to the editor above the zoom controls for opening/closing the editor.
- Block preview*
- Some basic debugging*
<sub><sup>*Features in development</sup></sub>

### Future features:
- Autocomplete
- Add blocks by dragging them from preview, not just button.
- "Edit as text" in right-click menu allowing you to edit existing block stacks
- Match editor colors to current scratch theme

Anything else you want? Comment on this!

**Comment by ErrorGamer2000** [comment]
Yeah, that's probably a better title. Thanks @TheColaber!

**Comment by retronbv** [comment]
> Multiple languages (ScratchScript[i.e. scratchblocks], JavaScript, Python)

So you’re gonna convert Python and JS to scratch blocks? That’s gonna be pretty hard. Do you have a working concept?

**Comment by ErrorGamer2000** [comment]
I am using objects, like this:
```javascript
var key = {
    category: {
        blockname: {
            codename: {
                scratchscript: "",
                javascript: "",
                python:""
            }
        }
    }
}
```

**Comment by retronbv** [comment]
How would that work tho? Do you have a code snippet?

**Comment by ErrorGamer2000** [comment]
Then I split the content of a contenteditable div by a newline character, then each line gets split at each (, ), [, ] for the inputs and the values get ignored initially and replaced by an input placeholder (I am using `%i`) the lines are then rejoined using the placeholder and taken from there... give me a minute and I will explain a little better...

**Comment by TheColaber** [comment]
I think in the meantime this should be turned into a discussion since you guys are discussing it a lot.

**Comment by ErrorGamer2000** [comment]
okay then!
