### ISSUE TITLE
Remind user to share a project

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#1628]
Hello!

I am [Genius398](https://scratch.mit.edu/users/Genius398/). I want a new addon. Description below.

It will be a "Remind Share" addon. This addon will show a calendar and will allow us to choose the date. Then, when that date arrives, we can remind the user to share the project with window.confirm.

If @WorldLanguages or @griffpatch is seeing this, please find a solution

It's possible but hard.

**Comment by ErrorGamer2000** [comment]
For this to work correctly, someone would have to set up a server that will wait until the given date and then publish the project through your account... maybe possible with Node.js?

**Comment by mxmou** [comment]
> For this to work correctly, someone would have to set up a server that will wait until the given date and then publish the project through your account... maybe possible with Node.js?

It's possible, but I don't think we would want to send people's passwords to a server.

**Comment by TheColaber** [comment]
This is kinda impossible without a server unless you leave your browser open at that time. I'm sure however we could give you a notification at that time. Unless... not sure if chrome.alarams API could withstand being run without being online. I mean it could be possible is my point, best without a server.

**Comment by ErrorGamer2000** [comment]
Maybe a persistent script? If you make the extension's background page persistent then that may work...

**Comment by jeffalo** [comment]
all methods of this sound dangerous.

1. sending via a server, not a chance. 
2. if we do it client side, and the user isn't online they can risk the project not going up at the right date which is in my opinion worse than just sharing it now

**Comment by ErrorGamer2000** [comment]
If only there was a way to create an account that could have access to everything . . . *sigh*. This is a really good idea though...

**Comment by Genius398** [comment]
Hi, but I can't do it. I'm still a beginner coder.

**Comment by Genius398** [comment]
> If only there was a way to create an account that could have access to everything . . . _sigh_. This is a really good idea though...

You can make an organisation account.

**Comment by ErrorGamer2000** [comment]
And that's not going to be easy...

**Comment by ErrorGamer2000** [comment]
To get permission at least

**Comment by Genius398** [comment]
> And that's not going to be easy...

You mean?

**Comment by Genius398** [comment]
> To get permission at least

Means?

**Comment by ErrorGamer2000** [comment]
We would have to get permission from the scratch team, would we not?

**Comment by ErrorGamer2000** [comment]
OOOH, you mean one account that we all make projects on...

**Comment by ErrorGamer2000** [comment]
I thought you meant an account with scratch team/admin privileges

**Comment by Genius398** [comment]
> We would have to get permission from the scratch team, would we not?

No

> I thought you meant an account with scratch team/admin privileges

Yes, in Github

**Comment by ErrorGamer2000** [comment]
Yes, that may work, but the account would be public... what are the chances that someone would abuse it...

**Comment by ErrorGamer2000** [comment]
because it is impossible to determine who does what.

**Comment by Genius398** [comment]
> Yes, that may work, but the account would be public... what are the chances that someone would abuse it...

But we can close comments.

**Comment by Genius398** [comment]
> because it is impossible to determine who does what.

If you want then I'll make one.

Can I be a member?

**Comment by ErrorGamer2000** [comment]
Can't close comments like that.

A member of what? ScratchAddons? I am not a member myself.

**Comment by Genius398** [comment]
> Can't close comments like that.
> 
> A member of what? ScratchAddons? I am not a member myself.

We can close them. Shall I ask @WorldLanguages ?

**Comment by Genius398** [comment]
> Can't close comments like that.
> 
> A member of what? ScratchAddons? I am not a member myself.

You are a member

**Comment by ErrorGamer2000** [comment]
really? I had no idea... probably better to ask the others though...

**Comment by Genius398** [comment]
> really? I had no idea... probably better to ask the others though...

ok

You can go to "My Organizations"

**Comment by Genius398** [comment]
How many of you like this idea? Email me at anantjitchander@gmail.com

**Comment by WorldLanguages** [comment]
This is kinda rejected - it would maybe be fine as long as users understand Chrome would need to be open for it to work, but that might not be very easy to achieve. Also, since Chrome needs to be open: if the user is using the device actively, an alarm/notification will suffice. And if the user is not using the device, a scheduled autoclicker program would also be enough (since they're not actively using the device, they could just leave the unshared project tab open and use an everyday scheduled autoclicker on the share button).
If you're instead going to send passwords/token to a server to do this then there's no reason an extension would be necessary.

**Comment by RedGuy12** [comment]
The extension could send the only to the server
________________________________

**Comment by Genius398** [comment]
> This is kinda rejected - it would maybe be fine as long as users understand Chrome would need to be open for it to work, but that might not be very easy to achieve. Also, since Chrome needs to be open: if the user is using the device actively, an alarm/notification will suffice. And if the user is not using the device, a scheduled autoclicker program would also be enough (since they're not actively using the device, they could just leave the unshared project tab open and use an everyday scheduled autoclicker on the share button).
> If you're instead going to send passwords/token to a server to do this then there's no reason an extension would be necessary.

OR can we make it so that it reminds the user to share the project?

**Comment by WorldLanguages** [comment]
> OR can we make it so that it reminds the user to share the project?

Sure, but again, there's no reason for that to be part of an extensions. You can use web push with a server, or even do it serverless with the new notification triggers API.

**Comment by Genius398** [comment]
> > OR can we make it so that it reminds the user to share the project?
> 
> Sure, but again, there's no reason for that to be part of an extensions. You can use web push with a server, or even do it serverless with the new notification triggers API.

Ok.

**Comment by Genius398** [comment]
> This is kinda rejected - it would maybe be fine as long as users understand Chrome would need to be open for it to work, but that might not be very easy to achieve. Also, since Chrome needs to be open: if the user is using the device actively, an alarm/notification will suffice. And if the user is not using the device, a scheduled autoclicker program would also be enough (since they're not actively using the device, they could just leave the unshared project tab open and use an everyday scheduled autoclicker on the share button).
> If you're instead going to send passwords/token to a server to do this then there's no reason an extension would be necessary.

But then we can send an alert with `window.confirm("Will you like to share the project"+project_name+"?");` when Google Chrome (or whatever browser) opens and Scratch Addons loads
