### ISSUE TITLE
Pause button not working

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#1635]
Pause button not working
Hi!

I was playing a multiplayer platformer and there was no pause button

**Comment by jeffalo** [comment]
did you check the console for if there were any errors?

**Comment by Genius398** [comment]
> did you check the console for if there were any errors?

Thanks now it is working.


Can I join?

**Comment by Hans5958** [comment]
Huh. Oh, well. Solved, I guess?
