### ISSUE TITLE
editor-devtools: remove string "Version [...] - Released [...]" from help modal

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1637]
I don't think it's a good idea having to update this date each time, now that the extension will have biweekly updates to update locales. We *could* try to keep the version number, tho.
The "By griffpatch and other contributors [...]" string might also need to be changed so that it makes more sense if we remove the version number as context.

**Comment by apple502j** [comment]
FYI versions are placeholder, it can't hurt them bc it's not translated
