### ISSUE TITLE
Turbowarp player in editor (player)

### ISSUE THREAD

**Issue by retronbv** [ScratchAddons/ScratchAddons#164]
This replaces the existing player with turbowarp by grabbing the id from url and embedding turbowarp where the normal player would be

**Link to the new addon**

[here](https://github.com/YOYITsM3M8/ScratchAddons)

**Comment by Hans5958** [comment]
Make sure you search for the issues first before creating one! (#79, #150)

**Comment by YOYITsM3M8** [comment]
This was deemed duplicate of #150

**Comment by Hans5958** [comment]
This is actually not a duplicate, #150 refers to buttons to TurboWarp. This refers to changing the player in the first place.

**Comment by retronbv** [comment]
I never expected this issue to reopen

**Comment by Hans5958** [comment]
Neither does I. I lowkey remembered that someone opened it. Turns out it closed as a dupe.

**Comment by retronbv** [comment]
I opened it lol

**Comment by Hans5958** [comment]
> I opened it lol

Yeah I know, just edited it to clarify

**Comment by WorldLanguages** [comment]
This addon is hard to get right so I'll try to make it myself or help on the dev discord so that someone can make it

**Comment by retronbv** [comment]
finally :tada: :tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada:
