### ISSUE TITLE
Cat blocks addon

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#1645]
I can't find the cat blocks addon. Is it there?

**Comment by pufferfish101007** [comment]
https://github.com/ScratchAddons/ScratchAddons/discussions/1423

**Comment by Genius398** [comment]
> #1423

what?

**Comment by pufferfish101007** [comment]
That discussion explains how to get cat blocks and other easter egg addons.

**Comment by Genius398** [comment]
> That discussion explains how to get cat blocks and other easter egg addons.

ok
