### ISSUE TITLE
Where to type the Konami code to get the cat blocks?

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#1647]
Where to type the Konami code to get the cat blocks?

**Comment by pufferfish101007** [comment]
The main settings page.

**Comment by Genius398** [comment]
> The main settings page.

How?

**Comment by Genius398** [comment]
> The main settings page.

Can I do it now?

What is the code?

**Comment by mxmou** [comment]
You just have to be on the settings page and type [the code](https://en.wikipedia.org/wiki/Konami_Code).

**Comment by Genius398** [comment]
> You just have to be on the settings page and type [the code](https://en.wikipedia.org/wiki/Konami_Code).

Thanks!
