### ISSUE TITLE
[Feature] A sound when you get a message

### ISSUE THREAD

**Issue by NoobTracker** [ScratchAddons/ScratchAddons#165]
Since there's already an addon for that badge thingy, I think that adding a little sound whenever you get a message (is turned off by default) would be nice. Maybe the "meow" sound from the Scratch sound library.

**Comment by Hans5958** [comment]
```
var player = document.createElement('audio');
player.src = 'https://raw.githubusercontent.com/Hans5958/message-notifier/master/Message%20Notifier/notificationsound.wav';
player.preload = 'auto';
/* ... */
var functionThatChecksIfThereAreNewMessages = () => {
	/* ... */
	if (originalCount != count) {
		player.play();
	}
	/* ... */
}
/* ... */
```
Here's my implementation in [my older userscript](https://github.com/Hans5958/userscripts/blob/master/Scratch/Message%20Notifier/main.user.js). The only issue here is that, since it is userscript, if there are 5 Scratch tabs open, all 5 will have their own noise. I hope there is a feature on the extension/addon part on Chrome/Firefox.

**Comment by NoobTracker** [comment]
Probably, since it would probably work the way that little icon also works.

**Comment by JeffaloBob** [comment]
this should be part of
![image](https://user-images.githubusercontent.com/40470736/92003406-471d9680-ed41-11ea-90b3-b15341de9215.png)

**Comment by NoobTracker** [comment]
Yep

**Comment by WorldLanguages** [comment]
Scratch Notifier already notifies you, and in most OS it produces a sound.

**Comment by JeffaloBob** [comment]
> Scratch Notifier already notifies you, and in most OS it produces a sound.

close this?

or i guses if more options get supported maybe there could be an audio dropdown and you could choose a sound effect similar to in scratchnotifier.cf

**Comment by Hans5958** [comment]
> 
> 
> Scratch Notifier already notifies you, and in most OS it produces a sound.

[citation needed], or is this from the Notification API? Keep in mind that I never touch those as a user and dev in my entire life.

**Comment by WorldLanguages** [comment]
Notifications do produce a sound if the browser and OS support it, however I don't see why we couldn't add this as an option. Does anyone have a good public domain "ping" sound?

**Comment by easrng** [comment]
Check the scratch sound library.

**Comment by NoobTracker** [comment]
> 
> 
> Does anyone have a good public domain "ping" sound?

Why not just make one with a sine wave in Audacity?
