### ISSUE TITLE
The future of the changelog (no, just moving it)

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#1651]
After the establishment a while ago, [the changelog](https://github.com/ScratchAddons/ScratchAddons/blob/changelog/CHANGELOG.md) in [the `changelog` branch](https://github.com/ScratchAddons/ScratchAddons/tree/changelog) seemed to be kept in a limbo state, being in a single branch for unforeseeable future. I think something needs to be done. So, I propose these changes to solve this issue.

- Move [the changelog](https://github.com/ScratchAddons/ScratchAddons/blob/changelog/CHANGELOG.md) in [the `changelog` branch](https://github.com/ScratchAddons/ScratchAddons/tree/changelog) (summarised/public changelog) to the website. (in other words, instead of updating this changelog, update the ones on the website
The users rarely see the changelog from the branch, and the exact texts is already on https://github.com/ScratchAddons/ScratchAddons/releases. I think we don't need it to be three locations at the same time. Also, this allows improvements to be added to the changelog, like the highlights from the notification modal, better styling, etc. (also probably going to be changed to `.yml`, which generates a `.html`)

- Merge [the changelog](https://github.com/ScratchAddons/ScratchAddons/blob/changelog-detailed/CHANGELOG.md) in [the `changelog-detailed` branch](https://github.com/ScratchAddons/ScratchAddons/tree/changelog-detailed) (detailed/technical changelog) to master. (optional)
Within the same reason, we can put the technical, detailed changelog on GitHub. The contents are mostly made by me and apple502j. This should be kept for future reference for future developers, because it is not enough to only refer the summarised changelog.

**Comment by WorldLanguages** [comment]
LGTM

**Comment by Hans5958** [comment]
If no one's objecting, that mrans I can start the migration process, after I done v1.3.0 on the detailed changelog.

@WorldLanguages, give this a go?

**Comment by TheColaber** [comment]
@Hans5958 I think you've done your first point, but the branch still exists... Any updates?

**Comment by Hans5958** [comment]
Sorry for the late response. My notifs is quite clogged that I just saw you replied because you mentioned it on the other issue.

The technical changelog is not ready and still has long ways to go. I have created a todo list of things that should be done. I might consider improving the public changelog on the website first, then complete the techincal changelog.

**Comment by WorldLanguages** [comment]
Closing as done - changelog is now a yaml file on website repo.
