### ISSUE TITLE
Be able to add custom games to cloud games list

### ISSUE THREAD

**Issue by AwesomeKalin** [ScratchAddons/ScratchAddons#1652]
I'm making a multiplayer game and I'd like to keep a count of how many players are online at what time
**Describe the solution you'd like**
Be able to put custom games in the cloud games list

**Comment by retronbv** [comment]
I am pretty sure this feature was planned **except**, it would pull all projects from a studio. No support for projects only in your list.
But that’s how I remember it.

**Comment by TheColaber** [comment]
I had made this a thing with a new popup. All you would do is put `#cloud` or something is the desc and it would know it is a cloud project... I haven't PRed for yet, but will after one of my bigger PRs get merged.

**Comment by retronbv** [comment]
> All you would do is put #cloud or something is the desc and it would know it is a cloud project

it searches every project with #cloud and will put it in the popup?

**Comment by TheColaber** [comment]
No, every project of the user.

**Comment by RedGuy12** [comment]
I also think that we're should not be biased towards Griffpatch's games.
________________________________

**Comment by mxmou** [comment]
> I had made this a thing with a new popup. All you would do is put `#cloud` or something is the desc and it would know it is a cloud project... I haven't PRed for yet, but will after one of my bigger PRs get merged.

What if you wanted to put other people's games into the list? It should be possible to add any cloud project using the popup itself.

**Comment by RedGuy12** [comment]
@mxmou or we could use the dynamic length settings once they are done

**Comment by mxmou** [comment]
@RedGuy12 That would work too.

**Comment by AwesomeKalin** [comment]
Nice! Not as I originally thought of it in my head, but still good!

**Comment by Genius398** [comment]
> I'm making a multiplayer game and I'd like to keep a count of how many players are online at what time
> **Describe the solution you'd like**
> Be able to put custom games in the cloud games list

Yes. I like [https://scratch.mit.edu/users/KIKOKO_](KIKOKO_'s) projects, and I'm tired of seeing griffpatch's projects over there

**Comment by Hans5958** [comment]
Has anyone come up with an idea where we put a repository containing a JSON data, with all the cloud projects included in it? 

The extension will fetch the data from the repository regularly, and users can add their own project by creating a PR to the said repository?

**Comment by retronbv** [comment]
I was thinking we could allow the user to choose a studio. The studio could have all of the projects they want.

**Comment by AwesomeKalin** [comment]
I've made a temporary change and submitted a pull request to change the studio

**Comment by AwesomeKalin** [comment]
It was denied, so now I'm making a change where you can put a studio ID to show cloud games from. The default will be the studio that I used for the denied PR though

**Comment by WorldLanguages** [comment]
I'm adding this to the backlog because in the Scratch Messaging → Scratch Addons transition, I didn't look into detail on what functionalities the game tab had. I've been told it would work in any project, and it would tell you what users are currently playing it.
It would also be cool to let users add projects into it, but #1234 might be a blocker for doing it properly.

**Comment by lisa-wolfgang** [comment]
As an extension of this idea, the Games tab could be renamed to "Bookmarks" and allow for convenient access to a user-defined list of projects. There could also be a button on every project page that lets you add a project to your Bookmarks tab.

**Comment by piw-piw** [comment]
Add something like that, but with project IDs.
![image](https://user-images.githubusercontent.com/76477070/169683013-20cdd4d2-b87c-40c9-9953-6e18e495a64a.png)

**Comment by Norbiros** [comment]
Apple made it:
https://github.com/ScratchAddons/ScratchAddons/pull/4516
But you need type project url, not just id.

**Comment by apple502j** [comment]
Note: ID only works for projects, but since it now also supports studios using URL is better.
