### ISSUE TITLE
Strange gradient background appearing on all projects

### ISSUE THREAD

**Issue by DogeIsCut** [ScratchAddons/ScratchAddons#1654]
**Describe the bug**

A Strange gradient background appearing on all projects

**To Reproduce**

1. Import these settings
[scratch-addons-settings.txt](https://github.com/ScratchAddons/ScratchAddons/files/6032026/scratch-addons-settings.txt)
2. Create a new project
3. Observe

**Expected behavior**

A Normal blank white background

**Screenshots**

![msedge_uXR1LOaaWy](https://user-images.githubusercontent.com/23178844/108913699-90abb780-75e7-11eb-877d-d97358478855.png)

**Device (please complete the following information):**

- OS: Windows 10
- Browser Microsoft Edge
- Version 88

**Comment by WorldLanguages** [comment]
I cannot reproduce on Chrome after importing settings. Scratch Addons itself (its core) doesn't style nor modify the canvas, so can you disable each addon, one by one, then refresh the page, and see when it gets fixed (after disabling which addon)? So that we can trace the addon causing this

**Comment by TheColaber** [comment]
Could be a11y addon, but that's the only one I would expect...

**Comment by DogeIsCut** [comment]
found out it was the new load all blocks exstention.

**Comment by TheColaber** [comment]
> found out it was the new load all blocks exstention.

This is probably caused by the video sensing extension... try disabling that setting.

**Comment by Genius398** [comment]
> > found out it was the new load all blocks exstention.
> 
> This is probably caused by the video sensing extension... try disabling that setting.

yes
