### ISSUE TITLE
Change Editor Tutorials to more "Advanced" tutorials

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#1665]
> In the online editor, there is a 'tutorial' button, which has tutorials for beginners. The thing I would like is- advanced tutorials like Cloud Multiplayer tutorials, Scrolling Platformer, Scrolling movement, etc. from youtube users, such as griffpatch, CrystalKeeper7(not much tutorials), FUNUT, Warfame, McGuy, and many more..

**Comment by scratchusernamemrtbts** [comment]
:+1:

**Comment by Riptide-Scratch** [comment]
Would it be like embed yt videos?

**Comment by TheColaber** [comment]
Exactly as how tutorials for scratch currently work, just with different videos.

**Comment by scratchusernamemrtbts** [comment]
how about add a description for the tutorial too! so they'll know what the tutorial is about.

**Comment by Riptide-Scratch** [comment]
But that would add on heavily to the addon's download size.

**Comment by Secret-chest** [comment]
> But that would add on heavily to the addon's download size.

No,**it does not** need to download videos. It is just an iframe to YT.

**Comment by WorldLanguages** [comment]
I'd say this is rejected, it's not one of the intents of Scratch Addons to educate users on how to make projects.

**Comment by RedGuy12** [comment]
500th closed issue!
