### ISSUE TITLE
[Feature] Sort addons.json alphabetically

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#167]
**Is your feature request related to a problem? Please describe.**

This `addons.json` is not listed alphabetically.
https://github.com/ScratchAddons/ScratchAddons/blob/0ebac847670dff8d4f6f82901d639554dcc8df1c/addons/addons.json#L1-L14

**Describe the solution you'd like**

Why don't we sort this alphabetically?

**Comment by Explosion-Scratch** [comment]
Sure! It'd be pretty easy ig, you could just make a PR.

**Comment by Hans5958** [comment]
I'm waiting for other responses, since I'm not sure if everyone will be okay with it.

**Comment by apple502j** [comment]
Editing addons.json makes edit conflicts, so make sure other addon makers are ready.

**Comment by JeffaloBob** [comment]
that seems like unnecessary effort for each person to do everytime a new add-on is made... how are addons sorted in the options menu?

**Comment by WorldLanguages** [comment]
Why even order it alphabetically? I don't see the point.

**Comment by WorldLanguages** [comment]
> how are addons sorted in the options menu?

@JeffaloBob Right now:
- Enabled addons, alphabetically by name
- Disabled addons, recommended, alphabetically by name
- Disabled addons, without the recommended tag, alphabetically by name

**Comment by WorldLanguages** [comment]
Closing this - see https://github.com/ScratchAddons/ScratchAddons/pull/221, the order of addons here matters (and that's why I added support for comments inside `addons.json`, to explain exactly that)
