### ISSUE TITLE
Enabling or disabling addons in the popup should not cause them to move around

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#1670]
See https://github.com/ScratchAddons/ScratchAddons/issues/1670#issuecomment-826062306
Original description:

**Describe the bug**

Disabling themes with no running userscripts removes them from "Addons currently running on this tab".

**To Reproduce**

1. Enable website dark mode
2. Open the "Addons" tab in the popup
3. Disable website dark mode
4. It's removed from the list of currently running addons, which means you have to scroll to the bottom to enable it again after closing and reopening the popup.

**Expected behavior**

It should stay under currently running addons until the tab is refreshed.

**Comment by TheColaber** [comment]
Not sure you want this behavior. If it is not affecting the tab, it shouldn't be running. However, we have programmed it to stay at the top of the list if it was presently disabled... so whats the problem then? I don't think "It should stay under currently running addons until the tab is refreshed."

https://user-images.githubusercontent.com/72760579/109302933-fe362e80-7807-11eb-90af-ecbb2a938581.mp4

**Comment by mxmou** [comment]
@TheColaber It's inconsistent with other addons, and the purpose of the Addons tab is easy temporary toggling of addons, which is impossible if closing the popup and reopening it causes themes to move to the bottom.

This is also important if the popup gets changed to only show enabled addons (which is probably a good idea).

If this doesn't get changed, then this behavior should also apply to addons with userscripts, and there should be a way to make certain addons stay at the top of the popup permanently (#1250).

**Comment by TheColaber** [comment]
When #1500 all addons will start transitioning to the way Website dark mode, and other themes currently work. Really, it is that all the other addons are inconsistent. I think @1250, as you said is what we should be doing.

**Comment by mxmou** [comment]
I changed the label because this is not really a bug.

**Comment by WorldLanguages** [comment]
> It's removed from the list of currently running addons, which means you have to scroll to the bottom to enable it again after closing and reopening the popup.

I thought about this as well yesterday. PR #1500 will resolve this issue, see line: https://github.com/ScratchAddons/ScratchAddons/pull/1500/files#diff-716aae76bfb4eaa095810abaddc214bb23abc4a9ddc232f27cb3203233c1c0daR474

**Comment by TheColaber** [comment]
> I thought about this as well yesterday. PR #1500 will resolve this issue, see line: https://github.com/ScratchAddons/ScratchAddons/pull/1500/files#diff-716aae76bfb4eaa095810abaddc214bb23abc4a9ddc232f27cb3203233c1c0daR474

Meaning that, that PR will also resolve this issue?

**Comment by mxmou** [comment]
Now it's slightly better because the addon appears at the top of non-currently-running addons, but it's still frustrating. On the settings page enabling or disabling addons doesn't make them move around and the popup should behave the same. Reopening.

**Comment by WorldLanguages** [comment]
@mxmou How do you think it should work then? Right now, they move around to keep the list of `Addons currently running on this tab` up to date.

**Comment by mxmou** [comment]
> @mxmou How do you think it should work then? Right now, they move around to keep the list of `Addons currently running on this tab` up to date.

The purpose of the popup is easy toggling of addons, and toggling is easier if they don't move around while you're doing it. I think they should stay in the same position until you close and reopen the popup.

**Comment by mxmou** [comment]
Fixed in 1.14
