### ISSUE TITLE
Statistics section still appears on users that don't exist

### ISSUE THREAD

**Issue by superscratch444tre** [ScratchAddons/ScratchAddons#1679]
**Describe the bug**

Statisctics section still appears on pages of users that don't exist!

**To Reproduce**

1. Go to the profile page of an unexistent user.
2. See that the statistic section appears.

**Expected behavior**

The statistics section should be hidden

**Screenshots**

![image](https://user-images.githubusercontent.com/69812464/109384666-517eae80-78e6-11eb-958c-60821750a1a6.png)

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Chrome, lastest version
- Version: lastest

**Additional context**

None.

**Comment by WorldLanguages** [comment]
Good catch

**Comment by Explosion-Scratch** [comment]
Kool

**Comment by superscratch444tre** [comment]
Will this be fixed until the release of v1.11.0?

**Comment by mxmou** [comment]
> Will this be fixed until the release of v1.11.0?

Probably, but it isn't really a big problem.
