### ISSUE TITLE
addon.tab.scratchClass breaks when tab is not in focus

### ISSUE THREAD

**Issue by jeffalo** [ScratchAddons/ScratchAddons#1685]
**Describe the bug**

if the tab is not focused while addon.tab.scratchClass is ran, then it will return an invalid class which breaks stuff.

**To Reproduce**

I think the easiest way to repro would just be checkout https://github.com/jeffalo/ScratchAddons/tree/variable-tab

load a project page and switch to another browser tab while scratch is loading. come back in around 10 seconds. the class is not properly applied

**Expected behavior**

perhaps `addon.tab.scratchClass` should return a promise that we can await in the addons

**Device (please complete the following information):**

- chrome 88.0.4324.190  on windows 10 20h2

**Comment by jeffalo** [comment]
i switched to using `document.querySelector("[class^=gui_tabs]")` instead of scratchClass which seems to solve it for my addon but this is something to link into still. plus async/await is cool anyways

**Comment by GrahamSH-LLK** [comment]
You shouldn't use document.querySelector with addon.tab.scratchClass.

**Comment by jeffalo** [comment]
> You shouldn't use document.querySelector with addon.tab.scratchClass.

i know, but the issue still exists by setting className

**Comment by mxmou** [comment]
> > You shouldn't use document.querySelector with addon.tab.scratchClass.
> 
> i know, but the issue still exists by setting className

I thought the correct class is applied automatically when it's available if you're using it to set `className`.

**Comment by WorldLanguages** [comment]
`addon.tab.scratchClass`'s return value should only be used to add it to an element - not for query selectors. Its only goal is making custom elements that also inherit Scratch's styles.
