### ISSUE TITLE
Links in "more links" addon can't include %

### ISSUE THREAD

**Issue by superscratch444tre** [ScratchAddons/ScratchAddons#1697]
**Describe the bug**

Links in "more links" addon doesn't include %,<, and other symbols

**To Reproduce**

1. Go to the comment section of a studio, a profile or a project
2. Write a comment with a link that contains %,<,> or some other symbols
3. Post the comment
4. See that the link does not include the symbol

**Expected behavior**

The symbol should be a part of the link

**Screenshots**

![image](https://user-images.githubusercontent.com/69812464/109515215-c0066c80-7a9e-11eb-99cb-543749eac8da.png)

![image](https://user-images.githubusercontent.com/69812464/109515726-4de25780-7a9f-11eb-877f-3ebc39076d5b.png)

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Chrome, lastest version
- Version: lastest

**Additional context**

None.

**Comment by TheColaber** [comment]
cc @apple502j

**Comment by RedGuy12** [comment]
% should definately be added...maybe not < tho
________________________________

**Comment by superscratch444tre** [comment]
> % should definately be added...maybe not < tho

Both are important in scratchblocks.github.io

**Comment by apple502j** [comment]
Being unable to include % is a bug. other ones are working as intended IIRC.

**Comment by RedGuy12** [comment]
< isn't part of the url spec

ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/?#[]@!$&'()*+,;=

are what we should allow
see https://stackoverflow.com/a/1547940/11866686
________________________________

**Comment by superscratch444tre** [comment]
> < isn't part of the url spec ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/?#[]@!$&'()*+,;= are what we should allow see https://stackoverflow.com/a/1547940/11866686


Ah, I didn't know that...

**Comment by retronbv** [comment]
Shouldn’t < or > be escaped?

**Comment by RedGuy12** [comment]
> Shouldn’t < or > be escaped?

scratchblocks.github.io should encode the output using `encodeURIComponent`, yes. if it's not, that a bug with them, [make an issue there](https://github.com/scratchblocks/scratchblocks/issues/new)

**Comment by WorldLanguages** [comment]
> Shouldn’t < or > be escaped?

Yeah, they are escaped with `%`, so this is still a bug :P

**Comment by retronbv** [comment]
f in the chat bois, f in the chat.....
