### ISSUE TITLE
Scratch 2.0→3.0 shows vertical overflow in comments (zalgo text)

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1699]
Example: https://scratch.mit.edu/users/Chiroyce/#comments-125081052
Vanilla Scratch does not show the overflow.
Low prio ¯\\_(ツ)_/¯

**Comment by mxmou** [comment]
This can be fixed, but it will still look ugly:
![image](https://user-images.githubusercontent.com/51849865/109521534-b59f9f00-7aad-11eb-94ab-5f3aa1141149.png)

The bubble itself needs to have `overflow: visible`.

**Comment by TheColaber** [comment]
@mxmou That's pretty much how it looks when SA is off.

**Comment by mxmou** [comment]
> @mxmou That's pretty much how it looks when SA is off.

Ideally it would be cut off at the border of the bubble.

**Comment by Explosion-Scratch** [comment]
```js
string.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
```
(from [Bijou.js](https://bijou.js.org), you're welcome.)

For example:
```js
//Logs "--Explosion--" to console!
console.log("-̷̝̜̟̈́-̵̫̬̤̣̑͌̓̈̚͝E̵̺̊͂͘͠x̶̨̼̝͍̑́̅̎͝p̸̮̤̫̩̳͂̔̌̓̈l̶̢̤̣͌͌̒ỡ̸͍̤̣̖̑͘s̵̢̢̖̼̖̲͌̈̾̏i̴̻̭̝͋́͒͌̃̌́o̴̖̮͗̽͐̈͊͆n̸͍͕̱͗̐̆̿͝-̷͈̗͚̘̿͒̅̉-̶̢̹̰̜̏͜".normalize('NFD').replace(/[\u0300-\u036f]/g, '');
```

**Comment by mxmou** [comment]
@Explosion-Scratch I think I'm going to use a CSS-only solution, but thank you anyway.

**Comment by WorldLanguages** [comment]
Yeah, zalgo should still be visible (but ideally stop overflowing where it should be)

**Comment by lisa-wolfgang** [comment]
On a somewhat-related note, this also happens in the Messaging tab in the popup.
