### ISSUE TITLE
[Feature] custom icons for addons

### ISSUE THREAD

**Issue by YOYITsM3M8** [ScratchAddons/ScratchAddons#170]
**Is your feature request related to a problem? Please describe.**
Custom icons for the addons

**Describe the solution you'd like**

Add a png file to link in manifest

**Describe alternatives you've considered**

**Additional context**

**Comment by Explosion-Scratch** [comment]
That would be nice!

**Comment by YOYITsM3M8** [comment]
Yup

**Comment by Hans5958** [comment]
This, but don't forget to do fallback.

**Comment by YOYITsM3M8** [comment]
Yes definitely fallback like a puzzle piece 🧩

**Comment by JeffaloBob** [comment]
i feel like letting addon creators make their own icons will make it look super busy, i suggest instead there should be more icons based on tags.

**Comment by WorldLanguages** [comment]
I don't think icons are a good idea, tbh. It makes the settings page look more like a store of independent "extensions", when in fact, they aren't.

**Comment by YOYITsM3M8** [comment]
Yeah, I guess

**Comment by WorldLanguages** [comment]
I officially reject this suggestion :P
