### ISSUE TITLE
"More links" addon should also work in the extension popup

### ISSUE THREAD

**Issue by superscratch444tre** [ScratchAddons/ScratchAddons#1701]
**Is your feature request related to a problem? Please describe.**

If someone posts a link in a comment, and I view it in the messaging popup, I need to open the comment in a new tab to go to that link. (The link isn't clickable!)

![image](https://user-images.githubusercontent.com/69812464/109521543-55a4fa80-7aa5-11eb-9b1c-54c72b1e9f1b.png)

**Describe the solution you'd like**

The "More Links" addon should also work in the popup.

**Describe alternatives you've considered**

None yet.

**Additional context**
something like that:

![image](https://user-images.githubusercontent.com/69812464/109521784-943ab500-7aa5-11eb-8f82-dbe9992ebe2c.png)

**Comment by TheColaber** [comment]
So now we can inject userscript in the popup :D

**Comment by superscratch444tre** [comment]
> So now we can inject userscript in the popup :D
> 
> Edit: In all seriousness, we could kinda just use the library on the comments

So, can this be done?

**Comment by WorldLanguages** [comment]
I don't see why we couldn't check if `more-links` is enabled, and if so, inject our linkify library into the popup (see #1234)

**Comment by superscratch444tre** [comment]
@WorldLanguages So is this possible to make?
