### ISSUE TITLE
Language i want to translate : Hindi

### ISSUE THREAD

**Issue by Barthdry** [ScratchAddons/ScratchAddons#1708]
Language i want to translate : Hindi
My transifex account: [Barthdry](https://www.transifex.com/user/profile/Barthdry/)

_Originally posted by @Barthdry in https://github.com/ScratchAddons/ScratchAddons/discussions/1052#discussioncomment-412700_

**Comment by TheColaber** [comment]
Please keep all discussion about translation in #1052
