### ISSUE TITLE
Disable autosave addon disables CTRL+S and File menu saving

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#1709]
**Describe the bug**

When the Disable autosave addon is enabled, the Scratch editor doesn't save at all. The saving animation plays briefly, but the project doesn't actually upload to Scratch's servers.

**To Reproduce**

1. Enable the "Disable autosave" addon
2. Go to any of your projects
3. Try to save it
4. Once the animation finishes, reload the page
5. Your change was probably not saved

**Expected behavior**

The addon should still allow manual attempts to save.

**Device (please complete the following information):**

- OS: Windows
- Browser: Firefox 86
- Version: v1.10.0

**Additional context**

I think the addon used to work, but I can't remember for sure.

**Comment by TheColaber** [comment]
I am not able to repoduce. Can you send a video or something? I'm on the master rn so not sure if this is on the stable.

**Comment by Scratchfangs** [comment]
I have the same problem, I see it saying "saving project" but when I reload, nothing saved.

**Comment by WorldLanguages** [comment]
Screen recording or it didn't happen @lisa-wolfgang @Scratchfangs

**Comment by lisa-wolfgang** [comment]
Hmm, it doesn't seem to always happen, either.
