### ISSUE TITLE
When a user has a message from the Scratch team, the message displays incorectly.

### ISSUE THREAD

**Issue by Tacodude7729** [ScratchAddons/ScratchAddons#1710]
**Describe the bug**
When the user has a message 'from the scratch team', the addon correctly shows 1 notification but, the messages section will incorectly show the last notification received before the message from the scratch team.

**Expected behavior**
The message from the scratch team should show up.

**Screenshots**
Unfortunaly, I cleared the notification without taking a screenshot.

**Device (please complete the following information):**
Ubuntu 20.04 Chrome

**Comment by Genius398** [comment]
> **Describe the bug**
> When the user has a message 'from the scratch team', the addon correctly shows 1 notification but, the messages section will incorectly show the last notification received before the message from the scratch team.
> 
> **Expected behavior**
> The message from the scratch team should show up.
> 
> **Screenshots**
> Unfortunaly, I cleared the notification without taking a screenshot.
> 
> **Device (please complete the following information):**
> Ubuntu 20.04 Chrome

I support you in this thing

**Comment by WorldLanguages** [comment]
This is intentional behavior, labeling as enhancement

**Comment by mxmou** [comment]
> This is intentional behavior, labeling as enhancement

Shouldn't it at least subtract the number of alerts from the message count? I don't think displaying the last normal message is intentional.

**Comment by WorldLanguages** [comment]
@mxmou Scratch Messaging intentionally does not interact with alerts and reporting comments. Checking how many unread alerts ("messages from the Scratch Team") the user has requires an additional API call.

**Comment by Tacodude7729** [comment]
> @WorldLanguages  This is intentional behavior, labeling as enhancement

Perhaps I wasn't clear. When I had a message from the scratch team, the plugin showed me I had 1 unread message. But, the message it showed in the messages tab was not the message from the scratch team but one I had received and already read  (some random comment). I'm not asking for scratch team messages to show up, I'm asking, that when you get a scratch team message, there shouldn't be another notification for whatever the latest thing in your inbox is. This isn't an enhancement, it's a bug.

**Comment by apple502j** [comment]
There is no way to check for ST messages without making an API call, at which point it's useless if we didn't add complete displaying of them.

**Comment by WorldLanguages** [comment]
> Perhaps I wasn't cleahr. Wen I had a message from the scratch team, the plugin showed me I had 1 unread message. But, the message it showed in the messages tab was not the message from the scratch team but one I had received and already read (some random comment). I'm not asking for scratch team messages to show up, I'm asking, that when you get a scratch team message, there shouldn't be another notification for whatever the latest thing in your inbox is. This isn't an enhancement, it's a bug.

What you're mentioning was an intentional decision by me. We cannot let users ignore the fact they have a moderator alert. Some users don't even check the messages page anymore, and only use Scratch Messaging. So it's either a) force the user to go to the messages page to clear the alert, or b) show the alert within Scratch Messaging and allow the user to clear it from there. There's no middle ground, we need to make sure users read alerts. Option b) wasn't implemented, so as of now, we rely on the user noticing "clear messages" does not clear all messages so that they go to the real Scratch messages page to check the alert and clear it.

**Comment by mxmou** [comment]
> We cannot let users ignore the fact they have a moderator alert.

But the current behavior doesn't inform the user that they have a moderator alert.

**Comment by WorldLanguages** [comment]
> But the current behavior doesn't inform the user that they have a moderator alert.

Nope, because being aware of whether the unread message is an alert or not requires additional API calls (or a well thought algorithm that notices the newest message is still the same after clearing the message count)

**Comment by LES-11** [comment]
Another option could be have a banner that says something along the lines of: ``You have a notification from the ST. Please go to the messages page to view and clear your message``
This would make it a lot clearer as to what is happening to the user.

(yes i know this is an older issue but im still going to input my thoughts)

**Comment by jeffalo** [comment]
i don't have an opinion on how alerts are displayed but the mark messages as read should never delete alerts. alerts should have to be deleted manually no matter what.

**Comment by WorldLanguages** [comment]
@LES-11 Keep in mind Scratch Messaging currently does not know whether the unread notification is a message or not, as I said before:

> Nope, because being aware of whether the unread message is an alert or not requires additional API calls (or a well thought algorithm that notices the newest message is still the same after clearing the message count)

**Comment by GrahamSH-LLK** [comment]
Can't it subtract the number of messages from scratch from the number of messages shown? If the number isn't 0, then it can show the banner?

**Comment by mxmou** [comment]
> Can't it subtract the number of messages from scratch from the number of messages shown? If the number isn't 0, then it can show the banner?

The only way to find out if there are alerts is to make another API call.

**Comment by Miala-python** [comment]
For Screenshots: 

![image](https://user-images.githubusercontent.com/65893041/116095384-a3ef0800-a6a8-11eb-9392-266ba606e1f1.png)
>When I click on the messages button:
>
>![image](https://user-images.githubusercontent.com/65893041/116095333-99347300-a6a8-11eb-8f73-f7718113185b.png)

**Comment by TheColaber** [comment]
If anyone is interested in trying this, here's what I got for you:
```js
fetch("https://api.scratch.mit.edu/users/TheColaberTest/messages/admin", { // Gets all admin messages
  "headers": {
    "x-token": "xtoken"
  }
});
fetch("https://scratch.mit.edu/site-api/messages/messages-delete/", { // "Marks the message as read"
  "headers": {
    "content-type": "application/json",
    "x-csrftoken": "xcsrftoken",
    "x-requested-with": "XMLHttpRequest"
  },
  "body": JSON.stringify({ alertType: "notification", alertId: 999999 }), // alertId will be given from the fetch above.
  "method": "POST",
});
```

**Comment by WorldLanguages** [comment]
I'll make it so that Scratch Messaging warns you about having unread admin messages. But it won't actually display them. It will link you to the messages page.
@TheColaber That's useful. Does /messages/admin return an array? Is checking the length of the array sufficient?

**Comment by TheColaber** [comment]
> Does /messages/admin return an array? Is checking the length of the array sufficient?

Correct. That would work.
