### ISSUE TITLE
My Player Doesnt Move

### ISSUE THREAD

**Issue by javascript-programmer** [ScratchAddons/ScratchAddons#1717]
Hi There 
I have Recently noticed
That My Player doesn't Move 
Since The extension is blocking the movement
And It also turns  on video in the video sensing in every project
can you please fix that?

**Comment by retronbv** [comment]
The video sensing automatically turning on is because of an addon. What addons do you have enabled that would be messing with the editor/project player?

**Comment by TheColaber** [comment]
> And It also turns on video in the video sensing in every project

![image](https://user-images.githubusercontent.com/72760579/109810993-48e4eb80-7bf8-11eb-91bf-461a680b608d.png)
Just disable the video sensing option here.

I am really worried about this addon. Don't people know what they choose to have enabled?

**Comment by mxmou** [comment]
> I am really worried about this addon. Don't people know what they choose to have enabled?

Video sensing is enabled by default. I don't think it should be because it enables video automatically.

**Comment by TheColaber** [comment]
It is, but that addon is not. In fact, it wasn't even featured. So the only reason why this could have happened is if users are randomly enabling all addons.

**Comment by jeffalo** [comment]
> It is, but that addon is not. In fact, it wasn't even featured. So the only reason why this could have happened is if users are randomly enabling all addons.

addons have a responsibility to provide sensible defaults. enabling video in every project is not a sensible default.

**Comment by WorldLanguages** [comment]
> addons have a responsibility to provide sensible defaults. enabling video in every project is not a sensible default.

It seemed like a sensible default for me because Scratch 2.0 had video sensing built in (as well as pen and music). I had camera permission blocked (and haven't used the Scratch editor video sensing features for years) so I missed this detail

**Comment by WorldLanguages** [comment]
@javascript-programmer 

1. Disable the "video sensing" setting of the "auto-show editor extensions" addon
2. Can you link to the project where the player doesn't move?

**Comment by mxmou** [comment]
> So the only reason why this could have happened is if users are randomly enabling all addons.

That's our fault: the popup allows enabling addons without looking at their descriptions and settings. A possible solution would be to only show enabled addons in the popup (related: #1663).

**Comment by TheColaber** [comment]
Good point. The popup is causing problems. I feel like only showing enabled addons isn't enough. I think we should show enabled addons and recommended addons. (And maybe if the user searches with the search bar, then they want to find that addon so we should show all then)

**Comment by mxmou** [comment]
> Good point. The popup is causing problems. I feel like only showing enabled addons isn't enough. I think we should show enabled addons and recommended addons. (And maybe if the user searches with the search bar, then they want to find that addon so we should show all then)

If so, enabling an addon that wasn't yet enabled on the current page using the popup should expand it so that the user sees the description and settings.

**Comment by WorldLanguages** [comment]
This issue is about a "player not moving", please create another issue for "addons" popup behavior

**Comment by javascript-programmer** [comment]
thanks for the help
