### ISSUE TITLE
Make the setting JSON file look cleaner

### ISSUE THREAD

**Issue by scratchusernamemrtbts** [ScratchAddons/ScratchAddons#1719]
**Is your feature request related to a problem? Please describe.**

I want to be able to edit the setting by using the JSON file but it is hard to read
So I can edit only the JSON file and import to every browser I use
**Describe the solution you'd like**

Make the SA save the setting file in a more cleaner file
**Describe alternatives you've considered**

 N/A

**Additional context**

N/A

**Comment by TheColaber** [comment]
By "cleaner", do you just mean formatted?

**Comment by scratchusernamemrtbts** [comment]
Yes

**Comment by scratchusernamemrtbts** [comment]
So it will be easy to read

**Comment by WorldLanguages** [comment]
JSON is for machines, not humans. If you really want to edit it, get a "code editor" (json isn't code but you get the point lol) that will format it for you.

**Comment by scratchusernamemrtbts** [comment]
> JSON is for machines, not humans. If you really want to edit it, get a "code editor" (json isn't code but you get the point lol) that will format it for you.

Thanks
