### ISSUE TITLE
We will reject addons using innerHTML or triple curly from now on

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#173]
Please do not use innerHTML. Use appendChild or textContent or innerText. Existing addons will be changed to use these methods. This includes Vue `{{{`.

**Comment by YOYITsM3M8** [comment]
Kkkkkk I always use appendChild bc innerHTML doesn’t work for me sometimes. innerHTML is easier tho

**Comment by JeffaloBob** [comment]
![image](https://user-images.githubusercontent.com/40470736/92022246-4265dc00-ed5b-11ea-8baf-27cfcb114dad.png)

**Comment by Explosion-Scratch** [comment]
This is gonna sound stupid, but… What is innerhtml?

**Comment by JeffaloBob** [comment]
> This is gonna sound stupid, but… What is innerhtml?

in javascript there are many ways to interact with the html page. one of them is directly modifying the HTML which is bad because it opens up for attacks like XSS and stuff.

**Comment by Explosion-Scratch** [comment]
Oh, I see. Thanks! :)

**Comment by WorldLanguages** [comment]
The issue isn't innerHTML itself really (even tho it's dangerous if you don't know what you're doing), but the review process in extension stores. They don't like innerHTML.

**Comment by Hans5958** [comment]
I don't think you can say that all `innerHTML` implementation is bad. Sure that "`innerHTML` is bad because it parses it directly so they can XSS", but I don't think that's the case here.

But, sure, using `textContent` is feasable.

**Comment by tb148** [comment]
Maybe add an "announcement" label for this type of issues?

**Comment by Hans5958** [comment]
Pins are enough, perhaps?

**Comment by tb148** [comment]
> 
> 
> Pins are enough, perhaps?

We only have limited numbers of pins. So accessing older ones is hard without an unique label.

**Comment by apple502j** [comment]
Vue.js `{{{` is now on the denylist. If you really need to use it, please ask me. The only allowed usage for now is for comments (because they are sanitized server side).

**Comment by tb148** [comment]
What is Vue `{{{`?

**Comment by apple502j** [comment]
Works same as `innerHTML`.

**Comment by YOYITsM3M8** [comment]
what about innerText

**Comment by apple502j** [comment]
innerText is safe.

**Comment by YOYITsM3M8** [comment]
K

**Comment by NoobTracker** [comment]
Question: What about `insertAdjacentHTML()`?

**Comment by apple502j** [comment]
@NoobTracker As long as you can add HTML, don't.

**Comment by BoomerScratch** [comment]
Will an addon with this get rejected?
```javascript
element.innerHTML = string.replace(/</g,"&lt;").replace(/>/g,"&gt;");
```

**Comment by NoobTracker** [comment]
@apple502j I think that it's used somewhere in an extension ... but don't ask me which one.

**Comment by tb148** [comment]
> 
> 
> @apple502j I think that it's used somewhere in an extension ... but don't ask me which one.

Just search it in this repo and you will find.

**Comment by NoobTracker** [comment]
Well I dunno how to do that.
I think @JeffaloBob did it ...

**Comment by BoomerScratch** [comment]
@easrng But what if you want, for example, this?
```javascript
element.innerHTML = string.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\n/g,"<br>");
```

**Comment by NoobTracker** [comment]
Well @BoomerScratch it seems like the reason why this isn't allowed anymore is that the addon people don't like it, although it might be used in completely harmless situations.

**Comment by easrng** [comment]
> @easrng But what if you want, for example, this?
> 
> ```js
> element.innerHTML = string.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\n/g,"<br>");
> ```

Use textcontent and `white-space: pre-line;`

**Comment by Explosion-Scratch** [comment]
It seems like everyone is on the same page about this now so I'll close it.

**Comment by Secret-chest** [comment]
> It seems like everyone is on the same page about this now so I'll close it.

@Explosion-Scratch What about _getting_ innerHTML?

**Comment by WorldLanguages** [comment]
@Secret-chest Getting innerHTML is fine.
