### ISSUE TITLE
Profile page banner addon: do not hide "report user" button

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#1743]
Might have been intentional, but we shouldn't be removing report buttons

**Comment by mxmou** [comment]
![image](https://user-images.githubusercontent.com/51849865/110200009-ca888380-7e5b-11eb-9715-f9f07e6de8e5.png)

**Comment by TheColaber** [comment]
@WorldLanguages Not sure if you came up with this, or if it was feedback, but report buttons don't show up on your own profile.
![image](https://user-images.githubusercontent.com/72760579/110210459-d118fa00-7e5f-11eb-946e-d82132e35e41.png)

**Comment by WorldLanguages** [comment]
lol
