### ISSUE TITLE
DevTools "Cut Block" bug

### ISSUE THREAD

**Issue by ErrorGamer2000** [ScratchAddons/ScratchAddons#1750]
I have noticed a couple of times that when you try to undo the "Cut Block" action that is added by DevTools, it puts the block back in the workspace **on top** of the stack it came from, not back in it. I was looking through DevTools.js earlier when I found the issue.
 
On [line 1534](https://github.com/ScratchAddons/ScratchAddons/blob/7d124a486261e8d4082dbbf4b007ddc6376b1e9d/addons/editor-devtools/DevTools.js#L1534), inside the `eventCopyClick` function, the block is removed from the stack in order to make the code work.

```javascript
...
function eventCopyClick(e, blockOnly) {
    let wksp = devTools.utils.getWorkspace();
    devTools.hidePopups(wksp);

    let block = wksp.getBlockById(dataId);
    if (block) {
        block.select();
        let next = blockOnly ? block.getNextBlock() : null;
        if (next) {
            next.unplug(false); // setParent(null);
        }

        // separate child temporarily
        document.dispatchEvent(new KeyboardEvent("keydown", { keyCode: 67, ctrlKey: true }));
        if (next || blockOnly === 2) {
            setTimeout(() => {
                if (next) {
                    wksp.undo(); // undo the unplug above...
                }
                if (blockOnly === 2) {
                    let block = wksp.getBlockById(dataId);
                    UndoGroup.startUndoGroup(wksp);
                    block.dispose(true);
                    UndoGroup.endUndoGroup(wksp);
                }
            }, 0);
        }
    }
}
...
```

The code removes the block, then puts it back with `wksp.undo()`, but *only if "copy block" was selected.* This is a lttle bug, but it has messed me up a few times before when I forget to actually put the block back. 
 
My proposed fix is simple, just adding one line of code.

```javascript
...
if (next || blockOnly === 2) {
    setTimeout(() => {
        if (next) {
            wksp.undo(); // undo the unplug above...
        }
        if (blockOnly === 2) {
            wksp.undo() //Invoke undo to put the block back in the stack
            let block = wksp.getBlockById(dataId);
            UndoGroup.startUndoGroup(wksp);
            block.dispose(true);
            UndoGroup.endUndoGroup(wksp);
        }
    }, 0);
}
...
```

**Comment by lisa-wolfgang** [comment]
@ErrorGamer2000 If you've already fixed the issue, you should create a pull request to propose your changes. That way, it's one step closer to being patched instead of a developer having to make the change.

**Comment by WorldLanguages** [comment]
Tagging @griffpatch

**Comment by ErrorGamer2000** [comment]
Well, for some reason I can't get the bug to be recreated... I have tried the fix and it still works, but now it is working without the fix...

**Comment by TheColaber** [comment]
This seems not to have been a bug? I tried to repo and I couldn't... 


https://user-images.githubusercontent.com/72760579/110341729-a910ce80-7ff8-11eb-9ffa-37759157fee8.mp4

Closing for now, until someone comes across this issue.
