### ISSUE TITLE
Connection indicator in popup

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#1756]
**Is your feature request related to a problem? Please describe.**

Since Scratch experiences frequent outages, it would be nice to be able to see at a glance if Scratch is up or not.

**Describe the solution you'd like**

At the very left of the tabs, there could be a small circular indicator that's green when online and red when offline. Additionally, the extension could show a small message when Scratch is down and another message when it comes back up. This would look something like the Firefox Private Network extension:

![image](https://user-images.githubusercontent.com/43426138/110364449-660b2700-8009-11eb-8c21-d056950ffeb1.png)
![image](https://user-images.githubusercontent.com/43426138/110364491-77543380-8009-11eb-8d61-10b59e9d2a1c.png)

**Describe alternatives you've considered**

The indicator could also appear on the extension icon -- again, in a similar manner to Firefox Private Network.
There could also be an option to tell if it's not just Scratch but the entire device/network -- this could be achieved by trying to ping scratchaddons.com.

**Comment by WorldLanguages** [comment]
I don't think this would be possible in Chrome?

**Comment by retronbv** [comment]
> > I don't think this would be possible in Chrome?
> 
> It would be if it was shown on the extension icon (for example as a badge). Maybe it could show a message in Firefox and just a badge in Chrome.

the badge is already being used for message count?

**Comment by areeq0325** [comment]
Would this work with the custom block colors addon?

**Comment by retronbv** [comment]
> Would this work with the custom block colors addon?

What does the custom block colors addon have to do with this?

**Comment by mxmou** [comment]
> isnt the badge is already being used for message count?

When Scratch is down there is no message count so an error badge could be shown instead.

**Comment by areeq0325** [comment]
@retronbv Oh whoops wrong issue
