### ISSUE TITLE
Hide project stats

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#1757]
**Describe the new addon**

Sometimes I just don't feel like being told that a generic platformer has thousands of loves. This addon would hide the project stats on the project page (removing the numbers by the love and favorite buttons and completely removing the remix and view counts) and the counts in the What the Community is Remixing/Loving sections of the front page.

This would likely be a good addon to have an options panel for.

**Comment by TheColaber** [comment]
Use this userscript, and have a nice day:
```js
document.querySelector(".stats").remove();
```

**Comment by mxmou** [comment]
> Use this userscript, and have a nice day:
> 
> ```js
> document.querySelector(".stats").remove();
> ```
This also removes the love and favorite buttons. Complete version for the project page (not tested):
```js
document.querySelector(".project-loves").innterText = "";
document.querySelector(".project-favorites").innterText = "";
document.querySelector(".project-remixes").remove();
document.querySelector(".project-views").remove();
```

It isn't possible to remove counts in What the Community is Loving/Remixing without a `MutationObserver` so making this an addon where you have `addon.tab.waitForElement()` would be much easier.

**Comment by RedGuy12** [comment]
> > Use this userscript, and have a nice day:
> > ```js
> > document.querySelector(".stats").remove();
> > ```
> 
> This also removes the love and favorite buttons. Complete version for the project page (not tested):
> 
> ```js
> document.querySelector(".project-loves").innterText = "";
> document.querySelector(".project-favorites").innterText = "";
> document.querySelector(".project-remixes").remove();
> document.querySelector(".project-views").remove();
> ```
> 
> It isn't possible to remove counts in What the Community is Loving/Remixing without a `MutationObserver` so making this an addon where you have `addon.tab.waitForElement()` would be much easier.

`innterText`?

**Comment by mxmou** [comment]
> `innterText`?

Fixed.
