### ISSUE TITLE
Set new sprite position to (0, 0)

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#1759]
**Describe the new addon**

When a new sprite is created, for whatever reason, the Scratch Team decided to position it at (36, 28). This isn't even due to sprite visibility concerns because every single new sprite created starts at this strange position.

I propose an addon that sets the position of newly created sprites to (0, 0).
Users could also set a custom position in the Options panel.

**Comment by Endermaster3690** [comment]
Yeah this is a thing for me too. I usually want to keep my sprites centered by using forever: go to x 0 y 0 but with this it seems to be a little harder.

**Comment by Endermaster3690** [comment]
> Scratch positions empty sprites at (36, 28) and sprites from the library at a random position. Maybe the custom position would affect all sprites by default but could be disabled for library sprites?

[insert super mario maker 2 Cool Idea! comment stamp here]

**Comment by TheColaber** [comment]
Is it really such a problem for a sprite to be a little off the center when added? What benefit do you get from moving it to the center?

**Comment by Endermaster3690** [comment]
> Is it really such a problem for a sprite to be a little off the center when added? What benefit do you get from moving it to the center?

getting it in the right place?

**Comment by mxmou** [comment]
> Is it really such a problem for a sprite to be a little off the center when added? What benefit do you get from moving it to the center?

It saves time (if the sprite doesn't move while the project is running you typically won't use the go to block).

**Comment by Endermaster3690** [comment]
> There is no "right" place. Not sure I see the benefit, after all, you will be setting it's xy position later with blocks.

what if we want to keep the sprite in the center? Like Maximouse said,
> It saves time (if the sprite doesn't move while the project is running you typically won't use the go to block).

**Comment by towerofnix** [comment]
> It saves time (if the sprite doesn't move while the project is running you typically won't use the go to block).

Yeah, agreed here! Usually I just type zero-zero into the X and Y position inputs, which is a little nicer than using an unnecessary go to block. An addon to stick new sprites in the center automatically would be cool.

> Scratch positions empty sprites at (36, 28) and sprites from the library at a random position. Maybe the custom position would affect all sprites by default but could be disabled for library sprites?

How about an option to toggle whether it acts on library sprites? I agree that most of the time library sprites are worth showing at a random position (since it helps keep added sprites visible and can act as [a source of inspiration](https://github.com/LLK/scratch-gui/issues/53#issuecomment-285200124)), but it also seems worth the tiny bit of extra UI to make it customizable according to what addon users themselves want. :P

**Comment by Secret-chest** [comment]
> > snip
> 
> Yeah, agreed here! Usually I just type zero-zero into the X and Y position inputs, which is a little nicer than using an unnecessary go to block. An addon to stick new sprites in the center automatically would be cool.
> 
> > snip
> 
> How about an option to toggle whether it acts on library sprites? I agree that most of the time library sprites are worth showing at a random position (since it helps keep added sprites visible and can act as [a source of inspiration](https://github.com/LLK/scratch-gui/issues/53#issuecomment-285200124)), but it also seems worth the tiny bit of extra UI to make it customizable according to what addon users themselves want. :P

Yes, I think library sprites should appear at a random position. It just makes sense. Library sprites are often used just for talking, as decoration, or for animation.
