### ISSUE TITLE
Use CDNs for libraries used in userscripts?

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#176]
Modules are nice because they don't pollute the global scope... However, it's not really great to have libraries inside the extension source code, that don't run in extension context at all. Extension reviewers might think there's something sketchy there, because minified code can hide malicious code. Of course, Vue and Redux are exception to this rule, since there's no way to load them through a CDN without requiring a less strict content security policy (or in the case of Redux, the traps wouldn't work at all, I think)

**Comment by WorldLanguages** [comment]
At the moment, these libraries would be `text-field-edit.js`, `moment.js`, and `md5.js`, as well as some in addons still in PR (like @Hans5958's - but don't worry, we'll accept these PRs then make the changes).
I propose having `addon.tab.loadScript(url)`, returning a promise that resolves when the script has executed (onload), or rejecting if it somehow failed (onerror).

**Comment by JeffaloBob** [comment]
what about how some libraries had to be modified slightly to work?

**Comment by Hans5958** [comment]
> 
> 
> what about how some libraries had to be modified slightly to work?

I think it will be a really rare case for that, but well, edge cases.

**Comment by WorldLanguages** [comment]
> what about how some libraries had to be modified slightly to work?

Those were modified to be converted into modules that can be imported directly to addon script modules - however, what I'm saying here is to just pollute the global scope (so any addon will be able to use `md5` if only one addon imports it)

**Comment by BoomerScratch** [comment]
> I propose having `addon.tab.loadScript(url)`, returning a promise that resolves when the script has executed (onload), or rejecting if it somehow failed (onerror).

But that is the same as `import()`, right?

**Comment by Hans5958** [comment]
I don't think it does.

**Comment by BoomerScratch** [comment]
@Hans5958 Use it like this:
```javascript
import("URL to script here")
```
For example:
```javascript
import("https://code.jquery.com/jquery-3.5.1.min.js"); // Imports JQuery
```

**Comment by Hans5958** [comment]
I never import modules on my day-to-day basis so I don't know.

**Comment by WorldLanguages** [comment]
> But that is the same as `import()`, right?

Kinda - if 2 addons want to load the same URL, and it has already been loaded by another addon, an `addon.*` API could figure that out. Keep in mind this is only for typical libraries that go in the global scope (like jQuery on `window.$`), modules are different.
