### ISSUE TITLE
[Variable Manager]: Allow Variable Name changing

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#1777]
We have got tons of feedback on this, so I mean... let's do it I guess.

**Comment by Endermaster3690** [comment]
yes do it

**Comment by Genius398** [comment]
> We have got tons of feedback on this, so I mean... let's do it I guess.

Go!

**Comment by mxmou** [comment]
Maybe also toggle the stage monitor?

**Comment by Endermaster3690** [comment]
> Maybe also toggle the stage monitor?

i have no idea what that means.

**Comment by mxmou** [comment]
> > Maybe also toggle the stage monitor?
> 
> i have no idea what that means.
> like toggle if the stage shows?

Toggle if the variable is visible on the stage.
