### ISSUE TITLE
Name Backpack Items and Folderize them

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#1795]
Would allow giving names to things in your backpack which could also allow you to put them in folders.

**Comment by lisa-wolfgang** [comment]
This would probably be easy enough for sprites and costumes -- not sure about scripts...

**Comment by Mr-Programmer-777** [comment]
Support! You could have a whole folder dedicated to Space SFX, Generic Platformer garbage or Cute cats.
Perhaps scripts could be named with a comment?
e.g: name = Basic Movement

**Comment by RedGuy12** [comment]
this has the same problems as an addon that renames backpack items tho
naming it when it's first added works fine
theres no way to rename without removing and adding back
we've rejected this multiple times on the discord
