### ISSUE TITLE
Allow addons to use extension icon double click?

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#18]
I got used to clicking once on the Scratch Notifier extension icon to open messages. Here, it wouldn't work since we want to implement popups (#16). Maybe we could find a way to trigger an action when the icon is double clicked, and allow the user to choose which addon can listen to that event.

**Comment by tb148** [comment]
My idea:
The user can choose which addon to display when single clicked, and double clicking opens a addon menu for other addons.

**Comment by WorldLanguages** [comment]
Doesn't look like it's possible to detect when the extension has been double clicked, as long as there's a popup.
