### ISSUE TITLE
Remove block extension

### ISSUE THREAD

**Issue by Mr-Programmer-777** [ScratchAddons/ScratchAddons#1801]
Trying out an extension or misclicked?
This would let you click "remove" on Pen or TTS to flush it down the loo.
Why not?

Yours bog-flushingly,
MrProgrammer777

**Comment by retronbv** [comment]
If there are no blocks from an extension, the extension is automagically removed. (This is normal scratch behavior)

**Comment by Mr-Programmer-777** [comment]
> If there are no blocks from an extension, the extension is automagically removed. (This is normal scratch behavior)

Really? I never knew that! They always stick like glue to me..

**Comment by Mr-Programmer-777** [comment]
All resolved! No bog-flushing.

**Comment by WorldLanguages** [comment]
@Mr-Programmer-777 I blocked you from this org for 1 day because you created too many issues/discussions in a very short period of time. I invite you to continue participating, but do not just spam ideas. Try to limit the amount of suggestions because we realistically won't implement most of them

**Comment by Hans5958** [comment]
> @Mr-Programmer-777 I blocked you from this org for 1 day because you created too many issues/discussions in a very short period of time. I invite you to continue participating, but do not just spam ideas. Try to limit the amount of suggestions because we realistically won't implement most of them

Eh, I think it's fine as long it is realistic and not malicious.

**Comment by Mr-Programmer-777** [comment]
@WorldLanguages Its fine. I just won't bother in future. But nobody got anywhere in life without trying, did they? That unreasonable ban you put on me was like a knife. I finally found my home online, found guys that are like me, and you come on, and talk about your members, people who found something great to do, like they don't matter. People help for a reason.

Yours blandly, annoyedly, and twiddling-thumbsly,
MrProgrammer777.

**Comment by Mr-Programmer-777** [comment]
Im going to leave it at that. I am going to go and enjoy my time on here. I don't like bringing out the agonized, painful side of me.

**Comment by TheColaber** [comment]
Don't get us wrong, we love hearing from ppl, but too much makes it too hard to focus on what's really important.

**Comment by Mr-Programmer-777** [comment]
> Don't get us wrong, we love hearing from ppl, but too much makes it too hard to focus on what's really important.

That's reasonable, and I respect that. Anyway, where can I start learning to make addons? I'm all ready and eager!

**Comment by TheColaber** [comment]
You would first need to learn some Javascript. Once you do, you can follow this tutorial: https://github.com/ScratchAddons/ScratchAddons/wiki/Creating-an-addon

**Comment by Mr-Programmer-777** [comment]
> You would first need to learn some Javascript. Once you do, you can follow this tutorial: https://github.com/ScratchAddons/ScratchAddons/wiki/Creating-an-addon

I already read that, where can I learn the JS I need?

**Comment by TheColaber** [comment]
https://www.youtube.com/watch?v=PkZNo7MFNFg and a lot of other tutorials online.

**Comment by Mr-Programmer-777** [comment]
I used w3schools.com for HTML, and now I'm alright at it.

**Comment by Mr-Programmer-777** [comment]
Okeydokes!

**Comment by Mr-Programmer-777** [comment]
@TheColaber 
> https://www.youtube.com/watch?v=PkZNo7MFNFg and a lot of other tutorials online.

I've been watching for 20 mins, I already have a really good understanding of variables. Thanks for reccomending this!

**Comment by RedGuy12** [comment]
@TheColaber<https://github.com/TheColaber> @MrProgrammer
https://www.youtube.com/watch?v=PkZNo7MFNFg doesn’t cover the DOM, that’s an essential part of basically all JS programming

**Comment by Mr-Programmer-777** [comment]
> @TheColaber<https://github.com/TheColaber> @MrProgrammer https://www.youtube.com/watch?v=PkZNo7MFNFg doesn’t cover the DOM, that’s an essential part of basically all JS programming

What does DOM stand for?

**Comment by RedGuy12** [comment]
Document Object Model, how JS interacts with the HTML

**Comment by TheColaber** [comment]
https://www.youtube.com/watch?v=xqozr9hlHeg this one covers it

**Comment by TheColaber** [comment]
Actually, tbh that one isn't so good... I would recommend this for DOM: https://www.youtube.com/watch?v=FIORjGvT0kk

**Comment by RedGuy12** [comment]
> Actually, tbh that one isn't so good... I would recommend this for DOM: [youtube.com/watch?v=FIORjGvT0kk](https://www.youtube.com/watch?v=FIORjGvT0kk)

here's the rest of the playlist https://www.youtube.com/watch?v=FIORjGvT0kk&list=PL4cUxeGkcC9gfoKa5la9dsdCNpuey2s-V

**Comment by Mr-Programmer-777** [comment]
Have you guys ever had it where your studying, and the teacher smacks down 2 more hefty books about english or maths, and says, "Now read these."?

**Comment by Mr-Programmer-777** [comment]
Hmm, I think I get this now.
So, JS can change stuff, move, or find things?

**Comment by Mr-Programmer-777** [comment]
(I think we should move to discussions)

**Comment by RedGuy12** [comment]
JS can do almost anything.

**Comment by Mr-Programmer-777** [comment]
I see that now! I've always liked using Python but JS looks like the cooler daniel.

**Comment by Mr-Programmer-777** [comment]
I made a discussion; https://github.com/ScratchAddons/ScratchAddons/discussions/1817
Just a heads up, I need to go to bed soon. If I don't respond, wait for me at about 4 or 5pm tommorow. (GMT)

**Comment by WorldLanguages** [comment]
> Eh, I think it's fine as long it is realistic and not malicious.

Sure, hence 1 day ban to calm things down :P

@Mr-Programmer-777 Welcome back

**Comment by Hans5958** [comment]
> Don't get us wrong, we love hearing from ppl, but too much makes it too hard to focus on what's really important.

Nah, if people at least give their interest by at least react to the issue, then I sure we can triage some that are highly interested.

> Sure, hence 1 day ban to calm things down :P

Nah, I'll give no ban if I were you.
