### ISSUE TITLE
Detect modifier keys

### ISSUE THREAD

**Issue by SheepTester** [ScratchAddons/ScratchAddons#1802]
It's not uncommon for Scratchers to want to be able to detect modifier keys (examples: [1](https://scratch.mit.edu/discuss/topic/365380/) [2](https://scratch.mit.edu/discuss/topic/375629/) [3](https://scratch.mit.edu/discuss/topic/398371/)).

Somewhat conveniently, [Scratch already does detect all keys](https://github.com/LLK/scratch-gui/blob/c264b46f614bfbe0692a64da007911fb090c5714/src/lib/vm-listener-hoc.jsx#L90-L94). Unfortunately, [all modifier keys are explicitly ignored by the VM](https://github.com/LLK/scratch-vm/blob/faa58a517f673f16fdaf74cc467d482410c0e538/src/io/keyboard.js#L62-L65). It also [won't let you try to detect multiletter keys](https://github.com/LLK/scratch-vm/blob/develop/src/io/keyboard.js#L98-L101) with the key _ pressed? block.

To implement this, perhaps it may be sufficient to use an addon trap and override the Keyboard methods with ones that allow multiletter key names (thus allowing modifier keys).  I can make a PR for this if you think this feature would be a good fit for your extension.

However, a possible downside of adding this feature might be that it encourages projects that rely on this addon shared on the Scratch website, if that's a concern. Also, with the above solution, keys can be detected using the value from [event.key](http://keycode.info/); would that be the best solution? The key name won't be localised, and some keys might have unintuitive names like `Meta`.

Also, some Scratchers might want to be able to distinguish between left and right modifier keys or certain mouse buttons (left vs. right, for example). These can be done by calling `vm.postIOData` with custom values, but would that be the best solution, and would it fit with this addon?

**Comment by retronbv** [comment]
What would happen for people not using SA? It just wouldn’t work?

**Comment by SheepTester** [comment]
> What would happen for people not using SA? It just wouldn’t work?

Indeed, the key _ pressed? block would just always return false. That's a downside of this since probably not everyone would support alternative keykinds, and it would promote projects that require SA to work. ¯\\\_(ツ)_/¯

**Comment by TheColaber** [comment]
This type of thing would be ok for mods like Turbowarp, but not for scratch addons since it would be on the actual website of scratch, and 99% of users won't have the functionailty.

**Comment by WorldLanguages** [comment]
Yeah, we want to avoid blocks that behave differently with and without SA (only exception: sa-pause)
