### ISSUE TITLE
Block dropdowns menus and connected comment outlines having the wrong color

### ISSUE THREAD

**Issue by Endermaster3690** [ScratchAddons/ScratchAddons#1806]
**Describe the bug**

Dropdown and comments connected to a block outlines are the original block colors instead of the modified ones.

**To Reproduce**

Open a project and create a comment connected to a block. Or get a block with dropdowns. With dropdowns get a custom color a bit different than the original. With comments make the custom color very see-able from yellow.

**Expected behavior**

read describe the bug

**Screenshots**

![lancer](https://user-images.githubusercontent.com/80355301/110701457-cd1a0e80-81b6-11eb-821a-6cadd4e59202.png)

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome
- Version: idk

**Additional context**

no

**Comment by WorldLanguages** [comment]
Not sure I understand what the bug is

**Comment by Endermaster3690** [comment]
> Not sure I understand what the bug is

Try this:
Set the extension color to black.
Get a text to speech change voice block and open its dropdown.
Look at the dropdown list outlines.
The dropdown list outlines are not black. Instead they are the original extension color.

Did that show you the bug?

**Comment by RedGuy12** [comment]
Can't repo.

**Comment by Endermaster3690** [comment]
> Can't repo.
> 
> Can you provide a `scratch-addons-settings.json`?

I am using the Editor Dark mode setting in Editor dark theme. Maybe that'll help.
Or you have the original block colors.

Anyways i have no idea where i get `scratch-addons-settings.json` and how to put it here.

**Comment by WorldLanguages** [comment]
Ohh, the outlines are the important part

**Comment by Endermaster3690** [comment]
> Ohh, the outlines are the important part

can you add a fix for this bug?
