### ISSUE TITLE
Cat Blocks doing weird things to hat input blocks

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#1809]
![image](https://user-images.githubusercontent.com/72760579/110719120-437c3800-81da-11eb-8137-6be441f5f43d.png)
![image](https://user-images.githubusercontent.com/72760579/110719529-04021b80-81db-11eb-87d4-bf50f4545a53.png)

It might look fine at first, but change the input to a smaller, or larger length value, and the block won't update its size. The problem is that I used DOM to add the ears and stuff. However, I should do this completely with Blockly. However scratch has changed stuff with Blockly (a surprise right lol) so I can't exactly just copy and paste code.

If you don't know what I am talking about or can't repo, don't worry, leave it to me to solve this issue.

**Comment by Endermaster3690** [comment]
that happened to me. oh yeah the 2 30 prevent is my image. Anyways i hope this gets fixed.

**Comment by FunctionalMetatable** [comment]
that happened to me too but i wasn't bothered to file a bug report :P
