### ISSUE TITLE
Bug with muting project player

### ISSUE THREAD

**Issue by HTMLwebcoder** [ScratchAddons/ScratchAddons#1813]
basically when you have the project player muted, then pause the player with the pause button, then play, the sound is not muted even when the mute icon is displaying

**To Reproduce**
1: import a sound that plays for at least 30 seconds
2: play the project player and mute.
 3: pause the project player. 
4: play the project player.

make sure to have audio turned on and watch the WHOLE video i linked to this post

https://user-images.githubusercontent.com/80441526/110738983-80055f00-81ed-11eb-9524-a90524909573.mp4

and thats the bug!
(if you dont hear anything then try importing a longer sound or looping it)

**Device (please complete the following information):**

- OS: [Chrome OS] 
- Browser [google chrome]
- Version [please specify (extension version, OS version, browser version...?)]

**Comment by superscratch444tre** [comment]
I have the same error. 
Also when muting a project when running, then stopping it with the red sign, and then starting it again, it says it's muted but i can still hear the music.

**Comment by TheColaber** [comment]
All these problems were fixed by #1803
