### ISSUE TITLE
Ability to Remix your own Projects

### ISSUE THREAD

**Issue by RedLight-Scratch** [ScratchAddons/ScratchAddons#1816]
**Describe the new addon**

This addon would let you remix your own project, and probably add the remix button back to the project page. I am not sure if this is possible, but it would be a lot quicker than downloading the project then uploading it in a new project.

**Comment by lisa-wolfgang** [comment]
There's a workaround for this where you sign in with an alt account and load the project, then on a different tab, sign back into your main account, then go back to the project and remix. I would imagine that if the site allows this already, it wouldn't be too much trouble to make an addon for it, similar to how the "Feature unshared projects" addon had a workaround before it was implemented.

**Comment by TheColaber** [comment]
Scratch has an API for this thankfully... `https://projects.scratch.mit.edu/?is_remix=1&original_id=ID&title=TITLE`

**Comment by Genius398** [comment]
> **Describe the new addon**
> 
> This addon would let you remix your own project, and probably add the remix button back to the project page. I am not sure if this is possible, but it would be a lot quicker than downloading the project then uploading it in a new project.

2 ways to do this without the addon:

1. Copy your project by going to Project<Project Editor<File menu<Copy
2. - Log in to a different account
    - Go inside the project you want to remix
    - Open another Scratch tab, and log out of it, then log into your main account (the one with the project you're remixing)
    - Switch back to the first tab and click the "remix" button
    That's it! The reason it works is that you are technically logged into your main account when you press remix, so that's 
    where it saves the remix to.

**Comment by CuriousG2** [comment]
> 
> 1. Copy your project by going to Project<Project Editor<File menu<Copy

I forgot about that! That is probably the best way to do it.

**Comment by WorldLanguages** [comment]
"Copy" does not actually remix the project, it clones it. This could still be an addon

**Comment by Genius398** [comment]
> "Copy" does not actually remix the project, it clones it. This could still be an addon

But it is still possible!

Log in to a different account
Go inside the project you want to remix
Open another Scratch tab, and log out of it, then log into your main account (the one with the project you're remixing)
Switch back to the first tab and click the "remix" button
That's it! The reason it works is that you are technically logged into your main account when you press remix, so that's
where it saves the remix to.







But it will be easier with an addon so that users don't have to make 2 accounts

**Comment by Genius398** [comment]
> That is probably the best way to do it.

Not the best way, but the second-best way

**Comment by WorldLanguages** [comment]
> But it is still possible!

When did I say it's not...

**Comment by Genius398** [comment]
> > But it is still possible!
> 
> When did I say it's not...

ok

**Comment by Genius398** [comment]
Any pulls?
