### ISSUE TITLE
Share Button to Project

### ISSUE THREAD

**Issue by Resince** [ScratchAddons/ScratchAddons#1821]
**Describe the new addon**

This addon would add a share button on project pages that would allow users to easily share projects on sites such as Twitter or Facebook via the built-in intent prompts. (Could be merged with the copy link button)

![image](https://user-images.githubusercontent.com/49600150/110884021-3b370200-8299-11eb-87cd-c136f481483d.png)

**Comment by Secret-chest** [comment]
Also on whatsapp using wa.me

**Comment by Genius398** [comment]
good idea

@WorldLanguages

**Comment by lisa-wolfgang** [comment]
I'm a little confused... wouldn't the Copy Link button suffice for this?
What exactly do you want to "share" on the other sites?

**Comment by apple502j** [comment]
It's easy, Scratch even had this feature for a while

**Comment by RedGuy12** [comment]
> I'm a little confused... wouldn't the Copy Link button suffice for this?
> What exactly do you want to "share" on the other sites?

links to projects

**Comment by mxmou** [comment]
> > I'm a little confused... wouldn't the Copy Link button suffice for this?
> > What exactly do you want to "share" on the other sites?
> 
> links to projects

But you can do that using the Copy link button already.

**Comment by Mr-Programmer-777** [comment]
No support. There's no point.

**Comment by Resince** [comment]
> > > I'm a little confused... wouldn't the Copy Link button suffice for this?
> > > What exactly do you want to "share" on the other sites?
> > 
> > 
> > links to projects
> 
> But you can do that using the Copy link button already.

On any site, you can in theory copy and paste the link however this would actively promote sharing and offer a more direct solution in comparison to the current options. It'd allow for quick-sharing considering the fact that you can use intent prompts that social media sites offer to construct a template of what a user might want to send. For example:

> Check out the project ${projectName} on Scratch. ${projectURL}

While this isn't anything revolutionary, it could easily enhance a user's experience.

**Comment by Barthdry** [comment]
You can use embed or link but anyway good idea

**Comment by Genius398** [comment]
I will try to do this in #1986

**Comment by WorldLanguages** [comment]
An addon like this would probably be rejected.
