### ISSUE TITLE
Live project collaboration

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#1829]
**Describe the new addon**

This is definitely something for the backlog, as it will require lots of discussion on logistics and lots of bug testing.

Similar to Google Docs, this would allow users to live-edit Scratch projects with each other. There could be an "invite" button in the top menu bar of the editor that would set which users are allowed to edit a certain project. As each user edits the project, their changes are sent to all other users (via a service hosted on scratchaddons.com?) and the editor makes the changes accordingly.

Note that this is currently rejected by the Scratch Team due to the potential for private messaging, but realistically, users with the ability to coordinate a time to use this feature already have private messaging due to Scratch Addons discussion on Scratch being prohibited.

**Comment by RedGuy12** [comment]
Would require a server which I think we’re trying to do without.

**Comment by WorldLanguages** [comment]
Realistically impossible.

**Comment by Endermaster3690** [comment]
> Would require a server which I think we’re trying to do without.

yeah

> Realistically impossible.

i guess

**Comment by Mr-Programmer-777** [comment]
The ST will NOT like this at all...
No support for this to be added.
It's a brilliant idea and I would love to have it, but that would really be pushing it.

**Comment by WorldLanguages** [comment]
> The ST will NOT like this at all...

Advertising extension is already prohibited so I don't think it would make a difference, tbh

**Comment by Endermaster3690** [comment]
Yeah the ST wont like it. Close the thread and don't add this.

**Comment by lisa-wolfgang** [comment]
I guess it's a bad idea to give the ST an actually legitimate reason to dislike Scratch Addons.
