### ISSUE TITLE
[Feature] Add a "Leave feedback" and "Visit on GitHub" button to the extension's menu.

### ISSUE THREAD

**Issue by NoobTracker** [ScratchAddons/ScratchAddons#183]
Yeah, exactly that. Add a "Leave feedback" and "Visit on GitHub" button to the extension's menu. The "Leave feedback" link would go to a page for creating a new issue with the type "Feedback" with some prewritten stuff and Visit on GitHub just goes to the main page.

**Comment by WorldLanguages** [comment]
There's now a "send feedback" button, which takes the user to the website where there's a noticeable link to GitHub.
