### ISSUE TITLE
[New addon] Markdown support for comments

### ISSUE THREAD

**Issue by NoobTracker** [ScratchAddons/ScratchAddons#184]
**Describe the new addon**

As you might know, comments on Scratch don't have any sort of formatting options. Besides using unicode fonts but you know what I mean. Now how should that work?

When you write a comment, there would be a markdown switch next to the submit button. When you enable that switch, you get those buttons you also have here on GitHub. At the same time, it sets something up so some nonsense will be added to your comment to show that it uses markdown, an invisible unicode character, or maybe even a visible one since that extension will just hide it for everyone who has it enabled.
For file uploading Jeffalo's image uploader would be used.
The addon could add support for blank lines.

There would be options to enable Markdown for comments by defauls and for interpreting Markdown even if there is not that character.

Why Markdown and not BBCode, you might ask. The reason is simple: Markdown uses less characters and since comments have a limit that's kinda neat.

**Link to the new addon**

Doesn't exist so far.

**Comment by Hans5958** [comment]
ST wouldn't like those hacky things done on the website. Just look what happens on the first version of isOnline a while ago.

**Comment by NoobTracker** [comment]
Well, adding the support for _this_ and **this** isn't exactly a really hacky thing - it's like adding emoji support if the comments had none - anyone also without the extension can read it, but those with it can do it better.

**Comment by Hans5958** [comment]
I still afraid, but I don't know, I'm a guy who is not using Scratch for a while. Probably @WorldLanguages knows better than me.

**Comment by NoobTracker** [comment]
As I said, that's like replacing :) with that emoji so not really extrem stuff. Yep, let's ask @WorldLanguages .

**Comment by NoobTracker** [comment]
Has anyone an idea where you can get a markdown interpreter on GitHub?

**Comment by NoobTracker** [comment]
Okay, I asked Za-Chary.

**Comment by NoobTracker** [comment]
Also, has anyone an idea how to let the script run for every comment, also when you load new ones? @JeffaloBob

**Comment by YOYITsM3M8** [comment]
Forever loop?

**Comment by NoobTracker** [comment]
I'm not sure if that's a good idea ... it would be better when it just executes once as soon as a new element that belongs to a certain class is loaded.

**Comment by WorldLanguages** [comment]
> ST wouldn't like those hacky things done on the website. Just look what happens on the first version of isOnline a while ago.

Unrelated.

**Comment by WorldLanguages** [comment]
Anyway, please no. This is useless if only a few people are able to see the markdown.

**Comment by WorldLanguages** [comment]
whoops

**Comment by NoobTracker** [comment]
> 
> 
> Anyway, please no. This is useless if only a few people are able to see the markdown.

Well, one of the cooler things about markdown is that anyone can understand it and for the few people who use it can see it a bit better. Also, having the option to upload images in comments in also cool, right?

**Comment by NoobTracker** [comment]
And it could use another weird unicode character for a new line.

**Comment by NoobTracker** [comment]
@WorldLanguages What exactly is the reason why you think that it's useless?

**Comment by NoobTracker** [comment]
Using the location?! Gangstas .... but how?

**Comment by Hans5958** [comment]
Just go search for isOnline code on GitHub or his GitHub. It is somewhere there.

**Comment by NoobTracker** [comment]
Instantly found the scratch wiki page

**Comment by NoobTracker** [comment]
Anyway, has anyone an idea how you could make a script run each time a new element belonging to a certain class is loaded? That would be pretty interesting and also useful to know for other stuff I guess.

**Comment by WorldLanguages** [comment]
@NoobTracker Constantly run `addon.tab.waitForElement`. To classify elements as "already seen", add them a class like `addonname-already-seen` then in the selector required by waitForElement, add `:not(.addonname-already-seen)`

**Comment by NoobTracker** [comment]
Hey, that's a pretty good idea! So I just run that in a `while(true){}`?

**Comment by NoobTracker** [comment]
@WorldLanguages Wouldn't that break everything and create those "script not responding" problems?

**Comment by WorldLanguages** [comment]
Nope

**Comment by NoobTracker** [comment]
Why not?
(and do I need to use `await`, like the last time?)

**Comment by mxmou** [comment]
> Has anyone an idea where you can get a markdown interpreter on GitHub?

[Here?](https://github.com/markdown-it/markdown-it)



> Why not?
> (and do I need to use `await`, like the last time?)

Probably because `await` runs asynchronously.

**Comment by NoobTracker** [comment]
> 
> 
> Probably because `await` runs asynchronously.

You see, I'm really not the high-level guy ....

**Comment by Hans5958** [comment]
> Probably because `await` runs asynchronously.
Actually, `await` runs synchronously. It makes asynchronous functions run synchronously by waiting for a response.

**Comment by easrng** [comment]
> > Probably because `await` runs asynchronously.
> > Actually, `await` runs synchronously. It makes asynchronous functions run synchronously by waiting for a response.

That's not true. `await` makes a promise act synchronous, but it's still async and won't lock up the browser.

**Comment by easrng** [comment]
> > Anyway, please no. This is useless if only a few people are able to see the markdown.
> 
> Well, one of the cooler things about markdown is that anyone can understand it and for the few people who use it can see it a bit better. Also, having the option to upload images in comments in also cool, right?

Yeah, that's why I like this.

**Comment by WorldLanguages** [comment]
`await` is just syntactic sugar, it means "the code below is the `then` callback, even tho it's not really a callback."

**Comment by Explosion-Scratch** [comment]
> Anyway, please no. This is useless if only a few people are able to see the markdown.

Umm, 10,000 people?

**Comment by pufferfish101007** [comment]
> > Anyway, please no. This is useless if only a few people are able to see the markdown.
> 
> Umm, 10,000 people?

10000 people who all use sa aren't going to read a comment
That's less than 0.02% of all scratch users.

**Comment by retronbv** [comment]
> > > Anyway, please no. This is useless if only a few people are able to see the markdown.
> > 
> > 
> > Umm, 10,000 people?
> 
> 10000 people who all use sa aren't going to read a comment
> That's less than 0.02% of all scratch users.

I donut understand what the point of that message is

**Comment by NoobTracker** [comment]
omg SA took off? had no clue that happened. I thought that maybe 100 people use it.

**Comment by retronbv** [comment]
> omg SA took off? had no clue that happened. I thought that maybe 100 people use it.

Welcome back NT lol

**Comment by mxmou** [comment]
> omg SA took off? had no clue that happened. I thought that maybe 100 people use it.

It was released as an update to griffpatch's Messaging Extension so it already had 3000 users at launch.

**Comment by NoobTracker** [comment]
> 
> 
> > omg SA took off? had no clue that happened. I thought that maybe 100 people use it.
> 
> Welcome back NT lol

Welp, since I'm (_false_!) banned on Scratch, I don't really see a reason in coding or thinking about addons.

**Comment by retronbv** [comment]
> > > omg SA took off? had no clue that happened. I thought that maybe 100 people use it.
> > 
> > 
> > Welcome back NT lol
> 
> Welp, since I'm (_false_!) banned on Scratch, I don't really see a reason in coding or thinking about addons.

I am also _false_ banned but still have time for this lol

**Comment by NoobTracker** [comment]
> 
> 
> > > > omg SA took off? had no clue that happened. I thought that maybe 100 people use it.
> > > 
> > > 
> > > Welcome back NT lol
> > 
> > 
> > Welp, since I'm (_false_!) banned on Scratch, I don't really see a reason in coding or thinking about addons.
> 
> I am also _false_ banned but still have time for this lol

Why did that happen?

**Comment by Secret-chest** [comment]
Why newlines in comments but not markdown?

**Comment by BroJac5246** [comment]
> Why newlines in comments but not markdown?

Because the newlines actually exist and just aren't shown.
