### ISSUE TITLE
Error when changing theme settings

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#1841]
**Describe the bug**

When changing the settings of a theme while it's running in a tab, it behaves as if the settings were reset and an error appears in that tab's console. This is because line 52 of `content-scripts/cs.js` calls `injectUserstylesAndThemes` without providing the `addonsWithUserstyles` argument (it should probably be an empty array), causing an error on line 68.

**To Reproduce**

1. Enable editor dark mode
2. Open the editor
3. Change the dark mode version setting
4. Go back to the editor and open the console

**Expected behavior**

The settings would change correctly.

**Comment by apple502j** [comment]
Regressed by #1753
