### ISSUE TITLE
Add RTL support

### ISSUE THREAD

**Issue by wgyt** [ScratchAddons/ScratchAddons#1844]
**Is your feature request related to a problem? Please describe.**
Our UI doesn't support RTL for languages like Arabic
**Describe the solution you'd like**
Add RTL Support
**Describe alternatives you've considered**
idk
**Additional context**
![image](https://user-images.githubusercontent.com/68466727/111031711-e00b2980-83d6-11eb-9d04-ab344f216231.png)

**Comment by RedGuy12** [comment]
the main scratch website keeps the text right-aligned, why cant we do the same?

**Comment by mxmou** [comment]
> the main scratch website keeps the text right-aligned, why cant we do the same?

We can, but we also need to mirror some UI elements.

**Comment by RedGuy12** [comment]
> > the main scratch website keeps the text right-aligned, why cant we do the same?
> 
> We can, but we also need to mirror some UI elements.

oop meant left-aligned

**Comment by mxmou** [comment]
> oop meant left-aligned

The editor supports RTL though.
