### ISSUE TITLE
[New addon] Replacing /discuss/youtube links with true youtube links

### ISSUE THREAD

**Issue by NoobTracker** [ScratchAddons/ScratchAddons#185]
**Describe the new addon**

It would just replace links for those annoying embedded videos with real videos. It would have two parts:
The first one replaces the links for /discuss/youtube with true youtube links so when you actually click somewhere where someone else wants to rickroll you without having the extension you get to the YT page instead. It may just be only triggered when you visit /discuss/youtube so you get redirected from there in case it isn't that easy to do that straight with the link. 
The second one replaces the y in youtube with %79 so the censor has no clue that you just fooled it. That could just be done for every URL since it changes more or less nothing. It happens when you create a link in the forums. This part effects everyone so you can finally link something with `?t=whatever`.
The second part might be removed and is optional in case that causes issues.

**Link to the new addon**

Doesn't exist so far.

**Comment by Hans5958** [comment]
@WorldLanguages close pls
