### ISSUE TITLE
Scrolling don't work after selecting custom block.

### ISSUE THREAD

**Issue by ZdravPrav** [ScratchAddons/ScratchAddons#1855]
After the new update , when you select custom block using "Find" (developer tools) , you can't scroll up and down anymore,
and you can again scroll when you manually change position in editor, or zoom/unzoom, or move script.

**Comment by lisa-wolfgang** [comment]
@ZdravPrav Could you specify which version specifically you have? When you click on the extension, the version is listed next to the title "Scratch Addons".

**Comment by ZdravPrav** [comment]
v1.11.0 I have auto update I guess

**Comment by ZdravPrav** [comment]
> @ZdravPrav Could you specify which version specifically you have? When you click on the extension, the version is listed next to the title "Scratch Addons".

v1.11.0 I have auto update I guess

**Comment by WorldLanguages** [comment]
@ZdravPrav Thanks for reporting, this was fixed by #1849. Coming to stable tomorrow with v1.11.1

**Comment by WorldLanguages** [comment]
Duplicate of #1834

**Comment by WorldLanguages** [comment]
(Please tell me if it's not exactly the same issue, but it likely is)

**Comment by mxmou** [comment]
I don't think this is a duplicate: @ZdravPrav was able to scroll again after interacting with the blocks.

**Comment by Endermaster3690** [comment]
> (Please tell me if it's not exactly the same issue, but it likely is)

they couldn't scroll after getting a custom block with find. I didn't use custom blocks.
