### ISSUE TITLE
API builder

### ISSUE THREAD

**Issue by Ani-Xan** [ScratchAddons/ScratchAddons#186]
Have you guys ever heard of [WrapAPI](https://wrapapi.com/)? It could be really helpful in building API's for Scratch and @ScratchAddons

**Comment by NoobTracker** [comment]
I've never heard of that before (but I'm also not that into web developement).
What exactly do you want to discuss?

**Comment by apple502j** [comment]
Already WIP: https://github.com/hamptonmoore/FluffyScratch

**Comment by Ani-Xan** [comment]
> Already WIP: https://github.com/hamptonmoore/FluffyScratch

Interesting. @NoobTracker, I thought that it should be taken into consideration that this is a helpful tool that could benefit @ScratchAddons

**Comment by apple502j** [comment]
This is not our job. We only handle client side stuff.

**Comment by Ani-Xan** [comment]
@apple502j Okay.
