### ISSUE TITLE
Spelling Issues

### ISSUE THREAD

**Issue by Barthdry** [ScratchAddons/ScratchAddons#1865]
**Variable Manager**

Variable Manager is good but there are some english spelling mistakes in english.
Spelling mistake. I have also spotted some other english mistakes

Thanks for using the variable manager addon, we're intrested in what you think about it! Send feedback

**Comment by apple502j** [comment]
Can you list all mistakes?

**Comment by RedGuy12** [comment]
I think they are British vs American English mistakes
________________________________

**Comment by apple502j** [comment]
Fixed in 1.11.1
