### ISSUE TITLE
Show the time of when a project was shared

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#1868]
**Describe the new addon**
This addon will show the time of when a project was shared. In the setting of the addon, the user will be able to:
1. Choose their time zone
2. Switch between 12-hour and 24-hour clock

Example: 
1. (12-hour clock) Shared at [time] [AM/PM] on [date]
2. (24-hour clock) Shared at [time] on [date]

**Comment by WorldLanguages** [comment]
If implemented, should be part of "Last edit tooltip" addon

**Comment by Genius398** [comment]
> If implemented, should be part of "Last edit tooltip" addon

Yes

**Comment by Secret-chest** [comment]
The time zone and format setting should be changed from More Settings, so it can be used by other time-related addons.

**Comment by Genius398** [comment]
> The time zone and format setting should be changed from More Settings, so it can be used by other time-related addons.

Yes I forgot to mention that

**Comment by Genius398** [comment]
Good idea or not?

**Comment by FunctionalMetatable** [comment]
gonna try make this

**Comment by Genius398** [comment]
> gonna **try** make this, not guaranteed
> 
> edit: see #1940

Thanks!
