### ISSUE TITLE
Auto-show editor extensions with Video Sensing will force Video Sensing on all your projects, even without opening the editor.

### ISSUE THREAD

**Issue by firecoder1** [ScratchAddons/ScratchAddons#1869]
**Describe the bug**

Using auto-show editor extensions with video sensing enabled will turn on video automatically, on the editor and the website. This occurs even when you've never opened the editor with this addon enabled. You can fix with a "turn video off" block.

**To Reproduce**

1. Open one of your projects with no video sensing code.
2. Click the green flag and video sensing will enable itself.

**Expected behavior**

I expect that video will not turn on, at least until I open the editor.

**Screenshots**

**Device (please complete the following information):**

- OS: [e.g. iOS] Windows
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] Chrome version is 89.0.4389.82 (Official Build) (64-bit), Scratch Addons version is 1.11.0

**Additional context**
It seems that this will not enable automatically when in someone else's project on the site.

**Comment by mxmou** [comment]
The ability to auto-show video sensing will be removed in version 1.11.1 because of the problems it causes.

**Comment by firecoder1** [comment]
OK, makes sense (also sorry for late reply)
