### ISSUE TITLE
[New addon] Extension for typing more in comments

### ISSUE THREAD

**Issue by NoobTracker** [ScratchAddons/ScratchAddons#187]
**Describe the new addon**

There are some unicode characters like ﬃ that are multiple characters at once - and the great thing is: They only count as a single character! So, as you might have guessed, we could make a script that can, when enabled, replace standard characters with combined ones to save space in comments! 
I'm not sure how many of those combined characters exist and if their unicode numbers are predictable, but if, then it would be a great script, right?

**Link to the new addon**

Doesn't exist so far.

**Comment by apple502j** [comment]
I don't think this gets added. We certainly don't want users to advertise ScratchAddons to read comments they send.

**Comment by WorldLanguages** [comment]
Would be cool, but not worth it - it would break screen readers for little benefit.

**Comment by NoobTracker** [comment]
@apple502j It wouldn't do stuff like that! Those are just unicode characters anyone can see. Our script would just help to replace your text with those.

**Comment by NoobTracker** [comment]
@WorldLanguages It would turn itself on as soon as you have more then 500 characters I would say - that way you can get the last 20 characters you wanted to write into the post without creating a second comment.

**Comment by NoobTracker** [comment]
> 
> 
>  it would break screen readers

Well, when the unicode characters are predictable, then the screen readers might add that. And I don't know about you, but i personally think that it isn't that realistic that someone blind uses a *visual* programming language.
And the extension might just replace them.

**Comment by apple502j** [comment]
Scratch Team does not like to use such letters, iirc - because it can be used to bypass filters. After all, if W_L says no, it is no.

**Comment by WorldLanguages** [comment]
Yeah, I agree on the fact screen readers are dumb, and should be smarter. But still, we're trying to have addons with enough code quality, and doing that while messing with textareas is difficult. Not worth it for a few more extra chars.

**Comment by NoobTracker** [comment]
Ah okay I completely ignored the fact that you can bypass filters doing that. I wonder if there are websites that do that for you.
And @WorldLanguages' main point was that it can break screen readers and, as I said, that makes no sense imo.

**Comment by apple502j** [comment]
I'm sure this is now under the "rejected" category.

**Comment by NoobTracker** [comment]
Yep.

Well, I also wasn't able to find much information on such characters - none to be precise. So I guess I have no clue how to do something like that.

**Comment by WorldLanguages** [comment]
Don't take the mention of screen readers literally - I know it's very unlikely it will affect anyone. The main point is that it's too hacky and may have weird side effects (might trigger the bad word filter, or allow you to bypass it). Those do not qualify for a rejection by themselves, but in this case, it's just not worth it.

**Comment by NoobTracker** [comment]
Ah okay, that's what you mean. Well, as I said, I can't find any information about them and how to create them so I guess I'm screwed anyway.

**Comment by NoobTracker** [comment]
Okay, now I found out more about them - it seems like there are only like 5 of those things, all of them with ff.

**Comment by mxmou** [comment]
> Okay, now I found out more about them - it seems like there are only like 5 of those things, all of them with ff.

There are [quite a lot](https://en.wikipedia.org/wiki/Orthographic_ligature#Ligatures_in_Unicode_(Latin_alphabets)) of them actually, but most of them except ff, ffi, ffl, fi and fl aren't very useful.

**Comment by NoobTracker** [comment]
Well I wouldn't call 100 or something that much. 26³=17576. That's a bit more then 100.
