### ISSUE TITLE
Auto-hide block palette hide animation doesn't work

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#1876]
**Describe the bug**

When the auto-hide block palette addon is enabled, showing the block palette has an animation but hiding it doesn't.

**To Reproduce**

1. Enable auto-hide block palette
2. Go to the editor and let the palette hide
3. It hides instantly, with no animation

**Expected behavior**

It would be animated.

**Comment by TheColaber** [comment]
Um... it should... Did you set the setting to no animation?

**Comment by mxmou** [comment]
> Um... it should... Did you set the setting to no animation?

No, the animation duration is default. It looks like this:
![gif](https://user-images.githubusercontent.com/51849865/111164873-bc92db00-859e-11eb-9ef2-049976b1dfd2.gif)

When the palette shows, it's animated correctly, but not when it hides.

**Comment by TheColaber** [comment]
Am not able to repro... mine animates in and out.

**Comment by mxmou** [comment]
Weird. I'm on Chrome 89, if that affect this.

**Comment by TheColaber** [comment]
I am also... not sure if there is something going on in the css...

**Comment by WorldLanguages** [comment]
@mxmou What hide palette mode?

**Comment by mxmou** [comment]
@WorldLanguages All modes. This could be fixed by not applying the `sa-flyoutClose` class until the animation finishes.

**Comment by mxmou** [comment]
Is there a particular reason for the addon to use CSS animations and not transitions?

**Comment by WorldLanguages** [comment]
Probably not

**Comment by mxmou** [comment]
> Probably not

Then using transitions would probably be the best fix.
