### ISSUE TITLE
Palette is initially visible when auto-hide block palette is enabled

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#1877]
**Describe the bug**

Auto-hide block palette doesn't hide the palette when opening the editor, which doesn't make sense.

**To Reproduce**

1. Enable auto-hide block palette
2. Open the editor
3. The palette is visible
4. Move your mouse over the palette and back out
5. It's now hidden

**Expected behavior**

It would be initially hidden.

**Comment by WorldLanguages** [comment]
Does this happen in all 3 modes?

**Comment by mxmou** [comment]
@WorldLanguages Yes.

**Comment by mxmou** [comment]
#2263 certainly didn't fix this.

**Comment by WorldLanguages** [comment]
Whoops, right
