### ISSUE TITLE
Devtools: "Send to top" and "Send to bottom" should have lowercase names

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#1878]
**Describe the bug**

`editor-devtools` adds new context menu items to costumes, called "Send to top" and "Send to bottom". For consistency with the rest of the context menu their names should be lowercase.

**Comment by mxmou** [comment]
Reopening because #2146 reverted the name change. The strings for the help popup and for the context menu should be separate.

**Comment by mxmou** [comment]
@apple502j See the above comment.

**Comment by WorldLanguages** [comment]
Whoops, I saw these names being changed and I thought about this issue but I forgot to actually look at it.
Moving to next milestone to avoid further localization work

**Comment by griffpatch** [comment]
Hey guys - It is my belief that this is actually the correct case for Scratch. Options like "Clean up Tiles" are cased this way. It's just that the costumes tab options are usually single word so this does not come up here. It would probably still make sense to keep it as I made it here with capital last words (I am actually in favor of all sentence case throughout, but that's not how it's done in Scratch so!)

**Comment by WorldLanguages** [comment]
@mxmou should we close this?

**Comment by mxmou** [comment]
@WorldLanguages To me this still seems like an inconsistency. Although all lowercase was chosen because items are single words, I think making items with multiple words lowercase is better than mixing two different capitalization styles in a single menu.

Alternatively, devtools could change all items of all context menus to be capitalized.

**Comment by WorldLanguages** [comment]
> Alternatively, devtools could change all items of all context menus to be capitalized.

You mean devtools could change the capitalization of vanilla Scratch context menu items?

**Comment by mxmou** [comment]
> > Alternatively, devtools could change all items of all context menus to be capitalized.
> 
> You mean devtools could change the capitalization of vanilla Scratch context menu items?

Yes. This is a strange solution but it's an option.

**Comment by WorldLanguages** [comment]
Eh, this still feels wrong to me:
![image](https://user-images.githubusercontent.com/17484114/115778379-f5d41d00-a38c-11eb-9754-be46de3fa51c.png)

I vote for all lowercase

@griffpatch Speak now or forever hold your peace :P

**Comment by griffpatch** [comment]
Me too
