### ISSUE TITLE
Search bar covers flag in editor with thin window size

### ISSUE THREAD

**Issue by oof-le-oof** [ScratchAddons/ScratchAddons#1881]
**Describe the bug**

"Find" search bar covers green flag at small window sizes

**To Reproduce**

1. Confirm "Find" search bar is on in Settings
2. Open a Scratch project editor
3. Resize window so it's thinner

**Expected behavior**

Search bar gets thinner, disappears entirely, or displaces Flag/Stop/Pause (if enabled)

**Screenshots**

![image](https://user-images.githubusercontent.com/74682558/111186116-ec76ba00-856f-11eb-878e-bd0b42f03f91.png)

**Device:**

- OS: Windows 10
- Browser: Chrome
- Version: 89.0.4389.82

**Comment by WorldLanguages** [comment]
Not sure whether to add `scope: core` or `scope: addon` here tbh, who should be in charge of this not happening? Find bar?

**Comment by mxmou** [comment]
@WorldLanguages Probably the find bar (it could have something like `max-width: calc(100% - something)`).
