### ISSUE TITLE
The settings page looks like the addons tab in the popup on small window sizes

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#1882]
**Describe the bug**

For some reason the removal of the top bar when the settings page is opened in the popup (#1006) is done using a media query. This means that on small window sizes (width < 540px) the settings page has no top bar.

**To Reproduce**

1. Open the settings page
2. Decrease the window width until the top bar disappears.

**Expected behavior**

The top bar should be there (removing it should be done by setting a class, not using a media query). Clicking the sidebar button in the top bar when the window is small is supposed to open the sidebar as a dropdown menu, which also appears to have been removed in #1006.

**Comment by GrahamSH-LLK** [comment]
The dropdown part was actually removed in my CSS redo pr. I moved files and never added an import

**Comment by mxmou** [comment]
> The dropdown part was actually removed in my CSS redo pr. I moved files and never added an import

I think it would be a good idea to re-add it because it makes the page usable even if the window is small.

**Comment by GrahamSH-LLK** [comment]
I know. It's already fixed in #1832

**Comment by TheColaber** [comment]
fixed
