### ISSUE TITLE
@apple502j locked my discussion for no reason

### ISSUE THREAD

**Issue by Mr-Programmer-777** [ScratchAddons/ScratchAddons#1883]
Can you unblock it please? I've just been away for a few days and now I can't say hello and get help from my friends that are helping me.

Also, I've been thinking, and I have decided that i AM going to try and make an addon. From scratch!

Yours excitedly and questioningly,
MrProgrammer777

**Comment by RedGuy12** [comment]
#1817

**Comment by Mr-Programmer-777** [comment]
Yeah, I think it actually will be quite easy.
Wish me good luck!

**Comment by mxmou** [comment]
He probably locked it because discussions aren't intended for chat.

**Comment by Mr-Programmer-777** [comment]
It's cause I said that I was giving up, but I had to go for a few days so...
Plus, the discussion was **Chat** and, it was somewhat relative to ScratchAddons.
I really want it to open up again, so I can always have a natter with you guys if I need help (if that's ok :)

**Comment by RedGuy12** [comment]
@Mr-Programmer-777 try this? https://gitter.im/ScratchAddons-chat/community#
