### ISSUE TITLE
Make the "Highlight currently running blocks" addon look cleaner

### ISSUE THREAD

**Issue by LES-11** [ScratchAddons/ScratchAddons#1886]
**Is your feature request related to a problem? Please describe.**

The "Highlight currently running blocks" addon is currently just a blue box, which doesn't look very clean in comparison to the yellow outline that scratch shows.

**Describe the solution you'd like**

Keep the addon, however instead of it being a blue box, make it be like the yellow glow outline that scratch shows, just in blue.

**Describe alternatives you've considered**

The option to change the color of the glow (not really an alternative, more like an addition).

**Additional context**

![Capture](https://user-images.githubusercontent.com/75516401/111205861-edfead00-8584-11eb-8740-fb94854cb1e3.png)

(I hope this makes sense...)

**Comment by Mr-Programmer-777** [comment]
Yeah. The blue outline looks really ugly..

**Comment by GrahamSH-LLK** [comment]
```
<svg>
<filter id="blueStackGlow" height="160%" width="180%" y="-30%" x="-40%"><feGaussianBlur in="SourceGraphic" stdDeviation="4"></feGaussianBlur><feComponentTransfer result="outBlur"><feFuncA type="table" tableValues="0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1"></feFuncA></feComponentTransfer><feFlood flood-color="blue" flood-opacity="1" result="outColor"></feFlood><feComposite in="outColor" in2="outBlur" operator="in" result="outGlow"></feComposite><feComposite in="SourceGraphic" in2="outGlow" operator="over"></feComposite></filter></svg>```

**Comment by LES-11** [comment]
> on an element should give it a better glow

I don't know if I was clear of this bit: The point is to have the blue outline contour the blocks with a glow. 
(not just make the blue square more glowy)

**Comment by RedGuy12** [comment]
@GrahamSH-LLK they want the outline to wrap around the blocks

**Comment by GrahamSH-LLK** [comment]
That's what it does.

**Comment by TheColaber** [comment]
If this is what @LES-11 meant:
![image](https://user-images.githubusercontent.com/72760579/112209120-7fa69400-8bef-11eb-9073-18f6f00fa302.png)
Then this is exactly what @GrahamSH-LLK's code does.
