### ISSUE TITLE
New editor themes!

### ISSUE THREAD

**Issue by Mr-Programmer-777** [ScratchAddons/ScratchAddons#1887]
Hello everyone!
If you didn't know, I'm making some new themes for the editor.
First on the list is an editor styled like Visual Studio!
Yeah, that's right. I'm re-decorating the buttons and stuff!
Remember to check up on this Issue!
Sometimes I might need some help with a little bit of code or syntax, so make sure to check below.

**Link to the new addon**
[smart-editor-themes.vis-std.zip](https://github.com/ScratchAddons/ScratchAddons/files/6144369/smart-editor-themes.vis-std.zip)
All code 100% by me, with no help, just syntax tutorials!

**Comment by retronbv** [comment]
Do you have discord? We would like to speak to you!

**Comment by Mr-Programmer-777** [comment]
> Do you have discord? We would like to speak to you! (For helping purposes)
No. I am never, ever using that hell-hole again. Here is fine.
(Sorry about that, i have PTSD from Discord)

The addon is done! I need someone to review it...
[smart-editor-themes.vis-std.zip](https://github.com/ScratchAddons/ScratchAddons/files/6144360/smart-editor-themes.vis-std.zip)

**Comment by Mr-Programmer-777** [comment]
I'll talk to you all tommorow, gtg

**Comment by Mr-Programmer-777** [comment]
Yeah, it's bad but as long as i know it works i'll add stuff.

**Comment by RedGuy12** [comment]
> > Do you have discord? We would like to speak to you! (For helping purposes)
> > No. I am never, ever using that hell-hole again. Here is fine.
> > (Sorry about that, i have PTSD from Discord)
> 
> The addon is done! I need someone to review it...
> [smart-editor-themes.vis-std.zip](https://github.com/ScratchAddons/ScratchAddons/files/6144360/smart-editor-themes.vis-std.zip)

The syntax is wrong.

**Comment by Resince** [comment]
Not needed. A simpler solution could be allowing for themes to be more editable, similar to the customizable scratch blocks addon. Otherwise, something such as tapermonky could always be used to run userstyles/scripts.

**Comment by RedGuy12** [comment]
Agreed. See also #1805

**Comment by mxmou** [comment]
This is a cool idea but it doesn't really fit with Scratch Addons. Maybe you share it as a Stylus userstyle instead.

**Comment by Hans5958** [comment]
> Do you have discord? We would like to speak to you! (For helping purposes)

Nah, we should encourage them to talk here often. Discord doesn't track the development better than GitHub.

> This is a cool idea but it doesn't really fit with Scratch Addons. Maybe you share it as a Stylus userstyle instead.

That's nonsense. The point of SA is to merge extensions and userscripts of Scratch into a single, powerful extension,

**Comment by Mr-Programmer-777** [comment]
Guys, to answer your thoughts and questions; I will be adding a LOT more. I'm just crap at coding (for now anyway), so i'm relying on other addons at the moment (an SDK if you will), while I'm learning to code. Bear with me!

> The syntax is wrong.

@RedGuy12 can you tell me how, and could you show me where the syntax is wrong?

> This is a cool idea but it doesn't really fit with Scratch Addons. Maybe you share it as a Stylus userstyle instead.

I'll be adding more, as soon as I know it works.

>Not needed. A simpler solution could be allowing for themes to be more editable, similar to the customizable scratch blocks addon. Otherwise, something such as tampermonky could always be used to run userstyles/scripts.

Same as above.

I'll add some more things when it all works.

**Comment by RedGuy12** [comment]
See #1805, that will allow you to make it look like anything you want. Maybe after that's done you can make a "visual studio" preset for the addon

**Comment by Mr-Programmer-777** [comment]
Guys, to answer your thoughts and questions; I will be adding a LOT more. I'm just crap at coding (for now anyway), so i'm relying on other addons at the moment (a SDK if you will) while i learn to code more.

**Comment by mxmou** [comment]
> See #1805, that will allow you to make it look like anything you want. Maybe after that's done you can make a "visual studio" preset for the addon

Although #1805 only changes colors. I'm working on an addon that would make the editor look 1.4 or 2.0 so maybe this could be part of it.

**Comment by CubeyTheCube** [comment]
> Guys, to answer your thoughts and questions; I will be adding a LOT more. I'm just crap at coding (for now anyway), so i'm relying on other addons at the moment (a SDK if you will) while i learn to code more.

maybe you should have made the issue after you "added a LOT more"

**Comment by lisa-wolfgang** [comment]
This issue will probably be closed. In the future, conversation like this would be best done in the Discussions tab.
