### ISSUE TITLE
[Feature] responsive options page

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#189]
**Is your feature request related to a problem? Please describe.**

when i use the options page in a tall window it doesn't resize well (adds scrollbars and is generally funny looking)

**Describe the solution you'd like**

properly make the sidebar smaller based on screensize

**Describe alternatives you've considered**

no

**Additional context**

i know this isn't mobile supported but its more professional if it does this

**Comment by NoobTracker** [comment]
Ah okay I first thought that you're talking about something completely different I'm now gonna suggest.

**Comment by JeffaloBob** [comment]
> Ah okay I first thought that you're talking about something completely different I'm now gonna suggest.

im confused? then why post this comment?

**Comment by NoobTracker** [comment]
bruh I wanted to write a second one but then I forgot to do that because things and reasons.

**Comment by GrahamSH-LLK** [comment]
This would be great. //cc @WorldLanguages

**Comment by NoobTracker** [comment]
![thatd-be-great](https://user-images.githubusercontent.com/63962365/92593131-e510e400-f2a0-11ea-8c51-dcf23658bf90.jpg)

**Comment by WorldLanguages** [comment]
I removed the milestone. PRs are welcome at any time
