### ISSUE TITLE
Format localization files to optimize repository size (later) and better diff viewing

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#1895]
It seems that the localization files is done minified. This caused the whole file to be rewritten, which means the changes is going to be large. This is inefficient, and will make the repository larger as time goes, and makes time to pulling and cloning even longer as time goes.

This can be optimized to save file size by formatting. Formatting lets Git knows which lines are changed, cutting unneccessary bytes that needed for the change. This could save around 10% to 30% for future commits, which could scale significantly as time goes on. 

The current size of the repository is 4 MB, which I think diffs of the localization took 25% to 35% (can be around 40% to 50% but the localization files is still young), so we can decrease the growth of the repository size by doing this.

Also, this lets us know what strings are really changed on those files, instead of a vague diff which difference is just red and green in hindsight.

## Comparison

These are patch files. It is the representative of the diff between two commits. This is written on the Git files, although of course in a different format.

### Mostly new files

- [Without formatting (17.966 bytes)](https://github.com/ScratchAddons/ScratchAddons/files/6149158/1-unformatted.patch.txt)
- [With formatting (13.146 bytes)](https://github.com/ScratchAddons/ScratchAddons/files/6149160/1-formatted.patch.txt)

### Mostly modified files

- [Without formatting (126.622 bytes)](https://github.com/ScratchAddons/ScratchAddons/files/6149161/2-unformatted.patch.txt)
- [With formatting (107.735 bytes)](https://github.com/ScratchAddons/ScratchAddons/files/6149162/2-formatted.patch.txt)

**Comment by WorldLanguages** [comment]
Huh, I wouldn't think it would make a big difference tbh. Guess I don't really know how git actually store diffs.

**Comment by Hans5958** [comment]
> Huh, I wouldn't think it would make a big difference tbh. 

Well, as I said, the saving that we can got is around 10% to 30%, and this will scale as long as there is development on this repository.

Another one is the diff viewing. Get this. Why do we normalize this...

![image](https://user-images.githubusercontent.com/11584103/111323622-a23f2700-869c-11eb-852e-cc183a6d2941.png)
https://github.com/ScratchAddons/ScratchAddons/pull/1892/files

...and not this?

![image](https://user-images.githubusercontent.com/11584103/111323652-aa976200-869c-11eb-8fa1-93eb1713e6cc.png)
https://github.com/PreMiD/Localization/pull/6216/files

**Comment by WorldLanguages** [comment]
> Why do we normalize this

Because these files are automatically generated?

**Comment by apple502j** [comment]
This actually increases repository size. It is clear that git doesn't store diffs; otherwise how does `--depth 1` work?

**Comment by apple502j** [comment]
Not sure if it's suitable approach. We should minify for production - so if we decide to not do so here, we need a build process of some sort.

It's clear that git doesn't store things in diff/patch format, and it's likely that they treat CRLF the same as any other letters. If this causes actual problems, we can fix later.

**Comment by Hans5958** [comment]
Huh, I think you are right. Git is really unpredictable.

- https://stackoverflow.com/questions/8198105/how-does-git-store-files
- https://stackoverflow.com/questions/40617288/a-commit-in-git-is-it-a-snapshot-state-image-or-is-it-a-change-diff-patch-delta
- https://stackoverflow.com/questions/51883141/if-git-functions-off-of-snapshots-of-files-why-doesnt-git-become-huge-over-t
