### ISSUE TITLE
disable cat blocks addon when it's april fools day

### ISSUE THREAD

**Issue by jeffalo** [ScratchAddons/ScratchAddons#1896]
april fools day for 2021 currently seems to have catblocks planned. we should disable catblocks on our end to ensure ntohing wakcy happens

**Comment by retronbv** [comment]
ntohing wakcy

**Comment by TheColaber** [comment]
Tbh, we should disable all the addons... ST won't repeat everything from last year...

**Comment by RedGuy12** [comment]
Or we can just show a note (Hey! Addons may conflict with April fools...)
But how will we know when it is? St always goes a bit early

**Comment by jeffalo** [comment]
> Tbh, we should disable all the editor addons... ST won't repeat everything from last year...

we can tell what they're doing in advance https://github.com/llk/scratch-gui/tree/hotfix/totally-normal-2021

**Comment by TheColaber** [comment]
I didn't see cat blocks so far... it really looks duplicate of last year without the cat blocks...

**Comment by TheColaber** [comment]
Nevermind I'm wrong... https://github.com/LLK/scratch-blocks/tree/hotfix/totally-normal-2021

**Comment by FunctionalMetatable** [comment]
well you never know it could just be a dummy branch just to fool people, they might have the 2021 thing private or something

**Comment by TheColaber** [comment]
> After some testing, everything seems to work fine even if we run cat blocks above cat blocks.
