### ISSUE TITLE
Allow addons to use the context menu

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#19]
Allow addons to add "right click extension icon" actions. However because of browser limitations, I think only about 5 addons could do this at the same time.
We should also consider allowing addons to add menu items when right clicking inside the Scratch website.

**Comment by JeffaloBob** [comment]
perhaps they could go under a drop down kinda thing? (if the amount of items is the limitation your talking about)
![image](https://user-images.githubusercontent.com/40470736/89685385-8e5c6700-d8fc-11ea-9ddb-896c0c5b5abc.png)

**Comment by WorldLanguages** [comment]
I believe there's a limit of 6 or so items per menu, we could probably work around this by making every addon have its own submenu but there would still be a limit of addons that can have a submenu, and so on...

**Comment by JeffaloBob** [comment]
maybe the user could decide what submenus are there/which addons are in each menu

**Comment by WorldLanguages** [comment]
Yeah. It will only become a problem if many addons decide to have submenus, tho.

**Comment by TheColaber** [comment]
What addons are expected to be in the context menu?

**Comment by WorldLanguages** [comment]
None, at the moment

**Comment by YOYITsM3M8** [comment]
The bitmap copy?

**Comment by WorldLanguages** [comment]
No, that only works with Ctrl+C. If it did work with the context menu, it still wouldn't use `chrome.contextMenus` - its actually Scratch's custom context menu.

**Comment by YOYITsM3M8** [comment]
Ok

**Comment by WorldLanguages** [comment]
`contextMenus` is now in the manifest's permissions array, so as of v1.2 any addon can use `chrome.contextMenus` from its persistent scripts.

**Comment by Explosion-Scratch** [comment]
It's cool to see all of these old issues turning up again. Thanks for
taking care of them though WL!
