### ISSUE TITLE
[Feature] Improving the settings by adding custom JS

### ISSUE THREAD

**Issue by NoobTracker** [ScratchAddons/ScratchAddons#190]
**Is your feature request related to a problem? Please describe.**

Kinda. I thought about implementing something that would require this in my PR.

**Describe the solution you'd like**

I would like to have the option to somehow add a JS file that can handle some things in the settings, like only making options clickable when something else is clicked. Also, it could do stuff like disabling in this example my forkphorus extension when

- [ ] Add forkphorus
- [ ] Add TurboWarp

are both disabled.

**Describe alternatives you've considered**

I thought about just adding some weird attributes in the JSON but I think that just JS would be more flexible and easier.

**Additional context**

Nope.

**Comment by apple502j** [comment]
Can't we use select and option?

**Comment by NoobTracker** [comment]
@apple502j No, I mean just in the settings. That's a page where we currently can't mess with.

**Comment by apple502j** [comment]
If we support select and option tag for setting form OP issue is effectively resolved, because you can only choose one.

**Comment by NoobTracker** [comment]
I mean that you can have something like

- [ ] Use addon
- [ ] Add fork
- [ ] Add warp

and then a script like
```
when fork or warp disabled then
if fork and warp are both turned off
set use addon to false
```
just in JS.

**Comment by Hans5958** [comment]
I don't think it is needed in the case. Other than making things more complicated than ever, it seems that your case seemed unnecessary to be handled that way.

**Comment by NoobTracker** [comment]
It would be an optional thing if it makes no sense to activate a boolean if the other one isn't enabled. That would be more complicated but it would also do more things and be cooler and as I said you can add that if it makes sense. Otherwise you don't.

**Comment by WorldLanguages** [comment]
The first version of the settings handler did support `child_bool` but it was too complex imo. If one setting requires another setting enabled, make that setting the main addon, and the other setting an optional setting.

**Comment by NoobTracker** [comment]
That's not a great solution but whatever.

**Comment by WorldLanguages** [comment]
Closing this, we might add more ways to customize how addon settings are shown, but not through JS
