### ISSUE TITLE
Add new manifest properties on docs

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#1909]
It's time to add the new properties of the addon manifest on the documentation.

- [x] `dynamicDisable`
- [x] `dynamicEnable` (#1858) - will do when PR merged
- [x] `settings[].allowTransparency`
- [x] ...

**Comment by TheColaber** [comment]
@Hans5958 not sure we should keep making new issues for each time we are behind... but anyway, will work on right now.

**Comment by Hans5958** [comment]
> @Hans5958 not sure we should keep making new issues for each time we are behind... but anyway, will work on right now.

Well, it's an overdue issue, so, yeah.
