### ISSUE TITLE
[New addon] Onion skinning?

### ISSUE THREAD

**Issue by jeffalo** [ScratchAddons/ScratchAddons#193]
**Describe the new addon**

In the scratch paint editor, a "onion skin" of the last costume should appear on top of the latest costume with some transparency. 

I don't know if this is possible, but maybe some of apple's tricks can be used to modify the paint editor?

**Comment by NoobTracker** [comment]
I don't exactly care about making animations but (where in my quote manager is that quote - ah, there)

> It's never bad to have features

So cool and I don't know a single con.

**Comment by WorldLanguages** [comment]
This has been suggested through feedback.
