### ISSUE TITLE
Easter Egg Addons "poof" on disable

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#1932]
**Describe the bug**

When you disable an easter egg addon, it gets removed from the addon list, whether by popup or page.

**To Reproduce**

1. Go to the settings page
2. Enter the konami code
3. Enable easter egg addon
4. Reload page
5. Disable that addon

**Expected behavior**

Stay there, if it was just disabled.

**Comment by easrng** [comment]
We should keep this behavior but add an animation to the poof

**Comment by RedGuy12** [comment]
no not poof until page is reloaded

**Comment by WorldLanguages** [comment]
This was fixed by #1931
