### ISSUE TITLE
Without `"core"` the settings page doesn't load those settings

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#1935]
**Describe the bug**

Try loading
```json
{
  "addons": {
    "custom-block-shape": {
      "enabled": true,
      "settings": { "cornerSize": 150, "notchSize": 75, "paddingSize": 70 }
    }
  }
}
```
for example and notice that there is no alert when you press "Confirm".

**To Reproduce**

1. Go to settings page
2. Click on 'More settings'
3. Load settings that don't have the core key.
4. Try pressing confirm but not alert appears.
5. See error in console.

**Expected behavior**

Not error

**Comment by apple502j** [comment]
Settings should be loaded as provided by the extension. Not really a bug.
