### ISSUE TITLE
`chrome.runtime.reload()` does not reload settings page

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#1936]
**Describe the bug**

When loading settings, the alert says the page will reload, but it just closes.

**To Reproduce**

1. Go to settings page
2. Click on 'More settings'
3. Load any settings
4. Press confirm
5. See the alert
6. The page closes after pressing "ok"

**Expected behavior**

at least tell the user it will close instead of reload

**Comment by apple502j** [comment]
It does not say that the page reloads.
