### ISSUE TITLE
Remind user to share a project 

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#1938]
Hello!

I am Genius398. I want a new addon. Description below.

It will be a "Remind Share" addon. This addon will show a calendar and will allow us to choose the date. Then, when that date arrives, we can remind the user to share the project with `window. confirm("Do you want to share the project"+project_name+"?")`

It's possible but hard.

This is not a duplicate of #1628

**Comment by RedGuy12** [comment]
Is a dupe of #1628.

Not going to happen.

**Comment by TheColaber** [comment]
Duplicate of #1628 as RedGuy12 said.
