### ISSUE TITLE
Developer tools renames the clean up blocks option confusingly

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#1943]
**Describe the bug**

When the `editor-devtools` addon is enabled, the *Clean up Blocks* option in the workspace context menu is renamed to *Clean Up Blocks (+)*. Apparently the (+) is supposed to mean that it's better than Scratch's option, but at first I thought it means that + is a keyboard shortcut for it.

**To Reproduce**

1. Enable developer tools
2. Open the editor
3. Right click the workspace
4. The clean up option is named *Clean Up Blocks (+)*, although pressing + does not clean up blocks

**Expected behavior**

One of the following:
* Don't rename the option
* Name it something like *Clean up Blocks (improved)* so that it isn't confusing.

Either way it shouldn't change capitalization from that used by Scratch.

**Comment by Genius398** [comment]
Yes it is quite confusing

**Comment by Scratchfangs** [comment]
There should be an option in Scratch Addon Settings to completely remove Scratch's Cleanup System and replace it with the Scratch Addon's Cleanup System.

**Comment by CST1229** [comment]
It could even just be renamed to "Clean Up Blocks +".
