### ISSUE TITLE
Backpacking Sprite Folders

### ISSUE THREAD

**Issue by Vivaan-S** [ScratchAddons/ScratchAddons#1945]
**Is your feature request related to a problem? Please describe.**

It's really annoying that the scratch editor crashes every single time you try to backpack a sprite folder.

**Describe the solution you'd like**

I would like that we are able to backpack sprite folders. When you pull them out, as usual, other people who do not have scratch addons will see them as normal.

**Describe alternatives you've considered**

It would also be fine if when you backpack a sprite folder, it automatically converts it to normal sprites.

**Additional context**

I really hope you add this, and if you don't, at least please stop the editor from crashing when you backpack a sprite folder.

~    --VSCoder-- on Scratch

**Comment by Vivaan-S** [comment]
@WorldLanguages

**Comment by TheColaber** [comment]
Please do not ping World_Languages whenever you want something.

**Comment by Vivaan-S** [comment]
Okay.
