### ISSUE TITLE
Not able to mark a message "read"

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#1948]
**Describe the bug**
Even when I click on the "mark as read" button, the messages will also be there

**To Reproduce**
1. Go to 'New Tab'
2. Click on 'The SA extension
3. Click on "mark as read"
4. The message pops up again after 30 secs

**Expected behaviour**
1. Go to 'New Tab'
2. Click on 'The SA extension
3. Click on "mark as read"
4. No message pops up again after 5 mins

Info: 
- OS: Windows 10
- Browser: Chrome
- Version 88

**Comment by RedGuy12** [comment]
open the messages page. are there any messages from the scratch team? if so, duplicate of #1710.

**Comment by Genius398** [comment]
> open the messages page. are there any messages from the scratch team? if so, duplicate of #1710.

No. It is a normal comment. On the messages page, it is fine (no new messages), but SA keeps on alerting me.

**Comment by RedGuy12** [comment]
can you show a video?

**Comment by Genius398** [comment]
> can you show a video?

ok. Making one

**Comment by Genius398** [comment]
> can you show a video?
























2 mins please

**Comment by Genius398** [comment]
https://user-images.githubusercontent.com/74092334/112164697-1ab16500-8c14-11eb-8069-f8f0c6ef9725.mp4

**Comment by RedGuy12** [comment]
Go to this messages page: https://scratch.mit.edu/messages
are there any ST messages? if not, can you show a screenshot of that?

**Comment by Genius398** [comment]
> Go to this messages page: https://scratch.mit.edu/messages
> are there any ST messages? if not, can you show a screenshot of that?

No ST messages. Normal comments

**Comment by Genius398** [comment]
ST comments are displayed normal

**Comment by RedGuy12** [comment]
can you show a screenshot?

**Comment by Genius398** [comment]
> can you show a screenshot?

Sure!

**Comment by Genius398** [comment]
![Capture](https://user-images.githubusercontent.com/74092334/112166581-c4ddbc80-8c15-11eb-9f2c-09cf5b730e46.PNG)


The thing is in the messages area in Scratch, it is read, but in SA it is not

**Comment by RedGuy12** [comment]
Odd...

Thanks for reporting.

**Comment by Genius398** [comment]
> Odd...
> 
> Thanks for reporting.

😀

**Comment by apple502j** [comment]
Probably Scratch downtime.

**Comment by Genius398** [comment]
> Probably Scratch downtime.

means?

**Comment by mxmou** [comment]
> > Probably Scratch downtime.
> 
> means?

Maybe Scratch had issues while this was happening.

**Comment by WorldLanguages** [comment]
Couldn't be reprod
