### ISSUE TITLE
Invite all of your followers with a single buttons

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#1949]
**Describe the new addon**
This addon will add a button in the curators' page of any studio you own/are a manager of. Clicking it will invite all of the user's followers

Simple isn't it?

**Comment by GrahamSH-LLK** [comment]
Re https://github.com/ScratchAddons/ScratchAddons/discussions/927
>A button to invite all followers to a studio (#635)
>"There are rate limits, and I don't think any type of automatic inviting would be ok."

**Comment by Genius398** [comment]
> Re #927
> 
> > A button to invite all followers to a studio (#635)
> > "There are rate limits, and I don't think any type of automatic inviting would be ok."

Ok sorry
