### ISSUE TITLE
Rename "60FPS player mode"

### ISSUE THREAD

**Issue by oof-le-oof** [ScratchAddons/ScratchAddons#1963]
**Is your feature request related to a problem? Please describe.**

The "Alt+GreenFlag" looks strange, and the FPS can be changed (it's not necessarily 60)

**Describe the solution you'd like**

Change to "Alternate FPS player mode" or something similar

**Describe alternatives you've considered**

Remove "Alt+GreenFlag" from name, it's a little awkward to put how to use the addon in the name of the addon
For example the mute addon is not named "Ctrl+GreenFlag mute project"

**Comment by WorldLanguages** [comment]
> For example the mute addon is not named "Ctrl+GreenFlag mute project"

That addon has no setting for "custom muteness", tho. It's obvious you don't want to mute a project all the time, but some people might want to run projects at 60FPS all the time.

**Comment by oof-le-oof** [comment]
> > For example the mute addon is not named "Ctrl+GreenFlag mute project"
> 
> That addon has no setting for "custom muteness", tho. It's obvious you don't want to mute a project all the time, but some people might want to run projects at 60FPS all the time.

I just included this because the Mute addon doesn't explain what buttons you need to click to use it in the title whereas the FPS changer does.

**Comment by WorldLanguages** [comment]
Yeah, and I explained why. It's obvious you don't want to have all projects be muted all the time, but it's not that obvious that you do need to Alt+GreenFlag to apply custom FPS - some users might just think having 60 FPS as the default (no Alt+GreenFlag required) would be a good idea, and might miss that the addon requires user interaction to do something.

**Comment by WorldLanguages** [comment]
It is now called `60FPS project player mode`
