### ISSUE TITLE
Leave button appears even when I am not a curator of a studio

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#1967]
**Describe the bug**

The leave button appears in studios we are not a curator of
**To Reproduce**

1. Go to Scratch
2. Click on a studio
3. Scroll down to Curators
4. See error (That even if you are not a curator of a studio the leave button appears)

**Expected behaviour**
1. Go to Scratch
2. Click on a studio
3. Scroll down to Curators
4. See error (That only if you are a curator of a studio the leave button appears)

**Screenshots**
Not applicable

**Device (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 88

**Comment by GrahamSH-LLK** [comment]
This is a known issue, there is no efficient way to find out if you are a curator. Leaving open if anyone has ideas on how to do it without force-fetching the HTML API. (It can take up to 30 seconds on large studios)

**Comment by TheColaber** [comment]
@GrahamSH-LLK no, I think there was, there was just no way to tell if they were curator or manager...

**Comment by GrahamSH-LLK** [comment]
> @GrahamSH-LLK no, I think there was, there was just no way to tell if they were curator or manager...

Not as far as I know.

**Comment by Genius398** [comment]
> @GrahamSH-LLK no, I think there was, there was just no way to tell if they were curator or manager...

Maybe a Scratch API?

**Comment by mxmou** [comment]
There will probably be [an API](https://github.com/LLK/scratch-www/blob/develop/src/redux/studio.js#L97) for this soon.

**Comment by oof-le-oof** [comment]
Leave this, it's just fun

**Comment by WorldLanguages** [comment]
@apple502j Does your version of studio-manager-tools for www studios fix this?

**Comment by apple502j** [comment]
@WorldLanguages 99% yes. However it will not remove the button if someone else manages to kick the user when the user is on the studio page. Should we fix this bug? /s

**Comment by WorldLanguages** [comment]
To be fixed when Scratch updates to 3.0 studios this week or so
