### ISSUE TITLE
[New addon] Remapping smileys

### ISSUE THREAD

**Issue by NoobTracker** [ScratchAddons/ScratchAddons#197]
**Describe the new addon**

Do you know that :) gets replaced with :smile: in the Scratch forums? Probably. But you can use :[]) to avoid that. So what do we do?  
We just code it so that when sending a post :) gets replaced with :[]) and :smiIe: with :). Wouldn't that be great?

**Link to the new addon**

Doesn't exist.

**Comment by NoobTracker** [comment]
Um ... bump? @WorldLanguages ?

**Comment by TheColaber** [comment]
What is the benefit of this feature?

**Comment by NoobTracker** [comment]
The benefit, @TheColaber , is that you don't accidentaly use smileys. Btw, I think it's :[b][/b]) and not :[]) but as you might know, I'm false perm banned on Scratch so I don't care too much anymore.

**Comment by TheColaber** [comment]
> The benefit, @TheColaber , is that you don't accidentaly use smileys. Btw, I think it's :[b][/b]) and not :[]) but as you might know, I'm false perm banned on Scratch so I don't care too much anymore.

I know, but how do you accidentally create smileys? If you say "Thanks :)" Why would you not want it to turn into a smile?

Also, wut did the ST say?

**Comment by NoobTracker** [comment]
Let me show you an example:(you probably already see it) 
Et voilà, sad smiley. Things like that. 

And I got perm banned because my appeal was like "ST please unban me I didn't break the rules" and there response was something like "uh no you don't seem to be able to understand what's breaking the rules and what doesn't" but my ban was cause by a false report.

**Comment by TheColaber** [comment]
> "uh no you don't seem to be able to understand what's breaking the rules and what doesn't"

That doesn't sound like the ST...

**Comment by NoobTracker** [comment]
That wasn't an original quote. The original was more like "Saying that you don't wanna follow the CGs isn't a good answer. We will not unban you" and then they just ignored me.

**Comment by TheColaber** [comment]
> That wasn't an original quote. The original was more like "Saying that you don't wanna follow the CGs isn't a good answer. We will not unban you" and then they just ignored me.

Hmm, weird. Did you say "you don't wanna follow the CGs"

**Comment by NoobTracker** [comment]
No, I said something like "I didn't even break them". But anyway, totally off topic.

**Comment by YOYITsM3M8** [comment]
> No, I said something like "I didn't even break them". But anyway, totally off topic.

**Entirely off topic:** I got banned because my alt account got banned for breaking community guidelines even tho I haven't been on it for months

**Comment by NoobTracker** [comment]
@YOYITsM3M8 that's pretty weird. Was it because you did something bad some months ago that was only found months later? And what was the reason for your alt account's ban?

**Comment by YOYITsM3M8** [comment]
> @YOYITsM3M8 that's pretty weird. Was it because you did something bad some months ago that was only found months later? And what was the reason for your alt account's ban?
> 
> 

Breaking the community guidelines but I have only shared 3 projects on my alt

**Comment by NoobTracker** [comment]
Just a general "You broke the rules" or what exactly caused it?

**Comment by YOYITsM3M8** [comment]
> Just a general "You broke the rules" or what exactly caused it?

yeah

**Comment by NoobTracker** [comment]
totally weird, totally off topic. Btw, do you know @JeffaloBob 's [chat](https://chat.jeffalo.net/#)?

**Comment by YOYITsM3M8** [comment]
> totally weird, totally off topic. Btw, do you know @JeffaloBob 's [chat](https://chat.jeffalo.net/#)?

yes

**Comment by RedGuy12** [comment]
> Closed #197<https://github.com/ScratchAddons/ScratchAddons/issues/197>.

Why?
________________________________
