### ISSUE TITLE
Background image for the website

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#1970]
Spoiler: This is an expansion of #1944 (not made by me)

**Describe the new addon**
This addon will allow us to upload an image and that image will be the background for Scratch.mit.edu

**Comment by retronbv** [comment]
This sounds useless.

**Comment by Genius398** [comment]
> This sounds useless.

Ok

**Comment by Explosion-Scratch** [comment]
Wait, wait, it's a valid suggestion. I think it'd be pretty cool TBH.

**Comment by FunctionalMetatable** [comment]
Dupe of #1598

**Comment by WorldLanguages** [comment]
Duplicate of #1598
