### ISSUE TITLE
Upcoming studio changes

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#1972]
The ST is working on a scratch-www studio page. This will affect any addons that interact with the studios page and possibly other addons, as this will bubble into other pages. This will also help resolve #1967.

**Comment by mxmou** [comment]
We should probably change addons that interact with studios to support both studio pages when the new studio page is complete, and remove code for the old studio page when it's actually released.

**Comment by jeffalo** [comment]
we could also watch studio development and when we believe it's getting close, release an update that removes studio styling in anticipation of the update. not a great solution but it wont leave unused code.

**Comment by WorldLanguages** [comment]
IMO it wouldn't be that complex to support URL matches like `https://scratch.mit.edu/studios_r2/*` and `https://scratch.mit.edu/studios_www/*` if really needed 🤔 (`https://scratch.mit.edu/studios/*` would still match both)

**Comment by mxmou** [comment]
> IMO it wouldn't be that complex to support URL matches like `https://scratch.mit.edu/studios_r2/*` and `https://scratch.mit.edu/studios_www/*` if really needed 🤔 (`https://scratch.mit.edu/studios/*` would still match both)

This would only be need temporary so I think it would be better to just handle it in a userscript.

**Comment by WorldLanguages** [comment]
@mxmou Sure, but RIP theme autoupdate unless dynamicEnable works by then :P
Also, it's always a bad idea to hide the styles until the userscript can run, might cause a flash of unstyled (actually, "unthemed" would be a more acurrate word) content

**Comment by mxmou** [comment]
At the moment manually injecting both scratchr2 and scratch-www styles (from scratchr2 and dark-www addons) into the new studio page works well. Even if this changes, adjusting some selectors will probably be enough to be compatible with both studio pages.
![image](https://user-images.githubusercontent.com/51849865/113404298-38b35e00-93a8-11eb-918c-042aff9df6ea.png)

*(If anyone wants to test it, note that the studio comments endpoint is currently only available to Scratch Team members. I manually redirected it to `https://api.scratch.mit.edu/users/andresmh/projects/104/comments`)*

**Comment by mxmou** [comment]
The studio changes will probably be out soon. Could the next version of SA add the necessary changes?

**Comment by RedGuy12** [comment]
Moved to #2484
