### ISSUE TITLE
Paint editor tools are wrong placed

### ISSUE THREAD

**Issue by Exlectruz** [ScratchAddons/ScratchAddons#1974]
**Describe the bug**

- The paint editor tools are in the wrong position, they should be vertical, not horizontal. This takes up space and I have to zoom out to 67% to have more space when painting...

_________________________________________________________________
![toolbox](https://user-images.githubusercontent.com/79061511/112565415-c648e980-8dbb-11eb-9867-91d9c6430a22.png)

![bug](https://user-images.githubusercontent.com/79061511/112564590-5128e480-8dba-11eb-81ec-3451a6adb8de.png)
_________________________________________________________________

Solution: 
![solution](https://user-images.githubusercontent.com/79061511/112565431-ccd76100-8dbb-11eb-9bb6-090519382809.png)

**Device:**

- OS: [e.g. iOS] Windows 10 pro.
- Browser [e.g. chrome, safari] Chrome.
- Version [e.g. 22] 89.0.4389.90 (Build oficial) (32 bits).

**Comment by TheColaber** [comment]
This is not caused by scratch addons. 
![image](https://user-images.githubusercontent.com/72760579/112565895-5e42d500-8db4-11eb-92a3-0c0c2c776888.png)
In fact, I'm very used to seeing my paint editor look like this... It's not until you resize your screen when that happens.

**Comment by apple502j** [comment]
Working as intended

**Comment by WorldLanguages** [comment]
@Exlectruz If you believe this is caused by Scratch Addons, feel free to reopen the issue.
