### ISSUE TITLE
Option to remove "My Variable" and "Scratch Cat" and "Pop" when making a new project/sprite

### ISSUE THREAD

**Issue by Scratchfangs** [ScratchAddons/ScratchAddons#1975]
When you make a new project, a Scratch Cat sprite appears with a variable named "my variable". Also, whenever you make a blank sprite, "pop" appears in sounds. This is extremely annoying when you had a lot of sprites that used to be blank. What if there was a feature to remove those from coming up whenever you make a new project/sprite? Obviously, Scratch Cat and Pop would still be available in the Sound and Costume library.

**Comment by Scratchfangs** [comment]
![image](https://user-images.githubusercontent.com/71499307/112625165-eea90600-8e04-11eb-9687-f6aded05ac77.png)
![image](https://user-images.githubusercontent.com/71499307/112625211-fcf72200-8e04-11eb-8df6-2a434566b940.png)
![image](https://user-images.githubusercontent.com/71499307/112625242-07b1b700-8e05-11eb-9f38-8b5ca96b765f.png)

**Comment by FunctionalMetatable** [comment]
Maybe a "default project" addon where it takes a private, default project and when you make a project it copies the project over?

**Comment by jeffalo** [comment]
> Maybe a "default project" addon where it takes a private, default project and when you make a new project it copies the project over?

this seems like a better solution. the addon could have an input for a project id and all new projects are based on that. if someone had the time and sanity, it could take an optional studio id, and when making a new project ask the user which project to start with.

**Comment by FunctionalMetatable** [comment]
how would this work? would a script need to be injected instead of `/js/projects.bundle.js`?

**Comment by jeffalo** [comment]
> how would this work? would a script need to be injected instead of `/js/projects.bundle.js`?

maybe we'd just replace the create button with a custom button that does what we want, easier than messing with the project page and stuff

**Comment by mxmou** [comment]
> > how would this work? would a script need to be injected instead of `/js/projects.bundle.js`?
> 
> maybe we'd just replace the create button with a custom button that does what we want, easier than messing with the project page and stuff

The people who use the New Project button in My Stuff or go to `scratch.mit.edu/create` or `scratch.mit.edu/projects/editor` would still get the normal default project.

**Comment by FunctionalMetatable** [comment]
might try work on this then

**Comment by FunctionalMetatable** [comment]
> > > how would this work? would a script need to be injected instead of `/js/projects.bundle.js`?
> > 
> > 
> > maybe we'd just replace the create button with a custom button that does what we want, easier than messing with the project page and stuff
> 
> The people who use the New Project button in My Stuff or go to `scratch.mit.edu/create` or `scratch.mit.edu/projects/editor` would still get the normal default project.

how about when the user goes to scratch.mit.edu/projects/editor **and** it gets project id => the addon sends a request to the server to update the project json .then if it works it reloads the page and .catch then it just displays a notification

**Comment by jeffalo** [comment]
> > > > how would this work? would a script need to be injected instead of `/js/projects.bundle.js`?
> > > 
> > > 
> > > maybe we'd just replace the create button with a custom button that does what we want, easier than messing with the project page and stuff
> > 
> > 
> > The people who use the New Project button in My Stuff or go to `scratch.mit.edu/create` or `scratch.mit.edu/projects/editor` would still get the normal default project.
> 
> how about when the user goes to scratch.mit.edu/projects/editor **and** it gets project id => the addon sends a request to the server to update the project json .then if it works it reloads the page and .catch then it just displays a notification

or you could just use vm methods to replace the project with one downloaded from projects.scratch.mit.edu

**Comment by Scratchfangs** [comment]
Bump?

**Comment by TheColaber** [comment]
> Bump?

This isn't the scratch forums. Implement it yourself, because we have more important things to do. If you have the time to say "bump", I'm sure you have time to create it.

**Comment by Vivaan-S** [comment]
I find this a good idea.

**Comment by silvxrcat** [comment]
Helpful, but what if I want my own sprite to pop up? Like maybe an option to load a .sprite3 file every time you make a project?
