### ISSUE TITLE
404 not converted

### ISSUE THREAD

**Issue by lightningmc09** [ScratchAddons/ScratchAddons#1976]
**Describe the bug**
404 does not get converted to 3.0

404 pages sometimes do not get converted from 2.0 to 3.0
**To Reproduce**
go to scratch.mit.edu/errorfourohfour

go to scratch.mit.edu/errorfourohfour
1. See error

**Expected behavior**

 expect to see my 3.0 color changed taskbar at top

**Screenshots**

![Screenshot (26)](https://user-images.githubusercontent.com/81425039/112642903-c378e380-8e11-11eb-8e12-06ee547cf190.png)
![Screenshot (27)](https://user-images.githubusercontent.com/81425039/112642935-ca075b00-8e11-11eb-9312-d9ef10d003ff.png)

**Device (please complete the following information):**

- OS: windows 10
- Browser edge
- Version i actually dont know

**Additional context**

sometimes shows color sometimes doesn't

**Comment by retronbv** [comment]
Do you have the addon enabled?

**Comment by TheColaber** [comment]
I can repro... the page never does get converted to 3.0, but my profile page does...

**Comment by TheColaber** [comment]
Reason being there is no match:
![image](https://user-images.githubusercontent.com/72760579/112645516-ef4d9680-8e1c-11eb-8cef-96612ad6b506.png)
But if you go to scratch.mit.edu/404, it will...

**Comment by mxmou** [comment]
The best way to fix this is #23, but I don't think setting the match of `scratchr2_errors.css` to `["https://scratch.mit.edu/*"]` would cause any problems.
