### ISSUE TITLE
Ability to hide "Projects Loved by Scratchers I'm Following"

### ISSUE THREAD

**Issue by Scratchfangs** [ScratchAddons/ScratchAddons#1981]
A few of the people I am following are liking/favoriting very cringy/stupid things and it's being added to "Projects Loved by Scratchers I'm Following". Why not just unfollow them? Well, I did F4F a few months ago and they are still very active. They visit my profile often so they will know when I unfollow them. What if there was a new addon to disable "Projects Loved by Scratchers I'm Following"?

**Comment by mxmou** [comment]
Maybe hide any row on the front page?

**Comment by RedGuy12** [comment]
> Maybe hide any row on the front page?

see #1758 for that

**Comment by WorldLanguages** [comment]
Duplicate of #1758
