### ISSUE TITLE
Bring back "MEOW" language

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#1983]
Remember the MEOW language? Yeah, how cool will it be to bring it back, huh?

Let's bring it back!

**Comment by Scratchfangs** [comment]
Why though, it's just "meow"?

**Comment by Genius398** [comment]
> Why though, it's just "meow"?

No. See https://scratch.mit.edu/discuss/topic/34269/ and https://scratch.mit.edu/projects/20001538/

**Comment by GrahamSH-LLK** [comment]
No, this would be ridiculous. We'd have to figure out how to retranslate every string and inject them properly. It was hard to maintain even for the ST, and they had direct access to the localization system.
