### ISSUE TITLE
Add a "needs server" label

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#1999]
This is a suggestion to add a "status: needs server" label. We may plan to buy some kind of hosting if we get donations, so this would help organize issues that will be possible in the future.

**Comment by GrahamSH-LLK** [comment]
cc @Hans5958

**Comment by Hans5958** [comment]
Use a scope label instead? `scope: server`?

**Comment by GrahamSH-LLK** [comment]
Sure, you're in charge of labels.

**Comment by Hans5958** [comment]
Alright. Added `scope: server`.

**Comment by RedGuy12** [comment]
can you add it to #155 pls?
