### ISSUE TITLE
[Question] Where do comments have their submit button?

### ISSUE THREAD

**Issue by NoobTracker** [ScratchAddons/ScratchAddons#200]
Now this is weird: Comments don't have a submit button. The post button is just a link to #null. Can anyone tell me how that works? @JeffaloBob I think you already did those weirt out-of-context replies, maybe you can help me.

**Comment by JeffaloBob** [comment]
first off #200 🎉 but i don't understand what you're saying?

**Comment by YOYITsM3M8** [comment]
OOH I KNOW!!! in their html xD
but actually no

**Comment by NoobTracker** [comment]
![thatsaproblemiguess](https://user-images.githubusercontent.com/63962365/92262916-1de53d80-eedc-11ea-98f8-d557c3044b0c.PNG)
(for those who don't speak german, Leerraum means empty space)
forms usually have a submit button. With type="submit".

**Comment by JeffaloBob** [comment]
> OOH I KNOW!!! in their html xD
> but actually no

... what?

**Comment by NoobTracker** [comment]
> 
> 
> OOH I KNOW!!! in their html 

:roll_eyes: I'm glad this smiley exists

**Comment by YOYITsM3M8** [comment]
>... what?

the submit button is in the html

**Comment by JeffaloBob** [comment]
> ![thatsaproblemiguess](https://user-images.githubusercontent.com/63962365/92262916-1de53d80-eedc-11ea-98f8-d557c3044b0c.PNG)
> (for those who don't speak german, Leerraum means empty space)
> forms usually have a submit button. With type="submit".

i'm pretty sure scratch's javascript handles comment posting, and the a tag is just there to have some kind of clickable element.

**Comment by NoobTracker** [comment]
But how can they identify that that `a` is clicked?

**Comment by YOYITsM3M8** [comment]
in the js look for any a with the "href" of #null

**Comment by JeffaloBob** [comment]
> But how can they identify that that `a` is clicked?

because javascript?

**Comment by NoobTracker** [comment]
There is no event listed.

**Comment by NoobTracker** [comment]
As you can see at `<textarea>`, Firefox shows events.

**Comment by NoobTracker** [comment]
Can you find out that something was clicked without using an event?

**Comment by GrahamSH-LLK** [comment]
Where is this code?

**Comment by Explosion-Scratch** [comment]
#200 nice!! (I don't speak javascriot much yet so I can't really contribute)

**Comment by NoobTracker** [comment]
> 
> 
> Where is this code?

It's from the comment box on your profile and everywhere else too I guess.

**Comment by GrahamSH-LLK** [comment]
> > Where is this code?
> 
> It's from the comment box on your profile and everywhere else too I guess.

Ah! Profiles are scratchr2. That explains it.

**Comment by NoobTracker** [comment]
Okay, didn't know that there's a difference.

**Comment by GrahamSH-LLK** [comment]
Project pages are Scratch-WWW. Studios and Profiles are scratchr2, the older repo.

**Comment by NoobTracker** [comment]
Okay, I didn't know that the `form`s are different. I know that those pages look different (and I think that r2 looks better).
