### ISSUE TITLE
Cannot click "follow" with profile page banner addon on [v1.12.0]

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#2008]
Apparently also makes "change featured project" button unclickable

@mxmou Care to fix ASAP for potentially v1.12.1?

**Comment by TheColaber** [comment]
this seems to be the problem...

https://user-images.githubusercontent.com/72760579/112905634-b92c4300-90b8-11eb-8474-83dd65a99dc5.mp4

some z-index should work...
