### ISSUE TITLE
Better quoter should use `location.hash = "#reply"` instead of `scrollIntoView`

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2018]
The better quoter addon uses `scrollntoView` to scroll down to the reply box after clicking "Quote". This is inconsistent with Scratch, which instead adds `#reply` to the URL, moving the textarea to the top of the screen, not the middle. More importantly, the current behavior of the addon makes it impossible to go back to the post after quoting using the browser back button.

#1192 did it correctly - I don't know why it was closed.

**Comment by pufferfish101007** [comment]
Thanks - I'll make sure to include this in my rewrite.

**Comment by mxmou** [comment]
This was intentional, so I don't think it can be called a bug.
