### ISSUE TITLE
[Bug] Notification Messed Up

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#202]
**Describe the bug**

When I clicked on a forum notification, it brought me to https://scratch.mit.edu/discuss/topic/%E2%9C%94%E2%9C%B3%E2%9C%85%20THE%20EMERALD%20SHOP%204.0%20%E2%9C%94%E2%9C%B3%E2%9C%85%20Quality%20orders%20done%20by%20friendly,%20reliable,%20and%20professional%20staff!%20%E2%9C%85%E2%9C%B3%E2%9C%94%20/unread/, not the post.

**To Reproduce**

Click on forum notification.

**Expected behavior**

It should open the correct page.

**Device (please complete the following information):**

ChromeOS

**Comment by GrahamSH-LLK** [comment]
It should have been https://scratch.mit.edu/discuss/topic/400433/unread/

**Comment by WorldLanguages** [comment]
Haha I made a single mistake, wrote `topic_title` instead of `topic_id`

**Comment by WorldLanguages** [comment]
Fixed on that commit ^
