### ISSUE TITLE
Follow button not working with profile page banner

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [ScratchAddons/ScratchAddons#2027]
**Describe the bug**

When the profile page banner addon is on, the follow button doesn't work.

**To Reproduce**

1. Enable profile page banner if it's not already on
2. Go to a profile that is not yours
3. Try to click the follow button

**Expected behavior**

Follow button should work

**Device (please complete the following information):**

- Windows 10
- Brave browser (chrome)
- version 89.0.4389.105

**Comment by TheColaber** [comment]
Will be fixed in the next version of ScratchAddons

**Comment by mxmou** [comment]
Duplicate of #2008
