### ISSUE TITLE
follower graph bug

### ISSUE THREAD

**Issue by Riptide-Scratch** [ScratchAddons/ScratchAddons#2028]
ok so idk if this is supposed to happen
![buuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuug](https://user-images.githubusercontent.com/70417080/113068906-1afdb300-9174-11eb-9ac0-340b42a13ef0.jpg)
[scratchers profile](https://scratch.mit.edu/users/epicm_pikachu/)

**Comment by RedGuy12** [comment]
I can't repo, but I believe this was fixed by #2016

**Comment by mxmou** [comment]
Duplicate of #2005

**Comment by mxmou** [comment]
@RedGuy12 Yes, this will be fixed in the next version.
