### ISSUE TITLE
Do not allow the extension to run on incognito mode

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#203]
The whole extension is made without incognito in mind (specially auth APIs) and many addons would break. Let's just disable it being able to work in incognito: https://developer.chrome.com/extensions/manifest/incognito

**Comment by WorldLanguages** [comment]
Note: in Chrome, it's possible to specify `"incognito": split`, which means that the extension is basically duplicated in incognito mode, so it work perfectly. However, Firefox doesn't support `split`, and if that produces an error we might not be able to specify "split" in Chrome without having separate manifests for each browser.

**Comment by Explosion-Scratch** [comment]
Hmm, I use incognito most of the time though so that my parents don't know I'm coding when I'm supposed to be doing schoolwork (I do my work quickly). Can we do the 'split' thing?

**Comment by GrahamSH-LLK** [comment]
Firefox does support split. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito

**Comment by WorldLanguages** [comment]
@GrahamSH-LLK It doesn't: https://bugzil.la/1380812
We don't care if it supports it or not tho, let's just hope it allows us to write `split` even tho it's not supported, and it should fallback to `not_allowed`, hopefully?
