### ISSUE TITLE
Image of 2D Colorpicker gets selected

### ISSUE THREAD

**Issue by BarionLP** [ScratchAddons/ScratchAddons#2032]
**Describe the bug**

The Image of the 2D Colopicker gets selected instead of the white dot (Just look the VIdeo)

**To Reproduce**

With the 2D Colopicker enabled, select a color (and hold)

**Expected behavior**

The Backgrond Image gets selected and follows the cursor.

**Screenshots**

https://user-images.githubusercontent.com/76686287/113131528-9ebfaa00-921d-11eb-8b10-def7844ff498.mp4

**Device (please complete the following information):**

- OS: Windows 10
- Browser Firefix
- 87.0

**Additional context**

**Comment by apple502j** [comment]
already fixed

**Comment by RedGuy12** [comment]
Can repo on the master with the "fix".

**Comment by GDUcrash** [comment]
weird.. I specifically remember fixing the bug with draggable background...
