### ISSUE TITLE
Short reporter labels are not centered with custom block shape addon

### ISSUE THREAD

**Issue by BarionLP** [ScratchAddons/ScratchAddons#2033]
**Describe the bug**
Names of Inputs in custom Blocks have an offset

**To Reproduce**
Create an Custom Block
Add an Input
I'm not sure but I think it has something to do with the customizable block size addon

**Screenshots**
![grafik](https://user-images.githubusercontent.com/76686287/113133798-5bb30600-9220-11eb-94e6-d3fd4705a54c.png)

**Device (please complete the following information):**

- OS: Windows 10
- Browser Firefox
- Version 87.0

**Comment by BarionLP** [comment]
I noticed that this applys to every Textfield with one Letter

**Comment by RedGuy12** [comment]
Cc @lisa-wolfgang?

**Comment by mxmou** [comment]
Can confirm. This is caused by the custom block shape addon.
