### ISSUE TITLE
Issue with custom block colors

### ISSUE THREAD

**Issue by EpicMtnGamer** [ScratchAddons/ScratchAddons#2035]
**Describe the bug**

I don't know if anyone else has experienced this problem, but the colors of the blocks are not accurate to the custom colors I have set. This doesn't happen with some block types, but any draggable objects don't have the same color as the block.

**To Reproduce**

Like I said, I don't know if anyone else has experienced this problem, so I don't know how to reproduce this issue...

**Screenshots**

![image](https://user-images.githubusercontent.com/81708033/113189303-0b8c7180-9229-11eb-9aaa-f49b9d5c70c2.png)
The motion blocks are intended to be green and the events blocks are intended to be fully cyan, not cyan with yellow.

**Device (please complete the following information):**

- OS: [e.g. iOS] Windows 10
- Browser [e.g. chrome, safari] Chrome

**Comment by WorldLanguages** [comment]
No enough info
