### ISSUE TITLE
Dark mode doesn't run on embed pages

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#2039]
This might be on purpose, but I got feedback, that they had website dark mode on, and live featured project, and it had the project running with a white border around it and also sometimes with the controls (flag, stop, etc). 

Try on `https://scratch.mit.edu/projects/485292780/embed` for example.

**Comment by mxmou** [comment]
The project player is otherwise only affected by editor dark mode but because embeds are on profile pages with live featured project I think it makes sense to add this to website dark mode.
