### ISSUE TITLE
[Bug] Tab.js:17 Cannot assign to read only property 'path' of object '#<CustomEvent>'

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#204]
**To Reproduce**

Open a project in Chrome. 

**Expected behavior**

No errors

**Screenshots**

![image](https://user-images.githubusercontent.com/17484114/92293079-18e1b780-eef7-11ea-9ec3-6d62320bce5e.png)

**Device (please complete the following information):**

Chrome only bug

**Comment by GrahamSH-LLK** [comment]
Is this a ScratchAddons bug?

**Comment by BoomerScratch** [comment]
Ping @apple502j, #135 seemed to have caused this.
