### ISSUE TITLE
No Category Icon for TW

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#2040]
![image](https://user-images.githubusercontent.com/72760579/113226169-7bb4ea80-925d-11eb-8755-72829c615c68.png)
We supported the list category... why not TW?

**Comment by GarboMuffin** [comment]
This seems like something that I should resolve in my fork with a lot of various patches, not something that needs to be in upstream

**Comment by GarboMuffin** [comment]
This can be closed, it's been fixed in the relevant downstream repository and doesn't make sense to send upstream
