### ISSUE TITLE
What about adding cat blocks?

### ISSUE THREAD

**Issue by TheSmallyDog** [ScratchAddons/ScratchAddons#2041]
I thought it would be cool to add an easter egg addon like Cat blocks and there will be a checkbox and it will say **Enable Cat Blocks when not April Fools day** and it will be able to have cat blocks even when it's not april fools day.

**Comment by pufferfish101007** [comment]
This already exists - see https://github.com/ScratchAddons/ScratchAddons/discussions/1423

**Comment by Hans5958** [comment]
@TheColaber - I suggest you to do not remove the other labels.
