### ISSUE TITLE
scratch-messaging: support JSON API for comments

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#2046]
Right now, we're still using the old `site-api` API for comments, even for project comments. Studio pages and profiles still use that, so they cannot be removed, but the `site-api/project` endpoint could be.
We should migrate to the JSON API for project comments.
Whenever we need to switch studios and profiles, the switch will also be easier if project comments already work with the JSON API.

**Comment by mxmou** [comment]
There is now a `scratch-api` endpoint for studio comments.
