### ISSUE TITLE
Textarea placeholders on profile pages are not dark

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2049]
**Describe the bug**

The placeholders for *About me* and *What I'm working on* on profile pages aren't affected by dark mode.

**To Reproduce**

1. Enable website dark mode
2. Go to your profile page
3. Remove all text from your *About me* or *What I'm working on*
4. Press "tab" or click outside of the changed textarea
5. The placeholder that appears is white

**Expected behavior**

It would be dark.

**Screenshots**

![image](https://user-images.githubusercontent.com/51849865/113415596-d5352a80-93bf-11eb-8871-63b80de25cb6.png)

**Comment by Exlectruz** [comment]
happened to me too
