### ISSUE TITLE
[Bug] getting logged out while using messaging extension

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#205]
**Describe the bug**

when using scratchaddons i get logged out very often

**To Reproduce**

no perfect repo steps, but,
1. make sure you're logged in
2. reload a lot of times
3. switch tabs
4. reload a lot of time
3. you might be logged out

**Expected behavior**

not be logged out every 10 seconds

**Screenshots**

![image](https://user-images.githubusercontent.com/40470736/92304536-2773b180-ef7f-11ea-91ac-dc2011a66efa.png)

**Device (please complete the following information):**

- OS: windows 10 1909
- Browser: chrome
- Version: latest as of when i post

**Additional context**

its annoying

**Comment by BoomerScratch** [comment]
Does it happen without ScratchAddons?

**Comment by JeffaloBob** [comment]
> Does it happen without ScratchAddons?

no

**Comment by BoomerScratch** [comment]
@JeffaloBob Oh, that kinda sucks :/

Anyways, I'm labeling this as help wanted.

**Comment by JeffaloBob** [comment]
> @JeffaloBob Oh, that kinda sucks :/
> 
> Anyways, I'm labeling this as help wanted.

sounds good.

**Comment by NoobTracker** [comment]
That really sucks. But I never had that problem. I use firefox.

**Comment by BoomerScratch** [comment]
@JeffaloBob Also, have you done [this](https://scratch.mit.edu/discuss/topic/369320/#:~:text=Here's%20the%20issue%E2%80%93)?

**Comment by JeffaloBob** [comment]
> @JeffaloBob Also, have you done [this](https://scratch.mit.edu/discuss/topic/369320/#:~:text=Here's%20the%20issue%E2%80%93)?

i don't think thats the issue, but thanks for the link!

**Comment by NoobTracker** [comment]
Well, _maybe_ the extension does that weird message loading and the comment never load thing. Maybe.

**Comment by BoomerScratch** [comment]
I'm unable to reproduce...

**Comment by NoobTracker** [comment]
Maybe it is really that bug and the extension checks the messages and loads the comments.

**Comment by JeffaloBob** [comment]
alright, i've narrowed the issue down to the Scratch Messaging addon

**Comment by NoobTracker** [comment]
Am I right? At least kinda a bit somehow?

**Comment by JeffaloBob** [comment]
ok so i talked to the world of languages and they told me to test the messaging addon update branch which does infact fix the issue.

**Comment by NoobTracker** [comment]
Okay, what exactly was the problem?

**Comment by JeffaloBob** [comment]
its trying to load comments for a user named undefined

**Comment by NoobTracker** [comment]
that's not good I know that user they get really mean comments you don't want to see their messages
