### ISSUE TITLE
The reply box becomes white when dragging backframe into it

### ISSUE THREAD

**Issue by FunctionalMetatable** [ScratchAddons/ScratchAddons#2052]
**Describe the bug**

When dragging the background into the reply box, the textarea becomes white when in dark-www addon

**To Reproduce**
Go to a forum thread,
Scroll down to the reply box,
drag something from outside into the textarea
textarea becomes white

**Expected behavior**

textarea to be dark always

**Screenshots**

![image](https://user-images.githubusercontent.com/67440879/113424978-f51d1c00-93c8-11eb-9381-46c3f622802a.png)

**Device (please complete the following information):**

- OS: Windows 10
- Browser: MS Edge
- Version: latest

**Comment by mxmou** [comment]
The screenshot looks quite a bit wrong. Could any other extension be interacting with Scratch?

**Comment by FunctionalMetatable** [comment]
> The screenshot looks quite a bit wrong. Could any other extension be interacting with Scratch?
> 
> **Edit:** Unless you intentionally made the box header green.

there is no other extension running except tampermonkey which injects green on the box header. i've disabled tampermonkey and i can still reproduce it
![image](https://user-images.githubusercontent.com/67440879/113431644-f6077b00-93d3-11eb-8c96-04163c51606a.png)

**Comment by mxmou** [comment]
Can't reproduce, unless I don't understand what "dragging the background into the reply box" means.

**Comment by FunctionalMetatable** [comment]
does this help?
![CPT2104021807-1075x693](https://user-images.githubusercontent.com/67440879/113437501-a11d3200-93de-11eb-9d27-2fd88ff61c28.gif)

(for some reason my gif recording extension hides the mouse when i press down)

**Comment by mxmou** [comment]
Still can't reproduce. I don't know what could cause this.

**Comment by WorldLanguages** [comment]
Might be an Edge only issue?

**Comment by mxmou** [comment]
@WorldLanguages I'm using Edge 89.

**Comment by Shluffy** [comment]
I can kind of reproduce. 
ChromeOS 13816.25.0, Chrome 90.0.4430.36
Latest version
browser: chrome (well, obviously)
If i drag the previous page link over the text box, but then place it outside of the text box it stays white. The text is also right,

**Comment by TheColaber** [comment]
@mxmou I bet this is also caused by image-uploader...
