### ISSUE TITLE
Lock icon staying on tab switch

### ISSUE THREAD

**Issue by TheChorister** [ScratchAddons/ScratchAddons#2054]
**Describe the bug**

The lock icon stays when viewing another tab (such as *Costumes* or *Sounds*)

**To Reproduce**

1. Enable the Auto-hide Block Palette addon.
2. Go to a project page.
3. Switch to another tab (*Costumes* or *Sounds*)
4. The lock icon will stay, floating above everything.

**Expected behavior**

The lock icon hides, when the user switches to another tab.

**Screenshots**

https://user-images.githubusercontent.com/81648449/113342931-03b2f700-9327-11eb-8579-904f9211871e.mov

**Device (please complete the following information):**

- OS: Raspbian
- Browser: Chrome
- Version: Chrome 84.0.4147.141 (Official Build), Scratch Addons v1.12.0

**Additional Context**

- Toggle on: Palette area hover
- Duration: Default

**Comment by TheColaber** [comment]
Will be fixed in v1.12.1

**Comment by WorldLanguages** [comment]
@TheChorister Update to latest version, v1.12.1 is available in both stores
