### ISSUE TITLE
Searchable My Stuff page

### ISSUE THREAD

**Issue by BarionLP** [ScratchAddons/ScratchAddons#2063]
**Describe the new addon**
The project page should be searchable.
Make sure this is compatible with the 2.0 to 3.0 addon

**Comment by mxmou** [comment]
Do you mean [this page](https://scratch.mit.edu/users/griffpatch/projects/)?

**Comment by BarionLP** [comment]
yes and the [personal ](https://scratch.mit.edu/mystuff/)

**Comment by mxmou** [comment]
I changed the title to be more clear.

**Comment by RedGuy12** [comment]
This is a duplicate.
________________________________

**Comment by mxmou** [comment]
@RedGuy12 Looks like you're right. Closing as duplicate of #1573
