### ISSUE TITLE
Set Thumbnail to stage/costume

### ISSUE THREAD

**Issue by BarionLP** [ScratchAddons/ScratchAddons#2064]
**Is your feature request related to a problem? Please describe.**
Sometimes I just want to have the current stage or the costume of a sprite as the thumbnail.

**Describe the solution you'd like**
Add buttons to the thumbnail addon which do that (as an dropdown menu, otherwise it would take up too much space)
"Set Thumbnail to current stage"
"Set Thumbnail to Costume [number/name] of [sprite]"

**Comment by TheColaber** [comment]
"Set Thumbnail to current stage" - Soooo bacially pressing "Save Now"?
"Set Thumbnail to Costume [number/name] of [sprite]" - Thumbnail Setter addon works.

**Comment by RedGuy12** [comment]
But if you have thumb setter addon then you can’t do the first

**Comment by TheColaber** [comment]
> But if you have thumb setter addon then you can’t do the first

No... you still can... there is a setting that disables it, so just disable that setting.

**Comment by BarionLP** [comment]
You mean disable, save, enable? A bit awkward... 
but ok if no one wants to program that.

**Comment by lisa-wolfgang** [comment]
This issue will probably be closed, as there is too little benefit from adding this feature. Use Scratch's regular thumbnail saving behavior or download the costume/backdrop to your computer and then upload to the Thumbnail setter addon.
