### ISSUE TITLE
[New addon] Recover '\n' in comments

### ISSUE THREAD

**Issue by NoobTracker** [ScratchAddons/ScratchAddons#207]
**Describe the new addon**

So you know that line breaks are impossible in comments? No, not really. They get somehow represented as a space, but acutally they still have the character code 10 instead of 32 like a regular space. I really don't know why they're not displayed since they're still there but I think that we should be able to somehow recover them.

I found that out by accident when I looked at some stuff I can do with comments. Every comment ends with a '\n' and that really confused me. So I made some more test and it seems like I'm right.

**Link to the new addon**

Doesn't exist.

~~Oh, btw, could that be enabled by default as a fix?~~

**Comment by NoobTracker** [comment]
Okay now it gets pretty weird.
Currently I'm coding on a markdown addon, and to understand what is in the comment since it didn't seem like it is what I expected I tried this code:
```
export default async function ({ addon, global, console }) {
  addon.settings.addEventListener("change", () => console.log("changed!"));

  while (true) {
    await addon.tab.waitForElement(".comment-content:not(.markdownForCommentsViewed),.comment .content:not(.markdownForCommentsViewed)");
    var element = document.querySelector(".comment-content:not(.markdownForCommentsViewed),.comment .content:not(.markdownForCommentsViewed)");
    element.classList.add("markdownForCommentsViewed");


    var result = '';
    for(var i = 0;i < element.parentElement.textContent.length;i++){
      result += element.parentElement.textContent.charCodeAt(i) + ' ';
    }
    alert(result);
  }
}

```
And that code told me that the comments are full of some weird stuff.

**Comment by NoobTracker** [comment]
Ah it's just me being stupid beyond belief and adding a parent somewhere so I saw the creator of the post too and stuff. No weird stuff. But the '\n's are still there.

**Comment by NoobTracker** [comment]
Okay, I rewrote the script.
```
export default async function ({ addon, global, console }) {
  addon.settings.addEventListener("change", () => console.log("changed!"));

  while (true) {
    await addon.tab.waitForElement(".comment-content:not(.markdownForCommentsViewed),.comment .content:not(.markdownForCommentsViewed)");
    var element = document.querySelector(".comment-content:not(.markdownForCommentsViewed),.comment .content:not(.markdownForCommentsViewed)");
    element.classList.add("markdownForCommentsViewed");


    var result = '\n';
    for(var i = 0;i < element.textContent.length;i++){
      result += element.textContent.charCodeAt(i) + ' ';
    }
    element.textContent += result;
  }
}
```
It seems like those comments somehow suppresses line breaks. The result should start with a new line but it doesn't.

**Comment by NoobTracker** [comment]
That would also explain why line breaks take away a character although you can't see them and you never have more then a single space.

**Comment by Explosion-Scratch** [comment]
So this would make line breaks actually work? Cool.

**Comment by NoobTracker** [comment]
> 
> 
> So this would make line breaks actually work? Cool.

Indeed, that's the idea and it seems like the data is still there so it would be actually possible.

**Comment by NoobTracker** [comment]
Is there some sort of CSS that disables line breaks? I mean, they're still there and usually they should work ...

**Comment by NoobTracker** [comment]
So, on my [alt profile](https://scratch.mit.edu/users/4mat/) I tested some stuff. The last comment contains the letters a-z but between m and n I made 20 line breaks or so. The resulting decimal stuff is 
`10 32 32 32 32 32 32 10 32 32 32 32 32 32 10 32 32 32 32 32 32 32 32 97 98 99 100 101 102 103 104 105 106 107 108 109 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 110 111 112 113 114 115 116 117 118 119 120 121 122 10 32 32 32 32 32 32 10 32 32 32 32`
`97 98 99 [...]` is abc [...]. So there's some weird stuff at the beginning and end (some lines with just a buncha spaces and then a line break it seems like, don't ask me why!) but you can see that between 109 and 110 (m and n I guess) there are some 10s. You can see the comment more or less how it was when you insert it [here](https://www.rapidtables.com/convert/number/ascii-hex-bin-dec-converter.html) in the decimal text box. So, the data is still there and you can get it by using .textContent but it isn't displayed for some reason we need to find and remove.

**Comment by JeffaloBob** [comment]
> Is there some sort of CSS that disables line breaks? I mean, they're still there and usually they should work ...

if you add `whitespace: breakspaces` it should show but the issue is that there are line breaks before every comment so then you end up with thick comments

**Comment by NoobTracker** [comment]
> 
> 
> > Is there some sort of CSS that disables line breaks? I mean, they're still there and usually they should work ...
> 
> if you add `whitespace: breakspaces` it should show but the issue is that there are line breaks before every comment so then you end up with thick comments

Well what about adding some JS? Overall, that's what my current code does I stole from the true YT links.

**Comment by JeffaloBob** [comment]
> > > Is there some sort of CSS that disables line breaks? I mean, they're still there and usually they should work ...
> > 
> > 
> > if you add `whitespace: breakspaces` it should show but the issue is that there are line breaks before every comment so then you end up with thick comments
> 
> Well what about adding some JS? Overall, that's what my current code does I stole from the true YT links.

trim the newlines from the start and end of each comment?

**Comment by NoobTracker** [comment]
> 
> trim the newlines from the start and end of each comment?

Yep

**Comment by NoobTracker** [comment]
Uh problem `whitespace: breakspaces` is invalid.
![thatsnotnice](https://user-images.githubusercontent.com/63962365/92309006-112b1d00-efa2-11ea-832f-551f20dedabc.PNG)

**Comment by JeffaloBob** [comment]
oops sorry anyways heres how it should look
![image](https://user-images.githubusercontent.com/40470736/92309048-4d5e7d80-efa2-11ea-8c63-9386c761992a.png)
and just try the different ones

**Comment by NoobTracker** [comment]
Ahhhhh that works.
