### ISSUE TITLE
i s O n l i n e

### ISSUE THREAD

**Issue by wgyt** [ScratchAddons/ScratchAddons#2076]
# isonline
## disclaimer
this has been discussed in discord but I am opening this anyways.
## how
if the user turns on the addon, show online / offline
get data from a scratch project that proxies requests to a server
add an option to share online / offline
this option would also go through the proxy project
## why
i s O n l i n e
## by the way
- I have a server that we could use that is open source

**Comment by GrahamSH-LLK** [comment]
This exists somewhere

**Comment by mxmou** [comment]
Duplicate of #342, related to #504.
