### ISSUE TITLE
Colors for Editor

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#2079]
**Describe the new addon**
So with this addon, we can choose colours for different parts of the editor Eg: Blocks Pallete, Sprite Area, Sounds Tab, Code Tab, Variables Tab, Costume Tab and Backpack

**Comment by mxmou** [comment]
Why would you want to use different colors for different tabs? If you don't need that, then this is a duplicate of #657 and will be added in version 1.13.

**Comment by Genius398** [comment]
> Why would you want to use different colors for different tabs? If you don't need that, then this is a duplicate of #657 and will be added in version 1.13.

Ok I'm sorry I'll close it

**Comment by RedGuy12** [comment]
The different colors for tabs can be accomplished using custom block colors.
