### ISSUE TITLE
Maximum brightness in settings page color picker is 99%

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2086]
**Describe the bug**

It isn't possible to set a color's brightness to 100% on the settings page. It's limited to 99%.

**To Reproduce**

1. Open the settings page
2. Open a color picker
3. Set mode to HSV
4. Increase the brightness using your mouse (not by typing into the number input)
5. At the maximum brightness the V value shows 99 and the color is visibly different from white.

**Expected behavior**

The brightness could be set to 100%.

**Comment by GrahamSH-LLK** [comment]
I think I found the solution to this, I just need to make sure it doesn't cause any regressions.
