### ISSUE TITLE
Can I redesign the settings page?

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#2088]

**Comment by RedGuy12** [comment]
Why? I dont really think it's needed.
________________________________
From: Secret-chest ***@***.***>
Sent: Tuesday, April 6, 2021 5:32:26 AM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Can I redesign the settings page? (#2088)

**Comment by TheColaber** [comment]
Why not? Create a PR with all your changes. No need for this issue.

**Comment by Secret-chest** [comment]
> Why not? Create a PR with all your changes. No need for this issue.

Ok

**Comment by WorldLanguages** [comment]
Depends, expect your PR not to be merged unless we can discuss the changes beforehand
