### ISSUE TITLE
Make it hard for users to mention "scratch addons" in Scratch comments

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#2089]
**Context**
Scratch added "scratch addons" to their comment bad word filter which is fine.
A few weeks ago they started muting new scratchers that commented that.
Now, even 6 y/o accounts get a 5 minute mute for "not following the Community Guidelines".
This modal is clearly confusing and doesn't direct Scratchers to the userscript/extension policy, and fixing it is likely not considered a priority by the Scratch Team.
![image](https://user-images.githubusercontent.com/17484114/113735011-36b40c80-96d2-11eb-91f8-ac2f269d22ba.png)

**Suggestion**
- If the user is about to post a comment that mentions "scratch addons" (case insensitive), make sure the comment is not actually sent to the Scratch servers yet.
- Use the same alert format but with our own message (making sure it's clear it's by us, related to #1880), telling users their comment was not sent (did not reach Scratch servers), linking them to the userscript/extension policy.
- That alert should have a small link/button named "send anyway" that can only be clicked after 3 seconds have happened. When clicked, we should trigger a `confirm()`. It's pretty obvious the user will get muted for 5 minutes, but we don't want to actually *prohibit* users for doing anything with their account as long as they are aware of the consequences.

**Comment by CubeyTheCube** [comment]
In general how about SA implements their own filter that prevents people from getting muted by not sending the comments to the server if they contain a bad word - not 100% sure if the st will like that though

**Comment by RedGuy12** [comment]
Lol, the ST doesn't like anything we do

**Comment by WorldLanguages** [comment]
I don't think we should maintain a list of muted words. In order to test whether a word is muted we need to try commenting it, and that comment might end up in a moderation queue of some sort, which we don't want to spam.

**Comment by retronbv** [comment]
> I don't think we should maintain a list of muted words. In order to test whether a word is muted we need to try commenting it, and that comment might end up in a moderation queue of some sort, which we don't want to spam.

Can we somehow find the list?

**Comment by mxmou** [comment]
@retronbv No, the list is private.

**Comment by retronbv** [comment]
> @retronbv No, the list is private.

I thought someone said something about the list somewhere in the discord

**Comment by mxmou** [comment]
I think we should also do this to "scratchaddons" and "fbeffbjdlemaoicjdapfpikkikjoneco" (the extension ID) to also prevent links - Scratch will likely add those to the blacklist too.

Could this also be done on the forums? Muting doesn't exist there but people could still get an alert.

**Comment by CubeyTheCube** [comment]
Scratch uses cleanspeak's api, all we need to do is add a couple of words to the filter, then send the comment to a server before posting, if it's clean then it will be sent. It can't be perfect but it will create 99% less 6 year old rage

**Comment by WorldLanguages** [comment]
> send the comment to a server before posting

bruh no

**Comment by CubeyTheCube** [comment]
> > send the comment to a server before posting
> 
> bruh no

oh yeah that might be a bad idea. and storing bad words client side also is. hmmm

**Comment by Hans5958** [comment]
> In general how about SA implements their own filter that prevents people from getting muted by not sending the comments to the server if they contain a bad word.

This, please. Just implement list of words that we already know it is illegal to do. I don't mind if it's incomplete or some sorts. It's better than nothing.

**Comment by WorldLanguages** [comment]
Are you sure about including a list of bad words as part of the extension source...?

**Comment by TheColaber** [comment]
I think he might have meant the ones for scratch addons but...

**Comment by WorldLanguages** [comment]
The main goal with this specific issue is giving users context, not making sure they follow the rules. Previously, if you mentioned scratch addons your comment would get reported and/or probably get in a "suspicious comments" moderation queue - and you'd get an alert that would link to the policy. This 5 min mute also affects your account but does not link to the policy, which is important context. We do not need to stop the comment from getting posted to provide context, but it would be weird not to do so.

**Comment by WorldLanguages** [comment]
lol
![image](https://user-images.githubusercontent.com/17484114/113896377-413cd780-97a0-11eb-9b96-3db9b0b3e106.png)

**Comment by jeffalo** [comment]
> lol
> ![image](https://user-images.githubusercontent.com/17484114/113896377-413cd780-97a0-11eb-9b96-3db9b0b3e106.png)

![image](https://user-images.githubusercontent.com/40470736/113896594-5fb7c880-97ca-11eb-874b-dbf904996f32.png)

**Comment by Hans5958** [comment]
> Are you sure about including a list of bad words as part of the extension source...?

Yes. Will there be problems?

And, yes, this is off-topic.

**Comment by WorldLanguages** [comment]
> Yes. Will there be problems?

Probably... not, but who knows? Why risk it...?

**Comment by Hans5958** [comment]
> > Yes. Will there be problems?
> 
> Probably... not, but who knows? Why risk it...?

YOLO

**Comment by mxmou** [comment]
And I don't think we need that - the purpose of an extension isn't to prevent users from breaking Scratch rules. The extension policy is an exception because the message Scratch shows is unclear.

**Comment by Hans5958** [comment]
> 
> 
> And I don't think we need that - the purpose of an extension isn't to prevent users from breaking Scratch rules. The extension policy is an exception because the message Scratch shows is unclear.

Keep in mind that my suggestion is the ones that diverges the main point addresed on the issue. 

We're on different sides here. I think having a filter that catches comments with a bad word before it got sent is something I count as feature that empowers the Scratch experience. I sometimes don't know when something is muted or not, so having an addon that catches it first before Scratch catches it would be useful to me.

But, again. This a different addon. I suppose I should create another issue addressing this.

#2104

**Comment by DogCatPuppyLover** [comment]
#2104

**Comment by Miala-python** [comment]
On scratch, we can't know what is the word problem.
(Sorry, I don't speak English)

**Comment by Sly-Little-Fox** [comment]
Why not to create an addon instead of adding filter to the core? It would be easier and more convenient for users (some users may want to disable it).

**Comment by WorldLanguages** [comment]
@Sly-Little-Fox Users can still post the comment by clicking "Post anyway" then "confirm". Not a big deal.
Keep in mind 99% of times the comment won't get posted anyway because of Scratch's filter (as long as the user didn't find a way to bypass it, but not our filter)

**Comment by Sly-Little-Fox** [comment]
> @Sly-Little-Fox Users can still post the comment by clicking "Post anyway" then "confirm". Not a big deal.
> Keep in mind 99% of times the comment won't get posted anyway because of Scratch's filter (as long as the user didn't find a way to bypass it, but not our filter)

Yes, but changing core for it is just weird.
