### ISSUE TITLE
Color picker component blocks main thread in settings page for many seconds

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#2090]
Haven't tested deeply, but I ran the Chrome profiler and it's related to the color picker component. Not sure if it's a Vue issue or a ColorPicker element issue.
I was also able to reproduce that blocking file `libraries/color-picker.js` from loading using devtools "network request blocking" caused load time to go from ~7s to ~2s

**Comment by GrahamSH-LLK** [comment]
Should we wait until the page is loaded to load the color picker?

**Comment by WorldLanguages** [comment]
Let's first try to figure out what actually blocks the main thread related to the color picker...?

**Comment by RedGuy12** [comment]
Yeah, defer it
________________________________

**Comment by WorldLanguages** [comment]
Potential easy fixes:
1. Only using one color picker for the whole page with some CSS magic - would work since user only has one color picker active at a time
2. Delay loading the color picker until the user hovers or clicks:
```html
    <template id="picker-component">
      <div class="color-container" :key="value" @click="loadColorPicker = true" @mouseover="loadColorPicker = true">
        <button :style="{'background-color': color }" class="setting-input color" @click="toggle(addon,setting,true)">
          <template v-if="loadColorPicker">
            <color-picker
            class=""
            :value="value"
            id="picker"
            v-show="isOpen"
            v-click-outside="isOpen = false"
            v-el:pickr
            :formats="formats"
            :no_alpha="no_alpha"
          ></color-picker>
          </template>
        </button>
      </div>
    </template>
```

I'm still not 100% sure why the color picker is slow, but that might be out of our control, since we're using a 3rd party library

**Comment by GrahamSH-LLK** [comment]
CSS magic would truly have to be that: magic.
The only way we keep it aligned with the button is that it’s a child of it.

**Comment by RedGuy12** [comment]
Or we could have one color picker element that we move around the page with JavaScript

**Comment by WorldLanguages** [comment]
> Or we could have one color picker element that we move around the page with JavaScript

... and CSS

**Comment by RedGuy12** [comment]
> > Or we could have one color picker element that we move around the page with JavaScript
> 
> ... and CSS

according to Graham, it'd have to be a child of the button, so we'd need javascript to move it around, not css

**Comment by GrahamSH-LLK** [comment]
> > > Or we could have one color picker element that we move around the page with JavaScript
> > 
> > 
> > ... and CSS
> 
> according to Graham, it'd have to be a child of the button, so we'd need javascript to move it around, not css

It couldn’t be pure CSS, but JS would work. I forgot that the CSS changing would be done by JS.

**Comment by WorldLanguages** [comment]
PR above ^ implemented option 2.
We should find the root cause of this and find if we can fix it. If we 1) can't find it or 2) can't fix it, we should try using another color picker library, and see if the issue still persists with that one.

**Comment by apple502j** [comment]
Moved to #2531

**Comment by WorldLanguages** [comment]
> Moved to #2531

I mean yeah, it's one of the causes, but this probably deserves an issue of its own... Maybe
