### ISSUE TITLE
Extension block error in developer tools

### ISSUE THREAD

**Issue by Chikorita-Lover** [ScratchAddons/ScratchAddons#2095]
Blocks from Scratch extensions, such as music and pen, appear with transparent backgrounds in the middle-click pop-up menu in griffpatch's developer tools.

**To Reproduce**

1. Enable griffpatch's developer tools
2. Add an extension (such as music) to your Scratch project
3. Middle-click the code area
4. Search for a block from the extension
5. See error

**Expected behavior**
Extension blocks should have colored backgrounds.

**Screenshots**
![Screenshot of bug](https://media.discordapp.net/attachments/754186550061039687/829155287948328971/unknown.png)

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 89.0.4389.114 (Chrome)

**Comment by mxmou** [comment]
Caused by the customizable block colors addon.

**Comment by RedGuy12** [comment]
Sounds like this is still happening? https://github.com/TurboWarp/scratch-gui/issues/159

**Comment by Chikorita-Lover** [comment]
Nope, it was just patched in version 1.14.0 :D
