### ISSUE TITLE
Color picker doesn't prevent setting transparency if `allowTransparency` is set to false

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2097]
**Describe the bug**

Yes, another color picker bug. Omitting the `allowTransparency` property of a color setting in `addon.json` adds a `no_alpha` attribute to the web component, which has no effect: <del>the color picker source code doesn't even mention "no_alpha" anywhere</del> I was wrong, it does. This means that the user can still make the color transparent.

**To Reproduce**

1. Clone [this branch](https://github.com/mxmou/ScratchAddons/tree/dark-presets) or just remove `allowTransparency` from an existing `addon.json`
2. Open the settings page
3. Change the transparency of any editor dark mode setting except the border color, or the color from which you removed `allowTransparency`
4. The transparency changes and the transparent setting can be accessed by the addon normally

**Expected behavior**

It would not be possible to make colors that don't enable transparency transparent.

**Comment by GrahamSH-LLK** [comment]
> the color picker source code doesn't even mention "no_alpha" anywhere
What?! Did I forget to push something?

**Comment by GrahamSH-LLK** [comment]
This shouldn't be a bug, afaik. The code is there.

**Comment by mxmou** [comment]
> This shouldn't be a bug, afaik. The code is there.

Weird. In #1805 only one color sets `allowTransparency` but I'm able to make all of them transparent.

**Comment by mxmou** [comment]
This will likely cause problems if not fixed before 1.13.0.
