### ISSUE TITLE
Addons should be able to change how settings are exposed to CSS

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2099]
**Is your feature request related to a problem? Please describe.**

Currently settings are provided to CSS as custom properties. If any other values (typically colors) are needed by a userstyle, they need to be set by a userscript (like I did in #1805) which means that users have to wait for the correct colors. This can be a problem for website dark mode where users frequently navigate between pages.

**Describe the solution you'd like**

A new `addon.json` property with the following syntax:
```json
{
  "cssVariables": [
    {
      "name": "setting1",
      "value": "setting1"
    },
    {
      "name": "setting1-text",
      "value": {
        "type": "textColor",
        "source": "setting1",
        "black": "rgba(0, 0, 0, 0.5)",
        "white": "rgba(255, 255, 255, 0.5)"
      }
    }
  ]
}
```

`"name"` would be the name of the CSS variable. `"value"` would be a setting name or an object with a `"type"` property describing a color operation and additional properties depending on the type. Most types would have a `"source"` property which could be a setting name or another such object. Possible values for the `"type"` could be:
* `"textColor"`: automatically selects an appropriate text color (or border color, image filter etc.) based on the source. `"black"` would be the value that is used for light background colors (the default could be `#575e75`) and `"white"` the value for dark backgrounds (defaults to `#ffffff`). An optional property called `"threshold"` would be used to specify how bright/dark the background color needs to be to be considered bright/dark.
* `"multiply"`: makes a source color darker or more transparent. Additional properties would define the coefficients for red, green, blue and alpha valules.
* `"brighten"`: similar to the above, but makes the source brighter or less transparent. Would do the same thing as line 38 of `text_color.js` in #1805. (Probably rarely useful but exactly what I need for generating the secondary color in editor dark mode.)
* `"alphaBlend"`: would have two source colors, the first one would need to be opaque, the second one could be transparent. Would return an opaque color equivalent to drawing the second source on top of the first one.

If this replaces the implicitly created variables it would also reduce the amount of them.

This could be extended to work with other setting types, not just colors.

**Comment by RedGuy12** [comment]
But why would they need it in a variable if it wasn’t dynamic?

If I’m misunderstanding this and it is dynamic, then why wouldn’t the preexisting settings work for this?

**Comment by WorldLanguages** [comment]
Title might be misleading, it looks like the main thing to achieve here is being able to do simple operations on color settings without needing a userscript, and exposing those results as CSS variables. Of course they would still be calculated by JavaScript, but it would be done as part of cs.js
