### ISSUE TITLE
Smart Costume Duplication

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#2100]
Suggestion from ClearlyNotACupcake#3241:
when duplicating costumes and if the name of the costume is one single letter, instead of the new name being like 'A2', name it 'B'

**Comment by Endermaster3690** [comment]
and if its named 0 make it 1

**Comment by TecFuture** [comment]
This would be helpful but what if 

When you duplicate costumes, it changes name in scratch backend code but in frontend it displays the same costume name as the original. You can also edit it and after you edit the name is changed and now thats the official name also in the backend code.

**Comment by xItzDiamondx** [comment]
Nice idea. I'll try to develop that.

**Comment by Secret-chest** [comment]
> This would be helpful but what if
> 
> When you duplicate costumes, it changes name in scratch backend code (like costume2) but in frontend it displays the same costume name as the original(like costume).
> 
> You can also edit it and after you edit the name is changed and now thats the official name also in the backend code.

@TecFuture I don't like that. I think it will only make it harder for you to keep track of your costumes.

**Comment by TecFuture** [comment]
> > This would be helpful but what if
> > When you duplicate costumes, it changes name in scratch backend code (like costume2) but in frontend it displays the same costume name as the original(like costume).
> > You can also edit it and after you edit the name is changed and now thats the official name also in the backend code.
> 
> @TecFuture I don't like that. I think it will only make it harder for you to keep track of your costumes.

Make it a option?

**Comment by CubeyTheCube** [comment]
> > > This would be helpful but what if
> > > When you duplicate costumes, it changes name in scratch backend code (like costume2) but in frontend it displays the same costume name as the original(like costume).
> > > You can also edit it and after you edit the name is changed and now thats the official name also in the backend code.
> > 
> > 
> > @TecFuture I don't like that. I think it will only make it harder for you to keep track of your costumes.
> 
> Make it a option?

Seems confusing even if it is an option. Either way you can make costume names the "same" using zero-width unicode characters.

**Comment by WorldLanguages** [comment]
Let's say the idea is rejected, I guess
