### ISSUE TITLE
Middle clicking the changelog link in the popup opens the popup in a new tab

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2105]
**Describe the bug**

Middle clicking the changelog link in the popup opens the popup in a new tab.

**To Reproduce**

1. Open the popup.
2. Middle click the version number.

**Expected behavior**

The changelog opens normally. This could be done by adding `preventDefault()` to the click event listener or by changing the href from `#` to the changelog page.

**Comment by oof-le-oof** [comment]
Middle clicking is generally used to open things in new tabs. If that option was removed, some users might get confused.

**Comment by mxmou** [comment]
@oof-le-oof It won't be removed, but it should open the changelog, not this:
![image](https://user-images.githubusercontent.com/51849865/114138669-41f37c00-990e-11eb-9145-38ad6bff1174.png)
