### ISSUE TITLE
Website dark mode makes ban message unreadable

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2106]
**Describe the bug**

Website dark mode makes the ban message ("None Your account will be automatically unblocked..." for automatic bans) unreadable.

**To Reproduce**

1. Enable website dark mode
2. Log into an account that is banned (if you have any)
3. Try to read the message

**Expected behavior**

It would be readable. It could be fixed by setting the background color of `.contact #block-message` to `#333333`.

**Comment by xItzDiamondx** [comment]
Could be fixed.

**Comment by Samq64** [comment]
Will the website dark mode rewrite fix this?

**Comment by mxmou** [comment]
> Will the website dark mode rewrite fix this?

Probably not.

**Comment by WorldLanguages** [comment]
> It would be readable. It could be fixed by setting the background color of `.contact #block-message` to `#333333`.

A user with a banned account was able to confirm this would work.
