### ISSUE TITLE
add image by url upload to image-uploader

### ISSUE THREAD

**Issue by FunctionalMetatable** [ScratchAddons/ScratchAddons#2107]
**Describe the solution you'd like**
To be able to upload an image from an URL to assets.scratch.mit.edu

**Comment by RedGuy12** [comment]
Workaround:

Open the image in new tab

Right click and select “copy image”

Go back to the forums

Do ctrl+v in the textbox

**Comment by FunctionalMetatable** [comment]
> Workaround: Open the image in new tab Right click and select “copy image” Go back to the forums Do ctrl+v in the textbox

but svgs like https://shields.io/badge/example-test-brightgreen - you can't copy it

**Comment by jeffalo** [comment]
this is not (easily) possible due to cors.

**Comment by WorldLanguages** [comment]
This needs a server

**Comment by TecFuture** [comment]
> This needs a server

Server for what?

**Comment by mxmou** [comment]
> > This needs a server
> 
> Server for what?

For fetching the image, because of CORS (a restriction that prevents websites from sending requests to other domains if those domains don't explicitly allow cross-origin requests).

**Comment by RedGuy12** [comment]
Doesn't need a server,  see https://stackoverflow.com/a/9612294/11866686
________________________________

**Comment by WorldLanguages** [comment]
@RedGuy12 Did you actually test it...? If you can somehow read cross origin images, report the vulnerability to browsers and get money or write a blog post on how the web is broken

**Comment by mxmou** [comment]
@RedGuy12 I don't think that works. `toDataURL()` throws an error if a cross-origin image was drawn onto the canvas. https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL#exceptions

**Comment by CubeyTheCube** [comment]
> @RedGuy12 I don't think that works. `toDataURL()` throws an error if a cross-origin image was drawn onto the canvas. https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL#exceptions

Convert the cross origin image to a data url, then render that on the canvas

**Comment by mxmou** [comment]
> Convert the cross origin image to a data url, then render that on the canvas

You can't convert it to a data URI without rendering it on the canvas.

**Comment by CubeyTheCube** [comment]
> > Convert the cross origin image to a data url, then render that on the canvas
> 
> You can't convert it to a data URI without rendering it on the canvas.

I'm pretty sure you can with the fetch and FileReader APIs. 
https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL

Here's some rough code
```js
function getDataURI(imageURL) {
  return new Promise((resolve, reject) => {
    fetch(imageURL) // you might need a cors proxy 
    .then(resp => resp.blob())
    .then(file => {
      const reader = new FileReader();
      reader.addEventListener("load", function () {
        const { result } = reader;
        resolve(result);
      }, false);
      reader.readAsDataURL(file);
    });
  });
}
```

**Comment by jeffalo** [comment]
> you might need a cors proxy

**Comment by WorldLanguages** [comment]
> > you might need a cors proxy

Hence, a server

**Comment by CST1229** [comment]
By the way, at least on Firefox, if you paste an image URL into the file name box in a file select dialog, it gets downloaded into a temp folder and that gets used.

**Comment by FunctionalMetatable** [comment]
> By the way, as a workaround, at least on Firefox, if you paste an image URL into the file name box in a file select dialog, it gets downloaded into a temp folder and that gets used.
> IDK if it works on Chrome.

it works for me too.

but its better to have something like this, right?

**Comment by silvxrcat** [comment]
I need this, so I'm replying.

**Comment by Norbiros** [comment]
Theoreticaly, because we are browser extension (not webpage) we can override cors header in requests. Something like this: https://github.com/balvin-perrie/Access-Control-Allow-Origin---Unblock

**Comment by apple502j** [comment]
How was this not closed before? Clearly not something we can do, or will do. We do not include CORS proxy functionality inside extension for review purposes, and we do not host servers just for this.
