### ISSUE TITLE
 2.0 → 3.0 studio description scrollbar doesn't work

### ISSUE THREAD

**Issue by vivilua** [ScratchAddons/ScratchAddons#2130]
When using the 2.0 → 3.0 addon, the scrollbar on studio descriptions doesn't move nor does it affect the viewport when it's clicked and dragged.

- OS: Windows 10
- Browser: Firefox 87.0 (64-bit)

**Comment by mxmou** [comment]
Can reproduce. I can scroll using the mouse wheel but not using the scrollbar.

**Comment by RedGuy12** [comment]
Pointer-events ?
________________________________

**Comment by xItzDiamondx** [comment]
I believe it was changed today.

**Comment by WorldLanguages** [comment]
@xItzDiamondx Your comments aren't very helpful, what changed today?

**Comment by mxmou** [comment]
This is happening again. https://scratch.mit.edu/users/Maximouse/#comments-196239395
