### ISSUE TITLE
[Bug] I can't reply to profile posts in the extension

### ISSUE THREAD

**Issue by NoobTracker** [ScratchAddons/ScratchAddons#214]
**Describe the bug**

As far as I understand that you should be able to open that message thingy and then just reply there. Well, that doesn't work. Kinda. Because when I wanted to reply finally, it said that it looks like I'm commenting really quickly and I need to take a break.

**To Reproduce**

Just somehow get a profile comment message and try to reply.

**Expected behavior**

Nothing. You click on the post button but nothing happens.

**Device:**

- OS: Win7
- Browser Firefox
- Version Umm ... the newest one

**Additional context**

Maybe it's related to the log out problem, #205

**Comment by apple502j** [comment]
Can you open the debugger for the extension?

**Comment by NoobTracker** [comment]
Um ... how?

**Comment by apple502j** [comment]
about:debugging should have a button to open console

**Comment by NoobTracker** [comment]
Ah yes.

**Comment by NoobTracker** [comment]
No errors when I try to send the message.
When it works then the reply form should disappear, right?

**Comment by GrahamSH-LLK** [comment]
Try redownloading the extension.

**Comment by NoobTracker** [comment]
Did that now and I already saw that some stuff changed. Let me test it.

**Comment by NoobTracker** [comment]
Ah .... now it works.
