### ISSUE TITLE
Un-upload a Thumbnail

### ISSUE THREAD

**Issue by 22yeetz22** [ScratchAddons/ScratchAddons#2140]
**Is your feature request related to a problem? Please describe.**

When you upload a thumbnail from the "Set Thumbnail" button, is it possible to undo that?

**Describe the solution you'd like**

To add a clear thumbnail button or something like that.

**Describe alternatives you've considered**

Ask if you want to add or delete the thumbnail.

**Additional context**

I'm not still sure if that was a thing, so can you make sure?

**Comment by WorldLanguages** [comment]
Just resave the project

**Comment by 22yeetz22** [comment]
> Just resave the project

What do you mean? I want to delete it from the project.

**Comment by WorldLanguages** [comment]
@22yeetz22 Make any edits to the project (inside the editor), then click "save now"
