### ISSUE TITLE
Extended key detection

### ISSUE THREAD

**Issue by DogCatPuppyLover** [ScratchAddons/ScratchAddons#2157]
**Describe the new addon**

This addon would enable users to detect keys like backspace, ctrl/shift/alt/other special keys and capital versus lowercase letters. They would work something like this, similar to the sa-pause block:

![Screenshot 2021-04-13 190239](https://user-images.githubusercontent.com/79656307/114643608-db15f000-9c8a-11eb-89e6-0a4d46b14f65.png)

**Comment by TheColaber** [comment]
This rejected because all non-sa users would have the game being unplayable.
