### ISSUE TITLE
[Bug] The forkphorus stage replace stuff is kinda broken

### ISSUE THREAD

**Issue by NoobTracker** [ScratchAddons/ScratchAddons#216]
I just found a bug in my own addon and that confuses me. When you click on forkphorus on [this project](https://scratch.mit.edu/projects/421062771/), then weird things happen, the original stage is still there. But that's literally the only project where that's the case! And I dunno why.

(btw, the project is pretty broken in fork)

**Comment by WorldLanguages** [comment]
Closing, bug around addon that isn't included for now. Hopefully we will be able to come out with a nice pretty addon to use 3rd party players within Scratch.
