### ISSUE TITLE
Copy and Paste a Block Definition

### ISSUE THREAD

**Issue by 22yeetz22** [ScratchAddons/ScratchAddons#2164]
**Describe the bug**

When you right-click a block definition with dev tools enabled, you see an option for copying that definition. Once you copy it and paste it, you have 2 of the same block definitions.

**To Reproduce**

1. Enable Griffpatch's developer tools extension.
2. Make a block definition.
3. Right-click it.
4. Click on the option that says "Copy Block"
5. Right-click somewhere else.
6. Select the "Paste" option
7. There are now 2 of the same block definitions.

**Expected behavior**

It to not let it happen or to alert me or something.

**Screenshots**

![Screenshot 2021-04-14 105414 Glitch](https://user-images.githubusercontent.com/74276537/114740828-d2b3c880-9d0f-11eb-908d-e09088634b9a.png)

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome
- Version:  89.0.4389.114 (Official Build) (64-bit)

**Additional context**

**Comment by xItzDiamondx** [comment]
I don't understand the problem.

**Comment by Secret-chest** [comment]
It's cool to be able to make two scripts run as a custom block.

**Comment by griffpatch** [comment]
This is a Scratch bug - you can use the Ctrl+C then Ctrl+V to do the same thing - The extension just exposes this feature using the right click menu.
