### ISSUE TITLE
[New addon] see inside but make cloud variables still eprk

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#217]
**Describe the new addon**

when the user sees inside, cloud variables should continue to work

**Link to the new addon**

n/a

**Comment by apple502j** [comment]
I don't think this is allowed. Easy to do if you use redux, though.

**Comment by BoomerScratch** [comment]
Yeah, this will lead to a lot of hacking, alerts, and bans.

**Comment by WorldLanguages** [comment]
Please no :P

**Comment by JeffaloBob** [comment]
:( fine

**Comment by NoobTracker** [comment]
:( 
I already thought about suggesting that.
