### ISSUE TITLE
Email confirmation unreadable with dark-www

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2170]
**Describe the bug**

The page where you can confirm your email address is unreadable (white text on white background) if the `dark-www` addon is enabled.

**To Reproduce**

1. Create a new account
2. Click the "Confirm your email" link in the banner

**Expected behavior**

It would be readable.

**Comment by WorldLanguages** [comment]
@mxmou Bump, seems like an easy bug to fix? Or maybe it was fixed and you forgot to close.

**Comment by mxmou** [comment]
@WorldLanguages Not fixed. I forgot to do it.
