### ISSUE TITLE
Still asks "Share?" When already shared

### ISSUE THREAD

**Issue by 22yeetz22** [ScratchAddons/ScratchAddons#2176]
**Describe the bug**

**To Reproduce**

1. Check "confirm actions" and check all of the little checkboxes.
2. Make a new project.
3. Share it. It will ask you again to make sure. Click "OK".
4. Go inside again while it is shared.
5. Click "Shared".
6. It will still ask you to share when it is already.

**Expected behavior**

To unshare or to ask me to unshare.

**Screenshots**

![Screenshot 2021-04-15 105138 Glitch](https://user-images.githubusercontent.com/74276537/114900281-5685b780-9dd9-11eb-9039-722df1dd9b6f.png)

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: Version 90.0.4430.72 (Official Build) (64-bit)

**Additional context**

nothing

**Comment by RedGuy12** [comment]
There’s no unshare button tho…

**Comment by 22yeetz22** [comment]
Oh I meant the "Shared" button

**Comment by GrahamSH-LLK** [comment]
We should make that into an unshare button!

**Comment by WorldLanguages** [comment]
...making sure the user doesn't click by accident

**Comment by Cool-Scratcher** [comment]
> We should make that into an unshare button!

Happy accidents.
