### ISSUE TITLE
Update all settings at once when setting presets

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#2177]
Right now, every setting is updated individually, causing several writes to `chrome.storage` and many "change" events on `addon.settings`.
Instead, they should all be set at once. Addons don't have any way to listen for *single* setting changes so that's not a problem.
This also causes a weird cascade effect when setting a preset in a theme and seeing it update realtime, you can see it load step by step:
![Mb7l4MJC8U](https://user-images.githubusercontent.com/17484114/114933888-99628200-9e0f-11eb-97e5-17e7a6dd17ba.gif)

**Comment by RedGuy12** [comment]
Maybe all settings should be updated simultaneously not just presets, `onbeforeunload`. But that might not be the best when you'd have to close the popup for settings to be updated. Maybe only on the settings **page**?

**Comment by WorldLanguages** [comment]
@RedGuy12 Not sure what you mean. The point here is that there's no reason to update each setting one by one, and it probably creates a little CPU/disk activity spike hehe
