### ISSUE TITLE
Make cloud variables change when someone else changes them, but not when you change it.

### ISSUE THREAD

**Issue by BoomerScratch** [ScratchAddons/ScratchAddons#218]
**Describe the new addon**

When you see inside the project, all the cloud variables get disabled _completely_. So, when someone else changes the cloud variables, the cloud variable doesn't change. This new addon does change the cloud variables in the editor if someone else changes it, but if _you_ change it after clicking 'see inside', it doesn't change for others.

This is the non-hacky version of #217.

**Comment by NoobTracker** [comment]
Well, that doesn't do much at all. Cloud games are still broken when you see inside. Why would you want to see what other people do? That's kinda weird.

What would be cooler imo is that cloud vars are only disabled when you actually change something in the editor.

But probably such a thing could be easily modded to make cloud vars still work and set the record time on a griffpatch project to 0 or something.

**Comment by Explosion-Scratch** [comment]
Yeah, it sounds cool, but I really don't see a good use for it.

**Comment by NoobTracker** [comment]
> 
> 
> Yeah, it sounds cool, 

mostly in the first second and after that initial second you realize that that is not that useful but could be easily modded to be something useful.

**Comment by TheColaber** [comment]
this sounds useless unless you can give me any reason why someone needs this.

**Comment by RedGuy12** [comment]
Also would be extremely laggy.
________________________________
