### ISSUE TITLE
Mini-map editor

### ISSUE THREAD

**Issue by Miala-python** [ScratchAddons/ScratchAddons#2187]
Hello,
I have an idea: a mini-map in the editor for look the define blocks.
It's just an idea.
Thank you.

(Sorry, I don't really speak English)

**Comment by retronbv** [comment]
Like the little view in vsc?

**Comment by RedGuy12** [comment]
I believe you want a way to find define blocks. If that is so, then this is already implemented in the **Scratch Developer Tools** addon by griffpatch.
![image](https://user-images.githubusercontent.com/61329810/115087117-389c7d80-9ed3-11eb-82ee-cdecb8ea5e6a.png)
