### ISSUE TITLE
Auto-hide block pallete animation not working in some devices

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#2190]
Including my own, will try to find out why it doesn't work later.
Regression by #1980, it worked for me before that change.

**Comment by RedGuy12** [comment]
Which modes?

**Comment by WorldLanguages** [comment]
@RedGuy12 all of them iirc, i'll include more information later.

**Comment by RedGuy12** [comment]
Works for me.

Windows 10
Microsoft Edge
Master branch

**Comment by RedGuy12** [comment]
I'll

**Comment by WorldLanguages** [comment]
I can't seem to reproduce again on master
