### ISSUE TITLE
Loading presets for addons with color settings is not possible

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2196]
**Describe the bug**

Caused by #2191

Loading any preset on any addon with color settings (e.g. editor dark mode) results in the following error:
```
Uncaught (in promise) TypeError: Cannot read property '_valueChanged' of undefined
    at VueComponent.value (index.js:75)
```

**To Reproduce**

1. Open the settings page
2. Load any editor dark mode preset
3. Open the console - there is an error
4. Try to interact with the settings page - it doesn't work

**Expected behavior**

Presets could be loaded.

**Comment by TheColaber** [comment]
Well, this is the simple fix... but this is because the pickers don't exist because of the new change. 
![image](https://user-images.githubusercontent.com/72760579/115115011-2157a180-9f60-11eb-8aba-1503c4ee69d9.png)

**Comment by RedGuy12** [comment]
> Well, this is the simple fix... but this is because the pickers don't exist because of the new change.
> ![image](https://user-images.githubusercontent.com/72760579/115115011-2157a180-9f60-11eb-8aba-1503c4ee69d9.png)

but then wouldn't they not update?

**Comment by RedGuy12** [comment]
oops wrong button

**Comment by TheColaber** [comment]
> but then wouldn't they not update?

they don't exist yet.

**Comment by WorldLanguages** [comment]
Nice catch sorry for not testing enough :C
