### ISSUE TITLE
Inconsistant Scrollbars between browsers

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#2198]
This seems to be within the webpages and here is an example:
![image](https://user-images.githubusercontent.com/72760579/115117178-4998cd80-9f6b-11eb-85f5-3f57df49fefb.png)
Left: FF
Right: Chrome
They should be styled to look like chrome.

**Comment by mxmou** [comment]
This is because `scrollbar-color` is set to `grey none`. It should be `grey transparent`.

**Comment by mxmou** [comment]
They can't look exactly like Chrome though because Firefox doesn't support `::-webkit-scrollbar`.
