### ISSUE TITLE
Clicking a color setting with an open color picker should close the picker

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2201]
**Is your feature request related to a problem? Please describe.**

Normally clicking on an open dropdown closes it. The settings page color picker doesn't do that.

**Describe the solution you'd like**

Clicking a setting with an open color picker would close the picker.

**Comment by GrahamSH-LLK** [comment]
This replicates input[type=color], @WorldLanguages told me to add this.

**Comment by mxmou** [comment]
@GrahamSH-LLK `<input type="color" />`'s behavior is weird and was likely added to match the old behavior (it used to open a dialog box, and it still does on Firefox). `<select>` and practically every dropdown in any application is closed if you click it while it's open.

**Comment by GrahamSH-LLK** [comment]
> @GrahamSH-LLK `<input type="color" />`'s behavior is weird and was likely added to match the old behavior (it used to open a dialog box, and it still does on Firefox). `<select>` and practically every dropdown in any application is closed if you click it while it's open.

Okay, I'll remove it!

**Comment by WorldLanguages** [comment]
Reopened bc of #2374
