### ISSUE TITLE
Opening editor from My Stuff on Firefox causes a crash

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2206]
**Describe the bug**

Opening the editor from My Stuff on Firefox results in the following error on line 180 of `module.js`: `Uncaught TypeError: can't access property "tab", scratchAddons.eventTargets is undefined`. Apparently Scratch calls `replaceState` before data is received from the background script.

**To Reproduce**

1. Open the My Stuff page
2. Click a "See inside" button

**Expected behavior**

There would be no errors.

**Comment by WorldLanguages** [comment]
Nice catch
