### ISSUE TITLE
Disappearing text bug

### ISSUE THREAD

**Issue by Chaos-emerald** [ScratchAddons/ScratchAddons#2225]
**Describe the new addon**

This will just delete the code for the block text.

**Link to the new addon**

No link, sorry.

**Comment by Chaos-emerald** [comment]
bump

**Comment by RedGuy12** [comment]
is there a bug or do you want a new feature?

**Comment by Chaos-emerald** [comment]
> is there a bug or do you want a new feature?

A new easter egg addon that replicates an old Scratch bug.

**Comment by Chaos-emerald** [comment]
Bump again

**Comment by RedGuy12** [comment]
why? that would make scratch extremely hard to use...
