### ISSUE TITLE
ScratchAddons in Offline Editor

### ISSUE THREAD

**Issue by xItzDiamondx** [ScratchAddons/ScratchAddons#2226]
**Is your feature request related to a problem? Please describe.**
No, I don't think it is.

I'm on my PC and on my desktop, I notice Scratch Offline Editor lurking. The question is, can y'all make a PWA of ScratchAddons or just a safe .exe file?
**Describe the solution you'd like**
Specified above.

I would like you all to make a PWA of ScratchAddons or a PWA for PC and Mac if possible. Thanks.
**Describe alternatives you've considered**
I mean, I could download Turbowarp Desktop...

**Additional context**
None

**Comment by RedGuy12** [comment]
Rejected. Just use TW desktop.
