### ISSUE TITLE
New addon: confirm project share

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#223]
I removed that feature from Developer Tools because it's too unrelated to the purpose of the extension. Instead, it should be a separate addon.

**Comment by Hans5958** [comment]
Don't we should seperate Developer Tools even more because it is a collection of tools and not just a single tool?

**Comment by WorldLanguages** [comment]
It would be nice but the code is pretty spaghet so its easier said than done :p

**Comment by JeffaloBob** [comment]
maybe griffpatch's devtools could further be taken apart?

**Comment by Hans5958** [comment]
you're reiterating what i said

**Comment by JeffaloBob** [comment]
> > maybe griffpatch's devtools could further be taken apart?
> 
> you're reiterating what i said
> 
> > It would be nice but the code is pretty spaghet so its easier said than done :p

oh.

i guess i can't read™️
