### ISSUE TITLE
Rewrite a11y addon to put everything inside `export default`

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#2231]
Current impl messes up typing analyzers. Functions can be placed outside if it uses dependency-injection style instead of weirdly scoped variables.

**Comment by WorldLanguages** [comment]
Can we just remove the addon instead? :P

**Comment by silvxrcat** [comment]
yup another secret addon I must find

or am i just dumb and a11y stands for somethin

**Comment by CubeyTheCube** [comment]
> yup another secret addon I must find
> 
> or am i just dumb and a11y stands for somethin

a11y stands for accessibility
pretty sure it's not secret ~~but its not the best addon in the world~~

**Comment by RedGuy12** [comment]
project screen reader support
________________________________
