### ISSUE TITLE
Profile Widgets

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#2236]
**Profile Widgets**

It would be extraordinary if we could add widgets to our profiles to make them look unique! For example when people view our profile we should have icons showing how many followers, views and loves this user has! This way we don't need to keep updating banners since the widgets will auto update!

**Comment by RedGuy12** [comment]
like add a separate section to your profile that only scratch addons users can see? might be rejected, but if it's not it needs a server

also, if you just want to put stats in that section, there's already an addon that shows profile statistics

**Comment by CubeyTheCube** [comment]
> like add a separate section to your profile that only scratch addons users can see? might be rejected, but if it's not it needs a server
> 
> also, if you just want to put stats in that section, there's already an addon that shows profile statistics
> 
> and don't self emoji please

I think they want a way to basically embed some sort of webpage on your profile... like if I wanted I can add a "widget" that interactively shows information about me and tells you how many covid cases there are in tuvalu

**Comment by Mast3rGenius** [comment]
Seems kinda pointless.

**Comment by GrahamSH-LLK** [comment]
This would be a cool feature with Ocular maybe. @jeffalo Wanna support this?

**Comment by devxan** [comment]
Anyone want to make something like this but for scratch? https://www.producthunt.com/posts/twitter-real-time-banner

![image](https://user-images.githubusercontent.com/57809064/131391639-c95e1ae9-f472-4cc2-b629-49f5456f20e6.png)

**Comment by lisa-wolfgang** [comment]
This issue will probably be closed, as such a service does not exist yet, and creating such a service is outside the scope of Scratch Addons.

If a service is created that would allow Scratch Addons to add this, we may reopen the issue.
