### ISSUE TITLE
Could we use repl.it to host the Database?

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#2237]
**Repl.it Databases are free**

I have been using repl.it recently its like github but its more like vs code and it has a free database storage unit. Possibly we could transfer the API there unless it's too small...

**Comment by RedGuy12** [comment]
we dont have a database?

**Comment by TheColaber** [comment]
If you are talking about possible addons needing an API, sure, we could use replit or glitch or something. But right now, we aren't convinced having a server is a good thing right now. That's why this is closed. Specific addons can have issues made for them if not already.
