### ISSUE TITLE
Forum messager

### ISSUE THREAD

**Issue by ErrorGamer2000** [ScratchAddons/ScratchAddons#2238]
Pretty much the same as the normal messaging popup, but works with the forums. I may try to build it.

**Comment by mxmou** [comment]
The messaging popup already supports forum messages.

**Comment by WorldLanguages** [comment]
@mxmou You can't reply inline with scratch messaging. Replying forums inline doesn't sound like a good idea tho

**Comment by mxmou** [comment]
@WorldLanguages I agree: the popup is too small for that, especially because in some active topics a notifications often means multiple new pages of posts.

**Comment by WorldLanguages** [comment]
Rejected, then
