### ISSUE TITLE
[editor-darkmode]: Page Background should not affect the stage monitor

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#2239]
**Describe the bug**

PAGE BACKGROUND, INPUT BACKGROUND, and ACCENT BACKGROUND are affecting variables, lists, and ask inputs in the stage which is should not happen. One reason is that it does not fit the project's scheme of things.

**Expected behavior**

Either other settings or just not be affected at all.

**Additional context**

One person also mentioned to me that "SPRITE LIST BACKGROUND" sounded like it was going to change the background of the lists on the stage. I think it might need to be renamed a bit for clarity.

**Comment by mxmou** [comment]
Ask inputs were always affected by all dark mode versions, but if that's a problem it could be removed.

Could sprite list background be called sprite pane background?
