### ISSUE TITLE
Use consistent names for parts of Scratch

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2243]
**Is your feature request related to a problem? Please describe.**

Different parts of Scratch are named inconsistently in different addon descriptions (the version I think is the best is in italic):

**Editor:**
* *editor* (data category tweaks, devtools, thumbnails setter, record project video, variable manager, clone counter, display stage on left side, messages in editor), project editor (editor dark mode), Scratch editor (searchable dropdowns, fix broken SVG uploads)
* *to the right of the Code, Costumes and Sound tabs* (devtools help popup), next to "sounds" (variable manager)
* next to the flag (mouse position): should probably be *above the stage*; should also be added to the description of the clone counter
* next to the green flag (pause button): should probably be *next to the green flag and stop sign*
* *sprites pane* (drag and drop files), sprite pane (editor dark mode after #2241), sprite list (editor dark mode before #2241, sprite folders)
* *costume/sound list* (drag and drop files, sprite folders), list of costumes (devtools help popup), asset list (editor dark mode)
* *block category menu* (editor dark mode), block category list (auto-show editor extensions)
* workspace (devtools help popup, editor dark mode), script window (devtools help popup), scripts window (devtools help popup), scripts area (custom scripts area zoom settings), editor workspace (save blocks as image): I think *scripts workspace* should be used
* tidy up (devtools), *clean up* (Scratch)
* dropdown (searchable dropdowns): should probably be *block dropdown*
* editor context menu when right-clicking a block (colored context menus): should probably be *block context menu*

**Website:**
* *2.0-styled pages* (2.0 → 3.0), 2.0 and 3.0 pages (website dark mode): "3.0 pages" are unrelated to Scratch 3.0, they just look similar to it, which means that "3.0-styled pages" is a better name.
* profile page (profile page banner, profile statistics, live featured project), *profile* (Scratch, feature unshared projects, longer WIWO, search profile)
* navbar (discuss button): should probably be *navigation bar*
* the curator of the front page (curator link): should probably be *front page curator*
* the forum homepage (forum search): misleading because it actually works on all forum pages - should probably be *the forums*
* into the forums (image uploader): should it be *onto the forums*?
* post (show BBCode, forums time zone), *forum post* (better quoter)

**Describe the solution you'd like**

Use the same vocabulary everywhere.

**Comment by apple502j** [comment]
Listing IMO below

>     * _editor_ (data category tweaks, devtools, thumbnails setter, record project video, variable manager, clone counter, display stage on left side, messages in editor), project editor (editor dark mode), Scratch editor (searchable dropdowns, fix broken SVG uploads)

editor.
>     * _to the right of the Code, Costumes and Sound tabs_ (devtools help popup), next to "sounds" (variable manager)

Sounds tab for UI, sound tab only for referencing sound-tab.jsx
>     * next to the flag (mouse position): should probably be _above the stage_; should also be added to the description of the clone counter

above the stage.
>     * next to the green flag (pause button): should probably be _next to the green flag and stop sign_

next to the stop sign seems fine.
>     * _sprites pane_ (drag and drop files), sprite pane (editor dark mode after #2241), sprite list (editor dark mode before #2241, sprite folders)

This is a hard one. "sprite pane" iirc is the common name, technically the correct name is "sprite selector" for sprite-only and "target pane" for sprite + stage but that's only relevant for modders like garbo
>     * _costume/sound list_ (drag and drop files, sprite folders), list of costumes (devtools help popup), asset list (editor dark mode)

costume pane. (technically asset panel but who cares)
>     * _block category menu_ (editor dark mode), block category list (auto-show editor extensions)

block category menu
>     * workspace (devtools help popup, editor dark mode), script window (devtools help popup), scripts window (devtools help popup), scripts area (custom scripts area zoom settings), editor workspace (save blocks as image): I think _scripts workspace_ should be used

"code area" for post-3.0, "scripts area" for 2.0 and below, "workspace" only for Blockly coder
>     * tidy up (devtools), _clean up_ (Scratch)

clean up, ofc
>     * dropdown (searchable dropdowns): should probably be _block dropdown_

block dropdown seems fine
>     * editor context menu when right-clicking a block (colored context menus): should probably be _block context menu_

"block context menu". we should also remove "right click/left click" entirely.
>     * _2.0-styled pages_ (2.0 → 3.0), 2.0 and 3.0 pages (website dark mode): "3.0 pages" are unrelated to Scratch 3.0, they just look similar to it, which means that "3.0-styled pages" is a better name.

"X-styled pages", but we can use "scratchr2 pages" and "scratch-www pages" for internal stuff
>     * profile page (profile page banner, profile statistics, live featured project), _profile_ (Scratch, feature unshared projects, longer WIWO, search profile)

profile page for banner, lfp, fup, longer-wiwo. profile/user for search-profile. user for scratchstats.
>     * navbar (discuss button): should probably be _navigation bar_

navigation bar.
>     * the curator of the front page (curator link): should probably be _front page curator_

front page curator
>     * the forum homepage (forum search): misleading because it actually works on all forum pages - should probably be _the forums_

the forums. (homepage is used for what is called "splash page" aka `/`)
>     * into the forums (image uploader): should it be _onto the forums_?

on or onto
>     * post (show BBCode, forums time zone), _forum post_ (better quoter)

post is fine when forum is implied, forum post otherwise

also, "master" -> "main"?

**Comment by mxmou** [comment]
> > ```
> > * _sprites pane_ (drag and drop files), sprite pane (editor dark mode after #2241), sprite list (editor dark mode before #2241, sprite folders)
> > ```
> 
> This is a hard one. "sprite pane" iirc is the common name, technically the correct name is "sprite selector" for sprite-only and "target pane" for sprite + stage but that's only relevant for modders like garbo

I'd use sprite selector but then most people wouldn't understand it. The Scratch Wiki uses "sprite pane" so that's probably the most commonly used name.

> > ```
> > * _costume/sound list_ (drag and drop files, sprite folders), list of costumes (devtools help popup), asset list (editor dark mode)
> > ```
> 
> costume pane. (technically asset panel but who cares)

Currently every addon that mentions it calls it "list", not "pane".

**Comment by Hans5958** [comment]
Probably also related to #1880 because god dang why it is inconsistent

Keep in `master`. (a) this is what we have since the inception, (b) removing master branch would require changes to 20 pending PRs, and (c) we have no time for arguing like how the Git contributor does.

**Comment by apple502j** [comment]
Information above is very outdated; none of those are actually problematic. It's as simple as pressing a button.

**Comment by Hans5958** [comment]
> very outdated

Explain why. (ignore (b). I didn't know it was made easier)

> not problematic

Uh, if you think that it is still an issue, sure, that's subjective. Otherwise, you are pretty ignorant.

> simple as pressing a button

Actually, it's two buttons and filling a text form, but still. 

Remaming, archiving, and deleting the repository is also "simple," but all of these things require risk assessment. We're a well-sized project, everything should be considered well before something is done.

**Comment by WorldLanguages** [comment]
There's also :D
![image](https://user-images.githubusercontent.com/17484114/121597379-07de4d80-ca17-11eb-935d-1cd25ab4e1fa.png)

**Comment by mxmou** [comment]
> > * profile page (profile page banner, profile statistics, live featured project), _profile_ (Scratch, feature unshared projects, longer WIWO, search profile)
> 
> profile page for banner, lfp, fup, longer-wiwo. profile/user for search-profile. user for scratchstats.

Scratch uses the word "profile" in the account menu, not "profile page". The description of the scratchstats addon talks about profile pages, not users.

**Comment by Hans5958** [comment]
Not sure why I got the "related to #1880" hidden. We need to consider that also.
