### ISSUE TITLE
[editor-darkmode]: TW preset

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#2246]
<details>
<summary>Btw, this is the turbowarp settings, which I've had requests for...</summary>
<pre>
"accent": "#111111ff",
"activeTab": "#1e1e1eff",
"border": "#00000026",
"categoryMenu": "#111111ff",
"darkComments": false,
"darkScrollbars": false,
"dots": true,
"fullscreen": "#111111ff",
"input": "#1e1e1e",
"menuBar": "#333333ff",
"page": "#111111ff",
"palette": "#111111cc",
"primary": "#ff4d4dff",
"selectedMode": "3-darker",
"selector": "#1e1e1eff",
"selector2": "#2e2e2eff",
"selectorSelection": "#111111ff",
"stageHeader": "#111111ff",
"tab": "#2e2e2eff",
"textShadow": false,
"workspace": "#1e1e1eff"
</pre>
</details>

_Originally posted by @TheColaber in https://github.com/ScratchAddons/ScratchAddons/issues/1805#issuecomment-815418391_

**Comment by mxmou** [comment]
Now that input background doesn't affect blocks, `input` should be `#1e1e1e`.

**Comment by Samq64** [comment]
I'm planning on making a PR for this. Should the accent colour stay blue or should I make it red like TurboWarp?
