### ISSUE TITLE
Cloud games customizable

### ISSUE THREAD

**Issue by Miala-python** [ScratchAddons/ScratchAddons#2247]
**Is your feature request related to a problem? Please describe.**

>We can't look the people of an other game of our choice.

**Describe the solution you'd like**

>Make a button "Add game".

![image](https://user-images.githubusercontent.com/65893041/115570080-1ed9ac80-a2be-11eb-9ad9-17e926c0ec95.png)

(Sorry, I do not speak english very well.)

**Comment by TheColaber** [comment]
Duplicate of #1652
