### ISSUE TITLE
Scratch Messaging addon: enhancements

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#225]
- Better comment posting flow
- "Click to confirm deletion" sometimes overflows comment top bar
- Newly posted comments say "in 61 seconds"
- Open comment in a new tab button: placement is weird (next to the central dot symbol)
Might think of more as time goes on

**Comment by BoomerScratch** [comment]
> * Newly posted comments say "in 61 seconds"

[This is a Scratch bug](/LLK/scratch-www/issues/4338). I commented a fix (as you can see), but nothing really happened after.

**Comment by WorldLanguages** [comment]
@BoomerScratch Actually it's a bug I introduced while changing something, trying to fix another bug-ish. I saw it say "now" before this change, which is what I'd expect.
