### ISSUE TITLE
convert dark-www to presets

### ISSUE THREAD

**Issue by FunctionalMetatable** [ScratchAddons/ScratchAddons#2252]
**Is your feature request related to a problem? Please describe.**

As `editor-dark-mode` has now converted to presets, wouldn't it be better if that this addon was presets as well?

**Describe the solution you'd like**

convert dark-www to presets

**Describe alternatives you've considered**

`null`

**Comment by TheColaber** [comment]
Related: #645 (but not dupe?)

**Comment by mxmou** [comment]
#645 is very similar to this. Closing as duplicate.

**Comment by TheColaber** [comment]
Duplicate of #645
