### ISSUE TITLE
Dark Mode Customizations

### ISSUE THREAD

**Issue by JellyScript** [ScratchAddons/ScratchAddons#2262]
Different styles of dark mode. Like, convert all words to a certain color. I just know there are different types of dark modes, and it would be cool if Scratch (Addons) had some.

**Comment by WorldLanguages** [comment]
> convert all words to a certain color

Can you elaborate?

**Comment by JellyScript** [comment]
Of course. Actually, I have this one extension that allows different themes
for dark mode. I was wondering if Scratch Addons can have that feature. The
reason I ask is because when I use the extension, it messes up the vector
and bitmap editor. What I mean is can we have custom versions of dark mode?

**Comment by RedGuy12** [comment]
It shouldn’t mess up the paint editor…that’s a big bug



Also, we have custom dark mode for the project editor, same for the website is coming soon.

**Comment by JellyScript** [comment]
> It shouldn’t mess up the paint editor…that’s a big bug Also, we have custom dark mode for the project editor, same for the website is coming soon.

Yeah, it's a different extension. Uh... thanks.

**Comment by RedGuy12** [comment]
So what do you want? Custom dark mode?
> we have custom dark mode for the project editor, same for the website is coming soon.

**Comment by JellyScript** [comment]
> So what do you want? Custom dark mode?
> 
> > we have custom dark mode for the project editor, same for the website is coming soon.

Yeah, if you can. I mean custom dark mode for both. Thank you!

**Comment by RedGuy12** [comment]
Duplicate of #645
