### ISSUE TITLE
Convert All Costumes To Vector

### ISSUE THREAD

**Issue by JellyScript** [ScratchAddons/ScratchAddons#2266]
Maybe add a button to convert all costumes to vector or bitmap?

**Comment by apple502j** [comment]
Converting costumes to vector is useless, fyi. It's still a bitmap disguised as a vector.

**Comment by WorldLanguages** [comment]
@JellyScript Can you clarify what you mean? Is the point of this to avoid clicks, or to get better quality by "vectorizing" bitmaps?

**Comment by JellyScript** [comment]
@WorldLanguages It's pretty hard to explain. So, one time I was replacing all the faces in a gif with the Scratch Cat, but I messed up on one and couldn't edit it again. (I had already switched to a different costume) And I realize that Bitmap is just Vector but you can't edit anything once you place something. And yes, the quality is a little better in Vector.
