### ISSUE TITLE
Variations of the dark theme

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#227]
There are multiple variations for the dark theme, so why only use one?

**Comment by WorldLanguages** [comment]
Can you elaborate? I don't understand what you mean.

**Comment by Hans5958** [comment]
I believe there are multiple versions/variations of the dark theme of Scratch that is made by various people, such as:

https://github.com/infinitytec/3.Dark
https://github.com/infinitytec/3.Darker
https://chrome.google.com/webstore/detail/better30/gjoimmimmkpppgkhobhceblafkienddi?hl=en

Is there any way to also include these variations and not just conform into a single one?

**Comment by WorldLanguages** [comment]
Sure it is! I just ported one to test how to order `addons.json` to make it work.
However we kinda have the problem described here: #220, it doesn't make sense to let users enable two or more dark modes at once, that's not expected to work.

**Comment by WorldLanguages** [comment]
I suggest merging all dark modes into a single addon.
Then, with a "select" type option (not yet implemented), the user can decide what theme to use (and we should democratically decide a default one lol).
Then, with conditional userstyle loading (not yet implemented), we can declare in the manifest some userstyles should only be injected if a certain addon setting is set to a value.
This addon should have a global css file that is injected no matter the selected style, that is responsible for making other addon UIs dark.
So yeah, this is blocked by two other features but we should get into them soon.
