### ISSUE TITLE
Zooming out zooms in.

### ISSUE THREAD

**Issue by 22yeetz22** [ScratchAddons/ScratchAddons#2270]
**Describe the bug**

When you click the zoom-in button, it zooms out.

**To Reproduce**

1. Enable custom scripts zoom settings thing.
2. Go on a project.
3. Click the zoom-in button.
4. It zooms out and vise versa with the zoom out button.
5. Also, for the ctrl + scroll it zooms out when it's supposed to zoom in.

**Expected behavior**

IT TO ZOOM IN.

**Screenshots**

A video.

https://user-images.githubusercontent.com/74276537/115966388-fab2e100-a4f2-11eb-8535-2889b676604f.mp4

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome
- Version: 90.0.4430.85 (Official Build) (64-bit)

**Additional context**

**Comment by WorldLanguages** [comment]
huh, epic bug tbh

**Comment by TheColaber** [comment]
Cannot repro with repro steps. Can anyone repro?

**Comment by WorldLanguages** [comment]
@22yeetz22 Could you post a screen recording of the issue? I find it unlikely we'll find the root cause otherwise

**Comment by 22yeetz22** [comment]
> @22yeetz22 Could you post a screen recording of the issue? I find it unlikely we'll find the root cause otherwise

Ok I did it

**Comment by TheColaber** [comment]
... could you send it?

**Comment by 22yeetz22** [comment]
> ... could you send it?

what do you mean?

**Comment by RedGuy12** [comment]
> > ... could you send it?
> 
> what do you mean?

send the video

**Comment by Endermaster3690** [comment]
> > > ... could you send it?
> > 
> > 
> > what do you mean?
> 
> send the video

it's on the opening post thingy.

**Comment by mxmou** [comment]
This happens if the zoom speed is 83% or less. When zooming in, the zoom is probably multiplied by speed/120 instead of 1 + speed/20.

**Comment by WorldLanguages** [comment]
> This happens if the zoom speed is 83% or less. When zooming in, the zoom is probably multiplied by speed/120 instead of 1 + speed/20.

@mxmou Could you try to find the line of code that causes the issue?

**Comment by mxmou** [comment]
@WorldLanguages `addons/custom-zoom/userscript.js`, line 22. The formula should be `1 + 0.2 * (addon.settings.get("zoomSpeed") / 100)`, not `1.2 * (addon.settings.get("zoomSpeed") / 100)`.
