### ISSUE TITLE
Remove curved stage borders

### ISSUE THREAD

**Issue by Tacodude7729** [ScratchAddons/ScratchAddons#2277]
Right now in Scratch, you can't see the very corners of the stage because of a beveled border. It can be useful to be able to see these areas of the stage. This plugin would remove the curved border of the stage, allowing you to see the whole stage.

I have made this plugin to do this so I could use it myself but don't know if this deserves it's own plugin or not, so I haven't created a pull request.
https://github.com/Tacodude7729/ScratchAddons/tree/master/addons/remove-curved-stage-border

Before
![image](https://user-images.githubusercontent.com/27910867/115946028-e4605180-a501-11eb-8b49-f9a7dee3ffdd.png)

After
![image](https://user-images.githubusercontent.com/27910867/115946009-d4487200-a501-11eb-823c-94b2ae360ce8.png)

**Comment by mxmou** [comment]
I think this could be a useful addon. It would probably look better if it also removed rounded corners from the elements below the stage.

**Comment by Tacodude7729** [comment]
@mxmou While it could look better there is a LOT of round edges in the scratch editor and just scratch in general. Removing them all would take a bit of work and I think it is beyond the scope of this issue.

**Comment by Secret-chest** [comment]
@Tacodude7729 You use Linux!
