### ISSUE TITLE
Use camelState instead of snake_case for the addon.json metadata/manifest keys

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#228]
The project is using JavaScript, which commonly uses camelCase, so why the snake_case?

**Comment by WorldLanguages** [comment]
Not sure. Probably because extension manifests are also javascript and also use this pattern. Too late to change it now lol

**Comment by Hans5958** [comment]
I think the manifests are using underscore because the W3C about general things, not JavaScript. Most JavaScript/Node.js applications (ESLint, Prettier, etc) use camelCase instead of snake_case.

About things being too late, I don't think it is considering this is not released yet.

**Comment by mxmou** [comment]
> Not sure. Probably because extension manifests are also javascript and also use this pattern. Too late to change it now lol

Currently we have `enabled_by_default` and `runAtComplete`. I don't think it's too late to rename one of them.

**Comment by WorldLanguages** [comment]
Sorry, closing :P
