### ISSUE TITLE
Addon Groups (minimizable)

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#2281]
Already actively being worked on in #2260

I'll send a picture soon.

**Comment by Hans5958** [comment]
Is there a possibility to turn off these categorizations?

Also, I will send a mockup for alternative designs to consider tommorow.

**Comment by mxmou** [comment]
Could a name other than "categories" be used? Currently items of the category menu on the left are called categories.

**Comment by mxmou** [comment]
And I don't think the categories should be shown in the popup. It should only show enabled addons anyway.

**Comment by Hans5958** [comment]
Alright, here are some alternatives of my design, along with the representation of the current status as I see on Discord. I propose to (a) remove the word "addon" because it is redundant (The list consist of addons and no more) and WL wanted to avoid the usage of the word "addon," and (b) have a line so it looks cool.

The images are listed below. For me, I prefer number 2.

![Slide1](https://user-images.githubusercontent.com/11584103/115989283-d7b62900-a5e7-11eb-9d1c-f7780c7f20c7.PNG)
![Slide2](https://user-images.githubusercontent.com/11584103/115989286-da188300-a5e7-11eb-9bfa-01584f43c93f.PNG)
![Slide3](https://user-images.githubusercontent.com/11584103/115989287-dab11980-a5e7-11eb-8c41-1b16cbe2be33.PNG)

**Comment by mxmou** [comment]
@Hans5958 I think the margin above the header should be larger than below.

**Comment by Hans5958** [comment]
> 
> 
> @Hans5958 I think the margin above the header should be larger than below.

Well, sure, but this is just a demo using PowerPoint and some guesswork. The examples may not be accurate with what he has currently.

**Comment by mxmou** [comment]
> The examples may not be accurate with what he has currently.

I don't think the design has been worked on yet.

**Comment by RedGuy12** [comment]
> Could a name other than "categories" be used? Currently items of the category menu on the left are called categories.

Those are going to be merged with the tags iirc.



> For me, I prefer number 2.

I agree

**Comment by mxmou** [comment]
> > Could a name other than "categories" be used? Currently items of the category menu on the left are called categories.
> 
> Those are going to be merged with the tags iirc.

How? They have a completely different purpose than the recommended and beta tags.

**Comment by RedGuy12** [comment]
> > > Could a name other than "categories" be used? Currently items of the category menu on the left are called categories.
> > 
> > 
> > Those are going to be merged with the tags iirc.
> 
> How? They have a completely different purpose than the recommended and beta tags.

They both are used for filtering.

**Comment by mxmou** [comment]
> They both are used for filtering.

Categories define which part of Scratch an addon is for; "recommended" and "beta" define the status of an addon. I don't think using the same UI to filter by both is a good idea.

**Comment by Hans5958** [comment]
> 
> 
> > The examples may not be accurate with what he has currently.
> 
> I don't think the design has been worked on yet.

The fact is that this is something that was only discussed on Discord, and then will be implemented on GitHub after it is completed. In fact this issue is made from a request that I made to @TheColaber and @WorldLanguages. 

It's pretty often, and it's something that I oppose. Classic SA's Discord people. 

Here's a stream of screenshots that sorted chronologically, without context because I didn't read it in detail.

![](https://media.discordapp.net/attachments/755131743136383107/834856208858349638/unknown.png)
![](https://media.discordapp.net/attachments/755131743136383107/834860793971081296/unknown.png)
![](https://media.discordapp.net/attachments/755131743136383107/834864383834194030/unknown.png)
![](https://media.discordapp.net/attachments/755131743136383107/835138006356328489/unknown.png)

> 
> 
> > > > Could a name other than "categories" be used? Currently items of the category menu on the left are called categories.
> > > 
> > > 
> > > Those are going to be merged with the tags iirc.
> > 
> > 
> > How? They have a completely different purpose than the recommended and beta tags.
> 
> They both are used for filtering.

I think it's either we missed something, because I don't often see Discord and @mxmou don't use Discord, or you missed something.

**Comment by WorldLanguages** [comment]
> The images are listed below. For me, I prefer number 2.

Agreed

**Comment by Hans5958** [comment]
@TheColaber You said there will be pics. Where is it?

**Comment by Secret-chest** [comment]
> Alright, here are some alternatives of my design, along with the representation of the current status as I see on Discord. I propose to (a) remove the word "addon" because it is redundant (The list consist of addons and no more) and WL wanted to avoid the usage of the word "addon," and (b) **have a line so it looks cool.**
> 
> The images are listed below. For me, I prefer number 2.
> 
> EDIT: I need to address two things.
> 
> 1. I see that in the current state, it uses `<details>`. It might work, but keep in mind for that.
> 2. I thought it uses arrows. Turns out it uses triangles currently. Whoops. That will be another suggestion from me.
> 3. I thought it is "New Addons" without an exclamation mark. Turns out it is "New Addons!" Whoops.
>    I prefer to remove the exclamation mark, but if we really need that, replace it with "New :sparkles:" or just "New!"
> 
> :scissors:
> 
The lines should be darker, transparent, thinner or inexistent, because they look horrible

**Comment by Secret-chest** [comment]
And please remove the exclamation mark and replace it with New :sparkles:. And change the font to Roboto or something (Montserrat is too wide) because Sora does NOT have Romanian diacritics!

**Comment by Secret-chest** [comment]
And please remove the exclamation mark and replace it with New :sparkles:. And change the font to Roboto or something (Montserrat is too wide) because Sora does NOT have Romanian diacritics!

**Comment by TheColaber** [comment]
@Hans5958 I am in the process of adding css but it looks like this
![image](https://user-images.githubusercontent.com/72760579/116078807-0de5be00-a665-11eb-93fd-dc0dbab78ff7.png)
UI ideas needed

**Comment by mxmou** [comment]
> UI ideas needed

https://github.com/ScratchAddons/ScratchAddons/issues/2281#issuecomment-826296125

**Comment by TheColaber** [comment]
Updates...
![image](https://user-images.githubusercontent.com/72760579/116084694-0aa20080-a66c-11eb-8361-b61475582c91.png)

**Comment by TheColaber** [comment]
Any suggestions?
![image](https://user-images.githubusercontent.com/72760579/116085307-b0ee0600-a66c-11eb-90b4-4919db8a15fd.png)

**Comment by mxmou** [comment]
> Updates...
> ![image](https://user-images.githubusercontent.com/72760579/116084694-0aa20080-a66c-11eb-8361-b61475582c91.png)

Maybe the line could be transparent (https://github.com/ScratchAddons/ScratchAddons/issues/2281#issuecomment-826533345)?

I think the expand icon should be the same size as those of individual addons, and aligned with them.

**Comment by TheColaber** [comment]
@mxmou did you mean something like this?
![image](https://user-images.githubusercontent.com/72760579/116085893-47222c00-a66d-11eb-8700-5222a70418ee.png)

**Comment by mxmou** [comment]
@TheColaber I think this looks good, although I would add more spacing between the expand icon and the category name.

**Comment by TheColaber** [comment]
TODOs by wl: (some i need clarification on)
- [ ] decide how to order each group
- [ ] handle search with groups
- [ ] handle hidden addons with groups (when searching or filtering)
- [ ] what do we do with filter by tag?
- [x] css
- [ ] not sure why everything has "for website" or "for editor" visible tag
- [ ] handle small settings page in popup
- [x] bug: cannot close color pickers
- [ ] different categories in iframe mode
- [ ] disabled easter egg addons
- [ ] "hidden" tag (same group as beta)
- [ ] expanded should be a prop, not an addon prop

**Comment by TheColaber** [comment]
Latest Commit
![image](https://user-images.githubusercontent.com/72760579/116091106-87d07400-a672-11eb-8c8d-58fe3d4cf70f.png)

**Comment by mxmou** [comment]
> not sure why everything has "for website" or "for editor" visible tag

Related to #2218 - those were only intended to be shown in the Themes category.

**Comment by mxmou** [comment]
> what do we do with filter by tag?

If this means the the "filter by" bar at the top, I think it could be removed because it's now possible to do something very similar by expanding and collapsing categories.

The ability to filter between editor themes and website themes when in the themes category could be moved to the category menu.

**Comment by TheColaber** [comment]
> If this means the the "filter by" bar at the top, I think it could be removed because it's now possible to do something very similar by expanding and collapsing categories.
>
> The ability to filter between editor themes and website themes when in the themes category could be moved to the category menu.

W_L also mentioned that we will be adding more tags like "project player" and "userprofiles", "studios", "costumeeditor", etc.
Some of these will be added by just looking at the match URL which brings up #23

**Comment by mxmou** [comment]
> W_L also mentioned that we will be adding more tags like "project player" and "userprofiles", "studios", "costumeeditor", etc.
> Some of these will be added by just looking at the match URL which brings up #23

Please read my explanation in https://github.com/ScratchAddons/ScratchAddons/pull/2257#issuecomment-824940698 for why this is a bad idea. Addons should define these tags manually and I think they should just be added to the category menu as "subcategories" of existing categories. This would mean that addons can be in multiple categories and that even some categories might be repeated (project player in both editor and website features, editor themes in both editor and themes). If we don't want to repeat categories, an alternative is making project player addons a new category, separate from editor and website.

**Comment by TheColaber** [comment]
>  Addons should define these tags manually and I think they should just be added to the category menu as "subcategories" of existing categories.

That is the plan?

**Comment by Hans5958** [comment]
> >  Addons should define these tags manually and I think they should just be added to the category menu as "subcategories" of existing categories.
> 
> That is the plan?

No. Your plan is to also use them as tags. He disagreed per this statement.

> Addons should define these tags manually...

**Comment by mxmou** [comment]
> > I think the expand icon should be the same size as those of individual addons, and aligned with them.
> 
> I disagree. The end of the line is aligned with the end of the box, so the start of the triangle should be aligned with the start of the box.

Currently the end of the line is not aligned with anything. Comparison:
![image](https://user-images.githubusercontent.com/51849865/116104565-d7359500-a6b0-11eb-8c13-8b22a64fc6f9.png)
![image](https://user-images.githubusercontent.com/51849865/116104572-d8ff5880-a6b0-11eb-8970-29a899545242.png)

I think both look good, although I prefer the top (current) one.

**Comment by Hans5958** [comment]
Read the last edit. I prefer the bottom since it covers the length of whole box, the top one looks awkward.

**Comment by Hans5958** [comment]
> Is there a possibility to turn off these categorizations?

**Comment by RedGuy12** [comment]
Closed groups have the triangle pointing up. Closed addons have the triangle pointing down.
________________________________

**Comment by TheColaber** [comment]
![](https://user-images.githubusercontent.com/51849865/116104565-d7359500-a6b0-11eb-8c13-8b22a64fc6f9.png)
No?

**Comment by RedGuy12** [comment]
Nvm, I was looking at an old screenshot

**Comment by Hans5958** [comment]
> 
> 
> ![](https://user-images.githubusercontent.com/51849865/116104565-d7359500-a6b0-11eb-8c13-8b22a64fc6f9.png)
> No?

No. See https://github.com/ScratchAddons/ScratchAddons/issues/2281#issuecomment-826906455. I prefer the second one. The only problem with these is the first one, which I prefer the end to be aligned with something, like the toggle. I still prefer the second one though.

**Comment by Hans5958** [comment]
@TheColaber

**Comment by TheColaber** [comment]
@Hans5958 I'm still rooting for the first due to how everything is aligned.

**Comment by mxmou** [comment]
Now it looks like this:
![image](https://user-images.githubusercontent.com/51849865/116235636-664cb680-a75e-11eb-90f1-a01bca2aa855.png)

I think the shadow is too subtle. The previous design was probably better.

**Comment by Hans5958** [comment]
> 
> 
> @Hans5958 I'm still rooting for the first due to how everything is aligned.

I prefer if we can make it distant instead of making it similar.

> 
> 
> Now it looks like this:
> ![image](https://user-images.githubusercontent.com/51849865/116235636-664cb680-a75e-11eb-90f1-a01bca2aa855.png)
> 
> I think the shadow is too subtle. The previous design was probably better.

Well, I almost can't see it. I prefer the lines.

@GrahamSH-LLK because goddang I believe he didn't know this issue existed

**Comment by Hans5958** [comment]
Here's a comparison on the website.

Here's the current one. This is good.

![image](https://user-images.githubusercontent.com/11584103/116248388-08d45c00-a796-11eb-8992-4f1f8e4a3dbe.png)

Here's with additional padding. This is not. 

![image](https://user-images.githubusercontent.com/11584103/116248318-f78b4f80-a795-11eb-9745-0a454b5d844b.png)

**Comment by mxmou** [comment]
@Hans5958 That's true, but this still looks a bit weird to me:
![group_design_1](https://user-images.githubusercontent.com/51849865/116249409-16c1b700-a76d-11eb-9433-da4c1b0b38e7.png)

On the website this isn't a problem because individual items don't have "List view" and "Easter egg" checkboxes - if they did, it would make sense to align them with those in the header.

**Comment by Hans5958** [comment]
> @Hans5958 That's true, but this still looks a bit weird to me:
> ![group_design_1](https://user-images.githubusercontent.com/51849865/116249409-16c1b700-a76d-11eb-9433-da4c1b0b38e7.png)
 
I would prefer if we can do `margin-left: -1rem` or something like that.

> On the website this isn't a problem because individual items don't have "List view" and "Easter egg" checkboxes - if they did, it would make sense to align them with those in the header.

I don't think that matters. What matters here is that the line should be aligned with the box border, not the content.

**Comment by Hans5958** [comment]
@TheColaber Please we don't need thick top and bottom padding. Why do we have more thick paddings? You guys can't stop flexing your large-ass monitors, while I'm here being stuck at 1024x768! /s

**Comment by WorldLanguages** [comment]
> You guys can't stop flexing your large-ass monitors

Zoom out then!!!

**Comment by Hans5958** [comment]
> 
> 
> > You guys can't stop flexing your large-ass monitors
> 
> Zoom out then!!!

[Tell that to around some percentage of the users](https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide)
