### ISSUE TITLE
multiple  projects in one project

### ISSUE THREAD

**Issue by bemo5** [ScratchAddons/ScratchAddons#2283]
this wuold  allow users to have more than ne project per proect by replacing all when klicked block in  it with when reciving  (proectname){url}{randomcombination}start and it would ad an when recived (the same as start but start is replaced with stop ) stop other scripts in sprite

**Comment by RedGuy12** [comment]
I don't understand. Can you elaborate?

**Comment by bemo5** [comment]
i   mean  the feature would be an addon that would  allow you to load proects eigther via file or url  and then add all the 
sprites (and backdrops) in the  code of the uploadet or selectet proect via the addon   to the  project you're currently 
on and replace when klicked whit when msg(proectname + some random string that  noone  is  going to use anyways )   recived   and would also  add  when stop (the same as bevore) recived  stop other scripts in sprite in all sprites of an proect thats addet    and it would also replace all the  stop all blocks in the project white  send the stop message to the project and for compatibility it may would raname sprites by adding numbers behind theyre names same for  vars and lists

**Comment by FunctionalMetatable** [comment]
so you mean merging projects into one project?

**Comment by mxmou** [comment]
> so you mean merging projects into one project?

I think so.

**Comment by apple502j** [comment]
This is not possible (or, it is possible but is very hard) - esp when it comes to file size limit and shared values.
