### ISSUE TITLE
Disappearing Text Bug as an addon

### ISSUE THREAD

**Issue by Chaos-emerald** [ScratchAddons/ScratchAddons#2299]
**Describe the new addon**

This addon will be challenging by removing block text.

**Link to the new addon**

No link, sorry.

**Comment by Chaos-emerald** [comment]
@GrahamSH-LLK and others, don't review this (you can if you want)

**Comment by RedGuy12** [comment]
You already made an issue for this (#2225) and it was rejected. This would make Scratch extremely hard to use.
