### ISSUE TITLE
More options for userscript matches (not only URLs)

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#23]
Let's say a userscript only works on user profiles. The current match would currently be `https://scratch.mit.edu/users/*/`, why not just `userprofile`? And other potential filters for common use.

**Comment by WorldLanguages** [comment]
I believe it's too late to implement this. It's not a big deal, either. Closing

**Comment by Hans5958** [comment]
> too late

**Comment by TheColaber** [comment]
I believe this one is worth reopening. Once we implement #390, addons that work on the editor/project page would also need to work on turbowarp's editor/project page. If we simply said for the match URL to be `project`, then we could have the match URL patterns for both turbowarp and scratch to link to htpps://scratch.mit.edu/projects/* and https://turbowarp.org/* (excluding the https://turbowarp.org/privacy.html page). And, if we end up supporting addons on another site, then it would be useful there too. This would also help with #646. And I think it's just easier if all the user needed to add in their addon, was just `search` or `user`

**Comment by RedGuy12** [comment]
And phosphorous

**Comment by WorldLanguages** [comment]
> I believe this one is worth reopening. Once we implement #390, addons that work on the editor/project page would also need to work on turbowarp's editor/project page. If we simply said for the match URL to be `project`, then we could have the match URL patterns for both turbowarp and scratch to link to htpps://scratch.mit.edu/projects/* and https://turbowarp.org/* (excluding the https://turbowarp.org/privacy.html page). And, if we end up supporting addons on another site, then it would be useful there too. This would also help with #646. And I think it's just easier if all the user needed to add in their addon, was just `search` or `user`

I honestly doubt userscript made for the Scratch editor could work "as-is" on TurboWarp, so it wouldn't make sense to merge both origins into one permission - an addon might only work on the Scratch editor

**Comment by RedGuy12** [comment]
Well maybe userstyles

Paul Reid

________________________________

**Comment by TheColaber** [comment]
> I honestly doubt userscript made for the Scratch editor could work "as-is" on TurboWarp, so it wouldn't make sense to merge both origins into one permission - an addon might only work on the Scratch editor

I'm sure that most do, and some (like poject-notes-tabs) could easily be fixed by adding an if statement.

**Comment by TheColaber** [comment]
> I honestly doubt userscript made for the Scratch editor could work "as-is" on TurboWarp, so it wouldn't make sense to merge both origins into one permission - an addon might only work on the Scratch editor

How bout now hehe. But even so, this should 100% be implemented... for future mods.

**Comment by TheColaber** [comment]
wl has recondered. pr soon.

**Comment by TheColaber** [comment]
@mxmou 
> One reason is that there are addons that don't set their match to the forums but are closely related to them (discuss button)

In this case, the addon can manually add the tag.
> There are also addons that have forum matches to implement forum-specific functionality but aren't otherwise forum addons (infinite scrolling).

I argue that infinite scrolling and other addons like that *should* have the forums tag, even if their effect on it is very little. Alternatively, we can check if the userscripts/userstyles have the `settingMatch` property. Then it will ignore its matches.
> Another reason is that if we add subcategories, editor addons will need to set them explicitly anyway. Why would website addons work differently?

The editor is not different pages, whereas the forums and the profiles are.

**Comment by mxmou** [comment]
> > One reason is that there are addons that don't set their match to the forums but are closely related to them (discuss button)
> 
> In this case, the addon can manually add the tag.
> 
> > There are also addons that have forum matches to implement forum-specific functionality but aren't otherwise forum addons (infinite scrolling).
> 
> I argue that infinite scrolling and other addons like that _should_ have the forums tag, even if their effect on it is very little. Alternatively, we can check if the userscripts/userstyles have the `settingMatch` property. Then it will ignore its matches.

This would cause similar issues as the theme tag did. I don't think we should add more features that affect both functionality and categorization like that.

The forums tag should be only for addons users want to see when choosing "forums" in a menu. Maybe infinite scrolling should be one of them, but what about website dark mode?

**Comment by mxmou** [comment]
> The editor is not different pages, whereas the forums and the profiles are.

It still doesn't make sense for editor addons to behave differently than website addons in any way.
