### ISSUE TITLE
Refactor directory structure of libraries

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#2302]
TL;DR:

- `/libraries/thirdparty/`, `/libraries/thirdparty/cs/` - no lint
- `/libraries/common/`, `/libraries/common/cs/` - lint
- `cs` includes web-accessible files
- `/libraries/licenses/` remains
- `CREDITS.md` and `license-info.json` are the only files directly under `/libraries/`

**Comment by GrahamSH-LLK** [comment]
Can `CREDITS.md` be renamed to `README.md`? Then GitHub will show it just by navigating to the directory.
