### ISSUE TITLE
[custom block colors] Some blocks change the text colors of other blocks

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#2310]
cc @mxmou

**Describe the bug**
When I add a hat block to a stack of blocks, the text color changes on the whole stack to match the hat block's color. See images.
Stack of blocks with correct coloring: ![image](https://user-images.githubusercontent.com/61329810/116284924-3c41c700-a753-11eb-856c-457874271ebb.png)
Adding a hat block changes all the text colors: ![image](https://user-images.githubusercontent.com/61329810/116285093-698e7500-a753-11eb-9478-2064579a0fc0.png)

All blocks after a pen block in a stack have the pen text color. blocks before the pen block are fine:
![image](https://user-images.githubusercontent.com/61329810/116286532-f128b380-a754-11eb-9fbc-475658045b71.png)

Exeptions:
Blocks inside other blocks are not affected by hat blocks (they are affected by pen blocks): ![image](https://user-images.githubusercontent.com/61329810/116285273-993d7d00-a753-11eb-8495-29331dc23c4f.png)
List blocks, extention blocks, and custom blocks are not affected: ![image](https://user-images.githubusercontent.com/61329810/116285819-1ff25a00-a754-11eb-8340-8ccf2f46241c.png)
Define hat blocks, extention hat blocks, and when backdrop switches to hat blocks do not change the stack's text color: ![image](https://user-images.githubusercontent.com/61329810/116285726-08b36c80-a754-11eb-86ae-179bdfef09a7.png)

**To Reproduce**

This is with the "Customizable block colors" addon enabled. The "Text Color" setting must be set to "colored on white" or "colored on black"

**Expected behavior**

The text color on stacks should be independent of the text color of the hat block.

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Commit/branch: latest on master

**Comment by RedGuy12** [comment]
wait it's with all blocks except motion, operators, event, and custom blocks
![image](https://user-images.githubusercontent.com/61329810/116287259-d0ad2900-a755-11eb-9753-c0e1461bc7b0.png)
![image](https://user-images.githubusercontent.com/61329810/116287304-dc005480-a755-11eb-9fb0-4fd05b96fa66.png)
it doesn't have to be a hat block or a pen block.


Looks blocks affect motion blocks.
Sound blocks affect motion and looks blocks.
Control blocks affect motion, looks, and sound blocks.
Variables blocks affect motion, looks, sound, control, sensing, and operators blocks.
Lists blocks affect motion, looks, sound, control, sensing, operators, and variables blocks.

operator blocks always go inside other blocks, yet they are still affected
Event blocks are affected by control, sensing, operators, variables, lists, and custom blocks, but only the inputs. the rest of the blocks are fine still...
Sensing blocks have the same situation as event blocks. their inputs are affected by operators, variables, lists, and custom blocks
Extention block's inputs (only the inputs) are affected by all blocks.
custom blocks and pen blocks are never affected still.
pen blocks still affect every other block in the stack. other extention blocks dont, only pen blocks.

**Comment by RedGuy12** [comment]
This should be fixed before it reaches stable.

**Comment by mxmou** [comment]
The reason is that blocks are technically descendants of those that precede them in a stack. I didn't notice this while testing because I arranged blocks in the same order as their styles are defined.
