### ISSUE TITLE
Do we really need Codacy?

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#2313]
Codacy is just an ESLint with fancy website. Why not setup pure eslint instead?

**Comment by GrahamSH-LLK** [comment]
You said it yourself, it has a 
> fancy website.
That lets people who don't want to run ESLint see how their PR or code (or just master) is doing.

**Comment by apple502j** [comment]
We can run eslint without fancy website? Just add it to prettier workflow
