### ISSUE TITLE
Ctrl+Space developer tool does not work

### ISSUE THREAD

**Issue by HiImBlahh** [ScratchAddons/ScratchAddons#2321]
when i tried ctrl plus space to add block by name it didn't work.

**Comment by TheColaber** [comment]
Do you have the devtools addon enabled? Otherwise, I wouldn't know why this would not work.

**Comment by HiImBlahh** [comment]
> Do you have the devtools addon enabled? Otherwise, I wouldn't know why this would not work.

Yes, i do

**Comment by Shluffy** [comment]
What is your browser information? Also, I could reproduce.

**Comment by TheColaber** [comment]
@Shluffy or @HiImBlahh, Could you try pressing Ctrl + Space as usual on the workspace and then press Ctrl + Shift + J and then take a screenshot of the popup that shows?

**Comment by Shluffy** [comment]
> @Shluffy or @HiImBlahh, Could you try pressing Ctrl + Space as usual on the workspace and then press Ctrl + Shift + J and then take a screenshot of the popup that shows?

I'm on a chromebook and ctrl shift j doesn't seem to do anything. I can use the middle click to get it though

**Comment by TheColaber** [comment]
Ah no chromebook won't work.

**Comment by Shluffy** [comment]
> Ah no chromebook won't work.

Sorry.

**Comment by Shluffy** [comment]
> Ah no chromebook won't work.

if it is console wouldn't ctrl shift I work on a chromebook (doesn't make a difference, device owner blocks inspect)

**Comment by TheColaber** [comment]
Sure, try that... I'm trying to see if there are any errors that devtools might be creating.

**Comment by GarboMuffin** [comment]
On ChromeOS, ctrl+space is an OS-level shortcut to switch keyboard layout

**Comment by HiImBlahh** [comment]
> What is your browser information? Also, I could reproduce.

I'm on chromebook

**Comment by HiImBlahh** [comment]
> Ah no chromebook won't work.

aw man. is there a way you can change it to a different ctrl+ thing or put it in the popup when you right click?

**Comment by HiImBlahh** [comment]
> ~Sure, try that... I'm trying to see if there are any errors that devtools might be creating.~ GarboMuffin found the problem.

what is it

**Comment by HiImBlahh** [comment]
> On ChromeOS, ctrl+space is an OS-level shortcut to switch keyboard layout
> 
> It seems like it cannot be disabled by JS

can you change the add block by name to a different shortcut?

**Comment by Shluffy** [comment]
> > On ChromeOS, ctrl+space is an OS-level shortcut to switch keyboard layout
> > It seems like it cannot be disabled by JS
> 
> can you change the add block by name to a different shortcut?

I mean, you already could just use middle click, although that only works if you have a mouse.

**Comment by HiImBlahh** [comment]
I figured it out! All i have to do is place 3 fingers on the mouse pad and click, and it pops up! I am now closing this. Thanks for your help

**Comment by Shluffy** [comment]
still about the shortcut?

**Comment by HiImBlahh** [comment]
> still about the shortcut?

what so you mean

**Comment by Shluffy** [comment]
> > still about the shortcut?
> 
> what do you mean

the shortcut not working. That still is a problem.

**Comment by HiImBlahh** [comment]
> > > still about the shortcut?
> > 
> > 
> > what do you mean
> 
> the shortcut not working. That still is a problem.

oh. do you want me to open it again? The reason i closed it is because i found a solution, which is to put 3 fingers on the mouse pad and click.

**Comment by Shluffy** [comment]
> > > > still about the shortcut?
> > > 
> > > 
> > > what do you mean
> > 
> > 
> > the shortcut not working. That still is a problem.
> 
> oh. do you want me to open it again? The reason i closed it is because i found a solution, which is to put 3 fingers on the mouse pad and click.

yes, as the bug is still present.

**Comment by HiImBlahh** [comment]
ok, opened

**Comment by mxmou** [comment]
I think a shortcut that works on all platforms should be added (without removing the existing one).
