### ISSUE TITLE
Suggestion: auto hide variables when created

### ISSUE THREAD

**Issue by HiImBlahh** [ScratchAddons/ScratchAddons#2322]
It auto hides variables when they are created.

An addon for the editor. when the checkbox is clicked it will auto hide variables when they are created.

**Link to the new addon**

**Comment by RedGuy12** [comment]
+1
________________________________
From: HiImBlahh ***@***.***>
Sent: Thursday, April 29, 2021 12:43:50 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Suggestion: auto hide variables when created (#2322)


It auto hides variables when they are created.

An addon for the editor. when the checkbox is clicked it will auto hide variables when they are created.

Link to the new addon

**Comment by HiImBlahh** [comment]
I only thought of this because i think it's annoying when the variables show themselves when i create them.

**Comment by ErrorGamer2000** [comment]
I am thinking about trying it ... actually a good idea.
