### ISSUE TITLE
Transparent Orphan blocks

### ISSUE THREAD

**Issue by ErrorGamer2000** [ScratchAddons/ScratchAddons#2330]
**Describe the new addon**

If a block is unused and orphaned, it is made transparent, like in code.org.

**Comment by ErrorGamer2000** [comment]
Can just use
```js
block.setOpacity(0.25);
```

**Comment by TheColaber** [comment]
https://user-images.githubusercontent.com/72760579/116724140-4a3f5400-a9ae-11eb-960f-6ca62a50fa85.mp4

Something like that?

**Comment by ErrorGamer2000** [comment]
yes

**Comment by Endermaster3690** [comment]
let's add an option to set transparency

**Comment by ErrorGamer2000** [comment]
There will be. It's almost done already. I even got the dropdown menus to change ^^

**Comment by ErrorGamer2000** [comment]
https://user-images.githubusercontent.com/70162741/116730572-e31da180-a9a5-11eb-9efb-b672fd3a4649.mp4

**Comment by Endermaster3690** [comment]
Good! I think I'd use the addon.
Also off topic but what happened to the snap keyboard editor addon?

**Comment by ErrorGamer2000** [comment]
Umm.... It's a little beyond my skillset at the moment. I only did tiny bits of tutorials on MDN and W3schools and am otherwise self-taught... I am going to keep working on it though. My biggest issue it that I have to dynamically create and add blocks, determine between variables, strings, and operators, and THEN convert it to the correct format to add to the workspace...

**Comment by ErrorGamer2000** [comment]
#2332

**Comment by silvxrcat** [comment]
Like https://arcade.makecode.com?
