### ISSUE TITLE
Enhance thumbnail setter

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#2334]
1. This should be a "community" addon, not an "editor" addon - editor addons are about the project itself, and thumbnails are only a concept as part of the community site. Adding the "set thumbnail" button to the editor makes some sense, but not really. It's probably better to add a "set thumbnail" button next to "add to studio" and "copy link", or somewhere else in the project page. Not sure how we should transition so that users find the button after the change (specially difficult because this is enabled by default).
2. Should have better UX. Show the user the updated thumbnail. Clarify that if someone looks wrong, but the request 200ed, it's Scratch's fault, not ours (Scratch's thumbnail server sometimes works weirdly). Clarify within the UI that resaving the project will change the thumbnail (unless "DON'T SET THUMBNAILS AUTOMATICALLY" setting is on)

**Comment by RedGuy12** [comment]
> Not sure how we should transition so that users find the button after the change (specially difficult because this is enabled by default).

We could put it in both places, then when they click it in the editor, let them know about the new button. And in the next version, we can remove it.

**Comment by PoIygon** [comment]
> > Not sure how we should transition so that users find the button after the change (specially difficult because this is enabled by default).
> 
> We could put it in both places, then when they click it in the editor, let them know about the new button. And in the next version, we can remove it.

how about in the pop up when there's a new update you can tell people that it has moved to the project page

**Comment by mxmou** [comment]
I think the button should be next to "See inside", not "Add to studio".

Maybe consider doing this and #1440 at the same time?

**Comment by WorldLanguages** [comment]
We also need a better way to check whether the buttons should be injected. The current way of checking if the title element is there is probably racy and does not work 100% of the time

**Comment by mxmou** [comment]
@WorldLanguages This was mentioned when the PR was made: https://github.com/ScratchAddons/ScratchAddons/pull/2174#discussion_r614074984

**Comment by RedGuy12** [comment]
Use waitForElement?



Also, consider this:

You open the editor on someone else's project. The username does not match so the button is not there.

Then you click remix and suddenly the button should be there...but it's not (havent tested, this bug might not exist)
________________________________

**Comment by WorldLanguages** [comment]
@RedGuy12 Yeah, project state is complicated and I'm pretty sure most of our addons aren't ready for all of those edge cases.
