### ISSUE TITLE
Addons Completely Bugging Out

### ISSUE THREAD

**Issue by AIador** [ScratchAddons/ScratchAddons#2337]
**Describe the bug**
Plugin works as intended, except for the "Addons" option in the plugin. Clicking the settings button results in a blank page, inspecting reveals "<body style="display: none">" and manually changing it results in this r/softwaregore worthy image: 
![image](https://user-images.githubusercontent.com/83485226/116769460-86e46d00-a9f9-11eb-8167-e7b0df19fa2c.png)

**To Reproduce**

I have no idea... download Scratch Addons on Firefox ig...?

**Expected behavior**

Plugin operating as normal, me being able to edit addons, not seeing an r/softwaregore image, etc.

**Device (please complete the following information):**

- OS: Windows 10
- Browser Burning Fox (Firefox)
- Version I have no idea tbh

**Comment by TheColaber** [comment]
Wow, this is very interesting... Vue or the JS is not loading....... Could you press Ctrl + Shift + J and take a picture of the console?

**Comment by RedGuy12** [comment]
@Alador, do you have do versions of scratch addons installed?

**Comment by WorldLanguages** [comment]
@AIador Can you post a screenshot of the devtools console?

**Comment by AIador** [comment]
@WorldLanguages: ![image](https://user-images.githubusercontent.com/83485226/116815856-bc35ab80-ab1c-11eb-87b3-6d6d9f5517ae.png)
@RedGuy12: Scratch Addons is ver. 1.13

**Comment by TheColaber** [comment]
@AIador Is that the console from the scratchaddons settings page?

**Comment by RedGuy12** [comment]
It looks like the GitHub console.

**Comment by WorldLanguages** [comment]
@Alador yeah please screenshot the console of the settings page, not any other one

**Comment by AIador** [comment]
that _is_ the console from the settings page

**Comment by GarboMuffin** [comment]
> SyntaxError: expected expression, got '.' index.js 81

Probably refers to:

https://github.com/ScratchAddons/ScratchAddons/blob/215d762b84f0e1e01918fd8841dd2a995a1ad81b/webpages/settings/index.js#L81

So your browser doesn't understand optional chaining. You should probably update it.

**Comment by apple502j** [comment]
Scratch Addons supports Chrome 81+.

**Comment by TheColaber** [comment]
In that case, would it be easy to add `"minimum_chrome_version": "81"` to the manifest.json?

**Comment by RedGuy12** [comment]
> Scratch Addons supports Chrome 81+.



> In that case, would it be easy to add `"minimum_chrome_version": "81"` to the manifest.json?

He's on FF, not chrome

**Comment by TheColaber** [comment]
Then also add `"strict_min_version": "idk"` to browser_specific_settings.gecko?

**Comment by WorldLanguages** [comment]
Yeah, don't expect us to support browser versions older than 6 months
