### ISSUE TITLE
Holding right click will only drag that block

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#2338]
> Idea: holding right click instead of left click and dragging a block out of a script will only take out that block and not everything underneath it.

https://github.com/LLK/scratch-blocks/blob/develop/core/block_svg.js#L745 might be useful but who knows...

**Comment by WorldLanguages** [comment]
Good idea

**Comment by lisa-wolfgang** [comment]
This wouldn't work very well for touchpad users -- perhaps an option could also be added to the dropdown.

**Comment by piw-piw** [comment]
Or the possibility of setting.
