### ISSUE TITLE
Transifex doesn't display 1 letter long variables

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2344]
**Describe the bug**

Variables in the string `gamepad/axes-a-b` aren't shown as variables in Transifex, possibly because their names are only 1 character long.

**To Reproduce**

View the `gamepad/axes-a-b` string on Transifex.

**Expected behavior**

They would be displayed as variables.

**Screenshots**

![image](https://user-images.githubusercontent.com/51849865/116816268-88c94000-ab61-11eb-9c22-e3c2343bf20c.png)

**Comment by apple502j** [comment]
Whoops, not related to length, I just forgot to copy-paste userscripts on devtools on Transifex page.

**Comment by WorldLanguages** [comment]
@mxmou Yes you read that right, for some reason (mainly Transifex being poop), apple502j has been manually pasting code into the console every day that turns these into placeholders. And he forgot this time :P

**Comment by mxmou** [comment]
@WorldLanguages Was #1361 also caused by that?

**Comment by WorldLanguages** [comment]
Probably
