### ISSUE TITLE
Certain addons make "Save now" appear even if no changes were made

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2346]
**Describe the bug**

If the `data-category-tweaks-v2` addon is enabled, the "Save now" button always shows in the menu bar, even if no changes were made to the project.

**To Reproduce**

1. Enable data category tweaks
2. Open the editor

**Expected behavior**

The "Save now" button would only appear when making changes to the project.

**Device (please complete the following information):**

- Browser: Edge
- Version: 90

**Comment by GarboMuffin** [comment]
Can anyone reproduce this? I can't

**Comment by WorldLanguages** [comment]
@mxmou Clearer repo steps? What addons do you have enabled and with what settings?

**Comment by mxmou** [comment]
This doesn't appear to be caused by Scratch Addons.

**Comment by DNin01** [comment]
Some more information from @mxmou on https://github.com/ScratchAddons/ScratchAddons/issues/7549#issuecomment-2179319329:

> > @DNin01
> > You might also want to try testing with different combinations of addons enabled. Maybe start with all addons disabled and enable them one by one and see which ones make this happen.
> 
> I believe it's [those that trigger workspace updates](https://github.com/search?q=repo%3AScratchAddons%2FScratchAddons%20emitworkspaceupdate&type=code).
