### ISSUE TITLE
Devtools find bar disappears when changing language

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2347]
**Describe the bug**

When the editor language is changed, the find bar added by `editor-devtools` disappears.

**To Reproduce**

1. Enable developer tools
2. Open the editor
3. The find bar is present
4. Change the language
5. The find bar disappears

**Expected behavior**

It would stay.

**Comment by WorldLanguages** [comment]
Was fixed by #3052
