### ISSUE TITLE
Remove one of the three "More Settings" buttons from popup

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2353]
**Is your feature request related to a problem? Please describe.**

When the "Addons" tab is selected in the popup, there are now three buttons that open the settings page (including the one in the popup header).

**Describe the solution you'd like**

Remove the More Settings button next to the search bar.

**Describe alternatives you've considered**

Remove the newly added one instead and change the message above it to say "Click *More settings* above to explore all 80+ addons".

**Comment by RedGuy12** [comment]
I talked with WL about this on Discord, he said "well, we want people to go there"

**Comment by mxmou** [comment]
@RedGuy12 Isn't two buttons enough to tell people to do there? And no, a full width search bar doesn't look bad:
![image](https://user-images.githubusercontent.com/51849865/116825759-e1640180-ab90-11eb-85a0-6ba3a7a3f951.png)

**Comment by WorldLanguages** [comment]
TBD for next release

**Comment by mxmou** [comment]
The problem is that the buttons are very close to each other. It isn't much better than
![image](https://user-images.githubusercontent.com/51849865/116825854-60f1d080-ab91-11eb-81c3-12a8b290f945.png)

@WorldLanguages Why not this release?

**Comment by WorldLanguages** [comment]
> @WorldLanguages Why not this release?

For my own mental health :P

**Comment by xItzDiamondx** [comment]
> @RedGuy12 Isn't two buttons enough to tell people to go there? And no, a full width search bar doesn't look bad:
> ![image](https://user-images.githubusercontent.com/51849865/116825759-e1640180-ab90-11eb-85a0-6ba3a7a3f951.png)

I mean, it would look good if the tabs were centered.

**Comment by mxmou** [comment]
@xltzDiamondx Here's the full screenshot:
![image](https://user-images.githubusercontent.com/51849865/116922916-446b9c00-ac56-11eb-8612-822181c8cb68.png)

**Comment by xItzDiamondx** [comment]
Maybe this will work? (I'll add a pull request)

**Comment by WorldLanguages** [comment]
This is probably OK:
![image](https://user-images.githubusercontent.com/17484114/118377902-87a70280-b5a6-11eb-8f2a-219f8e09e14b.png)

Note: screenshot above added the settings icon to "open full screen settings", which was previously used in the button I removed.
I'm not convinced about search being that wide tho. But I guess this is consistent with the margin of the <addon-body> elements, which also have 10px to either side.

**Comment by xItzDiamondx** [comment]
Looks even and nice.

**Comment by TheColaber** [comment]
maybe if we add a new feature, it could take up some space

**Comment by WorldLanguages** [comment]
@TheColaber That's not how it works lol, we do not add features when we need to fill space, we add them when it's suitable :P

**Comment by TheColaber** [comment]
In that case, make it suitable too.

**Comment by return-misaPuding** [comment]
lol

Dne ne 16. 5. 2021 1:01 uživatel TheColaber ***@***.***>
napsal:
