### ISSUE TITLE
Decimals in Followers over time

### ISSUE THREAD

**Issue by Endermaster3690** [ScratchAddons/ScratchAddons#2362]
**Describe the bug**

**To Reproduce**

1. Go to someone's profile who has had the same amount of followers for a while, example S1A_02: https://scratch.mit.edu/users/S1A_02/
3. Scroll down to 'Followers over time'
4. See decimals

**Expected behavior**

have decimals

**Screenshots**

![deciglitch](https://user-images.githubusercontent.com/80355301/116883155-e48bdb80-abea-11eb-9b00-3474449cbd70.png)

**Device (please complete the following information):**
- OS: Windows
- Browser Google Chrome
- Version version of what?

**Additional context**

no

**Comment by xItzDiamondx** [comment]
lol i just was looking at the issue and it just gets closed
