### ISSUE TITLE
not highlighting whoel word in variable manager

### ISSUE THREAD

**Issue by Shluffy** [ScratchAddons/ScratchAddons#2365]
**Describe the bug**

Ctrl+Shift+[Left or right arrow key] won't highlight the whole word in Variable manager

**To Reproduce**

1. Go to a scratch project
2. Make a variable/use a variable with multiple spaces
3. Try to highlight a whole word at once

**Expected behavior**
to highlight the whole word

**Device:**
Google Chrome OS, Version 91.0.4472.25 (Official Build) beta (64-bit) on a chromebook.

**Additional context**

**Comment by RedGuy12** [comment]
That's a browser bug. Or maybe your browser does that for a reason. Try looking in your browser settings to see if you can change that behavior.
