### ISSUE TITLE
"Save blocks as image" addon doesn't capture custom block colors

### ISSUE THREAD

**Issue by towerofnix** [ScratchAddons/ScratchAddons#2379]
**Describe the bug**

The "save blocks as image" addon captures blocks as they look in default Scratch, without colors applied by "customizable block colors". 

**To Reproduce**

1. Make sure both "save blocks as image" and "customizable block colors" are enabled.
2. Change the block color settings to something besides the default (e.g. one of the presets).
3. Export blocks from the editor (as PNG or SVG, all or only selected—same result either way).
4. View the downloaded image. Note it has the default block colors, not the customized ones.

**Expected behavior**

Generally, captures of blocks should probably show as close to they actually look in the editor as possible. If for any reason a user desires otherwise (i.e. would rather capture blocks as they look in the default editor, like current), the fix could be implemented as a toggle option.

**Screenshots**

Compare the colors below (note the "when I receive" block as well as custom blocks):

![On left, the editor, with brown "when I receive" and deep purple custom blocks. On right, an image capture of the same script, with the default editor colors, yellow "when I receive" and coral custom blocks.](https://user-images.githubusercontent.com/9948030/117090678-5ec57880-ad2f-11eb-82ab-b511028eade3.png)

**Device (please complete the following information):**

- OS: Linux/Debian
- Browser: Firefox (Developer Edition)
- Version: 89

**Additional context**

Notably, the "custom block shape" addon [plays nicely](https://user-images.githubusercontent.com/9948030/117090934-21151f80-ad30-11eb-9cb8-42efdf5c43bf.png) with "save blocks as image" (though custom colors are still not captured).

**Comment by Marc92020** [comment]
Exporting SVGs also just shows a small part of the top of any code made
