### ISSUE TITLE
Addon/option to disable selecting a sprite when double clicking inside editor?

### ISSUE THREAD

**Issue by towerofnix** [ScratchAddons/ScratchAddons#2380]
**Describe the new addon**

A lot of games involve repeatedly clicking! In Scratch, double-clicking on a sprite in the editor makes it become the focused sprite, which causes a bit of lag when loading in the new blocks, and makes you have to return to the sprite you're working in to go back to coding. (Plus, when using the sprite folders addon, if the sprite you're double-clicking is in a collapsed folder, it'll un-collapse the folder. This is annoying and basically makes it so I never collapse the folder a sprite I regularly click is in, since I just keep having to re-collapse it. :P)

This is a pretty small feature so maybe it fits better as an addition to an existing addon—but it's also probably a regularly sought tweak, so unless it already exists and I'm missing it somewhere, it may actually be worth having it as its own thing. Up for discussion!

(It could be added as part of a more substantial "treat stage like outside editor" addon, alongside other options, like "disable dragging sprites in editor". [I implemented a basic version of this in Scrap a few years ago!](https://github.com/towerofnix/scrap-mod/pull/49))

**Comment by ErrorGamer2000** [comment]
I just put it in fullscreen mode, that fixes it.

**Comment by ErrorGamer2000** [comment]
I have a suggestion. What if we put an invisible `div` over the project area that can be toggled on and off?

**Comment by ErrorGamer2000** [comment]
Aaannnd.... It Works! just paset this code into the console:

```js
((doc) => {
  let c = document.querySelector("canvas");
  let rect = c.getBoundingClientRect();
  let div = document.createElement("div");
  div.style.position = "fixed";
  div.style.top = rect.top + "px";
  div.style.left = rect.left + "px"
  div.style.height = rect.height + "px"
  div.style.width = rect.width + "px"
  doc.appendChild(div);
})(document.body || document.documentElement)
```

**Comment by retronbv** [comment]
> paset

paste*

**Comment by ErrorGamer2000** [comment]
oof

**Comment by GrahamSH-LLK** [comment]
> Aaannnd.... It Works! just paset this code into the console:
> 
> ```js
> ((doc) => {
>   let c = document.querySelector("canvas");
>   let rect = c.getBoundingClientRect();
>   let div = document.createElement("div");
>   div.style.position = "fixed";
>   div.style.top = rect.top + "px";
>   div.style.left = rect.left + "px"
>   div.style.height = rect.height + "px"
>   div.style.width = rect.width + "px"
>   doc.appendChild(div);
> })(document.body || document.documentElement)
> ```

I _think_ that would disable _all_ clicks. Plus, things like that should be done with Blockly/vm.

**Comment by ErrorGamer2000** [comment]
Hadn't thought about that, yeah...

**Comment by towerofnix** [comment]
> I _think_ that would disable _all_ clicks. Plus, things like that should be done with Blockly/vm.

Yep, this is right—without interfacing with Scratch's internals we don't have a way to differentiate between dragging sprites and passing ordinary click/drag events through.

The VM doesn't actually have anything to do with this, somewhat surprisingly! As far as I can tell there is no "editor mode" in it. That's handled by scratch-gui, particularly its [`<Stage>`](https://github.com/LLK/scratch-gui/blob/ba76db7350bd43b79119cac2701bc10f6c511f0c/src/containers/stage.jsx) component—see [`onStartDrag`](https://github.com/LLK/scratch-gui/blob/ba76db7350bd43b79119cac2701bc10f6c511f0c/src/containers/stage.jsx#L342).

The React property to change (or somehow otherwise capture) is [`useEditorDragStyle`](https://github.com/LLK/scratch-gui/blob/ba76db7350bd43b79119cac2701bc10f6c511f0c/src/containers/stage.jsx#L351-L352). Maybe other addon writers have experience with how to go about overriding that?

**Comment by GrahamSH-LLK** [comment]
@apple502j would be the one to know whether that's possible.

**Comment by towerofnix** [comment]
Actually re: my edit, maybe those are methods which could more easily be overridden? E.g, capturing/overriding calls to `vm.startDrag`. It'd be important to *not* disable dragging on targets which are *specifically* draggable, but we could simulate that pretty easily:

```js
const enableDragging = false; // or true ofc

// Just pseudocode!
overrideAndCaptureSomehow(vm, 'startDrag', (vm, originalFn, args) => {
    const targetId = args[0];
    const target = vm.getTargetById(targetId);
    if (enableDragging || target.draggable) {
        originalFn.apply(vm, args);
    }
});
```

**Comment by apple502j** [comment]
Yep that's much easier. While we could trap React components (and some complex addons like folders do that), VM pollution is much more easy and simple way.

**Comment by lisa-wolfgang** [comment]
This issue was addressed by having https://github.com/ScratchAddons/ScratchAddons/pull/2818 enabled (I tested) -- should it be closed?

Nobody has complained about not having the option to disable double-clicking separately from dragging, but we might want to add that for completeness.

**Comment by towerofnix** [comment]
Yes, that addon covers the requested behavior here! Thanks. For now I'll leave it open in case it's agreed that there be separate toggles in that addon for disabling editor-selecting and editor-dragging individually (and somebody wants to implement that). I think it would make sense to add the toggles, both enabled by default of course.
