### ISSUE TITLE
Forum emojis are blank when "Better forums post editor buttons" is on

### ISSUE THREAD

**Issue by socialized0** [ScratchAddons/ScratchAddons#2383]
### **Describe the bug**

When having the "Better forums post editor buttons" addon on, you are unable to see the forum emojis (such as :mad:). The only way I can fix this behavior is to turn the addon off, which I don't want to.

### **To Reproduce**

**1.** Go to Scratch Addons settings
**2.** Turn on the addon "Better forums post editor buttons"
**3.** Find a forum post with emojis
**4.** Notice that the emojis are completely blank

### **Expected behavior**
Being able to see the forum emojis while having "Better forums post editor buttons" on.

### **Screenshots**

When the addon is off: 
![image](https://user-images.githubusercontent.com/75202279/117155766-b9111880-adc5-11eb-9f89-6df03fcde67d.png)

When the addon is on: 
![image](https://user-images.githubusercontent.com/75202279/117155669-a3035800-adc5-11eb-8543-9ff018d02d8e.png)

### **Device (please complete the following information):**

- **OS:** Windows 10 build 19042
- **Browser:** Firefox Nightly
- **Version:** 90.0a1 (2021-04-30)

### **Additional context**
The bug also occurs on Firefox Stable.

**Comment by apple502j** [comment]
@RedGuy12 Seems like this feature is intentional? plz explain

**Comment by TheColaber** [comment]
###### why did you ping redguy?

**Comment by RedGuy12** [comment]
i didn't make this addon @Secret-chest did

**Comment by apple502j** [comment]
whoops

**Comment by Secret-chest** [comment]
I will fix it

**Comment by WorldLanguages** [comment]
lol I thought about this happening but forgot
