### ISSUE TITLE
addon.json property: `history`

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#2384]
Example:
```json
{
  "history": [
    {
      "event": "added",
      "version": "1.10.0"
    },
    {
      "event": "update",
      "info": "Added settings",
      "version": "1.11.0"
    },
    {
      "event": "update",
      "info": "Fixed elements not appearing sometimes",
      "version": "1.11.1"
    },
    {
      "event": "update",
      "info": "Now has presets",
      "version": "1.13.0"
    }
  ]
}
```
1. This would be nice for devs
2. This would be nice for the user if we implemented #1424 so that way they won't have to go to changelog for updated addons
3. History can be kept in the settings page in the form of #475
4. This might be a better solution then `versionAdded`

**Comment by Hans5958** [comment]
Hello, 2021! Somehow found this issue out of nowhere.

It would be better to implement it on the documentation instead. The plans on ScratchAddons/website-v2#260 would have the changelog section, which let devs describe the changes better.

**Comment by WorldLanguages** [comment]
Agree with Hans - this won't belong in the addon manifest.
