### ISSUE TITLE
Cat Blocks: Watch mouse pointer setting does not work for newly loaded extensions

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#2391]
**Describe the bug**

When you load an extension into scratch, the hat blocks on the flyout do not watch you. Yet when you drag them out, the blocks in the workspace do.

**To Reproduce**

1. Go to Editor
2. Click on ![image](https://user-images.githubusercontent.com/72760579/117191433-8f002c00-adae-11eb-8f84-0ebfb07db4c9.png)
3. Load Makey makey for example
4. See how it's hat blocks in the flyout aren't watching you

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

I could repro on both chrome and firefox, on both scratch and tw.

**Comment by Weredime** [comment]
cant repro

**Comment by Samq64** [comment]
I can't reproduce on Chromium or Firefox.

**Comment by RIMOPA** [comment]
What do you mean with a hat block that watches you?

**Comment by WorldLanguages** [comment]
@Samq64 Does "can't reproduce" mean that the eyes on Makey Makey hat blocks are following your cursor?

**Comment by Samq64** [comment]
Yes, even the ones in the block palette right after loading the extension.

**Comment by WorldLanguages** [comment]
@TheColaber Could you try to reproduce your own bug report again?

**Comment by TheColaber** [comment]
Could still repro. Again, here are the steps:
1. Enable Cat Blocks and its setting: Watch cursor. (Up up down down left right left right b a)
2. Open new project
3. Add a new extension, such as Makey Makey.
4. Observe as the hat blocks *are cat blocks* but do not follow the cursor, however the other hat blocks such as the "when flag clicked" hat does.

**Comment by Samq64** [comment]
I can reproduce, but only if I change block categories before loading the extension.
