### ISSUE TITLE
Gamepad support removes pause button

### ISSUE THREAD

**Issue by Steve0Greatness** [ScratchAddons/ScratchAddons#2392]
When you have both the pause button and gamepad support on at the same time, the pause button will get removed

turn on gamepad support, then turn on the pause button.
Then go to any project.
![The bug.](https://u.cubeupload.com/Steve_Greatness/72fScreenshot2021050512.png)
- OS: chrome OS
- Browser Chrome
- Version 13816.64.0?

**Comment by TheColaber** [comment]
The problem should still happen without the gamepad addon. The bug has been fixed and v1.14.1 will be released today.
