### ISSUE TITLE
Firefox-only popup theming issue

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#2394]
**Describe the bug**

![image](https://user-images.githubusercontent.com/43426138/117207968-359dfa00-adba-11eb-8f6d-3f094d8c7be5.png)

The triangle remains dark after switching to light mode.

**To Reproduce**

1. Update to the latest release version of Scratch Addons (v.1.14.1) on Firefox
2. Enable light mode
3. Open the popup

**Expected behavior**

The triangle should be white or (better yet) orange.

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Firefox 88
- Version: 1.14.1

**Comment by GrahamSH-LLK** [comment]
AFAIK we don't control that triangle, it's part of firefox's ui.

**Comment by mxmou** [comment]
@GrahamSH-LLK We do.
