### ISSUE TITLE
Enhance URL matching algorithm

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#24]
https://github.com/ScratchAddons/extension/blob/95fa8f3f2f4857b5e49684afc3728e2de1d3fa6c/background/get-userscripts.js#L36
`https://scratch.mit.edu/users/kaj` should match `https://scratch.mit.edu/users/*/`. A slash at the end should be implicit.
I should also remove the function from the window object. I did that to debug something and forgot about it.

**Comment by tb148** [comment]
I think this is a bug.

**Comment by BoomerScratch** [comment]
I think we should use regexes. Let me try to do this.

**Comment by WorldLanguages** [comment]
@tb148 Yeah. I'll use the URL built-in constructor to fix this (and also make it so stuff like hashes (e.g. #comments-1234567) doesn't affect it.
