### ISSUE TITLE
Players icon in cloud games is orange

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2406]
**Describe the bug**

The icon that appears next to player counts in the cloud games addon is orange.

**To Reproduce**

1. Open the popup
2. Click the "Games" tab

**Expected behavior**

It would be white.

**Screenshots**

![image](https://user-images.githubusercontent.com/51849865/117263757-e3f57e00-ae52-11eb-94db-ddbf8964de49.png)

**Additional context**

It was ~~un~~intentionally changed in #2260.

**Comment by apple502j** [comment]
[Intentional](https://github.com/ScratchAddons/ScratchAddons/pull/2260/commits/c970657e17b7a5fcf00063b4799db07d5a0481ae), period.

> NOTE: this also affects cloud-games but I think this color is better.

**Comment by mxmou** [comment]
@apple502j This is inconsistent with icons in the messaging popup. It also looks weird: nothing else in the cloud games popup is orange, why should the icons be?

**Comment by Shluffy** [comment]
maybe change more icons to be orange so it fits with the rest of the popup?

**Comment by mxmou** [comment]
@Shluffy That would fix the inconsistency, but it's a strange design choice. Orange is used for parts of the UI that should stand out, like the selected tab, which most icons are not.

**Comment by Shluffy** [comment]
> @Shluffy That would fix the inconsistency, but it's a strange design choice. Orange is used for parts of the UI that should stand out, like the selected tab, which most icons are not.

Okay.

**Comment by WorldLanguages** [comment]
This was intentional, sure, but because the PR was so big we all missed this detail :P
