### ISSUE TITLE
Many plugins don't work after 1.14 update.

### ISSUE THREAD

**Issue by Tacodude7729** [ScratchAddons/ScratchAddons#2410]
**Describe the bug**

Many plugins don't work after the 1.14 update. The error is always the same `Cannot read property 'scratchGui' of undefined`. The effected plugins do nothing when enabled. **Many** plugins seems to be effected. Sometimes chrome claims scratch is unresponsive and asks to kill the tab, I'm assuming this is related.

The error for searchable drop-downs:
```
Uncaught (in promise) TypeError: Cannot read property 'scratchGui' of undefined
    at Object.condition (userscript.js:178)
    at EventTarget.waitForElement (Tab.js:53)
    at findBlocklyDropDownDiv (userscript.js:176)
    at Module.default (userscript.js:183)
    at loadUserscript (run-userscript.js:21)
```
The error for script and sprite count:
```
Uncaught (in promise) TypeError: Cannot read property 'scratchGui' of undefined
    at Object.condition (userscript.js:62)
    at EventTarget.waitForElement (Tab.js:53)
    at hideInSmallStageMode (userscript.js:59)
    at Module.default (userscript.js:4)
    at loadUserscript (run-userscript.js:21)
```
Searchable dropdowns not working.
![image](https://user-images.githubusercontent.com/27910867/117280836-5c395f00-aea6-11eb-974b-d51b52813c0f.png)

Ubuntu 20.04 Chrome 89.0.4389.114
**For me, this issue dosn't effect firefox.**

**Comment by GarboMuffin** [comment]
#2268 is really the PR that keeps on giving

if anyone wants to fix, add `addon.tab.redux.state &&` to https://github.com/ScratchAddons/ScratchAddons/blob/5b639ca74166aea8bf9ad69f7f0eb1884989f173/addons/editor-searchable-dropdowns/userscript.js#L178

or, maybe just revert that entire PR because it's clearly very broken

**Comment by GarboMuffin** [comment]
or, at least condition throwing an error should be caught and treated as return false in API

**Comment by GarboMuffin** [comment]
ok, this is more nuanced than I initially thought. Those addons don't have runAtComplete: false so they won't run before redux is ready, so my initial fix probably won't do anything. It would probably fix the error but not make the addons work.

@Tacodude7729 Can you try turning off your other browser addons? Specifically "Redux DevTools", if you have that installed. It seems that it conflicts with Scratch Addons: https://github.com/ScratchAddons/ScratchAddons/blob/b4cc1574db0285d94074b623ac544b7809d2561a/content-scripts/load-redux.js#L3-L5

**Comment by WorldLanguages** [comment]
@Tacodude7729 Do you see a `Redux feature is disabled due to conflict.` warning in your console?

**Comment by lisa-wolfgang** [comment]
I tested both affected addons, and I'm unable to repro on v.1.14.1 using a Chromium browser.

**Comment by Tacodude7729** [comment]
@WorldLanguages @GarboMuffin Disabling redux dev tools solves the issue, but I see no `Redux feature is disabled due to conflict.` message. Here is my entire log before the error https://pastebin.com/H03Zpzcv.

**Comment by TheColaber** [comment]
`Redux feature is disabled due to conflict.` would only be shown if the Redux devtools extension is enabled. The problem has been found

**Comment by apple502j** [comment]
This is working as intended. Please uninstall Redux DevTools.

**Comment by WorldLanguages** [comment]
Moved to #2419

**Comment by WorldLanguages** [comment]
@Tacodude7729 Could you please go to any Scratch website page that is not the editor (example: https://scratch.mit.edu/info/quotes) and check there if the `Redux feature is disabled due to conflict.` warning appears there? We want to confirm whether the warning works or not. Make sure your devtools is showing warns.

**Comment by Tacodude7729** [comment]
@WorldLanguages Uh, no. On that page I get three console messages.
```
DevTools failed to load SourceMap: Could not load content for chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/libraries/thirdparty/cs/comlink.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/libraries/thirdparty/cs/icu-message-formatter.es.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
(index):1 [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" name=​"password" class=​"password">​
```
I don't know why. When I put the below into the console I see the warning, so the check seems to be working correctly.
```
 if (typeof window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ !== "undefined") { 
   console.warn("Redux feature is disabled due to conflict."); 
 } 
```

**Comment by RedGuy12** [comment]
Those three errors are fine.

It looks like Redux DevTools has either changed the name for their variable or made it locally scoped.

**Comment by apple502j** [comment]
@RedGuy12 that shouldn't happen. it only makes sense if it's named `__REDUX_DEVTOOLS_EXTENSION_COMPOSE__` on the global scope.
