### ISSUE TITLE
Setting the progress bar to a high number glitches out

### ISSUE THREAD

**Issue by 22yeetz22** [ScratchAddons/ScratchAddons#2412]
**Describe the bug**

It can go as high as you want it.

**To Reproduce**

1. Set the project bar to 1e+99 (or a high number)
2. Save a project in the editor.
3. Watch.

**Expected behavior**

To have a limit.

**Screenshots**

https://vimeo.com/545951538

**Device (please complete the following information):**

- OS: Windows 10
- Browse: Chrome
- Version: 90.0.4430.93 (Official Build) (64-bit)

**Additional context**

**Comment by lisa-wolfgang** [comment]
I mean... it's just doing what you ask it to do. This isn't a glitch. If a user wants to set their progress bar height to an absurd value, they should be able to do that. Most users have the common sense to set it to a reasonable value.

**Comment by Shluffy** [comment]
I think that this isn't really a bug, why would there be a limit?

**Comment by mxmou** [comment]
Most numeric settings have reasonable minimum and maximum values, so it would make sense to do the same for this one, but this isn't a bug.
