### ISSUE TITLE
Bring back the dark lists & variables but as an option

### ISSUE THREAD

**Issue by silvxrcat** [ScratchAddons/ScratchAddons#2415]
**Is your feature request related to a problem? Please describe.**

Yes! As to update 1.14, It resolved the stage being affected by dark mode, but to me, this seemed intentional and I'm fond of it.

**Describe the solution you'd like**

An option to switch on/off dark mode impacting the stage.

**Describe alternatives you've considered**

Better3- nah haven't tried any alternatives.

**Additional context**

I thought it was intentional :,D

**Comment by RedGuy12** [comment]
we decided the stage should be affected by website dark mode, not editor dark mode.

**Comment by TheColaber** [comment]
> we decided the stage should be affected by website dark mode, not editor dark mode.

When and why?

**Comment by RedGuy12** [comment]
> > we decided the stage should be affected by website dark mode, not editor dark mode.
> 
> When and why?

#2241

**Comment by mxmou** [comment]
@RedGuy12 We didn't, we decided that it shouldn't be dark at all (and making it affected by website dark mode would only make sense on the project page, not in the editor or full screen mode).

I think making this an option is a good idea.

**Comment by WorldLanguages** [comment]
Agreed on making it an option. Off by default. Should affect the monitors and ask inputs the same way, no matter if the project is in player, editor or fullscreen mode

**Comment by silvxrcat** [comment]
> Agreed on making it an option. Off by default. Should affect the monitors and ask inputs the same way, no matter if the project is in player, editor, or fullscreen mode

Agreed, it should be off by default like dark mode.

**Comment by silvxrcat** [comment]
Will this be added soon?
