### ISSUE TITLE
Meta: moving addon suggestions to Discussions

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#2425]
There are currently 114 new addon suggestions, and to be honest that's too many. We should probably move them to Discussions.

**Comment by TheColaber** [comment]
No apple. Just use the filter. This whole extension is about addons. It doesn't make sense to somehow decide they aren't the main focus anymore.

**Comment by mxmou** [comment]
Discussions are designed for questions and general discussion, not for feature requests.
