### ISSUE TITLE
"Use local timezone on forums" doesn't work in the "last edited" section

### ISSUE THREAD

**Issue by superscratch444tre** [ScratchAddons/ScratchAddons#2426]
**Describe the bug**

"Use local timezone on forums" addon doesn't convert the "last edited" section to the user's timezone.

**To Reproduce**

1. Go to a forum post that has been edited with the "Use local timezone on forums" addon enabled **(Make sure your timezone is different from scratch's timezone!)**
2. See that the hour shown in the "last edited" section isn't converted to your timezone.

**Expected behavior**

The "last edited" section should also be converted to the user's timezone.

**Screenshots**

<img width="850" alt="Screenshot 2021-05-07 183923" src="https://user-images.githubusercontent.com/69812464/117474890-180c9400-af64-11eb-88d7-8711419e3277.png">

("Azi" and "Astăzi" translate to "Today" in romanian, if you are wondering)

**Device (please complete the following information):**

- OS: [e.g. Windows 10]
- Browser [e.g. chromium (opera GX)]
- Version [e.g. lastest]

**Additional context**

My timezone shows that at the moment of writing (and making the screenshot), it was almost 19:00 (If that helps you somehow XD).

**Comment by WorldLanguages** [comment]
Note: this addon never did that. Not related to addon remake for v1.14.0
