### ISSUE TITLE
Release SA on Opera Store

### ISSUE THREAD

**Issue by silvxrcat** [ScratchAddons/ScratchAddons#2442]
**Is your feature request related to a problem? Please describe.**

Yes. I thought this was already done, so I checked the store and it wasn't there.

**Describe the solution you'd like**

Port SA onto the Opera Store.

**Additional context**

With the rise of Opera GX (which I'm using right now, check it out) it would be a great enhancement for SA being multi-browser supported.

**Comment by WorldLanguages** [comment]
@silvxrcat No ~ at the end of issue names please.

**Comment by WorldLanguages** [comment]
We probably won't be releasing in any more stores, since Chromium browsers should be able to download extensions from the Chrome Web Store just fine. It would take more work for little benefit.

**Comment by mxmou** [comment]
Edge only allows extensions from the Microsoft store by default, but I don't know why a user wouldn't want to change this setting.

**Comment by Scratchfangs** [comment]
Use this: https://addons.opera.com/en/extensions/details/install-chrome-extensions

**Comment by Scratchfangs** [comment]
This can be closed now.
