### ISSUE TITLE
Gamepad support - add support for individual axis

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#2445]
**Is your feature request related to a problem? Please describe.**

This is related to two problems:
1. Some controllers have axis that don't align with the expected arrow key layout (for example, tilting up makes the axis go right)
2. The limited options obviously don't support WASD, IJKL, or other buttons

**Describe the solution you'd like**

Axis and their directions should be treated as individual inputs. For example, Axis 0+ and Axis 0- could be new options, and they could go above/below the other buttons.

**Describe alternatives you've considered**

For simplicity, this could be hidden under an "Advanced" section, or be togglable in the settings.

**Comment by Secret-chest** [comment]
I dont have a gamepad but this sounds good

**Comment by GarboMuffin** [comment]
The gamepad addon lacks a lot of things. It will be improved eventually, especially for things related to joysticks.

> I do. PS4 Controller works. Problem: On Turbowarp, it doesn't work. The left joystick doesn't let me move when I'm playing Fortnite Z

What does "On Turbowarp, it doesn't work." mean? Does it work fine in Scratch Addons but not TurboWarp? If you open the configuration menu, what is the left joystick configured as and does the red dot move as it should?

**Comment by xItzDiamondx** [comment]
I'll make it a separate issue
