### ISSUE TITLE
Separate list category

### ISSUE THREAD

**Issue by towerofnix** [ScratchAddons/ScratchAddons#245]
**Describe the new addon**

An addon which divides the "Variables" category into two distinct categories, one for (scalar/ordinary) variable blocks and one for list blocks. Check out LLK/scratch-blocks#1874 for the rationale behind this request.

**Link to the new addon**

I've created an implementation based on my code in LLK/scratch-blocks#2099 and LLK/scratch-gui#6079 - PR incoming.

**Comment by Explosion-Scratch** [comment]
Nice! This would be super usefull! Also it's nice to see you here :)
