### ISSUE TITLE
Upgrade to Vue 3

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#2462]
**Is your feature request related to a problem? Please describe.**

We use Vue 1, which is really outdated.
**Describe the solution you'd like**

Upgrade to Vue 3.

### Read me: why this is possible and why we should
- Apple basically just added a build step for the manifest. You can use it without, but before publishing the extension you're going to run the action any way. Vue 3 would be the same way. We could have a folder that has the built webpages. Most people who wouldn't know how to build are contributing to addons at this point, and the build folder on master would work. We could exclude the unbuilt webpages from builds/
- Vue 3 is awesome. We could have single-file components with scoped css, and all of the benefits. (reactivity, etc)
- There are WAY more components that support Vue 3 than Vue 1.
- We wouldn't have to deal with Vue 1 jank (I think there's literally code for Jquery support?!) .
- I think we could rig up HMR!!!!!!!!! (Live reloading in tab)

**Comment by GrahamSH-LLK** [comment]
Response from @WorldLanguages:
- Apple basically just added a build step for the manifest. You can use it without, but before publishing the extension you're going to run the action any way. Vue 3 would be the same way. We could have a folder that has the built webpages. Most people who wouldn't know how to build are contributing to addons at this point, and the build folder on master would work. We could exclude the unbuilt webpages from builds/
we got closer but it's still not comparable
the build is only for release
here, we'd need to build for every change to the settings page
slightly different
- Vue 3 is awesome. We could have single-file components with scoped css, and all of the benefits. (reactivity, etc)
our settings page is relatively small, no need for scoped styles. reacitivity is pretty much the same, we rarely use Vue.set
- There are WAY more components that support Vue 3 than Vue 1.
we dont need any except color picker
- We wouldn't have to deal with Vue 1 jank (I think there's literally code for Jquery support?!) .
where?
- I think we could rig up HMR!!!!!!!!! (Live reloading in tab)
HMR adds complexity for no good reason, and I doubt it works very well in chrome, where some changes require full extension reload

**Comment by apple502j** [comment]
It's fine right now. Plus we don't have build script. It's for packaging; AKA making zips
