### ISSUE TITLE
Meta: Add .gitpod.yml and .gitpod.dockerfile for gitpod support

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#2465]
I've mostly worked out how to get Gitpod VNC support working with Firefox, so we could have a button in the readme that launches firefox with SA in Gitpod for people who can't work locally.

**Comment by apple502j** [comment]
And the number of dotfiles explode. Sure it could work, but I'd expect it's pretty rare that they can't work locally. (We do not support building extensions on school laptops, in case it wasn't clear)
