### ISSUE TITLE
New addon - scroll by dragging scripts toward edges

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#2471]
_This is a migrated suggestion from #591._

**Describe the new addon**

When dragging a script and moving the mouse-pointer toward an edge of the blocks space, the addon scrolls the editor from that direction a la 2.0.

**Comment by ErrorGamer2000** [comment]
Also, another idea that kind of goes along with this: locking the pointer to the workspace when a block is being dragged. Maybe? I am going to do some experimenting.

**Comment by ErrorGamer2000** [comment]
Oh, never mind that is impossible...

**Comment by lisa-wolfgang** [comment]
#4471 is technically a duplicate of this, but since that now has significantly more discussion, I'll go ahead and close this one.
