### ISSUE TITLE
New addon - fix moving comments

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#2475]
**Describe the new addon**

This addon would fix comments not saving correctly when they're moved, which results in something like this:

_before switching sprites_
![image](https://user-images.githubusercontent.com/43426138/117892962-2ff35900-b27f-11eb-8f0b-9cc8f05354e0.png)

_after switching sprites_
![image](https://user-images.githubusercontent.com/43426138/117892973-34b80d00-b27f-11eb-878e-7970b3ecec18.png)

**Comment by RedGuy12** [comment]
I think we're trying to reduce the number of big fix addons. Maybe you could pr to one of the https://github.com/LLK repos instead? Idk their contributing guidlings.
________________________________
From: lisa-wolfgang ***@***.***>
Sent: Tuesday, May 11, 2021 5:35:41 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] New addon - fix moving comments (#2475)


Describe the new addon

This addon would fix comments not saving correctly when they're moved, which results in something like this:

before switching sprites
[image]<https://user-images.githubusercontent.com/43426138/117892962-2ff35900-b27f-11eb-8f0b-9cc8f05354e0.png>

after switching sprites
[image]<https://user-images.githubusercontent.com/43426138/117892973-34b80d00-b27f-11eb-878e-7970b3ecec18.png>

**Comment by lisa-wolfgang** [comment]
> I think we're trying to reduce the number of big fix addons. Maybe you could pr to one of the https://github.com/LLK repos instead? Idk their contributing guidlings.

![image](https://user-images.githubusercontent.com/43426138/117910198-24188e80-b2a1-11eb-9574-530d28ea95e5.png)
![image](https://user-images.githubusercontent.com/43426138/117910213-2a0e6f80-b2a1-11eb-9428-48d03f01343b.png)
![image](https://user-images.githubusercontent.com/43426138/117910229-2ed32380-b2a1-11eb-9ad3-738272d58692.png)

**Comment by FunctionalMetatable** [comment]
what a coincidence that garbomuffin just fixed it on turbowarp

https://github.com/TurboWarp/scratch-blocks/commit/62c3c97919a1c9985948e8f40725f9b47fcf64c6

**Comment by mxmou** [comment]
If an addon like this is added, it should also fix [other bugs related to block comments](https://github.com/LLK/scratch-blocks/issues?q=is%3Aissue+block+comments) if possible.
