### ISSUE TITLE
Add more character space to about me as well

### ISSUE THREAD

**Issue by Shluffy** [ScratchAddons/ScratchAddons#2479]
**Is your feature request related to a problem? Please describe.**

I run out of space there as well as before I enabled the addon for an extra 55 characters for what I'm working on

**Describe the solution you'd like**

do the same for about me, possibly an option under that addon

**Describe alternatives you've considered**

n/a

**Additional context**

Possibly make it more then 55 characters allowed. Is there a soecific reason 55 was picked?

**Comment by TheColaber** [comment]
This is only possible for the wiwo sadly

**Comment by mxmou** [comment]
> This is only possible for the wiwo sadly...

Did you test it? It would be weird if about me and WIWO were handled differently on the backend.

**Comment by RedGuy12** [comment]
The WIWO addon forces scratch to use normally unused code. The unused code only lets you use 55 extra characters, and there is no unused code for the about me.
________________________________
From: ShluffyMonster ***@***.***>
Sent: Wednesday, May 12, 2021 11:31:44 AM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Add more character space to about me as well (#2479)


Is your feature request related to a problem? Please describe.

I run out of space there as well as before I enabled the addon for an extra 55 characters for what I'm working on

Describe the solution you'd like

do the same for about me, possibly an option under that addon

Describe alternatives you've considered

n/a

Additional context

Possibly make it more then 55 characters allowed. Is there a soecific reason 55 was picked?
