### ISSUE TITLE
Custom CSS Addon

### ISSUE THREAD

**Issue by CodeLikeCrazE** [ScratchAddons/ScratchAddons#2506]
**Describe the new addon**

My idea for this addon is just an addon titled "Custom CSS", which allows you to paste in custom CSS, which would apply to the editor. It might also have a custom JS feature built in. There could be a few little buttons allowing you to apply some pre made styles.

**Comment by RedGuy12** [comment]
use stylus and tampermonkey

**Comment by WorldLanguages** [comment]
Yeah, premade styles can basically be addons
