### ISSUE TITLE
Some studio popups have no text and are half nothing

### ISSUE THREAD

**Issue by Endermaster3690** [ScratchAddons/ScratchAddons#2509]
**Describe the bug**

title i guess

**To Reproduce**

1. Go to a studio
2. Click on Curators then click invite
3. Invite someone successfully
4. See error in popup

**Expected behavior**

title

**Screenshots**

![popup](https://user-images.githubusercontent.com/80355301/118402292-e2843c80-b62e-11eb-89bf-380498b1019f.png)

**Device (please complete the following information):**

- OS: [e.g. iOS] windows 10
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22] of what?

**Additional context**

no

**Comment by RedGuy12** [comment]
Scratch bug, not SA bug

**Comment by Endermaster3690** [comment]
> Scratch bug, not SA bug

aight
