### ISSUE TITLE
Automatically update themes (no refresh needed)

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#252]
Whenever we detect a settings/enabled state change in a theme addon, we should re-check what styles should be applied, and if there's a difference, remove all current styles and then readd them (we can't just add or remove a single style without breaking the "relevance score" in CSS except specific situations, like simply disabling a theme).

**Comment by Explosion-Scratch** [comment]
Ooh, that'd be nice. I think stylus does this already.

**Comment by WorldLanguages** [comment]
This would also make userstyle react to URL changes, like going to editor mode inside a project. See #322
