### ISSUE TITLE
Infinite scrolling in Explore

### ISSUE THREAD

**Issue by qbjl** [ScratchAddons/ScratchAddons#2520]
### Is your request related to a problem? Please describe.

Yes! Have you ever just went to a project on the explore tab, then go back to see you're at the top of the page again? It sucks for me.

### Describe the solution you'd like

Infinite scrolling on the Explore page to avoid losing where you were on the page.

### Describe alternatives you've considered

n/a

### Additional context

I checked and this shouldn't be a dupe. ✌️

**Comment by WorldLanguages** [comment]
I'll work on this after #5419.
