### ISSUE TITLE
Capture event listeners in tab.traps

### ISSUE THREAD

**Issue by ErrorGamer2000** [ScratchAddons/ScratchAddons#2521]
### Is your request related to a problem? Please describe.

Not related to any issue so far (as far as I know).

### Describe the solution you'd like

I have already drafted a working piece code for this, using the same sort of method as the extension uses to get the vm:

```js

//Works
const listeners = (__scratchAddonsTraps.eventListeners = new Array);

const oldAddListener = Element.prototype.addEventListener;
Element.prototype.addEventListener = function (...args) {
  listeners.push({
    event: args[0],
    callback: args[1],
    options: args[2],
    element: this,
  });

  oldAddListener.bind(this)(...args);
};

//Also works now...
const oldRemoveListener = Element.prototype.removeEventListener;
Element.prototype.removeEventListener = function (...args) {
  let listener = listeners.splice(
    listeners.indexOf(
      listeners.filter(
        (listener) =>
          listener.event === args[0] &&
          listener.callback === args[1] &&
          (typeof args[2] === "object" && typeof listener.options === "object" ? JSON.stringify(args[2]) === JSON.stringify(listener.options) : args[2] === listener.options) &&
          this === listener.element
      )[0]
    ),
    1
  );

  oldRemoveListener.bind(this)(...args);
};
``` 

This will allow us to manually remove and/or use listeners on elements that are usually hidden. For example the file uploads. They have change listeners on them, but they run before the event can be prevented keeping us from changing them. If, for example, I wanted to change how files were uploaded (I am working on an addon that will allow images to be uploaded at full quality, but I need this) I would need to remove the current listener and add a new one that would trigger the other listener after I have manipulated the file. With this, we could remove the event listener (because we would have the function used), and be able to re-assign it to a different, custom, event.

### Describe alternatives you've considered

I haven't found any alternatives yet...

### Additional context

Api suggestions:

- `addon.tab.traps.getListenersForElement(selector)`
  - Example method:
```js
getListenersForElement = (selectorOrElement) =>
  __scratchAddonsTraps.eventListeners.filter(
    typeof selectorOrElement === "string" ?
      (listener) => listener.element === document.querySelector(selectorOrElement) :
      (listener) => listener.element === selectorOrElement
  )
```
  - Example use:
```js
const listeners = addon.tab.traps.getListenersForElement('input[type="file"]');

const listeners = addon.tab.traps.getListenersForElement(document.querySelectorAll('input[type="file"]')[0]);
```

**Comment by ErrorGamer2000** [comment]
I have tested it, and It works. Should I make a PR?

**Comment by RedGuy12** [comment]
maybe? it might be better to wait for approval from wl first so you don;t waste your time writing the code if it's never going to be implemented.

or if you already wrote the code, what do you have to loose?

**Comment by ErrorGamer2000** [comment]
I already wrote and tested it, I am updating a branch of my fork now.

**Comment by ErrorGamer2000** [comment]
Although, I am unsure as to whether I should go ahead and expand the traps api?

**Comment by apple502j** [comment]
Nope
