### ISSUE TITLE
2D Color Picker addon still showing saturation slider

### ISSUE THREAD

**Issue by Mr-Anonymous75** [ScratchAddons/ScratchAddons#2533]
### Description

The color picker shows the saturation slider, even though the 2d picker is already there. 
But that doesn't always happen - the bug sometimes magically fixes itself, but comes back later.

### Repoduction steps

**Warning:** this might not always work.

1. Open the SVE
2. Open the color picker
3. See both saturation slider and 2d picker.

### Expected behaviour

The saturation slider should not be visible, and there should be text saying "**Shade** <Saturation>, <Brightness>".

### Actual behaviour

The saturation slider is visible and interactive, even though the 2d picker is visible. There's also no "**Shade** X, X" text, but instead just the saturation value above its slider - so no way to know what the brightness is. 
However, this does not always happen - the bug sometimes magically fixes itself, but usually comes back later. 

### Screenshots

![screenshot](https://user-images.githubusercontent.com/73294041/118746610-2ae16b80-b876-11eb-89b5-0f67810d9dba.png)

### Enviroment

- Browser: Microsoft Edge Beta 91.0.864.27
- Scratch Addons version: 1.14.3
- Operating system: Windows 10 20H2

**Comment by xItzDiamondx** [comment]
I don't see it.
![Screenshot 2021-05-19 9 22 26 AM](https://user-images.githubusercontent.com/81493936/118829461-c200f000-b883-11eb-8a3b-4346733a8c17.png)
I tested on ChromeOS Turbowarp. Don't see it.

**Comment by Mr-Anonymous75** [comment]
> I don't see it.
> ![Screenshot 2021-05-19 9 22 26 AM](https://user-images.githubusercontent.com/81493936/118829461-c200f000-b883-11eb-8a3b-4346733a8c17.png)
> I tested on ChromeOS Turbowarp. Don't see it.

Once again, the bug does not always happen. It's there sometime, but not some other time.

**Comment by xItzDiamondx** [comment]
Sorry, I didn't read that.

**Comment by TheColaber** [comment]
@Mr-Anonymous75 is there a reason why this was closed? Was the problem solved?

**Comment by Mr-Anonymous75** [comment]
> @Mr-Anonymous75 is there a reason why this was closed? Was the problem solved?

Yeah, I don't have the problem anymore. If it happens again, I'll reopen it.
