### ISSUE TITLE
color option for options

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#254]
**Is your feature request related to a problem? Please describe.**

colour picker in add-on option manifest

**Describe the solution you'd like**

colour picker in addon option manifest

**Describe alternatives you've considered**

no

**Additional context**

colour picker, in addon option manifest

**Comment by WorldLanguages** [comment]
please fix the typo in the title for this to be considered

**Comment by JeffaloBob** [comment]
> please fix the typo in the title for this to be considered

no

**Comment by BoomerScratch** [comment]
```html
<input type="color"/>
```

**Comment by WorldLanguages** [comment]
Oh wow didn't know there was a native input type for that.

**Comment by YOYITsM3M8** [comment]
Some people spell "color" like "colour"

**Comment by GrahamSH-LLK** [comment]
Is anyone working on this?

**Comment by WorldLanguages** [comment]
I don't think so

**Comment by easrng** [comment]
Not a typo

**Comment by WorldLanguages** [comment]
@easrng It was a joke, sorry :c
