### ISSUE TITLE
editor-theme3 colors report bubbles

### ISSUE THREAD

**Issue by CST1229** [ScratchAddons/ScratchAddons#2553]
### Description

When editor-theme3 is enabled (colors don't matter), report bubbles (the speech bubbles that appear when clicking on a reporter block) get colored to the last block dropdown you clicked. If you didn't click any, the bubble will remain white.

### Repoduction steps

1. Enable editor-theme3 (Customizable block colors) and open editor
2. Click any block dropdown
3. Click any reporter

### Expected behaviour

The report bubble should stay white.

### Actual behaviour

The bubble is colored.

### Screenshots

Before clicking any dropdown: 
![Before dropdowns](https://user-images.githubusercontent.com/68464103/119159192-4b1c5080-ba57-11eb-9c49-3fa77f3b8b38.png)
After clicking dropdowns:
![Looks](https://user-images.githubusercontent.com/68464103/119159248-553e4f00-ba57-11eb-89f1-87c1d4db8e89.png)![Motion](https://user-images.githubusercontent.com/68464103/119159294-5d968a00-ba57-11eb-8a6a-263c08eb5565.png)![Events](https://user-images.githubusercontent.com/68464103/119159338-671ff200-ba57-11eb-9824-9d930899c384.png)![Extension](https://user-images.githubusercontent.com/68464103/119159365-6edf9680-ba57-11eb-870f-36fdc793863d.png)

### Environment

- Browser: Firefox 88.0
- Scratch Addons version: v1.14.3
- Operating system: Windows 10
- My browser / operating system: Windows NT 10.0, Firefox 88.0, No Flash version detected

### Additional context

Was able to reproduce with only editor-theme3 enabled.
Probably related to the passive darkening of square dropdowns.

**Comment by ErrorGamer2000** [comment]
I have noticed this as well...

**Comment by RedGuy12** [comment]
It might be nice for the addon to color the bubbles the color of the block.

**Comment by ErrorGamer2000** [comment]
Probably context menus. And it is all the wrong color for operators.

**Comment by spaciousmind** [comment]
oh yeah I'm experiencing this too.

since I'm using the dark theme too If the reporter block text was white it wouldn't really be an issue for me. but as it is they're barely readable.

**Comment by CST1229** [comment]
Looking at the source code, this is actually caused by the recoloring of the dropdown menus themselves (which are needed because they are the color of the block).
