### ISSUE TITLE
Music blocks not working in Chrome MacOS (pause addon)

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#2557]
### Description

Often projects with music blocks do not play any sound. In order to make them work I have to disable scratch addons, re-enable scratch addons and then reload the project.

### Reproduction steps

1.  load https://scratch.mit.edu/projects/534055678
2.  click green flag. no sound at all
3.  disable scratch addons
4.  re-enable scratch addons
5.  reload project

### Expected behaviour

audible sound

### Actual behaviour

no sound at all

### Environment

- Browser: Chrome 90.0.4430.212
- Scratch Addons version: 1.14.3
- Operating system: MacOS Macintosh X 10.15.7

**Comment by apple502j** [comment]
What addons do you use?

**Comment by sfederici** [comment]
A lot (48) of them

**Comment by apple502j** [comment]
Are you using pause addon?

**Comment by sfederici** [comment]
Yes

**Comment by apple502j** [comment]
What happens when that is disabled? Pausing a project currently stops all sounds.

**Comment by sfederici** [comment]
I tried reloading the project page (with the pause addon enabled) and the sound didn't work. Disabling the addon made the sound work (without reloading the project page). After that I can re-enable the addon and the sound still works

**Comment by lisa-wolfgang** [comment]
I was unable to get the pause addon to stop the sound on that project without actually pressing the pause button. I loaded the page with it enabled and with it disabled, and I toggled it multiple times while the project was running, but I wasn't able to repro with that addon.

**Comment by sfederici** [comment]
Do you have a Windows PC? Mine is macOS

**Comment by lisa-wolfgang** [comment]
Yes, I am using Windows -- this might be a Mac-specific issue?

**Comment by GarboMuffin** [comment]
I cannot reproduce this on "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" with every addon enabled

Consider exporting your addon settings and attaching here, maybe?

**Comment by lisa-wolfgang** [comment]
@sfederici Have you tried temporarily disabling all of your other extensions?
If that's too cumbersome, you could install Scratch Addons on a new Chrome profile and test it.

**Comment by WorldLanguages** [comment]
Confirmed by a Scratcher through Feedback

**Comment by sfederici** [comment]
The project still doesn't work (even with the pause addon disabled). I can't hear any sound. NOTE: other websites, e.g. youtube, regularly play sounds in other tabs of the same chrome window

**Comment by sfederici** [comment]
But maybe the fix will be in the next release? :-)

**Comment by RedGuy12** [comment]
it will be on 1.17.0.

**Comment by TheColaber** [comment]
@RedGuy12 Why not v1.16.5?

**Comment by RedGuy12** [comment]
> @RedGuy12 Why not v1.16.5?

![image](https://user-images.githubusercontent.com/61329810/124674646-c3609900-de80-11eb-8d84-52adabe0d4af.png)

**Comment by WorldLanguages** [comment]
This was cherrypicked into v1.16.5 too

**Comment by sfederici** [comment]
Sorry I couldn't test it before. Now it works for me
