### ISSUE TITLE
[Question] What the heck is this checkbox?! lol

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#257]
What is the checkbox on the top at the far right? lol
![image](https://user-images.githubusercontent.com/61319150/92761594-780c5580-f357-11ea-9d1d-bbc8d77ac046.png)

**Comment by BoomerScratch** [comment]
Probably the text doesn't show up :lol:

**Comment by Explosion-Scratch** [comment]
> Probably the text doesn't show up :lol:

What does the text say then? :P

**Comment by JeffaloBob** [comment]
replace stage?

**Comment by Explosion-Scratch** [comment]
> replace stage?

Oh, lol, the checkboxes are on the _right_ of the text. I for some reason thought it was the other way around.

**Comment by JeffaloBob** [comment]
perhaps this is a UX issue

**Comment by WorldLanguages** [comment]
Lol we should probably center the text

**Comment by WorldLanguages** [comment]
(or align it to the right)

**Comment by towerofnix** [comment]
Perhaps a light background transition could be applied when hovering over individual option tiles?
