### ISSUE TITLE
Addon settings preview

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2570]
Related: #475

### Is your request related to a problem? Please describe.

Editor dark mode allows the user to customize colors, but it isn't always obvious which color does what. Website dark mode will have a similar feature in the future.

### Describe the solution you'd like

An option in `addon.json` to specify a Vue component displayed on the settings page as a preview of the settings. Changing a setting would update the preview, and clicking an area in the preview would highlight the setting that affects it.

**Comment by WorldLanguages** [comment]
Epic idea.

**Comment by WorldLanguages** [comment]
@mxmou Not sure if will be ready for this release, but what properties should the component receive? I'd say:
- `hoveredSettingId` (string or null)
- `settings` (key: setting id, value: setting value)
- `manifest` (read only)

And how would it work CSS wise? What will be the max size for the component div? What CSS should we apply to the wrapper div on <addon-body>?

**Comment by WorldLanguages** [comment]
Lol no, backlog
