### ISSUE TITLE
Change Default Sprites

### ISSUE THREAD

**Issue by Vivaan-S** [ScratchAddons/ScratchAddons#2573]
### Is your request related to a problem? Please describe.

My request is not related to a problem

### Describe the solution you'd like

Create a new addon to change the default loaded sprite to something else other than the cat. I want that when the editor loads, it doesn't show the cat, but my own `.sprite3` file

### Describe alternatives you've considered
None

### Additional context
None

**Comment by mxmou** [comment]
I like this idea. Related: #1975, particularly https://github.com/ScratchAddons/ScratchAddons/issues/1975#issuecomment-808432709

**Comment by ErrorGamer2000** [comment]
I like it too. It will probably be pretty hard though.

**Comment by Vivaan-S** [comment]
I don't know. It seems like a good idea to me. You could replace the json data of when a new project was created, as mentioned in #1975
