### ISSUE TITLE
Don't refer to comments as posts

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2583]
### Is your request related to a problem? Please describe.

An error message in Scratch Messaging says "You are posting too quickly. Please wait longer between posts." The word "posts" should only be used for forum posts.

### Describe the solution you'd like

Change it to "Please wait longer between comments."

**Comment by WorldLanguages** [comment]
Keep in mind I think that message was taken from vanilla Scratch, word by word

**Comment by mxmou** [comment]
@WorldLanguages The vanilla message uses the words "comment" and "post" in a strange way: "Woah, seems like you're commenting really quickly. Please wait longer between posts."
