### ISSUE TITLE
Studio tools bug on new studio page

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2585]
### Description

When switching from Curators to another tab on the new studio page, the UI added by `studio-tools` doesn't disappear.

### Repoduction steps

1. Open the new studio page (in a local scratch-www build - make the necessary changes to run Scratch Addons there)
3. Switch to the Curators tab
4. Switch to any other tab
5. Switch back to the Curators tab

### Expected behaviour

When switching to another tab, the "promote curators" and "remove curators" inputs would disappear. When switching back to Curators, they would appear again.

### Actual behaviour

When switching to another tab, they don't disappear. When switching back to Curators, they're duplicated.

### Additional context

Possibly caused by a change in scratch-www.

**Comment by mxmou** [comment]
This is happening again, but only with Remove curators.

**Comment by WorldLanguages** [comment]
We probably want a v1.16.4 before July 6th? :P
