### ISSUE TITLE
Improving SVG/PNG export menu

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#2594]
### Reproduction steps

Right-click in script area when the area is empty

### Expected behaviour

The "export blocks as SVG/PNG" options don't show up in the right-click menu

### Actual behaviour

The "export blocks as SVG/PNG" options show up in the right-click menu

### Environment

- Browser: Chrome 90
- Scratch Addons version: 1.14.3
- Operating system: macOS 10.15.7

**Comment by TheColaber** [comment]
#1754 basically resolves this since it moves all block related items to only appear when one right clicks on blocks

**Comment by sfederici** [comment]
I see. If I right-click a block and I select "export this block as..." I would expect only the block I right-clicked to be exported (not all the blocks in the sequence it belongs to). If I right-click a sequence of blocks and I select "export all as..." I would expect only the blocks in the sequence I right-clicked to be exported (not all the blocks in all sequences in the script area). I guess the correct options for me should be:

- export this block
- export this script
- export all scripts

**Comment by mxmou** [comment]
> #1754 basically resolves this since it moves all block related items to only appear when one right clicks on blocks

"Export all as ..." options should also appear when right clicking elsewhere in the workspace.

**Comment by TheColaber** [comment]
Right now, how my PR has it as:

**Workspace Options**
Export All as PNG
Export All as SVG
**Blocks Options**
Export Block as PNG
Export Block as SVG

When it says export block, it really means just that block. So if you have a stack like
```
move (10) steps
turn (5) degrees
```
and you right-click on the `move steps` block, only the `move steps` block will get exported.

I could add more options tho. These options were based on the old addon
