### ISSUE TITLE
(Forum material icons) dropdown going over image

### ISSUE THREAD

**Issue by Shluffy** [ScratchAddons/ScratchAddons#2595]
### Description

styling has a dropdown  arrow going over the image (just slightly) 
![Screenshot 2021-05-24 2 20 33 PM](https://user-images.githubusercontent.com/81823039/119390649-595aae80-bc9b-11eb-8810-4096506371cd.png)

### Repoduction steps
go to an open forums topic

### Expected behaviour
css to be clean

### Actual behaviour

goes slightly over onto the other pic
### Screenshots

![Screenshot 2021-05-24 2 20 33 PM](https://user-images.githubusercontent.com/81823039/119390758-7e4f2180-bc9b-11eb-9d3d-308e093eff41.png)

### Environment

ChromeOS 13904.37.0, Chrome 91.0.4472.66

### Additional context

sorry if this is the wrong type.

**Comment by RedGuy12** [comment]
Cc @Secret-chest

**Comment by mxmou** [comment]
This is actually caused by website dark mode.

**Comment by Shluffy** [comment]
> This is actually caused by website dark mode.

how though? I don't use dark more (on scratch).

**Comment by mxmou** [comment]
@Shluffy If so, it's Scratch 2.0 → 3.0's fault.

**Comment by Shluffy** [comment]
really?
![Screenshot 2021-05-24 3 13 10 PM](https://user-images.githubusercontent.com/81823039/119396248-9e361380-bca2-11eb-9967-0387399c1556.png)
![Screenshot 2021-05-24 3 13 16 PM](https://user-images.githubusercontent.com/81823039/119396260-a2623100-bca2-11eb-89c7-4facd24b1936.png)
![Screenshot 2021-05-24 3 13 25 PM](https://user-images.githubusercontent.com/81823039/119396278-a8f0a880-bca2-11eb-939b-fea31a119940.png)
@mxmou i tried turning that off and it is still happening

**Comment by RedGuy12** [comment]
Try with only forum icons on
________________________________

**Comment by Shluffy** [comment]
> Try with only forum icons on

can still reproduce

**Comment by Secret-chest** [comment]
On my computer I can't repro...

**Comment by Shluffy** [comment]
> On my computer I can't repro...

What browser and stuff like that are you on?

**Comment by Shluffy** [comment]
@Secret-chest what are we doing with this? what browser and os are you on? it may be platform or screen size specific

**Comment by Secret-chest** [comment]
@Shluffy I noticed it too now. I will try to fix this
