### ISSUE TITLE
Millions Of Userscripts To Add

### ISSUE THREAD

**Issue by Ani-Xan** [ScratchAddons/ScratchAddons#26]
Hello! I am very interested in Scratch extensions and userscripts; I use them on a daily basis. Here are some a userscripts you guys should add: 

https://github.com/mxmou/exactcount (Is there a way to show comment, curators, and managers too?)
https://github.com/WorldLanguages/studioToolsBookmarklet (This is amazing.) 
https://github.com/WorldLanguages/animatedThumbnailsBookmarklet (You should add a button on the scratch project sites themselves to add a new thumbnail. Also add a way to change thumbnails via MyStuff page.)
https://github.com/WorldLanguages/FollowersNumberEnabler (Just amazing, maybe add a # of favorites, comments, curated studios & following studios.)
https://github.com/WorldLanguages/isOnlinev2 (When I used this, it led me to a porn site. Make a working version of this that will also show if the person is online or not-found to the left of the follower button-, as long as they also use the add-on. ) 

I know it's a lot and some of this might not be possible, but these would be amazing. 
(Can't wait to test out the addon on chrome when it's ready! If you guys have a beta, let me in plz. 😀

**Comment by Ani-Xan** [comment]
Also, check out https://github.com/mxmou/customize-scratch#watch-youtube-videos-on-scratch-in-full-screen and maybe this amazing users style: https://github.com/mxmou/customize-scratch#scratch-30-look-for-old-parts-of-the-website (Although, it doesn't match the whole Scratch 3.0 new look and could be improved. @scratchaddons)
Look at some of these! https://github.com/forkphorus/cat-plus#readme (I like [searchable dropdown](https://github.com/forkphorus/cat-plus/raw/master/searchable-dropdowns.user.js), [unrounded stage](https://github.com/forkphorus/cat-plus/raw/master/unrounded-stage.user.js) (I wish I could toggle this on and off more easily), [Better context menus](https://github.com/forkphorus/cat-plus/raw/master/better-context-menus.user.js) (LOVE THIS), [Extra metadata](https://github.com/forkphorus/cat-plus/raw/master/extra-metadata.user.js) (Although I think this effects load speeds), and the AMAZING [Make projects shared](https://github.com/forkphorus/cat-plus/raw/master/make-projects-shared.user.js), which lets you bypass sharing restrictions.

**Comment by Ani-Xan** [comment]
### Here are a few more: 
@BoomerScratch's [userstyles](https://github.com/BoomerScratch/userstyles)
https://github.com/BoomerScratch/userstyles#scratch-forum-scrollbars 
https://github.com/BoomerScratch/userstyles#youtube-video-ad-hider 
https://github.com/BoomerScratch/userstyles#scratch-forums-quote--code-beautifier 
Please also make a better version of [THIS ](https://github.com/Hans5958/scratch-userscripts#follow-dashboard)"follow dashboard" by @Hans5958. I do not know how to use it and this could be really helpful for "follow accounts".

**Comment by Ani-Xan** [comment]
Could this also be incorporated into the scratch forum page (and maybe all the scratch wiki pages)? (This can use Scratch 3.0 blocks! YES!) https://github.com/scratchblocks/scratchblocks 
Stare at what I made: (Also [here](http://scratchblocks.github.io/#?style=scratch3&script=OMG%20WOW%20A%20CAT%20BLOCK%3A%3A%20%23ff5959%20cat))
![CAT BLOCK](https://user-images.githubusercontent.com/57809064/89074656-90895900-d331-11ea-9b30-6acbf5477687.png)
I figured out how to do this [here](https://en.scratch-wiki.info/wiki/Block_Plugin).

**Comment by Ani-Xan** [comment]
Could I also join the organization? (And repo?) @ScratchAddons

**Comment by Hans5958** [comment]
Hey, guy that got pinged here. Keep in mind that my Scratch userscripts are now located on [the userscripts repo](https://github.com/Hans5958/userscripts/tree/master/Scratch).

Also, speaking about this project, does [Mega Scratch Userscript](https://github.com/MegaScratchUserscript/Mega-Scratch-Userscript) already exists with the exact reason?

**Comment by Explosion-Scratch** [comment]
@Hans5958 Mega Scratch Userscript no longer works with 3.0. We are working on creating the equivalent for 3.0

**Comment by WorldLanguages** [comment]
Thanks so much for all these suggestions. I'll continue development soon.

**Comment by WorldLanguages** [comment]
I'm aware I am not very consistent but be sure this won't become a dead project lol

**Comment by Ani-Xan** [comment]
> I'm aware I am not very consistent but be sure this won't become a dead project lol

Do you mean that this will stay up to date, @WorldLanguages? (And also, who should I talk to in order to join the @ScratchAddons organization?

**Comment by Hans5958** [comment]
> 
> 
> Mega Scratch Userscript no longer works with 3.0. We are working on creating the equivalent for 3.0

I understand, but this seems like a brand new project than a fork. Anyways, godspeed with the project.

Also, is there an relevant Discord server/AT thread/project/wherever the discussion take place for this project?

**Comment by Explosion-Scratch** [comment]
@Hans5958 No, there is no Discord or AT topic for this, scratch dosen't allow talking about userscripts anynore and I don't know who has/iss allowed to have discord (not me lol)

**Comment by Hans5958** [comment]
> No, there is no Discord or AT topic for this, scratch dosen't allow talking about userscripts anynore and I don't know who has/iss allowed to have discord (not me lol)

Understandable, but don't it's just weird that this project came out of nowhere without any annoucement or some kind of discussion from it? I don't know. Probably because I am quite away from Scratch so I must missed something.

Also, not sure if this is the right place to talk about this. So sorry for other participants of this issue.

**Comment by WorldLanguages** [comment]
@Hans5958 The discussion started here: https://github.com/mxmou/customize-scratch/issues/14
As Explosion said, this can't be talked on Scratch, and not everyone can or wants to use Discord.
This means we tolerate some offtopic talking like this one since this is the only place where we can talk lol.

**Comment by Explosion-Scratch** [comment]
@WorldLanguages, thanks for linking that! I wish scratch would allow topics about userscripts and userstyles

**Comment by Ani-Xan** [comment]
@Explosion-Scratch
> I wish scratch would allow topics about userscripts and userstyles

I totally agree. Do you know the exact reason they're not allowed?

**Comment by Explosion-Scratch** [comment]
@Ani-Xan. Possibly malicious code and
stylus had a privacy issue.

**Comment by Explosion-Scratch** [comment]
Also to join @ScratchAddons ask WorldLanguages, they own it.

**Comment by Hans5958** [comment]
> 
> 
> @Hans5958 The discussion started here: [mxmou/customize-scratch#14](https://github.com/mxmou/customize-scratch/issues/14)
> As Explosion said, this can't be talked on Scratch, and not everyone can or wants to use Discord.
> This means we tolerate some offtopic talking like this one since this is the only place where we can talk lol.

Appreciate the linked issue. I understand it's a long long way before ST decided to block userscripts and userstyles, because I also make one. It's quite dissapointing.

Speaking about this org, may I join it?

> > I wish scratch would allow topics about userscripts and userstyles
> 
> I totally agree. Do you know the exact reason they're not allowed?

For safety reasons, of course. ST didn't want children to aimlessly install extensions/userscripts that the don't know, and bad stuff happens, either from ST got complaints from their parents, or the users itself got their privacy breached, even it's an extremely rare case.

https://scratch.mit.edu/discuss/topic/284272/

**Comment by Ani-Xan** [comment]
> Speaking about this org, may I join it?

Ask @WorldLanguages. Their email is on their GitHub profile. (WorldLanguages is the creator of ScratchAddons)

**Comment by Hans5958** [comment]
> 
> 
> > Speaking about this org, may I join it?
> 
> Ask @WorldLanguages. Their email is on their GitHub profile. (WorldLanguages is the creator of ScratchAddons)

I'm asking on this issue, nothing's wrong with that, right?

**Comment by Ani-Xan** [comment]
> > > Speaking about this org, may I join it?
> > 
> > 
> > Ask @WorldLanguages. Their email is on their GitHub profile. (WorldLanguages is the creator of ScratchAddons)
> 
> I'm asking on this issue, nothing's wrong with that, right?

Nothing wrong, just stating what I did.

**Comment by Hans5958** [comment]
> 
> 
> > > > Speaking about this org, may I join it?
> > > 
> > > 
> > > Ask @WorldLanguages. Their email is on their GitHub profile. (WorldLanguages is the creator of ScratchAddons)
> > 
> > 
> > I'm asking on this issue, nothing's wrong with that, right?
> 
> Nothing wrong, just stating what I did.

I see. I could also contact him on Discord, and maybe Twitter, if I want.

**Comment by Ani-Xan** [comment]
> I see. I could also contact him on Discord, and maybe Twitter if I want.

Correct. 🎉 Do you know World_Languages' Discord?

**Comment by BoomerScratch** [comment]
There are a lot more:
https://github.com/ScratchAddons/ScratchAddons/issues/6#issuecomment-664999449

**Comment by BoomerScratch** [comment]
@Ani-Xan Make sure userscripts are made for Scratch!
For example, my YouTube video ad hider is made for YouTube, but not for Scratch.

**Comment by Ani-Xan** [comment]
> There are a lot more:
> [#6 (comment)](https://github.com/ScratchAddons/ScratchAddons/issues/6#issuecomment-664999449)

Already saw those. 😊 


> @Ani-Xan Make sure userscripts are made for Scratch!
> For example, my YouTube video ad hider is made for YouTube, but not for Scratch.

@BoomerScratch It would still be helpful, right? We could those so they only affect scratch.

**Comment by Hans5958** [comment]
> 
> 
> > I see. I could also contact him on Discord, and maybe Twitter if I want.
> 
> Correct. 🎉 Do you know World_Languages' Discord?

Ask him. Didn't know if he wants me to share it.

**Comment by Ani-Xan** [comment]
> Ask him. Didn't know if he wants me to share it.

Okay, @Hans5958. I hear you.

**Comment by Hans5958** [comment]
@tb148 @BoomerScratch @WorldLanguages Pinging some active maintainers, can I got added to the org?

**Comment by WorldLanguages** [comment]
@Hans5958 imo we're enough already. As long as one of us can review pull requests we're fine

**Comment by Hans5958** [comment]
Ah, bummer.

**Comment by BoomerScratch** [comment]
@Explosion-Scratch Stylus did not have privacy issues; stylish had (it was probably spyware then :fearful:).

> > I wish scratch would allow topics about userscripts and userstyles
> 
> I totally agree.

Same lol

**Comment by WorldLanguages** [comment]
I think I made a new issue for each one of the listed here (except userstyles, which we'll look at later, probably after the first release). Closing, then. Please tell me if I forgot to make issues for any of the mentioned userscripts.

**Comment by WorldLanguages** [comment]
@Hans5958 I didn't test each one of your userscripts because some appear to be old, if you feel that any of them are still useful and still work, feel free to create an issue for them. The linkify one looks good.

**Comment by GrahamSH-LLK** [comment]
> I'm aware I am not very consistent but be sure this won't become a dead project lol

@WorldLanguages Still not dead!
