### ISSUE TITLE
addon.tab.direction

### ISSUE THREAD

**Issue by GarboMuffin** [ScratchAddons/ScratchAddons#2601]
I'm proposing a new API, `addon.tab.direction`, that returns either "ltr" or "rtl"

It would replace code like:

https://github.com/ScratchAddons/ScratchAddons/blob/34c8290463ab792691f0599aa50b7dc7f760c840/addons/mediarecorder/userscript.js#L24

Main motivation for this being in addon.tab is that there is no `<div class="gui">` in TurboWarp and I don't want to be forced to constantly patch addons to fix how they detect direction

**Comment by TheColaber** [comment]
Editor addons, can at least use `Blockly.getMainWorkspace().RTL`

**Comment by GarboMuffin** [comment]
That's fine too.

All I really want is that addons don't try to read direction from `<div class="gui">`

**Comment by mxmou** [comment]
Until either the ST adds RTL support to the website or we make an addon for that, this is only necessary for editor addons.

**Comment by WorldLanguages** [comment]
@GarboMuffin How should we make this work here, without turning `addon.tab.direction` into a promise? Any redux tricks to get the dir without waiting for the .gui element? `addon.auth.scratchLang === "ar" || /* etc */`?

![image](https://user-images.githubusercontent.com/17484114/120111453-6880a700-c148-11eb-8768-67c604a2808a.png)

**Comment by GarboMuffin** [comment]
You could wait for something like the stage to exist in the DOM first, then redux will definitely be available

For the devtools extension I imagine you'll probably want to implement `addon.tab.direction` using DOM because you don't have redux access there
