### ISSUE TITLE
Weird Messages Color

### ISSUE THREAD

**Issue by 22yeetz22** [ScratchAddons/ScratchAddons#2613]
### Is your request related to a problem? Please describe.

No, but the new color of the number of messages you have is really weird.

### Describe the solution you'd like

Let users customize it in the "more settings" section.

### Describe alternatives you've considered

Go back to the old color

### Additional context

The new, weird color:
![Weird Color ScratchAddons](https://user-images.githubusercontent.com/74276537/119556543-c7b77380-bd64-11eb-8918-6e23317334d7.png)

**Comment by RedGuy12** [comment]
You CAN change it in the addon settings.

**Comment by WorldLanguages** [comment]
Did you read the update notification...?
