### ISSUE TITLE
More clear warning modals

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#2618]
The implementation of the warning modal when turning on the addons seems incomplete. Users are shown warning without clear indication of what is warned.

I have suggested before to do it so all the notices and warnings will appear in the same modal, so that's what I'm suggesting again.

Also, yeah, the "Dangerous" tag seemed ambiguous. What exactly is it? Why is that? What should I know?

**Comment by lisa-wolfgang** [comment]
I think https://github.com/ScratchAddons/ScratchAddons/issues/1861 is related

**Comment by WorldLanguages** [comment]
@Hans5958 Could you clarify the suggestion?

**Comment by Hans5958** [comment]
> I think https://github.com/ScratchAddons/ScratchAddons/issues/1861 is where you made that suggestion before.

Oh, yeah. I might close this as duplicate then? Sorry.

**Comment by DNin01** [comment]
Not totally sure, but I think this request is a little narrower than #1861, as it is specifically about the confirmation message still used for dangerous addons today. I'm going to reopen this so I have something to link to #9070. It directly resolves this issue.

**Comment by mxmou** [comment]
> Not totally sure, but I think this request is a little narrower than [#1861](https://github.com/ScratchAddons/ScratchAddons/issues/1861), as it is specifically about the confirmation message still used for dangerous addons today.

#1861 was made before the current confirmation existed. Adding the confirmation didn't resolve it fully, but your PR will.
