### ISSUE TITLE
Removing addons/addons.json?

### ISSUE THREAD

**Issue by tb148** [ScratchAddons/ScratchAddons#262]
This file caused a lot of merge conflicts, and it might cause more, such as in #209.
However whether or not to do so is a question.
We can generate the list automatically.

**Comment by GrahamSH-LLK** [comment]
Yeah! That would be great!

**Comment by GrahamSH-LLK** [comment]
If it can do it automatically, we don't need the file at all!

**Comment by towerofnix** [comment]
Keep in mind that addons.json is currently used as a descriptor for the *order* addons are evaluated, which per the note at the top of the file...

```json
[
  "// Note: these addons need this exact order to work properly,",
  "// because the first in the list gets their CSS injected first,",
  "// and so on, and we want dark mode to make other addons dark.",
  "editor-searchable-dropdowns",
  "editor-devtools",
  "editor-dark-mode",
  "editor-colored-context-menus",
  "// ..."
]
```

...does in some cases need to be specified with a particular order.

The rest of the addons don't apparently care what order they're applied, and could be loaded automatically, but those which must be loaded in a particular order should still be specified by hand.

Maybe addons.json could be changed to a format like this?

```json
{
  "loadFirst": [
    "editor-searchable-dropdowns",
    "editor-devtools",
    "editor-dark-mode",
    "editor-colored-context-menus"
  ]
}
```

The rest would be loaded automatically in a nondeterminate (in practice probably by ID) order.

(This is only possible if the addons directory *can* be automatically parsed, mind.)

**Comment by tb148** [comment]
I think we can add a `priority` settings for each addon.

**Comment by towerofnix** [comment]
`priority` is a numeric analogue *for* the order, though, and then you run into effectively the same issues that you do with CSS `z-index`: you have to keep track of all those priority values somewhere, or else you're going to run into accidentally ordering them in an unintentional way. Since we're dealing with a single one-dimensional list (not the multi-layer shenanigans of CSS/HTML), I think keeping a plain array is the most reliable and straightforward way to organize them.

**Comment by Platinum-Phoenix** [comment]
Maybe as @GrahamSH-LLK said, the list can be generated automatically.

Then, the user could have the option to arrange which add-ons should load first.

**Comment by WorldLanguages** [comment]
@towerofnix pretty much said what I was thinking, I did consider having priority for stylesheets but you have the same issue as `z-index`, you need to keep track of the numbers in different files.
I'd prefer only having to specify the addons that need a particular order and find the others dynamically but that's not possible from an extension.
Tbh automating it probably simply moves the problem away. Resolving conflicts in a 1 dimensional array isn't really problematic. And then we need to deal with `priority` madness.

**Comment by WorldLanguages** [comment]
> If it can do it automatically, we don't need the file at all!

Not really, unless we add a build step (and we don't want that).

**Comment by tb148** [comment]
I think the conflicts isn't too big right now. So I'm closing it.
