### ISSUE TITLE
Backup making addon

### ISSUE THREAD

**Issue by Time-dragon** [ScratchAddons/ScratchAddons#2631]
### Is your request related to a problem? Please describe.

Yes! I get mad when my projects get mass reported.

### Describe the solution you'd like

An addon to create backups.

### Describe alternatives you've considered

I tried report detectors, but the remix tree addon gets in the way.

### Additional context

This can be used by TheInternetIsCoool to stop mass reports.

**Comment by TheColaber** [comment]
Plz just create copies yourself, or just wait for the St to review it

**Comment by Time-dragon** [comment]
> Plz just create copies yourself

But what if I'm too lazy to copy it?

**Comment by TheColaber** [comment]
Then learn to not be lazy. 2 clicks is not very hard.
