### ISSUE TITLE
Addon idea: Wiki dark mode

### ISSUE THREAD

**Issue by Time-dragon** [ScratchAddons/ScratchAddons#2632]
### Is your request related to a problem? Please describe.

I get blinded by the wiki.
### Describe the solution you'd like

Awiki dark mode addon.
### Describe alternatives you've considered

None, but Dark Reader could be one.

**Comment by apple502j** [comment]
This is out of scope for this extension.

**Comment by mxmou** [comment]
I'm working on a userstyle that makes the wiki dark. See https://mxmou.github.io/customize-scratch/

Scratch Addons is only for the Scratch website though.

**Comment by Time-dragon** [comment]
> This is out of scope for this extension.

No, this is for the Scratch Wiki, a part of Scratch.

**Comment by Shluffy** [comment]
this is **Scratch** addons, not **scratch wiki** addons

**Comment by mxmou** [comment]
@Time-dragon The wiki is no longer a part of Scratch. See https://en.scratch-wiki.info/wiki/Scratch_Wiki#Server_Transfer

**Comment by RedGuy12** [comment]
Impossible because of how the extention and the wiki are made
________________________________
