### ISSUE TITLE
Templates addon

### ISSUE THREAD

**Issue by Time-dragon** [ScratchAddons/ScratchAddons#2633]
### Is your request related to a problem? Please describe.

I hate it when I can't make a menu sprite or a platformer with a template.

### Describe the solution you'd like

An addon filled with templates.

### Describe alternatives you've considered

Challenge Galaxy, but that is a bunch of challenges/tutorials.

**Comment by apple502j** [comment]
Don't we already have backpacks?

**Comment by CST1229** [comment]
Isn't this [rejected](https://github.com/ScratchAddons/ScratchAddons/discussions/927)?

**Comment by mxmou** [comment]
@CST1229 This is very similar, so I think it can be considered rejected.
