### ISSUE TITLE
Text Isn't Centered

### ISSUE THREAD

**Issue by 22yeetz22** [ScratchAddons/ScratchAddons#2636]
### Description
The text in the text box is not centered.

### Reproduction steps
1. Go to the editor.
2. Set a variable to an odd number of digits.
3. It is not centered,

### Expected behavior
It should be centered.

### Actual behavior
It is not centered.

### Screenshots

Normal Scratch:
![Not Centered Bug But In Normal Scratch](https://user-images.githubusercontent.com/74276537/120034114-2af21180-bfc2-11eb-8145-29d0268b85f9.png)

ScratchAddons Version:
![Not Centered Bug ScratchAddons](https://user-images.githubusercontent.com/74276537/120034090-23cb0380-bfc2-11eb-91ab-e13b9b3f1851.png)

### Environment

- Browser: Google Chrome
- Scratch Addons version: v1.15.0
- Operating system: Windows

### Additional context

There might be an addon that does this, but I'm not sure which.
Edit: When you click on the text box, it centers.

**Comment by GarboMuffin** [comment]
#2033
