### ISSUE TITLE
Broken Discuss Button When The Text is Too Long

### ISSUE THREAD

**Issue by 22yeetz22** [ScratchAddons/ScratchAddons#2639]
### Is your request related to a problem? Please describe.

Yep. When you enable the discuss button, you can name it whatever you want, even a randomly generated password with 256 characters that makes the other buttons faze off the screen.

### Describe the solution you'd like

Have a limit to the length of the name of the discuss button.

### Additional context

![broken discuss button scratchaddons](https://user-images.githubusercontent.com/74276537/120087116-f6a65000-c0aa-11eb-9d19-e0e7c2726f06.png)

**Comment by return-misaPuding** [comment]
Actually, I don't think that we need to limit the lenght, if people don't
want this to happen, they just don't have to set it to something long.

Dne ne 30. 5. 2021 1:24 uživatel 22yeetz22 ***@***.***>
napsal:

**Comment by WorldLanguages** [comment]
@22yeetz22 If you find any more "bugs" like this, please directly make a pull request fixing the bug, instead of creating an issue.

**Comment by 22yeetz22** [comment]
> @22yeetz22 If you find any more "bugs" like this, please directly make a pull request fixing the bug, instead of creating an issue.

Uh, how? I'm sorta new to GitHub and the only thing I know how to do is to make an issue. :(

**Comment by return-misaPuding** [comment]
Fork this repo, edit the file you want to change, go back to the original
repo, go to page "Pull requests", click "create a pull request", then
"compare across forks", pick your fork in the "Head" field and click
"Create pull request"

Dne ne 30. 5. 2021 17:30 uživatel 22yeetz22 ***@***.***>
napsal:
