### ISSUE TITLE
Profile statistics - users unranked in ScratchDB display as #1

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#2646]
### ~~Repoduction~~ Reproduction steps

1. Enable the "Profile statistics" addon
2. Go to the profile of a user who is unranked in ScratchDB ([example](https://scratch.mit.edu/users/-Foibles/))
3. Scroll down to the statistics section and look at the love/favorite/view ranks.

### Expected behaviour

It should display a ?

### Actual behaviour

It displays a 1

### Screenshots

![image](https://user-images.githubusercontent.com/43426138/120119045-2745c280-c15b-11eb-84bc-9391f24ac37c.png)

### Environment

- Browser: Chromium 90
- Scratch Addons version: 1.15.0
- Operating system: Windows 10

### Additional context

Could be a ScratchDB problem since it happens on [scratchstats.com](https://scratchstats.com) too

**Comment by mxmou** [comment]
The addon should check `statistics.views` and only show the love, favorite and view ranks if it isn't `undefined`.

**Comment by Shluffy** [comment]
> The addon should check `statistics.views` and only show the love, favorite and view ranks if it isn't `undefined`.

@mxmou is the value going to be `null` or `undefined`? see [this](https://github.com/Shluffy/ScratchAddons/commit/2a3e741c880756b74f085988e5cf0e9b42c5f9bc#diff-81b67588d9ce7c30d8491517135b8746caa50f303b3a8393bcea49a531655fdf) commit

**Comment by apple502j** [comment]
ScratchDB needs to be fixed

**Comment by mxmou** [comment]
@apple502j That would be ideal, but it's also possible to check if the user has any projects and hide project-related ranks if they don't.

**Comment by apple502j** [comment]
This can also happen when the user has shared projects iirc @mxmou
