### ISSUE TITLE
material-forum-editor-buttons: posted images do not show

### ISSUE THREAD

**Issue by FunctionalMetatable** [ScratchAddons/ScratchAddons#2652]
### Description

Transparent images (images that have transparency) don't render when you have the material editor buttons addon on.

### Reproduction steps

1. Go to a post that has a transparent image in it (i used [this post](https://scratch.mit.edu/discuss/post/5297493/)).
2. Turn on the material editor buttons addon on.
3. See Error

### Expected behaviour

Transparent images showing

### Actual behaviour

Transparent images invisible and not showing
### Screenshots

![sa-material-buttons-image-transparent-error](https://user-images.githubusercontent.com/67440879/120338655-593a5e80-c2ec-11eb-8f7c-c096252ff754.gif)

### Environment

- Browser: Microsoft Edge 91.0.864.37
- Scratch Addons version: v1.15.0
- Operating system: Windows 10

**Comment by FunctionalMetatable** [comment]
cc @Secret-chest

**Comment by Secret-chest** [comment]
@FunctionalMetatable Please understand I can't do it right now!

**Comment by Secret-chest** [comment]
Can't repro.

**Comment by Secret-chest** [comment]
Sorry. Someone close this.

**Comment by FunctionalMetatable** [comment]
Maybe with images with cdn.scratch.mit.edu/*?

**Comment by apple502j** [comment]
Doesn't have anything with transparency from what I can tell.
