### ISSUE TITLE
"go to TurboWarp" button

### ISSUE THREAD

**Issue by piw-piw** [ScratchAddons/ScratchAddons#2657]
### I made addon `Turbowarp button`.
This is my first addon, so it probably has bugs.
The code snippet is from the addon `remixtree button`.
Not complete, there is no author, no texts. I just don't know if I should type it in or not.

This is the button that opens the TurboWarp website (in the same tab).
![image](https://user-images.githubusercontent.com/76477070/120481303-412c1300-c3b0-11eb-8b4a-d58016aac4de.png)
You can change the background color.

https://github.com/piw-piw/ScratchAddons/tree/master/addons/turbowarp-button

**Comment by apple502j** [comment]
Seriously, how many duplicates of #164 do we have?

**Comment by retronbv** [comment]
I guess I just have a good idea. 🧐

**Comment by piw-piw** [comment]
Can you use my addon?

**Comment by TheColaber** [comment]
> Can you use my addon?

> This addon is hard to get right so I'll try to make it myself or help on the dev discord so that someone can make it

I think the way you made it, is not the way that it should be done. We are trying to add an iframe on the project page. One idea that someone came up with, is that of the notes and credits or instructions includes 'turbowarp' in the instructions, the iframe should already be there. Good try, and you can refer back to the main issue and join our discord server to get help.

**Comment by return-misaPuding** [comment]
I don't think that this is the best way of doing it - if you automatically
add the turbowarp iframe, you can't use Scratch cloud servers. Maybe add a
button which would swap the Scratch project iframe for the turbowarp iframe?

Dne čt 3. 6. 2021 13:45 uživatel TheColaber ***@***.***>
napsal:

**Comment by piw-piw** [comment]
@TheColaber Iframe?
