### ISSUE TITLE
I dont Know if its The addon. but I recently (today) Encountered a Issue.

### ISSUE THREAD

**Issue by Hunter-Ready** [ScratchAddons/ScratchAddons#2660]
**On my project '2048'  i Was makiing a '1' Tile.**
my username is yooperhunter. expect i could only Use the Select tool on Vector.

**Comment by Hunter-Ready** [comment]
its still happening after i Uninstalled it. there is also some lock above the costume Name.

**Comment by CubeyTheCube** [comment]
> its still happening after i Uninstalled it

then it's not an issue with sa
close the issue

**Comment by TheColaber** [comment]
Try disabling other extensions that are running on that page. This is not SA's problem, as you mentioned.
