### ISSUE TITLE
Email on message addon

### ISSUE THREAD

**Issue by Time-dragon** [ScratchAddons/ScratchAddons#2665]
### Is your request related to a problem? Please describe.

No. I want it so that users can use their email to receive Scratch messages.

### Describe the solution you'd like

1. Ping server for messages and email tied to last messaged user
2. Send message to email

### Describe alternatives you've considered

None
EDIT: fixed describe solution

**Comment by FunctionalMetatable** [comment]
Similar to #1954

**Comment by apple502j** [comment]
This is not Scratch Addons' job.

To read a message, we currently need a password (or API token, but that can basically do what passwords can). This is obviously like phishing and hosting servers may not like that.

If they are using the browser when the message is received, then we may be able to send email through the addons, but can't we just use Scratch Notifier instead?

Closing as rejected.

**Comment by WorldLanguages** [comment]
Yeah, unrelated to a browser extension

**Comment by Time-dragon** [comment]
> Closing as rejected.

WE DON'T REJECT ON GITHUB, DO WE?

**Comment by Time-dragon** [comment]
@WorldLanguages related to the browser extension
Edit: On a roll!

**Comment by RedGuy12** [comment]
> > Closing as rejected.
> 
> WE DON'T REJECT ON GITHUB, DO WE?

yes we do

**Comment by Time-dragon** [comment]
> > > Closing as rejected.
> > 
> > 
> > WE DON'T REJECT ON GITHUB, DO WE?
> 
> yes we do

gah

**Comment by Time-dragon** [comment]
bu-oh wait we dont bump, so in that case unreject
