### ISSUE TITLE
IP Ban Deannoyifier addon

### ISSUE THREAD

**Issue by Time-dragon** [ScratchAddons/ScratchAddons#2666]
### Is your request related to a problem? Please describe.

I'm mad at the IP Ban screen appearing.

### Describe the solution you'd like

Have ~~Scratch Addons~~ the addon tell Scratch that the IP Ban was lifted.

### Edit
forgot details

**Comment by apple502j** [comment]
Please only post meaningful suggestions.

**Comment by Time-dragon** [comment]
> Please only post meaningful suggestions.

This is meaningful.

**Comment by retronbv** [comment]
This is probably the reason you are IP banned on scratch. They probably were tired of you being annoying.

**Comment by Time-dragon** [comment]
> This is probably the reason you are IP banned on scratch. They probably were tired of you being annoying.

I was not being annoying, I was banned for no reason.

**Comment by mxmou** [comment]
> > This is probably the reason you are IP banned on scratch. They probably were tired of you being annoying.
> 
> I was not being annoying, I was banned for no reason.

If you aren't using a VPN or a public network, you can appeal the IP ban, but no browser extension can do that for you.
