### ISSUE TITLE
Better unexpanded <addon-body> CSS

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#2681]
Making an issue instead of fixing myself bc I'm bad at CSS lol
These have been bothered me for a while now

1. If long addon names get wrapped, they should not be taking more width than they need to. This issue also causes some tags to wrap, like "for editor" in the screenshot. Fixing this kills 2 birds with one stone.
2. Addon descriptions should not have a max width. They should all reach the same point with an ellipsis (unless those that are shorter and couldn't fill the space, of course)

How it looks now:
![image](https://user-images.githubusercontent.com/17484114/120906553-c3c30580-c630-11eb-9303-da6982a89422.png)

How it should look: **(except first addon name should wrap, if I could figure out how to do that, I'd PR instead :P)**
![image](https://user-images.githubusercontent.com/17484114/120906627-6aa7a180-c631-11eb-83b2-1e42f8e31006.png)

Alternatively to the addon name wrapping, we could make it never wrap, and instead make the description shorter

css lords welp

**Comment by mxmou** [comment]
It now looks like this:
![image](https://user-images.githubusercontent.com/51849865/120921881-52359680-c6c6-11eb-8e04-a2b18c54383a.png)

**Comment by WorldLanguages** [comment]
@mxmou king 👑
