### ISSUE TITLE
Reuse the image uploader for comments as well, but using CDN2

### ISSUE THREAD

**Issue by FunctionalMetatable** [ScratchAddons/ScratchAddons#2692]
### Is your request related to a problem? Please describe.

Always, I have to go to cubeupload to upload an image to show people in the comments

### Describe the solution you'd like

Adding the image uploader on comment boxes. Note that assets automatically downloads the image, but CDN2 doesnt.

### Describe alternatives you've considered

Using a bookmarklet, but i cannot copy images from the clipboard.

**Comment by gosoccerboy5** [comment]
I know my voice doesn't really count here, but it seems a bit of a waste to me. I can make a tool that will help
