### ISSUE TITLE
Remove border on pfps

### ISSUE THREAD

**Issue by gosoccerboy5** [ScratchAddons/ScratchAddons#2697]
### Is your request related to a problem? Please describe.

Scratch recently added this cool epic amazing looking (/s) border on profile pictures on project comments.
![Screen Shot 2021-06-06 at 8 47 41 PM](https://user-images.githubusercontent.com/82768218/120949244-baf23280-c709-11eb-801e-1420315e5b5c.png)

### Describe the solution you'd like

override it in css

### Describe alternatives you've considered

idk maybe add a different type of border

### Additional context

there we go, I got the link. there's a [forum topic](https://scratch.mit.edu/discuss/topic/517693/) about the border on pfps, and it's pretty unpopular

(I see you fdreerf! You think you can downvote my posts..)

**Comment by mxmou** [comment]
The addon could have options to:
* remove the border
* make it extend behind transparent profile pictures
* change its color

**Comment by silvxrcat** [comment]
> The addon could have options to:
> 
>     * remove the border
> 
>     * make it extend behind transparent profile pictures
> 
>     * change its color

or not even show up if the program detects trasparency
