### ISSUE TITLE
"Use local timezone on forums" should adjust dates in "Last Post" listings, too

### ISSUE THREAD

**Issue by towerofnix** [ScratchAddons/ScratchAddons#2698]
### Is your request related to a problem? Please describe.

Ideally, the "use local timezone on forums" addon would make timestamps consistent across the whole site. There are a few places it currently doesn't, including a subforum/category/topic list's "Last Post" column.

### Describe the solution you'd like

Make 'em consistent! Adjust dates/times in the Last Post column the same way as for other areas where timestamps show up.

### Describe alternatives you've considered

One alternative is to leave the timestamps exactly as is, inconsistent across the site. This is good for ~~discord~~ chaos and mayhem reasons, which is definitely always a worthwhile factor to consider. :shipit:

### Additional context

See also #2426 for another timestamp this addon doesn't adjust ("last edited" timestamps).

**Comment by apple502j** [comment]
I hope ScratchDB returns these data (because Scratch sometimes does respect time zones and is unreliable)
