### ISSUE TITLE
Settings page mockup

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#27]
Pls @GDUcrash
Make a pull request with mockup HTML/CSS for the settings page. Then I can make it reactive for Vue. Having an UI to interact with while developing is nice.

**Comment by Explosion-Scratch** [comment]
Sounds cool, I'd like to see some ideas of what we're aiming at here.

**Comment by GDUcrash** [comment]
I'm done with the settings page
