### ISSUE TITLE
[Question] Can I make a PR with edits to the front page of this repo?

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#270]
I made edits to the front page but it did not let me make a PR with my changes. Is there a way that I can?

**Comment by apple502j** [comment]
What's front page?

**Comment by Explosion-Scratch** [comment]
like the code tab. Just the normal view of the repo, not the issues tab or anything.

**Comment by WorldLanguages** [comment]
Hmm what are you trying to edit exactly? I'm confused

**Comment by Explosion-Scratch** [comment]
Like the section on the side titled 'about'. Oh well.

**Comment by GrahamSH-LLK** [comment]
Just put what you want it to say here and tag @WorldLanguages.

**Comment by Explosion-Scratch** [comment]
I just added the website link and some tags to it.
