### ISSUE TITLE
live forum posts

### ISSUE THREAD

**Issue by FunctionalMetatable** [ScratchAddons/ScratchAddons#2708]
### Is your request related to a problem? Please describe.

I hate refreshing the page over and over just to see a post.

### Describe the solution you'd like

A live forum post addon which automatically adds a new post when posted.

**Comment by Shluffy** [comment]
how would this work?

**Comment by FunctionalMetatable** [comment]
> how would this work?

fetch the same page, parse the html and check for new posts.

**Comment by Shluffy** [comment]
> > how would this work?
> 
> fetch the same page, parse the html and check for new posts.

how often though? that might be a lot of requests

**Comment by RedGuy12** [comment]
Yeah, but as long as only one is going at a time, there won't be any lag.

**Comment by GrahamSH-LLK** [comment]
I don't know... for this addon to be useful, it would have to fetch too fast to be useful. A better implementation would connect to a backend server via WebSockets, because a backend should be able to better handle fetching.

**Comment by FunctionalMetatable** [comment]
Closing because https://github.com/ScratchAddons/ScratchAddons/pull/3063#issuecomment-884500536
