### ISSUE TITLE
Private /discuss/youtube

### ISSUE THREAD

**Issue by BoomerScratch** [ScratchAddons/ScratchAddons#271]
**Describe the new addon**

Sets the /discuss/youtube YT player host to youtube-nocookie.com. This is easily done with the URL constructor:
```javascript
var url = new URL("https://youtube.com/embed/ytvidid");
url.host = "youtube-nocookie.com";
console.log(url.toString());
```

**Comment by NoobTracker** [comment]
Neat idea, maybe just mod the True YT Links addon?

**Comment by GrahamSH-LLK** [comment]
> anyone who cares about privacy already has third party cookies disabled
