### ISSUE TITLE
Scratch 3 Developer Tools don't load

### ISSUE THREAD

**Issue by iqnite** [ScratchAddons/ScratchAddons#2712]
### Description

Sometimes the DevTools don't load.

### Expected behaviour

The DevTools should load every time.

### Actual behaviour

Sometimes the Find bar doesn't load, and the "show receivers/senders" option when right-clicking a "broadcast" block is never displayed.

### Screenshots

![image](https://user-images.githubusercontent.com/50552317/121189431-6619fd80-c86a-11eb-8876-18bb06171fe6.png)

### Environment

- Browser: Vivaldi 3.8.2259.42 (with Chrome 90.0.4430.214)
- Scratch Addons version: 1.15.0
- Operating system: WIndows 10

**Comment by WorldLanguages** [comment]
> the "show receivers/senders" option when right-clicking a "broadcast" block is never displayed.

I thought that was removed alltogether?

**Comment by WorldLanguages** [comment]
> Sometimes the Find bar doesn't load

You're going to need to send more details.
