### ISSUE TITLE
Some addons appear two times in the settings page

### ISSUE THREAD

**Issue by superscratch444tre** [ScratchAddons/ScratchAddons#2728]
### Description

Title. This happened to me in the easter egg addons page.

### Repoduction steps

1. Go to the settings page
2. Go to easter egg addons
3. See that the "Redirect mobile forums to main forums" addon appears 2 times.

https://user-images.githubusercontent.com/69812464/121538111-30f9e080-ca0d-11eb-9960-ce74310f192d.mp4

### Expected behaviour

The addon should appear only one time.

### Actual behaviour

Title.

### Screenshots

![error](https://user-images.githubusercontent.com/69812464/121538616-9948c200-ca0d-11eb-9e30-28a1916d2733.png)

### Environment

- Browser: chrome, last version
- Scratch Addons version: master branch
- Operating system: Windows

### Additional context

It also happens in other sections, not just in easter egg addons.

**Comment by WorldLanguages** [comment]
Expected behavior, new addons will always appear twice.
