### ISSUE TITLE
Forum SVG Icons Makes Forum Emojis Not Show

### ISSUE THREAD

**Issue by leahcimto** [ScratchAddons/ScratchAddons#2729]
### Description
When the SVG forum icon addon is enabled, forum emojis don't show.

### Repoduction steps
1. Turn on "Better forum post editor buttons" addon
2. Go to any post with emojis
3. Notice that emojis don't show, just space.

### Expected behaviour
You should be able to see the emojis.

### Actual behaviour
You can't see the emojis.

### Screenshots

Expected:
<img width="928" alt="Screen Shot 2021-06-10 at 10 35 24 AM" src="https://user-images.githubusercontent.com/68165163/121544239-929f5800-c9d7-11eb-8864-88dbcf7b929e.png">

Actual with SVG icons enabled:
<img width="954" alt="Screen Shot 2021-06-10 at 10 40 53 AM" src="https://user-images.githubusercontent.com/68165163/121545241-56b8c280-c9d8-11eb-89e2-56c69aa4f56a.png">

### Environment

- Browser: Chrome 91
- Scratch Addons version: Not exactly sure how to check, but I think the latest one.
- Operating system: macOS 11 Big Sur

### Additional context
None

**Comment by mxmou** [comment]
This was supposed to be fixed in version 1.15 in #2437, but I can confirm that it still happens.

> Scratch Addons version: Not exactly sure how to check, but I think the latest one.

The version number is displayed in the extension popup and in the More Settings popup on the settings page.

**Comment by leahcimto** [comment]
> The version number is displayed in the extension popup and in the More Settings popup on the settings page.

Ok, my version is 1.15.0.

**Comment by FunctionalMetatable** [comment]
Maybe adding the `:not([src*="djangobb_forum/img/smilies/"])` css selector to the end of https://github.com/ScratchAddons/ScratchAddons/blob/9b4230ff84bf10824e617c55230a36b2ff2bf0a7/addons/material-forum-editor-buttons/icons.css#L76 may work. Not sure

**Comment by RedGuy12** [comment]
> Maybe adding the `:not([src*="djangobb_forum/img/smilies/"])` css selector to the end of
> 
> https://github.com/ScratchAddons/ScratchAddons/blob/9b4230ff84bf10824e617c55230a36b2ff2bf0a7/addons/material-forum-editor-buttons/icons.css#L76
> 
> may work. Not sure

it seems to me that block is not even needed... @Secret-chest what images from the cdn is that modifying?

**Comment by apple502j** [comment]
Fixed by #2812
