### ISSUE TITLE
Dark mode creates extra margin between projects in mystuff

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#2740]
https://user-images.githubusercontent.com/72760579/121617585-4c77e200-ca33-11eb-9835-2cbfd067a3bb.mp4

**Comment by mxmou** [comment]
Not a bug: this behavior isn't the best but it was added to avoid conflicting with Scratch 2.0 → 3.0 styles. I'm working on a new way to handle the compatibility between these two addons which will make it possible to avoid this.
