### ISSUE TITLE
Copy link to comment in messaging tab

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#2743]
> Allow the "Copy link to comment" addon to be alsoin the messaging tab of Scratch Addons.

I'll stop my feedback issue rush now and continue tomorrow.

**Comment by TheColaber** [comment]
wait i forgot about 
![image](https://user-images.githubusercontent.com/72760579/121736661-da041200-cac5-11eb-9f2a-3562f20ff2f8.png)

**Comment by Shluffy** [comment]
@TheColaber but that doesn't copy link. That takes you to the link. It's not really the same. You then also need to manually copy the link

**Comment by WorldLanguages** [comment]
@TheColaber I added this to the backlog for a reason...

**Comment by RedGuy12** [comment]
Right click, copy link
________________________________

**Comment by WorldLanguages** [comment]
@RedGuy12 Doesn't work, its an onclick event handler
