### ISSUE TITLE
Stop auto-running duplicated blocks addons also stops click to run scripts

### ISSUE THREAD

**Issue by Vivaan-S** [ScratchAddons/ScratchAddons#2751]
### Description

When you enable the "do not auto-run duplicated blocks", it also blocks click to run scripts.
### Repoduction steps

1.  enable the "do not auto-run duplicated blocks" addon
2.  go into a project and create a script that says "hello world" (dont attach it to a green flag)
3.  click the script.

### Expected behaviour

the script should run

### Actual behaviour

the script won't work
### Screenshots

i would need a video
### Environment

- Browser: Chrome
- Scratch Addons version: latest version, chrome webstore
- Operating system: Windows

**Comment by TheColaber** [comment]
You probably have this addon enabled
![image](https://user-images.githubusercontent.com/72760579/121738147-d8d3e480-cac7-11eb-9710-a400053e738b.png)

**Comment by Vivaan-S** [comment]
ohhh
