### ISSUE TITLE
[searchable-dropdowns]: add button to add new broadcasts and variables.

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#2753]
> make the search box be able to create messages and variables directly
![image](https://user-images.githubusercontent.com/72760579/121749037-0032ad80-cad8-11eb-97cc-73738e5ef403.png)

To create variables, maybe there could be some sort of filtered thing, that also sets the variable's scope?

**Comment by WorldLanguages** [comment]
Messages sure. Variables, eh

**Comment by fierin** [comment]
Broadcasts, Variables, And Custom Blocks could be made to be made like this:

Middle Click to start block search

Variable:

var [insert variable name]

Broadcast:

broadcast [insert name]
broadcast [insert name] and wait

Custom Blocks:

Define [insert name]

**Comment by fierin** [comment]
> > make the search box be able to create messages and variables directly
> > ![image](https://user-images.githubusercontent.com/72760579/121749037-0032ad80-cad8-11eb-97cc-73738e5ef403.png)
> 
> To create variables, maybe there could be some sort of filtered thing, that also sets the variable's scope?

tbh broadcasts already have a create button.

**Comment by fierin** [comment]
Creator of scratch addons pls make this

**Comment by fierin** [comment]
TheColaber  please add custom blocks to the issue request

**Comment by TheColaber** [comment]
There is currently no way to even search for custom blocks. Unless you have an idea, I have no way to implement this.

**Comment by mxmou** [comment]
> There is currently no way to even search for custom blocks. Unless you have an idea, I have no way to implement this.

I think @fierin wants to be able to create custom block using the devtools middle click feature.

**Comment by fierin** [comment]
> > There is currently no way to even search for custom blocks. Unless you have an idea, I have no way to implement this.
> 
> I think @fierin wants to be able to create custom blocks using the devtools middle click feature.

Yes, sorry for not clarrifying, since it seams my recomendation doesnt fit here, i will make a separate post.
