### ISSUE TITLE
[Mute project player] Adjust volume

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#2755]
> Volume slider on projects, next to the stop sign (this would basically be an update for the project muting addon)

**Comment by Cool-Scratcher** [comment]
This would make the "Mute project player" addon into a "Project volume" addon, so then muting the project would just be a feature. Also, keep in mind that the project player is getting a *little* cluttered with all the addons, someone would have to find a way to accommodate for all the different possible combinations and- *deep breath* there's a lot to think about.

**Comment by WorldLanguages** [comment]
@Cool-Scratcher #2846 helps with that, at least in the technical side, to guarantee consistent order of buttons
