### ISSUE TITLE
[Bug] Make recommended addons enabled by default 

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#276]
Title. I guess this is a bug.

**Comment by JeffaloBob** [comment]
enabled by default and recommended are seperate things, but i dont see why it should be like that so yeah i think this is a good idea

**Comment by WorldLanguages** [comment]
I see why this would seem like a bug. Whether it is or not depends on what extension Scratch Addons will replace (if any). Right now, I'm planning it to replace Scratch Messaging Extension, and toggling on random stuff for existing users is not a good idea. However, after the transition, likely all recommended addons will be enabled by default.

**Comment by Explosion-Scratch** [comment]
> I see why this would seem like a bug. Whether it is or not depends on what extension Scratch Addons will replace (if any). Right now, I'm planning it to replace Scratch Messaging Extension, and toggling on random stuff for existing users is not a good idea. However, after the transition, likely all recommended addons will be enabled by default.

Okay! Got it!
