### ISSUE TITLE
When I click a block, it does not run

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#2769]
###Description###

Before I updated to v 1.15.0, I was able to click a block, and it will run. But after the update, a block only runs if it is attached to an event block
### Reproduction steps

1. Go to a project
2. Click on a block that is not attached to an event block
3. It won't work

### Expected behaviour
1. Go to a project
2. Click on a block that is not attached to an event block
3. The block will run

Not applicable 

- Browser: Chrome 89 
- Scratch Addons version: 1.15.0
- Operating system: Windows 10

**Comment by mxmou** [comment]
Is this addon enabled?
![image](https://user-images.githubusercontent.com/51849865/121859036-87aa3780-ccf7-11eb-9ff7-12f78aed829f.png)

**Comment by Genius398** [comment]
no

**Comment by Genius398** [comment]
Uhh yes.. maybe i did not see that

**Comment by Genius398** [comment]
Issue closed
