### ISSUE TITLE
turbowarp /forkphorus button should stop the project first

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#277]
**Describe the bug**

if you press the button while a project is playing / audio or something the audio continues or the page crashes

**To Reproduce**

1. start project
2. let music play
3. press button that replace stage

**Expected behavior**

simulate pressing the stop button so that the project stop before replacing it with the embedded player

**Screenshots**

![image](https://user-images.githubusercontent.com/40470736/93027558-eed27880-f60d-11ea-8f80-0a02cec1644b.png)
idk

**Device (please complete the following information):**

- window 10 1909
- chrome latest idk

**Comment by JeffaloBob** [comment]
addon no longer exists

**Comment by WorldLanguages** [comment]
Bruh it exists it just won't be included on v1.0.0

**Comment by JeffaloBob** [comment]
wel i was just assuming when its remade it'll be fixed
