### ISSUE TITLE
Different files types for Project Recorder

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#2777]
### Is your request related to a problem? Please describe.

When I save the project recording, I always get it as a webm file. Then I have to convert it into mp4 to upload it.

### Describe the solution you'd like
We can have a dropdown on the record modal to chose between video file type options

### Describe alternatives you've considered

none

### Additional context

none

**Comment by FunctionalMetatable** [comment]
Tag "new addon" should be removed.
https://github.com/ScratchAddons/ScratchAddons/blob/ca2e93ec0f8de572db3884fe876bf652a15fd64a/addons/mediarecorder/userscript.js#L288

**Comment by WorldLanguages** [comment]
Rejected, browsers only allow recording as webm and we won't ship our own converter
