### ISSUE TITLE
Have projects move slower addon

### ISSUE THREAD

**Issue by Shluffy** [ScratchAddons/ScratchAddons#2778]
### Is your request related to a problem? Please describe.

projects can only run at 30-240 fps using the 60fps addon. You can't make it run slower

### Describe the solution you'd like

A new addon like this

### Describe alternatives you've considered

remove the minimum for the 60fps addon

### Additional context

can this be done by just changing the min to 1, max to 29, and change the default?

**Comment by Genius398** [comment]
Maybe duplicate of #2760 ?

**Comment by Shluffy** [comment]
> Maybe duplicate of #2760 ?

maybe the slow-mo part. Although if this solution works we can solve that slow-mo part. I can't test it though

**Comment by Genius398** [comment]
> > Maybe duplicate of #2760 ?
> 
> maybe the slow-mo part. Although if this solution works we can solve that slow-mo part. I can't test it though

The code/solution for reducing fps is correct. We just need someone to do it

**Comment by Shluffy** [comment]
> > > Maybe duplicate of #2760 ?
> > 
> > 
> > maybe the slow-mo part. Although if this solution works we can solve that slow-mo part. I can't test it though
> 
> The code/solution for reducing fps is correct. We just need someone to do it

if it is just messing with the addon.json file I could do that. I can't test it though

**Comment by Genius398** [comment]
yeah

**Comment by Genius398** [comment]
but can you unpack the extension

**Comment by Shluffy** [comment]
can you test [this](https://github.com/Shluffy/ScratchAddons/tree/blah
)

**Comment by Genius398** [comment]
ok

**Comment by Genius398** [comment]
It's great

**Comment by Genius398** [comment]
Please put the `addon.json ` file into the 60fps folder

**Comment by Genius398** [comment]
The testing is great

**Comment by Shluffy** [comment]
@Genius398 I changed the name because it would be custom fps. I will open a pr and see if they want that to be changed

**Comment by Genius398** [comment]
ok

**Comment by RedGuy12** [comment]
Duplicate of #2760

**Comment by Shluffy** [comment]
@RedGuy12 not dupe. This is to change the manifest to allow custom fps, while that is to rename the addon

**Comment by RedGuy12** [comment]
No, read the linked issue
________________________________

**Comment by Shluffy** [comment]
ah, okay
