### ISSUE TITLE
Consistency within the addon credits

### ISSUE THREAD

**Issue by Shluffy** [ScratchAddons/ScratchAddons#2786]
### Is your request related to a problem? Please describe.

some times the contributor is linked, while others not

### Describe the solution you'd like

consistency

### Describe alternatives you've considered

uh, ignore/close this

### Additional context

over here:
![image](https://user-images.githubusercontent.com/81823039/122076009-7ed56680-cdc8-11eb-9a3d-9680d094da27.png)
while over here:
![image](https://user-images.githubusercontent.com/81823039/122076214-b0e6c880-cdc8-11eb-9fb2-6db6c10e9974.png)

and most of them have a link, so why not make that one a link

**Comment by Shluffy** [comment]
and this should probably be for everyone, not just TheColaber.

**Comment by WorldLanguages** [comment]
Up to the author to PR
