### ISSUE TITLE
No support for debugger blocks in Custom block colors

### ISSUE THREAD

**Issue by piw-piw** [ScratchAddons/ScratchAddons#2787]
![image](https://user-images.githubusercontent.com/76477070/122082466-54070480-ce00-11eb-869f-7879e5513758.png)

**Comment by mxmou** [comment]
This happens when the Debugger addon is enabled and the Black preset of Customizable block colors is used.

**Comment by fierin** [comment]
if its in a milestone then is this added already?

**Comment by mxmou** [comment]
> if its in a milestone then is this added already?

A milestone just indicates when it's planned to be added.

**Comment by fierin** [comment]
> > if its in a milestone then is this added already?
> 
> A milestone just indicates when it's planned to be added.

Okay!
Thank you!

**Comment by WorldLanguages** [comment]
Anyone want to take this?

**Comment by RedGuy12** [comment]
I got it

**Comment by RedGuy12** [comment]
Just realized these should be added to block switching as well. I can try to understand that code



________________________________

**Comment by pufferfish101007** [comment]
> Just realized these should be added to block switching as well. I can try to understand that code

Atm the current block switching code is incompatible with custom blocks. I'm currently trying to add custom block switching, and I'll add debugger blocks while I'm at it.

**Comment by WorldLanguages** [comment]
@RedGuy12 Did you actually work on this?

@mxmou Maybe you can tackle this in #3165?

**Comment by RedGuy12** [comment]
I was planning to but I didn't understand the code. I did make the "if" functionality and anyone can feel free to write it and push it to the pr



________________________________
