### ISSUE TITLE
Too many logs causes lag

### ISSUE THREAD

**Issue by 22yeetz22** [ScratchAddons/ScratchAddons#2788]
### Is your request related to a problem? Please describe.

[
  "When there are too many logs, and you open the log tracker, you can barely scroll or move the page (100000 logs should be enough)."
]

### Describe the solution you'd like

[
  "Make pages of logs instead of one big page of logs.",
  "Or discard them after a certain point"
]

### Describe alternatives you've considered

[
  "Have a "load more (number of logs left to view)" button."
]

**Comment by Mr-Anonymous75** [comment]
I'd prefer a hybrid of those two solutions.

**Comment by lisa-wolfgang** [comment]
Or perhaps start discarding logs after a certain point? I don't know about you, but I probably wouldn't read all 100,000 of those logs.

**Comment by mxmou** [comment]
> Or perhaps start discarding logs after a certain point? I don't know about you, but I probably wouldn't read all 100,000 of those logs.

I think that's what terminals typically do.

**Comment by RedGuy12** [comment]
Someone in the Discord server said that they have crashed Scratch before by having too many logs.

> When there are more than, say, 1000 messages in the log, it only shows up to a 1000 in order to not crash Scratch. You can "Load more" to see another 1000 more. This limit can also be customizable in the Scratch Addons settings.
> 
> I've accidentally crashed Scratch by having projects with too many logs. Sure, I could probably do a better job at placing logs, but... seriously? An addon that can crash you?

**Comment by WorldLanguages** [comment]
We're not sure if it's the amount of DOM elements or JS heap memory that causes crash/lag, so let's limit the amount of messages that are stored in JS memory as well as removing DOM elements from logs that were removed from JS memory? 🤔
