### ISSUE TITLE
Unhide NFE Projects, Show Everything in Search

### ISSUE THREAD

**Issue by Scratchfangs** [ScratchAddons/ScratchAddons#2790]
Self explanatory, everything that is hidden in Search like FNAF projects, should be unhidden in Search. Same for NFE projects.

**Comment by Scratchfangs** [comment]
Don't forget this would be customizable, maybe enabled by default?

**Comment by mxmou** [comment]
This would require a third party searchable database of projects similar to ScracthDB. Probably not something that could currently be considered possible.

**Comment by Shluffy** [comment]
status invalid, close?

**Comment by mxmou** [comment]
@Shluffy I'm not sure if it should be closed - it's theoretically possible.

**Comment by Shluffy** [comment]
or at that point why not make an addon that searches using an sa search engine rather then the scratch one

**Comment by RedGuy12** [comment]
i think lefty is planning to add this to scratchdb, he already has some project endpoints 
![image](https://user-images.githubusercontent.com/61329810/122110544-4774b300-cde4-11eb-8147-20ec3737482d.png)

**Comment by Shluffy** [comment]
if lefty is adding it should we wait until that is done?

**Comment by WorldLanguages** [comment]
Realistically probably won't happen

**Comment by apple502j** [comment]
Yep, rejected.
