### ISSUE TITLE
Have addons work on uploads

### ISSUE THREAD

**Issue by Shluffy** [ScratchAddons/ScratchAddons#2792]
### Is your request related to a problem? Please describe.

addons should work on uploads.scratch.mit.edu

### Describe the solution you'd like

add `*.scratch.mit.edu` to addon matches, or add it but have it be `uploads.scratch.mit.edu`

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by mxmou** [comment]
I don't think this is necessary. `uploads.scratch.mit.edu` isn't intended to be used as a mirror of Scratch.

**Comment by RedGuy12** [comment]
intended behavior
