### ISSUE TITLE
Debugger Addon: Clear Console From the project scripts

### ISSUE THREAD

**Issue by Shluffy** [ScratchAddons/ScratchAddons#2795]
### Is your request related to a problem? Please describe.

If you go to [this](https://scratch.mit.edu/projects/544812614/) project with the debugger addon enabled and click the flag, and then click it again you will see HackBot Can't clear the console, and so it will log the data again

### Describe the solution you'd like

a block to clear the console

### Describe alternatives you've considered

ignore this

### Additional context

n/a

**Comment by Mr-Anonymous75** [comment]
Support. That would be nice.

**Comment by Genius398** [comment]
yeah

**Comment by Shluffy** [comment]
> Support. That would be nice.

this isn't the suggestions forum

**Comment by Mr-Anonymous75** [comment]
> this isn't the suggestions forum

I know. I was just saying that it's a nice suggestion. And seriously, it was not spam.

**Comment by GrahamSH-LLK** [comment]
Aah noooo that’s not what that block is for!

**Comment by Shluffy** [comment]
> Aah noooo that’s not what that block is for!

wdym?

**Comment by mxmou** [comment]
> > Aah noooo that’s not what that block is for!
> 
> wdym?

The debugger addon isn't intended for displaying output to the user.

**Comment by Shluffy** [comment]
alright then

**Comment by TheColaber** [comment]
Moving to #2810... Clear console after clicking flag.
