### ISSUE TITLE
Debugger Addon: Add "Clear on Green Flag" option

### ISSUE THREAD

**Issue by Mr-Anonymous75** [ScratchAddons/ScratchAddons#2798]
### Is your request related to a problem? Please describe.

I'm really used to Unity's clear on play option for the console, and well, it is really useful. So, it's really annoying to have to click clear every time I start a project with this addon. 

### Describe the solution you'd like

It would be nice if the option was in the File or Edit menus - not automatically clearing on play can be useful in some cases, and it'd be quite annoying to go to the settings page every time you want to turn off clear on play.
 
### Describe alternatives you've considered

Or just copy Unity and put the option in the console itself.

**Comment by fierin** [comment]
i feel like this should be project controlled (or optionally project controlled) so somethings get saved between plays: for a tilescrolling editor for example it could automaticlly send the level to the logs to backup the code. If the logs clear when your browser/pc or the tab is closed then it would be less usefull though.
