### ISSUE TITLE
Get Debugger logs

### ISSUE THREAD

**Issue by 22yeetz22** [ScratchAddons/ScratchAddons#2801]
### Is your request related to a problem? Please describe.

Sorta. I was making a project and I wanted to get an item from the logs and what sprite did it.
### Describe the solution you'd like

Make a block in the debugger to add this.

### Describe alternatives you've considered

Make a variable doing this.

### Additional context

Debugger.

**Comment by Samq64** [comment]
I'm not sure how useful this will be considering the block would just report a blank value for almost everyone who views the project.

**Comment by 22yeetz22** [comment]
Hmmm... True

**Comment by RedGuy12** [comment]
No. Use a variable.
