### ISSUE TITLE
Make sure we are still compatible with new studios

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#2805]
- [ ] various studio actions can fail when muted
- [x] manager limit
- [x] manager-limit modal dark mode (@mxmou can you do this?)
- [ ] reply count

**Comment by mxmou** [comment]
The manager limit modal already looks good in dark mode.

**Comment by Hans5958** [comment]
Closed in favor of #2917, I guess? (reopen if needed)
