### ISSUE TITLE
Clear Console automatically 

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#2810]
### Is your request related to a problem? Please describe.
We can make a block to clear the console. More, we can set it to clear at pause, start or stop

**Comment by apple502j** [comment]
Duplicate of #2795

**Comment by RedGuy12** [comment]
Naw, that issue is about using a block to clear it. This is automatically clearing it on the green flag.

**Comment by Shluffy** [comment]
apple is kinda right. it kindas a little and then a setting for more

**Comment by apple502j** [comment]
Duplicate of #2798
