### ISSUE TITLE
No Dark mode on the Remix Tree

### ISSUE THREAD

**Issue by Miala-python** [ScratchAddons/ScratchAddons#2823]
No dark mode for the Remixtree page.

Thanks

**Comment by RedGuy12** [comment]
![image](https://user-images.githubusercontent.com/61329810/122619097-40a0a700-d055-11eb-9f8a-a9e9004a1da4.png)

**Comment by WorldLanguages** [comment]
@mxmou ?

**Comment by RedGuy12** [comment]
aaa fixed it but accidentally refreshed the page

i can't remember what i did now
