### ISSUE TITLE
Customizable Comment colours > Editor dark mode

### ISSUE THREAD

**Issue by Mr-Programmer-777** [ScratchAddons/ScratchAddons#2839]
There is a dark Comments setting, which obviously changes colours for comments, so why not be able to customise those colours?
You could make a colour picker in the settings of the addon and just make the colour chosen darker/lighter for each rendered object, e.g border and wrapping.

**Comment by fierin** [comment]
good idea!

**Comment by Samq64** [comment]
I managed to get this working as a separate addon with customizable comment and text colours based on the dark comments.

![image](https://user-images.githubusercontent.com/81489795/138575597-452e0a81-2ee5-48ce-a8e3-34f0fb4d8f80.png)

The only thing I'm not happy about is that the 1px boarder around the comment still use the original comment colour when not attached to a block.
