### ISSUE TITLE
"Welcome to Scratch" message support: "message filters" and "Scratch Messaging" addons

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#2853]
![image](https://user-images.githubusercontent.com/61329810/122691688-dcb5e400-d1f6-11eb-8017-882b80b033ce.png)
![image](https://user-images.githubusercontent.com/61329810/122691680-d32c7c00-d1f6-11eb-95bc-8d24257ba1da.png)
see the difference? Default should be nothing checked

**Comment by TheColaber** [comment]
Why... Scratch's default is all of them checked.

**Comment by apple502j** [comment]
I think this bug is a wontfix due to its nature - yes this is a bug, but it does not matter in most cases. You can still make a PR if you want to waste some time.

**Comment by Hans5958** [comment]
> yes this is a bug, but it does not matter in most cases

And set as wontfix and closed? Come the heck on, dude. That is nonsense!

**Comment by WorldLanguages** [comment]
> he said that "nobody cares about light theme." 

To be fair, I also said that hehe

**Comment by TheColaber** [comment]
Our messaging addon also doesn't support this type of message...

**Comment by WorldLanguages** [comment]
> Our messaging addon also doesn't support this type of message...

+1 from Discord feedback

**Comment by WorldLanguages** [comment]
Search keywords: join message, new account, after creating new user

**Comment by Secret-chest** [comment]
I don't think there should be another checkbox only for this message.

**Comment by WorldLanguages** [comment]
> I don't think there should be another checkbox only for this message.

Agreed.

For the "message filters" addon, we should probably always show this message, no matter the filter.
For the "scratch messaging" addon, we could add support for this type of message relatively easily.

For the "scratch notifier" addon, we can ignore this type of message really.
