### ISSUE TITLE
`sa-pause` was moved

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#2854]
sa-pause (not reakpoint) only works when the debugger is enabled. we should move the block back for backwards compatabillity

**Comment by apple502j** [comment]
"Backwards compatabillity" does not exist, according to Oxford dictionary. Plus the block is not meant to be used in projects that are meant to be run - you should only add that while debugging.

**Comment by WorldLanguages** [comment]
I considered this notice to be enough. It should be removed in a month or so:
![image](https://user-images.githubusercontent.com/17484114/122789924-2ef61400-d28e-11eb-97e5-fd20c90a385b.png)

**Comment by lisa-wolfgang** [comment]
This would probably be a good scenario to use a "See also" section for. https://github.com/ScratchAddons/ScratchAddons/issues/2031#issuecomment-811075546
