### ISSUE TITLE
Add the ability to toggle dark/light themes at sunset/sunrise

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#2855]
### Is your request related to a problem? Please describe.

Toggling dark mode frequently (i.e. at night) is currently inconvenient. There are multiple options that need to be toggled for full dark mode -- the SA theme, the editor theme, and the website theme.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/43426138/122692925-34574e00-d1fd-11eb-89fc-d9ff80f853b4.png)

In the SA theme toggle, there would be an additional "Toggle at sunset/sunrise" option. Below that, there would be "Sunset" and "Sunrise" options where you would select a specific timeframe for dark mode to be active.

![image](https://user-images.githubusercontent.com/43426138/122692948-4afda500-d1fd-11eb-9e01-b4f115d5c8cd.png)

There could also be "Toggle at sunset/sunrise" options in each addon that has a dark mode, and possibly in some that don't.

### Describe alternatives you've considered

Each addon could have its own Sunset and Sunrise options, but that seems unnecessarily complicated. Perhaps there could be some kind of indicator or link to the ones in the main SA theme settings?

**Comment by Samq64** [comment]
Another option could be to just use your system's theme instead.

**Comment by lisa-wolfgang** [comment]
> Another option could be to just use your system's theme.

Some OSes (namely, Windows) make it a hassle to schedule dark mode toggling.

**Comment by ErrorGamer2000** [comment]
@Samq64 just means it could be an option alongside the sunset/sunrise toggling. That way you could still use the sunset/sunrise option if you wanted to.

**Comment by Chiroyce1** [comment]
> Another option could be to just use your system's theme.

I made a [different issue](https://github.com/ScratchAddons/ScratchAddons/issues/4041) for this a few minutes ago, since this was related to time and not the system theme.

**Comment by apple502j** [comment]
Rejected.

Since sunset and sunrise timing can change every week or so, it doesn't seem like a good option to add.

**Comment by DNin01** [comment]
Yeah, this might be more useful if it's adaptive as the seasons change. If I wanted accurate sunrise and sunset theme switching, I'd probably set that at the operating system level and then [let Scratch Addons adapt to that](https://github.com/ScratchAddons/ScratchAddons/issues/4041), so let's focus on that.

**Comment by Samq64** [comment]
Why is this closed as won't fix if #4280 is open and implements it?

**Comment by DNin01** [comment]
> Why is this closed as won't fix if #4280 is open and implements it?

That pull request hasn't been explicitly approved yet.

**Comment by DNin01** [comment]
I don't know.

1. This feature is much more useful if the sunrise and sunset times can change **by themselves** based on the time of the year and location, which would require asking for more permissions few people would probably want to grant.
2. System settings are a thing too. It would be nice to be able to change system settings as needed without having go in and change Scratch Addons' settings as well. Adapting to system settings instead also means if the system supports changing the theme automatically, we can just rely on it, no additional permissions required.

Speaking of setting your system to automatically set the theme based on time of day, you can do this in most modern operating systems, and if that's not the case, there's probably an app to do it (for example, there's [Auto Dark Mode](https://apps.microsoft.com/store/detail/XP8JK4HZBVF435) for Windows).

What if we described this as a static schedule - one that is not meant to change based on sunrise and sunset times? Would that be useful at all...?

**Comment by BroJac5246** [comment]
> I don't know.
> 
> 1. This feature is much more useful if the sunrise and sunset times can change **by themselves** based on the time of the year and location, which would require asking for more permissions few people would probably want to grant.

So make the permission optional. And then the user will understand that to use this feature, the extension needs their location. It makes sense, and I think a lot of people would be okay granting it.

> 2. System settings are a thing too. It would be nice to be able to change system settings as needed without having go in and change Scratch Addons' settings as well. Adapting to system settings instead also means if the system supports changing the theme automatically, we can just rely on it, no additional permissions required.

I think this should be an option ("Match system theme,"  etc.), but the OS's theme might not wind up reaching the extension based on the OS and browser.

> Speaking of setting your system to automatically set the theme based on time of day, you can do this in most modern operating systems, and if that's not the case, there's probably an app to do it (for example, there's [Auto Dark Mode](https://apps.microsoft.com/store/detail/XP8JK4HZBVF435) for Windows).

Ubuntu, for example, (and also probably many other OSs I don't know about) doesn't have the former option and requires a shell extension. Using an app or shell extension works but it just isn't as easy as if Scratch Addons does it automatically.

> What if we described this as a static schedule - one that is not meant to change based on sunrise and sunset times? Would that be useful at all...?

Sure. Plenty of programs do that. And it's not like you can tell the exact minute that the sun sets and be like, "Oh no! Scratch Addons was off by 15 minutes." Sunrise/sunset is still more convenient, but this is an okay compromise.

**Comment by rgantzos** [comment]
> > I don't know.
> > 
> > 1. This feature is much more useful if the sunrise and sunset times can change **by themselves** based on the time of the year and location, which would require asking for more permissions few people would probably want to grant.
> 
> So make the permission optional. And then the user will understand that to use this feature, the extension needs their location. It makes sense, and I think a lot of people would be okay granting it.

You wouldn't need any additional permissions. The location permission would be a lot to ask of Scratchers, and a simple IP address should be enough. However, that would likely require an external server, and the best option that protects privacy the best is to just pick the average sunset/sunrise time, and it should be fairly accurate in all places, using the current time.

**Comment by WorldLanguages** [comment]
Asking the user for their city and using some API is probably enough
But it doesn't really make sense to consider this feature unless we already provide a manual light/dark switch that at least syncs with the OS, I think we're tracking that in a different issue
