### ISSUE TITLE
Load in custom CSS/Themes (?) like BetterDiscord

### ISSUE THREAD

**Issue by silvxrcat** [ScratchAddons/ScratchAddons#2862]
### Is your request related to a problem? Please describe.

When I want to customize my scratch, I have to download Amino or some other program, Find the actual CSS classes/ids, and write CSS with barely any help from Emmet.

### Describe the solution you'd like

- An option on the side bar called themes
You can save downloaded themes from other places and turn them on/off whenever (OPTIONAL: The themes can be uploaded to the SA website and users can add themes by sending requests to get the theme CSS)
- Addon for custom CSS
When you turn on the Addon, you have to insert a CSS file (in this case a button that asks for a file) and then the program loads it/runs it.

### Describe alternatives you've considered

Amino is a good substitute, but there is barely any Emmet implementation and you have to click a button to read classes which completely closes the addon. 

### Additional context

This can solve the "Custom Dark Mode" addon people have been wanting.

This feature was heavily inspired by BetterDiscord.

Edit: Found out themes were rejected but not CSS. It did not include why they are rejected,

**Comment by WorldLanguages** [comment]
I agree on the fact there's lots of stuff to explore under theming. But Scratch Addons was literally just Scratch Messaging and Cloud Games one year ago so be patient with us :P

**Comment by silvxrcat** [comment]
> I agree on the fact there's lots of stuff to explore under theming. But Scratch Addons was literally just Scratch Messaging and Cloud Games one year ago so be patient with us :P

i'm trying i'm trying that's why i said optional in the post

**Comment by apple502j** [comment]
IMO, if you're going to use custom CSS, use Stylus. Scratch Addons a collection of pre-made styles and scripts.

**Comment by RedGuy12** [comment]
You can customize the editor colors very in depth using the editor dark mode and customizable colors addon. The same will be coming to the website soon. For any further customization, use Stylus. Rejected.
________________________________
From: silvxrcat ***@***.***>
Sent: Tuesday, June 22, 2021 4:32:23 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Load in custom CSS/Themes like BetterDiscord (#2862)


Is your request related to a problem? Please describe.

When I want to customize my scratch, I have to download Amino or some other program, Find the actual CSS classes/ids, and write CSS with barely any help from Emmet.

Describe the solution you'd like

  *   An option on the side bar called themes
You can save downloaded themes from other places and turn them on/off whenever (OPTIONAL: The themes can be uploaded to the SA website and users can add themes by sending requests to get the theme CSS)
  *   Addon for custom CSS
When you turn on the Addon, you have to insert a CSS file (in this case a button that asks for a file) and then the program loads it/runs it.

Describe alternatives you've considered

Amino is a good substitute, but there is barely any Emmet implementation and you have to click a button to read classes which completely closes the addon.

Additional context

This can solve the "Custom Dark Mode" addon people have been wanting.

This feature was heavily inspired by BetterDiscord.

**Comment by return-misaPuding** [comment]
This sounds like a good idea

**Comment by return-misaPuding** [comment]
Sorry for necroposting, this PR split into two emails for me.

Dne pá 23. 7. 2021 11:35 uživatel Michal Piling ***@***.***>
napsal:

> This sounds like a good idea
>
