### ISSUE TITLE
'This sprite only' variables get copied into other sprites.

### ISSUE THREAD

**Issue by Tacodude7729** [ScratchAddons/ScratchAddons#2867]
### Description

I was hesitant to create this issue as I know so little about it but here we go:  For some reason in my project with Scratch Addons private variables are being duplicated into sprites they weren't created in. I'll just be switching between sprites and somehow every private variable gets copied from one sprite into another. This is really annoying (luckily developer tools cleanup can fix this quickly), but I have no idea how to reliable reproduce the bug.
I can't even say for sure it's a Scratch Addons bug and not just a Scratch bug, but I have seen somebody else on Discord complaining about the same issue, and they where using Scratch Addons too. I have never seen the happen in Vanilla Scratch, but I basically only ever use Scratch Addons anyway.

### Steps to reproduce?
1. Have two sprites, create a private variable in the first one.
2. Switch between the sprites and do something (?) to trigger the bug.
3. The private variable you created in sprite one will now be in sprite two.

_Here is a bunch of local variables being copied from one sprite to another where they are not used, for some reason..._
![image](https://user-images.githubusercontent.com/27910867/123251141-350a2000-d52e-11eb-947d-f18ce92a6bce.png)

### Environment

Ubuntu 20.04 Chrome 89.0.4389.114

_Sorry this report is so vague. It's just a really annoying issue I would like to see fixed._

**Comment by WorldLanguages** [comment]
Can you list all editor addons you had enabled when the bug happened?

**Comment by apple502j** [comment]
Note that I have seen reports of similar bugs in vanilla.

**Comment by Tacodude7729** [comment]
I have now seen reports of similar bugs in vanilla too, this might not be a Scratch Addons issue. My list of plugins is quite extensive so it might not narrow it down too much but here:

- Alt+GreenFlag 60FPS player mode
- Bitmap images copying
- Block switching
- Cat blocks
- Clone counter
- Custom block shape
- Data category tweaks
- Developer tools
- Drag and drop files
- Editor dark mode a customizable colors
- Hex color picker
- Messages in editor
- Mouse position
- Onion skinning
- Pause button
- Project progress bar
- Record project bideo
- Remove curved stage border
- Searchable dropdowns
- Thumbnail setter
- Confirm actions
- Copy link to comment button
- Resizable comment input
- Scratch 2.0 -> 3.0
- Show exact count
- Show full areas
- Sprite and script count
- Website dark mode
- Youtube full screen
- Cloud games
- Message count on extension icon
- Scratch Messaging

**Comment by apple502j** [comment]
Closing; this is probably upstream issue - if anyone can repro it please record and report to official repo, with Scratch Addons disabled/uninstalled.
