### ISSUE TITLE
Scratch Messaging for Firefox is occasionally missing many messages

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#2872]
### Description

When checking messages using the Scratch Messaging addon, none of the comments appear, even though comments are present in my messages.

### Reproduction steps

Unknown at this time, although this is a Firefox-specific bug.

### Screenshots

I have 100 messages:
![image](https://user-images.githubusercontent.com/43426138/123554055-eafa8780-d743-11eb-9d1e-420022cbb308.png)

But only 45 items appear in the addon:
![image](https://user-images.githubusercontent.com/43426138/123554067-fa79d080-d743-11eb-873e-9f61e744779d.png)

### Environment

- Browser: Firefox 89.0.1
- Scratch Addons version: release v1.16.3
- Operating system: Windows 10

**Comment by TheColaber** [comment]
Twas told to me that they may be studio notifications/forums. We don't indicate how many times it repeats. This should maybe be made into an enhancement.

**Comment by lisa-wolfgang** [comment]
Nothing that appears to pertain to this issue.

**Comment by apple502j** [comment]
Can you upload the logs?

**Comment by lisa-wolfgang** [comment]
@apple502j Here are the logs from the past 24 hours:

![image](https://user-images.githubusercontent.com/43426138/123685021-cc63c180-d813-11eb-984d-429a2dc721b0.png)

**Comment by WorldLanguages** [comment]
> This could be a crash in the bg. Any errors in the bg?

Probably not. If that was the case, it would tell them they were logged out.
It's most likely all comments are triggering `continue;` in a for loop

**Comment by thecrewmate876** [comment]
Works for me (I haven't tried with the beta addon yet tho):

![image](https://user-images.githubusercontent.com/76265544/123828860-d4962c80-d8f9-11eb-8b70-c45a0b67b439.png)

**Comment by lisa-wolfgang** [comment]
Not sure what happened, but new comments have started to appear again:

![image](https://user-images.githubusercontent.com/43426138/123873008-723e2b80-d8fb-11eb-96c1-67623955e308.png)

Old comments are still missing:

![image](https://user-images.githubusercontent.com/43426138/123873047-7e29ed80-d8fb-11eb-908b-385f1529821d.png)

Scratch Addons hasn't updated at all, so it's possible that something with Scratch's APIs is causing this.

**Comment by lisa-wolfgang** [comment]
Update: all comments are now showing again. I was signed out and had to sign back in, so that could have fixed it. It's also possible that the problem was related to Scratch's servers and they're now working properly again.

**Comment by WorldLanguages** [comment]
I have no idea why logging back in would solve the problem, if it's in our side. Scratch Messaging does not cache comment content. They're requested again every time Scratch Messaging is opened.
Maybe this is actually `addon.auth` failing? But I don't think you need auth to get comment contents.

**Comment by lisa-wolfgang** [comment]
It appears that I never noted it here -- we've determined that the issue occurs with all message types, not just comments.

**Comment by lisa-wolfgang** [comment]
The issue is happening again for me in 1.18. Note that there was a major profile comment migration yesterday, which could have caused something to get mixed up.

**Comment by apple502j** [comment]
Closing; the refactor should've fixed this issue.
