### ISSUE TITLE
Custom Block Colors:RGB

### ISSUE THREAD

**Issue by fierin** [ScratchAddons/ScratchAddons#2880]
### REQUEST
It is amazing how customizable scratch has become using this addon.
Lets keep up with gaming standard,
RGB
it might hurt when using solid colors: but when using the outline mode it would be amazing! 
Animating in all its rainbow glory! 

### SOLUTION
add a animating option for the outline mode.
This could be RGB or moving a gradient: this would allow gradients to destinguish block tys rather than every type having RGB

###

###

**Comment by WorldLanguages** [comment]
Probably not...? This could be reopened if you send a screenshot demo or explain how this would be useful

**Comment by fierin** [comment]
oh… okay!

**Comment by fierin** [comment]
Though it was a request  for asthetic reasons.

**Comment by fierin** [comment]
i have a inspiration for this now.
ill generalize it to more color theme related things.
