### ISSUE TITLE
Support for debugger blocks in Developer Tools "Add block by name" popup.

### ISSUE THREAD

**Issue by Tacodude7729** [ScratchAddons/ScratchAddons#2883]
When Developer tools and Debugger are enabled, debugger blocks should be able to be added though the Ctrl + Space menu of developer tools.

_No breakpoint block in menu._
![image](https://user-images.githubusercontent.com/27910867/123898339-82601480-d9a8-11eb-8cf0-bafbfa99a612.png)

**Comment by fierin** [comment]
dont forget middle click.
This would indeed be useful.
in the process might aswell find a generalized way to make any custom block apear there.

**Comment by WorldLanguages** [comment]
> in the process might aswell find a generalized way to make any custom block apear there.

AFAIK this is already the case for user defined custom blocks

**Comment by fierin** [comment]
i mean blocks made by a addon
