### ISSUE TITLE
New Addon: Ctrl + Enter to post stuff

### ISSUE THREAD

**Issue by Shluffy** [ScratchAddons/ScratchAddons#2887]
### Is your request related to a problem? Please describe.
Ctrl + Enter Doesn't post stuff, and this would make it easier

### Describe the solution you'd like

an addon that would do this, and settings for what to do for ctrl enter (project comments, studio comments, profile comments, forum posts)

### Describe alternatives you've considered

n/a

### Additional context

i don't know how to detect the keys, but it would be a matter of getting the correct ids and then using `.click()` when it matches the ctrl + enter

**Comment by fierin** [comment]
it would be useful: but better yet press enter to do those and shift enter to add new line (just like most chatboxes)

**Comment by Shluffy** [comment]
github will just use `enter` and `shift + enter` for a new line, but `ctrl + enter` posting. this would be like outlook (i think), gmail, and github. I find that in google hangouts, zoom, and google meet that `enter` posting the chat message can be a pain in the neck

**Comment by fierin** [comment]
maybe it could be a setting? so people cna have what they prefer.
