### ISSUE TITLE
Theme:Animated

### ISSUE THREAD

**Issue by fierin** [ScratchAddons/ScratchAddons#2889]
### Is your request related to a problem? Please describe.
The custom block colors and custom editor colors’ themes’ looks static most of the time.
Dont get me wrong : it was intended that way,
but im sure some people who are with the recent trend of which the gaming community calls RGB:
you might want it to be otherwise.

### Describe the solution you'd like
create a option to have animated gradients. This would particularly fit in the outlines (especially custom block theme when it is set to outline.)
This Feature is mainly inspired by this: 
![DCDAA6D9-D14C-4F7C-9D74-6C7F30DD3E23](https://user-images.githubusercontent.com/86007204/123996029-7d7b7f00-da01-11eb-8806-7a49ccb65dac.png)
ofcource that is just a screenshot so it is not animated.

I know it doesnt have much use: but there are addons that are already for asthetics anyway.

### Aditional Clips

https://www.youtube.com/watch?v=FfVUaK1CSS4

https://user-images.githubusercontent.com/86007204/123997122-9fc1cc80-da02-11eb-9d15-bfb534e0222b.mp4

i couldnt find any other rgb ui other than minecrfat.

**Comment by Shluffy** [comment]
I think this might take to much styling for an addon, as it is animated. 
Using netherite ingot for the beacon? if that was in survival you would be flexing

**Comment by fierin** [comment]
doent worry thats not my world: its a video from mcpedl that was made to show the rgb ui… its just the only “demo” i found.
