### ISSUE TITLE
Addons change order in settings while searching after toggling addons

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#2898]
Even made it to [a YouTube video](https://youtu.be/SGTvJJrkkaA?t=314) lol

**Comment by TheColaber** [comment]
It shouldn't be any surprise if I tell you it was because of you.

https://github.com/ScratchAddons/ScratchAddons/blob/753e6dd7bc30d2a55649a922a96155b6e381e0eb/webpages/settings/index.js#L203-L204

**Comment by WorldLanguages** [comment]
Enabled addons going first is intentional - sorting happening after toggling is not

**Comment by WorldLanguages** [comment]
Was solved by #2909
