### ISSUE TITLE
Add nothing to show when blank search

### ISSUE THREAD

**Issue by 22yeetz22** [ScratchAddons/ScratchAddons#2904]
### Is your request related to a problem? Please describe.

no
add a thing that says: nothing to show here
or something like that for clueless people
when there are no search results in the setting search

### Describe the solution you'd like

add a thing that says: nothing to show here
or something like that
just in case a person doesn't know

### Describe alternatives you've considered

i have not considered anything else yet

### Additional context

why not add

**Comment by WorldLanguages** [comment]
I considered this to make it easier to add in the futre, but didn't actually implement it
