### ISSUE TITLE
Remove `beta` tag from studio tools

### ISSUE THREAD

**Issue by Shluffy** [ScratchAddons/ScratchAddons#2914]
![image](https://user-images.githubusercontent.com/81823039/124522151-2dfdd000-ddc0-11eb-806c-53f1cd157779.png)

[this](https://github.com/ScratchAddons/ScratchAddons/blob/f17fa3e3f434c01c14536e26eeec61f808e82e28/addons/studio-tools/addon.json#L46) shows that it was added in v1.2.0, so I think the beta tag can be removed safely

**Comment by RedGuy12** [comment]
it's because of the studio updates tomorrow.

**Comment by WorldLanguages** [comment]
It will be removed next update.
