### ISSUE TITLE
`infinite-scroll` makes it impossible to respond to forum posts

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#2919]
because the posts load and push the reply box down

reggeressed by #2879

**Comment by Hans5958** [comment]
AFAIK infinite scrolling is not done on forum posts, full stop. I changed the mechanism and made sure that it won't do anything in infinite scrolling.

Really weird if it somehow working again there.

**Comment by Hans5958** [comment]
I have gone ahead and tried to reproduce this, but to no avail. Observe that (a) I have scrolled into the reply box, (b) the addon is not loaded on the page, and (c) it doesn't go down.

The commit that I tested is 4a052b17.

![image](https://user-images.githubusercontent.com/11584103/124704638-9a8ee100-df1e-11eb-99cf-a5ad7ce0327d.png)

**Comment by RedGuy12** [comment]
Uh yeah it infinite scrolls for me... I'm on master
________________________________

**Comment by RedGuy12** [comment]
Video:
https://user-images.githubusercontent.com/61329810/124753319-73b8b680-deee-11eb-9b86-75455c94ec36.mp4

**Comment by Hans5958** [comment]
I think you should check your environment. My repo is currently clean and this does not happen.

**Comment by RedGuy12** [comment]
huh, i don't know what happened, but I pulled the last few commits (neither of which touched forums scroll) and I can no longer repro...
