### ISSUE TITLE
2.0-ify studios

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#2935]
### Is your request related to a problem? Please describe.

In the new studio theme the number of followers is missing

### Describe the solution you'd like

Show the number of followers In the new studio theme

### Additional context

none

**Comment by sfederici** [comment]
Ok, I found it below the studio description. I'd suggest to move it to the top area of the studio theme

**Comment by mxmou** [comment]
I'm working an addon that will make studios more similar to what they looked like before the update.

**Comment by apple502j** [comment]
Changed title to better describe suggestions
