### ISSUE TITLE
Notices are more visible than warnings in dark mode

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#2948]
In dark mode, the background color of notices stands out more than that of warnings.

**Comment by apple502j** [comment]
@mxmou can you fix that, plz? not very good at darkening things

**Comment by mxmou** [comment]
> (oh wait, i thought you were talking about new studios' notice when adding curators... :P)

Those are fine because they aren't visible most of the time.

**Comment by WorldLanguages** [comment]
I agree that the current colors are bad

**Comment by mxmou** [comment]
Also affects light mode, but not that much.
