### ISSUE TITLE
Ability to revert back to old studios.

### ISSUE THREAD

**Issue by Scratchfangs** [ScratchAddons/ScratchAddons#2953]
I made a suggestion for this, but it's unlikely that it would be added: https://scratch.mit.edu/discuss/topic/527643/

I'm asking for this to be added to SA, since imo, it looks like dog poop.

**Comment by Scratchfangs** [comment]
I know some people may like it, but it's optional.

**Comment by TheColaber** [comment]
Duplicate of #2947

**Comment by TheColaber** [comment]
In the future, please use the issue template and read the notice at the top.
