### ISSUE TITLE
[editor-stepping] Ability to change the highlighted color

### ISSUE THREAD

**Issue by FunctionalMetatable** [ScratchAddons/ScratchAddons#2957]
### Is your request related to a problem? Please describe.
I don't want blue to be the only color available for the highlighting blocks addon.

### Describe the solution you'd like

Setting to change color for the highlight in the editor-stepping addon

**Comment by CST1229** [comment]
This is actually pretty easy to make by just replacing the blue in the SVG with an addon setting value using addon.settings.get() and concatenation (and some changes to the addon manifest), although it only applies on page reload. In fact I actually did that in a branch of my fork, now all I need is to make a PR.
