### ISSUE TITLE
Handle multiple accounts logged in at once on one SA instance

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#2962]
If the Container feature is used on Firefox, it is possible to have two valid sessions on two tabs with one SA background instance. This feature is not restricted by `incognito` option of manifest.json.

Do we support this, and should we fix this? If so, which account should background and popups use?

See #2942

**Comment by CST1229** [comment]
I think the icon+messaging should use the account logged into the current tab. If there's no Scratch session on that tab, it would either use the containerless account or the last container's account.

**Comment by apple502j** [comment]
Superseded by #2965
