### ISSUE TITLE
Performance Update Megathread

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#2968]
- [ ] `addon.tab.scratchClass` needs to be async-ified due to upstream replacing inlined CSS with a CDN-served file
- [ ] Make sure dynamic import of studio tabs do not cause problems
- [ ] Make sure themes apply in the correct order

**Comment by apple502j** [comment]
@mxmou help :( branch is https://github.com/LLK/scratch-www/tree/hotfix/critical-js

**Comment by GarboMuffin** [comment]
> addon.tab.scratchClass needs to be async-ified due to upstream replacing inlined CSS with a CDN-served file

Are you sure that affects scratch-gui CSS? I think scratch-gui has all its CSS inlined in JS before it gets published to npm so all scratch-www sees is a single JS bundle, at least for now, so those changes probably don't affect editor styles. If I'm wrong about that, and if it makes things easier, you could go back to hardcoding the classes with hashes and I'll figure out how to adjust them for TW.

**Comment by apple502j** [comment]
Imma build that commit

**Comment by apple502j** [comment]
Okay so @GarboMuffin is correct; GUI styles are still inlined.

**Comment by apple502j** [comment]
Seems to be fine, closing
