### ISSUE TITLE
The website link in the README is incorrect [BUG]

### ISSUE THREAD

**Issue by Platinum-Phoenix** [ScratchAddons/ScratchAddons#297]
**Describe the bug**

The link to the website in the [README.md](https://github.com/ScratchAddons/ScratchAddons/blob/master/README.md) file is incorrect

**To Reproduce**

1. Go to the [README.md](https://github.com/ScratchAddons/ScratchAddons/blob/master/README.md) file
2. Scroll down to the [Learn More Section](https://github.com/ScratchAddons/ScratchAddons#learn-more)
3. Click on the link

**Expected behavior**

The link should go to the new [site](https://scratchaddons.com)
instead of the old site "scratchaddons.github.io"

**Comment by Platinum-Phoenix** [comment]
Its a really easy fix tbh

**Comment by Explosion-Scratch** [comment]
Thanks! I made a PR!
