### ISSUE TITLE
Disable auto-complete on search bar

### ISSUE THREAD

**Issue by LankyBox01** [ScratchAddons/ScratchAddons#2983]
### Is your request related to a problem? Please describe.

No, it's not. It's a completely new useful addon that will... I think the title is pretty clear. An addon to disable the auto-complete on the navigation searchbar.

### Describe the solution you'd like

No.

### Describe alternatives you've considered

~~Either that or delete the search bar completely~~

### Additional context

No.

**Comment by BroJac5246** [comment]
We should close this now that #4819 has been merged.
