### ISSUE TITLE
infinite-scroll: discuss.css has no settingMatch

### ISSUE THREAD

**Issue by CST1229** [ScratchAddons/ScratchAddons#2991]
### Description

When the `infinite-scroll` addon is enabled, discuss.css is always applied even if the forumScroll option is false, but forumScroll.js isn't. This results in being unable to navigate pages since the navigation is hidden and the userscript didn't activate.

### Repoduction steps

1. Enable the Infinite scroll addon
2. Don't check the "forums" box
3. Go to any forum and see the top or bottom

### Expected behaviour

The page navigation should still be there.

### Actual behaviour

The page navigation is hidden.

### Screenshots

![shot](https://user-images.githubusercontent.com/68464103/125395320-5337a300-e3ab-11eb-802f-8fe2de180dc2.png)

### Environment

- Browser: Firefox 90.0 (beta channel)
- Scratch Addons version: 1.17.0 prerelease (current master branch)
- Operating system: Windows 10
- My browser / operating system: Windows NT 10.0, Firefox 90.0, No Flash version detected

**Comment by TheColaber** [comment]
cc @Hans5958 what have you done
