### ISSUE TITLE
Code Converter log

### ISSUE THREAD

**Issue by Hexigon102** [ScratchAddons/ScratchAddons#2993]
### Is your request related to a problem? Please describe.
When you are making a game(or something) on Scratch and you might want to have a log showing how the code would look like it JavaScript so if making a version of the game on GitHub or another web coding program you can export the scratch project using the log.

### Describe the solution you'd like
I would like there to be a small log tab(like the debugger) that shows the converted code in your scratch project. you can choose if you want to export it and choose the coding language that it is converted to.

**Comment by apple502j** [comment]
Rejected.

The whole idea of "converting something into another language" is flawed. Just like how cultural difference affects translation of real-life languages, there are big differences that make this idea very hard to implement. For example, JavaScript itself does not offer stage rendering, so you'll have to add a few hundreds of kilobytes of code just to make that cat appear.

Perhaps you're looking for [sb-edit](https://www.npmjs.com/package/sb-edit)'s Leopard conversion, but that library is not maintained.

**Comment by Hexigon102** [comment]
> 
> 
> Rejected.
> 
> The whole idea of "converting something into another language" is flawed. Just like how cultural difference affects translation of real-life languages, there are big differences that make this idea very hard to implement. For example, JavaScript itself does not offer stage rendering, so you'll have to add a few hundreds of kilobytes of code just to make that cat appear.
> 
> Perhaps you're looking for [sb-edit](https://www.npmjs.com/package/sb-edit)'s Leopard conversion, but that library is not maintained.

then cant it say which ones you cant use for this spicific thing insted

**Comment by return-misaPuding** [comment]
Maybe you can just create a window which will translate the program using
either Leopard or Forkphorus's packager?

Dne út 13. 7. 2021 10:02 uživatel apple502j ***@***.***>
napsal:

**Comment by apple502j** [comment]
Forkphorus Packager is probably useless. It will generate the same code for every project, just with different zip file.
