### ISSUE TITLE
README.md Pull Request

### ISSUE THREAD

**Issue by Ani-Xan** [ScratchAddons/ScratchAddons#30]
I have created a commit for the README.md file because I thought it looked a little bland. [Here's ](https://github.com/ScratchAddons/ScratchAddons/pull/29)my Pull request! https://github.com/ScratchAddons/ScratchAddons/pull/29

**Comment by BoomerScratch** [comment]
Oh, you don't have to create a new issue to tell others that you've made a PR 😉
The count will automatically update:
![image](https://user-images.githubusercontent.com/60622217/89170263-abe9a380-d57f-11ea-9676-cd9e6d220f5f.png)
