### ISSUE TITLE
Debugger icon

### ISSUE THREAD

**Issue by coloredscratch** [ScratchAddons/ScratchAddons#3005]
the debugger icon needs to match the block colour when in the editor

**Comment by WorldLanguages** [comment]
Elaborate...?

**Comment by mxmou** [comment]
The block category icon for the debugger addon is the orange Scratch Addons logo and doesn't match the block color.

Maybe a blue version of the logs window icon could be used?

**Comment by WorldLanguages** [comment]
(Note: this is conceptually scope:addon but technically scope:core)

**Comment by mxmou** [comment]
> (Note: this is conceptually scope:addon but technically scope:core)

It's also related to the addon API because there needs to be a way for the addon to specify the icon.

**Comment by BackThePortal** [comment]
Also, add the descriptive icon to it if the extension that adds icons to categories is enabled. I think it should be like this: https://www.svgrepo.com/show/327714/code.svg
