### ISSUE TITLE
Missing string studio-tools/leave

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#3011]
### Description

#2918 removed the string `studio-tools/leave`, which is still used for the leave button on the My Stuff page.

### Repoduction steps

1. Enable the studio tools addon
2. Enable the setting to show a leave button in My Stuff
3. Open the My Studios tab in My Stuff

### Expected behaviour

The string would not be removed, because it's still used.

### Actual behaviour

The string is missing.

**Comment by mxmou** [comment]
Reopening - the string should now be re-added.

**Comment by WorldLanguages** [comment]
Didn't #3016 solve this?
