### ISSUE TITLE
Studio tools should use the same username placeholder as Scratch

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#3013]
### Is your request related to a problem? Please describe.

The placeholder used by studio tools for the promote and remove input fields ("Username") is different from that used by Scratch for the similar Invite Curators input ("Scratch Username").

### Describe the solution you'd like

Use Scratch's placeholder. The message ID is `studio.inviteCuratorPlaceholder`.

**Comment by apple502j** [comment]
Works as intended

**Comment by mxmou** [comment]
If not using Scratch's message is intended, the message used by the addon should be changed to match.

**Comment by apple502j** [comment]
Well, current one works fine IMO

**Comment by mxmou** [comment]
> Well, current one works fine IMO

What's wrong with changing it?

**Comment by WorldLanguages** [comment]
@apple502j Any better arguments...?
