### ISSUE TITLE
Less notices and warnings

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#3015]
### Is your request related to a problem? Please describe.

Notices are meant to be important instructions, but some addons use them for things that should probably be part of the description instead. Others use warnings when notices would be more appropriate.

### Describe the solution you'd like

Move some notices to addon descriptions:
- non-draggable sprites
- developer tools
- pause button
- the second notice ("this feature works ...") in sprite folders

Change the custom block shape warning to a notice.

**Comment by WorldLanguages** [comment]
The notice on pause button could be directly removed by now.

**Comment by lisa-wolfgang** [comment]
> Change the custom block shape warning to a notice.

I set it as a warning because code readability and ease of editing could potentially be heavily impacted.

**Comment by mxmou** [comment]
> > Change the custom block shape warning to a notice.
> 
> I set it as a warning because code readability and ease of editing could potentially be heavily impacted. See #3061.

Wouldn't it only be impacted for others, not the project creator? That's why I think a notice makes more sense.
