### ISSUE TITLE
Add a "stretch" feature in the costume editor.

### ISSUE THREAD

**Issue by CodeGuy92** [ScratchAddons/ScratchAddons#3024]
### Is your request related to a problem? Please describe.

No.

### Describe the solution you'd like

For what?
I want a new button that enables/disables the stretch mode so you can stretch pictures and text in the custom editor.

### Describe alternatives you've considered

Nah

### Additional context

Nope

**Comment by Hexigon102** [comment]
sounds good

**Comment by lisa-wolfgang** [comment]
I'm assuming that you're referring to something else, because you can already stretch objects in the editor using the left/right/top/bottom handles when selecting:

![image](https://user-images.githubusercontent.com/43426138/126070364-c9fad4ac-a623-496f-b883-f385b1b63e44.jpeg)
![image](https://user-images.githubusercontent.com/43426138/126070388-7db840ef-6672-409e-bb7b-c074d5f4afad.jpeg)

**Comment by CodeGuy92** [comment]
> I'm assuming that you're referring to something else, because you can already stretch objects in the editor using the left/right/top/bottom handles when selecting:
> 
> ![image](https://user-images.githubusercontent.com/43426138/126070364-c9fad4ac-a623-496f-b883-f385b1b63e44.jpeg)
> ![image](https://user-images.githubusercontent.com/43426138/126070388-7db840ef-6672-409e-bb7b-c074d5f4afad.jpeg)

bitmap pictures

**Comment by wgyt** [comment]
@CodeGuy92 this is a bitmap image:
![image](https://user-images.githubusercontent.com/68466727/126071483-1263133d-8d5a-4f44-bfa5-bdd45c48af8a.png)
![image](https://user-images.githubusercontent.com/68466727/126071493-82ecfec3-4d90-4bef-a7c8-19d2269d31ba.png)

**Comment by CodeGuy92** [comment]
> @CodeGuy92 this is a bitmap image:
> ![image](https://user-images.githubusercontent.com/68466727/126071483-1263133d-8d5a-4f44-bfa5-bdd45c48af8a.png)
> ![image](https://user-images.githubusercontent.com/68466727/126071493-82ecfec3-4d90-4bef-a7c8-19d2269d31ba.png)

I meant... with polygon points...

**Comment by CodeGuy92** [comment]
like vector

**Comment by mxmou** [comment]
So something like the Reshape feature in vector? That would be very difficult, if not impossible, to implement in bitmap.

**Comment by CodeGuy92** [comment]
> So something like the Reshape feature in vector? That would be very difficult, if not impossible, to implement in bitmap.

welp

**Comment by lisa-wolfgang** [comment]
You have to be more specific in your issue description or we won't  know what you're requesting.
