### ISSUE TITLE
Unchangeable text

### ISSUE THREAD

**Issue by Medericoder** [ScratchAddons/ScratchAddons#3029]
Hi! I found a bug.

When I change the size of the stage (for example, when I change 480x360 for 640x360, or conversely), all text zones are set to "unchangeable text". The highlighting is not blue anymore : it is gray, and I am not able to write anymore.

![image](https://user-images.githubusercontent.com/80577386/125783759-54a7085d-991c-460e-aa6e-92ec74f77488.png)

**Comment by CST1229** [comment]
I think this isn't a SA thing, and I also experienced untypable text boxes in vanilla Scratch Desktop back when I used that so it may be a Scratch Desktop thing.
Try minimizing then unminimizing the window.

**Comment by mxmou** [comment]
This bug is caused by Scratch or TurboWarp, not Scratch Addons.
