### ISSUE TITLE
code button

### ISSUE THREAD

**Issue by CodeGuy92** [ScratchAddons/ScratchAddons#3040]
### Is your request related to a problem? Please describe.

I want to add a code button to the forums, so that you don't have to type [code]

### Describe the solution you'd like

No.

### Describe alternatives you've considered

No.

### Additional context

I already build some code but i'm too tired to complete it now, so if someone can make a new addon then it would be great thx

```
  var inputButtonContainer = document.createElement("li");
  inputButtonContainer.className = "markItUpButton markItUpButton17";

  var inputButton = document.createElement("a");
  inputButton.id = "codeButton";

inputButton.onclick = function () {
    document.getElementById("id_body").value += "[code=" + prompt("Language") + "]" + prompt("Code") + "[/code]";
};

  inputButton.style.backgroundImage =
    "url('https://cdn.scratch.mit.edu/scratchr2/static/__9c5e4a8de50f4ce487e67140f57c59fc__/djangobb_forum/js/markitup/sets/bbcode/images/code.png')";

  inputButtonContainer.appendChild(inputButton);

  if (toolbar) {
 document.querySelector(".markItUpButton5").insertAdjacentElement("afterend", inputButtonContainer);
  }
```

**Comment by CST1229** [comment]
Using markitUpButton17 would conflict with the image uploader's button...

**Comment by CodeGuy92** [comment]
> Using markitUpButton17 would conflict with the image uploader's button...

How would it conflict? It's just a class lol

**Comment by CST1229** [comment]
> > Using markitUpButton17 would conflict with the image uploader's button...
> 
> How would it conflict? It's just a class lol

IDK but it would probably cause some issues.

**Comment by CodeGuy92** [comment]
> > > Using markitUpButton17 would conflict with the image uploader's button...
> > 
> > 
> > How would it conflict? It's just a class lol
> 
> IDK but it would probably cause some issues.

I tested it using the console. Trust me, it works.
You should probably try it too

**Comment by CodeGuy92** [comment]
i'll build the addon now, after my other addon gets accepted.

**Comment by Secret-chest** [comment]
This may conflict with material-forum-editor-buttons

**Comment by RedGuy12** [comment]
You can handle it the same way you do image uploader
________________________________

**Comment by apple502j** [comment]
Working on it

**Comment by CodeGuy92** [comment]
> Working on it

ok
