### ISSUE TITLE
Title can overflow when old studio layout is used

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#3048]
!["tutorials and tools by (newline) (covered with Projects tab) guages"](https://user-images.githubusercontent.com/33279053/126042002-a5f01c7a-b856-4766-99cc-94b89078659a.png)

Doesn't seem like easy to fix

**Comment by WorldLanguages** [comment]
I doubt mxmou wasn't unaware of this.

**Comment by TheColaber** [comment]
Why not add the ... thing that scratch did before?

**Comment by WorldLanguages** [comment]
Because old-studio-layout is full of CSS hacks, since elements are not ordered the same as before.

**Comment by apple502j** [comment]
We can enforce max width and add `...`.

**Comment by mxmou** [comment]
> We can enforce max width and add `...`.

There is already a fixed width, which means that I did think of overflow when making the addon but then forgot about it.

**Comment by apple502j** [comment]
Imma fix rn

**Comment by apple502j** [comment]
- except this seems trickier than i thought

**Comment by WorldLanguages** [comment]
@mxmou If fixed today this can go for v1.17.1

**Comment by apple502j** [comment]
Okay got it
