### ISSUE TITLE
[New Addon] The Scratch Font

### ISSUE THREAD

**Issue by CodeGuy92** [ScratchAddons/ScratchAddons#3059]
I'm really sorry but i am in a really big rush right now, so i cannot fill in the correct form. I'll edit it later.

I want an addon that will enable the Scratch Font in the editor.

**Comment by lisa-wolfgang** [comment]
I believe that the devs are planning on pulling support for the font in the near future, even from projects that already have it.

This should be part of the more general-purpose suggestion to add custom fonts: #2050

**Comment by mxmou** [comment]
> I believe that the devs are planning on pulling support for the font in the near future, even from projects that already have it.

This is correct. See LLK/scratch-render-fonts#23
