### ISSUE TITLE
Sprite search/sort

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#3062]
### Is your request related to a problem? Please describe.

For projects with a large amount of sprites, it may be challenging and/or time-consuming to find specific ones, even with the assistance of sprite folders, especially on smaller displays (and in small stage mode) when the sprites panel is only one or two sprites wide.

### Describe the solution you'd like

At the top of the sprites area, a search bar would be added. The most relevant, recent, or frequently accessed sprites would appear upon searching -- this could be an option in the settings. It could also be possible to make the sprites auto-sort when not searching, with that order then being saved with the project for potential use in a browser without Scratch Addons.

Another settings option could be to hide the sprite properties panel to reduce clutter, as the addition of vertical space could make the sprites panel almost unviewable on some displays.

We would need to take care to ensure that this plays nice with sprite folders. It would, at the very least, need to be temporarily disabled while searching. Another option is to add this as a feature to the sprite folders addon and turn it into a more general-purpose sprite management addon, which might be better in the long run for future additions like a list view.

**Comment by Cool-Scratcher** [comment]
It seems to me that putting a search bar on top of the sprites might clutter up the layout. We don't have much space to work with...
![image](https://user-images.githubusercontent.com/65724251/127217400-4b363a6b-1320-4755-b2f1-d3bab7390e06.png)
Actually, wait... we don't have any space to work with.
Perhaps there could be an icon, and on click, the icon expands into a search bar? But then again, where would that be?

**Comment by fierin** [comment]
Wouldn't it be possible to add a sprite selector menu (enlarges the sprite area and adds a search bar)?

**Comment by lisa-wolfgang** [comment]
> It seems to me that putting a search bar on top of the sprites might clutter up the layout. We don't have much space to work with...

I was thinking that the sprite properties panel could be collapsed or removed.
