### ISSUE TITLE
Updated Sound Editor

### ISSUE THREAD

**Issue by Hexigon102** [ScratchAddons/ScratchAddons#3065]
### Is your request related to a problem? Please describe.
Yes sometimes the sound editor lacks in some sound effects that I think would be useful for some scratch users.

### Describe the solution you'd like
i think if someone could make an addon with sound editor Updates it would be useful

i also think they should be multiple **Robot buttons** on the editor and maybe they could merge different sound into one it would really help

**Comment by WorldLanguages** [comment]
This is too general to be an issue, it can be moved to a discussion.
