### ISSUE TITLE
Discussions Tab duplicates when defining document.body

### ISSUE THREAD

**Issue by CodeGuy92** [ScratchAddons/ScratchAddons#3070]
### Description

`document.body.innerHTML = document.body.innerHTML;`
Run this in your console a couple of times, you might notice something...

### Repoduction steps

^

### Expected behaviour

It shouldn't duplicate

### Actual behaviour

It duplicates

### Screenshots

Nope

### Environment

windows 10

**Comment by mxmou** [comment]
If it doesn't happen when using Scratch normally, it isn't a bug.
