### ISSUE TITLE
Improve 2.0→3.0 addon

### ISSUE THREAD

**Issue by iqnite** [ScratchAddons/ScratchAddons#3072]
### Is your request related to a problem? Please describe.

The 2.0→3.0 addon improves the design a bit, but it's still not exactly like the rest of the site. You can still see clear differences, for example, the buttons are smaller and buttons that should be gray are white and the animations, messages, and scrollbars still have the old style.

### Describe the solution you'd like

Using the same style as on real 3.0 pages.

### Additional context

It's not a really big issue and there are bigger addons to do before, but you should do this sometime.

**Comment by mxmou** [comment]
> the buttons are smaller

They will probably stay smaller, but the other things you listed can definitely be improved.
