### ISSUE TITLE
Caps In Update Message

### ISSUE THREAD

**Issue by Shluffy** [ScratchAddons/ScratchAddons#3073]
I just got this:
![image](https://user-images.githubusercontent.com/81823039/126403220-01bd8d05-0153-4936-9eaa-179a4d486b89.png)
Now on the settings page (and in it's `addon.json` file) it is spelled "Old studio layout" with the "o" being a capital o. this is also true for every other new addon listed.

To compare this issue:
![image](https://user-images.githubusercontent.com/81823039/126403220-01bd8d05-0153-4936-9eaa-179a4d486b89.png)
(update image)
![image](https://user-images.githubusercontent.com/81823039/126403680-6194657e-0f51-42de-9e8a-f1bbeb5f7b3f.png)
(new addons on setting page)

**Comment by apple502j** [comment]
This is not an issue.

**Comment by WorldLanguages** [comment]
This is intentional and consistent with the changelog.

**Comment by Shluffy** [comment]
Although this is intentional, this has never been labeled `bug`(on purpose, I realized that this is on purpose as it matches other update notifs). This might be more of a request to make it be the same as these words are proper nouns, as they are names. If your name is "apple" it would be spelled as "Apple", as a name is a proper noun. According to [this (grammerly.com)](https://www.grammarly.com/blog/proper-nouns/), "A proper noun is a specific (i.e., not generic) name for a particular person, place, or thing.". An addon name is not generic, and is specific. Also, "Proper nouns are always capitalized in English". This means that as this being a name it should be capitalized.

**Comment by RedGuy12** [comment]
It's too late to fix it anyway lol

Sent via the Samsung Galaxy A52 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Shluffy** [comment]
For the future, and maybe change the past part of the changelog.

**Comment by mxmou** [comment]
> An addon name is not generic, and is specific. Also, "Proper nouns are always capitalized in English". This means that as this being a name it should be capitalized.

I don't think addon names are proper nouns (with a few exceptions: Scratch Messaging, Scratch Notifier, Scratch 2.0 → 3.0). Most of them (such as "customizable block colors") are just very short descriptions of what the addon does.
