### ISSUE TITLE
Custom/Preset Page Colors

### ISSUE THREAD

**Issue by LegoManiac04** [ScratchAddons/ScratchAddons#3079]
### Is your request related to a problem? Please describe.
With the new studio update, studios have a blue background, which has shown to be hard to look at for users (such as myself). To me, that's the biggest visual issue with the update.
Of course, with Scratch Addons, you can switch on Dark Mode or Old Studio Layout, but I prefer the 3.0 layout over the addon style, as well as the light mode over the dark mode.

### Describe the solution you'd like
I would love to have the ability to set the page colors to a custom setting, or at least have the ability to set the background color of studio pages to the white seen across Scratch. I greatly enjoy the ability to change stuff like the header color, and I think being able to edit the background would be useful as well, even if it's just presets or maybe even an just an option in the Old Studio Layout addon to make the background white.

**Comment by mxmou** [comment]
Related to #645 - I think allowing all colors to be changed as described there and making the blue background one of the settings is a good solution.

**Comment by WorldLanguages** [comment]
I also noticed this, I'm not sure why studios have a different background color, weird decision by the Scratch Team 🤔
