### ISSUE TITLE
Some suggestions for the paint editor -- Layers, corners and more

### ISSUE THREAD

**Issue by LercDsgn** [ScratchAddons/ScratchAddons#3085]
### All Suggestions: 
_Layer Borders, Layer Visualizing, Corner Point Binding, Move Around Canvas With Hold & Drag_

---

**1. Layer borders**
Ever wanted to get a shape under the border of another shape but not the shape itself? Now you can do this!

**2. Layer Visualizing**
Easily view, switch between and change the order of layers.

**3. Corner Point Binding (Available while the Corner Adjusting Tool is selected)**
Binding corners  are similar to grouping elements on the editor. When you take an action on one, all the connected corners are going to reflect.

**4. Move Around Canvas With Hold & Drag**
With this one, you're no longer stuck at one part of the canvas, zoomed in and trying to move the view a little. Just press, hold, move and ta-da!

Edit, BONUS(-es): 
- **Instantly Draw A Line Between Two Points (Available while the Corner Adjusting Tool is selected)**, 
- **Change Properties (color, layer etc.) Of Area That Selected Points Of A Shape Formed (seperately from the rest of the shape)**.

**Comment by fierin** [comment]
This would go handin hand with onion skinning to make an amazing and intuative experience for people used to drawing apps with similar features.

Similarly i want to see some way for animation interpolation (more advances sujjestion)
