### ISSUE TITLE
Blocks Get Stuck to Mouse Pointer

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#3100]
### Description

After deleting a costume or sound clicking a drop-down that was set to that asset causes the block to be stuck to the mouse.

### Reproduction steps

1. Enable `editor-searchable-dropdowns`
2. In the `Cat` sprite add a switch costume block and set the costume to `cat-b`
2. Delete the `cat-b` costume
3. Click the drop-down on the switch costume block
4. Notice how the block is now stuck to your mouse pointer

### Expected behaviour

After deleting a costume or sound, clicking a drop-down that was set to that asset should bring up the drop-down like normal.

### Actual behaviour

After deleting a costume or sound clicking a drop-down that was set to that asset does not bring up the drop-down, and instead, causes the block to be stuck to the mouse pointer until a page reload.

The console also throws this error right after clicking the drop-down: `Uncaught TypeError: fieldVariable.selectedItem is null` (More info below.)

### Screenshots

https://user-images.githubusercontent.com/81489795/126908828-504c2e77-8d6d-4edf-bc9e-83ecf9449947.mp4

### Environment

- Browser: Firefox 90.0.2
- Scratch Addons version: 1.17.1
- Operating system: Windows 11 on preview build 22000.100 co_release

### Additional context

I don't think this will help much, but here is everything in the console before clicking the drop-down: [browser console.txt](https://github.com/ScratchAddons/ScratchAddons/files/6874367/browser.console.txt) After clicking it, all it did was throw this error:

`Uncaught TypeError: fieldVariable.selectedItem is null
    getItems moz-extension://328c0bf8-ebf5-4258-97d5-64ed47a28ae5/addons/editor-searchable-dropdowns/userscript.js:231
    show moz-extension://328c0bf8-ebf5-4258-97d5-64ed47a28ae5/addons/editor-searchable-dropdowns/userscript.js:37
    showEditor_ https://scratch.mit.edu/js/projects.bundle.js:227
    doFieldClick_ https://scratch.mit.edu/js/projects.bundle.js:227
    handleUp https://scratch.mit.edu/js/projects.bundle.js:227
    r https://scratch.mit.edu/js/projects.bundle.js:227
    bindEventWithChecks_ https://scratch.mit.edu/js/projects.bundle.js:227
    bindMouseEvents https://scratch.mit.edu/js/projects.bundle.js:227
    doStart https://scratch.mit.edu/js/projects.bundle.js:227
    handleWsStart https://scratch.mit.edu/js/projects.bundle.js:227
    onMouseDown_ https://scratch.mit.edu/js/projects.bundle.js:227
    r https://scratch.mit.edu/js/projects.bundle.js:227
userscript.js:231:5
`

I can reproduce on TurboWarp Desktop 0.8.0, but not the TurboWarp website.

**Comment by Shluffy** [comment]
What addons are enabled?

**Comment by Shluffy** [comment]
Default names are `costume1` and `costume2`

**Comment by Samq64** [comment]
> What addons are enabled?

All of them except Custom block shape, Customizable block colors, Display stage on left side,  Messages in editor,  Thumbnails setter, Website dark mode, 2D color picker, Cat blocks, Ctrl+Click to run scripts, Highlight currently executing blocks, Remove curved stage border, Feature unshared projects,  Filter messages on Scratch's messages page,  Profile statistics, True forums YouTube links, Redirect mobile forums to main forums and Semicolon glitch.

**Comment by Shluffy** [comment]
Messed around with this. This is What I find out:

- Cannot repro with SA disabled. Definitly an SA bug.
- Default names are `costume1` and `costume2` (with or without SA)
- Can Repro With SA on
- Costume Name Does Not seem to matter
- Cannot Repro With All addons enabled
-

**Comment by Shluffy** [comment]
Thanks. I am currently messing with this to see what is wrong

**Comment by Samq64** [comment]
> 
> 
> Thanks. I am currently messing with this to see what addon is causing this

It might be searchable drop-downs, but I'm not sure.

**Comment by Shluffy** [comment]
Messed around with this. This is What I find out:

- Cannot repro with SA disabled. Definitly an SA bug.
- Default names are `costume1` and `costume2` (with or without SA)
- Can Repro With SA on
- Costume Name Does Not seem to matter
- Cannot Repro With All addons enabled
- Problem Is in one of these 8 addons: Block Switching, Cat Blocks, Ctrl+click to run scripts, Data category tweaks, dev tools, Do not automatically run duplicated blocks, Save blocks as image, Searchable dropdowns



> > Thanks. I am currently messing with this to see what addon is causing this
> 
> It might be searchable drop-downs, but I'm not sure.

Yes, it is

**Comment by Shluffy** [comment]
You **CAN** click something in the editor and it will go back to it's normal place

**Comment by Samq64** [comment]
> 
> 
> You **CAN** click something in the editor and it will go back to it's normal place

Not for me. Clicking into a different sprite just messes it up even more. (It's still stuck to the mouse, but you can't see it anymore.)

**Comment by Shluffy** [comment]
> You **CAN** click something in the editor and it will go back to it's normal place

although after you can not interact with anything in that stack
or any blocks

**Comment by Shluffy** [comment]
> > You **CAN** click something in the editor and it will go back to it's normal place
> 
> Not for me. Clicking into a different sprite just messes it up even more. (It's still stuck to the mouse, but you can't see it anymore.)

can you provide a video?

**Comment by Samq64** [comment]
> can you provide a video?

Is this good?

https://user-images.githubusercontent.com/81489795/126910013-51c10be5-824b-47dd-a986-3803018eb000.mp4

**Comment by Shluffy** [comment]
i tried clicking the costumes tab

**Comment by Samq64** [comment]
> i tried clicking the costumes tab

The costume and sound editors seem to work fine for me.

**Comment by GarboMuffin** [comment]
was fixed by #3083

**Comment by Samq64** [comment]
> was fixed by #3083

Oops, I didn't see that. I'm glad it will be fixed with the next release though.
