### ISSUE TITLE
Browser colour selection

### ISSUE THREAD

**Issue by Richienb** [ScratchAddons/ScratchAddons#311]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to use colours from another project and I have to convert them to fit within Scratch's proprietary colour system.

**Describe the solution you'd like**

It would be useful if the default colour selection box asking for Colour, Saturation and Brightness is proxied by the browser colour selection box which automatically converts them to the format.

**Describe alternatives you've considered**

See [Converting Scratch Colours](https://stackoverflow.com/questions/63397614/converting-scratch-colours) for the workarounds I used.

**Additional context**

Implementation details:

From the hex colour returned by the `<input type="color">` element, convert it to HSV (Hue, Saturation, Value) so that `Math.round(hue * 5 / 18)` is Colour, Saturation remains the same and Value is Brightness. This allows us to find the closest possible colours.

We could additionally add an option to suggest the closest colours that don't have to be rounded by computing the Colour as `5 * Math.round(hue / 18)`. This would be useful if custom image sprites are used that have colours not normally selectable so that it can still be used in the `is touching colour` block without issues.

Accuracy (red: closest colours, blue: without rounding issues):

[![Accuracy graph](https://user-images.githubusercontent.com/29491356/93710969-93b8fc80-fb9e-11ea-9695-9d9ed1c332a2.png)](https://www.desmos.com/calculator/bqjtqnh5bn)

**Comment by WorldLanguages** [comment]
It would be great so simply add a hex color input.

**Comment by Richienb** [comment]
@WorldLanguages An `<input type="color">` element produces a hex input from a multitude of colour selection options.

**Comment by JeffaloBob** [comment]
i think an input colour would be neat, but having a hex input seems also good because the user's browser/os's colour picker could be lame and not have a hex input. im looking at you windows 10 pre chrome input redesign...

**Comment by GrahamSH-LLK** [comment]
But, this extension only caters to Chromium browsers and firefox.

**Comment by easrng** [comment]
> But, this extension only caters to Chromium browsers and firefox.

Well technically it should work everywhere with WebExtentions.

**Comment by JeffaloBob** [comment]
jeffalo high quality mockup time
![image](https://user-images.githubusercontent.com/40470736/93853158-9d805400-fcb3-11ea-984b-8124fedfeec6.png)
credit to world languages for introducing me to this wonderful colour

**Comment by Richienb** [comment]
I managed to prototype a colour picker: https://codepen.io/Richienb/pen/YzqgLbO

The biggest challenge in implementing browser colour selection is proxying the selections to the actual colour selector. We need to somehow simulate mouse presses that trigger the sliders which is something I haven't been able to do yet. If someone is able to do this, I'll be able to implement the rest of this addon.

**Comment by lisa-wolfgang** [comment]
Perhaps add tabs to the color selector that let you choose between HSB, RGB, or Hex.
It would also be really nice to be able to type in the values for HSB and RGB, or even just Scratch's proprietary color system, rather than getting that darn slider just right. (And the numbers that do display are rounded -- so no two colors are ever quite the same when using the sliders.)

**Comment by Drachenbauer** [comment]
It´s very difficult, to get the main scratch color-picker to take the color from the hexcode of the scratch-addon-color-picker-extension.
Enter does not seem to work well for that.
