### ISSUE TITLE
ScratchStats popup/tab

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#3119]
### Describe the solution you'd like

We should add a new tab in the extension popup. Like the addons, games and messages, tab. At this tab:

1.If the user is visiting the first time, they should enter a username.

2.If the user comes back, the previous username's stats will be displayed.

This saves us from going to scratchstats

We can also add a setting to enable/disable it, making an option of choosing between their username got from scratch API, or entering someone's username and being able to log out to change it)

### Describe alternatives you've considered
None

**Comment by Genius398** [comment]
Good/bad?

**Comment by WorldLanguages** [comment]
I am biased (again :P), but honestly, is user stats something you check often enough to warrant a dedicated popup?

**Comment by mxmou** [comment]
> I am biased (again :P), but honestly, is user stats something you check often enough to warrant a dedicated popup?

Maybe your own stats, but probably not other people's. I don't think there is a reason not to add this if it isn't enabled by default though.

**Comment by Genius398** [comment]
> I am biased (again :P), but honestly, is user stats something you check often enough to warrant a dedicated popup?

Uhhh....yes

**Comment by Genius398** [comment]
> > I am biased (again :P), but honestly, is user stats something you check often enough to warrant a dedicated popup?
> 
> Maybe your own stats, but probably not other people's. I don't think there is a reason not to add this if it isn't enabled by default though.

Yeah, it should be enabled by default

**Comment by mxmou** [comment]
> Yeah, it should be enabled by default

I'm not sure about that: do most people really look at their stats that often?

**Comment by Genius398** [comment]
> > Yeah, it should be enabled by default
> 
> I'm not sure about that: do most people really look at their stats that often?

ya

**Comment by Genius398** [comment]
> > Yeah, it should be enabled by default
> 
> I'm not sure about that: do most people really look at their stats that often?

at least I do

**Comment by retronbv** [comment]
Maybe it could show the stats of the user's profile you are on

**Comment by mxmou** [comment]
> Maybe it could show the stats of the user's profile you are on

There is already a profile statistics addon.

**Comment by retronbv** [comment]
> > Maybe it could show the stats of the user's profile you are on
> 
> There is already a profile statistics addon.

I forgot

**Comment by Genius398** [comment]
ok people this is kinda already there so bye

**Comment by Genius398** [comment]
bye
