### ISSUE TITLE
 Change CSS of My-stuff + 2.0 - 3.0

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#3136]
### Describe the solution you'd like

Like ST has changed up the studios, SA should change up the my-stuff to match the theme. Need I say more?

**Comment by FunctionalMetatable** [comment]
Should be used in `scratchr2` addon.

**Comment by mxmou** [comment]
If you're talking about the Scratch 2.0 → 3.0 addon:

* I think the blue header should remain to match Messages.
* I like the current tab bar, but making it match the studio one (but still centered) would probably be a good idea.
* I'd like the tiles to remain horizontal, but making project thumbnails rounded would match the 3.0 design more closely.

**Comment by Genius398** [comment]
in mystuff, the whole header is small. The blue shade is different. And the tab and project sorting style just doesn't match the 3.0 theme

**Comment by mxmou** [comment]
> in mystuff, the whole header is small. The blue shade is different. And the tab and project sorting style just doesn't match the 3.0 theme

I think this matches the 3.0 theme quite well:
![image](https://user-images.githubusercontent.com/51849865/127305933-03707fce-2fb1-4fe7-a529-a6a82e56814d.png)

Only the tabs and project thumbnails need to be changed.

**Comment by Genius398** [comment]
yes, great! TYSM!!

> > in mystuff, the whole header is small. The blue shade is different. And the tab and project sorting style just doesn't match the 3.0 theme
> 
> I think this matches the 3.0 theme quite well:
> ![image](https://user-images.githubusercontent.com/51849865/127305933-03707fce-2fb1-4fe7-a529-a6a82e56814d.png)
> 
> Only the tabs and project thumbnails need to be changed.

**Comment by Genius398** [comment]
also, should "Old Studio Layout" be combined with 3.0-2.0?

**Comment by mxmou** [comment]
> also, should "Old Studio Layout" be combined with 3.0-2.0?

If a 3.0 → 2.0 addon is ever added, it will probably only change the visual style, not the layout.

**Comment by Genius398** [comment]
> > also, should "Old Studio Layout" be combined with 3.0-2.0?
> 
> If a 3.0 → 2.0 addon is ever added, it will probably only change the visual style, not the layout.

ok

**Comment by FunctionalMetatable** [comment]
Related: #3072
