### ISSUE TITLE
"Demote" people

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#3139]
### Describe the solution you'd like

When we promote someone by accident in a studio, the only way to undo it is to remove and then re-invite them. A button can solve that issue
### Describe alternatives you've considered
You know...to remove and then re-invite them

**Comment by apple502j** [comment]
So, do we make a button to remove and then re-invite users?

**Comment by Genius398** [comment]
.... sort of. we can also directly demote them

**Comment by pufferfish101007** [comment]
> .... sort of. we can also directly demote them

That isn't possible.

**Comment by Genius398** [comment]
then only apple's option is correct

**Comment by Genius398** [comment]
> So, do we make a button to remove and then re-invite users?

this is the way then

**Comment by WorldLanguages** [comment]
Remove them manually and reinvite them manually. A "demote" button that actually kicks people would be either confusing or too complex to explain properly to users.
