### ISSUE TITLE
Player:FullScreen

### ISSUE THREAD

**Issue by fierin** [ScratchAddons/ScratchAddons#3140]
### Description
Add the ability to Turn on a native Full-Screen Similar to the addon linked below (in sources).

### Solution
Add a second maximize button to apply native Full-Screen.

#### Author:
 Fierin Deathbomb
#### Sources:
https://chrome.google.com/webstore/detail/scratch-fullscreen/gihphjdlkigognnhkankfjcclijhadpe

**Comment by TheColaber** [comment]
This is a dupe of an issue made by @pufferfish101007, tho I can't find the issue right now.

**Comment by fierin** [comment]
Oh! Thank you!

**Comment by mxmou** [comment]
> This is a dupe of an issue made by @pufferfish101007, tho I can't find the issue right now.

#587?

**Comment by fierin** [comment]
yes. Thank you.

**Comment by WorldLanguages** [comment]
Duplicate of #587
