### ISSUE TITLE
Making the Editor more like Scratch 2

### ISSUE THREAD

**Issue by Fanjoua** [ScratchAddons/ScratchAddons#3141]
I mean make the **Scratch 3** editor more like **Scratch 2** editor, like as much as you can, like **changing the background color of the editor, changing icon positions** etc.

**Comment by mxmou** [comment]
Related to #985

**Comment by Fanjoua** [comment]
> You can already get pretty close. Just download [this](https://github.com/ScratchAddons/ScratchAddons/files/6893806/scratch.2.0.style.txt), optionally rename the file extension to from `.txt` to `.json`, open up the Scratch Addons settings then click `more settings `> `import settings` and select the file you just downloaded.
> 
> I hope this helps!

yes but still we can get more I guess

**Comment by WorldLanguages** [comment]
One issue per specific 2.0 feature, please

**Comment by mxmou** [comment]
> One issue per specific 2.0 feature, please

I thought this is about the 2.0 visual design.

**Comment by WorldLanguages** [comment]
Ohh. Is there no issue for that yet?
