### ISSUE TITLE
TurboWarp/Forkphorus Player + View in TurboWarp/Forkphorus button Addon

### ISSUE THREAD

**Issue by SamuelTheTechnoKid** [ScratchAddons/ScratchAddons#3145]
Hello, Scratch Addons GitHub! I have a request: You know TurboWarp and Forkphorus, right? Well, I want you to add it to Scratch Addons, please! Or as a View in button or as a replacement!

**Comment by RedGuy12** [comment]
Lol literally will be added next update



________________________________
From: SamuelTheTechnoKid ***@***.***>
Sent: Wednesday, July 28, 2021 1:43:27 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] TurboWarp/Forkphorus Player + View in TurboWarp/Forkphorus button Addon (#3145)


Hello, Scratch Addons GitHub! I have a request: You know TurboWarp and Forkphorus, right? Well, I want you to add it to Scratch Addons, please! Or as a View in button or as a replacement!

**Comment by TheColaber** [comment]
In other words, this is a dupe of another issue

**Comment by WorldLanguages** [comment]
Duplicate of #164

**Comment by fierin** [comment]
yes a dupe

**Comment by retronbv** [comment]
> Duplicate of #164

Yay if it's a dupe that means it's a good idea 🥳🥳🥳

**Comment by fierin** [comment]
> > Duplicate of #164
> 
> Yay if it's a dupe that means it's a good idea 🥳🥳🥳

Could also mean its just popular
