### ISSUE TITLE
[New addon]: Show user id in profiles

### ISSUE THREAD

**Issue by FunctionalMetatable** [ScratchAddons/ScratchAddons#3166]
### Is your request related to a problem? Please describe.

I don't want to go to the API and read raw json always
### Describe the solution you'd like

An addon where it shows the user id of the user on a profile, presumably next to the country of the user, moving the my-ocular status to the right

### Describe alternatives you've considered

None

**Comment by CST1229** [comment]
Or it could do what Magnifier does:
![this](https://user-images.githubusercontent.com/68464103/127645841-f6284160-8259-4837-bcae-5d8b9f08a7cf.png)

**Comment by mxmou** [comment]
Could this be part of the profile statistics addon?

**Comment by CodeGuy92** [comment]
> Or it could do what Magnifier does:
> ![this](https://user-images.githubusercontent.com/68464103/127645841-f6284160-8259-4837-bcae-5d8b9f08a7cf.png)

Aight bet
![image](https://user-images.githubusercontent.com/79767244/127733771-ea79b32a-5896-4617-99b4-3530e90c5dfb.png)

**Comment by CodeGuy92** [comment]
```
let syufddsuyfdsyi = document.getElementsByClassName("header-text")[0].firstElementChild

fetch('http://api.scratch.mit.edu' + location.pathname)
  .then(response => response.json())
  .then(data => syufddsuyfdsyi.insertAdjacentHTML('beforeend', `<font size="3" color="lightgrey">#` + data.id + `</font>`));
```

I tried making some code, but it return this:
```Mixed Content: The page at 'https://scratch.mit.edu/users/LankyBox01/' was loaded over HTTPS, but requested an insecure resource 'http://api.scratch.mit.edu/users/LankyBox01/'. This request has been blocked; the content must be served over HTTPS.```

**Comment by CodeGuy92** [comment]
I made some code that, for some reason, actually works:
```
let syufddsuyfdsyi = document.getElementsByClassName("header-text")[0].firstElementChild

fetch('https://api.scratch.mit.edu' + location.pathname)
  .then(response => response.json())
  .then(data => syufddsuyfdsyi.insertAdjacentHTML('beforeend', `<font size="3" color="lightgrey">#` + data.id + `</font>`));
```

Not joking, try running it:
https://scratch.mit.edu/users/LankyBox01/
https://scratch.mit.edu/users/World_Languages/
https://scratch.mit.edu/users/maximouse/

**Comment by CodeGuy92** [comment]
Time to turn it into an addon-

**Comment by FunctionalMetatable** [comment]
> I made some code that, for some reason, actually works:
> 
> ```
> let syufddsuyfdsyi = document.getElementsByClassName("header-text")[0].firstElementChild
> 
> fetch('https://api.scratch.mit.edu' + location.pathname)
>   .then(response => response.json())
>   .then(data => syufddsuyfdsyi.insertAdjacentHTML('beforeend', `<font size="3" color="lightgrey">#` + data.id + `</font>`));
> ```
> 
> Not joking, try running it:
> https://scratch.mit.edu/users/LankyBox01/
> https://scratch.mit.edu/users/World_Languages/
> https://scratch.mit.edu/users/maximouse/

much easier way

**Comment by CodeGuy92** [comment]
https://github.com/CodeGuy92/ScratchAddons/tree/CodeGuy92-user/addons/user-id
This is my progress, any opinions before i test it locally?

**Comment by FunctionalMetatable** [comment]
don't use insertAdjacentHtml

**Comment by CodeGuy92** [comment]
> don't use insertAdjacentHtml

well, what should i use then? I tried just a basic append, but it inserts the HTML as plain text.

**Comment by FunctionalMetatable** [comment]
> > don't use insertAdjacentHtml
> 
> well, what should i use then? I tried just a basic append, but it inserts the HTML as plain text.

create an actual element and use appendchild

**Comment by CodeGuy92** [comment]
> > > don't use insertAdjacentHtml
> > 
> > 
> > well, what should i use then? I tried just a basic append, but it inserts the HTML as plain text.
> 
> create an actual element and use appendchild

*browsing w3schools*

**Comment by CodeGuy92** [comment]
ok, let me improve the code

**Comment by CodeGuy92** [comment]
I think i fixed it now, have a look.
https://github.com/CodeGuy92/ScratchAddons/blob/CodeGuy92-user/addons/user-id/userscript.js

let me test it locally too, just to be sure

**Comment by CodeGuy92** [comment]
This works, let me make a pull request.

![image](https://user-images.githubusercontent.com/79767244/127734598-ec35d436-ee54-4bfa-a993-3c3f65da0f9c.png)
![image](https://user-images.githubusercontent.com/79767244/127734620-3a5e03dc-3a47-48e1-af54-f06d99798560.png)
