### ISSUE TITLE
"Go to user" tab in popup

### ISSUE THREAD

**Issue by Genius398** [ScratchAddons/ScratchAddons#3167]
### Describe the solution you'd like

A new tab in the popup. We can write a username there, and it will take us to the page I have the code. `javascript: let user = prompt("Which user would you like to go to?"); window.location.href = "https://scratch.mit.edu/users/" + user + "/";`

**Comment by RedGuy12** [comment]
There's already a search user profile addon

**Comment by Genius398** [comment]
> There's already a search user profile addon

ohhh
