### ISSUE TITLE
Romanian translations aren't consistent.

### ISSUE THREAD

**Issue by CodeGuy92** [ScratchAddons/ScratchAddons#3168]
I am from Romania, and i can assure you, everything is wrong here. I can't make a pull request right now, but anyone can just make a commit to fix this.
https://github.com/CodeGuy92/ScratchAddons/commit/dad0c7bba2d2bc173ee019885f2ff80490c43a38
https://github.com/CodeGuy92/ScratchAddons/commit/89765c7c11dd57256004378324c886a47832089d
https://github.com/CodeGuy92/ScratchAddons/commit/248fe627b1bdd9c8cac54f0ef1c20c60ffef15ba
https://github.com/CodeGuy92/ScratchAddons/commit/b393e42defea9a404cc50fe116441229fa7be7ba

**Comment by WorldLanguages** [comment]
Do not edit the JSON files directly
https://scratchaddons.com/docs/localization/joining-the-localization-team/

**Comment by CodeGuy92** [comment]
> Do not edit the JSON files directly
> https://scratchaddons.com/docs/localization/joining-the-localization-team/

But i'm not 18.
