### ISSUE TITLE
Make translation instructions easier to find

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#3177]
Currently, the only locations where a link to instructions about how to help translate are the "Help Translate" button in the Scratch Addons settings and within the docs themselves. This makes it relatively hard to find and even harder to stumble across.

A couple of potential places to put it:
- Under the language dropdown on scratchaddons.com
- In the description for "International" (under the "Features" header) on scratchaddons.com
- In the footer on scratchaddons.com
- In the "Contribute" section of the README in the ScratchAddons repo
- In the "Contributing guidelines" (`CONTRIBUTING.md`) in the ScratchAddons repo
- Some/all of the above

**Comment by WorldLanguages** [comment]
Related: https://github.com/ScratchAddons/website-v2/issues/309

**Comment by WorldLanguages** [comment]
> * In the footer on scratchaddons.com

Just wanted  to point out that including the link in the footer will *probably* result in lower quality submissions. We want to make sure people asking to be translator know about the extension settings page.

> In the "Contribute" section of the README in the ScratchAddons repo

This will probably be added as part as #6387, so I believe merging that PR should close this issue.
