### ISSUE TITLE
Sprites dragging bug

### ISSUE THREAD

**Issue by Medericoder** [ScratchAddons/ScratchAddons#3179]
I think this bug is because of the the "drag sprites" addon.
(In this video, I'm in TurboWarp, and I don't press any key like "Shift" or other...)

https://user-images.githubusercontent.com/80577386/127746486-6a7e3c87-1020-41ff-ba19-95db1698ade9.mp4

**Comment by WorldLanguages** [comment]
@Medericoder Can you try to reproduce the issue on scratch.mit.edu with Scratch Addons installed, and only that addon enabled? (disable all other ones)

**Comment by Medericoder** [comment]
> @Medericoder Can you try to reproduce the issue on scratch.mit.edu with Scratch Addons installed, and only that addon enabled? (disable all other ones)

I tried, and there is no problem 👍

**Comment by TheColaber** [comment]
@Medericoder Great, can you create an issue on Turbowarp's repository? https://github.com/Turbowarp/scratch-gui
