### ISSUE TITLE
Enable All Addons

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#318]
It takes a while to enable every single extension, and it would be more helpful to add a button to enable them all at once.

**Describe the solution you'd like**

Add a button to do that.
**Mockup**

![image](https://user-images.githubusercontent.com/64214252/93807015-0a461080-fc18-11ea-9d65-cc3acf2fa68a.png)

**Comment by JeffaloBob** [comment]
i wonder if it could be changed to have a tickbox kinda layout like gmail, then you could do mass actions like enabling all or disabling all.

**Comment by Explosion-Scratch** [comment]
Yeah, that would work well.

On Monday, September 21, 2020, Jeffalo <notifications@github.com> wrote:
> i wonder if it could be changed to have a tickbox kinda layout like
gmail, then you could do mass actions like enabling all or disabling all.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/JUcaVqkMh_xZebCRlWQkVxm7RI1U9LKJHLfV6C2EauHZYjJHPSbuv85OaEt24STm0Yon10qQmYLlRRszwHpH2-DYReOWMUEO_kN15dmZH0rq2Yt3Y3fMbeybhJV8M-nKpAWDE7IvcK4Y9rzhva8G3uCLSVgaSk3h_0odEOCEBlr3xiFKWJdfqmXJIhzWSmoq6_JMRknkc6OKSOiHk8KtOs3PY-vpCeU19qlE1rnsZw=s0-d-e1-ft#https://github.com/notifications/beacon/AOT2P3VYZA2UAKXYLD2SN2DSG6NNZA5CNFSM4RU3SG6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFGALDSA.gif>

**Comment by BoomerScratch** [comment]
I like this idea :+1:

**Comment by WorldLanguages** [comment]
Related comment: https://github.com/ScratchAddons/ScratchAddons/issues/487#issuecomment-713889252

Relevant part: not all enabled addons can be enabled with a click of a button, because some of them require optional permissions to be accepted by the user.

> Revisiting recommended addons, so many appear to be of personal preference, so I'm not sure whether this is a good idea:
> 
> * Scratch 2.0 → 3.0 is a theme, and likely shouldn't be enabled automatically
> * Scratch Notifier and bitmap images copying require optional permissions, so they can't be enabled automatically
> * Searchable dropdowns might be annoying for some users, because context menus will take more space
> 
> Some recommended addons I see could be enabled by default:
> 
> * Developer tools
> * Project progress bar
> * Studio manager tools
> * YouTube full screen
> 
> Some currently not recommended addons that could be enabled by default (they likely should be recommended?):
> 
> * (not made yet) Ctrl+click to run project muted
> * Alt+click for 60fps
> * Last edit tooltip
> * Search profile
> 
> Other than those, what addons to use is a pretty subjective decision.

**Comment by Explosion-Scratch** [comment]
It's also be nice to have a checkbox sort of system, like in gmail, with
select all, and then to run operations such as toggle, turn off, or turn on
on the selected ones.

**Comment by WorldLanguages** [comment]
After the recent changes, I feel this issue needs updated discussion on whether (or how) to implement this properly.

**Comment by TheColaber** [comment]
> After the recent changes, I feel this issue needs updated discussion on whether (or how) to implement this properly.

I've actually made this... One sec I'll send a link and you tell me what you think.

**Comment by GrahamSH-LLK** [comment]
Your implementation needs better transitions, but overall it looks good.

**Comment by TheColaber** [comment]
Transitions?

**Comment by TheColaber** [comment]
Btw, it enables all addons visible on the screen. So if you have beta addons on screen, it will only turn on those

**Comment by GrahamSH-LLK** [comment]
> Btw, it enables all addons visible on the screen. So if you have beta addons on screen, it will only turn on those

It needs to update the select when you switch tabs.

**Comment by TheColaber** [comment]
> > Btw, it enables all addons visible on the screen. So if you have beta addons on screen, it will only turn on those
> 
> It needs to update the select when you switch tabs.

I mean tbh I think there should just be 2 sperate buttons, you can click on the same button twice

**Comment by WorldLanguages** [comment]
@TheColaber Can you post screenshots and elaborate over the way you did it?

**Comment by TheColaber** [comment]
So we have this new option, to enable all or none.
![image](https://user-images.githubusercontent.com/72760579/99456910-1be62480-28f8-11eb-859f-3e1ae7c06964.png)
When you click on Enable All when you are in Editor and Recommended
![Screenshot 2020-11-17 171419](https://user-images.githubusercontent.com/72760579/99457105-6f587280-28f8-11eb-8e61-3390b71ce171.png)
Now it looks like this:
![image](https://user-images.githubusercontent.com/72760579/99457690-5c926d80-28f9-11eb-9be4-5f2c9e2d3a80.png)
When I go back to all addons... It will look like this:
![image](https://user-images.githubusercontent.com/72760579/99457748-78960f00-28f9-11eb-83e2-333d37dea541.png)
Now I can just press it again... and all addons are enabled!
![image](https://user-images.githubusercontent.com/72760579/99457972-cd398a00-28f9-11eb-8416-ed342c49aeb7.png)
If some permissions are needed for particular addons, it will ask like normally. If you say no to a permission, it will only disable the addon that needs that permission.

The code basically just finds all visible addons and clicks on the switches.

**Comment by WorldLanguages** [comment]
2021 note: PRs for this might be accepted, but the UX would need to be tweak in order to not be confusing.

**Comment by mxmou** [comment]
There are multiple problems with this:
* Some addons have warnings. I don't think there is a way to make sure that users read all warnings when enabling all addons.
* This wouldn't actually enable all features we provide because some are settings that are disabled by default.
* This would require changing all addons that add UI to Scratch to clearly indicate which parts of the UI are added by SA.

**Comment by WorldLanguages** [comment]
Yeah this issue is pretty outdated :P

**Comment by mxmou** [comment]
Now that addon groups exist, I think there is actually a good way to implement this. It could be done by adding switches to the Enabled and Recommended groups. Clicking the switch next to Enabled, which would be initially on, would disable all addons. Clicking the switch next to Recommended would enable all recommended addons.

One issue with this is that at least hide-flyout, customizable-something addons and Scratch Notifier probably shouldn't be enabled without asking the user first.

**Comment by WorldLanguages** [comment]
> One issue with this is that at least hide-flyout, customizable-something addons and Scratch Notifier probably shouldn't be enabled without asking the user first.

We could probably work around that by having a new tag/group for "good addons but not for everyone", and remove those from recommended. Those 3 addons and some others should be included there.
So all groups would be:
- New
- Enabled
- Recommended (enabled by default addons, addons that add reasonable features like copy link to comment and confirm project sharing, addons that need user interaction to work like alt+greenflag for 60fps, or that add little useful icons in the editor that you can visually ignore like onion skinning)
- "Good addons" (hide-flyout, customizable zoom/transparency/whatever, Scratch Notifier, more links, cat blocks, profile statistics)
- Others (I'd like to see most forum addons being here, since I doubt most of our users actively use the forums)
- Beta (beta and dangerous)

**Comment by RedGuy12** [comment]
"Opinionated addons" for the new category?
________________________________

**Comment by mxmou** [comment]
> "Opinionated addons" for the new category?

Maybe something like "Featured".

**Comment by lisa-wolfgang** [comment]
Maybe add a new section called "Highly recommended" or "Essential" and make it a gold color, then put the enabled-by-default addons there?
The issue with other names is that they're ambiguous in status compared to "Recommended" -- it should be clear that the new section is different.

**Comment by WorldLanguages** [comment]
No mass enable.

**Comment by mxmou** [comment]
> No mass enable.

Even for addons that are enabled by default?

**Comment by mxmou** [comment]
This issue is also about disabling all addons at once, which probably isn't rejected.

**Comment by WorldLanguages** [comment]
Well you're right, but let's please open another issue and include those comments as modern context. This one is one year old.
