### ISSUE TITLE
Stage is On Left When I'm Signed in

### ISSUE THREAD

**Issue by UtterDonkey** [ScratchAddons/ScratchAddons#3187]
I have stage on left disabled, and it works fine - until I sign in. When I sign in, it goes to the left side?!? Now, when I sign in, I turn stage on left on so it's on the right side.

### Reproduction
I can't manage to reproduce

 

### What Should Happen
Stage is always on right, unless stage on left in enabled.

### Environment

- Browser: Edge
- Scratch Addons version: latest
- Operating system: Windows 10 64-bit

**Comment by CST1229** [comment]
Do you have Better3.0 installed? (For me, when I installed it, the stage automatically went to the left even with that addon disabled)

**Comment by UtterDonkey** [comment]
I can't remember if I removed Better3.0. would that only text or when I'm Signed in?

**Comment by CST1229** [comment]
What?

**Comment by UtterDonkey** [comment]
Yes I have better3.0! I have remove it and it works fine now. Thanks so much for your help!!
