### ISSUE TITLE
addon.tab.createModal

### ISSUE THREAD

**Issue by FunctionalMetatable** [ScratchAddons/ScratchAddons#3191]
### Is your request related to a problem? Please describe.

I see few addons making scratch-www modals (like the studio-followers one + gamepad) and they all duplicate work by creating different modals. I am also creating an issue for this as I want to create the "Secret Lives" addon but it doesn't seem like i should write more code for these modals :/
### Describe the solution you'd like

An addon api, presumably addon.tab.createModal that can create a modal for an addon
### Describe alternatives you've considered

N/A

### Additional context

```javascript
addon.tab.createModal(title: String, isScratchGui: Boolean /* For different css classes */) <Element>
```

**Comment by mxmou** [comment]
I think the function should return an object with the content element and two functions (open and close). I'm not sure if it should handle the close button or leave that to the addon. There should also be an additional parameter to specify a class for the modal container to allow custom CSS.

The DOM structure of modals is:
* Editor:
  * div class="`modal_modal-overlay_<hash>`" dir=`addon.tab.direction`
    * div class="`modal_modal-content_<hash>`"
      * div class="`modal_header_<hash>`"
        * div class="`modal_header-item_<hash> modal_header-item-title_<hash>`"
          * title
        * div class="`modal_header-item_<hash> modal_header-item-close_<hash>`"
          * div class="`close-button_close-button_<hash> close-button_large_<hash>`"
            * img class="`close-button_close-icon_<hash>`" src="`/static/assets/cb666b99d3528f91b52f985dfb102afa.svg`"
      * content: div
* scratch-www:
  * div class="`modal-overlay`"
    * div class="`modal-content modal-sizes`"
      * div class="`modal-content-close`"
        * img class="`modal-content-close-img` src="`/svgs/modal/close-x.svg`"
      * div class="`modal-header`"
        * div class="`modal-title`"
          * title
      * content: div class="`modal-inner-content`"
* scratchr2:
  * div class="`modal-backdrop fade in`" (only when open)
  * div class="`modal hide fade` (and `in` when it's open)"
    * div class="`modal-header`"
      * span class="`close`"
        * `×`
      * h3
        * title
    * content: div class="`modal-body`"

**Comment by mxmou** [comment]
Existing addons that could use this are:
* editor-devtools
* gamepad
* mediarecorder
* studio-followers

Not debugger because it makes a card, not a modal. Addons that currently use `alert()` or `confirm()` could also be changed to use this API, especially if a specialized function for simple messages and confirmations is added.

**Comment by WorldLanguages** [comment]
I like being able to move addons like confirm sprite deletion to stop using confirm().
This might be a bit tricky tho, because some Scratch modals support using browser back button to close them (like "create variable" prompt) and I'm not sure if we should copy that (but potentially break stuff) or be inconsistent intentionally.

**Comment by mxmou** [comment]
> I like being able to move addons like confirm sprite deletion to stop using confirm().
> This might be a bit tricky tho, because some Scratch modals support using browser back button to close them (like "create variable" prompt) and I'm not sure if we should copy that (but potentially break stuff) or be inconsistent intentionally.

The editor supports using the back button for closing modals, but not the forward button for reopening them. I don't think we should copy that.

**Comment by apple502j** [comment]
Note that it may be impossible to use our own modal - especially if we rely on them being synchronously executing. If we are overriding, say VM function, then we can't change the return type to Promise ourselves, unless the function is already returning promise. (Talking to you, remove-sprite-confirm)

**Comment by WorldLanguages** [comment]
> Note that it may be impossible to use our own modal - especially if we rely on them being synchronously executing. If we are overriding, say VM function, then we can't change the return type to Promise ourselves, unless the function is already returning promise. (Talking to you, remove-sprite-confirm)

Good point! Haven't considered that!
