### ISSUE TITLE
Make the 403 page actually work

### ISSUE THREAD

**Issue by FunctionalMetatable** [ScratchAddons/ScratchAddons#3194]
### Is your request related to a problem? Please describe.

Do you remember https://scratch.mit.edu/403/? Well, it's never been used yet..
### Describe the solution you'd like

~~Actually create our own scratch-www based 403 page **or**~~ copy over the scratchr2 page
### Describe alternatives you've considered

n/a

**Comment by apple502j** [comment]
Are you asking for www-ification of the page?

**Comment by mxmou** [comment]
> Are you asking for www-ification of the page?

I think they want 403s (in the forums) to show a page and not just the browser's default message.

**Comment by lisa-wolfgang** [comment]
This issue will probably be closed, as the page does indeed exist as of now.
