### ISSUE TITLE
A better way to see unshared projects

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#3222]
Alright, this one might be controversial and is going to make someone angry (and I bet Apple will close this because Apple being Apple), but hear me out.

Here are the reasons.

1. It is still not fixed, even after numerous of calls to the Scratch Team.  
I couldn't find one, but I think it's safe to assume so.
2. Other players (such as TurboWarp) can run it just with the ID.
3. It is probably a open secret for now.  
There are some people are sharing their unshared project using TurboWarp. If they didn't know, I think it is the best interest to make them aware of it, to fight the false sense of privacy.
4. It is already proposed multiple times.  
At least twice, long time ago, at #70 and #91.

My idea is to have a button on not found project page. No need to check if it is exist (if you do, sure). Just a button that said "you can try use...." You can, say, implement a player to run it, but for now, let's just keep it simple.

**Comment by WorldLanguages** [comment]
*Probably* fine. Users can already use TurboWarp, or even the default-project addon.

**Comment by WorldLanguages** [comment]
Apparently when I posted the previous comment, I forgot about a conversation I had with griffpatch on September 2020, before Scratch Addons was actually released to the masses. All messages by griffpatch, comments between square brackets by me:

> Not sure we should have an extension to view deleted comments except perhaps on your own profile.

> Still not sure about the deleted comment thing...

> Lol - sadly [view unshared projects] is probably a good idea to keep off too

> And yes - that update cloud variables or pretend to be a different user one is right out there

**Comment by WorldLanguages** [comment]
Unshared projects will be actually private eventually

https://docs.turbowarp.org/unshared-projects
