### ISSUE TITLE
Clicking the gear on the exension popup does not open the settings page

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#3234]
### Description

When I open the extension popup and click the settings icon the popup closes, but nothing happens.

### Repoduction steps

1.  Click to the Scratch Addons icon on the right side of your browser's toolbar.
2. Click on the gaer icon.
3. The popup closes, but the seetings page does not open.

### Expected behaviour
When clicking the gear icon on the popup, the settings page should open.

### Actual behaviour

The settings page does not open.

### Screenshots

Screenshots are not very helpful here and when screen recording, the extension popup is filtered out.

### Environment

- Browser: Firefox 90.0.2
- Scratch Addons version: 1.18.0
- Operating system: Windows 11 running insider preview build 22000.100 co_release

### Additional context

This does not affect any other method of opening settings like clicking the "open full screen settings" button on the addons tab.

**Comment by apple502j** [comment]
Cannot reproduce - can you reproduce this consistently?

**Comment by Samq64** [comment]
> Cannot reproduce - can you reproduce this consistently?

Yes, it was happening consistently before, but I just disabled and re-enabeed Scratch Addons and it works fine now.

Sorry for not trying simple things before making an issue.
