### ISSUE TITLE
Allow createing new list items through the `variable-manager` addon by pressing enter.

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#3235]
### Is your request related to a problem? Please describe.

When using the `variable-manager` addon it's annoying that I can't create new list items by pressing enter because it unfocuses the texteara.

### Describe the solution you'd like

Pressing enter while editing a list using the  `variable-manager` addon should create a new list item.

### Describe alternatives you've considered

Using the list monitor on the stage or use pressing shift+enter on the textarea to create new list items.

**Comment by RedGuy12** [comment]
Good idea. We could change to using Shift+Enter or Ctrl+Enter for unfocusing.

**Comment by mxmou** [comment]
Shift+Enter is used to insert items, but that should probably be made clear in the UI.

**Comment by Samq64** [comment]
> 
> 
> Shift+Enter is used to insert items, but that should probably be made clear in the UI.

Thank you so much for telling me that!
