### ISSUE TITLE
Some users can't scroll studio-followers modal if infinite-scroll is enabled

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#3238]
Cannot reproduce myself.

> Sorry if my comment is the same as the one bellow but the followers bar on studios IS AWSOME AND I LOVE THE FORMAT!!! But 1 probem it only shows 28 of your followers but i have 900+, Im not sure why. 

https://scratch.mit.edu/users/World_Languages/#comments-153270248

There was some feedback on scratchaddons.com/feedback as well but I won't try to search for it.
Pretty sure this bug existed before 1.18.0 release

**Comment by WorldLanguages** [comment]
New feedback today:

> The browse followers glitch
Today when I was creating a new studio, I wanted to invite all my followers but surprisingly i could only add that much followers that were on my screen i couldnt scroll down or up to invite more people. I would be happy if this glitch is being fixed. thank you

**Comment by WorldLanguages** [comment]
If this isn't fixed by v1.19.0 maybe we should disable infinite scrolling in that part of studios

Also, I'm not sure if people reporting this have old-studio-layout on or off. That might change things.

**Comment by WorldLanguages** [comment]
All feedback reports from modern Chrome (91 and 92)

**Comment by FunctionalMetatable** [comment]
cant repro

maybe its because i dont have that much followers? idk

**Comment by WorldLanguages** [comment]
Whoops I forgot lol

**Comment by WorldLanguages** [comment]
Well, the bug itself is "fixed" as we removed the feature...
See #5419 as well
