### ISSUE TITLE
High resolution thumbnails addon

### ISSUE THREAD

**Issue by towerofnix** [ScratchAddons/ScratchAddons#3239]
### Is your request related to a problem? Please describe.

Scratch's website embeds a variety of bitmap thumbnails across the site: user profile pictures and project/studio covers are the main ones. Generally, Scratch aims not to waste users' internet data, so the images are actually thumbnails, hard-coded to (approximately) the portion of the screen the image will actually take up. But for some people, data usage isn't a significant issue, and their screens display at a higher resolution than the images were intended to be seen at! This leaves blurry/pixelly images that are a bit of a sore to look at, and miss out on a lot of the original detail.

(Retina/high-DPI screens are the biggest example since they're automatically using 4x the pixels to display as Scratch expects, so images look like your resolution's just a normal non-retina display for the most part. Personally, I don't have a retina display, but I usually have browser pages zoomed 120-150%, because I have bad eyesight and like reading to be easy instead of terrible. :P That means images are scaled up too though, so I get blurry images as well.)

### Describe the solution you'd like

An addon which automatically updates the source URLs for images to a higher resolution would be very nice! Just hardcoding to 2x the default dimensions (so 4x pixels) would be plenty I think, though a slider to let the user pick could be cool too. (Some people probably only need 1.2x or so for example, while others could use higher if they zoom in a lot.)

It should definitely have a warning that clearly shows it'll use more data to load images too, though. (I haven't actually fact-checked this but I'd guess it's probably exponential, so 3x upscale would be a way bigger file than 2x, which itself is already significantly larger than the default 1x?)

### Describe alternatives you've considered

Honestly, there aren't any good alternatives I can think of besides just looking at blurry images. Which is fine, but suboptimal, and something an addon could do well. :P

I guess one alternative is badgering the Scratch Team to do bigger thumbnails, or spooky dynamic image loading :ghost:, themselves, but they probably won't because the data impact is too big (on both users' data plans and the ST's own CDNs) and the code could be too risky to publish to millions of active users. It'd work better as an addon because then users can choose to opt into high-res thumbnails themselves, with an understanding of data usage consequences.

### Additional context

Oh wait one more alternative is always using the site at 100% zoom on non-retina displays.

Except that's bad because then I can't see.

:shipit:

**Comment by FunctionalMetatable** [comment]
i'm thinking something like this

```javascript
export default async function ({ addon }) {
  main: while (true) {
    const image = await addon.tab.waitForElement("img", {
      markAsSeen: true,
    });

    const cdn2 = /\/get_image\/(\w+)\/(\d+)_(\d+)x(\d+).(\w+)/;
    const uploads = /\/((?:[a-z]|\/)+)\/(\d+).(\w+)/;

    let match = cdn2.exec(image.src) || uploads.exec(image.src);

    if (match) {
      // uploads 1st param parsing
      if (match.length !== 5) {
        let type = "";

        switch (match[1].split("/")[0]) {
          case "projects":
            type = "project";
            break;
          case "galleries":
            type = "gallery";
            break;
          case "users":
            type = "user";
            break;
          default:
            type = "";
            continue main;
        }

        match[1] = type;
      } else {
        image.width = match[3];
        image.height = match[4];
      }
      image.src = `https://cdn2.scratch.mit.edu/get_image/${match[1]}/${match[2]}_9200x3600.png?time=${Date.now()}`; // Prevent cache
    }
  }
}
```

**Comment by towerofnix** [comment]
Nice, I was hoping someone else would write prototype code!

I do want to comment on this line though :P

```
image.src = `https://cdn2.scratch.mit.edu/get_image/${match[1]}/${match[2]}_9200x3600.png?time=${Date.now()}`; // Prevent cache
```

This is the greatest extreme of my suggestion, and while it's good to see what's possible, we should hesitate before using that as the final solution. (I know this is prototype code so maybe you didn't mean it to be. :P Just saying, here!)

I don't think we should disable the cache. That would be a markedly unnecessary strain on both browser image processing and data usage, considering avatars and thumbnails don't generally update *that* frequently. And though it's only ever going to be relatively few people using this addon (compared to the entire Scratch community), it would still be less than optimal to put that type of strain on Scratch's CDNs too.

I also don't think we should fetch the original resolution ("`9200x3600`", i.e. let Scratch give whatever's biggest). Especially for avatars which can be quite large, that's a lot of image data which will just never show up on the screen. That's why I recommended the slider—then users can choose the resolution they personally need, without going overkill!
