### ISSUE TITLE
Announcement: road to v1.0.0

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#324]
Lol you likely expect a long announcement but it's not much I have to say:

We expect to upload v1.0.0 into the Chrome Web Store for review in the following days.
New addons won't be accepted until release, or October 1st, whatever happens first.
After a 24 hour period without any bug fixes, either on addons or the "extension itself", I'll consider the current state of master as v1.0.0, make a nice .zip and add it to the releases tab. And of course, submit it to the Chrome Web Store.
After everything went OK in the Chrome Web Store, we'll be releasing on Firefox.
Keep in mind Scratch Addons will be uploaded as a replacement for Scratch Messaging Extension by griffpatch, so the current install links on https://ScratchAddons.com link to that for now.
The release might be blocked a few more days until we make the final edits to the website (scratchaddons.com)

That's all folks, thanks for helping out.

**Comment by Hans5958** [comment]
Finally the real issue

Megre #288 pls?

**Comment by Explosion-Scratch** [comment]
Also, why not use branches and accept new addons and add more features on a
beta branch? That's litterally what they're for...

On Wednesday, September 23, 2020, Hans5958 <notifications@github.com> wrote:
> Finally the real issue
>
> Megre #288 pls?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/xqP9odd-FyLJxL6AFjc3u3YvCYRqNDASjirsKi0IfUYxYIfYgqe_YmCJAR5LEZLMS8zQyTK0xXX5UV99dcUHwbS8SZFXiXySGMtH4clkz26Zjpz540qRarovl4VgkhSFWFb3NKpfIBjA66J5LcUxaUVfqIeHJ3zGvs5lM1_rdJtbK4TGcIAXj9pMt8E86XdYlYhTipeHwWx9jr3mNYAMu2zO3xY2g7cIYG5unmkK1w=s0-d-e1-ft#https://github.com/notifications/beacon/AOT2P3QZUDV26TC4DRMWOSLSHE37ZA5CNFSM4RWL2VP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFGGBGJI.gif>

**Comment by WorldLanguages** [comment]
@Explosion-Scratch I did not mean to say PR aren't going to be accepted. I meant to say new addons won't be released as part of v1.0.0

**Comment by JeffaloBob** [comment]
🎉🎉🎉🎉🎉

**Comment by GrahamSH-LLK** [comment]
Wohoo! v1.0.0 zipped and released on github!

**Comment by JeffaloBob** [comment]
wooooooo!!!

**Comment by tb148** [comment]
What about firefox?

**Comment by WorldLanguages** [comment]
I'll be uploading to Firefox today, I think.

**Comment by JeffaloBob** [comment]
chrome release 🥇 thank you world language 👑

**Comment by WorldLanguages** [comment]
Still waiting for griffpatch for Firefox release :P

**Comment by Hans5958** [comment]
> 
> 
> Still waiting for griffpatch for Firefox release :P

griffpatch was online a while ago

**Comment by Explosion-Scratch** [comment]
@Hans5958 I can't tell if that's cool, funny, creepy, or just plain wierd XD

On Sunday, September 27, 2020, Hans5958 <notifications@github.com> wrote:
> Still waiting for griffpatch for Firefox release :P
>
> griffpatch was online a while ago
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/zjeUCjUIdak5IOpK9WTg_7BVmrVXv869RR-_Gr4o7GYctpdhCiQ-vvdrA83apYhlc9nZ6OaT6nkck7GerF_9JAUOlGVjwUY5acV-mRbYKmRiaOyiQTQUBRV8ZRs3QbvbGZhZ6K0gGj5JUXsARcG2U4je8RQ9yqAxNkG_ZsnvFkpywZBQQ1s82wuyv2bjtunMHIEeAaB1SDjnOvZtcvy6RnmfVRNFfXcXIp_16Oas6A=s0-d-e1-ft#https://github.com/notifications/beacon/AOT2P3QF5VXCBJS5MTQD5LLSH5KTJA5CNFSM4RWL2VP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFGZ4Z2A.gif>

**Comment by Hans5958** [comment]
> @Hans5958 I can't tell if that's cool, funny, creepy, or just plain wierd XD
Well, I'm not stalking. I was on the discussion.

**Comment by Explosion-Scratch** [comment]
XD

On Monday, September 28, 2020, Hans5958 <notifications@github.com> wrote:
> @Hans5958 I can't tell if that's cool, funny, creepy, or just plain wierd
XD
> Well, I'm not stalking. I was on the discussion.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/DUgUAGD9DtvJ0TYfC8WsM9ibWwwi7nfY_zcMCr3QmKBhT_KZhYxBWeBuPfEXrBZNz9xIaGPIXU1LJBexpMvqHkyl4x6CMkuP2mehiapdQb_FeCguyg8eNQ-popZcuuByYzDWFv1cGeRFhf1tIxMRiiEPAe9P0lL9zFdaq-krZPx1Y3urrotOZgUiL7pPhY2VbxWZtIK_EDvttGSgQcb9bwnQ6FOt0seBw6cfjncVbw=s0-d-e1-ft#https://github.com/notifications/beacon/AOT2P3TBH2OMYU7EBCKRUZ3SH7TZ7A5CNFSM4RWL2VP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFG2PXWY.gif>

**Comment by WorldLanguages** [comment]
Now available on Firefox:
https://addons.mozilla.org/en-GB/firefox/addon/scratch-messaging-extension/
Closing!
