### ISSUE TITLE
SA sometimes doesnt load

### ISSUE THREAD

**Issue by FunctionalMetatable** [ScratchAddons/ScratchAddons#3242]
### Description
Sometimes, SA doesn't load in pages.

### Reproduction steps
N/A, happens randomly on dev instance

### Expected behaviour

SA loading properly

### Actual behaviour

SA not loading at all on some pages randomly

### Screenshots

![css](https://user-images.githubusercontent.com/67440879/128351454-8e15e6a7-4ace-43fd-88e5-d5ed152ea4ed.JPG)
![handle-messages](https://user-images.githubusercontent.com/67440879/128351457-35d1acd7-5bc8-418e-b812-93872f0d5a43.JPG)
![messages](https://user-images.githubusercontent.com/67440879/128351459-512b4618-713c-4213-963e-119da542deb6.JPG)
![runtime](https://user-images.githubusercontent.com/67440879/128351460-a8f6342f-126f-455a-a504-4ef3b92c3832.JPG)

### Environment

- Browser: Edge 92
- Scratch Addons version: v1.18.0 (local)
- Operating system: Windows 10

**Comment by TheColaber** [comment]
The first image is fine, that happens to everyone. The other 3 aren't supposed to happen.

**Comment by FunctionalMetatable** [comment]
The last image is the one thats breaking SA on pages i think as the background cannot connect to content script

**Comment by mxmou** [comment]
I think this the same issue as #2451.

**Comment by FunctionalMetatable** [comment]
Related: [StackOverflow: How to fix 'Unchecked runtime.lastError: The message port closed..](https://stackoverflow.com/questions/54126343/how-to-fix-unchecked-runtime-lasterror-the-message-port-closed-before-a-respon#56483156)

**Comment by apple502j** [comment]
The first is fine. the second and third are not fine, but they shouldn't cause crashes. The fourth one - i don't know.

I'd recommend opening devtools 24/7 to capture the error in real time.

**Comment by FunctionalMetatable** [comment]
> I'd recommend opening devtools 24/7 to capture the error in real time.

Background page doesn't show any errors.

Only this in scratch, possibly content-script
```
scratch.mit.edu/:1 Unchecked runtime.lastError: The message port closed before a response was received.
```

**Comment by FunctionalMetatable** [comment]
Also, this errors in edge:
```error
text-color.js:3 Uncaught (in promise) TypeError: hex.substring is not a function
    at parseHex (text-color.js:3)
    at Object.textColor (text-color.js:70)
    at getColor (cs.js:238)
    at setCssVariables (cs.js:270)
    at onInfoAvailable (cs.js:309)
    at onResponse (cs.js:39)
parseHex @ text-color.js:3
textColor @ text-color.js:70
getColor @ cs.js:238
setCssVariables @ cs.js:270
onInfoAvailable @ cs.js:309
onResponse @ cs.js:39
```

**Comment by apple502j** [comment]
Okay, thanks for the traceback. That is a bug we can fix. @FunctionalMetatable 

As for Chrome: "The message port closed before a response was received." is a catch-all phrase for any bug present in background script, iirc.

**Comment by apple502j** [comment]
@FunctionalMetatable What addon did you have on Edge installation?

**Comment by FunctionalMetatable** [comment]
> @FunctionalMetatable What addon did you have on Edge installation?

Version: v1.19.0-pre
Addons: Scratch 2.0 → 3.0 was creating that error

**Comment by apple502j** [comment]
@FunctionalMetatable Can you consistently reproduce the bug? The only way I can think of is at installation time, when Scratch tab is already open...

**Comment by FunctionalMetatable** [comment]
> @FunctionalMetatable Can you consistently reproduce the bug? The only way I can think of is at installation time, when Scratch tab is already open...

yeah, it blocks all addons from running..

wait i fixed it, the settings were broken and there was no value for it
