### ISSUE TITLE
Wrong Label

### ISSUE THREAD

**Issue by Medericoder** [ScratchAddons/ScratchAddons#3244]
Hi! There is a wrong label with the new "TurboWarp" button (when the Scratch button is hovered over by the mouse pointer)!

https://user-images.githubusercontent.com/80577386/128373616-541b0091-044b-4b12-8487-abe91fa4d442.mp4

**Comment by Medericoder** [comment]
Can I be a beta tester? I don't know how to become one.

**Comment by apple502j** [comment]
Well, you are a beta tester now! It's not like you need to register or something.

**Comment by CodeGuy92** [comment]
time to make a pull request boi-

**Comment by Secret-chest** [comment]
> Can I be a beta tester? I don't know how to become one.

@Medericoder Download from the repo and install from source!

**Comment by WorldLanguages** [comment]
lol nice video
