### ISSUE TITLE
Blocks Category Icons

### ISSUE THREAD

**Issue by Medericoder** [ScratchAddons/ScratchAddons#3246]
Two things :

- The "Addons" category needs a custom icon.
- It's strange that extensions don't have the same shape (with a colored circle and a white icon). I think it needs improvement.

![image](https://user-images.githubusercontent.com/80577386/128381969-10c11ba9-50c4-404e-9080-cd4d5f81eb4c.png)

**Comment by CST1229** [comment]
Also, keep in mind that in SA, the category added by the debugger has the Scratch Addons icon and is named Debugger. Try making an issue in the [TurboWarp repo](https://github.com/TurboWarp/scratch-gui/issues).
![kép](https://user-images.githubusercontent.com/68464103/128398171-10631fa9-786d-4db7-956e-b7530ad1dac9.png)
![kép](https://user-images.githubusercontent.com/68464103/128398181-234c8e54-7d46-46bc-9de3-0f1520ebc6a6.png)
(Note: The labelless categories are just a userstyle I made)
