### ISSUE TITLE
Glitch with Gamepad Settings

### ISSUE THREAD

**Issue by joeandericsatudios1** [ScratchAddons/ScratchAddons#3247]
When you open the gamepad settings in the Editor, no text shows up. But when it's opened in the Project Page or Player, it does. Can you fix it please?

-joeandericstudios1

**Comment by apple502j** [comment]
Screenshots and error at console (press f12)?

**Comment by joeandericsatudios1** [comment]
![image](https://user-images.githubusercontent.com/85552963/128839965-6233eedf-2e7c-471f-a721-4bedc1e4faa4.png)
![Screenshot (168)](https://user-images.githubusercontent.com/85552963/128840115-bc8c7ab8-66df-4c2b-9e09-8ecf37491229.png)

**Comment by WorldLanguages** [comment]
@GarboMuffin ?

**Comment by RedGuy12** [comment]
looks like there's also a darkmode bug...

**Comment by GarboMuffin** [comment]
I can't reproduce this without additional logs or information

**Comment by RedGuy12** [comment]
idea: maybe dark mode is turning the text and the background white

**Comment by WorldLanguages** [comment]
@joeandericsatudios1 Can you try to reproduce the bug with both dark modes disabled?

**Comment by joeandericsatudios1** [comment]
Got it fixed. I had a completely different scratch extension with THAT one's dark mode on too. It might have been that then!
