### ISSUE TITLE
Inspect element

### ISSUE THREAD

**Issue by CodeGuy92** [ScratchAddons/ScratchAddons#3248]
### Description

You can inspect element Inputs in addons to modify "min" and "max" attributes.

### Repoduction steps

1. Go to chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/webpages/settings/index.html
2. Select "More Items per Row"
3. Inspect element any input and set the min/max attributes to any value
4. Test it

### Expected behaviour

You should not be able to use inspect element at all, honestly.

### Actual behaviour

You can inspect element Inputs in addons.

### Screenshots

![image](https://user-images.githubusercontent.com/79767244/128398598-d20d228f-e446-436e-aaeb-766f3c916022.png)
![image](https://user-images.githubusercontent.com/79767244/128398626-6c735844-6a1e-44e5-b3d8-dad05f8ea314.png)

### Environment

- Browser: Chrome 92
- Scratch Addons version: v1.18.0
- Operating system: Windows 10 Home

### Additional context

e

**Comment by apple502j** [comment]
Uhh what? Is this a bug?

**Comment by WorldLanguages** [comment]
@CodeGuy92 This is intentional users are free to experiment with invalid settings.

**Comment by CodeGuy92** [comment]
> @CodeGuy92 This is intentional users are free to experiment with invalid settings.

Alright.

**Comment by RedGuy12** [comment]
Maybe not "intentional" but definitely impossible to fix.



________________________________

**Comment by TheColaber** [comment]
Not impossible with javascript checkers. But this intentional, its what wl told me to do when I wanted 10fps.
