### ISSUE TITLE
Make a project player tab

### ISSUE THREAD

**Issue by era2010-coder** [ScratchAddons/ScratchAddons#3249]
Make a project player tab so you can run Scratch projects in the pop-up.

**Comment by mxmou** [comment]
Why would you want to do that in the popup?

**Comment by era2010-coder** [comment]
because it would be good so you can be playing a Scratch game and be doing something else.

**Comment by apple502j** [comment]
Popup is too small and can close at any time.

If you mean opening a popup window, then duplicate of #1993.
