### ISSUE TITLE
Warns

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#325]
**Describe the bug**

This isn't quite a bug, but it's something that should be fixed before the 1.0 release. There are 2 warns from Vue. 
[Vue warn]: <div v-for="tag of tags" v-if="tag.tabShow[selectedTab]">: Using v-if and v-for on the same element is not recommended - consider filtering the source Array instead.
[Vue warn]: Unknown custom element: <switch> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**To Reproduce**

- Open extensions page
- See Warns

**Expected behavior**

No warns

**Device (please complete the following information):**

ChromeOS

**Comment by WorldLanguages** [comment]
> something that should be fixed before the 1.0 release

Not really, these are warns, not errors :P

**Comment by GrahamSH-LLK** [comment]
But will the chrome reviewers get that...

**Comment by WorldLanguages** [comment]
Both clearly say they're warnings, not errors.

**Comment by GrahamSH-LLK** [comment]
True.

**Comment by WorldLanguages** [comment]
I'll try to fix them soon, so reopening :P

**Comment by GrahamSH-LLK** [comment]
Ok.
