### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#326]
**Describe the bug**

When I clicked the icon it gave me this
![image](https://user-images.githubusercontent.com/61319150/94075424-cd694d80-fdc0-11ea-9606-99c8af5109cd.png)

**To Reproduce**

Click the extension icon.

**Expected behavior**

It should work.

**Screenshots**
![image](https://user-images.githubusercontent.com/61319150/94075469-e114b400-fdc0-11ea-92f2-44f0fdc42c0e.png)
**Device (please complete the following information):**

- OS: Chrome OS
- Browser: Chrome
- Version: Latest

**Additional context**

No.

**Comment by WorldLanguages** [comment]
@Explosion-Scratch, looks like you overwrote, or deleted, the folder you imported Scratch Addons from.

**Comment by Explosion-Scratch** [comment]
That's what I thought. I'll try reinstalling it.
