### ISSUE TITLE
Hide editor dark mode "dark scrollbars" setting on Firefox

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#3267]
### Is your request related to a problem? Please describe.

The dark scrollbars setting has no effect on Firefox, and it's unnecessary anyway because Firefox changes scrollbars automatically based on the background color.

### Describe the solution you'd like

Hide the setting on Firefox.

### Describe alternatives you've considered

Make it do something on Firefox - possibly by setting the scrollbar color to light gray when it's disabled.

**Comment by WorldLanguages** [comment]
```json
{
  "if": {
    "browser": "moz|cr"
  }
}
```
?

Keep in mind that currently all conditions inside ifs are OR, not AND. Works for now but probably not forever. Here it should be clearly be an AND, but this setting has no if already so it's ok for now.
