### ISSUE TITLE
Message-filters addon doesn't show studio comments

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#3271]
### Is your request related to a problem? Please describe.

It seems that the "Activity" switch in the message-filters addon groups both "projects" and "comments" tabs in studios in a single switch, even if there is a "comments" switch.

### Describe the solution you'd like

When the "comment" switch is enabled in the message-filters addon show new comments in studios even if the "activity" switch is not enabled.

### Describe alternatives you've considered

None

### Additional context

None

**Comment by sfederici** [comment]
As I'm very interested in this feature, is this bug going to be taken into account?

**Comment by WorldLanguages** [comment]
@sfederici It seems to work as intended, can you explain the bug?

![image](https://user-images.githubusercontent.com/17484114/132923495-5dcb6bd4-aa25-4bfb-9947-c2ff10bd3049.png)

**Comment by sfederici** [comment]
I checked Comments, Loves, Remixes, Studio invites and Forum activity and I unchecked Studio activity. I'm not getting any message for comments in my studios. Just to give you an example, I don't see MysticCr8tor's comment in my studio comments https://scratch.mit.edu/studios/135830/comments

**Comment by WorldLanguages** [comment]
@sfederici Scratch does not send messages for new studio comments. It only sends studio comment messages when someone replies to your comment.

**Comment by sfederici** [comment]
As far as I know, when there is a new studio message, Scratch notifies a general "studio activity". This is bad, as I cannot discriminate between my activity (that is adding projects, that I don't understand why it is notified as I know that I added those projects) and comments posted in the studio. I guess this cannot be discriminated by Scratch Addons, can it?

**Comment by WorldLanguages** [comment]
Ohh okay, I now see what you meant this whole time.
As you said, the message itself does not include information on what triggered activity, and even tho it could be technically be concluded, it's not really feasible to do that.

**Comment by sfederici** [comment]
I re-posted in the bugs forum https://scratch.mit.edu/discuss/topic/542647/?page=1#post-5603354. But the Scratch Team already ignored this very same comment several month ago :-(

**Comment by WorldLanguages** [comment]
Because it's not really a bug. It works as intended.
Studio activity sucks but that's how it's supposed to work.
