### ISSUE TITLE
TurboWarp frame without addons

### ISSUE THREAD

**Issue by piw-piw** [ScratchAddons/ScratchAddons#3272]
In TurboWarp frame I don't have pause button and rectangle stage.
![image](https://user-images.githubusercontent.com/76477070/128841146-b77e1f14-76a3-4a33-8be6-29fa70c608e3.png)
![image](https://user-images.githubusercontent.com/76477070/128841109-1de8f4d1-c0cb-4d24-865c-8c62b395e04a.png)

**Comment by FunctionalMetatable** [comment]
Quoting from the addon's info:

> "Replace player" mode changes the Scratch player to a TurboWarp embed, which doesn't support Scratch editor addons nor seeing inside projects.

**Comment by mxmou** [comment]
Scratch Addons doesn't have access to TurboWarp.

**Comment by GarboMuffin** [comment]
Something that may be of interest: https://github.com/TurboWarp/scratch-gui/issues/70#issuecomment-898796392 (not released quite yet)
