### ISSUE TITLE
Ability to inject userstyles when the page starts loading

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#328]
**Is your feature request related to a problem? Please describe.**

I'm working on 2.0 → 3.0 and refreshing the page looks like this:
![Userstyle delay](https://user-images.githubusercontent.com/51849865/94247835-f8b57f00-ff1d-11ea-8bfd-28d422ec47a2.gif)

**Describe the solution you'd like**

An option for a userstyle to load when the page starts loading.

**Describe alternatives you've considered**

I don't think there are any alternatives - for a website dark theme, for example, it can't be the way it currently is.

**Additional context**

None

**Comment by WorldLanguages** [comment]
Right now userstyles load as fast as possible as a module can, I think @apple502j?
I think we could move userstyles with no issues to https://github.com/ScratchAddons/ScratchAddons/blob/master/content-scripts/cs.js

**Comment by WorldLanguages** [comment]
@mxmou Just wanted to tell you this issue is more complicated than you could think :P The fact what to inject is dynamic makes the solution to this pretty hacky. Luckily, I've seen people document how Stylus does it, so we can just copy their approach.

**Comment by WorldLanguages** [comment]
It took quite a bit of work... But it appears to be working just as Stylish does now (and no refresh needed to test changes - hope you find it better to debug the CSS now)
