### ISSUE TITLE
website broke entirely

### ISSUE THREAD

**Issue by DatGamerYoloYT** [ScratchAddons/ScratchAddons#3281]
the website is fucking broken when using it

**Comment by RedGuy12** [comment]
this was a mistake by the scratch dev. fixed now

**Comment by jeffalo** [comment]
to add a little more context, this wasn't scratch addons fault. all scratch users were affected. you just used it at the perfect wrong time :P sorry about that.

![scratch4zachary](https://user-images.githubusercontent.com/40470736/129229838-e55e5737-01d4-44ed-a477-f8c4b27be89b.png)
![scratch4bag](https://user-images.githubusercontent.com/40470736/129229842-e7a8e9d5-aa0e-44b0-b9fb-f55cf404871e.png)
![scratch4home](https://user-images.githubusercontent.com/40470736/129229846-40606bbd-2ebb-465c-b7c0-48efc97a902d.png)

**Comment by WorldLanguages** [comment]
@DatGamerYoloYT Be respectful D:
