### ISSUE TITLE
Debugger addon: Redirect log(), warn(), error()

### ISSUE THREAD

**Issue by Mr-Anonymous75** [ScratchAddons/ScratchAddons#3282]
### Is your request related to a problem? Please describe.

I'm creating a project, and I want to add error messages to a list inside the project. However, I also want to put the messages to the debugger console for people who have SA.

### Describe the solution you'd like

If the user creates a custom block called "error ()", "log ()", or "warn ()", then let that **_add_** to the debugger addon's blocks. Not override - add, meaning that the block will still log something into the debugger console, but will also do what's in the user's custom block. 
Then, if that block is called while someone without SA is using the project, it will call the creator's custom block - but obviously, it won't try to log anything to the debugger console. 

I've already tried creating a custom block called "error (message)", and putting "add (message) to [list name v]" in it. The debugger addon's error() block did not call it. Then, I turned off SA and tried again. Now, the error() block was pink instead of the usual debugger color, and calling it did nothing. Dragging out the custom error(message) block from the block palette and clicking on it, though, did work.

**Comment by mxmou** [comment]
Can't you make your own log block that calls SA's log and adds the item to the list?

**Comment by Mr-Anonymous75** [comment]
> Can't you make your own log block that calls SA's log and adds the item to the list?

Well, yeah, but this seems like a more elegant solution, and it shouldn't be too hard to achieve.

**Comment by CST1229** [comment]
Also note that the debugger blocks have 2 zero width spaces each at the start and end of the text. So, for example if you make a custom block with the name `​​error​​` (copy-paste) and a text input with name "content" and an argument ID "arg0" (which is normally impossible to achieve since created block arguments are randomly hashes) I think it will become a debugger block.

**Comment by apple502j** [comment]
Debuggers should only be used for testing, and should never affect other things like lists. If your goal is to add stuff to a list, debugger is not what you want. Rejected.

**Comment by WorldLanguages** [comment]
> If the user creates a custom block called "error ()", "log ()", or "warn ()", then let that add to the debugger addon's blocks. Not override - add, meaning that the block will still log something into the debugger console, but will also do what's in the user's custom block.

This is already the case. But the blocks aren't actually called "error" but as @CST1229 said below, there's invisible chars.

**Comment by WorldLanguages** [comment]
Still, as apple said, it's a bad idea to use debugger for someone else that isn't yourself.

**Comment by Mr-Anonymous75** [comment]
> Also note that the debugger blocks have 2 zero width spaces each at the start and end of the text. So, for example if you make a custom block with the name `​​error​​` (copy-paste) it will become a debugger block and if you add a text input with name "content" and an argument ID of "arg0" (which is normally impossible to achieve since created block arguments are random hashes) I think it will actually log stuff.

Thanks!
After editing the json file to set the parameter's id to `arg0`, the block adds the content to a list called `console` for users without SA, and logs it to the debugger console for people with SA.
