### ISSUE TITLE
New addon that allows 'enter' key to be selected in 'when <> key pressed' and 'key <> pressed?' blocks.

### ISSUE THREAD

**Issue by Tacodude7729** [ScratchAddons/ScratchAddons#3298]
Right now in vanilla Scratch, it is possible to detect the 'enter' key with the 'when <> key pressed' and 'key <> pressed?' blocks. The only problem is for some reason the 'enter' option is not available in the drop downs of these blocks and can only be accessed through editing the `project.json`. See [this project](https://scratch.mit.edu/projects/560948099/) for a demo of these hacked blocks in action.

 I suggest a plugin which allows the enter option to be selected in these two blocks, simply by adding it to the drop down just like the other keys. 

As far as I'm aware, this trick only works for enter and doesn't work on other keys like shift, backspace, etc.

**Comment by WorldLanguages** [comment]
> As far as I'm aware, this trick only works for enter and doesn't work on other keys like shift, backspace, etc.

Hmm, we generally don't want addons that add hacked blocks, but here you're saying `enter` is supported natively, it's just not displayed in the dropdown, right?

**Comment by wgyt** [comment]
> > As far as I'm aware, this trick only works for enter and doesn't work on other keys like shift, backspace, etc.
> 
> Hmm, we generally don't want addons that add hacked blocks, but here you're saying `enter` is supported natively, it's just not displayed in the dropdown, right?

It is supported natively, just not shown in the drop down, this could be part of #817 if that exists ever

**Comment by Tacodude7729** [comment]
> Hmm, we generally don't want addons that add hacked blocks, but here you're saying `enter` is supported natively, it's just not displayed in the dropdown, right?

That's correct. If you look at the project I linked I created those blocks with the plugin. They work in vanilla, for some reason the option is just hidden form the dropdown.

**Comment by Tacodude7729** [comment]
This trick works for many symbol keys too, I've added support for them into the plugin. Note that it works for symbols like '#' that need shift key + '3' key, but it's buggy. If you release the shift key first scratch will still report that your holding '#", so I didn't include them.

**Comment by TecFuture** [comment]
> This trick works for many symbol keys too, I've added support for them into the plugin. Note that it works for symbols like '#' that need shift key + '3' key, but it's buggy. If you release the shift key first scratch will still report that your holding '#", so I didn't include them. I have also update the project https://scratch.mit.edu/projects/560948099/ to include all the other special keys so you can see them in action, working with or without the plugin.

Ahh I faced those issues in another project, hurt my project :(
