### ISSUE TITLE
Crash when optional permission revoked while scratch-notifier is enabled

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#3307]
Repro steps on Firefox:

1) Install extension from AMO
2) Enable scratch-notifier
3) Revoke notification permission via about:addons
4) Close and re-open browser
5) Crash while loading persistent script, `chrome.notifications` is undefined @ `addon-api/background/Notifications.js`

**Comment by apple502j** [comment]
Note: theoretically possible in Chrome but not sure if there is a way to revoke optional permissions.

**Comment by WorldLanguages** [comment]
Chrome doesn't let you revoke permissions
