### ISSUE TITLE
[New Addon] Account Switcher

### ISSUE THREAD

**Issue by ianfife** [ScratchAddons/ScratchAddons#3309]
### Is your request related to a problem? Please describe.

Signing out and then signing back in on an alt account is slow and inefficient.

### Describe the solution you'd like

I want there to be an account switcher maybe above the sign out button where you can easily switch to all of your other logged in accounts with the click of a button.

Btw, this is similar to another issue, but I decided to post anyways because you closed it and I don't think it gave very good reasoning for the addon. #1074

**Comment by RedGuy12** [comment]
Rejected. Use a password manager to speed up the process, or use Firefox containers.

**Comment by ianfife** [comment]
> Rejected. Use a password manager to speed up the process, or use Firefox containers.

This misses the point. I use Brave's native password manager, which helps, but clicking sign out, waiting, and then autofilling with the right account is slow and inefficient, password manager or not.

**Comment by CST1229** [comment]
> 
> 
> > Rejected. Use a password manager to speed up the process, or use Firefox containers.
> 
> This misses the point. I use Brave's native password manager, which helps, but clicking sign out, waiting, and then autofilling with the right account is slow and inefficient, password manager or not.

For me, in Firefox at least, I use containers to quickly switch between accounts, which takes one right click on the tab and 2 clicks to select the container. (I haven't noticed the button in the address bar until now)

**Comment by WorldLanguages** [comment]
@ianfife Keep in mind there's nothing wrong with the suggestion itself, but we simply want to avoid interacting with session IDs. I thought there was another reason we rejected but I forgot by now (this has been brought up multiple times).
After all, account switcher is best suited as a different extension. If someone is interested in developing it the proper way (alternate session IDs need to be stored as an HTTP only cookie, and session IDs should never go outside of the extension background script) as a standalone extension, they can license it under GPL and have us publish it. Even tho it would be a different extension, we could promote it, review the code and ensure compatibility with addons.
