### ISSUE TITLE
2.0 -> 3.0 f**ks up everything

### ISSUE THREAD

**Issue by LankyBox01** [ScratchAddons/ScratchAddons#3312]
### Description

a lot of stuff happening here

### Repoduction steps

1. Enable 2.0 -> 3.0 addon
2. Go to a profile page
3. See the bug

### Expected behaviour

These other sections shouldn't be on the right side, everything should be centered.

### Actual behaviour

Every section is split on 2 sides

### Screenshots

![image](https://user-images.githubusercontent.com/79767244/129745377-d9423917-90da-4116-82ab-0ca3aad7b43d.png)

### Environment

- Browser: Chrome 92.0.4515.159
- Scratch Addons version: v1.18.0 (August 3, 2021) https://github.com/ScratchAddons/ScratchAddons/compare/v1.17.2...v1.18.0
- Operating system: Windows 10 OS Version 2009 (Build 19042.1165)

**Comment by mxmou** [comment]
What other extensions and userstyles could be affecting the page? 2.0 --> 3.0 doesn't make box headers white.

**Comment by LankyBox01** [comment]
for some reason now the page works perfectly

> What other extensions and userstyles could be affecting the page? 2.0 --> 3.0 doesn't make box headers white.

I don't have any other extensions turned on... other than Scratch addons & Adblock

**Comment by TheColaber** [comment]
@LankyBox01 Be kind D:

**Comment by LankyBox01** [comment]
@TheColaber Ok ):
