### ISSUE TITLE
Record editor (for tutorials)

### ISSUE THREAD

**Issue by Mr-Anonymous75** [ScratchAddons/ScratchAddons#3322]
# Problem

It's really hard to get a good recording of the Scratch editor.

I mean, even with vanilla Scratch, it's practically impossible to get a shot of the editor with _actually readable_ text. And with dark theme and stuff, it's even harder!
And the customized editor - or at least mine - looks nothing like the vanilla scratch one - I don't want a tutorial that has dark theme and all that stuff, but I can't manage to even _use_ the editor without the upgrades anymore.

# Solution

## Integration
It would be best if this was integrated with the project recording addon - the "Record Options" popup would have an option to record either the stage or the editor - initially, that is. Once you start recording, there would be a button to switch the view between them.

## Ideal

In the final video, it will look mostly like vanilla Scratch - the dark theme will disappear, the block pallette won't auto-hide - basically, all the aesthetics will disappear. But all the while, for the user, it will be like nothing changed. Of course some changes will have to remain - the middle-clicking features, the search box, the extra right click menu options. 

### Extra

Though this probably will be hard to implement, it would be nice if, in case the user doesn't use them in the recording period, even the non-aesthetic changes would be absent in the final video 

## Alternatives

An alternative would be to _just get an actually readable recording_.

**Comment by apple502j** [comment]
If you're making a tutorial video then I'd recommend not using Scratch Addons at all. Please use an actual screen recording software.

**Comment by WorldLanguages** [comment]
What you suggest isn't really possible in practice
