### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by xItzDiamondx** [ScratchAddons/ScratchAddons#3326]
### Is your request related to a problem? Please describe.

No problems, just thought an app would be cool
### Describe the solution you'd like

A app with all the Addons built-in?
### Describe alternatives you've considered
Idk

### Additional context

None

**Comment by TheColaber** [comment]
TurboWarp is our alternative to a desktop/app with addons. Just go to turbowarp.org on your phone and you should see an option to "Add to home screen" as part of the chrome options. It will take some time to download. Turbowarp has PWA which allows you to do that.
