### ISSUE TITLE
Addon count is wrong?

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#3328]
### Description

Unless I'm doing math wrong, the new addons seem to be factoring in to the total addon count in the popup, which results in however many new addons there are being counted twice.

The popup claims that there are 95+ addons:

![image](https://user-images.githubusercontent.com/43426138/130001631-c537a58f-3263-40ad-b129-07b5390b81ca.png)

But the settings page says otherwise:

![image](https://user-images.githubusercontent.com/43426138/130001676-3ad1ef0c-8dcd-41b8-9008-936537c7523f.png)

61 + 8 + 22 + 2 only equals 93 addons. However, adding the 6 new addons (which are already accounted for, since new addons also appear in the other sections) makes for a false count of 99 addons.

Lol sorry guys, 1.19 won't have 100+ addons

### Environment

- Browser: Firefox 91
- Scratch Addons version: 1.18 (release)
- Operating system: Windows 10

**Comment by apple502j** [comment]
@lisa-wolfgang There are currently 106 addons in the beta. This includes easter eggs.
![image](https://user-images.githubusercontent.com/33279053/130010914-664789eb-0c1a-4e0c-acc8-df15566b07d3.png)

1.18 has 97 addons, we added 9 ( 2 featured 7 other ), so 106.

**Comment by lisa-wolfgang** [comment]
Ah, I forgot to count easter eggs.

**Comment by mxmou** [comment]
Wouldn't it make sense to exclude Easter eggs from the count? They aren't visible by default so they shouldn't be presented as normal features.
