### ISSUE TITLE
Multiple line comments shown as one line in popup

### ISSUE THREAD

**Issue by thecrewmate876** [ScratchAddons/ScratchAddons#3336]
### Description

If a comment has multiple lines like this:

```
This is a 

multiple

line comment
```

it is shown like this in the popup:

![Multiple-line comment in popup](https://user-images.githubusercontent.com/76265544/130250107-84d485d6-5f92-48fd-a177-7a8839b461bb.png)

### Repoduction steps

1. Ask someone to send a multiple line comment on your profile
2. Open popup and see the comment.

### Expected behaviour

The comment should be shown with multiple lines.

### Actual behaviour

The comment is shown like this:

![Multiple-line comment in popup](https://user-images.githubusercontent.com/76265544/130250107-84d485d6-5f92-48fd-a177-7a8839b461bb.png)

### Screenshots

In the popup:

![Multiple-line comment in popup](https://user-images.githubusercontent.com/76265544/130250107-84d485d6-5f92-48fd-a177-7a8839b461bb.png)

On the profile:

![Multiple-line comment in profile](https://user-images.githubusercontent.com/76265544/130251910-a721a554-d1bd-4075-a8bb-080606e71d19.png)

### Environment

- Browser: Firefox Stable 90.0.1
- Scratch Addons version: 1.18.0
- Operating system: Windows 10 20H2 May 2021 Update (Build 19042.1165)

### Additional context

N/A

**Comment by CST1229** [comment]
Don't forget that the multi-line comments themselves are an addon.
![pic](https://user-images.githubusercontent.com/68464103/130253104-10407d10-2d97-4d48-ada7-f4063b3b16a7.png)

**Comment by thecrewmate876** [comment]
> 
> 
> Don't forget that the multi-line comments themselves are an addon.
> ![pic](https://user-images.githubusercontent.com/68464103/130253104-10407d10-2d97-4d48-ada7-f4063b3b16a7.png)

@CST1229 Yeah well I have that enabled.

**Comment by RedGuy12** [comment]
@CST1229: See also #3332

“The popup should implement the feature, not addons.”

**Comment by CST1229** [comment]
> 
> @CST1229: See also #3332 “The popup should implement the feature, not addons.”

Yeah I know, I was mostly replying to them writing the expected behavior as comments being multi-line which is an addon doing that.
