### ISSUE TITLE
Addon that makes paste in the paint editor's paste position directly on the original item.

### ISSUE THREAD

**Issue by Endermaster3690** [ScratchAddons/ScratchAddons#3343]
### Is your request related to a problem? Please describe.

not really but it could help people

### Describe the solution you'd like

an addon that makes the paste go directly on the original position of copying instead of what it does in the video below.

### Describe alternatives you've considered
haven't considered

### Additional context
this is the video showing what i don't like. please ignore watermark.

https://user-images.githubusercontent.com/80355301/130332182-54123071-a2f8-45f1-81c2-c3e5cbc998f8.mp4

**Comment by RedGuy12** [comment]
Maybe it could do the same for duplicating sprites?

**Comment by CST1229** [comment]
I think this is actually fairly easy... Only thing is that it needs to access scratch-paint somehow...
