### ISSUE TITLE
Turbo Mode Button Near Green Flag

### ISSUE THREAD

**Issue by billyBob456** [ScratchAddons/ScratchAddons#3347]
### A Button that Enables Turbo Mode
Just a simple yellow lightning button ⚡ on top of the project to make toggling turbo mode easier. It makes it a lot easier especially for mobile users and new people to Scratch.

**Comment by WorldLanguages** [comment]
Idea rejected

**Comment by WorldLanguages** [comment]
Shift+GreenFlag is already easy.
And how often do you actually want to use turbo mode?

**Comment by LercDsgn** [comment]
> Shift+GreenFlag is already easy.
Sure, but they asked for some mobile friendly one (I'm not sure why would one use Scratch that seriously and I didn't even know extensions existed for mobile but yeah that doesn't change the fact that this is what they're asking)

> And how often do you actually want to use turbo mode?
Works really good with generation-like projects to see it generated step by step or instantly, so maybe they view or create those kinds of projects often?
