### ISSUE TITLE
Highlight block addon causing lots of lag

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#336]
**Describe the bug**

when using the addon that highlights the active block, the project lags

**To Reproduce**

1. enable addon 
2. open the editor in a project with a lot of blocks (it's fairly noticeable [here](https://scratch.mit.edu/projects/283529161/editor/))

**Expected behavior**

the highlight blocks addon does not make projects lag

**Device (please complete the following information):**

windows 10/chrome

**Additional context**

I've seen this bug reported a lot in the feedback, with different OSs

**Comment by JeffaloBob** [comment]
i also don't think the addon works, or i dont really know what its supposed to do.

**Comment by WorldLanguages** [comment]
It appeared to work for me.

**Comment by WorldLanguages** [comment]
It might not be possible to avoid lag all together - if it's not possible, this issue will turn out as a "warn users about it".

**Comment by Hans5958** [comment]
Related #345

**Comment by WorldLanguages** [comment]
Related: #431 
Note that it appears that the way this addon is coded, plus the traps, both hurt performance and create a double combo of lag.
