### ISSUE TITLE
Remove CSS variables when disabling an addon

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#3361]
### Is your request related to a problem? Please describe.

I'm working on an editor theme and I want it to be compatible with editor dark mode. The best way to do that seems to be using CSS variables like this:
```css
.example-class {
  background-color: var(--editorDarkMode-exampleSetting, #4d97ff);
}
```

That works, but when I disable editor dark mode, the variables stay, so I need to refresh the page to see the fallback color again.

### Describe the solution you'd like

When an addon with `dynamicDisable` is disabled, its `customCssVariables` should be removed <del>(by setting all of them to an empty string)</del>.

### Describe alternatives you've considered

Add a CSS file to editor dark mode containing something like this:
```css
:root {
  --editorDarkModeCompatibility-page: var(--editorDarkMode-page);
  --editorDarkModeCompatibility-menuBar: var(--editorDarkMode-menuBar);
  --editorDarkModeCompatibility-tab: var(--editorDarkMode-tab);
}
```

When editor dark mode is disabled, the CSS will be removed and the variables will be undefined as expected.

**Comment by WorldLanguages** [comment]
> (by setting all of them to an empty string)

Why not remove the property?

**Comment by mxmou** [comment]
> > (by setting all of them to an empty string)
> 
> Why not remove the property?

That would make more sense.
