### ISSUE TITLE
Open Cloud games in new tab as well

### ISSUE THREAD

**Issue by Shluffy** [ScratchAddons/ScratchAddons#3368]
### Is your request related to a problem? Please describe.

Only messages will link you to the page in a new window. Because it is a popup, you can load cloud games and get this:
![image](https://user-images.githubusercontent.com/81823039/130843930-8f87c419-07a7-4dea-b735-7e0252064ac2.png)

### Describe the solution you'd like

add the open in new tab button same as messages

### Describe alternatives you've considered

none

### Additional context

n/a

**Comment by Oren-Lindsey** [comment]
https://github.com/ScratchAddons/ScratchAddons/pull/4449
I made a pr for this
