### ISSUE TITLE
Show stats on your own projects

### ISSUE THREAD

**Issue by Mr-Anonymous75** [ScratchAddons/ScratchAddons#3374]
# Problem

I recently enabled the hide project stats addon. And though, yes, I do love to not know how many loves and faves a generic platformer has, I still want to know how many my own project does.

# Solution

Even though it's someone's own project, they still might want to hide some stats, like the remix count. So, it would be best to use the options already there for other people's projects, and add more options for the user's own.

## Alternatives

An alternative would be to just add a checkbox named something like "Still show stats on your own projects".

**Comment by lisa-wolfgang** [comment]
Note that to reduce complexity, only a single toggle was added to show all stats on the user's own projects.
