### ISSUE TITLE
Make project info addon more beautiful

### ISSUE THREAD

**Issue by LankyBox01** [ScratchAddons/ScratchAddons#3378]
Instead of... well... this,
![image](https://user-images.githubusercontent.com/79767244/130999984-1f1e8d7e-0345-4709-b75a-6c5dac6f3497.png)

Maybe it could look like... this?
![Untitled](https://user-images.githubusercontent.com/79767244/131000440-7bc707ea-2d52-4c41-9b50-ef6a7c4e86ad.png)

https://scratch.mit.edu/svgs/project/sprite-count.svg
https://scratch.mit.edu/svgs/project/block-count.svg

**Comment by Endermaster3690** [comment]
How about a choose thingy for text only, icons only and text and icons??

**Comment by mxmou** [comment]
> How about a choose thingy for text only, icons only and text and icons??

I don't think the appearance of addons needs to be fully customizable - the functionality is more important. Too much customization can be a problem: #1262
