### ISSUE TITLE
New addon : "Hide stage"

### ISSUE THREAD

**Issue by Medericoder** [ScratchAddons/ScratchAddons#3395]
Hi!
I propose an addon which allows to visually remove the area which allows to code the backdrops.
Personally, I never use backdrops.

**Comment by apple502j** [comment]
Do you mean removing the backdrop selector?

**Comment by Marc92020** [comment]
Just don't use the backdrops

**Comment by Medericoder** [comment]
> Do you mean removing the backdrop selector?

Yes.



> Just don't use the backdrops

But it takes too much places on the screen.
