### ISSUE TITLE
Hide unshare button

### ISSUE THREAD

**Issue by Marc92020** [ScratchAddons/ScratchAddons#3401]
### Is your request related to a problem? Please describe.
Sometimes I accidentally share a project inside the editor because the see project page button is very close to the share button.

### Describe the solution you'd like
it would be cool to have a hide unshare addon so people don't accidentally share unfinished projects like i do

### Describe alternatives you've considered
maybe moving the share button somewhere else could be an alternative

### Additional context
e
hide unshare button mockup:
![image](https://user-images.githubusercontent.com/75702334/131406680-59d54df4-8cd5-4a4c-9f22-9ac4014dca8b.png)

**Comment by RedGuy12** [comment]
try the devtools "confirm share" function

**Comment by WorldLanguages** [comment]
See "confirmations" addon

**Comment by apple502j** [comment]
Also, that addon would be "hide share button".

**Comment by Marc92020** [comment]
> try the devtools "confirm share" function

Oh yah forgot


> Also, that addon would be "hide share button".

Oops I made a mistake with the title
