### ISSUE TITLE
New addon: Live project stats

### ISSUE THREAD

**Issue by Oren-Lindsey** [ScratchAddons/ScratchAddons#3407]
### Is your request related to a problem? Please describe.

I don't like it when you have to reload the page to see the latest project stats

### Describe the solution you'd like

Hello, this is scratchusername40 on scratch. I'd like an add-on that shows project stats live as they change. It would update the project stats while you're on the page. This would make the site feel more responsive and live, and it would just be cool to have. 
### Describe alternatives you've considered

None
### Additional context

To prevent spamming the servers, and because scratch projects don't update that fast, it could be like twitter and be limited to updating every 5-9 seconds or something like that, and also when you update any of the stats, by loving, favoriting, or viewing a project
Also, maybe this could be added to ocular reactions or something too

**Comment by WorldLanguages** [comment]
Would be pretty useless because Scratch caches project stats in server side.
