### ISSUE TITLE
Costumes counter for sprites addon

### ISSUE THREAD

**Issue by Endermaster3690** [ScratchAddons/ScratchAddons#3413]
### Is your request related to a problem? Please describe.
no just an idea

### Describe the solution you'd like

an addon

### Describe alternatives you've considered
no

### Additional context
no

**Comment by LankyBox01** [comment]
![image](https://user-images.githubusercontent.com/79767244/131724909-960fccd8-3631-4cf6-8596-efc8ded4fa00.png)
take the last costume's corner count. There you go.

**Comment by Endermaster3690** [comment]
i know, but just to minimize time usage. yes i know this isnt a speedrun
