### ISSUE TITLE
Should there be an isOnline addon?

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#342]
so i remember back when isOnline was at its peak and it was super useful to tell if someone was online.

i was wondering, maybe there could be a super simple iO implementation (probably not with the recommended tag and with a new name) which wouldn't have any of the friends list features.

basically, ping server every few minutes with username (or maybe user id), and on the server, if someone has not pinged in x minutes, then they are offline.

then when visiting a profile, fetch an api from the server and decide whether they are online, offline, or not using the extension. 

isonline had some other features that let you know if your friends were online, but something like that could cause privacy concerns blah blah. it also had a ghost mode, which would also be fairly simple to implement in this simple iO.

i think even i know how to make a simple iO implementation and if you want i can make the PR to add it.

_there might also have to be a privacy policy and stuff like that 😬_

**Comment by JeffaloBob** [comment]
i made a demo server on repl.it

https://io-meme.jeffalobob.repl.co/ will display how many users are online
https://io-meme.jeffalobob.repl.co/online?user=username will make a user online for 10 seconds
https://io-meme.jeffalobob.repl.co/isonline?user=username will check if they're online

**Comment by JeffaloBob** [comment]
and the code https://repl.it/@jeffalobob/io-meme

**Comment by jemunm378** [comment]
I think it’s a great idea.

**Comment by tb148** [comment]
This is AWESOME! However we should also have a "non-SA user" status so people don't get confused why online users have an "offline" status.
This might be done by setting an `isUser` status the first time they ping.

**Comment by YOYITsM3M8** [comment]
Yas

**Comment by JeffaloBob** [comment]
we will also have to handle verification if the user pinging is really them. any ideas on how to implement this?

**Comment by JeffaloBob** [comment]
@WorldLanguages ^^

**Comment by jemunm378** [comment]
Maybe the users can verify using their scratch account. Maybe something similar to this?: [https://github.com/ScratchVerifier/ScratchVerifier](url)

**Comment by WorldLanguages** [comment]
Keep in mind, we won't be adding any online indicator/notifications for now, while we focus in other parts of the extension.

**Comment by JeffaloBob** [comment]
i can focus though

**Comment by WorldLanguages** [comment]
I need to focus on whether your focus is appropriate :P

**Comment by JeffaloBob** [comment]
i was thinking of something that may be better, instead of displaying offline users, only online users are displayed. 

this makes it a bit simpler to code and allows focus or something idk just let me make it

**Comment by Explosion-Scratch** [comment]
This could be very neatly incorporated into the multiplayer cloud games section of griffpatch's messaging extension. It would be nice though if it only showed who was online, not who was offline and also maybe the option to be offline even when online. (Perhaps a prompt could solve this.)
