### ISSUE TITLE
Make "link to" menu a separate addon

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#3420]
### Is your request related to a problem? Please describe.

The "More forum toolbar buttons" addon adds three formatting options and a "link to" menu to the toolbar. The latter isn't related to the other features of the addon, except that it also inserts something into the forum post.

### Describe the solution you'd like

Make the "link to" menu a separate addon.

### Additional context

This would also allow more specific names and descriptions (example below), which means the addons would be easier to find.
* More forum post formatting options
  * Adds buttons to change the text color, center text, and insert code to the forum post editor toolbar.
* "Link to" menu for forum posts
  * Adds a menu to the forum post editor toolbar that lets you insert links to Wikipedia, Scratch Wiki, Google search results, and Dictionary.com using special BBCode tags.

**Comment by WorldLanguages** [comment]
That feels a little bit overkill. Makes more sense to just "forget" to mention the BBCode tags for linking to Wikipedia and others in the addon description. No one really searches for those.

**Comment by Secret-chest** [comment]
> That feels a little bit overkill. Makes more sense to just "forget" to mention the BBCode tags for linking to Wikipedia and others in the addon description. No one really searches for those.

@WorldLanguages True. No one searches for those, but they are a nice bonus as I used them yesterday to link to the Copyleft article on Wikipedia without writing http://en.wikipedia.org/wiki/Copyleft or looking it up on google. They are really useful when helping another Scratcher.

**Comment by WorldLanguages** [comment]
Ok I'm closing, mxmou you can reopen if you really want to
