### ISSUE TITLE
Full areas and exact count are categorized as forum addons.

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#3421]
### Description

"Show full areas" and "show exact count" addons are shown in the Scratch Website Features → Forums section on the settings page.

### Expected behaviour

They also affect other parts of the website, so they should be in the Website → Others section.

**Comment by WorldLanguages** [comment]
It works kinda weirdly right now, maybe we should finally split the "tags" property into multiple ones so that we can be more flexible for addons like this.

**Comment by mxmou** [comment]
Not a bug - they're in both "Profiles" and "Forums".
