### ISSUE TITLE
Gamepad blocks

### ISSUE THREAD

**Issue by DJ-Laser** [ScratchAddons/ScratchAddons#3433]
### Problem:
I want blocks to change gamepad settings because I want my game to use the mouse as axis 1 in the level editor, and use WASD while playing the game.

### Solution:
![gamepad bttns](https://user-images.githubusercontent.com/90146620/132133560-f201b86c-1b9d-4e99-96a7-801d04b63097.png)

Add blocks like
<button [1,2,3... v] pressed>
( [x,y v] of axis [1,2,3... v] )
set button [1,2,3... v] to (click,a,b,c... v)
set axis [1,2,3... v] to [cursor, WASD... v]]
set axis [1,2,3... v] to custom (a,b,c... v) (a,b,c... v) (a,b,c... v) (a,b,c... v)
and also blocks to read addon settings and if they are enabled.

*(the v in the image and text means a dropdown)

### Alternative:
we could use lots of checks and a variable for when we are using a gamepad to make a different control system.

**Comment by apple502j** [comment]
We'll improve the TurboWarp comment-based settings instead.

**Comment by DJ-Laser** [comment]
> We'll improve the TurboWarp comment-based settings instead.
What do you mean? I think creating controls blocks is a good idea as it will let creators make menus to change keybinds for different areas of their games

**Comment by apple502j** [comment]
@DJ-Laser We don't want to enforce certain keybinds, so we will let users change it on our own UI.

**Comment by DJ-Laser** [comment]
well can you at least be able to create multiple control styles and have the user edit them separately. For example there can be a
switch gamepad control style to [] and have it be like the broadcast block where you can choose one or create a new one. Then the user can edit each control style individually and for example have joystick one be wasd in level editor style and ads with bttn 1 = w in gameplay style.

**Comment by apple502j** [comment]
Not sure if we can do that, but at least we'll try
