### ISSUE TITLE
Link for Firefox extension just goes to Griffpatch's Messaging Extension

### ISSUE THREAD

**Issue by infinitytec** [ScratchAddons/ScratchAddons#344]
**Describe the bug**

The link for the Firefox extension on https://scratchaddons.com/ goes to https://addons.mozilla.org/firefox/addon/scratch-messaging-extension/ and not the actual extension.

**To Reproduce**

Self-explanatory

**Expected behavior**

Link takes me to the proper extension.

**Device (please complete the following information):**

- Browser: Firefox

**Additional context**

This is just on the website.

**Comment by GrahamSH-LLK** [comment]
The firefox extension is not live yet, and it will replace the scratch messaging extension.

**Comment by infinitytec** [comment]
Ah, fair enough. Makes sense.
