### ISSUE TITLE
Text in svg export is offset incorrectly

### ISSUE THREAD

**Issue by ksdavidc** [ScratchAddons/ScratchAddons#3458]
### Description

The svg export function seems to be off. 
1. It requires that the clean up blocks be run before exporting, else the area copied is cropped off center..
2. Importing the svg, either via normal or hd, results in text being misplaced relative to the blocks. They seem to be diagonally offset by about 50 pixels in the south westerly direction.
If I open the exported svg in inkscape, it appears correctly. It appears the export is working, therefore.

Png works fine.

I have tried with image sizing at original, stretch and shrink.

### Repoduction steps

1. clean up blocks
2. export as svg
3. import via regular or hd

### Expected behaviour

text for blocks should align
### Actual behaviour

does not
### Screenshots
<img width="688" alt="Screen Shot 2021-09-11 at 3 50 39 AM" src="https://user-images.githubusercontent.com/62230004/132903398-17eadffb-d9df-4897-b560-d4b27ad3099c.png">

[Archive.zip](https://github.com/ScratchAddons/ScratchAddons/files/7145809/Archive.zip)

### Environment

mac 
latest addon version/ 

chrome 93
- Browser: 
- Scratch Addons version: 
- Operating system:

**Comment by Samq64** [comment]
I'm pretty sure this is scratchblocks bug because importing blokcs scratchblocks.github.io does the same thing.

**Comment by WorldLanguages** [comment]
I've never seen the export as SVG function have results like that, are you sure that isn't a bug on Scratch? Try editing the SVG with something else?

**Comment by ksdavidc** [comment]
> I've never seen the export as SVG function have results like that, are you sure that isn't a bug on Scratch? Try editing the SVG with something else?
I was able to edit the original files in Inkscape with no problem. I think the problem is on the import end, not export end.

The link in my original post was not working (fixed now). It goes to to a zip file with an exported svg (working) and a screenshot was not working. 

[Archive.zip with working svg export in it](https://github.com/ScratchAddons/ScratchAddons/files/7145809/Archive.zip)

**Comment by ksdavidc** [comment]
> I'm pretty sure this is scratchblocks bug because importing blokcs from scratchblocks.github.io does the same thing.

Is that on my computer, or in scratch addons? How do I turn it off to see?

**Comment by Samq64** [comment]
>How do I turn it off to see?
Just open a private window.

**Comment by WorldLanguages** [comment]
The SVG looks fine when opened in Chrome.
I then uploaded it into vanilla Scratch, and it looks like you said.
This is a Scratch bug, not Scratch Addons bug.

**Comment by WorldLanguages** [comment]
In theory we could try to see what causes this, and make the SVG exporter work around it, but I'm not sure if someone has enough knowledge and time for that.
