### ISSUE TITLE
Allow the Forums Time Zone to be set to a specific zone, not the system one.

### ISSUE THREAD

**Issue by DroneBetter** [ScratchAddons/ScratchAddons#346]
**Is your feature request related to a problem? Please describe.**

If you want to refer to an objective time, you have to manually convert to UTC.

**Describe the solution you'd like**

A dropdown menu in the Forums Time Zone setting's interface, to allow a different time zone to be used. Possibly also add a toggle, enabled by default, to set automatically based on system/geographic default.

**Comment by WorldLanguages** [comment]
I agree on this, that addon could be enhanced quite a lot.

**Comment by TheColaber** [comment]
closing since this addon has been removed and likely wont be readded to the upcoming version.
