### ISSUE TITLE
Avast One Essential flagging Scratch addons as "possible malware"

### ISSUE THREAD

**Issue by JoshAtticus** [ScratchAddons/ScratchAddons#3466]
![scratch-addons-errror](https://user-images.githubusercontent.com/72828296/132938175-764abfe2-4673-4eaf-b1b6-91deaee07cb5.png)

For some reason, when Avast One users run a smart scan, Avast automatically says that Scratch Addons has a 1-star review (no?) for Mozilla Firefox. Google Chrome however is not affected by this glitch. As far as I know Scratch addons has a 4.5 star review.
-->

**Comment by CST1229** [comment]
Are you sure it is the real Scratch Addons?

**Comment by apple502j** [comment]
Avast should really tag Windows 7 as a malware.

But no, this is not our issue.

**Comment by JoshAtticus** [comment]
> 
> 
> Are you sure it is the real Scratch Addons?

Yes, I downloaded it from addons.mozilla.org

**Comment by JoshAtticus** [comment]
> 
> 
> Avast should really tag Windows 7 as a malware.
> 
> But no, this is not our issue.

Well, yes, it isn't your issue, but why flag Windows 7 as malware?

**Comment by Samq64** [comment]
Support for Windows 7 ended on January 14, 2020.

**Comment by WorldLanguages** [comment]
We have 4+ stars, so that's an Avast bug.
Also, please use Windows 10

**Comment by JoshAtticus** [comment]
I know support ended but I'm still not upgrading. I also know that you have 4+ stars. I updated avast and it stopped flagging SA as malware.

**Comment by JoshAtticus** [comment]
I'd rather not have ads piped directly into the most used bits of my OS, and have telemetry tracking my every move, it gives me the creeps.

**Comment by wgyt** [comment]
> I'd rather not have ads piped directly into the most used bits of my OS, and have telemetry tracking my every move, it gives me the creeps.

use linux

**Comment by JoshAtticus** [comment]
> 
> 
> > I'd rather not have ads piped directly into the most used bits of my OS, and have telemetry tracking my every move, it gives me the creeps.
> 
> use linux

I need my computer for school
