### ISSUE TITLE
Refactor folders addon context menu

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#3468]
I forgot that addon had a dynamic context menu - that'll be hard to do using the new API. Should we just keep using the good ol' way?

**Comment by mxmou** [comment]
Could a function be added for creating multiple items at once, with a function returning an array of [callback, options] pairs as a parameter? Or does the implementation not allow that?

**Comment by apple502j** [comment]
@mxmou That is technically possible - requires refactoring some API code.

**Comment by WorldLanguages** [comment]
DevtoolsExtension will stop adding any new context menu items, so this API can be changed as many times as we want without compat concerns.
