### ISSUE TITLE
Notifications should contain message content

### ISSUE THREAD

**Issue by j5155** [ScratchAddons/ScratchAddons#348]
**Is your feature request related to a problem? Please describe.**

no

**Describe the solution you'd like**

When you get notified of a message, currently it just tells you you have a message and the category of the message. I'd prefer this to be something similar to World_Languages's Scratch Notifier extension, where it tells you the message content, instead of having to click on the extension itself.

**Describe alternatives you've considered**

Installing the Scratch Notifier extension again.

**Additional context**

none

**Comment by WorldLanguages** [comment]
*Note: in case you don't know, me World_Languages made the Scratch Notifier feature inside Scratch Addons as an improved version of my Scratch Notifier extension*

I'm confused on what you mean by that, for me notifications look the same between the extension and the addon. Can you post a screenshot of a notification? If you're having trouble getting messages, please log in to an alternative account in incognito mode and send yourself a comment.

**Comment by j5155** [comment]
Scratch Addons:
![image](https://user-images.githubusercontent.com/54331556/94485393-564e0380-018a-11eb-80a3-7c50bc5915ad.png)
Scratch Notifier:
![image](https://user-images.githubusercontent.com/54331556/94485628-b349b980-018a-11eb-9ab4-7c9b6cda40a1.png)
wait, this is very odd, now Scratch Addons is sending me a thing exactly like that? I think this is a bug, let me change the original post
