### ISSUE TITLE
Add settings to the extra key support addon, which re-enables the 'experimental' keys.

### ISSUE THREAD

**Issue by Tacodude7729** [ScratchAddons/ScratchAddons#3480]
Could we have a setting for the plugin (disabled by default), something like 'show unstable keys', which re-enables the keys you disabled _[Keys not supported on all operating systems and keyboard layouts]_. A warning  could be attached stating that some users may not be able to press these keys, and use at your own risk. I agree that having keys some people can't hit may not be a great idea if it's unclear, but I also think that we shouldn't take away these options for people who might want to use them (like, for a text editor or something).

_Originally posted by @Tacodude7729 in https://github.com/ScratchAddons/ScratchAddons/issues/3299#issuecomment-917503485_

**Comment by WorldLanguages** [comment]
Yeah, go ahead and PR, it can get merged for v1.21.0
