### ISSUE TITLE
Recently viewed projects addon

### ISSUE THREAD

**Issue by samcodee** [ScratchAddons/ScratchAddons#3483]
### Is your request related to a problem? Please describe.

A few days before, I found a really good pen text engine. Usually, I will fav / love the project so that I can revisit it later. This time I forgot to do that and lost the project forever. (not really, but I hope you get the picture.) It is very hard to find it again (View the alternatives section)

### Describe the solution you'd like

I think it would be useful to have addon that adds a dropdown item in the account dropdown like "View recently viewed projects / Users". Or, It can also be added to the profile page like "Recently viewed projects".

#### Dropdown item in the profile picture dropdown

![image](https://user-images.githubusercontent.com/62462363/133023480-a2a69e3c-f4b8-4244-b1a6-085832460deb.png)

#### Recent projects category in profile page

![image](https://user-images.githubusercontent.com/62462363/133023715-1fe1dddd-73f6-4bf0-979c-fddbc78b87f2.png)

*Screenshots created with inspect element document design mode

### Alternatives

You can view the recent projects by:-

1. Creating a new studio
![image](https://user-images.githubusercontent.com/62462363/133023132-884cfe78-e766-439e-8ef6-330c1711ed3b.png)

2. Click the browse projects button
![image](https://user-images.githubusercontent.com/62462363/133023158-756e4665-b0f3-4560-a298-861d08c38dab.png)

3. In the popup, click "recent" to view recently viewed projects
![image](https://user-images.githubusercontent.com/62462363/133023223-95999f22-04af-4eb2-bdaf-3e975bbed0b1.png)

**Comment by apple502j** [comment]
Why implement ourselves when the browser provides it?

**Comment by RedGuy12** [comment]
It does?


________________________________

**Comment by CST1229** [comment]
> 
> It does?

Browser history.

**Comment by WorldLanguages** [comment]
I don't hate the idea of having a row named "recently viewed projects (only visible to you)" added to people's profiles through an addon, to be honest.

**Comment by TheColaber** [comment]
> I don't hate the idea of having a row named "recently viewed projects (only visible to you)" added to people's profiles through an addon, to be honest.

And scratch already has an api...
