### ISSUE TITLE
Studio comments don't notify with the full comment

### ISSUE THREAD

**Issue by j5155** [ScratchAddons/ScratchAddons#349]
**Describe the bug**

The scratch notifier add on doesn't show the comment when the comment is a reply in a studio.

**To Reproduce**

1. Go to a studio
2. Comment
3. Get a reply

**Expected behavior**

The extension to tell you the comment in the notification

**Screenshots**

Regular comment:
![image](https://user-images.githubusercontent.com/54331556/94486295-ada0a380-018b-11eb-939c-1224369cbae0.png)
Studio comment:
![image](https://user-images.githubusercontent.com/54331556/94486329-ba24fc00-018b-11eb-9fc2-07513dfc7096.png)

**Device (please complete the following information):**

- OS: Windows
- Browser: Chrome 
- Version: 85

**Comment by WorldLanguages** [comment]
That makes more sense! Let's see, it's likely a stupid bug in the code...

**Comment by WorldLanguages** [comment]
Can reproduce.
Fixed by adding a single character hehe, stupid bug
