### ISSUE TITLE
Profile comments occasionally have too much padding

### ISSUE THREAD

**Issue by LegoManiac04** [ScratchAddons/ScratchAddons#3503]
### Description

When loading the comments on a profile, the padding of the comment box is sometimes much greater than it should be, though it disappears rather quick. What's really odd about this is that it only sometimes does this..

### Reproduction steps

1. Go to any profile, and scroll down to the comments section before it loads. It doesn't always do this, so it may take a few tries to reproduce.

### Screenshots

https://user-images.githubusercontent.com/87787046/133486022-fc1978da-7899-4b9a-b75b-65a2c8150239.mp4

### Environment

- Browser: Firefox 92.0 
- Scratch Addons version: 1.19.1 
- Operating system: Linux 

### Additional context

I have the Scratch 2.0 → 3.0 addon enabled.

**Comment by RedGuy12** [comment]
Caused by comment-linebreaks lagging.
