### ISSUE TITLE
Enable / Disable Scratch addons Entirely

### ISSUE THREAD

**Issue by samcodee** [ScratchAddons/ScratchAddons#3508]
### Is your request related to a problem? Please describe.

I think it will be useful to enable or disable Scratch Addons Entirely. I think currently you can only delete the extension to disable it, Which I think is not a good user experience.

### Describe the solution you'd like

Be able to disable the Whole extension easily. A possible solution is extension context menus.
https://developer.chrome.com/docs/extensions/reference/contextMenus/

Something like this:-

![image](https://user-images.githubusercontent.com/62462363/133551064-4915c94f-38d7-44ed-bf13-2084b67f8deb.png)
_*Please ignore the fact that the icon is not appropriate._ 

You could also add a warning in the Scratch Addons popup and the settings page stating that the extension is disabled.

There could also be a setting in the options page where you can set your most used extensions and make them easily turned on/off using the context menus :-

![image](https://user-images.githubusercontent.com/62462363/133552467-4ed52026-89fe-452e-925e-c7325ab4f799.png)

There is also this neat separator to separate different categories. 

You can also change when and where the context menu should appear. You can also make it appear when right clicking the extension Icon.

https://developer.chrome.com/docs/extensions/reference/contextMenus/#type-ContextType

There are also many types of Context Menus:-

https://developer.chrome.com/docs/extensions/reference/contextMenus/#type-ItemType

**Comment by apple502j** [comment]
https://i.gyazo.com/2f679fce29292cf725752fac6cd9d343.mp4

**Comment by samcodee** [comment]
>  2f679fce29292cf725752fac6cd9d343.mp4

I understand. Sorry. What about disabling/enabling most used extensions?

**Comment by Dhuls-Scratch** [comment]
> > 2f679fce29292cf725752fac6cd9d343.mp4
> 
> I understand. Sorry. What about disabling/enabling most used extensions?

[extension://fbeffbjdlemaoicjdapfpikkikjoneco/webpages/settings/index.html](extension://fbeffbjdlemaoicjdapfpikkikjoneco/webpages/settings/index.html)
[moz-extension://7b574b07-6886-409e-b544-ba99b42d8373/webpages/settings/index.html](moz-extension://7b574b07-6886-409e-b544-ba99b42d8373/webpages/settings/index.html)
Plus, "most" would probably just be "randomly select some extensions", which, IMO, is not a good idea.

**Comment by CST1229** [comment]
>
> extension://fbeffbjdlemaoicjdapfpikkikjoneco/webpages/settings/index.html
> moz-extension://7b574b07-6886-409e-b544-ba99b42d8373/webpages/settings/index.html
> 

https://scratch.mit.edu/scratch-addons-extension/settings
