### ISSUE TITLE
Import costume/sprite from URL

### ISSUE THREAD

**Issue by tnhung2011** [ScratchAddons/ScratchAddons#3509]
### Is your request related to a problem? Please describe.

When I need image files for my project, I need to download it then upload it to my project. That's why my laptop full of image files (like trashes)

### Describe the solution you'd like
I wanted to add an feature that can import files from an URL.

### Describe alternatives you've considered

The "Files drag and drop" is (kinda) good for drag files from laptop but when I drop images from web (or an URL), Scratch opened the image in the new tab.

### Additional context
...

**Comment by Endermaster3690** [comment]
how I get rid of trash image files is overwrite other images.

**Comment by apple502j** [comment]
Just delete the file after you used it.
