### ISSUE TITLE
Extra keys doesn't work

### ISSUE THREAD

**Issue by Marc92020** [ScratchAddons/ScratchAddons#3525]
### Description
"Extra key support" addon isn't working.

### Repoduction steps

1. Turn Extra key support addon on
2. Try to find the extra keys
3. You can't

### Expected behaviour
The extra key options should show

### Actual behaviour
They don't

### Screenshots
![Screenshot 2021-09-18 6 48 09 PM](https://user-images.githubusercontent.com/75702334/133910418-120b0072-a1fc-4fdc-8d71-6a5a9735f6df.png)

### Environment

- Browser: Chrome 93
- Scratch Addons version: 1.20.0
- Operating system: Chrome OS
### Additional context
n

**Comment by Samq64** [comment]
Dod you accidentally put any whitespace in your search?

**Comment by Marc92020** [comment]
> Do the extra keys appear when scrolling through the list of keys without searching? If they do, then remove any whitespace you might have accidentally put in your search and see if it works. If neither of those work, then it's probably a bug with searchable drop-downs.

it didn't show up when scrolling but its working now but it only works when the block is in the code area

**Comment by Samq64** [comment]
https://github.com/ScratchAddons/ScratchAddons/issues/3299#issuecomment-912858475 must have not been completely fixed.

**Comment by Marc92020** [comment]
> #3299 (comment)

yes
