### ISSUE TITLE
A file/data reader addon

### ISSUE THREAD

**Issue by Bumburblast** [ScratchAddons/ScratchAddons#3529]
Hey, I'm making a game and for a mechanic I needed an addon that could pass variable data from one project to another, for example pass the percentage of a game to another project.
But since I don't know anything about coding or anything similar, I don't think I can do it on my own.

For example, I could pass the progress of some variables from one project to another, then I could make these variables that show 100% pass from this project to another project that uses the same variables.
![JuanTheGameLegendOfCrimson1](https://user-images.githubusercontent.com/90998026/133915273-d28323be-9851-4de6-b24e-4c18e9a0d9ce.png)
![JuanTheGameLegendOfCrimson2](https://user-images.githubusercontent.com/90998026/133915275-e20df8d6-d1ff-43e5-a761-698b78eb3ef8.png)

**Comment by Dhuls-Scratch** [comment]
1. Issue templates exist. Use them
2. It's best to let contributors and maintainers assign labels. You should just add the "status: needs triage" and "type: enhancement" labels
3. This could cause compatibility issues with those who don't use Scratch Addons, depending on how this is done
4. For now, scratchclient can be used to sorta accomplish this

**Comment by CST1229** [comment]
>     2\. It's best to let contributors and maintainers assign labels.

How do you even assign a label yourself?

**Comment by mxmou** [comment]
> How did the creator of the issue even assign a label themselves? I thought they couldn't do it outside of the issue template labels.

They didn't - these labels are part of the new addon template.

**Comment by Bumburblast** [comment]
> 1. Issue templates exist. Use them
> 2. It's best to let contributors and maintainers assign labels. You should just add the "status: needs triage" and "type: enhancement" labels

Sorry, im new in github, thanks for the tip

**Comment by wgyt** [comment]
This could be done using cloud variables.

**Comment by apple502j** [comment]
Too complicated IMO.

**Comment by return-misaPuding** [comment]
It would cause compatibility issues for non-SA users. ScratchAddons isn't there to make new Scratch. This can be done by [https://scratch.mit.edu/discuss/topic/10153/?page=48](bridge variables) tho, so pls discuss this in their respective topic
