### ISSUE TITLE
find-bar: pressing Ctrl+Z when input is not focused anymore, refocuses it

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#3534]
Open a project, type something in the devtools box, put some blocks in the workspace, and press ctrl+z. Scratch undoes, and devtools input is also "undone" by the browser. Apparently only happens in Chrome, which sometimes lets ctrl+z undo after the input was blurred.

A terrible bug fix is:
```js
    document.addEventListener("keydown", (e) => {
      if ((e.metaKey || e.ctrlKey) && (e.key === "z" || e.key === "y")) {
        if (document.activeElement === document.body) e.preventDefault();
      }
    });
```

**Comment by mxmou** [comment]
This also happens to Scratch's own inputs, without SA: change the name of a costume, then change something in the costume and press Ctrl+Z. Both the change to the name and the change to the costume are undone.

**Comment by TheColaber** [comment]
@mxmou We could at least fix our own inputs and possibly make an addon that fixes scratch's. That depends on whether or not the scratch team is ok with a pr that fixes that bug on their repo. If not, we could fix that annoying bug.

**Comment by WorldLanguages** [comment]
I can't reproduce anymore on Chrome 95.

**Comment by BroJac5246** [comment]
Is anyone working on a fix for this? It keeps happening to me and is driving me crazy.

**Comment by WorldLanguages** [comment]
@BroJac5246 I suggested some bad code that fixes this in the original post of this issue.

**Comment by BroJac5246** [comment]
> @BroJac5246 I suggested some bad code that fixes this in the original post of this issue.

But is there any intention of someone creating a PR that fixes this soon?
