### ISSUE TITLE
Add supported fonts to list of fonts

### ISSUE THREAD

**Issue by Marc92020** [ScratchAddons/ScratchAddons#3538]
### Is your request related to a problem? Please describe.
There are a lot of still supported fonts (like Scratch font and Comic Sans MS) and I feel like they should be added to the list instead of always having to get them from projects or generators.

### Describe the solution you'd like
Adding fonts like the Scratch font and Comic Sans and other supported secret fonts.

### Describe alternatives you've considered
h

### Additional context
e

**Comment by apple502j** [comment]
Comic Sans isn't supported; it will probably use normal sans-serif fonts on macOS.

**Comment by apple502j** [comment]
Duplicate of #3059, #2050, etc

**Comment by Marc92020** [comment]
> Comic Sans isn't supported; it will probably use normal sans-serif fonts on macOS.

HTML Cursive (which is comic sans) works

**Comment by Secret-chest** [comment]
> > Comic Sans isn't supported; it will probably use normal sans-serif fonts on macOS.
> 
> HTML Cursive (which is comic sans) works

What about Linux

**Comment by wgyt** [comment]
> > > Comic Sans isn't supported; it will probably use normal sans-serif fonts on macOS.
> > 
> > 
> > HTML Cursive (which is comic sans) works
> 
> What about Linux

Linux web browsers come with their own cursive fonts. The CSS cursive font is a generic name for the system’s default cursive font
