### ISSUE TITLE
Pressing duplicate in the right click menu while holding control should only duplicate one block with the 'Grab single block with Ctrl key' addon

### ISSUE THREAD

**Issue by Tacodude7729** [ScratchAddons/ScratchAddons#3540]
Right now when click 'duplicate' from the right click menu of a block, it duplicates that block and everything attached to it, much like the dragging behavior.  In SA now, we can grab single blocks with the ctrl key, and it would be nice to be able to duplicate single blocks too.
I think this should be done through the same mechanism as grabbing one block, holding the ctrl key. If you where holding ctrl while you pressed 'duplicate' it would only duplicate one block. It may be a good idea to change the 'duplicate' text to something like 'duplicate one block' while the control key is being held, to let the user know what is happening.

_Default behavior of duplicate, clicking duplicate on the script in the left produces the results on the right._
![image](https://user-images.githubusercontent.com/27910867/134113147-3fb4e393-1745-4fc8-b65c-b3bec881942f.png)
_Suggested behavior of duplicate, clicking duplicate with ctrl held on the script in the left produces the results on the right._
![image](https://user-images.githubusercontent.com/27910867/134113173-f1de2820-191e-48ff-b34e-880ffffeb2fd.png)

I think this would be best added to the existing  'Grab single block with Ctrl key' addon, I feel like it goes very naturally with it to the point where I absentmindedly found myself trying to do it (hence, this suggestion). 

It's also possible this could be implemented as an additional option in the right click menu, maybe if implemented in a separate plugin this could be an option.

**Comment by Tacodude7729** [comment]
I believe this is satisfactorily resolved by #3541

**Comment by towerofnix** [comment]
Agreed...

...but I think the coolness factor and this being probably pretty simple to implement means it's worth doing anyway. :shipit:

**Comment by lisa-wolfgang** [comment]
> 
> 
> I believe this is satisfactorily resolved by #3541

Yup -- since that method is more efficient than the one proposed here, I'll go ahead and close this issue. If someone wants the Ctrl key functionality in the right-click context menu, they should create another issue.
