### ISSUE TITLE
"Line breaks in comments" doesn't work

### ISSUE THREAD

**Issue by unity-ltd** [ScratchAddons/ScratchAddons#3550]
### Description

"Line breaks in comments" doesn't work with studio comments

### Repoduction steps

1. make a comment with a line break

### Expected behaviour

It makes a line break

### Actual behaviour

It still converts it into spaces

### Environment

- Browser: 
- Scratch Addons version: 1.20.2
- Operating system: Windows 10 21H1

**Comment by Dhuls-Scratch** [comment]
Can't replicate
### Environment

- Browser: Microsoft Edge 93.0.961.52
- Scratch Addons version: v1.20.2
- Operating system: Windows 10 Pro x64 21H1

What browser are you using?

**Comment by ianfife** [comment]
Cannot replicate

### **Environment**

- Browser: Brave 1.29.81 (93.0.4577.82)
- Scratch Addons version: v1.20.2
- Operating system: Windows 11 21H2

**Comment by apple502j** [comment]
Closing until we get a repro case. If you reproduced the issue, please inspect the comment's element (the one with `comment-content` class) and paste the applied styles listed on the DevTools. It should list "white-space: break-spaces". If it is listed but the comment does not have linebreaks, please untick and re-tick the checkbox next to the white-space CSS rule listing (that is a browser glitch, not ours)
