### ISSUE TITLE
the scratch addons stopped working

### ISSUE THREAD

**Issue by littlemono1** [ScratchAddons/ScratchAddons#3552]
idk but see the screenshots i took
https://drive.google.com/file/d/1Aphc4aJDUqp3AKwr1tDuuFLi5arBFA7J/view?usp=sharing
https://drive.google.com/file/d/1_1mgSnGhNo5YybWZDfezXY2hZQo17xFR/view?usp=sharing
it is not loading

**Comment by apple502j** [comment]
Try reinstalling Scratch Addons.

**Comment by apple502j** [comment]
Closing until we get a repro
