### ISSUE TITLE
New Addon - Project Fullscreen

### ISSUE THREAD

**Issue by e-coders** [ScratchAddons/ScratchAddons#3553]
New Addon - Project Fullscreen
I've made it, I hope that it may also works, but I want to merge commit. please merge pull request.
For Source Code - "e-coders-official/ScratchAddons/addons/project-fullscreen" there I've added.

**Comment by e-coders** [comment]
https://github.com/E-Coders-Official/ScratchAddons

**Comment by e-coders** [comment]
https://github.com/ScratchAddons/ScratchAddons/pull/3554

**Comment by e-coders** [comment]
https://github.com/ScratchAddons/ScratchAddons/pull/3554

**Comment by e-coders** [comment]
https://github.com/ScratchAddons/ScratchAddons/pull/3554

**Comment by e-coders** [comment]
https://github.com/ScratchAddons/ScratchAddons/pull/3554

**Comment by e-coders** [comment]
https://github.com/ScratchAddons/ScratchAddons/pull/3554

**Comment by e-coders** [comment]
?

**Comment by RedGuy12** [comment]
Duplicate of #587

**Comment by e-coders** [comment]
But there I've added a Embed Page. I can simply say that I'v Really not copied. You can see the code.

**Comment by e-coders** [comment]
:((
