### ISSUE TITLE
Support dark mode in project trashing modal

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#3569]
> When permanently deleting your projects from the trash folder, the popup that appears saying something like "Enter your password to permanently delete these projects", appears with a white background even though I have one of the dark themes enabled.

cc @mxmou

**Comment by Endermaster3690** [comment]
what does cc mean

**Comment by TheColaber** [comment]
I would always check Google before asking those kinda questions, but it means "carbon copy", which it's name was used back when people use typewriters. But again, that question is offtopic.

**Comment by apple502j** [comment]
No, we're not going to remove project modal dark mode. /s
