### ISSUE TITLE
Error on the extension.

### ISSUE THREAD

**Issue by jemunm378** [ScratchAddons/ScratchAddons#357]
**Describe the bug**

There's a error that say "Unrecognized manifest key 'browser_specific_settings'."

**To Reproduce**

1. Go to 'chrome://extensions/'
2. Look for 'Scratch Addons'
3. Click on 'Errors'

**Expected behavior**

No Errors suppose to be shown.

**Screenshots**

Can't.

**Device (please complete the following information):**

- OS: [Windows]
- Browser [Chrome]

**Additional context**

None.

**Comment by WorldLanguages** [comment]
That's just a warning for an unrecognized manifest key that's required by Firefox, it would be cool to get rid of it, but sadly Firefox has no way of having a separate manifest for it :(

**Comment by jemunm378** [comment]
Oh, Alright!
