### ISSUE TITLE
Hold shift to drag block duplicate

### ISSUE THREAD

**Issue by towerofnix** [ScratchAddons/ScratchAddons#3572]
### Is your request related to a problem? Please describe.

When working with large scripts, it's pretty common to want to reuse similar patterns of blocks—even just variables accessed multiple times in a script, for example. Right-clicking and selecting "Duplicate" each time can be pretty slow, and so is moving to the block palette and dragging out the block(s) you're going to use multiple times.

### Describe the solution you'd like

An addon which adds a simple feature to the existing drag-drop gesture would help greatly: hold shift while starting a drag to create a duplicate of the block and attach it to the cursor, like normal Duplicate menu behavior. (A difference would be that the block is dropped when the drag ends, rather than when clicking, unlike the "attached" blocks of the menu.)

### Describe alternatives you've considered

Manually duplicating (via menu) or dragging from the block palette both work, but are slow. This is a quality of life addon request. Nothing groundbreaking, but it could come in handier than the existing alternatives!

### Additional context

For stack blocks, I feel it wouldn't be very useful to duplicate following blocks (like normal menu behavior). This could be left as an option, but I think the default should be to only duplicate the clicked stack block (and, as same with reporters, blocks inside inputs too).

**Comment by lisa-wolfgang** [comment]
https://github.com/ScratchAddons/ScratchAddons/pull/3541

**Comment by lisa-wolfgang** [comment]
Implemented in the above PR.
