### ISSUE TITLE
Forum editing glitch

### ISSUE THREAD

**Issue by RAFhub6** [ScratchAddons/ScratchAddons#3576]
### Description

The bug appears to be a forum button glitch, and scratch blocks in categories aren't displaying.
### Repoduction steps

1. 
2. 
3. 

### Expected behaviour
Button icons are expected.

Expected all of the icons, and scratch blocks access.
### Actual behaviour
There are no icons and i'm unable to place scratch blocks

### Screenshots
![Screenshot 2021-09-28 191626](https://user-images.githubusercontent.com/72543405/135060616-7b5bde16-0c86-4c13-93f0-0ff6a57ab8a5.png)

### Environment

- Browser: 
- Scratch Addons version: 
- Operating system: 

### Additional context

When i'm editing on the forums, this happens.
The buttons glitched out, Is there anything causing this?

**Comment by 000-001-87** [comment]
.
