### ISSUE TITLE
List import block

### ISSUE THREAD

**Issue by Bumburblast** [ScratchAddons/ScratchAddons#3580]
An addon that allows to import lists and/or export them, but that can only be used outside scratch (like the turbowarp extension because of the possible corruptions than having it in normal scratch).
What I'm looking for with this, is a system to save files with lists, but I don't know if you can export and import the list data not being in the editor.
They would be type blocks that export (or edit) the txt file in the same folder that turbowarp creates when exporting the project in executable.
And another block that only imports that txt file, so you could do things with the lists like passing data from one version of the project to another.

I'm sorry if I'm too annoying with this, but I'm just looking for a method for that, save and load games in scratch without variables in the cloud.

**Comment by apple502j** [comment]
Please do not suggest TurboWarp-exclusive features here.
