### ISSUE TITLE
Dango glitching

### ISSUE THREAD

**Issue by Mbrick2** [ScratchAddons/ScratchAddons#3586]
### Repoduction steps

1. Activate Dango rain on profile (April Fools Day)
2. Open a user page with the word dango in about me
3. Drag a link or scroll slowly (latter doesn't always work)

### Expected behaviour

The animation will continue

### Actual behaviour

It glitches like shown in video below

### Video

https://user-images.githubusercontent.com/90691415/135439143-03a5fead-fc1a-4200-81c4-d75458c0a059.mov

Its slightly sped up

### Environment

- Browser: Chrome 93
- Scratch Addons version: 20.2
- Operating system: macOS mojave

**Comment by mxmou** [comment]
I tried both dragging links around and scrolling, but it didn't do this.

**Comment by Mbrick2** [comment]
I tried in edge and it was fine

**Comment by WorldLanguages** [comment]
> I tried in edge and it was fine

Chromium edge shouldn't act differently, weird

**Comment by RedGuy12** [comment]
Closing as stale
