### ISSUE TITLE
Content script modifies document in images

### ISSUE THREAD

**Issue by starkodder** [ScratchAddons/ScratchAddons#3610]
I were on a scratch svg file, and when I imported the file to scratch it couldent saved.
This was caused by scratchaddons adding a script tag to every .scratch.mit.edu/ site.
I needed to delete it maually in inkscape.

To solve this: just add the script file to .html files.
Why scratch caused it: they dont want you to add malware download javascript svg files?

My browser: firefox, OS: windows 10 pro

**Comment by WorldLanguages** [comment]
@starkodder This is interesting and something I have never considered. But what's the URL for the SVG file? Scratch Addons only has access to `scratch.mit.edu/*`, `api.scratch.mit.edu/*` and `clouddata.scratch.mit.edu/*`. We don't have access to cdn, cdn2 or assets subdomains. So I guess this was an SVG file from the Scratch GUI (green flag button img or something like that?)
