### ISSUE TITLE
Comment blocks

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#3614]
Moved from #3134

It would be great to have comment blocks as an independent addon. However, currently only `debugger` adds its own blocks to the editor, so that's the name of the addon category. We should change that.
We should also discuss the name for the block. Should it be `//`, `comment` or `comment:`?

![image](https://user-images.githubusercontent.com/17484114/136289335-43e7416f-3b48-4869-b0e4-1aff38dc1e07.png)

**Comment by TheColaber** [comment]
Maybe also a todo block?

**Comment by Endermaster3690** [comment]
how's this gonna work with non sa users

**Comment by Endermaster3690** [comment]
> > how's this gonna work with non sa users
> 
> It's just a custom block.

people can make their own custom blocks for comments

**Comment by CST1229** [comment]
> 
> 
> > > how's this gonna work with non sa users
> > 
> > 
> > It's just a custom block.
> 
> people can make their own custom blocks for comments

Having it just be on the block palette makes it quicker to use and doesn't leave useless define blocks on the code area.

**Comment by WorldLanguages** [comment]
> we only need 1 define block

per sprite

**Comment by Samq64** [comment]
> What bug did it fix and which addon?

Clean up blocks+ fixes a bug where comments don't move with the blocks they're attached to when clean up blocks is used.

**Comment by Endermaster3690** [comment]
> > we only need 1 define block
> 
> per sprite

that's what i mean.

**Comment by WorldLanguages** [comment]
editor-devtools could also search for vanilla comments

**Comment by Oren-Lindsey** [comment]
> editor-devtools could also search for vanilla comments

I'm pretty sure that you yourself actually said that wasn't possible

**Comment by WorldLanguages** [comment]
You might be right, I'm not sure. I just know vanilla comments are very buggy

**Comment by apple502j** [comment]
It is possible (just use VM instead of Blockly).

**Comment by RedGuy12** [comment]
has perf impacts, see https://github.com/ScratchAddons/ScratchAddons/pull/3644#issuecomment-991935765

**Comment by WorldLanguages** [comment]
Okay, so let's consider comment blocks rejected unless someone can prove it's worth it and the performance impacts aren't noticeable.
