### ISSUE TITLE
`fullscreen`: Open in browser full screen doesn't work

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#3629]
### Description

`Open full screen project player in full screen browser mode` doesn't work.

### Repoduction steps

1. Enable the enhanced full screen addon.
2. Enable the "Open full screen project player in full screen browser mode" option.
3. Open a project.
4. Click the fullscreen button.

### Expected behaviour

The browser should enter fullscreen when pressing the fullscreen button.

### Actual behaviour

The browser doesn't enter fullscreen when pressing the fullscreen button.

### Screenshots

N/A

### Environment

- Browser: Edge 94, Firefox 93
- Scratch Addons version: 1.21.1
- Operating system: Windows 11 21H2

**Comment by Samq64** [comment]
Cannot reproduce any more after restarting Microsoft Edge.

**Comment by WorldLanguages** [comment]
Sometimes browsers refuse to open full screen for weird reasons :P

**Comment by Samq64** [comment]
I can reproduce again, but it's inconsistent.

**Comment by Samq64** [comment]
This seems to happen on both the editor and project pages. When it does happen it keeps happening consistently until toggling the setting on and off and reloading the page. Sometimes that helps and sometimes it doesn't. If it does work then it keeps working consistently until the user adjusts the setting again.

**Comment by lisa-wolfgang** [comment]
Hmm, I'm not sure what the issue is if you can't consistently reproduce it. I haven't been able to reproduce this myself on Edge either.
