### ISSUE TITLE
Make a variable that reports if dark mode is on

### ISSUE THREAD

**Issue by Oren-Lindsey** [ScratchAddons/ScratchAddons#3647]
### Is your request related to a problem? Please describe.
It's currently not possible to tell if a user has dark mode turned on

### Describe the solution you'd like
I'd like a bool that tells you if dark mode is turned on. It would be like the Turbowarp <is compiled?> block, and it would return true if the user had SA and dark mode was turned on, and false if they didn't. This would allow projects to match the look and feel of the website. You have dark mode on? Then the project has dark mode. This seems easy to do to me, and so I think you should do it.

### Describe alternatives you've considered
Going even further, it would be incredible if you could detect if any addon was turned on, like this:
![scratchblocks-4](https://user-images.githubusercontent.com/67929847/137024043-80a9a5b7-9275-428d-ab15-9d298e368cbe.png)
Or at least detect addons that made visual changes to scratch

### Additional context
It could look like this:
<img width="131" alt="Screen Shot 2021-10-12 at 4 18 06 PM" src="https://user-images.githubusercontent.com/67929847/137024020-7263100f-10cc-4ec0-8d1c-4741321629cb.png">

**Comment by RedGuy12** [comment]
No
