### ISSUE TITLE
gamepad: compatible controllers

### ISSUE THREAD

**Issue by debugyoshi** [ScratchAddons/ScratchAddons#3688]
I tried using a Wii Remote with the addon Gamepad support. I succesfully used bluetooth to my computer, but the addon couldn't detect it. Am I doing something wrong, or is the Wii Remote not supported?

**Comment by lisa-wolfgang** [comment]
@debugyoshi On Windows, you need to install a special driver to use a Wii Remote as a proper controller: https://www.julianloehr.de/educational-work/hid-wiimote/

**Comment by debugyoshi** [comment]
I should have mentioned that I am doing this on a chromebook. Thanks for the help though. I think my computer has the ability to connect with the Wii Remote, but Scratch doesn't detect it.
