### ISSUE TITLE
"Suggested by ____" credit for addons

### ISSUE THREAD

**Issue by Ani-Xan** [ScratchAddons/ScratchAddons#369]
I have suggested MANY addons and I think that other people who have also suggested addons might want to be credited for their hard work and digging through websites. (I've done that numerous times.) Have the "Suggested by _____" located where the white arrow is pointing: 
 
![Settings](https://user-images.githubusercontent.com/57809064/94847603-a8d02f80-03d7-11eb-987e-7bf01491aeea.png)

**Comment by WorldLanguages** [comment]
I don't think we need a new area for this, "credit to" is intentionally generic, unlike "made to" or similar. Why not just add your name and then `(suggested this)` or something like that?

**Comment by Ani-Xan** [comment]
@WorldLanguages Makes sense.
