### ISSUE TITLE
editor-theme3 reduces size of clickable area in block dropdowns

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#3702]
This was reproduced with editor-theme3 in default settings.

To reproduce:
1. Go to this test project https://scratch.mit.edu/projects/588538791/editor/
2. Zoom in to more easily reproduce
3. Click where shown in screenshot. Block will be ran, instead of the dropdown being opened. Mouse will show hand instead of pointer.
![image](https://user-images.githubusercontent.com/17484114/138568030-18875c05-60d6-4bb8-8b41-7acdbe32bd10.png)
4. Disable editor-theme3
5. Clicking in edge does open the dropdown:
![image](https://user-images.githubusercontent.com/17484114/138568044-4712c91d-2087-4268-8818-6e8a5650de1f.png)

**Comment by RedGuy12** [comment]
@awesome-llama if you can fix, feel free to pr


________________________________
