### ISSUE TITLE
full screen addon on chromebook instantly becomes small screen again

### ISSUE THREAD

**Issue by spazestudios** [ScratchAddons/ScratchAddons#3707]
when you do full screen on a chrome book with the better full screen addon it works for like 1 second and then goes small screen.

**Comment by lisa-wolfgang** [comment]
@spazestudios See if you can still reproduce the bug. If so, please post the version of Scratch Addons you currently have installed.

**Comment by Samq64** [comment]
I just tested again on Kiwi beowser using veesion 1.21.2 and I can't reproduce this problem anymore.
