### ISSUE TITLE
New addon: script snapping

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#3729]
### Is your request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/43426138/140004918-e27aae8d-4083-4e03-b4ad-1fe7cdbc222d.png)

Placing scripts in straight lines takes a lot of time and effort, and it's unsatisfying to just... leave them not straight!

### Describe the solution you'd like

When a certain key is pressed (or perhaps by default if a certain setting is toggled) scripts would snap to certain x and y intervals on a grid when dragged or placed. It would make sense to use the workspace dots as the default grid.

### Describe alternatives you've considered

Living with unstraightened scripts for the rest of my life...

**Comment by Mbrick2** [comment]
Maybe snapping to the dots on the code are?

**Comment by Secret-chest** [comment]
> Maybe snapping to the dots on the code are?

They wrote that

**Comment by Mbrick2** [comment]
> > Maybe snapping to the dots on the code are?
> 
> They wrote that

Sorry. Missed that

**Comment by TheColaber** [comment]
Iirc this is a feature Blockly has, that scratch disables. I think it might be as simple as setting a workspace option as true, but maybe not.

**Comment by RedGuy12** [comment]
How is this different from clean up blocks +?


________________________________

**Comment by CST1229** [comment]
> 
> How is this different from clean up blocks +?
>

That also rearranges scripts a bit, and also is not when dragging a script. This is just snapping to a grid.

**Comment by TheColaber** [comment]
> How is this different from clean up blocks +?

One automatically snaps dragged blocks to the nearest spot and snaps all blocks to a "cleaned up" spot. I would use this addon, especially since sometimes, where clean up puts it is not where I want it to stay.

**Comment by CST1229** [comment]
Enabling snapping is actually really simple:
```javascript
Blockly.getMainWorkspace().grid_.snapToGrid_ = true;```
There's also a `snap` option in `Blockly.getMainWorkspace().options.gridOptions` but that doesn't seem to do anything, even after refreshing by switching tabs/sprites.

**Comment by TheColaber** [comment]
Alright someone can make this addon with the code CST posted above. If you really wanted to, there could be a setting for the distance between the grid. It should be as easy as:
```js
Blockly.getMainWorkspace().grid_.spacing_ = 100; // set by setting
Blockly.getMainWorkspace().grid_.update(Blockly.getMainWorkspace().scale)
```

**Comment by Samq64** [comment]
I've got the addon working. Who should I add to credits before creating a PR? CST1229, me or both?

**Comment by lisa-wolfgang** [comment]
@Samq64 I was working on it... I assigned myself to the issue.

**Comment by Samq64** [comment]
> 
> 
> @Samq64 I was working on it... I assigned myself to the issue.

Oh...

**Comment by lisa-wolfgang** [comment]
Should there be a button in the editor itself that toggles snapping? There may be rare occasions that a user would want to toggle snapping off.

**Comment by Samq64** [comment]
I don't think so. The only addon that's togglable from the editor is onion skinning which gets toggled pretty often. There are a bunch of addons people wantto disable more than *rarely* and they don't get a toggle, do why should this one?

**Comment by WorldLanguages** [comment]
> Should there be a button in the editor itself that toggles snapping? There may be rare occasions where a user would want to toggle snapping off.

Or maybe yet another hotkey :joy:

**Comment by lisa-wolfgang** [comment]
No no no no, no more hotkeys 😂
It's probably fine to not have a non-settings toggle.

**Comment by Endermaster3690** [comment]
> No no no no, no more hotkeys 😂 It's probably fine to not have a non-settings toggle.

so you mean just add a button in the editor?

**Comment by CubeyTheCube** [comment]
Maybe a context menu button that snaps the scripts, instead of them being snapped by default?

**Comment by lisa-wolfgang** [comment]
There will probably be neither an editor button nor a hotkey because it would just add more clutter to the editor for a feature that probably would only rarely need to be toggled.
