### ISSUE TITLE
Fix Buttons in Scratch 3.0 page addon     

### ISSUE THREAD

**Issue by Mbrick2** [ScratchAddons/ScratchAddons#3733]
### Is your request related to a problem? Please describe.
 the buttons look like:
 
![image](https://user-images.githubusercontent.com/90691415/140263986-fc18841c-c807-4043-8fda-1d7fb799d915.png)
whereas vanilla 3.0 looks like:
![image](https://user-images.githubusercontent.com/90691415/140264063-f8295db4-22fd-4c12-8fce-75ef8b49379f.png)

### Describe the solution you'd like

make the button look like:
![image](https://user-images.githubusercontent.com/90691415/140264063-f8295db4-22fd-4c12-8fce-75ef8b49379f.png)

### Describe alternatives you've considered
None except having oddly styled buttons

**Comment by mxmou** [comment]
Are you talking about the size or the colors? The background color of these buttons will remain white because they're on a blue background.

**Comment by kccuber-scratch** [comment]
The "Leave Studio" button isn't even part of the vanilla studios, it's a Scratch Addons feature

**Comment by CST1229** [comment]
> 
> 
> The "Leave Studio" button isn't even part of the vanilla studios, it's a Scratch Addons feature

But Follow Studio is a vanilla studio thing.

**Comment by Mbrick2** [comment]
> Are you talking about the size or the colors? The background color of these buttons will remain white because they're on a blue background.

i mean the format of the roundness
