### ISSUE TITLE
"Customizable block colors" doesn't update the color of block comment borders

### ISSUE THREAD

**Issue by towerofnix** [ScratchAddons/ScratchAddons#3750]
### Description

There's a little-recognized feature of scratch-blocks which makes the border of comments attached to blocks match the primary color of the block. The "Customizable block colors" addon updates those colors for actual blocks, but any attached comments will be bordered with the original block color, causing a mismatch.

### Repoduction steps

1. Use "Customizable block colors" to change the color of a block category to a distinctly different color than the 3.0 default.
2. Drag out a block from that category.
3. Right click on it and choose "Add Comment" from the menu.
4. Look at the color of the comment border and compare it to the color of the block (as well as the color used for that block's category in 3.0 default).

### Expected behaviour

Comment borders should match the updated color!

### Actual behaviour

They always use 3.0's default colors, and cause a visual mismatch.

### Screenshots

![Comment attached to a custom block. The custom block is a purple similar to in Scratch 2.0, but the comment shows default 3.0's coral-red color as its border.](https://user-images.githubusercontent.com/9948030/140628296-504ee764-3b96-446c-ad4a-7c40f454491e.png)

### Environment

- Browser: Firefox 91.3.0esr
- Scratch Addons version: 1.21.2
- Operating system: Linux (Debian)

### Additional context

None! :space_invader:

**Comment by Mbrick2** [comment]
Happens to me also
firefox
macOS

**Comment by lisa-wolfgang** [comment]
Seems to only happen with custom blocks, as well as while dragging any block comment like Mbrick 2 mentioned.
