### ISSUE TITLE
Add special keys to the "When () Press" code.

### ISSUE THREAD

**Issue by ilbailba** [ScratchAddons/ScratchAddons#3753]
Let's add characters such as "Ctrl", "Shift", "Alt" and "Tab" keys to the code we normally know [if the () key is pressed].

**Comment by kccuber-scratch** [comment]
These keys cannot be detected in scratch

**Comment by ilbailba** [comment]
what do you want to say?

**Comment by CST1229** [comment]
> 
> 
> what do you want to say?

Scratch ignores these keys, even if you hack blocks with them in.

**Comment by ilbailba** [comment]
oh. I understand. then i need to delete this issue.

**Comment by CST1229** [comment]
> 
> 
> oh. I understand. then i need to delete this issue.

Issues don't get deleted. They just get closed.
