### ISSUE TITLE
Allow messaging to work with multiple accounts.

### ISSUE THREAD

**Issue by Joeclinton1** [ScratchAddons/ScratchAddons#3764]
### Is your request related to a problem? Please describe.

I have 2 accounts and inorder to check my messages on both I am constantly swapping between them, each time I have to login so the messaging addon doesn't help much. 

### Describe the solution you'd like

I want the messaging api to automatically sign me out of my current account into my alternate account, check for messages, repeat for all other alternate accounts and then sign back into the original account. Then I'd like these messages to be shown in the messaging tab, with containers for each account.

it would also need a section in the addon to add your username and password for each account so that it can work properly.

### Describe alternatives you've considered

Currently I just sign in and out of my accounts but that is slow and the whole purpose of the messaging api is to notify me when I get new messages.
I looked through the issues and i couldn't find an issue aiming to solve this specific problem.

**Comment by RedGuy12** [comment]
We probably won't be storing session ids for security reasons. See #3327.

**Comment by Joeclinton1** [comment]
> We probably won't be storing session ids for security reasons. See #3327.

Could you name the security issue? Why would storing your session id's in an extension be a security issue?

**Comment by WorldLanguages** [comment]
Storing passwords in plain text (or trying our best to encrypt them somehow) would probably be a terrible idea.
Storing session ids (which take a lot of time to expire on Scratch) is covered in #3327 and I've delayed the decision of choosing whether Scratch Addons should interact directly with session ids (it currently does not) or if this logic should be moved to a separate extension also offered by the Scratch Addons project.

**Comment by Joeclinton1** [comment]
@WorldLanguages Normally the issue with storing passwords on a computer is that anyone with access to the computer can have access to the password, but the assumption is that the only person with access to the computer is the user. Also scratch.mit.edu passwords are hardly valuable to an intruder. Overall, storing a password on your computer isn't a security risk.  I cannot think of any other problem. You will have to give the extension your password or session_id but since the code is open source I wouldn't have a problem with doing that.

**Comment by apple502j** [comment]
Note that the security risk is just one thing - this code is reviewed by the Chrome and Firefox team, and storing password in an extension that is not a password manager is not something they'd want.

**Comment by Joeclinton1** [comment]
@apple502j I'm guessing you don't have a source which backups the statement that "storing password in an extension that is not a password manager is not something [Chrome or firefox] want" and that you just assumed that is the case.

The two sources which chrome provides are https://developer.chrome.com/docs/webstore/user_data/ and https://developer.chrome.com/docs/webstore/program_policies/.

The two above sources will confirm for you that any data handled locally does not need to be encrypted and chrome does not care if you store sensitive user data locally only. The only requirement is to update the privacy policy of the extension to discuss how this sensitive data is handled.

Firefox's policies are mentioned here: https://extensionworkshop.com/documentation/publish/add-on-policies-dec-2021/. Their policy is very similar to chromes and will also want an update to the privacy policy in order to align with their "no surprises" policy.

If you still think storing passwords locally is a security flaw and that chrome would not want it, maybe check out chrome://settings/passwords, which shows chrome's own password storage method where they store your passwords locally.

**Comment by micahlt** [comment]
> And why might they allow local storage of sensitive user data?
... because it's not a security risk!

Seems a little like an oversimplification - storing any data is always a slight security risk.  However, in this case it does appear that storing multiple session ID's in a database (preferably cryptographically encrypted) would be safe enough to justify adding it as a feature.

**Comment by RedGuy12** [comment]
If we added the addon, the session ids would likely be in chrome.storage.local unencrypted

**Comment by Joeclinton1** [comment]
@micahlt You don't need to store it in a database, just a text file or better with chrome's local storage api. As long as it is local the only risk is from a hacker gaining access to your device and searching for your passwords. But since chrome stores all your passwords locally, if a hacker gains access to your device they have your passwords either way. 

if you want to obfuscate the passwords you may want to two way encrypt them, but since you are also storing the key locally it doesn't do much.

**Comment by micahlt** [comment]
> @micahlt You don't need to store it in a database, just a text file or better with chrome's local storage api. As long as it is local the only risk is from a hacker gaining access to your device and searching for your passwords. But since chrome stores all your passwords locally, if a hacker gains access to your device they have your passwords either way.
> 
> if you want to obfuscate the passwords you may want to two way encrypt them, but since you are also storing the key locally it doesn't do much.

Fair enough!  Also, didn't mean to say "database", it was just second nature.  I figure you'll be using localStorage or something of the sort.

**Comment by Joeclinton1** [comment]
In the spirit of offering a fair argument I dug deeper into what the security risks could be beyond just someone gaining access to your password after accessing your computer. 

https://stackoverflow.com/questions/28543958/security-implications-of-storing-client-side-generated-passphrase-in-chrome-stor

This seems to be pretty comprehensive. They give the extra risk that another process or extension with high-privilege levels might read it off your computer and then send it to a server. Whilst I don't think there's a high risk of an extension doing this or anyone caring that much about your scratch password, you could reduce the risk by encrypting the password. Even if the encryption key is stored in the same place.

Their recommended solution is to store on a server, but that would require a server, transmitting passwords correctly, and then there's even more security risk. To do that you have to know what you're doing. Storing it locally, in my opinion is low risk since these are not bank details they're scratch session id's.

**Comment by WorldLanguages** [comment]
> If we added the addon, the session ids would likely be in chrome.storage.local unencrypted

I think the open PR stores them as http only cookies, to be consistent with how Scratch stores them. This way, it's very easy and we just need to tell users their logged in alt accounts have the same security protections as if they were actually logged into all of them at once somehow.

**Comment by Joeclinton1** [comment]
So what's the verdict on this? This is one of the features which would save me the most time, as it would let me get notifications about messages from both of my accounts without having to keep swapping accounts. It's a feature I really need, and that I assume others with the same problem need.

**Comment by apple502j** [comment]
@Joeclinton1 This is now possible. And thankfully, without saving passwords or sessions ourselves. For now, this requires Firefox - you can either use incognito, or use Firefox Container (note that the latter requires Scratch Messaging to be used in tab mode.) Simply log into the account on the main website using those sessions, and open Scratch Messaging using the same session - it should show up the results for the account then.
