### ISSUE TITLE
Search input is too small to fit addon name

### ISSUE THREAD

**Issue by Purple-Hacker** [ScratchAddons/ScratchAddons#377]
**Describe the bug**
The search box is too small and should be bigger.

**To Reproduce**

1. Go to options
2. Look at search bar
3. Type multiple words
4. It is too small

**Expected behavior**
It should be bigger to fit multiple words.

**Screenshots**
![scratchsearchtoosmall](https://user-images.githubusercontent.com/63299718/94990903-a01a5d80-057f-11eb-87f5-4af648beef33.png)

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Chrome latest
- Version: 1.0.0

**Comment by Explosion-Scratch** [comment]
How about making it expand on focus? Or maybe expand based on the text
inside? (Keep in mind that a smooth transition would be needed in this case)

On Saturday, October 3, 2020, Purple-Hacker <notifications@github.com>
wrote:
> Describe the bug
> The search box is too small and should be bigger.
>
> To Reproduce
>
> Go to options
> Look at search bar
> Type multiple words
> It is too small
>
> Expected behavior
> It should be bigger to fit multiple words.
>
> Screenshots
> <
https://ci3.googleusercontent.com/proxy/saCbt4bVtUO8C4V_HMRheubNh19DJ4izDp7kNUrNtjOG4k2uqIyeMWf6DFUbvYjebd8poJWDhRRovPTx_GHJ3TDHXNhh6D63kZyxRKnhPcHjAUYDwGvNqZgR3VXDlA-P1oGKsQhlNZRd1UQuaj0gSxk71Ybf2Fk=s0-d-e1-ft#https://user-images.githubusercontent.com/63299718/94990903-a01a5d80-057f-11eb-87f5-4af648beef33.png
>
>
> Device (please complete the following information):
>
> OS: Windows 10
> Browser: Chrome latest
> Version: 1.0.0
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/loOUstXqBquXwv_fTRYxN8yFgMSfM55kx243Eenk7uRweoI9K3PWcIALicNQ_uawQ3xFKLYOZ-YwfbQZuyuSO_F3Wy48VybGPJI--L_It7ucGcy-OzRC9F62iOaIjpUnuwS1RjdrNdjnapnGO4KBuk9ZriR1xYQcz5aerxgjUzGt2yNjaDbPgwvBIStwJD55QZeM6XBeQOvZ_vng-f6E4LqORSU=s0-d-e1-ft#https://github.com/notifications/beacon/AOT2P3R7B2JW22K24E7OKH3SI4GDZA5CNFSM4SCTQNG2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4KUP4YPQ.gif>

**Comment by WorldLanguages** [comment]
btw @Explosion-Scratch please stop replying to github issues through email, for some reason it comes out pretty spammy :c

**Comment by Explosion-Scratch** [comment]
Sorry. I forgot about that. It seems that replying to it through email on desktop works fine but when I reply through email on nmobile it totally glitches. I messed around with settings yesterday and I thought it fixed it, but evidentally not. I'll just visit the issue to reply from now on. Apologies.
