### ISSUE TITLE
Searching for enabled addons with "New" tag causes them to expand or shrink after each change

### ISSUE THREAD

**Issue by GarboMuffin** [ScratchAddons/ScratchAddons#3775]
### Description

https://user-images.githubusercontent.com/33787854/141031044-77e2edf9-fb18-494b-870d-e7920deb239f.mp4

Happens when you search for any enabled addons that has the "New" tag

## Environment

Scratch Addons 1.22

**Comment by apple502j** [comment]
![image](https://user-images.githubusercontent.com/33279053/141609735-0abd7ffb-efed-4ab4-8c0c-70dc062bf5cc.png)
Definitely is wrong

**Comment by TheColaber** [comment]
No, it's likely for there to be 2 elements when nothing is searched since it's new, but hopefully not when searching.

**Comment by RedGuy12** [comment]
Duplicate IDs are a nono


________________________________
