### ISSUE TITLE
Comment straightening + leashing

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#3782]
https://github.com/ScratchAddons/ScratchAddons/pull/3731 does not currently implement any functionality for comments. The ideal solution would be to add a "straightening" feature that would ensure that all block comments' connections are perfectly horizontal. It would also be nice to ensure that block comments don't stray too far from the actual block, which does happen quite often in sprawling workspaces.

Comment leashing should probably go in `fix-editor-comments` because it's pretty much a bug fix. The only problem is deciding where to put comment straightening. There are 2 main options:
1. In `script-snap`, which would make sense because they make comments neater, but the comment leash feature wouldn't fit here.
2. In `fix-editor-comments`, which would definitely make sense for the comment leash because the user doesn't typically expect block comments to be created about three screens away from the block, but maybe not the best option for the comment straightening since that isn't something everyone would want. But then again, this addon is all about enhancing comments...

It could alternatively be its own addon. It would be a rather small one, and I personally think it would fit better in another addon, but I'm just jotting this down to consider.

**Comment by Samq64** [comment]
> ...maybe not the best option for the comment straightening since that isn't something everyone would want.

Why is that a problem? Each bug fix in that addon is already togglable, so this one could just go there and be disabled by default.

**Comment by lisa-wolfgang** [comment]
> 
> 
> > ...maybe not the best option for the comment straightening since that isn't something everyone would want.
> 
> Why is that a problem? Each bug fix in that addon is already togglable, so this one could just go there and be disabled by default.

I suppose.
