### ISSUE TITLE
Move effect stage setting to a new add-on

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#3797]
### Is your request related to a problem? Please describe.

It would be nice to be able to customize some stage elements separately from `editor-dark-mode`.

### Describe the solution you'd like

A new add-on to be able to customize the colours of monitors, speech bubbles and ask prompts separately. This addon could also implement #3590.

### Describe alternatives you've considered

An addon that only customizes stage monitors while leaving the affect stage setting in `editor-dark-mode`.

### Additional context

N/A

**Comment by RedGuy12** [comment]
Why
________________________________
From: Samq64 ***@***.***>
Sent: Saturday, November 13, 2021 4:18:05 PM
To: ScratchAddons/ScratchAddons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScratchAddons/ScratchAddons] Move effect stage setting to a new add-on (Issue #3797)


Is your request related to a problem? Please describe.

It would be nice to be able to customize some stage elements separately from editor-dark-mode.

Describe the solution you'd like

A new add-on to be able to customize the colours of monitors, speech bubbles and ask prompts separately. This addon could also implement #3590<https://github.com/ScratchAddons/ScratchAddons/issues/3590>.

Describe alternatives you've considered

An addon that only customizes stage monitors while leaving the affect stage setting in editor-dark-mode.

Additional context

N/A

**Comment by WorldLanguages** [comment]
I'm not sure about this

**Comment by Samq64** [comment]
Yeah, now that I think about it, this is a bad idea.

**Comment by kccuber-scratch** [comment]
But what if it has more than colors? Like border radius and height and stuff of the stage monitors.

**Comment by lisa-wolfgang** [comment]
Will be partially resolved by https://github.com/ScratchAddons/ScratchAddons/pull/3912.

**Comment by mxmou** [comment]
> Yeah, now that I think about it, this is a bad idea.

The stage appears both in the editor and on the project page so I think this is better than always using the editor dark mode colors.

**Comment by Samq64** [comment]
Closing in favour of #5602.
