### ISSUE TITLE
New addon: Remove create button

### ISSUE THREAD

**Issue by webdev03** [ScratchAddons/ScratchAddons#3812]
### Is your request related to a problem? Please describe.
I have about 100 untitled projects laying in My Stuff. They're all because when I want to click on a button in the navbar I accidentally click on the Create button and it makes a new project.

### Describe the solution you'd like

An addon to remove the create button (projects can still be made; My Stuff > New Project)
![image](https://user-images.githubusercontent.com/75148774/141740223-297f523a-b433-4b3b-87f0-a18c13d0c902.png)
Maybe there could be a "Customise navbar" addon? I don't know how that would work for scratchr2 pages though maybe.

### Describe alternatives you've considered

Search through mystuff with the new addon to search through it and delete it manually but it still doesn't remove the create button.

### Additional context

![image](https://user-images.githubusercontent.com/75148774/141740080-b5ef597d-311e-4229-bd02-12e7f78a1c35.png)

**Comment by mxmou** [comment]
#951 is probably better than an addon to remove specific buttons.

**Comment by webdev03** [comment]
> #951 is probably better than an addon to remove specific buttons (although this would also be very useful).

oh sorry.. I had looked for just removing the about part.. not the whole navbar 😞
