### ISSUE TITLE
30 fps patch for firefox

### ISSUE THREAD

**Issue by SmearyThrower** [ScratchAddons/ScratchAddons#3813]
### Is your request related to a problem? Please describe.

 playing scratch games on Firefox run at a less than 30fps unlike on chrome with a constant 30fps it makes certain projects too slow and glitchiy to play

### Describe the solution you'd like

 I want a toggle on by default which forces scratch to run in 30 fps mode on firefox

### Describe alternatives you've considered

 use chrome

### Additional context

 none thank you

**Comment by webdev03** [comment]
Hmm...
I can't find the same problem when playing Appel.
Which projects does it happen on? Just wondering

**Comment by apple502j** [comment]
The project should run in 30FPS on any browsers.

**Comment by hello-smile6** [comment]
> ### Is your request related to a problem? Please describe.
> playing scratch games on Firefox run at a less than 30fps unlike on chrome with a constant 30fps it makes certain projects too slow and glitchiy to play
> ### Describe the solution you'd like
> I want a toggle on by default which forces scratch to run in 30 fps mode on firefox
> ### Describe alternatives you've considered
> use chrome
> ### Additional context
> none thank you

Couldn't you just use TurboWarp's scratch-vm on Scratch and load a different copy of scratch-gui?
