### ISSUE TITLE
Reduce the amount of network requests to ocular

### ISSUE THREAD

**Issue by webdev03** [ScratchAddons/ScratchAddons#3814]
### Is your request related to a problem? Please describe.

In the my-ocular addon for every post it fetches from the myocular API to display the status and colour. Too many requests which just return the same thing over and over again (unless you want to have different jokes for each post I guess?)

### Describe the solution you'd like

Store the ocular status and colours on the client in an object for each user on a page, check if the user's ocular status has already been fetched, if not fetch their status to prevent unnecessary requests to the myocular API.

### Describe alternatives you've considered

Dealing with the extra network requests!

### Additional context

Firefox Network tab.

**Comment by Dhuls-Scratch** [comment]
I just checked using [this topic](https://scratch.mit.edu/discuss/topic/557895/?page=1), using Scratch Addons 1.22.0, Microsoft Edge 95.0.1020.53, and Windows 10 64-bit. Out of the 245 requests made (note that I had "Disable Cache" checked), 40 of them (16.33%, almost 1/6) were to my-ocular.jeffalo.net. Of those 40 requests, half are post reactions (which I don't think we can do anything about), and the other half were statuses. However, half of the statuses (a quarter of all my-ocular requests) were repeats.

This could also solve the weird thing were {joke} tags can appear differently for the same person
![Screenshot 2021-11-15 212154](https://user-images.githubusercontent.com/87714852/141890089-6b7f4550-43e8-4237-bec9-d5187157928e.png)

**Comment by webdev03** [comment]
@Dhuls-Scratch That's exactly what I noticed and why I made this issue.

**Comment by webdev03** [comment]
I've started to try to make a fix for this to see if it is possible...

**Comment by webdev03** [comment]
https://github.com/webdev03/ScratchAddons/tree/ocular-status-fix I'm having a bit of trouble fixing it... if anyone can see my code.. I'm stuck for days and I can't figure out what went wrong

**Comment by jeffalo** [comment]
in ocular, i implemented a cache so that each user is stored in an array. before fetching a user, check if they are already in the array/have a promise that resolves to the user.

something similar should work here as well.

**Comment by webdev03** [comment]
I was trying to do that a few weeks back, but I kept on running into problems. I'll try again later today.

**Comment by CST1229** [comment]
@jeffalo What about adding an ocular endpoint to bunch multiple reaction/user requests into one?

**Comment by webdev03** [comment]
```js
export default async function ({ addon, global, console, msg }) {
  let posts = document.querySelectorAll(".blockpost");
  var store = {};
  // ...
  async function fetchStatus(username) {
    console.log(store[username])
    if (typeof store[username] != "undefined") {
      return {
        userStatus: store[username].userStatus,
        color: store[username].color
      }
    }
    const response = await fetch(`https://my-ocular.jeffalo.net/api/user/${username}`);
    const data = await response.json();
    store[username] = {
      userStatus: data.status,
      color: data.color,
    };
    return store[username];
  }
}

```
I'm unsure why it doesn't work.

**Comment by jeffalo** [comment]
> @jeffalo What about adding an ocular endpoint to bunch multiple reaction/user requests into one?

it's possible but unnecessary imo

> doesn't seem to store though

looks like it would only be storing after fetching the user, which doesn't help much as all the requets would be at the same time.

perhaps try storing the promise instead?

**Comment by webdev03** [comment]
> looks like it would only be storing after fetching the user, which doesn't help much as all the requets would be at the same time.
perhaps try storing the promise instead?

Thanks! I'll try that.

**Comment by hello-smile6** [comment]
> > looks like it would only be storing after fetching the user, which doesn't help much as all the requets would be at the same time.
> > perhaps try storing the promise instead?
> 
> Thanks! I'll try that.

I hope it works.

**Comment by webdev03** [comment]
```js
export default async function ({ addon, global, console, msg }) {
  let posts = document.querySelectorAll(".blockpost");
  var store = {};
  posts.forEach(async (i) => {
    let username = i.querySelector(".username").innerText;

    let left = i.querySelector(".postleft").children[0];
    var userStatus, color;
    console.log(typeof store[username], store[username])
    if (typeof store[username] != "undefined") {
      var { userStatus, color } = store[username];
    } else {
      var { userStatus, color } = await fetchStatus(username);
      store[username] = { userStatus: userStatus, color: color };
    }
    if (userStatus) {
      let br = document.createElement("br");
      addon.tab.displayNoneWhileDisabled(br);
      let status = document.createElement("i");
// ...
```
Don't know what happened. It's still confusing me!!

**Comment by hello-smile6** [comment]
> ```js
> export default async function ({ addon, global, console, msg }) {
>   let posts = document.querySelectorAll(".blockpost");
>   var store = {};
>   posts.forEach(async (i) => {
>     let username = i.querySelector(".username").innerText;
> 
>     let left = i.querySelector(".postleft").children[0];
>     var userStatus, color;
>     console.log(typeof store[username], store[username])
>     if (typeof store[username] != "undefined") {
>       var { userStatus, color } = store[username];
>     } else {
>       var { userStatus, color } = await fetchStatus(username);
>       store[username] = { userStatus: userStatus, color: color };
>     }
>     if (userStatus) {
>       let br = document.createElement("br");
>       addon.tab.displayNoneWhileDisabled(br);
>       let status = document.createElement("i");
> // ...
> ```
> 
> Don't know what happened. It's still confusing me!!

I'll install vscode and look at it, maybe I could help.

**Comment by hello-smile6** [comment]
I didn't install vscode yet.

**Comment by hello-smile6** [comment]
@webdev03 Okay, what isn't working?

**Comment by webdev03** [comment]
The whole script.

**Comment by hello-smile6** [comment]
> ```js
> export default async function ({ addon, global, console, msg }) {
>   let posts = document.querySelectorAll(".blockpost");
>   var store = {};
>   posts.forEach(async (i) => {
>     let username = i.querySelector(".username").innerText;
> 
>     let left = i.querySelector(".postleft").children[0];
>     var userStatus, color;
>     console.log(typeof store[username], store[username])
>     if (typeof store[username] != "undefined") {
>       var { userStatus, color } = store[username];
>     } else {
>       var { userStatus, color } = await fetchStatus(username);
>       store[username] = { userStatus: userStatus, color: color };
>     }
>     if (userStatus) {
>       let br = document.createElement("br");
>       addon.tab.displayNoneWhileDisabled(br);
>       let status = document.createElement("i");
> // ...
> ```
> 
> Don't know what happened. It's still confusing me!! Maybe I should leave this to someone who understands async more than me.....

Just put all of your code in an `async` function and use `await` on any async functions you run.

**Comment by hello-smile6** [comment]
@webdev03 Try merging https://github.com/webdev03/ScratchAddons/pull/1 , that might fix it. Maybe someone made some changes that you haven't received yet.
