### ISSUE TITLE
Enhanced full screen doesn't resize canvas

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#3815]
### Description

The enhanced full screen addon doesn't change the resolution of the project canvas when resizing the window.

### Reproduction steps

1. Enable the "enhanced full screen" addon and disable "open full screen project player in full screen browser mode".
2. Open a project in a small browser window.
3. Enter full screen mode.
4. Increase the size of the window.

### Expected behaviour

The resolution of the project canvas would be increased to match the new window size.

### Actual behaviour

The size of the canvas is increased, but the resolution is not, which makes the project blurry.

### Environment

- Browser: Edge 96 (beta)
- Scratch Addons version: latest development version
- Operating system: Windows

**Comment by apple502j** [comment]
Reopened, see #5567

**Comment by WorldLanguages** [comment]
PR was reverted because it caused regression: #5567
