### ISSUE TITLE
Add a hide all block and a stop specific sounds block

### ISSUE THREAD

**Issue by hello01-debug** [ScratchAddons/ScratchAddons#3824]
I'd like to see a hide all block added to Scratch 3.0. This would be useful in Game Over scenarios or transitions in games, rather than having to individually hide all of them. Another great block to have would be a [Stop [sound] Sound], which would stop a specific sound. I understand if the second one is not possible, but I would really like to have one or the other or both in Scratch.

**Comment by TheColaber** [comment]
Scratch addons can't add new blocks that add change core functionallity in a project. Otherwise, people without the addon won't be able to play the game :(
