### ISSUE TITLE
Resizable block palette

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#3827]
### Is your request related to a problem? Please describe.

Sometimes I want the block palette to take up less space, but the `Category click` setting in `hide-flyout` doesn't actually give me any more coding space. Also, sometimes I want to make it wider, for example when I'm using a large monitor and `variable-manager` is enabled so everything lines up.

### Describe the solution you'd like

A new add-on that allows horizontally resizing the block palette.

### Describe alternatives you've considered

- For lining up the tabs with the block palette when `variable manager` is enabled:
  - Making the block palette wider, or
  - Making the tabs less wide

- Fix #2766 (This add-on could still be useful even if that gets fixed though.)

### Additional context

N/A

**Comment by RedGuy12** [comment]
Related to/Duplicate of #2217

**Comment by Samq64** [comment]
Why have I never noticed that issue before?
