### ISSUE TITLE
1.23.0 ""prerenease""

### ISSUE THREAD

**Issue by kccuber-scratch** [ScratchAddons/ScratchAddons#3834]
### Description

Shows up as 1.23.0-prerenease in manifest
### Repoduction steps

1. download latest code
2. load it into browser
3. see that it says prerenease 

### Expected behaviour
it should say prerelease

### Actual behaviour
it says prerenease

### Screenshots
![image](https://user-images.githubusercontent.com/92891642/142747931-eab02d7b-e5b4-4688-be7f-0883c4e78e2f.png)

### Environment

- Browser:  FF 94
- Scratch Addons version:  1.23.0 ""prerenease""
- Operating system: 

### Additional context

n/a

**Comment by Mbrick2** [comment]
#3836

**Comment by mxmou** [comment]
Fixed by #3837?

**Comment by CST1229** [comment]
it's spelled prereñease not prerenease

**Comment by kccuber-scratch** [comment]
> Fixed by #3837?

Yep.

**Comment by WorldLanguages** [comment]
lol
