### ISSUE TITLE
`emoji-picker` Unicode emojis are outlined

### ISSUE THREAD

**Issue by Dhuls-Scratch** [ScratchAddons/ScratchAddons#3843]
### Description
title

### Repoduction steps

1. Go to a project, profile, or studio with comments on
2. Click the emoji-picker button (note the outlined icon)
3. Click see more

### Expected behaviour
The emojis have color

### Actual behaviour
title

### Screenshots
what happens
![Screenshot 2021-11-23 211103](https://user-images.githubusercontent.com/87714852/143165397-42b9a488-5355-457e-ab9c-4c92c15966f7.png)
what should happen
![Screenshot 2021-11-23 211440](https://user-images.githubusercontent.com/87714852/143167167-9ffea6cf-1dd1-44b7-9bcb-7db4e328e889.png)

### Environment

- Browser: Microsoft Edge 96.0.1054.29
- Scratch Addons version: 1.22.`
- Operating system: Windows 10 21H1

### Additional context
Google randomly decided to outline bold emojis

**Comment by TheColaber** [comment]
Related #3840... @mxmou maybe you can fix this addon in the pr too?
