### ISSUE TITLE
HD Upload button in Costumes row doesn't appear after returning to project editor

### ISSUE THREAD

**Issue by Jariel208** [ScratchAddons/ScratchAddons#3847]
### Description

When I click See Inside, the HD Upload button in the Costumes row is there, but when I click See Project Page and click See Inside, the HD Upload button in the Costumes row didn't appear. Plz fix this thx

### Screenshots

![Screenshot 2021-11-25 201047](https://user-images.githubusercontent.com/77120448/143509495-32b8db55-bb00-4619-b7b7-b918331d5848.jpg)
why

### Environment

- Browser: Google Chrome 96
- Scratch Addons version: 1.22.1
- Operating system: Windows 10

**Comment by mxmou** [comment]
I think this was fixed in #4103.
