### ISSUE TITLE
Highlight project creator username

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#3854]
### Is your request related to a problem? Please describe.

Scratch doesn't make a distinction between comments posted by the creator of a project and comments by other users.

### Describe the solution you'd like

An addon that adds an indicator to the creator's username - either a background color:
![image](https://user-images.githubusercontent.com/51849865/143686482-53316263-5b5a-459d-9d2f-5430993e675f.png)
or a label:
![image](https://user-images.githubusercontent.com/51849865/143686727-f97f9acf-ba20-475a-80eb-f8fedfe03ea6.png)

Something similar could be done on profiles, studios (with labels like "Host", "Manager", and "Curator"), and in the forums (for the original poster).

**Comment by WorldLanguages** [comment]
Screenshot from #5932:

![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/99813281-3af9-4af5-9c00-317f9c1e0758)
