### ISSUE TITLE
`columns` doesn't work with auto hidng block palette

### ISSUE THREAD

**Issue by Dhuls-Scratch** [ScratchAddons/ScratchAddons#3859]
### Description

> There is a bug when you have the following two addons enabled: Two-column category menu, Auto-hiding block palette, The palette will hide diagonally and still be visible
[src](https://scratch.mit.edu/users/World_Languages/#comments-173323936)

### Repoduction steps

1. enable both addons
2. move mouse away from block palette so it hides

### Expected behaviour

the column selector and the pallet hide

### Actual behaviour

only the pallets hides

### Screenshots

![wth](https://user-images.githubusercontent.com/87714852/143790451-d8a529fb-90a8-4ce2-bb60-fd80625a522e.png)

### Environment

 
- Browser: Firefox 94.0.2
- Scratch Addons version: 1.22.1
- Operating system: Windows 10 21H1 64-bit

**Comment by kccuber-scratch** [comment]
Duplicate of #3821

**Comment by Dhuls-Scratch** [comment]
oops
