### ISSUE TITLE
Enhance clean up blocks+

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#3887]
### Is your request related to a problem? Please describe.

Clean up blocks+ is already much better than Scratch's clean up blocks, but it would be useful to have it do more without spamming the user with a bunch of alerts or accidentally removing stuff that the user wants to keep.

### Describe the solution you'd like

Keeping the context menu option for rearranging scripts into a grid, but moving the other options (removing orphaned reporters and unused variables/lists) to a modal that could be accessed from the edit menu (or an SA menu if that ever gets added). There could also be a button next to the unused variable option that lists all the unused variables/lists with check boxes next to them so the user can uncheck the ones they want to keep. This would also make it easier for it to remove other things like assets or custom block definitions that are not used in the code while still letting the user keep the ones they don't want to delete.

### Describe alternatives you've considered

Keeping it the way it is right now and just adding more alerts if any other options get added.

### Additional context

This should be done after clean up blocks+ is moved to its own add-on.

**Comment by WorldLanguages** [comment]
I've created issue #6671 for general discussion about the `Clean up Blocks +` feature.

**Comment by Samq64** [comment]
Closing in favor of #6671.
