### ISSUE TITLE
Cloud games doesn't handle games with >40 players very well

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#3890]
### Description

When opening the cloud games pop-up it attempts to load Griffpatch's Massive Multiplayer Platformer with 150+ players, but gets stuck at 40 and continues to display the loading message until the pop-up is closed.

### Reproduction steps

1. Check to see if a lot of people are playing one of griffpatch's games (>40)
2. Open the cloud games pop-up

### Expected behaviour

Cloud games should either attempt to load all the players playing a game and display an error message if it fails or load up to a certain number of players, display a plus symbol next to the number of players for that game and dismiss the loading message if it was the last game. If the second option is chosen, it would also be nice for it to load up to 50 players instead of 40.

### Actual behaviour

Cloud games gets stuck loading a game with >40 players and shows the number of players as 40 regardless of how many players there are. The loading message never disappears.

### Screenshots

![image](https://user-images.githubusercontent.com/81489795/144867263-114ae40e-1e26-4937-bca7-339888d2759a.png)

### Environment

- Browser: Firefox 94
- Scratch Addons version: 1.22.1
- Operating system: Windows 11

### Additional context

N/A

**Comment by apple502j** [comment]
Issue is in the cloud server

**Comment by RedGuy12** [comment]
Isn't it because we only fetch the first page of cloud log?

**Comment by apple502j** [comment]
It does, but it should not cause the loading screen to be stuck. 40 is enough.
