### ISSUE TITLE
Add Option to sort comment messages for messages tab

### ISSUE THREAD

**Issue by BarthdryZ** [ScratchAddons/ScratchAddons#3894]
Please add a option to enable and disable known as potential scams
The Option or many options should be able to be able to not show some annoying messages like F4F or Random One Letter thing left in our profile.
I request it to have 2 options one is to block f4f and random one letter. Another one which is customisable means we can just hide things showing a particular word contained within the message.

**Comment by WorldLanguages** [comment]
An addon that hides comments is probably rejected.
