### ISSUE TITLE
Move full screen colour to `fullscreen`

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#3899]
### Is your request related to a problem? Please describe.

Now that both the editor and website colours are completely customizable it might not be obvious right away which dark mode changes the colour of the full screen background since it's accessed from both the project page and the editor.

### Describe the solution you'd like

Moving the full screen background and header colours to `fullscreen`.

### Describe alternatives you've considered

Adding a notice to `dark-www` telling the user that the full screen colour can be customized with `editor-dark-mode`.

### Additional context

This change would make even more sense if #3014 gets implemented.

**Comment by WorldLanguages** [comment]
I'm not sure if fullscreen is suitable for this

**Comment by lisa-wolfgang** [comment]
It would make more sense to make a new theme addon (for the project page only) and relocate this option there.
