### ISSUE TITLE
Make editor addons work on TurboWarp

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#390]
This has been suggested twice today.
We do not have host permissions to TurboWarp, however, we can make use of optional permissions.
@GarboMuffin, do you have anything to say? To be honest, I was going to ask if it was somehow possibly to make an addon that simply replaced the editor with TurboWarp (not just the player - that's easy with an iframe - I mean moving the whole editor experience), but it feels basically impossible and complicated.

**Comment by GarboMuffin** [comment]
Replacing the project player is probably not feasible, especially given the ever increasing scope of the project.

As long as you don't claim to be officially endorsed by the TurboWarp project, I don't mind addons running on turbowarp.org.

**Comment by areeq0325** [comment]
The issue title is misspelled

**Comment by YOYITsM3M8** [comment]
I have an idea.

add another section in 
![image](https://user-images.githubusercontent.com/49005044/99555825-bb55f680-298e-11eb-8475-fb8feaea36bc.png)
that says "Allow addons to run on TurboWarp" which will ask for permission to access turbowarp.org. thhen boom

**Comment by WorldLanguages** [comment]
@YOYITsM3M8 Yeah that's what I had in mind

**Comment by TheColaber** [comment]
Would it actually be possible to run addons on turbowarp with optional permissions?

As far as I know, scripts can only run on certain websites, if the websites are declared in the content scripts section of the manifest file.

So wouldn't we need to have one of the matches be turbowarp here?
https://github.com/ScratchAddons/ScratchAddons/blob/25f3d3863739056b2eb3ee4b7b5a67fddb64a3ad/manifest.json#L21-L32

**Comment by WorldLanguages** [comment]
@TheColaber Yeah, it's not that complex. However please let me PR this myself

**Comment by TheColaber** [comment]
> @TheColaber Yeah, it's not that complex. However please let me PR this myself

I wasn't going to make this, I was asking if it was possiable.

**Comment by WorldLanguages** [comment]
Moving to backlog for the possibility of TurboWarp including most (if not all) editor addons natively.

**Comment by RedGuy12** [comment]
What is backlog?

Paul Reid

________________________________

**Comment by WorldLanguages** [comment]
Closing this. TurboWarp should include our addons, not the other way around. This way, people don't need an extension to use our editor addons, shortening the discovery gap :)

**Comment by WorldLanguages** [comment]
Turbowarp now has addons
