### ISSUE TITLE
Everything disappeared after browser crash

### ISSUE THREAD

**Issue by NewBoi123** [ScratchAddons/ScratchAddons#3915]
my browser just crashed because of an ad and when i opened scratch, all of the addons stopped working, i checked scratch addons everything is gone, the messages, the games, the addons are literally gone, i tried removing and adding it back but it didn't work :(
![brocken extension](https://user-images.githubusercontent.com/96000912/145706917-80abd280-8e98-486f-9466-5cffaa3533a4.png)

**Comment by LegoManiac04** [comment]
Have you tried restarting your browser? I know stuff can break after a crash, so restarting your browser (or possibly your computer) will likely fix the issue.

**Comment by Samq64** [comment]
Are you using the Chrome Store version or a pre-release version from GitHub?

**Comment by kccuber-scratch** [comment]
This actually happened to me, i just waited like 2-3 weeks and it magically fixed itself, and I think this has been reported before.

**Comment by RedGuy12** [comment]
Closing as stale.
