### ISSUE TITLE
Scratch messaging only shows the project title on unshared projects

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#3916]
### Description

If someone comments on a project and then I unshare it, Scratch messaging just shows the project title without the comment.

### Reproduction steps

1.  Comment on a project made by your alt. (if you have a second account and a project you don't mind unsharing)
2. Log into your alt and unshare the project.
3. Open Scratch messaging.

### Expected behaviour

The comment should either appear in the Scratch messaging tab or not appear at all.

### Actual behaviour

Only the project title appears.

### Screenshots

![image](https://user-images.githubusercontent.com/81489795/145713482-a2f344b9-8343-4c30-98d7-a92d1178415c.png)

### Environment

- Browser: Firefox 95
- Scratch Addons version: 1,22,1
- Operating system: Windows 11

**Comment by apple502j** [comment]
Wontfix - vanilla project page also hides comments in this case.

**Comment by Samq64** [comment]
![image](https://user-images.githubusercontent.com/81489795/145716424-c79b5036-5d19-4ac3-bdba-1f3d4f733c1d.png)

**Comment by mxmou** [comment]
> Wontfix - vanilla project page also hides comments in this case.

I think the addon should try to match the messages page and not the project page if the comment fails to load.

**Comment by apple502j** [comment]
Re-opening, but low priority IMO

**Comment by RedGuy12** [comment]
The project page shows comments on your own unshared projects


________________________________

**Comment by Dhuls-Scratch** [comment]
"peoject"
also
![Screenshot 2021-12-13 183103](https://user-images.githubusercontent.com/87714852/145911139-a36415b1-fb89-4b23-bcb2-5441ab24c02f.png)
note that project was unshared

**Comment by Samq64** [comment]
This only happens with my own projects. Replies to comments on someone else's project that gets unshared don't show up in Scratch messaging at all.
