### ISSUE TITLE
Remix tree button

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#392]
Better3.0 has it, and it's been suggested through feedback.

**Comment by mxmou** [comment]
Like [this](https://mxmou.github.io/customize-scratch/#bring-back-the-remix-tree) or as a special button?

**Comment by WorldLanguages** [comment]
Oh nice @mxmou, sadly for some reason it didn't work - the element is before the view icon but is not visible. I also found that if you go to https://scratch.mit.edu/projects/104 (notice how the URL has no ending slash) and you "click" the button (I had to click it with JavaScript), it goes to https://scratch.mit.edu/projects/104remixtree because it assumes a slash at the end.

**Comment by mxmou** [comment]
Implemented in #531.
