### ISSUE TITLE
sb3/sb2/sb downloader for projects

### ISSUE THREAD

**Issue by SamuelTheTechnoKid** [ScratchAddons/ScratchAddons#3921]
So, I know you can downlaod Scratch projects with a sb3 downloader and even Scratch itself. But, can you make an easy button to do it instantly? And also making it support sb2 and sb files?

**Comment by CST1229** [comment]
You can use the [forkphorus .sb downloader](https://forkphorus.github.io/sb-downloader/) for downloading `sb2`s and `sb`s.

**Comment by RedGuy12** [comment]
Dyplucate of #762 

Not all blocks are supported in older versions of Scratch

**Comment by SamuelTheTechnoKid** [comment]
> Dyplucate of #762
> 
> Not all blocks are supported in older versions of Scratch

It's not a converter what I want. A sb3 downloader! Also, I know that. I mean, if the project was made in Scratch 2, download the .sb2 file.

**Comment by RedGuy12** [comment]
The sb2 file doesn't exist anymore


________________________________

**Comment by CST1229** [comment]
> The sb2 file doesn't exist anymore

It does if the project was never saved in Scratch 3.0.
