### ISSUE TITLE
Scratch Messaging has crashed

### ISSUE THREAD

**Issue by BarthdryZ** [ScratchAddons/ScratchAddons#3926]
Today the messaging extension is not working. I think Scratch Addons is messing up with the website with lots of pings or whatever or the reason could be griffpatch game.

Oops! Something went wrong We are so sorry, but it looks like Scratch has crashed. This bug has been automatically reported to the Scratch Team. Your error was logged with id 843cbcff6c084fd9b1be3a137b1aaa83

I think there should be a more effecient way to request to the server without overloading it.

**Comment by apple502j** [comment]
Crash is due to Scratch server instability
