### ISSUE TITLE
"Highlight currently executing blocks" blue box staying after project stopped

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#393]
> The 'Highlight currently executing blocks' function is a bit annoying when you stop the program as the blue box stays in place. It would be better if it disappeared when you stop the program. Even if this wasn't done automatically because some people will want it there, it would be good if there was an option in settings to make this happen.

**Comment by TheColaber** [comment]
This is no longer an issue in my experience.
