### ISSUE TITLE
Better addon linking

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#3934]
### Is your request related to a problem? Please describe.

The current addon linking system could be improved.

### Describe the solution you'd like

- Adding a button next to addons that opens them as a direct link. This would make addon linking more discoverable.
- Automatically Refreshing the page when the hash changes
- Switching to the `all` category and expanding collapsed categories
- Expanding the addon, even if it's not enabled or collapsed by default
- Hiding all other addons?
- Sort of related: Allow linking to different categories or the more settings page if that doesn't already exist.

### Describe alternatives you've considered

Using the current addon linking system which works pretty well apart from needing to reload the page.

### Additional context

This would make implementing  #3933 easier.

**Comment by RedGuy12** [comment]
changing the hash doesn't reload the page, but this doesn't work if the addon group with the addon is collapsed or if it's in a different category

_Originally posted by @RedGuy12 in https://github.com/ScratchAddons/ScratchAddons/issues/3933#issuecomment-995889459_

**Comment by RedGuy12** [comment]
also you cant link easter eggs
