### ISSUE TITLE
`dark-www`: wrong scroll bar colour on Firefox

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#3939]
### Description

Originally reported in #3938:

> On some pages, the scrollbar is a dark blue.

### Reproduction steps

1. On Firefox, enable `dark-www`
2. Set the coloured areas setting to something other than default
2. Open any `scratch-www` page except for the project page
3. Notice how the page's scroll bar is dark blue

### Expected behaviour

Ideally the scroll bar should follow the dark scrollbars setting, otherwise it should always stay light.

### Actual behaviour

The scroll bar on `scratch-www` pages is dark blue.

### Screenshots

![image](https://user-images.githubusercontent.com/79656307/146585558-b8b62a2c-f8b4-4812-85cc-0878df799a69.png)

### Environment

- Browser: Firefox 95
- Scratch Addons version: 1.23.0
- Operating system:  Windows 11

### Additional Context

This bug doesn't seem affect any other scroll bars as far as I can tell. The bug is probably caused by `desaturated_banners.css`

**Comment by CST1229** [comment]
This is because Firefox sets the scrollbar color based on the background color, and we can't change it unlike Chrome.
And the reason scratchr2 pages work is because they use a custom scrollbar.

**Comment by mxmou** [comment]
Scratch sets the background color of the `<body>` element to a light blue. That isn't normally visible, with a few exceptions:
* on Edge, it's used as the background color when trying to scroll past the end of the page;
* on Firefox, it's used to determine the color of the scrollbar.

The website dark mode addon now changes it do a dark blue when the colored areas setting is set to darker. It could be changed to dark gray to make the scrollbars on Firefox look better, but that would also change the overscroll background on Edge.

**Comment by mxmou** [comment]
> Actually, the page scrollbar is still not blue there for some reason, even though it's a browser scrollbar...

It's because the `<body>` is white there, so dark mode makes it dark gray.

**Comment by CST1229** [comment]
> The website dark mode addon now changes it do a dark blue when the colored areas setting is set to darker. It could be changed to dark gray to make the scrollbars on Firefox look better, but that would also change the overscroll background on Edge.

Browser detection for `if` would solve it. Change it on Firefox but not on other platforms.
Also could hide the dark scrollbars option.

**Comment by Samq64** [comment]
> on Edge, it's used as the background color when trying to scroll past the end of the page

I can't scroll past the end of any page at all on Edge 96.

**Comment by mxmou** [comment]
> > on Edge, it's used as the background color when trying to scroll past the end of the page
> 
> I can't scroll past the end of any page at all on Edge 96.

It's only possible with a touchpad or a touch screen.

**Comment by Samq64** [comment]
> > > on Edge, it's used as the background color when trying to scroll past the end of the page
> > 
> > 
> > I can't scroll past the end of any page at all on Edge 96.
> 
> It's only possible with a touchpad or a touch screen.

Then replacing it with the page background setting colour without checking for browsers is probably good enough.

**Comment by mxmou** [comment]
> > > > on Edge, it's used as the background color when trying to scroll past the end of the page
> > > 
> > > 
> > > I can't scroll past the end of any page at all on Edge 96.
> > 
> > 
> > It's only possible with a touchpad or a touch screen.
> 
> Then replacing it with the page background setting colour without checking for browsers is probably good enough.

Probably, especially if the background of the `<html>` element isn't changed.
