### ISSUE TITLE
User feedback: "data category tweaks" sort by cloud variables

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#394]
> I recommend to add cloud variables sorting like you did for this sprite and for all sprites.

**Comment by lisa-wolfgang** [comment]
This feature would seem redundant since cloud variables are already grouped at the top of the "for all sprites" category. It would essentially be adding a label to that section, which is already obvious because every cloud variable has a cloud in its name.

**Comment by WorldLanguages** [comment]
Huh, didn't think about that. They all start with a cloud.

**Comment by mxmou** [comment]
The data category tweaks addon was removed.
