### ISSUE TITLE
Customizable quotes and code blocks addon is not compatible with other themes

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#3946]
`forum-quote-code-beautifier` doesn't color properly anymore when `scratchr2` is also enabled (the border is always gray and the background is the same gray), which might be because of their order in `addons.json`.

_Originally posted by @CST1229 in https://github.com/ScratchAddons/ScratchAddons/issues/3938#issuecomment-996921777_

**Comment by kccuber-scratch** [comment]
Now it does zebra striping on code blocks too for some reason. Go to [this topic ](https://scratch.mit.edu/discuss/topic/566802)and you'll see what I'm talking about
