### ISSUE TITLE
Hide forum signatures addon

### ISSUE THREAD

**Issue by towerofnix** [ScratchAddons/ScratchAddons#3951]
This is kind of a no-brainer so I'm surprised it apparently hasn't been suggested yet :P

Simple addon which hides user signatures on forum posts when it's enabled. The "Full areas" addon expands signatures when active; there should be an opposite addon for those who don't care for signatures, want a break from banners and the like, or have any other reasons for hiding signatures!

Another option is to replace signatures with a (quite subtle) "expand signature" button that un-hides the sig when clicked (collapsing by default). This would make it so users don't have to disable the addon if they just want to have a quick look at one person's signature, for example.

**Comment by joecooldoo** [comment]
I like this idea.
