### ISSUE TITLE
Merge `block-duplicate` and `block-cherry-picking`

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#3957]
### Is your request related to a problem? Please describe.

`block-duplicate` and `block-cherry-picking` do very similar things and in the description for `block-duplicate` it says "Hold Ctrl as well to only duplicate a single block instead of the entire stack attached below it." making `block-cherry-picking` redundant.

### Describe the solution you'd like

Merge the two addons together making both options toggles.

### Describe alternatives you've considered

Only making ctrl+alt duplictae a single block when both addons are enabled.

### Additional context

N/A

**Comment by WorldLanguages** [comment]
I think we decided to intentionally separate them
