### ISSUE TITLE
Some editor text is unreadable

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#3963]
### Description

Some of the text in the editor is white on a white background making it hard to read.

### Reproduction steps

1. Enable `dark-www`
2. Disable `editor-dark-mode`
1. Open the editor

### Expected behaviour

All text on a white background should be dark grey.

### Actual behaviour

Some text on a white or light grey background is white.

### Screenshots

![image](https://user-images.githubusercontent.com/81489795/146798794-6aa7d2e7-4367-4e37-8f98-2de6a2eba9d2.png)

![image](https://user-images.githubusercontent.com/81489795/146798856-5dfdcf9d-9174-429b-badd-6114313a81f8.png)

![image](https://user-images.githubusercontent.com/81489795/146798912-11498f59-27dd-4cce-a0fe-1f6216144145.png)

![image](https://user-images.githubusercontent.com/81489795/146798989-0da15375-3475-46c5-a9ba-09cf148e7de3.png)

### Environment

- Browser: Firefox 95
- Scratch Addons version: 1.23.1
- Operating system:  Windows 11

### Additional Context

Enabling `editor-dark-mode` and using Scratch's default colours fixes some of the unreadable text, but not all of it.

**Comment by WorldLanguages** [comment]
Note: website dark mode needs to be enabled, and editor dark mode needs to be disabled.

@mxmou We did a whoopsie, probably on #3942. This bug happened once in the past.
I'm delaying v1.23.1 release in Chrome until we fix this and we can release v1.23.2

**Comment by Mbrick2** [comment]
@WorldLanguages only on chrome??

**Comment by WorldLanguages** [comment]
@Mbrick2 Firefox has already been released unfortunately.
