### ISSUE TITLE
discuss/forums tab

### ISSUE THREAD

**Issue by scoobydoofacethingdie** [ScratchAddons/ScratchAddons#3973]
### Is your request related to a problem? Please describe.
people like me can forget the link for the forums or forget to go to the bottom of the page
### A clear and concise description of what you want to happen.
add a tab button saying Forums that leads to the discuss page
### Additional context
![image](https://user-images.githubusercontent.com/85052868/146916196-2c2796ad-d332-4c32-bc58-25ef520558c8.PNG)

**Comment by CST1229** [comment]
This is already implemented.
See the "Discuss button" addon.
