### ISSUE TITLE
BUG - Arguments when creating a new custom block

### ISSUE THREAD

**Issue by Medericoder** [ScratchAddons/ScratchAddons#3976]
By using "TAB" key.

![image](https://user-images.githubusercontent.com/80577386/146977324-2a686814-dc05-40f2-ab50-c0df68afcecf.png)

**Comment by CST1229** [comment]
I think this is a Scratch bug

**Comment by TheColaber** [comment]
I think this is a scratch bug. This is unrelated to Scratch Addons.
