### ISSUE TITLE
The Scratch messaging keeps lagging while showing 

### ISSUE THREAD

**Issue by hasnain123333** [ScratchAddons/ScratchAddons#3994]
this not only my problem but my friends too who uses this addons some even removed this addons please solve it

**Comment by RedGuy12** [comment]
talked to him in the discord. he's using conflicting extensions

**Comment by hasnain123333** [comment]
> talked to him in the discord. he's using conflicting extensions

I removed them and still it does'nt work

**Comment by hello-smile6** [comment]
@hasnain123333 Try installing the latest release of Scratch Addons from GitHub.

**Comment by RedGuy12** [comment]
> > talked to him in the discord. he's using conflicting extensions
> 
> I removed them and still it does'nt work

What's scratchhelper
