### ISSUE TITLE
Stacked Blocks not showing up correctly

### ISSUE THREAD

**Issue by catb0x** [ScratchAddons/ScratchAddons#4009]
dont really have much to say
im on windows 11 + brave browser
![bug](https://user-images.githubusercontent.com/77354428/147831225-ea01e27a-4bfb-454d-868b-5b9e12937f84.png)
also it has nothing to do with the addons itself

**Comment by catb0x** [comment]
this might just be a rendering error but whats werid is that it only happens when i have the extention on
![Screenshot 2021-12-31 165526](https://user-images.githubusercontent.com/77354428/147831417-db9630de-7026-45e1-af05-e0ce6fc91407.png)

**Comment by hello-smile6** [comment]
> this might just be a rendering error but whats werid is that it only happens when i have the extention on ![Screenshot 2021-12-31 165526](https://user-images.githubusercontent.com/77354428/147831417-db9630de-7026-45e1-af05-e0ce6fc91407.png)

Is custom block sizing enabled?

**Comment by kccuber-scratch** [comment]
try with a different browser like firefox

**Comment by WorldLanguages** [comment]
It might be a hardware issue or a driver issue? No idea. It's weird that the settings page would look differently to you.

**Comment by catb0x** [comment]
it was a driver issue

**Comment by catb0x** [comment]
lol
