### ISSUE TITLE
`Website dark mode and customizable colors` does not work on mobile forums home page

### ISSUE THREAD

**Issue by hello-smile6** [ScratchAddons/ScratchAddons#4012]
### Description

When https://scratch.mit.edu/discuss/m/ is opened, you'll notice that the <a href="https://github.com/ScratchAddons/ScratchAddons/tree/abb61cb98bf0a708b8d90e02502a6f95ee5ae2eb/addons/dark-www">addon</a> doesn't do very well with the webpage. Could there maybe another stylesheet for it?

### Repoduction steps

1. Navigate to `extension-root://webpages/settings/index.html#addon-dark-www` and enable the addon with the default configuration.
2. Navigate to `https://scratch.mit.edu/discuss/m/`.
3. Observe the bad color scheme.

### Expected behaviour

The webpage would have dark mode.

### Actual behaviour

The webpage was extremely hard to read and interact with, due to the color scheme.

### Screenshots

![https://scratch.mit.edu/discuss/m](https://user-images.githubusercontent.com/73048226/147840236-56f5b34c-1e1a-4d94-95c5-87215d56f47f.png)

### Environment

- Browser: Chromium 99.0.4800.0 64-bit (installed from <a href="https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F954755%2Fmini_installer.exe?generation=1640986421390604&alt=media">chromium-browser-snapshots snapshot # 954755 64-bit win32 mini_installer.exe</a>)
- Scratch Addons version: abb61cb98bf0a708b8d90e02502a6f95ee5ae2eb
- Operating system: 
  ```
  Device name	localhost
  Full device name	localhost
  Processor	Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz   2.29 GHz  (2 processors)
  Installed RAM	10.0 GB
  Device ID	00000000-0000-0000-0000-000000000000
  Product ID	00000-00000-00000-00000
  System type	64-bit operating system, x64-based processor
  Pen and touch	No pen or touch input is available for this display
  Edition	Windows 10 Home
  Version	20H2
  Installed on	‎12/31/2021
  OS build	19042.985
  Experience	Windows Feature Experience Pack 120.2212.2020.0
   ```
  

### Additional context

<details>
<summary><code>chrome://version</code>:</summary>
<pre>
Chromium	99.0.4800.0 (Developer Build) (64-bit) 
Revision	6819323d794f3fe1eacf5a2247ac6f0af2b5592b-refs/heads/main@{#954755}
OS	Windows 10 Version 20H2 (Build 19042.985)
JavaScript	V8 9.9.47
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4800.0 Safari/537.36
Command Line	"C:\Users\hello-smile6\AppData\Local\Chromium\Application\chrome.exe" --from-installer --flag-switches-begin --flag-switches-end --file-url-path-alias="/gen=C:\Users\hello-smile6\AppData\Local\Chromium\Application\gen"
Executable Path	C:\Users\hello-smile6\AppData\Local\Chromium\Application\chrome.exe
Profile Path	C:\Users\hello-smile6\AppData\Local\Chromium\User Data\Default
Variations	8494cb17-3f4a17df
f475deb0-f475deb0
313957be-3ef44cd2
c264dd48-82956dd5
3e7d7783-f38a9353
7e184ca7-2ec1a7e
90a7075b-725c8fbe
a112f012-3f4a17df
16b16054-16b16054
59b6f412-ca15d1c3
60d4b352-ca15d1c3
ecc96f50-e31bd7b5
6cb5e962-3f4a17df
d6284ba0-3be74c4d
a77166f2-a77166f2
6e08fc3e-3f4a17df
481fc7e7-1ff68d1e
3e09e9b1-3f4a17df
60c843ad-3f4a17df
3fa8d059-3fa8d059
89a16501-3f4a17df
87f33ad6-3f4a17df
5d093a14-3f4a17df
74f8fa8f-74f8fa8f
4d936449-fd549ada
8950ab95-3f4a17df
7638c831-857014ec
1bb6a450-3f4a17df
6cbcf5b7-3f4a17df
6c5f69af-3f4a17df
5306c29b-9cbf73ff
4701a278-3f4a17df
4749874c-a300a3e6
7c2504d0-3d47f4f4
f2cb61f-3f4a17df
cb38fdd2-3f4a17df
47d92407-5b5edf5b
4b9a5bc0-efbbc50a
8470b833-3f4a17df
3f6e921e-3f6e921e
af17a5e6-3f4a17df
bf4029fe-1776d9e
4e3ec83a-e4938e2c
65570806-377be55a
f8a7f5e4-d6a08b38
6aa15a86-9d8c1aae
da2d8531-3f4a17df
e87da360-3f4a17df
8e3b682d-3f4a17df
6a5f15b-3f4a17df
6be2e990-3f4a17df
1d606bb5-8d14c5d8
d89faab1-3f4a17df
722b8030-3f4a17df
3042ad4b-ad2fa222
3fd33f16-fa281276
2ba47366-3f4a17df
248c3fbd-3f4a17df
833d778c-3f4a17df
5252c71-3f4a17df
61c68934-3f4a17df
e4b8f636-3f4a17df
5e3a236d-59e286d0
e79de56c-dee0823
357a64de-dee0823
8bccc03b-3f4a17df
29c62d4-3f4a17df
178e8b37-3f4a17df
facdb7bf-3f4a17df
69d4ebd5-3f4a17df
9e5c75f1-30e1b12b
d8692482-fe3984ae
b012722b-3f4a17df
727723f1-40193c20
8c8d8faf-3f4a17df
255dfea8-cf12f279
a083757a-d6a08b38
39ec51c3-572726d7
f7a3ec9-bd336006
ca5a2953-ff983c32
3487aa71-84708353
8bfdd36f-3f4a17df
234de0a0-ace4e138
23a898eb-fc93cf74
d3566fbd-c6f74b94
4ea303a6-3f4a17df
7048821f-7b0f7072
fc7e4d22-3f4a17df
a0cbf015-5ab9a6be
77e44b8e-3f4a17df
83890985-5cbb6de6
cac0a91c-3f4a17df
18e58339-3f4a17df
61a655b5-3f4a17df
ef4764d7-c9f4d4ef
fbe267b5-7f60b823
7760b5b2-3f4a17df
48d2009f-3f4a17df
49a20295-49a20295
1354da85-f1a864dc
54410569-3f4a17df
ad4acdda-3f4a17df
931c5f72-3f4a17df
ade3efeb-e1cc0f14
f48c01d3-6eb2bd2b
6aa685f2-dcaf2061
b1ceb06f-3f4a17df
32d6b1fe-3f4a17df
7975f5b5-3f4a17df
248e3a0-3f4a17df
3b96a1d-3f4a17df
dba92675-f23d1dea
bef5c006-3f4a17df
17b84626-3f4a17df
8d7344de-3f4a17df
733cb831-49b2945c
b53f3ef9-3f4a17df
2856aa31-3f4a17df
5b436ba6-3f4a17df
4a475c10-3f4a17df
</pre>
</details>

**Comment by mxmou** [comment]
I get a 503 error when I try to access that page.

**Comment by TheColaber** [comment]
> I get a 503 error when I try to access that page.

Weird, I can access it.

**Comment by RedGuy12** [comment]
I get 503

**Comment by Samq64** [comment]
It works for me.

**Comment by Chiroyce1** [comment]
> I get a 503 error when I try to access that page.
You need to visit a post/topic - https://scratch.mit.edu/discuss/m/topic/382164/

**Comment by Samq64** [comment]
The mobile forums have been removed.
