### ISSUE TITLE
Option to change default sprite to something else, like the turbowarp dango

### ISSUE THREAD

**Issue by HiImBlahh** [ScratchAddons/ScratchAddons#4014]
### Is your request related to a problem? Please describe.

no
### Describe the solution you'd like
a button to change the default scratch cat to something else. you would upload an image, or select one of the premade options like a dango. or it will allow you to not have a sprite entirely, and just start with a completely empty project

### Describe alternatives you've considered

none

**Comment by RedGuy12** [comment]
already exists

**Comment by HiImBlahh** [comment]
> already exists

where? i looked for it, but i couldn't find it

**Comment by Samq64** [comment]
The default project addon.
