### ISSUE TITLE
Shortcut block

### ISSUE THREAD

**Issue by Supernatnat11** [ScratchAddons/ScratchAddons#4026]
### Is your request related to a problem? Please describe.

All scratch blocks can quickly become too big or too long so take up a lot of space in the editor. 

### Describe the solution you'd like

Add that when you right click on a block (loop, custom block ...) you can shrink it to better be able to store your editor.

**Comment by Supernatnat11** [comment]
Please don't tell me it's already proposed

**Comment by RedGuy12** [comment]
Duplicate of #1199
