### ISSUE TITLE
Spanish translation errors

### ISSUE THREAD

**Issue by RIMOPA** [ScratchAddons/ScratchAddons#4029]
In Scratch Addons there are some translation errors, here I will put the ones I found in the Spanish translation:

If you see or find more leave a comment with a screenshot!

![image](https://user-images.githubusercontent.com/97112832/148135887-367c14f4-9313-42f4-8cf0-10fb5f3530bf.png)
There should be written "son almacenadas"

![image](https://user-images.githubusercontent.com/97112832/148136821-15aeeacd-c496-4164-9737-bd5cbea5c668.png)
There should be written "de navegación"

![image](https://user-images.githubusercontent.com/97112832/148138478-5fc11a80-c481-4bee-b281-6ce513946ec3.png)
There should be written "completa"

![image](https://user-images.githubusercontent.com/97112832/148144075-d8820971-88be-4630-8f59-b9daf32cc260.png)
There should be written "menús"

Thanks for reading and sorry for my english!

### Fixeds:
![image](https://user-images.githubusercontent.com/97112832/148136048-7a7e9c44-889d-4e91-beff-10133a37c0a5.png)
There should be written "Contador de bloques"

**Comment by TheColaber** [comment]
@WorldLanguages helps translate Spanish, let's see what he thinks

**Comment by RedGuy12** [comment]
Helps? He claimed monopoly


________________________________

**Comment by WorldLanguages** [comment]
All fixed, except second one. "Editor menu bar" is translated as "barra de menú del editor" in more than one string.

**Comment by WorldLanguages** [comment]
@RIMOPA Santi querés meterte en transifex? En teoría no hace falta que haya alguien más que yo pero no tengo tiempo (o no me organizo bien) para poder traducir bien. [https://scratchaddons.com/translate](https://scratchaddons.com/translate)

**Comment by RIMOPA** [comment]
¡Hola! Sí, me encantaría!

**Comment by WorldLanguages** [comment]
@RIMOPA hacete una cuenta o si ya la tenes, pedi de nuevo traducir al español

**Comment by RIMOPA** [comment]
No me aparece el español como idioma disponible, ni Spanish

**Comment by WorldLanguages** [comment]
@RIMOPA te acabo de aceptar, seguimos en dms de twitter?

**Comment by RIMOPA** [comment]
Bueno!
