### ISSUE TITLE
@superscratch444tre made monopoly on Romanian translations, and now he's inactive and I can't fix them

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#4030]
@superscratch444tre made monopoly on Romanian translations, and now he's inactive and I can't fix them

**Comment by superscratch444tre** [comment]
I'm still active

**Comment by Secret-chest** [comment]
> I'm still active, but not so much

Ok, dar poți să schimbi din Extensii Scratch în Adaosuri Scratch?

**Comment by superscratch444tre** [comment]
Ok, voi face asta în weekend sau azi dupa ora 17.00.
