### ISSUE TITLE
editor-theme3 does not affect colors for argument/label buttons

### ISSUE THREAD

**Issue by RIMOPA** [ScratchAddons/ScratchAddons#4036]
### Description

![image](https://user-images.githubusercontent.com/97112832/150003617-d274f606-b2c5-41ba-a450-d6f69a9f748e.png)
The color does not display correctly, the color should be 5F49D8 for all the blocks, not only the edges of the central block, but the others blocks displays with FF6680, the default color.

### Repoduction steps

1. Change the color with the Addon that  does that.
2. Go to Scratch.
3. Click on "Make a block"

### Screenshots

![image](https://user-images.githubusercontent.com/97112832/150003600-de338ed7-0c2b-44f4-b3f0-bdb8b588ff94.png)

### Environment

- Browser: Chrome: 96.0.4664.110 (Build oficial) (64 bits) (cohort: Stable)
- Scratch Addons version: 1.23.2 
- Operating system: Windows

Thanks for reading and sorry for my English!

**Comment by Norbiros** [comment]
Hello!
I think it is not a bug. In this addon you can change color of input field.
![Screenshot from 2022-02-02 19-19-53](https://user-images.githubusercontent.com/89837724/152213946-82586dc1-9bd9-4854-ac3b-4b877f3d090c.png)
Using this addon, you can use it in other things as:
![Screenshot from 2022-02-02 19-22-15](https://user-images.githubusercontent.com/89837724/152214163-59dc979e-427f-4d52-ab21-ee87a30b327f.png)

This is functionality of this addon! You changed block's color but not input. 

See you soon,
Norbiros

**Comment by RIMOPA** [comment]
> Hello! I think it is not a bug. In this addon you can change color of input field. ![Screenshot from 2022-02-02 19-19-53](https://user-images.githubusercontent.com/89837724/152213946-82586dc1-9bd9-4854-ac3b-4b877f3d090c.png) 
Using this addon, you can use it in other things as: ![Screenshot from 2022-02-02 19-22-15](https://user-images.githubusercontent.com/89837724/152214163-59dc979e-427f-4d52-ab21-ee87a30b327f.png)
> 
> This is functionality of this addon! You changed block's color but not input.

Hello! I tried it and the input color when creating a block changes to the selected input color #0004ff(![image](https://user-images.githubusercontent.com/97112832/152461507-0fa314d1-85b0-4c7d-96a1-d1b6e53c937e.png)) when I'm typing or selecting the input, but in other cases it shows #ff3355(typing or selecting inputs in Make a Block default ![image](https://user-images.githubusercontent.com/97112832/152460605-fbbe77a2-a36a-48e3-abea-1af74cfef2b9.png)). But I mean the buttons of text, number or text and boolean are #ff6680(default Custom Blocks color ![image](https://user-images.githubusercontent.com/97112832/152460637-e01d2c8f-c123-466e-a742-8994f2735e2e.png)) and not #5f49d8(selected Custom Blocks color ![image](https://user-images.githubusercontent.com/97112832/152460729-1f2297a4-23c7-4bfc-ad5f-640ce56e4476.png))

![image](https://user-images.githubusercontent.com/97112832/152461471-ebc53aae-cb89-488b-9975-bf7bb0a91297.png)

**Comment by RIMOPA** [comment]
@Norbiros
> Hello! I think it is not a bug. In this addon you can change color of input field. ![Screenshot from 2022-02-02 19-19-53](https://user-images.githubusercontent.com/89837724/152213946-82586dc1-9bd9-4854-ac3b-4b877f3d090c.png) 
Using this addon, you can use it in other things as: ![Screenshot from 2022-02-02 19-22-15](https://user-images.githubusercontent.com/89837724/152214163-59dc979e-427f-4d52-ab21-ee87a30b327f.png)
> 
> This is functionality of this addon! You changed block's color but not input.

Hello! I tried it and the input color when creating a block changes to the selected input color #0004ff(![image](https://user-images.githubusercontent.com/97112832/152461507-0fa314d1-85b0-4c7d-96a1-d1b6e53c937e.png)) when I'm typing or selecting the input, but in other cases it shows #ff3355(typing or selecting inputs in Make a Block default ![image](https://user-images.githubusercontent.com/97112832/152460605-fbbe77a2-a36a-48e3-abea-1af74cfef2b9.png)). But I mean the buttons of text, number or text and boolean are #ff6680(default Custom Blocks color ![image](https://user-images.githubusercontent.com/97112832/152460637-e01d2c8f-c123-466e-a742-8994f2735e2e.png)) and not #5f49d8(selected Custom Blocks color ![image](https://user-images.githubusercontent.com/97112832/152460729-1f2297a4-23c7-4bfc-ad5f-640ce56e4476.png))

![image](https://user-images.githubusercontent.com/97112832/152461471-ebc53aae-cb89-488b-9975-bf7bb0a91297.png)
