### ISSUE TITLE
idea: Offsite link warner

### ISSUE THREAD

**Issue by webdev03** [ScratchAddons/ScratchAddons#4037]
### Is your request related to a problem? Please describe.

Sometimes you have rickrolls, sometimes you have misleading links, very rarely you have inappropriate links, sometimes you just don't want to click on something but you click it. You accidentally click on the link oh no!! 😢 

### Describe the solution you'd like

```js
const elementsA = document.getElementsByTagName("a");
for (let i in elementsA) {
  if(!elementsA[i]) continue;
  elementsA[i].addEventListener("click", (e) => {
    if(elementsA[i].href.startsWith("https://scratch.mit.edu/")) return;
    e.preventDefault();
    if(!confirm(`Are you sure you want to go to ${elementsA[i].href}?`)) return;
    window.location.href = elementsA[i].href;
  })
}

```
should explain it all in JS (the problem with the above is it gives `addEventListener is not a function` errors)
Just prompt the user if they go offsite, the script will need to be changed to support subdomains of `scratch.mit.edu` too.

### Describe alternatives you've considered

dealing with it

### Additional context

made the script above in developer console

**Comment by webdev03** [comment]
This might be included in "More links" but this should apply to forum posts too (you can set custom text and fool people on the forums, especially safari users but they cant use scratch addons)

**Comment by WorldLanguages** [comment]
I don't think it makes sense for an extension to add protective measures like this. You need to install an extension to enable them, which makes little sense.
Also, there's nothing Scratch specific about this code. Any extension that will warn you before going offsite with a website allowlist would work too.
