### ISSUE TITLE
"Profile" Button When Searching

### ISSUE THREAD

**Issue by Geotale** [ScratchAddons/ScratchAddons#404]
When you search something, a "Profile" button appears that, when clicked, allows you to go to the profile of the user you searched. This is convenient for profiles of words such as "someone" without needing to change the url.

**Comment by JeffaloBob** [comment]
i wonder if an actual user search would be possible if we convince lefty to make an endpoint to his database for it

**Comment by JeffaloBob** [comment]
i've talked to lefty about adding a user search to his api and its a maybe. if that gets added, then it would be possible to have a real search for users.
