### ISSUE TITLE
Does not display that 60fps mode is on

### ISSUE THREAD

**Issue by RIMOPA** [ScratchAddons/ScratchAddons#4044]
### Description

Does not display correctly that 60fps mode is on, shows it is off, when you change of page.

### Repoduction steps

1. Activate the 60fps mode addon.
1. Create a new project.
2. Do what this shows (names of the variables don't matter):
![image](https://user-images.githubusercontent.com/97112832/148699914-5202817d-0d9c-41f8-90b6-6f0179f7e96a.png)
3. Press Alt+Green flag
4. Press ![image](https://user-images.githubusercontent.com/97112832/148699957-92a95151-81bd-4afe-9ee7-db75e5d8142b.png)
5. Wait until time stops.
6. You can see it runs at 60fps but the green flag button is gray and not pink.

### Expected behaviour

It should show 60fps mode is on (pink green flag button) and run at 60fps in the project page.
![image](https://user-images.githubusercontent.com/97112832/148700591-10f77348-7445-468e-9216-aac4f5e9c132.png)

### Actual behaviour

The button of the green flag is gray and runs at 60fps in the project page.
![image](https://user-images.githubusercontent.com/97112832/148700607-8a9f7a48-d2ee-4da4-b3d3-42d1837fd656.png)

### Environment

- Browser: 97.0.4692.71 (Build oficial) (64 bits) (cohort: 97_Win_71)
- Scratch Addons version: 1.23.2
- Operating system: Windows

### Additional context

In 60fps XYZ mode it reach 300 in ~4.5 seconds, but in normal mode it reach 300 in ~9 seconds.

Thanks for reading and sorry for my English!

**Comment by Mbrick2** [comment]
Is their a project which has the code

**Comment by RIMOPA** [comment]
Yes

**Comment by RIMOPA** [comment]
> Is their a project which has the code

Yes

**Comment by Chiroyce1** [comment]
Demo project - https://scratch.mit.edu/projects/625868790/

https://user-images.githubusercontent.com/97374054/148714975-5bc35bd4-78d1-4052-bf6e-28251371e74f.mov

**Environment:**
- macOS 11.6.2 
- Firefox 94.0.1
- Scratch Addons v1.23.2
