### ISSUE TITLE
Sound when you change sound (Scratch Notifier)

### ISSUE THREAD

**Issue by RIMOPA** [ScratchAddons/ScratchAddons#4045]
### Is your request related to a problem? Please describe.

My problem is that it is difficult to know how each sound sounds, to be able to choose between the two sounds of the Scratch Notifier Addon.

### Describe the solution you'd like

When you change the selected sound or click it sounds like it is

Thanks for reading and sorry for my English!

**Comment by Secret-chest** [comment]
Good idea but how would we know what is the system sound? We need the notification API to show a notification.

**Comment by RedGuy12** [comment]
Well the sound will be removed soon so it's a mute point

**Comment by GrahamSH-LLK** [comment]
> Well the sound will be removed soon so it's a mute point

Hehe whether that was intentional or not, that's hilarious.
(moot to mute because it's about sounds going away)

**Comment by RIMOPA** [comment]
If the selection of sounds are going away, we can reproduce the sound or the test notification when you activate the addon

**Comment by RIMOPA** [comment]
> If the selection of sounds are going away, we can reproduce the sound or the test notification when you activate the addon

I understood that for now they don't are going away

**Comment by WorldLanguages** [comment]
I think we'll need to remove the "Scratch Addons ping" because of manifest v3 anyway, so this is not really worth doing.
