### ISSUE TITLE
Add more languages to the site

### ISSUE THREAD

**Issue by PoIygon** [ScratchAddons/ScratchAddons#4053]
### Describe the solution you'd like
I want more languages in the "languages" thing at the bottom of the footer like the "meow" language and the "edible scratch" language because if the semicolon easter egg is in Scratch Addons then these languages have to be added too.

### Describe alternatives you've considered
If we cannot put extra languages in the language box then we can just set them as options in the scratch addons settings page

### Additional context
[The Edible Scratch Language](https://en.scratch-wiki.info/wiki/April_Fools%27_Day#2015) and i cannot find a link to the meow language page

**Comment by apple502j** [comment]
Rejected, see #1001
