### ISSUE TITLE
Question - scrolling signature bar

### ISSUE THREAD

**Issue by derter-menter** [ScratchAddons/ScratchAddons#4055]
I checked for duplicates

I cannot find the scrolling signature bar. was it removed? Mine does not appear anymore.

**Comment by kccuber-scratch** [comment]
please use the Bug template

**Comment by CST1229** [comment]
You mean the show full signatures thing? That's in the Full areas addon.

**Comment by derter-menter** [comment]
> please use the Bug template next time, also what browser/OS?
1.edge
2. But I don’t think it’s a bug, I probably have it turned off

**Comment by Chiroyce1** [comment]
> Mine does not appear anymore.

Open the addon settings and search for `signature`
![image](https://user-images.githubusercontent.com/97374054/149307102-dedda5f7-6088-43e8-ac19-1ad5cfa83fb4.png)

**Comment by derter-menter** [comment]
> > Mine does not appear anymore.
> 
> Open the addon settings and search for `signature` ![image](https://user-images.githubusercontent.com/97374054/149307102-dedda5f7-6088-43e8-ac19-1ad5cfa83fb4.png)

Thanks
