### ISSUE TITLE
Detect If Someone is Online.

### ISSUE THREAD

**Issue by jumpycoke** [ScratchAddons/ScratchAddons#4058]
This detects if anyone is online. This can be next to the Scratcher rank, with colors. Red for offline, green for online.

**Comment by mxmou** [comment]
There is a discussion about this: #342

**Comment by WorldLanguages** [comment]
My current stance on this is that, as a first step, we should provide an addon that lets users indicate their status on their "What I'm Working On" automatically. If the extension detects the user is idle, it should mark the user as offline automatically. This has the downside that in case of an unexpected shutdown, or even OS sleep, the user will stay as "online" even tho they aren't. It would be cool if Scratch had OAuth, in that case we could have a server that automatically sets users to offline without having to store their session token.

**Comment by CST1229** [comment]
> This has the downside that in case of an unexpected shutdown, or even OS sleep, the user will stay as "online" even tho they aren't.

Maybe store the UTC Unix timestamp (maybe offset because we don't need to have the last online date go back to 1970) in binary/some other base using invisible characters, then check that.

**Comment by WorldLanguages** [comment]
@CST1229 If we reserved 30 chars for the status, we could store a 7 char number: `(x) Online (x) OfflineABCDEFG[newline]`
At some point I found at least 4 zero width characters that work on scratch, so we can represent 4^7=16384 different numbers.
A year has 525600 minutes, 525600/16384~=32, so we could split every year into 32 minute portions, and use some other part of the 30 chars to represent the year (2022, 2023, etc.)

**Comment by CST1229** [comment]
> `(x) Online (x) OfflineABCDEFG[newline]`

I'd say to reserve 20 chars for the status and have it be in the format `[Offline/Online] [ZWS if online because length differences]ABCDEFGHIJK[newline]`.
Then we can store 11 quaternary digits in 10 less chars.
Also, note that right-to-left overrides affect everything after it, so  if it's at the start and it's in your set of 4 characters there should be another RTLO if the number of RTLOs in the digit is odd.

**Comment by WorldLanguages** [comment]
> I'd say to reserve 20 chars for the status and have it be in the format `[Offline/Online] [ZWS if online because length differences]ABCDEFGHIJK[newline]`.

That format works but it's not what Scratchers that manually update their status usually use, because it's less convenient than switching where the `(x)` is.
