### ISSUE TITLE
Combine Sprite Deletion Confirmation Addon into the Confirmation Addon

### ISSUE THREAD

**Issue by ianfife** [ScratchAddons/ScratchAddons#4059]
Combine sprite deletion confirmation into the Confirmation Addon as an option
![image](https://user-images.githubusercontent.com/50230324/149553610-1126c63b-a067-48b4-8707-0d1baf511683.png)

-Reduces Clutter

**Comment by RedGuy12** [comment]
Website addons are separate from editor addons

**Comment by Secret-chest** [comment]
But it's strange rn

**Comment by WorldLanguages** [comment]
Yeah, the rule always has been that addons only affect the website or only affect the editor. This way, Scratch forks like TurboWarp can port editor addons easily, with fully translated addon names. It also keeps the settings page organized, where every addon has a single category and subcategory.
