### ISSUE TITLE
Search profiles with user id

### ISSUE THREAD

**Issue by HiImBlahh** [ScratchAddons/ScratchAddons#4064]
### Describe the solution you'd like

a tab that pops up when you search, that allows you to view a profile from a user id

### Describe alternatives you've considered

nothing
### Additional context
this is what i'm talking about. the user id is the number
![Screenshot 2022-01-15 11 48 27 AM](https://user-images.githubusercontent.com/78574005/149635796-7d827fed-9539-4897-b54d-2538cbfa62ca.png)

**Comment by CST1229** [comment]
Not possible unless a) we use an external database (currently there is no public one) or b) we use a "reply" (the user replied to in the comment API is specified with a user ID), which sends the user a message, and is not allowed

**Comment by ilbailba** [comment]
but I guess it may only be among those who use sa.

**Comment by HiImBlahh** [comment]
> Not possible unless a) we use an external database (currently there is no public one) or b) we use a "reply" (the user replied to in the comment API is specified with a user ID), which sends the user a message, and is not allowed.

how was it even possible to get the id then? it would make sense that if you can get the id, you can figure out who it belongs to

**Comment by CST1229** [comment]
> > Not possible unless a) we use an external database (currently there is no public one) or b) we use a "reply" (the user replied to in the comment API is specified with a user ID), which sends the user a message, and is not allowed.
> 
> how was it even possible to get the id then? it would make sense that if you can get the id, you can figure out who it belongs to

The [user API](https://api.scratch.mit.edu/users/griffpatch) (specified with a username) has the ID, but there's no endpoint to get a user from ID.
