### ISSUE TITLE
Unshared projects to be played in TurboWarp

### ISSUE THREAD

**Issue by jumpycoke** [ScratchAddons/ScratchAddons#4070]
TurboWarp has a feature that can play unshared projects. So when we get the 404 error for unshared projects, there can be a button that  will say "Play this project in TurboWarp" Here, look at my picture. This is the concept for the button.
![image](https://user-images.githubusercontent.com/97655997/149707001-703a09cd-cb67-4059-93ec-86b98b60865f.png)

**Comment by RedGuy12** [comment]
Rejected for ethical reasons.

**Comment by Samq64** [comment]
Duplicate of #3222?

**Comment by RedGuy12** [comment]
oh i didnt see that issue
huh I thought this was rejected
