### ISSUE TITLE
ScratchAddons Testing Extension

### ISSUE THREAD

**Issue by Mbrick2** [ScratchAddons/ScratchAddons#4076]
Essentially this is a way to use addons and patches which have been PRed but not merged.
A few ways this could work.
# URL addon.json
Through addon.json. This means having a project.json hosted somewhere or you manually type it through a button found in the `More Settings` options or a separate extension.
Note: this would mean structuring the addon.json with web hosted urls like
```
{
  "name": "Scratch Messaging",
  "description": "Provides easy reading and replying to your Scratch messages.",
  "userscripts": [
    {
      "url": "https://addonhostingdomain.com/userscript.js",
      "matches": ["https://scratch.mit.edu/*"]
    },
    {
      "url": "https://addonhostingdomain.com/second_userscript.js",
      "matches": ["https://scratch.mit.edu/projects/*", "https://scratch.mit.edu/users/*"]
    }
  ],
  "tags": ["community"],
  "enabled_by_default": false
}
```

### Mockup: 

![Screenshot](https://user-images.githubusercontent.com/90691415/149842724-7038e975-51a3-4cc5-b37d-3bb2b5e216cf.png)
# Bot adding them
This means when a PR is made a bot adds it to the options on the "Testing Extension".

**Comment by RedGuy12** [comment]
not possible due to cws restrictions

**Comment by Mbrick2** [comment]
> not possible due to cws restrictions

cws?? If thats extension update times then #1 still works and #2 could just then be updated weekly

**Comment by RedGuy12** [comment]
we aren't allowed to run scripts not included with the extension

**Comment by Mbrick2** [comment]
> we aren't allowed to run scripts not included with the extension

oh well.
