### ISSUE TITLE
Transifex thinks <empty string> is a HTML tag

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#4082]
### Description

The Debugger addon contains a message called `debugger/empty-string`, which says `<empty string>` in English. Transifex displays it as a HTML tag because of the angled brackets.

### Repoduction steps

Open the Addons Translation resource on Transifex and find the message with key `debugger/empty-string`.

### Expected behaviour

The text would be displayed normally because it has no special meaning. If there is no other way to achieve that, the angled brackets could be replaced.

### Actual behaviour

It is displayed as a tag. Because tags typically aren't meant to be translated, there are already "translations" to German, Italian and Turkish that don't change the original text.

### Screenshots

![image](https://user-images.githubusercontent.com/51849865/150198117-db8e4ae1-300d-428c-bd06-037800bc9b6c.png)

**Comment by RedGuy12** [comment]
> The text would be displayed normally because it has no special meaning.

not possible, I had this same problem a while back

**Comment by WorldLanguages** [comment]
> another solution I can think of is not including any brackets in the string and just adding them on in the code

Yeah, let's just do that
