### ISSUE TITLE
Performance: change `addon.tab.scratchClass` to avoid using a mutation observer

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4106]
This does not affect TurboWarp.

Currently, a mutation observer needs to be attached to the whole document forever, even if the page already loaded:
https://github.com/ScratchAddons/ScratchAddons/blob/master/content-scripts/inject/module.js#L316

This is because addons might use `addon.tab.scratchClass` synchronously but might not add the element to the DOM until needed, and scratchClass might return a placeholder class name starting with `scratchAddonsScratchClass/`.

The mutation observer was added as a fix for #1690. That issue states:
> We can fix this by adding a mutation observer. This may hurt performance slightly but we have many mutation observers already, one per each addon running addon.tab.waitForElement...

That's not true anymore since #2268

Possible solutions:
1. Making scratchClass async
2. Documenting how scratchClass should be properly used to avoid this
3. TODO, haven't thought too much about this. This was in my mind for a lot but I never wrote an issue until now.

It would also be cool to have cleaner code that handles the CSS classes differences between scratch-gui and scratch-paint cc @mxmou any suggestions?

**Comment by mxmou** [comment]
> It would also be cool to have cleaner code that handles the CSS classes differences between scratch-gui and scratch-paint

The following classes exist in both gui and paint and are styled differently:
* `input_input-form`
* `input_input-small`
* `label_input-group`
* `label_input-label`

The label ones seem to be only meant to be used in the toolbar, and I don't think scratch-gui styled inputs would look too out of place in parts of the paint editor other than the toolbar either. There aren't currently any addons that would add new items to the paint editor toolbar, so using gui classes everywhere might be a good solution.

**Comment by WorldLanguages** [comment]
As part of #5962, it might be a good idea to make sure the synchronous `addon.tab.scratchClass()` method is available to be used if the userscript specifies `"runAtComplete": true` which is the default.

We could add an asynchronous `await addon.tab.scratchClassReady()` method that resolves the promise when the scratch classes are available.
