### ISSUE TITLE
Joke Banners

### ISSUE THREAD

**Issue by Mbrick2** [ScratchAddons/ScratchAddons#4120]
# Description
On every (or certain) pages this displayes a joke. On April Fools its a default 
# Mockup
![image](https://assets.scratch.mit.edu/83a3e2f67468e613377a73b95419b473.png)
## Note
[Original From Here](https://scratch.mit.edu/discuss/topic/547162/)

**Comment by CST1229** [comment]
Or maybe it should add random splash text to the Scratch logo as hover text, like Minecraft.

**Comment by apple502j** [comment]
nope

**Comment by Secret-chest** [comment]
> Or maybe it should add random splash text to the Scratch logo as hover text, like Minecraft.

good idea

**Comment by lisa-wolfgang** [comment]
Lol why couldn't this be an easter egg addon?

**Comment by Mbrick2** [comment]
> Lol why couldn't this be an easter egg addon?

Thats what it was intended to be

**Comment by RedGuy12** [comment]
> Or maybe it should add random splash text to the Scratch logo as hover text, somewhat like Minecraft.

Reminds me of NPM too
