### ISSUE TITLE
Edit ocular status from profile

### ISSUE THREAD

**Issue by Oren-Lindsey** [ScratchAddons/ScratchAddons#4129]
### Is your request related to a problem? Please describe.
You should be able to set your ocular status/favorite color from your profile. This would be very nice and seems easy to do

### Describe the solution you'd like
A text box like the wiwo or about me that lets you edit your ocular status. Also it should let you select a favorite color

### Describe alternatives you've considered
Maybe something like github, where you have a text box that appears in the dropdown when you click on your profile picture.

**Comment by RedGuy12** [comment]
We don't control ocular. Not possible.

**Comment by Mbrick2** [comment]
> We don't control ocular. Not possible.

Or do you.....
#3962 (closed) has quick fluffyscratch auth which can be used to authenticate the user using simple js to manipulate the page that then logs you in and changes your status. Wow, @jeffalo should make an api to change status if you are authenticated

**Comment by jeffalo** [comment]
how does ocular know that a request to change status is legitimately from scratch addons on a user's behalf, or from a malicious website?

i personally think a popup (like the ones on reactions) would work the best
