### ISSUE TITLE
Sa Accounts

### ISSUE THREAD

**Issue by Mbrick2** [ScratchAddons/ScratchAddons#4132]
^

**Comment by TheColaber** [comment]
@Mbrick2 can you please elaborate on "Sa Accounts"? In the meantime, I'll close the issue.

**Comment by Mbrick2** [comment]
I mean an account which you make which save your addon.json

**Comment by Dhuls-Scratch** [comment]
> I mean an account which you make which save your addon.json

Use browser sync, or Other Settings > Export Settings

**Comment by Mbrick2** [comment]
> > I mean an account which you make which save your addon.json
> 
> Use browser sync, or Other Settings > Export Settings

i am aware of that I mean cloud settings

**Comment by Dhuls-Scratch** [comment]
This seems like a lot of unneeded complexity for something that can already be accomplished easily.
