### ISSUE TITLE
Debugger for those who dont have SA

### ISSUE THREAD

**Issue by Mbrick2** [ScratchAddons/ScratchAddons#4133]
### Is your request related to a problem? Please describe.

Those who don't have SA have no console, just the block as a custom

### Describe the solution you'd like

The block being a hidden custom block and list and emulating them

**Comment by TheColaber** [comment]
> hidden custom block and list and emulating them

Yeah, either it's not possible, since we can't control how the block looks to other people, or we would have to change the project json, to somehow do this. Even so, we don't want to do this.

**Comment by WorldLanguages** [comment]
Just use the "add item to list" block.
