### ISSUE TITLE
`account-nav.js` sometimes erroring on scratchr2 pages

### ISSUE THREAD

**Issue by CST1229** [ScratchAddons/ScratchAddons#4135]
### Description

Sometimes, on scratchr2 pages, account-nav.js (a vanilla Scratch script) throws an error (full error in Screenshots). On the forums this usually causes the post editor buttons to not appear and the message box to be smaller and rarely causes the account menu to not be created

### Repoduction steps

It happens randomly. Possibly a race condition that triggers when discuss-button runs before account-nav.js.

### Expected behaviour

It should act normally.

### Actual behaviour

The behavior described above.

### Screenshots

```
Uncaught TypeError: can't access property "split", create.attr(...) is undefined
    setAccountNav https://cdn.scratch.mit.edu/scratchr2/static/__03550696c41ed0b9c8e860c6cb190a16__/js/account-nav.js:41
    jQuery 11
        j
        fireWith
        ready
        J
        promise
        ready
        init
        m
        <anonymous>
        <anonymous>
        <anonymous>
account-nav.js:41:40
    setAccountNav https://cdn.scratch.mit.edu/scratchr2/static/__03550696c41ed0b9c8e860c6cb190a16__/js/account-nav.js:41
    jQuery 11
        j
        fireWith
        ready
        J
        (Aszinkron: EventListener.handleEvent)
    promise
        ready
        init
        m
        <névtelen>
        <névtelen>
        <névtelen>

```
![](https://user-images.githubusercontent.com/68464103/151182665-662e6d14-86fc-4fc9-8fec-9453a875d556.png)

### Environment

- Browser: Firefox 97.0b7
- Scratch Addons version: 1.24.0 (master branch on my fork; however I don't think I've changed anything there so I think it is sa/sa commit `dc628d37944537e3799fb62b7d01ee106dad455c`)
- Operating system: Windows 10

### Additional context

Might not be an SA problem but I haven't encountered this on 1.23.0 so it might be.

**Comment by WorldLanguages** [comment]
I think I experienced this too. Probably caused by the discuss-button update.
