### ISSUE TITLE
Add color selection settings to Scratch 2.0 -> 3.0

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#415]
This awesome addon by Maximouse can easily alter the colors of the header and the hover color and normal color of links. Please add this function into settings!

**Comment by Explosion-Scratch** [comment]
I think adding this by 1.1 is appropriate.

**Comment by mxmou** [comment]
Is it OK if this feature is only available when 2.0 → 3.0 is enabled? That way it would be much less work to implement.

**Comment by WorldLanguages** [comment]
@mxmou Wdym by that? Keep in mind css variables accessing addon settings does not work yet

**Comment by Explosion-Scratch** [comment]
Hmm. I didn't know that. It's likely possible to use JS vars and then set the CSS ones to that...

**Comment by GrahamSH-LLK** [comment]
This is blocked by #151.

**Comment by mxmou** [comment]
> @mxmou Wdym by that? Keep in mind css variables accessing addon settings does not work yet

An userscript could set CSS variables.

**Comment by WorldLanguages** [comment]
@mxmou Sure, but it would be better if no js was needed for that.

**Comment by WorldLanguages** [comment]
@mxmou Can you confirm the state of this? You can now retrieve colors of type `settings` from CSS via variables. It's not documented yet, but you can see how other addons do it.

**Comment by Explosion-Scratch** [comment]
Did you guys know you can do this:
document.style.setProperty('--variable', whatever);

**Comment by WorldLanguages** [comment]
Nice try @Explosion-Scratch, yes we know and it's not needed here. Also, you forgot "documentElement", that won't work :P

**Comment by mxmou** [comment]
@WorldLanguages I know that's possible now, I'm going to implement this after I finish my dark mode.

**Comment by Explosion-Scratch** [comment]
> Nice try @Explosion-Scratch, yes we know and it's not needed here. Also, you forgot "documentElement", that won't work :P

\*sigh\* Just trying to help. Still learning JS lol

**Comment by GrahamSH-LLK** [comment]
> @WorldLanguages I know that's possible now, I'm going to implement this after I finish my dark mode.

Anything new?

**Comment by mxmou** [comment]
@GrahamSH-LLK I just opened the PR for dark mode (#699), so I'm probably going to do this after #700 and #701 are resolved.

**Comment by GrahamSH-LLK** [comment]
@mxmou Now?
