### ISSUE TITLE
Profile areas have no spacing

### ISSUE THREAD

**Issue by webdev03** [ScratchAddons/ScratchAddons#4154]
### Description

Profiles look.. broken..
For example here's Chiroyce's profile:
![image](https://user-images.githubusercontent.com/75148774/151921162-3a558c9a-62fd-45db-972f-2aa520ae45a3.png)

### Repoduction steps

1. go to any profile
2. see the big problem

### Expected behaviour

Should look similar to before with a few changes

### Actual behaviour

It has no spacing at all and the About Me doesn't have a line break

### Screenshots

![image](https://user-images.githubusercontent.com/75148774/151921208-4ae92573-b549-412a-bd38-50c5312cbd54.png)

### Environment

- Browser: Firefox 96.0.3
- Scratch Addons version: 1.24.0
- Operating system: macOS Monterey 12.2

### Additional context

I just saw the new update and it's cool but this is confusing
It might be my addon configuration?
I tested with my userstyle and adblocker off too

**Comment by webdev03** [comment]
Seems to happen with "Profile page banner" addon

**Comment by mxmou** [comment]
Appears to depend on the `devicePixelRatio` - I was able to reproduce the problem at 110%. Setting the height of the boxes to 90px instead of 91px fixes it.

**Comment by mxmou** [comment]
> I tried zooming in and out with Firefox and it doesn't seem to do anything to fix it.

If so, Helvetica Neue probably has a slightly larger character height than Arial. Setting an explicit line-height might be necessary.

**Comment by Chiroyce1** [comment]
@mxmou I think this may be related, not sure though. On [this profile](https://scratch.mit.edu/users/TheCloudDev/) with the 2.0 -> 3.0 addon enabled, the featured project has too much padding on the right.

<img width="996" alt="image" src="https://user-images.githubusercontent.com/97374054/152118818-ad045397-289c-402d-a665-649deeeed840.png">

**Comment by RedGuy12** [comment]
> I think this may be related, not sure though. On [this profile](https://scratch.mit.edu/users/TheCloudDev/) with the 2.0 -> 3.0 addon enabled, the featured project has too much padding on the right. This seems to happen when the text is too large, it doesn't wrap to a new line and instead continues on the same line.

This is a bug with scratchr2, not better-featured-project.
