### ISSUE TITLE
Navigation buttons in mystuff are not aligned properly

### ISSUE THREAD

**Issue by Chiroyce1** [ScratchAddons/ScratchAddons#4158]
### Description

The navigation buttons on the left side of [/mystuff](https://scratch.mit.edu/mystuff/) are not aligned properly when using the 2.0 -> 3.0 addon.

### Reproduction steps

1. Make sure 2.0 -> 3.0 addon is enabled
2. Visit [/mystuff](https://scratch.mit.edu/mystuff/)
3. The buttons are not aligned properly

### Expected behaviour

Buttons should start from the same place and should be aligned.

### Actual behaviour

Buttons are not aligned.

### Screenshots
![image](https://user-images.githubusercontent.com/97374054/151995096-fa07e710-a995-4da2-909e-c3f0e1f48be6.png)

### Environment

- Browser: Firefox 96
- Scratch Addons version: 1.24.0
- Operating system: macOS Big Sur

**Comment by Chiroyce1** [comment]
On second thought, I think this may be intentional 😮

**Comment by RedGuy12** [comment]
yes, this is intentional as "Shared projects" and "Unshared projects" are subcategories of "All projects"

**Comment by Chiroyce1** [comment]
hmm... is it possible to increase the indentation on it? I personally feel it's too little...

**Comment by WorldLanguages** [comment]
cc @mxmou

**Comment by Secret-chest** [comment]
It looks weird anyways. Scratch dosen't have real tabs.

**Comment by MystPi** [comment]
This threw me off at first too, but I think it's just for visual hierarchy.
