### ISSUE TITLE
Compatibility needed for 2.0->3.0 addon and search addon.

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#416]
**Describe the bug**

They need more compatibility. Right now it looks terrible.
**To Reproduce**

Use both together.

**Expected behavior**

They work well together.
**Screenshots**

![image](https://user-images.githubusercontent.com/64214252/95116587-3f248e00-0715-11eb-8951-6314e5ad0fa2.png)

**Comment by GrahamSH-LLK** [comment]
@mxmou @lholliger ^
                                  |

**Comment by lholliger** [comment]
I'll take a look at it soon, thanks for letting me know

**Comment by Explosion-Scratch** [comment]
I just noticed that right before coming here. I was going to report it in an issue but there already was one lol, total support though. No offense but it looks terrible now.

**Comment by WorldLanguages** [comment]
oof

**Comment by lholliger** [comment]
> I just noticed that right before coming here. I was going to report it in an issue but there already was one lol, total support though. No offense but it looks terrible now.

@Explosion-Scratch yeah I wrote it using all the 2.0 styling already on the page, entirely forgot about supporting the 3.0 style.
