### ISSUE TITLE
My Stuff tabs have no padding on the right

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#4160]
### Description

In some languages, there is no space between the tabs and the list of projects in My Stuff.

### Repoduction steps

1. Open My Stuff.
2. Set the language to German.
3. Scroll to the top of the page.

### Expected behaviour

There would be some empty space to the right of the tabs.

### Actual behaviour

There is no space.

### Screenshots

![image](https://user-images.githubusercontent.com/51849865/152037607-08f5b02c-7c96-444b-9b36-3d95e265a073.png)

**Comment by Norbiros** [comment]
@mxmou made better work 😄
