### ISSUE TITLE
Copy link/report/delete comment buttons not working with latest update

### ISSUE THREAD

**Issue by MystPi** [ScratchAddons/ScratchAddons#4161]
### Description
*On Scratch 3.0 pages* (like profiles), the buttons that appear when you hover over a comment don't work.

### Repoduction steps

1. Find a Scratch 3.0 page with comments
2. Try to do one of the actions
3. Fail trying

### Expected behaviour

They should work as intended.

### Actual behaviour

Instead, they don't work. Is it just me, or do they also not have icons, like on Scratch 2.0 pages?

Scratch 3.0 pages.
![image](https://user-images.githubusercontent.com/86574651/152052163-c734a8b5-86e7-4ea9-bd6c-cfb09af3da2a.png)

Scratch 2.0 pages.
![image](https://user-images.githubusercontent.com/86574651/152052257-23abace5-f4f5-46a2-bb0b-a7975077ba88.png)

### Environment

- Browser: Firefox 96.0.2
- Scratch Addons version: v1.24.0
- Operating system: Windows 11

**Comment by apple502j** [comment]
@MystPi To clarify: profiles don't work but projects and studios do?

**Comment by Chiroyce1** [comment]
@apple502j yes, it only affects comments on pages with the 2.0 -> 3.0 addon. It's missing the `cursor: pointer;` css rule and is also not functional.

https://user-images.githubusercontent.com/97374054/152093676-74d6bc7a-e24e-47cd-9c64-3a14fefd696a.mov

Tested on macOS Big Sur with Firefox 96 and SA v1.24.0
