### ISSUE TITLE
Usernames overflow on forum posts

### ISSUE THREAD

**Issue by Chiroyce1** [ScratchAddons/ScratchAddons#4163]
Description

Usernames overflow on forum posts when the username's length is >= 20 _(might also happen when the characters are too wide)_.

### Repoduction steps

1. Make sure the 2.0 -> 3.0 addon is enabled
2. Visit [this post](https://scratch.mit.edu/discuss/post/6001023/)
3. Username overflows behind the post area

### Expected behaviour

Username is shown clearly.

### Actual behaviour

Last letter of username is hidden behind the post area.

### Screenshots

<img width="352" alt="image" src="https://user-images.githubusercontent.com/97374054/152094196-5ee9c2f7-f917-49cc-9f5d-4d71124411c1.png">

### Environment

- Browser: Firefox 96
- Scratch Addons version: v1.24.0
- Operating system: macOS Big Sur

**Comment by mxmou** [comment]
This can happen without the addon (try replacing the username with 20 "W"s using Inspect), but the larger text makes it more common.

**Comment by Norbiros** [comment]
Yes :) But we can add special addon for it, or add this fix of this bug to other forums addon (or Scratch 2.0 > 3.0 because that changes a lot of style)... But is it necessary? If you report it to Scratch Team, they will fix it :)

**Comment by mxmou** [comment]
> If you report it to Scratch Team, they will fix it 😃

I don't think so - they aren't actively working on the forums.

I think Scratch 2.0 → 3.0 should add `text-overflow: ellipsis` to fix this. Alternatively, the font size could be reverted.

**Comment by Norbiros** [comment]
They have that... Problem is with long words like `asdasdasdasdasdasd`, words with `spaces` works normally. So we need to add: `word-wrap: break-word;`...

**Comment by mxmou** [comment]
> They have that... Problem is with long words like `asdasdasdasdasdasd`, words with `spaces` works normally. So we need to add: `word-wrap: break-word;`...

They shouldn't wrap - they should be clipped, but with an ellipsis. The example in the OP would become `I_LOVE_TO_MAKE_S...`.

**Comment by CST1229** [comment]
> > They have that... Problem is with long words like `asdasdasdasdasdasd`, words with `spaces` works normally. So we need to add: `word-wrap: break-word;`...
> 
> They shouldn't wrap - they should be clipped, but with an ellipsis. The example in the OP would become `I_LOVE_TO_MAKE_S...`.

Why not wrap?

**Comment by mxmou** [comment]
> Why not wrap?

The result is often ugly.
![image](https://user-images.githubusercontent.com/51849865/152643902-1d936ccb-c413-434a-8537-bc47e9a81266.png)

**Comment by Norbiros** [comment]
It depends on the word ... And on the screen, for example, if you do `crt +` your display will change and be different. And if you really want to know the name, you won't see all name on the ellipsis - you have to do inspect element. 
Another option is to do something like a scroll, when name is to long. What do you think?

**Comment by Samq64** [comment]
>And if you really want to know the name, you won't see all name on the ellipsis - you have to do inspect element.

Or a tooltip.

**Comment by Norbiros** [comment]
Okay, but we will need to implement JS. Scratchr2 uses css, we want to add 5 lines code only for thing?

**Comment by mxmou** [comment]
> Okay, but we will need to implement JS. Scratchr2 uses css, we want to add 5 lines code only for thing?

I'm working on an implementation that shows the full username on hover without JS:
![css_tooltip](https://user-images.githubusercontent.com/51849865/152765822-dbaec447-669c-4cae-87b5-a1d9a237a094.gif)
