### ISSUE TITLE
Featured project overlaps About me

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#4164]
I think this may be related, not sure though. On [this profile](https://scratch.mit.edu/users/TheCloudDev/) with the 2.0 -> 3.0 addon enabled, the featured project has too much padding on the right. This seems to happen when the text is too large, it doesn't wrap to a new line and instead continues on the same line.

<img width="996" alt="image" src="https://user-images.githubusercontent.com/97374054/152118818-ad045397-289c-402d-a665-649deeeed840.png">

_Originally posted by @Chiroyce1 in https://github.com/ScratchAddons/ScratchAddons/issues/4154#issuecomment-1027695008_

**Comment by mxmou** [comment]
@RedGuy12 Scratch sets the width to 280px, but the thumbnail inside is 282px, meaning that two pixels of the right padding are cut off. Replacing `auto` with 282px is the correct fix for this.
