### ISSUE TITLE
Error with developing addon

### ISSUE THREAD

**Issue by Norbiros** [ScratchAddons/ScratchAddons#4171]
### Description

When I use `console.log(addon.auth.username)` in code in console I can find `undefined`. 
Even in https://scratchaddons.com/docs/develop/addon-types/userscripts/ I can find example of using that.

### Repoduction steps

1. Create example page from link above.
2. Save, and load it.
3. Refresh page

### Expected behaviour

It should send my nickname.

### Additional context

`addon` works, because if for example you try to get addon folder - it works fine!

**Comment by GrahamSH-LLK** [comment]
Can you send your full code?

**Comment by RedGuy12** [comment]
`addon.auth.username` has been removed
