### ISSUE TITLE
md5 library used by image-uploader uses eval()

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4175]
This is by no means a new issue, and is still low prio, but it's interesting that Mozilla logs our extension as "eval can be harmful" just because of the md5 library usage of eval. We do not use eval ourselves.
Is eval actually necessary for an md5 library to function? Can we use a different library?

**Comment by towerofnix** [comment]
It's not required at all - the library only uses it [specifically when in a node.js environment](https://github.com/emn178/js-md5/blob/0263ab835f4847351a710f98488203108c0e1e90/src/md5.js#L138-L141), where it does [<code>eval("require('crypto')")</code> and <code>eval("require('buffer').Buffer)")</code>](https://github.com/emn178/js-md5/blob/0263ab835f4847351a710f98488203108c0e1e90/src/md5.js#L156-L157).

There are probably other libraries which don't do this :P

Or you could make a fork which either gets rid of the Node.js-specific code, or accesses `this` (or `globalThis`) `.require` instead. There might be forks which already do either of these.

**Comment by apple502j** [comment]
That is a Node.js-specific path

**Comment by towerofnix** [comment]
ninja'd :shipit:

**Comment by apple502j** [comment]
LOL
