### ISSUE TITLE
[v1.27.0] Updating the extension store description for Scratch Addons

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4176]
**TODO: as well as changing the description, Chrome extension category should be "productivity"**

Please submit any suggestions on how the description should be changed here.

This is the current description used in the Chrome Web Store and Mozilla Add-Ons page:

> — scratch.mit.edu features —
> - Messaging: click the extension icon to get a summary of your messages.
> - Cloud games: see who's playing multiplayer games.
> - Notifier: get browser notifications when you get new messages.
> - Navigation bar customization: re-add the “discuss” button.
> - Make 2.0-styled pages look like 3.0.
> - Website and editor dark modes.
> - And more!
>
> — Project editor features —
> - Developer tools: adds a find box and new menu options to the editor.
> - 60FPS player mode.
> - Pause button.
> - Onion skinning.
> - Auto-hide block palette.
> - Display stage on left side.
> - And more!
> 
> Keep in mind, all features are togglable! To enable or disable them, go to the settings page by clicking this extension’s icon under “extensions” in the top-right corner of your browser, and then click the gear icon.
> 
> No usernames or passwords are stored, and you are required to be signed into your Scratch account in your browser for some features to work.
> 
> This extension is open source software licensed under GPL v3.
> To contribute or check the source code: https://github.com/ScratchAddons
> For more information, go to: ScratchAddons.com
> 
> This project is not affiliated, associated, or in any way officially connected with the Scratch website, Team, Foundation, or any of its affiliates.

**Comment by WorldLanguages** [comment]
Should this have been a discussion? Whoops

**Comment by RIMOPA** [comment]
"And more!" sounds like there are three or five more addons, I think "And much more!" Is better.
 Sorry for my English

**Comment by Chiroyce1** [comment]
> Custom navbar: Customize the links displayed in the navigation bar.

Is this too vague?

**Comment by WorldLanguages** [comment]
> Is this too vague?

Most users will not use that addon so I'm not sure if it's worth mentioning.

**Comment by RedGuy12** [comment]
> Should this have been a discussion? Whoops

I mean, this is something that will be changed in a pr, so an issue is fine IMO


> Most users will not use that addon so I'm not sure if it's worth mentioning.

but we already mention discuss button

**Comment by WorldLanguages** [comment]
> but we already mention discuss button

My bad, at some point I replaced one addon with another and I thought it was discuss button for a sec.

**Comment by Mbrick2** [comment]
> — website features —
>
>    Messaging: click the extension icon to get a summary of your messages.
>    Notifier: get browser notifications when you get new messages.
 >   Custom navigation bar bar: Customize the links displayed in the navigation bar.
>    Make 2.0-styled pages look like 3.0.
>    Website and editor dark modes.
>    Browse followers button in studios.
>    Show full context on areas with limited height. 
 >   And a whole lot more!
>
>— Project editor features —
>
 >   Developer tools: adds a find box and new menu options to the editor.
  >  60FPS player mode.
    >Pause button.
    >Onion skinning.
  >  Auto-hide block palette.
  >  Display stage on left side.
  >  And much more!

**Comment by Norbiros** [comment]
I think maybe some small styling this text? Create some bold text, replace for example this `>` with `» `. Maybe remove link in `scratch.mit.edu` features? On mozzila it look bad for me. Add some `enters` etc. Make text nice to ice, for example i think Description Section in it is much better than feature list :)

**If mozzila don't support html tags, try using something like that: https://lingojam.com/BoldTextGenerator**

**Comment by WorldLanguages** [comment]
> Create some bold text

Only the Mozilla stores supports bold text. And I don't want to use any weird Unicode characters that look like bold.

**Comment by Norbiros** [comment]
Okay, so please made bold text for mozzila, they don't need to look the same... 
`Firefox better tu tu` 🥳 `subjective opinion (firefox 3% sadge)`

**Comment by Hans5958** [comment]
Alright, what is the most used addons? You have the stats right? We should put those that are frequently used there.

**Comment by Hans5958** [comment]
Also, while we're at it, might consider my new extension store images?

**Comment by Hans5958** [comment]
Just uploading the CWS ones for relevancy.

![sa cover chrome large](https://user-images.githubusercontent.com/11584103/155578391-8ff10226-f744-487c-a56d-b0eb02401a5d.png)
![sa cover chrome small](https://user-images.githubusercontent.com/11584103/155578400-9f4ff41d-a55f-41ba-85db-b25703578d91.png)

**Comment by Hans5958** [comment]
Also, the highlights on the website can also have an update.

**Comment by WorldLanguages** [comment]
> No usernames or passwords are stored, and you are required to be signed into your Scratch account in your browser for some features to work.

This part of the description was borrowed from Scratch Messaging Extension. I don't think it makes a lot of sense to keep it, what do you think? (please react to this message, thumbs up if we should remove it).
Also, we do technically store usernames in local storage - I think SME did that too, but anyway.

**Comment by apple502j** [comment]
"also known as nono word" please no

**Comment by Hans5958** [comment]
its satire bro

**Comment by jeffalo** [comment]
> its satire bro

i hope it is

**Comment by Wjplatformer** [comment]
How about making the `open source` part text of the home page a link to this repo or the contributors page? It feels more easily accessible when new users browse through, instead of returning to the top again.
![suggestion2](https://user-images.githubusercontent.com/82447031/156885819-6bbff2e3-b75b-49d8-9845-cd5e9ad648ca.png)

**Comment by Hans5958** [comment]
> How about making the `open source` part text of the home page a link to this repo or the contributors page? It feels more easily accessible when new users browse through, instead of returning to the top again. ![suggestion2](https://user-images.githubusercontent.com/82447031/156885819-6bbff2e3-b75b-49d8-9845-cd5e9ad648ca.png)

There's the "Repository" button on the navbar.

**Comment by Wjplatformer** [comment]
> > How about making the `open source` part text of the home page a link to this repo or the contributors page? It feels more easily accessible when new users browse through, instead of returning to the top again. ![suggestion2](https://user-images.githubusercontent.com/82447031/156885819-6bbff2e3-b75b-49d8-9845-cd5e9ad648ca.png)
> 
> There's the "Repository" button on the navbar.

I know that, although I feel that this could also be placed here as I usually do that in other websites. If not, this can direct to the top when clicked and we can see the `Repository` button. Also, another visual improvement is that this panel can still be orange as it looks a little too dark in dark theme.

**Comment by Hans5958** [comment]
I see what you mean. I might consider this, but I need to keep in mind with the i18n.

**Comment by Wjplatformer** [comment]
Alright then. Thanks

**Comment by Dhuls-Scratch** [comment]
Add something about animated-thumb, block-switching, mediarecorder, and studio-tools

**Comment by Hans5958** [comment]
Any updates, eh?

**Comment by WorldLanguages** [comment]
I think we should standardize this message. It's different in the website footer:

Footer:
> Scratch Addons is not affiliated, associated, or in any way officially connected with Scratch, the Scratch Team, the Scratch Foundation, or any of its subsidiaries or its affiliates.

Current description:
> This project is not affiliated, associated, or in any way officially connected with the Scratch website, Team, Foundation, or any of its affiliates.

Using the word "affiliates" seems wrong too. And the Chrome Web Store one can't reuse the word "Scratch" due to keyword spam rule.

**Comment by WorldLanguages** [comment]
@Hans5958 Could you see what I posted just above about the website footer?

**Comment by Hans5958** [comment]
About the keyword spam thing? I did, and I think it's fine.

**Comment by apple502j** [comment]
Can't we make it to 1.26?

**Comment by lisa-wolfgang** [comment]
I agree with Hans -- we should re-evaluate which addons are the most marketable (i.e. useful or exciting) and then rework the addon listing accordingly. We don't need separate sections for community and editor addons. If an addon's categorization isn't obvious from the addon name itself, then it shouldn't be listed. When most people read an extension description, they're trying to figure out if the extension is worth their time, so we need to grab their attention as soon as possible.

We also don't need to keep the paragraph about addons being togglable. Most people won't read past the feature list. A better, more accurate way to get that message across would be to include "customizable" in the opening sentence.

With that being said, and taking the other suggestions into consideration, here is my proposed description revision:

> Scratch Addons provides customizable features and themes for the scratch.mit.edu website and project editor.
>
> Choose from 100+ options:
> \- Quickly read and respond to messages by clicking the extension icon.
> \- Jump into active multiplayer games with the cloud games tab.
> \- Get browser notifications when you get new messages.
> \- Use the 3.0 style and/or dark mode for the whole website.
> \- Gain the ability to leave studios, easily promote or remove curators, and browse followers to invite.
> \- Improve the forums with a search bar, scrollable signatures, local timezone conversion, live preview, and more.
> \- Enhance the project player with a pause button, 60FPS, TurboWarp, gamepad support, and true fullscreen.
> \- Animate more easily with onion skinning, exact color picking, and costume search.
> \- Supercharge your coding efficiency with block search, jump to, quick-switch, quick-create, quick-duplicate, single-grab, and copy/paste.
> \- Stay tidy with the auto-hiding block palette, snap-to-grid, comment straightening, sprite folders, and nameable backpack scripts.
> \- View progress when loading and saving projects.
> \- Directly set and freeze project thumbnails to any image or GIF.
> \- Bring back the cat blocks from April Fools'.
> \- Make blocks thinner and change the colors.
> \- Debug projects with logging, programmatic pausing, and step-by-step execution.
> \- Monitor project performance and show the live clone count.
> \- And more with each update!
> 
> This extension is open source software licensed under GPL v3.
> To contribute or check the source code: https://github.com/ScratchAddons
> For more information, go to: ScratchAddons.com
> 
> This project is not affiliated, associated, or in any way officially connected with the Scratch website, Team, Foundation, or any of its affiliates.

We probably want to consolidate the feature list -- I just wanted to provide several options. There should definitely be at least one prominent bullet per main Scratch use case: messaging, project-playing, programming, and using the paint editor. Thoughts on what should be prioritized?

If I had to pick as few as possible, I would select these eight and order them like this:
- Quickly read and respond to messages by clicking the extension icon.
- Jump into active multiplayer games with the cloud games tab.
- Enhance the project player with a pause button, 60FPS, TurboWarp, gamepad support, and true fullscreen.
- Supercharge your coding efficiency with block search, jump to, quick-switch, quick-create, quick-duplicate, single-grab, and copy/paste.
- Animate more easily with onion skinning, exact color picking, and costume search.
- Directly set and freeze project thumbnails to any image or GIF.
- Debug projects with logging, programmatic pausing, and step-by-step execution.
- Stay tidy with the auto-hiding block palette, snap-to-grid for blocks, comment straightening, sprite folders, and nameable backpack scripts.

**Comment by DNin01** [comment]
How about this for a brief intro to start the description?
> Scratch Addons provides dozens of enhancements and customizable features all in one package to make using Scratch easier. Each enhancement is a toggleable addon, so you can choose the adjustments that you like.

**Comment by Secret-chest** [comment]
Why are you obsessed with dozens?

**Comment by Secret-chest** [comment]
> Scratch Addons brings together over 120 customizations, themes and quality-of-life updates, all in one extension, to make using Scratch more enjoyable. Everything is fully toggleable and customizable. You can choose which features you want to use.
> Scratch Addons is fully free, libre, open source software and maintained by a community of Scratchers. https://github.com/ScratchAddons/ScratchAddons

**Comment by apple502j** [comment]
**MOSTLY FINAL DRAFT** - I will ask @WorldLanguages to review this. Based on @lisa-wolfgang 's draft. Will send to W_L to get a final review. If you have objections post here now.

```
Scratch Addons provides customizable features and themes for the scratch.mit.edu website and project editor. Each enhancement is toggleable, so you can choose the adjustments that you like.

Choose from 100+ options:
- Quickly read and respond to messages by clicking the extension icon.
- Jump into active multiplayer games with the cloud games tab.
- Get browser notifications when you get new messages.
- Use the 3.0 style or dark mode for the whole website.
- Easily leave studios, promote or remove curators, and browse followers to invite.
- Improve the forums with a search bar and more.
- Enhance the project player with a pause button, 60FPS, gamepad support, and true fullscreen.
- Animate more easily with onion skinning, exact color picking, and costume search.
- Supercharge your coding efficiency with block search, jump to, quick-switch, quick-create, quick-duplicate, single-grab, and copy/paste.
- Stay tidy with the auto-hiding block palette, snap-to-grid, comment straightening, sprite folders, and nameable backpack scripts.
- Directly set and freeze project thumbnails to any image or GIF.
- Bring back the cat blocks from April Fools'.
- Debug projects with logging, performance monitoring, and step-by-step execution.
- And more with each update!

This extension is open source software licensed under GPL v3.
To contribute or check the source code: https://github.com/ScratchAddons
For more information, go to: ScratchAddons.com

This project is not affiliated, associated, or in any way officially connected with the Scratch website or the organizations that maintain it.
```

**Comment by Weredime** [comment]
> For more information, go to: ScratchAddons.com

Probably make the characters in the url lowercase (scratchaddons.com)

**Comment by Secret-chest** [comment]
> **MOSTLY FINAL DRAFT** - I will ask @WorldLanguages to review this. Based on @lisa-wolfgang 's draft. Will send to W_L to get a final review. If you have objections post here now.
> 
> ```
> Scratch Addons provides customizable features and themes for the scratch.mit.edu website and project editor. Each enhancement is toggleable, so you can choose the adjustments that you like.
> 
> Choose from 100+ options:
> - Quickly read and respond to messages by clicking the extension icon.
> - Jump into active multiplayer games with the cloud games tab.
> - Get browser notifications when you get new messages.
> - Use the 3.0 style or dark mode for the whole website.
> - Easily leave studios, promote or remove curators, and browse followers to invite.
> - Improve the forums with a search bar and more.
> - Enhance the project player with a pause button, 60FPS, gamepad support, and true fullscreen.
> - Animate more easily with onion skinning, exact color picking, and costume search.
> - Supercharge your coding efficiency with block search, jump to, quick-switch, quick-create, quick-duplicate, single-grab, and copy/paste.
> - Stay tidy with the auto-hiding block palette, snap-to-grid, comment straightening, sprite folders, and nameable backpack scripts.
> - Directly set and freeze project thumbnails to any image or GIF.
> - Bring back the cat blocks from April Fools'.
> - Debug projects with logging, performance monitoring, and step-by-step execution.
> - And more with each update!
> 
> This extension is open source software licensed under GPL v3.
> To contribute or check the source code: https://github.com/ScratchAddons
> For more information, go to: ScratchAddons.com
> 
> This project is not affiliated, associated, or in any way officially connected with the Scratch website or the organizations that maintain it.
> ```

Change `-` to bullet points: •

**Comment by apple502j** [comment]
@Weredime The capitalization is fine.
@Secret-chest Change accepted

**Comment by apple502j** [comment]
Okay, I checked the latest stats and it seems like there are addons that don't need listing and ones that do need listing. The description above lists 24 addons: hide-flyout, script-snap, forum-search, gamepad, scratch-notifier, fullscreen, cat-blocks, studio-followers, name-backpack-items, block-cherry-picking, debugger, scratchr2, folders, dark-www, fix-editor-comments, color-picker, onion-skinning, pause, 60fps, animated-thumb, cloud-games, studio-tools, scratch-messaging, editor-devtools.

From the feedback-based 470 usage reports I have (Addon usage data, Feb 1 - Jul 3), average user count is 269.8, or 214.7 if we exclude enabled-by-default addons. There are 21 addons whose user count is above 269.8, or 39 not enabled-by-default addons whose user count is above 214.7.

Given those considerations I will make a new draft and send to W_L.

**Comment by lisa-wolfgang** [comment]
Do keep in mind that some addons are much more marketable than others -- "do not automatically run duplicated blocks", while popular and very useful, is already a nightmare to explain, and we had an entire addon description for that. (Also, those stats are inaccurate due to the incomplete, outdated, and partially duplicate nature of the data, so we shouldn't rely on it as a source of truth.)

**Comment by lisa-wolfgang** [comment]
Also, remember that we should include at least one bullet point for each major use case of Scratch. Again, this description will be what many people use to decide whether our extension is worth their time, so we need it to be attention-grabbing and comprehensive. We can filter some of the bullet points out, as I suggested at the end of my original proposal.

**Comment by apple502j** [comment]
Okay, changed some stuff. Forums and scratch notifier are now gone, instead added project management.

```
Scratch Addons provides customizable features and themes for the scratch.mit.edu website and project editor. Each enhancement is toggleable, so you can choose the adjustments that you like.

Choose from 100+ options:
• Quickly read and respond to messages by clicking the extension icon.
• Jump into active multiplayer games with the cloud games tab.
• Use the 3.0 style or dark mode for the whole website.
• Easily leave studios, promote or remove curators, and browse followers to invite.
• Improve project management with the My Stuff search bar and the unshare button.
• Enhance the project player with a pause button, 60FPS, and gamepad support.
• Animate more easily with onion skinning, exact color picking, and costume search.
• Supercharge your coding efficiency with block search, dropdown search, jump to, block switching, single-grab, and copy/paste.
• Stay tidy with the auto-hiding block palette, comment straightening, and sprite folders.
• Directly set and freeze project thumbnails to any image or GIF.
• Bring back the cat blocks from April Fools'.
• Debug projects with logging, performance monitoring, and step-by-step execution.
• And more with each update!

This extension is open source software licensed under GPL v3.
To contribute or check the source code: https://github.com/ScratchAddons
For more information, go to: ScratchAddons.com

This project is not affiliated, associated, or in any way officially connected with the Scratch website or the organizations that maintain it.
```

**Comment by Secret-chest** [comment]
> Okay, changed some stuff. Forums and scratch notifier are now gone, instead added project management.
> 
> ```
> Scratch Addons provides customizable features and themes for the scratch.mit.edu website and project editor. Each enhancement is toggleable, so you can choose the adjustments that you like.
> 
> Choose from 100+ options:
> • Quickly read and respond to messages by clicking the extension icon.
> • Jump into active multiplayer games with the cloud games tab.
> • Use the 3.0 style or dark mode for the whole website.
> • Easily leave studios, promote or remove curators, and browse followers to invite.
> • Improve project management with the My Stuff search bar and the unshare button.
> • Enhance the project player with a pause button, 60FPS, and gamepad support.
> • Animate more easily with onion skinning, exact color picking, and costume search.
> • Supercharge your coding efficiency with block search, dropdown search, jump to, block switching, single-grab, and copy/paste.
> • Stay tidy with the auto-hiding block palette, comment straightening, and sprite folders.
> • Directly set and freeze project thumbnails to any image or GIF.
> • Bring back the cat blocks from April Fools'.
> • Debug projects with logging, performance monitoring, and step-by-step execution.
> • And more with each update!
> 
> This extension is open source software licensed under GPL v3.
> To contribute or check the source code: https://github.com/ScratchAddons
> For more information, go to: ScratchAddons.com
> 
> This project is not affiliated, associated, or in any way officially connected with the Scratch website or the organizations that maintain it.
> ```

Forums is very important, SN could merge with messaging.

• Quickly read and respond to messages by clicking the extension icon, and get notifications for new ones.

**Comment by apple502j** [comment]
There aren't many good forum features, at least not something to be put on description.

**Comment by mxmou** [comment]
> There aren't many good forum features, at least not something to be put on description.

I think image uploader could be mentioned.

**Comment by Secret-chest** [comment]
> > There aren't many good forum features, at least not something to be put on description.
> 
> I think image uploader could be mentioned.

And ocular!

**Comment by WorldLanguages** [comment]
**New proposed extension description:**
`Scratch Addons provides customizable features and themes for the scratch.mit.edu website and project editor.`
(Diff vs current one: new word "customizable", rest is kept the same)
Keep in mind the Chrome Web Store adds the manifest.json description at the start of the store description. I don't think it makes sense to add "each enhancement is toggleable, so you can choose the adjustments that you like" to the manifest.json description, so please suggest a good place to add that on the store description (it can't be the same line as the manifest.json description) or let's discard it.

**Comment by WorldLanguages** [comment]
Proposal by apple502j on comment https://github.com/ScratchAddons/ScratchAddons/issues/4176#issuecomment-1173136073 is very good.

Maybe we need better wording for `project management`?

@lisa-wolfgang Is it `April Fools'.` or `April Fools.`?

When naming the addons, I think we need to try to get close to the actual addon name:
- `exact color picking`: no search results, and I don't even know what this refers to - I guess hex color and color picker inputs?
- `dropdown search`: why not just `searchable dropdowns`?
- `jump to`: maybe `jump to custom block` or avoid mentioning at all?
- `comment straightening`; is it worth mentioning?

I like the wording for the new disclaimer, the website footer should also use it (`This project is not affiliated, associated, or in any way officially connected with the Scratch website or the organizations that maintain it.`)

**Comment by WorldLanguages** [comment]
> We also don't need to keep the paragraph about addons being togglable. Most people won't read past the feature list. A better, more accurate way to get that message across would be to include "customizable" in the opening sentence.

Right. As I said, the opening sentence is the manifest.json description. So the `each enhancement is toggleable, so you can choose the adjustments that you like` sentence from apple502j's latest proposal won't be kept. The new description clearly says: **choose** from 100+ **options**, and the new manifest.json description includes the world "customizable", so it's probably clear enough.

**Comment by lisa-wolfgang** [comment]
> @lisa-wolfgang Is it `April Fools'.` or `April Fools.`?

I looked into it and it should actually be "April Fools' Day" in full.

**Comment by WorldLanguages** [comment]
## \*\*My last proposal\*\* (unless anyone has something to say)

### **New manifest.json description:**
```
Scratch Addons provides customizable features and themes for the scratch.mit.edu website and project editor.
```
(Similar to current description: only change is "new" was changed to "customizable")

### **New store description:**
Note: Chrome Web Store always adds the manifest.json description to the store description as the first paragraph.
This version is slightly different from the one by apple502j from a few comments above.
```
Scratch Addons provides customizable features and themes for the scratch.mit.edu website and project editor.

Choose from 100+ options:
• Quickly read and respond to messages by clicking the extension icon.
• Jump into active multiplayer games with the cloud games tab.
• Use the 3.0 style or dark mode for the whole website.
• Easily leave studios, promote or remove curators, and browse followers to invite.
• Improve project management with the My Stuff search bar and the unshare button.
• Enhance the project player with a pause button, 60FPS, and gamepad support.
• Animate more easily with onion skinning, exact color picking, and costume search.
• Supercharge your coding efficiency with block search, searchable dropdowns, block switching, single-grab, and copy/paste.
• Stay tidy with the auto-hiding block palette, comment straightening, and sprite folders.
• Directly set and freeze project thumbnails to any image or GIF.
• Bring back the cat blocks from April Fools.
• Debug projects with logging, performance monitoring, and step-by-step execution.
• And more with each update!

This extension is open source software licensed under GPL v3.
To contribute or check the source code: https://github.com/ScratchAddons
For more information, go to: ScratchAddons.com

This project is not affiliated, associated, or in any way officially connected with the Scratch website or the organizations that maintain it.
```

About the last paragraph, we should also use it for the ScratchAddons.com website footer.

Keep in mind I might change a word or two for the final version. For example, when reading `project management`, unrelated ideas come to my mind (Gantt charts hehe). Maybe it's just me, but I think it could be phrased differently.

@apple502j @lisa-wolfgang @Hans5958 @mxmou @Weredime @RedGuy12 @TheColaber @GrahamSH-LLK Please react with thumbs up, or if you have something to say about this draft, post a comment.

**Comment by Secret-chest** [comment]
Why don't we highlight ocular?

**Comment by Secret-chest** [comment]
> 3.0 style or dark mode

3.0 style and/or dark mode

**Comment by Secret-chest** [comment]
> more easily

easier

**Comment by Weredime** [comment]
> Why don't we highlight ocular?

Explanation?
It might also be good so people can google ocular and get SA results

**Comment by lisa-wolfgang** [comment]
> > comment straightening
> 
> 
> 
> I don't think people will understand what that means. "Comment" could mean website comments or workspace comments, not just block comments.

It could be elaborated on by being rephrased to "editor comment straightening."

**Comment by lisa-wolfgang** [comment]
Also, looking at it again, snap-to-grid seems important to the "stay tidy" category.

**Comment by Hans5958** [comment]
Apologizes for backtracking, if it is: Why do we mention "website and project editor," even though scratch.mit.edu is descriptive enough.

PS. Maybe we should avoid scratch.mit.edu, but then IDK "Scratch" would be enough to refer it.

**Comment by apple502j** [comment]
> Why don't we highlight ocular?

It's not technically our service.

> 3.0 style and/or dark mode

Use "or". "and/or" is unnecessary.

> easier

Nope, "more easily" is the correct one.

> Also, looking at it again, snap-to-grid seems important to the "stay tidy" category, but it's missing here.

I removed it, it seemed like it's not that widely used.

> Apologizes for backtracking, if it is: Why do we mention "website and project editor," even though scratch.mit.edu is descriptive enough?
> PS. Maybe we should avoid scratch.mit.edu, but then IDK "Scratch" would be enough to refer it.

Search engine optimization?

> EDIT: Also do "GPL-3.0" instead of "GPL v3"?

It's fine I think

**Comment by mxmou** [comment]
> > 3.0 style and/or dark mode
> 
> Use "or". "and/or" is unnecessary.

"Or" sounds like they're mutually exclusive. "3.0 style and dark mode" would probably be harder to misunderstand.

**Comment by lisa-wolfgang** [comment]
We're not just targeting programmers, and "or" in the English language doesn't carry the inclusive meaning that it can in programming.

I agree with Maximouse that it should be changed to "and."

**Comment by WorldLanguages** [comment]
> Why don't we highlight ocular?

Ocular and TurboWarp won't be mentioned. 3rd party services won't be mentioned.

> > more easily
> 
> easier

I think "more easily" is fine, and Lisa wrote that line and she is a native English speaker (I'm not).

> > comment straightening
> 
> I don't think people will understand what that means. "Comment" could mean website comments or workspace comments, not just block comments.

Agreed. I might remove comment straightening completely maybe.

> Apologizes for backtracking, if it is: Why do we mention "website and project editor," even though scratch.mit.edu is descriptive enough?

Not sure, but I don't think it's necessary to change it.

> EDIT: Also do "GPL-3.0" instead of "GPL v3"?

Apparently it should be `GPLv3`: https://www.gnu.org/licenses/quick-guide-gplv3.html
I don't think this is worth changing either

> "Or" sounds like they're mutually exclusive. "3.0 style and dark mode" would probably be harder to misunderstand.

I agree that it could be read as "you have to choose between 3.0 style and dark mode". But `and/or` is ugly and may be difficult to translate. Any ideas on how to rephrase? It could also be confusing because there's two separate dark mode addons, and this sentence appears to imply there's only one.

**Comment by WorldLanguages** [comment]
There's a few details that could be discussed but glad we will get a better store description! The current one is so old from the Scratch Messaging Extension days. Thanks everyone!

**Comment by WorldLanguages** [comment]
> I agree that it could be read as "you have to choose between 3.0 style and dark mode". But `and/or` is ugly and may be difficult to translate. Any ideas on how to rephrase? It could also be confusing because there's two separate dark mode addons, and this sentence appears to imply there's only one.

lisa-wolfgang suggested an alternative on the Discord server: 
```
• Beautify every page on the Scratch website with the 3.0 style and options for dark mode and custom color themes
```

**Comment by WorldLanguages** [comment]
## Final version:

```
Scratch Addons provides customizable features and themes for the scratch.mit.edu website and project editor.

Choose from 100+ options:
• Quickly read and respond to messages by clicking the extension icon.
• Jump into active multiplayer games with the cloud games tab.
• Beautify every page on the Scratch website with the 3.0 style and options for dark mode and custom color themes.
• Easily leave studios, promote or remove curators, and browse followers to invite.
• Improve project management with the My Stuff search bar and the unshare button.
• Enhance the project player with a pause button, 60FPS, and gamepad support.
• Animate more easily with onion skinning, exact color picking, and costume search.
• Supercharge your coding efficiency with block search, searchable dropdowns, block switching, single-grab, and copy/paste.
• Stay tidy with the auto-hiding block palette and sprite folders.
• Directly set and freeze project thumbnails to any image or GIF.
• Bring back the cat blocks from April Fools.
• Debug projects with logging, performance monitoring, and step-by-step execution.
• And more with each update!

This extension is open source software licensed under GPL v3.
To contribute or check the source code: https://github.com/ScratchAddons
For more information, go to: ScratchAddons.com

This project is not affiliated, associated, or in any way officially connected with the Scratch website or the organizations that maintain it.
```

![image](https://user-images.githubusercontent.com/17484114/178084643-bf24724c-805f-4b85-9c9f-73efff465f90.png)

**Comment by Hans5958** [comment]
How about the store thumbnails? Would that warrant it's own issue?

**Comment by lisa-wolfgang** [comment]
Yes. (Reminder that those should be version-agnostic if at all possible.)

**Comment by WorldLanguages** [comment]
Also, store thumbnails can be changed more often because they don't go through translation.

**Comment by Hans5958** [comment]
Someone did #4811 to be made for the thumbnails, but more like with the other images. All the images is posted there.
