### ISSUE TITLE
Custom Block Category Colors

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#418]
**Describe the new addon**

Would let you choose a custom color for each block category.

**Comment by WorldLanguages** [comment]
This has been suggested through feedback as well.

**Comment by TheColaber** [comment]
Wasn't this added?

**Comment by YOYITsM3M8** [comment]
the addon that was added is for block colors not catergorys

**Comment by TheColaber** [comment]
We're talking about the same category, right?
![Screenshot 2020-10-30 173937](https://user-images.githubusercontent.com/72760579/97759228-f921d680-1ad6-11eb-821f-4df44269cebd.png)

**Comment by YOYITsM3M8** [comment]
yes

**Comment by WorldLanguages** [comment]
Yes, this was added

**Comment by ZenithRogue** [comment]
Lol, didn't know there was an issue created for this when I submitted #461
