### ISSUE TITLE
Mystuff page messed after update

### ISSUE THREAD

**Issue by prakarsh17** [ScratchAddons/ScratchAddons#4181]
### Description
![image](https://user-images.githubusercontent.com/88645086/152501265-e6d5fba1-e1b8-46d7-824a-12a4dc30ef77.png)
Broken My stuf...

**Comment by apple502j** [comment]
@prakarsh17 It looks fine? What's the problem?

**Comment by Chiroyce1** [comment]
If you're talking about the tabs on the left - #4158

**Comment by WorldLanguages** [comment]
It's looking as intended. If you have any suggestions on making the styling better, please create a new "enhancement" issue.

**Comment by prakarsh17** [comment]
> If you're talking about the tabs on the left - #4158

Yeah talking about it
