### ISSUE TITLE
 clone counter plugin seems not to be working

### ISSUE THREAD

**Issue by ksdavidc** [ScratchAddons/ScratchAddons#4184]
### Description

The clone counter plugin seems not to be working since last update. I have tried simple troubleshooting, including disabling some plugins, especially the debugger since I thought there might be conflict with the new clone tracker. no luck. Sorry, no more information available. 

### Repoduction steps

1. start scratch with plugin active. 
2. Run project that creates clones.
3. Look for clone counter where it should be. Notice nothing there.

### Expected behaviour

It should appear at top next to rest stop button.

### Actual behaviour

blank.

### Screenshots

![Screen Shot 2022-02-05 at 4 08 00 AM](https://user-images.githubusercontent.com/62230004/152588608-dfec4a4a-471a-4323-b8bd-afab8d96f73d.png)
not shown, but there are several clones created...
 
### Environment

- Browser: Chrome 97.0.4692.99
- Scratch Addons version: 1.24.1
- Operating system: mac 

### Additional context

n/a

**Comment by WorldLanguages** [comment]
We have gotten feedback about it, but we weren't able to reproduce

**Comment by WorldLanguages** [comment]
Pretty sure v1.24 update caused the issue, but the clones addon itself hasn't changed for months

**Comment by WorldLanguages** [comment]
Here's the list of enabled addon of feedback saying clone counter is broken:

https://scratchaddons.github.io/list-of-enabled-addons/?number=3bcoafqr60vr7vfwgd3i4mc9a6&version=v1.24.1 (Chrome 97)
https://scratchaddons.github.io/list-of-enabled-addons/?number=2xl47uac4qscl4974u4sq0gmwu&version=v1.24.1 (Chrome 97)
https://scratchaddons.github.io/list-of-enabled-addons/?number=2rrds5kg7u39x4sa5uqr4y9n9c&version=v1.24.1 (Chrome 97)
https://scratchaddons.github.io/list-of-enabled-addons/?number=1k4rcbun3kz82a6ewi693fgd7s&version=v1.24.1 (Chrome 97)

**Comment by WorldLanguages** [comment]
There are the addons in common between the four feedback items:

```js
[
    "editor-devtools",
    "msg-count-badge",
    "editor-stepping",
    "scratch-messaging",
    "full-signature",
    "60fps",
    "search-profile",
    "cloud-games",
    "studio-tools",
    "infinite-scroll",
    "mouse-pos",
    "clones",
    "pause",
    "resizable-comment-input",
    "confirm-actions",
    "block-switching",
    "mediarecorder",
    "onion-skinning",
    "mute-project",
    "folders",
    "fix-pasted-scripts",
    "remix-button",
    "echo-effect",
    "swap-local-global"
]
```

**Comment by WorldLanguages** [comment]
Disabling the 60fps addon fixed the issue - but I cannot reproduce with just 60fps and clones enabled.

**Comment by WorldLanguages** [comment]
Can reproduce with just these 3 enabled: 60fps, clones, editor-stepping

**Comment by RedGuy12** [comment]
i was only able to reproduce after clearing my storage and reloading the page. i have the 3 addons wl mentioned enbled. I'm on the latest commit (6228ad1c25ec54b62dd137fea7997eb6a4b722fc). I'm on edge 98.

**Comment by RedGuy12** [comment]
This was caused by 958428dc
