### ISSUE TITLE
Option to change scratchr2 navigation layout

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#4196]
### Is your request related to a problem? Please describe.

Not everyone likes the my stuff or settings navigation layout after the `scratchr2` addon update.

### Describe the solution you'd like

Adding a toggle to `scratchr2` to move the navigation to the top of stuff or settings like it was before 1.24.

### Describe alternatives you've considered

Removing the new navigation completely or making it a new addon.

**Comment by WorldLanguages** [comment]
Also, "old studio layout" still has a 2.0→3.0 setting that uses the old tab style.

**Comment by Secret-chest** [comment]
> Also, "old studio layout" still has a 2.0→3.0 setting that uses the old tab style.

PLEASE DON'T CHANGE IT TO PILLS.

**Comment by WorldLanguages** [comment]
> PLEASE DON'T CHANGE IT TO PILLS.

Of course not. Wouldn't make sense to change an addon that lets you return to the old styles. But we could add a third option, or rename the existing one.

**Comment by Secret-chest** [comment]
> > PLEASE DON'T CHANGE IT TO PILLS.
> 
> Of course not. Wouldn't make sense to change an addon that lets you return to the old styles. But we could add a third option, or rename the existing one.

And add an option to scratchr2 to use real tabs.

**Comment by mxmou** [comment]
Horizontal navigation in My Stuff could be a separate addon. Account Settings navigation was already on the side before, but on the wrong one, so I don't think an option to change that would be very useful.
