### ISSUE TITLE
Adding blocks (request for support)

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#4198]
### Is your request related to a problem? Please describe.

This is not a real proposal for an add-on, but just a request of help to this incredible community working on Scratch source code :-)

For my specific purposes (consistency with Scratch 1.4 basically) I need a version of Scratch 3 that has a set of blocks as similar as possible to the old Scratch 1.4 set of blocks. Is that possible via the add-on mechanism created by ScratchAddons? If so, would someone direct me to the relevant documentation and/or similar addons  (if any) that I can reuse to get this result?

What I need most, in order of relevance is:

1. adding back the "forever if" block
2. hiding the blocks that were added in Scratch 2/3 (e.g. the clones blocks)

Thanks in advance

### Describe the solution you'd like

Knowing if and how this can be done by using the add-on mechanism

### Describe alternatives you've considered

Working on the Scratch code (something that, I think, would be much more difficult for me)

### Additional context

None

**Comment by CST1229** [comment]
Why would you need to do this?

**Comment by apple502j** [comment]
Scratch Addons uses very hacky method to implement some of the features. It's much easier to modify the source code, especially when it comes to additions of new blocks. There is no feasible way to add a C block with a custom behavior.

**Comment by sfederici** [comment]
> Why would you need to do this?

When I teach to my students, I like them to be able to get the desired result with the minimum amount of knowledge. The FOREVER IF block was very useful in Scratch 1.4. Now I'm moving to Scratch 3 and this block is not available anymore. Without this block I verified that my students (that are not enrolled in a technical degree) will very often use the wrong IF FOREVER combination of blocks instead of the correct FOREVER IF combination. That frustrates them, so that some of them will drop the course.

**Comment by sfederici** [comment]
> It's much easier to modify the source code, especially when it comes to additions of new blocks. There is no feasible way to add a C block with a custom behavior.

I would gladly would that, but I never worked on the Scratch 3 source code (I just worked on the Scratch 1.4 code, completely different as implemented in SmallTalk). Is there an easy way for setting up the necessary environment where to edit and test the source code?

**Comment by Dhuls-Scratch** [comment]
> > It's much easier to modify the source code, especially when it comes to additions of new blocks. There is no feasible way to add a C block with a custom behavior.
> 
> I would gladly would that, but I never worked on the Scratch 3 source code (I just worked on the Scratch 1.4 code, completely different as implemented in SmallTalk). Is there an easy way for setting up the necessary environment where to edit and test the source code?

See https://github.com/LLK/scratch-gui/wiki/Getting-Started

**Comment by sfederici** [comment]
> See https://github.com/LLK/scratch-gui/wiki/Getting-Started

Thanks. I will certainly give it a try
