### ISSUE TITLE
Forum search addon has no "No results" message

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#421]
**Is your feature request related to a problem? Please describe.**

When you enter something into the forum search box and nothing is found, the "Loading..." text appears for a second, then disappears without any message. This can be confusing.

**Describe the solution you'd like**

A message explaining that there are no results.

**Describe alternatives you've considered**

**Additional context**

**Comment by JeffaloBob** [comment]
i can take this one
