### ISSUE TITLE
Debugger single stepping changes behaviour of broadcasts

### ISSUE THREAD

**Issue by Tacodude7729** [ScratchAddons/ScratchAddons#4210]
![image](https://user-images.githubusercontent.com/27910867/152661119-7215272c-5b8e-4089-aad1-47126239b0e0.png)
_(See https://scratch.mit.edu/projects/639623384/ for code)_ 

If you just unpause after the breakpoint, the following logs are produced:

![image](https://user-images.githubusercontent.com/27910867/152661138-6161519c-3164-4294-aaca-3e4c067c9ff3.png)

If you single step the rest of the way through the code after the breakpoint, the following logs are produced:

![image](https://user-images.githubusercontent.com/27910867/152661154-2f4f7672-1dc1-4a24-b787-abdeb0a84ce5.png)

I believe this issue comes from single stepping not handling the thread with the second broadcast restarting correctly.

**Comment by Samq64** [comment]
New addon?

**Comment by apple502j** [comment]
@TheColaber bruh
