### ISSUE TITLE
Failed to fetch error

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#4223]
### Description

```
"An error occurred while loading. Please report the following error code to us:
TypeError: Failed to fetch ( Copy )"
```
```
 + Error: [object Response]: status undefined
 + Error: No replies found on comments with parents (see logs)
```
Seems to be popup(?)
### Reproduction steps

Not sure, haven't repro'd myself
### Expected behavior

No error, page loads
### Actual behavior

Errors, doesn't load
### Environment

- Browser: 
- Scratch Addons version: 
- Operating system:

**Comment by apple502j** [comment]
wontfix until we have more info

**Comment by apple502j** [comment]
(This bug report is pretty useless to actually do anything - detailed repro step/stack trace would be appreciated)
