### ISSUE TITLE
More slider monitors

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#4229]
### Is your request related to a problem? Please describe.

It would be nice the be able to easily change things like a sprite's position, size or volume without having to use the inputs under the stage, or in the case of volume, click the block.

### Describe the solution you'd like

Allow monitors for things like position, size, and volume be sliders like suggested in LLK/scratch-gui#4291

### Describe alternatives you've considered

Adding something like #4200 for other values.

### Additional context

I'm not quite sure what should happen with non-SA users...

**Comment by CST1229** [comment]
> I'm not quite sure what should happen with non-SA users...

Scratch does support sliders for other block monitors:
![](https://user-images.githubusercontent.com/68464103/152809521-1d27f7ba-3996-49d0-a75c-7d3950a1e066.png)
(this screenshot was achieved through a bit of Redux hacking)

**Comment by apple502j** [comment]
They do support slider, but the change isn't reflected (for obvious reasons). It's also unclear how the range would be specified. Closing as impractical and not very useful.
