### ISSUE TITLE
Bring sprite to front

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#4231]
### Is your request related to a problem? Please describe.

When there are many sprites on the Stage, some sprite can be covered by other sprites. 

### Describe the solution you'd like

Bring a sprite to front by shift-clicking its thumbnail in the sprite area (as it was in Scratch 1.4)

### Describe alternatives you've considered

Go to lookup category and click the go to front layer block

### Additional context

This is useful when the users have not yet learned that sprites can be programmatically moved from layer to layer.

**Comment by Norbiros** [comment]
I made it 😄 
In next few days I will publish addon with this change.

**Comment by sfederici** [comment]
Thanks a lot!

**Comment by stefanofederici** [comment]
> I made it 😄 In next few days I will publish addon with this change.

Has this been added to the ScratchAddons release?

**Comment by Norbiros** [comment]
No... I made it part of another addon. I think I will make PR in few days with it and other features, but I don't know if W_L, will look at it... Sorry, but u need to wait

**Comment by sfederici** [comment]
> No... I made it part of another addon. I think I will make PR in few days with it and other features, but I don't know if W_L, will look at it... Sorry, but u need to wait

I see. Thanks for letting me know. In the meanting, would you mind tell me in which repository I can find the code (even the full one, I should be able to extract it) so that I can add this feature to the tool my student are going to use next monday? Thanks in advance.

**Comment by Norbiros** [comment]
In PR above... @sfederici
