### ISSUE TITLE
Addons stopped working on forum threads

### ISSUE THREAD

**Issue by LegoManiac04** [ScratchAddons/ScratchAddons#4236]
In the latest update (1.24.2) no addons are working on Forum threads. Everything appears to work correctly on all other pages though. I first noticed that the 2.0 > 3.0 addon wasn't being applied, but I then noticed Ocular reactions and all the other forums addons are gone too.
<h1></h1>

https://user-images.githubusercontent.com/87787046/152879870-c2b088f5-019c-4ff2-b963-3788ae8cbdb8.mp4

<h1></h1>

- SA version: 1.24.2
- Browser: Firefox 96.0.3
- OS: Debian

**Comment by WorldLanguages** [comment]
@LegoManiac04 Can you list all addons running on the page you have enabled?

**Comment by WorldLanguages** [comment]
@LegoManiac04 Try disabling the `more forum toolbar buttons` addon, does that fix the issue?

**Comment by LegoManiac04** [comment]
@WorldLanguages I disabled `more forum toolbar buttons` and I can confirm that it fixes the issue.

**Comment by LegoManiac04** [comment]
If it's still of use, this is everything enabled on that tab:

BBCode source button
Better emojis
Better forum quoter
Confirmations
Copy code button on forums
Customizable navigation bar
Customizable quotes and code blocks on forums
Expandable search bar
Forum search
Forums image uploader
Full areas
High resolution thumbnails
Local timezone on forums
ocular integration
Quote post number
Scratch 2.0 → 3.0
Website dark mode and customizable colors

**Comment by kccuber-scratch** [comment]
Can reproduce on Windows 10 and firefox 96:
![image](https://user-images.githubusercontent.com/92891642/152907909-5bbecca0-bb4f-4e54-98f7-b1401961247c.png)

**Comment by apple502j** [comment]
Can you post console logs (F12, then click Console, then copy-paste the logs) here?

**Comment by Chiroyce1** [comment]
> Can you post console logs (F12, then click Console, then copy-paste the logs) here?

`(!) TypeError: obj is null - cs.js:256:13`

<img width="816" alt="image" src="https://user-images.githubusercontent.com/97374054/152908837-db41b7ab-bc31-4cb6-812e-a72e104ffce5.png">

**Comment by apple502j** [comment]
ah, thx!

**Comment by apple502j** [comment]
Resolved in #4240
