### ISSUE TITLE
Remove unused addon.tab.loadWorker

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4243]

**Comment by apple502j** [comment]
Yep, this was an experimental stuff which I added for... what was that? mediarecorder ffmpeg support? idk

**Comment by Norbiros** [comment]
If it is unused, can we click backspace on this code? _we have backups, so no need for hide it with comments..._

**Comment by mxmou** [comment]
> If it is unused, can we click backspace on this code? _we have backups, so no need for hide it with comments..._

I think that's what this issue is about.
