### ISSUE TITLE
Semicolon on ajax pages 

### ISSUE THREAD

**Issue by Mbrick2** [ScratchAddons/ScratchAddons#4248]
### Description

semicolons show on ../ajax/.. pages

### Reproduction steps

1. enable semicolon glitch
2. go to https://scratch.mit.edu/messages/ajax/friends-activity/?max=1000

### Expected behavior

No semicolon (unless this was intended)

### Actual behavior

Shows a semicolon

### Screenshots

![image](https://user-images.githubusercontent.com/90691415/153157139-8cb83003-cf25-4639-b29f-25b6a4ca3165.png)

### Environment

- Browser: Firefox 97.0b9
- Scratch Addons version: v1.24.3 
- Operating system: macOS 11.6.1

**Comment by mxmou** [comment]
Those pages aren't meant to be visited directly, so I don't think this is a problem.

**Comment by WorldLanguages** [comment]
Yeah, addons aren't made with site-api or ajax paths in mind, and I don't think they should be.
