### ISSUE TITLE
Improve "Disable sprite wobble in sprite pane" addon

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#4249]
### Is your request related to a problem? Please describe.

The disable sprite wobble addon attempts to fix a bug that causes an extra scrollbar to appear when dragging something onto another sprite, making the sprites jump around. It does that by removing the wobble animation entirely. This makes it impossible to know if what you're dragging will end up in the correct sprite until you release the mouse, which shows a green glow around the sprite indicating success.

### Describe the solution you'd like

Fix the bug in a way that doesn't remove functionality by adding `overflow: hidden` to `[class*="sprite-selector_items-wrapper_"]`.

### Describe alternatives you've considered

Open a pull request in scratch-gui with this fix and remove the addon if/when it's accepted.

**Comment by WorldLanguages** [comment]
> Open a pull request in scratch-gui with this fix and remove the addon if/when it's accepted.

If it doesn't exist already, I'd like to see that pull request being created and link to it

**Comment by mxmou** [comment]
> Also, I think some users might have enabled the addon not because of the bug, but because they actually don't like the wobble 🤔

The sprite grows a bit as well, so maybe the addon could remove the wobble but not that?

**Comment by WorldLanguages** [comment]
Feedback on YouTube channel:

> If you enable disable sprite wobble in sprite pane, you may not know which sprite has got the costume if you are trying to drag the costume in the correct sprite

**Comment by RedGuy12** [comment]
With just this addon on: 
![image](https://user-images.githubusercontent.com/61329810/155739324-cc9af838-a540-408e-b102-e46d881c49b9.png)
there is a very slight blue border

if you enable editor dark mode there is a much more noticeable difference, even with "scratch's default colors"
![image](https://user-images.githubusercontent.com/61329810/155739540-9cc0645c-27fe-455c-bbda-31a849325f87.png)

**Comment by mxmou** [comment]
> if you enable editor dark mode there is a much more noticeable difference, even with "scratch's default colors" ![image](https://user-images.githubusercontent.com/61329810/155739540-9cc0645c-27fe-455c-bbda-31a849325f87.png)

That's a bug.
