### ISSUE TITLE
60 FPS addon broken

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#425]
**Describe the bug**

On my chromebook, when I do alt + click, it acts as a right click. I think you might need prevent default.
**To Reproduce**

On a laptop,
1. Go to a project
2. Click on green flag while holding alt.
3. See bug.

**Expected behavior**

It works

ChromeOS

**Comment by MasimbaTheHuman** [comment]
You can hold alt and tap the screen in turbowarp. It should work here too.

**Comment by WorldLanguages** [comment]
@MasimbaTheHuman, I don't think all Chromebooks have touch screens.
