### ISSUE TITLE
Add Documentation For Implementing Scratch Addons in forks of LLK/scratch-gui

### ISSUE THREAD

**Issue by UtterDonkey** [ScratchAddons/ScratchAddons#4259]
Add Documentation For Implementing Scratch Addons in forks of LLK/scratch-gui

**Comment by apple502j** [comment]
If you can fork scratch-gui, it's better to just mod it...

Technically TurboWarp does it, but I don't recommend it. (There are many patches on TW side that allow this)

**Comment by CST1229** [comment]
> If you can fork scratch-gui, it's better to just mod it...

I think that's what they meant.

**Comment by WorldLanguages** [comment]
Within the Scratch Addons project itself, implementing addons in forks of Scratch is an afterthought. You could take a look at [how TurboWarp does it](https://github.com/TurboWarp/scratch-gui/tree/develop/src/addons).

**Comment by UtterDonkey** [comment]
ok, I'll take a look
