### ISSUE TITLE
Project https://scratch.mit.edu/projects/642284992 won't load

### ISSUE THREAD

**Issue by scratchforsccom** [ScratchAddons/ScratchAddons#4261]
### Description

When loading project https://scratch.mit.edu/projects/642284992 in Chrome when ScratchAddons is enabled you get the "something went wrong" error

### Reproduction steps

1. enable Scratch Addons on Chrome
2. load project https://scratch.mit.edu/projects/642284992

### Expected behavior

The project should load normally, as it does in Safari or in Chrome when ScratchAddons is disabled

### Actual behavior

Error "something went wrong"

### Screenshots

None

### Environment

- Browser: Chrome 98.0.4758.80 (x86_64), Safari 14.1.2 (16611.3.10.1.6)
- Scratch Addons version: 1.24.3
- Operating system: MacOS BigSur

### Additional context

None

**Comment by apple502j** [comment]
How much RAM do you have?

**Comment by sfederici** [comment]
> How much RAM do you have?

64GB

**Comment by Norbiros** [comment]
In firefox works normally.

**Comment by sfederici** [comment]
> In firefox works normally

Yes, it does. Even with ScratchAddons enabled

> How much browser have RAM?

How do I know that?

> Try to close all other programs.

Tried. Same result.

> Try this in TurboWarp: https://turbowarp.org/642284992

Tried. Same result.

> Check your computer efficiency while loading project.

While loading 90% of CPU is free. 34GB of RAM are free.

> Are you using Chrome Book?

No, macOS BigSur on a MacBook Pro

**Comment by apple502j** [comment]
Closing. The project is simply too big - it crashes on my poor 8GB RAM laptop without Scratch Addons. I don't think there are many people who can debug such big projects here.

**Comment by scratchforsccom** [comment]
But I don't understand why, with a so large amount of RAM still available, it crashes only when ScratchAddons is enabled. I think this it something that should be investigated.

**Comment by WorldLanguages** [comment]
> But I don't understand why, with a so large amount of RAM still available, it crashes only when ScratchAddons is enabled

There's probably a maximum amount of memory the browser is willing to use for a single tab.
It crashed with Scratch Addons off, so I don't think there's much to be done here. Naturally, enabling addons increases RAM usage of the tab.

**Comment by Norbiros** [comment]
So go to Firefox, then it will work :)

**Comment by Chiroyce1** [comment]
This is probably a Chrome problem since I can load it with Scratch Addons in 16GB RAM.

<img width="984" alt="image" src="https://user-images.githubusercontent.com/97374054/153792516-91f3c390-046e-4dfb-b88f-1d9880b03a66.png">
<img width="402" alt="image" src="https://user-images.githubusercontent.com/97374054/153792546-800a127d-ff27-42b9-befa-7b7e6df37b06.png">

macOS Big Sur and Firefox
