### ISSUE TITLE
my-ocular+scratchr2: ocular statuses can overflow horizontally

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4262]
Likely regressed by #4227

Only happens if the ocular status has a very long word without any spaces.

![image](https://user-images.githubusercontent.com/17484114/153676941-719d6411-5657-47ca-81d9-bb99c71bab99.png)

**Comment by Chiroyce1** [comment]
Adding `word-wrap: break-word;` seems to fix it. Would this be enough?

<img width="430" alt="image" src="https://user-images.githubusercontent.com/97374054/153696365-c6101403-0df7-4772-8095-c043ebe01fc0.png">
