### ISSUE TITLE
"Show full areas" signature settings too complicated

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#427]
We need to balance between customization and being able to understand what the options do
Why are settings even needed for this? Why not a "always show full signature" checkbox? If disabled, there's a scroll bar and a button to expand it. If enabled, it's always expanded.

**Comment by GrahamSH-LLK** [comment]
I'm working on this.

**Comment by WorldLanguages** [comment]
Whoops, haven't seen this (and forgot to close dumb me)
See #447
