### ISSUE TITLE
Non-integer labels on follower graph

### ISSUE THREAD

**Issue by DogCatPuppyLover** [ScratchAddons/ScratchAddons#4270]
### Description

On profiles which have gained or lost very few followers, the labels on their follower graphs include non-integer numbers.

### Reproduction steps

1. Go to someone's profile (for example, [@Hello_world](https://scratch.mit.edu/users/Hello_world/))
2. View the follower graph
3. Read the number labels

### Expected behavior

Numerical labels on follower graphs should be integers only.

### Actual behavior

Non-integer labels are displayed.

### Screenshots

![Screenshot 2022-02-14 at 13-39-07 Scratch - Imagine, Program, Share](https://user-images.githubusercontent.com/79656307/153950829-d0b62da6-1ea6-4d8d-810a-6330195a6452.png)

### Environment

- Browser: Firefox 97
- Scratch Addons version: 1.24.3
- Operating system: Windows 10

**Comment by Norbiros** [comment]
You can fix it, by using:
```
y: {
  precision: 0,
  ticks: {
    callback: function(stepSize) {
      if ( !( stepSize % 1 ) ) {
        return new Intl.NumberFormat().format(Number(stepSize).toFixed(0));
      }
    }
  }
}
```
