### ISSUE TITLE
Blocks from backpack dropped in mouse position

### ISSUE THREAD

**Issue by Falling10fruit** [ScratchAddons/ScratchAddons#4272]
### Is your request related to a problem? Please describe.

I get tired to scroll to the top of the blocks just to drag the one block down to where I want it.

### Describe the solution you'd like

The block will drop in the position of the mouse

### Describe alternatives you've considered

At least appear on the screen instead of off-screen

### Additional context
Helps a lot when working with large amounts of code.

**Comment by mxmou** [comment]
Duplicate of #1559
