### ISSUE TITLE
Create a search bar in the 3.0 pages (when you will scroll down) and make the bar to be something different be customizable!

### ISSUE THREAD

**Issue by WojtekCodesToday** [ScratchAddons/ScratchAddons#4282]
- it default, it will be a search bar
- the bar can be changed for something different
- the bar colour can only be themed with the bottom of the page.

**Comment by WorldLanguages** [comment]
Please provide a mockup so that we can understand what you're suggesting

**Comment by WojtekCodesToday** [comment]
> Please provide a mockup so that we can understand what you're suggesting

I may not know a mockup, but this here i tried (i don't understand JS so it's just a image)

![Polish_20220219_083626878.png](https://user-images.githubusercontent.com/94251112/154791929-ea002d3d-39b1-43ed-b03b-97bd06a1c2ab.png)

Ignore the image name.

**Comment by CST1229** [comment]
What would it search for? If it searches on the page, you could just use your browser's search.

**Comment by WojtekCodesToday** [comment]
> What would it search for? If it searches on the page, you could just use your browser's search.

Well, its search the same way as you use in your top bar in your scratch page.

**Comment by CST1229** [comment]
> > What would it search for? If it searches on the page, you could just use your browser's search.
> 
> Well, its search the same way as you use in your top bar in your scratch page.

Why not just use the navigation bar search?

**Comment by WojtekCodesToday** [comment]
> > > What would it search for? If it searches on the page, you could just use your browser's search.
> > 
> > Well, its search the same way as you use in your top bar in your scratch page.
> 
> Why not just use the navigation bar search?

(not really but it will use the same way as the navigation bar search system)

**Comment by CST1229** [comment]
> > > > What would it search for? If it searches on the page, you could just use your browser's search.
> > > 
> > > 
> > > Well, its search the same way as you use in your top bar in your scratch page.
> > 
> > 
> > Why not just use the navigation bar search?
> 
> (not really but it will use the same way as the navigation bar search system)

I mean, why would you ever use a search bar on the footer when there's already a search bar on on the navigation bar, which is always visible?

**Comment by Chiroyce1** [comment]
> the bar colour can only be themed with the bottom of the page.

Why not change the colour of the search bar in the navigation bar instead of making a new one? That would make more sense imo.

**Comment by Secret-chest** [comment]
> Why not change the colour of the search bar in the navigation bar instead of making a new one? That would make more sense imo.

Why not add it to dark-www?

**Comment by WorldLanguages** [comment]
It makes no sense to have 2 search bars.
