### ISSUE TITLE
Show when user is following you

### ISSUE THREAD

**Issue by itta611** [ScratchAddons/ScratchAddons#4285]
### Is your request related to a problem? Please describe.
In Scratch it's hard to know the user is following you.

### Describe the solution you'd like
If the user following you, it indicate that in the user profile page.

### Describe alternatives you've considered
Or find yourself in the "Following" that the user profile.

**Comment by Norbiros** [comment]
I don't understand. It is very easy, go to this page: https://scratch.mit.edu/users/itta611/followers/ and you can find all people that are following you. 
Things that we can add, is search bar (when you have 500 people, and 5 pages, you need type `Ctr+F` on all 5 pages), or we can add this to `Infinity Scrolling ` add-on...

**Comment by itta611** [comment]
However, it's a hassle to do that every time, and I think it's convenient if you know immediately if someone is following you or not.

**Comment by apple502j** [comment]
I don't think this is feasible.
