### ISSUE TITLE
A box2D extension. (griffpatch extension)

### ISSUE THREAD

**Issue by WojtekCodesToday** [ScratchAddons/ScratchAddons#4286]
When thinking about the debugger extension, we need some fun as well, the easiest for me will be box2D extension for making it happen, and it will replace the share button, with a download button (with a warning that you are using a extension, that doesn't use servers), when added.

**Comment by mxmou** [comment]
How would having the extension on the Scratch website be useful if projects that use it can't be shared either way?

**Comment by Chiroyce1** [comment]
> How would having the extension on the Scratch website be useful if projects that use it can't be shared either way?

Similar to the debugger maybe? If people have SA, those blocks would be shown and they'd function, otherwise they'd be just custom blocks without definitions _(I don't know if hat blocks would work though)_.

**Comment by mxmou** [comment]
> > How would having the extension on the Scratch website be useful if projects that use it can't be shared either way?
> 
> Similar to the debugger maybe? If people have SA, those blocks would be shown and they'd function, otherwise they'd be just custom blocks without definitions _(I don't know if hat blocks would work though)_.

Debugger doesn't change how the project behaves, so non-SA users not being able to use it isn't a problem. Projects probably wouldn't work as expected without this extension.

**Comment by Chiroyce1** [comment]
> Debugger doesn't change how the project behaves, so non-SA users not being able to use it isn't a problem. Projects probably wouldn't work as expected without this extension.

That's true - so this would probably be a better fit in [TurboWarp](https://github.com/TurboWarp/desktop) or some other Scratch mod.

**Comment by WojtekCodesToday** [comment]
I wasn't thinking about the debugger, i was just thinking about a gravity extension (as an Easter egg the you all use as a Konami code)

**Comment by apple502j** [comment]
No.

**Comment by WojtekCodesToday** [comment]
> No.

Ok thank you.

**Comment by CST1229** [comment]
> > Debugger doesn't change how the project behaves, so non-SA users not being able to use it isn't a problem. Projects probably wouldn't work as expected without this extension.
> 
> That's true - so this would probably be a better fit in [TurboWarp](https://github.com/TurboWarp/desktop) or some other Scratch mod.

TurboWarp also tries to be vanilla-compatible (IIRC the non-argument TurboWarp blocks were from a really long time ago when TW wasn't supposed to be vanilla-compatible). Maybe it could be implemented in a mod like adacraft (which is a TurboWarp fork).
