### ISSUE TITLE
"Website dark mode and customizable colors": allow using same color as highlight color for banners

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#4297]
Sometimes the color you set would work for banners too. Why not allowing using the exact same color, same hue and saturation?

**Comment by mxmou** [comment]
The current behavior allows the highlight color and dark colored areas settings to be customized independently.

**Comment by apple502j** [comment]
Don't think this needs to be changed.

**Comment by Secret-chest** [comment]
> The current behavior allows the highlight color and dark colored areas settings to be customized independently.

But you can't change it to exactly whatever you want.

**Comment by mxmou** [comment]
> > The current behavior allows the highlight color and dark colored areas settings to be customized independently.
> 
> But you can't change it to exactly whatever you want.

#4187 is probably a better alternative to this.
