### ISSUE TITLE
[mute-project]: On Mac, command key doesn't work

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#4299]
I can't reproduce this since I don't have a mac, but we would just need to modify this line https://github.com/ScratchAddons/ScratchAddons/blob/master/addons/mute-project/userscript.js#L9

**Comment by WorldLanguages** [comment]
Supporting hotkeys on every platform is painful...

**Comment by Chiroyce1** [comment]
Can replicate on macOS, even the control key doesn't work since CTRL + click on Mac is the equivalent of a right-click.
