### ISSUE TITLE
Bugs with Linkify

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#430]
`more-links` needs some `addon.tab.waitForElement()`s in order to work properly. For example, if you load a project in editor mode, then go to community mode, links in the notes are not clickable. Haven't tested, but if you go to the project in player mode, then go inside, then back "outside", looking at the code (and how Scratch works) it looks like links would also dissapear.

**Comment by Hans5958** [comment]
Come on, #308 exists!

**Comment by WorldLanguages** [comment]
Lol it's getting hard to keep track 😔
