### ISSUE TITLE
Messaging unusable due to "Error: No replies found on comment"

### ISSUE THREAD

**Issue by RokCoder** [ScratchAddons/ScratchAddons#4305]
### Description

Messaging add-on drops to error screen (see screenshot) while retrieving messages. This has been consistent for almost a week. I am able to read messages while they are being retrieved up to the point at which the error occurs. Once this has happened, the error screen replaces the loaded messages.

### Reproduction steps

1. Select messaging tab
2. Wait while messages load

### Expected behavior

It would be preferable to be able to scan through all other messages should this error be encountered (and the message/thread causing the error be omitted)

### Actual behavior

Messages are removed from display and replaced with error message.

### Screenshots

![image](https://user-images.githubusercontent.com/20208339/155118728-c791cd1c-4792-4aa4-b173-6c86b82d8458.png)

### Environment

- Chrome 98.0.4758.102 (Official Build) (64-bit)
- Scratch Addons version: 1.24.3
- Operating system: Windows 10 Pro

**Comment by RedGuy12** [comment]
Fixed in #4295

**Comment by WorldLanguages** [comment]
@RokCoder Please wait until next stable release or download the current state of the repo.
