### ISSUE TITLE
scratchstats addon reports "Wed Dec 31 1969" for all dates

### ISSUE THREAD

**Issue by Oren-Lindsey** [ScratchAddons/ScratchAddons#4310]
### Description
scratchstats addon displays date of every data point as "Wed Dec 31 1969"
I can verify this is not what the api is returning: https://scratchdb.lefty.one/v3/user/graph/datonelefty/followers?range=365&segment=7

### Reproduction steps

1. Visit a users profile
2. Scroll to the stats about them
3. Hover over any data point on the graph

### Expected behavior
Popup should display actual time the data was saved

### Actual behavior
Popup displays "Wed Dec 31 1969"

### Screenshots
<img width="946" alt="Screen Shot 2022-02-22 at 12 53 28 PM" src="https://user-images.githubusercontent.com/67929847/155190672-87e4162a-81e1-4f49-b441-a6b49e2586fb.png">

### Environment
Browser: Chrome 98
SA: [v1.24.3](https://scratchaddons.com/changelog/?utm_source=extension&utm_medium=popup&utm_campaign=v1.24.3)
OS: macOS

- Browser: 
- Scratch Addons version: 
- Operating system: 

### Additional context
none

**Comment by Mbrick2** [comment]
Can reproduce as `Thu Jan 1 01 1970`. Seems to change according to the true date

**Comment by WorldLanguages** [comment]
This issue has been around for weeks, right? It's just that no one noticed it

**Comment by Oren-Lindsey** [comment]
I think so. I remember seeing it before but I didnt make an issue about it
