### ISSUE TITLE
IntelliScratch

### ISSUE THREAD

**Issue by Mbrick2** [ScratchAddons/ScratchAddons#4313]
## Overview
This would be extremely hard but imaging [InteliSence](https://code.visualstudio.com/docs/editor/intellisense) for Scratch. IntelliSense is basically autocomplete but for coding. It can be trained on advance scratch projects project.JSON and maybe even be its own extension. I know this is very complicated but look how useful it would be.

## Mockup

![image](https://user-images.githubusercontent.com/90691415/155291886-c59ce53e-227d-4c98-b437-52072171e59e.png)
![image](https://user-images.githubusercontent.com/90691415/155291849-778163d1-6e74-4a7f-90d5-4171a6237d88.png)

**Comment by apple502j** [comment]
Out of scope for this project.

**Comment by kccuber-scratch** [comment]
> Out of scope for this project.

Yeah we aren't trying to put GitHub Copilot in scratch or something lol
