### ISSUE TITLE
Add a note to to the navbar addon

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#4315]
### Is your request related to a problem? Please describe.

Some people might get confused when an internal navbar link doesn't start with a slash and think the addon is broken.

![image](https://user-images.githubusercontent.com/81489795/155333969-c79ad563-d6c0-462e-9bb1-412630069ff1.png)

### Describe the solution you'd like

Add a note that recommends starting an item with a slash.

### Describe alternatives you've considered

Base URLs that don't start with a slash off the home page, not the current one.

**Comment by apple502j** [comment]
This looks like a bug, not a feature request.
