### ISSUE TITLE
Change minimum Firefox required version to 86 (previously 74)

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4334]
Current minimum FF version is 74 (March 2020).
Unlike chromebook users, an outstanding majority of Firefox users can get the latest version of it easily. So I suggest changing the minimum to Firefox 86 (February 2021).

- `tabs` permission not required when host permissions are already present. We can now remove many `typeof browser` checks in core code ([Firefox 86+](https://blog.mozilla.org/addons/2021/02/09/extensions-in-firefox-86/))
- CSS `min()`, `max()` and `clamp()` can now be used (Firefox 75+)
- `Intl.DateTimeFormat` dateStyle and timeStyle parameter support, already in use by some addons (Firefox 79+)
- `<link rel="preload">` support: already in use by our settings page to load faster (Firefox 85+)

**Comment by Secret-chest** [comment]
`clamp()` sucks. Please don't use it.

**Comment by RedGuy12** [comment]
> `clamp()` sucks. Please don't use it.

something does not suck just if you don't understand it. i don't understand it either tbh, but i have heard that it is very useful.

**Comment by Secret-chest** [comment]
> > `clamp()` sucks. Please don't use it.
> 
> something does not suck just if you don't understand it. i don't understand it either tbh, but i have heard that it is very useful.

@RedGuy12 For what? Making "responsive" font sizes? Text shouldn't resize with the window.
