### ISSUE TITLE
Infinite cursor movement in the editor

### ISSUE THREAD

**Issue by RIMOPA** [ScratchAddons/ScratchAddons#4356]
### Is your request related to a problem? Please describe.

It's that annoying when I browse in the code area, the cursor stops at the end of the screen.

### Describe the solution you'd like

When You are browsing in the code area (clicking the background and moving), if the cursor hit the end of the screen, appears/is teleported to the other side of the screen.

**Comment by mxmou** [comment]
It isn't possible to control the mouse cursor.
