### ISSUE TITLE
Get raw json from export file.

### ISSUE THREAD

**Issue by BlueFalconHD** [ScratchAddons/ScratchAddons#4360]
### Is your request related to a problem? Please describe.

My friend and I are collaborating on a very messy scratch project. We use scratch addons to keep it organized. The problem is my computer (managed by my school) doesn't let extensions download files.

### Describe the solution you'd like

I would love a way to get the raw json of the config, so I can email it to my friend or something like that.

### Describe alternatives you've considered

A way to save configs to the scratch addons website, so you can easily share a config with a friend.

**Comment by Mbrick2** [comment]
Related #3446

**Comment by WorldLanguages** [comment]
> The problem is my computer (managed by my school) doesn't let extensions download files.

Interesting

**Comment by WorldLanguages** [comment]
I think we could add a "show settings as text" button that opens a data URI or blob URI in a new tab. Then you could copy it from there. @Chiroyce1 Want to send a PR?

**Comment by TheColaber** [comment]
There is a closed pr that implemented this (#3446). Also why Chiroyce?

**Comment by Chiroyce1** [comment]
> There is a closed pr that implemented this (#3446). Also why Chiroyce?

That PR's code directly copied it to the clipboard, WL is planning to letting the user copy it manually. And they specifically said Chiroyce since I [suggested that idea](https://github.com/ScratchAddons/ScratchAddons/pull/3446#issuecomment-1059757216).

> I think we could add a "show settings as text" button that opens a data URI or blob URI in a new tab. Then you could copy it from there. @Chiroyce1 Want to send a PR?

Sure, I'll try to get a draft up soon.
