### ISSUE TITLE
Microsoft Edge Addons store public release

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4362]
Meta issue

**Comment by Dhuls-Scratch** [comment]
Is there an advantage over the Chrome Web Store?

Not opposed to this, just wondering?

**Comment by WorldLanguages** [comment]
> Is there an advantage over the Chrome Web Store?

There isn't. Some users just expect us to be in the Edge store for some reason.
I doubt we will ever get into more stores. Opera has its own store, but users are very aware that the Chrome Web Store works on Opera. Brave might get its own store at some point, but users will still know that Chrome extensions work.

**Comment by sakhiy2010** [comment]
Can you release Scratch Addons in Microsoft Edge?

**Comment by Dhuls-Scratch** [comment]
> Can you release Scratch Addons in Microsoft Edge?

That's the point of this issue.
Judging by the milestone, probably when 1.25 releases

**Comment by sakhiy2010** [comment]
I can’t wait!

**Comment by mxmou** [comment]
> > Is there an advantage over the Chrome Web Store?
> 
> There isn't. Some users just expect us to be in the Edge store for some reason.

Installing extensions from the Chrome Web Store is disabled by default on Edge, so that might be why.

**Comment by sakhiy2010** [comment]
Yes
