### ISSUE TITLE
503 error is considered a scratchr2 page

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#4364]
### Description

The [maintenance](https://scratch.mit.edu/cdn/maintenance.html) and [trouble](https://scratch.mit.edu/cdn/trouble.html) pages appear when Scratch isn't available, with a 503 error code. When that happens, userstyles for scratchr2 pages run. Ideally, neither `scratchWWWNoProject` nor `isNotScratchWWW` would match those pages because they're static pages.

### Reproduction steps

Open the pages directly or open Scratch when it's down.

### Expected behavior

URLs under `/cdn/` (for testing) and the 503 error code would be excluded from `isNotScratchWWW`.

### Actual behavior

`isNotScratchWWW` matches these pages.

**Comment by WorldLanguages** [comment]
So this is an issue with the regexes, right? At first I thought this was about `addon.tab.clientVersion`

**Comment by WorldLanguages** [comment]
Or wait, or are you saying that the page's status code should affect the userstyles that are injected?
Right now, if the page returns a 503, the URL is set to `https://scratch.mit.edu/503/` and that is tested against the regexes.

**Comment by mxmou** [comment]
> So this is an issue with the regexes, right? At first I thought this was about `addon.tab.clientVersion`

Yes, it's about userscript/userstyle matches, specifically `isNotScratchWWW`, which shouldn't match 3.0-styled error pages.

**Comment by apple502j** [comment]
@mxmou I think some 503s use the r2 style and some use www style, so this might not be easy to do.

**Comment by WorldLanguages** [comment]
Ohh right, that makes sense.
Unless we find `/503_r2/` and `/503_www/` pseudo URLs to be worth it (but probably not)

**Comment by apple502j** [comment]
My opinion is "who cares", it should only appear during downtime...

**Comment by mxmou** [comment]
> My opinion is "who cares", it should only appear during downtime...

scratchr2 changes the background of buttons to blue, and because the text on the download button is also blue, the entire button becomes invisible. That's why a way to prevent the addon from running on that page is necessary.

**Comment by apple502j** [comment]
@mxmou Hmm.

From what I can tell, 1) www pages always get www styled 503, and 2) r2 pages can have both www (real outage) and r2 (bug in forums etc) styles.

Would it be fine if we ignore r2-style 503? No addons currently get enabled after checking if a page is r2 or www styled. (This might be fixable with a CSS selectors, though.)

For now, I'm thinking:

- It excludes 503 from either of the styles (www and r2) by default
- If page returns 503, it'll use a special URL like we do with r2 404 (www 404 is not real)
- Whether a page is www-503 or r2-503 is none of the core's business, CSS should figure it out

**Comment by mxmou** [comment]
> For now, I'm thinking:
> 
> * It excludes 503 from either of the styles (www and r2) by default
> * If page returns 503, it'll use a special URL like we do with r2 404 (www 404 is not real)
> * Whether a page is www-503 or r2-503 is none of the core's business, CSS should figure it out

That would be fine.
