### ISSUE TITLE
Hide Discuss Button

### ISSUE THREAD

**Issue by sakhiy2010** [ScratchAddons/ScratchAddons#4368]
I hope this New Suggestion published! 
That is so many buttons in that bar. I am request Hide Discuss Button because that button is rarely clicked by me.

**Comment by sakhiy2010** [comment]
That is so many buttons in that bar. I am request this because that button is rarely clicked by me.

**Comment by Chiroyce1** [comment]
I'm pretty sure it's disabled by default, if you want to hide it, go to the settings, then search for "Discuss" and then press the "x" button near the card that has `/discuss` written on it

<img width="507" alt="image" src="https://user-images.githubusercontent.com/97374054/156972579-2614151e-ce49-4587-b9aa-b7bdd9d4f903.png">

**Comment by sakhiy2010** [comment]
Ok thanks.
