### ISSUE TITLE
Show the Profile Button

### ISSUE THREAD

**Issue by sakhiy2010** [ScratchAddons/ScratchAddons#4369]
Show the profile button without having to click the username icon.

**Comment by mxmou** [comment]
It's already possible to add a link to your profile to the navigation bar using the "customizable navigation bar" addon. It could still be made easier to do by adding it to the dropdown menu next to the "+" button.

**Comment by Chiroyce1** [comment]
Video tutorial on how to add a custom link via the `Customizable navigation bar` addon

https://user-images.githubusercontent.com/97374054/156995076-905917f1-0b3d-420d-9c00-3caf63c09cb5.mov

**Comment by sakhiy2010** [comment]
> It's already possible to add a link to your profile to the navigation bar using the "customizable navigation bar" addon. It could still be made easier to do by adding it to the dropdown menu next to the "+" button.

Ok thanks
