### ISSUE TITLE
Hide Ungroup Button

### ISSUE THREAD

**Issue by sakhiy2010** [ScratchAddons/ScratchAddons#4371]
Because that button usually accidentally clicked by me, so the sprite is Ungrouped.

**Comment by sakhiy2010** [comment]
This
![4728356A-31B9-4D54-A7CE-85BD21161A98](https://user-images.githubusercontent.com/100205903/157041981-a53b2177-7f54-4539-88f6-c3c6c87cfd1e.jpeg)

**Comment by Dhuls-Scratch** [comment]
CTRL+Z (or CMD+Z on Mac I think)

**Comment by WorldLanguages** [comment]
Yeah, just undo if you misclick.

**Comment by Chiroyce1** [comment]
Or if you're on a device without a physical keyboard, just click this button
![image](https://user-images.githubusercontent.com/97374054/157182072-02098413-487a-4c48-a339-b20cc0955a79.png)
