### ISSUE TITLE
Forum Scratchblocks Injection

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#438]
This would be an extension that injected the new scratchblocks into the forums.

**Comment by BoomerScratch** [comment]
I'm not sure how to do this. Ask @tjvr?

**Comment by mxmou** [comment]
Related: https://github.com/ScratchAddons/ScratchAddons/issues/240#issuecomment-700482585

**Comment by WorldLanguages** [comment]
Anyone want to take this?

**Comment by GrahamSH-LLK** [comment]
Maybe. It would need to:
- Run at document start
- Block requests to menu.js, scratchblocks.js, and translate.js.
- Replace those files with the current versions
- Change the calls to "scratchblocks.renderMatching" so that they included "style:"scratch3"

**Comment by ZenithRogue** [comment]
You can also replace `scratchblocks.js` with `https://s3blocks.github.io/js/s3blocks.min.js`, as it is directly compatible with the existing forums
![image](https://user-images.githubusercontent.com/11393734/96348215-d1f5ee80-106c-11eb-8f77-9709d1f4a3ee.png)

**Comment by mxmou** [comment]
@WorldLanguages If I understand correctly, #439 solves the problem described in the comment I linked earlier (running before `$(document).ready`), so I might try to do this again now.

**Comment by GrahamSH-LLK** [comment]
I personally like plain scratchblocks/scratchblocks better.

**Comment by ZenithRogue** [comment]
Well, it is an _addon_, so you don't have to have it enabled

**Comment by GrahamSH-LLK** [comment]
I mean as opposed to s3blocks.

**Comment by mxmou** [comment]
> I personally like plain scratchblocks/scratchblocks better.

It has a bug - there is a lot of padding below the last script - which makes it unusable in the scratchblocks menu.

**Comment by GrahamSH-LLK** [comment]
I think I know how to do this! We can fetch the unparsed blocks by fetching the topic (pagination is actually handled server side!), then we can extract the text, and inject it into the current document. Then we can run new scratch blocks on the parsed text. The menus already have unparsed as an attribute!

**Comment by mxmou** [comment]
> I think I know how to do this! We can fetch the unparsed blocks by fetching the topic (pagination is actually handled server side!), then we can extract the text, and inject it into the current document. Then we can run new scratch blocks on the parsed text. The menus already have unparsed as an attribute!

Unfortunately this probably isn't a good implementation. For forum users page load speed is very important because we navigate between different topics a lot, and this would slow it down.

It would work though. Maybe we could implement the addon this way with a warning explaining that it makes topics load slower until there is a better solution (maybe a way for addons to access the `declarativeNetRequest` API).

**Comment by GrahamSH-LLK** [comment]
> > I think I know how to do this! We can fetch the unparsed blocks by fetching the topic (pagination is actually handled server side!), then we can extract the text, and inject it into the current document. Then we can run new scratch blocks on the parsed text. The menus already have unparsed as an attribute!
> 
> Unfortunately this probably isn't a good implementation. For forum users page load speed is very important because we navigate between different topics a lot, and this would slow it down.
> 
> It would work though. Maybe we could implement the addon this way with a warning explaining that it makes topics load slower until there is a better solution (maybe a way for addons to access the `declarativeNetRequest` API).

Addons can access webrequest currently (persistent scripts)? (and declarativeNetRequest if it was implemented)

**Comment by mxmou** [comment]
> Addons can access webrequest currently (persistent scripts)? (and declarativeNetRequest if it was implemented)

Would it be possible to replace `scratchblocks.js` with a modified version that would use `style: "scratch3"` by default?

**Comment by GrahamSH-LLK** [comment]
> > Addons can access webrequest currently (persistent scripts)? (and declarativeNetRequest if it was implemented)
> 
> Would it be possible to replace `scratchblocks.js` with a modified version that would use `style: "scratch3"` by default?

Possibly. We can also try to get an official build that uses it by default (tjvr seems to be active again)

**Comment by RedGuy12** [comment]
https://github.com/ScratchAddons/ScratchAddons/pull/2083#issuecomment-813654882
> Please do not ship another copy of scratchblocks.

---

Also the official build no longer has bugs related to padding.
