### ISSUE TITLE
Firefox runs content scripts in about:blank iframes (dark mode bugs)

### ISSUE THREAD

**Issue by Chiroyce1** [ScratchAddons/ScratchAddons#4380]
### Reproduction steps

1. Make sure the `Website dark mode and customizable colors` addon is enabled.
2. Go [here](https://scratch.mit.edu/contact-us/).
3. Scroll all the way down, and click on `Get Help`.
4. Click on `Contact Us` in the pop-up that appears on the right.

### Expected behavior

Textboxes in the pop-up that appears on the right should be consistent.

### Actual behavior

The pop-up that appears on the right should is not dark themed, textboxes are light the text is dark, except for one textbox (the description).

### Screenshots

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/97374054/157419253-144c2670-ebec-4236-b9b3-a56d5b171969.png">

### Environment

Firefox 98, Scratch Addons 1.24.3

**Comment by apple502j** [comment]
The popup is not part of the website.

**Comment by Chiroyce1** [comment]
Oops, forgot about that. But still, SA interferes with it. When the addon is off, it looks like this
<img width="411" alt="image" src="https://user-images.githubusercontent.com/97374054/157446430-49921caa-f544-4a10-802d-d3899060e5a4.png">

when it's on, it looks like this
<img width="403" alt="image" src="https://user-images.githubusercontent.com/97374054/157446498-7fc4098f-7d2a-403f-a8e2-bae345852c22.png">

**Comment by Chiroyce1** [comment]
@Hans5958 also could you remove the `wontfix` label since you opened this?

**Comment by apple502j** [comment]
Hm, so it is embedded with srcdoc'd iframe, so we could technically do it. (Not sure how to apply the styles to such iframes, though.)

**Comment by mxmou** [comment]
The contact us popup uses a different color scheme than the rest of the website, so I don't think it should be affected by this addon. The bug here is that the inputs are inconsistent (one of them is dark).

**Comment by Chiroyce1** [comment]
hmm... can you repro on a Chromium based browser?

**Comment by mxmou** [comment]
> hmm... can you repro on a Chromium based browser?

I tried on Edge and the textarea had a white background as expected. It was dark on Firefox.

**Comment by Tacodude7729** [comment]
Dark mode also messes with the help articles, making them very hard to read.
![image](https://user-images.githubusercontent.com/27910867/197322937-769f0b47-c787-4254-b2c9-052f3dcbefa8.png)

**Comment by mxmou** [comment]
Firefox apparently runs content scripts in iframes without a `src` attribute. I'm not sure how we could prevent that because `location.href` returns the URL of the parent window.

**Comment by WorldLanguages** [comment]
> Firefox apparently runs content scripts in iframes without a `src` attribute.

Huh, Firefox does that, but not Chrome?

**Comment by WorldLanguages** [comment]
Isn't this what `match_about_blank` is for? See the docs in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts

**Comment by mxmou** [comment]
> Isn't this what `match_about_blank` is for? See the docs in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts

Adding `"match_about_blank": false` doesn't fix the bug. If I understand the documentation correctly, it's actually meant to be false by default.

**Comment by WorldLanguages** [comment]
> If I understand the documentation correctly, it's actually meant to be false by default.

Agreed.
I'll investigate what we can do about this. Clearly, our extension content scripts shouldn't be running inside iframes without a src.

**Comment by RedGuy12** [comment]
> Firefox apparently runs content scripts in iframes without a `src` attribute. I'm not sure how we could prevent that because `location.href` returns the URL of the parent window.

would checking if `window.parent === window` work?

**Comment by mxmou** [comment]
> > Firefox apparently runs content scripts in iframes without a `src` attribute. I'm not sure how we could prevent that because `location.href` returns the URL of the parent window.
> 
> would checking if `window.parent === window` work?

That would break embeds (specifically the live featured project).

**Comment by WorldLanguages** [comment]
This appears to be a difference between how Chrome and Firefox handle iframes that don't have an "src" attribute (which is different from `<iframe src></iframe>` and `<iframe src=""></iframe>`!)
Here Scratch uses `<iframe></iframe>`

**Comment by WorldLanguages** [comment]
I wonder if browsers are following the HTML spec here... I don't know why there's a difference between "no src attribute" and "empty src attribute" in everyday browsers. The spec doesn't appear to make a distinction

![image](https://user-images.githubusercontent.com/17484114/205417737-3af25059-6abd-4fac-8ddf-cb0248bca354.png)

(https://html.spec.whatwg.org/multipage/iframe-embed-object.html)

**Comment by WorldLanguages** [comment]
Apparently browsers don't follow the spec, but we can still fix the issue easily

**Comment by WorldLanguages** [comment]
> Hm, so it is embedded with srcdoc'd iframe

Oh, maybe I just missed the fact the iframe had a srcdoc.
