### ISSUE TITLE
April fools ideas?

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4392]
Open to ideas. We should also see what the ST is planning.

Also, we should probably delete the dango-rain addon. Some users still have it enabled for some reason.

**Comment by lisa-wolfgang** [comment]
Debut the project-title-generator addon?

**Comment by WorldLanguages** [comment]
@lisa-wolfgang Ideally, it shouldn't be an editor addon, to avoid breaking the editor accidentally (unlikely) and also because website addon easter eggs probably get noticed more.

**Comment by RIMOPA** [comment]
A Scratch Addons section in the footer
![image](https://user-images.githubusercontent.com/97112832/157990005-0d49154e-289d-421b-b626-5694e8b9804d.png)

**Comment by kccuber-scratch** [comment]
make everyone look like they're ST members and can "ban" and "alert" and "remove comments" but it actually does nothing.

**Comment by webdev03** [comment]
If About Me contains "quack" play [The Duck Song](https://www.youtube.com/watch?v=MtN1YnoL46Q) audio

**Comment by Samq64** [comment]
Turn featured projects into a rickrolls.

**Comment by webdev03** [comment]
> Maybe turn featured projects into rickroll gifs? (Probably a bad idea)

I once made an Apple Shortcut to do that but for all images.

**Comment by RedGuy12** [comment]
> Also, we should probably delete the dango-rain addon. Some users still have it enabled for some reason.

NO NO NO

Wl it's still a good meme and we can't have the Easter eggs be completely empty




> We should also see what the ST is planning.

Looks like they are returning cat blocks and semicolon, and making a retro mode that adds a bunch of css filters



> If About Me contains "quack" play [The Duck Song](https://www.youtube.com/watch?v=MtN1YnoL46Q) audio

That'd be kinda annoying, especially if they can't stop it



> make everyone look like they're ST members and can "ban" and "alert" and "remove comments" but it actually does nothing.

rickrolls you



> Ideally, it shouldn't be an editor addon, to avoid breaking the editor accidentally (unlikely)

How

> and also because website addon easter eggs probably get noticed more.

I doubt that



> A Scratch Addons section in the footer ![image](https://user-images.githubusercontent.com/97112832/157990005-0d49154e-289d-421b-b626-5694e8b9804d.png)

How is that an Easter egg

**Comment by webdev03** [comment]
Ban page when first loading scratch.
Ban message:
```Sorry but apparently you're too good at Scratch coding.```
But after reloading it's gone.

**Comment by Secret-chest** [comment]
Turn all thumbnails and profile pictures to rickroll gifs

**Comment by Chiroyce1** [comment]
Make it seem like griffpatch commented on their profile and the comment should be 
> Hey there! I featured you in my new video! `{link-to-a-real-youtube-video-by-griffpatch}`

When the user clicks the link, call `e.preventDefault();` to cancel the click, and then add the rickroll video as an embed directly to the page. Also include a message like `This is an April Fools prank by Scratch Addons` so that we don't confuse the user 😆

**Comment by jeffalo** [comment]
Considering how many people use SA, doing community driven easter egg things might be interesting (like last year's dango rain via bio). They spread quick and are pretty funny. Something complex could be cool, maybe numbers in a bio simulate gravity on certain elements or something. I don't know.

Also, perhaps we can mimic one of Reddit's April Fools pranks, "the button" is interesting, but definitely with a longer timeout (1h?)

**Comment by CST1229** [comment]
Also, here's what the ST is planning: https://github.com/LLK/scratch-gui/compare/develop...hotfix/totally-normal-2022

**Comment by Chiroyce1** [comment]
> They spread quick and are pretty funny. Something complex could be cool, maybe numbers in a bio simulate gravity on certain elements or something. I don't know.

+1, I don't think majority of the suggestions in the topic (including mine) would be as popular as the dango rain one, it's easy to use, can be modified by the user, and quite fun. Something similar would definitely be better for this year.

**Comment by ilbailba** [comment]
Add-ons with cat hats. Let's have cats like Scratch's April Fools' joke at the top left of the plugins on the plugin settings page. I think it would be nice.

**Comment by Mbrick2** [comment]
#4120

**Comment by Mbrick2** [comment]
turn the word scratch into gobo and change the logo to gobo

**Comment by retronbv** [comment]
“editor collaboration”

**Comment by Samq64** [comment]
> Make it seem like griffpatch commented on their profile and the comment should be
> 
> > Hey there! I featured you in my new video! `{link-to-a-real-youtube-video-by-griffpatch}`
> 
> When the user clicks the link, call `e.preventDefault();` to cancel the click, and then add the rickroll video as an embed directly to the page. Also include a message like `This is an April Fools prank by Scratch Addons` so that we don't confuse the user 😆

Or just a griffpatch is following you message.

**Comment by WorldLanguages** [comment]
> If About Me contains "quack" play [The Duck Song](https://www.youtube.com/watch?v=MtN1YnoL46Q) audio

> Maybe turn featured projects into rickroll gifs? (Probably a bad idea)

Copyright issues

> Ban page when first loading scratch.

> Make it seem like griffpatch commented on their profile

> Or just a griffpatch is following you message.

Too malicious :P

**Comment by CST1229** [comment]
Appel blocks (cap blocks but Appel)

**Comment by Norbiros** [comment]
Replace "Scratch" word with another on all websites, or something like that?

**Comment by webdev03** [comment]
> Replace "Scratch" word with another on all websites, or something like that? And please, **DON'T REMOVE DANGO!!!** 🍡 🍡 🍡

SA only has access to scratch.mit.edu and subdomain pages.

**Comment by Norbiros** [comment]
By websites i meant, all subdomains.... Sorry for that

**Comment by rgantzosonscratch** [comment]
Idea: pressing the Scratch logo (in the top left corner) will take you to a random profile (or project).

**Comment by LES-11** [comment]
Flip a whole bunch on things on the website upside down like the ❤️ button, pfp, emoji’s etc. 
Also I like jeffalo’s idea of a community driven joke 
Lastly please keep dango rain


(I’ll see if I can think of anything else)

**Comment by Chiroyce1** [comment]
> By websites i meant, all subdomains.... Sorry for that

But most users only use the `scratch.mit.edu` domain, uploads or cdn2 is only requested in the background.

**Comment by webdev03** [comment]
> Idea: pressing the Scratch logo (in the top left corner) will take you to a random profile (or project).

Random project is possible, random profile would be hard, maybe using the all-data endpoint of SUI api.

**Comment by rgantzosonscratch** [comment]
well, it would still be difficult to see if a project was shared. what i
was thinking was you could use scratchstats or something and pick a random
user by leaderboard.

**Comment by LES-11** [comment]
Preload an animation of a scratchcat rickroll when you create a new project

**Comment by Secret-chest** [comment]
> turn the word scratch into gobo and change the logo to gobo

this

**Comment by Secret-chest** [comment]
> Preload an animation of a scratchcat rickroll when you create a new project

also this

**Comment by Wjplatformer** [comment]
when a project is shared, have an animation of a rocket launching on the whole page (like how dango works), and add audio :). Somewhat like saying it is `launched`.

**Comment by Mbrick2** [comment]
[This is what the ST is doing](llk.github.io/hotfix/totally-normal-2022)

**Comment by Chiroyce1** [comment]
> [This is what the ST is doing](https://llk.github.io/scratch-gui/hotfix/totally-normal-2022/)

You got _[ninja'd by 23 hours](https://github.com/ScratchAddons/ScratchAddons/issues/4392#issuecomment-1065840085)_

**Comment by Hans5958** [comment]
> Copyright issues

Linking/embedding a media doesn't consistute copyright, eh?

**Comment by jeffalo** [comment]
> > Copyright issues
> 
> Linking/embedding a media doesn't consistute copyright, eh?

[citation needed]

**Comment by Hans5958** [comment]
I don't know. That's what media piracy sites does.

"We don't host copyrighted content, we only embed them from available sources"

**Comment by rgantzosonscratch** [comment]
You might be able to get away with it if you just use the beat if a rickroll but have Scratchcat do it in a squeaky voice.

**Comment by RedGuy12** [comment]
> Ban page when first loading scratch. Ban message: `Sorry but apparently you're too good at Scratch coding.` But after reloading it's gone.

Too malicious 



> Turn all thumbnails and profile pictures to rickroll gifs

Removes functionality



> Also, here's what the ST is planning: [LLK/scratch-gui@develop...hotfix/totally-normal-2022](https://github.com/LLK/scratch-gui/compare/develop...hotfix/totally-normal-2022)

Not including website tho





> “editor collaboration”

See but blocklive actually exists now



> SA only has access to scratch.mit.edu and subdomain pages.

Only some subdomains, see manifest



> Idea: pressing the Scratch logo (in the top left corner) will take you to a random profile (or project).

We don't have any api or anything for that. Random numbers don't guarantee it's shared. And there are more shared boring and useless projects than you think.

**Comment by FunCode11** [comment]
Make a tutorial called, "Hmm, I don't know what the tutorial is???". The thumbnail will look so real but the video is a rickroll.

**Comment by apple502j** [comment]
Disable all editor addons (yes, this is serious, and we'll be doing probably)

**Comment by ilbailba** [comment]
> Disable all editor addons (yes, this is serious, and we'll be doing probably)

I think it might

**Comment by Samq64** [comment]
> Disable all editor addons (yes, this is serious, and we'll be doing probably)

Why not just the ones that are effected?

**Comment by CST1229** [comment]
Scratch Addons section in the footer that has some fun stuff buttons like temporary dango rain and potato swarms.

**Comment by Mbrick2** [comment]
> See but blocklive actually exists now

Whats blocklive?

**Comment by CST1229** [comment]
> > See but blocklive actually exists now
> 
> Whats blocklive?

https://chrome.google.com/webstore/detail/blocklive-scratch-realtim/gelkmljpoacdjkjkcfekkmgkpnmeomlk

**Comment by Mbrick2** [comment]
Dango on comments with the word dango

> https://chrome.google.com/webstore/detail/blocklive-scratch-realtim/gelkmljpoacdjkjkcfekkmgkpnmeomlk

No firefox?

**Comment by CST1229** [comment]
> [chrome.google.com/webstore/detail/blocklive-scratch-realtim/gelkmljpoacdjkjkcfekkmgkpnmeomlk](https://chrome.google.com/webstore/detail/blocklive-scratch-realtim/gelkmljpoacdjkjkcfekkmgkpnmeomlk)
> 
> No firefox?

I don't think there's a Firefox port yet.

**Comment by TechStudent11** [comment]
> Make it seem like griffpatch commented on their profile and the comment should be
> 
> > Hey there! I featured you in my new video! `{link-to-a-real-youtube-video-by-griffpatch}`
> 
> When the user clicks the link, call `e.preventDefault();` to cancel the click, and then add the rickroll video as an embed directly to the page. Also include a message like `This is an April Fools prank by Scratch Addons` so that we don't confuse the user 😆

This

**Comment by easrng** [comment]
To play a rickroll you can just ```js
const rickroll=new Audio("https://invidious-us.kavin.rocks/latest_version?id=dQw4w9WgXcQ&itag=18&local=true");

// some time later, once you actually want to play it (this must be in response to a user interaction)
rickroll.play()
```

**Comment by Cool-Scratcher** [comment]
Maybe an April Fool's fake update video from me showcasing all the memes and stuff you guys end up making? That would be funny.

I could also insert a bunch of inside jokes and references in the video, so idk lol

**Comment by Chameleon-Coder** [comment]
> Considering how many people use SA, doing community driven easter egg things might be interesting (like last year's dango rain via bio). They spread quick and are pretty funny. Something complex could be cool, maybe numbers in a bio simulate gravity on certain elements or something. I don't know.
> 
> Also, perhaps we can mimic one of Reddit's April Fools pranks, "the button" is interesting, but definitely with a longer timeout (1h?)

What's "the button?" I don't use Reddit.

**Comment by xAspirus** [comment]
Send user's session token to griffpatch's email id

**Comment by RedGuy12** [comment]
> Maybe an April Fool's fake update video from me showcasing all the memes and stuff you guys end up making? That would be funny.
> 
> I could also insert a bunch of inside jokes and references in the video, so idk lol

*c o n e s*

**Comment by CST1229** [comment]
> Send user's session token to griffpatch's email id

Lol no

**Comment by CubeyTheCube** [comment]
> 

This is actually a decent idea, Reddit did this once if I remember correctly. It'd be really funny to see the way kids react to this sort of thing.

**Comment by webdev03** [comment]
Search "do a barrel roll" in the projects search makes the page spin like google

**Comment by Chiroyce1** [comment]
Whenever you click the follow button on a users profile, run this
```js
document.body.style.transition = 'transform 3s'
document.body.style.transform = 'rotate(360deg)' // idk if this'll work on all browsers (works on firefox)
```
and then follow the user

**Comment by kccuber-scratch** [comment]
> make everyone look like they're ST members and can "ban" and "alert" and "remove comments" but it actually does nothing.

ok maybe instead of doing nothing it can make fake alerts from the ST like this one:
![image](https://user-images.githubusercontent.com/92891642/159127604-b8f96e87-6ab0-4a10-bf6a-d6f6fb3f3870.png)

**Comment by CST1229** [comment]
Maybe add the Sinhala characters like `ඞ` that are sometimes deemed suspicious by certain people to the emoji picker. (i'm somewhat expecting this to get a no but maybe)

**Comment by TheColaber** [comment]
Why don't we do the dango thing we did last year... Except potato 🥔. That's a current meme in the disco server.

**Comment by Chiroyce1** [comment]
> 

the addon's name `Potato Rain` sounds really weird lol

**Comment by WorldLanguages** [comment]
> Why don't we do the dango thing we did last year... Except potato 🥔. That's a current meme in the disco server.

Best idea so far :P

**Comment by Norbiros** [comment]
Can we make it works on all pages, not only profile's?

**Comment by kccuber-scratch** [comment]
> Why don't we do the dango thing we did last year... Except potato 🥔. That's a current meme in the disco server.

no... how about lemonoid rain 🍋 it would make griffpatch happy

**Comment by Secret-chest** [comment]
Turn all thumbnails to rickroll gifs when hovered

**Comment by lisa-wolfgang** [comment]
Potato rain is too unoriginal. Let's do a potato farming minigame or something.

**Comment by WorldLanguages** [comment]
I'll be pretty busy making sure addons don't crash the editor (see #4431) so what we do for April Fools boils down to:
1. Nothing, maybe
2. dango-rain again
3. Something small that users will notice, without copyright issues (no rickrolling, not having to type a specific term on search bar, no "griffpatch followed you" trolling, no unexpected audio)

**Comment by RIMOPA** [comment]
Snake in profiles backgrounds?

**Comment by retronbv** [comment]
> Why don't we do the dango thing we did last year... Except potato 🥔. That's a current meme in the disco server.

IT IS NOT A MEME. IT IS A WAY OF LIFE

**Comment by WorldLanguages** [comment]
Scratch Avocados? See PR: #4436

**Comment by Wjplatformer** [comment]
happy April Fools' Day everyone >:)
