### ISSUE TITLE
Set a thumbnail button is not showed

### ISSUE THREAD

**Issue by Miala-python** [ScratchAddons/ScratchAddons#4400]
Hello, I have a little problem:
The button to set a thumbnail does not appear ! 

Can you make something ? Thank you !

--- Video for show the problem ---
[![Youtube Video Tumbnail](https://i9.ytimg.com/vi_webp/fBt1t-GA6ls/mqdefault.webp?v=622dc459&sqp=CKSIt5EG&rs=AOn4CLDgDJXpAsGL6XLHd_nFJj2P6_EhHA)](https://www.youtube.com/embed/fBt1t-GA6ls)

--- Versions ---
Scratch Addons: 1.24.3
Chrome: 99.0.4844.51 (Build officiel) (64 bits) 
OS: Ubuntu 20.04

**Comment by mxmou** [comment]
The button is on the project page, below the Notes and Credits:
![image](https://user-images.githubusercontent.com/51849865/158056101-9b196d25-5902-4cb5-ad04-dd32af74e3ff.png)

**Comment by Miala-python** [comment]
OK, thank you very much !
