### ISSUE TITLE
Discussion Forums: Discussion Fourms footer doesn't align with hovering footer

### ISSUE THREAD

**Issue by Mwalters75** [ScratchAddons/ScratchAddons#4407]
I forget the addon name for that, maybe [`2.0 -> 3.0`](https://github.com/ScratchAddons/ScratchAddons/issues/4407#issuecomment-1067018302), it does affect the Discussion Fourms.

**Comment by Chiroyce1** [comment]
Are you talking about the `2.0 -> 3.0` addon? And do you mind sharing a screenshot of the problem?

**Comment by Mwalters75** [comment]
> Are you talking about the `2.0 -> 3.0` addon? And do you mind sharing a screenshot of the problem?

Yes, and:

![image](https://user-images.githubusercontent.com/67456566/158228764-f3830b40-744d-4abf-90ce-41ba9f6bcc31.png)

**Comment by mxmou** [comment]
What exactly is the bug? "Scratch Family" not being right-aligned?

**Comment by Mwalters75** [comment]
> What exactly is the bug? "Scratch Family" not being right-aligned?

On the bottom, the top footer is supposed to be _in_ the pop-up footer, not outside.

**Comment by mxmou** [comment]
I'm not sure if that would make sense: without 2.0 → 3.0, it isn't part of the footer
![image](https://user-images.githubusercontent.com/51849865/158320543-aa5383c8-d17a-4de7-b084-ee0616faa501.png)
and I don't think infinite scrolling should behave differently if other addons are enabled.
