### ISSUE TITLE
Debugger addon doesn't work on "wait" and sound blocks

### ISSUE THREAD

**Issue by stefanofederici** [ScratchAddons/ScratchAddons#4418]
### Description

When you step a wait block (such as "wait until" or a "play until" block) the debugger gets stuck. When you step a "play" block Scratch doesn't play the sound.

### Reproduction steps

Try the debugger on the attached project 
[staToccandoSprite.sb3.zip](https://github.com/ScratchAddons/ScratchAddons/files/8268685/staToccandoSprite.sb3.zip)

### Expected behavior

The debugger goes back to the "go to" block when the condition in the "wait until" block is not met 

### Actual behavior

The debugger gets stuck on the "wait until" block

### Screenshots

none

### Environment

- Browser: Chrome 99, Firefox 98
- Scratch Addons version: 1.25.0
- Operating system: macOS 11.6.1 (Big Sur)

### Additional context

non

**Comment by stefanofederici** [comment]
> > Try the debugger on the attached project
> 
> Please upload the project into scratch.mit.edu and send the link.

Here you go [https://scratch.mit.edu/projects/661003942/](https://scratch.mit.edu/projects/661003942/)

BTW: I wasn't notified of this answer of yours (I looked in the spam folder too) otherwise I would have answered before. I thought I would get a notification as soon as one answered?

**Comment by mxmou** [comment]
Can't repro on v1.38.2 using the linked project - stepping the "wait until" block switches back to the other thread.
