### ISSUE TITLE
Volume slider in project and project editor

### ISSUE THREAD

**Issue by ilbailba** [ScratchAddons/ScratchAddons#4422]
### Is your request related to a problem? Please describe.

When a project is started in Scratch, the **sound setting** of the **computer** of the person **who created the project** may not be the same as the **sound of the computer of the person playing the project**. This means that some projects may be quieter than normal, while some projects may have a louder sound. _That's the problem_.

-----------------------------------------------------------

### Describe the solution you'd like

I think there should be a **slider** for **adjusting the volume** in **both the project and the editor**. In this way, users will be able to **change only the sound of the project**, instead of **changing the sound of their computer and changing the sound** of all their applications.

-----------------------------------------------------------

### Describe alternatives you've considered

**Volume slider** => To adjust the volume of the volume (both in the project player and in the editor)

**Click on speaker icon** => To mute/unmute sound

**Alt+Up Arrow/Down Arrow** => To set the volume in multiples of 10

-----------------------------------------------------------

### Additional context

This plugin may **conflict** with the **"Muted project player mode"** plugin. Maybe they should be **combined**.

_I tried to make the **images look like the original**. **I hope it was good :)**_

_(Also ignore the LIST-BASED KAHOOT project. That project was one of the last projects I worked on and I discovered the sound problem in this project. I used this as an example. My purpose is not to advertise.)_

-----------------------------------------------------------

**Examples:**

![000](https://user-images.githubusercontent.com/71350431/159054732-fa2f703d-ea30-4581-a7d5-f2e7645c7305.png)
![020](https://user-images.githubusercontent.com/71350431/159054741-6970739b-c0ce-4fc6-aa62-db22633afb2a.png)
![070](https://user-images.githubusercontent.com/71350431/159054744-bb551110-8723-4b77-94fa-5915c2c4dea6.png)
![100](https://user-images.githubusercontent.com/71350431/159054745-0bd2444a-2615-484d-aeac-81b1fccf0535.png)

-----------------------------------------------------------
![Adsız4](https://user-images.githubusercontent.com/71350431/159053886-6666ab87-c640-4386-a3df-6de992b89e8e.png)
-----------------------------------------------------------
![Adsız3](https://user-images.githubusercontent.com/71350431/159053892-75130231-97a5-43fb-9baf-2e9b6307a219.png)

**Comment by RIMOPA** [comment]
This would take up more space on the toolbar, we already take up too much.
![image](https://user-images.githubusercontent.com/97112832/159065348-d4b36b31-e228-488b-8bc4-90965eef8c57.png)
(image from RedGuy13 [here](https://discord.com/channels/806602307750985799/943752054185263104/943990030874054686))

**Comment by ilbailba** [comment]
> This would take up more space on the toolbar, we already take up too much. ![OK so](https://user-images.githubusercontent.com/97112832/159066696-f6418359-a62c-4382-84a8-eefe22fe9d95.png) (image from RedGuy13 [here](https://discord.com/channels/806602307750985799/943752054185263104/943990030874054686))

I put it in the toolbar as an example. There are tons of places to put the volume adjustment.

**Comment by ilbailba** [comment]
It can even be put simply as a pop-up bar

**Comment by Secret-chest** [comment]
> This would take up more space on the toolbar, we already take up too much.
> ![OK so](https://user-images.githubusercontent.com/97112832/159066696-f6418359-a62c-4382-84a8-eefe22fe9d95.png)
> (image from RedGuy13 [here](https://discord.com/channels/806602307750985799/943752054185263104/943990030874054686))

Ideas:
* shorten "Turbo Mode" to just "Turbo" or even just the lightning icon
* "clones" text can be removed

**Comment by Hans5958** [comment]
Better idea: How about do it so when it hovers, the slider appears. Something like YouTube. Preferably go down due to space constraints.

**Comment by ilbailba** [comment]
> Better idea: How about do it so when it hovers, the slider appears. Something like YouTube. Preferably go down due to space constraints.

Yup. This can be too. But I think it's not the shape or position of the slider that matters here. The slider can be put anywhere desired.

**Comment by Secret-chest** [comment]
> And some (like mouse position) could be moved below the stage.

But add an option.
