### ISSUE TITLE
Forum Search doesn't work outside of topics

### ISSUE THREAD

**Issue by Dhuls-Scratch** [ScratchAddons/ScratchAddons#4424]
### Description

When forum search is enabled the searchbar will not appear

### Reproduction steps

1. Turn on Forum search
2. Go to a page for a subforum or the full forums

### Expected behavior

The search bar should appear

### Actual behavior

It doesn't

### Screenshots

What appears:
![Screenshot 2022-03-19 000923](https://user-images.githubusercontent.com/87714852/159107829-51028dd8-69a8-400e-9b99-73f7b54e986b.png)
What should appear:
![Screenshot 2022-03-19 000953](https://user-images.githubusercontent.com/87714852/159107828-109454ee-4d04-467e-9431-a305f90ef6f0.png)

### Environment

- Browser: Edge 99
- Scratch Addons version: v1.25.0
- Operating system: Windows 10 21H2 x64

### Additional context

Using the browser task manager to crash Scratch Addons and then reload it fixed the issue on forum topics, but not anywhere else

**Comment by Norbiros** [comment]
Version v1.25.0 broke this, on previous versions it works fine!

**Comment by Norbiros** [comment]
Can someone please look at this? It makes one addon completely not working...

**Comment by Dhuls-Scratch** [comment]
@Hans5958 (since you made it)
@apple502j (Since this might have something to do with #4372)

**Comment by Hans5958** [comment]
Forum search is not made by me (I contributed). @lholliger did it.
