### ISSUE TITLE
Remove the block palette scrollbar on Firefox

### ISSUE THREAD

**Issue by MystPi** [ScratchAddons/ScratchAddons#4425]
### Is your request related to a problem? Please describe.

On Firefox (I'm pretty sure Chrome doesn't do this), when the amount of icons in the block palette overflow, a scrollbar is shown. It could easily be fixed with CSS using `scrollbar-width: none`.
![image](https://user-images.githubusercontent.com/86574651/159118727-4e881b48-85e7-4b31-b85f-793b3bf5c844.png)

### Describe the solution you'd like

Simply hide the scrollbar in an addon, or just hide it by default.

### Describe alternatives you've considered

N/A.

### Additional context

None.

**Comment by mxmou** [comment]
See LLK/scratch-gui#8063

That issue has a priority label, which means the Scratch Team would probably accept a pull request to fix it.

**Comment by CST1229** [comment]
> That issue has a priority label, which means the Scratch Team would probably accept a pull request to fix it.

I assume only after someone is assigned to it.

**Comment by RedGuy12** [comment]
> If the issue is marked "Help Wanted" you can go ahead and start working on it!
We will only accept Pull Requests for bugs that have an issue filed that has a priority label

https://github.com/LLK/scratch-gui/blob/develop/.github/CONTRIBUTING.md

It has a priority label but no help wanted...https://github.com/LLK/scratch-www/issues/6441

**Comment by MystPi** [comment]
I created a PR to fix it: LLK/scratch-gui#8132
