### ISSUE TITLE
Full screen in light mode for turbowarp player. 

### ISSUE THREAD

**Issue by RedLight-Scratch** [ScratchAddons/ScratchAddons#4430]
### Reproduction steps

1. Turn on editor dark mode and turbowarp replace player button
2. Go to a project
3. Go into full screen
4. The screen is dark
5. Press the button to replace the scratch player with the turbowarp player
6. Go into full screen
7. The screen is light

### Expected behavior

The turbowarp player should be dark on the outside

### Actual behavior

The turbowarp player was white on the outside

### Screenshots

Scratch player in full screen:
![image](https://user-images.githubusercontent.com/76401850/159168889-5e0694b1-668a-46c0-9ea2-fd2ed6ed16a4.png)

Turbowarp player in full screen:
![image](https://user-images.githubusercontent.com/76401850/159168891-f04caeb8-0291-4a45-98da-afc0915a3ba5.png)

### Environment

- Browser: Firefox 98.0.1
- Scratch Addons version: 1.25.0 
- Operating system:  Windows 10

### Additional context

This is a pretty minor problem.

**Comment by kccuber-scratch** [comment]
Is this with the better fullscreen addon on or off?

**Comment by RIMOPA** [comment]
> Is this with the better fullscreen addon on or off?

Both.

**Comment by WorldLanguages** [comment]
This needs changes on Turbowarp's side

**Comment by Chiroyce1** [comment]
TurboWarp embeds are always light themed — https://turbowarp.org/655189478/embed

**Comment by WorldLanguages** [comment]
nice project

**Comment by Norbiros** [comment]
This is impossible. `Permission denied to access property "document" on cross-origin object`
https://stackoverflow.com/questions/4724904/how-to-change-style-of-iframe-content-cross-domain

The same problem is with this button...
![Screenshot from 2022-03-21 16-30-03](https://user-images.githubusercontent.com/89837724/159295071-62d99f5c-7c1c-4d74-9edb-07390f598426.png)
![Screenshot from 2022-03-21 16-29-54](https://user-images.githubusercontent.com/89837724/159295077-62e37089-99ea-4f12-ad22-b4a319eee0cc.png)

*Maybe we can cut iframe, and change page background, but it will look awful so...*

**Comment by GarboMuffin** [comment]
TurboWarp embeds have respected the system's dark mode preference in fullscreen for some time now and there is a URL parameter to override this https://docs.turbowarp.org/embedding#fullscreen-background

**Comment by WorldLanguages** [comment]
> The buttons are still stuck in light mode, though

@GarboMuffin By "the buttons", do you mean the stage header?

![image](https://user-images.githubusercontent.com/17484114/206281687-a27cb20b-05f7-4d3f-8251-ec24e8691678.png)

**Comment by WorldLanguages** [comment]
Okay, so it's an SA bug, not a TW limitation. I'll investigate

**Comment by WorldLanguages** [comment]
Moved the bug I mentioned above to a different issue: #5445 

Let's use this issue only for the fullscreen background

**Comment by tonyzhigit** [comment]
I don't think it was resolved yet, because it still doesn't work for me.
110.0.5478.4  dev x64 (cohort: Dev)

**Comment by mxmou** [comment]
@tonyzhigit It will be fixed in the next version of Scratch Addons (1.30.0).
