### ISSUE TITLE
Settings page "no results found": consider a category might be selected

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4442]
Message should remind the user that category filtering exists:

![image](https://user-images.githubusercontent.com/17484114/160247891-14bb15f9-4493-4c23-a14d-9620c841bf95.png)

**Comment by Secret-chest** [comment]
And there should be a button to do the same search in "all".

**Comment by Hans5958** [comment]
"...different keywords **and categories**"

**Comment by mxmou** [comment]
Is this message better? I can make a PR.
![image](https://user-images.githubusercontent.com/51849865/163585218-b43d818e-694c-4ca0-8168-ec333eeb9737.png)

**Comment by Norbiros** [comment]
Maybe also make something like that:
**Nor result found in "category". Perhaps try different keywords? Or search in "[all category](url)"

And when you click it it runs code: `vue.selectedCategory = "all";`.

**Comment by Hans5958** [comment]
Oh, no, how about "No results found on this category"

**Comment by WorldLanguages** [comment]
> Oh, no, how about "No results found on this category." I guess putting the name there better.

Can you clarify what you mean?

**Comment by Hans5958** [comment]
Editing

**Comment by mxmou** [comment]
I included the category name because the user could forget that they aren't in the "All" category.

**Comment by WorldLanguages** [comment]
> Is this message better? I can make a PR.

Yeah! Please do

Btw sorry for being inactive this week
