### ISSUE TITLE
Suport for use as a Bookmarklet?

### ISSUE THREAD

**Issue by minystreem** [ScratchAddons/ScratchAddons#4444]
Might be useful for people who can't install scratch addons.

**Comment by minystreem** [comment]
And for kids on chromebooks who can't install extension, I could try to port some stuff if that would help. my javascript kida sucks.

**Comment by Chiroyce1** [comment]
This wouldn't be possible since the current file structure of the extension is meant to be used as an extension itself, not raw JavaScript. Also some addons simply wouldn't work with bookmarklets (like the editor ones).

**Comment by CST1229** [comment]
> This wouldn't be possible since the current file structure of the extension is meant to be used as an extension itself, not raw JavaScript. Also some addons simply wouldn't work with bookmarklets (like the editor ones).

And some internal features of the extension only work when they can run as fast as possible, so a bunch of addons just wouldn't work. Userscript is a bit more possible I think.

**Comment by Hans5958** [comment]
Steps to make bookmarklets (quite a menace):
- Transpile code into compatible code
- Convert it into a bookmarklet
- [Have a website to host all of it](https://scratch-bookmarklets.github.io/)
- Update it automatically if possible
- ???
- Profit?
Something like that, but it's implausible at best IIRC.

**Comment by Secret-chest** [comment]
> Steps to make bookmarklets (quite a menace):
> 
> - Transpile code into compatible code
> - Convert it into a bookmarklet
> - [Have a website to host all of it](https://scratch-bookmarklets.github.io/)
> - Update it automatically if possible
> - ???
> - Profit?
> 
> Something like that, but it's implausible at best IMO.

That website repo is archived. What about bookmarklets.scratchaddons.com? It would display a list, and when you click one it would go to bookmarklets.scratchaddons.com/addon-id. There also would be a button to get a bookmaklet next to each addon on scratchaddons.com/addons.

**Comment by WorldLanguages** [comment]
I think we should first try to port Scratch Addons as a userscript. Then it could be used on Safari.
Converting a userscript to a bookmarklet would then be easier.

**Comment by RedGuy12** [comment]
SA is not possible as a bookmarklet because they run too late to capture Redux. And most addons use Redux.

**Comment by minystreem** [comment]
Oh yea, that would be quite complicated. probably not the best idea.

**Comment by Hans5958** [comment]
> That website repo is archived. 

I'm just giving an example. The state of that is not relevant.

> And most addons use Redux.

But that doesn't mean all addons use Redux... So it is possible, but only select addons, just like TurboWarp.

**Comment by Jakelemons** [comment]
Try this on for size :chromebook

javascript:let style = document.createElement("style");style.innerHTML = `[class^="stage-header_stage-button-icon"] {  transform: scaleX(-1);}[class^="target-pane_target-pane"] {  -webkit-flex-direction: row-reverse;  -ms-flex-direction: row-reverse;  flex-direction: row-reverse;}[dir="ltr"] [class^="target-pane_stage-selector-wrapper"] {  margin-left: 0;  margin-right: calc(0.5rem / 2);}[dir="ltr"] [class^="sprite-selector_sprite-selector"] {  margin-left: calc(0.5rem / 2);  margin-right: 0;}[dir="rtl"] [class^="target-pane_stage-selector-wrapper"] {  margin-right: 0;  margin-left: calc(0.5rem / 2);}[dir="rtl"] [class^="sprite-selector_sprite-selector"] {  margin-right: calc(0.5rem / 2);  margin-left: 0;}[class^="gui_flex-wrapper"] {  -webkit-flex-direction: row-reverse;  -ms-flex-direction: row-reverse;  flex-direction: row-reverse;  overflow-x: hidden;}[dir="ltr"] [class^="backpack_backpack-header"] {  border-top-right-radius: 0;  border-top-left-radius: 0.5rem;}[dir="ltr"] [class^="blocks_blocks_C530M"] .injectionDiv,[dir="ltr"] [class^="asset-panel_wrapper"] {  border-top-right-radius: 0;  border-bottom-right-radius: 0;  border-bottom-left-radius: 0.5rem;}[dir="ltr"] [class^="gui_extension-button-container"] {  border-bottom-left-radius: 0.5rem;}[dir="rtl"] [class^="backpack_backpack-header"] {  border-top-left-radius: 0;  border-top-right-radius: 0.5rem;}[dir="rtl"] [class^="blocks_blocks_C530M"] .injectionDiv,[dir="rtl"] [class^="asset-panel_wrapper"] {  border-top-left-radius: 0;  border-bottom-left-radius: 0;  border-bottom-right-radius: 0.5rem;}[dir="rtl"] [class^="gui_extension-button-container"] {  border-bottom-right-radius: 0.5rem;}.Popover {  z-index: 40;}`;document.body.appendChild(style);void(0);
