### ISSUE TITLE
Colorblind mode

### ISSUE THREAD

**Issue by ilbailba** [ScratchAddons/ScratchAddons#4446]
### Is your request related to a problem? Please describe.

Colorblind people can't use Scratch well enough.

### Describe the solution you'd like

So I thought of the colorblind mode. This will not be a plugin. It will be in the settings of the SA and will be adjusted from there. When this feature is turned on, Scratch and SA will change the color scheme based on the selected setting.

### Describe alternatives you've considered

Colorblind mode setting => Turns colorblind mode on or off.

Dropdown = Colorblind type
|
=> Deuteranomaly (red-green)
=> Protanomaly (red-green)
=> Tritanomaly (blue-yellow)

### Additional context

There are different types of color blindness. Also, I'm not a doctor. This is just a suggestion.

https://en.m.wikipedia.org/wiki/Color_blindness

**Comment by ilbailba** [comment]
> Customizable colors addons exist.

Hey! I'm not just talking about blocks. I'm speaking for the entire Scratch and SA site.

**Comment by RIMOPA** [comment]
So, what about a colorbind preset? Or a new "preset section" with some types of colorbind presets?

**Comment by WorldLanguages** [comment]
I don't think your suggestion is very precise. Yes, many types of color blindness exist, but what would the addons change exactly? I don't think we could know unless someone who actually has color blindness tells us.
And Scratch Addons already provide custom colors for the editor, blocks and website.

**Comment by ilbailba** [comment]
> So, what about a colorbind preset? Or a new "preset section" with some types of colorbind presets?

I planned to have presets or options according to the type and severity of the disease.

**Comment by WorldLanguages** [comment]
How would we determine the colors to put in the presets? We have little idea at all about color blindness.

Also, I think any issues with color blindness should be first reported to the Scratch Team. I think they'd find it suitable to change some styles for everyone to provide better accessibility, except the editor block colors, but those can already be changed with Scratch Addons and there's a 2.0 preset.

**Comment by Secret-chest** [comment]
> I think they'd find it suitable to change some styles for everyone to provide better accessibility

(I don't want to hurt @ilbailba if they are colorblind)

Why did you suggest that? First, they implement zero suggestions. Second, the colorblind tweaks should be an option. I don't want to wake up with category icons on each block.

I however understand this problem and there should be presets for all color-changing addons for various colorblindness situations. I can make a script to "colorblind" pictures of Scratch so we can see the changes we need to make.

**Comment by ilbailba** [comment]
> > I think they'd find it suitable to change some styles for everyone to provide better accessibility
> 
> (I don't want to hurt @ilbailba if they are colorblind)
> 
> Why did you suggest that? First, they implement zero suggestions. Second, the colorblind tweaks should be an option. I don't want to wake up with category icons on each block.
> 
> I however understand this problem and there should be presets for all color-changing addons for various colorblindness situations. I can make a script to "colorblind" pictures of Scratch so we can see the changes we need to make.

First of all, I'm not colorblind and I don't know anyone who is colorblind. The reason I recommend this: Scratch welcomes people of all ages, races, and sexual orientations, as they themselves state. When I read this, I thought of colorblindness. Yes, Scratch welcomes a huge audience, but they don't have an initiative for colorblindness and "customizable colors" is not a solution. Because customizable colors are made to replace colors in normal people's Scratch, not to make them normal for colorblinds. So if the color of a block is green, a colorblind can't tell it's green. It can actually change the color, but he can never be sure if it's the right color. This also applies to the colors of puppets, cover photos, profile photos or all images in projects. You can change the color of blocks with customizable colors, but you cannot change the color of puppets in a project. That's why you need to change all the colors, which is a very tiring and demanding process. Instead of making all Scratch projects for colorblind people or doing all the projects that colorblind people do for normal people, a more comfortable working environment can be provided for everyone with just a special filter (I mean colorblind mode). Scratch Addons aim to provide conveniences for Scratch users, and I think this option fits its purpose very well. And I repeat: I'm not just talking about the blocks or the gui, I'm talking about the whole Scratch and Scratch Addons.

Also, I would be very happy if you make a file 🙂.

It's too long 🙄.

(This feature can be likened to a filter. Sorry for my English, by the way. Also, I didn't understand a few things you said.)

**Comment by Secret-chest** [comment]
> > > I think they'd find it suitable to change some styles for everyone to provide better accessibility
> > 
> > (I don't want to hurt @ilbailba if they are colorblind)
> > 
> > Why did you suggest that? First, they implement zero suggestions. Second, the colorblind tweaks should be an option. I don't want to wake up with category icons on each block.
> > 
> > I however understand this problem and there should be presets for all color-changing addons for various colorblindness situations. I can make a script to "colorblind" pictures of Scratch so we can see the changes we need to make.
> 
> First of all, I'm not colorblind and I don't know anyone who is colorblind. The reason I recommend this: Scratch welcomes people of all ages, races, and sexual orientations, as they themselves state. When I read this, I thought of colorblindness. Yes, Scratch welcomes a huge audience, but they don't have an initiative for colorblindness and "customizable colors" is not a solution. Because customizable colors are made to replace colors in normal people's Scratch, not to make them normal for colorblinds. So if the color of a block is green, a colorblind can't tell it's green. It can actually change the color, but he can never be sure if it's the right color. This also applies to the colors of puppets, cover photos, profile photos or all images in projects. You can change the color of blocks with customizable colors, but you cannot change the color of puppets in a project. That's why you need to change all the colors, which is a very tiring and demanding process. Instead of making all Scratch projects for colorblind people or doing all the projects that colorblind people do for normal people, a more comfortable working environment can be provided for everyone with just a special filter (I mean colorblind mode). Scratch Addons aim to provide conveniences for Scratch users, and I think this option fits its purpose very well. And I repeat: I'm not just talking about the blocks or the gui, I'm talking about the whole Scratch and Scratch Addons.
> 
> Also, I would be very happy if you make a file 🙂.
> 
> It's too long 🙄.
> 
> (This feature can be likened to a filter. Sorry for my English, by the way. Also, I didn't understand a few things you said.)
> 

I understand, but it can be an addon. Scratch Addons' settings page can be used perfectly without colors.

**Comment by ilbailba** [comment]
> I understand, but it can be an addon. Scratch Addons' settings page can be used perfectly without colors.

But some plugins need colors. For example: Customizable block colors. I think this must be a setting so that the Scratch website and the SA Settings page can be synchronized. If this is a plugin, it can only work on the Scratch website. Also, I think it's much more appropriate to describe it as a "setup".
