### ISSUE TITLE
Cmd+Return on the Ctrl+Enter to post addon not working

### ISSUE THREAD

**Issue by Steve0Greatness** [ScratchAddons/ScratchAddons#4451]
### Description
On the settings page it says on that
![On macOs, you can also use the Cmd key](https://user-images.githubusercontent.com/75220768/161171911-926742c6-dbd3-4fec-8646-7ad47d43b017.png)
However, everytime that I've tried to use cmd+return(what Apple names their enter)

### Reproduction steps

1. Turn on `Ctrl+Enter to post`
2. Write a comment/forum post
3. Press cmd+return

### Expected behavior
When I press cmd+return it should post the comment/forum post.

### Actual behavior
When pressing cmd+return, literally nothing happens.

### Screenshots
***not applicable***

### Environment

- Browser(s): FireFox 98.0.2 (64-bit) and Chrome 100.0.4896.60
- Scratch Addons version: 1.25.1
- Operating system: Mac OS Catalina 10.15.3

### Additional context
I know that cmd+return works because it works here on GitHub.

**Comment by leahcimto** [comment]
Can replicate
