### ISSUE TITLE
Data category tweaks and two-column category menu not working

### ISSUE THREAD

**Issue by barackenkumpel** [ScratchAddons/ScratchAddons#4462]
### Description

Nothing changes when enabling these two extensions, but others work as expected.

### Reproduction steps 

1. Enable one or both of these addons
2. Open an editor page

### Expected behavior

Extentensions being applied

### Screenshots

![Screenshot_2022-04-03_18-25-00](https://user-images.githubusercontent.com/93818968/161437847-457a217d-42c8-4a9c-a522-5db9625284f0.png)

### Environment

- Browser: Firefox 91.7.0esr
- Scratch Addons version: v1.25.1
- Operating system: Debian bullseye

**Comment by CST1229** [comment]
Those addons were disabled because they broke with Scratch's April Fools jokes.
