### ISSUE TITLE
Cat Block addon doesn't seem to be working

### ISSUE THREAD

**Issue by EpicCreator9132** [ScratchAddons/ScratchAddons#4463]
When I enable the cat block addon the hat blocks remained the same. This addon used to work perfectly and the other addons seem to work fine. I really like using this add on and would appreciated it if you could take a look to find out what is wrong. Thanks.

**Comment by CST1229** [comment]
The addon was force-disabled because Mode > Caturday mode exists. It will automatically be re-enabled when the editor April Fools jokes end.

**Comment by EpicCreator9132** [comment]
Ok thank you.
