### ISSUE TITLE
Remove `easterEgg` addons from addon count in the popup

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#4465]
Wouldn't it make sense to exclude Easter eggs from the count? They aren't visible by default so they shouldn't be presented as normal features.

_Originally posted by @mxmou in https://github.com/ScratchAddons/ScratchAddons/issues/3328#issuecomment-902173809_

**Comment by WorldLanguages** [comment]
If the code to exclude those from the count isn't ugly, I approve this

**Comment by Norbiros** [comment]
I created this code:
```js
return `${Math.floor(this.manifests.filter(addon => !addon.tags.includes("easterEgg")).length / 5) * 5}+`;
```
It works very fine. If WorldLanguages will accept this code, I will create PR.
Problem is with addon `Scratch Blocks`. It doesn't have tag "easterEgg", but it shows when you type Konami code, so we should count it? If yes, code should look like:
```js
return `${Math.floor((this.manifests.filter(addon => !addon.tags.includes("easterEgg")).length + 1) / 5) * 5}+`;
```

**Comment by CST1229** [comment]
> Problem is with addon `Scratch Blocks`. It doesn't have tag "easterEgg", but it shows when you type Konami code, so we should count it?

Cat blocks also shows without typing the Konami code IIRC.

**Comment by Norbiros** [comment]
Yep. So I should count it as easter egg or not?

**Comment by mxmou** [comment]
> Yep. So I should count it as easter egg or not?

All addons that appear outside the Easter egg category should be included in the count.

**Comment by Norbiros** [comment]
Okay. So answer is "Count it as easter egg".

**Comment by mxmou** [comment]
> Okay. So answer is "Count it as easter egg".

Count it as a normal addon.

**Comment by WorldLanguages** [comment]
It's rounded to the nearest multiple of 5, so I don't think it's important to take into account that cat-blocks is an easterEgg and not an easterEgg at the same time.

**Comment by Norbiros** [comment]
Okay. Thanks for response!
