### ISSUE TITLE
developer-tools: "Ctrl+Space" to bring up "add block by name" doesn't work on macOS

### ISSUE THREAD

**Issue by Chiroyce1** [ScratchAddons/ScratchAddons#4466]
### Description

In the  developer-tools addon,  pressing "Ctrl+Space" to bring up "add block by name" doesn't work on macOS.

### Reproduction steps

1. On a Mac, on a browser with SA installed, make sure the developer-tools addon is enabled
2. Go to the project editor and press CTRL + SPACE in the code area (command + space is reserved by macOS for spotlight search)

### Expected behavior

It should let you type the name of a block and place it.

### Actual behavior

It doesn't even show up

### Environment

- Browser: Firefox 98
- Scratch Addons version: SA v1.25.1 and v1.26 (pre-release)
- Operating system: macOS Big Sur

**Comment by Mbrick2** [comment]
I think it might be the language change popup.

**Comment by Mbrick2** [comment]
> @Mbrick2 which one? the browser's or scratch's?

macOS's.
![image](https://user-images.githubusercontent.com/90691415/161922037-3fe63cd4-f98f-42d9-b9d5-f3d71e96b420.png)
**This is from DDG as my recorder couldn't capture it**

**Comment by Chiroyce1** [comment]
Can replicate with 2 keyboard languages on macOS - CTRL + SPACE brings up a prompt to change it, and it also doesn't work without multiple languages enabled.

**Comment by WorldLanguages** [comment]
It's possible websites might not be able to use Ctrl+Space as a hotkey on Macs.
Does Shift+Click work?

**Comment by Chiroyce1** [comment]
> Does Shift+Click work?

Yes it does!
<img width="527" alt="image" src="https://user-images.githubusercontent.com/97374054/162557440-695f3ea1-8118-48fd-87c3-c895f598d74c.png">


Also for some reason only using `shiftKey` works, but it throws an error in the console. `e.shiftKey` also works, but it doesn't throw an error. What's the difference?

**Comment by mxmou** [comment]
> Also for some reason only using `shiftKey` works, but it throws an error in the console. `e.shiftKey` also works, but it doesn't throw an error. What's the difference? Using `ctrlKey` doesn't throw an error though..
> 
> > https://github.com/ScratchAddons/ScratchAddons/blob/b2f64bbc4e475282e4d0de8e28fe38b304b7edce/addons/editor-devtools/DevTools.js#L1430

`ctrlKey` is a variable defined a few lines earlier: `let ctrlKey = e.ctrlKey || e.metaKey;`

**Comment by Chiroyce1** [comment]
Update: Shift + Click already works, but it's just not mentioned in the settings
<img width="354" alt="image" src="https://user-images.githubusercontent.com/97374054/162661606-52fac0b2-cab9-4c84-99ae-362bba2dd56c.png">

**Comment by scratchusernamemrtbts** [comment]
i just rebind the mac os key for changing the language cus i dont really use it that often and i use caps lock to change langugage
