### ISSUE TITLE
Open clicked links on website on a new tab

### ISSUE THREAD

**Issue by R081N-08** [ScratchAddons/ScratchAddons#4474]
I'm suggesting an addon that makes all clicked links on the Scratch website open on a new tab. This is useful if you don't want to lose the projects on the front page (they reroll when you reload the website).

**Comment by RedGuy12** [comment]
Rejected - use middle click

**Comment by Samq64** [comment]
What about touch and touchpad users? Could it be a disabled by default option in more links?

**Comment by mxmou** [comment]
> What about touch and touchpad users? Could it be a disabled by default option in more links?

I don't think right click → open in new tab is too difficult to use.
