### ISSUE TITLE
Scratch 2.0 → 3.0: affect alerts

### ISSUE THREAD

**Issue by Norbiros** [ScratchAddons/ScratchAddons#4497]
### Description

![Screenshot 2022-04-14 at 16-25-48 Scratch - Imagine, Program, Share](https://user-images.githubusercontent.com/89837724/163410806-1d08105d-a7ad-41d4-8bb9-89f42ee44165.png)
It shows this strange, small toolip without any text. In scratch you have this bug too, but it fits into old theme. This toolip shows text when you for example follow someone.

### Reproduction steps

1. Enable `Scratch 2.0 -> 3.0` addon
2. Go to your profile page
3. Change "About Me" section and save it

### Environment

- Browser: Firefox newest
- Scratch Addons version: newest
- Operating system: gentoo linux

**Comment by WorldLanguages** [comment]
> It shows this strange, small toolip without any text. In scratch you have this bug too, but it fits into old theme. This toolip shows text when you for example follow someone.

I'm confused - what's the bug then? The small tooltip is a Scratch bug unrelated to Scratch Addons.

**Comment by Chiroyce1** [comment]
Do you mean that the breadcrumb (is this what its called?) is missing text?
<img width="90" alt="image" src="https://user-images.githubusercontent.com/97374054/163527146-0d86ae42-2abe-4517-a24c-0274ea39a495.png">

**Comment by mxmou** [comment]
> Due to a scratch bug it doesn't have the text, so i think applying any styles to it doesn't make sense unless the bug is fixed and text is shown there.

Following and unfollowing shows a notice that does have text.

**Comment by Norbiros** [comment]
We can hide it on this specific page, but i was thinking to make it more like 3.0. Maybe change "top", background colour etc. I think it looks ugly now (especially when search bar overrides it).
