### ISSUE TITLE
custom blocks custom colors

### ISSUE THREAD

**Issue by piw-piw** [ScratchAddons/ScratchAddons#4508]
Set custom color for any custom block.
Something like that:
![image](https://user-images.githubusercontent.com/76477070/163692555-ec2ac9ee-a668-4a90-8616-957d08aab3f7.png)
! In addon with block comments:
![image](https://user-images.githubusercontent.com/76477070/163692763-14ee0ed3-7cbd-44b4-a809-353f817f45b0.png)

**Comment by RedGuy12** [comment]
Duplicate of #1706

**Comment by WorldLanguages** [comment]
@RedGuy12 Are you sure it's the exact same suggestion?

**Comment by piw-piw** [comment]
It's custom color, not category color.
