### ISSUE TITLE
addon api autocomplete 

### ISSUE THREAD

**Issue by jeffalo** [ScratchAddons/ScratchAddons#451]
**Is your feature request related to a problem? Please describe.**

i dont like documentation reading it makes me sad

**Describe the solution you'd like**

i'm not sure how some libraries do it but they get their own auto complete entries in vscode if that makes sense

like this one
![image](https://user-images.githubusercontent.com/40470736/95647932-d7cf5b00-0ad3-11eb-99c8-8c7164d79c8b.png)

**Additional context**

i hope this makes sense what i mean

**Comment by WorldLanguages** [comment]
Yeah I've looked into this before the release, sadly I don't think there's any convenient way. Keep in mind `addon` is an argument that is passed to the function, so VS Code does not really know what to expect from it. And I don't think you can declare types without a bunch of "dumb" imports at the top of the file, or using some JSDoc hack that might stop working someday...
Tbh I'll try to research this again

**Comment by easrng** [comment]
Yeah you'd need jsdoc or typescript definitions afaik
