### ISSUE TITLE
A Whole Loada' Recommendations!

### ISSUE THREAD

**Issue by jat354155** [ScratchAddons/ScratchAddons#4511]
# **The Problem: Making games, projects, and good looking animations already is pretty fast, but it could be faster**

## ![brush](https://user-images.githubusercontent.com/91216411/163728322-fe8ff00f-7764-46ec-bdc1-7727968b1f05.svg) Themes

- [ ] Why can you customize the "whole" scratch website, but not extension that customizes it?
- [ ] Why can you not customize the color of shown variables and lists with the ![puzzle](https://user-images.githubusercontent.com/91216411/163728448-2ae04f31-c67e-4830-beee-c73c96b88fbb.svg) Customizable Block Colors setting?

## ![puzzle](https://user-images.githubusercontent.com/91216411/163728448-2ae04f31-c67e-4830-beee-c73c96b88fbb.svg) Scratch editor features
- [ ] Why can't you upload a default project?
- [x] Why can't I get that one bugged vector curve that I can freely rotate?
- [x] Why do I have to go to TurboWarp to get one singular transparent shape every time I think of adding one?

## Screenshot(s)
![More transparency stuff](https://user-images.githubusercontent.com/91216411/163728952-bfcd2b56-0111-490a-b5e5-08b7ca4e8474.png)

- Could you help me out here? [@jat354155](https://scratch.mit.edu/users/jat354155/)

**Comment by RIMOPA** [comment]
Upload a default project:
  You can, upload the project and put Its ID in the addon "Customizable default project".

**Comment by jat354155** [comment]
> Upload a default project:
You can, upload the project and put Its ID in the addon "Customizable default project".

What I meant was you can't UPLOAD a default project, it has to be a project that already exists, and which you have the project ID to.

**Comment by CST1229** [comment]
> What I meant was you can't UPLOAD a default project, it has to be a project that already exists, and which you have the project ID to.

I think it's because we would need to implement file uploads and possibly store it in exported settings.

**Comment by CST1229** [comment]
Opacity slider: Currently kinda impractical until a future Scratch update that probably isn't coming soon.  
Bugged vector curve: IIRC you can do this in vanilla by holding Alt while dragging a curve handle.

**Comment by apple502j** [comment]
One suggestion at a time, please.

**Comment by WorldLanguages** [comment]
> Why can you customize the "whole" scratch website, but not extension that customizes it?

Because it's not necessary. The average Scratcher spends hours in the editor but minutes on Scratch Addons settings. Also, we have a light mode.

>  Why do I have to go to TurboWarp to get one singular transparent shape every time I think of adding one?

See #2129

**Comment by jat354155** [comment]
> > Why can you customize the "whole" scratch website, but not extension that customizes it?
> 
> Because it's not necessary. The average Scratcher spends hours in the editor but minutes on Scratch Addons settings. Also, we have a light mode.

I know 2 people who open the popup to read the messaging page, including myself, and I sometimes use the page to make the block colors useable. What if the person has a browser theme that just doesn't fit with the popup?
