### ISSUE TITLE
Email confirmation has white text on white background

### ISSUE THREAD

**Issue by Dhuls-Scratch** [ScratchAddons/ScratchAddons#4513]
### Description

Title

### Reproduction steps

1. Create a new account
2. Send the verification email
3. Where it says "Does this email look weird? - Click Here" open that link

### Expected behavior

I should be able to read the text

### Actual behavior

I can't

### Screenshots

![emailverification](https://user-images.githubusercontent.com/87714852/163750951-4cc41d26-106d-41f0-b41e-b7591576a1cf.png)

### Environment

- Browser:  Edge 100
- Scratch Addons version:  1.25.1
- Operating system:  Windows 10

**Comment by Chiroyce1** [comment]
Shouldn't the title be `Email confirmation has white text on light background`?
