### ISSUE TITLE
Buttons use different capitalization

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#4520]
* Show more messages
* Reload messages
* Open full screen settings
* Export Settings
* Import Settings
* View settings file

We should choose sentence case or title case and use it for all buttons.

**Comment by Norbiros** [comment]
IMO we should change just `Export/Import Settings`, because they are only settings that use title case...

**Comment by WorldLanguages** [comment]
Title case is used for `Help Translate`, `Send Feedback` and other buttons.

**Comment by mxmou** [comment]
> Title case is used for `Help Translate`, `Send Feedback` and other buttons.

I think those can be different because they're links in the side navigation, not commands.
