### ISSUE TITLE
60fps addon: list monitors sometimes not updating correctly

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4523]
### Description

If the 60fps addon is disabled, or the green flag wasn't alt+clicked, list monitors update properly.
If 60 fps mode is enabled, the monitors update inconsistently, and dragging the list somewhere else on the stage updates it. The list itself is updated, but it's not shown in the monitor.

### Reproduction steps

1. Enable 60fps addon (default settings)
2. Go to this project https://scratch.mit.edu/projects/679667242/editor
3. Find this block (Sprite1 sprite, it has a big comment attached to it)
![image](https://user-images.githubusercontent.com/17484114/164915207-b5cb21b8-5010-44b7-8045-62d97be606d7.png)
4. Click it multiple times (not faster than once every second), the 3 lists update accordingly.
5. Alt+click the green flag to enable 60 fps mode
6. Click the block multiple times (not faster than once per second) and at some point, one of the lists will show `(empty)` even tho it's not actually empty.
7. Drag around the list that is apparently empty, drop it and the list monitor will update.

### Screenshots

Video: https://cdn.discordapp.com/attachments/967263188624220170/967263333038325781/Screen_Recording_2022-04-22_at_9.55.35_PM.mov

### Environment

Reproduced in Chrome by bug reporter on Discord server. I reproduced in Chrome too, but I could only make the third list say `(empty)`. The user that reported the bug could also make the second list look empty.

Reproduced on TurboWarp by bug reporter even tho it doesn't use the 60fps addon.

**Comment by Samq64** [comment]
I reproduced on Turbowarp a little while ago without 60 fps.

**Comment by WorldLanguages** [comment]
This might be hard or impossible to fix, this might just be how monitors work.

**Comment by Chiroyce1** [comment]
CR on Firefox too, macOS Big Sur. I think this has to do with the way list monitors update according to the frame rate, but it is weird that only the last list shows `(empty)` and the first two show the correct values...

**Comment by apple502j** [comment]
See https://github.com/TurboWarp/scratch-gui/commit/7f73c7b5fe39662ae59c65047e473751b5cb7851 for the cause
Unsure how to fix this.
