### ISSUE TITLE
Addon Request: Disable spell checking in comments

### ISSUE THREAD

**Issue by xAspirus** [ScratchAddons/ScratchAddons#4528]
Should be a simple addon to implement
would disable the red underlines in comments

**Comment by mxmou** [comment]
This certainly wouldn't be difficult to implement, but I'm not sure why one would want to disable the spell checker specifically on Scratch and not on other websites.

**Comment by Norbiros** [comment]
I agree. We can make it by just adding `spellcheck="false"` to page's body, but this feature was invented to fix misspells in messages (to write words correctly). Why you want to disable it? If it highlights every word, try changing dictionary's language etc.

**Comment by Secret-chest** [comment]
What if you are multilingual? (I speak 🇷🇴 limba română and 🇬🇧 English)

**Comment by Secret-chest** [comment]
> This certainly wouldn't be difficult to implement, but I'm not sure why one would want to disable the spell checker specifically on Scratch and not on other websites.

Yes, this should be a separate browser extension. I can make it.

**Comment by mxmou** [comment]
> > This certainly wouldn't be difficult to implement, but I'm not sure why one would want to disable the spell checker specifically on Scratch and not on other websites.
> 
> Yes, this should be a separate browser extension. I can make it.

You don't need an extension to disable spell checking globally - just turn it off in the browser settings.

**Comment by mxmou** [comment]
> It is easy (in Firefox, idk how it works in chrome) just right click, select languages and your language.

Chrome has the same feature: right click → Spell check and select the language.

**Comment by apple502j** [comment]
Unsure if this is usable as an addon, as others have already said.

**Comment by Secret-chest** [comment]
> > It is easy (in Firefox, idk how it works in chrome) just right click, select languages and your language.
> 
> Chrome has the same feature: right click → Spell check and select the language.

Can you select more?

**Comment by mxmou** [comment]
> > > It is easy (in Firefox, idk how it works in chrome) just right click, select languages and your language.
> > 
> > 
> > Chrome has the same feature: right click → Spell check and select the language.
> 
> Can you select more?

The context menu only allows selecting one language, but the language settings don't have this limitation.

**Comment by xAspirus** [comment]
i was talking about code comments, not website! aaaa

**Comment by Norbiros** [comment]
> i was talking about code comments, not website! aaaa

It makes more sense now... But still I think it is unnesesary (you can change lang)

**Comment by xAspirus** [comment]
i want to write documentation in markdown in comments
