### ISSUE TITLE
Small blocks can't be grabbed. (Hide Block Palette addon)

### ISSUE THREAD

**Issue by press-dev** [ScratchAddons/ScratchAddons#4530]
Possibly a “hide block palette” addon issue: Certain small blocks like “show” and “hide” aren’t grabbable for me + other blocks grab hitboxes are offsetted.

note: I have two different sized displays but resizing the scratch page does not make a difference so I think that wouldn’t have caused it.

**Comment by mxmou** [comment]
Does this happen in every project?

**Comment by press-dev** [comment]
Every one of my projects + reloading the page or clearing cache does not work.

**Comment by press-dev** [comment]
Video: (note: My mouse is not offsetted in this video. This is what is actually happening.)

https://user-images.githubusercontent.com/94125865/165628921-0ac47a4e-9699-4b3a-b1f1-d4565b39a458.mp4

**Comment by press-dev** [comment]
I am going to close this until further help comes.
