### ISSUE TITLE
`more-links` creates an additional hyperlink for links that are hyperlinked by Scratch 

### ISSUE THREAD

**Issue by Chiroyce1** [ScratchAddons/ScratchAddons#4533]
## Description

Command (tested on macOS, control on Windows/Linux may also be affected) + Clicking a link (usually opens a link in a new tab) on Scratch with `more-links` enabled opens up link in 2 tabs instead of 1 

### Reproduction steps

1. Make sure the `more-links` addon is enabled
2. Command (or Ctrl) + Click the URL in [this](https://scratch.mit.edu/studios/30136012/comments/#comments-183295561) comment or any other link on a Scratch comment

### Expected behavior

Link opens in a new tab

### Actual behavior

Link opens in 2 new tabs

### Screenshots

Apart from the original link created by Scratch, another one is created by `more-links` even though it shouldn't be creating links to `scratch.mit.edu`

<img width="873" alt="image" src="https://user-images.githubusercontent.com/97374054/165679360-4934b6a0-a480-4296-8c7b-6aa70042af14.png">

https://user-images.githubusercontent.com/97374054/165679455-0379eca5-5ef3-41a0-b3c8-ac675b9eb5bd.mov

_(red clicks are command + clicks, black clicks are normal ones)_

### Environment

- Browser: Firefox 98
- Scratch Addons version: v1.25.1
- Operating system: macOS Big Sur

### Additional Info
The `more-links` addon [hasn't been updated in over 9 months](https://github.com/ScratchAddons/ScratchAddons/commits/master/addons/more-links), and this has only started happening very recently (v98 onwards), most likely due to an update for Firefox.

**Comment by mxmou** [comment]
Interestingly, this only happens when using Ctrl+click: middle click and "Open Link in New Tab" work correctly.

**Comment by Samq64** [comment]
I can reproduce with Firefox on Ubuntu.

**Comment by towerofnix** [comment]
I *can't* reproduce this with Firefox on Ubuntu - but it does generate the (incorrectly) nested `<a>` link here, so I think this is just a slight browser behavior difference, and it's worth investigating/fixing even if certain versions don't have an apparent bug.

(I'm on Firefox ESR, 91.8.0, which is a few versions back from current 99.0.)

**Comment by Mbrick2** [comment]
Can't Reproduce with FF 100 and macOS Big Sur

**Comment by Chiroyce1** [comment]
Can't reproduce on Firefox v100.0 - this has been fixed by Firefox, BUT this addon still creates two `<a>` tags instead of just not modifying it

<img width="583" alt="image" src="https://user-images.githubusercontent.com/97374054/168040231-3c857b89-7158-4086-9326-46799b65b4f4.png">
