### ISSUE TITLE
Less Scary Alternative To Warnings

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#455]
warnings are currently all in red and bold which looks kinda scary even though they're not really that scary.

perhaps there could be warnings and notes,

notes would be basically like warnings but in italics and white or something

**Comment by GrahamSH-LLK** [comment]
Interesting! I like that idea, although it is somewhat similar to the description. I agree about needing a less scary alternative.

**Comment by Explosion-Scratch** [comment]
Maybe like an asterisk?

**Comment by Explosion-Scratch** [comment]
I agree, it sort of looks hurried and unprofessional to have those warnings so bold and stuff.
