### ISSUE TITLE
Untranslated theme text in popup

### ISSUE THREAD

**Issue by Norbiros** [ScratchAddons/ScratchAddons#4558]
### Description

In newest version, when you load settings in popup it shows this for short around of time:
![popup](https://user-images.githubusercontent.com/89837724/168095087-24f91ecd-eb57-4816-a041-0e4683fc7c3d.png)
I think it started showing up, because of this PR https://github.com/ScratchAddons/ScratchAddons/pull/4510

### Reproduction steps

1. Open popup
2. Select settings

### Expected behavior

It shouldn't show this text.

### Environment

- Browser: Firefox 95
- Scratch Addons version: newest (1.26.0-pre)
- Operating system: Linux Gentoo

**Comment by mxmou** [comment]
Probably a missing v-cloak attribute.
