### ISSUE TITLE
Move userstyle caching from background to content script

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4561]
Currently, addons with `injectAsStyleElt: true` have its styles prefetched as soon as an `chrome.webRequest.onBeforeRequest` event is triggered. This is important for `scratchr2` and `dark-www` themes so that navigating from a page to another doesn't cause style flashing.

Due to manifest V3 and the service worker model, doing this doesn't make sense anymore - waking up the service worker takes time, and it might just be faster to cache each CSS file's contents in `chrome.storage.local`, `IndexedDB` or `localStorage`, on the content script's side.
They wouldn't be fetched each time like they currently are, which removes complexity from the background context of the extension, but this also means that we'd need to rethink how to handle debugging those addons - we'd want the stable version of the extension to cache these files once per version, but not when debugging and editing these CSS files locally in prerelease. Maybe this could be an opportunity to add some type of developer mode that if enabled, updates CSS automatically when the files are changed, without having to trigger a refresh or manually reenable addons.

Ideally, the content script shouldn't even wait for the background to respond to inject dark mode CSS, since every millisecond counts to avoid flashing. We could possibly allow the content script to independently check if these addons are enabled even if they haven't communicated with the background yet. Currently, the content script won't inject any CSS until the background page sends a `contentScriptInfo` object.

cc @mxmou any suggestions on features that would make developing and tweaking userstyles easier?

**Comment by lisa-wolfgang** [comment]
It would be nice to more easily check for compatibility with other addons, layout-wise and theme-wise. I can't think of any specific features at the moment, but just food for thought.

**Comment by mxmou** [comment]
> It would be nice to more easily check for compatibility with other addons, layout-wise and theme-wise. I can't think of any specific features at the moment, but just food for thought.

#1673 would be helpful because testing different configurations requires enabling and disabling addons frequently.

**Comment by WorldLanguages** [comment]
> #1673 would be helpful because testing different configurations requires enabling and disabling addons frequently.

Most addons support dynamic enable/disable now.
#4885 was merged, which also makes it easier to enable and disable addons frequently.
I guess the one that wasn't resolved yet was #1250

**Comment by WorldLanguages** [comment]
I'll reconsider whether to actually do this

**Comment by WorldLanguages** [comment]
> Ideally, the content script shouldn't even wait for the background to respond to inject dark mode CSS, since every millisecond counts to avoid flashing.

I think we could stop using `webRequest`, but avoid caching files in storage.

We could solve flashing on navigations (e.g. clicking a project on the Scratch homepage) by catching the click of links and sending a message to the background page with the href of the it. This way, the background page can preload the userscript/userstyle information for that URL before `chrome.tabs` events actually occur.
Flashing on first navigation (e.g. opening Scratch homepage in a new tab) would still happen. We could try our best there with `chrome.tabs` events or running a script on `document_start`, whichever works best (probably the former).

Non-persistent background pages don't support `webRequest`, so using a different way to preload data is a good idea for the MV3 migration and ensuring cross-browser support.

I'm now unconvinced about the idea of caching CSS files in `scratch.mit.edu` storage. I'll need to actually implement my idea to see if it's good enough to reduce flashing when using dark mode and/or scratchr2.

**Comment by WorldLanguages** [comment]
I'd need to check if Firefox's new "event pages" (pretty much the equivalent to Chrome's non-persistent background pages) support webRequest. They probably do (Firefox wants WR and WRB to continue working), but Chrome's equivalent doesn't, which is weird.

**Comment by WorldLanguages** [comment]
After some more thought, I'm pretty sure this needs some more discussion before making any changes.
I also forgot chrome.webRequest is used to check whether a page has returned a 200 status code or not. For example, scratchr2 404 pages are matched against scratch.mit.edu/404 even if the real URL is scratch.mit.edu/users/kaj

**Comment by lisa-wolfgang** [comment]
> Maybe this could be an opportunity to add some type of developer mode that if enabled, updates CSS automatically when the files are changed, without having to trigger a refresh or manually reenable addons.

+1 for this. It could be dependent on whether or not the extension is in "prerelease mode."

**Comment by WorldLanguages** [comment]
This issue contains outdated information and does not consider the Cache API. Moving to issue #7449.
