### ISSUE TITLE
Making Scratch Addons mobile friendly 

### ISSUE THREAD

**Issue by Lockstart** [ScratchAddons/ScratchAddons#4562]
Hey! I am currently using my phone to write that. I have Edge, Firefox and Chrome but I can't download scratch add-ons :/

**Comment by Samq64** [comment]
Try Kiwi.

**Comment by RedGuy12** [comment]
We won't add features for the minority. Someone can fork and make a mobile optimized version of SA if they want.

**Comment by WorldLanguages** [comment]
@Lockstart Try Kiwi on Android. Most addons should work.
