### ISSUE TITLE
When link clicked in forum post preview, page opens in preview and user cannot use preview until reload.

### ISSUE THREAD

**Issue by JaydenDev** [ScratchAddons/ScratchAddons#4581]
### Description
Clicking a link in the post preview opens the link, fails, then the user can only use the preview again after reloading.

### Reproduction steps

1. Type a link into the post.
2. Wait for preview to render
3. Click Link

### Expected behavior
The link not open, or at least allow the user to go back
### Actual behavior
Preview becoming unusable
### Screenshots
![image](https://user-images.githubusercontent.com/92550746/168714591-bac7af31-5af7-449d-9714-616fa63a3b10.png)
![image](https://user-images.githubusercontent.com/92550746/168714637-f5f36899-1e19-4d5a-b24e-4505509e5ca3.png)

### Environment
- Browser: Firefox 100.0
- Scratch Addons version: v1.25.1
- Operating system: Windows 11

**Comment by JaydenDev** [comment]
Extra Information

Add-on affected:  Live forum post preview

**Comment by apple502j** [comment]
I think this can occur without Scratch Addons.

**Comment by JaydenDev** [comment]
> I think this can occur without Scratch Addons.

That.. wouldn't make sense. The forum post preview is an add-on in Scratch Addons

**Comment by Chiroyce1** [comment]
> I think this can occur without Scratch Addons.

Yep, I can repro on Firefox v100 with SA completely turned off

https://user-images.githubusercontent.com/97374054/168735176-e3b93895-606e-4d55-a353-ec0f1f93873c.mov

> JaydenDev: *The forum post preview is an add-on in Scratch Addons*

No, the **Live** forum post preview is an add-on, the regular one (forum post preview) where you manually click the tick button to preview is a vanilla scratch forums feature.

**Comment by mxmou** [comment]
This is not caused by Scratch Addons. As a workaround, you can select the entire content of the post, press the Cut shortcut, wait until the preview is removed, then paste it back.

**Comment by JaydenDev** [comment]
Yes, the **live** forum post preview is exactly the module. Without ScratchAddons, this live forum post preview DOESN'T exist. This bug pertains to the addon. It DOES exist!

**Comment by mxmou** [comment]
> **So maybe ScratchAddons can provide a fix to this issue?**

It could, but the purpose of SA isn't fixing Scratch bugs. You can use the workaround I mentioned above.

**Comment by JaydenDev** [comment]
> > **So maybe ScratchAddons can provide a fix to this issue?**
> 
> It could, but the purpose of SA isn't fixing Scratch bugs. You can use the workaround I mentioned above.
Scratch's forums don't get updated or fixed very often, some patches on top of the old system would be good.
