### ISSUE TITLE
[website darkmode] While reporting a filterbot mistake on studio pages, textbox has a light background 

### ISSUE THREAD

**Issue by Chiroyce1** [ScratchAddons/ScratchAddons#4582]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/97374054/168734096-b7191f0b-097a-4d87-9eb7-d3f49aa706ea.png">

Firefox v100, SA v1.25.1

**Comment by mxmou** [comment]
This will be fixed in v1.26.
