### ISSUE TITLE
Search bar in the forums

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#4591]
### Description

I can't see the search bar in the forums

### Reproduction steps

1. I activated the search bar addon both in Chrome and Firefox
2. I went, for example, to [](https://scratch.mit.edu/discuss/) and [](https://scratch.mit.edu/discuss/31/ )
3. I can't see any new search bar (except for the top Scratch search box, in the site navigation bar)

### Expected behavior

A new search bar showing up

### Actual behavior

No new search bar

### Screenshots

<img width="1344" alt="Schermata 2022-05-19 alle 08 56 31" src="https://user-images.githubusercontent.com/2651868/169229707-7df1221f-21bb-4ab6-8508-1e7f39986264.png">
<img width="1344" alt="Schermata 2022-05-19 alle 08 56 09" src="https://user-images.githubusercontent.com/2651868/169229727-03d9afc1-66f7-4409-afe7-0ab6d1b08519.png">

### Environment

- Browsers: Chrome 101.0.4951.64 (x86_64) and Firefox 100.0 (64 bit)
- Scratch Addons version: 1.25.1
- Operating system: macOS BigSur 11.6.1

**Comment by apple502j** [comment]
Already fixed

**Comment by sfederici** [comment]
Will the fix be available in the next release? Or is it already available in the current version?

**Comment by mxmou** [comment]
It will be in 1.26.0.

**Comment by CST1229** [comment]
Shouldn't this be closed as completed (as it's already fixed)?

**Comment by mxmou** [comment]
> Shouldn't this be closed as completed (as it's already fixed)?

I think not planned is the correct close reason for duplicates, even if the original issue is fixed.
