### ISSUE TITLE
Custom Favicon For Scratch Website

### ISSUE THREAD

**Issue by KazookiTV** [ScratchAddons/ScratchAddons#4593]
### Is your request related to a problem? Please describe.
I have a Nord Theme for Scratch and I want the fav-icon to match it too.

### Describe the solution you'd like
I want a Text box in the add-ons page in settings to have the value of any image, make textbox value (the image) the fav-icon thing.

### Additional context
![image](https://user-images.githubusercontent.com/105769130/169534059-67ebe2f1-7178-4112-902a-3a62a9d9083d.png)
![image](https://user-images.githubusercontent.com/105769130/169534084-2156c0dd-1ac7-493b-8d8e-805ea3eeb18e.png)

**Comment by Chiroyce1** [comment]
This seems like a very minor addon - even dark-www doesn't implement a dark version of the favicon, so what is the reason for this? I think implementing the nord theme as a whole would be a better idea...

**Comment by Cool-Scratcher** [comment]
We should change the favicon for different themes, actually. It sounds like a nice touch, but maybe not as an entire addon. Maybe an option in the theme addons? As an option for every single theme...?

**Comment by mxmou** [comment]
Ideally the favicon would match the browser theme, not the Scratch theme, so I don't think this is necessary.

**Comment by KazookiTV** [comment]
> We should change the favicon for different themes, actually. It sounds like a nice touch, but maybe not as an entire addon. Maybe an option in the theme addons? As an option for every single theme...?

That could probably be a good idea

**Comment by WorldLanguages** [comment]
This isn't very Scratch specific - any extension that allows the user to change the favicon in a per-site basis would work.
The only valid reason to do this is to match the favicon with Scratch Addons themes, but as mxmou says, the tab strip should match the browser's theme, and Scratch Addons does not style that part of the browser.
