### ISSUE TITLE
Language option for settings page and popup

### ISSUE THREAD

**Issue by R081N-08** [ScratchAddons/ScratchAddons#4594]
### Is your request related to a problem? Please describe.

The settings page and the extension popup change their language to the user's browser language. This is annoying for those who prefer their browser language to be in their native language, while having Scratch Addons be in English (or something else).

### Describe the solution you'd like

I'm suggesting a new setting under "More Settings" in the bottom left of the settings page, that lets you choose between all available languages, similar to scratchaddons.com.

### Describe alternatives you've considered

It is possible to change your browser language everytime you plan on using Scratch Addons, but this is very inconvenient and a simple language setting would be better to have.

**Comment by RedGuy12** [comment]
The browser offers an easy way to localize extensions that we use outside of addons but it doesn't let us customize the language.

**Comment by WorldLanguages** [comment]
We are aware of this, and this would be already implemented if the technical part was cleaner and easier to migrate.

Duplicate of #2670

**Comment by Norbiros** [comment]
You can already change addons language, by changing this line:
https://github.com/ScratchAddons/ScratchAddons/blob/master/background/l10n.js#L13
But there is problem with translating settings page - we are using chrome's i18n, but we need to create our own system for that.
