### ISSUE TITLE
No images

### ISSUE THREAD

**Issue by piw-piw** [ScratchAddons/ScratchAddons#4599]
Some images aren't loading.
![image](https://user-images.githubusercontent.com/76477070/169683073-c8428749-228b-4c4c-92ba-f3013c68de36.png)

**Comment by Chiroyce1** [comment]
Could you right click on the images that don't load - and then press "Copy Image Link" and paste it here?

**Comment by apple502j** [comment]
Probably translation problems.

**Comment by apple502j** [comment]
Yep, Polish translation bug (no space after placeholder)

**Comment by Norbiros** [comment]
Fixed (on Transifex).
