### ISSUE TITLE
Absolutely Nothing

### ISSUE THREAD

**Issue by AustinMan** [ScratchAddons/ScratchAddons#4601]
I was minding my own business when I checked Scratch, and my Retinas burned, so I taped the Scratch Addons icon and nothing showed up. I waited a bit with no response, so I tapped the gear, it brought me to the page, but there were no options at all. I checked the first page on Github, to no avail, I checked if there was something you guys said on a social media account or something, nothing. I uninstalled the extension and re-installed it, also nothing! So here I am now, wanting to know what the heck to do!

**Comment by scratchusernamemrtbts** [comment]
maybe you forget to give the extension permission to edit the web or something

**Comment by apple502j** [comment]
This looks like a joke report.

**Comment by WorldLanguages** [comment]
@AustinMan If this is serious, provide your browser name and version number

**Comment by AustinMan** [comment]
I did
