### ISSUE TITLE
Replace Sora font with a different one

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#4614]
### Is your request related to a problem? Please describe.

I hate the sora font

### Describe the solution you'd like

Some way to use `system-ui` (no Montserrat or anything, that isn't a neutral font!)

### Describe alternatives you've considered

None

**Comment by Endermaster3690** [comment]
so like, a way to change the font or just hard switch it to a different font?

**Comment by mxmou** [comment]
`system-ui` is already used on scratchaddons.com so I think using it in the extension would make sense.

> so like, a way to change the font or just hard switch it to a different font?

Providing a good default font is better.

**Comment by WorldLanguages** [comment]
@mxmou Do you think Sora is bad?

**Comment by Secret-chest** [comment]
> @mxmou Do you think Sora is bad?

Anyways, why do you need to use such a fancy and ugly font?

**Comment by Hans5958** [comment]
To be honest, Sora would be good for a one-time heading, but not for anything else, other than the niche.

**Comment by Chiroyce1** [comment]
IMO a simple setting that lets you switch between Sora and `system-ui` should be a great solution.

**Comment by mxmou** [comment]
> @mxmou Do you think Sora is bad?

It isn't bad but I don't think it's the best for UI.

> IMO a simple setting that lets you switch between Sora and `system-ui` should be a great solution.

Leaving design choices to the user is not a solution. Even if there is a way to change the font, the better one should be selected by default.

**Comment by WorldLanguages** [comment]
> To be honest, Sora would be good for a ~one-time~ heading, but not for ~anything else~ a default font, other than the niche.

Agreed, now that I think more about it. Also, scratchaddons.com hasn't really used Sora (by default?) for a while (or maybe it never did?), so I can't really say it's part of the "Scratch Addons brand".

I think we could possibly remove Sora from most places, except headings.
And this should be consistent with the website, as well as extension store resources and screenshots. If the "Scratch Addons" header on the popup stays with Sora font, the same header on the website should also use Sora.

**Comment by kccuber-scratch** [comment]
How about Inter? It's a nice simple font and doesn't look all that fancy.
https://github.com/rsms/inter

**Comment by mxmou** [comment]
> How about Inter? It's a nice simple font and doesn't look all that fancy. https://github.com/rsms/inter

It's nice but we aren't currently using it anywhere, unlike `system-ui`.

**Comment by Secret-chest** [comment]
> > How about Inter? It's a nice simple font and doesn't look all that fancy. https://github.com/rsms/inter
> 
> It's nice but we aren't currently using it anywhere, unlike `system-ui`.

No, no and no. It's fancy and it sucks. Its shapes are too robotic.

**Comment by WorldLanguages** [comment]
Doesn't `system-ui` depend on the OS? There's no single `system-ui` font in the world, right?

**Comment by lisa-wolfgang** [comment]
> Doesn't `system-ui` depend on the OS? There's no single `system-ui` font in the world, right?

It's Segoe UI on Windows, SF Pro on macOS, and whatever the system default is on the given distribution of Linux. And distribution defaults vary widely.

In my opinion, leaving such a critical design decision up to an entirely unrelated piece of software (the user's operating system) is a terrible idea. What design goals does Scratch Addons, a browser extension used to modify a block-based programming website, have in common with Windows or macOS, operating systems used for the vast majority of a person's computing?

**Comment by mxmou** [comment]
> In my opinion, leaving such a critical design decision up to an entirely unrelated piece of software (the user's operating system) is a terrible idea. What design goals does Scratch Addons, a browser extension used to modify a block-based programming website, have in common with Windows or macOS, operating systems used for the vast majority of a person's computing?

I think there are enough reasons to use the system font provided by the OS:
* System fonts are designed to be easy to read as they're often used at small sizes.
* A system font usually has good language support.
* Browsers use it too, so SA won't look out of place.
* scratchaddons.com already uses it because it's the default in Bootstrap.

If we keep Sora in some places as W_L suggested, I don't think looking slightly different on different platforms is a problem if that means it looks good on all platforms. If we decide that consistency is more important, we could use a generic font like Roboto.

**Comment by Secret-chest** [comment]
> > > How about Inter? It's a nice simple font and doesn't look all that fancy. https://github.com/rsms/inter
> > 
> > It's nice but we aren't currently using it anywhere, unlike `system-ui`.
> 
> No, no and no. It's fancy and it sucks. Its shapes are too robotic.

Please be aware of this. Roboto is nice.

**Comment by WorldLanguages** [comment]
> Please be aware of this. Roboto is nice.

@Secret-chest Aware of what? You said you dislike the shapes of `system-ui`, but that depends on your OS! There's no single font called `system-ui`.

**Comment by Secret-chest** [comment]
> > Please be aware of this. Roboto is nice.
> 
> @Secret-chest Aware of what? You said you dislike the shapes of `system-ui`, but that depends on your OS! There's no single font called `system-ui`.

I said I dislike inter @WorldLanguages

**Comment by lisa-wolfgang** [comment]
This discussion isn't going anywhere -- not one concrete reason has been presented against Sora. The main reasons have been that "it looks bad" and "it's not the best," but a font decision needs to depend on more substantive reasoning than that.

**Comment by BroJac5246** [comment]
> This discussion isn't going anywhere -- not one concrete reason has been presented against Sora. The main reasons have been that "it looks bad" and "it's not the best," but a font decision needs to depend on more substantive reasoning than that.

I agree. Having not previously participated in this discussion, I can say that this is pointless and a waste of time. Unless a good reason to change the font is presented or an agreed-upon amazing font is found, this will get nowhere and is ultimately pointless.

**Comment by Secret-chest** [comment]
Sora is hard to read

**Comment by WorldLanguages** [comment]
Well, extension webpages can't be styled by other extensions, so we should at least add some hidden toggle to change the font to a more standard one, IMO.
However, changing the default font is a better idea than adding a setting to change the appearance of the UI. So I think it should be changed, at some point.

**Comment by WorldLanguages** [comment]
There has been some discussion about this on Discord around 1 month ago. No one there was actively in favor of keeping Sora, I think.

**Comment by Secret-chest** [comment]
What font would you choose then? Montserrat has been suggested, but it's very wide. My favourite is Roboto (and Source Sans Pro, but that works better for articles, not UI)

**Comment by Secret-chest** [comment]
UIs should use generic fonts. Find me an Android app that uses Sora.

**Comment by lisa-wolfgang** [comment]
The most important factors in font selection should be readability and language support. Aesthetic is secondary to function.

**Comment by WorldLanguages** [comment]
> What font would you choose then? Montserrat has been suggested, but it's very wide. My favourite is Roboto (and Source Sans Pro, but that works better for articles, not UI)

PR #4656 replaces Sora with Roboto.

**Comment by Secret-chest** [comment]
> > What font would you choose then? Montserrat has been suggested, but it's very wide. My favourite is Roboto (and Source Sans Pro, but that works better for articles, not UI)
> 
> PR #4656 replaces Sora with Roboto.

I knew already.
