### ISSUE TITLE
Addon option presets

### ISSUE THREAD

**Issue by ZenithRogue** [ScratchAddons/ScratchAddons#462]
**Describe the solution you'd like**
I would like the ability to preset options for addon settings

These presets would be dropped into the `addon.json`, and would overwrite any of the user defined values

This would be an especially useful addition for Theme3, and would allow easy implementation of #459 

Preview of concept:
![image](https://user-images.githubusercontent.com/11393734/95667581-b13e0e00-0b2d-11eb-8bff-8398f18a5465.png)

Accompanying json
```json
{
  "presets": [
    {
      "name": "Scratch 2.0 colors",
      "id": "colors2",
      "values": {
        "motion-color": "#4C97FF",
        "looks-color": "#9966FF",
        "sounds-color": "#CF63CF"
      }
    },
    {
      "name": "Another Preset idk",
      "id": "anotheridk",
      "values": {
        "motion-color": "#4C97FF"
      }
    }
  ]
}
```

**Alternate solutions**
To prevent the `addon.json` file from being overwhelmed, another option could be to have the presets located in their own individual preset files
```json
{
  "presets": [
    {
      "name": "Scratch 2.0 colors",
      "id": "colors2",
      "url": "preset.json"
    },
    {
      "name": "Another Preset idk",
      "id": "anotheridk",
      "url": "idk.json"
    }
  ]
}
```

**Comment by GrahamSH-LLK** [comment]
Cool! That's a great idea! I can just imagine all kinds of new uses for this!

**Comment by ZenithRogue** [comment]
Importing and exporting presets would be neat af as well

**Comment by WorldLanguages** [comment]
@ZenithRogue re: reset to default addon settings, that could be a button next to the presets. "default" is technically a preset.
