### ISSUE TITLE
Does Scratchaddons still work on Firefox?

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#4624]
### Description

Since today, the Scratchaddons settings page doesn't work in Firefox

### Reproduction steps

Open settings page

### Actual behavior

See picture 
<img width="1344" alt="Schermata 2022-05-31 alle 12 06 26" src="https://user-images.githubusercontent.com/2651868/171149827-2fe738ec-f879-409f-a515-d17918ed2699.png">

### Environment

- Browser: Firefox 100.0.2 (64 bit)
- Scratch Addons version: 1.26.0
- Operating system: macOS BigSur

**Comment by Weredime** [comment]
![image](https://user-images.githubusercontent.com/100447465/171154853-37b7c6b5-f472-4836-8353-0972ed5783c4.png)
Works for me

**Comment by apple502j** [comment]
@sfederici We need some more info:

1. Go to `about:debugging`
2. On This Firefox section, find SA, click Inspect
3. Go to console
4. Copy everything and paste here

**Comment by apple502j** [comment]
Also, check the console of the settings page too (F12 on settings page), and copypaste stuff here

**Comment by sfederici** [comment]
>     4. Copy everything and paste here

La risorsa con indirizzo “moz-extension://3ca06691-4118-ca40-b2c5-f3f3cbf63c92/libraries/thirdparty/Sora/latin-ext.400.woff2”, precaricata con “link preload”, non è stata utilizzata entro un intervallo di alcuni secondi. Assicurarsi che tutti gli attributi del tag preload siano impostati correttamente. [index.html](moz-extension://3ca06691-4118-ca40-b2c5-f3f3cbf63c92/webpages/settings/index.html)
La risorsa con indirizzo “moz-extension://3ca06691-4118-ca40-b2c5-f3f3cbf63c92/libraries/thirdparty/Sora/latin-ext.600.woff2”, precaricata con “link preload”, non è stata utilizzata entro un intervallo di alcuni secondi. Assicurarsi che tutti gli attributi del tag preload siano impostati correttamente. [index.html](moz-extension://3ca06691-4118-ca40-b2c5-f3f3cbf63c92/webpages/settings/index.html)
La risorsa con indirizzo “moz-extension://3ca06691-4118-ca40-b2c5-f3f3cbf63c92/libraries/thirdparty/Sora/latin.400.woff2”, precaricata con “link preload”, non è stata utilizzata entro un intervallo di alcuni secondi. Assicurarsi che tutti gli attributi del tag preload siano impostati correttamente.

**Comment by sfederici** [comment]
> Also, check the console of the settings page too (F12 on settings page), and copypaste stuff here

La risorsa con indirizzo “moz-extension://3ca06691-4118-ca40-b2c5-f3f3cbf63c92/libraries/thirdparty/Sora/latin-ext.400.woff2”, precaricata con “link preload”, non è stata utilizzata entro un intervallo di alcuni secondi. Assicurarsi che tutti gli attributi del tag preload siano impostati correttamente. [index.html](moz-extension://3ca06691-4118-ca40-b2c5-f3f3cbf63c92/webpages/settings/index.html)
La risorsa con indirizzo “moz-extension://3ca06691-4118-ca40-b2c5-f3f3cbf63c92/libraries/thirdparty/Sora/latin-ext.600.woff2”, precaricata con “link preload”, non è stata utilizzata entro un intervallo di alcuni secondi. Assicurarsi che tutti gli attributi del tag preload siano impostati correttamente. [index.html](moz-extension://3ca06691-4118-ca40-b2c5-f3f3cbf63c92/webpages/settings/index.html)
La risorsa con indirizzo “moz-extension://3ca06691-4118-ca40-b2c5-f3f3cbf63c92/libraries/thirdparty/Sora/latin.400.woff2”, precaricata con “link preload”, non è stata utilizzata entro un intervallo di alcuni secondi. Assicurarsi che tutti gli attributi del tag preload siano impostati correttamente. [index.html](moz-extension://3ca06691-4118-ca40-b2c5-f3f3cbf63c92/webpages/settings/index.html)

​

**Comment by apple502j** [comment]
@sfederici What happens when you reload the page while you have both consoles open? (Copy-paste everything, not just yellow/red stuff)

**Comment by Norbiros** [comment]
I am using Firefox 95.0.1, and everything works correctly.
Did you change something today/yesterday on your computer? Maybe new update? New firefox version?
Addons work correctly (maybe it is bug with just settings page)?

**Comment by TheColaber** [comment]
Maybe this is a bug in Firefox 100.0?

**Comment by Norbiros** [comment]
Nope, because in this issue #4591 @sfederici was using Firefox 100.0 (64 bit), and everything worked. It can be error with Firefox 100.0.2...

**Comment by WorldLanguages** [comment]
@sfederici Was the issue fixed after a reboot?

**Comment by sfederici** [comment]
Yes, I rebooted the mac right now, and it works. Is this a problem that you are aware of?

**Comment by apple502j** [comment]
Seems like a general browser instability issue.

**Comment by kccuber-scratch** [comment]
This happened to me before, but instead of having to restart the browser it magically started to work again for me. It was really weird.
