### ISSUE TITLE
Clone counter addon can show negative amount of clones

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4635]
> It says I have -3 clones. It worked after I reloaded.

https://github.com/ScratchAddons/ScratchAddons/blob/master/addons/clones/userscript.js#L47

**Comment by apple502j** [comment]
Hmm, how did this happen 🤔 
The only way to cause this is by dynamic-enabling clones addon after deleting sprites

**Comment by jeffalo** [comment]
A quick hack could be to just hide the clone count when it's less than or equal 0 (rather than hiding when it's exactly 0). It would probably be inaccurate after that though.

**Comment by CST1229** [comment]
> A quick hack could be to just hide the clone count when it's less than or equal 0 (rather than hiding when it's exactly 0). It would probably be inaccurate after that though.

Possibly manually recalculate the clone count if the clone count dips below 0.

**Comment by WorldLanguages** [comment]
> It would probably be inaccurate after that though.

We could show `clones: ?` and expect the user to reload if they want an accurate clone count.
