### ISSUE TITLE
A method to tell people about news and updates

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#464]
**Is your feature request related to a problem? Please describe.**

So far there is **no** method to tell users about news and updates related to Scratch Addons. No Scratch forums (of course), no Twitter account, no blogs, no subreddits, and heck, even no Discord server! It's only GitHub and the stores, and it's just limited to extension updates ~~(oh wait, there's even **zero** information about the new versions! #463)~~

**Describe the solution you'd like**

Give at least one method/channel to tell users about news and updates of Scratch Addons, preferably from either Twitter or Discord.

**Comment by GrahamSH-LLK** [comment]
How about a blog that is linked to inside of the addon on every update?

**Comment by ahmetlii** [comment]
Can't we just send notification from the addon?

**Comment by pufferfish101007** [comment]
> Can't we just send notification from the addon?

But some users won't want notifications, they could opt in, but it's not really a viable solution for everyone.

**Comment by Hans5958** [comment]
> 
> 
> Can't we just send notification from the addon?

No, it would be harder to maintain it than having a Twitter/Discord page.

**Comment by apple502j** [comment]
We have a Discord server and a subreddit. Closing as resolved.

**Comment by TheColaber** [comment]
> We have a Discord server and a subreddit. Closing as resolved.

No, I think they wanted a way to talk to the clients?

**Comment by Hans5958** [comment]
Reopening this issue as (a) Discord is out of the question because WL won't allow the public and (b) I'm not sure if the sub is prepared for it, let alone even legal. Please close whether we have some sort of reliable way to do it.

**Comment by apple502j** [comment]
(a) Discord is not out of the question because it is public (invite is on README anyway) and (b) Reddit is not illegal in Argentina, Japan, US or UK.

**Comment by Hans5958** [comment]
> 
> 
> (a) Discord is not out of the question because it is public (invite is on README anyway) and (b) Reddit is not illegal in Argentina, Japan, US or UK.

(a) Not exactly. According to WL is that the link is there "just for developers." Even thought I agree that it also makes it public, but somehow it's okay to put the Discord link on there and not okay on the website.
(b) Illegal as in Scratch. Apologise for the confusion.

**Comment by apple502j** [comment]
Any website referencing Scratch Addons is illegal according to the ST.

**Comment by Hans5958** [comment]
Yes..., so?

**Comment by TheColaber** [comment]
Would be cool if we had something like https://scratchaddons.com/blog where we could update it with new things for the people

**Comment by GrahamSH-LLK** [comment]
Jekyll blogs are easy, I could do  it

**Comment by thecoder876** [comment]
> Jekyll blogs are easy, I could do it

But it's going to be on the website, isn't it?

**Comment by thecoder876** [comment]
> Any website referencing Scratch Addons is illegal according to the ST.

So, closing this again?

**Comment by GrahamSH-LLK** [comment]
> > Jekyll blogs are easy, I could do it
> 
> But it's going to be on the website, isn't it? The website uses HTML, not Jekyll.

🤦 Jekyll is the software that _builds_ our site, not a language.

**Comment by GrahamSH-LLK** [comment]
> > Any website referencing Scratch Addons is illegal according to the ST.
> 
> So, closing this again?

That just means we can't link to it on Scratch

**Comment by thecoder876** [comment]
> > > Jekyll blogs are easy, I could do it
> > 
> > 
> > But it's going to be on the website, isn't it? The website uses HTML, not Jekyll.
> 
> 🤦 Jekyll is the software that _builds_ our site, not a language.

It can be used as a language, only that's not the case with Scratch Addons.

**Comment by GrahamSH-LLK** [comment]
> > > > Jekyll blogs are easy, I could do it
> > > 
> > > 
> > > But it's going to be on the website, isn't it? The website uses HTML, not Jekyll.
> > 
> > 
> > 🤦 Jekyll is the software that _builds_ our site, not a language.
> 
> It can be used as a language, only that's not the case with Scratch Addons.

No, Jekyll isn't a language...

**Comment by jeffalo** [comment]
nxut.

**Comment by GrahamSH-LLK** [comment]
> nuxt.
> 
> (+ tailwind?)

Do _you_ want to rewrite the entire site?

**Comment by jeffalo** [comment]
> > nuxt.
> > (+ tailwind?)
> 
> Do _you_ want to rewrite the entire site?

blog.scratchaddons.com could be a seperate site

**Comment by TheColaber** [comment]
> > > nuxt.
> > > (+ tailwind?)
> > 
> > 
> > Do _you_ want to rewrite the entire site?
> 
> blog.scratchaddons.com could be a seperate site

That's a good idea

**Comment by jeffalo** [comment]
also we now have the youtube channel

**Comment by WorldLanguages** [comment]
@Hans5958 Do you consider this issue resolved? We're now sending update notifications (not following all 100% considerations of your recent issue, but getting pretty close)

**Comment by Hans5958** [comment]
> 
> 
> @Hans5958 Do you consider this issue resolved? We're now sending update notifications (not following all 100% considerations of your recent issue, but getting pretty close)

Well, I wasn't satisfied with this implementation, because it's just a single notification for the updates, and that's it. Even so, I was satisfied that now people become more aware with the updates.

But, there's one more thing. How about the news?

**Comment by jeffalo** [comment]
> How about the news?
perhaps short (<120second)  video clips that members of the SA team can make for updates. like "helo im jeffalo and i just added a pause button", etc. we can use our newly popular YouTube channel for rgat

> one has servers to host one that I am sure that it could last for some time.
nuxt has static site generation which turns it into something we can put on gh-pages or vercel or whatever

**Comment by TheColaber** [comment]
@Hans5958 Would you consider this as resolved? We have had a community discord server for a while where we share updates with the community and have people beta test upcoming features. We have almost 100 members so I would say this is resolved. The server link is also on the website, but here it is... https://discord.gg/2qKGg5gGAh

**Comment by Hans5958** [comment]
Reopening for #2620. In summary, @lisa-wolfgang thinks that it is not enough.
