### ISSUE TITLE
Hide/Show Mouse

### ISSUE THREAD

**Issue by ProjectConsolia** [ScratchAddons/ScratchAddons#4641]
Hi! I would like if you add the ability to hide/show the mouse!

**Comment by Chiroyce1** [comment]
Is this an idea for a new block that implements this functionality, or just as an addon?

**Comment by ProjectConsolia** [comment]
Hi! Sorry for the late reply but yes it's for a new block.

**Comment by CST1229** [comment]
Wouldn't work for people not using the addon.

**Comment by mxmou** [comment]
Duplicate of #4122 (specifically "a custom block or variable that project creators can use to manually change cursor behavior")
