### ISSUE TITLE
Add a variable representing the sprite effect strength

### ISSUE THREAD

**Issue by tbarkai** [ScratchAddons/ScratchAddons#4642]
It would be nice to have access to more elements of the sprite's state.
This can be useful, for example, to program the rate of change of a specific effect, depending on its progression. This way, we could program "ease-in", "ease-out" and similar transitions.
Another place where this information could be useful is when you click the "change color" block several times until you find the color you want, but then you don't know what is the number of the color you've reached.

A simple solution could be to add a variable with dropdown under the "Looks" category that shows the current numeric value of the effect. (similar to the existing "size" or "costume name/number")

![image](https://user-images.githubusercontent.com/3757923/172042009-60ee4f00-f079-4b1d-9346-269164cda865.png)

**Comment by CST1229** [comment]
Wouldn't work for people not using the addon.
