### ISSUE TITLE
New lines on Ocular Statuses causes interference with the profile UI

### ISSUE THREAD

**Issue by Chiroyce1** [ScratchAddons/ScratchAddons#4643]
With 2.0 -> 3.0 enabled
<img width="990" alt="image" src="https://user-images.githubusercontent.com/97374054/172053945-4d4bb9b9-de9c-4fa0-8bec-7a1c823e8540.png">

and without
<img width="983" alt="image" src="https://user-images.githubusercontent.com/97374054/172053953-187b0c11-7323-427a-ae82-3af2a7a645a9.png">

[profile](https://scratch.mit.edu/users/9gr/)

Not really a bug, but if we're able to filter out new lines it'd be much better.

**Comment by Weredime** [comment]
Haha (I was abusing a ~bug~ feature. Just wanted to try it again)

No ocular users can actually put newlines.

**Comment by mxmou** [comment]
A large number of lines could also make unnecessary space on the forums.

**Comment by RedGuy12** [comment]
@jeffalo maybe newlines should be restricted on the my-ocular side
