### ISSUE TITLE
Custom blocks menu

### ISSUE THREAD

**Issue by piw-piw** [ScratchAddons/ScratchAddons#4644]
You can write menus in Json:

```
sa-menu_blocks:{"side":["left","right"]}
```
Default:
![image](https://user-images.githubusercontent.com/76477070/172190576-42ab61b3-51ca-4ed0-a71b-6ff682d554f9.png)
With custom menu:
![image](https://user-images.githubusercontent.com/76477070/172190351-3350e762-5c7b-4ee4-b9d2-1e6886e30c1b.png)
(With dropdown arrow, like there: ![image](https://user-images.githubusercontent.com/76477070/172191659-3954aa32-3278-4218-969f-1309dcb95a1b.png))

**Comment by apple502j** [comment]
I don't think this is possible, and that doesn't look like it's easy to use.

**Comment by piw-piw** [comment]
@mxmou Why?

**Comment by Secret-chest** [comment]
> @mxmou Why?

@apple502j Why?
