### ISSUE TITLE
Enabling a setting that adds a userstyle does not dynamically enable the addon

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#4665]
### Description

CSS variables for addon settings are only set if any of the addon's userstyles are active on the page. If those userstyles depend on a setting, enabling that setting doesn't set the CSS variables. This affects `editor-theme3`.

### Reproduction steps

1. Enable "customizable block colors" and disable "change the colors of blocks in the forums".
2. Go to https://scratch.mit.edu/discuss/topic/574329/
3. Enable "change the colors of blocks in the forums". The blocks will not have correct colors because the CSS variables are missing.

### Environment

- Browser: Edge 102
- Scratch Addons version: tested on 1.26.0 and current master
- Operating system: Windows

**Comment by apple502j** [comment]
This has a much bigger problem; such action does not cause the addon to be marked as enabled.
