### ISSUE TITLE
[v1.27.0] Add "new" tag to hide-flyout, consider other changes

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4668]
#4506 fixes a lot of bugs, and this addon is the least used recommended addon (#4100), so we should consider showcasing it so more users can enjoy it, even tho it doesn't have any new settings.

We could also consider rephrasing the current notice. It currently goes:
> "Palette area hover" mode only extends the viewing area. If you want to be able to drag blocks into that area without them getting trashed, use one of the other modes.

We could also consider
1. Changing the default mode
2. ~~Adding a notice reminding users to reload the page when switching modes (there's no setting autorefresh, and most addons support this, so it might be confusing)~~ Fixed by #4752

**Comment by mxmou** [comment]
> We could also consider rephrasing the current notice. It currently goes:
> 
> > "Palette area hover" mode only extends the viewing area. If you want to be able to drag blocks into that area without them getting trashed, use one of the other modes.

The notice can be removed if we change the default mode. I think category hover is the most useful one.

> Adding a notice reminding users to reload the page when switching modes (there's no setting autorefresh, and most addons support this, so it might be confusing)

Ideally we would add that feature before advertising the addon.

There are a few other things I think it would make sense to do now:
* Dynamic enable/disable
* Adding a close button to the category click mode - one currently needs to find the highlighted category and click it to close the palette.
* Using different animations depending on the mode and whether columns is enabled.

**Comment by WorldLanguages** [comment]
> Using different animations depending on the mode and whether columns is enabled.

I think it's time we make a graph/list stating what other addons should be considered when developing each addon. It would help us with testing, considering more edge cases when developing, and proper addon messaging and advertising. 
The pair `hide-flyout` and `columns` form is pretty interesting and we should take it into account.

**Comment by WorldLanguages** [comment]
`cloud-games` could have a new info type info message that mentions you can go to a project/studio to add it to the list automatically.
