### ISSUE TITLE
Only show link to user profile if user exists

### ISSUE THREAD

**Issue by pufferfish101007** [ScratchAddons/ScratchAddons#468]
**Is your feature request related to a problem? Please describe.**

When using the user search addon, the profile tab still gets added even if the user doesn't exist. This could be confusing when it goes to a 404 page.

**Describe the solution you'd like**

Fetch the user page, if it doesn't have a `200` status code then don't add the tab.

**Describe alternatives you've considered**

Rather than not adding the tab, we could just disable it or add a message when it's clicked saying that this user doesn't exist or something.

**Additional context**

I won't make a pr yet, as I don't know whether we want this or not, or want to do an alternative, but you can see the changes at https://github.com/pufferfish101007/ScratchAddons/blob/user-search-enhancement/addons/search-profile/userscript.js

**Comment by WorldLanguages** [comment]
This would be a nice addition, problem is, there's no way to know if a profile exists with 100% certainty (not a user - a profile) without requesting to scratchr2. The Scratch API (api.scratch.mit.edu) wouldn't work for this, since it would say kaj exists, when there's no profile for kaj. And requesting scratchr2 is pretty slow 🤔

**Comment by JeffaloBob** [comment]
request their profile comment api and if the user gets logged out then the account doesn't exist (/s)

**Comment by pufferfish101007** [comment]
Ok, so I've done some experimenting, and lefty's api (`https://scratchdb.lefty.one/v2/user/info/[user]`) returns `"id": null` for kaj, and the id of the user for everyone else. So this could work!
The reslonse time is about halfway between api.scratch.mit.edu and scratchr2, so that's not too bad. What do you think?

**Comment by GrahamSH-LLK** [comment]
What about super recently created accounts, or new scratchers?
