### ISSUE TITLE
Project title in editor is unreadable if the menu bar background is light

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#4685]
> The text won't turn black if the menu bar is light (image in thread)
![image](https://user-images.githubusercontent.com/72760579/174455830-eedb9c04-d363-4885-90f2-57312d38469f.png)

> i just changed the top bar color in editor to a lighter color
compared to the see inside button, which you can see in the right, the text stays white

**Comment by mxmou** [comment]
This affects the built-in "Scratch 1.x" preset. The text color on the remix button is also wrong:
![image](https://user-images.githubusercontent.com/51849865/209939988-67980a65-63ee-43ff-8961-910e070be0b6.png)
