### ISSUE TITLE
"Delete others" button on costumes and sounds context menu

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4692]
This option is useful for deleting all costumes/sounds from a sprite. To delete all costumes, you create a new one, then right click it and choose "delete others" (sprites must have at least 1 costume). To delete all sounds, you right click any and choose "delete others", then delete the remaining one manually.

Old implementation available at #3406 (before the existence of `addon.tab.createEditorContextMenu` #3429 and `addon.tab.createModal` - we should use those now)

**Comment by penguinmoose** [comment]
Good idea. I always need to delete a lot of unneeded costumes or sounds.

There should be some kind of confirmation popup, maybe even as simple as JS `confirm()`. There’s a chance people might select the delete others option by accident.
