### ISSUE TITLE
Move the sprite search box to the bottom

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#4710]
My suggestion is to move the sprite search box added by the `search-sprites` addon to the bottom edge. This would put it under the add sprite button, where you get the bonus of not having that button obscure sprites. Or alternatively, there could just be a separate addon to help with that.

Old example:

![Search field with text "Search sprites" next to add sprite button](https://user-images.githubusercontent.com/106490990/175842605-cb295640-4a24-4a73-9fd8-838fead4aae9.png)

New example:

![Scratch's sprite library search bar but next to the add sprite button](https://user-images.githubusercontent.com/106490990/176255761-6e43c450-9997-4345-b966-eea7a9d94dfe.png)

(Not to the bottom where you have to scroll down. Just have it float next to the add sprite button.)

**Comment by WorldLanguages** [comment]
@BarelySmooth What do you think?

**Comment by Secret-chest** [comment]
Search boxes at the bottom are weird. The add sprite button should be moved to the top instead.

**Comment by mxmou** [comment]
> Search boxes at the bottom are weird. The add sprite button should be moved to the top instead.

Moving the add button doesn't make sense because other similar buttons (for costumes, backdrops, sounds) are all at the bottom. I think the current layout is good.

**Comment by BarelySmooth** [comment]
I don't think this is necessary because most UIs have the search bar on the top. 

the sprite library, for example:
<img width="887" alt="Screenshot 2022-06-27 at 17 47 41" src="https://user-images.githubusercontent.com/83728060/175957030-75953193-49ff-40f2-812a-727e04cfb486.png">

This implementation might also make the search bar a lot bigger that it currently is, which could be a problem on smaller devices.

**Comment by DNin01** [comment]
@BarelySmooth I actually wasn't referring to the one in the sprite library, but the one Scratch Addons added to the sprites list.

**Comment by WorldLanguages** [comment]
I also feel the search sprites search bar is too big. But I wouldn't say it's too tall, idk... It might be a perception issue because the bar takes the whole horizontal space.

**Comment by DNin01** [comment]
> I also feel the search sprites search bar is too big. But I wouldn't say it's too tall, idk... It might be a perception issue because the bar takes the whole horizontal space.

Yeah, I agree. I wasn't planning to settle on that example, that's just all I did at the time. I'll see if I can do it another way in a little bit.

**Comment by DNin01** [comment]
#### Here you go.

![Scratch's sprite library search bar but next to the add sprite button](https://user-images.githubusercontent.com/106490990/176255761-6e43c450-9997-4345-b966-eea7a9d94dfe.png)

**Comment by WorldLanguages** [comment]
Maybe the search icon could be next to the "add sprite" icon, and a search bar like that would expand when clicked?

**Comment by Secret-chest** [comment]
Could you make it customizable?

**Comment by WorldLanguages** [comment]
> it could obscure more sprites if it wasn't positioned below the list 

Good point! This can happen with the current version of search-sprites (when there's exactly 10 sprites, on my case): 

![image](https://user-images.githubusercontent.com/17484114/176558792-b8afcc83-cae7-46c9-b5c1-18320fea1e25.png)
