### ISSUE TITLE
New addon: replace all website and editor icons with material icons

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#4720]
### Is your request related to a problem? Please describe.

Scratch icons (scratch website and editor) ~~suck~~ look very bubbly and strange to me. They are worse than Bootstrap icons, which are worse than Font ~~Not~~ Awesome.

### Describe the solution you'd like

Replace them with the material design icons. Not material symbols because material you ~~sucks more~~ makes me dizzy. [These material icons.](https://materialdesignicons.com)

This could be done by editing the SVG files.

**Comment by Secret-chest** [comment]
@World_Languages

**Comment by apple502j** [comment]
Rejected

**Comment by Endermaster3690** [comment]
> > Scratch's icons are designed to look good on Scratch. I don't think there should be an addon that only changes icons and keeps the rest of the design the same.
> 
> I don"t understand.

Scratch's icons are designed to look good on Scratch. He doesn't think there should be an addon that only changes icons and keeps the rest of the design the same.
