### ISSUE TITLE
addonSettings can reach chrome.storage.sync per-key size limit

### ISSUE THREAD

**Issue by owoguy** [ScratchAddons/ScratchAddons#4721]
i lose all of my settings that take forever to set up.

**Comment by Norbiros** [comment]
Okay, can you send us your chrome version and os version?
This bug happens to other extensions with settings too?
When they corrupt? When you are restarting your computer/browser?

*If you want to fix this bug fast, just export settings, save them in file and import them.*

**Comment by WorldLanguages** [comment]
This is probably a Chrome bug unrelated to us, but it would be great to understand why we have started getting feedback about this yesterday? New Chrome update?

**Comment by mxmou** [comment]
Chrome limits the size of a single item in sync storage to 8192 bytes and `addonSettings` can exceed that.

**Comment by apple502j** [comment]
Oh no, did we actually reach the limit? Time flies.

**Comment by apple502j** [comment]
By default the setting is 6037 bytes. We should compress or split them.
