### ISSUE TITLE
columns: Clicking below the flyout scrollbar scrolls up

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#4727]
### Description

If two-column category menu is enabled, clicking anywhere in the space below the scrollbar in the block palette scrolls up.

### Reproduction steps

1. Enable the "two-column category menu" addon.
2. Switch to a block category that isn't motion so that it's possible to scroll up.
3. Click the space below the block palette scrollbar.

### Expected behavior

The scrollbar would move down.

### Actual behavior

The scrollbar moves up.

### Environment

Edge 103 on Windows

**Comment by DNin01** [comment]
Upon further investigation, the scroll bar does different things depending on where below it you click. If you click a little below the scroll bar, it scrolls up, like you said. If you click a little lower, it doesn't do anything. If you click even lower, it scrolls down as expected. This tells me that the code that handles this behavior thinks the scroll bar is lower than it actually appears to be.

<sub>Edge 111, Windows 10, TurboWarp Addons version `f31e959`</sub>

**Comment by DNin01** [comment]
I just tried something that moved the block palette down in the Scratch desktop app and the same thing happened - you could drag the scroll bar normally but clicking above/below the scroll bar would not behave as expected, so this could actually be caused by Scratch. Probably still fixable, though.
