### ISSUE TITLE
Palette area hover isn't working

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#4736]
### Description

When Auto-hiding block palette is enabled on the dev version, the palette area hover and category hover settings do same

### Reproduction steps

1. Enable Auto-hiding block palette
2. Set the mode to "palette area hover"
3. Open the editor
4. Hover over the block palette area, nothing happens
5. Over over the category menu, the palette opens

### Expected behavior

The block palette should open when hovering over the block palette area.

### Actual behavior

Hovering over the block palette area does nothing.

### Screenshots

https://user-images.githubusercontent.com/81489795/176572169-7ba9f406-eeaa-4478-a84c-eca8ee8a7087.mp4

### Environment

- Browser: Chromium 103
- Scratch Addons version: 52935e92faf1488faceab2b48d443165c61e8961
- Operating system: Ubuntu 22.04

**Comment by apple502j** [comment]
Regressed in https://github.com/ScratchAddons/ScratchAddons/commit/a8831eb52e20de30936441790393927be0c2f913 perhaps?
