### ISSUE TITLE
Warn users before posting "scratch addons" on forums

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4746]
It's happening [quite a lot](https://ocular.jeffalo.net/search?q=%22scratch%20addons%22&sort=newest), and apparently the Scratch forums don't have a list of filtered words like comments, so the ST can't easily block it like they did with comments.

We already warn the user when about to comment "scratch addons", so we should reuse the code and do the same for posting forum topics.

**Comment by WorldLanguages** [comment]
We already add a notice when posting to bugs&glitches asking users to please disable SA and check if the bug happens on vanilla Scratch. Unfortunately, some users mention "this happens with Scratch Addons disabled" on their post after reading that, breaking extension policy accidentally.

**Comment by mxmou** [comment]
I think this would be helpful - the ST usually sends an alert with a link to the browser extension policy but sometimes nobody reports the post.

> apparently the Scratch forums don't have a list of filtered words like comments, so the ST can't easily block it like they did with comments

They do. There isn't an easy way to add new words to the list because it's hardcoded.
