### ISSUE TITLE
Requested new features for the Turbowarp player addon sumed up

### ISSUE THREAD

**Issue by OregSamSas** [ScratchAddons/ScratchAddons#4766]
### Is your request related to a problem? Please describe.

I always feel frustrated when things are not organized completely. (Now, it's surely not the very case, just I also like summaries, so here I'll create one. Also, if a PR needs an issue first, I'll create one.) There were several requests for the addon `turbowarp-player`, and now I want to list them here:

1.  #4005: customizable parameters for the player
2. #1439: adding HQ Pen to the previous request might solve this too (or at least gives a step forward)
3. https://discord.com/channels/806602307750985799/989883835900657737: mixed feature, being able to choose on every page the button's behaviour, like with a Shift+click (or other modifier keys, thinking of especially the control key)
4. https://discord.com/channels/806602307750985799/964100204309647370: Again, more TurboWarp settings!
5. #3985: Automatically execute the button's function

### Describe the solution you'd like

Implement as much of them as possible.

### Describe alternatives you've considered

Implement as much of them as impossible.

### Additional context

I've made some code for them in my repo, I will create a PR for this.

**Comment by apple502j** [comment]
Duplicate, closed. Please comment on those issues instead.

**Comment by OregSamSas** [comment]
> Duplicate, closed. Please comment on those issues instead.

Totally understood, just the question is: then in my PR, resolve them all (I created for it, just I didn't have enough time to submit my code, etc.)? Ok I can do it (at least I hope I'm able to resolve more issues at once).

**Comment by OregSamSas** [comment]
> Resolving multiple issues in a single PR is allowed as long as they are all related. So resolving all the issues you mentioned here in the same PR would be OK.

@apple502j @RedGuy12  Danke sehr, super Danke, für alles (tyvm for everything, especially the patience and understanding you have shown me with answering my not-the-best questions continuously. (I'm not sure about show and continuously is the words I'm looking for, but maybe it's still comprehensible)). And also apologies for the inconveniences I may have caused with this duplication.

**Comment by WorldLanguages** [comment]
No worries.
