### ISSUE TITLE
Change variable names to maintain consistensy

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#478]
This is the continuation of #228 and #288 (wow, what a coincidence!), because somehow it wasn't taken seriously.

**Is your feature request related to a problem? Please describe.**

There is an issue where the variables have inconsistent names, either on case, and even naming, probably because they are implemented hastily.

**Describe the solution you'd like**

Let's fix those inconsistencies.

**Firstly**, the options/settings, we need to decide which term to use.

**Secondly**, the case. I propose using camelCase instead of snake_case due to reasons.

1. camelCase is more often used in modern configuration files and manifest files, such as Prettier, ESLint, Node.js, VS Code, and, heck, even Scratch projects.
2. It looks nicer when viewing the code and when it is around variables with also camelCase.
3. camelCase is a standard on JavaScript. This project is JavaScript-based.

**Describe alternatives you've considered**

This can work both ways, and should be discussed nonetheless.

**Additional context**

Here are some changes that I suggested a while ago.

- setting_match -> optionMatch (settings or options?)
- setting_match.setting_id -> optionMatch.id (the "setting" is redundant because it already refers the setting)
- setting_match.setting_value -> optionMatch.value
- enabled_by_default -> enabledByDefault
- potential_values -> potentialValues
- persistent_scripts -> persistentScripts

**Comment by WorldLanguages** [comment]
> Firstly, the options/settings, we need to decide which term to use.

Lol I admit I got a bit crazy and started using them randomly.

**Comment by mxmou** [comment]
> Secondly, the case. I propose using camelCase instead of snake_case due to reasons.
> 
> 1. camelCase is more often used in modern configuration files and manifest files, such as Prettier, ESLint, Node.js, VS Code, and, heck, even Scratch projects.
> 2. It looks nicer when viewing the code and when it is around variables with also camelCase.
> 3. camelCase is a standard on JavaScript. This project is JavaScript-based.

But:
1. Snake case is used in browser extension manifests, and this is a browser extension, so it makes sense for parts of it to look like browser extensions too.
2. Currently most options are snake case, so changing the rest would be much less work.
3. At least in my opinion snake case is more readable.

**Comment by WorldLanguages** [comment]
> Snake case is used in browser extension manifests, and this is a browser extension, so it makes sense for parts of it to look like browser extensions too.

I admit I used this as an argument, however browser extension spec is oold... The extension API is full of callbacks, that doesn't mean `addon.*` APIs can't use promises.

**Comment by Hans5958** [comment]
> Snake case is used in browser extension manifests, and this is a browser extension, so it makes sense for parts of it to look like browser extensions too.
I believe they are used because of the nature that browsers, or other low-level programs, are built using C++. C++ uses the snake_case as their case. This, of course, not applicable to the extension development, considering it is JavaScript.

> Currently most options are snake case, so changing the rest would be much less work.
It's not that hard to change it, considering that I have done it in #479 using replace tool. Also, the code is still quite simple, compared to do it sooner and then we need to deal with the tech debt.

> At least in my opinion snake case is more readable.
I understand. In my opinion, I use camelCase because I wanted to follow the standard (eq. other libraries/parts of code are also using camelCase, so why bother using the other case?). I use camel_case when doing both Python and Bash/Shell.

**Comment by Hans5958** [comment]
Oh, yeah. I need to remind you about the settings/options problem. Which one to choose?

**Comment by WorldLanguages** [comment]
Well, options work, time to rename `addon.settings` to `addon.options`?

**Comment by Hans5958** [comment]
You sure about that? The source code seems to use the word "settings" more than the word "option".

Ex: https://github.com/ScratchAddons/ScratchAddons/blob/619b824e4bf2fe3421a5b464e6c19dea1c961d2c/background/get-addon-settings.js

Is this intended, or should we just change it to the word "settings"?

**Comment by WorldLanguages** [comment]
You're driving me crazy @Hans5958 :P
With the PR you changed `setting_match` to `optionMatch`, so I thought we could change `addon.settings` to `addon.options`? They basically refer to the same thing, just in different contexts?

**Comment by Hans5958** [comment]
> 
> 
> You're driving me crazy @Hans5958 :P
> With the PR you changed `setting_match` to `optionMatch`, so I thought we could change `addon.settings` to `addon.options`? They basically refer to the same thing, just in different contexts?

Right, let me get this straight. You wanted to change te `addon.settings` to `addon.options`, right? I thought you actually have `addon.options` in there because in the manifest it says `options`. Don't tell me that the variables in the manifests is not the same as the ones on the API.

This so-called "inconsistensies" really shows up it's problem.

In the other hand, I see that "settings" is more frequent than "options", and it is already made on the addons API (and also I have small knowledge about the API source code), so how about doing it as "settings"?

**Comment by WorldLanguages** [comment]
@Hans5958 I agree to switch all mentions of `options` to `settings.`
