### ISSUE TITLE
Material-style switches

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#4784]
### Is your request related to a problem? Please describe.

I think the current switch design (settings page) looks weird.

### Describe the solution you'd like

Material switches look nice: 
![components-switches-switch1.png](https://user-images.githubusercontent.com/74449186/178132057-19894aaa-ea4d-4dab-bb0a-7e0fb5c24e48.png)

**Comment by mxmou** [comment]
I think the current design is fine. WinUI (Windows 11) switches are very similar:
![image](https://user-images.githubusercontent.com/51849865/178135969-3fcb87a0-f2bc-441b-8dcd-cafeca59ed52.png)

**Comment by apple502j** [comment]
Hmm, do we use material design elsewhere?

**Comment by mxmou** [comment]
@apple502j We don't.

**Comment by Secret-chest** [comment]
> @apple502j We don't.

Material-_style_

**Comment by Secret-chest** [comment]
At least make that dot larger.

**Comment by BroJac5246** [comment]
I _personally_ don't mind the current ones.

That said, I suppose they _could_ be better

**Comment by Raspberry693** [comment]
We (we being those who maintain the actualy extension) could launch a poll with 1.27.0 and see what the users think

**Comment by Secret-chest** [comment]
> At least make that dot larger.

@apple502j
