### ISSUE TITLE
Change the SA blue colour to a better one

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#4785]
### Is your request related to a problem? Please describe.

The current blue colour looks a bit weird, it irks my eyes. It looks like `#0000ff`.

### Describe the solution you'd like

Change it to the link colour, or `#009688`, or anything else.

**Comment by mxmou** [comment]
"It looks a bit weird" is not an objective reason to change a color. If you dislike the current one, please suggest a different color that has sufficient contrast with white text and looks good in combination with the orange logo color.

It also has to be a shade of blue, which `#009688` definitely isn't.

**Comment by apple502j** [comment]
I'd argue that color is [blue in many cultures outside English-speaking countries, including here in Japan](https://en.wikipedia.org/wiki/Blue–green_distinction_in_language), but nonetheless that alone does not make a good reason.

**Comment by Samq64** [comment]
What about Scratch blue?

**Comment by mxmou** [comment]
> What about Scratch blue?

I don't think we should copy any aspects of Scratch's design. That color is also too bright for good text contrast, especially because we use a quite small font.

**Comment by Secret-chest** [comment]
Ok, but just change its hue to a little more cyan.

**Comment by Secret-chest** [comment]
> "It looks a bit weird" is not an objective reason to change a color. If you dislike the current one, please suggest a different color that has sufficient contrast with white text and looks good in combination with the orange logo color.
> 
> It also has to be a shade of blue, which `#009688` definitely isn't.

I don't think it is a shade of blue either, but why does it have to stay blue?

**Comment by Samq64** [comment]
`#0E4396`?

**Comment by mxmou** [comment]
Here's a comparison of the colors proposed so far in this issue:
<details>
<summary>Show images</summary>
<img src="https://user-images.githubusercontent.com/51849865/178999895-423efc40-b116-4bed-aa61-2ddb7ecdbfb1.png" />
<img src="https://user-images.githubusercontent.com/51849865/179000926-8b40d064-6320-48fd-9434-1fda3fa7900c.png" />
<img src="https://user-images.githubusercontent.com/51849865/179001450-270cf3b5-2deb-4c14-aa53-e9a58bd292a7.png" />
<img src="https://user-images.githubusercontent.com/51849865/179001816-9b9dd434-6aa9-4f5e-a3b7-acdfd72ba91d.png" />
<img src="https://user-images.githubusercontent.com/51849865/179002261-fefe9419-5e40-4dc2-955c-cac30e602ea0.png" />
<img src="https://user-images.githubusercontent.com/51849865/179002464-67a23334-36e7-4bbd-9ec6-7aa35831ecd4.png" />
</details>

I think the current one is still better than any other option.

**Comment by Secret-chest** [comment]
Now that I see, `#009688` looks very nice.
