### ISSUE TITLE
Customizable new sprite position does not work when you duplicate sprite

### ISSUE THREAD

**Issue by ASTHEBEST** [ScratchAddons/ScratchAddons#4786]
### Description

When you use Customizable new sprite position it won't work with duplicates.
### Reproduction steps

1 Create a sprite
2 Right click it and click Duplicate.

### Expected behavior

It should go to 0 0(the location I set) when I duplicate it.

### Actual behavior

It went to a place around 0 0

### Environment

- Browser: google chrome
- Scratch Addons version: 1.26.1
- Operating system: Mac

That is it

**Comment by apple502j** [comment]
Should it go to 0 0 or the position of the original sprite?
