### ISSUE TITLE
Localize addons (NOTE: All PRs are on hold!)

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#480]
It's likely too early to focus on this, but I want to create the issue. It would be nice if addon titles, descriptions, warnings, setting names, etc. could be localized. There could also be an `addon.i18n` API or similar, in order to get localized strings from userscripts or popups.

**Comment by apple502j** [comment]
Assigned prio-2 due to high number of confused people on Japanese forum.

**Comment by WorldLanguages** [comment]
@apple502j Oh. Nice catch. Maybe I should have thought twice over adding a "Set Thumbnail" button for all users, no matter their language choice.

**Comment by Hans5958** [comment]
Devil's advocate: I think the issue mentioned is still quite localized and not quite widespread, so I think it is not enough to get the priority 2.

**Comment by apple502j** [comment]
Current system:

## File Structure
`addons-l10n/LOCALENAME/ADDONID.json`
LOCALENAME is IEFT language tag (en-US, ja). ADDONID is addon id, or `_general` for general message.

## File Content
File is JSON.

Keys: `_general` contains `_locale` (IETF language tag) and `_locale_name` (translated name)
Addon-specific keys have `addonid/` as a prefix. Keys that start with `addonid/@` represent a field on `addon.json`; e.g. `example-addon/@name`, see below

## Obtaining translation
Userscripts: the exported function's argument object receives `msg` and `safeMsg`. Arguments are prefixed with `addonid/`. `safeMsg` escapes the message content (but not parameters) to prevent XSS. Loaded addons' messages are auto-loaded.

Background scripts (not encouraged): `await scratchAddons.l10n.load(["addon-id"])` then `scratchAddons.l10n.get("unprefixed/message")`

Content scripts (not encouraged): send `{loadMsgByAddonIds: ["addon-id"]}` then send `{msg: "unprefixed/message"}`

## Placeholders
`$xxx$` in the message represents a placeholder named `xxx` which can be replaced via the second argument of msg/get, or the `placeholders` for content scripts.

## Addon manifest
Some fields can have `null` to indicate that the translation is loaded from the file. The fields include: name, description, notice

**Comment by WorldLanguages** [comment]
I'm removing the prio tag since it really means nothing, lol
