### ISSUE TITLE
Change Scratch Addons logo for pre-release versions

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#4805]
### Is your request related to a problem? Please describe.

Sometimes it can be hard to distinguish between pre-release and stable versions of the extension.

### Describe the solution you'd like

Make the extension icon `--blue-variant` (`#0e44b8`) or another shade of blue for pre-release versions and maybe even reverse blue variant and brand orange.

<img src="https://cdn.discordapp.com/attachments/995476325408186418/997131691258810368/image.png" width="128">

### Describe alternatives you've considered

Adding "Beta" or "Pre-release" next to the version number on the extension popup, but that should be added either way.

**Comment by RIMOPA** [comment]
Maybe we could use a beta symbol like this quick one I made.
![g8567](https://user-images.githubusercontent.com/97112832/179850147-0f2c02de-ffbe-46f1-9f4f-f34dff80c4fd.png)

**Comment by Secret-chest** [comment]
That's not the beta sign. The beta sign is β. It is not cut.
