### ISSUE TITLE
Select the last opened tab when opening the popup

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#4809]
### Is your request related to a problem? Please describe.

The Messages tab in the popup is always selected by default, even if the user needs one of the other tabs more often.

### Describe the solution you'd like

Remember which tab was opened and select it again.

**Comment by TheColaber** [comment]
Would it be ok to use `localStorage` for this or would we have to use `chrome.storage.local`?

**Comment by DNin01** [comment]
An alternative would be to open the most relevant tab first: if you have some unread messages, the Messages tab will be selected. Otherwise, the Addons tab will. I prefer to land in Addons first, so I disable the addons for the other tabs unless I want to use them.
