### ISSUE TITLE
Use Version Name To Signify Prerelease

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#482]
For prerelease versions, we could set a version name, such as 1.2 Prerelease using "version_name": "1.2 Prerelease"
The feedback page could check for this.

**Comment by WorldLanguages** [comment]
I don't think browsers will like version numbers like that.

**Comment by WorldLanguages** [comment]
`Required value 'version' is missing or invalid. It must be between 1-4 dot-separated integers each between 0 and 65536.`

**Comment by WorldLanguages** [comment]
Lol that's funny, if you upload an extension with version number `65536.65536.65536.65536` you won't be able to upload a valid new version

**Comment by GrahamSH-LLK** [comment]
Version _name_, not version. https://developer.chrome.com/extensions/manifest/version#version_name

**Comment by GrahamSH-LLK** [comment]
It can be accessed using chrome.runtime.getManifest().version_name

**Comment by WorldLanguages** [comment]
`1.2.0-prerelease` appears to be semver compliant

**Comment by GrahamSH-LLK** [comment]
But not chrome extension compliant. As I said, there actually _is_ a difference between version and version name.

**Comment by GrahamSH-LLK** [comment]
It's ``"version": "1.2.0"`` vs. `` "version_name": "1.2.0 Prerelease"``. You can have both.
