### ISSUE TITLE
Something is wrong with `progress-bar`

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#4820]
### Description

There's a vertical bar instead.

### Screenshots

![There's a vertical bar thingy where the meter should be](https://user-images.githubusercontent.com/106490990/179336781-21f4c485-e260-4493-a793-8bf41dc25b2f.png)

### Reproduction steps
1. Enable the `progress-bar` addon
2. Turn off the setting "Show Progress Bar at Top of Page" (the one at the top is fine)
3. View a project

### Expected behavior

There should be a meter.

### Actual behavior

There's a vertical bar thingy where the meter should be.

### Environment

- Browser: Microsoft Edge 103
- Scratch Addons version: v1.27.0
- Operating system: Windows 10
<details> 
  <summary>Enabled Addons</summary>
  clones, color-inputs, confirm-actions, copy-message-link, ctrl-enter-post, disable-sprite-wobble, discuss-button, editor-colored-context-menus, emoji-picker, expanding-search-bar, fullscreen, gamepad, hide-delete-button, hide-flyout, hide-stage, msg-count-badge, progress-bar, project-notes-tabs, resizable-comment-input, sounds-duration
</details> 

### Additional context

I started seeing this after the 1.27.0 update.

**Comment by mxmou** [comment]
Regression caused by #4627
