### ISSUE TITLE
hide-stage Doesn't Work Properly with editor-stage-left

### ISSUE THREAD

**Issue by Platformer444** [ScratchAddons/ScratchAddons#4823]
### Description

When the editor-stage-left and hide-stage addons are enabled and the hide stage button is clicked, the stage layout buttons are gone.

### Steps to Reproduce
1. Enable editor-stage-left addon.
2. Go to the editor of any project.
3. Click on the hide stage button.

### Screenshots
<img width="960" alt="Screenshot (123)" src="https://user-images.githubusercontent.com/78246772/179347572-c73697a8-edde-4630-99de-f7b4abbd79b1.png">

### Environment

- Browser: Edge 103
- Scratch Addons version: 1.27.0
- Operating system: Windows 10

**Comment by mxmou** [comment]
I'm not able to reproduce this.

**Comment by Platformer444** [comment]
> I'm not able to reproduce this.

1. Enable editor-stage-left addon.
2. Go to the editor of any project.
3. Click on the hide stage button.

**Comment by mxmou** [comment]
> > I'm not able to reproduce this.
> 
> 1. Enable editor-stage-left addon.
> 2. Go to the editor of any project.
> 3. Click on the hide stage button.

That's what I did, and I got this:
![image](https://user-images.githubusercontent.com/51849865/179354548-613e51e7-c0af-43ff-be76-04d07fc5a514.png)

The rounded corners on the left side are wrong but everything else works as expected.

**Comment by mxmou** [comment]
Where does the purple share button in your screenshot come from? This could just be SA incorrectly interacting with another extension.

**Comment by Platformer444** [comment]
> Where does the purple share button in your screenshot come from? This could just be SA incorrectly interacting with another extension.

Might be that. I will to check tomorrow.

**Comment by CST1229** [comment]
> Where does the purple share button in your screenshot come from? This could just be SA incorrectly interacting with another extension.

The Blocklive Share button? That's from Blocklive (a scratch live collaboration extension that is currently not on the webstore I think because of the whole project token stuff).

**Comment by Platformer444** [comment]
Now I found out. It is happening because of an extension I had installed(Not Blocklive). I can now close this issue.
