### ISSUE TITLE
Fix focus outline for Scratch Messaging's reply box

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#483]
Currently it looks like this:
![image](https://user-images.githubusercontent.com/61319150/95919805-db810d00-0d73-11eb-9560-f92583cec151.png)
Maybe in the future it could look more like this (but with a darker border when focused):
![image](https://user-images.githubusercontent.com/61319150/95919861-f2276400-0d73-11eb-8eeb-4bf1c5eda876.png)
This can be solved with
```css
.reply-box:focus {
    outline: none;
}
```

**Comment by GrahamSH-LLK** [comment]
We should wait for #476. It includes tons of changes.

**Comment by Explosion-Scratch** [comment]
I'll close this for now.
