### ISSUE TITLE
[v1.27.0 regression] Editor crashing after clicking "make a block"

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#4831]
> When I click "make a block" on the My Blocks page, it says scratch has crashed. I disabled all my extensions including scratch addons, and it didn't crash. My other extension that has access to the scratch page is AdGuard adblocker.

https://scratchaddons.github.io/list-of-enabled-addons/?number=jvr03ciz8azqesccdzi0d2hn77l&version=v1.27.0

> I believe I've found a bug:
OS: Windows 10, Browser: Microsoft Edge, Other Extensions: ADBLOCKPLUS
When creating a custom block the editor screen crashes. This crash didn't happen on google chrome where I dont have the extension.

https://scratchaddons.github.io/list-of-enabled-addons/?number=n6dvwkapywkib9ifa9xrp8uhi0p&version=v1.27.0

> when i have "Auto-hiding block palette" enabled and the "Category Hover" option on, when i try to create a new block the code area crashes.

**Comment by WorldLanguages** [comment]
Probably hide-flyout/userscript.js:199

All users that reported had hide-flyout enabled

**Comment by Samq64** [comment]
I can confirm this happens with only Auto-hiding block palette enabled. Also, the new notice makes it look worse:
![image](https://user-images.githubusercontent.com/81489795/179370228-17aae063-e54d-4108-8242-272744c3a879.png)
