### ISSUE TITLE
Clicking the emoji button while the picker is open doesn't close the picker

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#4842]
### Description

Clicking the emoji picker button while the picker is open doesn't close the picker popup.

### Reproduction steps

1. Enable the emoji picker addon.
2. Go to a project, studio or user profile.
3. Click the emoji button next to the comment input.
4. Click it again.

### Expected behavior

The popup would be closed.

### Actual behavior

The popup is still open.

**Comment by DNin01** [comment]
It's probably getting closed and immediately reopened again.
