### ISSUE TITLE
Hide stage when running bug

### ISSUE THREAD

**Issue by Coolguy236gg** [ScratchAddons/ScratchAddons#4857]
-->

### Description
So, when I click the green flag and then hide the stage (using the new addon ofc) it freezes the entire webpage.
**NOTE:** This bug only happens when you start a big project containing loads of code, the **results may vary according to the power of your device.**

### Reproduction steps

1. Click the green flag of a project (**make sure it is a big project like paper Minecraft or something** or you will not have enough time to reproduce the bug.) The better your device is, you'll have to choose bigger projects.
2. Hide the stage using the new button obtained by enabling the "hide stage" addon.
3. If you have followed these steps correctly, your tab should crash.

### Expected behavior
The project should be **stopped** and then only it should close the stage.

### Actual behavior
The project **does not stop**, and the stage hides. I guess it probably uses up a lot of resources of the computer, which is why it freezes the tab.

### Screenshots
_Screenshots will not make sense_, so I will send a video
The video is a bit corrupted (idk y) so it has a black screen for a few seconds. Also, it says veed.io and it is editing software. I used it to compress the video, not edit it.

https://user-images.githubusercontent.com/109452958/179736237-a2ef8186-2836-4306-8e53-4bfdb52c90ad.mp4

### Environment

- Browser: Brave v1.41.96 (based on chromium)
- Scratch Addons version: v1.27.1
- Operating system: Windows 11 (_with extra tweaks to improve performance_)

### Additional context

I don't have anything to say here. It is kind of _self-explanatory._

**Comment by TheColaber** [comment]
So apparently putting `display: none` on `stage-wrapper_stage-canvas-wrapper` causes the page to crash. Either there is a CSS fix or we should stop the project when this happens.

**Comment by Coolguy236gg** [comment]
_Idk about actual coding_, (I code only from scratch). I hope it is easy to fix!

**Comment by Samq64** [comment]
I can't reproduce the bug. I tested on Firefox with Paper Minecraft while in the processor sprite which has 4000+ blocks and hiding the stage lagged a tiny bit, but less than dragging a stack of blocks in that sprite.

**Comment by GarboMuffin** [comment]
> So apparently putting display: none on stage-wrapper_stage-canvas-wrapper causes the page to crash. Either there is a CSS fix or we should stop the project when this happens.

Have you reproduced this or is this just a guess?

If you have reproduced it, use your browser's profiler to figure out which function it's getting stuck in.

**Comment by lisa-wolfgang** [comment]
Added this label because we still aren't sure what exactly is the cause of the issue.

**Comment by Coolguy236gg** [comment]
Thank you all for contributing to this bug fixing. have a nice day!
