### ISSUE TITLE
Recommended addons should be enabled by default

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#487]
v1.2.0 will be released 4 weeks after the transition from Scratch Messaging Extension. As another step following this linear transition, all (or most?) recommended addons should be enabled by default to new users.
As well, we should remove "scratch messaging" and "message count on extension icon" as hardcoded first 2 listed addons in the settings page.

**Comment by WorldLanguages** [comment]
Revisiting recommended addons, so many appear to be of personal preference, so I'm not sure whether this is a good idea:
- Scratch 2.0 → 3.0 is a theme, and likely shouldn't be enabled automatically
- Scratch Notifier and bitmap images copying require optional permissions, so they can't be enabled automatically
- Searchable dropdowns might be annoying for some users, because context menus will take more space

Some recommended addons I see could be enabled by default:
- Developer tools
- Project progress bar
- Studio manager tools
- YouTube full screen

Some currently not recommended addons that could be enabled by default (they likely should be recommended?):
- (not made yet) Ctrl+click to run project muted
- Alt+click for 60fps
- Last edit tooltip
- Search profile

Other than those, what addons to use is a pretty subjective decision.

**Comment by TheColaber** [comment]
Sounds Good! I think it would be better if addons that slow down your computer are not enabled by default.

**Comment by WorldLanguages** [comment]
Yeah, that should be sorted out before making alt+click recommended.

**Comment by Explosion-Scratch** [comment]
Yeah, that sounds good.

**Comment by WorldLanguages** [comment]
I'll be delaying this until #431 is resolved.
