### ISSUE TITLE
"Clear" button for `gamepad`

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#4878]
A lot of the time, I don't use the auto-generated controller mappings (because it's not perfect - it can't be) and change them to my own instead. To make things cleaner, I sometimes erase all of the auto-generated mappings first, but to do this, I have to select and clear each one individually. It's not that time-consuming, but a "clear" button could still do this for me and would be more convenient.

<sub>Also, maybe add a "reset" button to restore the auto-generated mappings.</sub>

**Comment by TheWeirdo600** [comment]
Good suggestion.
