### ISSUE TITLE
Rename the "more links" addon

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#4882]
Currently, the more links addon "adds links for URLs pointing outside scratch.mit.edu", but it's a little unclear if you don't know what problem it fixes. The title also doesn't self-explain the addon right now. I have a new name and description:

**Addon name:** Clickable external links
**Description:** Makes URLs pointing outside Scratch from descriptions and comments clickable links.

However, if #4845 were to be merged and/or if [`curator-link`](https://github.com/ScratchAddons/ScratchAddons/tree/66f9072dd7968929a87c30d2ed8b1b430033b689/addons/curator-link) were to be combined with this addon, it might make more sense to call it something else.

**Comment by Hans5958** [comment]
If you were to change it, at least keep it as a noun phrase: "Clickable external links" or "More external links"

I don't know, I ever saw forum mentions to be inplemented. Is it on this addon, or is it made as a new one?

**Comment by DNin01** [comment]
> If you were to change it, at least keep it as a noun phrase: "Clickable external links" or "More external links"
> 
> ~I don't know, I ever saw forum mentions to be inplemented. Is it on this addon, or is it made as a new one?~
> 
> I saw #4845 that will expand this addon. I think I'm on the side of expanding what the addon can do within the scope, looking at that time I named the addon broad enough to be expandable

If this addon were to be expanded, I think it could be called "Clickable URLs and mentions". Or if it were to stay as it is now, it could be called "Clickable non-Scratch URLs".

**Comment by WorldLanguages** [comment]
I asked on https://github.com/ScratchAddons/ScratchAddons/pull/4845#issuecomment-1194579076 whether clickable forum mentions should be part of more-links or not.

**Comment by DNin01** [comment]
Actually, I think "Clickable external links" is fine. The addon description can say "links pointing outside scratch.mit.edu" to clarify, just in case.

It looks like #4845 is proposing a new addon, not a change to this addon, so the aforementioned name is appropriate for now. Might be starting a PR to change the name soon.

**Comment by WorldLanguages** [comment]
> It looks like https://github.com/ScratchAddons/ScratchAddons/pull/4845 is proposing a new addon

I restarted the discussion, let's see what we conclude

**Comment by DNin01** [comment]
I still think it would be nice if the name could possibly be changed eventually because at first, it sounded kind of like it inserted links to external sites on the footer or something, but at least we were able to clarify it in the description for now, which I think makes it a lot easier to understand.
