### ISSUE TITLE
confirm-actions: When leaving a studio in /mystuff, confirmation modal opens

### ISSUE THREAD

**Issue by Weredime** [ScratchAddons/ScratchAddons#4884]
### Description
When you try to leave a studio in my stuff, it shows a modal meant for the unsharing projects feature.

### Reproduction steps

1. Enable confirmations addon, enable "Project unsharing" setting
2. Go to /mystuff
3. Try to leave/delete a studio
4. See modal

### Expected behavior
Forcefully leave the studio

### Actual behavior
Opens modal

### Screenshots

https://user-images.githubusercontent.com/100447465/180599462-a8a4dc93-c2c8-458b-9c23-af63ca27da70.mp4

### Environment

- Browser: Firefox 
- Scratch Addons version: 1.27.3
- Operating system: Windows 11

### Additional context
We could turn this into a feature?

**Comment by mxmou** [comment]
> ### Expected behavior
> Forcefully leave the studio

The expected behavior is that the button would behave as if confirm-actions was disabled, i.e. open a modal with the correct contents.
