### ISSUE TITLE
Pause keyboard shortcut

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#4888]
To use the pause feature from the `pause` addon, you need to click the pause button. What if, alternatively, we could use a keyboard shortcut? Maybe `shift`+`p`? Just to speed things up.

**Comment by Secret-chest** [comment]
No shift+letter only (as it is used for typing). Maybe shift+esc?

**Comment by RIMOPA** [comment]
Maybe `Ctrl`+`K` or `Ctrl`+`P`.

**Comment by BroJac5246** [comment]
There's been some discussion of a dedicated hotkey manager, see

#4662 and #4725

**Comment by DNin01** [comment]
> No shift+letter only (as it is used for typing). Maybe shift+esc?

We could just not allow the shortcut while you're typing,

**Comment by Amer1u** [comment]
Reply

في الأحد، ٢٤ يوليو ٢٠٢٢, ١٠:٢٧ م BroJac5246 ***@***.***> كتب:

**Comment by WorldLanguages** [comment]
I think we should wait until we can provide a dedicated hotkey manager in the settings page.

**Comment by Secret-chest** [comment]
> > No shift+letter only (as it is used for typing). Maybe shift+esc?
> 
> The shortcut shouldn't work while you're typing,

It wouldn't make sense.

**Comment by DNin01** [comment]
Resolved by #5121
