### ISSUE TITLE
Allow the toggled love and favorite button colors to be changed with `dark-www`

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#4895]
Right now, they're always red and yellow respectively. This feature is mainly to allow color-blind users to accommodate the experience so that they can more easily tell if they have clicked something. You can already change the "text and icon highlight color" color in the Editor dark mode and customizable colors addon to change the appearance of the toggleable things in the editor, like the hide/show switch, but this doesn't cover the love and favorite buttons.

Just an idea.

**Comment by DNin01** [comment]
There's currently a PR on `scratch-www` to make these icons colorblind-friendly, so this problem should be resolved after that happens.

**Comment by WorldLanguages** [comment]
@DNin01 What's the PR number?

**Comment by DNin01** [comment]
> @DNin01 What's the PR number?

https://github.com/LLK/scratch-www/pull/7264
