### ISSUE TITLE
The direction popup won't appear with `hide-flyout` on.

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#4896]
### Description

Usually, you can click the Direction text box in the editor that's in the sprite info box thing and it shows a popup with the buttons to change the rotation style.

### Reproduction steps

1. I think the culprit is the `hide-flyout` addon, but you can see the full list of the addons I am using below. So, use `hide-flyout`.
2. Open the editor.
3. Click on the Direction text box in the editor that's in the sprite info box thing, you know? It's over the sprites list.

### Expected behavior

There should be a popup like [this](https://en.scratch-wiki.info/w/images/Scratch3.0_rotation_style.svg).

### Actual behavior

No popup appears.

### Environment

- Browser: Microsoft Edge v103
- Scratch Addons version: v1.27.3
- Operating system: Windows 10
<details> 
  <summary>Enabled Addons</summary>
  clones, color-inputs, confirm-actions, copy-message-link, ctrl-enter-post, custom-zoom, dark-www, disable-sprite-wobble, editor-colored-context-menus, editor-dark-mode, expanding-search-bar, forum-toolbar, fullscreen, gamepad, hide-delete-button, hide-flyout, msg-count-badge, progress-bar, project-notes-tabs, resizable-comment-input
</details>

**Comment by WorldLanguages** [comment]
Can reproduce

Appears to be some rule on /addons/hide-flyout/style.css

**Comment by WiseDragoon5374** [comment]
Issue persists with the latest Scratch Addons version (v1.27.3). For whatever reason TW Desktop shows the popup, but it appears behind the stage (TW Desktop v1.5.0 production, win32 x64, Electron 19.0.9 running Addons version ed88cf2), so I think it happens here too.

**Comment by GarboMuffin** [comment]
Scratch Addons v1.27.3 was released 19 days ago, TW Desktop 1.5.0 uses addons from 17 days ago, and the fix was merged 10 days ago. It just hasn't been released yet.
