### ISSUE TITLE
Change find bar costume highlight colour

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#4898]
### Is your request related to a problem? Please describe.

I don't really like the find bar costume highlight colour (and sound highlight colour after #4817 is merged).

### Describe the solution you'd like

Changing the highlight colour to `#4280d7` for costumes and `#de91de` for sounds unless someone comes up with better colours.

**Comment by Secret-chest** [comment]
Make them configurable? I don't like the new ones.

**Comment by Secret-chest** [comment]
Make them configurable? I don't like the new ones.

**Comment by mxmou** [comment]
I'm not sure if the text even needs to be colored. The list of costumes only contains costumes and the list of sounds only contains sounds so a special color doesn't add any useful information.

**Comment by Samq64** [comment]
Seems to be implmented 
![image](https://user-images.githubusercontent.com/81489795/212482099-e2b19857-27b4-4dd7-86eb-aa398c072486.png)
![image](https://user-images.githubusercontent.com/81489795/212482110-716029a1-a7ae-470e-9375-3cbf4845775e.png)
