### ISSUE TITLE
Navigating find bar with keyboard can cause highlighted item to go off-screen

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#4899]
### Description

When using the up and down arrow keys to navigate the find menu on large projects, the highlighted item can go off-screen.

### Reproduction steps

1. Open a sprite with lots of variables and broadcasts
2. focus the fond bar
3. Make sure the fond menu has a scrollbar
4. repeatedly press the down arrow until the focused item disappears

### Expected behavior

Navigating the find menu with the arrow keys should scroll the menu.

### Actual behavior

Navigating the find menu with the arrow keys doesn't scroll the menu, so eventually the highlighted item goes off-screen

### Environment

- Browser: Firefox 102
- Scratch Addons version: 1.27.3
- Operating system: Ubutnu 22.04

I originally found this when testing #4817, but the issue is unrelated to that PR.

**Comment by OregSamSas** [comment]
You probably have Ubuntu 22.04 :) (I've seen Ubunto so rarely written time that I don't think I had seen a typo with it before, lol)

I successfully reproduced it, but I think I also had noticed it way before `find-bar` addon came into being just I was so lazy, I didn't report it.
