### ISSUE TITLE
middle click popup opens behind dropdowns and context menus

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#4906]
### Description

The popup for adding blocks provided by the developer tools addon is sometimes shown behind a context menu or dropdown.

### Reproduction steps

1. Right click the code area or click a dropdown input
2. Middle click next to the menu or dropdown that opens to open the devtools popup

### Expected behavior

The menu or dropdown would be closed.

### Actual behavior

The menu or dropdown is shown in front of the devtools popup.

### Screenshots

![image](https://user-images.githubusercontent.com/51849865/181046233-7b6b1b16-372c-49a5-b375-7a2d4a6eb1f4.png)

**Comment by mxmou** [comment]
Can't repro on v1.38.2.

**Comment by OneShot-Niko** [comment]
> Can't repro on v1.38.2.

It seems to still happen, but only with CTRL+SPACE:
![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/5e9d8456-ee25-435f-8f42-88e47f4116b3)
This can happen two ways:
a. inbetween ENABLED contextmenu options;
b. ontop of-- or in between-- DISABLED context menu options.
