### ISSUE TITLE
Project stats on the popup

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#492]
I think we should add a project stats tab to scratch addons so we can access project data quickly

**Comment by TheColaber** [comment]
Where would it go?

**Comment by JeffaloBob** [comment]
> Where would it go?

perhaps next to the report button there could be a little button that shows the metadata

**Comment by samuraininja360** [comment]
Um I mean it would be nice to add a tab next to the Messages and Games tabs. It should show an unordered list of your projects with their stats like Loves, Faves, Remixes and Views

**Comment by RedGuy12** [comment]
here the data scratchdb gives us:
```js
        "created": "2021-04-28T14:18:36.000Z",
        "modified": "2021-04-30T08:23:46.000Z",
        "shared": "2021-04-28T14:48:37.000Z",

        "blocks": 739,
        "costumes": 44,
        "variables": 56,
        "assets": 44,

        "ranks": {
            "views": 5299,
            "loves": 4288,
            "favorites": 4119
        },
        "views": 43832,
        "loves": 2075,
        "favorites": 1735,
```
some are already in other addons.

**Comment by WorldLanguages** [comment]
Extension popup isn't really suitable for this.
