### ISSUE TITLE
Change numbers in block inputs with arrow keys

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#4928]
Sometimes I want to increment/decrement a number in a block input by small numbers. To speed things up, I'd kind of like to see an addon that lets you use `↑`/`↓` while they're selected to increment/decrement them. This exists in Chrome's DevTools:

Increment by 1: `↑`
Increment by 10: `Shift`+`↑`
Increment by 100: `Ctrl`+`↑`
Increment by 0.1: `Alt`+`↑`

Just an idea.

**Comment by WorldLanguages** [comment]
Interesting suggestion
