### ISSUE TITLE
Links for cloud projects

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#493]
There is an issue with the cloud games tab where the links don't work when clicked

**Comment by TheColaber** [comment]
I'm pretty sure that was intensional (so you could actually be able to close and open the tabs) but I think it would be better to include a popout button to link to that project.
Also, the users on the tabs won't link to their profile.

**Comment by WorldLanguages** [comment]
Oh wow I swear it worked when I tested it

**Comment by WorldLanguages** [comment]
@GrahamSH-LLK clearly a bug lol, an <a> with no `href`

**Comment by samuraininja360** [comment]
Yeah no href what can I help with, so I can make a pull-request

**Comment by WorldLanguages** [comment]
This was fixed, we might have forgotten to reference this issue number
