### ISSUE TITLE
Add an option to stop my-ocular from displaying your Ocular status on your own profile/posts

### ISSUE THREAD

**Issue by BroJac5246** [ScratchAddons/ScratchAddons#4938]
### Is your request related to a problem? Please describe.
No. Today I was on my profile and realized that my Ocular status was displaying (with `my-ocular` enabled, of course). That's what's intended, and it's fine, but it clutters the display with information that I don't actually need or want.

Also, when I'm on the forums, I see my Ocular status. That's less intrusive, but still related.

### Describe the solution you'd like
I'd like it if there was an option in `my-ocular` to hide your Ocular status on your profile and/or forum posts. This would help to declutter the display.

### Describe alternatives you've considered
Deal with it

### Additional context
None

**Comment by DNin01** [comment]
This could also be set up to toggle showing the ocular status on profile pages for _all users_, not just yours.

**Comment by mxmou** [comment]
> Should this be updated to also hide your status, then?

It already does. If I understand the suggestion correctly, the OP wants to be able to switch between showing the status on all profiles, on others' profiles, and not showing it on profiles.

**Comment by Norbiros** [comment]
Okay, but what if we want to merge it with **ocular and aviate add-on** (#4739)?

In this PR I added "show status" setting, where you can select between Aviate/Ocular/Don't show. 
So maybe we can add new setting, that is only visible when show-status is set to ocular or aviate, is able to switch between showing the status on all profiles or on others' profiles.

**Comment by BroJac5246** [comment]
> So maybe we can add new setting, that is only visible when show-status is set to ocular or aviate, is able to switch between showing the status on all profiles or on others' profiles.

That's what would probably work best.
