### ISSUE TITLE
ScratchStats

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#494]
**Describe the new addon**

This addon would add scratchstats info to profiles. Each item, like Followers stats, Followers over time (beta), etc., could be toggled on and off. This would be really cool.
**Link to the new addon**

scratchstats.com

**Comment by TheColaber** [comment]
Seems cool... I'm not sure if we will really be taking scratchstats.com or it's APIs

**Comment by GrahamSH-LLK** [comment]
I know, but it's API's would probably power it.

**Comment by WorldLanguages** [comment]
Pls don't use scratchstats.com apis those need hosting :p

**Comment by JeffaloBob** [comment]
should be relativity easy if we fetch data from lefty's cool APIs and stuff

**Comment by BoomerScratch** [comment]
Related to #492

**Comment by Hans5958** [comment]
How about a quick link to the appropriate ScratchStats page, just like what I did on my userscript linked below?

https://github.com/Hans5958/userscripts/blob/master/Scratch/Shorter%20Scratch%20Stats%20Links.user.js

**Comment by lholliger** [comment]
I was planning on doing this one at some point (Maybe this weekend ill get started). All requests would go to ScratchDB since all ScratchStats does is take ScratchDB data + add some updated stuff, and that hits against a Cloudflare rate limit

**Comment by samuraininja360** [comment]
Yeah this sounds pretty good I like the idea

**Comment by RedGuy12** [comment]
> Pls don't use scratchstats.com apis those need hosting :p

What

**Comment by Hans5958** [comment]
> 
> 
> > Pls don't use scratchstats.com apis those need hosting :p
> 
> What

He meant that SS.com's API can't hold the demand when we use it on SA.
