### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#4947]
### Is your request related to a problem? Please describe.

If there is an syntax error, for example, a missing comma in the `addon.json`, the popup and settings pages don't load and it only lets the user know in the background page console.

### Describe the solution you'd like

Throw better error messages and maybe display something in the popup too.

### Describe alternatives you've considered

Skip addons with invalid manifests.

**Comment by WorldLanguages** [comment]
The error is thrown in the extension's background page.

**Comment by TheColaber** [comment]
You can also see the error when clicking the "errors" button: 
![image](https://user-images.githubusercontent.com/72760579/182735213-29fa9628-49fc-44dc-9361-eeefd5e67fe4.png)

**Comment by Samq64** [comment]
> The error is thrown in the extension's background page.

Thanks, I was looking from settings page for some reason.

**Comment by Samq64** [comment]
I still think there should be a better error message, because 
![image](https://user-images.githubusercontent.com/81489795/182743532-84e4ab5a-5912-4a2e-aa7f-ac85426ed91b.png)
isn't very clear and it doesn't even tell me which file is causing the error.

**Comment by Norbiros** [comment]
Few months ago I wrote sh script to check which files are invalid lol

**Comment by WorldLanguages** [comment]
Discussion is happening in #4949
