### ISSUE TITLE
Add Show More to Show full areas Addon

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#495]
**Describe the new addon**

Adds a Load More button (to the "Show full areas" when "SHOW SCROLL FOR WHAT I'VE BEEN DOING" is enabled) to load more data from the user. I didn't add any styling for the button (besides the margining) so that's why it looks so scratch 2.0-ish. Try with "Scratch 2.0 → 3.0" it looks way better.

**Note**

Obviously, we can change where we enable and disable this option, but I just thought, for now, we could just merge them. But lmk if you guys think it's better another way.

**Link to the new addon**

~See what I added [Here!](https://github.com/TheColaber/ScratchAddonsUpdate/tree/GrahamSH-LLK-Animated-Thumbnail/addons/full-signature) - It's **fully** implemented and it works great.~

See what I added [Here!](https://github.com/TheColaber/ScratchAddonsUpdate/tree/TheColaber-full-siggy/addons/full-signature) - It's **fully** implemented and it works great.

**Comment by GrahamSH-LLK** [comment]
A. You seem to have implemented this on my Animated Thumbnail branch. It includes other changes that aren't on master, so please implement this in a new branch. In the future, make your own branch.
B. Please don't use .innerHTML. You need to replace that with something else.

**Comment by TheColaber** [comment]
@GrahamSH-LLK 
A. Ok, I didn't realize that

B. I'll see what I can do.

**Comment by TheColaber** [comment]
@GrahamSH-LLK
What do I need to do to undo my changes to your branch?

**Comment by GrahamSH-LLK** [comment]
Otherwise, that looks amazing! Maybe you could make a select/input that lets you choose how many new items it adds each time.

**Comment by GrahamSH-LLK** [comment]
They aren't on _my branch_, they're on your fork to my branch. All you would have to do would be create a new branch, and copy your changes over.

**Comment by TheColaber** [comment]
@GrahamSH-LLK Why can't I use innerHTML? I'm not sure if there is a workaround for it...

**Comment by GrahamSH-LLK** [comment]
See #173

**Comment by TheColaber** [comment]
Ok I'll work on it

**Comment by TheColaber** [comment]
Alright Done.

**Comment by GrahamSH-LLK** [comment]
Great! You should make a PR.

**Comment by GrahamSH-LLK** [comment]
Never mind. You need to delete the "animatedthumbnail" folder and everything in it on your branch before making a PR.

**Comment by TheColaber** [comment]
@GrahamSH-LLK I just did that... It's not a fork and I have already made a fork before, so when I try to make another it goes to that.

**Comment by GrahamSH-LLK** [comment]
I mean the folder inside of the addons folder.

**Comment by Hans5958** [comment]
To be honest, he can just rename the folder to animated-thumbnail and squash commit will deal the rest, but that will works if you use Git and not the browser GitHub editor.

**Comment by GrahamSH-LLK** [comment]
Animated thumbnail is completely unrelated to this issue, he just accidentally edited his fork of my branch.

**Comment by TheColaber** [comment]
I'm not sure how to make one without a fork... Like I said before:

> It's not a fork and I have already made a fork before, so when I try to make another it goes to that.

**Comment by GrahamSH-LLK** [comment]
That's not the problem!

**Comment by GrahamSH-LLK** [comment]
I'm going to PR.

**Comment by TheColaber** [comment]
> I'm going to PR.

Yeah, that would be great!

**Comment by GrahamSH-LLK** [comment]
Actually, could you? Then I have temporary access to the repo so that I can straighten the whole animated thumbnail thing out.

**Comment by TheColaber** [comment]
> Actually, could you? Then I have temporary access to the repo so that I can straighten the whole animated thumbnail thing out.

IDK how to... I'm new to PRs
