### ISSUE TITLE
Call the "Mute" option something else

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#4955]
This:
![Right clicking the extension icon shows an option called Mute](https://user-images.githubusercontent.com/106490990/182968721-26aa08d2-399c-4ddd-aa30-2feee454e844.png)

"Mute" could mean:
- Turn off the sound
- Stop notifications
- Turn off the addons

It's slightly vague. Not too bad, but some percentage of users would get confused.

WorldLanguages said:
> It hides the message count, and disables notifications from the "Scratch Notifier" feature

Based on that, a more fitting, self-explanatory name might be:
- Do Not Disturb, or
- Disable Notifications

**Comment by WorldLanguages** [comment]
Needs discussion

**Comment by Cool-Scratcher** [comment]
This has confused me before. I thought it stopped the notification addon's sounds.

**Comment by mxmou** [comment]
I always thought this was only for notifications. I think the only unambiguous label would be something long like "Mute notifications and hide message count".

**Comment by Secret-chest** [comment]
Do Not Disturb

**Comment by WorldLanguages** [comment]
> I always thought this was only for notifications. I think the only unambiguous label would be something long like "Mute notifications and hide message count".

We could change the string dynamically depending on whether `scratch-notifier`, `msg-count-badge` or both are enabled.
It's also possible some users would want to mute notifications without hiding the count badge 🤔

**Comment by Samq64** [comment]
I agree with `Do not disturb`.

**Comment by BroJac5246** [comment]
I didn't know that this option even existed, but yes, I agree that its name should be changed.

I think that something along the lines of:

"Turn [On/Off] notifications and message count"

would be the most self-explanatory name.

That said, out of curiosity, do any of you use this feature? Like I said, I didn't even know that this existed.

**Comment by WorldLanguages** [comment]
This feature is focused at "Scratch Notifier" users, so they can mute notifications for a certain period of time without having to disable the addon and then remember to enable it.

**Comment by BroJac5246** [comment]
> This feature is focused at "Scratch Notifier" users, so they can mute notifications for a certain period of time without having to disable the addon and then remember to enable it.

Are you telling that to me?

**Comment by WorldLanguages** [comment]
> Are you telling that to me?

I'm just stating what the motivation to add the feature was

**Comment by DNin01** [comment]
If possible, we might also want it to only appear if Scratch Notifier is enabled. Otherwise, muting notifications would have no effect and therefore this setting should be hidden.

**Comment by WorldLanguages** [comment]
> Otherwise, muting notifications would have no effect

Keep in mind that muting also hides the message count.
The option should be hidden if and only if both `msg-count-bade` and `scratch-notifier` are disabled.

**Comment by DNin01** [comment]
Should we change it to Disable notifications/Enable notifications?

**Comment by BroJac5246** [comment]
> Should we change it to Disable notifications/Enable notifications?

That isn't clear that it affects the message count addon.

**Comment by DNin01** [comment]
> > Should we change it to Disable notifications/Enable notifications?
> 
> That isn't clear that it affects the message count addon.

Hmm, Hide messages, maybe?

**Comment by BroJac5246** [comment]
> > > Should we change it to Disable notifications/Enable notifications?
> > 
> > That isn't clear that it affects the message count addon.
> 
> Hmm, Hide messages, maybe?

But then it isn't clear that it affects Scratch Notifier.

**Comment by DNin01** [comment]
> > Hmm, Hide messages, maybe?
> 
> But then it isn't clear that it affects Scratch Notifier.

One or the other, eh?

I guess Do Not Disturb might be the best short message to imply that notifications will be tuned out like this. We could also add a notice to the Message count on extension icon addon that indicates that if you have SA's Do Not Disturb feature enabled, it won't display the message count.

**Comment by BroJac5246** [comment]
> > > Hmm, Hide messages, maybe?
> > 
> > But then it isn't clear that it affects Scratch Notifier.
> 
> One or the other, eh?
> 
> I guess Do Not Disturb might be the best short message to imply that notifications will be tuned out like this. We could also add a notice to the Message count on extension icon addon that indicates that if you have SA's Do Not Disturb feature enabled, it won't display the message count.

Do Not Disturb is a good general name if we can't think of anything better.

Either way, we should add a notice to the message count addon.
