### ISSUE TITLE
A feature to adjust the volume of all projects' sounds

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#4957]
### What this feature/function does

Some people who visit lots of projects know that some can have sound effects that are relatively loud. Some projects' music can be over twice as loud as most YouTube videos' commentary. You might leave your volume at a good level for YouTube, but then when you go to Scratch, the projects' music is _blasting_. That's why I'm proposing a feature here to allow you to turn down the master volume of all projects on Scratch so you don't have to think about it.

### How it works

This could probably be included in the ["Muted project player mode"](https://github.com/ScratchAddons/ScratchAddons/tree/master/addons/mute-project) addon, which would now be called "Volume control and muted mode" to fit the new function. There would be a new number input setting to change the overall volume of all Scratch projects. This will default to 100, which means no change, but you can change it to any number between 0 and 100. It is basically the master volume %. For example, at 50, all projects' audio will be only half as loud as they are normally.

### Alternatives I've considered

SA could also change this addon to add a button and slider on project pages to adjust the volume or mute the sound (like you can on YouTube with its volume slider). That's what #2755 suggests. We could also combine these two ideas, so the option I was talking about would just be the default and you could change the volume with the slider.

### Demonstration(s) and additional context

![Image of an addon's settings with a new setting to change the project volume](https://user-images.githubusercontent.com/106490990/182986003-9d4dbf93-0938-44f5-a448-0c4bb9c06833.png)

**Comment by BroJac5246** [comment]
Why would you need a shortcut to set a project's come to a certain percent? As you pointed out, the volume levels would still be inconsistent. While this could still be added, I believe that #2755 would be much more useful, since the user can adjust volume on a case-by-case basis.

That said, it might be worth pointing out that devices contain volume buttons for a reason.

**Comment by WorldLanguages** [comment]
The new addon on #4734 could have a "default volume" setting instead

**Comment by DNin01** [comment]
> That said, it might be worth pointing out that devices contain volume buttons for a reason.

I actually prefer those, but some people like to control just one app's volume for multiple reasons. That's where a volume slider for Scratch projects can be useful.

**Comment by Samq64** [comment]
> The new addon on #4734 could have a "default volume" setting instead

https://github.com/ScratchAddons/ScratchAddons/pull/4734/commits/83d23306cbfa988bd0b02c4c6ef41ede3be440cb
