### ISSUE TITLE
Drawing place in dark mode

### ISSUE THREAD

**Issue by LogSkele** [ScratchAddons/ScratchAddons#4958]
### Description

In the drawing space of a scratch project, (like where the checkered stuff are), in dark mode it's kinda dark too see much when you add dark text.

### Reproduction steps

1. Turn on darkmode
2. Create a project, or go into a random project 
3. Click the costumes of any sprite
4. Look at the drawing space

### Expected behavior

It shouldn't be that dark.

### Actual behavior

It's dark.

### Screenshots

<img width="679" alt="image" src="https://user-images.githubusercontent.com/79815764/183156270-5ae2267b-1583-4797-aec2-59cb655a89fd.png">

<img width="694" alt="image" src="https://user-images.githubusercontent.com/79815764/183156426-4707f8f7-9760-42d8-965b-e56118c617e8.png">

### Environment

- Browser: Microsoft Edge: Version 103.0.1264.77 (Official build) (64-bit)
- Scratch Addons version: 1.27.3
- Operating system: Windows

**Comment by mxmou** [comment]
The editor dark mode addon has a setting called "CHANGE THE COSTUME EDITOR BACKGROUND AND SELECTION BORDERS" that you can disable. Ideally it would be possible to do that from the costume editor itself.

**Comment by LogSkele** [comment]
fixed thanks.
