### ISSUE TITLE
Ability to open the cloud games in a new tab from within the cloud games addon

### ISSUE THREAD

**Issue by BoomerScratch** [ScratchAddons/ScratchAddons#496]
**Is your feature request related to a problem? Please describe.**

You can't directly open the cloud games in a new tab from within the cloud games addon.

**Describe the solution you'd like**

Add a button that allows opening the cloud games in a new tab.

**Comment by BoomerScratch** [comment]
I've tried this, but I'm not sure how Vue works. Can anybody help? https://github.com/BoomerScratch/ScratchAddons/tree/cloud-games-open-in-new-tab-button

**Comment by YOYITsM3M8** [comment]
I tested, it does not work clicking on the ‘pop out’ button does not work it falls through to the background.

**Comment by YOYITsM3M8** [comment]
The @click and v-on runs a VUE function. So you could define a vue function in popup.js that opens a tab with the specified project id

**Comment by BoomerScratch** [comment]
I have Vue working now, but I want to align the button after the text. Help?

**Comment by WorldLanguages** [comment]
@BoomerScratch Why a button? Just add a "href" attribute to the existing <a>

**Comment by WorldLanguages** [comment]
`:href="https://scratch.mit.edu/projects/{{project.id}}"` should work

**Comment by BoomerScratch** [comment]
@WorldLanguages A button looks nicer and probably doesn't annoy people.

**Comment by pufferfish101007** [comment]
> `:href="https://scratch.mit.edu/projects/{{project.id}}"` should work

But remember to add  ``` <base target="_blank">``` into the head, as in the messaging extension, otherwise it will try to open in the popup which **will not** work.

>  A button looks nicer and probably doesn't annoy people.

Just add a button inside an `<a>` tag i.e.:
 ```
<a :href="https://scratch.mit.edu/projects/{{project.id}}"><button>Open project</button></a>
```

**Comment by WorldLanguages** [comment]
> A button looks nicer and probably doesn't annoy people.

Tbh I don't think so. All bug reports said they links didn't work - they didn't say "a button is missing!"

**Comment by BoomerScratch** [comment]
Okay then.
