### ISSUE TITLE
Button to hide stage and expand sprite area

### ISSUE THREAD

**Issue by Chikorita-Lover** [ScratchAddons/ScratchAddons#4970]
### Is your request related to a problem? Please describe.

The sprite area is rather small in Scratch, and switching to different sprites can be annoying especially when a project has many sprites in it.

### Describe the solution you'd like

A button could be added next to the stage size buttons (just like the "Hide stage and sprite pane" addon) that hides the stage, and stretches the sprite pane up to fill the space that the stage normally occupies.

**Comment by DNin01** [comment]
Another place this button could be is over the sprite pane and it could appear as a handle (expand/collapse button with an arrow).

**Comment by Chikorita-Lover** [comment]
Hmm, would that be able to fit between the stage and the sprite pane? I don't think there's any room there for a button

**Comment by DNin01** [comment]
> Hmm, would that be able to fit between the stage and the sprite pane? I don't think there's any room there for a button

I think we could make this work.
![Image](https://user-images.githubusercontent.com/106490990/184049965-41233013-3647-474b-8ede-ef67e189d401.png)

**Comment by Chikorita-Lover** [comment]
I think you might have a larger screen, mine is only 1366 × 768, and there's almost no space there

**Comment by BroJac5246** [comment]
When on full screen on Chrome on my Chromebook, the website is 641px tall, and it's not enough.

I'm sure we could find a different spot for the arrow, though.

**Comment by DNin01** [comment]
> When on full screen on Chrome on my Chromebook, the website is 641px tall, and it's not enough.
> 
> I'm sure we could find a different spot for the arrow, though.

https://github.com/ScratchAddons/ScratchAddons/issues/4401#issuecomment-1207113309 might be able to help with that.

**Comment by BroJac5246** [comment]
> > When on full screen on Chrome on my Chromebook, the website is 641px tall, and it's not enough.
> > 
> > I'm sure we could find a different spot for the arrow, though.
> 
> https://github.com/ScratchAddons/ScratchAddons/issues/4401#issuecomment-1207113309 might be able to help with that when put together.

It's important to remember that the majority of users of this addon would likely have small screens.

I agree that an expand/collapse button is necessary, but there's not much space to put it.

Alternatively, we could rethink how Scratch displays the sprite list altogether, although that would be much more complicated. For example, we could have it expand when a mouse is hovering over it. <sub>That might create mobile compatibility issues, though</sub>
