### ISSUE TITLE
Global settings (for the whole extension)

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#498]
**Is your feature request related to a problem? Please describe.**

There is no global settings for the extension as a whole. What if they wanted to disable all of it within a single button, or they wanted to have the extension just run it "slowly" to solve some bugs for userscripts (probable future feature), or they wanted to set the theme into light/dark? (#497)

**Describe the solution you'd like**

Let us have a global settings for the whole extension, in a page preferably.

**Comment by WorldLanguages** [comment]
This has been in my mind since the beginning of the project, but I never created an issue (typical)

**Comment by Explosion-Scratch** [comment]
> This has been in my mind since the beginning of the project, but I never created an issue (typical)

I mean... #318 #275 #484

**Comment by Hans5958** [comment]
Well dropping ideas is nothing wrong

**Comment by WorldLanguages** [comment]
I want to work on this together with #9 - provide a setting on whether muting should hide the message count. Hiding it might be useful for some users in order to focus properly (it's tempting to check your messages), but not for all of them.

**Comment by Explosion-Scratch** [comment]
This would be really cool! Also would it be possible to edit the theme
color of scratchaddons itself? (You know, currently it's the orange, but
it'd be cool to adjust it)

**Comment by WorldLanguages** [comment]
Moving to v1.3
Dark/light mode appears to be the most important global setting, so it probably deserves its own dedicated button in the settings page - other less relevant settings deserve their home in here. Still TBD tho

**Comment by Hans5958** [comment]
I think it is better to move it to the global settings page, because it is still won't be clicked so often.
