### ISSUE TITLE
Blue submit button on forums

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#4990]
My suggestion is to make a new addon or option in an existing addon to color the forums Submit button blue, just like the Post button on comments.

Why? ...So it pops out _a little more_. This might also help it stand out from the ~~dreaded~~ Close topic button.

Just an idea.

**Comment by Samq64** [comment]
The Scratch 2.0 → 3.0 addon does that already: https://scratch.mit.edu/scratch-addons-extension/settings#addon-scratchr2

**Comment by DNin01** [comment]
> The Scratch 2.0 → 3.0 addon does that already: https://scratch.mit.edu/scratch-addons-extension/settings#addon-scratchr2

What if you only want a blue submit button without changing the whole forum theme?

**Comment by mxmou** [comment]
It already stands out compared to the "Go back" button/link next to it. I think that's good enough.

**Comment by WorldLanguages** [comment]
This sounds too specific to be a dedicated addons.
If you want to change the color of a specific button, write a userstyle and use Stylus.
