### ISSUE TITLE
addon.json addonEnabled for userscripts

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#4994]
### Is your request related to a problem? Please describe.

I'm trying to easily figure out if another addon is enabled from a userscript, bu the only thing I have to work with is `addon.self.getEnabledAddons()`.

### Describe the solution you'd like

An addon API that returns true if the specified addons are enabled.

**Comment by apple502j** [comment]
Addons shouldn't have to do this, why do you need this?

**Comment by Samq64** [comment]
> Addons shouldn't have to do this, why do you need this?

Trying to fix bugs in the silly volume slider addon.

**Comment by Norbiros** [comment]
```
!!addon.self.getEnabledAddons().find(e => e.id == "test-addon
```
?

**Comment by apple502j** [comment]
getEnabledAddons should not be used for this then. If a compatibility issue exists, fix the addon that breaks the addon, not the affected addon.
