### ISSUE TITLE
Clear unread messages when they are read through the extension

### ISSUE THREAD

**Issue by penguinmoose** [ScratchAddons/ScratchAddons#5000]
### Is your request related to a problem? Please describe.

I sometimes read messages through the extension. It’s a bit annoying when there are still unread messsges after I read them through the extension.

### Describe the solution you'd like

I think the extension should clear messages when they are read using the extension. This would prevent messages that are read through the extension to appear unread.

### Describe alternatives you've considered

- Maybe at least an option to clear messages when read through the extension that can be turned on and off.
- Alternatively, there could simply be a button to clear messages in the extension popup.

### Additional context

None

**_Oh, cool! This is number five thousand!_**

**Comment by apple502j** [comment]
There is already a button at the bottom.

**Comment by GrahamSH-LLK** [comment]
#5000 !!!!!
