### ISSUE TITLE
The "Load more" fix can be removed soon

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#501]
LLK/scratch-www#4473 has been merged, so after the next release of `scratch-www` the addon can be removed.

**Comment by WorldLanguages** [comment]
lol that pr took 2 weeks. oof

**Comment by mxmou** [comment]
@WorldLanguages LLK/scratch-www#4551
Apparently the release will be tomorrow.

**Comment by Explosion-Scratch** [comment]
Nice job Maximouse!
