### ISSUE TITLE
Infinite Scrolling skips posts in forum and misplaces some insertions

### ISSUE THREAD

**Issue by RT-Borg** [ScratchAddons/ScratchAddons#5014]
### Description

_**- pull request en route**_

**[Skip]**
On forum ("discuss") pages, the first page shows all 25 posts, but when the addon transfers posts from subsequent pages, a bug causes it to skip transferring every other post. For pages 2 and beyond, only 13 posts are displayed. (I've verified this carefully.)

**[Misplace]**
On some pages, the elements being inserted from the donor page are inserted after a footer instead of before.

### Reproduction steps

**[Skip]**
1. Enable Infinite Scrolling for Forums in settings
2. Visit a typical discuss page (e.g., [Help with Scripts](https://scratch.mit.edu/discuss/7/))
3. Scroll to a 2nd, 3rd, etc. page

**[Misplace]**
1. Enable Infinite Scrolling for Forums in settings
2. Visit a query page formatted as "posts" (e.g., [Show Your Posts](https://scratch.mit.edu/discuss/search/?action=show_user&show_as=posts))
3. Scroll just to the point where you transition from page 1 to inserting page 2

### Expected behavior

**[Skip]**
All posts should be displayed.

**[Misplace]**
Insertions should be above the footer.

### Actual behavior

**[Skip]**
Every other post is displayed.

In the code, the posts are collected in a live "posts" ElementCollection and iterated in a for loop. As post elements are appended/inserted, they are detached from the live collection being iterated. So as soon as item 1 is processed, the prior item 2 becomes item 1. The loop index also increments, so the prior item 2 is skipped.

**[Misplace]**
Insertions should be above the footer.

insertBefore() fails to find the footer element and defaults to inserting at the end of the parent, which leaves the footer above the page 2 insertions. This happens because the code is querying for a .linksb as the insertion point, and the page actually uses .postlinksb for the footer.

### Screenshots

**[Skip]**
Obvious if you're looking for it. Only 1/2 the items are listed.

**[Misplace]**
Note the footer between the final post of page 1 and the initial post of page 2:

![Infinite Scroll on Show your posts](https://user-images.githubusercontent.com/111162019/185768057-b943e63b-8475-4456-a5d2-61ac6bdda08f.PNG)

### Environment

Verified on Chrome and Firefox, current and pre-release versions of Scratch Addons.

Incoming PR verified in both browsers on pre-release.

### Additional context

**[Skip]**
This was broken a couple years ago in:
**Fix infinite scrolling on Show your topics/posts** #601

The changes section of that PR asked, "Why did the addon use innerHTML before?" The PR switched to append/insert post nodes, instead of inserting copies of the innerHTML, and introduced a bug in the posts iteration.

**Comment by RT-Borg** [comment]
Just a note: My fork is poorly named as "ScratchAddons-NecropostHighlighter". I didn't know when I created it for the (still in flight) Necropost Highlighter that I'd be limited to a single fork. I don't know whether I can safely rename the fork with pull requests outstanding.

**Comment by RedGuy12** [comment]
> I don't know whether I can safely rename the fork with pull requests outstanding.

You should be able to
