### ISSUE TITLE
An addon to allow reporter blocks to be in all dropdowns

### ISSUE THREAD

**Issue by penguinmoose** [ScratchAddons/ScratchAddons#5021]
### Is your request related to a problem? Please describe.

Often, it is necessary to put a reporter block (like an operator or variable) in a dropdown in a block. Usually, it is possible to do so because the dropdown is round which allows replacement with reporter blocks. However, certain blocks have rectangular dropdowns which cannot be replaced with reporter blocks. The only way to get around that is to use if-statements, which is inefficient, especially if there are a lot of options, or to use hacked blocks, which can be may be hard to obtain (I have not successfully made any hacked blocks before).

### Describe the solution you'd like

An addon to allow the replacement of all dropdowns with reporter blocks would be useful and also would save quite a bit of code.

### Describe alternatives you've considered

- An addon to turn all dropdowns into round dropdowns. Scratch already supports the replacement of round dropdowns with reporter blocks.

### Additional context

<img width="230" alt="Screen Shot 2022-08-21 at 5 59 43 PM" src="https://user-images.githubusercontent.com/67451414/185819956-4cf919d3-c3e3-4017-8a26-cc5112830eaf.png">

<img width="230" alt="Screen Shot 2022-08-21 at 6 01 14 PM" src="https://user-images.githubusercontent.com/67451414/185820029-ddd0d0ab-fc34-42d6-9b6c-27c8b3b2520f.png">

<img width="230" alt="Screen Shot 2022-08-21 at 6 02 33 PM" src="https://user-images.githubusercontent.com/67451414/185820095-96b457db-88a0-4bbf-803c-1feb151913b7.png">

**Comment by GarboMuffin** [comment]
So it is possible to manually edit project.json to fill a rectangle field with some inputs (didn't know this was impossible until a few minutes ago), however:

 - scratch-blocks will only display the dropdown, not your input
 - duplicating, backpack, etc. will not work
 - scratch-vm and scratch-blocks log warnings and sometimes throw various errors
 - switching from the costume or sound tab to the code tab will delete your input and revert the field back to a static dropdown (unrecoverable corruption)
 - sometimes you get Scratch sufficiently confused that the code editor will no longer render any scripts in that sprite (unrecoverable corruption without JSON editing)
 - compatibility with third-party runtimes, compilers, etc. is really bad

Some invasive traps could probably fix most of these, but that won’t fix the experience for anyone that doesn’t have the addon. This isn’t like folders where people without the addon just don’t see the grouping; people without the addon could have their entire project corrupted. I don't think this is viable as an addon.

Example project to play with: [input in field.sb3.zip](https://github.com/ScratchAddons/ScratchAddons/files/9390759/input.in.field.sb3.zip) (extract)

**Comment by mxmou** [comment]
> * duplicating, backpack, etc. will not work
> * switching from the costume or sound tab to the code tab will delete your input and revert the field back to a static dropdown (unrecoverable corruption)
> * normal script editing operations can make Scratch sufficiently confused that the code editor will no longer render any scripts in that sprite (unrecoverable corruption without advanced JSON editing)

That's more than enough for the Scratch Team to remove any project that uses this for not allowing remixing. It's definitely not viable as an addon.

**Comment by penguinmoose** [comment]
@mxmou Oh, I see.
