### ISSUE TITLE
`scratchstats` should still show the chart if user info is missing

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5022]
### Description

When trying the Profile statistics addon, it said that the statistics could not be loaded.

### Reproduction steps

1. Turn on the Profile statistics addon.
2. Go to a profile page.
3. Scroll down until you reach the Statistics area.

### Expected behavior

Statistics should show up below Followers.

### Actual behavior

It said that the statistics could not be loaded.

### Screenshots

![Error message: statistics could not be loaded.](https://user-images.githubusercontent.com/106490990/186002858-29e1d9e0-a42c-43be-a3ac-29859cbf4889.png)

### Environment

- Browser: Edge 104
- Scratch Addons version: 1.27.3 / 1.26.0 (modified)
- Operating system: Windows 10
- Enabled addons:
`clones, color-inputs, confirm-actions, copy-message-link, ctrl-enter-post, custom-zoom, dark-www, disable-sprite-wobble, editor-colored-context-menus, emoji-picker, expanding-search-bar, fullscreen, forum-toolbar, gamepad, hide-delete-button, hide-flyout, msg-count-badge, progress-bar, project-notes-tabs, resizable-comment-input, scratchstats`

### Additional context

Tested on D-ScratchNinja's (my) and TimMcCool's profile. Both threw the error multiple times.
scratchstats.com seemed to be working fine.

**Comment by mxmou** [comment]
> scratchstats.com seemed to be working fine.

![image](https://user-images.githubusercontent.com/51849865/186087717-3ad266fb-f273-4a55-90bd-bfef6a133037.png)
scratchstats.com doesn't have all the data either, it just replaces the numbers with question marks instead of throwing an error. The addon could do something similar.

**Comment by DNin01** [comment]
> > scratchstats.com seemed to be working fine.
> 
> scratchstats.com doesn't have all the data either, it just replaces the numbers with question marks instead of throwing an error. The addon could do something similar.

But it's also throwing the "same" error on TimMcCool's profile and this time, scratchstats.com shows the most followed rank for them.

**Comment by mxmou** [comment]
> > > scratchstats.com seemed to be working fine.
> > 
> > 
> > scratchstats.com doesn't have all the data either, it just replaces the numbers with question marks instead of throwing an error. The addon could do something similar.
> 
> But it's also throwing the "same" error on TimMcCool's profile and this time, scratchstats.com shows the most followed rank for them.

Could that be from your browser's cache? I only see the follower count.

**Comment by DNin01** [comment]
Oh! It just showed my statistics. Problem solved, then? I'll leave this issue open just in case it continues for me or anyone else.

**Comment by mxmou** [comment]
> Oh! It just showed my statistics. Problem solved, then? I'll leave this issue open just in case it continues for me or anyone else.

The ScratchDB issue has been fixed but we should make sure the addon doesn't break if it happens again.
