### ISSUE TITLE
Infinite Scrolling Load Beyond Limit

### ISSUE THREAD

**Issue by CodeLikeCrazE** [ScratchAddons/ScratchAddons#5029]
### Is your request related to a problem? Please describe.

I was looking for an old slightly offensive comment I made a while ago, and I wanted to apologize for it, and I scrolled and scrolled, but after around a year of messages, it just stopped. I disabled infinite scrolling and still it stopped.

### Describe the solution you'd like

I'm assuming this is a limit implemented a client, not on the server. My request is that Infinite Scrolling loads messages beyond the load limit.

### Describe alternatives you've considered

Infinite Scrolling should, instead of trying to click the load more button, actually fetches the messages from the API.

**Comment by Chiroyce1** [comment]
The Scratch API only stores messages upto a year ago, are you sure that comment was posted less than a year ago?

**Comment by mxmou** [comment]
Impossible. Messages don't have a client-side limit that we could change.
