### ISSUE TITLE
Add `.DS_Store` to gitignore

### ISSUE THREAD

**Issue by webdev03** [ScratchAddons/ScratchAddons#5045]
https://scratch.mit.edu/users/World_Languages/#comments-221456612
I am suggesting to add `.DS_Store` to the gitignore file. Maybe even add more things to the gitignore if necessary.
https://en.wikipedia.org/wiki/.DS_Store

This file is automatically generated by the Finder application on macOS computers. These files can sometimes come in git repositories when Mac users contribute. They are probably unnecessary for SA and also the Finder application doesn't even show these files, even when the option to show hidden files is on. The only way to see it is to use a different application like VS Code or `git status`. According to Wikipedia those files are also frequently changed so it would add more things to the commit log.

Do you think mac users should just add it to the global gitignore file on their device instead? Or do you think some people who are new to git would benefit from it being in the SA gitignore file?

**Comment by Chiroyce1** [comment]
Even GitHub's .gitignore generator doesn't automatically add .DS_Store to it, but I don't think there is any downside of adding one extra rule to the .gitignore for this project.

**Comment by RedGuy12** [comment]
Feel free to open a PR.

**Comment by Hans5958** [comment]
Resolved on #5096. Casual Apple didn't close issues.
