### ISSUE TITLE
`editor-dark-mode` incorrectly colors certain text in light themes

### ISSUE THREAD

**Issue by CST1229** [ScratchAddons/ScratchAddons#5056]
### READ BEFORE CREATING!

- [X] I understand

### Description

The Editor dark mode and customizable colors addon does not correctly set the text color for Code tab context menus and selected costumes/sounds to what their color would be on the highlight color.

### Steps to reproduce

1. Enable Editor dark mode and customizable colors
2. Enable the Scratch 2.0 or Scratch's default colors presets
3. Right click in the Code tab or select a costume/sound in their tabs
4. See bug

### Demonstration(s) and additional context

![](https://user-images.githubusercontent.com/68464103/187410787-eb10bb66-5ca2-4e9b-8d16-bdd3b3fc5f9f.png)
![](https://user-images.githubusercontent.com/68464103/187411102-b227ad82-eebe-44a8-a6ca-43f93d1325f8.png)

### Environment

Browser: Firefox 105.0b4
Scratch Addons version: v1.28.0
Operating system: Windows 10

**Comment by mxmou** [comment]
This was introduced in #4817
