### ISSUE TITLE
Reduce the number of addons running on "projects"

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#5060]
### READ BEFORE CREATING!

- [X] I understand

### Why this would be helpful/solve a problem

Addons like the remix tree button running on embeds and the editor for nothing. Same for editor addons that don't use the vm.

### What this change does

Make editor/project page addons that don't use the vm only load when I switch to the page it's actually going to be running on.

**Comment by apple502j** [comment]
Restricting embed does make sense, but it's probably not worth coding extra logic with editor just for those. Project page and the editor are the same page technically, and the addon determines which part it is displayed at.

**Comment by mxmou** [comment]
The embed page uses a separate match pattern (`projectEmbeds`) and most project page addons don't run there.
