### ISSUE TITLE
Hide "I understand" checkbox

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#5061]
### READ BEFORE CREATING!

- [X] I understand

### Why this would be helpful/solve a problem

The "I understand" checkbox with the "READ BEFORE CREATING!" header and no other text clutters the issue and looks little silly to anyone viewing the issue after it is created.

### What this change does

Hiding the checkbox after the issue is created. (This can already be done through editing since the template only appears the first time)

### Possible alternatives

Removing it.

### Demonstration(s) and additional context

![image](https://user-images.githubusercontent.com/81489795/187536713-d4f32848-1c10-40c4-b4bd-e6184b23733f.png)

**Comment by BroJac5246** [comment]
It also adds the text "1 Done," since it's considered a checklist. This can be confusing.

**Comment by WorldLanguages** [comment]
Agreed, should be removed from the form
It is annoying even if it didn't add "1 task done" to every issue

**Comment by DNin01** [comment]
Um... whoa - I didn't know it did that.
