### ISSUE TITLE
Improve the setting name "Use previous color instead of default when switching tools"

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5074]
This is a text change.

### What I'm talking about

[**"Use previous color instead of default when switching tools"**](https://github.com/ScratchAddons/ScratchAddons/blob/1a40713a6414f13df7e65f3b0584a4b06a540edf/addons/default-costume-editor-color/addon.json#L37) from the `default-costume-editor-color` addon's settings. If you're wondering what that means, if the fill color is set to transparent and you select the brush tool, Scratch, by default, resets the color to purple so you have a color to draw with (and something similar happens with the outline color). This addon option makes it so that instead of being switched back to the default color, it changes back to the previous fill or outline color you used.

This option may take some time for some people to understand, but it can be pretty hard to choose a concise name for that option and have everyone understand it. Should we try to find a better name?

### Possible changes
My ideas are:
- Recall previous color instead of resetting after switching tools
- Don't reset to default color after switching tools

This is worth discussing _thoroughly_ - I'd love if we could work together to find _the_ most easy-to-understand but still concise description possible for that option, especially since Scratch Addons doesn't have extended option descriptions (yet).

### Don't understand what I mean? Let me show you

https://user-images.githubusercontent.com/106490990/188237242-68f52189-816e-46c2-932f-030bab24adba.mp4

**Comment by BroJac5246** [comment]
When you have the context, this name makes sense to me, but I do agree that "Don't reset to default color after switching tools" would be more clear.

**Comment by WorldLanguages** [comment]
By the way, a potential redesign of the settings page would allow us to add longer descriptions, and possibly screenshots and links, to each setting.

**Comment by BroJac5246** [comment]
> By the way, a potential redesign of the settings page would allow us to add longer descriptions, and possibly screenshots and links, to each setting.

That would take a while, though, so I think this would be a good solution for now

**Comment by WorldLanguages** [comment]
In the meantime, I think we could change the setting name to `Recall previous color instead of resetting after switching tools` (first suggestion on issue original post) and add an info UI element to the addon that explains this better, with a real sentence.
