### ISSUE TITLE
Easter egg addons

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#508]
@WorldLanguages is going to code a way to use easter eggs.

**Comment by Hans5958** [comment]
I don't understand. What do you mean using easter eggs? I thought we can just code our own stuff for that.

Also, what's with the moving issues?

**Comment by WorldLanguages** [comment]
It will just be a way to get a secret panel of "hidden" addons

**Comment by Hans5958** [comment]
Yeah, but that would be a seperate feature than #169. This issue is about the secret easter egg addons. #169 is about the easter egg implemenation as a whole.

**Comment by WorldLanguages** [comment]
Then #169 should be moved to discussions :P

**Comment by Hans5958** [comment]
> 
> 
> Then #169 should be moved to discussions :P

Right. #169 seems like something that won't be closed in near time.

**Comment by lisa-wolfgang** [comment]
One of the easter egg addons could be loading the April Fools' 2020 editor.

**Comment by YOYITsM3M8** [comment]
Yes

**Comment by GrahamSH-LLK** [comment]
> One of the easter egg addons could be loading the April Fools' 2020 editor.

That's nearly impossible. Reproducing it? That's feasible. I've already coded something that brings back the semicolon glitch.

**Comment by WorldLanguages** [comment]
Fixed by #1177
