### ISSUE TITLE
An addon that prevents the device from falling asleep

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5084]
### Why this would be helpful/solve a problem

When you’re watching an animation on a device that is set to lock quickly, the screen will keep dimming because you’re not touching it.

### What this addon does

This addon would prevent the screen from locking while a project is running.

This could potentially drain your battery if you forgot to stop a project, so there could be a timeout where if you don’t touch anything for some amount of time, say, 5 minutes, plenty of time for most animations, the addon will let the screen lock.

### Possible alternatives

Not that I know of.

**Comment by apple502j** [comment]
I believe this has to be configured on Windows Settings.

**Comment by WorldLanguages** [comment]
Probably not well suited as an addon part of SA.

**Comment by mxmou** [comment]
This is specifically for preventing the device from falling asleep while a project is running so I think it could be a useful addon.

**Comment by apple502j** [comment]
I do not believe browsers would provide such options.

**Comment by BroJac5246** [comment]
I don't know if it'll be useful or not, but I found this: https://stackoverflow.com/questions/6106747/can-i-prevent-phone-from-sleep-on-a-webpage#6107010

I know some devices attempt to prevent locking while certain media is playing, but that would vary from OS to OS.

**Comment by Secret-chest** [comment]
> I do not believe browsers would provide such options.

I think you can play a video.

**Comment by pufferfish101007** [comment]
The [https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API](WakeLock api) exists, albeit only in chrome.

**Comment by Norbiros** [comment]
IMO we should use `hidden video` for now, but when mozilla gonna [add this in the future](https://mozilla.github.io/standards-positions/#screen-wake-lock) we can just switch...
