### ISSUE TITLE
An addon that lets you highlight and copy the value of a variable

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5085]
### Why this would be helpful/solve a problem

A few times, I’ve wanted to copy a long variable value (in other words, the text or number a variable is set to) to do something with it. I actually end up having to make a list, add the variable’s value to the list, and then copy the list item. You can probably see why this becomes tedious.

### What this addon does

Allows you to select variable values and copy them.

### Possible alternatives

Use the variable manager addon and find the variable.

**Comment by apple502j** [comment]
Variable manager sort of provides it?

**Comment by BroJac5246** [comment]
> Variable manager sort of provides it?

True, but this could still be useful. I personally don't use the variable manager because I feel that an entirely new tab is just too much. A simple option in the right-click popup to copy the value of a variable would, in my eyes, be potentially useful.

**Comment by WorldLanguages** [comment]
Unconvinced, but not rejected I guess...
Would be better if we find a way to make this part of a bigger addon, instead of just an "copy variable value to clipboard" addon which only does this

**Comment by DNin01** [comment]
Resolved by #5471.

**Comment by DNin01** [comment]
Although, it might be useful to be able to copy them from outside the editor, which is I think what I meant here. Would that be useful? If so, this can be reopened.

**Comment by WorldLanguages** [comment]
Unsure. Values that the project author intends to be copy-able are often list items. For other cases, going inside for a moment wouldn't take a lot of effort.
