### ISSUE TITLE
Resizable comment input addon

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#509]
**Describe the new addon**

Makes the comment input box on projects vertically resizable. See https://scratch.mit.edu/discuss/topic/400881/

I have already implemented this, but don't want to make a PR yet (conflicts).

**Link to the new addon**

https://mxmou.github.io/customize-scratch/#resizable-comment-inputs

**Comment by TheColaber** [comment]
Updates?

**Comment by mxmou** [comment]
@TheColaber Adding this would create conflicts in #507 and #602. If you don't think any of these will be merged soon I can make a PR for this.

**Comment by WorldLanguages** [comment]
@mxmou Please send the PR anyway
