### ISSUE TITLE
Integrate changing colour into customizeable navbar addon.

### ISSUE THREAD

**Issue by UniqueName12345** [ScratchAddons/ScratchAddons#5094]
### Why this would be helpful/solve a problem

Sometimes, I am not feeling like a blue banner. Maybe I want it green or red. This will allow users of the addon to change their banner colour to a hex colour.

### What this change does

There will be 2 new options:

- Primary hex color (a text box, "primary" means the banner itself)
- Text hex color (a text box, and the color of the text)

They will both accept hex color, and will both be applied upon restart.

### Possible alternatives

We could also make this an entirely separate addon.

### Demonstration(s) and additional context

(banner is the splash of color that appears at the top of scratch pages, excluding editor and a few other obscure pages)

**Comment by mxmou** [comment]
There is already a setting for this in the website dark mode addon. If you don't want dark mode you can choose the "Scratch's default color" preset.

**Comment by UniqueName12345** [comment]
> There is already a setting for this in the website dark mode addon. If you don't want dark mode you can choose the "Scratch's default color" preset.

Whoops! Forgot to look in SA _that_ much...
