### ISSUE TITLE
New addon: Make project shared

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#510]
**Describe the new addon**

As the title says. Unshared projects become shared. Magic.
**Link to the new addon**

https://github.com/forkphorus/cat-plus/blob/master/make-projects-shared.user.js

**Comment by mxmou** [comment]
Considering that the deleted comments addon was removed, I don't think this will be added.

**Comment by WorldLanguages** [comment]
Yeah. In the same way I agree deleted comments should actually be deleted, unshared projects should stay unshared. It's sad that this is possible.

**Comment by Hans5958** [comment]
I wonder why is this closed. Considering that people can just use Forkphorus/Leopard/TurboWarp to get the same effect, I don't see why this exact effect should be excluded here.

**Comment by WorldLanguages** [comment]
@Hans5958 For the same reason we removed the "see deleted comments" addon.

**Comment by mxmou** [comment]
@WorldLanguages Could the deleted comments addon be re-added if it only affected your own profile?

**Comment by Hans5958** [comment]
> 
> 
> @Hans5958 For the same reason we removed the "see deleted comments" addon.

Yeah, but that is compared to this suggestion, which method is more widely known, compared to the "see deleted comments" one.

**Comment by Explosion-Scratch** [comment]
True...

**Comment by JeffaloBob** [comment]
we need to make a fork where its not on the webstore and we just go out and make all of the crazy things

**Comment by YOYITsM3M8** [comment]
> we need to make a fork where its not on the webstore and we just go out and make all of the crazy things

+ 100m support

**Comment by Explosion-Scratch** [comment]
I sorta suggested that https://github.com/ScratchAddons/ScratchAddons/discussions/555

**Comment by apple502j** [comment]
Please no.
