### ISSUE TITLE
Custom scratch logo

### ISSUE THREAD

**Issue by Unkrown6YT** [ScratchAddons/ScratchAddons#5100]
### Why this would be helpful/solve a problem

Idk

### What this addon does

Customize scratch logo images

**Comment by mxmou** [comment]
Related: #4467

**Comment by BroJac5246** [comment]
Could this be added to the Customizable Navigation Bar addon?

**Comment by TheColaber** [comment]
That would seem like devtools all over again, or maybe that's just me

**Comment by Unkrown6YT** [comment]
> Could this be added to the Customizable Navigation Bar addon?

Yep

**Comment by WorldLanguages** [comment]
This is "too much customization", unless we provide Scratch logo replacement presets that make enough sense.

**Comment by WorldLanguages** [comment]
https://github.com/ScratchAddons/ScratchAddons/discussions/4467#discussioncomment-2524473 describes how to achieve this with Stylus.

Tell me if I'm missing any obvious reason users would want to change the logo. Maybe as part of a prebuilt "theme" (not the current themes - I mean something futuristic we might provide, where users submit their own presets and they're available in a pseudo-store)
