### ISSUE TITLE
Replace scratch player with turbowarp player

### ISSUE THREAD

**Issue by 0K9090** [ScratchAddons/ScratchAddons#5106]
### Why this would be helpful/solve a problem

This is for the people who need their project to be fast, but like the addons that turbowarp doesn't include

I might be stupid, so i'm sorry if i'm wasting anybody's time

### What this addon does

by enabling this, you have the option between scratch player, turbowarp player, or forkphorus. 

### Possible alternatives

We could add some scratch addons to turbowarp...

**Comment by mxmou** [comment]
This already exists as an option in the "TurboWarp button" addon. Using addons that TurboWarp doesn't support is unfortunately not possible.

**Comment by GarboMuffin** [comment]
> addons that turbowarp doesn't include

You should let us know which ones you want so we can maybe prioritize them: https://github.com/TurboWarp/scratch-gui/issues/new

**Comment by 0K9090** [comment]
i juset tested it, you can't replace the player in the editor for some reason

**Comment by mxmou** [comment]
> i juset tested it, you can't replace the player in the editor for some reason
> 
> why not?

The editor would have to be replaced as well (or TurboWarp wouldn't know what you changed) which isn't very different from just using TurboWarp.
