### ISSUE TITLE
Sprite in its own dropdown

### ISSUE THREAD

**Issue by 0K9090** [ScratchAddons/ScratchAddons#5107]
### Why this would be helpful/solve a problem

say you need a sprite to detect if it's touching of its clones. lets name the sprite apple. you'd have to go to another sprite and get the touching block from that sprite, then drag it to the apple sprite. this addon will save you the trouble of doing that.

### What this addon does

you could just stay in the apple sprite and select apple from the dropdown

### Possible alternatives

use a join block or just go into another sprite to get it

**Comment by CST1229** [comment]
In development: #4636

**Comment by 0K9090** [comment]
> In development: #4636

ok

**Comment by Hans5958** [comment]
@mxmou There is an issue for that on #3396, so this is a duplicate.
