### ISSUE TITLE
HQ Video recording?

### ISSUE THREAD

**Issue by jadasse** [ScratchAddons/ScratchAddons#5139]
### Why this would be helpful/solve a problem

The video recording quality is very bad, the VP8 encoding is very lossy, and the frame rate and duration are not handled correctly. The quality can ruin some sprites of smaller sizes.

### What this change does

This improves the encoding quality of the video, like VP9 or high-bitrate AVC. Quality can also be adjusted by bitrate or quality number (if it uses FFmpeg) Also, this will allow the user to set a custom 4:3 resolution, like 1440x1080, 960x720, 640x480, etc. It also handles the 30-fps frame rate and the duration of the recording correctly, it shows them in FFprobe or Mediainfo.

### Possible alternatives

One could use recording software like OBS, but it is not as convenient.

**Comment by apple502j** [comment]
Those who need better quality should use proper screen recording software. Browser does not provide record quality and resolution beyond the size of the stage.

**Comment by BroJac5246** [comment]
> Those who need better quality should use proper screen recording software. Browser does not provide record quality and resolution beyond the size of the stage.

Still, Scratch Addons provides a level of convenience not available to other software, since it runs directly on the Scratch website.

Therefore, I believe that such an addition to the media recorder should at least be considered.

**Comment by apple502j** [comment]
Considered and rejected.

**Comment by jadasse** [comment]
> Considered and rejected.
> 
> 
> 
> There are limitations caused by the fact that it runs directly on the website; this is one of them.

Bummer.

**Comment by DNin01** [comment]
#8031 did manage to do this.
