### ISSUE TITLE
FPS Viewer addon

### ISSUE THREAD

**Issue by Mr-Anonymous75** [ScratchAddons/ScratchAddons#5147]
### Why this would be helpful

Right now, scratchers have to implement a somewhat complicated (not the simplest, at least) script to view their fps while making a project. I'm not sure, but the fps-viewing script itself probably has an effect on the fps it's showing - and that's no good when you want to know how well your project runs. <sub><sup>Plus those variable displays look kinda ugly</sup></sub>

However, I'm sure there's a way to find out what fps a project is running at using an addon - and that would fix that problem.

### What this addon does

It'll add a display, similar to the one used by the clone counter, showing the current fps.

### Possible alternatives

FPS-displaying functionality could somehow be added to the debugger addon instead.

### Demonstration

![image](https://user-images.githubusercontent.com/73294041/193202374-669c4bab-6314-474a-acc5-7dbd68b01081.png)

**Comment by Norbiros** [comment]
We have debugger addon where you can see current FPS:
![Screenshot from 2022-09-30 08-54-16](https://user-images.githubusercontent.com/89837724/193209229-942335ac-cd64-475a-b905-62aeac45d6d7.png)

**Comment by Mr-Anonymous75** [comment]
> We have debugger addon where you can see current FPS: ![Screenshot from 2022-09-30 08-54-16](https://user-images.githubusercontent.com/89837724/193209229-942335ac-cd64-475a-b905-62aeac45d6d7.png)

I guess I should've checked before posting this

**Comment by Samq64** [comment]
There's also #3656
