### ISSUE TITLE
A feature to see someone's operating system and browser

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5167]
### Why this would be helpful/solve a problem

Sometimes, in order to narrow down issues people are experiencing, it's helpful to know their device and software details. But sometimes, people remove that information from their bug reports.

### What this change does

[Scratchstats](scratchstats.com) already seems to have some sort of way to guess the operating system and browser people on Scratch are using. I have no idea how it works but it's gotta be really cool. Scratch Addons could use whatever algorithm that is to show you the operating system and browser any user you view is using.

Also, if possible, we could pull this information from the `My browser / operating system:` label on a recent post from a user, which might be more reliable.

### Possible alternatives

Find the information yourself (it's already visible on Scratchstats).

### Demonstration(s) and additional context

This could show up below post authors' original posts and on profile pages.

**Comment by apple502j** [comment]
Rejected - this is not useful (for most users) as an addon.

**Comment by BroJac5246** [comment]
> Rejected - this is not useful (for most users) as an addon.

This could potentially be added as an option for the ScratchStats addon.

**Comment by CST1229** [comment]
> [Scratchstats](scratchstats.com) already seems to have some sort of way to guess the operating system and browser people on Scratch are using. I have no idea how it works but it's gotta be really cool. Scratch Addons could use whatever algorithm that is to show you the operating system and browser any user you view is using.

Scratch stores the user's browser and operating system in each project saved in 3.0. Scratchstats grabs the latest project and gets the info from there.

**Comment by BroJac5246** [comment]
> > [Scratchstats](scratchstats.com) already seems to have some sort of way to guess the operating system and browser people on Scratch are using. I have no idea how it works but it's gotta be really cool. Scratch Addons could use whatever algorithm that is to show you the operating system and browser any user you view is using.
> 
> Scratch stores the user's browser and operating system in each project saved in 3.0. Scratchstats grabs the latest project and gets the info from there.

Could be have an addon that spoofs that data to keep the user's OS anonymous?

**Comment by DNin01** [comment]
> Scratch stores the user's browser and operating system in each project saved in 3.0. Scratchstats grabs the latest project and gets the info from there.

I've seen that info in project.json files too!

**Comment by WorldLanguages** [comment]
ScratchStats.com gets browser/OS info exclusively from the most recently shared project's project.json userAgent property.
