### ISSUE TITLE
Context menu from sprites hiding behind stage

### ISSUE THREAD

**Issue by ArcherThesu** [ScratchAddons/ScratchAddons#5185]
### Description

The context menu (right click) on sprites seem to be hiding behind the stage?

### Steps to reproduce

1. Zoom in on big monitors
2. Create new sprite
3. create new folder with that sprite in it
4. open the new folder
5. right click the sprite
6. the "Duplicate" button in the context menu isn't there, most likely because it's hiding behind the stage.

### Demonstration(s) and additional context

![image](https://user-images.githubusercontent.com/96303291/195212220-3470d27a-aff0-4cfa-a1e1-f458929bd29e.png)

### Environment

Browser: Opera GX
Scratch Addons version: 1.28.0
Operating system: Windows 10

**Comment by WorldLanguages** [comment]
@ArcherThesu Is this caused by an addon? Or is this a vanilla Scratch bug?

**Comment by ArcherThesu** [comment]
@WorldLanguages I'm not sure. You can't have a long enough menu in scratch from the sprites I think..?

**Comment by WorldLanguages** [comment]
Sorry, I misread the issue, my bad

**Comment by WorldLanguages** [comment]
Could you go to Scratch Addons settings > More Settings > Export Settings and send the JSON file?

As well as doing this, please try this:
1. Create a new Opera/Chrome profile
2. Only install Scratch Addons into this new profile
3. Import the JSON file into Scratch Addons settings
4. Check if the issue persists. If it does, any details on your monitor resolution, browser font size, zoom level, etc. would help

**Comment by ArcherThesu** [comment]
For some reason, after switching workspaces (misinterpreting profile) in Opera, both workspaces started showing the Duplicate button? however, the duplicate button seems a bit cut-off.
![image](https://user-images.githubusercontent.com/96303291/195216872-ac21c99a-70c8-44dc-a83b-06607059598d.png)
I cant send the json file because github doesnt support.. the resolution is 1920x1080.

**Comment by ArcherThesu** [comment]
@WorldLanguages also I tried on chrome and the above also happens with the following steps. It seems like the original issue is solved somehow?

**Comment by ArcherThesu** [comment]
ok wait a minute all the sudden when I recreate the folder, it does the thing again..? when I create that folder the things inside it on the second row does the thing

**Comment by WorldLanguages** [comment]
> I cant send the json file because github doesnt support

You could try Scratch Addons settings > More Settings > View Settings File
And paste it into pastebin.com

**Comment by ArcherThesu** [comment]
Here's the pastebin link: https://pastebin.com/GtvCfnfg

**Comment by TheColaber** [comment]
Caused by hide-flyout. You have to zoom in on big monitors in order to repro.

**Comment by WorldLanguages** [comment]
Reported through feedback:

> Hi! I'm not sure what's causing but if you have the extension "Auto-hiding block palette" enabled it makes the context menu for sprites go under the testing screen making it so you can't access some features if you have folders enabled because it adds all the folders to the context menu. I hope you can get this fixed!
