### ISSUE TITLE
New SA setting: "display addon names in English"

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#5186]
### Why this would be helpful/solve a problem

Until we can solve #2670 directly, we should allow users to see addon names, description, setting names, etc. in English, even if their browser language is set to a different language that we support.
Tags such as "Recommended" and other strings would remain in that language, but many users would still appreciate the feature.

### What this change does

A new setting available on "More Settings", which could be named "display addon names in English".
We could add a small "beta" tag next to it, to indicate that it's meant to be temporal. In the future, we should let the user set the whole SA UI to any of the supported languages, and it would affect everything except the extension description.

The value of this setting would be stored in `chrome.storage.local`, it would not be exportable through the JSON file, and it would set `useDefault` to `true` on this line: https://github.com/ScratchAddons/ScratchAddons/blob/master/background/load-addon-manifests.js#L42

Changing this setting would require reloading the extension, with exactly the same logic as importing a JSON settings file.

### Possible alternatives

Waiting until we can provide an actual language selector, and allow users to choose other languages, not just English.
But I've seen too many suggestions about this. I even saw users asking how to change the language on Reddit (r/scratch).

**Comment by ksdavidc** [comment]
I just want to say thank you. I noticed this by accident, but BOY am I happy. This is a big deal for me (for reasons too lengthy to explain), and I am really glad you added it! Now if only we can get chrome to allow changing the language on macs without having to change the whole bloody system language, we'll be home free. Thanks!!! 

Speaking of which, what would really tickle my buns is if, in the case that english is not the default, that one could somehow see the english, but also (in some way, tooltip, control key, etc.) see the original language version. In other words, could one see BOTH languages??? I know it is probably unmanageably complicated, but if you are going in a tweaking things, perhaps there might be natural way to make it happen? 

To motivate this a little, perhaps insufficiently, I guess I have to explain my scenario after all. I'll generalize a bit:  Someone teaches scratch to foreigners. They both have SA installed, and the teacher wants to tweak a setting. They know the name of the setting in English, but have to find it in the other computer. Your setting allows them to make the english name to appear on the other computer. BUT, the user of the other computer doesn't know the name of the setting in their language. It would be helpful if they could see that as well, for example to help them find the setting later.

**Comment by WorldLanguages** [comment]
> could one see BOTH languages??? I know it is probably unmanageably complicated

Indeed - I think there are better ways to deal with situations like that. For example, addons and settings already have unique English IDs (outside of the localization system, they're only used as internal identifiers), so we could add a setting to show those.
