### ISSUE TITLE
Bigger save now button "hitbox"

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5189]
### Why this would be helpful/solve a problem

A lot of the time when I want to manually save, I have to move the mouse pointer somewhat precisely to hit the Save Now button in the top-right corner.

### What this addon does

This addon increases the size of the Save Now button's clickable area by increasing its padding height. This means that even if your mouse pointer lands slightly above or below the Save Now button, it can still click it.

Size before:
![The hit area is only on top of the text, not very forgiving](https://user-images.githubusercontent.com/106490990/195455700-fdaf4361-fceb-4128-a8cf-5751b0fc4236.png)

Size after:
![The hit area stretches slightly above and below the text for a bigger clickable button area](https://user-images.githubusercontent.com/106490990/195455794-7c86ea7c-dd9e-4c9c-be8c-4f94c48da267.png)

I would use this addon every day if I used Scratch Addons daily.

### Possible alternatives

Get used to Ctrl+S.

### Demonstration(s) and additional context

I already have a working userstyle for this that I will share in a PR soon if you think this addon is worth it.

Also, any name suggestions?

**Comment by BroJac5246** [comment]
> Also, any name suggestions?

"Larger 'Save Now' Button"?

**Comment by mxmou** [comment]
This is a very small change so it might be better to suggest it in scratch-gui.

**Comment by CST1229** [comment]
> This is a very small change so it might be better to suggest it in scratch-gui.

I'm pretty sure that will just stay there open forever and not get any official response.

**Comment by mxmou** [comment]
> > This is a very small change so it might be better to suggest it in scratch-gui.
> 
> I'm pretty sure that will just stay there open forever and not even get any official response.

Someone can open a PR if the issue gets a priority label.

**Comment by WorldLanguages** [comment]
This could be considered as an addon, but please create an issue on scratch-gui first. Send a link if it already exists.

**Comment by DNin01** [comment]
> This could be considered as an addon, but please create an issue on scratch-gui first. Send a link if it already exists.

Just did. https://github.com/LLK/scratch-gui/issues/8571

Should we still make an addon?

**Comment by BroJac5246** [comment]
> > This could be considered as an addon, but please create an issue on scratch-gui first. Send a link if it already exists.
> 
> Just did. https://github.com/LLK/scratch-gui/issues/8571
> 
> Should we still make an addon?

You can always start developing one, but it probably wouldn't be added until the submitted issue in the scratch-gui repo is responded to (at the earliest).

**Comment by DNin01** [comment]
> You can always start developing one, but it probably wouldn't be added until the submitted issue in the scratch-gui repo is responded to (at the earliest).

I also think that's a good time to decide whether to add the feature to SA or not. I'll start my PR in a couple days or when the referenced issue gets a priority label, whichever is sooner.

**Comment by WorldLanguages** [comment]
Let's give the Scratch Team a week to label the issue hopefully...?

**Comment by DNin01** [comment]
They just labeled my issue. I'm checking their response right now…

**Comment by WorldLanguages** [comment]
> Someone can open a PR if the issue gets a priority label.

@mxmou They added the priority-3 label. Is help-wanted necessary to submit a PR?
I don't think we should consider adding this as an addon until there's an unmerged PR on scratch-gui for ~3 months

**Comment by mxmou** [comment]
> They added the priority-3 label. Is help-wanted necessary to submit a PR?

Help wanted means that PRs are more likely to be accepted. If the issue doesn't have help wanted, it's probably a good idea to ask a ST member before submitting a PR.

**Comment by DNin01** [comment]
This may be fixed by the PR I just made.

**Comment by WorldLanguages** [comment]
Update: https://github.com/LLK/scratch-gui/issues/8571#issuecomment-1429961659

**Comment by WorldLanguages** [comment]
> This may be fixed by the PR I just made to scratch-gui.

No progress so far

**Comment by DNin01** [comment]
If we ever create addon categories such as Accessibility, this addon could go there.

**Comment by Samq64** [comment]
Maybe it could be converted to a button and be greyed out when there aren't any changes to save?

**Comment by WorldLanguages** [comment]
Would it be too bad to enable this by default to all Scratch Addons users?

There are situations where you definitely don't want to save a project (the "disable auto-save" addon exists for this reason), but hopefully no user is already clicking just below the "Save Now" button expecting the project not to save?

**Comment by Secret-chest** [comment]
> Should it be a more generalized addon for increasing the size of various buttons or is the current idea okay?

This doesn't increase the button size, only makes the padding clickable.

**Comment by DNin01** [comment]
> Would it be too bad to enable this by default to all Scratch Addons users?

I don't really like having to enable things by default because a user who didn't take a look at the addons that were already enabled may not be aware that we are modifying Scratch without their knowledge and might think Scratch added a feature if they discover it later, BUT... this one is so subtle and probably won't result in discussion even if Scratch did this, so I think we could consider enabling it by default without much of a problem.

**Comment by DNin01** [comment]
Also, we should make sure this is compatible with #4018 if it is implemented.

**Comment by DNin01** [comment]
Still doesn't feel quite right for this to be the only feature of a new addon. Are there any other places we could put this? Or could we combine other features with this new addon to make it more substantial? Like maybe there are other buttons and links that could have bigger hitboxes.

**Comment by WorldLanguages** [comment]
> Are there any other places we could put this

I guess this could be a setting for #6297, hopefully we can add setting descriptions by then.

**Comment by DNin01** [comment]
What about a "better buttons" addon? It would offer a few customization options for buttons and button-links, including increasing the paddings.

But then not having #6409 would get in our way.

**Comment by BroJac5246** [comment]
> What about a "better buttons" addon? It would offer a few customization options for buttons and button-links, including increasing the paddings.

I like the idea. But what other buttons can this affect?

> But then not having #6409 would get in our way.

Yeah that could be a problem.

**Comment by WorldLanguages** [comment]
@BroJac5246 I believe the GitHub user you pinged is no longer working for the Scratch Team

**Comment by BroJac5246** [comment]
I'd like to make this addon, if that's okay?

I have a mostly-working userstyle that I created.

**Comment by DNin01** [comment]
> I'd like to make this addon, if that's okay?
> 
> I have a mostly-working userstyle that I'm working on.

You can open a pull request, but just be aware that I'm still trying to think of a better way to conduct this.
