### ISSUE TITLE
Forum "Run Code" Button

### ISSUE THREAD

**Issue by lankybox02** [ScratchAddons/ScratchAddons#5198]
### Why this would be helpful/solve a problem

Using this addon, it would be easier to test out codes without having to open your console.

### What this addon does

This addon would add a "run" button to all javascript and HTML [code] tags on the forums

### Demonstration(s) and additional context

Sorry if this is a duplicate or already implemented, haven't been using scratchaddons for a while now

**Comment by mxmou** [comment]
This would probably be complex (the code would have to be sandboxed because running it on the Scratch domain is dangerous) and not very useful (forum post usually contain short code snippets, not complete scripts).

**Comment by apple502j** [comment]
Rejected, see above for reason.
