### ISSUE TITLE
Addon to Improve the Editor's Margins and Borders

### ISSUE THREAD

**Issue by BroJac5246** [ScratchAddons/ScratchAddons#5243]
### Why this would be helpful/solve a problem

The current Scratch editor is cool, but I'm not a huge fan of the current lack of margins in some locations. The sprite pane, stage button, and backpack button all appear to be cut off on the bottom, and, despite this being intentional, I don't like the way it looks.

### What this addon does

I'd like an addon that adds margins (and borders) to all of these elements (and possibly a few others), giving the editor an overall simpler feel. This would also remove the unsettling illusion of the editor having infinite height. I'm currently creating an addon that improves this, so I'm opening this issue first.

### Possible alternatives

Leave it as-is

### Demonstration(s) and additional context

Screenshots (you'll need to zoom in and look at the bottom part of each):
Current Editor:
![Regular Scratch Editor](https://user-images.githubusercontent.com/104146239/197355060-78c91e70-9d27-41c2-8c06-bd0cb1049e58.png)
My Current Version (for now):
![New Scratch Editor](https://user-images.githubusercontent.com/104146239/197363612-753aa3fc-1adf-481d-a05b-5d523d222acc.png)

**Comment by mxmou** [comment]
This is a very small visual change so I'm not sure if it would be a good addition to Scratch Addons.

**Comment by WorldLanguages** [comment]
This looks small to be added, but please add some red circles or something to the screenshot, so we know where to look.

**Comment by BroJac5246** [comment]
> This looks small to be added, but please add some red circles or something to the screenshot, so we know where to look.

I just updated the comment, the parts to the left and bottom of the red drawing are the parts that the addon would possibly affect.

**Comment by BroJac5246** [comment]
I don't think this makes sense or is worth it.
