### ISSUE TITLE
Footer can be behind the project when on project page

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#525]
**Describe the bug**
![image](https://user-images.githubusercontent.com/61319150/96374352-df2bdf80-1137-11eb-92ee-2f9df91994f3.png)
**To Reproduce**
1. Go to a project.
2. Scroll down a bit
3. Hover over the footer

**Expected behavior**
It works fine.

**Screenshots**

**Device (please complete the following information):**

**Additional context**

**Comment by WorldLanguages** [comment]
Looks like a `z-index` issue
