### ISSUE TITLE
Make dark mode... Darker?

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#526]
## Old version:
![image](https://user-images.githubusercontent.com/61319150/96374413-421d7680-1138-11eb-9a20-bf6fd8156a98.png)
## New version:
![Screenshot 2020-10-18 at 11 50 29 AM](https://user-images.githubusercontent.com/61319150/96374416-4f3a6580-1138-11eb-966c-425f6bf7fb7c.png)

**Comment by Explosion-Scratch** [comment]
The old version I like better. Also I don't really like the dividers between stuff.

**Comment by mxmou** [comment]
Both will be available soon.
