### ISSUE TITLE
hide-flyout: Opening dropdown in flyout hides flyout

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#5263]
### Description

The flyout will hide when opening a dropdown from a block in the flyout and hovering over that dropdown.
![image](https://user-images.githubusercontent.com/72760579/197643233-e78cc622-de84-4fcf-b4bb-cd9084e7f0ce.png)
![image](https://user-images.githubusercontent.com/72760579/197643255-f762b2aa-9ee7-4b48-b3fd-2f9ba51d5526.png)

### Steps to reproduce

1. Enable hide-flyout
2. Open dropdown of a block
3. Hover over that dropdown

### Environment

Browser: Chrome 106
Scratch Addons version: master
Operating system: Windows

**Comment by WorldLanguages** [comment]
Might not be a bug per-se, but we could think of potential solutions to this.

**Comment by CubesterYT** [comment]
I made a report about this in the SA Discord server a while ago, but it was forgotten, I had several videos showing the problem, not only with SA, but with TurboWarp. It was in the old bug reports channel, which is now gone.

**Comment by WorldLanguages** [comment]
+1 from feedback
