### ISSUE TITLE
Be more transparent about "no flash versionS detected"

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#5274]
See #1872. We automatically change the user agent when SA users post in the forums and click the globe icon. Scratch adds "no flash version detected" and we change it to "no flash versions detected".
Users might not expect this behavior, and it's not documented anywhere. We don't intentionally hide this behavior, but users might not realize the extra "s" when posting.
We could: (choose one)
1. Tell the user right in the forum post screen, after the globe icon is pressed (how would we explain it? will be confusing to some users)
2. Mention it somewhere in scratchaddons.com/docs, such as inside the extension privacy policy
3. Add a toggle for this somewhere in the settings page, and default it to enabled

**Comment by BroJac5246** [comment]
I think we should implement #4746, and the warning there could also include a note about "versions."

If we don't do that, though, then the extra "s" should definitely be documented. I didn't know about it, and a typical user almost certainly wouldn't.

**Comment by WorldLanguages** [comment]
> I think we should implement https://github.com/ScratchAddons/ScratchAddons/issues/4746, and the warning there could also include a note about "versions."

The warning there would only show before posting "scratch addons", so I don't think it would make sense.

**Comment by Samq64** [comment]
Why are we changing it all? Can't it just be removed?

**Comment by WorldLanguages** [comment]
> Why are we changing it all?

It's useful to [search for "versions detected" in the forums](https://ocular.jeffalo.net/search?q=%22no%20flash%20versions%20detected%22&sort=newest) and check if any bug reports there are caused by Scratch Addons.

**Comment by Hans5958** [comment]
Random idea on my mind for a while: Put this as a new addon that is untoggleable.

**Comment by WorldLanguages** [comment]
> Random idea on my mind for a while: Put this as a new addon that is untoggleable.

An alternative would be to include this inside "more settings"

**Comment by BroJac5246** [comment]
> > Random idea on my mind for a while: Put this as a new addon that is untoggleable.
> 
> An alternative would be to include this inside "more settings"

And it could be toggleable, we could just include a warning before it gets turned off about how this is useful to us.

**Comment by jeffalo** [comment]
Rather than trying to do it sneakily, why not include something like "Browser extensions enabled"?

**Comment by WorldLanguages** [comment]
@jeffalo That would be more transparent, but it could be considered to break the extension policy, even though "Scratch Addons" isn't mentioned explicitly.

**Comment by WorldLanguages** [comment]
Related: bug #6065
