### ISSUE TITLE
Footer partially shows on mystuff

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#528]
![image](https://user-images.githubusercontent.com/61319150/96374539-f5866b00-1138-11eb-9b8f-968b2e3f31ec.png)

**Comment by WorldLanguages** [comment]
@Explosion-Scratch What addon is causing this?

**Comment by WorldLanguages** [comment]
bruh what

**Comment by WorldLanguages** [comment]
closed the wrong issue lol

**Comment by Explosion-Scratch** [comment]
@WorldLanguages, I have no idea. I'll test it out later. Possibly Scratch
2.0 -> 3.0 but idk. I'll test tomorrow.

**Comment by lholliger** [comment]
infinite scroll with footer fixed enabled causes this most likely

**Comment by TheColaber** [comment]
This is not a bug in my experience. @Explosion-Scratch can you please see if this problem still happens for you?

**Comment by mxmou** [comment]
@TheColaber I think this is normal behavior caused by the infinite scrolling addon, not a bug, like lholliger said.

**Comment by TheColaber** [comment]
> @TheColaber I think this is normal behavior caused by the infinite scrolling addon, not a bug, like lholliger said.

Ah... I assumed he meant when he was completely scrolled down.

**Comment by RedGuy12** [comment]
Not a bug

**Comment by TheColaber** [comment]
not a bug 100%
> is normal behavior caused by the infinite scrolling addon, not a bug, like lholliger said.
