### ISSUE TITLE
ocular status can overflow and cover part of the post

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#5286]
### Description

Long words in ocular statuses in the forums don't wrap. If 2.0 → 3.0 is enabled, they can also cover parts of the posts. This was caused by #5089, which changed `addon.tab.displayNoneWhileDisabled(status)` to `addon.tab.displayNoneWhileDisabled(status, { display: "inline-block" })`.

### Steps to reproduce

Set a long status that doesn't contain spaces or punctuations and go to one of your recent posts. You can also use [this post](https://scratch.mit.edu/discuss/post/6682478/) for testing.

### Demonstration(s) and additional context

![Screenshot with 2.0 → 3.0](https://user-images.githubusercontent.com/51849865/198820016-8f84cd44-c862-4328-8ec6-209fb20113d0.png)
![Screenshot without 2.0 → 3.0](https://user-images.githubusercontent.com/51849865/198820054-18410628-b83a-4f90-8664-fb27856f6c98.png)

### Environment

Browser: Edge 106
Scratch Addons version: 1.29.0
Operating system: Windows

**Comment by Chiroyce1** [comment]
Cannot reproduce on Firefox 105, macOS 12
<img width="600" alt="image" src="https://user-images.githubusercontent.com/97374054/199505026-686309b9-2f5c-4ca8-8d42-bd8c0dc05b68.png">
