### ISSUE TITLE
Customizable Toolbar color and Scratch logo color and image

### ISSUE THREAD

**Issue by Unkrown6YT** [ScratchAddons/ScratchAddons#5287]
### Why this would be helpful/solve a problem

I decided to request 2 addons

### What this addon does

You can customize Toolbar colors

Scratch Logo and Color is customizable(not copy)

**Comment by mxmou** [comment]
> You can customize Toolbar colors

Which toolbar?

> Scratch Logo and Color is customizable(not copy)

#5100

**Comment by Unkrown6YT** [comment]
> > You can customize Toolbar colors
> 
> Which toolbar?
> 
> > Scratch Logo and Color is customizable(not copy)
> 
> That has been suggested before: #5100

For scratch projects

**Comment by Unkrown6YT** [comment]
> > > You can customize Toolbar colors
> > 
> > 
> > Which toolbar?
> > > Scratch Logo and Color is customizable(not copy)
> > 
> > 
> > That has been suggested before: #5100
> 
> For scratch projects toolbar

i mean scratch projects, etc. toolbars

**Comment by BroJac5246** [comment]
> > > > You can customize Toolbar colors
> > > 
> > > 
> > > Which toolbar?
> > > > Scratch Logo and Color is customizable(not copy)
> > > 
> > > 
> > > That has been suggested before: #5100
> > 
> > For scratch projects toolbar
> 
> i mean scratch projects, etc. toolbars

What do you mean by "toolbars"?

**Comment by Unkrown6YT** [comment]
> > > > > You can customize Toolbar colors
> > > > 
> > > > 
> > > > Which toolbar?
> > > > > Scratch Logo and Color is customizable(not copy)
> > > > 
> > > > 
> > > > That has been suggested before: #5100
> > > 
> > > 
> > > For scratch projects toolbar
> > 
> > 
> > i mean scratch projects, etc. toolbars
> 
> What do you mean by "toolbars"?

![Screenshot 2022-10-29 204459](https://user-images.githubusercontent.com/94491221/198847850-218ff800-d709-43c2-b616-fd21e548cd76.png)
Like this

**Comment by mxmou** [comment]
> ![Screenshot 2022-10-29 204459](https://user-images.githubusercontent.com/94491221/198847850-218ff800-d709-43c2-b616-fd21e548cd76.png)
> Like this

So you want to be able to change the background color of the controls bar?
