### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Unkrown6YT** [ScratchAddons/ScratchAddons#5288]
### Description

See Down below VVV

### Steps to reproduce

1. Recoloring Opacity Color, it turns into the 100% opacity
2. If changing opacity on selected colors, it turns colors into the black
3. The motion icon is not colored
![Screenshot 2022-10-29 180622](https://user-images.githubusercontent.com/94491221/198841646-ad09a104-f39a-4560-8694-900cdeeb9bb3.png)
4. A page slider is light while dark mode is enabled
5. Horizontal tabs on My Stuff enabled, but the line is default color while dark mode is enabled
![Screenshot 2022-10-29 181105](https://user-images.githubusercontent.com/94491221/198841786-1f35b57d-ace5-45ac-af96-6f4a429c47a5.png)

### Demonstration(s) and additional context

5 bugs

### Environment

Browser: Opera GX
Scratch Addons version: 1.29.0
Operating system: Windows 11

**Comment by mxmou** [comment]
Please create a separate issue for each bug and give it a descriptive title.

**Comment by Unkrown6YT** [comment]
> Please create a separate issue for each bug and give it a descriptive title.

How do i do that :(

**Comment by BroJac5246** [comment]
> > Please create a separate issue for each bug and give it a descriptive title.
> 
> How do i do that :(

Do what you did to make this issue, but make multiple: one for each bug you found, and include lots of details.

**Comment by CST1229** [comment]
> > > Please create a separate issue for each bug and give it a descriptive title.
> > 
> > 
> > How do i do that :(
> 
> Do what you did to make this issue, but make multiple: one for each bug you found, and include lots of details.

@Unkrown6YT
