### ISSUE TITLE
Nothing is displaying (happened x2)

### ISSUE THREAD

**Issue by Endermaster3690** [ScratchAddons/ScratchAddons#5289]
### Description

The fullscreen settings and the popup has barely any content.
My addons also all turn off it seems

### Steps to reproduce

1. Open popup and see like nothing
2. Click settings icon, see about nothing

### Demonstration(s) and additional context

Screenshot of the fullscreen settings with the popup open 
![Screenshot 2022-10-29 161852](https://user-images.githubusercontent.com/80355301/198852704-7776a088-b96f-4e03-b61e-8749479ab2eb.png)

### Environment

Browser: Chrome something i'll check in a minute
Scratch Addons version: 1.29 it happened when i updated
Operating system: windows 10, i think 64bit

**Comment by DNin01** [comment]
This is unmodified SA, right? Haven't touched the code in your installation?

**Comment by Endermaster3690** [comment]
> This is unmodified SA, right? Haven't touched the code in your installation?

i never touched it

**Comment by Samq64** [comment]
Can't repro on Firefox (updated yesterday) or Chromium (fresh install).

**Comment by DNin01** [comment]
> > This is unmodified SA, right? Haven't touched the code in your installation?
> 
> i never touched it

Good to know.

I'm not sure where the settings file is if SA isn't gonna let you export it, but if you can find it, you might be able to copy it, reinstall SA, and re-import it to get your addons back. Alternatively, you could just reinstall SA and set up your addons again, which might be a bit time-consuming if you didn't make settings file backups, but it's probably the fastest solution (if reinstalling will even restore SA, that is).

By the way, you can go to More Settings > Export Settings to back up your list of enabled addons and options to speed up recovery if this happens again.

Hopefully a reinstall will fix the issue. You can also try [downloading SA directly from GitHub](https://github.com/ScratchAddons/ScratchAddons#from-source) to test if a fresh installation works. It won't do anything to your current installation of SA, and if the direct download works, then SA will probably work again after a reinstall.

**Comment by Endermaster3690** [comment]
> > i never touched it
> 
> Good to know.
> 
> Hopefully a reinstall will fix the issue.

ok will do

>set up your addons again, which might be a bit time-consuming

ok sure

**Comment by mxmou** [comment]
Could be a crash in the background script.

**Comment by Endermaster3690** [comment]
Reinstalled, still doing this

**Comment by mxmou** [comment]
> Reinstalled, still doing this
> it still shows nothing

Can you try to check if there are any errors in the background page? Go to `chrome://extensions`, enable developer mode, click the `background/background.html` link under the Scratch Addons decription and select the Console tab. `ERR_FILE_NOT_FOUND` is normal, any other error is probably a bug.

**Comment by Endermaster3690** [comment]
>Can you try to check if there are any errors in the background page? Go to chrome://extensions, enable developer mode, click the background/background.html link under the Scratch Addons decription and select the Console tab. ERR_FILE_NOT_FOUND is normal, any other error is probably a bug.

this is what i saw

**Failed to load resource: net::ERR_FILE_NOT_FOUND** a billion times

**scratchAddons.localState.ready.manifests is now:  true** (local-state.js:40)

**background.html:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'addonSettings')
    at chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/background/get-addon-settings.js:39:64** (background.html:1)

**background.html:1 Unchecked runtime.lastError: IO error: .../LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)** (background.html:1)

**Comment by DNin01** [comment]
After the
```
background.html:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'addonSettings') at chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/background/get-addon-settings.js:39:64
```
error you got, instead I get
```
scratchAddons.globalState.addonSettings is now:  Object
scratchAddons.localState.addonsEnabled is now:  Object
scratchAddons.localState.ready.addonSettings is now:  true
Everything ready!
```

in the console on my working installation of SA 1.30.0-pre. So that's what is supposed to happen, but yours seems to have only gotten to the point of trying to load the settings file, which I'm guessing is in some sort of corrupted state. Considering that you reinstalled SA, it might have kept the settings file somewhere and only redownloaded SA's code, if the settings file is even the problem.

Only way around that that I can think of is to install SA [directly from GitHub](https://github.com/ScratchAddons/ScratchAddons#from-source) so it doesn't get stuck at the settings file (which will be separate on the direct download).

I'm hoping we can find a way to handle this error in the future to get your installation of SA back up and running again. I started a discussion here: #5291 in the hopes of starting work on this problem.

**Comment by Samq64** [comment]
Try typing `chrome.storage.sync.clear()` into the console, but make sure to backup your settings if they're still there.

**Comment by DNin01** [comment]
> Running `chrome.storage.sync.clear()` into the console should fix it, but you should probbably backup your settings first if they're still there. (Thanks WL for showing me that trick)

Could you maybe tell us also how to back up the settings, as well as how to open the console for Scratch Addons? Not sure if Endermaster3690 has worked with developer tools before.

**Comment by DNin01** [comment]
This is what GrahamSH-LLK said on my discussion:
> Background page crashing is probably fixable with a **browser restart**. I doubt anything actually corrupted. Looking at the error in #5289 it _looks_ like a **chromium bug** given the lock error.

**Comment by Samq64** [comment]
> Could you maybe tell us also what you do to back up the settings, as well as how to open the console for Scratch Addons so you can run the command?

Open the settings page and click more settings and then export settings and then on the same page press Ctrl+Shift+i and switch to the console tab if it isn't already.

**Comment by BroJac5246** [comment]
> Open the settings page and click more settings and then export settings.

Will that work with the settings page not loading?

**Comment by DNin01** [comment]
> Open the settings page and click more settings and then export settings.

I don't think that's possible this time. There's no More Settings button in sight.
![](https://user-images.githubusercontent.com/80355301/198852704-7776a088-b96f-4e03-b61e-8749479ab2eb.png)

**Comment by Endermaster3690** [comment]
> you should probbably backup your settings first if they're still there.

nO

> Only way around that that I can think of is to install SA [directly from GitHub](https://github.com/ScratchAddons/ScratchAddons#from-source) so it doesn't get stuck at the settings file

ok will do

**Comment by Endermaster3690** [comment]
i didn't reinstall through github and it fixed itself, all my addons are back
![Screenshot 2022-11-01 120719](https://user-images.githubusercontent.com/80355301/199293696-5d98b20f-4243-4729-be3c-60e13dbf6946.png)

**Comment by DNin01** [comment]
I have a feeling that might've been a browser issue, not a SA issue, like GrahamSH-LLK thought. Glad you have your addons back too!

SA could still do with indication of what the problem is and suggestions to solve it.

**Comment by WorldLanguages** [comment]
> SA could still do with indication of what the problem is and suggestions to solve it.

Is there an issue for this? I'm not sure if I got confused by thinking this single issue were actually 2 issues, or if it really exists

**Comment by DNin01** [comment]
> > SA could still do with indication of what the problem is and suggestions to solve it.
> 
> Is there an issue for this? I'm not sure if I got confused by thinking this single issue were actually 2 issues, or if it really exists

There's a discussion at #5291.

**Comment by WorldLanguages** [comment]
> There's a discussion at #5291.

Oh, that was it.

Could you make an issue, specifically about this:

> Allowing more control (like entering SA's options so you can export/import your settings) or at least let the user know what's going on if something fails to load.

1. We should tell the user that something has gone wrong (possibly a new page and redirect to it when needed)
2. Allow the user to export the settings from that page. The page should not be buggy, because then users can't export settings. It's better if we keep that page simple. We could also add a button that runs `chrome.storage.sync.clear()` and `chrome.storage.local.clear()`.

That page would also be useful for unsupported browsers. We could allows users to export their settings even if the browser is unsupported (as long as the browser isn't thaat old...)

**Comment by DNin01** [comment]
@WorldLanguages Done.

**Comment by Endermaster3690** [comment]
Oh god the issue is back, not sure if reopening is a good idea but i will do it anyway

**Comment by Endermaster3690** [comment]
needs info? ok here's a little

it looks the exact same as in the screenshot in the original post



background/background.html:
Error handling response: TypeError: Cannot read properties of undefined (reading 'addonSettings')
    at chrome-extension://fbeffbjdlemaoicjdapfpikkikjoneco/background/get-addon-settings.js:39:64
background.html:1 Unchecked runtime.lastError: IO error: .../LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)

### images

background/background.html
![Screenshot 2023-02-17 164143](https://user-images.githubusercontent.com/80355301/219811482-838dba9d-0708-4e2d-adc0-dd66b1ea850f.png)

**Comment by DNin01** [comment]
One of the first proposed solutions was to try restarting the browser. Try typing `chrome://restart` into the address bar and see if that solves the issue.
