### ISSUE TITLE
No dropdown arrow on the dropdown in mystuff + weird top border

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#529]
![image](https://user-images.githubusercontent.com/61319150/96374570-19e24780-1139-11eb-9882-1c7439ea41ae.png)
See the border at the top, also there is no arrow on the dropdown.

**Comment by mxmou** [comment]
Make sure any userstyles are disabled, I think that is the problem.

**Comment by mxmou** [comment]
Cannot reproduce anymore on the #699 branch.

**Comment by WorldLanguages** [comment]
Yeah, @mxmou that was a nice catch - someone has reported a similar issue a few weeks ago, and I bet this caused this.
