### ISSUE TITLE
`editor-theme3` doesn't change the colors of forum scratchblocks in post lists

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5290]
### Description

On forum post lists like https://scratch.mit.edu/discuss/search/?action=show_user&show_as=posts, the Customizable block colors addon won't change the color of blocks in listed posts.

### Steps to reproduce

1. Turn on `editor-theme3` and its option to change the color of blocks on the forums
2. Go to a post list like the one I mentioned above
3. Find a post with scratchblocks in it

### Demonstration(s) and additional context

Block colors are the defaults on the list of my posts, but they are recolored on an actual post.
![A comparison. Block colors are the defaults on the list of my posts, but they are recolored on an actual post.](https://user-images.githubusercontent.com/106490990/198852931-66b75a3a-618e-4ce0-a8a1-735c47acf7b6.png)

### Environment

Browser: Edge 106
Scratch Addons version: 1.29.0 (stable, unmodified)
Operating system: Windows 10

**Comment by mxmou** [comment]
The 3.0 scratchblocks addon has the same issue.
