### ISSUE TITLE
Changing hex color picker doesn't update the actual color

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#5296]
#4847 regression

> It´s very difficult, to get the main scratch color-picker to take the color from the hexcode of the scratch-addon-color-picker-extension.
> Enter does not seem to work well for that.

_Originally posted by @Drachenbauer in https://github.com/ScratchAddons/ScratchAddons/issues/311#issuecomment-1296238433_

**Comment by mxmou** [comment]
The following warning message is shown: `scratch-paint Invalid hex color code: rgb(77, 151, 255)`
If an object is selected, its color is updated correctly, but the color shown in the Scratch color picker isn't changed.

**Comment by WorldLanguages** [comment]
There's lots of bug reports on the Discord server about the hex color picker, I'm not sure if it's related to this issue:

> While pasting a hex color into the "Hex Address" section, it just does nothing. Help?

> When picking a color via hexcode with the Hexcode Picker addon, the color is displayed in the small window, but then cannot be set to the paint color at all, therefore making the hexcode addon useless.

> when i try to put in #292B2F or any other value it doesn't input
the fix is to make a shape and enter the hex code for the shapes color
and then use the bucket tool

> I've pressed enter but whatever it does it won't select my colour.

> When I put a color (writing it) it doesn't charge until I press enter, if I don't press it, It doesn't update until I click that selector again

**Comment by BroJac5246** [comment]
> There's lots of bug reports on the Discord server about the hex color picker, I'm not sure if it's related to this issue:
> 
> > While pasting a hex color into the "Hex Address" section, it just does nothing. Help?
> 
>[...]

I've been noticing that as well.

**Comment by WorldLanguages** [comment]
Anyone want to self-assign?

**Comment by WorldLanguages** [comment]
@CST1229 Are you aware of any reproduceable bugs mentioned above (in this issue) that weren't fixed by your PR? If so, we'll need to create issues for them.

**Comment by CST1229** [comment]
> Are you aware of any reproduceable bugs mentioned above (in this issue) that weren't fixed by your PR? If so, we'll need to create issues for them.

Clicking away from the input without pressing Enter updates the color of the input, but not the brush color (though I think this was always a thing and not a regression).

**Comment by WorldLanguages** [comment]
Moved that bug to #5296
