### ISSUE TITLE
Unreadable text in "report profile" modal

### ISSUE THREAD

**Issue by arch-herobrine** [ScratchAddons/ScratchAddons#5298]
### Description

![image](https://user-images.githubusercontent.com/112319383/198949281-9c9beed6-ac4b-406c-9ae4-68e9c5ded3a8.png)
The profile report screen goes blank when using dark mode.

### Steps to reproduce

using it
![image](https://user-images.githubusercontent.com/112319383/198949588-ad5c1602-962f-42b5-9e1c-42db92695156.png)

### Environment

Browser: google chrome
Scratch Addons version: 1.29.0
Operating system: Windows 10

**Comment by apple502j** [comment]
(This is Experimental Dark fyi)

**Comment by arch-herobrine** [comment]
![image](https://user-images.githubusercontent.com/112319383/199158735-541ed172-0907-4b4c-8646-9d9cf0089526.png)

**Comment by mxmou** [comment]
@arch-herobrine `color-scheme` is necessary to make scrollbars and form controls dark.
