### ISSUE TITLE
[Bug] Options page fails to load in firefox

### ISSUE THREAD

**Issue by tb148** [ScratchAddons/ScratchAddons#53]
**Describe the bug**

Firefox send this warning:

```
Reading manifest: Warning processing options_page: An unexpected property was found in the WebExtension manifest.
```

**To Reproduce**

Just load it in firefox.

**Expected behavior**

Make options page behave normally.

**Screenshots**

![图片](https://user-images.githubusercontent.com/28220642/89773949-7ae91000-db37-11ea-95e4-716abb553952.png)

**Device (please complete the following information):**

- OS: Win10
- Browser: firefox
- Version: none

**Additional context**

**Comment by BoomerScratch** [comment]
`options_page` only works on Chrome (not on Firefox).

**Comment by WorldLanguages** [comment]
Oh wow. That's bad. Let me look at WebExtension documentation on MDN.

**Comment by WorldLanguages** [comment]
Looks like `options_page` is deprecated. We need to use `options_ui`, example from MDN:
```json
"options_ui": {
  "page": "options/options.html"
}
```

**Comment by WorldLanguages** [comment]
I believe we might also need to set `open_in_tab` to `true`, since we have a dedicated full screen extension settings page.

**Comment by BoomerScratch** [comment]
Also, something off-topic: @tb148 became Scratch inaccessible for you? (LLK/scratch-www#4315)

**Comment by tb148** [comment]
> 
> 
> Also, something off-topic: @tb148 became Scratch inaccessible for you? ([LLK/scratch-www#4315](https://github.com/LLK/scratch-www/issues/4315))

Yes!

**Comment by BoomerScratch** [comment]
@tb148 Ouch! 🙁

**Comment by BoomerScratch** [comment]
@tb148 You can use a VPN but most VPN websites are blocked.
