### ISSUE TITLE
Merge the "Sprite Deletion Confirmation" addon into the general "Confirmations" addon

### ISSUE THREAD

**Issue by michaeIwave** [ScratchAddons/ScratchAddons#5301]
### Why this would be helpful/solve a problem

It would help me with my OCD because every other confirmation except sprite deletion has been merged into there.

### What this change does

This change would remove the "Sprite Deletion Confirmation" addon and add a new option in the "Confirmation" addon for sprite deletions.

### Possible alternatives

I dont think that there would be any other possible alternatives for this suggestion

### Demonstration(s) and additional context

![image](https://user-images.githubusercontent.com/105769130/199163433-3eec97a5-74c1-48dd-8181-2ded6a3a1660.png)

**Comment by apple502j** [comment]
I believe this is due to editor-website distinction, which does make sense for categorization reasons.

**Comment by Secret-chest** [comment]
> I believe this is due to editor-website distinction, which does make sense for categorization reasons.

Then rename this to "editor confirmations and make this a toggle in it.
