### ISSUE TITLE
Allow the opacity slider to be moved by clicking

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#5312]
### Why this would be helpful/solve a problem

The color, saturation and brightness sliders in Scratch's color picker can by moved by clicking a point on the slider:
![GIF showing clicks on the color slider](https://user-images.githubusercontent.com/51849865/199518725-74b123d5-11e7-43e9-8e9e-58e47a20c933.gif)

The opacity slider doesn't have this functionality, which makes it much harder to use.
![GIF showing clicks on the opacity slider](https://user-images.githubusercontent.com/51849865/199518871-c68b98a7-fe1e-4ff5-a1dc-e57f06d362ca.gif)

### What this change does

The same interaction should be possible with the opacity slider.

**Comment by WorldLanguages** [comment]
Good catch

**Comment by WorldLanguages** [comment]
From feedback: the slider can't be moved through a toushcreen

Possibly the same root cause as this?

**Comment by CST1229** [comment]
> From feedback: the slider can't be moved through a toushcreen
> 
> Possibly the same root cause as this?

Or maybe the opacity slider doesn't recognize touch* events.
