### ISSUE TITLE
Comment replies on deleted profiles cause messaging to fail

### ISSUE THREAD

**Issue by rgantzos** [ScratchAddons/ScratchAddons#5318]
### Description

If you open up the Scratch Messaging popup tab, it loads messages. As soon as it reaches each comment or reply, it fetches the comments from the page where the message is from. If the profile is banned, it returns a 403 error, as shown below:

<img width="637" alt="Screenshot 2022-11-03 at 5 56 42 PM" src="https://user-images.githubusercontent.com/86856959/199862459-984b81b3-1627-4beb-ac7f-0edadd0e7146.png">

The popup seems to be prepared for a 404, but not a 403 error (according to a background message I saw, and then found the source for [here](https://github.com/ScratchAddons/ScratchAddons/blob/master/popups/scratch-messaging/api.js#L164-L167).

After a 403 error is returned, the popup immediately fails and shows this:

<img src="https://user-images.githubusercontent.com/86856959/199862973-5f564d88-ef5f-4ed2-b94e-c01f4de07600.png" width="200">

The solution is to not only stop if there's a 404 error but also if there's a 403 error.

### Steps to reproduce

1. Comment on a profile and get replied to
2. Wait for it to get banned
3. Open the mmessages popup and wait for it to try loading comments from profile

### Environment

Browser: Chrome 106
Scratch Addons version: v1.29 (tested on multiple other beta versions though)
Operating system: MacOS

**Comment by WorldLanguages** [comment]
There are other scratch-messaging bugs more important than this and that affect more users, but we don't know the root cause for those

**Comment by rgantzos** [comment]
> There are other scratch-messaging bugs more important than this and that affect more users, but we don't know the root cause for those

I included a solution, and I can make a PR with a fix for it myself.

**Comment by DNin01** [comment]
> @rgantzos I think you misunderstood what I said.
> I'm just clarifying that this bug report isn't going to solve the many bug reports that say "it says I'm logged out but I'm logged in"!

Yeah, there might be other bugs that cause the same error. But feel free to make a PR, rgantzos. We’ll just still have other problems to fix.

**Comment by rgantzos** [comment]
> @rgantzos I think you misunderstood what I said.
> 
> I'm just clarifying that this bug report isn't going to solve the many bug reports that say "it says I'm logged out but I'm logged in"!

Yeah, but this will still fix one more bug.
