### ISSUE TITLE
clone counter

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#532]
**Describe the new addon**

it counts the amount of clones in a project

**Link to the new addon**

i'm working on it as we speak

**Comment by samuraininja360** [comment]
Nice what can I help to make a pull request

**Comment by JeffaloBob** [comment]
> Nice what can I help to make a pull request

i think its fine, i made my pr #533 but if you have any ideas for improvements let me know :)
