### ISSUE TITLE
`user-id`: Option to only show user IDs when hovering over username

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5329]
### Why this would be helpful/solve a problem

What if someone wants to have the option to quickly see anyone's user ID but doesn't want the `#12345678` thing to always appear next to every username on profile pages?

### What this change does

The addon would have a new option to show user IDs only when hovering over the username on a profile page. We could call it "only show when hovering over username".

### Possible alternatives

We could also use a tooltip or put it in a less distracting place.

**Comment by WorldLanguages** [comment]
We could do this, but it would be problematic if another addon wanted to show something different when usernames in profile pages are hovered.
Also, the current way makes it easy to copy the ID.

**Comment by penguinmoose** [comment]
> We could do this, but it would be problematic if another addon wanted to show something different when usernames in profile pages are hovered. Also, the current way makes it easy to copy the ID.

That's true. Maybe there could be a tooltip instead that only disappears when the user's cursor is far has been away from it for a few seconds? Although I guess other addons might want to show a tooltip too, but we should worry about that later.
