### ISSUE TITLE
Make "Better forum post editor buttons" Addon Also Affect "Forums image uploader" Addon

### ISSUE THREAD

**Issue by BroJac5246** [ScratchAddons/ScratchAddons#5337]
### Why this would be helpful/solve a problem

The `Better forum post editor buttons` addon turns all of the buttons in the forums post editor's toolbar black and makes them look consistent. However, this does not apply to the button added by the `Forums image uploader` addon, which remains colorful. This looks strange and defies the point of `Better forum post editor buttons`.

### What this change does

The `Better forum post editor buttons` will also affect the button added by `Forums image uploader`.

It's interesting to note that `More forum toolbar buttons` _is_ compatible with `Better forum post editor buttons`. I don't know why, but that's worth noting.

### Possible alternatives

We could also change the icon that `Forums image uploader` uses to one that naturally fits in with those that `Better forum post editor buttons` uses.

### Demonstration(s) and additional context

**Note: In all screenshots, I have `More forum toolbar buttons` enabled as well.**

Normal icons (neither addon being used):
![Screenshot 2022-11-08 12 08 07](https://user-images.githubusercontent.com/104146239/200630055-b36e775b-2513-4caa-b281-1a0a4c8d997e.png)

Just `Better forum post editor buttons` being used:
![Screenshot 2022-11-08 12 03 21](https://user-images.githubusercontent.com/104146239/200629021-cd86173b-8fd9-45aa-8d6f-2567393d927d.png)

Just `Forums image uploader` being used:
![Screenshot 2022-11-08 12 05 45](https://user-images.githubusercontent.com/104146239/200629509-a4d4579d-ac42-453c-ab64-8c6f0a3c9699.png)

Both addons being used:
![Screenshot 2022-11-08 12 06 31](https://user-images.githubusercontent.com/104146239/200629669-6dfae2d8-0e15-4d6f-ab15-8554f4d7fd97.png)
Notice how the icon from `Forums image uploader` stands out.

**Comment by mxmou** [comment]
It does have an icon but #4814 broke it.

**Comment by BroJac5246** [comment]
> It does have an icon but #4814 broke it.

Is there currently a plan to fix that?
