### ISSUE TITLE
Better Look

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#534]
**New Look for Scratch Addons**

I hope I can make an HTML and CSS folder to update the Scratch Addons popup window. It looks a bit old and maybe needs a bit of a modern touch. I can design the tabs and the popup so it looks more pleasing while you guys work on the back-end stuff. Some of the icons look redundant as well and I think we can make them look more like scratch. I will work on it soon and make  a pull request! Thanks!

**Comment by samuraininja360** [comment]
It is mainly the lists of notifications and the color scheme but other than that it is looking good

**Comment by WorldLanguages** [comment]
Keep in mind v1.2 is planned to have a new modern look as well. Download the master branch from this repo to see how it looks like

**Comment by samuraininja360** [comment]
Um I still think we can improve on it though because there are some errors with the "gecko" {"id": "something"} part and it is actually less readable than the original one. I like the tabs but I have a better Idea for the icons and hrefs I know I am just a beginner at developing extensions but after all I am only developing the front end popup html.

**Comment by samuraininja360** [comment]
I actually have to say the font and the popup looks much neater but I will try to make more icons and better visibility I think this is very good

**Comment by mxmou** [comment]
> there are some errors with the "gecko" {"id": "something"} part

That's a part of the extension manifest that's required by Firefox, but Chrome doesn't like it.
