### ISSUE TITLE
Mute certain types of messages

### ISSUE THREAD

**Issue by Coolguy236gg** [ScratchAddons/ScratchAddons#5340]
### Why this would be helpful/solve a problem

So I have joined some groups, and many projects get added in them daily. So whenever I enter scratch, I see that there is a new message and I get excited (hoping to see someone liking or hearting my project) only to see that **It was just another studio activity message**. It's really annoying as well, this is why I would like muting certain types of messages in scratch.

**Here, take a look at this mess**
![image](https://user-images.githubusercontent.com/109452958/201138218-a81aadb6-e140-46e4-9aba-c095194d15f6.png)
As you can see in the image, I get a lot of these messages and I don't want to unfollow the group, but still mute these.( so that I can check by directly going in the studio).
This is all I have to say about how it _could_ help.

The scratch message filter absolutely useless for me and I would like this mute filter to be added soon.
Thank you to all of the scratch addons dev(s) for making this amazing addon.

### What this addon does

This addon adds a button that we can click on and select a type of message we want to mute. With it of course will be an option to disable the mute. It is kind of a small addon so there is not much to say. 

### Possible alternatives

I can't really think of any alternatives to be honest.

### Demonstration(s) and additional context

I'm not really a developer or anything so I can't make any preview builds for you guys. I only know how to code in scratch, not stuff like java or anything. I will try to make it into a scratch project, (if I did I will put the link as a reply to this.).
Hoping that this addon will be added!

A random dude from the internet,
Coolguy236

**Comment by BroJac5246** [comment]
> Impossible

Couldn't we just have a blocklist, and SA will remove those notifications from the messages page, so that, while they still exist, they won't be displayed?

Other addons would respect this, and we would have a working system.

Alternatively, we could have a feature to collapse notifications from a certain source into a single dropdown, similar to what phones do. This would make implementation a lot easier.

**Comment by CST1229** [comment]
> Couldn't we just have a blocklist, and SA will remove those notifications from the messages page, so that, while they still exist, they won't be displayed?

That already exists (message filters addon).

**Comment by RedGuy12** [comment]
This suggestion is about certain types.


________________________________

**Comment by Coolguy236gg** [comment]
sorry guys, but I'm not that much of a technical person. Can't help here...
