### ISSUE TITLE
Add text translations for icons which are embedded in blocks

### ISSUE THREAD

**Issue by Tacodiva** [ScratchAddons/ScratchAddons#5342]
In SA right now there are two addons which need to convert blocks into text; dev tools for the middle click menu and the debugger for the thread window. Some blocks, however use icons in their text, namely the `when [green flag] clicked` and `turn [anti/clockwise] () degrees` blocks. Right now both of the addons handle these icons poorly, with the debugger awkwardly treating the icons as inputs and devtools keeping the word 'flag' untranslated or completely omitting the direction indicator for the turn blocks.

_Devtools leaving 'flag' untranslated_
![image](https://user-images.githubusercontent.com/27910867/201265321-80ef54ae-d216-4886-a81c-ce21b04cc09a.png)
_Devtools omitting the clockwise or anticlockwise icons, meaning the two blocks are indistinguishable_
![image](https://user-images.githubusercontent.com/27910867/201265845-21200213-d50d-4904-a630-a8df33a2eb2e.png)
_The debugger omitting the flag and doing weird things to the direction arrow_
![image](https://user-images.githubusercontent.com/27910867/201265703-ce17cff6-ce78-47dc-ae75-ae7b6ef45076.png)

**SA should have translations for these icons that addons can insert in their place when a text representation of blocks is needed.**

I'm not sure where these translations should go, given they need to be used in multiple addons.

**Comment by mxmou** [comment]
Alternatively, debugger could show the actual icons. That wouldn't work in devtools because the labels it uses need to be searchable.

**Comment by Tacodude7729** [comment]
> Alternatively, debugger could show the actual icons. That wouldn't work in devtools because the labels it uses need to be searchable.

I figure if we're gonna have the translations anyways it'd be much easier to just use them in the debugger too

**Comment by RedGuy12** [comment]
Translations used by multiple addons can go in addons-l10n/en/_general.json iirc.

**Comment by penguinmoose** [comment]
> Alternatively, debugger could show the actual icons. That wouldn't work in devtools because the labels it uses need to be searchable.

In devtools, it could actually have descriptions of the icon (translated, of course). For example, it could replace the clockwise icon with the text "clockwise".
