### ISSUE TITLE
Debugger blocks untranslated in threads tab

### ISSUE THREAD

**Issue by Tacodude7729** [ScratchAddons/ScratchAddons#5343]
When viewing scratch add-ons blocks in the debugger threads tab their text appears untranslated, despite being translated in the workspace view.

![image](https://user-images.githubusercontent.com/27910867/201267737-353cb907-757a-489e-8c4d-fa16ba0899b6.png)

**Comment by RedGuy12** [comment]
Translations used by multiple addons can go in addons-l10n/en/_general.json iirc.
