### ISSUE TITLE
`dark-www` unintentionally(?) changes the colors of Gamepad settings menu buttons

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5347]
### Description

When the Website dark mode and customizable colors is enabled, some button backgrounds in the Gamepad support addon's settings popup will match Page background.

**Expected behavior**: The background of the gamepad settings popup is white, so either everything else in the popup (e.g. the background and text) should be adjusted too or the buttons should be white instead of black to make the text easier to read.

**Actual behavior**: The background colors of drop-down menus, some buttons, and a checkbox are set to the Page background color set in the `dark-www` addon, but the text on them do not change, resulting in hard-to-read text.

### Steps to reproduce

1. Enable both `dark-www` and `gamepad`
2. Connect a controller and open the gamepad settings menu.

### Demonstration(s) and additional context

![Gamepad settings popup with dark gray buttons with very slightly lighter text](https://user-images.githubusercontent.com/106490990/201498857-84f39d3f-5a29-4a6f-93f8-504ee81cc52b.png)
This problem does not occur in full screen mode, and I also couldn't replicate the issue in the editor with `editor-dark-mode` enabled.

### Environment

Browser: Edge 107
Scratch Addons version: 1.29.0 stable
Operating system: Windows 10
I had other addons enabled but disabling `dark-www` still solved the problem.

**Comment by Samq64** [comment]
Fixed by #7546
