### ISSUE TITLE
Pin forum posts

### ISSUE THREAD

**Issue by fractioneater** [ScratchAddons/ScratchAddons#5353]
### Why this would be helpful/solve a problem

In the forums, sometimes I am trying to find a topic that I decided to check back on later, and if I don't remember the name of it or haven't posted anything on it, it's really hard to find.

### What this addon does

This addon would add an option to "pin" forum posts, which is like creating your own personal sticky, and they would show up at the top of the discussion home page. There would also be an option in the addon to automatically pin topics you're following, to make them easily accessible.

### Possible alternatives

It would also work to use browser bookmarks to keep forum topics organized, but that's not as simple as just pressing a button.

### Demonstration(s) and additional context

![forum topic with pin button](https://user-images.githubusercontent.com/98233032/202789369-5ba11667-1e72-4962-b6c7-50ba08a1f6b8.png)
Note the pin button to the right of the title ↑

**Comment by BroJac5246** [comment]
I sort of feel like that's a use for the follow topic button, but this could still be quite useful.

**Comment by fractioneater** [comment]
> I sort of feel like that's a use for the follow topic button, but this could still be quite useful.

I think the 'follow topic' button was intended to update people when there's action on a topic, because it doesn't help you find them again at all. The only thing it does is show new replies on the messages page.

**Comment by DNin01** [comment]
I feel like it might be better to have a page dedicated to pinned issues.

Also, there is a page for topics you're following:
Show your topics/[posts](https://scratch.mit.edu/discuss/search/?action=show_user&show_as=posts) → [Show your subscribed topics](https://scratch.mit.edu/discuss/search/?action=show_subscriptions)

I like the idea, though.

**Comment by BroJac5246** [comment]
> > I sort of feel like that's a use for the follow topic button, but this could still be quite useful.
> 
> I think the 'follow topic' button was intended to update people when there's action on a topic, because it doesn't help you find them again at all. The only thing it does is show new replies on the messages page.

It is, but sometimes that's what I do if I want to save a topic 😅

**Comment by RedGuy12** [comment]
> It would also work to use browser bookmarks to keep forum topics organized, but that's not as simple as just pressing a button.

Browser bookmarks are a button.
Plus, we'd have to save this in localStorage which we don't like to use unless we have to
Rejected

**Comment by WorldLanguages** [comment]
I agree on this being rejected.
Scratch does offer a way to see followed posts. In the other hand, browsers offer bookmarks, and even reading list nowadays.
