### ISSUE TITLE
Pause button doesn't work properly when clicked too fast

### ISSUE THREAD

**Issue by EightSidedBrick** [ScratchAddons/ScratchAddons#5361]
### Description

If I click the pause button the project using "Pause button by Jeffalo, GarboMuffin" at a rate below 50 milliseconds (about 20 clicks per second, I tested using an autoclicker) an uneven amount of times, then the project itself pauses, but sound keeps playing.
Also, if I'm using "play sound [] until done" block or any block that doesn't continue the script until the sound is finished and I get this glitch, the block is still running (still highlighted with "Running block border") and if it's the last block in a script, the script doesn't stop running too.

### Steps to reproduce

1. Download an autoclicker (I got one from opautoclicker.com)
2. Set click frequency to below 50.
3. Use the autoclicker on the pause button (added with "Pause button" addon) 

### Demonstration(s) and additional context

This probably doesn't create any problems for anyone, but it's still not working properly.

### Environment

Browser: Google Chrome 107.0.5304.107 (Official Build) (64-bit)
Scratch Addons version: 1.29.0
Operating system: Windows 10 Version 22H2

**Comment by BroJac5246** [comment]
I doubt that this affects anyone, but interesting catch.

**Comment by WorldLanguages** [comment]
We could fix this "bug" by having a cooldown, to avoid the pause button from being clicked more than once every, let's say, 200ms.

**Comment by BroJac5246** [comment]
This hasn't been fixed yet, so it needs to stay open.
