### ISSUE TITLE
"HD import" button not visible, behind stage (caused by hide-flyout)

### ISSUE THREAD

**Issue by tonyzhigit** [ScratchAddons/ScratchAddons#5367]
### Description

![image](https://user-images.githubusercontent.com/100283902/203292303-83b554d8-9256-41e2-bc97-2c6954566ca8.png)
I can't click the HD upload button because it was blocked by the stage.

### Steps to reproduce

1. Hover the _add sprite_ button.

### Environment

Browser: `109.0.5414.10 dev` x64 architecture
Scratch Addons version: 1.29.0
Operating system: Windows 11 21H2

**Comment by mxmou** [comment]
This only happens if `hide-flyout` is enabled.

**Comment by fractioneater** [comment]
How did you even get the new sprite button so close to the stage? I tried ctrl + plus, but it still never came close.

**Comment by DNin01** [comment]
Related to #5185

**Comment by tonyzhigit** [comment]
Solved.

**Comment by CST1229** [comment]
I don't think this should be closed because the bug isn't fixed yet.
