### ISSUE TITLE
An option (default?) to make blocks added by Scratch Addons auto-translate to the Scratch language, if possible

### ISSUE THREAD

**Issue by penguinmoose** [ScratchAddons/ScratchAddons#5373]
### Why this would be helpful/solve a problem

When the Scratch language is set to something other than English, blocks added by Scratch Addons are still in English.

### What this change does

This change would add an option (probably located in the Scratch Addons settings) to make the language of Scratch Addons blocks always the Scratch language, if possible.

### Possible alternatives

- This option could be enabled by default
- This option could be located elsewhere
- There can be no option to turn this off - this will simply be implemented

### Demonstration(s) and additional context

Keep in mind that my system language is set to English, but the Scratch language is set to Chinese. That is because I speak and read English (Chinese is just an example).
<img width="500" alt="The block pallete: the debugger section, 'lists', and 'search' are not translated." title="The block pallete: the debugger section, 'lists', and 'search' are not translated." src="https://user-images.githubusercontent.com/67451414/204109531-033735fe-5d7e-4183-9bc4-2af59c93a058.png">

**Comment by Samq64** [comment]
It looks like those strings are translated but only follow the browser's language, not Scratch's. I'm not sure if that's the case with all Scratch Addons strings though.

**Comment by CST1229** [comment]
[This is already a thing](https://github.com/ScratchAddons/ScratchAddons/blob/5b2f27e0bb8318657ea383f5d98f0bb75f13a244/addons-l10n/en/debugger.json#L18-L20), just that the strings for that language haven't been translated yet.

**Comment by WorldLanguages** [comment]
> make the language of Scratch Addons blocks always the Scratch language, if possible.

This has always been the case.

Could you confirm whether this is a bug, or if those strings haven't been translated yet?
Could you tell us what specific language you use on Scratch?

**Comment by GarboMuffin** [comment]
Scratch Addons does not have a Chinese translation

**Comment by WorldLanguages** [comment]
> Scratch Addons does not have a Chinese translation

Hmm, `/addons-10ln/zh-tw` does exist

**Comment by GarboMuffin** [comment]
zh-tw does but zh-cn does not

**Comment by Samq64** [comment]
I tried setting the Scratch Language to French and it wasn't translated, but if I set the browser language to French, it was.

**Comment by BroJac5246** [comment]
> I tried setting the Scratch Language to French and addons weren't translated, but if I set the browser language to French, they were.

I independently noticed that today as well, I set my TurboWarp Desktop language to French (lol) and found it strange that the debugger blocks weren't being translated.

**Comment by penguinmoose** [comment]
> > make the language of Scratch Addons blocks always the Scratch language, if possible.
> 
> This has always been the case.
> 
> Could you confirm whether this is a bug, or if those strings haven't been translated yet? Could you tell us what specific language you use on Scratch?

To clarify, I noticed this while messing around with the Scratch language. I can try changing the Scratch language to different ones if you want. (I speak and read English)

Also, this "problem" occurs with the other Chinese and Japanese too.

**Comment by penguinmoose** [comment]
> [This is already a thing](https://github.com/ScratchAddons/ScratchAddons/blob/5b2f27e0bb8318657ea383f5d98f0bb75f13a244/addons-l10n/en/debugger.json#L18-L20), just that the strings for that language haven't been translated yet (or the translations just aren't applied for some reason).

If the strings are not translated yet, it wouldn't take too long to translate them - it's less than 10 words.

**Comment by BroJac5246** [comment]
> > > make the language of Scratch Addons blocks always the Scratch language, if possible.
> > 
> > This has always been the case.
> > 
> > Could you confirm whether this is a bug, or if those strings haven't been translated yet? Could you tell us what specific language you use on Scratch?
> 
> **I use English.** To clarify, I noticed this while messing around with the Scratch language. I can try changing the Scratch language to different ones if you want. (I speak and read English)
> 
> Also, this "problem" occurs with the other Chinese and Japanese too.

Same, I'm learning French, so I changed the language to see how much I understood and could figure out. That's when I noticed that the debugger blocks weren't being translated.

**Comment by WorldLanguages** [comment]
> I tried setting the Scratch Language to French and addons weren't translated, but if I set the browser language to French, they were.

@Samq64 Do you have any additional information?

Try reloading the page twice after changing the language of the Scratch website/editor.

**Comment by Samq64** [comment]
> > I tried setting the Scratch Language to French and addons weren't translated, but if I set the browser language to French, they were.
> 
> @Samq64 Do you have any additional information?
> 
> Try reloading the page twice after changing the language of the Scratch website/editor.

I can't repro anymore. Addons are translated after reloading the page as expected except for the debugger category label in French but in other languages it is.
