### ISSUE TITLE
curator-link is broken when not signed in

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#5374]
### Description

Curator link doesn't do anything when signed out.

### Steps to reproduce

1. Enable `curator-link`
2. Go to https://scratch.mit.edu

### Environment

Browser: Firefox 107
Scratch Addons version: 1.29.0
Operating system: Ubuntu

**Comment by fractioneater** [comment]
It works fine for me, with "style as normal text" on or off. Does it just not count as a link for you?

**Comment by Samq64** [comment]
No, I'm sure it does absolutely nothing on the 1.29.0 stable and the console says it's running.

**Comment by Samq64** [comment]
I'll work on it later.

**Comment by BroJac5246** [comment]
It's working for me on v1.29.0 stable; Chrome 108 Beta.

**Comment by Samq64** [comment]
Yeah, it works on Chroimum for me too. This is Firefox-specific.

**Comment by mxmou** [comment]
This happens on both browser when signed out. #4828 changed a CSS selector from `.inner:last-of-type h4` to `.inner.mod-splash:nth-child(2) h4`. If the user isn't signed in, `.inner.mod-splash:nth-child(2)` doesn't match anything because there is a banner above the rows.

**Comment by Samq64** [comment]
What's the easiest way to fix this while not breaking dynamic enable/disable?

**Comment by mxmou** [comment]
> What's the easiest way to fix this while not breaking dynamic enable/disable?

I think the selector could be changed to `.inner.mod-splash + .inner.mod-splash h4`.
