### ISSUE TITLE
"HD Upload" button not visiable on "add backdrop" dropdown

### ISSUE THREAD

**Issue by tonyzhigit** [ScratchAddons/ScratchAddons#5382]
### Description

I enabled the "HD Upload" addon, but it doesn't show on the  "add backdrop" dropdown.
It shows up in the painting area though.<br> ![image](https://user-images.githubusercontent.com/100283902/204408123-3e75e2a4-cb09-4eb4-8a4c-20fe5e77d87b.png)
**Edit**: The "painting area" means this: <br> ![image](https://user-images.githubusercontent.com/100283902/204435124-98658955-bc4e-4f69-95f0-30cff804aba6.png)

### Steps to reproduce

1. Create a project.
2. Hover the add backdrop button. Sees the dropdown.

### Demonstration(s) and additional context

![image](https://user-images.githubusercontent.com/100283902/204408144-ce3dd686-2240-4a6a-bb69-ea0425a4c2ed.png)

### Environment

Browser: 109.0.5414.10 _dev arm64_
Scratch Addons version: 1.29.0
Operating system: Windows 11 _21H2 x64_

**Comment by penguinmoose** [comment]
Can reproduce on Google Chrome Version 107.0.5304.87 (Official Build) (arm64) on MacBook Pro M1 Pro, SA v1.29.0

This looks like the button was simply not added.

**Comment by BroJac5246** [comment]
> Can reproduce on Google Chrome Version 107.0.5304.87 (Official Build) (arm64) on MacBook Pro M1 Pro, SA v1.29.0
> 
> This looks like the button was simply not added. The addon description says that it adds the button on the upload costume dropdown, but does not mention the upload _backdrop_ dropdown.

Hmm... does anyone know if there's a reason for that (it seems a little too obvious to forget), or was it somehow overlooked?

**Comment by tonyzhigit** [comment]
> This looks like the button was simply not added. 

But it was added to the backdrop paint area as I mentioned before:

> It shows up in the painting area though.
> ![image](https://user-images.githubusercontent.com/100283902/204408123-3e75e2a4-cb09-4eb4-8a4c-20fe5e77d87b.png)

**Comment by tonyzhigit** [comment]
Closed. Duplicate of #3847.

**Comment by GarboMuffin** [comment]
This is not a duplicate. The addon currently makes no attempt to add itself to the add backdrop menu. #3847 is unrelated.

**Comment by tonyzhigit** [comment]
It is still not working. Will it be fixed by the next version?

**Comment by CST1229** [comment]
> It is still not working. Will it be fixed by the next version?

Yes. (A pull request being merged or an issue being closed does not mean the issue has been fixed in the current version, it means it will be fixed in the next version)
