### ISSUE TITLE
editor-dark-mode: add toggle to disable dark costume editor (paper.js)

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#5387]
### Why this would be helpful/solve a problem

I've read in some places (forgot exactly where) that some artists prefer the white background, and have disabled editor dark mode as a whole because of that.

### What this change does

Add a setting, which would be enabled by default, that would let users disable this behavior.

**Comment by WorldLanguages** [comment]
My bad - the setting already exists. And the setting name is pretty understandable.
I assume the person that sent this wasn't aware. By now, I forgot where and who said this, so I can't do much.

**Comment by Samq64** [comment]
I was just about to comment that.
