### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#539]
I need questions for https://scratchaddons.com/faq. Drop what questions do you think it will be asked frequently below.

**Comment by YOYITsM3M8** [comment]
Does this take my password?

**Comment by j5155** [comment]
What do all the addons do?
What should I do if I find a problem?
Can I tell people on Scratch about this?
Are there any consequences for enabling everything?

**Comment by WorldLanguages** [comment]
Performance warnings probably deserve a FAQ

**Comment by GrahamSH-LLK** [comment]
This should probably be a discussion.

**Comment by YOYITsM3M8** [comment]
Yeah probably

**Comment by Hans5958** [comment]
I was going to close this when I release the first public version of FAQ, and then I will make another discussion post. But, you can make this to be a discussion if you want.
