### ISSUE TITLE
Variable Sliders Discolor

### ISSUE THREAD

**Issue by CubesterYT** [ScratchAddons/ScratchAddons#5393]
### Description

I'm not sure for how long this bug has existed for, but I discovered it today. I've even done some testing to see where the problem originated from, and I've found it.
So if you have Website dark theme on, with the normal dark-www preset, if you go to a project with variable sliders, you'll see the sliders discolored, gettting affected by the Website Dark Theme addon. This problem does not occur in dark theme editor.

(Dark Mode) Website View of a Project with Sliders:
![image](https://user-images.githubusercontent.com/78769806/205404857-23181d05-e992-4a52-ab74-ec1f53a61536.png)

(Dark Mode) Editor View of the Same Project:
![image](https://user-images.githubusercontent.com/78769806/205404875-02471a31-bfc6-46b8-86c1-6f4da2767e68.png)

### Steps to reproduce

1. Enable Website Dark Mode, with the normal dark-www preset.
2. Either go to a project with Variable Sliders, or create your own.
3. Play the project from the normal site, not the editor

### Demonstration(s) and additional context

I found out this bug when viewing the current front page project. Which was this:
https://scratch.mit.edu/projects/743656794/

### Environment

Browser: Chrome 108.0.5359.72 | 108.0.5359.95
Scratch Addons version: 1.29.0
Operating system: Windows 10

**Comment by CubesterYT** [comment]
Chrome 108.0.5359.95 now because my browser just updated.

**Comment by DNin01** [comment]
It seems to become light blue after Page background goes below a certain brightness, so the slider is basically adapting to the background color (but that's not what we want).
