### ISSUE TITLE
Scratch 2.0 → 3.0 bugs

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#540]
![image](https://user-images.githubusercontent.com/17484114/96474587-5a10fb00-1209-11eb-8d40-1e5fe8f760e5.png)
only happens when you read a message and then reply to it

![image](https://user-images.githubusercontent.com/17484114/96474650-68f7ad80-1209-11eb-944d-529648e40dcf.png)

![image](https://user-images.githubusercontent.com/17484114/96474694-73b24280-1209-11eb-9048-142986ece76d.png)
may need more padding on the text?

![image](https://user-images.githubusercontent.com/17484114/96474837-9ba1a600-1209-11eb-8c7b-4bb33a7493f2.png)
not locked to the footer

- usernames should be blue in profile/studio comments

**Comment by WorldLanguages** [comment]
![image](https://user-images.githubusercontent.com/17484114/96475322-431ed880-120a-11eb-83db-d92533fa8096.png)
blue background should likely cover until the footer

**Comment by WorldLanguages** [comment]
Tagging @mxmou 
These are all not really important (except the account settings one i guess)

**Comment by YOYITsM3M8** [comment]
What is wrong with the 1st one?

**Comment by WorldLanguages** [comment]
The overlap
![image](https://user-images.githubusercontent.com/17484114/96475936-fd164480-120a-11eb-861a-ac6c1b97182d.png)

**Comment by YOYITsM3M8** [comment]
Ahhh.

**Comment by YOYITsM3M8** [comment]
Also, since when does Kaj only have 1 follower

**Comment by WorldLanguages** [comment]
Note: the account settings issue fixed itself for this user (and I've never experienced it)

**Comment by JeffaloBob** [comment]
> Also, since when does Kaj only have 1 follower

he's only following 1 guy

**Comment by YOYITsM3M8** [comment]
I’m dumb

**Comment by mxmou** [comment]
> ![image](https://user-images.githubusercontent.com/17484114/96474587-5a10fb00-1209-11eb-8d40-1e5fe8f760e5.png)
> only happens when you read a message and then reply to it

That could be fixed by increasing the spacing (which I don't want to) or removing highlight from replies if the parent comment is also highlighted (which I don't think is a good idea).

> ![image](https://user-images.githubusercontent.com/17484114/96474650-68f7ad80-1209-11eb-944d-529648e40dcf.png)

I'm not sure what could cause that.

> ![image](https://user-images.githubusercontent.com/17484114/96474694-73b24280-1209-11eb-9048-142986ece76d.png)
> may need more padding on the text?

I think it looks good enough.

> ![image](https://user-images.githubusercontent.com/17484114/96474837-9ba1a600-1209-11eb-8c7b-4bb33a7493f2.png)
> not locked to the footer

Not sure if that's worth fixing.

> * usernames should be blue in profile/studio comments

Thanks for noticing that, apparently @BoomerScratch did not change them when implementing 3.0-style comments 😄

**Comment by mxmou** [comment]
> ![image](https://user-images.githubusercontent.com/17484114/96475322-431ed880-120a-11eb-83db-d92533fa8096.png)
> blue background should likely cover until the footer

The blue background shouldn't be there. `profile.css` is incorrectly set to match `https://scratch.mit.edu/users/*` instead of `https://scratch.mit.edu/users/*/`.

**Comment by WorldLanguages** [comment]
Okay @mxmou I'll assume you'll send the PRs for the fixes you mention. If not please tell me and I'll do it.

> I'm not sure what could cause that.

It appears to be a bug somewhere within Scratch Addons, not your addon. Don't worry about it
