### ISSUE TITLE
add support for other websites that have "patched" scratch versions

### ISSUE THREAD

**Issue by adrian1-byte** [ScratchAddons/ScratchAddons#5401]
### Why this would be helpful/solve a problem

i think the scratch addons are already working partly on turbowarp, but i would love support for every site that has scratch 3.0 in it, so like it recognizes that there is the scratch editor open and then does the addon stuff.
btw the site i want to have the addons work is https://scratch.machinelearningforkids.co.uk

### What this change does

just applying addons on every website with the scratch 3.0 editor

### Possible alternatives

NO ALTERNATIVES

**Comment by mxmou** [comment]
Related: #1584

**Comment by WorldLanguages** [comment]
Also related to #5281
