### ISSUE TITLE
Search for comments on projects

### ISSUE THREAD

**Issue by iancode12** [ScratchAddons/ScratchAddons#5402]
### Why this would be helpful/solve a problem

like for example if someone wanted something i could search for that comment and do it. i think it would be great addon.

### What this addon does

the addon could add a button to the project page and there would be a search box to type it in and if there were any comments related to that on your project it would show up.

**Comment by penguinmoose** [comment]
Of course, an alternative would be to use the browser search tool. To clarify, this tool searches for comments that contain a string that you search for, right?

It would also be nice to be able to have some more advanced searches, like Ocular. For example,`&username="ScratchCat"` might search for comments by ScratchCat. Support for regular expression would also be nice. The searchbar would probably appear in other comment areas, like studios and profiles.

But will this search within _all_ comments on that project, or just the loaded ones? If it has to search on all comments, that would mean many API calls on projects with many comments.

**Comment by BroJac5246** [comment]
> But will this search within _all_ comments on that project, or just the loaded ones? If it has to search on all comments, that would mean many API calls on projects with many comments.

All comments, otherwise what's the point?

**Comment by WorldLanguages** [comment]
>  If it has to search on all comments, that would mean many API calls on projects with many comments.

Yes. My stance is that this addon is rejected, until someone builds a **website** (not an addon) that lets you search project comments. We can then choose whether it's worth it to port the concept to an addon that would add the search bar right into the comments area. If we decide not to, all Scratchers still benefit as they can search for project comments, and the website that allows them to do so can be advertised on Scratch without breaking the userscript/extension policy.
