### ISSUE TITLE
Adding more keys to detect

### ISSUE THREAD

**Issue by damightyq** [ScratchAddons/ScratchAddons#5408]
### Why this would be helpful/solve a problem

I'm making a platformer for my media literacy class and I want to run in the game. Therefore I need the shift key and scratch can't detect it.

### What this addon does

This addon would add to the Sensing category to detect more special keys like the enter key, the shift key, etc.

### Demonstration(s) and additional context

![scratchblocks](https://user-images.githubusercontent.com/102260104/205543051-b3bba062-bf5f-4c3d-afd0-12ff611c4b4d.svg)

**Comment by DNin01** [comment]
The only problem this brings up is the potential for the creation of projects that can only be run using Scratch Addons, which I don't feel belong on Scratch - they can make non-SA users confused and can lead to people mentioning SA, which [is against Scratch's rules](https://scratch.mit.edu/discuss/topic/284272/). Nevertheless, such a feature would be cool if it were possible.

By the way, [TurboWarp has this feature](https://turbowarp.org/419393072).

**Comment by DNin01** [comment]
Oh, also, there is already an addon called "Extra key support"[^1] that lets you select symbol keys like hyphen or period, and they actually work in unmodified Scratch, but that can't be done with `shift` or some others.

[^1]: [Will be called "Extra key options" in version 1.30](https://github.com/ScratchAddons/ScratchAddons/pull/5378)
