### ISSUE TITLE
Mention the new private security vulnerability reporting feature in `security.md`

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5409]
Since GitHub Universe, [GitHub now supports private security vulnerability reporting](https://github.blog/changelog/2022-11-09-privately-report-vulnerabilities-to-repository-maintainers/). Might want to update `security.md` to reflect that.

Of course, we can keep the email address as an alternative option.

**Comment by WorldLanguages** [comment]
I think that is already taken into account by this commit: https://github.com/ScratchAddons/ScratchAddons/pull/5307/commits/270dba75ca7b83cfbc4f42ae3820c3ce0aac767c
