### ISSUE TITLE
Themes for Scratch Addons pop-up and settings page

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#542]
Related to #497 and #534.

**Is your feature request related to a problem? Please describe.**

There's only one theme for Scratch Addons. How about allow people to set other themes?

**Describe the solution you'd like**

Implement a method to allow theme customization of the Scratch Addons pop-up and settings page.

**Comment by samuraininja360** [comment]
can I offfer to redesign it

**Comment by WorldLanguages** [comment]
@samuraininja360 Please wait until the current redesign PR gets merged

**Comment by Explosion-Scratch** [comment]
Yay!
