### ISSUE TITLE
“Mark as deleted” option for forums

### ISSUE THREAD

**Issue by lankybox02** [ScratchAddons/ScratchAddons#5444]
### Why this would be helpful/solve a problem

This feature would make it easier when users are trying to delete a post

### What this addon does

It would add a “mark as deleted” button next to the edit button on a post, which will immediately edit the post to “_(Deleted)_”, and possibly also sending a report.

### Possible alternatives

There are no alternative other than manually editing the post.

**Comment by WorldLanguages** [comment]
I don't think this is too hard to do manually. Offering a feature like this could be confusing, as some users might expect the post to be actually deleted.

**Comment by lankybox02** [comment]
I agree, while it is a bit unpractical and a bit confusing, i still think it would still be useful for a lot of people; it saves a good 30 seconds while browsing the forums and, especially if someone accidentally sent something like personal information and wants to quickly delete it
