### ISSUE TITLE
Turbowarp "replace player" stage header is white on dark mode

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#5445]
### Description

![image](https://user-images.githubusercontent.com/17484114/207727518-4e03c46f-501f-4e31-881a-bb1b4d66b9ca.png)

### Steps to reproduce

Enable `turbowarp-player` with "replace player" setting
Enable `dark-www` (NOT dynamically - enable it and then reload)

Go to https://scratch.mit.edu/projects/104/ and click the TurboWarp button

### Demonstration(s) and additional context

If website dark mode is dynamically enabled, for some reason the bug does not happen for the whole session!

### Environment

Happens in both Chrome and Firefox

**Comment by mxmou** [comment]
Sounds very similar to #5298.
