### ISSUE TITLE
SA userstyle

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#5469]
Since Stylus can't be used on other extensions, could we have a button in the _More Settings_ window to upload a custom CSS for the settings page / popup?

**Comment by WorldLanguages** [comment]
I think it simply makes more sense to fork the extension in those cases.

As a bonus, the Chrome Web Store says `Remote code is any JS, Wasm, or CSS that is not included in the extension's package`. After a careful review, a "custom CSS" feature would probably be OK, but it could still cause us review problems.

**Comment by penguinmoose** [comment]
Or, we can simply have a page that allows the user to change the colors of things in the extension popup and more settings.

**Comment by Secret-chest** [comment]
Sorry, but I wouldn't like having to refork the extension every update.

**Comment by WorldLanguages** [comment]
You may use Git's features that make it easier, or write a script that will add your custom CSS to whatever file you please.

**Comment by Secret-chest** [comment]
Still, why not have it?

**Comment by WorldLanguages** [comment]
Because there are workarounds and the feature would only be used by advanced users
