### ISSUE TITLE
Turning 2.0 Blocks 0n forum to 3.0

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#547]
**Describe the new addon**

Basically, switching all the 2.0 block SVGs to 3.0 block SVGs. IDK if this is even possible but this would be great.

Also, when I reload the page where a scratch block on the forum/wiki is, I first see it in its text form. Also, when I reload and stop reloading, I can see the elements on the page for that text. I was digging around and I saw that when the HTML gets injected in the page, it injects the blocks as text (that's why we see text for a split second).

Looks like this is the code they use for converting to scratch blocks from there:
https://scratchblocks.github.io/js/scratchblocks-v3.5-min.js?_=1603304343830:formatted

However, looks like the forums use this:
https://scratchblocks.github.io/js/scratchblocks-v3.5-min.js

A possible way to this would maybe be to try to get that text for the code in the beginning, save it, delete it before it gets converted to 2.0, then run the 3.0 script... Would that work???

**Comment by WorldLanguages** [comment]
See #438
