### ISSUE TITLE
`Website dark mode and customizable colors` Addon Does Not Work in Editor

### ISSUE THREAD

**Issue by tonyzhigit** [ScratchAddons/ScratchAddons#5481]
### Description

_What should happen_
The editor should be dark based on my settings in `Website dark mode and customizable colors`.
_What actually happening_
The editor is not dark.

### Steps to reproduce

1. Start a new project/View other projects in the editor.

### Demonstration(s) and additional context

The editor when I enabled the addon:
![image](https://user-images.githubusercontent.com/100283902/209321262-cea4ef4b-9c74-45a3-84ad-662577c81dbc.png)
The settings in the addon:
![image](https://user-images.githubusercontent.com/100283902/209321393-af6d2db2-d213-4c5b-a629-aa87aeedc440.png)

### Environment

Browser: Chrome `110.0.5478.4 dev` x64  (cohort: Dev) 
Scratch Addons version: v1.29.0
Operating system: Windows 11 21H2

**Comment by tonyzhigit** [comment]
I really don't know if this was supposed to happen or not. I thought it works everywhere except the editor.

**Comment by mxmou** [comment]
There's a separate dark mode addon for the editor.

**Comment by WorldLanguages** [comment]
Should we add an info note to both editor dark mode addons...?
Or should we wait until we have a "related addons" section?

**Comment by mxmou** [comment]
> Should we add an info note to both editor dark mode addons...?
> Or should we wait until we have a "related addons" section?

We could add a note to website dark mode (or change the description). I think editor dark mode already has an unambiguous description ("Customize colors used by the project editor.").
