### ISSUE TITLE
Volume Slider disables Clone Counter

### ISSUE THREAD

**Issue by TJ20201** [ScratchAddons/ScratchAddons#5486]
### Description

Using both the Volume Slider addon and the Clone Counter addon results in unwanted behaviour of the Volume Slider overriding the Clone Counter instead of being drawn alongside it. 

### Steps to reproduce

1. Enable "Volume Slider" and "Clone Counter" addons. (Pastebin to my settings file: [Click Here](https://pastebin.com/xQ7aRdcg))
2. Go to any project's view. Any at all, as VS and CC apply to every project.
3. Check if the Volume Slider and Clone Counter both appear, if not, you have reproduced the bug.

### Demonstration(s) and additional context

Due to my snipping tool shortcut not working, a Pastebin link has been supplied in the reproduction steps with my exported SA Settings file.

### Environment

Browser: Chrome 108.0.5359.125 (chrome://version/)
Scratch Addons version: v1.29.0
Operating system: Windows 10 Home (10.0.19045 x64)

**Comment by TJ20201** [comment]
I have managed to get my snipping tool keybind to work, and this is the appearance of the Stage of my own project.
![image](https://user-images.githubusercontent.com/86313252/209474191-a0647de8-8c20-494a-b097-3fc28f61f06a.png)

**Comment by DNin01** [comment]
Are you in the editor or on the project page? (The clone counter only appears inside the editor.)

**Comment by TJ20201** [comment]
Ah, I was on the project. However, I just tried on the Editor view on the latest source (with an extra addon from my Fork/custom-brand-image) and it appears as this.
![image](https://user-images.githubusercontent.com/86313252/209479928-f500e945-3571-4fb5-bc6b-6495d58973db.png)

**Comment by WorldLanguages** [comment]
Are you aware about the fact the clone counter isn't shown unless the project has at least 1 clone at the moment?

**Comment by TJ20201** [comment]
> Are you aware about the fact the clone counter isn't shown unless the project has at least 1 clone at the moment?

Yes, it turns out I clicked on the wrong project (my Slideshow API one) instead of my Ping Pong one (the one I originally opened this issue with the attachments from). Maybe a boolean setting could be added to the addon that allows it to show on the non-Editor view? (Just a suggestion.)

**Comment by DNin01** [comment]
> > Are you aware about the fact the clone counter isn't shown unless the project has at least 1 clone at the moment?
> 
> Yes, it turns out I clicked on the wrong project (my Slideshow API one) instead of my Ping Pong one (the one I originally opened this issue with the attachments from). Maybe a boolean setting could be added to the addon that allows it to show on the non-Editor view? (Just a suggestion.)

Interesting. I don't know how useful the clone counter would be for anyone who isn't editing the project they're playing, but I guess there _are_ cases where it would still be useful to know in general, like maybe if you were playing a project and then something broke and you looked at the clone counter to find that it was at 300. It can also just be interesting to measure the clone counter.

**Comment by TJ20201** [comment]
> > > Are you aware about the fact the clone counter isn't shown unless the project has at least 1 clone at the moment?
> > 
> > 
> > Yes, it turns out I clicked on the wrong project (my Slideshow API one) instead of my Ping Pong one (the one I originally opened this issue with the attachments from). Maybe a boolean setting could be added to the addon that allows it to show on the non-Editor view? (Just a suggestion.)
> 
> Interesting. I don't know how useful the clone counter would be for anyone who isn't editing the project they're playing, but I guess there _are_ cases where it would still be useful to know in general, like maybe if you were playing a project and then something broke and you looked at the clone counter to find that it was at 300. It can also just be interesting to measure the clone counter.

Yeah, I guess. It could still be useful for those who want to check the clone count for reasons such as lag but don't want to go to the editor for reasons such as loss of current playing data on some projects.
