### ISSUE TITLE
Merge `better-emojis` with `emoji-picker`

### ISSUE THREAD

**Issue by RIMOPA** [ScratchAddons/ScratchAddons#5494]
### Why this would be helpful

There have been some issues saying that there are too many addons and emojis are difficult to use without the picker, so probably most users with `better-emojis` have `emoji-picker` enabled.
This two addons are similar, so merging them would help users to use them and not to get disoriented.

### My suggestion

Make the `better-emois` addon an option for the `emoji-picker` addon.

### Possible alternatives

We could merge them without making `better-emojis` an option.

### Additional context

#5389 and #1663 and have other solutions to the problem.

**Comment by mxmou** [comment]
> This two addons are similar

They aren't very similar, even though they're both related to emojis. Emoji picker makes writing comments with emojis easier. Better emojis changes the way emojis look in all comments, including those written by others.

**Comment by BroJac5246** [comment]
They're totally different, so no support.

**Comment by WorldLanguages** [comment]
I don't think opinionated addons should be merged with unopinionated addons.
Also, the emoji picker is an obvious feature that Scratch lacks. This isn't the case of the better emojis addon.

**Comment by WorldLanguages** [comment]
Still, the idea of merging addons related to the same concept (such as the editor backpack, or linkifying text) is worth trying.
We are moving away from the "editor devtools" model (where many unrelated editor addons were merged) and instead merge addons that affect the same small section of Scratch, such as project thumbnails.

**Comment by Secret-chest** [comment]
> linkifying text

Do you want to bring that up again? They linkify completely different things.

**Comment by WorldLanguages** [comment]
@Secret-chest I'm not in favor of merging more-links with other addons. But merging curator-link with an upcoming "clickable forums mentions" (#4845) is planned.
