### ISSUE TITLE
Pause button

### ISSUE THREAD

**Issue by MasimbaTheHuman** [ScratchAddons/ScratchAddons#550]
Everyone wants a pause button. I HATE it when I have to reset my game if I die.

I don't know any links for it though.

**Comment by Explosion-Scratch** [comment]
This would likely be very tricky. It'd probably be possible to just completely stop it on any frame but pausing it could present challenges. You'd have to ask @apple502j about it, but it'd be super cool!

**Comment by JeffaloBob** [comment]
scratch-vm probably has some way to pause itself right?

**Comment by TheColaber** [comment]
Maybe you want to find the code that sets the frame or something like what TurboWarp does to set the frames to 60. You might want to try to set it to 0.

**Comment by mxmou** [comment]
> Maybe you want to find the code that sets the frame or something like what TurboWarp does to set the frames to 60. You might want to try to set it to 0.

Unfortunately that's just a boolean, true for 30 FPS, false for 60 FPS.

**Comment by WorldLanguages** [comment]
Maybe you can make it so running a tick actually doesn't do anything?

**Comment by wgyt735yt** [comment]
Forkphorus has this, I think we could do this.

**Comment by YOYITsM3M8** [comment]
forkphorus compiler to javascript

**Comment by GarboMuffin** [comment]
Just override vm._step to no-op if paused, that shouldn't be hard

**Comment by JeffaloBob** [comment]
this sounds like a fun addon to try to make, I'll see what i can make tomorrow

**Comment by JeffaloBob** [comment]
alright so i've tried something like this
```js
if (!playing) {
    vm.runtime._step = step
    vm.runtime.audioEngine.audioContext.resume()
    vm.runtime.ioDevices.clock.resume()
    img.src = addon.self.dir + "/pause.svg"
} else {
    step = vm.runtime._step
    vm.runtime._step = function() {}
    vm.runtime.audioEngine.audioContext.suspend()
    vm.runtime.ioDevices.clock.pause()
    img.src = addon.self.dir + "/play.svg"
}
playing = !playing
```

but an issue i have is that when you resume, the audio/timer are fine, but the actual execution will jump ahead as if it was never paused. i don't know if that's something which is possible to fix.

another thing to note is with something like this, it's not possible to see variable values in the editor which is a major reason to pause projects. 

griffpatch said:
> What we actually need to do is pull all the execution stack out into a temporary location, and then resume it later by putting it back in
> I've seen it done before
> Game bender does it in a custom build of scratch all the time ;)

which means it must be possible, but i don't think that's something i know how to do...

in the meantime, i've made some nice buttons and used the replacing step with no-op to make this:
![urgvTTGJVc](https://user-images.githubusercontent.com/40470736/97775618-69296e80-1b62-11eb-8111-eb67d1d2b4ff.gif)

**Comment by YOYITsM3M8** [comment]
nice

**Comment by TheColaber** [comment]
Wow, this will be an awesome addon! Does this low down performance?

**Comment by JeffaloBob** [comment]
@TheColaber yes because traps

**Comment by TheColaber** [comment]
> @TheColaber yes because traps

Ah, that's unfortunate

**Comment by JeffaloBob** [comment]
> > @TheColaber yes because traps
> 
> Ah, that's unfortunate

not really a big deal

**Comment by MasimbaTheHuman** [comment]
WOW MIND BLOWN

**Comment by JeffaloBob** [comment]
uh i don't think you needed to close the issue. the PR isn't merged yet lol

**Comment by MasimbaTheHuman** [comment]
> uh i don't think you needed to close the issue. the PR isn't merged yet lol

Sorry
