### ISSUE TITLE
Feedback on editor-dark-mode and text caret

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#5502]
Translated from Japanese:

> Hello World!
Will begin the main subject. I don't know if this is a bug or a feature, but I will report it.
I use the "editor dark mode and customization" in the addon. But when I use this, even the costume paint editor palette turns black and becomes unwieldy. So I always uncheck "Change costume editor background and borders", but I noticed a problem.
Suppose you write a letter in a paint editor. A text box will appear. And when you enter text, you should see this "|" (according to my research, it's called a caret) with a blinking vertical line indicating the position to enter. But what do you mean, it's white. I think it's probably because the accent color is still black.
It would be a problem if a white "|" appears on a white background. After unchecking "Change the background and borders of the costume editor", could you please debug so that the color of "|" returns to black? please.

Feedback comes from 1.29.0 stable version, on Chrome 108.
Not sure if this is currently fixed on the master branch. @mxmou please confirm.

By the way, in case anyone reading this is interested, specially mxmou: I plan to remove the current feedback system in favor of something like https://feedback.fider.io/ (but with some tweaks). So a discord account will not be required to read feedback. Public bug reports can be read by anyone, and private ones will be readable by logging in with a Scratch account (only for whitelisted Scratch accounts from maintainers).

**Comment by DNin01** [comment]
It looks like they're saying that the blinking text insertion line shown when adding text to a costume doesn't change to black when you have the Change the costume editor background and selection borders option enabled (the one that makes the costume editor background dark). At least, that's what happened to me.

This is what it looks like:
![](https://user-images.githubusercontent.com/106490990/209883085-1342413b-d2cb-4fec-9419-fc798776bedd.png)


(For the feedback system, I would prefer some other way than verifying ownership of a Scratch account, maybe GitHub OAuth?)

**Comment by mxmou** [comment]
I think this could be fixed by setting the `color` of the textarea explicitly. It's currently chosen by the browser based on the `color-scheme`.

**Comment by WorldLanguages** [comment]
Offtopic:

> (For the feedback system, I would prefer some other way than verifying ownership of a Scratch account, maybe GitHub OAuth?)

We could theoretically make it so maintainers can login with GitHub - but everyday users won't have a GitHub account, so we're forced to add a way to login with Scratch anyway (why add a second way to login then?). Note that it will still be possible to send feedback anonymously - logging in will be optional, and will only be required to upvote ideas.

**Comment by DNin01** [comment]
> Offtopic:
> 
> 
> 
> > (For the feedback system, I would prefer some other way than verifying ownership of a Scratch account, maybe GitHub OAuth?)
> 
> 
> 
> We could theoretically make it so maintainers can login with GitHub - but everyday users won't have a GitHub account, so we're forced to add a way to login with Scratch anyway (why add a second way to login then?). Note that it will still be possible to send feedback anonymously - logging in will be optional, and will only be required to upvote ideas.

I just have concerns, not with security, but kid safety, mainly because these systems usually need to use a Scratch project that references the authentication service. My worry is that a user may stumble upon the Scratch project used for authentication from browsing Scratch which allows them to visit its website, then visit the website which in turn references an external community (in any way visible to visitors coming from Scratch), and then find content that is not appropriate for Scratch. This could lead to the Scratch project needing to be taken down.

If we do this, I want to see a Scratch-friendly authentication system that doesn't violate the Scratch Community Guidelines or policies in any way. Redirects from and back to websites (like from a feedback service and back to that same feedback service) would probably be okay.

**Comment by WorldLanguages** [comment]
> find content that is not appropriate for Scratch

I want to clarify that what you're mentioning will not happen. All posts and comments will be moderated BEFORE they are made public.

**Comment by WorldLanguages** [comment]
> a Scratch project that references the authentication service

I think we could avoid naming the service inside Scratch.
