### ISSUE TITLE
remix tree on project page does not work

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#551]
**Describe the bug**

no remix tree button is added, error is thrown
![image](https://user-images.githubusercontent.com/40470736/96838174-caa55b00-1447-11eb-9805-0d038f8d6e89.png)

**To Reproduce**

1. enable remix tree addon
2. go to project page
3. see no remix tree button
4. sad

**Expected behavior**

remix tree button shows

**Device (please complete the following information):**

- OS: windows 10 1909
- Browser: chrome
- Version 29029d5d2782f6cfa280efc3159fff538a454085

**Comment by JeffaloBob** [comment]
it showed up for some reason now, but it doesn't actually do anything

**Comment by GDUcrash** [comment]
fixed in my [recent pr](https://github.com/ScratchAddons/ScratchAddons/pull/554)

**Comment by Explosion-Scratch** [comment]
> fixed in my [recent pr](https://github.com/ScratchAddons/ScratchAddons/pull/554)

Yep! It works for me! I'll close this!

**Comment by GrahamSH-LLK** [comment]
The PR isn't merged, wait until then.

**Comment by WorldLanguages** [comment]
Merged
