### ISSUE TITLE
Add a warning on the Scratch forums to avoid posts about Scratch Addons

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#552]
There are still people who report bugs on the Bugs and Glitches category/subforum. I think we should add either an addon or just an extension feature so there will be a warning to stop people post about Scratch Addons on that category. Maybe also do the same to the Suggestion category/subforum and griffpatch's comment section, if you want.

**Comment by WorldLanguages** [comment]
Keep in mind many bug reports related to Scratch Addons don't mention it at all, they actually think it's a bug within Scratch itself.

**Comment by TheColaber** [comment]
> Keep in mind many bug reports related to Scratch Addons don't mention it at all, they actually think it's a bug within Scratch itself.

Yeah, I think because we didn't mention that would happen in the settings so they kinda think it was scratch itself.

**Comment by WorldLanguages** [comment]
@TheColaber Of course we can't mention bugs in the settings, because if we knew about them we'd fix them (or remove the addon all together)

**Comment by mxmou** [comment]
> Keep in mind many bug reports related to Scratch Addons don't mention it at all, they actually think it's a bug within Scratch itself.

Maybe the warning could look like this:

> Make sure the bug you are reporting happens when Scratch Addons is disabled. If not, report it [here](https://scratchaddons.com/feedback).

**Comment by GrahamSH-LLK** [comment]
Make sure the bug you are reporting also happens when Scratch Addons is disabled. If not, report it here.
![Screenshot 2020-10-22 at 2 17 32 PM](https://user-images.githubusercontent.com/64214252/96913283-6f885e00-1471-11eb-95f7-b61800dfca89.png)
^Mockup^

**Comment by Explosion-Scratch** [comment]
Yep! That sounds good.

**Comment by Hans5958** [comment]
Well, it need some margin and some adjustments so it look fits.

**Comment by Explosion-Scratch** [comment]
It should look like the 60 second rule thing.

**Comment by Hans5958** [comment]
> 
> It should look like the 60 second rule thing.

Ah, I've never got those. Mind giving a screenshoot?

**Comment by scratchusernamemrtbts** [comment]
> > It should look like the 60 second rule thing.
> 
> Ah, I've never got those. Mind giving a screenshot?

here's a screen shot
<img width="949" alt="ภาพถ่ายหน้าจอ 2563-10-23 เวลา 11 56 37" src="https://user-images.githubusercontent.com/66320961/96958159-da47a100-1526-11eb-92c0-cb97d0671b22.png">

**Comment by Explosion-Scratch** [comment]
Yup! That's it!

**Comment by JeffaloBob** [comment]
instead of with Scratch Addons disabled, say with no browser extensions enabled because we are doing a duty for all fellow extesntions

**Comment by Explosion-Scratch** [comment]
That's true.

**Comment by Hans5958** [comment]
> 
> 
> instead of with Scratch Addons disabled, say with no browser extensions enabled because we are doing a duty for all fellow extesntions

Well, yes, but the others are not so Scratch oriented, but sure.

**Comment by GrahamSH-LLK** [comment]
I feel like we have to walk a thin line here. If we make it all extensions, people might just not bother doing anything.

**Comment by Explosion-Scratch** [comment]
Yeah, maybe just scratchaddons.

**Comment by TheColaber** [comment]
Is there like, a content script that we could use for default things, or would we need to create that?

**Comment by WorldLanguages** [comment]
@TheColaber This could be added within cs.js

**Comment by TheColaber** [comment]
Nice! I might work on this.
