### ISSUE TITLE
Fix position and layout of preset buttons

### ISSUE THREAD

**Issue by penguinmoose** [ScratchAddons/ScratchAddons#5549]
### Description

In the setting menu of the `dark-www` (website dark mode and customizable colors) addon, in the "presets" section, the "presets" heading is touching the first preset button, and there is no linebreak between the "presets" heading and the first preset.

In fullscreen settings, the presets are side-by-side, which is fine, but I would prefer them to be on top of each other and turn them into radio buttons (as we may add more and more presets).

### Steps to reproduce

1. Open the Scratch Addons extension popup.
2. Find the `dark-www` extension (I did this by typing dark-www into the addon search bar).
3. Click on the down caret icon to expand the addon and show its setting menu.
4. Find the `presets` section by scrolling down. 
5. Notice that the presets are positioned oddly, the **presets** label/heading is touching the first preset, and thus the presets do not align. See additional context.

### Demonstration(s) and additional context

<img width="350" alt="Screenshot 2023-01-05 at 1 54 26 PM" src="https://user-images.githubusercontent.com/67451414/210890808-5085ef6b-f012-4cb4-8687-193df0e80601.png">

^^^ There is no space between "presets" heading and the preset buttons.

I think this is because the presets are supposed to be side-by-side, but the extension popup is not wide enough, so the presets move down because there is not enough space. The first preset remains close to the "presets" label (which now acts like a heading) and even touches it. This results in the addon buttons being oddly positioned and the lack of spacing between the "presets" label and the actual preset buttons.

We should make the presets more responsive and go on top of each other with enough spacing.

### Environment

Browser: Chrome version 108.0.5359.124 (Official Build) (arm64)
Scratch Addons version: 1.29.0
Operating system: MacOS Ventura 13.0 on 14" 2021 MacBook Pro M1 pro

**Comment by DNin01** [comment]
This also happens with other addons.
![The Message count on extension icon addon in the extension popup with the text "Presets" touching the preset buttons](https://user-images.githubusercontent.com/106490990/210910075-0a082b75-f6df-4017-b5b5-f8b8ba413ea7.png)

**Comment by mxmou** [comment]
I don't think the way presets are listed on the full screen settings page needs to be changed - making the list vertical would use a lot more space.

**Comment by penguinmoose** [comment]
@mxmou That's true, as long as we don't have too many presets keeping them side by side would be fine.
