### ISSUE TITLE
Reduce height of variables with sliders 

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#5550]
### Why this would be helpful

The new Scratch 3.0 size of variable monitors on the Stage is too high when the slider is shown. This reduces the available space on the Stage.

### How this addon works

Bring back the size of variables with sliders on the Stage to the one of Scratch 2.0

### Possible alternatives

None

**Comment by WorldLanguages** [comment]
This one is hard because project authors may not expect variable monitors to be smaller than what they see.
Also, of course, enabling this addon would only mean that just **you** get smaller monitors, not everyone looking at your project.

**Comment by sfederici** [comment]
> of course, enabling this addon would only mean that just **you** get smaller monitors, not everyone looking at your project.

Oh, yes, you are right... :-(
Then you can delete this proposal :-)
