### ISSUE TITLE
Sprite Panel Collapse Speed is always instant

### ISSUE THREAD

**Issue by CubesterYT** [ScratchAddons/ScratchAddons#5557]
### Description

When having the Sprite Panel Collapse addon on, when collapsing and un collapsing it, the speed is the exact same, for all settings, which is instant:

https://user-images.githubusercontent.com/78769806/211115550-2a233486-e359-4a42-992a-3ad14a99eeb7.mp4

### Steps to reproduce

1. Enable the addon
2. Use the addon/change all speed settings
3. Nothing else

### Environment

Browser: Chrome 108.0.5359.125
Scratch Addons version: 1.30.0
Operating system: Windows 10

**Comment by GarboMuffin** [comment]
it's a compatibility issue with drag-drop -- they both want to transition the same element

**Comment by CubesterYT** [comment]
Oh yeah, I have drag and drop on:

![image](https://user-images.githubusercontent.com/78769806/211116379-ff89fd55-bba4-4e59-86b4-95e063e538e8.png)
