### ISSUE TITLE
"fullscreen" addon makes canvas white (width=0 height=0)

### ISSUE THREAD

**Issue by InTheProcess** [ScratchAddons/ScratchAddons#5567]
Regressed by #5498

### Description

Sometimes while creating my project, the scratch project's window goes completely white.  The project still works, it is just nothing renders anymore.

### Steps to reproduce

**EDIT:** see https://github.com/ScratchAddons/ScratchAddons/issues/5567#issuecomment-1382568279 for reproduction steps 
I am not completely sure how to reproduce the error, but it would occasionally happen when switching between See project page and back.

### Demonstration(s) and additional context

My Project looks like this:
[https://imgur.com/a/YCbAIjA](url)

Here is the list of addons I have enabled:
[https://pastebin.com/jENLuz74](url)
My project is around 23MB in size.

### Environment

Browser: 
Scratch Addons version: 
Operating system:

**Comment by BroJac5246** [comment]
Are you sure this is a Scratch Addons error?

**Comment by InTheProcess** [comment]
I am pretty sure.  I tried turning the extension off and worked on the project for a bit.  The error never came up.  It has only appeared with Scratch Addons Extension enabled.

**Comment by WorldLanguages** [comment]
@InTheProcess Chrome or Firefox?

**Comment by InTheProcess** [comment]
I use Brave, a chrome-based browser.

**Comment by InTheProcess** [comment]
Version 1.30.0

**Comment by InTheProcess** [comment]
Of the extention

**Comment by InTheProcess** [comment]
Using Windows 11 professional as my operating system.

**Comment by WorldLanguages** [comment]
Will be hard to find the root cause of this

**Comment by InTheProcess** [comment]
Could you describe what you mean?

**Comment by WorldLanguages** [comment]
Related: https://scratch.mit.edu/discuss/post/6883938/
![image](https://user-images.githubusercontent.com/17484114/211221703-84a53728-b083-4b94-84f4-1266aca9dd7e.png)

(Post author has Scratch Addons)

**Comment by InTheProcess** [comment]
Based on that post, it may be a Scratch related issue rather than the extension.

**Comment by WorldLanguages** [comment]
It might be a coincidence.

@InTheProcess Have you experienced this bug before January 5th? That's the date where we started releasing Scratch Addons v1.30.0

**Comment by InTheProcess** [comment]
No, never

**Comment by WorldLanguages** [comment]
I asked on their profile if they're using Scratch Addons, waiting for reply:

![image](https://user-images.githubusercontent.com/17484114/211370366-57be0a21-0ffd-412e-81d4-194370e0953f.png)

https://scratch.mit.edu/discuss/post/6884268/

**Comment by WorldLanguages** [comment]
Update: Jisena uses Scratch Addons.

**Comment by InTheProcess** [comment]
So this may be a Scratch Addons problem rather than Scratch itself.

**Comment by Samq64** [comment]
> the scratch project's window goes completely white. The project still works, it is just nothing renders anymore.
Like this?
![image](https://cdn.discordapp.com/attachments/995828149973700688/1052632432718909521/image.png)

**Comment by InTheProcess** [comment]
Yes, that is correct!

**Comment by Samq64** [comment]
Have you tried making sure your browser is completely up to date? I had this problem about a month ago and I think updating the browser fixed it.

**Comment by InTheProcess** [comment]
Yes, my browser is fully up to date.

**Comment by WorldLanguages** [comment]
I think I found a way to reproduce:
1. Enable the "enhanced full screen" addon
2. Go to any project: https://scratch.mit.edu/projects/104/
3. Go to full screen
4. Exit full screen
5. Click "see inside"

**Comment by WorldLanguages** [comment]
> I believed it looked exactly like that, but I didn't see the thing in the top left corner because a variable was obstructing the view.

It's possible that there was no "crashed" icon at all.
@InTheProcess It looks like you have the "enhanced fullscreen" addon enabled. Maybe try disabling it and wait to see if it happens again? In that case, these are 2 different bugs.

**Comment by Samq64** [comment]
I can reproduce with your steps. It's definitely a different issue, mine happened when creating a new project and only on Chrome.
