### ISSUE TITLE
Allow right-clicking a function parameter call (in the function's definition) to replace it with a dropdown, like variables.

### ISSUE THREAD

**Issue by DroneBetter** [ScratchAddons/ScratchAddons#557]
I'm not sure how it would work when it's in a block of code floating outside of the function, it could possibly allow selection of parameters from all functions, but it would be an improvement over having to drag another one in.

**Comment by TheColaber** [comment]
It would be cool if we could have the options for dropdowns and number-only options when we create on a block.

**Comment by Explosion-Scratch** [comment]
I don't quite understand, could you expand more?

**Comment by JeffaloBob** [comment]
> I don't quite understand, could you expand more?

i think they're suggesting a method to create "hacked blocks" with custom inputs as dropdowns

**Comment by mxmou** [comment]
@JeffaloBob They're suggesting the ability to replace a custom block parameter with another one by right-clicking.

**Comment by JeffaloBob** [comment]
> @JeffaloBob They're suggesting the ability to replace a custom block parameter with another one by right-clicking.

ah ok

**Comment by mxmou** [comment]
This could be an option in the block switching addon.
