### ISSUE TITLE
More fonts in the Scratch image editor

### ISSUE THREAD

**Issue by michaeleldar** [ScratchAddons/ScratchAddons#5571]
### Why this would be helpful

The default fonts are really bad so it would be good if there were more.

### How this addon works

In the drop down menu, there will be several more common fonts to choose from. Maybe it would be possible to import a custom font too?

### Additional context

I don't know how Scratch stores the data about fonts, but keeping compatibility with non-scratchaddons users might make this impossible.

**Comment by RedGuy12** [comment]
duplicate of #2050
