### ISSUE TITLE
paint-snap magnet also disables vanilla center snapping

### ISSUE THREAD

**Issue by Unkrown6YT** [ScratchAddons/ScratchAddons#5573]
### Why this would be helpful

I found the object doesn't going to corner while Magnet icon is enabled

### My suggestion

https://user-images.githubusercontent.com/94491221/211211653-04e3555b-b20b-4836-a12b-df55bb539437.mp4

**Comment by Samq64** [comment]
When `paint-snap` is enabled nothing snaps to the centre of the canvas when snapping isn't active even though it does in vanilla Scratch. This might be intentional though.

**Comment by ErrorGamer2000** [comment]
> When `paint-snap` is enabled nothing snaps to the centre of the canvas unless snapping is active. This might be intentional though.

It is intentional, yes.

**Comment by mxmou** [comment]
When `paint-snap` is enabled but snapping is disabled I would expect dragged object to behave exactly the same as in vanilla Scratch.

**Comment by WorldLanguages** [comment]
> When `paint-snap` is enabled but snapping is disabled I would expect dragged objects to behave exactly the same as in vanilla Scratch.

Agreed

**Comment by WorldLanguages** [comment]
Even though this was intentional, I'm going to consider this a bug until we can conclude otherwise.
This behavior breaks an implicit rule: it's not great when clicking in a button that apparently disables the addon temporarily and actually disabling the addon do different things.
