### ISSUE TITLE
Website dark mode: posts with no replies show up white

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#5576]
### Description

> I obviously use dark theme, and whenever I scroll through the forums I keep seeing posts that are white and I can't read them.

### Steps to reproduce

Haven't reproduced myself

### Demonstration(s) and additional context

![image](https://user-images.githubusercontent.com/17484114/211220937-d11717da-9588-453c-97bc-f22af958ddd4.png)

### Environment

Scratch Addons version: v1.30.0

Probably a regression

**Comment by DNin01** [comment]
It could also be caused by another addon or even a different browser extension.

**Comment by WorldLanguages** [comment]
Apparently this is caused by a different browser extension.
