### ISSUE TITLE
paint-snap addon breaks reshape tool

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#5577]
### Description

> whenever i just use costume editor snapping with the reshape tool it just does nothing

### Steps to reproduce

Haven't reproduced myself

### Environment

Scratch Addons version: v1.30.0

**Comment by DNin01** [comment]
It's possible they're saying that when using the reshape tool, the addon doesn't snap points.

**Comment by WorldLanguages** [comment]
> so when i was using the addon with the reshape tool whenever a part was grouped with another part it didn't let me drag it with the reshape tool but normally you would be able to move the part

**Comment by WorldLanguages** [comment]
This is probably not a SA bug

**Comment by mxmou** [comment]
> This is probably not a SA bug

It is. When `paint-snap` is disabled, it's possible to drag individual objects in a group if the reshape tool is selected:
![reshape_working](https://user-images.githubusercontent.com/51849865/211322714-b7167551-19ce-4adb-8926-959615e8d0ad.gif)
`paint-snap` breaks this, even if snapping is disabled. Dragging with the reshape tool does nothing:
![reshape_bug](https://user-images.githubusercontent.com/51849865/211322857-2807d6ff-3173-4814-a9c4-b1d70d9ada78.gif)

**Comment by ErrorGamer2000** [comment]
![image](https://user-images.githubusercontent.com/70162741/211371308-63b162e1-2335-42ff-b9d0-83c691b41769.png)
Found the issue, will pr a fix soon
