### ISSUE TITLE
`confirm-actions`: delay between blue translucent background appearing and popup being displayed

### ISSUE THREAD

**Issue by penguinmoose** [ScratchAddons/ScratchAddons#5590]
### Description

When a confirmation popup - specifically canceling comments (and some more) appears (with 2.0->3.0 enabled), the blue translucent background appears, but there is a delay before the actual popup flies down from the top.

See screen recording in additional context.

### Steps to reproduce

1. Enable `confirm-actions`
2. Type something into the comment box and cancel the comment (make sure you have comment cancelation confirmations on)
3. There is a delay between the blue translucent background appearing and the confirmation popup itself appearing.

### Demonstration(s) and additional context

Demonstration:

https://user-images.githubusercontent.com/67451414/211449040-9416a643-014a-44cd-b4e0-c9962354e6fc.mov

Notice the delay between the blue screen appearing and the popup flying down.

Perhaps SA is somehow taking time to "load" the popup, or is some of the timing wrong? Or is it intentional?

Enabled addons:
- `confirm-actions`
- `scratchr2` (2.0 -> 3.0)
- Lots of other addons, 43 in total

### Environment

Browser: Chrome 108.0.5359.124 (Official Build) (arm64)
Scratch Addons version: v1.30.0
Operating system: MacOS Ventura 13.0 on MacBook Pro M1 Pro

**Comment by DNin01** [comment]
That's probably Scratch behavior - this addon uses the exact same animation for popups on Scratch 2 pages.

**Comment by mxmou** [comment]
The delay is correct, the problem is that the background appears instantly instead of fading in.
