### ISSUE TITLE
What's happening not updating until load more pressed

### ISSUE THREAD

**Issue by michaeleldar** [ScratchAddons/ScratchAddons#5598]
### Description

This is very tiny and insignificant bug, so probably don't bother fixing it, but I'm reporting it just in case.

I just loved and faved my own project, and using the trick, I followed myself (ages ago, not now). However when I open scratch my feed doesn't include it (see video below). I then click load more, and it shows it. If I reload again, it disappears again. I'll post a comment if it persists.

### Steps to reproduce

1. [Follow yourself](https://scratch.mit.edu/projects/237725713/) (can be done well in advance, I have been following myself for a long time) (may or may not be related to the bug)
2. Like and/or fave your own project
3. Go to scratch.mit.edu, and follow the steps in the video.

Note: I managed to reproduce it myself again.

### Demonstration(s) and additional context

https://user-images.githubusercontent.com/66514999/211647689-44aaca4a-23aa-4a17-a029-851ae67a41a9.mov

Note: I reloaded during the video, that's when it disappears again.

### Environment

Browser: Chrome 108
Scratch Addons version: 1.30.0
Operating system: Mac OS

**Comment by michaeleldar** [comment]
Update: It fixed itself about five minutes later, but I am consistently able to reproduce it.

However, I think this I know why this is happening and how it can be used to improve what's happening.

My theory: Scratch's source for getting the what's happening data is slower, than scratchaddon's. This means that the scratch what's happening data updates slower for everyone, but when you press the load more button, it changes the what's happening with the latest data taken from scratchaddon's source. 

So you could just always make what's happening always fetch the data the way load more does.

If you don't understand, I can clarify in the comments

**Comment by BroJac5246** [comment]
> Update: It fixed itself about five minutes later, but I am consistently able to reproduce it.
> 
> However, I think this I know why this is happening and how it can be used to improve what's happening.
> 
> My theory: Scratch's source for getting the what's happening data is slower, than scratchaddon's. This means that the scratch what's happening data updates slower for everyone, but when you press the load more button, it changes the what's happening with the latest data taken from scratchaddon's source. 
> 
> So you could just always make what's happening always fetch the data the way load more does.
> 
> If you don't understand, I can clarify in the comments

I believe Scratch Addons retrieves its data from Scratch, so I don't _think_ that's the case.

**Comment by WorldLanguages** [comment]
I'm not really sure if this is a SA bug.

**Comment by michaeleldar** [comment]
> > Update: It fixed itself about five minutes later, but I am consistently able to reproduce it.
> > However, I think this I know why this is happening and how it can be used to improve what's happening.
> > My theory: Scratch's source for getting the what's happening data is slower, than scratchaddon's. This means that the scratch what's happening data updates slower for everyone, but when you press the load more button, it changes the what's happening with the latest data taken from scratchaddon's source.
> > So you could just always make what's happening always fetch the data the way load more does.
> > If you don't understand, I can clarify in the comments
> 
> I believe Scratch Addons retrieves its data from Scratch, so I don't _think_ that's the case.

It doesn't entirely look like that.

What I think:
Let's say you have 2 storage files, named 1 and 2
scratchaddons goes directly to 1, to get the very latest data.
scratch goes to 2, which every say minute syncs itself with 1, meaning it has a delay.

**Comment by michaeleldar** [comment]
> I'm not really sure if this is a SA bug.

I originally thought it was a bug, but now I realized it could make an improvement. Load more, is supposed to load more activity below, which is does, but it also fetches to a more recent version of the what's happening data, which scratch doesn't do until a few minutes has passed. When going to the homepage, making it immideatly trigger a load more event, without actually adding more underneath would make users get the very latest data, without having to wait a few minutes

If you (rightly) think this is too small a feature/bug to put effort into, then close it.

**Comment by mxmou** [comment]
When you open the home page, Scratch requests the first 5 items of What's Happening. When you click Load more, the addon requests the first 40 items. The response to both requests is cached by Scratch's server. They may be different, but neither is guaranteed to be more recent, so there's no reliable way to fix this.
