### ISSUE TITLE
(Google Chrome) Keep scratchaddons tab open

### ISSUE THREAD

**Issue by michaeleldar** [ScratchAddons/ScratchAddons#5599]
### Why this would be helpful

This is kind of a 2 in one issue.

(1) In google chrome, the scratchaddons tab (which you use by pressing the browser extension logo) should stay open when clicking a link inside it, like the firefox one. Maybe it closes because google chrome closes browser extensions when a link (in the browser extension tab) is clicked, but then would it be possible to just instantly re-open scratchaddons again? (I don't know how browser extensions work)

(2) When the mark messages as read button is pressed the scratchaddons tab should close.

### My suggestion

Above

**Comment by WorldLanguages** [comment]
Number 1 is imposible. Please suggest this to Chrome.

Number 2 is unnecessary and closing the popup might be unexpected. For example, I always mark messages as read _before_ actually reading them.
