### ISSUE TITLE
Make it harder to accidentally click the in-editor "unshare" button

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5606]
### Why this would be helpful

Some people may want to have the ability to unshare projects from the editor but don't want to have an obvious orange Unshare button at the top of the screen that looks like it's waiting to be clicked. I generally don't like when critical/dangerous actions are placed in accessible areas.

### My suggestion

We can make it possible to move the Unshare button to the File dropdown in the menu bar. This would help users avoid accidental clicks on the Unshare button.

This should be toggleable if we add it (because it may make this feature harder for new users to figure out, leaving them wondering what the addon is about. Users should be familiar with the addon before customizing it in ways that makes it harder to understand at first glance).

### Possible alternatives

- We could let the user keep the normal "Shared" label, and then have it change to an "Unshare" button when you're hovering over it, similar to how GitHub's the "Enabled" (or should I say "Disable") button in its 2FA settings works:

https://user-images.githubusercontent.com/106490990/211972263-576b3033-d3d2-4ba0-bfae-11f16ba69a2a.mp4

This could make it less distracting but probably not any easier to avoid. Then again, the user will probably have `confirm-actions` enabled.

- Always ask for confirmation whether `confirm-actions` is enabled or not.

**Comment by apple502j** [comment]
It does always show a confirmation.
