### ISSUE TITLE
Online status in profile

### ISSUE THREAD

**Issue by nekitkirov** [ScratchAddons/ScratchAddons#5608]
### Why this would be helpful

I want this because isOnline not working and it's so cool

### How this addon works

in profile next to ocular you see text online - green offline - red

**Comment by WorldLanguages** [comment]
See https://github.com/ScratchAddons/ScratchAddons/issues/4058, https://github.com/ScratchAddons/ScratchAddons/discussions/342, https://github.com/ScratchAddons/ScratchAddons/discussions/504
