### ISSUE TITLE
ScratchAddons Website

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#561]
Do you mind if I design the website for ScratchAddons I can add more pages and a better design to make it more pleasing to the eye. Can someone also show me the color palette as well.

**Comment by YOYITsM3M8** [comment]
bruh, scratchaddons.com

**Comment by samuraininja360** [comment]
I especially like the dark theme and normal theme button. I think I will keep the slideshow as well but I am working on the content display

**Comment by Explosion-Scratch** [comment]
Feel free to make PR's at the website repo though ( ScratchAddons/website )
