### ISSUE TITLE
`remix-button`: Can still remix even the project is unshared.

### ISSUE THREAD

**Issue by tonyzhigit** [ScratchAddons/ScratchAddons#5612]
### Description

I think that this is not supposed to happen.
You can still remix the project even though it was unshared.

### Steps to reproduce

1. Unshare a project.
2. Click the remix button.

### Demonstration(s) and additional context

![image](https://user-images.githubusercontent.com/100283902/212330689-39ee22ea-255b-4ea4-8d38-d84119d55e40.png)

### Environment

Browser: Chrome 111.0.5532.2
Scratch Addons version: 1.30.0
Operating system: Windows NT 10 x64

**Comment by Samq64** [comment]
This might not have been intentional, but I don't think it's really a bug either.

**Comment by WorldLanguages** [comment]
This is the first time I consider something to be a bug and not a bug at the same time 😂

**Comment by DNin01** [comment]
If Scratch allows you to, Scratch Addons will allow you to.

**Comment by BroJac5246** [comment]
I wouldn't consider this a bug, just something not originally thought of. If we want, we could add an option to show the button on unshared projects, but otherwise this should be left as-is, as some people might want this.

**Comment by apple502j** [comment]
Works as intended.
