### ISSUE TITLE
After ChromeOS installs Lacros, Scratch Addons breaks

### ISSUE THREAD

**Issue by TylerMS887** [ScratchAddons/ScratchAddons#5615]
### Description

Most addons stop functioning after enabling ChromeOS Lacros (`chrome://flags#lacros-support` on Ash or `os://flags#lacros-support` on Lacros). Instead most of it is vanilla Scratch.

### Steps to reproduce

1. Enable ChromeOS lacros at this page: chrome://flags#lacros-support. Click "Restart" and you will get a screen saying **Updating Chrome Browser**.
2. In the Lacros browser, open Scratch and follow a few links that appear on it (including search).
3. Most of the UI switches back to vanilla. Only a few addons persist.

### Demonstration(s) and additional context

Thankfully I was able to create a recording of this issue:
[Screen recording 2023-01-14 11.16.25.webm](https://user-images.githubusercontent.com/115214762/212469332-3b39ea64-f53c-45fd-a0c5-4db86f4c7bc7.webm)

Sorry if it's laggy...

### Environment

Browser: Lacros-chrome 111
Scratch Addons version: v1.30.0
Operating system: ChromeOS

**Comment by TylerMS887** [comment]
This is actually a ChromeOS bug as removing the extension and reinstalling it restored functionallity. I'll report the issue to Google.

**Comment by Samq64** [comment]
I don't see anything wrong with the video and if you're using an experimental version of Chrome I would say this is invalid.
