### ISSUE TITLE
Auto-follow forum topics

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5626]
### Why this would be helpful

Some people always want to be notified when they participate in a forum topic.

### How this addon works

This addon would automatically subscribe you to a topic when you post on it.

**Comment by WorldLanguages** [comment]
Simple idea and useful 👍

**Comment by Chiroyce1** [comment]
Nice idea, I probably could work on this but I'm not really sure about the best way to check if the user has posted on a topic. Any ideas?

**Comment by DNin01** [comment]
> Nice idea, I probably could work on this but I'm not really sure about the best way to check if the user has posted on a topic. Any ideas?

Would it be possible to detect when the Submit button was pressed followed by the website redirecting to the post the user just made?

**Comment by WorldLanguages** [comment]
> Nice idea, I probably could work on this but I'm not really sure about the best way to check if the user has posted on a topic. Any ideas?

@Chiroyce1 Are you looking into following a topic where the user _has just posted_, or all past forum posts where the user has posted over the years? I don't think we should be looking into the latter.

Regarding the first, I'd say we listen to the "submit" post button onclick, and save the topic ID to sessionStorage. After the page reloads, check if there's a session storage entry. If it exists, and it matches the topic ID in the current URL, click the follow button (or do it invisibly with AJAX/fetch, both will work)  and delete the sessionStorage entry.

**Comment by WorldLanguages** [comment]
The [Official [scratchblocks] Testing Topic](https://scratch.mit.edu/discuss/topic/625814/) can be useful to test this without actually spamming the forums. If you know of any other topics, let us know

**Comment by BroJac5246** [comment]
> The [Official [scratchblocks] Testing Topic](https://scratch.mit.edu/discuss/topic/625814/) can be useful to test this without actually spamming the forums. If you know of any other topics, let us know

You could also unfollow a topic you want to post in, then post to test this addon.

**Comment by Chiroyce1** [comment]
@WorldLanguages Yep, we don't need to take care of the latter, pretty sure this is needed just for newer topics a user posts on. Nice idea for the implementation, and I say we click the button itself, since the user can see that the topic has been followed (and then unfollow if they want to) and there is also a loading spinner indicating that a request has been made.

**Comment by WorldLanguages** [comment]
> I say we click the button itself, since the user can see that the topic has been followed (and then unfollow if they want to) and there is also a loading spinner indicating that a request has been made.

Agreed!
