### ISSUE TITLE
Two make list buttons [Data category tweaks]

### ISSUE THREAD

**Issue by scratchusernamemrtbts** [ScratchAddons/ScratchAddons#564]
**Describe the bug**
there are two make list button

**To Reproduce**

0. make sure you enable separate list
1. Go to 'any project'
2. Click on 'variable'
3. See error

**Expected behavior**
only one make list button

**Screenshots**
<img width="307" alt="ภาพถ่ายหน้าจอ 2563-10-25 เวลา 14 50 43" src="https://user-images.githubusercontent.com/66320961/97101633-abb9f980-16d1-11eb-95b0-3c92f5fd0a5f.png">

**Device (please complete the following information):**

- OS: [macOS Big Sur 11.0 beta 10]
- Browser [firefox]
- Version [81.0.2 (64bit)]

**Additional context**
some times it have two but sometimes it's normal

**Comment by Explosion-Scratch** [comment]
That's really wierd.

**Comment by Explosion-Scratch** [comment]
Do both list buttons work?

**Comment by ZenithRogue** [comment]
It seems to be an issue with the `data category tweaks` addon

**Comment by WorldLanguages** [comment]
Yeah, keep in mind this addon is going to be removed as of v1.2.0

**Comment by ZenithRogue** [comment]
Wait, why?

**Comment by GrahamSH-LLK** [comment]
Because it's super buggy. It's all over the bugs & glitches forums.

**Comment by Explosion-Scratch** [comment]
Closed because this is removed.

**Comment by Explosion-Scratch** [comment]
I think it's a good idea to reopen if data category tweaks ever gets re-added.

**Comment by Mr-Anonymous75** [comment]
> I think it's a good idea to reopen if data category tweaks ever gets re-added.

It has been re-added now, but I can't reproduce this bug...

**Comment by GrahamSH-LLK** [comment]
> > I think it's a good idea to reopen if data category tweaks ever gets re-added.
> 
> It has been re-added now, but I can't reproduce this bug...

Because the code is entirely different
