### ISSUE TITLE
Collapsing Sprite Properties Bug

### ISSUE THREAD

**Issue by Unkrown6YT** [ScratchAddons/ScratchAddons#5658]
### Description

Collapsing Sprite Properties would hide expanding sprite properties icon

### Steps to reproduce

1. Enable `sprite-properties`
2. Collapse the sprite properties
3. and the expand sprite properties icon was gone

### Demonstration(s) and additional context

https://user-images.githubusercontent.com/94491221/213925929-5d087583-9e4f-441b-a22f-e8be72ff4f0b.mp4

### Environment

Browser: Opera GX
Scratch Addons version: 1.30.1
Operating system: Windows 11

**Comment by CubesterYT** [comment]
Can verify, I have the problem, too. I had come to GitHub to report the same issue when I saw this. I can't figure out why this is happening. Still occurs with drag and drop off as well.
