### ISSUE TITLE
Update `dark-www` to adapt to the upcoming love and favorite icons

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5680]
### Description

https://github.com/LLK/scratch-www/pull/7264 just got merged yesterday and replaces the gray love and favorite icons with outlined love and favorite icons to help colorblind people distinguish their active and inactive states apart, but when using `dark-www`, it looks weird.

![Love and favorite icons on a dark background, adjusted by Scratch Addons.](https://user-images.githubusercontent.com/106490990/215907494-d7e3d23a-7bd3-4141-8974-830b1e921c52.png)

The favorite icon is outlined as expected, but the love icon looks gray without an outline. This is happening because the love icon had an opaque fill color. The favorite icon has a transparent fill color, so it's not affected/looks fine.

We'll have to modify our addon to fix this, hopefully sometime soon after the icons change.

### Steps to reproduce

1. The new outlined icons haven't been released to the Scratch website yet, but you can insert them by modifying the background image in the page's CSS with browser developer tools.
2. Open any project page.

### Environment

Browser: Edge 109
Scratch Addons version: v1.30.1 (from Chrome Web Store)
Operating system: Windows 10

**Comment by DNin01** [comment]
Could we maybe pin this issue until we release the fix so people coming to report this exact bug can find out what's going on?

**Comment by DNin01** [comment]
Should probably ask @WorldLanguages that question

**Comment by WorldLanguages** [comment]
> Could we maybe pin this issue until we release the fix so people coming to report this exact bug can find out what's going on?

Did anyone report this yet? If so, sure. If not, wait until someone does.
