### ISSUE TITLE
disable sprite drag in editor addon

### ISSUE THREAD

**Issue by jeffalo** [ScratchAddons/ScratchAddons#569]
**Describe the new addon**

adds a button which toggles the ability to drag the sprites in the editor.

**Link to the new addon**

im going to try making this

**Comment by Explosion-Scratch** [comment]
That'd be cool!

**Comment by Explosion-Scratch** [comment]
I hat that feature sometimes.

**Comment by Cool-Scratcher** [comment]
This is a great idea! I'd love to see this in action. Maybe a button next to the green flag?
