### ISSUE TITLE
`message-filters` spams requests

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5697]
### Description

When `message-filters` is enabled, requests to fetch messages are quickly and repeatedly being sent. They stop after a second, but there are a lot of repetitive requests, which is unnecessary. The addon should only send the same request once and wait until it's done before sending more.

### Steps to reproduce

1. Enable `message-filters`
2. Have your browser's developer tools open and recording network activity
3. Open the messages page
4. Check the network activity. You'll see a lot of duplicate requests.

### Demonstration(s) and additional context

![The network tab in DevTools with a bunch of "messages?limit=40&offset=40 or 80" requests](https://user-images.githubusercontent.com/106490990/216849009-01066389-7df1-4154-aa2b-bf3a274aeb17.png)

### Environment

Browser: Edge 109
Scratch Addons version: v1.30.0-pre and v1.30.1
Operating system: Windows 10

**Comment by WorldLanguages** [comment]
The addon doesn't fetch directly. It's likely that the root cause is that the addon is calling `.click()` on the load more button too quickly.
