### ISSUE TITLE
The style of username links is inconsistent on the Messages page with `dark-www` enabled

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5709]
### Description

**Expected behavior:** All usernames on the Messages page should only turn blue when you're hovering over them, like vanilla Scratch.

**Actual behavior:** With `dark-www` enabled, usernames for user profiles you have visited will be highlighted blue always, and others will only be white and highlighted blue while you're hovering over them.

### Steps to reproduce

1. Enable the Website dark mode and customizable colors addon. You can use any theme.
2. Open your messages page.
3. Check various usernames in your messages. Notice how some usernames are colored blue when they shouldn't be.

### Demonstration(s) and additional context

![Screenshot of Messages page in dark mode](https://user-images.githubusercontent.com/106490990/217672906-5fe2a8ef-1512-4db7-9189-0b76ddec8c14.png)

### Environment

Browser: Edge 109
Scratch Addons version: 1.30.2 and 1.30.0-pre
Operating system: Windows 10

**Comment by mxmou** [comment]
The blue ones are probably visited links, which means this is a specificity issue.

**Comment by fractioneater** [comment]
> The blue ones are probably visited links, which means this is a specificity issue.

Should we just ignore visited links to guarantee consistency?
