### ISSUE TITLE
Remember Collapsed Forum Categories

### ISSUE THREAD

**Issue by Steve0Greatness** [ScratchAddons/ScratchAddons#5710]
### Why this would be helpful

Collapsing categories is pretty useless. It doesn't automatically collapse previously closed categories(in other words, remembering the categories you've collapsed in the past).

### How this addon works

Scratch already saves a cookie when you collapse a category. When it's been collapsed the cookie's value is `collapsed`, otherwise it's just empty. The name of the cookie uses the category's number proceeded by `category_body_`.

`.box-content` needs an inline `display` of `none`, and `#category_head_`(followed up by the category's number) needs a class of `collapsed`.'

_I have actually made a working version of this, though it's very basic [Steve0Greatness/ScratchAddons:rememeber-collapsed-categories](https://github.com/Steve0Greatness/ScratchAddons/tree/rememeber-collapsed-categories)_

**Comment by WorldLanguages** [comment]
I guess the cookie is not HTTP-only? Assuming it's not, then it can be accessed through `document.cookie`

**Comment by Steve0Greatness** [comment]
I don't think you can set HTTP only cookie via Client-Side JS(which I think it's set through). I'm probably wrong though.

It isn't HTTP-only, so it can be accessed using `document.cookie`.

**Comment by Steve0Greatness** [comment]
Should I create a PR? There doesn't appear to be much to discuss here.

**Comment by BroJac5246** [comment]
> Should I create a PR? There doesn't appear to be much to discuss here.

Sure, I don't see why not. The worst that could happen is we decide not to add it, which is unlikely.
