### ISSUE TITLE
Release notes are hard to find

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#572]
The release notes that accompany new releases of Scratch Addons are only available in the GitHub repository, and not everyone is aware of this. I haven't found them in the release notes section of my Firefox version, nor are they anywhere on the website or in the extension itself.
You guys should consider putting them in a more visible location. It's nice for a user to see what's new (especially if the update is minor) but more importantly, if a major change is made (for example, the data category tweaks extension being removed) users know that it's intentional and not a bug or glitch.

(RIP data category tweaks extension)

**Comment by Hans5958** [comment]
1.2.0 changelog is not ready yet. Also there will be a hotfix that will be released on 1.2.1.

**Comment by Hans5958** [comment]
Related, #463.

@WorldLanguages, start putting the releases link [here](https://addons.mozilla.org/en-US/firefox/addon/scratch-messaging-extension/versions/) you stopid

**Comment by Explosion-Scratch** [comment]
We're currently working on the release notes, we're trying to decide on a
bunch of different places to put them lol

**Comment by GrahamSH-LLK** [comment]
The changelog will be at scratchaddons.com/changelog and possibly in a changelog.md

**Comment by GrahamSH-LLK** [comment]
The changelog at https://scratchaddons.com/changelog is linked to within the addon.
