### ISSUE TITLE
Twemoji option in better emojis

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#5735]
### Why this would be helpful

Twemoji is the superior emoji font

### My suggestion

Add an option to better-emojis to convert unicode emojis to twemoji

### Possible alternatives

Not have an option

**Comment by WorldLanguages** [comment]
> convert unicode emojis to twemoji

General purpose extensions can already do this for all websites - nothing Scratch specific about that feature.
This suggestion would only make sense if we converted Scratch emojis to twemoji.

**Comment by Secret-chest** [comment]
> Twemoji is the superior emoji font

Blobmoji is the superior emoji font

**Comment by WorldLanguages** [comment]
Closing.

If someone is interested, here's an idea that would make some sense (feel free to create a different issue): creating an addon that converts Scratch emoji (`_meow_`, `_:P_`, etc.) to Unicode emojis. Then the user could use any general-purpose extension to convert those to twemoji, or any other emoji flavor. Or the user may choose to keep them as Unicode, for example Mac users don't need an extension to get Apple emojis.
