### ISSUE TITLE
New userscript docs available on the website

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#5764]
There's 3 new pages available on the docs:

- About userscripts: https://scratchaddons.com/docs/develop/userscripts/
- Userscript Best Practices: https://scratchaddons.com/docs/develop/userscripts/best-practices/
- Userscript Debugging Tips: https://scratchaddons.com/docs/develop/userscripts/debugging-userscripts/

This are userscript docs, not addon.* API docs (they are separate). Any feedback is welcome. We hope to document the most common edge cases, implicit best practices, and basically anything that's good to now for both new and old contributors.
The userstyle docs will be remade to follow this pattern as well soon.

**Comment by WorldLanguages** [comment]
Self-feedback: 

Would be nice to add a best-practice: avoid `x.parentElement.parentElement` in favor of `x.closest(selector)`.

**Comment by Samq64** [comment]
I like how the the examples try to use code snippets from real addons, but wouldn't an addon that only has a userscript be a better option than using `scratch-messaging` for the example manifest?

**Comment by WorldLanguages** [comment]
@Samq64 I agree - I think Scratch Messaging is mentioned there just for historical reasons.

**Comment by WorldLanguages** [comment]
@Samq64 See https://github.com/ScratchAddons/website-v2/pull/310
