### ISSUE TITLE
forum-id: autoadded IDs no longer are small and in parentheses

### ISSUE THREAD

**Issue by CST1229** [ScratchAddons/ScratchAddons#5766]
### Description

(Unsure if this is a regression or an intentional thing.)

Probably before #5240 was merged, "Quote post number"'s auto-added IDs looked like this, in [small] tags and (parentheses):
![](https://user-images.githubusercontent.com/68464103/222503258-7ae8b421-be90-491f-9bb9-a417f2ab72b3.png)
![](https://user-images.githubusercontent.com/68464103/222503289-1ee4fa55-da31-40a6-9c5d-208a0b259583.png)

In master, they now look like this, exactly the same as when manually pressing the Quote post number button:
![](https://user-images.githubusercontent.com/68464103/222503447-0a7ff258-939e-4f32-a14b-712ec7c431d7.png)
![](https://user-images.githubusercontent.com/68464103/222503478-56942a07-56cb-4285-9513-141aa1dc1f78.png)

### Steps to reproduce

1. Enable Quote post number and its "Automatically add post link to quotes" setting
2. Quote a post on the forums
3. Notice the text is normal-size and not in parentheses

### Demonstration(s) and additional context

(see the images in the description)

### Environment

Browser: Firefox 111.0b7
Scratch Addons version: Pre-regression: v1.30.2, post-regression: 9558611e16e0b3e30fde7cdbf2964aa7979585e7
Operating system: Windows 10

**Comment by pufferfish101007** [comment]
Ah whoops :open_mouth:
Yes, this is a regression.
