### ISSUE TITLE
Quote post number addon: Link still appears even when topic is closed.

### ISSUE THREAD

**Issue by TylerMS887** [ScratchAddons/ScratchAddons#5795]
### Description

The quote post number addon still appears even when the topic is closed. This is unexpected because it's doing nothing.

### Steps to reproduce

1. Open a closed topic e.g. https://scratch.mit.edu/discuss/topic/426181/
2. Click "Quote post number"
3. The link will do nothing

### Demonstration(s) and additional context

![image](https://user-images.githubusercontent.com/115214762/224541139-c13c3c99-5752-4658-9a6b-2793d0e68ef8.png)

### Environment

Browser: Edge 110.0.1587.63
Scratch Addons version: 1.30.2 (I'm not getting updated to 1.31)
Operating system: Windows 11

**Comment by BroJac5246** [comment]
> Thanks for reminding me, the browser is not sending me the update to the new version (but I have a new browser update and will preform it now).

It looks like the Edge add-on hasn't been updated/approved yet. Hold tight until it reaches the Edge Add-ons store.

**Comment by TylerMS887** [comment]
> > Thanks for reminding me, the browser is not sending me the update to the new version (but I have a new browser update and will preform it now).
> 
> It looks like the Edge add-on hasn't been updated/approved yet. Hold tight until it reaches the Edge Add-ons store.

It's been days and it still hasn't arrived yet.

Maybe we didn't yet submit it to Microsoft?

**Comment by BroJac5246** [comment]
> > > Thanks for reminding me, the browser is not sending me the update to the new version (but I have a new browser update and will preform it now).
> > 
> > It looks like the Edge add-on hasn't been updated/approved yet. Hold tight until it reaches the Edge Add-ons store.
> 
> It's been days and it still hasn't arrived yet.
> 
> Maybe we didn't yet submit it to Microsoft?

@WorldLanguages it's been two weeks; are we sure it was sent for review to the Edge Add-ons store?

**Comment by WorldLanguages** [comment]
@TylerMS887 @BroJac5246 Thanks for the heads up, I'll check what happened and make sure Edge gets up to date as soon as possible
