### ISSUE TITLE
Missing arrows in menus

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#5803]
### Description

I noticed now that there are no more arrows in the block menus. I don't know what caused this.

I'm attaching my json settings file
[scratch-addons-settings 2023 03 15.json.zip](https://github.com/ScratchAddons/ScratchAddons/files/10984704/scratch-addons-settings.2023.03.15.json.zip)
 

### Steps to reproduce

1. load attached settings file
2. click "create" on Scratch website
3. look for blocks with menus

### Demonstration(s) and additional context

Just to give an example

<img width="181" alt="image" src="https://user-images.githubusercontent.com/2651868/225449100-6ffad871-cb5a-487e-99aa-1c7d2f064e75.png">

### Environment

Browser: Chrome 111.0.5563.64 (x86_64)
Scratch Addons version: 1.31.0
Operating system: macOS Big Sur

**Comment by DNin01** [comment]
Can reproduce on Edge 110 with `editor-theme3` enabled in Scratch Addons 1.31.0 stable. It happens when text color is set to anything other than white.

**Comment by DNin01** [comment]
Can also reproduce on TurboWarp.

I somehow wonder if this has to do with a browser or a Scratch update?

**Comment by BroJac5246** [comment]
What browser are you using, @sfederici?

**Comment by DNin01** [comment]
Seems to be caused by this CSS:
```
filter: url(data:image/svg+xml, <svg xmlns='http://www.w3.org/2000/svg'> <filter id='recolor'> <feColorMatrix color-interpolation-filters='sRGB' values=' 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 '/> </filter> </svg>#recolor);
```

**Comment by DNin01** [comment]
> What browser are you using, @sfederici?

Looks like some version of Chrome or a Chromium-based browser.

**Comment by sfederici** [comment]
> What browser are you using, @sfederici?

Chrome

**Comment by DNin01** [comment]
We'll probably need to adjust this code:
https://github.com/ScratchAddons/ScratchAddons/blob/5dc17a98acf953d565ef771da5bcf84f41748ae7/libraries/common/cs/text-color.js#L133

**Comment by WorldLanguages** [comment]
This was also reported in the Discord server

**Comment by WorldLanguages** [comment]
This is supposedely not a v1.31.0 regression, but caused by a Chromium update.
Scratch Addons v1.31.1 will ship a workaround fix.

**Comment by mxmou** [comment]
> This is supposedely not a v1.31.0 regression, but caused by a Chromium update. **Edit: actually a combination of both I think.**

v1.30.2 also has this bug in the latest version of Edge.
