### ISSUE TITLE
🔴 April Fools: Discussing our own easter egg

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#5807]
2021: Dango rain (#1931)
2022: Scratch Avocados (#4436)
2023: (?) Hopefully dangos again? We love dangos!

\
Some suggestions found on the Discord server from various authors:
- Merging #3991 
- Hide little dancing pixel Scratch cats in various places on the settings page, popup, Scratch website, etc. And locally track how many the user has found and clicked on
- "Featured Dangos" row in front page. We could feature multiple dango related projects that already exist, from various Scratchers.
- Replace the pause button icon with the dango icon. I don't think it would be fine to replace some native Scratch elements, but we can do it with our own.

**Comment by MaterArc** [comment]
I had an idea for an easter egg actually, what if SA made it so that when you click the magnifying glass it zoom in on the scratch page.
So when you click magnifying glass:
<img width="198" alt="Screen Shot 2023-03-16 at 2 46 22 PM" src="https://user-images.githubusercontent.com/105017592/225722507-63112663-6a07-4a3f-8a80-024d779da60c.png">

There will be a zoom animation that will show the scratch page zoomed in. 
<img width="1327" alt="Screen Shot 2023-03-16 at 2 47 20 PM" src="https://user-images.githubusercontent.com/105017592/225722742-ee3356c4-88b2-491b-bed6-6ad3e71ae73b.png">


Just an idea, and there are many ideas that can be done with the magnifying glass and other buttons, etc. Hope you like the idea :)

**Comment by MaterArc** [comment]
> I had an idea for an easter egg actually, what if SA made it so that when you click the magnifying glass it zoom in on the scratch page. So when you click magnifying glass: <img alt="Screen Shot 2023-03-16 at 2 46 22 PM" width="198" src="https://user-images.githubusercontent.com/105017592/225722507-63112663-6a07-4a3f-8a80-024d779da60c.png">
> 
> There will be a zoom animation that will show the scratch page zoomed in. <img alt="Screen Shot 2023-03-16 at 2 47 20 PM" width="1327" src="https://user-images.githubusercontent.com/105017592/225722742-ee3356c4-88b2-491b-bed6-6ad3e71ae73b.png">
> 
> Just an idea, and there are many ideas that can be done with the magnifying glass and other buttons, etc. Hope you like the idea :)

Also, on top of this, the user could zoom back out by 1) clicking the magnifying glass again or 2) by reloading the page

**Comment by WorldLanguages** [comment]
@MaterArc I'm not sure how we could achieve that zoom effect.
Also, our April Fools easter eggs are usually not that hidden. We expect a big portion of our users to notice it. I'm not sure how many users would click the magnifying glass.

**Comment by MaterArc** [comment]
> @MaterArc I'm not sure how we could achieve that zoom effect. Also, our April Fools easter eggs are usually not that hidden. We expect a big portion of our users to notice it. I'm not sure how many users would click the magnifying glass.


I see. I have another idea, maybe for the navbar you could switch the buttons around since people are used to the layout and when people try to click one, they will go to another page (this could be done throughout the website to make it really confusing lol): <img width="934" alt="Screen Shot 2023-03-16 at 4 06 15 PM" src="https://user-images.githubusercontent.com/105017592/225740400-790cd896-9994-4594-b9d7-445728c88b47.png">

**Comment by MaterArc** [comment]
Like you could switch the explore page with the create or something like that. @WorldLanguages How does that sound?

**Comment by DNin01** [comment]
It's also a good idea to make sure that any April Fools features don't look like they're part of Scratch and make sure people know that Scratch Addons is doing it.

**Comment by DNin01** [comment]
We could hide a Dango somewhere in the settings page that when clicked would enable an addon related to Dango.

**Comment by MaterArc** [comment]
> ###
> **[DNin01](/DNin01) ** commented [Mar 16, 2023](#issuecomment-1472776991)

I like that idea. Maybe when you click the dangos all new projects that you make from then on start with the sprite dango instead of scratch cat 🍡

**Comment by MaterArc** [comment]
> > > **[DNin01](/DNin01) ** commented [Mar 16, 2023](#issuecomment-1472776991)
> > 
> > 
> > I like that idea. Maybe when you click the dangos all new projects that you make from then on start with the sprite dango instead of scratch cat 🍡
> 
> Each project would have to give credit to the Dango design we use, though.

True

**Comment by BroJac5246** [comment]
> > > **[DNin01](/DNin01) ** commented [Mar 16, 2023](#issuecomment-1472776991)
> > 
> > 
> > I like that idea. Maybe when you click the dangos all new projects that you make from then on start with the sprite dango instead of scratch cat 🍡
> 
> Each project would have to give credit to the Dango design we use, though.

We could make our own and release it to the public domain.

**Comment by BroJac5246** [comment]
> maybe
>  make the account "kaj_admin" in mirror-image- "nimad_like" is not in the forbidden scratch account names

What are you saying?

**Comment by CyberNat2000** [comment]
> > maybe
> > make the account "kaj_admin" in mirror-image- "nimad_like" is not in the forbidden scratch account names
> 
> What are you saying?

mirror image:
 kaj_admin=nimda_jak
 sorry, but I didn't notice that during the translation I accidentally put that word in too and it translated "jak" to "like" for me

**Comment by BroJac5246** [comment]
On the forums, all posts (or maybe just those that have been edited) should say "Last edited by kaj, Tomorrow, 27:43," or something like that. I was inspired by a trick that some Scratchers (including myself) do in their signature.

**Comment by WorldLanguages** [comment]
> Like you could switch the explore page with the create or something like that. @WorldLanguages How does that sound?

Annoying.

**Comment by WorldLanguages** [comment]
> Maybe when you click the dangos all new projects that you make from then on start with the sprite dango instead of scratch cat

I don't think we should apply easter eggs to the editor. It's easy to mess up and cause crashes, and projects would be affected by our easter egg even after April Fools ends.

**Comment by WorldLanguages** [comment]
> On the forums, all posts (or maybe just those that have been edited) should say "Last edited by kaj, Tomorrow, 27:43," or something like that. I was inspired by a trick that some Scratchers (including myself) do in their signature.

Idea is reasonable - we would probably need to add a notice if the user hovers the text we added.

**Comment by WorldLanguages** [comment]
From my original post:

> * "Featured Dangos" row in front page. We could feature multiple dango related projects that already exist, from various Scratchers.

Any reasons not to do this instead? It's simple to make, and a big portion of users would notice it. It brings back the dango meme, and it highlights an interesting part of Japanese food culture. Scratch Addons has a considerable amount of Japanese users. This approach also takes advantage of existing projects, most of which have less than 50 views.

These are some projects that we could feature:
1. https://scratch.mit.edu/projects/683954771/
2. https://scratch.mit.edu/projects/297794351/
3. https://scratch.mit.edu/projects/501005426/
4. https://scratch.mit.edu/projects/538669082/
5. https://scratch.mit.edu/projects/533742531/
6. https://scratch.mit.edu/projects/754385820/
7. https://scratch.mit.edu/projects/619174229/

**Comment by CST1229** [comment]
> These are some projects that we could feature:

The TurboWarp default project, too /hj

**Comment by WorldLanguages** [comment]
See #5831 for the partial implementation of the Featured Dangos row.
We're still open to other ideas, though.

**Comment by WorldLanguages** [comment]
#5831 is close to being merged. Please check it out if you're interested.
