### ISSUE TITLE
Middle-click popup appears in corner

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#5808]
> With your settings, the first time I open the menu after opening the editor it appears in the top-left corner which is bug, but it's still styled and I can't scroll the page like you showed. I got the same result on both Firefox and Chromium.

_Originally posted by @Samq64 in https://github.com/ScratchAddons/ScratchAddons/issues/5787#issuecomment-1456922369_

**Steps to reproduce**
1. Enable `middle-click-popup`
2. Open the editor
3. Middle click. Notice how the popup appears in the top-left corner of the editor.
5. Open the menu again. Notice it appears near the cursor like it's supposed to.

**Comment by CST1229** [comment]
This only happens if you don't move your cursor (after the addon loads) before middle-clicking.

**Comment by WorldLanguages** [comment]
Technically a regression

**Comment by Tacodiva** [comment]
This is a very minor bug but I'll fix it up :)

**Comment by Tacodiva** [comment]
I have fixed this for middle click, but I don't think this is fixable for ctrl + space. According to [this](https://stackoverflow.com/a/7562566/8448397) SO answer, it's impossible to get the mouse position inside a keyboard event, so if this mouse hasn't moved yet there's no way of knowing where the mouse is.

**Comment by CST1229** [comment]
> 

Maybe make it appear near the top left of the workspace viewport by default.

**Comment by WorldLanguages** [comment]
> if this mouse hasn't moved yet there's no way of knowing where the mouse is

Interesting! I agree with CST, we could change the default
