### ISSUE TITLE
Fullscreen Header too dark

### ISSUE THREAD

**Issue by MasimbaTheHuman** [ScratchAddons/ScratchAddons#582]
When entering fullscreen, the area containing the green flag and stop sign will become dark if dark mode is enabled.

I expected for it to be light.

![Screenshot (1)](https://user-images.githubusercontent.com/64666021/97461266-d6d36180-18fa-11eb-8986-45de1525d239.png)

**Device (please complete the following information):**

- OS: [Windows 10]
- Browser [Chrome]
- Version [1.1.1]

**Comment by WorldLanguages** [comment]
Yeah, we should be consistent - everything should be dark (currently the background is white), or everything should be white.

**Comment by Explosion-Scratch** [comment]
It's be nice to just restyle the whole background when editor dark mode is
on.

**Comment by Explosion-Scratch** [comment]
*It'd
