### ISSUE TITLE
hide-flyout default to "open palette" 

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#5821]
### Why this would be helpful

I'm using a lot the hide-flyout addon. It works really well and it is extremely useful. As my students usually move from basic-Scratch to ScratchAddons they are surprised for not seeing the block palette (they are using a version preinstalled in the lab with all the necessary addons already enabled). 

### My suggestion

Change (or select by option) default for hide-flyout addon to palette open, instead of closed. Store the palette status -closed/open- in the browser, otherwise closing the palette every time could be annoying.

### Possible alternatives

None

**Comment by WorldLanguages** [comment]
This new feature would need to be a setting. The palette is hidden by default by design, as seen in old pull requests. So if this is implemented, you'd need to enable a setting,

**Comment by WorldLanguages** [comment]
> Store the palette status -closed/open- in the browser, otherwise closing the palette every time could be annoying.

@sfederici Could you clarify what you meant here?

**Comment by sfederici** [comment]
> @sfederici Could you clarify what you meant here?

Sure. If I close the palette, that means that I acknowledged that it can be closed. So, next time I open Scratch, it is reasonable that the palette is closed. Storing the palette status (closed/open) in the browser it would be to me a good addition to the addon.

**Comment by WorldLanguages** [comment]
@sfederici Hmm, I see what you mean. However, this will be added as a setting, so storing whether the user closed the palette at least once wouldn't make much sense, since the user can simply toggle the setting again.

**Comment by sfederici** [comment]
ok
