### ISSUE TITLE
A scrollbar appears when opening the middle click popup near the bottom of the window

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#5824]
### Description

When opening the middle click popup near the bottom of the browser window, the popup is cut off and the page becomes scrollable.

I would expect the popup to open above the mouse cursor instead.

### Steps to reproduce

1. Enable the "insert blocks by name" addon.
2. Open the editor.
3. Move your mouse near the bottom of the code area and open the popup (by middle-clicking or using a keyboard shortcut).

### Demonstration(s) and additional context

![image](https://user-images.githubusercontent.com/51849865/226178451-23749769-3d0f-428b-be51-acb693448519.png)

This bug existed before v1.31.

### Environment

Browser: Edge 112 dev
Scratch Addons version: e700f22
Operating system: Windows

**Comment by WorldLanguages** [comment]
cc @Tacodiva

**Comment by mxmou** [comment]
Why 1.31.1? This isn't a regression.

**Comment by WorldLanguages** [comment]
I was thinking tacodiva would consider fixing this within #5791 which has the v1.31.1 milestone
But you're right, they haven't confirmed whether they plan to fix this yet

**Comment by Tacodiva** [comment]
If I get around to fixing this I will but for now it's probably the lowest priority thing on my list
