### ISSUE TITLE
"Show exact count" doesn't handle empty sections on profile page

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#583]
**Describe the bug**

When the "Exact Counts for Profiles" checkbox is selected while the "Show exact count" addon is enabled, the addon does not notice that sections of the profile that are empty are hidden, causing overflow into other sections.

**To Reproduce**

1. Go to the Scratch Addons settings and enable the "Show exact count" addon (also make sure that the Exact Counts for Profiles checkbox is selected.)
2. Open the profile of any Scratch user for whom at least one of the following is true:
   - The user is not following any studios
   - The user is not a member of any studios
   - The user is not following anyone
   - The user has no followers

(For ease of reproduction, go to [CloudHost's profile](https://scratch.mit.edu/users/CloudHost).)

**Expected behavior**

The addon should account for empty sections of the profile -- in other words, when those values are 0.

**Screenshots**

![image](https://user-images.githubusercontent.com/43426138/97476642-a56b8d80-191c-11eb-8891-3bb804471baf.png)

**Device:**

- OS: Windows 10
- Browser: Chrome 86

**Comment by TheColaber** [comment]
Yeah, I forgot about that... CloudHost's profile is deleted. Can you find a different profile like that so I can try to fix it?

**Comment by WorldLanguages** [comment]
@TheColaber gdpr0000001

**Comment by TheColaber** [comment]
K, I'll fix this soon.
