### ISSUE TITLE
Boolean variable 

### ISSUE THREAD

**Issue by StioStudio** [ScratchAddons/ScratchAddons#5833]
### Why this would be helpful

All the info is allready on this suggestsion on discord: https://discord.com/channels/806602307750985799/1085879265846890596
I just thought I could ask if this would have been accepted if I made it

### How this addon works

When you have a ? in the end of a variable it looks like a boolean.
(If possible) make it so if you place it in a boolean place, it is <var? = 1> so that you can use it in stuff like if <> then

**Comment by BroJac5246** [comment]
And for regular Scratch users, it would be a regular variable in a "<_varName?_ = true>" block?

**Comment by StioStudio** [comment]
> And for regular Scratch users, it would be a regular variable in a "<_varName?_ = true>" block?

Yes, that was the idea

**Comment by WorldLanguages** [comment]
> All the info is allready on this suggestsion on discord: https://discord.com/channels/806602307750985799/1085879265846890596

You should repost all relevant messages here.

This is one of them which I think explains your suggestion well:
![image](https://user-images.githubusercontent.com/17484114/226489431-9a9342a1-6523-4966-8357-a74dd79e24c2.png)

**Comment by WorldLanguages** [comment]
If I remember correctly, we've had a few suggestions like this, but no addon exists yet that can show a different set of blocks instead of the actual ones stored in the project JSON. It's not simple.

**Comment by StioStudio** [comment]
I was thinking that if I could not do that, it would just look like <var?=1> but it happens automatically when you drag it out

**Comment by StioStudio** [comment]
But if I somehow make it. Would it be accepted?

**Comment by StioStudio** [comment]
> > I was thinking that if I could not do that, it would just look like <var?=1> but it happens automatically when you drag it out
> 
> No idea what you meant here.
Like this:
Drag the boolean variable out. The variable: var?
When you drag it out it looks like<var?=1>
Then you can place it anywhere

**Comment by WorldLanguages** [comment]
> When you drag it out it looks like<var?=1>

What if you didn't want the "equals one" part and just wanted to drag and drop the variable itself (for example say<variable>)

**Comment by StioStudio** [comment]
> > When you drag it out it looks like<var?=1>
> 
> What if you didn't want the "equals one" part and just wanted to drag and drop the variable itself (for example say)
Of course can you just take variabel out of the <=> but that can be annoyinng so maybe it is two ways to get the variable. One for normal and one for boolean

**Comment by mxmou** [comment]
> > When you drag it out it looks like<var?=1>
> 
> What if you didn't want the "equals one" part and just wanted to drag and drop the variable itself (for example say)

Why would you want to do that? "say <(var?) = (1)>" works too.

**Comment by StioStudio** [comment]
> > > When you drag it out it looks like<var?=1>
> > 
> > 
> > What if you didn't want the "equals one" part and just wanted to drag and drop the variable itself (for example say)
> 
> Why would you want to do that? "say <(var?) = (1)>" works too.

I think he meant the raw block so you can use it elsewhere

**Comment by WorldLanguages** [comment]
> Why would you want to do that? "say <(var?) = (1)>" works too.

@mxmou Well, you're technically right, as long as you're editing a project that respects the expected use of the question mark at the end of variables.
