### ISSUE TITLE
Blocks

### ISSUE THREAD

**Issue by ScratchCat10090** [ScratchAddons/ScratchAddons#5837]
### Why this would be helpful

Add a block image

### My suggestion

But i dont have

### Possible alternatives

Add blocks to images

### Additional context

But making sounds

**Comment by ScratchCat10090** [comment]
Im first

**Comment by BroJac5246** [comment]
Please elaborate. We can't understand a four single sentences or sentence fragments that doesn't make grammatical sense.

**Comment by Samq64** [comment]
Does it have something to do with the [Save blocks as image](https://scratch.mit.edu/scratch-addons-extension/settings#addon-blocks2image) addon?

**Comment by Samq64** [comment]
Actually, I'm closing as invalid. If this is a c suggestion, please open a new issue and fill it in properly.
