### ISSUE TITLE
Move the share button

### ISSUE THREAD

**Issue by StioStudio** [ScratchAddons/ScratchAddons#5842]
### Why this would be helpful

Whould take away the orange banner that takes a lot of space and move the share button to a more reasonable place.

### How this addon works

The share button would be moved to the other button (see innside, remix, turbowarp) and the orange banner would go away (including the text). 

### Possible alternatives

Could be merged with my pr on compact buttons, but can't think of any other addon.

### Additional context

This addon would happen in "projects"

**Comment by WorldLanguages** [comment]
It's hard to tell whether this idea would be accepted. Surely not as a new addon, but I find it hard to imagine an addon where this could be added. I wouldn't expect a "compact buttons" addon to change the position of buttons.

**Comment by StioStudio** [comment]
> It's hard to tell whether this idea would be accepted. Surely not as a new addon, but I find it hard to imagine an addon where this could be added. I wouldn't expect a "compact buttons" addon to change the position of buttons.

The reason I have not made this is because I don't have time and don't know how. Btw is it not any button addon? It defently should be an addon where a lot of the button changes is.

**Comment by WorldLanguages** [comment]
> Btw is it not any button addon? It defently should be an addon where a lot of the button changes is.

Could you clarify?

**Comment by StioStudio** [comment]
> > Btw is it not any button addon? It defently should be an addon where a lot of the button changes is.
> 
> Could you clarify?

Oh sure (sorry for my bad english). I was thinking SA should add a "button addon" where all addons that "changes buttons" are

**Comment by iqnite** [comment]
Don't think that making a whole addon just to move a banner (come on guys it's 96 px high) is a good idea. Guess that we'll keep this suggestion until someone does a related addon for the project page.
