### ISSUE TITLE
Remix tree button doesn't work at all

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#585]
**Describe the bug**

The "remix tree button on project pages" does not send the user to the remix tree page.

**To Reproduce**

1. Go to the Scratch Addons settings and enable the "Remix tree button on project pages" addon.
2. Go to the project page of any project.
3. Try to use the Remix Tree button.

**Expected behavior**

When the Remix Tree button is present, clicking it should send the user to the remix tree page.

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Chrome 86, Firefox 82

**Comment by JeffaloBob** [comment]
remix tree button doesn't work at all

**Comment by lisa-wolfgang** [comment]
Oh yeah, you're right. I'll edit the report to reflect that.

**Comment by ZenithRogue** [comment]
I have a pr waiting to be merged to fix it #581

**Comment by WorldLanguages** [comment]
Solved by #581
