### ISSUE TITLE
auto disable addon

### ISSUE THREAD

**Issue by StioStudio** [ScratchAddons/ScratchAddons#5861]
### Why this would be helpful

Makes it so that addons does not need to be turned off manuly. I thought of this because april fools addons got turned off manuly.

### My suggestion

How it would (probably) will work:
```jsonc
"disable": {
   "date": [
       {
       "day": 1,
      "moth": 04,
      "year": false //if false/undifined it is always on
      },
      {
      "day": 13,
      "moth": 6,
      "year": 2024
   ]
}
```

### Possible alternatives

I don't know

### Additional context

404

**Comment by Samq64** [comment]
Duplicate of #5248.

**Comment by Samq64** [comment]
Although the implementation in your issue is pretty different, so I guess this could stay open.

**Comment by StioStudio** [comment]
This would do it automatically, so it is pretty different

**Comment by WorldLanguages** [comment]
Related: #5431
