### ISSUE TITLE
Auto-hiding block pallets doesnt work, doesnt hide and the lock doesnt show

### ISSUE THREAD

**Issue by fjjghcctjycycy** [ScratchAddons/ScratchAddons#5862]
### Description

normally the blocks would hide and would only show when i hover over them. but for some reason thats not happening. i still see the stage move an inch to the right and the block selector become transparent but thats about it. the thing im actually here for doesnt work

### Steps to reproduce

try the json, the bug happens the second the page is loaded with all those settings on 

### Demonstration(s) and additional context

https://gofile.io/d/7cs2Wc this is my json

### Environment

Browser: Chrome 111.0.5563.146
Scratch Addons version: 1.31.1
Operating system: Windows

**Comment by Samq64** [comment]
See #5860

**Comment by DNin01** [comment]
This feature has been temporarily disabled because it doesn't work properly with Scratch's April Fools features, at least that's what I'm assuming.

**Comment by fjjghcctjycycy** [comment]
oh i didnt know that. well ill just wait it out 👌

**Comment by Samq64** [comment]
Re-opeing until all the addons are working again.

**Comment by DNin01** [comment]
Might want to pin this, also?

**Comment by Samq64** [comment]
Sure. I didn't because the answer here isn't as clear as the discussion, but it's linked anyway.

**Comment by WorldLanguages** [comment]
As of now, these addons are intentionally disabled because Scratch continues to provide the "mode" menu that lets users switch to cat blocks. If the user switches, multiple problems can happen, including editor crash.

It's possible that these addons will continue to stay unfunctional even after Scratch removes the "mode" menu. At that point, it will be considered a bug. Depending on the way that Scratch removes the "mode" menu, we might need to patch it or not.

**Comment by fjjghcctjycycy** [comment]
the issue is fixed! the bar now shows and hides depending on the proximity of the mouse to it, and variables are separated depending on if they are for this sprite only or global.

as i see it, any issues caused by the april fools update seem to have gone away so i will close this. if anything still doesnt work, just make a new issue with that exact problem listed as needing to be fixed. no need to reopen.

**Comment by WorldLanguages** [comment]
This was resolved by #5873
