### ISSUE TITLE
Data category tweaks not working

### ISSUE THREAD

**Issue by clfisher** [ScratchAddons/ScratchAddons#5868]
### Description

This is a bug: the data category tweaks extension is not working. (It does not do anything)

I have had the same problem on other devices.
I do have it enabled, and I have done testing.
It seems to only be this extension that is not working, all other extensions are working completely fine.
I have tested it in chrome and edge, neither browser works.

Hope you can reproduce and get fixed soon!
Also, this is my first post, so sorry if I am doing this wrong.
Thanks!

### Steps to reproduce

1. Download scratch addons
2. Enable Data category tweaks addon
3. Open scratch and check to see if activated

### Environment

Tested on both Chrome and Edge on Windows.
Scratch addons version 1.31.1

**Comment by Samq64** [comment]
See #5860. It effect more than just cat blocks.

**Comment by clfisher** [comment]
Thank you!
