### ISSUE TITLE
Variables not being seperated w/ SEPARATE SPRITE-ONLY VARIABLES on.

### ISSUE THREAD

**Issue by derpygamer2142** [ScratchAddons/ScratchAddons#5875]
### Description

The "SEPARATE SPRITE-ONLY VARIABLES" sub-option under Data category tweaks does not currently do anything. The variables should be separated but they are not.

### Steps to reproduce

1. Enable "Data category tweaks"
2. Open a new scratch project
3. Create 2 variables, one all sprite and one sprite only
4. They are not seperated.

### Demonstration(s) and additional context

These two variables are different types(as shown by the "convert to..." thing), but they are not seperated:

![Platformer Shooter Thing 2 Chapter 1 copy copy on Scratch - Google Chrome 4_3_2023 2_52_56 PM](https://user-images.githubusercontent.com/93667155/229612536-a772ab30-2e4e-46f7-a532-002a4178602e.png)
![Platformer Shooter Thing 2 Chapter 1 copy copy on Scratch - Google Chrome 4_3_2023 2_53_09 PM](https://user-images.githubusercontent.com/93667155/229612543-244b796b-a264-4aff-a03e-2c696e62ee18.png)

### Environment

Browser: Chrome Version 111.0.5563.147 
Scratch Addons version: v1.31.1
Operating system: Windows 11

**Comment by CST1229** [comment]
Known issue, see #5862.
> As of now, these addons are intentionally disabled because Scratch continues to provide the "mode" menu that lets users switch to cat blocks. If the user switches, multiple problems can happen, including editor crash.
> 
> It's possible that these addons will continue to stay unfunctional even after Scratch removes the "mode" menu. At that point, it will be considered a bug. Depending on the way that Scratch removes the "mode" menu, we might need to patch it or not.
