### ISSUE TITLE
Remove (or keep) featured-dangos addon

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#5891]
### Why this would be helpful

April Fools has ended already. We need to decide what to do about the featured-dangos addon (#5831)

### My suggestion

Removing the featured-dangos addon completely.

### Possible alternatives

Keeping it as an easter egg which the user can toggle. If we do this, I suggest changing the addon id to `featured-dangos-v2` so that we can easily set `enabledByDefault: false` to the "new" addon.

### Additional context

See #5831 and #5807

**Comment by WorldLanguages** [comment]
Doing a quick poll:
**Upvote:** remove addon
**Downvote:** keep addon as an easter egg addon, just like dango-rain. If you choose this, please consider future maintenance of the addon, such as one of the featured projects being deleted.

**Comment by BroJac5246** [comment]
I don't think the addon has any realistic value after April Fools' Day, so it should be removed. It's not like cat blocks or dango rain; it's literally just an extra useless row on the home page.

**Comment by Samq64** [comment]
> I don't think the addon has any realistic value after April Fools' Day, so it should be removed. It's not like cat blocks or dango rain; it's literally just an extra useless row on the home page.

I guess. I think it should stay for historical reasons, but 1.30.1 could always just be downloaded form the releases page.

**Comment by DNin01** [comment]
It makes some sense to keep it because we kept Dango Rain, but then it is pretty useless if you're going to have it on all the time.

**Comment by BroJac5246** [comment]
> It makes some sense to keep it because we kept Dango Rain, but then it is pretty useless if you're going to have it on all the time.

This has even less of a use than Dango Rain. Dango Rain is a surprise, and it's a fun way to show that you use Scratch Addons. Featured Dangos, on the other hand, will just get boring and has no real purpose, not even an impractical one. Because of that, it should be removed. If someone wants it for historical purposes then they can download an old version of the extension.

**Comment by Secret-chest** [comment]
I'd like it removed as it just shows a few hardcoded projects.

**Comment by Samq64** [comment]
> I'd like it removed as it just shows a few hardcoded projects.

That's why it should've used a studio, but there's no point in doing that now.

**Comment by WorldLanguages** [comment]
Note that this studio (made by some random SA user) is preserving the 5 featured dango projects: https://scratch.mit.edu/studios/33036797/

**Comment by WorldLanguages** [comment]
Looks like no one that voted to keep the addon has justified their decision or provided any suggestions on how to maintain the addon in the future considering that the list of projects is hardcoded 🤔

**Comment by WorldLanguages** [comment]
@Hans5958 @CST1229 @ilikecereal1 Since you downvoted:

You could create a different PR that instead keeps the addon (following my tip, see below)

> I suggest changing the addon id to featured-dangos-v2 so that we can easily set enabledByDefault: false to the "new" addon.

If we can't merge a PR that keeps the addon soon, I'll merge my PR which removes the addon from the extension (#5934).

A PR that keeps the addon should consider the following:
- Addon name and description may need changes
- Remove the april fools timestamps
- "Added by Scratch Addons extension" becomes unnecessary, we can remove it
- It's not ideal to keep the projects hardcoded, we should consider the case where one of the projects is unshared or taken down
- We should credit the project authors in the project page. Currently, because I had limited time to develop the addon, projects have no author below their titles

If you think this is worth it, you're welcome to open a PR

**Comment by WorldLanguages** [comment]
There has been some progress on the PR that keeps the addon, so I'm postponing the decision until next release
