### ISSUE TITLE
Scratch 4.0

### ISSUE THREAD

**Issue by StioStudio** [ScratchAddons/ScratchAddons#5894]
### Why this would be helpful

More pleasant scratch pages.

### How this addon works

Continue on the scratch 3.0 addon and make it to 4.0.
Inspired by: https://scratch.mit.edu/projects/827943393
Was thinking to make it look how it looks on that project.
The stuff I want from the project:
✓front page
×Answer to comments (allready a thing with SA)
✓profile pages
✓my stuff page
✓studio pages
✓project pages
×folders (allready a thing in SA)
✓editor
×new blocks

### Possible alternatives

Could set the "scratch 3.0" addon together with the "scratch 4.0" addon, but I think that would probably have been a very big addon then.

**Comment by BroJac5246** [comment]
The designer of the mock-up appears to be using Scratch Addons, so it might be interesting to reach out to them.

However, this could not be branded as Scratch 4.0 because eventually there might be an actual Scratch 4.0 in the future. Something like a Material You design option/addon might be interesting, though.

**Comment by StioStudio** [comment]
> The designer of the mock-up appears to be using Scratch Addons, so it might be interesting to reach out to them.
> 
> However, this could not be branded as Scratch 4.0 because eventually there might be an actual Scratch 4.0 in the future. Something like a Material You design option/addon might be interesting, though.

The name can of course be changed. I said "scratch 4.0" so it was easier to understand.

**Comment by StioStudio** [comment]
> The designer of the mock-up appears to be using Scratch Addons, so it might be interesting to reach out to them.

Can you maybe make them join. I don't know how to make them join without writing scratch addons.

**Comment by callumjt** [comment]
it really is annoying to reach out to people on scratch isnt it

**Comment by StioStudio** [comment]
> it really is annoying to reach out to people on scratch isnt it

Yeah. I have been muted 3 times right now. So I am scared of talking more XD

**Comment by BroJac5246** [comment]
> > The designer of the mock-up appears to be using Scratch Addons, so it might be interesting to reach out to them.
> 
> Can you maybe make them join. I don't know how to make them join without writing scratch addons.
> 

I would do it by asking them to check the GitHub of the browser extension they use for Scratch, but I don't know if we should get them involved.
