### ISSUE TITLE
[June 28th] Scratch will be updating the editor's accent color

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5897]
### What's happening?

According to https://github.com/LLK/scratch-gui/commit/413997483ffc794a81970af7376b04e816ab7610, the accent color of the editor will soon be updated to a dark purple along with the arrival of the new block colors and [change the color of some UI elements](https://github.com/LLK/scratch-gui/commit/413997483ffc794a81970af7376b04e816ab7610?short_path=914bdb2#diff-914bdb27bc5c3986cad49322ae7ba6f2e8d1c99bdfd6d6a4f1249bb1c67a777a).

### What this means for Scratch Addons

I know some users will want to change that color. Fortunately and unfortunately, for those users, it is already possible to modify some of the icons through the `editor-dark-mode` addon, but not all of them. The elements that I found that aren't customizable are the costume editor icons and potentially some backgrounds.

We'll need to update the addon so that any affected UI elements are customizable and also remain consistent with Scratch by updating most of the presets to use the new purple color by the time Scratch changes it, and/or create a preset with the current blue color so users can quickly select it if they want it.

**Comment by CST1229** [comment]
This is also an opportunity to make a YouTube video showing how to revert the accent color, since a lot of people are probably gonna be mad because of the change (just look at what happened with the studio update!).

**Comment by WorldLanguages** [comment]
Anyone have a screenshot of the old vs new colors?

**Comment by CST1229** [comment]
> Anyone have a screenshot of the old vs new colors?

![](https://user-images.githubusercontent.com/68464103/230698068-db31c44d-34ec-4c4c-a246-eb4f4b4afc86.png)
![](https://user-images.githubusercontent.com/68464103/230698075-7208b21d-75bc-41e2-9c8d-709a5475b91d.png)

**Comment by Secret-chest** [comment]
Not again! Just change it to darker blue!

**Comment by Secret-chest** [comment]
Now boys will hate Scratch, because it looks girly

**Comment by Samq64** [comment]
> Now boys will hate Scratch, because it looks girly

I'm not a huge fan either, but I don't think people liked the blue when Scratch 3 first came out.

**Comment by fractioneater** [comment]
It's interesting that almost all genuine issues and reasonable feature requests sit around on for years on github, yet something unimportant like the editor accent color can be changed without hesitation.

**Comment by Samq64** [comment]
> It's interesting that almost all genuine issues and reasonable feature requests sit around on for years on github, yet something unimportant like the editor accent color can be changed without hesitation.

The purple colour has been in Scratch lab for almost 6 months (only the menu bar though) and with the colour changes, they are acully working on dark mode which is a poplar feature request.

**Comment by Secret-chest** [comment]
They should actually communicate more intsead of randomly opening `feat: ramdom thing nobody asked for`

**Comment by DNin01** [comment]
> They should actually communicate more intsead of randomly opening `feat: ramdom thing nobody asked for`

They're just doing what they think will benefit the largest number of users.

**Comment by lisa-wolfgang** [comment]
Please, let's keep the discussion to how Scratch Addons is affected by this change. GitHub is not a forum for ranting.

**Comment by apple502j** [comment]
Now that this has a deadline - it drops at the end of June - we really need some plans. @mxmou since you're the one working on themes I am assigning you. Note, in addition to blocks, the website and editor will receive color changes.

**Comment by Secret-chest** [comment]
> Now that this has a deadline - it drops at the end of June - we really need some plans. @mxmou since you're the one working on themes I am assigning you. Note, in addition to blocks, the website and editor will receive color changes.

I'm a translator and I have received the strings. The changes will be live by 7th of June.

This is what I've received through Transifex (seems to be an upcoming forum post):

> ## Coming Soon: Color Contrast in Scratch!
> We’re excited to share some upcoming changes to the colors on the Scratch site. Check out the video above or read below to learn more about what this means.
> The biggest change you'll notice is that the nav bar at the top of your screen will change color, from blue to purple. You may also notice some smaller updates (like the alerts color for your messages), but the Scratch site will still feel and work the same.
> The other exciting change will appear in the Project Editor. Scratchers will now have the option to use High Contrast blocks, which will be easier for some people to read. You'll be able to change this color mode inside of the Editor. You can always change the color mode back or decide not to try High Contrast blocks at all! You may even see some new color mode options in the future.
> ### When will this happen?
> We will be sharing these updates to the website on June 7th!
> ### Why are we making this change?
> We made these changes so our site can be more accessible and used by everyone -- including people with disabilities. We want to make sure everything on the site is easy to read so more people can express themselves on Scratch.
> All of the changes we are making meet Web Content Accessibility Guidelines, which you can learn more about in the links below: 
> * Kiddle: Accessibility Facts for Kids
> * W3 WCAG Guidelines and Standards
> * Wikipedia Article About WCAG
> It's important that Scratch is inclusive for all Scratchers! We love that our community is made of Scratchers with differing abilities, backgrounds, and cultures, and this is just one step toward making sure everyone feels welcome on Scratch.
> Special thanks to Scratchers who gave us feedback about the High Contrast blocks on Scratch Lab. Your suggestions helped us make the design even better.
> We hope you have fun exploring the new High Contrast blocks, and stay tuned for future announcements!
> Scratch On!
> _ceebee, on behalf of the Scratch Team_

**Comment by CST1229** [comment]
> Special thanks to Scratchers who gave us feedback about the High Contrast blocks on Scratch Lab. Your suggestions helped us make the design even better.

(Did they even change the design at all?)

**Comment by DNin01** [comment]
> > Special thanks to Scratchers who gave us feedback about the High Contrast blocks on Scratch Lab. Your suggestions helped us make the design even better.
> 
> 
> 
> (Did they even change the design at all?)

The feedback might have influenced their decision to make the change optional. That's all I can think of.

**Comment by mxmou** [comment]
scratchfoundation/scratch-www#7632 adds a banner announcing the update. The start and end dates are June 21-29, which probably means the update will be released after that.

**Comment by WorldLanguages** [comment]
> We will be sharing these updates to the website on June 7th!

Looks like we had to take this literally. "Share updates" may have meant talking about the updates 😂

**Comment by WorldLanguages** [comment]
It's also possible that they'll share a preview of the beta branch before the changes actually go live 🤔

**Comment by mybearworld** [comment]
They specified June 28 in a translation string.

**Comment by Samq64** [comment]
Official Scratch Team announcement: https://scratch.mit.edu/discuss/topic/689659/
It looks like it's the same as what @Secret-chest posted above.

**Comment by DNin01** [comment]
Better finish our changes soon, then!

**Comment by mybearworld** [comment]
> They specified June 28 in a translation string.
> 
> ![An image showing a translation string called "On June 28th, you'll see some changes to the colors on the Scratch site.", showing that June 28 is the planned release date.](https://user-images.githubusercontent.com/130385691/244163244-08e5d88c-7629-495c-ba0e-0bc8e5b7093b.png)

The video where this was in is now public as well.

**Comment by WorldLanguages** [comment]
Related: #6299

**Comment by WorldLanguages** [comment]
Nice work everyone!
Now let's keep an eye, as Scratch has hinted they might add dark mode in the future.
