### ISSUE TITLE
Privacy policy and/or security policy

### ISSUE THREAD

**Issue by BoomerScratch** [ScratchAddons/ScratchAddons#59]
**Is your feature request related to a problem? Please describe.**

Privacy policy: people sometimes want to know which data gets collected, and more. We can create a privacy policy for that.
Security policy: a security policy can be used to tell people what they need to do if they found a security vulnerability.

**Describe the solution you'd like**

For a privacy policy: create a PRIVACY.md markdown file.
For a security policy: create a SECURITY.md markdown file, or go [here](https://github.com/ScratchAddons/ScratchAddons/security/policy).

**Comment by BoomerScratch** [comment]
Ping @WorldLanguages, there is a wiki page created about privacy, do we still need a security policy?

**Comment by WorldLanguages** [comment]
Hmm we could, but all it should say is to email me at worldxlanguages@gmail.com

**Comment by GrahamSH-LLK** [comment]
Did you use namecheap? If so, https://www.namecheap.com/support/knowledgebase/article.aspx/308/2214/how-to-set-up-free-email-forwarding.

**Comment by Hans5958** [comment]
He did use NC, but it still depends how he set up his domain.

**Comment by WorldLanguages** [comment]
Resolved by #460 
Extension privacy policy should belong in the website, if we write one
