### ISSUE TITLE
Embed button on project page

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#590]
**Describe the new addon**

Re-adds the Embed button from the 2.0 project page.
Would be useful for those who are unfamiliar with the 3.0 embed format.

**Comment by Explosion-Scratch** [comment]
Already exists!
Click this:
![image](https://user-images.githubusercontent.com/61319150/97611180-d236a800-19e3-11eb-8346-0279c9aa20d1.png)
Then copy the embed code!
![image](https://user-images.githubusercontent.com/61319150/97611229-e24e8780-19e3-11eb-8e3a-7ef1e8a67474.png)

**Comment by lisa-wolfgang** [comment]
Haha, never noticed that before. Probably because I just copy the link from the browser's omnibox... :)P

**Comment by YOYITsM3M8** [comment]
Ngl scratch should get scrat.ch so they can do a urlshortener for users, projects, and forums.

**Comment by Hans5958** [comment]
They already have https://scratch.com, but that's not the point of this issue.
