### ISSUE TITLE
shinies.space integration

### ISSUE THREAD

**Issue by emma144** [ScratchAddons/ScratchAddons#5902]
### Why this would be helpful

[shinies.space](https://shinies.space/) is a very simple digital currency for scratch, mainly for shops and requests. For now, people can send and receive shinies directly from their dashboard at https://shinies.space/dashboard, however, this addon would make it easier for users to create transactions.

### How this addon works

This addon would add a button to pay or request shinies on everyone's profiles (who have registered on shinies.space). Here's a simple code snippet that I took & modified from the shinies documentation:
```
let customerName = ...; // the scratcher who is paying
let customerKey = 'mykey123'; // the scratcher's payment key
let receiver = ...; // who receives the money
let amount = 10; // how many shinies to pay
let appName = receiver + ' via ScratchAddons'; // the app name that will be shown in the transaction

// CORS is disabled on this route
fetch(`https://shinies.space/pay-with-key?user=${customerName}&key=${customerKey}&receiver=${receiver}&amount=${amount}&appname=${appName}`, {
    method: 'POST'
})
.then(r=>r.text())
.then(d=>console.log(d)); // Plain-text success or error message for the customer.
```

And if we run this, it would show up like this on the payer's transaction history:
![image](https://user-images.githubusercontent.com/128169269/230718727-8d7e77bd-6e5e-4a5a-a0fd-cdbeecf8fd45.png)

the "external application" link:
![image](https://user-images.githubusercontent.com/128169269/230718804-72bfcb52-7c5b-4f18-878f-3cbbb1815c1c.png)

and the receiver's transaction history:
![image](https://user-images.githubusercontent.com/128169269/230718820-689a4877-2300-48bd-8a2f-397b7904697d.png)

**Comment by callumjt** [comment]
interesting

**Comment by Samq64** [comment]
The site looks like it's really new and has almost no CSS. Could you provide a link to the repository for shinies.space?

**Comment by emma144** [comment]
The website launched recently, it has gained 50 users and the reason it has no CSS is because it is supposed to be minimalistic. https://scratch.mit.edu/discuss/topic/676147/

**Comment by Samq64** [comment]
I think the site will need at least 500 users and some styling before this can be considered.

**Comment by Secret-chest** [comment]
I don't think so. It seems pretty ridiculous, let's not encourage its use

**Comment by emma144** [comment]
How would you consider it 'ridiculous'?

**Comment by Secret-chest** [comment]
It really makes no sense, deciding to serve someone based on how many of these fake points they've got.

**Comment by BroJac5246** [comment]
The currency just launched 2 days ago and it has no practical purpose because the only way to obtain them is to request them from the owner. It's a system open to abuse that currently has no value. And just because there are 50 users doesn't mean 50 people use it. I signed in to see what was happening, but I definitely don't use it! If this takes off then this could _maybe_ be considered, but for now this should definitely be rejected. There's no practical way for us to implement this, and it is currently worthless until more users theoretically use it.

**Comment by DNin01** [comment]
Probably not at this time. It sounds fun, but this service doesn't really line up with Scratch's goal, either.

**Comment by WorldLanguages** [comment]
I misclicked. Sorry!
