### ISSUE TITLE
Accommodate for Scratch's upcoming menu bar modification

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5905]
### What's happening?

Scratch's menu bar is being reworked for the upcoming color changes update.
![image](https://user-images.githubusercontent.com/17484114/239035688-68b32e53-33bf-42f8-b1ca-9f4eb386cb38.png)

### What this means for Scratch Addons

- Some addons such as `tutorials-button` and `mediarecorder` may have to be tweaked slightly to place and manipulate buttons properly and look consistent with the rest of the buttons.

- We might also have to adjust some addons to not crowd the menu bar. However, Scratch responds to smaller screens by compressing some menu bar items:

![Screenshot 2023-03-13 at 2 25 26 PM](https://user-images.githubusercontent.com/4893763/224796702-42b3af44-68f7-4ff6-8b63-3de0f46aef87.png)

If we can make use of that, we may be able to fit any buttons added by addons on the new menu bar.

- For those who don't like more space being taken up, we could make a "compact editor menu bar" addon that could allow removing some text from certain items from the menu bar or something like that. I don't think we can just hide the buttons since, ideally, people should at least have access to them, but we could probably remove the text and leave the icons.

### Related

- #5761
- #5309

---

P.S.: as we get closer to this update, it may be helpful to create a milestone for accommodating for and staying consistent with Scratch's update. Just let me know if it's okay if I help with that.

**Comment by WorldLanguages** [comment]
> the language icon now has text next to it for the currently selected language

Why? It takes so much space! I don't get it

**Comment by WorldLanguages** [comment]
> P.S.: as we get closer to this update, it may be helpful to create a milestone for accommodating for and staying consistent with Scratch's update. Just let me know if it's okay if I help with that.

Sounds good to me. But I don't think we'll be able to know when these changes will reach Scratchers, right?

**Comment by DNin01** [comment]
> > P.S.: as we get closer to this update, it may be helpful to create a milestone for accommodating for and staying consistent with Scratch's update. Just let me know if it's okay if I help with that.
> 
> Sounds good to me. But I don't think we'll be able to know when these changes will reach Scratchers, right?

I have created a milestone.

**Comment by Secret-chest** [comment]
Why add text to a language button? Maybe they're doing this to give us issues to solve! 🤔🤔🤔

**Comment by mxmou** [comment]
There's a new PR that combines the language and theme dropdowns into a single menu.

**Comment by WorldLanguages** [comment]
> There's a new PR that combines the language and theme dropdowns into a single menu.

Here's a link: [Feature/settings menu](https://github.com/scratchfoundation/scratch-gui/pull/../pull/8956)

**Comment by WorldLanguages** [comment]
The new menu is called "settings", so this is might be a good opportunity to add our own buttons/dropdowns into it.

**Comment by DNin01** [comment]
> There's a new PR that combines the language and theme dropdowns into a single menu.

That looks good! I really like the icons.

**Comment by WorldLanguages** [comment]
> The new menu is called "settings", so this is might be a good opportunity to add our own buttons/dropdowns into it.

We could possibly link to our settings page like this (opens in a new tab):

Alternative 1:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/f8608811-c2cb-45ba-9486-97688d7d5f68)

Alternative 2:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/bbf7a46d-b7f1-4071-b76b-93f87d6ee330)

**Comment by WorldLanguages** [comment]
@mxmou said in a different issue:
> > Maybe for editor-theme3, it could add a new "Custom" option to the dropdown that applies the custom block colors (probably also selecting it by default).
>
> We could also simply disable the theme picker when theme3 is enabled. There could be a tooltip with a link to the addon settings.

I think this idea is nice, but how would it look?

**Comment by DNin01** [comment]
> @mxmou said in a different issue:
> 
> > > Maybe for editor-theme3, it could add a new "Custom" option to the dropdown that applies the custom block colors (probably also selecting it by default).
> > 
> > 
> > We could also simply disable the theme picker when theme3 is enabled. There could be a tooltip with a link to the addon settings.
> 
> I think this idea is nice, but how would it look? We should make it clear somehow that the color mode "is administered by the customizable block colors addon" (or something like that) and provide a link to https://scratch.mit.edu/scratch-addons-extension/settings#addon-editor-theme3

We could gray it out and display a tooltip saying, "These settings are overridden by Scratch Addons."

**Comment by WorldLanguages** [comment]
@DNin01 Consider we might want to add a direct link to `editor-theme3`'s settings. The "addon settings" button below will link to the main settings page.

**Comment by Samq64** [comment]
It would be cool if the the colour menu had Scratch Addons presets, but that wouldn't make much sense until somthing like #2739 is implemented.

**Comment by CST1229** [comment]
> Consider we might want to add a direct link to `editor-theme3`'s settings. The "addon settings" button below will link to the main settings page.

Maybe the theme dropdown would still exist but be replaced with something like:
> - Disabled by the "Customizable block colors" addon *(grayed out, can't be clicked)*
> - Edit settings *(links to theme3 settings)*

**Comment by Secret-chest** [comment]
I think `editor-dark-mode` should be disabled too.

**Comment by WorldLanguages** [comment]
> I think `editor-dark-mode` should be disabled too.

Why?

**Comment by DNin01** [comment]
> I think `editor-dark-mode` should be disabled too.

What do you mean by "disabled"?

**Comment by WorldLanguages** [comment]
> Scratch could also add UI themes.

That has been discussed here: https://github.com/ScratchAddons/ScratchAddons/issues/6030#issuecomment-1557777736

**Comment by Samq64** [comment]
> Scratch could also add UI themes.

They already do that with the workspace controls since it's part of Blockly.

![image](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/a8b72ce9-eb38-4aad-9c68-82524b39fe8d)

**Comment by DNin01** [comment]
Is there anything else we need to do?

**Comment by WorldLanguages** [comment]
Well, we didn't add a "scratch addons settings" button yet.
