### ISSUE TITLE
"Always show number pad" description is confusing

### ISSUE THREAD

**Issue by WriteThatDown** [ScratchAddons/ScratchAddons#5906]
### Description

If you look at the description for the "always show number pad" addon. It says 

> A number pad will show when editing number inputs from certain blocks, such as "set x to".

But, since settings a variable in scratch can also be a string, the number pad doesn't actually show on this block. A more a appropriate example could be

> A number pad will show when editing number inputs from certain blocks such as "change x by ()"

Just a little thing that I noticed while browsing scratch addons.

### Steps to reproduce

1. Open scratch addons settings
2. Find the "always show number pad" addon
3. Look the description

### Environment

Browser: Firefox
Scratch Addons version: 1.31.2
Operating system: Windows 10

**Comment by CST1229** [comment]
> But, since settings a variable in scratch can also be a string, the number pad doesn't actually show on this block. A more a appropriate example could be

I'm pretty refers "set x to" refers to the Motion block, not the "set [] to ()" block in Variables.

**Comment by WorldLanguages** [comment]
Using "change [] by ()" might be less confusing, since both the motion and variable blocks that use that syntax show a number pad.

**Comment by penguinmoose** [comment]
It should also mention that the same number pad is shown on mobile.
