### ISSUE TITLE
Fix Scratch bug with running duplicated scripts

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#591]
**Describe the new addon**

When duplicating a block and placing it inside of a script, the addon disables the triggering of the event that would cause that script to run.

_The second part of this issue was migrated to #2471._

**Comment by Explosion-Scratch** [comment]
Nice ideas! @JeffaloBob can you do these?

**Comment by lisa-wolfgang** [comment]
These are still my top pet peeves with Scratch 3.0 -- and I'm sure I'm not alone! (I hope lol)
