### ISSUE TITLE
"reply" button with scratchr2 addon capitalized

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#5912]
### Description

The "reply" button on scratchr2 pages with the scratchr2 addon is capitalized, while on scratch-www pages it isn't.

### Steps to reproduce

1. Go to any profile with comments with the scratchr2 addon enabled.

### Demonstration(s) and additional context

*scratchr2 pages with scratchr2 addon disabled*
![image](https://user-images.githubusercontent.com/130385691/230948694-3ac43324-cfc8-4662-8ba9-c2cbf214c109.png)
*scratchr2 pages with scratchr2 addon enabled*
![image](https://user-images.githubusercontent.com/130385691/230948571-5aac962e-17f0-4584-b746-994240647329.png)
*scratch-www pages*
![image](https://user-images.githubusercontent.com/130385691/230948752-36b8abfc-0004-4b90-8cbc-ef76e2689798.png)

### Environment

Browser: Edge 113.0.1774.3 (Official build) dev (64-bit) 
Scratch Addons version: 1.31.1
Operating system: Windows 11

**Comment by GrahamSH-LLK** [comment]
this is a nonissue. if you feel like fixing it, go ahead except the pr won't be approved because you'd have to change it with js and there's literally no point. scratchr2 (addon) isn't even intended to provide exact parity.

**Comment by mxmou** [comment]
> you'd have to change it with js

No JS is needed for this, just `text-transform: lowercase`.

**Comment by mybearworld** [comment]
This seems like a relatively simple thing then, so I've made a PR for it.
