### ISSUE TITLE
Adjust block padding

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#592]
**Describe the new addon**

Allows the user to adjust the amount of padding applied to blocks via an option in the settings.

**Comment by TheColaber** [comment]
What is the purpose of this?

**Comment by lisa-wolfgang** [comment]
Some people have complained about the large block size in Scratch 3.0, and it would be useful to see more scripts on the screen without decreasing the text size.

**Comment by Explosion-Scratch** [comment]
This would be cool! (Support? Can you do that on github addons or only on
scratch?)

**Comment by TheColaber** [comment]
The problem is, these are SVG images. Whoever understands SVG paths would be able to help us...

**Comment by mxmou** [comment]
@TheColaber It might be possible to change Blockly's constants before the blocks are rendered.

**Comment by TheColaber** [comment]
> @TheColaber It might be possible to change Blockly's constants before the blocks are rendered.

Is it possible to change it?

**Comment by ZenithRogue** [comment]
The block padding is (or, at least, used to be) sandboxed, and cannot be set externally

[Please see this post issue I authored previously]
(https://github.com/mrjacobbloom/scratch-themes-resources/issues/1)

**Comment by mxmou** [comment]
@ZenithRogue That's because Closure Compiler removes constants and replaces them with the actual values. I didn't think of that.

**Comment by RedGuy12** [comment]
Someone, I think Sheep_tester, made a userscript for this that I use... it's a bit nifty with frozen but works great overall

**Comment by lisa-wolfgang** [comment]
> Someone, I think Sheep_tester, made a userscript for this that I use... it's a bit buggy with dropdowns but works great overall

Oh, that's cool! I found the link to it: https://sheeptester.github.io/hello-world/userscripts/thinner-scratch.user.js

**Comment by SheepTester** [comment]
Yep, since `Blockly` is global, one can do many fun things with it:

```js
// The main "workspace"; it's been a while since I wrote this but I think that's like the scripts area
const workspace = Blockly.getMainWorkspace()

// This I believe gets the block palette; `workspace_` is a bit worrying because it seems like it might be a private property ¯\_(ツ)_/¯
const palette = workspace.getFlyout().workspace_
```

Creating a block and getting its constructor grants us access to the fanciest `BlockSvg` constructor with all the block constants, as defined in vanilla Scratch in [core/block_render_svg_vertical.js](https://github.com/LLK/scratch-blocks/blob/develop/core/block_render_svg_vertical.js):

```js
const BlockSvg = Blockly.getMainWorkspace().newBlock().constructor
```
