### ISSUE TITLE
Change non-material forum editor buttons to light versions when a dark theme is enabled 

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#5923]
### Why this would be helpful

With the dark-www addon, it'd be nice for buttons to not have a light background, however dark-www makes buttons have one as otherwise, the buttons would have very low contrast.

### My suggestion

When dark-www has a dark theme, replace the icons with light alternatives instead.

### Possible alternatives

- An option in material-forum-editor-buttons, which is what this issue was at first, however, it makes more sense to have this built into the dark-www addon as it's something that is expected to come with dark mode.

### Additional context

None.

**Comment by mxmou** [comment]
Removing the background without changing the icons would make some buttons almost invisible:
![image](https://user-images.githubusercontent.com/51849865/231998267-3af2773a-3066-4d25-a5df-8e5fdb4c4b78.png)

If someone makes white versions of these icons, I think it's better to remove the background and always use those instead of adding a setting.

**Comment by Secret-chest** [comment]
> Removing the background without changing the icons would make some buttons almost invisible:
> ![image](https://user-images.githubusercontent.com/51849865/231998267-3af2773a-3066-4d25-a5df-8e5fdb4c4b78.png)
> 
> If someone makes white versions of these icons, I think it's better to remove the background and always use those instead of adding a setting.

I think they should just be inverted (only the black ones)

**Comment by mybearworld** [comment]
> I think they should just be inverted (only the black ones)

![image](https://user-images.githubusercontent.com/130385691/232082475-12295ea8-0d7f-4e44-87f9-82ab1337d514.png)
This is how inverting looks. It makes the gradients look off and also turn the blue color in the list related items orange, which isn't too great. 

> If someone makes white versions of these icons, I think it's better to remove the background and always use those instead of adding a setting.

You mean as part of dark-www? That would make sense.

**Comment by mybearworld** [comment]
How's this?
![image](https://user-images.githubusercontent.com/130385691/232086608-3dae1032-c273-4724-b102-09108cd4e534.png)

**Comment by mxmou** [comment]
> How's this?
> ![image](https://user-images.githubusercontent.com/130385691/232086608-3dae1032-c273-4724-b102-09108cd4e534.png)

I like this. A subtle gradient might help match the style of the original icons better, but I don't think it's necessary.

**Comment by mybearworld** [comment]
For the subtle gradient:
![image](https://user-images.githubusercontent.com/130385691/232142523-f5f676fb-4300-4b07-8949-bad573f79b2e.png)
Would that be better?

**Comment by mxmou** [comment]
> For the subtle gradient:
> ![image](https://user-images.githubusercontent.com/130385691/232142523-f5f676fb-4300-4b07-8949-bad573f79b2e.png)
> It really is quite subtle.

The difference is quite small but I think I prefer this version.

**Comment by mybearworld** [comment]
> The difference is quite small but I think I prefer this version.

Me too - I think it's that it appears darker and therefore not so "in your face".

**Comment by mybearworld** [comment]
I can't edit the title, but I've edited the issue to change the focus to it being built into dark-www.
