### ISSUE TITLE
Addon Setting Descriptions

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#5928]
### Why this would be helpful

Some addon settings are hard to explain in just a couple of words, but having settings with really long names doesn't look very good and clutters things up when there are a lot of them.

### My suggestion

Shortening addon setting names and using a tooltip that can be accessed with a little `?` button to display longer descriptions.

### Possible alternatives

Displaying the list of settings vertically even on the settings page with the browser maximized.

### Additional context

I thought this was discussed a little while ago, but I can't find it.

**Comment by WorldLanguages** [comment]
Duplicate of #5320 (?)

**Comment by Samq64** [comment]
yeah, that was the one. I'm not sure why I missed it.
