### ISSUE TITLE
Switch blocks via dropdown (operators, conditionals)

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#593]
**Describe the new addon**

When right-clicking a +, -, *, or / block, the dropdown would allow the block to be switched out for any of the others a la 2.0.

![image](https://user-images.githubusercontent.com/43426138/97520917-6106de80-196a-11eb-9f7b-ded00d986737.png)

Would also work for the AND/OR/NOT blocks and the '>'  '<'  '=' blocks.

**Comment by Explosion-Scratch** [comment]
That would also be nice! Also support for switching with boolean statements
(E.g. and to not)

**Comment by Explosion-Scratch** [comment]
Sorry, that's a bad example, and to or would be a better one.

**Comment by lisa-wolfgang** [comment]
Good idea, I'll change my initial post.

**Comment by samuraininja360** [comment]
Yes I remember this good idea!
