### ISSUE TITLE
Project stats (number of assets, sprites, scripts)

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#594]
**Describe the new addon**

Shows the number of assets, sprites, and/or scripts on the project page a la 2.0.

![image](https://user-images.githubusercontent.com/43426138/97521591-e0e17880-196b-11eb-864e-f941d43dd352.png)

**Comment by Hans5958** [comment]
Note: not a duplicate of #492

**Comment by WorldLanguages** [comment]
Note that ST members can see these counts, but normal users can't

**Comment by Hans5958** [comment]
Well, even if that number is literally removed completely, it's still possible to count it.
