### ISSUE TITLE
Keyword-based spoiler warnings

### ISSUE THREAD

**Issue by DogCatPuppyLover** [ScratchAddons/ScratchAddons#5954]
### Why this would be helpful

Many websites have ways of hiding parts of posts, to obscure sensitive content or spoilers. However, Scratch doesn't have this feature. You can add warnings to the beginning of your comments, but those are easy to read past. You can also use the "see more replies" feature, but that takes a while (especially with the recent increase in time between comments.)

### My suggestion

My suggestion is to add a feature to Scratch Addons that allows users to blur or obscure comments that contain a list of keywords.

Here's a mockup:
![image](https://user-images.githubusercontent.com/79656307/233490359-f6c0587d-4de7-4f4d-bc47-f78f492fbce6.png)

### Possible alternatives

We could implement Discord-like spoiler tags using `||`, but that would be less versatile and would only spoiler content made by other SA users who knew to use that syntax.

**Comment by DNin01** [comment]
Some users might use this to blur out comments containing potentially offensive words. One problem I see with blurring out inappropriate content is that users may skip those comments without reporting them.

Also, if this was meant to be used to reliably hide spoilers, how would the user know what the spoiler is in order to blur it out? Like, for example, if a user didn't want to know a secret code, they'd have to enter the secret code into the addon to blur it out, defeating the whole purpose of hiding it now that the user knows it. (I guess they could at least match comments with the word "spoiler", though.)

**Comment by DogCatPuppyLover** [comment]
> Some users might use this to blur out comments containing potentially offensive words. One problem I see with blurring out inappropriate content is that users may skip those comments without reporting them.
> 
> Also, if this was meant to be used to reliably hide spoilers, how would the user know what the spoiler is in order to blur it out? Like, for example, if a user didn't want to know a secret code, they'd have to enter the secret code into the addon to blur it out, defeating the whole purpose of hiding it now that the user knows it. (I guess they could at least match comments with the word "spoiler", though.)

1. This is a good point; however, there are enough non-SA users that I don't think this would end up being a problem. And what offensive words would you be talking about? I can't think of an offensive word that someone would add to their blocklist that isn't already blocked by the filterbot.
2. I was thinking that you could block the name of the media. For example, to avoid spoilers for Star Wars, you could block "star wars" and maybe some star-wars related keywords. As you said, you could also block "spoiler" itself (so that if someone adds "spoiler warning" to a comment, that would get flagged.)

**Comment by rgantzos** [comment]
> 2. I was thinking that you could block the name of the media. For example, to avoid spoilers for Star Wars, you could block "star wars" and maybe some star-wars related keywords. As you said, you could also block "spoiler" itself (so that if someone adds "spoiler warning" to a comment, that would get flagged.)

This would take a very long list of keywords, and would often be inaccurate. Someone could be talking about a game or just their favorite movies and mention Star Wars. There’s no reason to do it like this. The best way would be to use basic markdown formatting such as || as Discord does. The thing is, Scratch already doesn’t support any markdown at all, and many people can agree that spoilers are pretty useless compared to the other markdown features that many platforms support.

**Comment by WorldLanguages** [comment]
It's hard to find a good solution for this, which makes me wonder whether this is an actual problem or not. If you're this serious about spoilers, you might as well install a general-purpose extension that attempts to block spoilers in all websites, right? Of course the UX wouldn't be the same, but you would achieve your goal.
Supporting markdown in comments is off-topic here.
