### ISSUE TITLE
In the "following", "favorite projects", etc. sections, add an option to undo that action

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#5957]
### Why this would be helpful

Sometimes, you want to clean up what you're favoriting, following, etc. and don't want to open everything in a new tab.

### My suggestion

On applicable pages, add an X button to every item which removes it from the list.

### Additional context

| Page | What the X does |
|--------|--------|
| Shared Projects | Unshare the project |
| Favorite Projects | Unfavorite the project |
| Studios I'm Following | Unfollow the studio |
| Studios I Curate | Leave the studio |
| Following | Unfollow the user |

**Comment by mybearworld** [comment]
I used the wrong issue template... Making a new one.

**Comment by Samq64** [comment]
By the way the issue template isn't enforced when editing an existing issue.

**Comment by WorldLanguages** [comment]
This was moved to #5958
