### ISSUE TITLE
Show senders/receivers of broadcast

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#596]
**Describe the new addon**

Adds new options in the dropdown of a broadcast block that, when selected, shows the sprites that contain a send/receive broadcast block, a la 2.0.

![image](https://user-images.githubusercontent.com/43426138/97521915-88f74180-196c-11eb-9299-d634257338f0.png)
![image](https://user-images.githubusercontent.com/43426138/97521822-5fd6b100-196c-11eb-8137-c2254c44bf28.png)

**Comment by WorldLanguages** [comment]
Oh wow. I completely forgot Scratch 2.0 had this. Nice feature.

**Comment by Explosion-Scratch** [comment]
That's cool! Is that possible to actually do though through an addon?

**Comment by lisa-wolfgang** [comment]
I don't know if this would work internally, but when loading the editor, the addon could search every block in the project for broadcasts and index the broadcast blocks with their sprite. (This index would be updated when new broadcast blocks are placed.) Then when selecting the feature in the dropdown, the addon would be able to highlight the sprites that have the selected broadcast in the index.

**Comment by YOYITsM3M8** [comment]
also updated when broadcast blocks are deleted too
