### ISSUE TITLE
Add an option to disable the colorblind love and favorites

### ISSUE THREAD

**Issue by JackyBorderCollie** [ScratchAddons/ScratchAddons#5966]
### Why this would be helpful

I (and probably some other people too) liked the old Love and Favorite buttons. However, they now made them outlined, and I prefer the old ones.

### How this addon works

When enabled, the love and favorite icons when the project is not loved and favorited will be filled, not just an outline.

### Possible alternatives

I don't think there's an addon for this yet.

**Comment by DNin01** [comment]
Related: #5722

**Comment by WorldLanguages** [comment]
If you're suggesting to return to the previous love and favorite icons, look at #5722 for relevant discussion.

If you're suggesting something different, such as keeping the current icons but adding the ability to remove their fill (not exactly the same as returning to the old icons, I believe, but I might be wrong) please clarify

**Comment by WorldLanguages** [comment]
OP didn't clarify so I assume we are using this issue to track #5722 and #6087.

Keep in mind that #5722 was created before an issue existed and most of the discussion on it was against adding this feature.

**Comment by BroJac5246** [comment]
Looking at the picture in #6087, I must say that I prefer the new icons because they offer better contrast, which is something that everyone benefits from.

I oppose this suggestion because of the points brought up in #5722.

**Comment by WorldLanguages** [comment]
Worth mentioning: in Scratch 2.0, the love and favorite buttons were in reverse order, but we all got used to it.

**Comment by WorldLanguages** [comment]
Related: PR #6400 at some point suggested a set of colors that is **more accessible** apparently, than the new accessible colors chosen by Scratch a few months ago. If we add a "more accessible" option, maybe we could also add an option to return to the non-accessible colors, I guess.

cc @DNin01 any thoughts? What was the difference between your accessible colors and the ones chosen by Scratch? In what sense are the current colors not accessible enough? I'm curious

**Comment by DNin01** [comment]
> cc @DNin01 any thoughts? What was the difference between your accessible colors and the ones chosen by Scratch? In what sense are the current colors not accessible enough? I'm curious

Sorry, what did you mean by my "accessible colors"?

> If we add a "more accessible" option, maybe we could also add an option to return to the non-accessible colors, I guess.

Some people like less contrast because it's more pleasant or for other reasons, so we could offer presets for both increased contrast and reduced contrast. The old icons or a set of new, lighter icons that we make could very well be part of a setting to reduce contrast.

Regarding the name, since everyone has different needs, I like terms such as "high contrast" rather than "more accessible".

**Comment by WorldLanguages** [comment]
> Sorry, what did you mean by my "accessible colors"?

I was referring to the `High contrast ❤️⭐ icons: Makes the colored love and favorite icons darker to increase contrast` feature that at one point was part of #6400

**Comment by DNin01** [comment]
> > Sorry, what did you mean by my "accessible colors"?
> 
> 
> 
> I was referring to the `High contrast ❤️⭐ icons: Makes the colored love and favorite icons darker to increase contrast` feature that at one point was part of #6400

Oh! That just makes the filled-in love and favorite icons darker to increase contrast against the background. The yellow star especially might be hard for some users to see.

**Comment by WorldLanguages** [comment]
> Oh! That just makes the filled-in love and favorite icons darker to increase contrast against the background. The yellow star especially might be hard for some users to see.

I see. Well, I think you could send a PR so that we can actually give that a chance (we previously discarded it for lack of time before release) and we can also consider adding an option to return to the 2022 vanilla love/favorite icons to the same addon/setting 🤔

**Comment by DNin01** [comment]
> > Oh! That just makes the filled-in love and favorite icons darker to increase contrast against the background. The yellow star especially might be hard for some users to see.
> 
> I see. Well, I think you could send a PR so that we can actually give that a chance (we previously discarded it for lack of time before release) and we can also consider adding an option to return to the 2022 vanilla love/favorite icons to the same addon/setting 🤔

Should this be an expansion to the Customizable link style addon or should it be its own addon? Although we started Customizable link style as an accessibility feature, it's also a great customization option for style regardless of the user's abilities.

**Comment by DNin01** [comment]
And how would be handle the addon ID in that case? Would the existing `colorblind` addon move into a new one or...?

**Comment by WorldLanguages** [comment]
> Should this be an expansion to the Customizable link style addon or should it be its own addon?

Hmm, it might need to be its own addon, anything else wouldn't fit. In the future we can provide a group/category/filter to list all accessibility-related addons, but as you said, they are great customization options for everyone.

> And how would be handle the addon ID in the case that that feature or Customizable link style gets a different addon? Would the existing `colorblind` addon move into a new one or...?

That addon ID is really unfortunate now, so we may change the ID and add a script that migrates settings. Maybe you should open a different issue about it.

**Comment by Samq64** [comment]
Are there any other icons that this could apply to?

**Comment by medlans** [comment]
> Worth mentioning: in Scratch 2.0, the love and favorite buttons were in reverse order, but we all got used to it.

Then I clearly failed to get used to it because I had to make a userscript to swap them since I kept thinking it was the 2.0 order LOL (anyway I guess I’m the only one :P)

> Are there any other icons that this could apply to?

I mean, I guess the remix button??..

**Comment by DNin01** [comment]
I will close this because this Scratch change happened quite long ago and it would be weird to add this feature now of all times when probably 90% of people don't even remember. If an addon like 3.0 to 2.0 ever gets made, then we can add this to that addon.
