### ISSUE TITLE
Project downloader

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5968]
### Why this would be helpful

It can be useful to download projects without having to open the editor for each project.

### How this addon works

This addon could add a download button in My Stuff and/or project pages, potentially chosen by the user.
![Download button on My Stuff page](https://user-images.githubusercontent.com/106490990/234718706-cc11f8b8-2108-4287-b128-1fc2a691e947.png)
![Download button on project page](https://user-images.githubusercontent.com/106490990/234718704-33e6fa1d-ab25-4005-a2bf-42ed379b6601.png)

**Comment by Samq64** [comment]
Related discussion: #5744

**Comment by WorldLanguages** [comment]
Quoting myself:

> I'm not sure about the technical aspects of downloading a project outside of the editor. We might need to ship a lot of code as well as a zip library.

> After we figure that out we can decide whether we can let the user download more than one project at once as a zip file. Or possibly download many individual files at once (but browsers don't allow that by default)

Of course we should be careful and avoid spamming network requests.

**Comment by WorldLanguages** [comment]
@DNin01 Well, the PR you linked only adds the download button to the project page. It just saves the user three clicks per project.

**Comment by DNin01** [comment]
> @DNin01 Well, the PR you linked only adds the download button to the project page. It just saves the user three clicks per project.

Maybe we could create an issue for adding it to the My Stuff page after the PR is merged.

**Comment by Jazza-231** [comment]
> It just saves the user three clicks per project.

And depending on the hardware/general situation, a lot of time.

Unrelated, do people have a preference for the button position? Should it be down near the copy link button like this mockup, or leave it where my PR has it?

> This addon could add a download button in My Stuff

I do also like this idea, make the issue, I'll code it up, and we'll see what people think from there

**Comment by Samq64** [comment]
> Unrelated, do people have a preference for the button position? Should it be down near the copy link button like this mockup, or leave it where my PR has it?

I think it's fine where it is but I guess it could be moved if you really don't like the colour order.

> > This addon could add a download button in My Stuff
>
> I do also like this idea, make the issue, I'll code it up, and we'll see what people think from there

It doesn't necessarily have to be in this PR. I just thought it would be a good idea to change the addon ID now to make things easier later on.

**Comment by WorldLanguages** [comment]
> Unrelated, do people have a preference for the button position? Should it be down near the copy link button like this mockup, or leave it where my PR has it?

Scratch 1.x had a download button in the upper-right corner I think, if it matters 😅

**Comment by Jazza-231** [comment]
> I think it's fine where it is in the PR but I guess it could be moved if you really don't like the colour order.

I think it does make more sense where this issue adds it so I'll change it
