### ISSUE TITLE
Remove new line from Prettier

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#5978]
### Why this would be helpful

Actions are disabled by default on new forks and prettier often fails because there's no new line at the end of a file in a PR even though everything else looks fine.

### My suggestion

Removing the new line at the end of files from the Prettier action.

### Possible alternatives

Making it clear to new contributors how to enable the action or ignoring the failed check.

### Additional context

Related: #5977

**Comment by DNin01** [comment]
If I'm right, some operating systems may not read files correctly without that new line, meaning that having a new line at the end of files is pretty important. So, unless somebody else knows more about this and concludes that it's unnecessary, I think we should keep this check so we always know if we need to format code. It's not that hard to fix and is not interrupting our development process.

The contributing guidelines already suggest enabling workflows on forks.
