### ISSUE TITLE
middle-click-popup bug: "stop other scripts in sprite" cannot stack into other blocks

### ISSUE THREAD

**Issue by hueychen27** [ScratchAddons/ScratchAddons#5979]
### Description

When you press ctrl + space and type in "stop other scripts in sprite", the block appearing has nothing to snap on in the little menu. The bottom is flat like the "stop all" block. It's supposed to be like most other blocks without a flat bottom.

### Steps to reproduce

1. Enable the "Insert Blocks by Name" addon
2. Press the command "ctrl + space"
3. Search up "stop other scripts in sprite"

### Demonstration(s) and additional context

I can't show you a screenshot because the menu closes when I try doing it.

### Environment

Browser: Firefox 102.10.0esr (64bit)
Scratch Addons version: v1.31.2
Operating system: Kali Linux

**Comment by DNin01** [comment]
Screenshot:
![A "stop other scripts in sprite" cap block](https://user-images.githubusercontent.com/106490990/235381116-d3b84233-4723-42da-9e92-42e796c4f3a8.png)

**Comment by WorldLanguages** [comment]
This appears to be bug #4139 happening again after the remake of the addon.

**Comment by Samq64** [comment]
Does it stay a cap block when dragging it out?

**Comment by DNin01** [comment]
> Does it stay a cap block when dragging it out?

It doesn't. The block is normal once inserted.

**Comment by WorldLanguages** [comment]
Oh, then this is a minor bug.

**Comment by hueychen27** [comment]
yes
