### ISSUE TITLE
Is exact project count for studios broken?

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#598]
> Amazing, but the exact count is broken (for studios, at least) 
I don't think there are 8023 projects on this studio: https://scratch.mit.edu/studios/26758523/

**Comment by WorldLanguages** [comment]
That studio doesn't appear to have more than 5 normal project pages (of 60 projects each)

**Comment by mxmou** [comment]
Assuming my userscript isn't broken, that studio has 227 projects right now.

The problem is that the addon treats `offset` as a page number, as seen in this line:
```js
let count = 40 * offset + pageLen;
```

**Comment by TheColaber** [comment]
Hmm, that's interesting... the api goes to https://api.scratch.mit.edu/studios/26758523/projects/?limit=40&offset=220

**Comment by TheColaber** [comment]
Oh, yeah I see the problem now... Yeah, we just need to change the code that @mxmou said above and remove the part that says `40 * ` Should I create a PR?

**Comment by mxmou** [comment]
@TheColaber I made a PR already before I saw your comment.
