### ISSUE TITLE
Custom studio front page row

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#5990]
> What about turning this into an addon to add any studio to the front page? Someone could make a studio with actually good featured projects.

_Originally posted by @Secret-chest in https://github.com/ScratchAddons/ScratchAddons/issues/5939#issuecomment-1512993399_

**Comment by WorldLanguages** [comment]
Related: #1758

If we release an addon that lets the user reorder the existing front page rows, we could also implement this suggestion and accept studio URLs.

**Comment by Samq64** [comment]
Related PRs: #4776 and #5501

**Comment by Secret-chest** [comment]
It could use table settings to show more.
