### ISSUE TITLE
Userstyle collection

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#6]
Here are the userstyles that I have collected so far:

Scratch forum editor buttons .svg’s
• https://github.com/JeffaloBob/material-scratch-forum-editor-buttons
Forum quote beautifier:
• https://github.com/BoomerScratch/userstyles/blob/master/scratch-forum-quote-code-beautifier.user.css
Forum post scrollbars:
• https://github.com/BoomerScratch/userstyles/blob/master/scratch-forum-quote-code-beautifier.user.css
Scratch forums long signatures and scratch blocks scrollbarifier:
• https://sheeptester.github.io/hello-world/userscripts/scratch-forums.user.css
Scratch dark mode (by _nix)
• https://gist.github.com/towerofnix/806550f907da63f63f55bb39c99789bf

(I am in the process of archiving these)

**Comment by Explosion-Scratch** [comment]
how do I add a label?

**Comment by WorldLanguages** [comment]
Hmm I had to change a permission setting, thanks for the heads up.

**Comment by Explosion-Scratch** [comment]
Okay! Thanks! :) These have now been archived in the internet archive.

**Comment by BoomerScratch** [comment]
Maybe go [here](https://userstyles.org/styles/browse/scratch.mit.edu) for more?

**Comment by BoomerScratch** [comment]
Can you remove 'Rickroll exposer'? Because that is not a userstyle for Scratch, it's for any website.

**Comment by Explosion-Scratch** [comment]
@Boomerscratch I'll remove rickroll exposer, also thanks for linking me to that site!

**Comment by BoomerScratch** [comment]
We also need userscripts. A lot can be found [here](https://gist.github.com/search?q=scratch.mit.edu+userscript) and [here](https://github.com/search?q=scratch.mit.edu+userscript). You should check if they are made for Scratch 3.

**Comment by JeffaloBob** [comment]
hey, i don't know when or why that fork of a-e-'s thing was made, but https://github.com/easrng/material-scratch-forum-editor-buttons is the original and my fork adds nothing...

**Comment by WorldLanguages** [comment]
@Explosion-Scratch If you can, please look at https://github.com/ScratchAddons/ScratchAddons/issues/26
I created issues for mentioned userscripts, but not userstyles, can you add them here?

**Comment by WorldLanguages** [comment]
Add them to this issue, I mean. Until userstyles are officially supported, having an issue for each one doesn't make much sense.

**Comment by Explosion-Scratch** [comment]
Oh, hi there! My apologies for not being very active over here. I've been super busy with school and then I got banned on scratch for a little bit because I used a link shortner on a bunch of my projects without knowing that they wern't allowed and I put "Last edited by Paddle2See" in a forum post as a joke. Anyways, I'll try to find some time for this tomorrow.

**Comment by tb148** [comment]
> 
> 
> Oh, hi there! My apologies for not being very active over here. I've been super busy with school and then I got banned on scratch for a little bit because I used a link shortner on a bunch of my projects without knowing that they wern't allowed and I put "Last edited by Paddle2See" in a forum post as a joke. Anyways, I'll try to find some time for this tomorrow.

Off topic: Why are link shortners not allowed?

**Comment by mxmou** [comment]
@tb148 Link shorteners are not allowed because you don't know where links go until you click them.

**Comment by mxmou** [comment]
@WorldLanguages Should we make a separate issue for each one now that userstyles are supported?

**Comment by WorldLanguages** [comment]
@mxmou Yep. Feel free to do so.

**Comment by Explosion-Scratch** [comment]
Closed because this is old and people are creating issues with new addons nicely already.
