### ISSUE TITLE
Editor comment previews does not dynamically disable properly

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6000]
### Description

When the addon "Editor comment previews" is disabled without refreshing, the contents of the last comment you were hovering over become visible and are not displayed correctly.

![A messed up comment preview](https://user-images.githubusercontent.com/106490990/236057072-21fc8b4c-5e50-468f-ab53-e4b70685eb00.png)

If you have Editor dark mode and customizable colors enabled, this messed-up preview will have a background. Otherwise, it'll just be text. You also can't click through it.

### Steps to reproduce

1. Enable the addon
2. Hover over a comment for a preview
3. Disable the addon

### Environment

Browser: Edge 112
Scratch Addons version: 1.32.0-pre
Operating system: Windows 10

**Comment by WorldLanguages** [comment]
6000 🎉 
(self-censoring as off-topic 😂)

**Comment by Secret-chest** [comment]
🪅🎉🎊 6000 🎊🎉🪅

This is unbelievable

Soon we'll get to #10000

I remember the 1.3 days, when we had ~1000 items

**Comment by CST1229** [comment]
> Minimise me please

You can do it:
![image](https://user-images.githubusercontent.com/68464103/236114955-ecd07f6f-fa12-434c-a74e-e0998d757cd0.png)

**Comment by Hans5958** [comment]
🎉

![](https://user-images.githubusercontent.com/11584103/236115582-c47e8783-9c97-4b79-bdd0-62851c99ee9c.png)
