### ISSUE TITLE
Remove feature-unshared

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#6005]
Unshared projects are now private; that addon won't work.

**Comment by Samq64** [comment]
It could still be combined with the thumbnail setter to make a cool-looking profile.

**Comment by Samq64** [comment]
I tbinkwe should keep the addon and add a red warning to it on the settings page.

**Comment by Secret-chest** [comment]
Maybe make it an easter-egg?

**Comment by mybearworld** [comment]
> It could still be combined with the thumbnail setter to make a cool-looking profile.

Isn't that what the addon is for in the first place?

**Comment by CST1229** [comment]
The thumbnails of unshared projects are still visible.

**Comment by rgantzos** [comment]
> > It could still be combined with the thumbnail setter to make a cool-looking profile.
> 
> Isn't that what the addon is for in the first place?

I don't know anyone who used the feature for anything else, not sure why this is being removed considering all the thumbnails are still public.
