### ISSUE TITLE
scratchblocks doesn't convert pre elements to scratchblocks if tab not in focus

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6014]
### Description

If the tab where `scratchblocks` is active is not in focus, the blocks will just be `pre` elements, which aren't fully converted.

### Steps to reproduce

1. Open this link in a new tab, and don't focus it until it has finished loading: https://scratch.mit.edu/discuss/topic/669945/
2. Focus the tab
3. Observe

### Demonstration(s) and additional context

![A demonstration of this bug.](https://user-images.githubusercontent.com/130385691/236638043-a6302e45-b25a-4c53-a3df-e97556dd6ef3.png)

### Environment

Browser: Microsoft Edge 114.0.1807.6 (Official build) dev (64-bit) 
Scratch Addons version: 1.31.2
Operating system: Windows 11

**Comment by WorldLanguages** [comment]
Can't easily reproduce. Race conditions might be in play here.

**Comment by mybearworld** [comment]
> Can't easily reproduce. Race conditions might be in play here.

That's odd.

---

In case this is helpful somehow, here's the console with and without the error:

**With error**
![with error](https://user-images.githubusercontent.com/130385691/236662224-1952fc58-4113-4c73-94c6-2146eedf73fb.png)

**Without error**
![without error](https://user-images.githubusercontent.com/130385691/236662244-cb60fb69-54d5-40de-aff2-77e7a7fe591b.png)

**Comment by WorldLanguages** [comment]
@mybearworld That looks... confusing.
Old attempts of the `scratchblocks` addon did in fact block the original scratchblocks script from running, but the final version does not. So why would scratchblocks be undefined?
So if scratchblocks is undefined, it should mean it's not Scratch Addons causing it? Can you try to take the first screenshot but this time with extensions disabled?

**Comment by mybearworld** [comment]
> Can you try to take the first screenshot but this time with extensions disabled?

I only have one extension, and that's some userstyles/scripts I made, where all user scripts are surrounded by `(() => {...})();`, but weirdly enough, even though I'm not creating any variables globally, it does seem to change the errors (same effect, though):
![the new error messages](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/ca505868-c8a2-47d2-b3cd-c14d5794093f)

**Comment by WorldLanguages** [comment]
@mybearworld So both Scratch Addons and your own scripts are disabled when taking your last screenshot?

**Comment by mybearworld** [comment]
> @mybearworld So both Scratch Addons and your own scripts are disabled when taking your last screenshot?

No, that was just my own disabled. With SA disabled as well, there is no console output whatsoever.

**Comment by mybearworld** [comment]
Disabling that addon does not fix it.

**Comment by WorldLanguages** [comment]
@mybearworld Any additional info?

**Comment by mybearworld** [comment]
Not really.

**Comment by mybearworld** [comment]
I've just tried to replicate this with every addon (except for `scratchblocks`) disabled, and it does still happen. The errors seem different yet again, though:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/524dc89d-b42b-4d51-b970-2c16f92e8e2b)

**Comment by WorldLanguages** [comment]
Wanted to note there's a bit of `scratchblocks` code outside of the "addons" folder too, in order to run some code as fast as possible: https://github.com/ScratchAddons/ScratchAddons/issues/5466#issuecomment-1360880549

**Comment by WorldLanguages** [comment]
@NotFenixio Any relevant info or console errors? Don't worry if you don't have those

**Comment by NotFenixio** [comment]
These are the only errors that seem relevant.
![image](https://github.com/ScratchAddons/ScratchAddons/assets/103071021/56f56fd6-65b5-4cfa-bfaa-5e900757062d)
Without the addon "ScratchBlocks 3.0 on forums" I've never seen this error, but with the addon enabled it happens everytime.

**Comment by just-a-hriday** [comment]
The same thing seems to happen to me when I _do_ stay on the tab as well - but only sometimes. I have no idea what causes it.
In those cases, I get some errors that leaving the tab while loading doesn't get:

![](https://github.com/ScratchAddons/ScratchAddons/assets/73294041/5b6656c5-db41-4b64-8c0a-b88481045477)
<sup>

Strangely, these seem to be coming from vanilla scratch js files.

The errors are thrown immediately after the scratchblocks addon starts running, but I'm not sure if that means anything.

**Comment by WorldLanguages** [comment]
This addon doesn't exist anymore
