### ISSUE TITLE
Text to speech (TTS) captions in projects

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6016]
### Why this would be helpful

It's a relatively easy addon to make and it can be helpful for accessibility.

According to GrahamSH, `it's [a] widely requested [addon]` (haven't verified myself)

### How this addon works

Here's an example screenshot:

![image](https://user-images.githubusercontent.com/17484114/236650784-fce053b5-4066-46db-b96c-6d4b9548c0bb.png)

It should support dynamic values like joins and variables.

### Additional context

There's a closed PR (implementation) here: #5514

**Comment by mybearworld** [comment]
[Here](https://scratch.mit.edu/discuss/topic/536596/)'s a suggestion (on Scratch) about this.

**Comment by Samq64** [comment]
Duplicate of #5483

**Comment by Samq64** [comment]
Why isn't GitHub closing the issue when clicking close with comment?
