### ISSUE TITLE
Extension policy comment censoring (commenting "Scratch Addons") bugs

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6028]
### Description

The implementation of #2089 is not perfect. Sometimes, comments that mention "Scratch Addons" go straight to the internet without us letting the user know about the extension policy.

### Steps to reproduce

- go to the projects tab of a studio, refresh page, wait a few seconds, click comments tab
 (or when using a direct link: go to comments tab, refresh page)
- disable internet (in order to avoid your account from actually getting muted)
- attempt commenting "test", to see if the comment will be sent to the server (to avoid getting accidentally muted)
- attempt commenting "test: scratch addons" 

There might be other edge cases in studios, profiles and projects. We should test: loading more comment pages, sending replies, etc.

### Environment

Scratch Addons v1.32.0
Worth testing in both Chromium and Firefox

**Comment by WorldLanguages** [comment]
Thanks @CST1229 for the reproduction steps.

**Comment by DNin01** [comment]
I tried adding `console.log` below `if (!textarea) return;` and trying to post some empty comments and every time I tried it there was a message in the console. It worked when replying and posting top-level comments in all areas, so it doesn't look like that's the problem, but rather `shouldCaptureComment`, but I'm not 100% sure.

**Comment by WorldLanguages** [comment]
The code handling project comments might also be hurting performance even when inside the editor.
