### ISSUE TITLE
Auto add class and id to elements

### ISSUE THREAD

**Issue by StioStudio** [ScratchAddons/ScratchAddons#6029]
### Why this would be helpful

It is very hard to select elements, aspecialy on the homepage. I need to do a lot of advanced CSS to get them, and I don't even know if it works in firefox. So having easy to select elements like "SA-featured-projects" would be helpful.

### My suggestion

Adding classes or ids to elements. Could be smart to have "SA-text" in them so it does not crash with scratch. 

### Possible alternatives

I don't know

**Comment by StioStudio** [comment]
Add to those that allready have too, so that we don't need to mind if scratch changes some

**Comment by WorldLanguages** [comment]
I will close this as rejected.
Adding IDs to elements will be a waste of time if no addons are going to use some of them. It would also have performance implications and we'd have to figure out optimizations.
Addons may create JS modules that handle this (and potentially use them across more than 1 addon) if really necessary, in a case-by-case basis.

**Comment by StioStudio** [comment]
> I will close this as rejected. Adding IDs to elements will be a waste of time if no addons are going to use some of them. It would also have performance implications and we'd have to figure out optimizations. Addons may create JS modules that handle this (and potentially use them across more than 1 addon) if really necessary, in a case-by-case basis.

Ok understandable. I will add them my self in the addon with JS and select them with CSS
