### ISSUE TITLE
Recently viewed forums

### ISSUE THREAD

**Issue by ghost** [ScratchAddons/ScratchAddons#603]
An addon where you can see all the forums you viewed.

**Comment by pufferfish101007** [comment]
The problem is,  it'll only record them when you're using the addon. If you're on a different device, it won't save. But it might be useful, although we'd have to implement extension storage into the addon.* api.

**Comment by GrahamSH-LLK** [comment]
I feel like this is starting to get into the iffy territory. We'd have to make sure that people know that the info can _never_ get back to us, and provide a clear button. Otherwise, this would be an awesome addon! Once @WorldLanguages implements proper popups, this could be an awesome reality!

**Comment by WorldLanguages** [comment]
Use browser history.
