### ISSUE TITLE
Clone counter, 60fps, and mouse position rely on CSS selectors that may change in the next Scratch update

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#604]
**Describe the bug**

i did the lazy code and forgot about this

eg. https://github.com/ScratchAddons/ScratchAddons/blob/fde7a805344cc2364b9ce4f75835413fcfb128c0/addons/clones/userscript.js#L7

https://github.com/ScratchAddons/ScratchAddons/blob/fde7a805344cc2364b9ce4f75835413fcfb128c0/addons/60fps/userscript.js#L20

https://github.com/ScratchAddons/ScratchAddons/blob/master/addons/mouse-pos/userscript.js#L7

**Comment by YOYITsM3M8** [comment]
Oh noes jeffalo was lazy and people might suffer!

**Comment by TheColaber** [comment]
Simply replace
https://github.com/ScratchAddons/ScratchAddons/blob/fde7a805344cc2364b9ce4f75835413fcfb128c0/addons/clones/userscript.js#L7
with 
```javascript
 let bar = await addon.tab.waitForElement("[class^='.controls_controls-container']", { markAsSeen: true }); 

```

**Comment by JeffaloBob** [comment]
thanks! if i have time i'll try to make a pr

**Comment by TheColaber** [comment]
> thanks! if i have time i'll try to make a pr

I can do it if you want... up to you

**Comment by JeffaloBob** [comment]
> > thanks! if i have time i'll try to make a pr
> 
> I can do it if you want... up to you

that would be nice :)

**Comment by Hans5958** [comment]
now I get it you don't like capital letters, but punctuations, come on man.

**Comment by TheColaber** [comment]
> > > thanks! if i have time i'll try to make a pr
> > 
> > 
> > I can do it if you want... up to you
> 
> that would be nice :)

Ok, I'll do it now.

**Comment by WorldLanguages** [comment]
Keep in mind, it looks like these don't actually change. Dark theme userstyles have been using the same class names since 2019.
