### ISSUE TITLE
middle-click-popup bug: Partially typed 'of' blocks created with wrong target.

### ISSUE THREAD

**Issue by hueychen27** [ScratchAddons/ScratchAddons#6042]
### Description

Enable the "Insert blocks by name" addon.
When you search up something like "x position of c" and click on the block that says that, a block that says "x position of stage" will appear.

### Steps to reproduce

1. Press control space
2. Search up "x position of sprite" except type it partially like " x position of spr"
3. Click on block that says "x position of sprite"

### Demonstration(s) and additional context

What comes out:
![x_position_of_Stage](https://github.com/ScratchAddons/ScratchAddons/assets/78285518/cbc05dde-951c-4876-871b-d623f1a9898d)
What is expected:
![expected](https://github.com/ScratchAddons/ScratchAddons/assets/78285518/a215023f-963b-4356-9ed3-9ae6f6d667f4)

### Environment

Browser: Firefox 102.10.0esr
Scratch Addons version: v1.31.2
Operating system: Kali Linux

**Comment by Tacodiva** [comment]
I am unable to reproduce this. Does it happen on a new blank project?

**Comment by hueychen27** [comment]
It happens on every project with a sprite.

**Comment by CST1229** [comment]
Can reproduce, but it only seems to happen on the Stage:

https://github.com/ScratchAddons/ScratchAddons/assets/68464103/ac34ede8-5238-4fd1-bc45-fe6a6274ddb6

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0
(Firefox Developer Edition 114.0b3; Windows 10)
SA version: 1.31.2

**Comment by hueychen27** [comment]
No, you got to click it and not press enter.

**Comment by hueychen27** [comment]
https://github.com/ScratchAddons/ScratchAddons/assets/78285518/cd811c03-b334-4ba9-8e87-21efdaa3642b

**Comment by Tacodiva** [comment]
Yup, can repro now, I wasn't typing it partially that was what I was missing. Thanks for the report.

**Comment by hueychen27** [comment]
yep
