### ISSUE TITLE
Scratch Addons Broke(For me)

### ISSUE THREAD

**Issue by Ronxlotl** [ScratchAddons/ScratchAddons#6048]
### Description

Scratch addons v1.31.2 became broken the extention page and the dropdown appeared blank, and all addon weren't appearing.

### Steps to reproduce

I don't know any fixes.

### Environment

Browser: <!Brave>
Scratch Addons version: <1.31.2>
Operating system: <!Windows11>

**Comment by WorldLanguages** [comment]
Can't help if we don't know your browser.

**Comment by Ronxlotl** [comment]
> Can't help if we don't know your browser.

Brave Is a browser

**Comment by Ronxlotl** [comment]
> > Can't help if we don't know your browser.
> 
> Brave Is a browser

Wait hold on i'm editing it for other devs to know my browser

**Comment by WorldLanguages** [comment]
Oh I see, it was a markdown mistake.

**Comment by WorldLanguages** [comment]
Try going to `chrome://extensions`, enable developer mode, find Scratch Addons in the list and inspect background/background.html

**Comment by Ronxlotl** [comment]
Theres an "Find Errors" Feature For Brave I'm Screenshotting Two Errors That Brave Found

**Comment by Ronxlotl** [comment]
Yeah Theres 90 Errors Name "ERR_FILE_NOT_FOUND"

**Comment by WorldLanguages** [comment]
I think those can be ignored, anything else?
Post screenshots if you can

**Comment by Ronxlotl** [comment]
Hold on

**Comment by Ronxlotl** [comment]
The extenstion Page Blank
![Screenshot 2023-05-14 111501](https://github.com/ScratchAddons/ScratchAddons/assets/111940602/eb4646d8-7987-43a4-8be9-db2231ac1a6e)

**Comment by WorldLanguages** [comment]
I meant screenshots of any errors in the inspect view

**Comment by WorldLanguages** [comment]
Did you try restarting your browser? Type `brave://restart` into the address bar and press enter

**Comment by Ronxlotl** [comment]
It still doesn't fix scratch addons

And heres the screenshots
![Screenshot 2023-05-14 112351](https://github.com/ScratchAddons/ScratchAddons/assets/111940602/7c627329-89f1-4c1e-bb51-6c578280de1b)
![Screenshot 2023-05-14 112417](https://github.com/ScratchAddons/ScratchAddons/assets/111940602/3c19e323-eaef-40c4-aa84-f3ec79db876f)
![Screenshot 2023-05-14 112451](https://github.com/ScratchAddons/ScratchAddons/assets/111940602/1291eef2-a243-4843-b8d8-bbd98c1dafe4)
![Screenshot 2023-05-14 112519](https://github.com/ScratchAddons/ScratchAddons/assets/111940602/f4e1c102-5c04-4293-bf49-8d25387e39d8)
![Screenshot 2023-05-14 112545](https://github.com/ScratchAddons/ScratchAddons/assets/111940602/f1d88a96-36e0-469a-8efa-64fe754b6ae3)
![Screenshot 2023-05-14 112606](https://github.com/ScratchAddons/ScratchAddons/assets/111940602/3957152a-4cd8-488f-b42b-d693862dadf3)
![Screenshot 2023-05-14 112638](https://github.com/ScratchAddons/ScratchAddons/assets/111940602/77296955-6200-4cd2-ac4c-6089ba5fd9e2)

**Comment by Ronxlotl** [comment]
It works now

**Comment by Samq64** [comment]
It looks like there was a problem loading `addonSettings`.

**Comment by WorldLanguages** [comment]
The `IO error: .../LOCK: File currently in use. (ChromeMethodBFE...` error happens quite frequently in Chromium. A browser restart should fix it. We could attempt to show an error message, but the root cause is outside our scope
