### ISSUE TITLE
Changing `discuss-button` settings with compact navbar on duplicates username

### ISSUE THREAD

**Issue by rgantzos** [ScratchAddons/ScratchAddons#6057]
### Description

If you modify the links in the navigation bar in any way using the `discuss-button` feature enabled and you have the compact navbar setting enabled, then the username in the dropdown duplicates.

### Steps to reproduce

1. Enable `discuss-button` and the compact navbar
2. Open a Scratch tab and open the dropdown
3. Make changes to the links in the SA settings

### Demonstration(s) and additional context

https://discord.com/channels/806602307750985799/1107703718033490020

### Environment

Browser: Chrome 113
Scratch Addons version: v1.32.0-pre
Operating system: MacOS

**Comment by DNin01** [comment]
I was just about to report this.

Here are some screenshots:
![Small text "D-ScratchNinja" repeats 4 times](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/3791aa30-31de-4d2f-b772-ff38444b6cc8)
![Big text "D-ScratchNinja" repeats 3 times](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/cb56032b-80c1-41cf-a6bb-b88655825ffb)

**Comment by iqnite** [comment]
Is it a macOS bug? I'm on 1.33.0-pre and it doesn't happen.
