### ISSUE TITLE
Faster project loading prevents inserting sprites from backpack

### ISSUE THREAD

**Issue by the-gunned-noob** [ScratchAddons/ScratchAddons#6062]
idk what addon did it bc i tried every one that shouldve affected it but only way to fix it is by turning off addons pls help i cant put stuff from my backpack in projects

**Comment by DNin01** [comment]
Try turning off Scratch Addons entirely from your browser's Extensions/Add-ons page and see if the issue persists.

It might also be helpful to provide some information about your device such as your browser.

**Comment by DNin01** [comment]
> You've already tried disabling all the backpack addons and it didn't help, right? Could you try disabling "faster project loading"?

I tried dragging things out of my backpack with that addon enabled and they were still inserted, so that's not the problem.

**Comment by DNin01** [comment]
I don't think this is a Scratch Addons problem.

> [I can't drag sprites into projects, and I have absolutely no clue why](https://scratch.mit.edu/discuss/topic/685161/) by GoldenLegend5
>
> [sprites not dropping when unleashed from the backpack](https://scratch.mit.edu/discuss/topic/685130/) by BraidenNO31315
>
> [Backpack Bug](https://scratch.mit.edu/discuss/topic/685117/) by SUSBOOOOOOOI
>
> [Backpack won't let me put sprites into my Scratch Project](https://scratch.mit.edu/discuss/topic/685156/) by vondyhunter420
>
> [I can't put sprites into my project from the backpack](https://scratch.mit.edu/discuss/topic/685150/) by TigersharkSauce
>
> [Please help! I´m not able to import an object from the backpack :(](https://scratch.mit.edu/discuss/topic/685141/) by suumycrafty

**Comment by DNin01** [comment]
Wait a minute, there is a pattern...
> No Flash version**s** detected

Versions means the user uses Scratch Addons.

Let me look into this a little more.

**Comment by DNin01** [comment]
On second test, dragging in sprites logged an error message that Scratch Addons blocked a request.
<sub>(Last time, I actually only tried dragging in sprites with SA disabled)</sub>

So it is Faster project loading. Disabling the addon resolved the issue.

It's interesting how many bug reports this can cause.

**Comment by medlans** [comment]
Oh I was wondering what was happening LOL because I thought someone said that it was doing the same on an iPad, but I misread their post (also I'm not sure if this is just me, but it shows as "version" for me and not "versions" so I had no idea, is that meant to happen)

**Comment by mybearworld** [comment]
That message telling users to make sure Scratch Addons doesn't cause the bug seems not to be working too well...
(Also, does SA add that "versions" so that you can easily tell, or is that the result of something else entirely?)

**Comment by mxmou** [comment]
> (Also, does SA add that "versions" so that you can easily tell, or is that the result of something else entirely?)

It's added intentionally by SA: see #1872 and #5274.

I like the suggestion in https://github.com/ScratchAddons/ScratchAddons/issues/5274#issuecomment-1454733741 because people reading the post would know that the bug might be caused by an extension.

**Comment by medlans** [comment]
> Oh I was wondering what was happening LOL because I thought someone said that it was doing the same on an iPad, but I misread their post (also I'm not sure if this is just me, but it shows as "version" for me and not "versions" so I had no idea, is that meant to happen)
Nevermind, it only happens when you create a new topic in Bugs and Glitches, not when you create a post. Though that could be an issue because I've seen people who remove the user agent part from their topic, and then post it later.

**Comment by WorldLanguages** [comment]
Firefox users are already getting v1.32.1 with this bug fix as of now.
Users who installed from the Chrome Web Store need to wait until v1.32.1 is reviewed. Note that only 60% of users who installed from CWS received the v1.32.0 update, so 40% of them weren't affected. New update v1.32.1 will be released to 100% of users after it's reviewed.
Users who installed from the Edge store have never received the v1.32.0 update so they were never affected by this bug. Edge store is reviewing v1.32.1 now.

When posting feedback on scratchaddons.com/feedback that includes the word "backpack", the user will be automatically recommended to disable the "faster project loading" addon.

**Comment by WorldLanguages** [comment]
Thanks `@medians` for helping out on the Scratch forums! Looks like they have replied to every single bug report about this and encourage users to disable the "faster loading" feature.

**Comment by WorldLanguages** [comment]
> That message telling users to make sure Scratch Addons doesn't cause the bug seems not to be working too well...

Yeah, I'll create a new issue suggesting a different approach for the future: #6067
