### ISSUE TITLE
Forum user-agent is not always modified ("version"→"versions")

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6065]
> (also I'm not sure if this is just me, but it shows as "version" for me and not "versions" so I had no idea, is that meant to happen)
> Nevermind, it only happens when you create a new topic in Bugs and Glitches, not when you create a post. Though that could be an issue because I've seen people who remove the user agent part from their topic, and then post it later.

_Originally posted by @medlans in https://github.com/ScratchAddons/ScratchAddons/issues/6062#issuecomment-1550939949_

**Comment by DNin01** [comment]
Also, this happened to me once or twice and then didn't happen again:
![Text saying No Flash version s s detected](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/8bfbd3c4-6592-4f4c-a9f6-bddda8a53ebd)

**Comment by WorldLanguages** [comment]
+1 from duplicate issue: we should replace the user agent everywhere, not just on new posts of the B&G forum.
