### ISSUE TITLE
Setting seperateors

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6068]
### Why this would be helpful

Some addons have a lot of settings and it can get pretty cluttered.

### My suggestion

Adding an option to the addon manifest that adds a little blank space and maybe a line.

### Possible alternatives

#5719

### Additional context

Related: #2031

**Comment by WorldLanguages** [comment]
I think we could move this suggestion to #5719, and support settings groups without an assigned name.
