### ISSUE TITLE
Improved Function Editing: reorder custom block parameters

### ISSUE THREAD

**Issue by DogCatPuppyLover** [ScratchAddons/ScratchAddons#6073]
### Why this would be helpful

Oftentimes, I would like to add a new input to a function (aka "my blocks"). For example, I might have a function like this:
```
create sprite at x: (x) y: (y) costume: (costume)
```
I might want to add another value, z, for the z-position of the sprite. However, unless I want to delete some of the inputs and rewrite my code, my only option is to add it to the end:
```
create sprite at x: (x) y: (y) costume: (costume) z: (z)
```
This is frustrating, because logically, it should be after x and y. Especially in complicated functions, rewriting it for an aesthetic change simply isn't worthwhile, but it still makes for a bad user experience (especially if you are programming an engine that other Scratchers are meant to use).

A more practical problem is if you created a function with unlabeled inputs, like this:
```
create sprite at (x) (y) (costume)
```
Then, you might want to add labels to your function, to make it easier to use. However, inserting labels between inputs is not possible, and you'd have to delete and re-create the inputs, and rewrite the function.

### How this addon works

When you edit a function, you can click on inputs to rename them. In addition, a "delete" icon appears above the inputs when selected. This addon would add "move left" and "move right" icons above the inputs, allowing you to rearrange them within the function. In addition, if you clicked the "add input" or "add label" buttons while selecting an input or label, it would add the new input or label right after your selection, rather than at the end of the function.

### Possible alternatives

I'm not sure if there are any good alternatives to this--except maybe an option to substitute all instances of one function input for another? That would be able to do the same job, but it would be more complicated and less intuitive.

**Comment by DNin01** [comment]
This addon could be called "Rearrangeable custom block arguments".

**Comment by fractioneater** [comment]
This suggestion has 18 upvotes on the community Discord server, so it looks like people agree on its usefulness.

**Comment by RedGuy12** [comment]
> This suggestion has 18 upvotes on the community Discord server, so it looks like people agree on its usefulness.

Couldn't find it on there, are you able to link me?

**Comment by fractioneater** [comment]
> Couldn't find it on there, are you able to link me?

[This suggestion][1] is the one I mentioned before, and the only one that isn't marked as a dupe. There are a few more that are marked as dupes of the first one, though.

[1]: <https://ptb.discord.com/channels/806602307750985799/1019732460382191646/threads/1036240906996699228>
