### ISSUE TITLE
Revert #6053 before release

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6084]
See #6053

In the future we might find better ways to deal with this.

**Comment by DNin01** [comment]
I think we could use a build step to add that ability for developers only. (Can build steps even do that? I haven't done npm or Node.js commands before.)

**Comment by Hans5958** [comment]
With enough courage, it is possible to implement such feature, by adjusting the `manifest.json` generation (IIRC there is an packer that do these without the build step) and keeping the other parts of code thats related to the new domains.

**Comment by WorldLanguages** [comment]
> My idea would be to use a build step to add that ability just for developers. (Would that work? I haven't done npm or Node.js commands before.)

If it's just for the manifest, it might make more sense to have a build step that removes this ability for the store release other than the other way around. Worth considering both solutions.

**Comment by apple502j** [comment]
Let's have the packer do its job, @WorldLanguages ?

**Comment by WorldLanguages** [comment]
Idea sounds good, but we can discuss the details later. For example, I think we could consider removing browser_specific_settings from the non-release version, but it's also a bad idea since `chrome.runtime.id` will work differently in Firefox. It might also be annoying for contributors working in Firefox as they probably would have to import their settings file each time they open their browser.
Having a versionName property in the manifest probably makes no sense either if we use the packer for this.
