### ISSUE TITLE
Some addons need the blue color updated

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6091]
Scratch is changing the editor's accent color from `#4d97ff` to `#855cd6`. Editor addons that still use blue will need to be updated to use purple for the Scratch update. You can see by [searching](https://github.com/search?q=repo%3AScratchAddons%2FScratchAddons+%284d97ff+OR+%22215%2C+100%25%2C+65%25%22+OR+--editorDarkMode-primary+OR+--editorDarkMode-highlightText+OR+--editorDarkMode-menuBar%29+path%3Aaddons%2F+NOT+path%3Aaddons%2Fscratchr2%2F&type=code) that there are several things we need to do, excluding website addons.

#### Addons in the editor that need an update include:
- [x] `debugger` <sub>27, 80, 218, icons</sub>
- [x] `hide-flyout` <sub>88, 89, 98</sub>
- [x] `hide-stage` <sub>Icon</sub>
- [x] `onion-skinning` <sub>5</sub>
- [x] `paint-snap` <sub>5</sub>
- [x] `pause` <sub>12</sub>
- [x] `progress-bar` <sub>41</sub>
- [x] `sprite-properties` <sub>64, 77</sub>
- [x] `variable-manager` <sub>Icon</sub>

Handled by #6094

Edit: I just realized the website is receiving the same changes too. Here's a [search](https://github.com/search?q=repo%3AScratchAddons%2FScratchAddons+%284d97ff+OR+%22215%2C+100%25%2C+65%25%22+OR+--darkWww%29+NOT+--editorDarkMode+path%3Aaddons%2F&type=code) that should help us find the addons that need an update.

#### Addons on the website that need an update include:

- [x] `old-studio-layout` <sub>A lot of lines</sub>
- [x] `scratchr2` <sub>A lot of lines</sub>
- [x] `dark-www` <sub>A lot of lines</sub>

A content script, too:
- [x] [`modal.js`](https://github.com/ScratchAddons/ScratchAddons/blob/ac844e45dcba6c7f5d99a85f5f3bf8a3fd13b679/addon-api/content-script/modal.js#L92)

The following apply to scratchr2 pages which may or may not have the accent color updated but will still be modified by `dark-www` (note: https://github.com/ScratchAddons/ScratchAddons/issues/6115#issuecomment-1566244936):
- [x] `customize-avatar-border` <sub>91</sub>
- [x] `necropost-highlighter` <sub>2</sub>
- [x] `scratchstats` <sub>178</sub>

Handled by #6265

Let me know if I missed anything.

**Comment by Samq64** [comment]
I didn't realize it was used in so many places. Maybe a CSS variable could be set and overriden with editor-dark-mode?

**Comment by Samq64** [comment]
Maybe it's not worth it though since the colour probbably won't be changed again.

**Comment by WorldLanguages** [comment]
Probably not worth for this specifically, but I'm open to the idea of certain CSS variables defaults that aren't handled by any specific addon and always exist (as long as the extension is running on the page, of course).

**Comment by Secret-chest** [comment]
I'd like icons to be affected by `editor-dark-mode`

**Comment by WorldLanguages** [comment]
> Probably not worth for this specifically, but I'm open to the idea of certain CSS variables defaults that aren't handled by any specific addon and always exist (as long as the extension is running on the page, of course).

@mxmou Do you think this could be useful? For example, there's over 25 instances of `var(--darkWww-box, white)` which could be shortened to just `var(--darkWww-box_)`. Just an example. There might also be other reasons why we might want to add our own CSS variables that are defined even if no addons have injected any CSS (but addons may override them). Any ideas?

**Comment by WorldLanguages** [comment]
Can we close this...?

**Comment by DNin01** [comment]
> Can we close this...?

Yeah, I was thinking so too.
