### ISSUE TITLE
Improving "Save blocks as image" addon

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#6096]
### Why this would be helpful

As a teacher, I spend a lot of time creating slides with Scratch scripts' images. The "Save blocks as image" addon requires to:

- right-click the script
- select the desired option
- click import in my slide authoring tool
- find the exported picture folder
- select the exported picture
- click import

So, I don't use the Scratch Addons "Save blocks as image" addon as it is tool slow, and I simply create a snapshot of the screen and paste it in my authoring tool. The image is not PNG/SVG, but it is faster.

### My suggestion

Add to the Scratch Addons right-click menu the possibility to copy the SVG/PNG image of the script to the clipboard so that using the script image will require just 3 steps (right-click, select option, paste) instead of 6.

**Comment by WorldLanguages** [comment]
> click import in my slide authoring tool

Can't you drag and drop from the browser's downloaded files list?

**Comment by sfederici** [comment]
I use a mac. If I switch to another application (e.g to the browser) I don't see the authoring tool window anymore. In order to see both windows (the tool and the library) I should either 1) not use my authoring tool full screen (something that I really don't want to; the available working space is always too small for me) or 2) keep the browser's downloaded files list window minimized in the dock and, every time, i) click the browser's downloaded files list icon in the dock to enlarge it ii) drag the file, iii) re-minimize the browser's downloaded files list. Again, 6 operations instead of 3.

**Comment by WorldLanguages** [comment]
Looks like we have no other option but to add this feature directly to the extension.
Initially I thought this problem was general enough, right? You can run into this problem in thousands of web applications that only support image download but not copying the image to the clipboard.

**Comment by BroJac5246** [comment]
I think we should do this, although I personally support this because I don't want to have to delete the file after I download it.

**Comment by TheColaber** [comment]
I had an idea to rework this entire addon, to help with these changes but to also make it take up less options in the right click menu. So instead of there being those 4 options when you right click on the block, there would be one: "Save block as image". When you click it, it will open up a popup (like how we do for the recorder addon) showing what block/stack was selected. From there, you can select to just save the block or the entire stack, and if you want to download as an svg, png, or save to clipboard. It would be 3 clicks (Right click block, Select "Save block as image", Click "Copy to clipboard"), while at the same time introducing better UI/UX and taking up 3 less options in the right click menu.

**Comment by Samq64** [comment]
> So instead of there being those 4 options when you right click on the block, there would be one: "Save block as image". When you click it, it will open up a popup (like how we do for the recorder addon) showing what block/stack was selected. From there, you can select to just save the block or the entire stack, and if you want to download as an svg, png, or save to clipboard.

#4919 could be another option.

**Comment by sfederici** [comment]
Menus with less options are a value, but it would take a further click, right?

**Comment by sfederici** [comment]
> #4919 could be another option.

A submenu (opened with hover, without the need for a further click) would be better for me

**Comment by Jazza-231** [comment]
@sfederici This is so old I'm not even sure you're still active. I'm very sorry it took so long, but this will become a feature in the near future, hopefully in the next release or two.

**Comment by sfederici** [comment]
I'm active and still in needs for this addon. So, thanks a lot!

**Comment by WorldLanguages** [comment]
@sfederici Please take a look at the 2 screenshots on the first post of #6830. It should now take 3 clicks to copy a block as a PNG image. If you include pasting, it's 4 clicks.
