### ISSUE TITLE
[June 28th] Scratch will be updating the website's accent color and other colors

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6115]
The website is being updated to use the new purple accent color too! You can see the progress [here](https://github.com/scratchfoundation/scratch-www/tree/feature/color-contrast).

Trouble is, there are quite a few more addons that will need to be modified.

As per usual, we'll probably offer a preset to go back to the blue color for users that prefer that.

**Comment by Samq64** [comment]
Will these changes also be released on June 7th?

**Comment by DNin01** [comment]
> Will these changes also be released on June 7th?

I don't know for sure, but I'm guessing they will be.

**Comment by Samq64** [comment]
Do you know if the changes would also effect `scratchr2` pages?

**Comment by DNin01** [comment]
> Do you know if the changes would also effect `scratchr2` pages?

Probably not, but `dark-www` would affect both pages, so we could either not allow changing the accent color on `scratchr2` pages or have `dark-www` change the color and update any addons to adapt to it. If `dark-www` is disabled, those addons should stay the same to be consistent.

**Comment by mxmou** [comment]
> > Do you know if the changes would also effect `scratchr2` pages?
> 
> Probably not, but `dark-www` would affect both pages, so we could either not allow changing the accent color on `scratchr2` pages or have `dark-www` change the color and update any addons to adapt to it. If `dark-www` is disabled, those addons should stay the same to be consistent.

Another option is to add separate settings for 2.0-styled pages.

**Comment by DNin01** [comment]
> > > Do you know if the changes would also effect `scratchr2` pages?
> > 
> > 
> > Probably not, but `dark-www` would affect both pages, so we could either not allow changing the accent color on `scratchr2` pages or have `dark-www` change the color and update any addons to adapt to it. If `dark-www` is disabled, those addons should stay the same to be consistent.
> 
> Another option is to add separate settings for 2.0-styled pages.

That amount of customization would be overwhelming unless we figure something out.

**Comment by Samq64** [comment]
> Another option is to add separate settings for 2.0-styled pages.

If we do that, I think only the navigation bar and link colours need separate settings, and they should be hidden when Scratch 2 to Scratch 3 is enabled.

**Comment by DNin01** [comment]
> > Another option is to add separate settings for 2.0-styled pages.
> 
> If we do that, I think only the navigation bar and link colours need separate settings, and they should be hidden when Scratch 2 to Scratch 3 is enabled.

It's still not ideal for the user experience - I think some users might be briefly confused in different ways, but it might be all we can do.

**Comment by Samq64** [comment]
The yellow headers will also be replaced with green ones.
![image](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/4a999b2f-be66-4424-9365-5084f891fd58)

The tabs are also purple now.

**Comment by WorldLanguages** [comment]
> Do you know if the changes would also effect `scratchr2` pages?

I think we should assume they will.

**Comment by WorldLanguages** [comment]
Note: I've renamed the `Scratch color changes` milestone as `Scratch color changes (v1.33.1)`.
We're going to merge some new addons and features into v1.33.0, as well as compatibility code for the new version of the editor (including the block colors menu).
Migration code for the new colors and most CSS changes will belong in v1.33.1, which will reach users after the Scratch update, and not before.

**Comment by Secret-chest** [comment]
> Will these changes also be released on June 7th? (by the Scratch Team)
Yes, they said so in the translateable forum post.

**Comment by Secret-chest** [comment]
> Another option is to add separate settings for 2.0-styled pages.

Let's treat the `scratchr2` as obsolete.

**Comment by mxmou** [comment]
> > Another option is to add separate settings for 2.0-styled pages.
> 
> Let's treat the `scratchr2` as obsolete.

Some commonly used pages (profile, My Stuff, forums) haven't been migrated to scratch-www yet.

**Comment by medlans** [comment]
What would happen on 2.0 pages? Would there be a 2.0 preset?

**Comment by WorldLanguages** [comment]
@medlans As far as we know, Scratch will update the navbar of 2.0 pages too.
We will provide "old default colors" presets for both the website and editor, so that it's easy to return to the old colors in the whole site: project editor, 3.0 pages and 2.0 pages.

**Comment by WorldLanguages** [comment]
> The yellow headers will also be replaced with green ones. ![image](https://user-images.githubusercontent.com/81489795/241587046-4a999b2f-be66-4424-9365-5084f891fd58.png)
> 
> The tabs are also purple now.

Note that we probably won't provide a way to bring back old banner colors (such as the old yellow Explore) for the v1.33.2 update. Correct me if I'm wrong.

**Comment by Secret-chest** [comment]
> Note that we probably won't provide a way to bring back old banner colors (such as the old yellow Explore) for the v1.33.2 update. Correct me if I'm wrong.
Even if we won't, I hope we will soon have an addon to change them.

**Comment by WorldLanguages** [comment]
Related: https://github.com/ScratchAddons/ScratchAddons/pull/6268#issuecomment-1611881366

**Comment by WorldLanguages** [comment]
> Note that we probably won't provide a way to bring back old banner colors (such as the old yellow Explore) for the v1.33.2 update. Correct me if I'm wrong.

Do we have a dedicated issue for this, so that we can close this one?

**Comment by Samq64** [comment]
> I'll make one

#6350
