### ISSUE TITLE
`editor-theme3`: Combine "colored on white background" and "colored on black background" into one setting

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6118]
### Why this would be helpful

These two settings make the blocks look like neon signs. There are two of these, one for a black background and one for a white background, which I suspect is to support both light- and dark-themed editors. But does anyone need "colored on white background" for dark themes or "colored on black background" for light themes?

### My suggestion

These two settings could be combined into one setting named "neon". This block appearance would be the same as before, but the background color would be derived from the workspace background set in `editor-dark-mode`, so it would work in both light and dark themes.

But this could cause problems for the "Black" preset, which uses "colored on black background". This only works well in dark mode, and with the recent change to use the high-contrast block palette to increase contrast against the dark background, it's even worse in light mode now.

We could solve that by:
1. Removing the preset
2. Changing the preset based on the workspace background (if the user has `editor-dark-mode` enabled and is using a dark workspace background, this would use high-contrast colors for the blocks. Otherwise, it would use darker colors to increase contrast against the light background.)

**Comment by Secret-chest** [comment]
Remember, is the setting you're removing harmful in any way?

**Comment by mxmou** [comment]
> Removing the preset

These options were added specifically to make the Black preset possible.

> Changing the preset based on the workspace background (if the user has `editor-dark-mode` enabled and is using a dark workspace background, this would use high-contrast colors for the blocks. Otherwise, it would use darker colors to increase contrast against the light background.)

I think this would be too complex.

**Comment by DNin01** [comment]
> > Changing the preset based on the workspace background (if the user has `editor-dark-mode` enabled and is using a dark workspace background, this would use high-contrast colors for the blocks. Otherwise, it would use darker colors to increase contrast against the light background.)
> 
> 
> 
> I think this would be too complex.

I was thinking of just showing one of two variants of the preset at a time, if you weren't aware. We could have two versions of this preset (two presets with basically the same settings but each designed for a different theme), one for light and one for dark, and one of them would be hidden based on whether the workspace color set in `editor-dark-mode` was considered light or dark.

But supporting `if` for presets just for this addon might not be worth it.

**Comment by DNin01** [comment]
Another option is to create two variants of the Black preset and name them accordingly: "Neon (dark)" and "Neon (light)", and always show them. The user will probably know what to do.

**Comment by mxmou** [comment]
> I was thinking of just showing one of two variants of the preset at a time, if you weren't aware. We could have two versions of this preset (two presets with basically the same settings but each designed for a different theme), one for light and one for dark, and one of them would be hidden based on whether the workspace color set in `editor-dark-mode` was considered light or dark.
> 
> But supporting `if` for presets just for this addon might not be worth it.

What would happen when the user changes the workspace background? The way you described it sounds like they would have to go to the `editor-theme3` settings and enabled the same preset again to switch to the appropriate version.

> Another option is to create two variants of the Black preset and name them accordingly: "Neon (dark)" and "Neon (light)", and always show them. The user will probably know what to do.

I don't think every user would understand the difference. Even if we assume they would, the way it currently works allows more customization and doesn't need such UX compromises.

**Comment by DNin01** [comment]
Guess changing this is harder and less important than I thought. Alright then, it's fine the way it is.
