### ISSUE TITLE
Let people know that there might be some issues after the Scratch color changes

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6119]
It's possible that our addons will have some issues and inconsistencies after Scratch changes the design. It would be nice to let users know why anything looks weird in case that happens. One way we could do this is by releasing a version of Scratch Addons immediately after the update that displays a notification that looks something like this:

> Scratch just had a big update that changes some of the colors around the website. The Scratch Addons team has been working hard to update addons to accommodate, but you might still see some strange things for a little while. If you want, you can disable any themes from Scratch Addons' settings.

**Comment by WorldLanguages** [comment]
We can display an update notification for v1.33.1 (even though we don't typically show a different update notification for patch releases).

**Comment by WorldLanguages** [comment]
> It would be nice to let users know why anything looks weird in case that happens.

Also a good opportunity to let them know the "new purple" is not our fault and that it can be quickly reverted in Scratch Addons settings if they wish.

**Comment by WorldLanguages** [comment]
Something like this? @BroJac5246 @Chiroyce1 @Samq64 @mxmou

![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/8772241c-b25e-46ee-89d0-6474abefeb9a)

**Comment by Samq64** [comment]
I would add the word the before Scratch Addons settings but I think it's always been that way. And maybe the word big could be removed, but then again,  t end users a brand colour change is pretty major.

**Comment by DNin01** [comment]
> Something like this? @BroJac5246 @Chiroyce1 @Samq64 @mxmou
> 
> ![image](https://user-images.githubusercontent.com/17484114/246694958-8772241c-b25e-46ee-89d0-6474abefeb9a.png)

I would want to let people know that:
- Scratch made an update.
- **There may be some issues with other addons.**
- **They might want to reset the settings back to default, turn off the addon or choose a preset so they can see the changes Scratch made.**

I personally wouldn't say that the user can revert the changes in the notification because if we leave that information in, the user may be more likely to decide to switch the colors back and never move forward instead of leaving the new colors on and adapting to them. The original blue color can't be the norm forever.

**Comment by Secret-chest** [comment]
> I personally wouldn't say that the user can revert the changes in the notification because if we leave that information in, the user may be more likely to decide to switch the colors back and never move forward instead of leaving the new colors on and adapting to them. The original blue color can't be the norm forever.

It can't be, but some users may be pleased to hear they can revert it.

**Comment by mybearworld** [comment]
> I personally wouldn't say that the user can revert the changes in the notification because if we leave that information in, the user may be more likely to decide to switch the colors back and never move forward instead of leaving the new colors on and adapting to them. The original blue color can't be the norm forever.

I think we should mention the possibility, but a bit more subtle somehow. The way it's worded in the screenshot makes it sound like you _should_ revert it.

**Comment by WorldLanguages** [comment]
Open to suggestions. Don't want to ask ChatGPT to find a way to make it more subtle.

**Comment by DNin01** [comment]
Could be something like this:
> Scratch just released an update that changes some of the colors around the website. If you'd like to update your settings to use these new colors, go back, or otherwise customize the colors, you can reset or change any themes from Scratch Addons' settings.
>
> Scratch Addons' developers have been working hard to update addons to work with the changes, but you might still see some strange things for a little while.

I tried to make sure that the point of the message wasn't to tell you that you can revert the changes.

**Comment by WorldLanguages** [comment]
See #6256.
