### ISSUE TITLE
Enhanced Developer Tools

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#612]
The Scratch Feveloper Tools is great but there are some suggestions I have. @griffpatch made an amazing search bar to search functions and variables. But one thing I think the function search lacks is to see where we are calling these functions. Currently the tool only finds the definitions of functions but it would be better to also find where we used these functions.

Note: I am currently working on the new website look for scratchaddons.com

**Comment by pufferfish101007** [comment]
In the main extension by griffpatch (https://github.com/griffpatch/scratch-developer-tools) I'm fairly sure it does take you to where it's called, I remember using it... Is the addon different to the extension or is my memory faulty?

**Comment by GrahamSH-LLK** [comment]
> Note: I am currently working on the new website look for scratchaddons.com
You're going to have to clear it with @Hans5958. He's in charge of the website. What kind of changes are you working on? Where's your fork?

**Comment by WorldLanguages** [comment]
Please open this issue in griffpatch's repo - in a way, the addon is just a manual "mirror" of the extension
