### ISSUE TITLE
Profile and Mystuff Navigation Bar is outdated

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#613]
**Old Scratch 2.0 Navigation Bar**

This may be just a bug on scratch but I thought we could change the old navigation bar in `scratch.mit.edu/mystuff` and `scratch.mit.edu/users/*`. I think we might be able to use the 3.0 CSS and images to modify the old navbar with `const navbar = document.getElementById("navigation")` something like that in `"content_scripts"` which is probably in manifest.json but anyways just a suggestion to fix that bug on scratch.

**Comment by TheColaber** [comment]
I think we have an addon that is "Scratch 2 > 3" or something like that that does this...

**Comment by WorldLanguages** [comment]
`Scratch 2.0 → 3.0` does this
