### ISSUE TITLE
Scratch Messaging: show lovers and favers of project

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#614]
**We need to know who loved favourited or remixed our project**

In the [Scratch Messages](https://scratch.mit.edu/messages) page usually when someone loves/faves/remixes your project you get notified who did it. I know you developers wanted to keep the loves/faves/remix notifications compact but it should atleast this should be an option in the **settings** page for scratch addons.

**Comment by WorldLanguages** [comment]
Hmm, I see your point. This is likely a result of Scratch Messaging built by me and griffpatch, who get too many loves to check each one :P
