### ISSUE TITLE
Check marks for Scratch Team members

### ISSUE THREAD

**Issue by YandeMC** [ScratchAddons/ScratchAddons#6148]
### Why this would be helpful

some people might not understand the asterisks meaning

### How this addon works

add a checkmark to scratch team members to help prevent impersonation to people who dont know the asterisks meaning
![image](https://github.com/ScratchAddons/ScratchAddons/assets/113806118/52eab4ff-d071-4b04-b1f6-2bb4925330e5)
![image](https://github.com/ScratchAddons/ScratchAddons/assets/113806118/ed8c90c9-a66b-4dc2-9041-4074bc2148e5)

### Additional context

[discord suggestion](https://discord.com/channels/806602307750985799/1063028603077525546)
#6145

**Comment by WorldLanguages** [comment]
![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/9e5e920e-f214-4293-9a84-04cf7c770bc1)

**Comment by Samq64** [comment]
> ![image](https://user-images.githubusercontent.com/17484114/243225205-9e5e920e-f214-4293-9a84-04cf7c770bc1.png)

Has someone opened an issue for that yet?

**Comment by WorldLanguages** [comment]
I think a forum post in scratch.mit.edu might be more suitable.
