### ISSUE TITLE
Accept Studio Invites in One Click

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#615]
**It is kind of annoying when you have to got to the curator tab every time you have a studio invite** 

A very neat way to handle this would be to add a drop down section under a studio invite message displaying an accept button and an ignore button. I don't know how to interact with scratch studio curator data because I am still a front end web developer. But I am assuming @WorldLanguages knows how to handle scratch curator data

**Comment by pufferfish101007** [comment]
This would be very cool! This could be quite easy to implement and it would still be all front end - just add an extra button that when clicked makes an api call, depending on the link to the curator tab.
Do you mean on the extension's messages oage in the popup, scratch.mit.edu/messages or both? If it's just in the popup, this could be added to the messahing extension quite easily.
Eeither way, I'd love to have this!

**Comment by DogCatPuppyLover** [comment]
I might create it myself, but if anyone else needs it, here's the ajax code for accepting an invite to a studio:

`$.ajax({
          type: "PUT",
          url: "https://scratch.mit.edu/site-api/users/curators-in/STUDIO_ID/add/?usernames=USERNAME"});
`
