### ISSUE TITLE
`load-extensions` settings not working as expected

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6154]
### Description

`load-extensions` is loading the music and micro:bit extensions even though I disabled those settings. The settings show up correctly on the settings page.

### Steps to reproduce

Not sure yet.

### Demonstration(s) and additional context

Enabling another setting like pen works, but the other two extensions are still loaded. Toggling those extensions on and off didn't help.

The branch I was on was before #5940, so either something got messed up when downgrading, or there is a bug in `load-extensions` on that branch.

### Environment

Browser: Firefox 113
Scratch Addons version: v1.31.1 (#5878)
Operating system: Endeavour OS (Arch Linux), KDE Plasma 5.27

**Comment by WorldLanguages** [comment]
Can you open a different issue about the declarativeNetRequest error message? That looks suspicious

**Comment by WorldLanguages** [comment]
I'll research this before v1.33.0 gets released to stores. Thanks for the potential bug report

**Comment by WorldLanguages** [comment]
> Can you open a different issue about the declarativeNetRequest error message? That looks suspicious

Moved that to #6167
Note that this is completely unrelated to a potential bug in settings storage.

**Comment by WorldLanguages** [comment]
Can't figure out what could be causing this. #5940 has very few meaningful line changes. And none of them affect the settings page or the `addon.settings.get()` API.

If this is actually a bug, it probably can't happen in practice to a real user as you can't go back in time to an old version.

**Comment by apple502j** [comment]
@Samq64 Just to make sure, you are testing with a new project every time? Some extensions cannot be unloaded once added.

**Comment by Samq64** [comment]
> @Samq64 Just to make sure, you are testing with a new project every time? Some extensions cannot be unloaded once added.

No, but there aren't any extension blocks being used. I'll double-check that tomorrow.

**Comment by Samq64** [comment]
When showing and hiding a monitor, the extension stays loaded, but micro:bit doesn't have any monitors, so I'm not sure what's going on there.

**Comment by apple502j** [comment]
Closing until someone finds a repro.

**Comment by WorldLanguages** [comment]
Related: no user report of broken/changed settings after v1.33.x update.
