### ISSUE TITLE
Firefox 113+ partially supports declarativeNetRequest

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6167]
### Description

Users on Firefox 113+ can't post comments from Scratch Messaging nor mark their messages as read. This is because URLs that end with `?sareferer` have lost their special treatment (background/handle-fetch.js)
**Edit: this didn't affect users that installed SA from the Firefox Addons store as we don't ship the declarativeNetRequestWithHostAccess permission as part of our [Firefox manifest](https://github.com/ScratchAddons/ScratchAddons/blob/master/.github/gen-manifest.mjs#L2).**

First column is Chrome, second column is Edge, third column is Firefox:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/b67dec1c-fb0d-4c01-afff-5c5523a1b98d)

(source: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest)

### Steps to reproduce

Inspect the extension background page on Firefox.

![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/cdbbe9e0-ac83-4941-8c61-1a213b58fd67)

### Demonstration(s) and additional context

`domains` is deprecated, but the alternative `initiatorDomains` is only supported since Chrome 101+

### Environment

Firefox 113+
Scratch Addons v1.32.1 or master branch

**Comment by Chiroyce1** [comment]
> ### Steps to reproduce
> 
> Inspect the extension background page on Firefox.
> 
> ![image](https://user-images.githubusercontent.com/17484114/244213161-cdbbe9e0-ac83-4941-8c61-1a213b58fd67.png)
> ### Demonstration(s) and additional context
> 
> `domains` is deprecated, but the alternative `initiatorDomains` is only supported since Chrome 101+
> ### Environment
> 
> Firefox 113+ Scratch Addons v1.32.1 or master branch

Cannot reproduce, Firefox 113, SA v1.32.1, I can post replies and mark my messages as read from the SA messaging popup.

**Comment by Chiroyce1** [comment]
> ### Steps to reproduce
> 
> Inspect the extension background page on Firefox.
> 
> ![image](https://user-images.githubusercontent.com/17484114/244213161-cdbbe9e0-ac83-4941-8c61-1a213b58fd67.png)
> ### Demonstration(s) and additional context
> 
> `domains` is deprecated, but the alternative `initiatorDomains` is only supported since Chrome 101+
> ### Environment
> 
> Firefox 113+ Scratch Addons v1.32.1 or master branch

Cannot reproduce, Firefox 113, SA v1.32.1, I can post replies and mark my messages as read from the SA messaging popup.

**Comment by WorldLanguages** [comment]
@CST1229 Good catch, looks like this is a difference between this repository's manifest.json vs. the one we send to the Firefox store: https://github.com/ScratchAddons/ScratchAddons/blob/master/.github/gen-manifest.mjs#L2

**Comment by CST1229** [comment]
> @CST1229 Good catch, looks like this is a difference between this repository's manifest.json vs. the one we send to the Firefox store: [`master`/.github/gen-manifest.mjs#L2](https://github.com/ScratchAddons/ScratchAddons/blob/master/.github/gen-manifest.mjs?rgh-link-date=2023-06-09T17%3A26%3A07Z#L2)

did you mean to ping chiroyce?

**Comment by WorldLanguages** [comment]
Yeah, @ + C failed at me.
@Chiroyce1

**Comment by Chiroyce1** [comment]
> @CST1229 Good catch, looks like this is a difference between this repository's manifest.json vs. the one we send to the Firefox store: https://github.com/ScratchAddons/ScratchAddons/blob/master/.github/gen-manifest.mjs#L2

Ah I see, so is this redundant now, or is a change still going to be made?

**Comment by WorldLanguages** [comment]
> Ah I see, so is this redundant now, or is a change still going to be made?

Well, Firefox says they'll continue to support webRequestBlocking, but it won't make sense to have 2 pieces of code that do the same thing differently, I think. So after we increase the minimum browser versions we support we can remove webRequestBlocking code entirely.
