### ISSUE TITLE
Volume slider bug: goes above "turbo mode" indicator

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6184]
### Description

![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/ca1c400d-4a43-4400-bb3d-8870f579e74e)

### Steps to reproduce

"Only show slider" setting off.
Enable turbo mode, hover the volume icon.

### Environment

Probably all browsers. Screenshot is from my Chromium browser.
Scratch Addons v1.32.1

**Comment by DNin01** [comment]
No not another oversight!

**Comment by DNin01** [comment]
Looks like we just forgot to hide the text "Turbo Mode" while the user is hovering over the slider. Turbo Mode is a pretty forgettable feature at times.

This bug does not happen when "Always show slider" is on.
