### ISSUE TITLE
`custom-zoom`: Zoom controls showing on color mode change

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6191]
### Description

When the `AUTOHIDE ZOOM CONTROLS` setting is enabled and you change the color mode, the zoom controls show up despite you not hovering over them. This resolves itself when you hover over the zoom controls again.

### Steps to reproduce

On scratchfoundation.github.io/scratch-gui/beta/:
1. Enable the Customizable code area zoom addon
2. Turn on the setting `AUTOHIDE ZOOM CONTROLS`
3. Open the Scratch editor and then change the color mode

### Demonstration(s) and additional context

https://github.com/ScratchAddons/ScratchAddons/assets/106490990/292aed82-e49e-40f4-a296-4f56dfc993a4

### Environment

https://scratchfoundation.github.io/scratch-gui/beta/
Browser: Edge 114
Scratch Addons version: v1.33.0-pre https://github.com/ScratchAddons/ScratchAddons/commit/ffc78bf8438eb0296ffc342552b49f68ebd5592e
Operating system: Windows 10

**Comment by WorldLanguages** [comment]
Nice catch!

**Comment by mxmou** [comment]
This can already happen in the current version of Scratch when changing the language.
