### ISSUE TITLE
Faster loading

### ISSUE THREAD

**Issue by pufferfish101007** [ScratchAddons/ScratchAddons#620]
**Describe the new addon**

This addon makes Scratch pages load approximately 2× faster than normal, by implementing a modified version of [defresh](https://defresh.js.org). At the moment it has a few bugs and is in the testing phase. The latest commit should fix all bugs, but I can't test all of it as I'm on mobile.
The basic problem is that when using the browser history navigation, the url changes but the page content doesn't. I'm assuming this is because the addon isn't being loaded to the page as it isn't refreshing, but that should mean that all userscripts should keep running... I don't really know. Anyway, I tested it on another website with dynamically adding a script tag to the page to be loaded and it all works fine. So hopefully by adding all the scripts from background.html to the html file it should reload all the addons. Hopefully.

**Link to the new addon**

https://github.com/pufferfish101007/ScratchAddons/tree/faster-loading/addons/faster-loading

**Comment by TheColaber** [comment]
Is it safe? Is there any chance it might not?

**Comment by pufferfish101007** [comment]
> Is it safe? 

It's completely safe. All it does is fetches the file contents of the url (well, it xhrs them, but it's pretty much the same thing), and then appends all the script tags from background.html to the rbd of the html file. In theory all the correct addons should then load. 



> Is there any chance it might not?

What do you mean by that?

**Comment by WorldLanguages** [comment]
Hmm, right now addons only load after a navigation. Implementing this correctly might be a challenge

**Comment by pufferfish101007** [comment]
Yes, I was considering appending the scripts in background.html to the loaded page and was windering if that would work (see #621)
I'm currently in the process of figuring out how to run  local extension on mobile... I can get ones from the chrome extension store but not locally :/

**Comment by WorldLanguages** [comment]
Rejected I guess. No Scratch dependent code. And too complex.
