### ISSUE TITLE
Cannot share project that is taken down by scratch team

### ISSUE THREAD

**Issue by kokofixcomputers** [ScratchAddons/ScratchAddons#6203]
### Description

I shared a project but scratch team confused it as a cloud chat so they took it down but then with scratchaddons 
1.33.0-prerelease enabled i cannot reshare it after disabling it i can reshare it.

### Steps to reproduce

1. Share a project that Scratch team will think as a cloud chat and let them take it down
2. With Scratch addons enabled reshare the project
3. Do it again and again until you cannot share the project

### Environment

Browser: Brave
Scratch Addons version:[v1.33.0-pre](https://scratchaddons.com/changelog/?utm_source=extension&utm_medium=popup&utm_campaign=v1.33.0#v1.33.0)
Operating system: Mac

**Comment by DNin01** [comment]
I'm assuming this is a bug with the Share from My Stuff page addon?

**Comment by CST1229** [comment]
Scratch Addons does not have any features that let you reshare projects taken down by the Scratch Team, and doing so would probably both be rejected (as that would be a major security issue) and impossible to do.

**Comment by WorldLanguages** [comment]
@CST1229 I think OP is referring to some addon that doesn't take into account the sharing project flow when a project has been taken down by the Scratch Team, which is different to sharing a normal project.

**Comment by kokofixcomputers** [comment]
Nope I can only share the project with SA disabled

**Comment by kokofixcomputers** [comment]
And i think with that some projects cannot be shared even a new project until SA is disabled

**Comment by WorldLanguages** [comment]
@mxmou Possibly you could modify the scratch-www source code to try to debug this in localhost? It's hard to test this without getting a project took down.

**Comment by DNin01** [comment]
Is [this](https://github.com/ScratchAddons/ScratchAddons/issues/6219) the bug you were experiencing?

**Comment by kokofixcomputers** [comment]
I found out that SA does not only affect project sharing but also affect other things like cancel the comment I've updated to the release version but the issue still exist.

**Comment by WorldLanguages** [comment]
Possibly this was just #6219 and unrelated to the fact your project has been taken down by Scratch moderators.

**Comment by kokofixcomputers** [comment]
So in the developer console i found that when i try to cancel a comment it has some sort of error: 
Uncaught Error: Wait until addon.tab.scratchClassReady() resolves before using addon.tab.scratchClass
    at Tab.scratchClass (Tab.js:297:13)
    at Module.confirm (modal.js:241:32)
    at Tab.confirm (Tab.js:839:18)
    at document.addEventListener.capture (userscript.js:66:12)

And this is when i try to cancel a comment: 
<img width="1424" alt="Screen Shot 2023-06-17 at 1 16 50 PM" src="https://github.com/ScratchAddons/ScratchAddons/assets/113046561/8c4ff5e2-61a6-47c4-9eeb-efb8f70551b2">

and when i try to press the x button it doesen't work. It is the same for sharing a project.

**Comment by kokofixcomputers** [comment]
And yes it is unrelated.

**Comment by WorldLanguages** [comment]
Yeah this is just #6219.
Next time try posting the bug details and screenshots earlier as that would have avoided actual users that installed from the store from getting the bug.

**Comment by WorldLanguages** [comment]
Considering this a duplicate of #6219

**Comment by kokofixcomputers** [comment]
Well maybe since i created this first

**Comment by DNin01** [comment]
> Well maybe since i created this first

We'll link to this issue from the other one.
