### ISSUE TITLE
New Scratch 2.0 privacy policy update banner isn't affected by Scratch 2.0 -> 3.0 or dark-www addon

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6206]
### Description

They've added a privacy policy update banner to 2.0 pages, and it isn't styled.

### Steps to reproduce

1. Enable the Scratch 2.0 -> 3.0 and/or dark-www addons
2. Go to a scratchr2 page

### Demonstration(s) and additional context

![image](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/5b7b2144-bbdf-4ad4-86fd-ef3938b282fe)

### Environment

Browser: Edge 114
Scratch Addons version: 1.32.1
Operating system: Windows

**Comment by mybearworld** [comment]
Yeah, I wasn't sure which one to use

**Comment by WorldLanguages** [comment]
The banner will probably be gone by next release so...

**Comment by mxmou** [comment]
> The banner will probably be gone by next release so...

I checked the code and it looks like the banner will disappear on June 16th on both scratch-www and scratchr2, so it probably doesn't make sense to try to fix this.
