### ISSUE TITLE
In the forums, "Highlight project creator in comments" calls the first poster of a page the OP.

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6213]
### Description

When a forum topic has more than one page, it would be expected that the person marked as the OP is the OP. Instead, it's always the first poster on the page.

### Steps to reproduce

1. Go to any page of a topic where the first poster isn't the OP, like https://scratch.mit.edu/discuss/topic/614802/?page=42
2. Go to a post of that same user, like https://scratch.mit.edu/discuss/post/7315597/

### Demonstration(s) and additional context

_Actual OP_
![Actual OP](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/5804851f-92ba-4d47-8b49-ec29dd5eeb33)

_First post of a page marked as OP_
![First post of a page marked as OP](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/a22bdc9e-4b8f-4be5-9092-6f258d82011c)

### Environment

Browser: Edge 114
Scratch Addons version: 1.33.0
Operating system: Windows 11

**Comment by DNin01** [comment]
Not sure if this is a bug or intentional.

**Comment by mybearworld** [comment]
> Not sure if this is a bug or intentional.

It's the way it's implemented, but the description and badge state "Original poster" and there's not much point to highlighting who made the first post of a page. It's probably an oversight.

**Comment by mybearworld** [comment]
Heh, I thought this would be a lot more complicated then it was

**Comment by WorldLanguages** [comment]
Nice catch
