### ISSUE TITLE
Clean slate

### ISSUE THREAD

**Issue by GloomyFM** [ScratchAddons/ScratchAddons#6225]
### Why this would be helpful

If you want to start on a clean slate without a new account (like every animator wants to) then this addon will clear/delete/remove everything from your profile.

### How this addon works

This addon is also related to the button feature of #6223 so it can have a use.

this will delete/remove everything like your profile picture. about me, wiwo, featured project, shared projects, studios/people you follow, studios you curate, profile comments being deleted (and closed) and all of your favourites.

this would in the danger section and if you click the addon it will display a pop up making sure you really want to clear everything. If you say yes then everything will be deleted.

### Possible alternatives

I don’t think there would be any other alternative

### Additional context

Example of a full profile:
<img width="1080" alt="image" src="https://github.com/ScratchAddons/ScratchAddons/assets/121749159/65280eed-d42e-4edd-9973-aacb383d6ffe">
example of an empty profile:
<img width="1080" alt="image" src="https://github.com/ScratchAddons/ScratchAddons/assets/121749159/bf0cb9d0-2c8b-4e98-a4af-d452851fcd7c">

**Comment by Chiroyce1** [comment]
I don't think it would be possible to clear the "What I've been doing" section though, it usually auto-clears after a certain amount of inactivity. The rest, sure yeah it is possible. But due to rate limits, if someone does have a lot of shared projects, favourite projects, or they're in a ton of studios, then this could possible run for a long time before it clears up everything.

**Comment by mybearworld** [comment]
I think this would be way too destructive. At this point. just create a new account.

**Comment by WorldLanguages** [comment]
Related discussion regarding destructive actions: #6223

**Comment by apple502j** [comment]
I'm quite surprised this issue is still alive. It should've been rejected sooner. There's no way we're implementing rarely used stuff that is too dangerous to test.
