### ISSUE TITLE
Minor tweaks to better-img-uploads

### ISSUE THREAD

**Issue by Jazza-231** [ScratchAddons/ScratchAddons#6238]
### Why this would be helpful

1. One of the changes fixes uploading an image with the exact same ratio as the scratch stage importing it 1 pixel smaller than the stage (e.g. uploading a 480x360 image would import it as 479x359, which annoyed me for ages)
2. Another change allows .sprite3 files to be uploaded with the hd image upload button. This isn't a big issue in itself, but consequently, this means that if you use the drag-and-drop addon with the hd image upload option enabled, you can now drag sprite3 files into the sprite pane (which was also something that annoyed me for ages)

### My suggestion

See above, but specifically all this does is add some special logic for sprite3 files and change 1 number.

### Possible alternatives

These are such small changes I don't think there's any other way to do it (unless I committed coding sins with the way I implemented them, oops)

### Additional context

A before (in turbowarp) and after (on scratch) for uploading a 960x720 image and a sprite file.
https://github.com/ScratchAddons/ScratchAddons/assets/81956724/02043519-adb9-4635-a546-6b77d2351409

Also, I know these are tiny tiny changes and arent really necessary so it makes sense if this is gonna get rejected for being too small.

**Comment by Jazza-231** [comment]
Oh, and in case it wasn't clear, I already made the changes, just need to see if people think it's worth making the pr for them.

**Comment by mxmou** [comment]
> Also, I know these are tiny tiny changes and arent really necessary so it makes sense if this is gonna get rejected for being too small.

That could be a reason to reject a new addon, but not an improvement to an existing one. The changes you suggested sound very useful to me.

**Comment by WorldLanguages** [comment]
Go ahead and submit the PR.

**Comment by Jazza-231** [comment]
Yay :D 
Submitted the PR
