### ISSUE TITLE
Remix Button for Own Projects Bug

### ISSUE THREAD

**Issue by SpryzenRYTonScratch** [ScratchAddons/ScratchAddons#6251]
### Description

Working fine, however when you remix your own project you get another message count that doesn't actually give you a message to check. I don't believe it should be telling you that YOU remixed your own project.

### Steps to reproduce

1. Put on the add-on if you haven't already
2. Remix project
3. Check Message Count 
4. No Message??

### Environment

Browser: Opera 99 (I also checked Chrome, v114, in case and the bug was still there)
Scratch Addons version: v1.33.1
Operating system: Windows 10

**Comment by mxmou** [comment]
SA can't prevent Scratch from sending a message. If what you see on the Messages page doesn't match the message count, that's probably caused by caching.

**Comment by SpryzenRYTonScratch** [comment]
> SA can't prevent Scratch from sending a message. If what you see on the Messages page doesn't match the message count, that's probably caused by caching.

Ok
