### ISSUE TITLE
Apply "Ctrl+Enter to post" when reporting in the forums

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6262]
### Why this would be helpful

I'd like to use Ctrl+Enter when submitting things, which is the point of the addon.

### My suggestion

Also post when pressing Ctrl+Enter on report screens in the forums.

**Comment by Chiroyce1** [comment]
Should be simple: add a match for `/discuss/misc/*` in the addon.json, and directly in the `forums.js` file handle the new `#id_reason` text field.
