### ISSUE TITLE
Clone counter not showing in fullscreen editor mode

### ISSUE THREAD

**Issue by hueychen27** [ScratchAddons/ScratchAddons#6275]
### Description

If you go in the editor, create a clone, make the stage smaller, and click fullscreen, you will not see the clone counter. It should show in fullscreen even if the stage is smaller.

### Steps to reproduce

1. Produce at least a clone in a project.
2. Go in the editor.
3. Enable the "Clone counter" extension.
4. Press the "Switch to small stage" icon which will make the stage small and the code area big.
5. Press the fullscreen button.

### Demonstration(s) and additional context

A video about the bug:
https://github.com/ScratchAddons/ScratchAddons/assets/78285518/50ab1f57-3a3b-4a70-b887-d3099eac9693

### Environment

Browser: Firefox ESR 102.12.0esr (64-bit)
Scratch Addons version: v1.33.1
Operating system: Kali Linux

**Comment by WorldLanguages** [comment]
Thanks for the video

**Comment by medlans** [comment]
I can replicate, I was so confused until I noticed the switch to small stage icon part as I was trying to search the edit dropdown for small stage layout and the triangle when I couldn't find it though..
Anyway, I also can't see the mouse position too, but I don't really want that in fullscreen just outside of it.

**Comment by WorldLanguages** [comment]
Yeah this probably also affects the mouse position addon, and possibly also the gamepad button?

**Comment by hueychen27** [comment]
Yep. And the volume slider addon.

**Comment by hueychen27** [comment]
Pretty much all the extra addons on the top of the project display except the pause button addon.
