### ISSUE TITLE
More icons (and less text)

### ISSUE THREAD

**Issue by StioStudio** [ScratchAddons/ScratchAddons#6279]
### Why this would be helpful

Stuff like the "View All" link, "Post", "Cancel", "Reply", the header text on project rows, and more.

### How this addon works

By adding icon and (if wanted to:) deleting the text.

### Additional context

The "the header text on project rows" and "View All" example: (don't mind the weird design on the home page)
![image](https://github.com/ScratchAddons/ScratchAddons/assets/98958235/957e5fe9-dd7e-4196-8cde-814723462f69)

**Comment by WorldLanguages** [comment]
But there's no "view all" button in the Featured Projects row!

**Comment by StioStudio** [comment]
> But there's no "view all" button in the Featured Projects row!

No, but there is on Projects Curated by - user, Scratch Design Studio - studio, Scratch News, Shared Projects, Favorite Projects, Studios I Curate, Following, Followers and Statistics

**Comment by StioStudio** [comment]
> But there's no "view all" button in the Featured Projects row!

Ohh you meant that....😅... don't mind it. It is just an STE feature

**Comment by nikeedev** [comment]
So, it was not happening after all…?

**Comment by WorldLanguages** [comment]
Don't know, I think the original post is a bit confusing. When proposing to replace text with icons, it's a bit ambiguous: which icon would replace the "post" button, for example? Will extension users actually be interested on enabling a feature like this?

**Comment by nikeedev** [comment]
> Don't know, I think the original post is a bit confusing. When proposing to replace text with icons, it's a bit ambiguous: which icon would replace the "post" button, for example? Will extension users actually be interested on enabling a feature like this?

@StioStudio

**Comment by StioStudio** [comment]
> > Don't know, I think the original post is a bit confusing. When proposing to replace text with icons, it's a bit ambiguous: which icon would replace the "post" button, for example? Will extension users actually be interested on enabling a feature like this?
> 
> @StioStudio

No thank you
