### ISSUE TITLE
share-through-mystuff should not use a deprecated REST API

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6280]
This addon indirectly uses the `scratch.mit.edu/site-api` API instead of `api.scratch.mit.edu` for sharing projects

**Comment by mxmou** [comment]
Even though this API is technically deprecated, the same endpoint (`/site-api/projects/all/<id>/`) is used by Scratch to unshare projects.

**Comment by WorldLanguages** [comment]
Exactly, it's not used to share projects. Only to unshare them
