### ISSUE TITLE
The 'Website dark mode and customizable colors' does not change the editor color bar color.

### ISSUE THREAD

**Issue by RIT-entertainment** [ScratchAddons/ScratchAddons#6291]
### Description

No matter what options you select on the feature listed in the title, the editor title bar [the thing at the top] always appears purple.

### Steps to reproduce

1.Enable the 'Website dark mode and customizable colors' addon
2.Set navigation bar to any color
3.Look at project editor

### Environment

Browser: Chrome 114
Scratch Addons version: Newest as of 28/06
Operating system: Windows 10

**Comment by mxmou** [comment]
There's a separate addon called "Editor dark mode and customizable colors".
