### ISSUE TITLE
Modal API "X" (close) image URL is no longer available

### ISSUE THREAD

**Issue by kokofixcomputers** [ScratchAddons/ScratchAddons#6292]
### Description

When pressing the "Record" button in the new Scratch Editor the x image is gone

Screenshots:

Record:

<img width="933" alt="Screen Shot 2023-06-28 at 9 25 04 AM" src="https://github.com/ScratchAddons/ScratchAddons/assets/113046561/b696210b-aabd-48fc-8456-8b740ed49433">

And when I go to the image URL:

<img width="933" alt="Screen Shot 2023-06-28 at 9 27 11 AM" src="https://github.com/ScratchAddons/ScratchAddons/assets/113046561/9cea3d3b-dc83-41ba-a564-fea12c3ea9be">

### Steps to reproduce

1. Create a scratch project
2. Press record
3. Look at the close button
4. done

### Environment

Browser: Brave
Scratch Addons version: 1.33.2
Operating system: (You should not need to know)

**Comment by mxmou** [comment]
This affects all editor addons that use the modal API.
