### ISSUE TITLE
Hide editor menu bar icons

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6294]
### Why this would be helpful

> Scratch added icons to the menu bar at the top, which kinda makes it an eyesore. Maybe make an addon to remove those and get rid of the extra spacing, so it looks like it did before? Side note, using an element blocker from an adblocker doesn't work; the icons come back when you click on something else. 

> they take up a lot of space

> Please add a addon to remove the icons added to the nav bar on project editor in settings/file/edit - it's spacey

### My suggestion

Could be a new addon
Potentially could be merged with the "hide tutorials" addon

**Comment by medlans** [comment]
Yeah, I would like this too. Maybe name it hide header stuff or something, and you could choose to hide tutorials and/or icons?

**Comment by WorldLanguages** [comment]
> It would be cool to have an option to only show either the text or the icons (I like the icons)

**Comment by callumjt** [comment]
i could make this if no ones else is making it

**Comment by Samq64** [comment]
Sure, but it's a feature so it probably won't be added until 1.34.

**Comment by BroJac5246** [comment]
> Potentially could be merged with the \"hide tutorials\" addon

I think it should be this. I was thinking earlier today that the hide tutorials addon is a little strange, but a "Customizable Editor Header" or similar addon would make sense.

**Comment by medlans** [comment]
> > Potentially could be merged with the "hide tutorials" addon
> 
> I think it should be this. I was thinking earlier today that the hide tutorials addon is a little strange, but a "Customizable Editor Header" or similar addon would make sense.

I learned the header tools were removed in 3.0 today, could this be there?

**Comment by DNin01** [comment]
Note that Scratch removes the text labels if the screen is not wide enough, leaving only the icons. If we aren't careful, we could hide the icons and they buttons would become basically invisible.

**Comment by Secret-chest** [comment]
**Menus:** select Icons only / Text only / Both
**Tutorials:** select Show / Icon only / Text only / None
**Only show user icon:** bool
**Padding size (%):** int (percentage)

**Comment by Secret-chest** [comment]
> I learned the header tools were removed in 3.0 today, could this be there?
> 
> @medlans What are "header tools"?
I think it means the scissors, help, grow, shrink, duplicate buttons on the Scratch 2.0 and 1.x header

**Comment by WorldLanguages** [comment]
Note that addon compact-editor (PR #4018) added this functionality, and it cannot be toggled. It keeps only the text in the settings/file/edit menus.
More discussion on how we should handle customizations of the editor menu bar belongs here: #6432

**Comment by WorldLanguages** [comment]
For discussion on toggling `text only / icons only` separately from the compact-editor addon, let's talk on issue #6432
