### ISSUE TITLE
Update default customizable quotes on forums colour

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6296]
### Why this would be helpful

`scratchr2` (mostly) switched over to using the new purple, but the default customizable quotes on forums colour is still the old Scratch 2 blue.

### My suggestion

Change the default colour to the new purple.

**Comment by mxmou** [comment]
> `scratchr2` (mostly) switched over to using the new purple, but the default customizable quotes on forums colour is still the old Scratch 2 blue.

The default is actually the same as the post header color, which is still blue. I think we should wait for the ST to update it.

**Comment by WorldLanguages** [comment]
Related feedback:

> Also, the links on https://scratch.mit.edu/help/videos/ still showed purple.

**Comment by Samq64** [comment]
I didn't even know that page existed.

**Comment by medlans** [comment]
> Related feedback:
> 
> > Also, the links on https://scratch.mit.edu/help/videos/ still showed purple.
> 
> It's a Scratch page that is rarely used.

By the way, it also happens when I hover over usernames on profile pages, and I think it only happens on scratchr2. Also, when I applied all my settings, I could see purple borders around unfollow discussion.

> I didn't even know that page existed.

It still does, and I have it linked as “Help” on my navbar because the actual help page doesn’t exist anymore and just redirects to ideas. I remember it used to be linked on there.

**Comment by WorldLanguages** [comment]
> it also happens when I hover over usernames on profile pages

Yeah, on the "default colors (blue)" preset, hovering over a comment author still shows purple:

![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/e8738204-481d-4cb5-8907-d089b39412c7)

**Comment by mxmou** [comment]
> Related feedback:
> 
> > Also, the links on https://scratch.mit.edu/help/videos/ still showed purple.
> 
> It's a Scratch page that is rarely used.

I don't think it makes sense to try to support that page. There's even an open PR in scratch-www that makes it redirect to Ideas: scratchfoundation/scratch-www#7307

**Comment by medlans** [comment]
> > Related feedback:
> > > Also, the links on https://scratch.mit.edu/help/videos/ still showed purple.
> > 
> > 
> > It's a Scratch page that is rarely used.
> 
> I don't think it makes sense to try to support that page. There's even an open PR in scratch-www that makes it redirect to Ideas: [scratchfoundation/scratch-www#7307](https://github.com/scratchfoundation/scratch-www/pull/7307)

Okay, the issue was "fake-link" was not being turned purple so all I did was make something that changes it to the 2.0 link color.

**Comment by WorldLanguages** [comment]
This is a small forums addon, so we can deal with this in v1.34 I think

**Comment by mxmou** [comment]
Added pending label because Scratch's hasn't updated the post header color yet.

**Comment by Samq64** [comment]
It looks like they have now.
