### ISSUE TITLE
author/creator badge in project comments  

### ISSUE THREAD

**Issue by YandeMC** [ScratchAddons/ScratchAddons#6298]
### Why this would be helpful

its possible to miss comments from the creator because there is nothing marking what comments are the the creators comments or a normal user.
these comments can have updates and changes to the project and can be easily missed and ignored as a normal comment .

### How this addon works

![ste's version](https://github.com/ScratchAddons/ScratchAddons/assets/113806118/afbf5a9c-bd45-40ea-a42d-8a64a22b6ede)
 
this is ste's implementation and it adds a small badge 
### Possible alternatives

there could be a different  color, bolded or underlined name for the project creator

**Comment by Samq64** [comment]
This was added in 1.33. 
https://scratch.mit.edu/scratch-addons-extension/settings#addon-op-badge

**Comment by YandeMC** [comment]
oh
