### ISSUE TITLE
editor-dark-mode does not change color of costume editor buttons

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6299]
### Why this would be helpful

From feedback
Not sure if this was mentioned already in some issue these last few days, sorry

### My suggestion

![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/832ab5c3-d699-4965-afb8-4a73c45b7be0)

> in the costume editor the buttons arent changed. 

Screenshot: "Scratch 3.0 default colors (blue)" preset

**Comment by CST1229** [comment]
dark-www? not editor-dark-mode?

**Comment by mxmou** [comment]
Some of these icons are data URIs, which makes them very easy to recolor. Those that aren't could be replaced with a data URI or an inline SVG with fill set to `currentColor`. `recolorFilter` isn't an option - it only works with monochrome icons.

**Comment by WorldLanguages** [comment]
+1 from feedback
