### ISSUE TITLE
The update notification's links are purple too

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6300]
After Scratch changed the colors, the update notification now has purple links too. This reduces the contrast on the notification's dark background.

![SA update notification with purple links](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/3379b6a6-b95c-40b1-884c-863e9d273929)

**Comment by WorldLanguages** [comment]
Looks like this on scratchr2 pages (screenshot is My Stuff)
![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/12909d3e-ec09-4966-b12d-bc8b8077dff3)

**Comment by mxmou** [comment]
The color of these links should probably be the same as on the settings page - `#1aa0d8`.
