### ISSUE TITLE
The costume editor's checkerboard pattern is set incorrectly

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6301]
### Description

Normally, the costume editor checkerboard pattern uses white and light blue, but `editor-dark-mode` sets it based off of Highlight color, so the secondary color becomes light purple on default settings.

### Steps to reproduce

1. Set highlight color in Editor dark mode and customizable colors to something other than blue.
2. Open the paint editor.

### Environment

N/A

**Comment by Secret-chest** [comment]
I think a separate setting is the only way.

**Comment by Samq64** [comment]
When the addon is set to Scratch's default colours, does it really need to be compatible with all the tiny inconsistencies?

**Comment by Samq64** [comment]
When the addon is set to Scratch's default colours, does it really need to be compatible with all the tiny inconsistencies?

**Comment by mxmou** [comment]
> When the addon is set to Scratch's default colours, does it really need to be compatible with all the tiny inconsistencies?

I don't think it should try to fix inconsistencies if they're intentional. This one probably is, because the canvas background is very similar to the page background which is also blue.
