### ISSUE TITLE
Inconsistant accent color across pages with 2.0->3.0 enabled

### ISSUE THREAD

**Issue by penguinmoose** [ScratchAddons/ScratchAddons#6302]
### Description

Scratch recently changed the color scheme for better contrast. On pages that have already converted to 3.0 styling, such as the homepage, projects, studios, and the messages page, the accent color is the high contrast purple. The top bar is purple, and so are the buttons. The 2.0 pages are also the same, just with 2.0 styling if 2.0->3.0 isn't enabled.

However, with 2.0->3.0 enabled, the 2.0 pages use the old accent colors (blue). They should use the high-contrast styling as implemented in the original 3.0 pages.

I think this is because 2.0->3.0 doesn't have to do anything on the pages that already use 3.0 styling. However, it does have to convert the styling to 3.0 on the pages that still are 2.0.

### Steps to reproduce

1. Enable the 2.0->3.0 addon.
2. Visit a page that already has 3.0 styling even without the addon, such as the Scratch homepage, project pages, studios, or the messages page. The styling uses the new high-contrast accent color.
3. Visit a page that hasn't updated to the 3.0 styling. The 2.0->3.0 addon changes it to the 3.0 styling, but with the old colors (not high contrast).
4. Turn off the 2.0->3.0 addon.
5. These 2.0 pages have the new colors (purple) if 2.0->3.0 isn't enabled.

### Demonstration(s) and additional context

https://github.com/ScratchAddons/ScratchAddons/assets/67451414/79734a6c-23a6-4254-9c26-87f8ddd65a36

### Environment

Browser: Google Chrome 114.0.5735.133 (Official Build) (arm64)
Scratch Addons version: 1.33.1
Operating system: MacOS Ventura 13.4 on M1 Pro (MacBook Pro)

#### Related:
#6299
#5897

**Comment by Samq64** [comment]
This is fixed in 1.32.2 which should already be released to most users.
