### ISSUE TITLE
Update notication appears in live featured project 

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6304]
### Description

When set to Scratch's project player, the Scratch Addons update notification appears inside the project embed. I haven't check if this happens on players embedded in other sites.

### Steps to reproduce

1. Enable `live-featured-project`
2. Set the project player to Scratch
3. Go to https://scratch.mit.edu/users/griffpatch/
4. Set the extension manifest version to 2.0
5. Reload the extension
6. Go back to the open profile tab

### Demonstration(s) and additional context

![image](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/f51d8d25-000e-4994-9604-db6b07a38bf6)

### Environment

Browser: Firefox 114
Scratch Addons version: 1.33.2
Operating system: Linux

**Comment by WorldLanguages** [comment]
lol

**Comment by WorldLanguages** [comment]
> I haven't check if this happens on players embedded in other sites.

Not possible because we don't have host permissions for other sites.
