### ISSUE TITLE
Wrong value of `--darkWww-box-scratchr2TransparentText` on default colors presets? (dark-www)

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6306]
In both `Scratch default colors` and `Scratch default colors (blue)`, this color which is used for "About Me" and "What I'm working On", is set to `rgba(0, 0, 0, 0.47)` instead of `#888` which is what Scratch uses.

Note that the Scratch 2.0→3.0 addon should be disabled in order to experience this bug.

**Comment by mxmou** [comment]
This is unrelated to the contrast changes.

**Comment by WorldLanguages** [comment]
@mxmou I thought it would be great to fix bugs from the "default colors (blue)" preset for next version. Did not attempt to imply this was a recent regression.

**Comment by WorldLanguages** [comment]
+1 from feedback:

> With any light-colored theme (purple and blue) addon
"Web site dark mode and customizable colors" makes the text and emoji in About Me and other places pale.

**Comment by mxmou** [comment]
`rgba(0, 0, 0, 0.47)` on a white background should looks the same as `#888888`, which means this is a bug in Chromium's rendering. It can be fixed by using a non-transparent text color, which also fixes emojis.
