### ISSUE TITLE
2.0 colors preset for website colors

### ISSUE THREAD

**Issue by medlans** [ScratchAddons/ScratchAddons#6318]
### Why this would be helpful

People might want to be able to bring back the old 2.0 colors from before the update, maybe even on 3.0 pages.

### My suggestion

There could be a preset to load these easily, but here's some colors it could use (this is what I have as my settings currently):
Navbar color: #0F8BC0
Link color: #1AA0D8
Highlight color: #19b6fa, #169FDB

### Possible alternatives

2.0 <-> 3.0?

**Comment by WorldLanguages** [comment]
> 2.0 <-> 3.0?

Well, it's true that a new `Scratch 3.0→2.0` addon would be better than providing a preset, but I'm not really sure if someone is willing to make the effort to maintain such an addon

**Comment by medlans** [comment]
> > 2.0 <-> 3.0?
> 
> Well, it's true that a new `Scratch 3.0→2.0` addon would be better than providing a preset, but I'm not really sure if someone is willing to make the effort to maintain such an addon It would also be incompatible with the existing `Scratch 2.0→3.0` addon as having both addons enabled at the same time wouldn't make sense.

I mean, I was thinking of merging them, and letting the user swap between them.
Anyway, if it were a new addon, I'm guessing that it would just make the 3.0 pages look like 2.0 and the pages that were already 2.0, 3.0.

**Comment by CST1229** [comment]
> It would also be incompatible with the existing `Scratch 2.0→3.0` addon as having both addons enabled at the same time wouldn't make sense.

It would make 3.0 pages 2.0 and 2.0 pages 3.0, probably.

**Comment by mxmou** [comment]
There's already an issue for a 3.0 → 2.0 addon: #985
