### ISSUE TITLE
Title categories mixed up

### ISSUE THREAD

**Issue by MasimbaTheHuman** [ScratchAddons/ScratchAddons#632]
The 3.0. theme mixes the profile categories on certain profiles. Not every profile has this bug.

1. Go to @yeeeeeeet's scratch profile
2. Scroll down to 'comments'
3. It says followers instead of comments.

![Screenshot (2)](https://user-images.githubusercontent.com/64666021/97891439-a2d5b300-1ce3-11eb-9118-3d158e438fe2.png)

- OS: [windows 10]
- Browser [chrome]
- Version [1.2.1]

**Comment by TheColaber** [comment]
This will be fixed when #629 is merged

**Comment by pufferfish101007** [comment]
Yes #583 - it's the show exact count I think not 3.0 theme

**Comment by WorldLanguages** [comment]
Duplicate of #583 - but thanks for reporting!
