### ISSUE TITLE
Scratchaddons shows no active games

### ISSUE THREAD

**Issue by michaeleldar** [ScratchAddons/ScratchAddons#6321]
### Description

In the scratchaddons games tab it says there are 0 people in every single game, but when I go into one there are lots of people.

### Steps to reproduce

1. Open the scratchaddons browser extension button
2. Go into the games tab

### Demonstration(s) and additional context

https://github.com/ScratchAddons/ScratchAddons/assets/66514999/f1b07cbd-51a1-4531-96b7-b3ed9bd0aa4c

### Environment

Browser: 
Scratch Addons version: 
Operating system:

**Comment by apple502j** [comment]
Can you do the following:
1. Open Games in new tab (the button next to the Games tab in the popup)
![image](https://github.com/ScratchAddons/ScratchAddons/assets/33279053/4c341c62-65ff-4c7e-bea9-1cbd4c0520e8)
2. Press F12 and open Console tab
3. Screenshot the result

@michaeleldar

**Comment by michaeleldar** [comment]
<img width="720" alt="image" src="https://github.com/ScratchAddons/ScratchAddons/assets/66514999/ea0bf0d3-285d-43c3-a4b1-e1319317b752">
Not very revealing I guess

**Comment by DNin01** [comment]
Might be a random Cloud variables issue. Scratch experiences problems with Cloud variables sometimes.

**Comment by apple502j** [comment]
Closing as API glitch.
