### ISSUE TITLE
tab completely breaks

### ISSUE THREAD

**Issue by MasimbaTheHuman** [ScratchAddons/ScratchAddons#634]
I was using amber OS, and when it loaded, my cursor was set to type and I couldn't interact with anything.

1. Go to https://scratch.mit.edu/projects/395051494/
2. wait for load
3. See error

![Screenshot (3)](https://user-images.githubusercontent.com/64666021/97901587-3e215500-1cf1-11eb-8660-262eae2cf9ed.png)

- OS: [Windows 10]
- Browser [chrome]
- Version [1.2.1]

After a minute or two, I was able to interact with things again.

**Comment by TheColaber** [comment]
Which addon did this? Maybe the console might give you a hint...

**Comment by WorldLanguages** [comment]
It's likely the infinite scrolling addon. Can you try disabling it?

**Comment by MasimbaTheHuman** [comment]
Nvm I muted Scratch Addons and tried again same thing. AmberOS is very big too.
