### ISSUE TITLE
Add the option to use high contrast blocks when displaying 3.0 Scratchblocks on forums

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6351]
### Why this would be helpful

Since [scratchblocks](https://github.com/scratchblocks/scratchblocks) has been updated to support high contrast Scratch-3.0 blocks, we can now offer users the option to have the `scratchblocks` addon display high contrast blocks on the forums.

Users have always been able to customize them through `editor-theme3`, but we don't have to make it the only option.

### My suggestion

Add an option to `scratchblocks` to use high contrast blocks.

**Comment by WorldLanguages** [comment]
If we add a toggle, we would end up with conflicting settings, which one would have more priority?

**Comment by DNin01** [comment]
> If we add a toggle, we would end up with conflicting settings, which one would have more priority?

What do you mean?

**Comment by DNin01** [comment]
Could we hide the switch if `editor-theme3` is enabled?
