### ISSUE TITLE
Unload unneeded addon.json data

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6355]
### Why this would be helpful

According to #5190:

> ### Memory usage (background page)
> It's important to consider the memory usage of our background page. It's true that Scratch itself is pretty memory intensive, but SA is running all the time, even if the user isn't currently using Scratch! Since v1.0.0, all manifests are stored inside a variable in the background page. This includes all this data from all addons, no matter if they're enabled or not:
> 
> * Addon ID
> * The entire addon.json file as an Object
> * If the browser language is not set to English, and it's a language we support (such as Spanish), the English name and description are stored in memory too (see https://github.com/ScratchAddons/ScratchAddons/blob/master/background/load-addon-manifests.js#L58)
> 
> This `scratchAddons.manifests` array gets larger with every release. I'm not sure how to properly check the actual memory usage of this "big" object, but according to Chrome Devtools, it appears to use about 0.25MB.
> 
> We could also check whether `scratchAddons.l10n` stores any unnecessary messages in memory in the background page.

### My suggestion

To cut down on memory usage, we can:
- Unload details about disabled addons
- Potentially unload even more data if the user hasn't accessed Scratch for a while

Information would be loaded back into memory as needed, like if a user expands an addon to change settings or enables an addon.

The following information will be needed in these cases:
| Type of data | <span title="Needed for the addon to work">🧩</span> | <span title="Needed in order to be displayed in the popup">◻️</span> | <span title="Needed in order to be displayed in the full screen settings page">⚙️</span> |
|--------|--------|--------|--------|
| Name | | 🔷 | 🔷 |
| Description | | | 🔷 |
| Tags and category | | 🔷 | 🔷 |
| Settings and other details | | | |
| Selected settings | 🔷 | | |
| JS and CSS | 🔷 | | |

<details><summary>Key</summary>
<p>

🧩 Needed for the addon to work
◻️ Needed in order to be displayed in the popup
⚙️ Needed in order to be displayed in the full screen settings page

</p>
</details>

Everything information-related would be needed if the user expanded the addon card, and the ID would probably always stay in memory.

### Possible alternatives

Compress the contents. Like, maybe we can use numerical IDs instead of strings to identify addons and settings.

**Comment by apple502j** [comment]
Too complicated for something that only takes less than a megabyte of data. We are not using Windows 95.

The thing with those mini-optimizations is that you misunderstand what is causing a performance issue. Generally speaking, a static object is more performant than something that regularly triggers a disk load and garbage collection (assuming the size of the data is negligible).

**Comment by DNin01** [comment]
> Too complicated for something that only takes less than a megabyte of data. We are not using Windows 95.
> 
> 
> 
> The thing with those mini-optimizations is that you misunderstand what is causing a performance issue. Generally speaking, a static object is more performant than something that regularly triggers a disk load and garbage collection (assuming the size of the data is negligible).

Yeah, someone said it was only about 0.25 MB.

**Comment by WorldLanguages** [comment]
Yeah, I can't find any evidence to suggest the manifests in RAM JavaScript memory take more than 1MB, in Chromium.
Doesn't look like our background page (after starting up and loading manifests) is using a lot of memory vs. an empty background page. Not much we can do about this.
