### ISSUE TITLE
`scratchr2` not working correctly since purple update

### ISSUE THREAD

**Issue by just-a-hriday** [ScratchAddons/ScratchAddons#6365]
### Description

- The title bar stays the Scratch 2.0 blue instead of becoming purple or 3.0 blue.
- The buttons are the 3.0 size, but have 2.0 styling.
- Probably other stuff.

### Steps to reproduce

1. Enable _Scratch 2.0 → 3.0_.
2. Go to a Scratch 2.0 page like a profile or the forums.
3. Observe the weird stuff going on.

### Demonstration(s) and additional context

![scratch mit edu_users_just-a-hriday_](https://github.com/ScratchAddons/ScratchAddons/assets/73294041/4ad6057e-65b2-4fc3-8da5-4d7635fd45f1)
<sup>Scratch 2.0 blue instead of new purple. `dark-www` also does not affect it.</sup>

![scratch mit edu_users_just-a-hriday_](https://github.com/ScratchAddons/ScratchAddons/assets/73294041/c3150a70-cf02-4e9d-9aea-315eaa717e26)
<sup>Buttons styled like their Scratch 2.0 versions.</sup>

https://github.com/ScratchAddons/ScratchAddons/assets/73294041/66e6bb76-4b11-4890-9661-846518b23d5c

<sup>When hovered, blue (supposed to be purple) buttons are confused which colour they should be.</sup>

### Environment

Browser: Edge 114
Scratch Addons version: 1.33.3
Operating system: Windows 11

**Comment by mxmou** [comment]
I'm not able to reproduce this on the master branch using the same browser.

**Comment by just-a-hriday** [comment]
> I'm not able to reproduce this on the master branch using the same browser.

Hmm. I guess it's just me then.

**Comment by Samq64** [comment]
> Hmm. I guess it's just me then.

Is it still happening to you?

**Comment by WorldLanguages** [comment]
Try disabling other browser extensions?

**Comment by just-a-hriday** [comment]
> Try disabling other browser extensions?

Oh, that fixes it. Thanks!
