### ISSUE TITLE
Migrate preset settings for #5602

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6366]
https://github.com/ScratchAddons/ScratchAddons/pull/5602#issuecomment-1620465667

**Comment by Samq64** [comment]
I would PR this but I'm not familiar with how the preset migration system works.

**Comment by WorldLanguages** [comment]
Actually, I was about to say that I'm not sure if these settings should be automatically migrated. I'm a bit indifferent about it now.

I guess we should migrate the presets anyway because we have always migrated settings after changing existing presets.
