### ISSUE TITLE
Colorblindness accommodations addon

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6374]
### Why this would be helpful

There are a number of things on Scratch that can be improved to be more accessible to colorblind users.

### How this addon works

This addon would provide accommodations for colorblind users.

**Link style**
The most notable setting in this addon will the ability to change the style of links. Colorblind users can have a hard time differentiating links from normal text. There would be two options for link text: bold and underlined.

**Contrast enhancements**
Some elements can also be harder for colorblind users to see. For example, the toggled love and favorite icons aren’t the best in terms of contrast. This setting could darken certain elements so they are accessible.

Any more you can think of?

All of these features could be turned off as well, so if you don’t need a certain accommodation, you don’t have to apply it.

### Possible alternatives

Add these features to `dark-www`.

**Comment by Secret-chest** [comment]
While I'm not colourblind and I don't want to have these features, I can think of more:
* Fill in selected item in editor toggles
* Small caps links? I've seen it used sometimes
* Colourblind block colour preset
* Hue indicator in colour picker (for example 95 - Rose, 48 - Spring green)

**Comment by DNin01** [comment]
After the editor update, toggled switch buttons are now filled in when turned on. It may be hard for some users to see, though, so we could do something about that.

Block color options for colorblind users can probably be added to `editor-theme3`. Related issue: #5956

I was thinking of that fourth idea too. Microsoft is great at that one. But I'm not sure how much it would help someone who is colorblind because they would have never experienced the actual color to know what it looks like.

**Comment by BroJac5246** [comment]
> I was thinking of that fourth idea too. Microsoft is great at that one. But I'm not sure how much it would help someone who is colorblind because they would have never experienced the actual color to know what it looks like.

As someone who is colorblind, I actually find this appealing. Color blindness can occur later in life, even though it is often inherited, and depending on the type of colorblindness, people may still have an idea of what a color looks like, even if they have difficulty discerning it themselves.

**Comment by Secret-chest** [comment]
Alternatively, we could display the closest named CSS colour

**Comment by WorldLanguages** [comment]
> * Hue indicator in colour picker (for example 95 - Rose, 48 - Spring green)

That sounds interesting! Are there libraries that already handle this? (hopefully supporting colors in multiple languages)
Does this type of feature have a name so that we can research it?

**Comment by DNin01** [comment]
> > * Hue indicator in colour picker (for example 95 - Rose, 48 - Spring green)
> 
> That sounds interesting! Are there libraries that already handle this? (hopefully supporting colors in multiple languages) Does this type of feature have a name so that we can research it?

I did find this: https://github.com/colorjs/color-namer

**Comment by DNin01** [comment]
And this: https://github.com/microsoft/PowerToys/blob/main/src/common/ManagedCommon/ColorNameHelper.cs
