### ISSUE TITLE
Dark-www makes links in forum post previews look the same as regular text

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6376]
### Description

When dark-www is active, links look the same as regular text. This does not happen if dark-www is dynamically enabled, and does still happen if it is dynamically disabled.

### Steps to reproduce

1. Enable dark-www
2. Go to a forum topic you can post on
3. Put something that contains a link in the field
4. Click on the preview button

#### dark-www enabled

![A Scratch page in dark mode with a white link (e.g. indistinguishable from actual text)](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/400e7772-2f34-4825-a30a-5cc9b467a468)

#### dark-www dynamically enabled

![A Scratch page in dark mode with links looking correct](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/e57ecb2e-76f7-4cd4-a750-04e39d4e3d3b)

#### dark-www dynamically disabled

![A Scratch page with regular colors with links being black (e.g. indistinguishable from actual text)](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/6a1618f0-cfdc-4ccc-998b-0f55034cc42d)

#### dark-www disabled

![A Scratch page with regular colors with links looking correct](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/b63844aa-7418-4430-95a4-002d59d222c5)

### Environment

Browser: Edge 114
Scratch Addons version: 1.33.3
Operating system: Windows 11

**Comment by mybearworld** [comment]
This comes down to `var(--darkWww-link-scratchr2)` not being defined. Just changing this to `var(--darkWww-link)` fixes this, but does not behave the same (the links are purple, whereas in vanilla Scratch they are still blue).

**Comment by mxmou** [comment]
> the links are purple, whereas in vanilla Scratch they are still blue

I think Scratch is wrong - the links are purple in the actual post so they should be purple in the preview too.

**Comment by mybearworld** [comment]
> > the links are purple, whereas in vanilla Scratch they are still blue
> 
> I think Scratch is wrong - the links are purple in the actual post so they should be purple in the preview too.

I agree, but shouldn't we try to replicate Scratch with the defaults?

**Comment by medlans** [comment]
Okay, I thought I was going to crazy. Was the issue where it would sometimes show black even when you hovered over the username fixed?

**Comment by mybearworld** [comment]
> Was the issue where it would sometimes show black even when you hovered over the username fixed?

What username?

**Comment by mxmou** [comment]
> > I think Scratch is wrong - the links are purple in the actual post so they should be purple in the preview too.
> 
> I agree, but shouldn't we try to replicate Scratch with the defaults?

Not necessarily if Scratch's behavior is obviously unintended.

> Shouldn’t the links be the link color the user selected??

Yes, and that means purple with the default settings.

> > Was the issue where it would sometimes show black even when you hovered over the username fixed?
> 
> What username?

Probably the author's username on the forums. I don't think an issue related to those was fixed recently.

**Comment by medlans** [comment]
> > Was the issue where it would sometimes show black even when you hovered over the username fixed?
> 
> What username?

It happens when you hover over the usernames above profile pictures on forum topics, not just on author usernames.

**Comment by BroJac5246** [comment]
> > > the links are purple, whereas in vanilla Scratch they are still blue
> > 
> > I think Scratch is wrong - the links are purple in the actual post so they should be purple in the preview too.
> 
> I agree, but shouldn't we try to replicate Scratch with the defaults?

No, because then when Scratch fixes it, we'll be wrong. Either way, we'll be different at some point, so at least we should be correct.
