### ISSUE TITLE
Scratch 2.0 → 3.0: Match studio input field styles with 3.0's style

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#638]
**Describe the bug**

It seems that the input field styles on the studio page has not the same style as the general 3.0 style. Why don't make it the same?

**Screenshots**

This is just an example. It's not just the title input element, but also the description.

| Not focused | Focused |
| - | - |
| ![image](https://user-images.githubusercontent.com/11584103/97992499-538f9f80-1e15-11eb-893e-0e36b47f7a3d.png) | ![image](https://user-images.githubusercontent.com/11584103/97993692-fe548d80-1e16-11eb-81e4-0b5e451bc0a9.png) |
| ![image](https://user-images.githubusercontent.com/11584103/97993877-3e1b7500-1e17-11eb-8677-96acf08f88bd.png) | ![image](https://user-images.githubusercontent.com/11584103/97993925-4c699100-1e17-11eb-98b4-fb2987c3cf80.png) |

**Comment by mxmou** [comment]
The title is supposed to look the same, but one of its parent elements has `overflow: hidden`.

**Comment by Hans5958** [comment]
Also mind the dashed border on the editable inputs

**Comment by TheColaber** [comment]
Is this resolved now? 
![image](https://user-images.githubusercontent.com/72760579/115116845-ca56ca00-9f69-11eb-94bd-65d9018c9a9b.png)
![image](https://user-images.githubusercontent.com/72760579/115116853-d2166e80-9f69-11eb-960c-3bad7ff63a1f.png)

**Comment by mxmou** [comment]
@TheColaber It is. It could still be improved but the studio page will probably be migrated soon anyway.
