### ISSUE TITLE
dark-www doesn't affect alert messages

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#6383]
### Description

The `dark-www` (Website dark mode and customizable colors) addon doesn't change the background colour of alerts ("messages from the Scratch Team") on the messages page based on the highlight colour, instead leaving them purple.

### Steps to reproduce

1. Get an alert. The easiest way to do this is to curse, get muted and wait 5 minutes to receive the "Welcome back!" message.
2. Visit the [messages page](https://scratch.mit.edu/messages) containing the alert.
3. See how the alert's background is still purple.

### Demonstration(s) and additional context

![screenshot](https://github.com/ScratchAddons/ScratchAddons/assets/74449186/2878335c-5448-43bd-9b6d-d7409b7ef55c)

That screenshot is in Romanian and also shows a few other addons, but the issue is there.

### Environment

Browser:  Chromium 114.0.5735.133 (Official version) for Linux Mint (64 bits) 
Scratch Addons version:  1.33.3
Operating system:  Linux Mint 21.1 (Cinnamon 5.6.8, Kernel 5.19.0-46-generic)

**Comment by Secret-chest** [comment]
sorry for that curse btw, just replying to one advertising on each of @griffpatch 's projects

**Comment by medlans** [comment]
Yeah, I could replicate:
![wow](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/c5ff9ff9-49f2-4ede-ba5b-e52c3fa06d8d)
![yesigotalertedforthis](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/77395ac8-18bb-48cd-bdeb-15705a77abbe)
By the way, I had to change it to orange and also had to change my alert message to blue after that.

**Comment by DNin01** [comment]
> sorry for that curse btw, just replying to one advertising on each of @griffpatch 's projects

(Unrelated to issue): It's better to report spam or abuse without responding to it, much like how you would report a phishing email without clicking any links. It's much easier for moderators to take care of the situation and you don't risk the comment authors getting mad at you.

**Comment by medlans** [comment]
Also, here's some other parts that are still blue and purple for me:
1. Project loading screen (I have 2.0 presets for the editor including the actual colors, blocks, etc and it was showing grey before)
2. "More" button in backpack
3. Sign in button (in the editor)

**Comment by mybearworld** [comment]
It'd probably be better to use `automodmute` instead of cursing.
