### ISSUE TITLE
Cannot mark message as read

### ISSUE THREAD

**Issue by kokofixcomputers** [ScratchAddons/ScratchAddons#6391]
### Description

I cannot mark messages as read in the scratch addons messaging tab when i click the button nothing happens

### Steps to reproduce

1. Have some messages
2. Wait for scratchaddons to load the messages
3. Click on Mark Messages as Read
4. Done

### Environment

Browser: Chrome
Scratch Addons version: 1.33.2
Operating system: MacOS

**Comment by WorldLanguages** [comment]
> Browser: Chrome

which Chrome version? @kokofixcomputers 
Did you download from Chrome Web Store?

**Comment by kokofixcomputers** [comment]
Yes i downloaded it from the Chrome Web Store.

**Comment by WorldLanguages** [comment]
Cannot reproduce in Google Chrome 114.0.5735.199

@kokofixcomputers Are you using a Chromium fork, such as Brave? That could be causing the issue?

**Comment by WorldLanguages** [comment]
I'll assume this is caused by https://github.com/brave/brave-browser/issues/30854
