### ISSUE TITLE
Some elements that use the color purple can't be changed with Editor dark mode and customizable colors

### ISSUE THREAD

**Issue by EliteNinja2084** [ScratchAddons/ScratchAddons#6392]
### Description

When you edit the direction with the sprite editor, (This area: 
![image](https://github.com/ScratchAddons/ScratchAddons/assets/138089723/4b7b0c45-0996-48f8-a7ca-fce922b12eae) , not the block) the direction dial and dragging a sprite border is based off of the new purple look even with the setting to replace those colors with blue.

### Steps to reproduce
The direction dial
1. Open the editor
2. Click on the direction thing near the sprites name
3. Its purple!

Dragging a sprite border
1. Open the editor
2. Drag a sprite/costume
3. The border is purple!
### Demonstration(s) and additional context
The direction dial:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/138089723/756fb42e-7f7e-42f4-8739-34790eff260e)
Dragging a sprite border:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/138089723/4b29c4b2-225c-4828-9ec3-bdfaacfaba97)
and 
![image](https://github.com/ScratchAddons/ScratchAddons/assets/138089723/cfa96743-4a89-4a83-88df-f8c059843441)

### Environment

Browser:  Opera GX
Scratch Addons version:  1.10.0
Operating system:  Windows

**Comment by medlans** [comment]
This also happens with other places:
![Embed](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/ce978c02-681d-4147-8d25-9dd9938822fa)
(I've seen this also in the record project video of scratch addons, the "More" button in backpack, alerts, the sign in button when logged out in the editor, creating new lists/variables/messages, and join scratch (editor))

**Comment by EliteNinja2084** [comment]
> This also happens with other places: (I've seen this also in the record project video of scratch addons, the "More" button in backpack, alerts, the sign in button when logged out in the editor, creating new lists/variables/messages, join scratch (editor), and the share to/embed button on the project page)

Want me to add those?

**Comment by medlans** [comment]
> > This also happens with other places: (I've seen this also in the record project video of scratch addons, the "More" button in backpack, alerts, the sign in button when logged out in the editor, creating new lists/variables/messages, join scratch (editor), and the share to/embed button on the project page)
> 
> Want me to add those?

Yea, if you select the boxes in some of those it still shows purple, and it’s not just the editor.
