### ISSUE TITLE
Accessibility: 60 FPS state is distinguished by color

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6404]
30 FPS and 60 FPS are differentiated by coloring the green flag blue with a [hue rotate](https://github.com/ScratchAddons/ScratchAddons/blob/6794e137ce2b3da41194a81ab98ba10906d2f6a5/addons/60fps/userscript.js#L16-L18), which may not be accessible for colorblind users.

![Green flag vs 60FPS flag](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/472b84aa-f1e3-4505-a619-5172801c15c5)

You could say that seeing the project obviously running smoother could indicate that as well, but it's also a good idea to provide intuitive feedback that the user has turned on 60 FPS mode, which is what the blue flag is there for.

**Comment by BroJac5246** [comment]
Also, blue doesn't make as much sense after the colors update so now is a good time to change it.

**Comment by Secret-chest** [comment]
Could it be a blue flag with a fast-forward symbol inside?

**Comment by DNin01** [comment]
> Could it be a blue flag with a fast-forward symbol inside?

I like the idea, but it may not be big enough. Perhaps a fast-forward symbol next to the flag, like on the bottom-right corner of the flag image?

**Comment by rgantzos** [comment]
> > Could it be a blue flag with a fast-forward symbol inside?
> 
> I like the idea, but it may not be big enough. Perhaps a fast-forward symbol next to the flag, like on the bottom-right corner of the flag image?

You just need to be able to notice a difference. It is good for it to be readable, but the important factor is that it is noticeable.

**Comment by JoanRiosiPla** [comment]
Hi, I started working on this and I think I've got it working. Regarding the icon, how about this one?:
![scratchFlagFast](https://github.com/ScratchAddons/ScratchAddons/assets/104719628/f65ae773-7cce-49f9-96ac-dc4664fb9d3d)

**Comment by Secret-chest** [comment]
I personally think the flag should still be blue.
