### ISSUE TITLE
scratchr2: message badge should be laggier

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#6424]
### Why this would be helpful

On scratch-www pages, the message page is very laggy.

### My suggestion

This should be brought to scratchr2 pages when the addon is enabled, to maintain consistency.

**Comment by WorldLanguages** [comment]
?

**Comment by BroJac5246** [comment]
Am I misreading this or are you suggesting that we intentionally slow down a page? Also I'm not quite sure what page you're talking about. What lags? Can you give a video comparison? And why would we make a page lag in the first place? That just creates a worse user experience.

**Comment by Secret-chest** [comment]
Joking

**Comment by mxmou** [comment]
> Am I misreading this or are you suggesting that we intentionally slow down a page? Also I'm not quite sure what page you're talking about. What lags? Can you give a video comparison? And why would we make a page lag in the first place? That just creates a worse user experience.

I think the OP meant the message count in the navigation bar, not the messages page. It's often outdated on scratch-www pages because of caching. I don't think trying to make scratchr2 pages behave the same makes sense because they currently show the more accurate number.

**Comment by DNin01** [comment]
If anything, we should probably do the opposite - bring the messages badge with faster refreshes to scratch-www.

**Comment by DNin01** [comment]
I understand how making the two page generations have a consistent messages badge could help reduce confusion. We just need to decide which one to use.
