### ISSUE TITLE
Pop-up sized incorrectly when opened from Firefox' overflow menu

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#643]
**Describe the bug**

When the extension's pop-up is opened from the overflow menu on Firefox, the pop-up has an incorrect size, indicated by the presence of the scrollbars.

**To Reproduce**

1. Place Scratch Addons inside the overflow menu (either resize your window or put it manually)
2. Open the pop-up by clicking the icon
3. Observe

**Expected behavior**

The pop-up should have a correct size, or should automatically adjust with the set size. 

**Screenshots**

![image](https://user-images.githubusercontent.com/11584103/98095730-82f9e700-1ebd-11eb-8acd-7a23f8ac5177.png)

**Device**

Mozilla Firefox 82.0.2, SA 1.2.1

**Comment by WorldLanguages** [comment]
I have no idea what the overflow menu is.

**Comment by Hans5958** [comment]
I wanted to take a picture but this laptop is quite laggy, but this should help.

https://support.mozilla.org/en-US/kb/customize-firefox-controls-buttons-and-toolbars

**Comment by wgyt735yt** [comment]
> 
> 
> I have no idea what the overflow menu is.

The overflow menu is opened using the button I circled:
![image](https://user-images.githubusercontent.com/68466727/98545703-de342c80-2263-11eb-912f-3fdb928bf6f4.png)

**Comment by Hans5958** [comment]
yea right

**Comment by mxmou** [comment]
Firefox 89 changed the overflow menu width, which fixes this. I'll make a PR anyway, for compatibility with older Firefox versions and to fix other issues.

**Comment by RedGuy12** [comment]
Resolved by #2274 (the wrong issue was linked)
