### ISSUE TITLE
Recommend VSCode extensions

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6430]
### Why this would be helpful

The Prettier GitHub action would probably be better as a VSCode extension recommendation.

### My suggestion

Now that we finally have some VSCode settings we should add some extension recommendations for things like Prettier. After that we could make the action manual or remove it entirely.

### Additional context

#3968 adds this along with some other things but it's from December 2021.

**Comment by DNin01** [comment]
Speaking of Prettier, I use it now on github.dev.

#6272 recommends extensions related to Vue within the webpages directory.

**Comment by Samq64** [comment]
Closing in favour of #6440
