### ISSUE TITLE
With `editor-compact` enabled, turning on Turbo Mode pushes the project controls up

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6435]
### Description

When Turbo Mode is enabled with `editor-compact` enabled, the text "Turbo Mode" doesn't seem to have enough space to fit where it usually does, causing the project controls row to be pushed up. At least, that's what I think.

### Steps to reproduce

1. Enable `editor-compact`.
2. Shift+Click the green flag to turn on Turbo Mode.

### Demonstration(s) and additional context

https://github.com/ScratchAddons/ScratchAddons/assets/106490990/96ae8078-ad08-4c0b-a1cd-21f4fd6d80cb

### Environment

Browser: Edge 115
Scratch Addons version: v1.34.0-pre
Operating system: Windows 11

**Comment by WorldLanguages** [comment]
Clone counter affects it too I think
