### ISSUE TITLE
Make default settings for `mediarecorder` customizable

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6438]
### Why this would be helpful

Project video recorder currently has a non-customizable set of default settings, and it looks to me like you can't change them, meaning you have to set all of the settings to what you want every time you hit record.

### My suggestion

It would be nice to be able to customize the defaults from the addon's settings. `onion-skinning` and `paint-snap` already do this.

**Comment by DNin01** [comment]
> > It would be nice to be able to customize the defaults from the addon's settings.
> 
> 
> 
> Maybe we could remember the settings from the last time the user recorded? No need to add new addon settings IMO.

If we do that, should we save the settings in storage or not do that and only remember until the editor is closed or refreshed?

**Comment by WorldLanguages** [comment]
In storage would work, I think.

**Comment by DNin01** [comment]
> In storage would work, I think.

How often would the user reuse the same settings across recording sessions? The main reason I want it to remember my settings is because sometimes I discard a recording and try again.

**Comment by DNin01** [comment]
On the topic of adding addon settings, it's possible not all settings in the "Start Recording" settings modal really need to also be in addon settings. Maybe only some of them should be there.

**Comment by WorldLanguages** [comment]
> How often would the user reuse the same settings across recording sessions?

The last used settings are probably more useful than setting them to the default each time.
