### ISSUE TITLE
columns too tall when switching back to code editor with editor-compact

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6444]
### Description

When switching to another editor tab and back with both the two-column category menu and compact editor enabled the category selector takes up way too much vertical space.

### Steps to reproduce

1. Enable `columns` and `editor-compact`
2. Open the editor
3. Switch to the costumes tab
4. Switch back to the code tab

### Demonstration(s) and additional context

![image](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/9e0c8eae-bb50-4b42-87dc-ccfd1c6ee380)

### Environment

Browser: Firefox 115
Scratch Addons version: master
Operating system: Linux

**Comment by WorldLanguages** [comment]
Probably `addClass()` isn't being called when it should be
