### ISSUE TITLE
`editor-compact`: When dynamically enabling `echo-effect`, the echo button doesn't have a "title" attribute

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6445]
### Description

When Compact editor is enabled and you dynamically enable the Echo effect button addon, the echo effect button in the sound editor doesn't have a tooltip. It does when you reload the page.

### Steps to reproduce

1. Enable `editor-compact`. Make sure the `hideLabels` setting is enabled.
2. Open the Sounds tab in the editor.
3. Enable `echo-effect`.
4. Hover over any effect button (faster, slower, etc.). They have tooltips.
5. Hover over the echo effect button. It doesn't have a tooltip.
6. Reload the page.
7. Go back to the Sounds tab and hover over the echo effect button. It now has a tooltip.

### Environment

Browser: Edge 115
Scratch Addons version: v1.34.0-pre; https://github.com/ScratchAddons/ScratchAddons/commit/d2a9ce32afd85340702c271d579b7dc6ac455212
Operating system: Windows 11

**Comment by Samq64** [comment]
Are there any other potential addons that are effected by this?

**Comment by WorldLanguages** [comment]
> Are there any other addons that could effected by this?

I don't think so, no other addons add their own buttons to the costume/sound editors (onion skinning and snapping don't count)
