### ISSUE TITLE
Add the ability to customize all parts of the Scratch Website

### ISSUE THREAD

**Issue by aetinx** [ScratchAddons/ScratchAddons#645]
**Is your feature request related to a problem? Please describe.**

Add an option to change what the actual Scratch website looks like, as in colours and fonts (add the ability to upload fonts from the user's PC).

**Describe the solution you'd like**

The option to change colours and fonts of any part of the website.

**Describe alternatives you've considered**

null

**Additional context**

null

**Comment by mxmou** [comment]
The ability to customize colors will probably be added to Scratch 2.0 → 3.0 in a future update. Changing fonts could be a new addon.
