### ISSUE TITLE
Sometimes some setting inputs go missing on the settings page (Vue 3)

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6453]
### Description

Sometimes on the settings page some setting inputs either disappear or leave just the reset button. The setting labels and the settings themselves don't seem to be effected. There are no errors in the console on the settings page.

### Steps to reproduce

I can't reproduce the bug consistently.

### Demonstration(s) and additional context

![](https://media.discordapp.net/attachments/751207339545198682/1125527919335329833/missing-settings.jpeg)
![](https://media.discordapp.net/attachments/819307061493760031/1133475867729862757/image.png)

### Environment

Browser: Chromium 115
Scratch Addons version: https://github.com/ScratchAddons/ScratchAddons/commit/a9f139029c4656583c8a05a4d4593b15dabe0665 (#6272)
Operating system: Linux

**Comment by apple502j** [comment]
Issues in a PR should be noted on that PR, or on Graham's fork.

**Comment by GrahamSH-LLK** [comment]
nah he's supposed to put this here. he's the only one who seems to experience this and it's not a major issue anyways

**Comment by GrahamSH-LLK** [comment]
This is _not_ just a Vue 3 branch issue. However, only one person has ever been able to repro.
