### ISSUE TITLE
Keyboard shortcuts may not work on alternate keyboard layouts

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6455]
### Description

I haven't tested this because I only use a QWERTY keyboard, but apparently, the `code` property of `KeyboardEvent` is not affected by your keyboard layout. Instead, `code` basically returns the QWERTY-equivalent character of the key you pressed on your keyboard, which may useful if you are making a web game, since you can tie controls to physical positions on the keyboard instead of characters on the keyboard.

You can learn more about it on MDN: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

Potentially affected scripts: [Code search (7 items)](https://github.com/search?q=repo%3AScratchAddons%2FScratchAddons+%28e.code+OR+event.code%29&type=code)

### Steps to reproduce

Paste this in your browser console:
```js
window.addEventListener(
  "keydown",
  (e) => {
    console.log(e.code);
  }
);
```

Then, with an alternate keyboard layout, press a key that is different on a QWERTY keyboard (such as 'A' on AZERTY. You will see "KeyQ" in the console).

### Environment

Browser: Edge 115
Operating system: Windows 11

**Comment by WorldLanguages** [comment]
Related merged PR: #5883
