### ISSUE TITLE
Why is Scratch 2.0 (2015) an option in `dark-www`?

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6459]
This is actually a Scratch _3.0_ color scheme, but the old version (it was updated to the current blue we know and love in the editor during the preview for accessibility reasons, until it was again updated to purple last month). I don't think anyone cares that the blue was made a slightly darker shade (especially by now), so why do we need to offer this preset? It's barely any different from what the colors are now.

Saying 2.0 kind of makes sense because it was during the 2.0 era, but this color scheme still applies to `scratch-www`. Confusing.

So let me ask, why was it decided that this should be added? Who would actually use this daily? I would've personally suggested not adding it due to the points above.

**Comment by WorldLanguages** [comment]
Note that we can remove old presets without breaking anything (for now...)

**Comment by medlans** [comment]
Prob called that because 3.0 development started in like 2016 I believe. Though I honestly thought when I made the issue that the scratchr2 preset would be the only one.

**Comment by apple502j** [comment]
Well, there's no problem with having too many presets I think...

**Comment by DNin01** [comment]
> Well, there's no problem with having too many presets I think...

That is an option.

**Comment by mxmou** [comment]
> This is actually a Scratch _3.0_ color scheme, but the old version (it was updated to the current blue we know and love in the editor during the preview for accessibility reasons, until it was again updated to purple last month).

It was never actually used in any development version of the 3.0 editor, only in some early concepts. It was most likely changed to be consistent with the block color palette, not for accessibility, because neither color is accessible.

> I don't think anyone cares that the blue was made a slightly darker shade (especially by now), so why do we need to offer this preset? It's barely any different from what the colors are now.

Few people will use it, but I don't think that means we shouldn't add it. It was used on the website for more than two years, and the difference between it and the 3.0 colors is quite noticeable.

> Saying 2.0 kind of makes sense because it was during the 2.0 era, but this color scheme still applies to `scratch-www`. Confusing.

Many Scratchers call scratch-www pages "3.0 pages" because they look similar to the 3.0 editor, but the scratch-www front page was released before the development of Scratch 3.0 even started.

> So let me ask, why was it decided that this should be added? Who would actually use this daily? I would've personally suggested not adding it due to the points above.

We can't add every preset someone might want to use, but I think having presets for earlier versions of Scratch's design makes sense.

**Comment by WorldLanguages** [comment]
The question was answered. I guess if you want to explicitly propose to remove the preset you may create another issue.

**Comment by DNin01** [comment]
I actually meant for this to kind of be a suggestion to revert it, but it came out as more of a question.

I thought most people wouldn't remember it or care for it and that's why I didn't understand why we decided to add it.

There are two common bars for deciding whether to add a preset or not. You can add just the ones most people will use, which excludes this preset, or add pretty much all the presets you know people could possibly like, for quicker access, which includes this. Get what I mean?

It makes sense for an extension with customization in mind that's not affiliated with Scratch that we choose the latter and not be as strict about what becomes a preset, which, I suppose, is why this preset came to be.

**Comment by Secret-chest** [comment]
> neither color is accessible.

Accessibility isn't binary.
