### ISSUE TITLE
https://scratch.mit.edu/ at the beginning of match patterns should be optional

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#646]
**Is your feature request related to a problem? Please describe.**

All userstyle and userscript matches start with https://scratch.mit.edu/.

**Describe the solution you'd like**

That should be optional.

**Comment by WorldLanguages** [comment]
Maybe. We might allow addons to support other sites like Turbowarp, so omitting that might get ambiguous.

**Comment by Hans5958** [comment]
I think it depends on the permissions. Right now it's just the Scratch site. Maybe when we expand our permission, then we'll talk.

BTW, just in case the permission is going to be expanded, please also add scratchaddons.com and implement #.

**Comment by WorldLanguages** [comment]
@Hans5958 Required permissions won't ever be expanded unless scratch.mit.edu migrates to some other domain. These would be optional permissions, and in consequence Turbowarp support would be disabled by default.
