### ISSUE TITLE
Replace project loading screen with the projects thumbnail

### ISSUE THREAD

**Issue by TheYande** [ScratchAddons/ScratchAddons#6461]
### Why this would be helpful

simple and small addon that makes the loading screen a little more interesting.
the thumbnail is usually rarely seen, only when first seeing the project on the user page and front page , this lets the user see the thumbnail a little more

### How this addon works

this addon would move the current loading screen into the corner and fill the extra space with the projects thumbnail

**Comment by DNin01** [comment]
It's a nice idea, but addons aren't usually this small and minor.

**Comment by Samq64** [comment]
Maybe this could fit into #4696 or the progress bar addon? The main problem is thumbnails are usually pretty low resolution so it wouldn't look good on the full window loading screen.

**Comment by penguinmoose** [comment]
It would also add some interesting content to the somewhat dull loading screen.

@Samq64 I think that this can be integrated into the progress bar addon. However, I'm not sure how the loading bar should integrate into the thumbnail. The loading screen should still look like a loading screen, so the user doesn't confuse the loading screen as the project itself.

Resolution shouldn't be a big problem. Normally, project thumbnails are shown at project size before the user hits the green flag - and they look ok. See screenshot:

<img width="504" alt="Screenshot 2023-07-27 at 2 29 31 PM" src="https://github.com/ScratchAddons/ScratchAddons/assets/67451414/9dc91f9c-454d-4684-bb0b-c328b72f9ec5">

**Comment by DNin01** [comment]
> @Samq64 I think that this can be integrated into the progress bar addon. However, I'm not sure how the loading bar should integrate into the thumbnail. The loading screen should still look like a loading screen, so the user doesn't confuse the loading screen as the project itself.

Could the thumbnail be blurred while the project is loading?

**Comment by DNin01** [comment]
Combining this with the `progress-bar` addon could lead to a "Better loading screen" addon with new options.

**Comment by medlans** [comment]
> Combining this with the `progress-bar` addon could lead to a "Better loading screen" addon with new options.

 I was just thinking about having an option for progress bar colors (as in the color of the loading part and what other parts look like) and a custom loading screen color, I had to use something I was working on to get it blue and grey (before I saw this, and I was trying to make it look like 2.0) so maybe customizable loading screen or something

**Comment by Samq64** [comment]
I think this could be part of #4696 but the thumbnail would be darkened and placed under the loading animation.

**Comment by BroJac5246** [comment]
> I think this could be part of #4696 but the thumbnail would be darkened and placed under the loading animation.

Could that be part of `progress-bar` as well?

**Comment by DNin01** [comment]
> > I think this could be part of #4696 but the thumbnail would be darkened and placed under the loading animation.
> 
> Could that be part of `progress-bar` as well?

We could, but if the progress bar theme of this addon goes away then what would happen to the progress bar for saving projects?

**Comment by Samq64** [comment]
> Could that be part of `progress-bar` as well?

That's a feature and I would consider the other two themes.

**Comment by Samq64** [comment]
One thing to consider is that the loading screen is taller than stage so it might be a little tricky to get it to look seamless.

**Comment by Samq64** [comment]
I added this to #4696.
