### ISSUE TITLE
Add latestUpdate to some recent changes

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6463]
This is a reminder for myself before releasing v1.34.0
I think some changes, specially in the dark mode addon, might deserve a latestUpdate change

**Comment by Samq64** [comment]
Are there any other addons that need it?

**Comment by WorldLanguages** [comment]
> Are there any other addons that need it?

@Samq64 I don't think so, I believe I was just thinking about the new Scratch 2.0 presets, which we could highlight in the settings page, instead of just listing it in the changelog

**Comment by Samq64** [comment]
> I believe I was just thinking about the new Scratch 2.0 presets, which we could highlight in the settings page, instead of just listing it in the changelog

Maybe in the future we could add the ability to add presets to `latestUpdte`?
