### ISSUE TITLE
Tips/Things to try in settings page

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#647]
**Is your feature request related to a problem? Please describe.**

When a new update comes out, chances are a user doesn't look at the channel log and just pick addons they think they know what they do. You know how at the bottom of the issues page and pr page of GitHub, there are always these little things like:
`ProTip! Type g i on any issue or pull request to go back to the issue listing page.` I think we should have these little tips somewhere on our settings page.

**Describe the solution you'd like**

A little message will appear somewhere on the screen to try something. The message will pick random from an array of messages that it can say.

**Describe alternatives you've considered**

Not do that at all lol.

**Additional context**
By @mxmou:
![image](https://user-images.githubusercontent.com/51849865/98284037-d09b5000-1fa0-11eb-9cab-03581acf15c9.png)

**List of Tips to say**
Did you know you could make an addon? Press [here](https://github.com/ScratchAddons/ScratchAddons/wiki/Creating-an-addon)!
Hot Tip: Some addons have options, enable them in the dropdowns!

**Comment by YOYITsM3M8** [comment]
Hmmhmhmmhmhmhm

**Comment by TheColaber** [comment]
Btw, The message doesn't need to go at the bottom, I was just trying it there for example.

**Comment by YOYITsM3M8** [comment]
The font size looks a bit too big

**Comment by TheColaber** [comment]
We can change it... I just did a quick little think with the inspector tools so this won't be the end result.

**Comment by YOYITsM3M8** [comment]
:c some teacher at my school died this morning to COVID. :C

**Comment by GrahamSH-LLK** [comment]
Tooltips might be better suited.

**Comment by TheColaber** [comment]
> Tooltips might be better suited.

No one is going to actually know to hover over something...

**Comment by GrahamSH-LLK** [comment]
Tooltips... that open automatically, and stay there until they are closed.

**Comment by TheColaber** [comment]
> Tooltips... that open automatically, and stay there until they are closed.

Mockup? I don't quite understand...

**Comment by mxmou** [comment]
@TheColaber Probably something like this?

![image](https://user-images.githubusercontent.com/51849865/98284037-d09b5000-1fa0-11eb-9cab-03581acf15c9.png)
In WinUI this is called a targeted teaching tip.

**Comment by TheColaber** [comment]
Nice! I guess all we need now is a list of tips/didYouKnows... anyone?

**Comment by YOYITsM3M8** [comment]
Did you know you could make an addon? Press **here**

**Comment by YOYITsM3M8** [comment]
Hot Tip: Some addons have options, enable them in the dropdowns!

**Comment by Explosion-Scratch** [comment]
Support but the font's to big and the icon looks terrible. (No offence)

**Comment by TheColaber** [comment]
> Support but the font's to big and the icon looks terrible. (No offence)

are you talking about the current mockup or the one that I had before?

**Comment by TheColaber** [comment]
Revisiting issue - seems to me that there is really nothing important that could be displayed in these "tips". if there is, there probably a better ui/design we could use to suggest the user to try something.

**Comment by OneShot-Niko** [comment]
> Revisiting issue - seems to me that there is really nothing important that could be displayed in these "tips". if there is, there probably a better ui/design we could use to suggest the user to try something.

I know this was closed, however perhaps similarly to the project loading screen in some way?
<sub>Although even that just uses flavor text such as "Inflating gobos"</sub>

**Comment by BroJac5246** [comment]
> > Revisiting issue - seems to me that there is really nothing important that could be displayed in these "tips". if there is, there probably a better ui/design we could use to suggest the user to try something.
> 
> I know this was closed, however perhaps similarly to the project loading screen in some way?
> <sub>Although even that just uses flavor text such as "Inflating gobos"</sub>

I would actually really love to see that on the popup and settings pages since those take too long to load. A simple animation would be better than starting at placeholders.

**Comment by Samq64** [comment]
> I would actually really love to see that on the popup and settings pages since those take too long to load.

#6272 solves the performance issues so it wouldn't make much sense to do that now.

**Comment by TheColaber** [comment]
> I would actually really love to see that on the popup and settings pages since those take too long to load. A simple animation would be better than starting at placeholders.

It only takes me about 1 second to load the settings page... how long does it take for you? And yes, once we bump to a higher version of vue, like https://github.com/ScratchAddons/ScratchAddons/pull/6272, this problem should cease to exist.

**Comment by BroJac5246** [comment]
> > I would actually really love to see that on the popup and settings pages since those take too long to load. A simple animation would be better than starting at placeholders.
> 
> It only takes me about 1 second to load the settings page... how long does it take for you? And yes, once we bump to a higher version of vue, like https://github.com/ScratchAddons/ScratchAddons/pull/6272, this problem should cease to exist.

I timed it and it took 8 seconds.

**Comment by TheColaber** [comment]
Do you just have a really slow computer or slow wifi?

**Comment by BroJac5246** [comment]
> Do you just have a really slow computer or slow wifi?

It's a cheap Chromebook that isn't super fast but also isn't awfully slow — it's fine for web browsing and it's reasonable to expect that many users will use similar devices.

**Comment by GrahamSH-LLK** [comment]
> > Do you just have a really slow computer or slow wifi?
> 
> It's a cheap Chromebook that isn't super fast but also isn't awfully slow — it's fine for web browsing and it's reasonable to expect that many users will use similar devices.

How long does it take on my PR?

**Comment by BroJac5246** [comment]
> > > Do you just have a really slow computer or slow wifi?
> > 
> > It's a cheap Chromebook that isn't super fast but also isn't awfully slow — it's fine for web browsing and it's reasonable to expect that many users will use similar devices.
> 
> How long does it take on my PR?

About 1 1/2 seconds. It's much, much better.

**Comment by WorldLanguages** [comment]
Nice to hear that the settings page slowness is mainly caused by Vue v1.
