### ISSUE TITLE
Markdown support in addon manifests

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6474]
### Why this would be helpful

On the settings page addon descriptions often reference other addons or things such as keybinds. Currently we use quotes but italics would probably be better. We also mention a website in a few addon descriptions and being able to link them would be nice. There might also be some cases where bold text could be useful.

### My suggestion

Adding basic markdown support to addon descriptions and notices.

### Possible alternatives

Just adding italic support or continue using quotes. For links we could automatically linkify them.

**Comment by apple502j** [comment]
Rejected for now; the performance cost, the burden caused by making it translator-friendly, and the additional dependency would not outweigh the potential benefits. Also, italics are bad (especially in CJK fonts)

**Comment by WorldLanguages** [comment]
@apple502j Can you propose a way so that, at least, descriptions and notices can have clickable plain text links on them? Of course, we wouldn't want translators to be able to put any link they want.

**Comment by apple502j** [comment]
We don't need a full Markdown syntax for any of these. We just have to allow placeholders. That does require changes in addon.json schema, though, and it is a little more painful than other parts since addon descriptions are used in the website and potentially TurboWarp.
