### ISSUE TITLE
Forums error messages are still very bright with dark-www

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6475]
### Description

When you get an error such as "Post can't be empty", "Sorry, you have to wait 60 seconds between posts.", and have dark-www enabled, the addon doesn't change the error.

### Steps to reproduce

1. Get an error
2. Look at it

### Demonstration(s) and additional context

![The error message being very bright](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/27004c6d-f177-48fa-bb8e-580e64c36334)
It'd be better like:
![The error message blending in](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/eb4db188-7b0b-46d3-897a-398852fffc36)

### Environment

Browser: Edge 115
Scratch Addons version: 1.33.3
Operating system: Windows

**Comment by WorldLanguages** [comment]
These errors (same CSS classes) are also used by the extension when trying to post the words "scratch addons" or when making a new post in Bugs&Glitches.

**Comment by mybearworld** [comment]
Annoyingly, these errors have a color of #f5f5f5 by default, which is a unique color...
