### ISSUE TITLE
Scratch is supposedly upgrading their API and services

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6486]
From the [announcement about upcoming maintenance](https://scratch.mit.edu/discuss/topic/702112/) (I'm glad I always catch these things):
> **Why are we making changes?**
We are moving our API and other Scratch services from an older version of our web service platform to a new configuration. In order to do this work as quickly as possible, we need to temporarily pause site features and the site itself.

This might result in some unexpected behavior in Scratch Addons.

**Comment by mybearworld** [comment]
Might be good to add to the update notification

**Comment by penguinmoose** [comment]
> Might be good to add to the update notification

That's a good idea, but it relies on an update to release before those API changes. Of course, we could just push an update solely for that notification, but that's kind of lame.

**Comment by CST1229** [comment]
I think this is just something like moving servers, not actual API changes.

**Comment by WorldLanguages** [comment]
I don't think we can expect anything from this, so this will be just one more downtime

**Comment by apple502j** [comment]
@DNin01 Please do not file issues like this. Scratch downtime causes no issues for us. If there are significant changes, we will file instead.
