### ISSUE TITLE
Preview project Notes & Credits and Instructions

### ISSUE THREAD

**Issue by Steve0Greatness** [ScratchAddons/ScratchAddons#6487]
### Why this would be helpful

Sometimes I want to see what the text I've written in Instructions/Notes & Credits will look like to other users.

### How this addon works

This would add an `.action-button` on project pages that will replace the `textarea` with a rendered version.

### Possible alternatives

Open a private window, but this doesn't work on unshared projects.

### Additional context

![Screenshot 2023-08-04 010159](https://github.com/ScratchAddons/ScratchAddons/assets/75220768/a01eb4fe-1a29-4f87-b240-5e64d4c58af0)

(The above image is a working version([Steve0Greatness/ScratchAddons:Preview-Description](https://github.com/Steve0Greatness/ScratchAddons/tree/Preview-Description)). I just thought I should make an issue before, submitting a PR because I think them's the rules.)

**Comment by WorldLanguages** [comment]
Yeah, go ahead with the PR. This is obviously useful.
I don't think this is a duplicate, but it might be.

**Comment by WorldLanguages** [comment]
Theoretically this could also be extended to studio descriptions, "about me", "what i'm working on", and even comments.
