### ISSUE TITLE
"Mark messages as read" does not work in Brave browser

### ISSUE THREAD

**Issue by TriforceMayhem** [ScratchAddons/ScratchAddons#6494]
### Description

I recently switched to the Brave browser. Scratch Addons works entirely fine in Brave aside from the "Mark messages as read" button, which doesn't appear to do anything.

### Steps to reproduce

1. Install Brave
2. Install Scratch Addons in Brave
3. Log into Scratch
4. Receive a message
5. Click on the "Mark messages as read" button

### Environment

Browser: Brave v1.56.20
Scratch Addons version: v1.33.3
Operating system: Windows 10

**Comment by WorldLanguages** [comment]
This appears to be a Brave bug: https://github.com/brave/brave-browser/issues/30854

I'm keeping this open in case we can do something to fix this from our side! I'm not sure, as I use Brave and haven't experienced this bug.

**Comment by RedGuy12** [comment]
https://github.com/brave/brave-browser/issues/30854 was closed as resolved in Nightly v1.63.94

**Comment by WorldLanguages** [comment]
We'll assume this was fixed, then.
