### ISSUE TITLE
Show exact count (studios) counting incorrectly

### ISSUE THREAD

**Issue by RokCoder** [ScratchAddons/ScratchAddons#650]
**Describe the bug**

I noticed the project count for this studio (https://scratch.mit.edu/studios/25643089/projects/) and thought it seemed a little on the high side. A quick check shows there to be around 160 projects in it.

**To Reproduce**

1. Go to https://scratch.mit.edu/studios/25643089/projects/
2. See the projects count
3. Count the projects

**Expected behavior**

The project count should match the number of projects :)

**Screenshots**

![image](https://user-images.githubusercontent.com/20208339/98383768-d0ed2700-2044-11eb-96e4-c409bf0814bf.png)

**Device (please complete the following information):**

- Microsoft Windows 10 Enterprise Version 10.0.18363 Build 18363
- Google Chrome Version 86.0.4240.183 (Official Build) (64-bit)

**Additional context**

N/A

**Comment by WorldLanguages** [comment]
Thanks for reporting!
This will be fixed on the v1.3.0 release.
