### ISSUE TITLE
Better customizable link style settings UX

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6503]
### Why this would be helpful

The current way the customizable link style settings are displayed to the user have some issues:

1. There's a setting labelled default that isn't the default
1. That default setting is useless since it basically disables the addon
1. The bold setting can be confusing since links are already bold in a lot of places

The default setting was probably just left over from a last minute change.

### My suggestion

Replacing the link style setting with a toggle to make all links bold and an option to choose none as the underline style. This would also allow users to have bold underlined links.

### Additional context

![image](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/30831d57-de10-408e-a416-8fed3600409c)

Unfortunately I think strings are closed for this release.

**Comment by WorldLanguages** [comment]
I decided to include this addon with the "beta" tag in this release as an experiment, so don't worry too much about these. Next version, we can change the addon ID and anything we want from the manifest, and migrate user settings.

**Comment by Samq64** [comment]
Related: https://github.com/ScratchAddons/ScratchAddons/pull/6400#issuecomment-1666850429
> Why can't be both bold and underline be enabled?

**Comment by mybearworld** [comment]
The bold option should probably have three values - "Default", "Make all non-bold", "Make all bold" (or similar), to avoid the issue in #6532.
