### ISSUE TITLE
The forum breadcrumbs and page numbers are styled as links with `colorblind` and `scratchr2`

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6534]
### Description

`scratchr2` restyles the breadcrumbs and page numbers in the forums so they do not look like links. However, `colorblind` styles them as such.

### Steps to reproduce

1. Enable the underline option in `colorblind`
2. Enable `scratchr2`
3. Go to a forums page at least one level deep

### Demonstration(s) and additional context

![The breadcrumbs being styled as links](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/ac55a744-cff5-4d12-b581-be7a77c50515)
![The page numbers being styled as links](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/41e6209a-f633-4fc6-ab68-e275647c30fa)

### Environment

Browser: Edge 115
Scratch Addons version: 1.34.0
Operating system: Windows

**Comment by mybearworld** [comment]
Not entirely sure if this would be bad for accessibility if changed? The border seems to distinguish it pretty well already, though.

**Comment by penguinmoose** [comment]
> Not entirely sure if this would be bad for accessibility if changed? The border seems to distinguish it pretty well already, though.

The border is a bit faint, but I think that's fine. The border does look kind of weird, especially if you use a dashed or dotted underline.

If we do want the page links to be underlined, we should be able to just add it to the exclude selectors in the userstyle.

**Comment by mybearworld** [comment]
> If we do want the page links to be underlined, we should be able to just add it to the exclude selectors in the userstyle.

The problem with that is that the exclusion should only happen when `scratchr2` is enabled. Otherwise, they are styled as links and should be considered as such by `colorblind`. This seems like it will require JavaScript.

**Comment by DNin01** [comment]
I noticed this while developing and decided it isn't a huge deal. We can come back to work on it now, though. If I remember, the underline disappears while you're hovering, right? If so, it probably won't be too hard to always remove the underline through a userstyle in `scratchr2`.

**Comment by mybearworld** [comment]
> If I remember, the underline disappears while you're hovering, right?

It doesn't.
