### ISSUE TITLE
Usernames of `studio-followers` panel don't get affected by `colorblind`

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6538]
### Description

The `studio-followers` panel styles its usernames as links, but `colorblind` doesn't style it.

### Steps to reproduce

1. Enable the underline option in `colorblind`
2. Enable `studio-followers`
3. Go to a studio you manage
4. Open the panel of `studio-followers`

### Demonstration(s) and additional context

![The "Invite followers to studio" panel not having styled links](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/0f02f1b5-ff9c-4adf-a915-829efc008e3d)

### Environment

Browser: Edge 115
Scratch Addons version: 1.35.0
Operating system: Windows

**Comment by DNin01** [comment]
But as @mxmou pointed out, these aren’t actually links. Clicking them doesn’t take you to a profile page.

**Comment by Samq64** [comment]
I was talking about the following and followers tab text. I should've commented somewhere else since it was off-topic to the PR and also applies to some other buttons.

**Comment by DNin01** [comment]
The Browse Projects menu also does not seem to have underlined "links". What does everyone think? Does it make sense that they aren't underlined because they don't link to the project/profile or should they be styled because they are on buttons?
