### ISSUE TITLE
Links styled as buttons on profiles get underlines on hover with `colorblind`

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6540]
### Description

Buttons like "Cancel" or the emoji picker get an underline on hover.

### Steps to reproduce

1. Enable the underline setting in `colorblind`
2. Go to a profile
3. Hover over the buttons under a comment

### Environment

Browser: Edge 115
Scratch Addons version: 1.34.0
Operating system: Windows

**Comment by Samq64** [comment]
I know the contributing guidelines say to create issues before pull requests but if you found multiple bugs in the same addon and you know how to fix them you can just submit one PR with all the hotfixes.

**Comment by mybearworld** [comment]
> I know the contributing guidelines say to create issues before pull requests but if you found multiple bugs in the same addon and you know how to fix them you can just submit one PR with all the hotfixes.

Oh! That would certainly simplify things.

**Comment by WorldLanguages** [comment]
Yeah, all of these issues could have been one, or just none at all, as long as DNin could understood which bug your PR was fixing.
