### ISSUE TITLE
Re-add fix footer option to infinite scrolling

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6542]
### Why this would be helpful

One user said it made it more convenient to access the forums but they probably didn't know the navbar addon existed.

@mybearworld Has made a few good points though:

>> Removes the "fix footer" setting from infinite-scroll. This setting has been the default for a while and I have seen no evidence of appreciation for it.
>> ...
>> If users send feedback about wanting this feature back, we might readd it as an off-by-default setting.
>- https://github.com/ScratchAddons/ScratchAddons/pull/6426
>
> So, here's feedback! I used this feature a lot even outside of pages with infinite scrolling. It's a much more convenient way of accessing the footer and I think this addon shouldn't have been removed.
>
>> Without a infinite scrolling feture, the reason of someone to scroll to the bottom is to access the footer, but with it, the reason of someone to scroll to the bottom is to have more stuff; more content.
> - https://github.com/ScratchAddons/ScratchAddons/issues/5419#issuecomment-1345267393
>
> This logic seems flawed to me. Say you're scrolling through some comments, and someone asks something about the Terms of Use and you want to reference it. Without a "Fix Footer" feature, this requires going to a new tab, opening Scratch and going to the ToU there, while with such an option, you can just middle click that link.
>
>> Even Never Ending Reddit, the "infinite scrolling" of Reddit Enhancement Suite for old Reddit, doesn't offer a fixed footer, probably with the reason I mentioned.
>
> Just because someone else isn't doing it doesn't necessarily mean SA shouldn't be doing it.

### My suggestion

Re-add the fix footer setting, but with a different name and disabled by default. It's also probably be a good idea to make it only apply pages to with infinite scrolling this time.

**Comment by mybearworld** [comment]
It could also be an addon outside of `infinite-scroll` entirely.

**Comment by BroJac5246** [comment]
I can see some uses for the footer. But who would actually leave this setting on just to access it? Realistically, very few people. If you need the footer that bad then you can take the few seconds to middle-click the Scratch logo and switch to the new tab. Or if you need it frequently then you can bookmark the pages or add them to the navbar.

It was brought up that the user probably didn't know about the customizable navbar addon, but I want to point out in advance that people are more likely to find an addon then they are to find a setting within an addon, so this setting shouldn't be the go-to solution for accessing frequently used links from the footer.

If people really want this, though, then one potential solution would be to make the footer collapsible.

**Comment by WorldLanguages** [comment]
> If people really want this, though, then one potential solution would be to make the footer collapsible.

What do you mean by "collapsible"? Requiring a click instead of hovering being enough?

**Comment by WorldLanguages** [comment]
> It could also be an addon outside of `infinite-scroll` entirely.

Yeah, I would suggest we readd this as a separate non-featured addon, but I'm open to reading other suggestions.
