### ISSUE TITLE
Allow for increment via arrows also in sprite info area

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#6546]
### Why this would be helpful

Many users with discalculia problems do not understand numbers intuitively. Instead they can easily understand the meaning of increasing/decreasing the x/y/size/direction features of a sprite by using the arrow keys in the x/y/size/direction controls in the info area

### My suggestion

Allow users to increment/decrement values of the x/y/size/direction controls in info area by using the same arrow strategy adopted by the "Arrow key incrementation in editor" addon

**Comment by WorldLanguages** [comment]
@sfederici You should try out the https://github.com/mybearworld/fork-ScratchAddons/tree/increment-properties branch

**Comment by sfederici** [comment]
> @sfederici You should try out the https://github.com/mybearworld/fork-ScratchAddons/tree/increment-properties branch

Do you mean that the modification I asked is already available in that branch? If so, how can I test it?

**Comment by WorldLanguages** [comment]
@sfederici You can download this zip https://github.com/mybearworld/fork-ScratchAddons/archive/refs/heads/increment-properties.zip uncompress the folder and load the folder in chrome://extensions (with "developer mode" enabled)

**Comment by sfederici** [comment]
Thanks for the suggestion. When I try to load it I get this error

"content-scripts/inject/run-userscript.js:17 (funzione anonima)"

where line 17 is

      msg.locale = scratchAddons.l10n.locale;

**Comment by WorldLanguages** [comment]
You sure you can't ignore the errors?

**Comment by sfederici** [comment]
Right after loading, the Scratch GUI only shows several addons, not all of them (e.g. no "block shape" addon) and something is weird (e.g. double pause button). If I "trash" the errors nothing changes. How can I fruitfully ignore the errors?

**Comment by WorldLanguages** [comment]
I forgot to mention, you're supposed to disable the other Scratch Addons installation.

**Comment by sfederici** [comment]
Ok, now it works. Yes, this is exactly what I was suggesting
