### ISSUE TITLE
Infrequently, declarativeNetRequest doesn't take effect in Firefox, so user can't mark messages as read

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6550]
### Description

Unlike debugging the extension from a folder, our declarativeNetRequest rule does not work when downloading from the Firefox extension store.

### Steps to reproduce

Try to mark messages as read from the scratch messaging popup.

### Demonstration(s) and additional context

Related:
#6168
#6205

### Environment

Browser: Firefox 116
Scratch Addons version: v1.34.0 downloaded from addons.mozilla.org
Operating system: Windows, but probably doesn't matter

**Comment by apple502j** [comment]
Cannot reproduce.

**Comment by WorldLanguages** [comment]
> Cannot reproduce.

@apple502j:
> Scratch Addons version: v1.34.0 downloaded from addons.mozilla.org

You sure you tested the store version?

**Comment by WorldLanguages** [comment]
Can't reproduce anymore. No idea what's going on.

**Comment by WorldLanguages** [comment]
One of the feedback reports says the issue was fixed after a browser restart/update.

It's very likely the bug is gone after restarting the browser.

**Comment by WorldLanguages** [comment]
This also happens on Brave sometimes: #6494

**Comment by DNin01** [comment]
Is this still an issue? Everyone has probably since updated to newer versions of Firefox and Scratch Addons which means this issue won't be happening to them anymore, based on your evidence that a restart fixes the problem.
