### ISSUE TITLE
"Compact editor" doesn't work as expected in some locales

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6551]
### Description

Will add more information as I find out.

Related possibly: #6545

Feedback (Japanese):
> When I tried the "compact editor" function, I couldn't edit the numbers in the bottom row of sprite properties. "I want you to fix that."

### Steps to reproduce

TBD

### Environment

Browser: Chrome but probably doesn't matter
Scratch Addons version: v1.34.0

**Comment by WorldLanguages** [comment]
Screenshot:

![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/e5590bca-249a-42b2-8b16-1b7f8ba5fb8d)

**Comment by WorldLanguages** [comment]
Possibly you need the "collapsible sprite properties" addon DISABLED to experience this bug.

**Comment by mybearworld** [comment]
Same for German
![image](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/68b52cad-0ea4-4060-ad5b-7abe101907b9)

**Comment by WorldLanguages** [comment]
Looks like the bad line is userstyle.css line 92

Added by commit https://github.com/lisa-wolfgang/ScratchAddons/commit/4c0cc8afee58b3a7f39f245efc7af39526e2e233, `Compatibility with sprite-properties addon`

**Comment by WorldLanguages** [comment]
> Added by commit [lisa-wolfgang@4c0cc8a](https://github.com/lisa-wolfgang/ScratchAddons/commit/4c0cc8afee58b3a7f39f245efc7af39526e2e233), `Compatibility with sprite-properties addon`

That makes no sense now, because @mxmou worked on sprite-properties support recently, and sprite-properties.css sets `height:0`, so the line that is causing the bug doesn't even do anything when sprite-properties is enabled!

**Comment by WorldLanguages** [comment]
Line 132 also uses a fixed value of `4.75rem`, we would need to change this too I think:

![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/56b87e05-1a45-403d-b678-1a2877e06529)
