### ISSUE TITLE
`editor-number-arrow-keys`: More options for how much to increment

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6555]
### Why this would be helpful

The new `editor-number-arrow-keys` addon features a few options for how much to change a number by when pressing up/down. [It was decided](https://github.com/ScratchAddons/ScratchAddons/pull/6020#issuecomment-1620458388) that the options be part of a single-select setting, but there aren't very many options to choose from, there's just 0.01, 0.1, 1, 10, and of course, none.

### My suggestion

Some way to include more options such as larger or more precise units, namely 0.5 and 100.

### Additional context

Continuation of a conversation on #6547:
> @WorldLanguages
> Also, some people suggested a `0.5` setting, I think we could add it.

> @Secret-chest
> I would also find 0.25 and 0.125 useful.

> @rgantzos
> I don't think it's worth getting into the thousandths, but a custom option would be very helpful.

<sub>Yes, I am intentionally mentioning the commentors, if that even works in quotes.</sub>

**Comment by Samq64** [comment]
I suggest converting them to number inputs if people want options like 0.125.

**Comment by DNin01** [comment]
I think a setting for "Custom" might be the way to go. This would show a number field if I'm understanding correctly.

**Comment by mybearworld** [comment]
> I think a setting for "Custom" might be the way to go. This would show a number field if I'm understanding correctly.

Is that possible with the way settings work? If so, I'd agree.

**Comment by DNin01** [comment]
> > I think a setting for "Custom" might be the way to go. This would show a number field if I'm understanding correctly.
> 
> Is that possible with the way settings work? If so, I'd agree.

Yes, through [`if`](https://scratchaddons.com/docs/reference/addon-manifest/#if).

**Comment by WorldLanguages** [comment]
> I think a setting for "Custom" might be the way to go. This would show a number field if I'm understanding correctly.

We were never required to add support for decimals in number settings (there's only an "integer" setting type). So it might take a bit more work.

**Comment by WorldLanguages** [comment]
We didn't receive any messages on the feedback page regarding adding more number options. But adding 0.5 came up in the Discord server.

We can try to deal with this for v1.35.0

**Comment by Secret-chest** [comment]
> We didn't receive any messages on the feedback page regarding adding more number options. But adding 0.5 came up in the Discord server.

For me, 0.5, 0.25 and 0.125 would be really helpful as I said.

**Comment by WorldLanguages** [comment]
> For me, 0.5, 0.25 and 0.125 would be really helpful as I said.

Anyone reading this please PR and add these three option to the three settings :) should be quite easy

**Comment by DNin01** [comment]
> > For me, 0.5, 0.25 and 0.125 would be really helpful as I said.
> 
> Anyone reading this please PR and add these three option to the three settings :) should be quite easy

I tried and the numbers just turned into NaN whenever I tried to increment by any of those values. This will require a userscript modification.

Also, the settings don't look very happy in the popup:
![Single-select field for increment step spanning two lines](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/cf1b1c09-6480-4214-a5d6-60bc018b602e)

**Comment by WorldLanguages** [comment]
> This will require a userscript modification.

Yeah, you need to modify the const defined in the first line of the userscript.

**Comment by DNin01** [comment]
> > This will require a userscript modification.
> 
> Yeah, you need to modify the const defined in the first line of the userscript.

🤦

**Comment by Secret-chest** [comment]
Let's replace "None" with 0.

**Comment by mybearworld** [comment]
> Let's replace "None" with 0.

Why?

**Comment by BroJac5246** [comment]
> > Let's replace "None" with 0.
> 
> Why?

Probably for consistency.

However, "none" feels more natural.

**Comment by Secret-chest** [comment]
Save some space.

**Comment by mybearworld** [comment]
> Save some space.

I don't think we need that much space....

**Comment by DNin01** [comment]
"0" somehow seems more like it would do something than "None", but we could think about it.

Or maybe we should just remove "None" entirely. If you don't want it to do anything, don't use the shortcut.

**Comment by mybearworld** [comment]
> Or maybe we should just remove "None" entirely. If you don't want it to do anything, don't use the shortcut.

If you tend to mistype the arrow keys, disabling a simple arrow key may help. Maybe you have some hotkey that makes Ctrl+Arrow do something different which you don't want Scratch to override, but still want to use the arrow keys to increment things. Better have an option than don't have one.
