### ISSUE TITLE
"Compact editor": some number inputs should be wider

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6563]
### Description

![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/fd88142a-0238-44c7-a51d-6a642accaf78)

### Steps to reproduce

Enable the "compact editor" and try to change a width in the vector editor.

### Demonstration(s) and additional context

In contrast, Chrome has enough space to show 1 full digit, but not 2 full digits. We may also consider that a bug?

### Environment

Browser: Firefox
Scratch Addons version: v1.34.0

**Comment by Chiroyce1** [comment]
> In contrast, Chrome has enough space to show 1 full digit, but not 2 full digits. We may also consider that a bug?

Without compact editor enabled, it shows a maximum of 3 digits so I think it should *at least* have enough space for 2 digits

**Comment by medlans** [comment]
I typed 24 in chrome and saw this
![Screen Shot 2023-08-19 at 12 12 51 PM](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/61ba2328-d027-4746-82b3-f53b7e2fdd2c)

**Comment by WorldLanguages** [comment]
Looks like the initial PR commit did not affect specifically the stroke number in the costume editor: https://github.com/lisa-wolfgang/ScratchAddons/blame/8eaf5050815f70940ae9fd20b0d6e471353dfc2a/addons/editor-compact/userstyle.css#L134

But it was later extended to apply to all "small inputs" in commit https://github.com/lisa-wolfgang/ScratchAddons/commit/595a4030d9307e0c12304a99ee503b7217a805b3#diff-c9bd3ecc85db15e8061fe24aa7f400ff2bbdf67c2d748043985dbb83fa38fb69R131

**Comment by WorldLanguages** [comment]
This CSS works fine for `<input type=text>` as those don't have up/down arrows taking space.
