### ISSUE TITLE
Duplicated sprites in folders do not show up as expected

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6564]
### Description

When duplicating a sprite in a folder with another sprite in a different folder or outside of a folder, a copy of the folder appears.

![Two of the same folder](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/edd4dd2e-82d9-486f-8517-72891c1ff20b)

One or two funny visual things happen as a result like both folders collapsing and opening at the same time, but it doesn't seem like it affects the project in a bad way.

You can do certain things that fix the behavior, such as saving and reloading the project.

### Steps to reproduce

1. Enable `sprite-folders`.
2. Create a folder.
3. Add a sprite to the right and outside of the folder.
4. Duplicate one of the sprites in the folder.

Duplicated sprites are placed at the end of the list, which is probably what causes this to happen.

### Environment

Replicated in TurboWarp and scratchfoundation.github.io/scratch-gui/develop.

**Comment by medlans** [comment]
I did this in 1.34.0 (on the main Scratch website) and this didn't happen at first (I think it auto saved probably): 
![folder](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/aa9af594-dd12-4f26-ab91-e100cc079424)
But then I refreshed and I could replicate, and when I removed the folder, it removed both.
Also, some small thing: is the info button supposed to be visible?
