### ISSUE TITLE
"Expanding search bar" regression on v1.34.0

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6567]
Regressed by #6399
Apparently affects both Chromium and Firefox

> When searching something on the search bar, the search bar glitches/expands through the Create, Ideas, Explore, etc.. tabs.
OS: Windows 11
Browser: Microsoft Edge 115.0.1901.203 (Official build) (64-bit version)
Scratch Addons: 1.34.0

Firefox screenshot sent in Discord server:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/891e53cf-a8c9-4947-8c45-204f85a9b224)

**Comment by WorldLanguages** [comment]
Image sent by same user that sent Edge feedback (see OP)
![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/8f97262c-5ee6-4b95-8520-4fec49236def)

**Comment by medlans** [comment]
It just does this to me on chrome (same SA version on Chrome 115.0)
![yeaithappenswithoutthe2 0navbartoo](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/3681db6f-d140-44b9-be40-04b9c68e7d76)

**Comment by DNin01** [comment]
A few questions:
- Are any other browser extensions installed too?
- Is it possible to show us the list of enabled addons? Or even better, steps to reproduce?

**Comment by medlans** [comment]
> A few questions:
> 
> * Are any other browser extensions installed too?
> * Is it possible to show us the list of enabled addons? Or even better, steps to reproduce?

I think expandable search bar and scratchr2 -> scratch-www, but only on scratchr2 pages.

**Comment by DNin01** [comment]
That's kind of what I was thinking.

**Comment by Secret-chest** [comment]
Can repro on Ungoogled Chromium, Linux Mint 21.2 Cinnamon.
