### ISSUE TITLE
"Editor dark mode": convert modes to presets, allow for custom colors

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#657]
Now that presets exists, it would be nice to convert the current "3 userstyles" approach from `editor-dark-mode` to a single CSS file that uses CSS variables, then allow users to choose a preset, or customize it themselves as they wish. Hopefully no setting will need a userscript to function correctly? If not, it's not a big deal anyway.

**Comment by mxmou** [comment]
Then that addon would be "customize everything", not a dark mode.

**Comment by WorldLanguages** [comment]
@mxmou Indeed, I am not sure how we could name an addon like that. It would be a custom colors addon with dark mode presets.

**Comment by WorldLanguages** [comment]
This would be a nice opportunity to clear up the editor context menu mess - dark modes usually mess with borders, heights, and don't make it easy to distinguish the separations between different buttons added by different addons:

![image](https://user-images.githubusercontent.com/17484114/99882724-61a93280-2c01-11eb-8c9d-72d8d4ad9e43.png)

**Comment by mxmou** [comment]
Would "Editor customized colors" and "Website customized colors" be good names for the addons after this change?

**Comment by WorldLanguages** [comment]
@mxmou Not sure, they'd effectively be those, but I bet most people would just use them for dark mode.

**Comment by mxmou** [comment]
@WorldLanguages I agree, but I think it's better to cover all features in the name and instead mention in the description that it can be used for dark mode.

**Comment by RedGuy12** [comment]
@MaxiMouse well, 60fps was changed to custom fps, but the title stayed the same since "most people would keep it at 60".
________________________________

**Comment by mxmou** [comment]
@RedGuy12 @WorldLanguages I think it depends on what the defaults are. If the default colors are dark, then dark mode is the correct name. If not, it's customized colors.

**Comment by WorldLanguages** [comment]
Dark mode will continue to be the default

**Comment by mxmou** [comment]
> Dark mode will continue to be the default

This is very unintuitive to use. It means that the default dark mode version can't have a name, that resetting the addon to defaults would make it a dark mode instead of the default colors like in custom block colors, and that there would have to be a preset with Scratch's default colors (for people who just want to tweak them slightly instead of using dark mode).

**Comment by WorldLanguages** [comment]
Oh right, haven't considered that.
What I meant was that by default, colors would be black. But if the user clicks "reset" in a color, it would return to the Scratch default.
AKA what I meant is that the dark mode preset would be the default *selected preset*, but the default values for the colors would of course be Scratch's native colors. I don't think we're doing this already for any addon, but I can't find any better way to merge custom colors and dark mode into a single addon, acknowledging that dark mode is what most users will choose.

**Comment by mxmou** [comment]
@WorldLanguages That makes sense. Could the addons be called something like "dark mode and custom colors" then?

**Comment by WorldLanguages** [comment]
Sure
I'm not sure what "reset" should do tho. Default Scratch colors could be a preset, and "reset" could return to the dark mode default. Not sure. It's complicated :P
It's even worse if you consider many users have different flavors of editor dark mode, so if they accidentally change a color and click "reset", it might be reset to the color used for that in another theme.

**Comment by mxmou** [comment]
> I'm not sure what "reset" should do tho. Default Scratch colors could be a preset, and "reset" could return to the dark mode default. Not sure. It's complicated :P
> It's even worse if you consider many users have different flavors of editor dark mode, so if they accidentally change a color and click "reset", it might be reset to the color used for that in another theme.

A possible solution is checking which preset is the most similar to the user's choices and resetting to that when clicking "Reset" on a color.

**Comment by mxmou** [comment]
Alternatively, Reset could be a dropdown menu with different presets.

**Comment by mxmou** [comment]
I made the dots on the workspace background gray on dark backgrounds, which means their contrast with the background is never higher than this:
![image](https://user-images.githubusercontent.com/51849865/110660000-66e7b880-81c3-11eb-8313-24062d713457.png)

Because they're so small, this makes them almost impossible to see in 3.Dark, invisible in Dark Editor and completely unobtrusive in other presets. Would it make sense to remove the option to hide them?

**Comment by WorldLanguages** [comment]
@mxmou I'd say you keep it for now
