### ISSUE TITLE
no features working in scratch addons.

### ISSUE THREAD

**Issue by BleauLu** [ScratchAddons/ScratchAddons#6583]
### Description

Scratch addons isn't working and it's just like I don't have scratch addons! I don't have cat blocks or pause buttons, and scratch is just the same! Scratch addons is installed, and yesterday it was working, but now it's not, and no features are working for me!

### Demonstration(s) and additional context
A few details:

No cat blocks in this screenshot.
![image](https://github.com/ScratchAddons/ScratchAddons/assets/143015772/bfa0092c-b4e7-4240-81c2-ec24612dadc5)
No pause button.
![image](https://github.com/ScratchAddons/ScratchAddons/assets/143015772/b46be132-2ac4-436c-b670-b7a2cb73ebbd)

### Environment

Browser: 
Scratch Addons version: 
Operating system:

**Comment by CST1229** [comment]
If the popup doesn't show anything, restart your browser.

**Comment by BleauLu** [comment]
i did

**Comment by callumjt** [comment]
Have you tried reinstalling?

**Comment by BleauLu** [comment]
yes

**Comment by BleauLu** [comment]
it's also signed in with my account

**Comment by BleauLu** [comment]
> Have you tried reinstalling?

yes

**Comment by WorldLanguages** [comment]
Does the Scratch Addons settings page work?

**Comment by BroJac5246** [comment]
Have you disabled all other extensions? One or more of them could be causing conflicts. Also, what OS, browser, and browser version are you using?

**Comment by BleauLu** [comment]
> Does the Scratch Addons settings page work?

yes, but not scratch addons

**Comment by BleauLu** [comment]
> Have you disabled all other extensions? One or more of them could be causing conflicts. Also, what OS, browser, and browser version are you using?

they never have and i am using Chrome browser

**Comment by WorldLanguages** [comment]
@BleauLu Please reopen the issue if this happens to you again

**Comment by BleauLu** [comment]
> @BleauLu Please reopen the issue if this happens to you again

i know that
