### ISSUE TITLE
Buttons Not Aligned.  

### ISSUE THREAD

**Issue by MaterArc** [ScratchAddons/ScratchAddons#6584]
### Description

When you enable the Scratch 2.0 to Scratch 3.0 addon, on the 'my stuff' page, two of the buttons aren't properly aligned. 

### Steps to reproduce

1. Enable the Scratch 2.0 → 3.0 Addon
2. Go to the My stuff page
3. Look at the buttons with your eyes and process the information with your brain lol

### Demonstration(s) and additional context

fine lol
<img width="262" alt="Screenshot 2023-08-23 at 4 45 30 PM" src="https://github.com/ScratchAddons/ScratchAddons/assets/105017592/30d11019-de04-4eb3-9d63-28a6ccf511d8">

### Environment

Browser: Chrome version 116.0.5845.96
Scratch Addons version: 1.34.1
Operating system: macOS version 10.15.7

**Comment by rgantzos** [comment]
It's supposed to be like that, just like on the normal My Stuff page. The Shared Projects and Unshared Projects tabs are subcategories of the All Projects tag. Here's what it looks like without the addon:
<img width="261" alt="Screenshot 2023-08-23 at 1 54 11 PM" src="https://github.com/ScratchAddons/ScratchAddons/assets/86856959/ee5947f6-54e6-415f-98d3-c6e6e1eb3774">

**Comment by MaterArc** [comment]
Never really noticed that lol, someone can close it if they need. It just looks out of place to someone who didn't know that the original was indented to show categories. Anyways though, glad to hear it wasn't a bug or anything.

**Comment by DNin01** [comment]
Works as intended.

**Comment by Samq64** [comment]
I made an issue for this a while back too. There is an addon to use horizontal tabs on my stuff which I think makes it look either way.

**Comment by Secret-chest** [comment]
The indent should be larger, because now it just looks misaligned.

**Comment by WorldLanguages** [comment]
At some point, I was also confused at this. Unsure what could be done.

**Comment by mxmou** [comment]
> At some point, I was also confused at this. Unsure what could be done.

Something like this?
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/cce3ef7d-698c-4529-bb0b-86e931227605)

**Comment by WorldLanguages** [comment]
Yeah, that would be nice!

**Comment by DNin01** [comment]
Fancy having the subtabs disappear when you aren't looking at a list of projects? (When My Studios or Trash is selected, the Shared Projects and Unshared Projects buttons would be hidden.)

Here's the CSS for that, BTW:
```css
.v-tabs li.first:not(li.first.active):not(:has(~ .sub-list.active)) ~ .sub-list:not(.sub-list.active) {
    display: none;
}
```

But then that would not apply without `scratchr2` so this probably isn't what we want to do.

I'm proud enough of that CSS to post this comment, though.

**Comment by mybearworld** [comment]
> Fancy having the subtabs disappear when you aren't looking at a list of projects? (When My Studios or Trash is selected, the Shared Projects and Unshared Projects buttons would be hidden.)
> 
> Here's the CSS for that, BTW:
> 
> ```css
> .v-tabs li.first:not(li.first.active):not(:has(~ .sub-list.active)) ~ .sub-list {
>     display: none;
> }
> ```
> 
> But then that would not apply without `scratchr2` so this probably isn't what we want to do.
> 
> I'm proud enough of that CSS to post this comment, though.

This would require JavaScript, as `:has` is not supported in Firefox by default.
