### ISSUE TITLE
Sound Enhancing

### ISSUE THREAD

**Issue by samarth959** [ScratchAddons/ScratchAddons#6586]
### Why this would be helpful

Make Sounds more clear to hear

### How this addon works

Make Sounds more clear to hear

**Comment by BroJac5246** [comment]
This could be legitimate. It just doesn't make sense because AI costs money and we don't have money.

**Comment by Secret-chest** [comment]
Possibly just amplify the project volume?

**Comment by WorldLanguages** [comment]
"Enhance" is vague.
