### ISSUE TITLE
Conflict when renaming variables when using both scratchtools and scratch addons

### ISSUE THREAD

**Issue by ksdavidc** [ScratchAddons/ScratchAddons#6588]
### Description

The ScratchTools "Default to Local Variables" addon seems to have a conflict with the Scratch Addons "Switch variables between "For all sprites" and "For this sprite only"". The conflict appears when renaming a global variable. The global variable is redefined to be local.  I would expect only set NEW variables to be set to local, not the redefining already defined variables.

Of course I don't which addons, or if both, is responsible, so I am alerting both developers.

### Steps to reproduce

1. enable both plugins. 
2. take a global variable and attempt to rename it. 
3. The popup will show the formerly global variable as local.

disabling either of the plugins produces a different dialog, with no conflict, apparently.

### Environment

Browser:  116.0.5845.11
Scratch Addons version:  1.34.1
Operating system: mac

Scratchtools version 
Version: 3.1.2
Features enabled: 74
Language: en-US

**Comment by Samq64** [comment]
We don't officially support running other Scratch extensions alongside Scratch Addons. I would suggest disabling the feature from one of the extensions.

**Comment by robertlearnedjs** [comment]
I was actually headed over to GitHub to make an issue about this too. I've noticed multiple places where ScratchTools and Scratch Addons conflict with each other. I use multiple browser extensions, but I don't want to have to uninstall Scratch Addons.

Is there any compatibility coming in the future? Now that there are more popular browser extensions, I think it's a good idea to try to work on compatibility. I'm also reaching out to the ScratchTools team via their feedback section to discuss this. Please aim for compatibility. Even if it isn't your first priority, it should be one of them.

**Comment by WorldLanguages** [comment]
For this specific issue, it looks like it would be easier for ScratchTools to fix it in their side. Their feature should only affect the "Create Variable" modal, and not the "Rename Variable" one. I asked them if they could track this in their GitHub and created https://github.com/STForScratch/ScratchTools/issues/667

(Related: do we have a "new addon" issue suggesting a "local variables by default" addon?)

**Comment by WorldLanguages** [comment]
> I've noticed multiple places where ScratchTools and Scratch Addons conflict with each other.

@robertlearnedjs I'll be thankful if you can provide a list of the bugs you've noticed. I'm not sure if these types of issues should be closed or not in our repository, but you're still welcome to elaborate a list of incompatibilities both extensions should be aware of. You can send them through feedback or on GitHub.

> Is there any compatibility coming in the future?

Bugs like this one are pretty difficult to detect unless you take into account other extension's features into account, not much can be done about that from the technical side. But many Scratch Addons APIs are already extension-agnostic, such as [appendToSharedSpace](https://scratchaddons.com/docs/reference/addon-api/addon.tab/addon.tab.appendtosharedspace/) and dark mode CSS variables.

**Comment by WorldLanguages** [comment]
Looks like ScratchTools has created a relevant GitHub project board: https://github.com/orgs/STForScratch/projects/6/views/1

**Comment by rgantzos** [comment]
> > Is there any compatibility coming in the future?
> 
> Bugs like this one are pretty difficult to detect unless you take into account other extension's features into account, not much can be done about that from the technical side. But many Scratch Addons APIs are already extension-agnostic, such as [appendToSharedSpace](https://scratchaddons.com/docs/reference/addon-api/addon.tab/addon.tab.appendtosharedspace/) and dark mode CSS variables.

Pull requests such as #5089 have been opened to fix compatibility issues and just improve the extensions in general. I haven’t seen much happen to them lately, though.

**Comment by WorldLanguages** [comment]
I'll get to it soon

**Comment by ksdavidc** [comment]
Nice work @WorldLanguages and @rgantzos Admittedly this is a low low priority issue, and as pointed out, compatibility issues are inherently problematic, but kudos to both of you for carrying on anyway and helping those of us out who find ourselves in the predicament of using both plugins. Having more than one approach to finding and solving problems is generally good. 3 cheers for you from the gallery.

**Comment by rgantzos** [comment]
This has been resolved with [#671](https://github.com/STForScratch/ScratchTools/pull/671).
