### ISSUE TITLE
Local variables by default

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6592]
### Why this would be helpful

When working with big projects new variables are usually local, but Scratch defaults to global ones.

### How this addon works

An addon that changes the default selected variable scope in the create a variable dialog to local.

### Possible alternatives

Maybe this could be part of `swap-local-global`?

### Additional context

Apparently ScratchTools has this feature.

**Comment by WorldLanguages** [comment]
> Maybe this could be part of `swap-local-global`?

Yeah, it's either a setting there, or a new addon.

**Comment by medlans** [comment]
Yea st has it, I have that extension and I checked. I think that it could be added here or the extension could be made compatible with ST since I need that to add some stuff and scratch-www -> scratchr2.

> > Maybe this could be part of `swap-local-global`?
> 
> Yeah, it's either a setting there, or a new addon.

I think maybe a local var Addon could be made to combine the 2, and turn it on.

**Comment by WorldLanguages** [comment]
Related: #6594

**Comment by penguinmoose** [comment]
I think it's better if instead, this addon makes it retain the previous local/global selection (also applies to the cloud variable checkbox).

**Comment by WorldLanguages** [comment]
> I think it's better if instead, this addon makes it retain the previous local/global selection (also applies to the cloud variable checkbox).

Maybe we could instead allow you to create multiple variables within the same New Variable modal? (through a custom UI or maybe comma separated)

**Comment by WorldLanguages** [comment]
Also, I think `data-category-tweaks-v2` could provide separate "Create Global Variable" and "Create Local Variable" if the setting to separate them is enabled.

**Comment by Samq64** [comment]
Closing in favor of #6940.
