### ISSUE TITLE
delete my variable upon creating project

### ISSUE THREAD

**Issue by samarth959** [ScratchAddons/ScratchAddons#6597]
### Why this would be helpful

delete the my variable variable as soon as I create a project

### How this addon works

delete the my variable variable as soon as you create a project

### Additional context

![Screenshot 2023-08-26 092029](https://github.com/ScratchAddons/ScratchAddons/assets/105594295/6460cd27-3abd-411c-ab2d-752596d84676)

**Comment by samarth959** [comment]
please make this an addon in scratch addons

**Comment by Samq64** [comment]
This can already be done with the customizable default project addon.

**Comment by medlans** [comment]
I’m guessing this is a 3.0 thing since this isn’t in 2.0?
> This can already be done with the customizable default project addon.

I mean, the project now has to be shared. Or is that an option there??

**Comment by mxmou** [comment]
> > This can already be done with the customizable default project addon.
> 
> I mean, the project now has to be shared. Or is that an option there??

The addon has an "empty project" preset.

**Comment by WorldLanguages** [comment]
Related: #4707

**Comment by medlans** [comment]
> > > This can already be done with the customizable default project addon.
> > 
> > 
> > I mean, the project now has to be shared. Or is that an option there??
> 
> The addon has an "empty project" preset.

Yea I figured that out after checking XD, and this:

https://scratch.mit.edu/discuss/post/7471644/ (I had to disable the addon since it was making it the default 2.0 project but with a comment)
It doesn’t have the cat but to be fair I don’t really know many people who don’t delete it 99% of the time
