### ISSUE TITLE
[New addon] exactcount by mxmou

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#66]
**Describe the new addon**

Exact count is a JavaScript program that shows the exact number of projects in a Scratch studio, even if it's larger than 100.

**Link to the new addon**

https://github.com/mxmou/exactcount

Should probably not be enabled by default since it requires multiple requests. Or it could be enabled by default, but require user interaction.

**Comment by JeffaloBob** [comment]
i wonder, would this benefit from having a backend? it could be faster that way (1 req vs how many exactcount uses) and if its cached a bit its fast.

**Comment by mxmou** [comment]
> i wonder, would this benefit from having a backend? it could be faster that way (1 req vs how many exactcount uses) and if its cached a bit its fast.

For larger studios it probably would.

**Comment by mxmou** [comment]
@WorldLanguages Does "require user interaction" mean something like clicking on the "100+" to see the count? That looks like a good solution.

**Comment by WorldLanguages** [comment]
@mxmou It means exactly that. Clicking is a bit weird tho - and adding a button just for this may be a bit too extreme. Honestly, I'm not sure. I think both user interaction **and** manual addon enabling would be a great mix.

**Comment by mxmou** [comment]
> @mxmou It means exactly that. Clicking is a bit weird tho - and adding a button just for this may be a bit too extreme. Honestly, I'm not sure. I think both user interaction **and** manual addon enabling would be a great mix.

Clicking would be less weird if the "100+" would have a tooltip (like "Click to see exact count").

**Comment by Explosion-Scratch** [comment]
Yay!
