### ISSUE TITLE
Sprite pane not using all available space when both `editor-compact` and (collapsing)`sprite-properties` enabled

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6602]
### Description

The sprite pane should use all of the available height to display the most amount of rows possible.

### Steps to reproduce

1. Go to a project with a significant amount of sprites (for example https://scratch.mit.edu/projects/823872487/editor/)
2. Enable both addons: `editor-compact` and `sprite-properties` on default settings

![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/05b6bb94-6035-4ba3-9c76-8c18f312c5f8)

### Demonstration(s) and additional context

See above

### Environment

Browser: Chrome, but probably can be experienced in Firefox too
Scratch Addons version: v1.34.1

**Comment by dos-pasos** [comment]
https://github.com/ScratchAddons/ScratchAddons/blob/e935edc8f1a1e0aa83e4ab0b4609b4346c88e9e9/addons/sprite-properties/userstyle.css#L13C1-L13C1
se aumenta la especificidad con un div

div[class^="sprite-selector_scroll-wrapper_"] {
  height: 100%;
  transition-property: height;
  transition-duration: var(--spriteProperties-transitionDuration);
}

o 
siguiendo el formato del autor agregamos selector descendente, que parte desde la etiqueta body
.sa-hide-sprite-properties [class^="sprite-selector_scroll-wrapper_"] { 
  height: 100%;

**Comment by WorldLanguages** [comment]
Thanks @dos-pasos 
You're saying this is simply a CSS selector specificity issue.
