### ISSUE TITLE
Some addons don't play well with custom extensions in TurboWarp

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6608]
### Description

- `middle-click-popup` and probably some other addons display blocks from custom extensions in white
- `middle-click-popup` does not display the popup and instead makes your mouse get stuck dragging the code area if certain extensions are imported (namely, [Math and String](https://extensions.turbowarp.org/NOname-awa/math-and-string.js))
  <details><summary>Error</summary>
  <p>
  
  ```
  userscript.js:314  Uncaught TypeError: Cannot read properties of undefined (reading 'length')
      at userscript.js:314:16
      at Array.sort (<anonymous>)
      at Object.buildFilterList (userscript.js:313:15)
      at Object.show (userscript.js:79:12)
      at n.Gesture.doWorkspaceClick_ (userscript.js:483:21)
      at Blockly.Gesture.handleUp (blockly_compressed_vertical.js:860:32)
      at HTMLDocument.r (blockly_compressed_vertical.js:2292:240)
  (anonymous) @ userscript.js:314
  buildFilterList @ userscript.js:313
  show @ userscript.js:79
  n.Gesture.doWorkspaceClick_ @ userscript.js:483
  Blockly.Gesture.handleUp @ blockly_compressed_vertical.js:860
  r @ blockly_compressed_vertical.js:2292
  ``` 
  
  </p>
  </details> 

### Steps to reproduce

Self-explanatory

### Environment

Browser: Edge 116
TurboWarp Addons version: e65a5ac (**OUTDATED** compared to Scratch Addons)
Operating system: Windows 11

**Comment by GarboMuffin** [comment]
our middle-click-popup version is **very** old and supposedly some of these issues are fixed on ScratchAddons master

**Comment by DNin01** [comment]
Also, should I have opened this on https://github.com/TurboWarp/addons?

**Comment by DNin01** [comment]
I'll just go ahead and open another one: https://github.com/TurboWarp/addons/issues/4

**Comment by WorldLanguages** [comment]
Yeah, I think it's just `editor-devtools` that still uses window prompt.

**Comment by WorldLanguages** [comment]
I didn't mention it because I'm pretty sure most third-party Scratch forks wouldn't include that addon in their build, for obvious reasons.

**Comment by GarboMuffin** [comment]
TurboWarp has its own replacement for that addon so no need to worry about that one

**Comment by Tacodiva** [comment]
I'm closing this because I'm pretty sure this is not a problem with SA here but rather a problem with TurboWarp's fork of SA and an issue has been opened there.
