### ISSUE TITLE
Extension popup: default to "Addons" tab instead of Messaging

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6610]
### Why this would be helpful

At this point, the Addons tab is probably the most relevant when the user just installed the extension.
The Messaging tab is still the default for historical reasons. Keep in mind that Scratch Addons v1.0.0 did not provide an Addons tab.

### My suggestion

We already remember the tab which was last selected, but after installing, we continue to show Messaging by default.

We should change it to Addons by default.

### Possible alternatives

We could change the order of the tabs, but that can break muscle memory.
We could try to make the order of tabs customizable at some point.

Also, the "Addons" tab could have an "open in new tab" indicator that opens the full-screen settings page. I'm not sure if this was ever discussed. It sounds pretty obvious.

**Comment by mxmou** [comment]
The message count badge is enabled by default, and I think it makes sense to open the Messages tab when clicking the icon while the badge is visible - at least until #5127 is implemented.

> Also, the "Addons" tab could have an "open in new tab" indicator that opens the full-screen settings page. I'm not sure if this was ever discussed. It sounds pretty obvious.

It's already very easy to open the settings page from the popup. I'm not sure if users would expect two clickable elements placed very close to each other to do exactly the same thing.

**Comment by WorldLanguages** [comment]
Good point, this is very related to #5127 as the user may not notice the number badge is unread messages.

**Comment by DNin01** [comment]
I really do like the Addons tab - there's no content that has to be fetched from Scratch or anything like that and it lets me get right into my favorite thing about the extension popup: configuration. However, it can be convenient to be dropped into the Messaging tab **when you have unread messages**.

**Comment by WorldLanguages** [comment]
> I'm not sure if users would expect two clickable elements placed very close to each other to do exactly the same thing.

Lol this is #2353 again I just noticed

**Comment by mxmou** [comment]
Fixed by #6781
