### ISSUE TITLE
Copy `.editorconfig` configuration to `.vscode/settings.json`

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6621]
### My suggestion

`.editorconfig` is kind of like a standard configuration file that is meant to be usable in all code editors and IDEs.

In Visual Studio Code, you need to install the [EditorConfig for VS Code extension](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) to use it, from what I know. We already have a [`.vscode/settings.json`](https://github.com/ScratchAddons/ScratchAddons/blob/master/.vscode/settings.json) file, so we might want to try specifying each configuration from `.editorconfig` in `.vscode/settings.json` as well so that no extension is required. **We would not remove `.editorconfig`.**

Related: #6617

### Possible alternatives

Recommend the EditorConfig extension: #6593

@apple502j @WorldLanguages

**Comment by WorldLanguages** [comment]
Yeah, looks like VSCode does not support it natively (if you asked me before, I assumed it did).

So I think we should take a look at everything we currently define in .editorconfig and also add it to the vscode settings file when possible.
