### ISSUE TITLE
Better search engine

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#6624]
(new addon) replaces the search bar with google search

**Comment by mxmou** [comment]
How would that be better than the current search? Google doesn't even index projects (scratchfoundation/scratch-www#3637).

**Comment by Open137** [comment]
Wouldn't something like this work? [https://cse.google.com/cse?cx=f20c5192f78814823](https://cse.google.com/cse?cx=f20c5192f78814823). It seems to get results reasonably well. Especially when you select what you're looking for with the tabs.
