### ISSUE TITLE
Password autofill opens when search bar is clicked

### ISSUE THREAD

**Issue by realbashy** [ScratchAddons/ScratchAddons#6637]
### Description

When the search bar is clicked, the search bar acts as if it were a username/password form.

### Steps to reproduce

1. Click on search bar.

### Demonstration(s) and additional context

![Untitled](https://github.com/ScratchAddons/ScratchAddons/assets/104329537/1986e677-5649-4712-9aed-22b706243746)

### Environment

Browser: Chrome 116
Scratch Addons version: 1.34.1
Operating system: Windows 11

**Comment by mxmou** [comment]
This is a Chrome bug.

**Comment by mxmou** [comment]
There's a bug report about this on the Scratch forums: https://scratch.mit.edu/discuss/topic/706469/

It might be possible for the ST to fix this, but I don't think Scratch Addons can do anything about it - Chrome opens the autofill popup as soon as the input appears, so changes made to it after that would have no effect.

**Comment by medlans** [comment]
Also, it happens without extensions.

**Comment by WorldLanguages** [comment]
> I don't think Scratch Addons can do anything about it

If Scratch could fix this by changing some HTML attribute in the input, we could also do that programmatically with an addon as soon as the page loads. But I'm not sure about the root cause of this bug, so no idea which attributes need to be changed.

**Comment by BroJac5246** [comment]
Bump. I know this isn't our bug but they're taking forever to fix this and it's really driving me nuts. I would love to see a bug fix addon as a temporary solution.

**Comment by Samq64** [comment]
> Bump. I know this isn't our bug but they're taking forever to fix this and it's really driving me nuts. I would love to see a bug fix addon as a temporary solution.

We already have the remove search bar autocomplete addon so this could just be added there.

**Comment by WorldLanguages** [comment]
@BroJac5246 By chance do you know why Chrome thinks it should autofill? Any HTML attributes we could change to fix this?

**Comment by BroJac5246** [comment]
> @BroJac5246 By chance do you know why Chrome thinks it should autofill? Any HTML attributes we could change to fix this?

I tried looking into it but I didn't have any luck. Interestingly, it has the same class (`"input"`) as the login details. However, I'm not sure how to get Chrome to reconsider whether it's a username entry field or not. If you duplicate it, the new one won't have the password popup, suggesting that Chrome isn't dynamically rechecking it. It might be possible to, say, change the class or another attribute as soon as the page starts loading, but I don't have time to test that.
