### ISSUE TITLE
Add addon

### ISSUE THREAD

**Issue by BwenedianJr** [ScratchAddons/ScratchAddons#6643]
### Why this would be helpful

Can you add the “editor dark mode and customizable colors” addon? I know turbowarp already has dark mode but I think it would be cool to change the editor colors too! I am a mobile User and can’t download apps to get all scratch addons so this addon is the only way I can make scratch 3 look like scratch 2.

### How this addon works

Allows you to edit the colors of the editor

### Possible alternatives

Add another editor setting in the dark mode button that makes it look like 2.0 and 1.4

**Comment by mybearworld** [comment]
I don't think this is the correct repository for this

**Comment by BwenedianJr** [comment]
?

**Comment by BwenedianJr** [comment]
Ohh this is not turbowarp LOL

**Comment by mxmou** [comment]
See TurboWarp/scratch-gui#284
