### ISSUE TITLE
Add a web editor to test all addons

### ISSUE THREAD

**Issue by BwenedianJr** [ScratchAddons/ScratchAddons#6644]
### Why this would be helpful

Can you make an online editor for mobile users to try out addons without the extension? It would be useful especially if the editor could be added to the home screen

### My suggestion

Above

### Possible alternatives

none

### Additional context

none

**Comment by WorldLanguages** [comment]
TurboWarp can be added to the home screen.

**Comment by BwenedianJr** [comment]
Yes, but it has only a few addons

**Comment by WorldLanguages** [comment]
It includes most editor addons, I think. Or are you referring to website addons?

**Comment by BwenedianJr** [comment]
No, I wanted to try out the “editor dark mode and customizable colors” addon along with the other editor addons to make it look like scratch 2.0

**Comment by WorldLanguages** [comment]
Hopefully TurboWarp will add support for that addon at some point.

I hope after we redesign the settings page here at Scratch Addons, we find it easier to support a userscript version of Scratch Addons that would be installable through Tampermonkey/Greasemonkey in any supported browser, and it would also allow anyone to easily fork scratch-gui and run SA-userscript on top directly in the website, without any extensions needed.

**Comment by BwenedianJr** [comment]
By the way, I’m on a school ipad so I can’t get extensions. Is there a way I can get scratch addons still?

**Comment by WorldLanguages** [comment]
Not that I know of. I think best you can get on an iPad is turbowarp.org

**Comment by BroJac5246** [comment]
> By the way, I’m on a school ipad so I can’t get extensions. Is there a way I can get scratch addons still?

You can't access Scratch Addons from an iPad anyways, so at least know you're not missing out because of your school.
