### ISSUE TITLE
Customizable block colors does not affect developer tools middle click feature

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#666]
![image](https://user-images.githubusercontent.com/17484114/98445439-8fb54f80-20f6-11eb-9a1a-ce0f3a1f2499.png)

**Comment by WorldLanguages** [comment]
666 🎉

**Comment by Hans5958** [comment]
aww man we reached 666 after the halloween

**Comment by wgyt735yt** [comment]
It seems like the colors in dev tools are hard coded and won't look at the actual colors of the blocks.

**Comment by WorldLanguages** [comment]
Moved from #720: changing block colors should likely affect other colors within developer tools, like the find bar.

**Comment by areeq0325** [comment]
Also #777, problems with the background

**Comment by YOYITsM3M8** [comment]
this #666

**Comment by MasimbaTheHuman** [comment]
> 666 🎉

How is that a good thing?
