### ISSUE TITLE
Text in exported blocks don't follow color mode setting

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6663]
### Description

I use the High Contrast color mode in Scratch, mainly because the Events blocks are more comfortable to read and so that screenshots of blocks are accessible to those who need higher contrast.

That's why I wanted to report that when I tried to use the "Save blocks as image" addon, I actually got a picture of high contrast blocks with _white_ text (a horrible combination).

And yes, this happens in both SVG and PNG exports. Here are the results:
[block_9_17_2023-12_01_36 PM](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/fd53cb86-d205-4e9f-935a-1182773b6339)
[block_9_17_2023-12_01_01 PM](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/00c5e371-2631-4a54-b2c2-3599f5f12934)

Guess I'll just have to use screenshots instead.

### Steps to reproduce

1. Enable the "Save blocks as image" addon and disable "Customizable block colors" (don't _dynamically_ disable, that fixes the issue)
2. Have the color mode set to High Contrast (I don't know if you need to reload between color mode changes)
3. Export an SVG or PNG image of the blocks

### Demonstration(s) and additional context

Available above.

### Environment

Browser: Edge 117
Scratch Addons version: v1.34.1 stable and https://github.com/ScratchAddons/ScratchAddons/commit/1a4a8e2b0a3e8027a5df6bae3ab351fd95376ad7
Operating system: Windows 11

**Comment by WorldLanguages** [comment]
Wow, you're first to notice this I think
