### ISSUE TITLE
custom-block-shape: does not support blocks with 'null' inputs

### ISSUE THREAD

**Issue by DogeisCut** [ScratchAddons/ScratchAddons#6667]
### Description

Blocks with 'null' inputs normally look like this:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/23178844/d071dcec-f1f0-4818-b80e-d4b13906d9cb)

Compared to blocks with normal inputs:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/23178844/0ed988ca-d75a-4d90-8a92-09e3cb8526ae)

When 'Customizable block shape' is applied with the '2.0 Blocks' preset, this is what they look like:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/23178844/8f811f9d-6161-46af-a0ac-ef277c19991d)
![image](https://github.com/ScratchAddons/ScratchAddons/assets/23178844/f7781233-af60-4c52-abbd-e573c9d43276)

Notice that the null inputs (1st image) do not scale with the block, making them stick out horrendously. 

### Steps to reproduce

1. Turn off all addons.
2. [Go to the editor of this project.](https://scratch.mit.edu/projects/560198467/editor)
3. Note the perfectly fine-looking blocks. (Aside from the obviously JSON edited inputs)
4. Turn on 'Customizable block shape' and apply the '2.0 Blocks' preset.
5. Observe the ugliness of the null inputs.
6. Refresh and realize it doesn't fix it.
7. Sob 

### Demonstration(s) and additional context

Fixing this would be useful to TurboWarp extension creators as null inputs are often used for blocks that should only accept changing values such as reporters and booleans.

### Environment

Browser: 
Scratch Addons version: 
Operating system:

**Comment by Samq64** [comment]
Does the scratchblocks support those inputs? If not I don't think this is worth fixing.

**Comment by DogeisCut** [comment]
There's also their use in custom TurboWarp extensions.

**Comment by CST1229** [comment]
> Or those extensions could just not use blank inputs?

Blank inputs are usually used to hint/require the user to drag a block in (kinda like how you can't type in a boolean input), so probably not.

**Comment by BroJac5246** [comment]
> Eh. I mean, you're never _supposed_ to see these kinds of blocks so I wouldn't expect us to fix it.
> 
> However, this could be practical in TurboWarp, as you have noted. Is that enough for this to stay open? Otherwise, I would probably say, this doesn't need fixing. In that case, it could also be fixed on TurboWarp's end, maybe? Or those extensions could just not use blank inputs?

It's still a bug, and there are definitely cases where this is noticable.
