### ISSUE TITLE
Include blocks from Scratch 3.0 in the Discussion Forums' scratchblocks palette

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6673]
### Why this would be helpful

The forum source code has not been updated since Scratch 3.0 (in fact, a few years before 3.0 released), so naturally, it doesn't include some of the amazing blocks that were added in 3.0.

I'm talking about this:
![Forum scratchblocks palette](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/527c710b-ed6b-4d7c-b591-614e421c9687)

### How this addon works

I'd like a new addon or update to an existing addon that adds the missing blocks to the menu.

**Comment by Samq64** [comment]
The forums now use Scratch 3 blocks (see #7910).

**Comment by Samq64** [comment]
There are still a couple issues but the blocks seem to be there.

![screenshot-2024-11-07-16-09-46](https://github.com/user-attachments/assets/1f517f2d-cdb9-4349-9a95-0399b2da3082)

**Comment by medlans** [comment]
> There are still some issues but the blocks are there.
> 
> ![screenshot-2024-11-07-16-09-46](https://private-user-images.githubusercontent.com/81489795/384043937-1f517f2d-cdb9-4349-9a95-0399b2da3082.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMTk3NjAsIm5iZiI6MTczMTAxOTQ2MCwicGF0aCI6Ii84MTQ4OTc5NS8zODQwNDM5MzctMWY1MTdmMmQtY2RiOS00MzQ5LTlhOTUtMDM5OWIyZGEzMDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDIyNDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkOGE1MTQ0OWM4MTI0Nzg1YzZlMDNhMjI1ZmY2MDAzNDM5MmQwNTRkN2U4N2JmNWU1ZDQ1ZTc1YTE2YmQ4MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yKNchRt_yVZ20A1UNiNPgGXb4LbyxmfJK5sPe26lyoY)

Yea, the only categories/extensions that didn't change were motion and pen I believe. Though the only extensions listed are Video and Pen, which means that the Music blocks no longer display.
