### ISSUE TITLE
Unhide Commonly Hidden Searches in Search

### ISSUE THREAD

**Issue by Scratchfangs** [ScratchAddons/ScratchAddons#6682]
### Why this would be helpful

If you add # after a search query, it will show projects that has been blocked from being shown in the search. For example, searching "FNAF" would not work, but searching "#FNAF" will show projects. Same works for things like "#GTA" and "#FPS".

![image](https://github.com/ScratchAddons/ScratchAddons/assets/71499307/334ecb8b-1cbd-4017-9091-4a11a9308bc7)
![image](https://github.com/ScratchAddons/ScratchAddons/assets/71499307/a5e036d0-7637-4adc-80e3-8b915587027d)

### How this addon works

This would automatically add a %23 in the URL after https://scratch.mit.edu/search/projects?q=, which is the same as a # key. This will show all projects. It could also hide the # symbol in the search bar.

**Comment by Scratchfangs** [comment]
This also works with multiple words.

![image](https://github.com/ScratchAddons/ScratchAddons/assets/71499307/2e8d1a94-6807-476e-adcf-09ae93d28a0f)
![image](https://github.com/ScratchAddons/ScratchAddons/assets/71499307/158c8d89-aebb-4e3a-bd59-6e116ccacd8d)

**Comment by WorldLanguages** [comment]
Is there any post about this in the Scratch discussion forums?

**Comment by Scratchfangs** [comment]
I don't think so.

**Comment by WorldLanguages** [comment]
Not sure if this type of addon fits in our extension. Probably not.
Also, if you already know the trick, it's quite easy to add the hash symbol yourself to the search box.

**Comment by Scratchfangs** [comment]
I find it to be more of a quality of life feature.

**Comment by BroJac5246** [comment]
Some people would use it, and this is a real feature of Scratch.

**Comment by WorldLanguages** [comment]
We avoid features which are the complete opposite of the intention by the Scratch Team. This is similar to adding NFE warnings: some users might find it useful to know if the project they're about to see is NFE, but it's still a complete misunderstanding of the moderator's intentions.

**Comment by BroJac5246** [comment]
> We avoid features which are the complete opposite of the intention by the Scratch Team. This is similar to adding NFE warnings: some users might find it useful to know if the project they're about to see is NFE, but it's still a complete misunderstanding of the moderator's intentions.

Yeah but that's not intentional

**Comment by WorldLanguages** [comment]
Exactly, I'm closing this

**Comment by BroJac5246** [comment]
> Exactly, I'm closing this

So this is a Scratch bug?
