### ISSUE TITLE
Ideas page button triggers share conformation

### ISSUE THREAD

**Issue by leahcimto** [ScratchAddons/ScratchAddons#6683]
### Description

When the "Choose a tutorial" button is pressed on [the ideas page](https://scratch.mit.edu/ideas), the "Are you sure you want to share?" popup appears.

### Steps to reproduce

1. Turn on the Conformations addon
2. Open https://scratch.mit.edu/ideas
3. Click on the "Choose a tutorial" button

### Environment

Browser: Firefox 117
Scratch Addons version: 1.34.1
Operating system: macOS Ventura

**Comment by mybearworld** [comment]
https://github.com/ScratchAddons/ScratchAddons/blob/0c6a216756fe27ffcd6006c91c67f3a8f2e7f189/addons/confirm-actions/userscript.js#L16

The ideas share button also has `.banner-button`.
