### ISSUE TITLE
`editor-theme3` doesn't change color of define blocks correctly in the forums

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6686]
### Description

The top line of blocks changed by `editor-theme3` in the forums always will have the regular color.

### Steps to reproduce

1. Enable `editor-theme3`.
2. Change the color of the define block.
3. Enable "Change color of blocks in the forums".
4. Go to a forum page with a define block (https://scratch.mit.edu/discuss/post/7529163/)

### Demonstration(s) and additional context

![A dark mode screenshot of a forum post with a scratch define block in it that has its color changed by editor-theme3, but not the color of the upper line.](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/3d505468-87ac-4798-8c86-11fce918481a)

### Environment

Browser: Edge 116
Scratch Addons version: 1.34.1
Operating system: Windows

**Comment by DNin01** [comment]
No longer a problem. (See #7910)
