### ISSUE TITLE
Variables and lists can be deleted by undoing after changing settings in/toggling some addons

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6691]
### Description

When I do something with the "Customizable block text style", "Customizable block shape", and possibly other addons, a dangerous action gets added to the undo history - if you click undo after enabling, disabling, or adjusting the settings in the aforementioned addons, it makes the variable and list blocks disappear from the block palette. What's more, when I undid in a sprite containing these variables, it asked me if I wanted to **quite literally DELETE THE USES OF THEM**. Also, if there is a comment attached to a block, it disappears if you undo once, and then variables and lists get deleted on the second undo, which sounds similar to a Scratch bug.

Redoing looks like it restores the variables in the block palette, but the block inputs are still messed up. Also, any variables that are also in other sprites seem to be unaffected.

Also, this happened somehow:
![Blank field equals 42 block](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/ec365ba8-76d9-42f6-bea8-3283438dd6fe)
![Broadcast blank and wait, broadcast blank](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/5682d386-a31f-4f6e-a00e-5b1bea1214af)
(Yes, literal message dropdowns got deleted - there weren't variable blocks inserted there.)

This is the most hilarious destructive bug I have seen here yet.

Testers, make sure you try this out in a project you don't care about or somebody else's project so that nothing... like, auto-saves or something.

### Steps to reproduce

1. Toggle or reconfigure "Customizable block text style"
2. Right-click > Undo

### Environment

Browser: Edge 117
Scratch Addons version: I was able to reproduce this all the way back to some version of v1.33.0 and TurboWarp (its addons haven't updated in a long while), and this bug is probably even older than that.
Operating system: Windows 11

**Comment by DNin01** [comment]
Happens with `editor-theme3` too.

Seems like it might have something to do with `clearWorkspaceAndLoadFromXml()`.

**Comment by Samq64** [comment]
> Seems like it might have something to do with clearWorkspaceAndLoadFromXml().

If it is then it should be possible to also reproduce with editor dark mode and cat blocks.

**Comment by mxmou** [comment]
This can't be an addon API bug because each of these addons uses its own code for reloading the workspace.

**Comment by mybearworld** [comment]
When you change the settings again after this has happened, the input fields go back to what they were before a reporter was inserted into them.

**Comment by WorldLanguages** [comment]
> Scratch Addons version: I was able to reproduce this all the way back to some version of v1.33.0 

Oof...

**Comment by WorldLanguages** [comment]
Tip from Garbo:

> see if doing ScratchBlocks.Events.setEvents(false) before and setEvents(true) after fixes it

I think that setting it to false avoids undo history from being affected until it gets set back to true, among other things
