### ISSUE TITLE
[New addon] Animated/custom thumbnail setter by World_Languages

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#67]
**Describe the new addon**

My animated thumbnail bookmarklet as an addon.

**Link to the new addon**

https://github.com/WorldLanguages/animatedThumbnailsBookmarklet/blob/master/code.js

Should probably be off by default, and add a button so it can be used if enabled.

**Comment by Hans5958** [comment]
any updates?

**Comment by GrahamSH-LLK** [comment]
If you want to figure it out, sure. I tried, and gave up.

**Comment by Hans5958** [comment]
oh

**Comment by YOYITsM3M8** [comment]
I would add a button in the File drop down. That button would upload a image and set it as the thumbnail

**Comment by Explosion-Scratch** [comment]
^^
That would be great.

**Comment by YOYITsM3M8** [comment]
lol i am trying to do that but am failing :C

**Comment by Explosion-Scratch** [comment]
XD sry
