### ISSUE TITLE
`enablepopup` has buttons ordered vertically instead of horizontally

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6706]
### Description

![Open full screen settings and Cancel buttons misaligned](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/9e790c5f-e2a3-4f17-b9fe-a7e06e21b331)
They're supposed to be side to side.

I think I know when this happened - see Environment.

### Steps to reproduce

1. Try to enable `scratch-notifier` from the popup

### Environment

Browser: Edge 117
Operating system: Windows 11

I believe this is when it started: **[`50b7f15`](https://github.com/ScratchAddons/ScratchAddons/commit/50b7f157cfc02424b22fcb5a63d84d0a4e81359a)** (#6469). Reverting it fixes the problem.

**Comment by WorldLanguages** [comment]
Whoops, looks like that's the only place where we didn't expect buttons would ever become block (flex) instead of inline.
