### ISSUE TITLE
Sprite Tab Selecting

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#671]
**In The Scratch Editor We Have 3 Tabs**

One thing many of us would find useful is having the tabs on the sprite list. So when we are switching between sprites we can choose which tab we want to go to immediately.

**Comment by WorldLanguages** [comment]
Can you try to explain better? I'm not sure I understand

**Comment by samuraininja360** [comment]
So you know the sprite list in the bottom right corner. I think it should have icons to access the costumes code and sounds tabs. It should be positioned above the sprite image.

**Comment by mxmou** [comment]
So you could go to a specific tab of another sprite in a single click?

**Comment by TheColaber** [comment]
![Screenshot 2020-11-08 093542 (1)](https://user-images.githubusercontent.com/72760579/98467912-ffcede80-21a5-11eb-8996-21013a0739a9.png)
I'm guessing like that?

**Comment by lisa-wolfgang** [comment]
Maybe when hovering over a sprite, the bottom label could be replaced with 3 small buttons, one with each tab's icon.

**Comment by samuraininja360** [comment]
Makes sense

**Comment by GrahamSH-LLK** [comment]
Honestly, this would be hard to use, and literally removes a single click.

**Comment by lisa-wolfgang** [comment]
> Honestly, this would be hard to use, and literally removes a single click.

@GrahamSH-LLK Although it may only be one click, because the entirety of the code/costumes for the sprite have to load on each click, that one click could save several seconds in very large projects.

**Comment by TheColaber** [comment]
not really... the program would first have to select the sprite... wait for it to load and then select the tab... that's not very efficient and likely not very possible without playing with DOM... it only saves the user how long it takes them to be able to move their mouse.
