### ISSUE TITLE
Check Scratch API endpoints where we use `nocache` or `timestamp` in the URL

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6717]
The requests with those URL parameters are being intentionally throttled, which makes Scratch Messaging slow, we should check whether we want to bypass the cache at all

**Comment by WorldLanguages** [comment]
Feedback also says marking messages as read takes a lot of time, weird

**Comment by WorldLanguages** [comment]
> Feedback also says marking messages as read takes a lot of time, weird

Looks like we don't show the fact messages were indeed marked as read until retrieving the updated message count.
The "mark as read" request itself is not throttled.

**Comment by The-Abigail608** [comment]
so it's scratch's fault.

**Comment by rgantzos** [comment]
> so it's scratch's fault.

Well… yeah. It’s their servers, they’re the ones who added it.
