### ISSUE TITLE
Exponent Blocks

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#672]
**I hate having to drag each multiplication block when I am using the pythagorean theory**

So I was thinking this was a huge drawback or bug with the scratch editor. Is it possible to fix this inadequacy with a block like `((10)^(2))`
and use it in a dropdown option for the `mod` operator. Or on its own I don't mind.

**Comment by WorldLanguages** [comment]
I don't think this would be possible. You could create a custom block and use a variable to return the result.
