### ISSUE TITLE
`collapse-footer`: Footer starts expanded on `scratchr2` pages

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6720]
### Description

On `scratchr2` pages specifically, when the addon is activated, the footer seems to start out expanded before promptly collapsing, which is very unpleasant.

There's also a subtle but probably unintended animation on `scratch-www` pages.

### Steps to reproduce

1. Enable Sticky footer
2. Navigate to a Scratch 2.0 page

### Environment

Browser: Edge 117
Scratch Addons version: `ede3409`
Operating system: Windows 11

**Comment by Samq64** [comment]
I removed `!important` because everything looked fine on `scratch-www` but it's required on `scratchr2`.

**Comment by RedGuy12** [comment]
fwiw i believe this was also a bug when the addon was part of infinite-scroll

**Comment by Samq64** [comment]
At least on Chromium it looks like on v1.33 it only happened when the page was cached but on master it happens consistently.
