### ISSUE TITLE
Add an option to disable dragging in the stage

### ISSUE THREAD

**Issue by 6543ozne** [ScratchAddons/ScratchAddons#6731]
### Why this would be helpful

I think this would  be helpful when your project has a lot of clickable features and you don't want to accidentally drag them while you test it.

### How this addon works

This addon would add an icon and a checkbox that when checked, would make you unable to drag sprites around
![2023_10_02_0ej_Kleki](https://github.com/ScratchAddons/ScratchAddons/assets/105403431/13c2ae26-5c6d-4a2a-8363-dfa45ce76e65)

### Possible alternatives

idfk man

### Additional context

![image](https://github.com/ScratchAddons/ScratchAddons/assets/105403431/c1a98c63-16a2-48b7-a4f1-62eb1b49a78a)

**Comment by rgantzos** [comment]
This is already an addon.

**Comment by 6543ozne** [comment]
oh ok

**Comment by 6543ozne** [comment]
you mind showing me the link

**Comment by 6543ozne** [comment]
nevermind
