### ISSUE TITLE
Cloud games tab isn't working

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6750]
![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/3c4ba64e-708d-4185-abb3-a6e167bb9424)

**Comment by WorldLanguages** [comment]
Actually, vanilla Scratch cloud monitors are also failing: https://scratch.mit.edu/cloudmonitor/823872487/

**Comment by WorldLanguages** [comment]
See Scratch forums post: https://scratch.mit.edu/discuss/topic/715789/

**Comment by DNin01** [comment]
![Error messages](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/6c6db532-b8a3-4acc-ba8d-b623b2be231a)

**Comment by DNin01** [comment]
If we really wanted to, this could be an opportunity to improve the error message on the popup. Perhaps if all fetches fail, a single error message could be displayed instead?

```
Uh oh, seems like Cloud Data is experiencing a problem. Try again later.
```

**Comment by Secret-chest** [comment]
> Sorry, but the Scratch cloud data servers are down. Please try again later.

**Comment by WorldLanguages** [comment]
I think we have that error for 5xx error codes, but not for too many redirects

**Comment by WorldLanguages** [comment]
Looks like it's working now.
