### ISSUE TITLE
Declare `minimum_chrome_version` in the manifest.json

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6751]
### Why this would be helpful

Chrome extension manifest files can optionally have a [`minimum_chrome_version`](https://developer.chrome.com/docs/extensions/mv3/manifest/minimum_chrome_version/) key, which specifies what the oldest possible version an extension can run on.

> #### New Installs
> In versions of Chrome older than the minimum version, the Chrome Web Store will show a "Not compatible" message in place of the install button. Users on these versions will not be able to install your extension.
> 
> #### Existing Installs
> Existing users of your extension will not receive updates when the `minimum_chrome_version` is higher than their current browser version. This happens silently so you should exercise caution and consider ways of letting existing users know that they are no longer receiving updates.

Declaring a minimum version means:
- If we ever drop support for older versions, the extension won't automatically update to an unsupported version - it will stay on the most recent supported version.
- If a user's browser is unsupported, the install button on the Chrome Web Store is grayed out, which just means better UX since the user will be stopped earlier, before they have a chance to be disappointed that they installed the extension only to realize it wasn't going to work.

### My suggestion

In addition to [our current JS check](https://github.com/ScratchAddons/ScratchAddons/blob/3976d322d6493ad09150123816b9db626204ed66/background/handle-unsupported-version.js), add this key to the manifest.

And yes, it is MV2-compatible.

### Possible alternatives

Other than what I described above, it's not _really_ necessary, and I haven't checked for an equivalent for Firefox, and it does mean we can't automatically redirect the user to information or collect [analytics](https://analytics.scratchaddons.com/scratchaddons.com?period=all&page=**%2Funsupported-browser%2F&source=extension) on how many users are on unsupported browsers.
<sub>I can't believe that's actually how many people are coming from an unsupported browser. (Or do people just like that page?)</sub>

Alternatives to this that might be better include:
- Keeping the current check and redirect.
- With #6741 in mind, instead of redirecting to our website, open an error page and send error information.

### Related

- Preventing security updates could be problematic, here are some related issues:
  #2620, #5248

**Comment by WorldLanguages** [comment]
I never tried to add this key because I'm not sure how Chrome behaves when the minimum is increased - do they get stuck in the old version? Does Chrome just delete the extension?

Due to security concerns, I prefer to break extensions when possible. Letting users keep an old version is risky (unless they downloaded from GitHub, of course).

**Comment by WorldLanguages** [comment]
> If we ever drop support for older versions, the extension won't automatically update to an unsupported version - it will stay on the most recent supported version.

What's your source?

**Comment by DNin01** [comment]
> > If we ever drop support for older versions, the extension won't automatically update to an unsupported version - it will stay on the most recent supported version.
> 
> What's your source?

https://developer.chrome.com/docs/extensions/mv3/manifest/minimum_chrome_version/

**Comment by WorldLanguages** [comment]
> I can't believe that's actually how many people are coming from an unsupported browser. (Or do people just like that page?)

Wow, 35% of views to the unsupported browser page are from Firefox. How do you even get an old version of Firefox? I guess those are just people using old operating systems, Windows 7?

Also, here's the breakdown by OS:

![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/25e8d60f-1566-4b76-936c-7a38ccc1839f)

Yeah, this looks like expected. Old Chrome versions are often Chromebooks which don't get any updates anymore. They are sometimes old or current laptops provided by schools.
Kinda crazy to see Mac above Windows though.

**Comment by DNin01** [comment]
How important would you say these unsupported-browser analytics actually are? IMO, they're not really giving us feedback that's useful to us, so it's probably fine to sacrifice them.

**Comment by WorldLanguages** [comment]
I agree, having the statistics on how many users see this page, and their browser/OS, isn't very important. We already try to support as many browsers as reasonably possible.

**Comment by Samq64** [comment]
> I guess those are just people using old operating systems, Windows 7?

I think it supports up to 115. I'm not completely sure about 32 bit for MacOS.

**Comment by BroJac5246** [comment]
> How valuable would you say these unsupported-browser analytics actually are? To me, they don't seem to be giving us feedback that's useful to us, so it's probably fine to sacrifice them.

Is it even worth the effort to "sacrifice them," though? Like, does it hurt to keep it?

**Comment by WorldLanguages** [comment]
> Is it even worth the effort to "sacrifice them," though? Like, does it hurt to keep it?

#6669 says users should be able to export their settings if their browser becomes unsupported after an update. It's easier to add that functionality if the "unsupported browser" page becomes a `chrome-extension://` URL.
The easiest solution that preserves analytics is probably a fullscreen iframe, and a simpler fallback if there's no internet connection.

**Comment by WorldLanguages** [comment]
After our first MV3 release, we will have an implicit `minimum_chrome_version` of 88, as older browsers than that don't know how to interpret a manifest with a version number of three.

Most likely (I'm not sure) our background-page/service-worker will completely fail to load in versions older than Chrome 96-ish. However, I think in Chrome 88-96 we can continue to display the Unsupported Browser page when users try to access the settings page or try to open the popup. However, we will not be able to open the Unsupported Browser page automatically after the browser is opened.

Most likely, we will not add an explicit `minimum_chrome_version` property to our manifest **in the store versions of the extension**. It will be implicitly be 88 soon.

**Comment by WorldLanguages** [comment]
Related: #6876

**Comment by DNin01** [comment]
> Most likely (I'm not sure) our background-page/service-worker will completely fail to load in versions older than Chrome 96-ish.

Why?

**Comment by WorldLanguages** [comment]
As far as I can remember, Chrome 88 supports MV3 service workers, but does not allow for module imports, so the `import` keyword becomes a syntax error.

**Comment by DNin01** [comment]
> As far as I can remember, Chrome 88 supports MV3 service workers, but does not allow for module imports, so the `import` keyword becomes a syntax error.

That makes sense.

---

Well, from the conversation on this issue, I think it's safe to assume we'd rather not use `minimum_chrome_version`, but instead set up our own error page to prevent usage on those versions. It would brick the extension for those users, but it's better than our users being stuck on a version with security bugs.

**Comment by DNin01** [comment]
I guess the one case we could set this is once we migrate to Manifest V3 after we have released a MV2 version that leaves outdated users stuck on the "unsupported browser" page. An advantage of that is we can keep redirecting users to the "unsupported browser" page even if they're on a Chrome version where the service worker can't start if they were to update to a MV3 version.

**Comment by WorldLanguages** [comment]
@DNin01 No idea what you mean, doesn't manifest_version:3 implicitly convert to minimum_chrome_version:88? Why would we add it explicitly to the manifest?

**Comment by WorldLanguages** [comment]
You're right, I think we could do that - adding a minimum_chrome_version at the same time as we upgrade to MV3, and keeping it intact until MV4 comes along.
Still, I think it could get confusing one year from now, as it may get mistaken as the real minimum supported version.

**Comment by medlans** [comment]
> > I can't believe that's actually how many people are coming from an unsupported browser. (Or do people just like that page?)
> 
> Wow, 35% of views to the unsupported browser page are from Firefox. How do you even get an old version of Firefox? I guess those are just people using old operating systems, Windows 7?

That was likely all because of me, but basically there's a Firefox directory that allows you to get old versions of Firefox including ones that allow Adobe Flash.
