### ISSUE TITLE
White profile search picture when dark mode is enabled

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6772]
### Description

> When using the "Website dark mode and customizable colors" (on any dark theme), and "Username Search" addons, then when searching for a username, the profile picture will show up as just white. This happens on Firefox, bu I have not tested other browsers.

I can also repro on Chromium.

### Steps to reproduce

1. Enable  username search
2. Enable website dark mode
3. Search for Griffpatch

### Demonstration(s) and additional context

![20231014_10h27m32s_grim](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/68e6d96e-122a-4295-8687-5d3e903a08ce)

### Environment

Browser: Firefox and Chromium 118
Scratch Addons version: 1.35.0
Operating system: Linux

**Comment by WorldLanguages** [comment]
Makes sense, we forgot about this.

Low-prio as there was previously no profile picture at all.
