### ISSUE TITLE
ocular-integration does not show status color

### ISSUE THREAD

**Issue by ajskateboarder** [ScratchAddons/ScratchAddons#6773]
### Description

Any user's Ocular color does not show up next to their status in forums. Colors still show on profile pages, though, so this is likely not intentional

### Steps to reproduce

1. Enable the "ocular integration" addon in ScratchAddons
2. Go to any post in a topic where a user with an Ocular status and color has posted. For instance, [this one](https://scratch.mit.edu/discuss/post/7377709/) (this poster should have a green-colored dot next to their status as of now)
3. Notice the lack of any colored dot

### Environment

Browser: Firefox 118.0.2 (should also be reproducible in Chromium-based browsers)
Scratch Addons version: 1.35.0
Operating system: Windows 11

**Comment by WorldLanguages** [comment]
Whoops, I forgot [status-dot.css](https://github.com/ScratchAddons/ScratchAddons/blob/master/addons/my-ocular/status-dot.css) also applied in forum topics
