### ISSUE TITLE
editor-colored-context-menus ignores high-contrast mode

### ISSUE THREAD

**Issue by pufferfish101007** [ScratchAddons/ScratchAddons#6776]
### Description

When in high-contrast mode in the editor (editor-theme3 disabled), context menus are unreadable ddue to the text being white instead of black.

### Steps to reproduce

1. Enable editor-colored-context-menus
2. Enable hihh contrast mode via setyings in editor
3. Right click a block

### Demonstration(s) and additional context

![Screenshot_20231015-185845_Kiwi Browser](https://github.com/ScratchAddons/ScratchAddons/assets/50246616/29c72b02-3076-467a-8cac-bd93ea35bc38)

### Environment

Browser: chromium 116
Scratch Addons version: 1.35.0
Operating system: android 10

**Comment by just-a-hriday** [comment]
I can reproduce, edge 118
