### ISSUE TITLE
`scratch-messaging`: Ghost messages after marking as read

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6777]
### Description

When marking messages as read, the message counter will go to 0. However, after some time, it'll go back to the count it was before - when checking the messages, it goes back to 0.

### Steps to reproduce

1. Get a message
2. Mark it as read
3. Go out of the popup
4. Wait for a bit
5. See the ghost message
6. Click on the popup
7. See it disappear

### Demonstration(s) and additional context

Very likely caused by #6728, but unintentional: 

> I made it so after marking messages as read from the popup, the message count is obtained again bypassing the cache, so there should be no ghost messages after reopening the popup.

### Environment

Browser: Edge 118
Scratch Addons version: 1.35.0
Operating system: Windows 11

**Comment by WorldLanguages** [comment]
Good catch. The cache bypass works, but if it fetches again it may hit the (old) cache.

I'm not sure how this can be solved. I'll check how much information you can get through JavaScript on whether a response comes from the network or from the cache.

**Comment by WorldLanguages** [comment]
+1 from feedback
Will probably warrant a v1.35.1 release
