### ISSUE TITLE
Framerate Setter

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#679]
**Describe the new addon**

An option on projects to set the framerate.

**Link to the new addon**

None, however, @GarboMuffin made https://garbomuffin.github.io/p3/ which has an option for the framerate the project runs at. They stated that they: 
> Replaced Scratch's "compatibility mode" with a more generic "framerate" option

@GarboMuffin Would it be possible to bring this to Scratch Addons?

**Comment by pufferfish101007** [comment]
I think this should be possible, something like this might work:
```
export default async function ({addon, console}) {
  const vm = addon.tab.traps.onceValues.vm;
  vm.runtime.start = () => {
     // Do not start if we are already running
        if (this._steppingInterval) return;

        let interval = Runtime.THREAD_STEP_INTERVAL;
        if (this.compatibilityMode) {
            interval = 1000 /
 addon.settings.get("frame_rate");
        }
        this.currentStepTime = interval;
        this._steppingInterval = setInterval(() => {
            this._step();
        }, interval);
        this.emit(Runtime.RUNTIME_STARTED);
  }
}
```
However that is untested and it doesn't account for changing the framerate while the project is running.

**Comment by lisa-wolfgang** [comment]
Also want to mention that [forkphorus](forkphorus.github.io) has this.
