### ISSUE TITLE
[New addon] Show full numbers in profiles (FollowersNumberEnabler)

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#68]
> https://github.com/WorldLanguages/FollowersNumberEnabler (Just amazing, maybe add a # of favorites, comments, curated studios & following studios.)

Probably shouldn't be enabled by default, and we should probably provide settings on what should be loaded, since it slows down the page. I'd be fine with follow counts.

**Comment by Explosion-Scratch** [comment]
I'd like this! It adds stats at a glance, allowing me to judge a user by
their followers, not their projects.

**Comment by Explosion-Scratch** [comment]
That was a joke
