### ISSUE TITLE
`better-quoter` does not escape [square brackets]

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6815]
### Description

In the forums, [square brackets] are used for tags. Anything that is enclosed within square brackets will be removed from the post. This has some exceptions - in particular, [[]doing this] will make the brackets show up in the post. However, when quoted by `better-quoter`, they'll not be escaped.

### Steps to reproduce

1. Highlight a section of a post with an escaped tag, like https://scratch.mit.edu/discuss/post/7608011/
2. Quote it

### Demonstration(s) and additional context

![A screenshot of a forum topic in Scratch. The end of a post is visible with some text highlighted, that includes an escaped \[scratchblocks\] tag, so it is visible in the post. After this is this post quoted with better-quoter, where this escaped \[scratchblocks\] tag is included verbatim - therefore, at the very bottom in the post preview pane, the markup is messed up where half of the post is in an unclosed \[scratchblocks\] tag.](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/bb178abb-662d-4342-8ad8-555501f26166)

### Environment

Browser: Edge 118
Scratch Addons version: 1.35.1
Operating system: Windows

**Comment by ajskateboarder** [comment]
That's odd... any reason why this addon just fetch the source instead?

![Screenshot 2023-11-03 152703](https://github.com/ScratchAddons/ScratchAddons/assets/81255936/79102385-5491-4f60-b7e9-a9d83d18ec01)

**Comment by CST1229** [comment]
> That's odd... any reason why this addon just fetch the source instead?

It has to find the selection in the BBCode, and that's not very easy.
