### ISSUE TITLE
blocks2image addon: new feature to copy image instead of downloading it

### ISSUE THREAD

**Issue by Jazza-231** [ScratchAddons/ScratchAddons#6823]
### Why this would be helpful

So you dont have to save the blocks to your PC then upload them to wherever

### My suggestion

Adds a third option to copy the blocks directly to the clipboard

### Possible alternatives

Maybe a keybind? im not sure if that's appropriate tbh

### Additional context

Ive already made it: https://github.com/Jazza-231/ScratchAddons/tree/copy-blocks-to-clip

just making an issue to hear if others thing this is a good idea

**Comment by mybearworld** [comment]
What exactly would get copied to the clipboard?

**Comment by just-a-hriday** [comment]
Sounds like a good idea.

**Comment by WorldLanguages** [comment]
Is this "copy the image of the blocks to the clipboard"? I thought this was about the editor-devtools feature at first.

**Comment by Jazza-231** [comment]
Right yeah its not obvious, this is copying the *image* of the block to the clipboard

**Comment by Jazza-231** [comment]
Would like opinions on how to indicate these are images while keeping it concise 
![image](https://github.com/ScratchAddons/ScratchAddons/assets/81956724/fedaaa1f-bc07-4c48-8d9d-3ce2d977fdb0)

**Comment by mybearworld** [comment]
I think you can create the PR - questions like the above are probably more well suited for the PR.

**Comment by Jazza-231** [comment]
Alrighty

**Comment by WorldLanguages** [comment]
One downside is that this will require more context menu items.

**Comment by Samq64** [comment]
> One downside is that this will require more context menu items.

Related: #4919
