### ISSUE TITLE
New lines in block reporters

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6831]
### Why this would be helpful

It can be helpful to use new lines sometimes, like in say blocks.

### How this addon works

This addon would allow you to put new lines, and also style them a bit better than the current styling.

**Comment by Samq64** [comment]
Related: #4172

**Comment by WorldLanguages** [comment]
Yeah, pretty much a duplicate...

Are there any built-in CSS primitives to display new lines differently? Or is it difficult?

**Comment by mybearworld** [comment]
> Related: #4172

I didn't see that somehow - this issue also includes being able to type them, but you could probably still say it's a duplicate.

> Are there any built-in CSS primitives to display new lines differently? Or is it difficult?

There are, but Scratch renders new lines as `&nbsp;`s.
