### ISSUE TITLE
Snapping + Onion skinning: Cannot open settings

### ISSUE THREAD

**Issue by iqnite** [ScratchAddons/ScratchAddons#6840]
### Description

When clicking on the settings buttons for Onion skinning or Snap in costume editor, the menu doesn't show up and the icon's color changes quickly before switching back to the original one.

### Steps to reproduce

1. Enable Snapping in costume editor and/or Onion skinning
2. Click on the settings button for Snapping/Onion skinning
3. Try to see the settings (it's impossible)

### Demonstration(s) and additional context

https://github.com/ScratchAddons/ScratchAddons/assets/50552317/1fa58a54-8d7c-4b81-8122-dc58adc87f69

I think this is caused by https://github.com/ScratchAddons/ScratchAddons/pull/6801

### Environment

Browser: Vivaldi 6.4.3160.41 (Stable channel) (64-Bit) 
Scratch Addons version: 1.36.0-prerelease [8d22730](https://github.com/ScratchAddons/ScratchAddons/commit/8d2273099d8e261f4638458cb5339e7143f0b4e6)
Operating system: Windows 11 Pro 23H2 22635.2700

**Comment by DNin01** [comment]
Looks like @WorldLanguages's commits [c7f699e](https://github.com/ScratchAddons/ScratchAddons/pull/6801/commits/c7f699eb8dbe8b09ab519b6d40c98d8f4f4285cf) and [38a3ed2](https://github.com/ScratchAddons/ScratchAddons/pull/6801/commits/38a3ed257d9b6d9a5179f58f977ad10476115400) are the culprit.

**Comment by WorldLanguages** [comment]
Yeah, the button itself did follow the class name scheme before I modified the selector, but it wasn't ideal
