### ISSUE TITLE
button label on permissions page not centered

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6844]
### Description

The Enable button's label on the permissions page isn't centered.

This is probably a regression from #6469

### Steps to reproduce

1. Disable extension site access
2. reload the extension

### Demonstration(s) and additional context

![image](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/acd62608-b441-4ce2-a966-70d2456018c4)

### Environment

Browser: Chromium 117
Scratch Addons version: 1.35.1
Operating system: Linux

**Comment by WorldLanguages** [comment]
Oof... I wonder if we should prefer duplicating the CSS instead of reusing existing classes for these cases

**Comment by DNin01** [comment]
Yeah, I guess we didn't realize how many regressions that change would cause…

I would rather fix the offending style rule than making a bunch of exceptions to fix it where it's broken.
