### ISSUE TITLE
[Minor] Project audio unpauses when opening sound library

### ISSUE THREAD

**Issue by iqnite** [ScratchAddons/ScratchAddons#6847]
### Description

If I have paused a project with music and open the sound library, the project audio resumes. Note that the rest is still paused, and the Pause button keeps the triangle shape; The only thing that unpauses is the audio.

I don't know if this is semi-intentional, anyways it's annoying.

### Steps to reproduce

1. Open and start a project containing music in the editor (like a "forever: play sound until the end" loop)
2. Click on Pause
3. Switch to the Sounds tab, hover on Add sound and click Choose a sound

### Environment

Browser: Vivaldi 6.4.3160.41 (Stable channel) (64-bit) 
Scratch Addons version: 1.36.0-prerelease [8d22730](https://github.com/ScratchAddons/ScratchAddons/commit/8d2273099d8e261f4638458cb5339e7143f0b4e6)
Operating system: Windows 11 Pro 23H2 22635.2700

**Comment by WorldLanguages** [comment]
+1 from Discord
