### ISSUE TITLE
Cloud Games tab doesn't work

### ISSUE THREAD

**Issue by fancyfinn9** [ScratchAddons/ScratchAddons#6852]
### Description

As seen in the image below, the cloud games tab, while it does show the games, it tells me that it cannot get the cloud data.
![Screenshot 2023-11-10 121716](https://github.com/ScratchAddons/ScratchAddons/assets/142792026/11df4478-1ee8-4bec-97e1-965b67e90338)

### Steps to reproduce

1. Install Scratch Addons
2. Switch to the Games tab of the pop-up which appears when you click the extension icon

### Environment

Browser: Microsoft Edge 119.0.2151.58 (Official build) (64-bit) 
Scratch Addons version: 1.35.1
Operating system: Windows 10, 64-bit

**Comment by Samq64** [comment]
See #6750
