### ISSUE TITLE
Dragging variables is weird when the browser window is shrunken

### ISSUE THREAD

**Issue by hueychen27** [ScratchAddons/ScratchAddons#6854]
### Description

You can drag a variable in Scratch to the right when the browser window is maximized. When the window is shrunken enough, variables can't be dragged to the rightmost part of the game screen. Also, variables "lag" behind the mouse cursor. The height of the window does not affect the variable dragging.

### Steps to reproduce

1. Make a variable visible.
2. Shrink the screen.
3. Drag the variables.

### Demonstration(s) and additional context

https://github.com/ScratchAddons/ScratchAddons/assets/78285518/affc603f-e7b3-497a-bb20-e37f246564f0

### Environment

Browser: Firefox ESR 115.4.0esr
Scratch Addons version: v1.35.1
Operating system: Kali Linux

**Comment by Samq64** [comment]
This is a Scratch bug, not a Scratch Addons one.
