### ISSUE TITLE
Wrong comment warning position with scratchr2

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6859]
### Description

> Dunno if it could really be fixable (other than attempting to swap it to the message thing like with studio pages or project pages), so I'd rather send it through the feedback page here (and since I'm not really a good explainer). The mute reason overlaps a bit of comments on 2.0 pages (eg. user profiles, etc) with 2.0 -> 3.0 enabled (Firefox 119.0.1 32 bit here) - It's not really a big problem but thought I'd report anyways.
(Apologies for using assets.scratch.mit.edu for this incase it's inconvenient in this regard)
https://assets.scratch.mit.edu/get_image/.%2E/ba823cc902c18cef4d76f224c73cefed.png
Does block a bit of view until you dismiss it which is kind of annoying though.

### Steps to reproduce

This also happens with our message.

1. Enable `scratchr2`
2. Go to your profile
4. Comment "Scratch Addons"

### Demonstration(s) and additional context

![ba823cc902c18cef4d76f224c73cefed](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/e8daa2e1-28fa-43c8-aba2-8147182b8f9c)

This doesn't happen on scratch-www because it doesn't use a tooltip and on profiles without the addon the textbox isn't as wide.

### Environment

Browser: Firefox 119
Scratch Addons version: 1.35.1
Operating system: Linux

**Comment by Scythn** [comment]
Didn't think of this when writing it in feedback - However if possible, maybe it could get moved from the left of the textfield to above it?
<sub>This is only a theoretical solution though...</sub>

**Comment by CST1229** [comment]
(For a safer way to test without triggering the filter, the same kind of warning appears when trying to post an empty comment:)
![image](https://github.com/ScratchAddons/ScratchAddons/assets/68464103/632361f9-6fea-49a5-a4ab-0a8578f00278)

**Comment by Scythn** [comment]
> (For a safer way to test without triggering the filter, the same kind of warning appears when trying to post an empty comment:) ![image](https://user-images.githubusercontent.com/68464103/282319111-632361f9-6fea-49a5-a4ab-0a8578f00278.png)

You could also get the mute text and just inspect element for a similar affect, since with scratchr2 / 2.0 -> scratch-www / 3.0 on the overlap is a lot less prominent with the empty comment notice
![empty](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/72933247-8474-4a8c-a1a4-12f671fddec1)

**Comment by CST1229** [comment]
> You could also get the mute text and just inspect element for a similar affect, since with scratchr2 / 2.0 -> scratch-www / 3.0 on the overlap is a lot less prominent with the empty comment notice

Getting muted sends an alert to the Scratch Team, which is probably not good.

**Comment by Scythn** [comment]
> Getting muted sends an alert to the Scratch Team, which is probably not good. Trying to post an empty comment makes the warning show up _without_ risking your account standing in any way.

I meant it as in replicating the alert text and then inspecting to replace the empty comment alert, apologies for my bad explanation.

**Comment by Samq64** [comment]
> Didn't think of this when writing it in feedback - However if possible, maybe it could get moved from the left of the textfield to above it?

On other pages our warning is displayed above in orange, so it would make sense to do that for all warnings on profiles with the addons.

**Comment by Scythn** [comment]
> On other pages our warning is displayed above in orange, so it would make sense to do that for all warnings on profiles with the addons.

I meant the scratchr2 notice, but yes that could also work
