### ISSUE TITLE
compact-editor: not enough room for backpack when on costumes tab

### ISSUE THREAD

**Issue by Scythn** [ScratchAddons/ScratchAddons#6862]
### What should happen
Backpack item names show as normal in costumes (via compact editor enabled)
### What actually happens
Item icons (costume, etc) in backpack are cut into half (roughly) and titles are not visible, only workarounds to it are zooming out (90%) or entering full screen.

### Steps to reproduce

1. Enable compact editor (if not enabled yet) and go into the project editor,
2. Go to costumes,
3. Open backpack (Items should be cut in half).

### Demonstration(s) and additional context

![backpack](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/3332e044-79c8-4eea-b8cc-286fac417a77)
<sub>forgot i should use a screenshot of not just the costume pane probably</sub>
### Environment

Browser: Firefox (v119.0.1, 32 bit)
Scratch Addons version: v1.35.1
Operating system: Windows 10 (1366 x 768 screen resolution)

**Comment by WorldLanguages** [comment]
Is the Sounds tab affected?

**Comment by WorldLanguages** [comment]
Can somewhat reproduce with 110% zoom, but I believe this depends heavily on browser zoom.

@Scythn Could you post a screenshot of the same costumes tab and zoom level, but with "compact editor" off? Also, make sure you first toggle the zoom and addon(s) and then open the backpack, in case that makes a difference.

**Comment by WorldLanguages** [comment]
> I have a smaller monitor {1366 x 768}

I see, thanks for mentioning that. Also don't worry about the late response (16 hours isn't late lol!)

**Comment by Scythn** [comment]
> > I have a smaller monitor {1366 x 768}
> 
> I see, thanks for mentioning that.

I should've pointed it out earlier to be honest (will add to OP)

> Also don't worry about the late response (16 hours isn't late lol!)

Alrighty then <sub>you're right atleast it didnt take weeks lol</sub>

**Comment by WorldLanguages** [comment]
>[just tried on Edge and also occurs there](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/8617194f-b15f-4bc9-95a8-d00d73a69849), even with every other addon disabled

Oh, then the issue isn't the compact-editor addon then.

**Comment by mybearworld** [comment]
> Honestly probably just because of my smaller screen resolution now that I really think about it if it's only occuring with 1366 x 768 monitors ([just tried on Edge and also occurs there](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/8617194f-b15f-4bc9-95a8-d00d73a69849), even with every other addon disabled) - So this probably isn't that big of an issue in the long run and can be closed without needing any fix.

It shouldn't be closed - addons should work regardless of screen size.

**Comment by BroJac5246** [comment]
> > Honestly probably just because of my smaller screen resolution now that I really think about it if it's only occuring with 1366 x 768 monitors ([just tried on Edge and also occurs there](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/8617194f-b15f-4bc9-95a8-d00d73a69849), even with every other addon disabled) - So this probably isn't that big of an issue in the long run and can be closed without needing any fix.
> 
> It shouldn't be closed - addons should work regardless of screen size.

And 1366 x 768 is the resolution of a lot of smaller laptops (particularly education Chromebooks), so we probably have a good number of users with screens that are that size.

**Comment by WorldLanguages** [comment]
This comment I'm about to make is a bit off-topic, but I believe the Scratch editor itself isn't well designed for smaller laptop resolutions. Which is quite awkward, as many school chromebooks have those types of screens. I've seen multiple pictures of the Scratch editor with a vertical scrollbar at 100% zoom.

**Comment by mybearworld** [comment]
> This comment I'm about to make is a bit off-topic, but I believe the Scratch editor itself isn't well designed for smaller laptop resolutions. Which is quite awkward, as many school chromebooks have those types of screens. I've seen multiple pictures of the Scratch editor with a vertical scrollbar at 100% zoom.

I think it was designed for tablets, but those don't have scroll bars, so they weren't as big of a focus.

**Comment by BroJac5246** [comment]
> This comment I'm about to make is a bit off-topic, but I believe the Scratch editor itself isn't well designed for smaller laptop resolutions. Which is quite awkward, as many school chromebooks have those types of screens. I've seen multiple pictures of the Scratch editor with a vertical scrollbar at 100% zoom.

I haven't personally had any problems on a 1366 x 768 Chromebook, but maybe that's a problem on other operating systems or screen sizes?
