### ISSUE TITLE
Split up/generate the `manifest.json`

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6874]
As mentioned by @WorldLanguages in #5162, we will need a separate `manifest.json` file for Firefox.

Manifest V3 changes the way background pages work: that is, Chrome no longer supports background pages, and instead accepts a single [service worker](https://developer.chrome.com/docs/extensions/migrating/to-service-workers/) containing JavaScript code. However, Firefox only supports background pages at this time.

To help maintain browser compatibility and make sure we can test the extension on Firefox, it looks like we're going to need to split up the extension manifest into two files, one for Chrome and one for Firefox, or create a script that generates one for the appropriate browser, and that, my friends, is where build steps come into play.

If we split up the manifest file, developers would need to run a build script or manually perform some steps before using the extension. It's just a very simple assembly process, just place the correct one into the output project's root directory for use by the browser extension, so running the build script wouldn't be strictly necessary, it'd just make it faster. And no, we can't just have the project readily assembled with the Chrome manifest already in place because overwriting that could cause the replaced manifest file to be staged and committed. We'd have to "`.gitignore`" it.

It is possible that [Firefox will support service workers in the near future](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background#browser_support) though, and [W3C is trying too](https://github.com/w3c/webextensions/issues/282), so we'll wait a bit and see if we won't have to do this.

**Comment by WorldLanguages** [comment]
> looks like we're going to need to split up the extension manifest into two files

We are not, please wait until I create my own issue as a summary of what the situation is :P

Tip: see all of the latest comments on here. https://github.com/w3c/webextensions/issues/282

**Comment by WorldLanguages** [comment]
I wrote a post here: #6874

**Comment by DNin01** [comment]
> I wrote a post here: #6874

I think you meant #6876?

**Comment by DNin01** [comment]
> This means contributors will need modern Firefox versions that support MV3, as well as [modern Chromium versions that don't reject Firefox-friendly manifest files](https://github.com/w3c/webextensions/issues/282#issuecomment-1786857524). Apparently, it's going to be Chrome 121+ and Firefox 121+ (coincidentally, it's the same version number!)

Yay! So we won't have to worry about swapping the manifest file for either browser, right?

**Comment by WorldLanguages** [comment]
It is not strictly necessary. See #6877 for a demo. Currently, you need Chrome Canary or Firefox Nightly to test it.

**Comment by WorldLanguages** [comment]
It wasn't strictly necessary to do this after all.
