### ISSUE TITLE
All new addons should be marked as beta for one update cycle

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#688]
I've noticed that most bug reports are related to the latest addons.
This policy would allow users to test-drive the new addons and report any bugs before the addon is designated as complete or Recommended. If all buggy behavior found is fixed (or nonexistent), the addon can be marked as such in the next update.

**Comment by WorldLanguages** [comment]
I agree to do this with complex addons, like the ones that interact with the editor, and might break projects permanently. But not with simple addons that just slightly change the website.

**Comment by lisa-wolfgang** [comment]
I just figured that it should be verified that new addons work correctly. That's what beta labels are for. For many of the new v.1.2 addons, I didn't witnessed enough addon testing on the developer side for those addons to not be labeled as beta.

**Comment by lisa-wolfgang** [comment]
Closing, see #2622
