### ISSUE TITLE
`discuss-button`: "Compact user dropdown" doesn't always work on the My Stuff page

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6880]
### Description

"Compact user dropdown" doesn't always work on the My Stuff page. The padding is still removed, though.

### Steps to reproduce

1. Go to My Stuff
2. Do some stuff quickly
3. If nothing happened, go back to another page and repeat

### Demonstration(s) and additional context

Image:

![The right part of the header with no padding between username and profile picture](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/798dd2c7-0e4e-4d4a-be98-8ca124e07161)

Error in the console:

```js
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'textContent')
    at add (r2.js:17:54)
```

### Environment

Browser: Edge 119
Scratch Addons version: 1.35.1
Operating system: Windows

**Comment by DNin01** [comment]
Does this have anything to do with other addons?

**Comment by Scythn** [comment]
> Does this have anything to do with other addons, like maybe `scratchr2`?

Nope, I just got it with scratchr2 -> scratch-www off on Firefox, also got it on Vivaldi a few seconds ago but refreshed too quick.
![ff](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/ad261c0b-d717-4773-94a6-82c085c495b6)
Only had the compact user navbar setting on for this, I disabled everything else.

**Comment by mybearworld** [comment]
> before finishing to load MyStuff though, you can get this really briefly,

That's to be expected for userscripts. I didn't get it for scratchr2 yet, but it's also really Heisenbuggy.

**Comment by Scythn** [comment]
> That's to be expected for userscripts. 

Yeah I forgot, apologies.

>I didn't get it for scratchr2 yet, but it's also really Heisenbuggy.

Well, you do appear to have scratchr2 --> scratch-www on judging by the screenshots given in the OP. <sub>Since the MyStuff page is a scratchr2 page</sub>

**Comment by mybearworld** [comment]
> Well, you do appear to have scratchr2 --> scratch-www on judging by the screenshots given in the OP. Since the MyStuff page is a scratchr2 page

I do, but I did test it without `scratchr2` a couple of times. I wanted to create this issue a while ago, but it's really hard to reproduce for some reason

**Comment by DNin01** [comment]
And it's only on the My Stuff page, or is it on any scratchr2 page?

**Comment by mybearworld** [comment]
Are you sure you had that setting on in your screenshot? The padding seems there, there. Do you still have that tab open? If so, is there an error in your console?

---

This is very likely a race condition, but the code uses addon.tab.waitForElement...

**Comment by WorldLanguages** [comment]
> This is very likely a race condition, but the code uses addon.tab.waitForElement...

Well, it seems `container` is waited until it exists, but line 17 of r2.js expects descendants of that element to exist, which may not always be the case.

**Comment by mxmou** [comment]
I can reproduce this consistently using Ctrl+Shift+R.
