### ISSUE TITLE
Specify a version for Prettier

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6882]
### Why this would be helpful

Our ["Format code with Prettier" workflow](https://github.com/ScratchAddons/ScratchAddons/blob/3a342fa4a27cc79f138df666a03d72b4a548a5ec/.github/workflows/format-code.yml) automatically checks the formatting of all the code in a branch when it is updated. On forks with actions enabled, any inconsistencies are corrected and committed automatically.

That's super useful to make sure the code that contributors are proposing is consistent with Prettier's unified style, but it isn't all that fun when the style changes and causes files that were consistent style-wise before to be modified with no forewarning, even ones that weren't touched by the pull request author. Take a moment to imagine hundreds of unrelated files being modified by Prettier automatically the moment you push commits to your pull request. Wouldn't you be mystified? I sure was when [that happened to me](https://github.com/ScratchAddons/ScratchAddons/pull/6259#commits-pushed-75ded5d).

In some cases, pull request authors have to wait until we fix the problem (I believe it's because our [branch protection rules](https://github.com/ScratchAddons/ScratchAddons/settings/branches) don't allow our action to push to our `master` branch, but I don't know for sure) and then merge `master` from upstream into their branch to fix the problem.

I have seen an instance of this not [one](https://github.com/ScratchAddons/ScratchAddons/pull/6362) but [two](https://github.com/ScratchAddons/ScratchAddons/pull/6868) times.

### My suggestion

To help us control these problems, we might want to specify a version of Prettier to use. This would prevent updates from causing all these headaches, though we might still want to update it from time to time. The nice thing about that is we might be able to inform contributors about the changes so they're not confused when this happens.

**Comment by WorldLanguages** [comment]
I'm all for pinning the version + no automatic commits.

**Comment by DNin01** [comment]
> + no automatic commits

Hey, wait a minute, if we set a specific version to use and then update it later, contributors **won't have the code formatting change on them until they merge `upstream/master` into their branches**, because the workflow files on their branches will still have the old version. Is that enough to keep having the workflow trigger automatically?

**Comment by DNin01** [comment]
Yup, I am correct.
![Commit history listing page with Format code and Set Prettier version to 3 0 0 (for testing) commits](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/93315e2c-7201-4be4-8a8c-74aa47ca45c0)

**Comment by DNin01** [comment]
I was able to make it so that:
- The workflow runs automatically as usual on the source repository and as a status check in its pull requests.
- The workflow runs only on dispatch on forks. If it is triggered for another reason, the job is skipped (no steps are run).

[Here's how I did it.](https://github.com/ScratchAddons/ScratchAddons/compare/master...DNin01:ScratchAddons:format-code-on-dispatch#diff-b84b7047a336e29b9cef6d718895a7e9d0a403bf6474da65a7af7906d497ef07) Not sure if there's another better way.

I'll open a pull request for that if you'd still like it to work this way after what I said.

**Comment by DNin01** [comment]
So how does that sound, @WorldLanguages? Does not having to disable automatic format commits after all sound like a plan, based on what I've said since your last comment?

Also, #6897 is waiting on your approval.

**Comment by WorldLanguages** [comment]
> That mitigates the automatic committing problem, which means we probably don't have to make it manual after all. How's that?

I was thinking, even if there's no update by Prettier, auto commits can be annoying if you forget to pull, as you may get into conflicts on the lines Prettier changed. Of course you can force push afterwards but it's not ideal.

**Comment by DNin01** [comment]
> > That mitigates the automatic committing problem, which means we probably don't have to make it manual after all. How's that?
> 
> I was thinking, even if there's no update by Prettier, auto commits can be annoying if you forget to pull, as you may get into conflicts on the lines Prettier changed. Of course you can force push afterwards but it's not ideal.

I realize also, people can always manually disable the workflow via the web interface if they don't want it.

**Comment by DNin01** [comment]
![Disable workflow button under context menu in Actions tab](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/8e54351b-8e0e-4db8-ae26-7dff278c55d6)

**Comment by WorldLanguages** [comment]
Is there a way to make it optin instead of optout?

**Comment by DNin01** [comment]
> Is there a way to make it optin instead of optout?

By default, forks have Actions turned off, so technically all of the workflows are already opt-in, though if you just want specific workflows to run, you have to enable Actions and then disable the workflows you don't want.
