### ISSUE TITLE
Small Footer is broken on Annual Report Page

### ISSUE THREAD

**Issue by wgyt735yt** [ScratchAddons/ScratchAddons#689]
**Describe the bug**

On https://scratch.mit.edu/annual-report the small footer appears broken on the top of the page.

**To Reproduce**

1. Enable the addon that changes the footer. (I forgot)
2. Go to https://scratch.mit.edu/annual-report
3. See a misplaced footer.

**Expected behavior**

The footer should be slightly visible at the bottom of the page.

**Screenshots**

![image](https://user-images.githubusercontent.com/68466727/98543073-ebe7b300-225f-11eb-8960-55bb0fee760f.png)

**Device (please complete the following information):**

- OS: Windows 10 Enterprise 20H2 64 Bit
- Browser Firefox 82.0.2 64 Bit
- SA Version 1.3.1

**Additional context**

This was something that I found using stock SA without any modifications.

**Comment by WorldLanguages** [comment]
What addon causes this?

**Comment by lisa-wolfgang** [comment]
This happens with the "Infinite scrolling" addon when the "Fix Footer" option is selected.

**Comment by wgyt735yt** [comment]
> 
> 
> This happens with the "Infinite scrolling" addon when the "Fix Footer" option is selected.

@WorldLanguages ^^^
