### ISSUE TITLE
[New addon] Allow full screen on Youtube by mxmou

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#69]
**Describe the new addon**

Enables the full screen button in Scratch's YouTube video player

**Link to the new addon**

https://github.com/mxmou/customize-scratch#watch-youtube-videos-on-scratch-in-full-screen

Should be disabled by default because it slows down the experience a bit (and I don't think we have a way for userscripts to run on `document_start` yet, unfortunately)

**Comment by mxmou** [comment]
If I understand correctly userscripts can run on `DOMContentLoaded` now, so I will try to make a PR for this.
