### ISSUE TITLE
Notifacations don't work

### ISSUE THREAD

**Issue by MasimbaTheHuman** [ScratchAddons/ScratchAddons#691]
I don't receive notifications on windows 10.

well, I allowed notifacations.

- OS: [Windows 10]
- Browser [chrome]
- Version [1.3.1]

**Comment by TheColaber** [comment]
Yeah, I don't either... but when I enabled the sound option in the settings, our sound worked.

**Comment by WorldLanguages** [comment]
Notifications work for me normally in Chrome.

**Comment by j5155** [comment]
Notifications also work normally for me with chrome
