### ISSUE TITLE
Remove the "redirect to standard forums" addon (&/or inclusions of the mobile forums in addons)

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#6910]
### Why this would be helpful

The mobile forums were removed (and even asked about in the forums) after the 4-5 day long maintenance lap, the addon is basically useless now since [any attempt to go to the mobile forums now gives you a 404](scratch.mit.edu/discuss/m/).

### My suggestion

Just remove the addon since it has no use anymore, although it might be best to ask contact-us before doing so incase it was only removed temporarily for whatever reason that exists.
EDIT:
> Reminder: I think one or more addons try to run on the mobile forums, that no longer exist

Since heavily related I think I can still edit and include this, however if not just let me know, but either way removing them if the removal of the mobile forums isn't temporary (kinda weird of the mobile forums did get removed only temporarily) could probably optimize a bit since they basically run on nothingness (eg. necropost highlighter is just gonna uselessly run on /m/* (disincluding the mobile page), however it has nothing to highlight anymore unless I'm also reading the code wrong lol)
### Possible alternatives

1. Move it to konami code (though that'd be an odd choice)
2. Wait and see if it's only a temporary removal (best guess would be asking contact-us, though I doubt this is temporal)
3. Add a note to addons including it that it no longer functions and may be deleted sometime soon (basically the same as 2 but with adding a note to all the addons that also run on the mobile forums)

### Additional context

https://scratch.mit.edu/discuss/topic/726596/ ("Were the mobile forums supposed to be removed?")
![mobile leads to 404](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/24b34fa7-91a9-47f3-b5ff-7f32b2bab1c6)

**Comment by WorldLanguages** [comment]
Reminder: I think one or more addons try to run on the mobile forums, that no longer exist

**Comment by CST1229** [comment]
It might still be of use for the few old mobile forums links that exist (mainly search results, though those will eventually disappear).

**Comment by DNin01** [comment]
There is a small chance that they might come back soon, but my guess is they are gone. Wait a few weeks, perhaps?

**Comment by Samq64** [comment]
> It might still be of use for the few old mobile forums links that exist (mainly search results, though those will eventually disappear).

Unless Srctach setups its own redirect I would say the addon is more useful now and could even be enabled by default since it just fixes broken links.

**Comment by Secret-chest** [comment]
We can extend it to redirect `alpha.` and `beta.` links to the main domain, as well as `wiki.` links to the corresponding page.

**Comment by WorldLanguages** [comment]
> We can extend it to redirect `alpha.` and `beta.` links to the main domain, as well as `wiki.` links to the corresponding page.

We cannot, as the extension doesn't have host permissions for those subdomains.

**Comment by DNin01** [comment]
> > We can extend it to redirect `alpha.` and `beta.` links to the main domain, as well as `wiki.` links to the corresponding page.
> 
> 
> 
> We cannot, as the extension doesn't have host permissions for those subdomains.

They could be added as optional host permissions, though.
