### ISSUE TITLE
`forum-time-zones` no longer works

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#6911]
### Description

`forum-time-zones` doesn't work.

### Steps to reproduce

1. Enable `forum-time-zones`
2. Go to a post

### Demonstration(s) and additional context

This is because the mobile forums, which was used by the addon, no longer exist. To fix this, the way the addon works has to be changed.

### Environment

Browser: Edge 119
Scratch Addons version: 1.35.1
Operating system: Windows

**Comment by ajskateboarder** [comment]
Did this addon parse HTML from the mobile forums simply because there was less HTML to parse, or is there some other reason?

**Comment by CST1229** [comment]
> Did this addon parse HTML from the mobile forums simply because there was less HTML to parse, or was there some other reason?

I think the mobile forums always uses the local time zone.

**Comment by ajskateboarder** [comment]
> > Did this addon parse HTML from the mobile forums simply because there was less HTML to parse, or was there some other reason?
> 
> It was definitely not just because "there was less HTML to parse".

Okay, but to be fair, there's like half as much HTML on mobile pages than plain forum pages (probably due to lack of posting/subscribing features on the same page), and the DOMParser can be a bit slow with larger HTML. So you know ¯\\\_(ツ)\_/¯

**Comment by Samq64** [comment]
`addon.auth.scratchLang` seems to be returning null. This might not be new though. (See https://github.com/ScratchAddons/ScratchAddons/pull/4391#discussion_r1257303256)

**Comment by Samq64** [comment]
The addon seems to work as intended for me when logged in.

**Comment by WorldLanguages** [comment]
> The addon seems to work as intended for me when logged in.

Right, I think the forums engine *tries* to use the local timezone when logged in, but it fails to do so...?

**Comment by WorldLanguages** [comment]
> We should check an open PR that proposes changes to this addon

PR #4391 continues to use the mobile forums as the data source, so nothing interesting there.

Any other updates on this?
