### ISSUE TITLE
`forum-cooldown` addon (occasionally) doesn't display cooldown

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#6914]
### Description
EDIT: Originally I thought this was because of the mobile forums being removed, however it appears I was wrong as it only occasionally doesn't occur. Apologies for not testing thrice instead of twice.

The forum cooldown display addon occasionally does not display cooldown.

### Steps to reproduce

1. Enable the addon
2. Post something (Reccomended to do this in the official scratchblocks testing topic)
3. Try to instantly post something else, you'll get the small note but the cooldown will not display itself.

### Demonstration(s) and additional context

None ((for now))

### Environment

Browser: Firefox/FF 120.0 32 bit
Scratch Addons version: v1.35.1 (stable/public)
Operating system: Windows 10

**Comment by Secret-chest** [comment]
Still works for me, but not all the time.

**Comment by OneShot-Niko** [comment]
Trying to replicate this and just can't anymore

This might've been just an addon conflict that got resolved but I honestly have no idea since I just cannot replicate this anymore, so i'll just close
