### ISSUE TITLE
4K render

### ISSUE THREAD

**Issue by MasimbaTheHuman** [ScratchAddons/ScratchAddons#692]
An addon that applies a 4K render to the scratch website, including the site, projects, forums, editor, etc.

**Comment by JeffaloBob** [comment]
a.. what?

**Comment by MasimbaTheHuman** [comment]
> a.. what?

A 4K quality render of scratch.

**Comment by WorldLanguages** [comment]
You can achieve this by setting your OS' resolution to 4K.

**Comment by MasimbaTheHuman** [comment]
> You can achieve this by setting your OS' resolution to 4K.

How do I do that on ChromeOS
