### ISSUE TITLE
`ctrl-enter-to-post` does not work when creating a new topic

### ISSUE THREAD

**Issue by Zydrolic** [ScratchAddons/ScratchAddons#6925]
### Description

Unsure if it really counts as a bug, could be said as a suggestion, however due to the wording of the addon I kinda doubt it's intentional.
# Tested on:
Firefox 120.0.1 (32 bit)
Vivaldi 6.4.3160.47 (stable channel) (32 bit)
LibreWolf 120.0-2 
(I don't know why I tested with LibreWolf since it's a Firefox fork but I wanted to anyways)

### Steps to reproduce

1. Enable the ctrl+enter to post addon (make sure to have "enable on forums" turned ON)
2. Make a new topic (any subforum)
3. Try using CTRL+ENTER to create the topic (It shouldn't work)

### Demonstration(s) and additional context

No response

### Environment

Browser: FF/Firefox 120.0.1 (32 bit)
Scratch Addons version: v1.35.1 (stable/public)
Operating system: Windows 10

**Comment by Chiroyce1** [comment]
Good catch! The path is `/discuss/{id}/topic/add/` but the addon only checks matches for `/discuss/topic/*`
https://github.com/ScratchAddons/ScratchAddons/blob/229cde320fd79f3b03268e1e094f1ada79f4471f/addons/ctrl-enter-post/addon.json#L35-L40
