### ISSUE TITLE
Code Debugger

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#693]
**Describe the new addon**

Basically debugs your code.
Features in mind:

- Option in right-click to debug a stack of blocks
  - Shows variables and parameters (for custom blocks) values
  - Shows what part of that code is currently running (has been done already)
- Adds a Console
  - Reports performance issues and tries to find areas that cause these bugs.
  - If it doesn't find any bugs, create checks on might be not working
  - sa-log(stuff) - to log data in the console

**Link to the new addon**
null

Oh yeah, and trust me, this addon would have major value.

**Comment by lisa-wolfgang** [comment]
Does anyone have suggestions for what, specifically, this addon would debug? @TheColaber already mentioned performance issues.
I would suggest, at least for performance suggestions, to put an indicator on the right side of the area above the block editor that shows the number of issues.
For tips on what might not be working, often a "bug" is just a quirk of the way Scratch works, so perhaps those quirks could be included in the debugger's report. This would be especially helpful when the debugger doesn't find any "bugs".

**Comment by TheColaber** [comment]
@lisa-wolfgang Thanks! ^Updated^

**Comment by j5155** [comment]
This would be nice, maybe also with a "step through" setting, that, say, inserts invisible "SA_Pause" blocks between every other block? Used in combination with highlight current block, it would be amazing for debugging programs.

**Comment by YOYITsM3M8** [comment]
> This would be nice, maybe also with a "step through" setting, that, say, inserts invisible "SA_Pause" blocks between every other block? Used in combination with highlight current block, it would be amazing for debugging programs.

we dont want to do invisible blocks because those mess with the json and could corrupt the project

**Comment by j5155** [comment]
> > This would be nice, maybe also with a "step through" setting, that, say, inserts invisible "SA_Pause" blocks between every other block? Used in combination with highlight current block, it would be amazing for debugging programs.
> 
> we dont want to do invisible blocks because those mess with the json and could corrupt the project

it was basically an analogy, also the project should not save with the debug mode enabled
you could also just do whatever the SA pause block does every frame or something

**Comment by jeffalo** [comment]
just make sure it's compatible/works well with the pause button addon. perhaps they should be merged if pausing is useful for your debugger.

**Comment by mxmou** [comment]
> just make sure it's compatible/works well with the pause button addon. perhaps they should be merged if pausing is useful for your debugger.

I think making these two a single addon would be a good idea.

**Comment by TheColaber** [comment]
> just make sure it's compatible/works well with the pause button addon. perhaps they should be merged if pausing is useful for your debugger.

We thought about making an API for addons to add blocks, ONLY if it is still playable when scratch addons is disabled and when disabled, the blocks would show as custom blocks. Merging is a good idea though.
