### ISSUE TITLE
I found a way to fix the image uploading thing!

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#6933]
As we all know, `assets.scratch.mit.edu/get_image/` is censored. However, by substituting that with `assets.scratch.mit.edu/scratchr2/static/.%2E/` it allows posting. The part after that is the same as the old method.

https://scratch.mit.edu/discuss/topic/726810/?page=2#post-7680645 for example

**Comment by WorldLanguages** [comment]
Might be easier to continue with the "percent symbol" URL encoding trick, instead of changing the route which might possibly break in the future.

**Comment by WorldLanguages** [comment]
> Let's not work around the filter or we'll create even more problems.

The workaround for the filter was always used, and it was a better option than creating one project per each image that was uploaded.

**Comment by DNin01** [comment]
> > Let's not work around the filter or we'll create even more problems.
> 
> The workaround for the filter was always used, and it was a better option than creating one project per each image that was uploaded.

A different workaround? I know there's something about `.%2E` - I remember having to use that to get the forums to accept some image without even realizing it was a bypass (I've never used assets.scratch.mit.edu as an image host).

I mean, I'm neutral on _that_ one - back before the recent changes, I don't think the Scratch Team really cared if we used this bypass, but now I'm not sure how serious the team is about us not using assets database links.

<sub>This is hard to explain</sub>

Remember, the Scratch Team reserves the right to take action against evasion of the filter, and we don't want that to happen. We mean no harm. Just saying.

**Comment by DNin01** [comment]
Of course, it could be that the team is fine with this but had to put a wall in place to prevent a different problem. @Chiroyce1 said [here](https://github.com/ScratchAddons/ScratchAddons/issues/6913#issuecomment-1847451312):
> They added it to the main site's filter first since it was a major risk of having a one click link that auto downloads any file, regardless of its format. When it was added to the forums, even though it isn't a clickable link, it still flags it. Instead of saying that it isn't a supported image host it says "unsuitable language" which doesn't seem like intentional behaviour.

**Comment by WorldLanguages** [comment]
I have seen no evidence to suggest they explicitly changed the filter to avoid usage of the "assets" subdomain for images - it seems to be a side-effect of another, unrelated decision.
