### ISSUE TITLE
Settings -> Color mode -> "addon settings" (on hover) lights up "Color mode" (minimal graphical error)

### ISSUE THREAD

**Issue by ghost** [ScratchAddons/ScratchAddons#6935]
### Description

A really small graphical error, unsure if it's caused by how the customizable website/editor's dropdown works.
Probably not even needed to fix or just insanely low priority since I highly doubt it's really noticable if you are really hovering over the button to go to addon settings.

### Steps to reproduce

1. enable customizable editor theme
3. change anything (not needed I think)
4. go into the editor
5. click settings
6. click color mode
7. hover over "addon settings"
8. "Color Mode" should also light up

### Demonstration(s) and additional context

![demonstration](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/03603be0-8787-4ca9-8b76-4868094b454a)
("Addon Settings" is being hovered over here, I'll probably replace with a better screenshot later on)
### Environment

Browser: FF/Firefox 120.0.1 (32 bit)
Scratch Addons version: v1.35.1
Operating system: Windows 10
<sub>EDIT: I forgot to mention firefox</sub>

**Comment by Samq64** [comment]
The color mode menu being highlighted isn't a bug, but editor dark mode does cause this one when not hovering over any menu items:
[Screencast_20231206_144436.webm](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/bbe5cbc8-1410-4419-bbc3-86c479909382)

**Comment by DNin01** [comment]
I get it, so when you hover over "Addon Settings", it also causes "Color Mode" to become highlighted as if it was being hovered as well. Is that right?

I'm not sure if this is just an indicator that the dropdown is open, though. Will have to try myself.

**Comment by DNin01** [comment]
Looks intentional, then.

As you can see, when I open the dropdown for Color Mode, the dropdown button is highlighted, and it stops being highlighted when the dropdown is no longer open.

https://github.com/ScratchAddons/ScratchAddons/assets/106490990/d9eff8ab-fb34-4869-b2fa-d7097eb27d83

The behavior is the same whether the `editor-theme3` addon is active or not.

**Comment by DNin01** [comment]
It's also not even necessary to hover over "Addon Settings" for this to happen - the dropdown just has to be open.
