### ISSUE TITLE
Editor menu items don't stay highlighed with dark mode

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6936]
> The color mode menu being highlighted isn't a bug, but editor dark mode does cause the highlight to disappear when when not hovering over any menu items.
![bug.webm](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/57e3a65a-99c8-47ba-a30c-8c95c80572ac)

_Originally posted by @Samq64 in https://github.com/ScratchAddons/ScratchAddons/issues/6935#issuecomment-1843594879_

**Comment by WorldLanguages** [comment]
Interesting catch

**Comment by WorldLanguages** [comment]
Addon ID search keyword: dark-www / Editor dark mode and customizable colors
