### ISSUE TITLE
ocular integration: option to use ocular-rewritten instead of ocular

### ISSUE THREAD

**Issue by Zydrolic** [ScratchAddons/ScratchAddons#6943]
### Why this would be helpful

<sub>Sent this in feedback but realized I should probably make an issue instead as it's faster</sub>
[Rewritten](ocular-rewritten.jeffalo.net) usually loads a lot faster than [(normal) ocular](ocular.jeffalo.net) does, especially if there's blockspam, atleast by even a few seconds (eg. [rewritten](https://ocular-rewritten.jeffalo.net/post/7470503) - [ocular](https://ocular.jeffalo.net/post/7470503))

### My suggestion

Add an option to use rewritten (on posts) instead of ocular

### Possible alternatives

1. Just migrate the addon from normal ocular to rewritten, rewritten has an option to view posts on normal ocular anyway so an extra click isn't that big of a deal
2. Don't implement

### Additional context
(Changed title & desc on github mobile, will edit this later)
![inspect mock-up v2](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/39626f6d-11b7-49f3-bb20-e3b8591b5ee3)
Could be set to rewritten or (normal) ocular by default.

**Comment by Samq64** [comment]
Are the APIs compatible with each other? Also the rewritten branch seems to have been last updated more than a year ago but mater was updated last week. Is the site built straight from master?

**Comment by iqnite** [comment]
ocular rewritten seems to be in a Beta phase, as the site still has some bugs. Also, the current ocular is not "legacy", it's production. I think we should wait until ocular rewritten gets the official version.

**Comment by iqnite** [comment]
I'm no maintainer, and the issue will be good to consider in the future. Leave it open for now.

**Comment by iqnite** [comment]
ocular itself might get replaced with the rewritten version at some point in the future, with no need for Scratch Addons to add anything.

**Comment by WorldLanguages** [comment]
Hopefully you can set up your own redirect by using a general-purpose extension. This only affects the "view on ocular" link, right?

**Comment by jeffalo** [comment]
rewritten was an experimental rewrite of ocular. If I have time to bring it to match the main site's feature set, it would replace ocular.jeffalo.net.
