### ISSUE TITLE
`horizontal-mystuff-tabs` does not load on /mystuff/*/

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#6945]
### Description

This is a pretty minor bug since I doubt anyone would accidentally add something after mystuff, unless they forgot how the sections are sorted in URLs, possibly.
### What should happen
adding anything after my stuff and going to that URL should still run the addon like normal, or redirect back, etc. Other things in alternatives (Demonstration/s & additional context)
### What actually happens
The addon never loads and leaves you with the normal layout.

### Steps to reproduce

1. enable `horizontal-mystuff-tabs` (if you haven't already)
2. go to MyStuff
3. add literally anything after it, [for example this](https://scratch.mit.edu/mystuff/bugreportexampleforSA/).

### Demonstration(s) and additional context

![firefox demonstration](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/213e409e-55f3-45ba-8b5c-357761fcf44f)
This does work on v1.35.1; However I think this is still enough, if not I'll gladly add a screenshot of this in an edit.
### Alternative fix ideas
1. Redirect the user to /mystuff/ instead
2. Attempt to force-run the addon

### Environment

Browser: Firefox 120.0.1 (32 bit) & Vivaldi 6.4.3160.47 (Stable channel) (32 bit) (Chromium) 
Scratch Addons version: v1.36.0-pre (since commit 66d5782, unsure how to get the version hash lol, my apologies) - Works on v1.35.1 as well however, tested on both
Operating system: Windows 10, 32 bit.

**Comment by DNin01** [comment]
Does Scratch ever direct users to such URLs or is this only something that you have to be _trying_ to reproduce?

I know there are the shared, unshared, studios, and trash tabs but the `#` component of the URL doesn't seem to affect this behavior.

**Comment by WorldLanguages** [comment]
Pretty crazy this works: https://scratch.mit.edu/mystuff/a/b/c/d/e/f

Scratch probably messed up its routes configuration

**Comment by DNin01** [comment]
> Never directs to any of such URLs (to my knowledge).
>
> Though now that I think hard it might not be required to even report this whatsoever all that much considering the chances of someone manually editing the URL to go to mystuff or a specific section is really low.

Yeah, probably not worth our time to fix - it's not a serious bug.

**Comment by BroJac5246** [comment]
I know it probably doesn't matter but how hard is it to actually fix this? Would it just require us to change the URL that the addon runs on or would it require major changes?

**Comment by Samq64** [comment]
> or if perhaps just a wildcard after mystuff/

Yeah in regex `*` also match's nothing. Feel free to submit a PR.

**Comment by BroJac5246** [comment]
> > or if perhaps just a wildcard after mystuff/
> 
> Yeah in regex `*` also matches nothing. Feel free to submit a PR.

That's what I was getting at; glad to see it works.
