### ISSUE TITLE
`README.md`: "content user scripts" URL leads to a 404

### ISSUE THREAD

**Issue by Zydrolic** [ScratchAddons/ScratchAddons#6946]
Resolved by #6947
### Description

The URL in the README.md leading to the chrome docs doesn't appear to exist anymore.
I think I should make an issue for this before opening the PR which replaces this with (hopefully) the new url.

### Steps to reproduce

1. go to readme.md
2. try viewing the URL of "extension content scripts", it's a 404.

### Demonstration(s) and additional context

[This is the old URL](https://developer.chrome.com/docs/extensions/content_scripts/).

### Environment

Browser: Occurs on any, this is to do with the readme.md file of the repo
Scratch Addons version: above
Operating system: above

**Comment by Samq64** [comment]
Submitting an issue isn't really necessary for bugs that you plan on fixing yourself.

**Comment by Hans5958** [comment]
> Submitting an issue isn't really necessary for bugs that you plan on fixing yourself.

Eh, it's not a big of a deal. It's better to create issues so we don't waste anyone's work by working something rejected.
