### ISSUE TITLE
`better-quoter`: escaping BBCode always happens while viewing BBCode with `show-bbcode` in pre-release

### ISSUE THREAD

**Issue by Zydrolic** [ScratchAddons/ScratchAddons#6948]
### Description
Unsure if I should use /feedback or just make an issue on pre-release issues (especially since the PR that added this is merged, so I think it'd be odd if I reported the bug there)
### What should happen
Quotes post like normal (BBCode included)
### What actually happens
Adds un-needed double that prevents the BBCode from properly registering ([]).

### Steps to reproduce

1. Enable `better-quoter` & `show-bbcode`
2. Go to any post in the scratchblocks testing topic
3. View bbcode
4. Highlight from start to finish and try quoting.
5. See issue (hopefully)

### Demonstration(s) and additional context

used in example: https://scratch.mit.edu/discuss/post/7631503/
![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/4bd2e7d0-475f-496d-ab9d-7de2042ffc91)

### Environment

Browser: Firefox 12.0.1 (32 bit)
Scratch Addons version:  v1.36.0-pre (using commit 66d5782 's version which was just a transifex update (EDIT: nevermind thank you to DNin01 I forgot that's the commit hash which I'm supposed to give lol)
Operating system: Windows 10 (32 bit)

**Comment by WorldLanguages** [comment]
So you believe this was regressed by #6816?

**Comment by DNin01** [comment]
I think this behavior is intentional? By quoting the BBCode source, you would be trying to quote the raw BBCode as plain text.

**Comment by DNin01** [comment]
> using commit https://github.com/ScratchAddons/ScratchAddons/commit/66d578272b1a551f28db8dc0c7c50953869ec914 's version which was just a transifex update

That _is_ a commit hash, by the way.

**Comment by DNin01** [comment]
@mybearworld Was this intentional? Should it work this way? I mean, it kind of makes sense.

**Comment by DNin01** [comment]
This is different behavior from what happened before this change, though.

**Comment by mybearworld** [comment]
> @mybearworld Was this intentional? Should it work this way? I mean, it kind of makes sense.

I kind of doubt the interoperability of these two addons was intentional to begin with - it only worked because it just treated it as a regular post, and it didn't escape the brackets. Fixing that inevitably lead to this breaking.

However, I don't really think the behavior shown here makes sense - what is the use case for quoting BBCode? You may want to quote unescaped BBCode when you want to be precise with what exactly you quote - I think this addon should allow for that.

I didn't have this in mind with that fix.

**Comment by DNin01** [comment]
> However, I don't really think the behavior shown here makes sense - what is the use case for quoting BBCode? You may want to quote unescaped BBCode when you want to be precise with what exactly you quote - I think this addon should allow for that.

It might be as simple as not escaping the syntax when you click Quote while the post is in "view source" mode to fix the problem.

**Comment by pufferfish101007** [comment]
might be nice to have a setting for this

**Comment by mybearworld** [comment]
> might be nice to have a setting for this

Is there a use case for the current pre-release behavior?

**Comment by DNin01** [comment]
I think it wouldn't be a bad idea to patch this.

**Comment by WorldLanguages** [comment]
Sorry for going off-topic - @Zydrolic I suggest you create discussions (https://github.com/ScratchAddons/ScratchAddons/discussions) in this repository, instead of sending questions through scratchaddons.com/feedback
