### ISSUE TITLE
`better-featured-project`: increase height of bio

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#6953]
### Why this would be helpful

Currently, the bio itself displays roughly one line less than without this addon.
This is just a bit annoying knowing the fact that you have basically -1 linebreak from the addon for the nice banner layout.

### My suggestion

Increase the heights, "editable read" works at 125px (Though this is only visually, text still gets overshadowed), cannot find a matching value for readonly nor What I've Been Doing, I've tried to experiment around it.

### Possible alternatives

1. don't implement
2. Decrease the height of the project banner

### Additional context

![increased height](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/01217627-eebc-44af-80cf-97fb0640d31e)
(EDIT NOTE: I know the one in the example can be seen by just scrolling down)

**Comment by WorldLanguages** [comment]
I wonder if this was intentional. But if it's just one line that is cut off, it wouldn't make a big difference.
