### ISSUE TITLE
Private Studios

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#696]
**This might be a feature only Scratch MIT Media Lab will be able to add but I think it is worth considering**

Every time people want to collab on Scratch they are forced to make a studio which draws attention to unwanted watchers. Mostly collaborators on Scratch want to keep their code private until game release so I suggested that we have the ability to make studios private just like repositories!

**Comment by mxmou** [comment]
I don't think this is possible. Studios are always public, you can't change that.

**Comment by TheColaber** [comment]
I think a better suggestion would to be when you create a studio It would be private to everyone (so it doesn't look like you just created a blank studio) and you can choose to publish it to everyone. That way no one sees it privately and your studio would be ready when you want. Maybe we can have an HTML page that the user will be redirected to write out the studio info first and then have the option to share the studio which will then send to an API to fill out the studio info.

**Comment by apple502j** [comment]
This feature will be re-considred when pigs fly.
