### ISSUE TITLE
`my-ocular`: option to set status as profile colour

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6963]
### Why this would be helpful

People want to personalize their profiles more and a different pimary/navigation 
bar colour that others can see would be a great wag to do that.

### My suggestion

Adding an option to the Ocular addon to use the user's status colour as the primary colour when visiting their profile which will override `scratchr2` and `dark-www`.

### Possible alternatives

A new addon that looks for hex colour in the about me.

**Comment by mybearworld** [comment]
This would currently look like this for my profile:

**Comment by mybearworld** [comment]
Another thing - this would be changing the profile color of people who may not even know Scratch Addons exists, let alone this addon's option, and who therefore didn't consider this when setting their Ocular color - take [@Redtone1080](https://scratch.mit.edu/users/Redstone1080/)'s `#999999`, for example.

**Comment by WorldLanguages** [comment]
I would try to avoid these types of feature suggestions.
