### ISSUE TITLE
`better-quoter` & `show-bbcode`: post does not get quoted if source is being viewed

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#6964]
Tested PR that fixes this: #6965
### Description
Regressed by [`addons/show-bbcode/userscript.js` line 15](https://github.com/ScratchAddons/ScratchAddons/blob/79e693afdc790adc1b1f25f978d525a47753cc2a/addons/show-bbcode/userscript.js#L15)

Firstly, I wanna apologize for not testing this, I completely forgot to try this and just used highlight when testing the PR mybearworld had made, I completely forgot to try this way, unsure if I should comment on the PR since it's merged already, so I did both, technically.
### What should happen
Post gets quoted as if it was viewed normally
### What happens
Quote happens, but contents are empty.
This only happens if you simply press quote (`better-quoter` required) with `show-bbcode` on

### Steps to reproduce

1. enable `better-quoter` & `show-bbcode`
2. view source of any post
3. press the quote button, do not highlight anything.
4. The post's contents are empty.

### Demonstration(s) and additional context

![demonstration](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/53289d38-6df1-4ab3-aaa0-76bc64069241)

### Environment

Browser: Firefox 120.0.1 (32 bit)
Scratch Addons version: 79e693a (1.36.0-pre)
Operating system: Windows 10

**Comment by mybearworld** [comment]
Oh wow, so not only does a bug fix of mine have a regression, but also *the bug fix of that* has one! Truly wonderful.
