### ISSUE TITLE
Passing Variables and Lists Through Parameters

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#697]
**Function Parameter Addon**

When I started learning JavaScript I was amazed at how I could modify variables and lists by passing it through a parameter. It allows for more flexibility and complex algorithms. This is something that MakeCode was able to do... Can we do it?

**Comment by mxmou** [comment]
Variables local to custom blocks would be a great addition, but a Scratch mod would be needed for that.
