### ISSUE TITLE
editor-dark-mode: costume-editor action icons are incorrectly colored after changing zoom

### ISSUE THREAD

**Issue by Jazza-231** [ScratchAddons/ScratchAddons#6975]
### Description

In the costume editor, using editor-dark-mode you can set a colour for the buttons like move to front layer etc. When you zoom in enough, scratch moves these to a dropdown "more" menu, and they lose their custom colour both in that menu and when you zoom back out again.

### Steps to reproduce

1. Open costume editor
2. Zoom until the go to front/back layer buttons hide
3. Unzoom and see they are purple

(Make sure the icon colour is not set to purple, i chose TW red)

### Demonstration(s) and additional context

https://github.com/ScratchAddons/ScratchAddons/assets/81956724/69fb3a8f-2ad0-4155-86f3-1381ceeee303

I seems we dont handle dynamic elements very well in quite a few scenarios

also sorry for switching back to obs, i was a bit confused

### Environment

Browser: 
Scratch Addons version: 
Operating system:

**Comment by WorldLanguages** [comment]
Related bug fix: #6645

**Comment by mxmou** [comment]
This sounds similar to #6956.
