### ISSUE TITLE
Popup very zommed out on Firefox Android

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6976]
### Description

On Firefox for Android the popup is scaled incorrectly so everything is too small.

### Steps to reproduce

1. Install on Firefox for Android
2. Switch to portrait mode
3. Open Add-ons > Scratch Addons

### Demonstration(s) and additional context

![Screenshot_20231218-083418_Firefox](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/9589a76e-7462-42f6-8641-aaeafbd0f8b7)

### Environment

Browser: Firefox for Android 120
Scratch Addons version: 1.35.1
Operating system: Android 11
Screen: 8.0" (800x1260)

**Comment by BroJac5246** [comment]
> > > This is actually intended, I believe - It should be autoresizing.
> > 
> > I would like to know what size Firefox is telling Scratch Addons the screen is and also see if this changes is you change the DPI ("Minimum width") in Android Developer Options.
> 
> Since I haven't got SA on normal ff (I use nightly instead) I tried and it still occurs, though also with fullscreen being basically impossible to be usable.
> 
> Changed from 360 _DP_ (note: not a typo) to 500, it's still really small and fullscreen is still oversized.
> I'm assuming it's using predefined sizes from the popup styling? Could be wrong.

Hopefully there's a way for us to manually adjust it, then.
