### ISSUE TITLE
`animated-thumb` requires camera permission with Android Firefox

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6977]
### Description

The camera permission is required when selecting a file to use as thumbnail. This is probably a Firefox bug but I thought I'd report it here anyway.

### Steps to reproduce

1. Enable `animated-thumb`
2. Click set thumbnail on a project
3. Click select file

### Environment

Browser: Firefox for Android 120
Scratch Addons version: 1.35.1
Operating system: Android 11

**Comment by BroJac5246** [comment]
Is there an option to _choose_ whether to upload a picture or take a picture with the camera? That would explain it is that's the case. If not we might want to reach out to the Firefox team.

**Comment by Samq64** [comment]
> Is there an option to _choose_ whether to upload a picture or take a picture with the camera?

Yes, but only after the permission is granted.

**Comment by BroJac5246** [comment]
> > Is there an option to _choose_ whether to upload a picture or take a picture with the camera?
> 
> Yes, but only after the permission is granted.

Does it look like it's using Android's default popup or is it clearly created by Firefox? (Or you could share a screenshot)

**Comment by Samq64** [comment]
> Does it look like it's using Android's default popup or is it clearly created by Firefox? (Or you could share a screenshot)

Just the default one.
![Screenshot_20231218-163605_Android System](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/cfad4d19-f9c8-40eb-9883-d4d6f3ee2043)

**Comment by BOplaid** [comment]
> > > Does it look like it's using Android's default popup or is it clearly created by Firefox? (Or you could share a screenshot)
> > 
> > 
> > Just the default one. ![Screenshot_20231218-163605_Android System](https://private-user-images.githubusercontent.com/81489795/291414758-cfad4d19-f9c8-40eb-9883-d4d6f3ee2043.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwOTk1ODEsIm5iZiI6MTcwMzA5OTI4MSwicGF0aCI6Ii84MTQ4OTc5NS8yOTE0MTQ3NTgtY2ZhZDRkMTktZjljOC00MGViLTk4ODMtZDRkNmYzZWUyMDQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE5MDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYTQxZWE0ZGE2YmY3NzI2YWIzYzk5ZTFlNmYwYzQ0MWM5NDA0Y2JkNTE5YTdiZGUxZmM2MTFjNGEwMDVlMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K3NKuFlC9BeHNr0AXAuS4usWFTXIiBAQJfFzN6oJiJg)
> 
> As far as I'm sure, you are merely being given the option to use the camera, you are not being forced to use it. I'm assuming this is a default rather than forcing the files upload.

yea, i also think that thats the case.

**Comment by DNin01** [comment]
So Firefox is asking for permission to use the camera before you get the prompt to choose whether to import a file or take a picture?

**Comment by BroJac5246** [comment]
> > > Does it look like it's using Android's default popup or is it clearly created by Firefox? (Or you could share a screenshot)
> > 
> > Just the default one. ![Screenshot_20231218-163605_Android System](https://private-user-images.githubusercontent.com/81489795/291414758-cfad4d19-f9c8-40eb-9883-d4d6f3ee2043.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwOTk1ODEsIm5iZiI6MTcwMzA5OTI4MSwicGF0aCI6Ii84MTQ4OTc5NS8yOTE0MTQ3NTgtY2ZhZDRkMTktZjljOC00MGViLTk4ODMtZDRkNmYzZWUyMDQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE5MDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYTQxZWE0ZGE2YmY3NzI2YWIzYzk5ZTFlNmYwYzQ0MWM5NDA0Y2JkNTE5YTdiZGUxZmM2MTFjNGEwMDVlMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K3NKuFlC9BeHNr0AXAuS4usWFTXIiBAQJfFzN6oJiJg)
> 
> As far as I'm sure, you are merely being given the option to use the camera, you are not being forced to use it.
> I'm assuming this is a default rather than forcing the files upload.

It's possible that Android requires that permission in order to show the popup, though I don't have time to test that.

**Comment by BroJac5246** [comment]
> So Firefox is asking for permission to use the camera before you get the prompt to choose whether to import a file or take a picture?

Yes.

**Comment by Samq64** [comment]
> So Firefox is asking for permission to use the camera before you get the prompt to choose whether to import a file or take a picture?

Yes, it's an upstream issue.

**Comment by WorldLanguages** [comment]
If the HTML spec doesn't contemplate this with some attribute for \<input> elements, we probably can't do anything about this 🤔

**Comment by WorldLanguages** [comment]
A post I found on StackOverflow includes this snippet:

`<input type="file" accept="capture=camera,image/*" />`

Maybe removing "camera" and keeping only "image" would remove the camera option, but I'm not sure. Even if it does, there's a low possibility it will work in all browsers.

**Comment by mxmou** [comment]
> A post I found on StackOverflow includes this snippet:
> 
> `<input type="file" accept="capture=camera,image/*" />`
> 
> Maybe removing "camera" and keeping only "image" would remove the camera option, but I'm not sure. Even if it does, there's a low possibility it will work in all browsers.

The addon already sets the accept attribute to `image/*`: https://github.com/ScratchAddons/ScratchAddons/blob/f23b744/libraries/common/cs/thumb-setter.js#L21

`capture=camera` isn't one of the [valid values](https://html.spec.whatwg.org/multipage/input.html#attr-input-accept). It's probably a non-standard extension.

**Comment by Samq64** [comment]
Closing as an upstream issue
