### ISSUE TITLE
PFP Renderer

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#698]
**Get A Scratch Users Profile Pic To Add Flavour To Your Projects**

I have absolutely no idea how -greencat- achieved this but it is an amazing addon to quality projects. It somehow fetches user profile pictures by using JavaScript or by accessing a database. I think this will be a great addition to the editor like the set thumbnail button.

**Comment by mxmou** [comment]
-greencat-'s project uses cloud variables to communicate with an external server. I don't understand how this could be an addon.

**Comment by GrahamSH-LLK** [comment]
Yeah, this wouldn't be an addon.

**Comment by WorldLanguages** [comment]
@samuraininja360 In a small open source project like ours, a small amount of invalid issues really wastes our time. Please stop, or I'll have to block you permanently from creating new issues. This is not Scratch's suggestion forum.
