### ISSUE TITLE
Custom blocks are blurry while editing them

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#6986]
### Description

I'm still trying to find which addon causes this, it does not appear to be `transparent-orphans`, I've tried that addon.

(unsure how else I could show my settings)
<details><summary>Settings</summary>
<p>

`{"core":{"lightTheme":false,"version":"1.36.0-prerelease"},"addons":{"2d-color-picker":{"enabled":false,"settings":{}},"60fps":{"enabled":true,"settings":{"framerate":60}},"account-settings-capitalize":{"enabled":true,"settings":{}},"animated-thumb":{"enabled":true,"settings":{}},"auto-follow-topics":{"enabled":true,"settings":{}},"better-emojis":{"enabled":true,"settings":{}},"better-featured-project":{"enabled":true,"settings":{"blur":0}},"better-img-uploads":{"enabled":true,"settings":{"fitting":"fill"}},"better-quoter":{"enabled":true,"settings":{}},"bitmap-copy":{"enabled":true,"settings":{}},"block-cherry-picking":{"enabled":true,"settings":{"invertDrag":false}},"block-count":{"enabled":true,"settings":{}},"block-duplicate":{"enabled":true,"settings":{}},"block-palette-icons":{"enabled":true,"settings":{}},"block-switching":{"enabled":true,"settings":{"control":true,"customargs":true,"customargsmode":"defOnly","data":true,"event":true,"extension":true,"looks":true,"motion":true,"noop":false,"operator":true,"sa":true,"sensing":true,"sound":true}},"blocks2image":{"enabled":true,"settings":{}},"cat-blocks":{"enabled":true,"settings":{"watch":false}},"clones":{"enabled":true,"settings":{"projectpage":true,"showicononly":false}},"cloud-games":{"enabled":false,"settings":{"displayedGames":[{"url":"https://scratch.mit.edu/studios/539952/"},{"url":"https://scratch.mit.edu/projects/720258286"}]}},"collapse-footer":{"enabled":true,"settings":{"infiniteScroll":false,"speed":"short"}},"color-inputs":{"enabled":true,"settings":{}},"color-picker":{"enabled":true,"settings":{}},"colorblind":{"enabled":true,"settings":{"bold":"all","underline-style":"none"}},"columns":{"enabled":false,"settings":{}},"comments-linebreaks":{"enabled":true,"settings":{"height":20,"scrollbars":true}},"compact-messages":{"enabled":true,"settings":{"comment_padding":10,"hide_icons":true,"message_padding":5,"no_borders":false}},"confirm-actions":{"enabled":true,"settings":{"cancelcomment":true,"closingtopic":true,"followinguser":true,"joiningstudio":true,"projectsharing":true,"projectunsharing":true,"removingprojects":true}},"copy-message-link":{"enabled":true,"settings":{}},"copy-reporter":{"enabled":true,"settings":{}},"ctrl-click-run-scripts":{"enabled":true,"settings":{}},"ctrl-enter-post":{"enabled":true,"settings":{"comments":true,"forums":true}},"curator-link":{"enabled":true,"settings":{"styleAsNormalText":false}},"custom-block-shape":{"enabled":false,"settings":{"cornerSize":100,"notchSize":100,"paddingSize":100}},"custom-block-text":{"enabled":true,"settings":{"bold":true,"shadow":true,"size":100}},"custom-menu-bar":{"enabled":false,"settings":{"compact-username":false,"hide-tutorials-button":false,"menu-labels":"both","my-stuff":false}},"custom-zoom":{"enabled":true,"settings":{"autohide":true,"maxZoom":500,"minZoom":1,"speed":"none","startZoom":68,"zoomSpeed":200}},"customize-avatar-border":{"enabled":true,"settings":{"fill-transparent":true,"hide-outline":false,"outline-color":"#ff0000ff"}},"dango-rain":{"enabled":true,"settings":{}},"dark-www":{"enabled":true,"settings":{"_version":7,"blue":"#590790ff","border":"#a30000ff","box":"#000000ff","button":"#ff1c1cff","darkBanners":"darker","darkForumCode":true,"footer":"#390505ff","gray":"#000000ff","input":"#000000ff","link":"#295285ff","messageIndicatorColor":"#650000ff","messageIndicatorOnMessagesPage":"#7c0000ff","navbar":"#360202ff","page":"#000000ff"}},"data-category-tweaks-v2":{"enabled":true,"settings":{"moveReportersDown":false,"separateListCategory":true,"separateLocalVariables":true}},"debugger":{"enabled":true,"settings":{"fancy_graphs":false,"log_broadcasts":true,"log_clear_greenflag":true,"log_clone_create":true,"log_failed_clone_creation":true,"log_greenflag":false,"log_invalid_cloud_data":false,"log_max_list_length":false}},"default-costume-editor-color":{"enabled":true,"settings":{"fill":"#ff0000ff","persistence":true,"stroke":"#000000","strokeSize":7}},"default-project":{"enabled":true,"settings":{"projectId":556445222}},"disable-auto-save":{"enabled":false,"settings":{}},"disable-paste-offset":{"enabled":true,"settings":{}},"disable-sprite-wobble":{"enabled":true,"settings":{"mode":"no-wobble"}},"disable-stage-drag-select":{"enabled":true,"settings":{"drag_while_stopped":true}},"discuss-button":{"enabled":true,"settings":{"compact-nav":true,"items":[{"name":"Forums","url":"/discuss"},{"name":"Wiki","url":"https://en.scratch-wiki.info/"},{"name":"Ocular","url":"https://ocular.jeffalo.net/"}],"stick":"screen"}},"drag-drop":{"enabled":true,"settings":{"use-hd-upload":true}},"echo-effect":{"enabled":true,"settings":{}},"editor-buttons-reverse-order":{"enabled":false,"settings":{}},"editor-colored-context-menus":{"enabled":true,"settings":{}},"editor-comment-previews":{"enabled":true,"settings":{"delay":"none","follow-mouse":true,"hover-view":true,"hover-view-block":true,"hover-view-procedure":true,"reduce-animation":true,"reduce-transparency":true}},"editor-compact":{"enabled":true,"settings":{"hideLabels":true}},"editor-dark-mode":{"enabled":true,"settings":{"_version":10,"accent":"#151515","activeTab":"#202020","affectPaper":true,"affectStage":false,"border":"#ffffff0d","categoryMenu":"#202020","dots":false,"fullscreen":"#000000","highlightText":"#ccb3ff","input":"#202020","menuBar":"#202020","page":"#111111","palette":"#202020cc","popup":"#000a","primary":"#ff0000ff","selector":"#202020","selector2":"#202020","selectorSelection":"#111111","stageHeader":"#000000","tab":"#151515","workspace":"#151515"}},"editor-devtools":{"enabled":true,"settings":{"enableCleanUpPlus":true,"enablePasteBlocksAtMouse":true}},"editor-extra-keys":{"enabled":true,"settings":{"experimentalKeys":false,"shiftKeys":true}},"editor-messages":{"enabled":true,"settings":{}},"editor-number-arrow-keys":{"enabled":true,"settings":{"alt":"tenth","altCustom":"0.1","regular":"one","regularCustom":"1","shift":"ten","shiftCustom":"10","useCustom":false}},"editor-random-direction-block":{"enabled":true,"settings":{}},"editor-searchable-dropdowns":{"enabled":true,"settings":{}},"editor-sounds":{"enabled":false,"settings":{}},"editor-square-inputs":{"enabled":false,"settings":{"color":true,"text":true}},"editor-stage-left":{"enabled":false,"settings":{}},"editor-stepping":{"enabled":true,"settings":{"highlight-color":"#ff0000ff"}},"editor-theme3":{"enabled":true,"settings":{"Pen-color":"#0FBD8C","_version":3,"comment-color":"#737106ff","control-color":"#FFBF00","custom-color":"#5f49d8","data-color":"#ff1a1aff","data-lists-color":"#ff661aff","events-color":"#DE9E2E","forums":false,"input-color":"#FFFFFF","looks-color":"#9966FF","motion-color":"#4C97FF","operators-color":"#59C059","sa-color":"#29BEB8","sensing-color":"#5CB1D6","sounds-color":"#CF63CF","text":"colorOnBlack"}},"editor-unshare-button":{"enabled":true,"settings":{}},"emoji-picker":{"enabled":true,"settings":{}},"exact-count":{"enabled":true,"settings":{"forumuser":true,"studio":true,"user":true}},"expanded-backpack":{"enabled":true,"settings":{"rows":3,"upscale":true}},"expanding-search-bar":{"enabled":true,"settings":{}},"faster-project-loading":{"enabled":true,"settings":{}},"feature-unshared":{"enabled":true,"settings":{}},"featured-dangos-v2":{"enabled":false,"settings":{}},"find-bar":{"enabled":true,"settings":{}},"fix-editor-comments":{"enabled":true,"settings":{"fix-drag":true,"leash":true,"scroll":true,"standalone-edit":true,"straighten":false}},"fix-pasted-scripts":{"enabled":true,"settings":{}},"fix-uploaded-svgs":{"enabled":true,"settings":{}},"folders":{"enabled":true,"settings":{}},"forum-copy-code":{"enabled":true,"settings":{}},"forum-id":{"enabled":true,"settings":{"auto_add":true}},"forum-live-preview":{"enabled":true,"settings":{"rate":"fast"}},"forum-post-countdown":{"enabled":true,"settings":{}},"forum-quote-code-beautifier":{"enabled":true,"settings":{"_version":1,"bordercolor":"#580909ff"}},"forum-search":{"enabled":true,"settings":{}},"forum-time-zones":{"enabled":true,"settings":{}},"forum-toolbar":{"enabled":true,"settings":{"center":true,"code":true,"color":true,"dictionary":true,"google":true,"wiki":true,"wp":true}},"full-signature":{"enabled":true,"settings":{"blocks":true,"signature":true,"whathappen":true,"whatworkingon":true}},"fullscreen":{"enabled":true,"settings":{"browserFullscreen":true,"hideToolbar":false}},"gamepad":{"enabled":false,"settings":{"hide":false}},"hi-res-thumbnails":{"enabled":false,"settings":{"multiplier":200}},"hide-delete-button":{"enabled":true,"settings":{"costumes":true,"sounds":true,"sprites":true}},"hide-flyout":{"enabled":true,"settings":{"speed":"none","toggle":"category"}},"hide-new-variables":{"enabled":true,"settings":{}},"hide-project-stats":{"enabled":true,"settings":{"comments":true,"favorites":false,"loves":false,"lovesFront":false,"myStuff":true,"remixes":true,"remixesFront":false,"showOwnStats":true,"studios":true,"views":false}},"hide-signatures":{"enabled":true,"settings":{"hide":true,"toggle":true}},"hide-stage":{"enabled":true,"settings":{}},"horizontal-mystuff-tabs":{"enabled":true,"settings":{}},"image-uploader":{"enabled":true,"settings":{}},"infinite-scroll":{"enabled":true,"settings":{"forumScroll":true,"messageScroll":true,"profileCommentScroll":false,"projectScroll":false,"searchExploreScroll":true,"studioActivityScroll":false,"studioBrowseProjectScroll":false,"studioCuratorScroll":true,"studioProjectScroll":true,"studioScroll":false}},"initialise-sprite-position":{"enabled":true,"settings":{"duplicate":"custom","library":false,"x":0,"y":0}},"items-per-row":{"enabled":true,"settings":{"projects":5,"search":4,"studioCurators":3,"studioProjects":3,"studios":8,"users":14}},"jump-to-def":{"enabled":true,"settings":{}},"last-edit-tooltip":{"enabled":true,"settings":{}},"live-featured-project":{"enabled":false,"settings":{"alternativePlayer":"none","autoPlay":false,"enableTWAddons":true,"shareUsername":true,"showMenu":true}},"load-extensions":{"enabled":false,"settings":{"music":true,"pen":true,"text2speech":false,"translate":false}},"longer-wiwo":{"enabled":true,"settings":{}},"material-forum-editor-buttons":{"enabled":true,"settings":{}},"mediarecorder":{"enabled":true,"settings":{}},"message-filters":{"enabled":true,"settings":{}},"middle-click-popup":{"enabled":true,"settings":{"popup_max_height":40,"popup_scale":48,"popup_width":16}},"more-links":{"enabled":true,"settings":{}},"mouse-pos":{"enabled":true,"settings":{}},"move-to-top-bottom":{"enabled":true,"settings":{}},"move-to-top-layer":{"enabled":true,"settings":{}},"msg-count-badge":{"enabled":true,"settings":{"color":"#6e2121ff","showOffline":true}},"mute-project":{"enabled":true,"settings":{}},"my-ocular":{"enabled":true,"settings":{"discuss":true,"profile":true,"reactions":true,"show-status":"everywhere"}},"name-backpack-items":{"enabled":true,"settings":{}},"necropost-highlighter":{"enabled":true,"settings":{"applyToBugsAndGlitches":true,"applyToHelpWithScripts":true,"applyToNewScratchers":true,"applyToOpenSourceProjects":false,"applyToProjectIdeas":true,"applyToQuestionsAboutScratch":true,"applyToRequests":false,"applyToSuggestions":false,"chooseCustomForums":false,"colorTopicCells":true,"monthCountConsideredOld":1}},"no-script-bumping":{"enabled":true,"settings":{}},"number-pad":{"enabled":true,"settings":{}},"old-studio-layout":{"enabled":true,"settings":{"version":"scratchr2"}},"one-click-studio-invites":{"enabled":true,"settings":{}},"onion-skinning":{"enabled":true,"settings":{"afterTint":"#0000FF","beforeTint":"#FF0000","default":false,"layering":"front","mode":"merge","next":0,"opacity":25,"opacityStep":10,"previous":1}},"op-badge":{"enabled":true,"settings":{}},"opacity-slider":{"enabled":true,"settings":{}},"paint-by-default":{"enabled":true,"settings":{"backdrop":"paint","costume":"paint","sound":"upload","sprite":"paint"}},"paint-skew":{"enabled":true,"settings":{}},"paint-snap":{"enabled":false,"settings":{"boxCenter":true,"boxCorners":false,"boxEdgeMids":false,"enable-default":true,"guide-color":"#ff0000","objectCenters":true,"objectCorners":false,"objectEdges":true,"objectMidlines":true,"pageAxes":true,"pageCenter":true,"pageCorners":false,"pageEdges":true,"threshold":10}},"pause":{"enabled":true,"settings":{}},"pick-colors-from-stage":{"enabled":true,"settings":{}},"preview-project-description":{"enabled":true,"settings":{}},"progress-bar":{"enabled":true,"settings":{"height":8,"topbar":false}},"project-info":{"enabled":true,"settings":{"show":"text"}},"project-notes-tabs":{"enabled":true,"settings":{}},"redirect-mobile-forums":{"enabled":true,"settings":{}},"remember-collapsed-categories":{"enabled":true,"settings":{}},"remix-button":{"enabled":true,"settings":{}},"remix-tree-button":{"enabled":true,"settings":{}},"remove-curved-stage-border":{"enabled":true,"settings":{}},"remove-search-bar-autocomplete":{"enabled":true,"settings":{}},"remove-sprite-confirm":{"enabled":true,"settings":{}},"rename-broadcasts":{"enabled":true,"settings":{}},"resizable-comment-input":{"enabled":true,"settings":{}},"scratch-messaging":{"enabled":true,"settings":{}},"scratch-notifier":{"enabled":true,"settings":{"becomehoststudio_notifications":false,"becomeownerstudio_notifications":false,"commentsforme_notifications":true,"commentsonmyprojects_notifications":true,"curatorinvite_notifications":false,"favoriteproject_notifications":false,"followuser_notifications":false,"forumpost_notifications":false,"loveproject_notifications":false,"mark_as_read_when_clicked":true,"notification_sound":"silent","remixproject_notifications":false,"studioactivity_notifications":false}},"scratchblocks":{"enabled":false,"settings":{}},"scratchr2":{"enabled":true,"settings":{"postStyle":"box"}},"scratchstats":{"enabled":false,"settings":{}},"script-snap":{"enabled":true,"settings":{"grid":40}},"search-my-stuff":{"enabled":true,"settings":{}},"search-profile":{"enabled":true,"settings":{}},"search-sprites":{"enabled":true,"settings":{}},"semicolon":{"enabled":false,"settings":{}},"share-through-mystuff":{"enabled":true,"settings":{}},"show-bbcode":{"enabled":true,"settings":{}},"sounds-duration":{"enabled":true,"settings":{}},"sprite-properties":{"enabled":true,"settings":{"autoCollapse":true,"hideByDefault":true,"transitionDuration":"none"}},"studio-followers":{"enabled":true,"settings":{}},"studio-tools":{"enabled":true,"settings":{"mystufftools":true}},"swap-local-global":{"enabled":true,"settings":{}},"transparent-orphans":{"enabled":true,"settings":{"block":0,"dragged":40,"orphan":0}},"true-youtube-links":{"enabled":false,"settings":{}},"turbowarp-player":{"enabled":true,"settings":{"action":"player","addons":true}},"user-id":{"enabled":true,"settings":{"only-on-hover":false}},"variable-manager":{"enabled":true,"settings":{}},"vol-slider":{"enabled":true,"settings":{"always":true,"defVol":15}},"youtube-fullscreen":{"enabled":true,"settings":{}},"zebra-striping":{"enabled":true,"settings":{"intensity":36,"shade":"darker"}}}}`

</p>
</details> 

This doesn't appear to be a Scratch bug as hard as I can attempt to replicate on Vivaldi (6.5.3206.39 (Stable channel) (32 bit))
More so appears to be an issue on Firefox, now that I am testing again during the submission of the issue.
### What should happen
Creating/Editing custom blocks does not cause any blurs.
### What actually happens
The custom block is blurry for a few moments.

### Steps to reproduce

1. Use Firefox or any Firefox fork (I am unable to replicate on Chromium, specifically Vivaldi)
2. Load settings above (I am unsure which really caused it, I am trying to narrow down which one it was.)
3. Try making/editing a custom block, it should blur.

### Demonstration(s) and additional context

NOTE: the reason the text is "hard to screenshot" is because I'm slow lol so I just thought what the first thing could be that I'd do fast.
![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/f50a0fc7-393b-42e9-b0bf-dc3d908ab424)

### Environment

Browser: Firefox 120.0.1 (32 bit)
Scratch Addons version: 1.36.0-pre (e5519b0)
Operating system: Windows 10

**Comment by WorldLanguages** [comment]
Do we know if this is related to #6872 ?

**Comment by OneShot-Niko** [comment]
Can't seem to replicate this anymore.
