### ISSUE TITLE
Move settings search into header

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#6997]
From the Development Discord:
> (@TheColaber) hmm
> ![](https://media.discordapp.net/attachments/751207339545198682/1187997665955434556/image.png?ex=6598ec0b&is=6586770b&hm=992bfeac55ae067612ee85b4a75ac041b066cafdc1b72f3d6749ccdcf224df55&=&format=webp&quality=lossless&width=775&height=191)

> (@rgantzos ) ![](https://media.discordapp.net/attachments/751207339545198682/1188001978933067856/Screenshot_2023-12-22_at_10.15.35_PM.png?ex=6598f00f&is=65867b0f&hm=736405a1977a8938c5ed77e8052849c40c0a911cdb735528d7ac70dffc1740f9&=&format=webp&quality=lossless&width=775&height=467)

This makes a lot of sense since there's nothing else where to search bar is now.

**Comment by TheColaber** [comment]
The only problem I realized after is that the popup view of the settings page will have to be modified in some way to accommodate for the search bar being in the header.

**Comment by DNin01** [comment]
With the search bar being the only thing on that row above the list of addons, I think it could be moved to the Scratch Addons header to free up that little bit of space, but it's not a big deal, other than it being a design decision. Worth considering is what should happen to it on smaller windows, as it would have to be crammed in with the other elements on the header.

**Comment by mxmou** [comment]
> Worth considering is what should happen to it on smaller windows, as it would have to be crammed in with the other elements on the header.

There's enough space unless the window is so small that the whole layout breaks anyway.

**Comment by WorldLanguages** [comment]
We're probably not going to make this small change by itself ever. But it's okay to keep this as an open issue

**Comment by mxmou** [comment]
> We're probably not going to make this small change by itself ever. But it's okay to keep this as an open issue

Why not? It would save a lot of space, which is especially important if we want the extension to work on mobile devices.

**Comment by Secret-chest** [comment]
On mobile devices it could actually make the header overflow.

**Comment by DNin01** [comment]
> On mobile devices it could actually make the header overflow.

What if it was collapsed to a search icon and expanded into a full search bar when clicked, on those devices? However, considering there's not enough space on the popup to put it on the header, probably we would simply keep it where it is now if the screen is too small and on the popup.
