### ISSUE TITLE
[New addons] Cat+ userscripts

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#70]
**Describe the new addon**

Userscripts that improve Scratch 3. (currently unmaintained, many scripts are broken or work inconsistently)

**Link to the new addon**

https://github.com/forkphorus/cat-plus#readme

**Comment by GarboMuffin** [comment]
Hi, I was the developer of the Cat+ userscripts. I noticed I never added a license so I've done that now.

The only scripts that I think might be worth porting to ScratchAddons would be:

 - colored-editor-context-menu.user.js
 - extra-metadata.user.js
 - make-projects-shared.user.js
 - searchable-dropdowns.user.js (has some weird quirks but it works)

The other ones are probably broken or griffpatch's developer tools do it better.

I'd be willing to submit PRs for some of these, if you'd like.

**Comment by WorldLanguages** [comment]
Thanks for commenting on the issue, @GarboMuffin!
Thanks for offering to help, but keep in mind there are still many upcoming wiki pages to write. If you feel lost, that's expected at this stage. Only if you feel like it, try to make a  PR. There's a small guide on how to make a new addon here: https://github.com/ScratchAddons/ScratchAddons/issues/74#issuecomment-678488280
Make sure to refresh the extension from `chrome://extensions` after making changes to your addon.
Feel free to tag me if you need help with a specific issue.

**Comment by TheColaber** [comment]
Are there any other things we might want from Cat+?

**Comment by Ani-Xan** [comment]
@WorldLanguages @TheColaber 
I think we should add an option to toggle the unrounded stage within the editor menus of Scratch (and add the unrounded stage userscript). We should have it enabled by default, but people who really want it have to go into the editor of a project and enable it. 👍🏻 
😸

**Comment by GrahamSH-LLK** [comment]
We've ported 2 of these, and the others have their own issues.

**Comment by Ani-Xan** [comment]
@GrahamSH-LLK We should find a fix.

**Comment by GrahamSH-LLK** [comment]
> @GrahamSH-LLK We should find a fix. (or alter the code)

What? Oh, I meant issues as in GitHub Issues, like this one.

**Comment by Ani-Xan** [comment]
@GrahamSH-LLK Oh, lol. 😖
