### ISSUE TITLE
Confirmations Addon: Confirm when you press the "reply" button

### ISSUE THREAD

**Issue by hueychen27** [ScratchAddons/ScratchAddons#7000]
### Why this would be helpful

When I am trying to write a comment, I sometimes accidentally press the "reply" button which removes the comment you are writing. It would be helpful to warn the user when there is content in the comment and you press the "reply" button.

### My suggestion

Warn the user about clicking the "reply" button when the comment has text in it and add the feature to the "Confirmations" addon. If the comment you are writing is empty, don't warn the user about clicking the "reply" button.

### Additional context

![comment](https://github.com/ScratchAddons/ScratchAddons/assets/78285518/74ae834b-46cb-4952-9f65-082b9cd33689)

**Comment by DNin01** [comment]
We could implement this through an extension of the "confirm canceling comments" setting. If it was enabled, clicking the reply button if you're already writing a reply would confirm first.

**Comment by WorldLanguages** [comment]
Huh, never noticed this. We should definitely consider this
