### ISSUE TITLE
`middle-click-popup`: CTRL+SPACE works on project page after leaving editor

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7011]
### Description

> [!NOTE]
> This works only project pages after leaving the editor of the project, nowhere else. Bad at describing so I'm just gonna use the note markdown tag.

### What should happen
Pressing CTRL and SPACE does absolutely nothing outside the editor, even after leaving it.
### What actually happens
The popup shows up - You can still type in it, but blocks won't show up.

### Steps to reproduce

1. Enable `middle-click-popup`
2. Go to a project (or make a new one)
3. If you made a new project, exit editor and simply press CTRL+SPACE, then you see the issue. If you went to a project, go inside the editor.
4. Leave the editor.
5. Press CTRL & SPACE at the same time, then you have the issue.

### Demonstration(s) and additional context

![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/327cbe1c-8877-4e5e-b3ad-944ed8c2f0e7)
(note these screenshots are on different projects just to demonstrate, above is someone elses and below is an unshared one)
![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/895c0410-2bf3-4190-a5cf-f3cfb8088367)
### Environment

Browser: FF 121.0 (32 bit)
Scratch Addons version: 8f41844
Operating system: Windows 10

**Comment by WorldLanguages** [comment]
Nice catch!
