### ISSUE TITLE
`editor-theme3`: high contrast template makes block creation harder to read

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7015]
### What should happen
The high contrast template is (atleast really close) to the high contrast mode
### What actually happens
The background of the "create block" will sync to white, which makes it hard to read.
For comparison, the first two images (highlighted, not highlighted) here are without `editor-theme3`. They are really easy to read:
![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/7d2273b7-f1ce-4333-b73c-95a0048dff0d)
![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/389aa479-ea44-4ebd-830d-b812b357ebc3)
Demonstrations will have the other two.

### Steps to reproduce

1. enable `editor-theme3`
2. use high contrast template
3. try making a block
4. the text and text background sync and are hard to read

### Demonstration(s) and additional context

![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/c3dbc09c-05be-4845-96d2-f8511314758d)
![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/0ae23eda-9ba9-4046-9133-aff91bc8c51f)
As for some additional context, I decided I'd edit the high contrast template since its easy to read, but got curious if the template really matches the normal Scratch version that much.

I have no idea for a possible solution but I think I should still report this considering I cannot find any issue or pull
### Environment

Browser: Vivaldi 6.5.3206.48 (Stable channel) (32 bit) - Firefox 121.0 (32 bit)
(Tried on Vivaldi just to make sure, thus I believe best if I include it)
Scratch Addons version: b48fbcb
Operating system: Windows 10

**Comment by WorldLanguages** [comment]
Nice catch!
