### ISSUE TITLE
`block-cherry-picking` doesn't account for cutting blocks

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7023]
### Description

I'm actually unsure if this is intentional or not but thought it'd probably be better if I made an issue anyways since there doesn't appear to be any
### What should happen
cutting a block (with CTRL+X) will only account for that block rather than copying everything below it as well
### What actually happens
Everything below the block gets copied as well so you are forced to delete the entire lane that you don't need

### Steps to reproduce

1. enable `block-cherry-picking` (if you haven't or had it disabled for some reason)
2. (A) go into the editor or (B) one of your projects
3a. Spam a few random blocks and include a C block presumably
4. go to any line of code and hold CTRL, then cut the block.
4. Paste, it won't only be the singular block you held CTRL with.

No idea how this could get fixed considering they both use CTRL, unless maybe this could be avoided by adding a shift variation that only focuses on the specific block?
Though, somewhat related: #6804 

### Demonstration(s) and additional context

_No response._

### Environment

Browser: Firefox 121.0 (32 bit)
Scratch Addons version: f23b744
Operating system: Windows 10

**Comment by DNin01** [comment]
There is an upstream issue that I can replicate without using Scratch Addons, and might be what you're experiencing.

When cutting, only the focused block is removed, but when you paste cut or copied blocks, the entire stack starting from the block you cut or copied is pasted.

https://github.com/ScratchAddons/ScratchAddons/assets/106490990/da270fe6-8038-4378-afb7-87b72e3e0d7b

At least this doesn't happen when using the `editor-devtools` addon's "Cut Block" button.

`block-cherry-picking` wasn't designed to fix or cause this bug, so I'm going to close this issue as an upstream bug.

About us implementing a bug fix in the form of an addon, I think it makes more sense for this bug fix to be a different addon.

**Comment by OneShot-Niko** [comment]
> There is an upstream issue that I can replicate without using Scratch Addons, and might be what you're experiencing.
> 
> When cutting, only the focused block is removed, but when you paste cut or copied blocks, the entire stack starting from the block you cut or copied is pasted.
> Block.cut.and.paste.discrepancy.mp4
> 
> At least this doesn't happen when using the `editor-devtools` addon's "Cut Block" button.
> 
> `block-cherry-picking` wasn't designed to fix or cause this bug, so I'm going to close this issue as an upstream bug.
> 
> About us implementing a bug fix in the form of an addon, I think it makes more sense for this bug fix to be a different addon.

Fair.
