### ISSUE TITLE
`hide-flyout` palette & category hover automatically closes blocks pane when editing an input

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7024]
### Description

<sub>(Note: for some reason I was unsure if this was a bug so I used the suggestion template originally, reformatted this manualy)</sub>

`hide-flyout` is really useful, especially category hover & pallete area hover- However it will still automatically close if you are editing an input before dragging it on the code pane.

This can be annoying if you edit a variable setter and then drag (which I do) instead of dragging and then editing

### Steps to reproduce

1. Enable `hide-flyout` and either palette or category hover
2. Go in the editor
3. Edit an input

### Possible alternatives

1. Make it optional (though that'd be odd)
2. Don't implement
3. Auto-lock when editing an input

(Keeping this in for now)
### Additional context

![hide-flyout-closes-on-input](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/28068b48-7642-492f-8603-c78deba52adc)
(occurs after merely attempting to edit the input)

**Comment by DNin01** [comment]
I would classify this as a bug... a pretty annoying one indeed, especially combined with #6902.

**Comment by DNin01** [comment]
> 3\. Auto-lock when editing an input

That's a good idea - if you happen to hover outside while you're editing an input in the flyout, the flyout won't collapse.

**Comment by OneShot-Niko** [comment]
> I would classify this as a bug... a pretty annoying one indeed, especially combined with #6902.

Will retitle then.
Apologies - Wasn't really sure.

**Comment by WorldLanguages** [comment]
+1 from feedback

Also happens with dropdowns

**Comment by hueychen27** [comment]
Solution: Keep palette activated when cursor is focused within the palette's elements, not just the palette background itself.
