### ISSUE TITLE
`semicolon`: doesnt appear on scratchr2 pages with `sticky-footer`

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7025]
### What should happen
the semicolon appears above the sticky footer
### What actually happens
the semicolon gets layered below the sticky footer(?) so you cannot see it

### Steps to reproduce

1. konami code (#1423)
2. enable `semi-colon` then go back and enable `sticky-footer`
3. go to a profile page
4. see the ~~horror~~ issue

### Demonstration(s) and additional context

![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/1dc5f2fa-ff0b-40a4-b043-daead4ae13db)

### Environment

Browser: Firefox 121.0 (32 bit)
Scratch Addons version: f23b744
Operating system: Windows 10

**Comment by iqnite** [comment]
Previously, people complained when the semicolon glitch appeared. Now, tey complain when it doesn't appear...

**Comment by WorldLanguages** [comment]
> ### What should happen
> the semicolon appears above the sticky footer

I disagree, tbh.

**Comment by OneShot-Niko** [comment]
> > ### What should happen
> > the semicolon appears above the sticky footer
> 
> I disagree, tbh.

I agree to your disagreement, tbh.
~~It's really not even a big issue anyway lol~~

**Comment by iqnite** [comment]
> I agree to your disagreement, tbh. ~It's really not even a big issue anyway lol~

The bug's valid, but it's quite small. Also, it's an easter egg that doesn't add any functionality to the site, so no functionality is lost because of the bug. Adapting the entire Sticky Footer addon just isn't worth it.
