### ISSUE TITLE
Replace all instances of list or variable with another variable in a sprite

### ISSUE THREAD

**Issue by hueychen27** [ScratchAddons/ScratchAddons#7026]
### Why this would be helpful

I have a list that I want to change into another list and I don't want to manually replace the list with that other list.

### How this addon works

This addon is similar to the swapping lists and variables addon. Instead of swapping, make every instance of the first list or variable in a sprite another list or variable.

### Possible alternatives

This could be merged with the "Developer tools" addon.

### Additional context

Manual labor that I want to be done in a button:

https://github.com/ScratchAddons/ScratchAddons/assets/78285518/e216b0bb-28a7-487b-9ecc-0f0713d4cea3

**Comment by CST1229** [comment]
I think the "Developer tools" addon already adds this (right click a variable/list reporter -> Swap variables/lists in Sprite)

**Comment by hueychen27** [comment]
No, it swaps variable/lists. I want to replace variable/lists.

**Comment by medlans** [comment]
> No, it swaps variable/lists. I want to replace variable/lists.

It works for me: 
Before:
![BeforeList](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/1c31a3c1-26e5-4537-87e0-c3b3b4804de8)
![BeforeVar](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/9c2b4968-0099-4965-b837-479916bc3287)
![BeforeListDropdown](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/d078b7e8-c488-46f0-96c2-6db85700f220)
![BeforeHoverVar](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/41ef7379-2ac6-40d8-9dc1-6213ab87b43c)
After:
![AfterList](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/ae00b2ee-7a18-4679-b1e3-ba8ea346b01a)
![AfterVar](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/976cf5a1-216f-46e5-abd8-1f876691d7a6)

**Comment by CST1229** [comment]
> It works for me:

Even for "merging" two variables (screenshot is TurboWarp but it works the same way in SA too):
![image](https://github.com/ScratchAddons/ScratchAddons/assets/68464103/2cad567c-96bf-4842-87f4-9e590452bd93)
![image](https://github.com/ScratchAddons/ScratchAddons/assets/68464103/7a84c3ea-243e-4fa4-83f0-11dde5bd9a9a)
![image](https://github.com/ScratchAddons/ScratchAddons/assets/68464103/9f6d8f58-ab5c-48d2-ba78-98ca89fea6d7)

**Comment by hueychen27** [comment]
I tried again and it works. "Swapping" is misleading. "Replace" or "Switch" would be a better word.

**Comment by WorldLanguages** [comment]
> I tried again and it works. "Swapping" is misleading. "Replace" or "Switch" would be a better word.

I agree.
