### ISSUE TITLE
forever if block from scratch 1.4

### ISSUE THREAD

**Issue by jack-oid** [ScratchAddons/ScratchAddons#7029]
### Why this would be helpful

this would bring back a useful block. instead of grabbing a forever and an if block there is only one block.

### How this addon works

![forever if](https://github.com/ScratchAddons/ScratchAddons/assets/154941233/d950446f-92a1-4b56-99e6-e39a62b8b723)

**Comment by CubesterYT** [comment]
Scratch Addons cannot bring back a block that's been completed removed from Scratch. If it was still in Scratch, we could bring it back using simple methods, but forever if no longer exists in Scratch's code.

**Comment by BroJac5246** [comment]
I believe this has been suggested many times in various places and forms, but see #7002 for a related (yet different) suggestion.

**Comment by WorldLanguages** [comment]
See discussion #7002
