### ISSUE TITLE
`editor-dark-mode` does not affect WebGL disabled/unsupported popup

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7037]
### Description

(I got this on pure accident after forgetting to enable WebGL on LibreWolf as I reset about:config a lot lol)
### What should happen (possibly)
The WebGL unsupported/disabled popup is affected by `editor-dark-mode`
### What actually happens
It's not affected by `editor-dark-mode`.

### Steps to reproduce

1. enable `editor-dark-mode`
2. ~~Unsure how you can disable WebGL on chromium (though i think it's something on along the lines of about://flags and then enabling the "Disable WebGL" flag)~~ On chromium, disable the `-disable-webgl` flag, on Firefox, go to `about:config` and search for `webgl.disabled`, if it's true, go to the [editor](https://scratch.mit.edu/projects/editor/), if it's false, set it to true.
3. See issue.

### Demonstration(s) and additional context

![issue](https://u.cubeupload.com/Zyy/editordarkmodepopup.png)

### Environment

Browser: LibreWolf 121.0-1 (Windows MSIX package, mozilla-MSIX - 1.0)
Scratch Addons version: 1.36.0-pre (d4090b6)
Operating system: Windows 10 (32 bit,  monitor size: 1366 x 768)

**Comment by mybearworld** [comment]
On Chrome/Edge, there's a command line flag `-disable-webgl` that you can use to start the browser with. That'll disable WebGL and allow testing of it.

**Comment by OneShot-Niko** [comment]
> On Chrome/Edge, there's a command line flag `-disable-webgl` that you can use to start the browser with. That'll disable WebGL and allow testing of it.

Alrighty, gonna edit
