### ISSUE TITLE
ScratchBlocks don't get rendered if you leave the tab while loading and having 3.0 blocks on forums

### ISSUE THREAD

**Issue by NotFenixio** [ScratchAddons/ScratchAddons#7043]
### Description

When you open a topic and before it loads you leave while having the addon "ScratchBlocks 3.0 on forums" enabled, the block will not be rendered and instead will show a weird line with the blocks.

### Steps to reproduce

1. Make sure you have the addon "ScratchBlocks 3.0 on forum" enabled.
2. Open a topic that contains scratchblocks, like the official scratchblocks testing topic.
3. Before it loads, leave the tab and wait until it loads.
4. Go back and see the bug.

### Demonstration(s) and additional context

Can't submit a video, sadly.

### Environment

Browser: Firefox 121.0 (64-bit)
Scratch Addons version: v1.35.1
Operating system: Windows 11

**Comment by mybearworld** [comment]
Duplicate of #6014 I think

**Comment by NotFenixio** [comment]
> Duplicate of #6014 I think

Yep, thanks for that.
