### ISSUE TITLE
Add MP4 support to media-recorder addon

### ISSUE THREAD

**Issue by Joeclinton1** [ScratchAddons/ScratchAddons#7052]
### Why this would be helpful

webm is what is recorded by the stream by default but playback is not as widely supported as a more common video codec like MP4. Most notably mobile users on discord might not be able to view an uploaded webm video leading to some people needing to first convert their file before uploading.

### My suggestion

Add a setting for the addon called "export as MP4". If this setting is enabled this would run the webm-to-mp4 package: https://www.npmjs.com/package/webm-to-mp4 or the ffmpeg-js port: https://github.com/Kagami/ffmpeg.js/ to convert the webm file to an mp4 before exporting. Depending on how slow it is this may also show a progress bar.

### Possible alternatives

You can always convert it externally, perhaps with ffmpeg via command line or an online converter, but this would be far more convenient.

**Comment by CST1229** [comment]
IIRC this is impractical because MP4 encoding libraries are _very_ large (as in, tens of megabytes large).

**Comment by RedGuy12** [comment]
`webm-to-mp4` just depends on `ffmpeg.js`, which yeah is 40 MB

**Comment by Joeclinton1** [comment]
We can use this actually https://ffmpegwasm.netlify.app/ the two files that need to be npm installed add up to 80kb

**Comment by RedGuy12** [comment]
Their example includes loading external scripts (which the CWS wouldn't like) which is over 30 MB
