### ISSUE TITLE
Add v8/v9 codec support for mediarecorder addon

### ISSUE THREAD

**Issue by Joeclinton1** [ScratchAddons/ScratchAddons#7055]
### Why this would be helpful

Currently the media recorder addon uses the mime type: video/webm. The default codec export of this depends on the browser but in Chrome it exports to avc1 codec. The problem is this codec is not supported by android or ios. HOWEVER android supports both VP8/VP9 and IOS supports VP9. Which means very easily you could make the videos exported by the addon work on mobile discord!

### My suggestion

A setting option for picking the desired codec (a dropdown would be best I think), and then in the code
Add something like this:
`recorder = new MediaRecorder(stream, { mimeType: "video/webm; codecs=${codec}" });`

### Possible alternatives

Instead of offering support for multiple codecs just make it export to the superior VP9 codec by default. This is as easy as adding `codecs=vp9`. This might actually be better now that I think about it.

(all browsers that support mediarecorder also support exporting to VP9 codec)

### Additional context

I have tested the VP9 codec export, and it works on my android phone's discord.

**Comment by Joeclinton1** [comment]
I would make the pr for this addon now, but you guys are so slow at reviewing things I don't know if it would ever get approved.

**Comment by GarboMuffin** [comment]
are you aware of any reason at all to not just use VP9 all the time?

**Comment by Joeclinton1** [comment]
> are you aware of any reason at all to not just use VP9 all the time?

I did some research and could not find any reason to not just use VP9 all the time. It's apparently better for compression than avc1. And if it is also more supported on mobile, then it seems to be a clear cut winner.

**Comment by GarboMuffin** [comment]
I tested all major browsers on all major desktop operating systems they support:

 - Chrome defaults to recording VP8, but also supports VP9 and AV1 (https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/mediarecorder/video_track_recorder.cc;l=378;drc=67d90538f11c6b232dbfd716075db52aeb34fd15)
 - Firefox only supports recording VP8 (https://searchfox.org/mozilla-central/rev/21574e46b5a76083def8467eed472b7b448ea200/dom/media/MediaRecorder.cpp#308)
 - Safari only supports recording H264 into an mp4 (https://github.com/WebKit/WebKit/blob/25c142f653a1234a8c98ce488c590dc2a17a0758/Source/WebCore/Modules/mediarecorder/MediaRecorderProvider.cpp#L57)

If iOS' video codecs are the same as macOS', then H264 and VP9 can be played but VP8 can't. All roughly matches what you observed

Based on that there is no perfect solution. Preferring `video/webm; codecs=vp9` sounds reasonable but still needs fallback to `video/webm` for Firefox (and also `video/mp4` for Safari; #7006)

**Comment by Joeclinton1** [comment]
@GarboMuffin I have actually tested exporting in Chrome and checked the codec of the video exported. I can tell you for a fact the default is AVC1 aka H264 to be more specific. This is because the build settings by default have USE_PROPRIETARY_CODECS set to true.

There is a function called mediarecorder.isSupportedType() that can be used to check if it's supported or not. We can check VP9, VP8 and mp4. And choose them in order of priority, via some if else logic.

**Comment by GarboMuffin** [comment]
I also actually recorded some `video/webm` videos with Chrome and mpv said it was VP8. The code suggests it would only default to H264 for MP4. That doesn't really matter in the end anyways. The default settings clearly aren't what we want

**Comment by WorldLanguages** [comment]
> Preferring `video/webm; codecs=vp9` sounds reasonable but still needs fallback to `video/webm` for Firefox (and also `video/mp4` for Safari)

I believe this is your conclusion, if you both agree on that it can be merged quickly with no problem.
