### ISSUE TITLE
`editor-dark-mode`: accent background affects icons in the costume editor

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7066]
### Description

I have honestly no idea how to describe this, however as far as I can tell accent color is the cause.
The icons of the undo buttons get altered by the accent background, for whatever reason.

### Steps to reproduce

1. enable `editor-dark-mode` if you haven't
2. change the accent background (to for example complete red / ff0000)
3. look at the icons again.

### Demonstration(s) and additional context

Also this is probably due to a transparent background (originally thought it wasn't) - Viewing the image itself, even the icon gets visibly altered. Infact, go to the image source (via rightclick + open image in new tab), inspect, in styles, add `background-color: #000000` and just to see it better.
![example](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/bd53c755-8d75-479c-811f-b5d33b1c1683)
(i changed accent color for these two)
![h](https://u.cubeupload.com/Zyy/theheckhappened.png)
EDIT2: a few other icons also appear to get affected, however not by accent color (flip-vertical is one)
### Environment

Browser: Firefox 121.0 (32 bit)
Scratch Addons version: 1.36.0-pre (81b5ba2)
Operating system: Windows 10

**Comment by OneShot-Niko** [comment]
Seems like this is actually caused by an addon conflict. Trying to narrow that down...

**Comment by WorldLanguages** [comment]
I got a notification for this issue this week, but nothing has changed. Weird GitHub behavior I guess

**Comment by OneShot-Niko** [comment]
> I got a notification for this issue this week, but nothing has changed. Weird GitHub behavior I guess

No, it was me saying it might be an addon conflict, tested for a bit and realized I was wrong and just deleted the comment.
<sub>I should've hid it as outdated or resolved instead</sub>

**Comment by WorldLanguages** [comment]
Can you try debugging the CSS with the devtools until you find the rule that is causing this?

**Comment by OneShot-Niko** [comment]
> Can you try debugging the CSS with the devtools until you find the rule that is causing this?

Found it, doesn't seem like its with a CSS rule, though.

Hiding `experimental_editor.css`, which is the only file in `editor-dark-mode` that mentions the classname (or removing the classname from the CSS), does nothing

![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/5485c24e-be84-4b7a-89d7-35722b6c7f64)

The only thing that could be causing this is `paint_icons.js`:

https://github.com/ScratchAddons/ScratchAddons/blob/325916a3e7c296f904961b10d791f83c845c075a/addons/editor-dark-mode/paint_icons.js#L7C1-L12C5
