### ISSUE TITLE
Remove the max height from signatures with `full-signature`

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#7068]
### Why this would be helpful

No matter how few space a signature actually needs, it'll *always* take up 168px with `full-signature`. This can be very annoying, especially for 1 line signatures (like mine).

### How this works

This would remove the minimum height from signatures.

### Additional context

**Before**
![The signature takes up a lot of unnecessary space - it's only a line long](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/f8e26c63-82a9-4b3e-8580-a1447c0357c3)

**After**
![The signature only takes up one line](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/d2061c42-09a4-4b86-9f30-e4982930befe)

**Comment by mxmou** [comment]
There's no minimum height in vanilla Scratch - it's added by the `full-signature` addon, which is enabled by default.

**Comment by DNin01** [comment]
> There's no minimum height in vanilla Scratch - it's added by the `full-signature` addon, which is enabled by default.

Maybe we should fix that.

**Comment by mybearworld** [comment]
> > There's no minimum height in vanilla Scratch - it's added by the `full-signature` addon, which is enabled by default.
> 
> Maybe we should fix that.

I made a PR to do that - #7071

**Comment by WorldLanguages** [comment]
> There's no minimum height in vanilla Scratch - it's added by the `full-signature` addon, which is enabled by default.

That's not good
