### ISSUE TITLE
`dark-www`: link color affects closed topics on "show your topics"

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7070]
### Description

dark-www's custom link color affects closed topics linked in [the "show your topics" URL](https://scratch.mit.edu/discuss/search/?action=show_user&show_as=topics) at the bottom of the forums, however it works fine anywhere else

<sub>this is probably the least used part of the forums to be real here, I literally discovered this by accident</sub>

### Steps to reproduce

1. enable dark-www
2. change link style
3. go [here](https://scratch.mit.edu/discuss/search/?action=show_user&show_as=topics) or to the bottom of the forums mainpage and click "topics"
4. Look for any closed ones, atleast ones you haven't read a post in. You'll have to manually check if you've been reading all of them.

### Demonstration(s) and additional context

![h](https://u.cubeupload.com/Zyy/anotherbug.png)

### Environment

Browser: Firefox 121.0 (32 bit) & LibreWolf 121.0-1 (mozilla-MSIX - 1.0)
Scratch Addons version: v1.35.1-stable & v1.36.0-pre (81b5ba2)
Operating system: Windows 10

**Comment by mybearworld** [comment]
Vanilla Scratch doesn't handle it correctly either:

![A closed topic with purple link color in regular Scratch](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/da8af31f-a1c7-41c4-972b-d0ec9829ce2f)

**Comment by OneShot-Niko** [comment]
> Vanilla Scratch doesn't handle it correctly either:
> 
> ![A closed topic with purple link color in regular Scratch](https://private-user-images.githubusercontent.com/130385691/296326211-da8af31f-a1c7-41c4-972b-d0ec9829ce2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwODQxMjcsIm5iZiI6MTcwNTA4MzgyNywicGF0aCI6Ii8xMzAzODU2OTEvMjk2MzI2MjExLWRhOGFmMzFmLWExYzctNDFjNC05NzJiLWQwZWM5ODI5Y2UyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQxODIzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzNmZDhkZjI0MjcyNTE4ODEwZTYyYTM5MTRkMmY3YTBlZTgwMjg2MGRhYWNkYjE0YWE2MThhZGNkZWRhMDExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kRkn9EwtLQbv9mZ-_VG9Cxqggd7cCjPkOSZB7a3nwT0)

Oh, whoops - Somehow didn't realize.
