### ISSUE TITLE
`reorder-custom-inputs`: Icons can clip out of the "Make a Block" modal

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7083]
### Description

Unsure how to explain this -  I should've probably looked on the PR myself and this appears not to have been discussed

### Steps to reproduce

1. enable `reorder-custom-inputs`
2. project
3. drag the code view of the custom block so the icons cover the top part of the modal, or just put as many as you want and then select the first one, drag the view to the other side

### Demonstration(s) and additional context

![clipping out (top)](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/ef66ce77-595f-4f28-930c-f7598d46929a)
![clipping out (side)](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/85562f4a-02a2-445e-8770-1bccfd9651a9)

### Environment

Browser: Firefox 121.0
Scratch Addons version: v1.36.0-pre (ee47b13)
Operating system: Windows 10 (32 bit)

**Comment by mxmou** [comment]
This can happen to the delete icon without the addon.
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/18527d9a-8e58-40bc-a35b-29912d2bee4f)
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/8e955678-1207-4029-9c08-72de912eb393)

**Comment by OneShot-Niko** [comment]
> This can happen to the delete icon without the addon.
> ![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/18527d9a-8e58-40bc-a35b-29912d2bee4f)
> ![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/8e955678-1207-4029-9c08-72de912eb393)

Ah, my bad - Completely forgot about that.

**Comment by Joeclinton1** [comment]
The arrows appear vertically misaligned in your screenshot, that's a minor bug, could be fixed with better css.
