### ISSUE TITLE
Pause button should be in "website features"

### ISSUE THREAD

**Issue by ghost** [ScratchAddons/ScratchAddons#709]
The pause button addon should be classified as a website feature because you can use it for other projects.

**Comment by mxmou** [comment]
Technically it's both a website feature and an editor feature.

**Comment by WorldLanguages** [comment]
Many project features can be used for other projects.

**Comment by mxmou** [comment]
@WorldLanguages That's true, but people would understand editor features as features that only work inside the editor.

**Comment by WorldLanguages** [comment]
Yeah, maybe "Scratch Projects features" might have been a better name.

**Comment by WorldLanguages** [comment]
This issue is outdated. We have a "project player" subcategory now.
