### ISSUE TITLE
Show Report Button in your own projects

### ISSUE THREAD

**Issue by rbtmcmc1234** [ScratchAddons/ScratchAddons#7092]
### Description

Show the ( ! Report) button in your projects.

### Steps to reproduce

`Report `Button```Project.random//???????number
![679ce05ac8c35bbf83f596e895ab711b](https://github.com/ScratchAddons/ScratchAddons/assets/157301284/0cd6fb6b-cfd1-4fb6-bff9-7624f65d0d75)
`

### Environment

Browser: 
Scratch Addons version: 
Operating system:

**Comment by rgantzos** [comment]
1. This sounds like a feature request
2. If it is, would you need to report your own projects

**Comment by BroJac5246** [comment]
Instead of reporting your own projects, why not just fix or delete them yourself? It's faster and you won't be banned.

**Comment by DNin01** [comment]
But who would want to use that feature?

**Comment by TonyBmMath** [comment]
very funny
