### ISSUE TITLE
I can release Scratch Addons on Safari

### ISSUE THREAD

**Issue by Oren-Lindsey** [ScratchAddons/ScratchAddons#7097]
I am going to be getting an Apple developer account (within the next week probably, but it will be very soon). So I will release SA on Safari when I get it. Just wanted to let y'all know.

**Comment by Oren-Lindsey** [comment]
Also, I don't have access to discord right now. So don't try to contact me there.

**Comment by Samq64** [comment]
@GarboMuffin has already offered to publish it and has opened a PR to add proper support to the extension: #7006.

**Comment by Oren-Lindsey** [comment]
Ok if someone else is already doing it that's fine. I didn't know that. But I'm here if you need me.
