### ISSUE TITLE
`middle-click-popup` + `compact-editor`: Normal scrollbar is always visible

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7107]
### Description

This looks to be a firefox only bug since after asking others using a different variety (eg. mybearworld using Microsoft Edge)

This is also a really small bug that's probably just a CSS issue if I had to take a guess.

### Steps to reproduce

1. Enable `middle-click-popup`
2. Go to any project
3. CTRL+Space or any other shortcut the addon gives and look at the scrollbar in the popup, it will show the unstyled and styled one.

### Demonstration(s) and additional context

As example, it does not occur on Edge:
(screenshot credit: mybearworld)
![Fine on Edge](https://i.ibb.co/hFjh0MC/image.png)
And on Firefox, you can see the unstyled scroll-bar:
![doublescroll](https://u.cubeupload.com/Zyy/dualslider.png)

### Environment

Browser: Firefox 122.0 (32 bit)
Scratch Addons version: 1.36.0-pre (commit/hash: 7565b6e)
Operating system: Windows 10

**Comment by mxmou** [comment]
Chromium now supports `scrollbar-width`.
