### ISSUE TITLE
User Message Client for Desktop

### ISSUE THREAD

**Issue by KokiKitsune2007** [ScratchAddons/ScratchAddons#7111]
### Why this would be helpful

This would be helpful because people can just view their messages without going on the actual website.

### My suggestion

I'm suggesting that we add this because it might save browser resources and people won't have to go onto the actual website.  It works by launching a desktop app, linking your Scratch account, and it displays a list of all your notifications and messages.

**Comment by Samq64** [comment]
What's wrong with just using the messaging tab in the popup?

**Comment by WorldLanguages** [comment]
Most desktop apps are browsers nowadays :P

**Comment by KokiKitsune2007** [comment]
Ok, lol
