### ISSUE TITLE
`dark-www`: Preview iframe colors occasionally do not get adjusted

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7114]
### Description

This could be caused by the addon being paired with `forum-live-preview`,

### Steps to reproduce
EDIT: Consistent set-up by Maximouse: [#7114 (Comment)](https://github.com/ScratchAddons/ScratchAddons/issues/7114#issuecomment-1917812560)

1. enable dark-www & `forum-live-preview` (unsure if enabling forum live preview is needed or not)
2. Go to any post, presumably the scratchblocks topic
3. Enter anything
3a. If you did not encounter the bug, hard refresh (CTRL+SHIFT+R or CTRL+F5)
3b. If you encountered the bug, then the post preview should remain in default colors.

### Demonstration(s) and additional context

Related: #4130
Apparently, I missed getting a screenshot.
Will edit if I ever encounter it again.

### Environment

Browser: Firefox 122.0 (32 bit)
Scratch Addons version: 7565b6e
Operating system: Windows 10

**Comment by mxmou** [comment]
Here's a way to reproduce this consistently:
* Click the preview icon
* Alt-click the preview icon to remove the preview
* Click the preview icon again

If `forum-live-preview` is enabled, you can do this instead:
* Write something and wait until the preview appears
* Change a part of the post, then immediately press the Alt key and hold it until the preview is removed
* Change a part of the post again

**Comment by WorldLanguages** [comment]
Not a scope:core bug, right? If so please tell me

**Comment by OneShot-Niko** [comment]
> Not a scope:core bug, right? If so please tell me

I think it is, but I'm unsure.
The https://github.com/ScratchAddons/ScratchAddons/labels/scope%3A%20core label should probably just not get added onto the issue, but then again I honestly have no idea.
