### ISSUE TITLE
Weird Popup Layout

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#713]
**Describe the bug**

Sometimes, the popup appears like this:
![image](https://user-images.githubusercontent.com/72760579/98729942-9b5c7c80-2369-11eb-97ad-6b97af883a3e.png)
with the button right next to the text. I don't know how I caused this... I am not able to reproduce this...

**Expected behavior**

Stacked on top instead of being right next to each other.

**Device (please complete the following information):**

- OS: [Windows]
- Browser [Chrome
- Version [86]

**Comment by Explosion-Scratch** [comment]
This is likely due to ```flex-direction```being set to column instead of row, are you guys using flex?

**Comment by WorldLanguages** [comment]
I think this might happen if Scratch is down

**Comment by Daniel4-Scratch** [comment]
Maybe the CSS was corrupt for a second?

**Comment by TheColaber** [comment]
> Maybe the CSS was corrupt for a second?

lol, of course not, I think W_L is right.

**Comment by TheColaber** [comment]
this happened 50 years ago, safe to close for now.
