### ISSUE TITLE
Last dropdown options offscreen sometimes

### ISSUE THREAD

**Issue by iqnite** [ScratchAddons/ScratchAddons#7135]
### Description

**Problem:**
When a block with a long dropdown menu is between a certain distance (around 390 pixels) from the screen edge, the last few options are offscreen.

**Possible cause:**
Scratch normally solves this by flipping the dropdown menu to the upper side of the block, but it doesn't consider the search box added by Scratch Addons to determine if the menu is offscreen.

**Potential fix:**
Tell Scratch that the menu is bigger or adapt it manually.

### Steps to reproduce

1. Place a block with a lot of dropdown menu options around 390px from the edge of the screen
2. Open the dropdown menu and make sure `editor-searchable-dropdowns` is enabled
3. Scroll to the bottom of the menu

### Demonstration(s) and additional context

https://github.com/ScratchAddons/ScratchAddons/assets/50552317/2e210d93-6dbe-4bc5-82d8-92a3bdc275bb

*The bug occurs at 0:08.*

### Environment

Browser: Vivaldi 6.5 
Scratch Addons version: 1.35.1 
Operating system: Windows 11

**Comment by iqnite** [comment]
**Update:** Not a Scratch Addons bug, moved to https://github.com/ScratchAddons/ScratchAddons/issues/7136

**Comment by DNin01** [comment]
I can reproduce by resizing the window. If it's not tall enough, this bug can occur.

**Comment by WorldLanguages** [comment]
Even though this can happen on vanilla, I would still try to consider this separately...
