### ISSUE TITLE
New settings aren't usually invisible

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#7147]
_Where's my new setting?_

https://github.com/ScratchAddons/ScratchAddons/assets/106490990/553c1618-8ea7-41f8-924f-7e3207c3c877

Not sure what we can do about this, but it's best if new settings can be seen without having to toggle other settings.

This wouldn't be a problem if dependent settings were grayed out instead of completely hidden.

**Comment by WorldLanguages** [comment]
I've also noticed this, maybe all settings could be visible (but grayed out if necessary) like you said, but I would try to look at other software UIs for inspiration.

**Comment by mxmou** [comment]
For this addon, a select setting might be better than two Boolean settings:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/cfc74ccb-bb15-4b07-ad74-dc43069548b3)

> I've also noticed this, maybe all settings could be visible (but grayed out if necessary) like you said, but I would try to look at other software UIs for inspiration.

This is what PowerToys does:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/8ff13a63-c5b5-48ea-9d72-8fce4c64733f)
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/39e9439b-3fc7-4e71-b2e2-104638f7590f)

If we choose this solution, the UI should clearly show which settings are related.

**Comment by DNin01** [comment]
What PowerToys does is similar to #5719 and the screenshot in #6352.

**Comment by WorldLanguages** [comment]
In general, I agree that a three-option select is superior to 2 booleans where one depends on the other.

**Comment by DNin01** [comment]
Strings are closed, so unfortunately, we can't really solve this problem in a timely manner. We can and should still turn these two switches into a selection for clarity, but by the time we merge it, many people will have already checked out what's new, or we'll have updated to v1.37.0 where we'll have different new feature highlights.

**Comment by RedGuy12** [comment]
> maybe all settings could be visible (but grayed out if necessary)

I brought this up when I implemented this feature, but I think it was either @mxmou or @lisa-wolfgang who said it would be weird since it's not immediately obvious what other setting it depends on - especially for cross-addon dependencies.

**Comment by CST1229** [comment]
> I brought this up when I implemented this feature, but I think it was either @mxmou or @lisa-wolfgang who said it would be weird since it's not immediately obvious what other setting it depends on - especially for cross-addon dependencies.

Just throwing a random idea here: when a dependant setting is unavailable (or maybe always), have some hover text that says what the setting depends on (could be either the text itself while also adding a dotted underline or a ? icon next to it).
