### ISSUE TITLE
Exponential Blocks

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#715]
**Easily raise a number to the power of another**

I think adding exponential blocks allow more flexibility and make it easier to code the Pythagorean theory. It saves a lot of space when writing code. One way we could implement this would be by adding a drop down to the `()mod()` block or create a separate block for this feature.

**Comment by TheColaber** [comment]
Dupe of your own topic: #672?

**Comment by WorldLanguages** [comment]
@samuraininja360, due to what I said here: https://github.com/ScratchAddons/ScratchAddons/issues/698#issuecomment-724804753, I'm banning you from the organization for 30 days. You're still welcome to send feedback through https://scratchaddons.com/feedback, however.
