### ISSUE TITLE
`fullscreen` & `progress-bar`: Toolbar doesn't show when hovered

### ISSUE THREAD

**Issue by iqnite** [ScratchAddons/ScratchAddons#7166]
**EDIT:** Culprit identified: `progress-bar` causes the issue if "Show bar on top of page" is enabled.

### Description

In the "Enhanced full screen" addon, if the "Open full screen project player in full screen browser mode" option is enabled, the "Show toolbar when hovered" option doesn't do anything.

### Steps to reproduce

Click on the full screen button either in the player or on the project page with the settings mentioned above turned on.

### Demonstration(s) and additional context

Screenshot (Microsoft Edge):
![image](https://github.com/ScratchAddons/ScratchAddons/assets/50552317/27a8c074-0e27-4d23-9f61-94ae2758a6fb)

Enabled addons: https://github.com/ScratchAddons/ScratchAddons/issues/7166#issuecomment-1948484722

### Environment

Browser: Vivaldi 6.5.3206.63 (Stable channel) (64-Bit) 
Scratch Addons version: 1.36.0-pre.aa12349 
Operating system: Windows 11 23H2 

~~Bug does not occur in Microsoft Edge!~~
**Edit:** The feature works in Microsoft Edge, but a similarly strange bug occurs (see the screenshot above).
Other browsers to be tested.

**Comment by DNin01** [comment]
We'll keep researching this.

You should try testing this case with other addons disabled or find out if there are any addons that cause this bug.

Another thing we should test is touch screen compatibility.

The only thing I can think of that would be a browser-specific cause for this issue is a browser menu bar dropping down when hovering over the top of the screen, like Edge and I think Chrome do in F11 full screen.

A screen recording would be nice, just to make sure.

**Comment by Samq64** [comment]
This is specifically for when browser fullscreen is enabled right? I can't repro on Firefox or Brave but with the browser fullscreen setting disabled the toolbar isn't shown when hovering outside the tab on Firefox.

**Comment by iqnite** [comment]
[Uploading scratch-addons-settings (6).json…]()

**Comment by iqnite** [comment]
[scratch-addons-settings (6).json](https://github.com/ScratchAddons/ScratchAddons/files/14312155/scratch-addons-settings.6.json)

**Comment by DNin01** [comment]
I got a completely different issue to happen:
![Stage header without a background](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/9deba052-d63a-42c7-b83d-01f188d32e6d)

Enabled editor addons when that happened include:
```
60fps, clones, confirm-actions, debugger, disable-auto-save, faster-project-loading, fullscreen, gamepad, hide-flyout, mediarecorder, mouse-pos, paint-snap, place-backpack-code-at-cursor, reorder-custom-inputs, vol-slider
```
Not sure how that happened, and I tried to make it happen again but couldn't reproduce. I did dynamically enable `fullscreen`, though.

**Comment by DNin01** [comment]
Anyway, if you could try gradually disabling most of your editor addons while trying to reproduce your issue, that would be useful information. Maybe there's a specific addon that's causing this behavior. You can do it on a separate installation or export your settings first so you don't lose your original settings.

**Comment by iqnite** [comment]
The Progress Bar addon probably wants to prevent the user from triggering hover behaviors lying below the progress bar.

**Comment by WorldLanguages** [comment]
> **EDIT:** Culprit identified: `progress-bar` causes the issue if "Show bar on top of page" is enabled.

Oh, I see.

**Comment by WorldLanguages** [comment]
> A possible fix would be to hide the bar entirely instead of changing its opacity or to move it behind all other elements. I can do that in a new PR.

You mean the bar from progress-bar, right?
