### ISSUE TITLE
Preset Project Templates: Cloud Multiplayer Engine

### ISSUE THREAD

**Issue by samuraininja360** [ScratchAddons/ScratchAddons#717]
**Can We Have A Templates Button That Has A List Of Project Templates**

I imagined being able to instantly import Cloud Multiplayer projects in just one click. It saves a lot of time and we can easily add features to our multiplayer engines. I think this should be like the Scratch Idea Tutorials.

**Comment by JeffaloBob** [comment]
this one is actually a pretty good idea that scratchaddons can make.

so it would list some templates which would b obtained from a studio and then when you click one it would create the project?

cloud variables would be wacky to add though

**Comment by TheColaber** [comment]
Maybe a button next to tutorials, expect when you click on it, it displays templates instead.

**Comment by YOYITsM3M8** [comment]
ooh yeah

**Comment by RedGuy12** [comment]
what about credit? you can't talk about extentions on the main site

what if there are too many cloud variables already made?

**Comment by TheColaber** [comment]
@RedGuy12 
The credit will go to the people who make that template, they don't need to say SA. In fact, I think this addon will automatically credit that user.

I think this addon will replace the contents of the project, so that's not to worry.

**Comment by WorldLanguages** [comment]
If anyone wants to do this, please create a studio and put the templates on there, and ask users to remix the projects, or to reupload them.
