### ISSUE TITLE
Orange border on studio buttons

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#718]
**Describe the bug**

The Invite/promote/remove curators button and the Leave studio button both have ugly orange buttons.

**To Reproduce**

1. Go to any studio you manage
2. Click on 'Curators'
3. See error

**Expected behavior**

The regular grey border should show up...

**Screenshots**

https://assets.scratch.mit.edu/ba4034b632b70dea813be9a2a37dc4d5.png

**Device (please complete the following information):**

- OS: Windows NT 10.0
- Browser: Chrome 86.0.4240.183 (actually it's edge..)
- Version: of what?
- Flash: No Flash version detected

**Additional context**

Is that supposed to be there?

The only addon I have enabled for that screenshot is Studio Manager Tools by World_Languages

**Comment by WorldLanguages** [comment]
This is intended, to differentiate "official" Scratch buttons from the ones added by Scratch Addons. I admit there might be a better color choice, tho.
