### ISSUE TITLE
Disable Cloud Data Addon

### ISSUE THREAD

**Issue by RedLight-Scratch** [ScratchAddons/ScratchAddons#7181]
### Why this would be helpful

-Some online multiplayer projects are better to play offline for less lag
-Some non-cloud projects actually track you by sending information about your Username, Timezone, and OS to a server

### How this addon works

There would be a toggle on the project page to enable or disable cloud variables (you could also have an option to send but not receive or receive but not send the cloud data).

**Comment by iqnite** [comment]
Good idea! There are 3 scenarios in which Scratch disconnects cloud variables, we could replicate one of them to achieve the same effect:
- If the user is in the editor
- If the user is logged out
- If the user is a new scratcher

**Comment by WorldLanguages** [comment]
Duplicate of #5111
