### ISSUE TITLE
Dark mode issues in specific dialogs

### ISSUE THREAD

**Issue by 22yeets22** [ScratchAddons/ScratchAddons#7182]
### Description

In the report user dialog, when you do not select an option and try to submit the radio button bg will become white

### Steps to reproduce

1. Go to any user profile
2. Click report
3. A dialog will open up and try to submit it
4. Some background colors will appear white

### Environment

Browser: Opera One
Scratch Addons version: 1.35.1
Operating system: Windows 11

**Comment by Open137** [comment]
A similar problem happens when adding a student on a teacher account. It's almost impossible to read the text.
![Screenshot 2024-02-18 at 08-39-30 Scratch - Imagine Program Share](https://github.com/ScratchAddons/ScratchAddons/assets/159662550/e289d98a-1396-437f-8463-5e2c1d1878ba)

**Comment by WorldLanguages** [comment]
I guess this is about the "website dark mode and customizable colors" addon (dark-www)

**Comment by OneShot-Niko** [comment]
Isn't this just #7082 or am I misunderstanding?

**Comment by mxmou** [comment]
> Isn't this just #7082 or am I misunderstanding?

It's a different bug:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/4f429d7a-5587-4472-aff2-bd015ec410ef)

**Comment by OneShot-Niko** [comment]
> > Isn't this just #7082 or am I misunderstanding?
> 
> It's a different bug: ![image](https://private-user-images.githubusercontent.com/51849865/305737046-4f429d7a-5587-4472-aff2-bd015ec410ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyODIzMDEsIm5iZiI6MTcwODI4MjAwMSwicGF0aCI6Ii81MTg0OTg2NS8zMDU3MzcwNDYtNGY0MjlkN2EtNTU4Ny00NDcyLWFmZjItYmQwMTVlYzQxMGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDE4NDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZmM1N2RlODVjMTI1M2ViZGI2YWQ0MzMzNDc1ZTI4OWU4Njk3MDFjNGM5MjU3Mzc0NTBhMTg0Y2JjMGMyOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4DVpU57NXpXpYIiYmGbxOrbibJQsxm7RmbOKptXil7A)

Ah, my bad then.
