### ISSUE TITLE
Griffpatch Search Bar and Custom Block Colors

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#720]
**Describe the bug**

When I change the block colors for variable, events, and custom, the Griffpatch Search Bar doesn't update with the new colors.

**To Reproduce**

Change the colors, then click on Griffpatch's search bar.

**Expected behavior**

I think it would be nice for the colors to update.

**Comment by JeffaloBob** [comment]
#669

**Comment by Hans5958** [comment]
Duplicate of #666
