### ISSUE TITLE
`editor-theme3` prevents the number pad from updating inputs

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#7206]
### Description

When typing into a block input using the number pad with customizable block colors is enabled the updated value isn't displayed until the number pad is closed.

### Steps to reproduce

1. Enable `editor-theme3` and `number-pad`
2. Open the editor
3. Type into a number input using the number pad
4. Click outside the number pad

### Demonstration(s) and additional context

The bug happens without the number input addon, enabling it just makes reproducing the bug on desktop easier.

### Environment

Browser: Firefox mobile
Scratch Addons version: 1.36
Operating system: Android

**Comment by DNin01** [comment]
Might be a #6902 regression

**Comment by DNin01** [comment]
Yeah, so, when you're editing a field on a block, Scratch creates another input field on top of the block's input field. When entering in a number with the number pad, the _block's_ input field does not update until you click away.

Here's a video. After entering a number, I reveal the input that isn't updating automatically.

https://github.com/ScratchAddons/ScratchAddons/assets/106490990/306e1feb-4af2-4828-a501-8cfce9686d50

#6902 hides the overlaid input that does update automatically, leaving only the block's input visible, which doesn't update automatically.

@mxmou, we have a problem.
