### ISSUE TITLE
New addon, "Customizable website font"

### ISSUE THREAD

**Issue by Waakul** [ScratchAddons/ScratchAddons#7208]
### Why this would be helpful

Sometimes people get bored of scratch's default font and thinks of a change.

### My suggestion

a "Customizable website font" addon that can change the website's font from Helvetica Neue to something else

**Comment by Waakul** [comment]
WIP

**Comment by Waakul** [comment]
https://github.com/ScratchAddons/ScratchAddons/pull/7209 resolves this

**Comment by mxmou** [comment]
Duplicate of #1646
