### ISSUE TITLE
Wiki Button

### ISSUE THREAD

**Issue by RedGuy12** [ScratchAddons/ScratchAddons#721]
**Is your feature request related to a problem? Please describe.**

It's hard to acsess the forums without a navbar button. Same for the Wiki.

**Describe the solution you'd like**

I propose a addon that adds a Wiki button to the navbar, just like Maximouse and World_Language's Discuss button.

**Comment by JeffaloBob** [comment]
furthermore, when addon options get advanced enough #255, being able to create your own navbar would be cool.

**Comment by Hans5958** [comment]
I actually thought about this for a while, because this is also an MSU feature. This featured could be implemented inside the "Discuss button" addon. I also wanted to change the name and the ID if this got a green light, since the options are quite simple, but I'm not sure if it's actually okay.

**Comment by TheColaber** [comment]
> furthermore, when addon options get advanced enough #255, being able to create your own navbar would be cool.

#255 + Dropdowns = Custom navbar! Let's do it!

**Comment by Explosion-Scratch** [comment]
Why not just the ability to have a custom url for the button? Maybe even the ability to add multiple buttons?
