### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by Waakul** [ScratchAddons/ScratchAddons#7213]
### Why this would be helpful

A redesign for v2.0.0

### My suggestion

Redesigns by me and @Hexagonl 
![Frame 28 (2)](https://github.com/ScratchAddons/ScratchAddons/assets/135821321/da9d346e-1815-458c-ace5-7d2562f5ed10)
i will develop this but we need need to discuss about this first so ill create an issue

**Comment by Hexagonl** [comment]
I would like to note I only assisted in the concept art on Discord because I was bored and it was mildly interesting, I do not feel that SA requires a redesign as of this moment. Most of the work is by Waakul, all I did was fix the color contrast and wasted space issues

**Comment by Waakul** [comment]
tbh i'm not making it look exactly like this, I'm making some changes while I'm developing it

**Comment by Waakul** [comment]
> I would like to note I only assisted in the concept art on Discord because I was bored and it was mildly interesting, I do not feel that SA requires a redesign as of this moment. Most of the work is by Waakul, all I did was fix the color contrast and wasted space issues

we really need something cool for v2.0.0 and the current design sucks so...

**Comment by Waakul** [comment]
![image](https://github.com/ScratchAddons/ScratchAddons/assets/135821321/d53c9b06-01ff-4bac-9903-6dbce06b17c5)
current progress screenshot

**Comment by Samq64** [comment]
There are links to some other settings page redesigns here: https://github.com/ScratchAddons/ScratchAddons/discussions/5103#discussioncomment-3631004

Also unfortunately we're still using a really old version of Vue and are trying to go easy on changes until it's ported to a newer version (#6272) so a proper redesign won't happen until after that but smaller changes should be fine.

**Comment by Waakul** [comment]
> There are links to some other settings page redesigns here: [#5103 (comment)](https://github.com/ScratchAddons/ScratchAddons/discussions/5103#discussioncomment-3631004)
> 
> Also unfortunately we're still using a really old version of Vue and are trying to go easy on changes until it's ported to a newer version (#6272) so a proper redesign won't happen until after that but smaller changes should be fine.

no much features, only CSS changes

**Comment by Waakul** [comment]
> There are links to some other settings page redesigns here: [#5103 (comment)](https://github.com/ScratchAddons/ScratchAddons/discussions/5103#discussioncomment-3631004)
> 
> Also unfortunately we're still using a really old version of Vue and are trying to go easy on changes until it's ported to a newer version (#6272) so a proper redesign won't happen until after that but smaller changes should be fine.

porting to vue3 wont effect css files...

**Comment by Waakul** [comment]
wait we could do vue3, mv3, and redesign all together and bump into v2.0.0

**Comment by Samq64** [comment]
> porting to vue3 wont effect css files...

Everything is moved around and Git doesn't track everything correctly so there might be a couple merge conflicts but I don't mind fixing those.

> wait we could do vue3, mv3, and redesign all together and bump into v2.0.0

I think that's the plan assuming it's all ready by June.

**Comment by Waakul** [comment]
> > porting to vue3 wont effect css files...
> 
> Everything is moved around and Git doesn't track everything correctly so there might be a couple merge conflicts but I don't mind fixing those.
> 
> > wait we could do vue3, mv3, and redesign all together and bump into v2.0.0
> 
> I think that's the plan assuming it's all ready by June.

ik, I'll try to fix those myself later ig

**Comment by GrahamSH-LLK** [comment]
design ideas should go in a discussion

**Comment by Waakul** [comment]
@GrahamSH-LLK huh?

**Comment by Waakul** [comment]
@MaterArc told me to open an issue instead
