### ISSUE TITLE
Typing the konami code in the popup window gives double explore all 165+ addons iframe

### ISSUE THREAD

**Issue by Waakul** [ScratchAddons/ScratchAddons#7220]
### Description

Typing the konami code in the popup window gives double explore all 165+ addons iframe
![image](https://github.com/ScratchAddons/ScratchAddons/assets/135821321/8aabcf12-d9c5-4000-baab-77411586f789)

### Steps to reproduce

1.open the extension popup window
2.type the konami code
3.observe that there are double explore all 165+ addons iframe thingy

### Environment

Browser: Microsoft Edge 121.0.2277.128 (Official build) (64-bit) 
Scratch Addons version: v1.37.0-pre
Operating system: Windows 11, 8gb ram, AMD Ryzen 5000 Series

**Comment by OneShot-Niko** [comment]
Can't repro on firefox, works fine for me.
![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/8b8fcb2c-b821-41a8-a58e-f97b63668000)

This might be a chromium only issue

**Comment by mxmou** [comment]
Can reproduce on Edge and Firefox.

**Comment by mybearworld** [comment]
This only seems to happen when no easter egg addons are enabled.

**Comment by Waakul** [comment]
> This only seems to happen when no easter egg addons are enabled.

i didn't have any easter egg addon enabled indeed

**Comment by DNin01** [comment]
Might be the same issue as #5847
