### ISSUE TITLE
fullscreen in project page  doesnt show "customizable website colors and dark mode" settings

### ISSUE THREAD

**Issue by Waakul** [ScratchAddons/ScratchAddons#7221]
### Description

fullscreen in project page  doesnt show "customizable website colors and dark mode" settings
![image](https://github.com/ScratchAddons/ScratchAddons/assets/135821321/2ea7eca6-ab29-4f06-8908-ca109d9960c7)

### Steps to reproduce

1.turn on the "customizable website colors and dark mode"
2.set the colors to whatever you want
3.go to a project page
4.go fullscreen
5.observe that the colors are not applied

### Environment

Browser: Microsoft edge 121.0.2277.128 (Official build) (64-bit) 
Scratch Addons version: v1.37.0-pre
Operating system: Windows 11

**Comment by mxmou** [comment]
This is intentional - full screen is controlled by editor dark mode.

**Comment by Samq64** [comment]
Related: #5210
