### ISSUE TITLE
Make square block inputs addon a setting in the "customizable block shape" addon

### ISSUE THREAD

**Issue by Waakul** [ScratchAddons/ScratchAddons#7224]
Make square block inputs addon a setting in the "customizable block shape" addon because it's where it belongs to..

**Comment by WorldLanguages** [comment]
I think I disagree, "customizable block shape" shouldn't handle the shape of the block inputs.

**Comment by BroJac5246** [comment]
> I think I disagree, "customizable block shape" shouldn't handle the shape of the block inputs.

Why? It seems like a logical place.

**Comment by WorldLanguages** [comment]
Maybe it's just me, but when I think about "block shape" I think of the exterior shape.

If you buy a Vercel.com cup, and change the triangle for a circle, you're not changing the shape of the cup.

![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/f9072997-56ab-4ed8-934a-ab939d0dfcec)

**Comment by Samq64** [comment]
I think we've also been going towards more smaller addons instead of fewer addons with a bunch of settings. See #3957
