### ISSUE TITLE
Add option to show the addon ID

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#726]
**Is your feature request related to a problem? Please describe.**

Sometimes I wanted to check the ID of an addon for developing purposes, but then I sometimes confused because the ID an addon is sometimes not the same as the name of the addon.

**Describe the solution you'd like**

I propose to add an option/setting to show the ID of all addon. I think the best way is to place the ID besides the name, styled with a gray color. This option should be added on the more settings page, of course.

**Comment by GrahamSH-LLK** [comment]
It's crazy how many theoretical settings we've come up with! This could be part of a "developer mode". 
Some things I've come up with for that:
- Button to refresh the extension
- Disable the "farewell" and "welcome" things
- Other developer-related things

**Comment by mxmou** [comment]
> This could be part of a "developer mode".

Then debug messages could be disabled when not in developer mode.

**Comment by YOYITsM3M8** [comment]
why would u wanna disable the farewell and welcome bc those are when you install or remove

**Comment by GrahamSH-LLK** [comment]
> why would u wanna disable the farewell and welcome bc those are when you install or remove

Yeah. They're annoying when you redownload the zips, and uninstall.

**Comment by YOYITsM3M8** [comment]
i dont get the disable welcome message part. you cant enable the addon before it installs

**Comment by GrahamSH-LLK** [comment]
(I know, I know)

**Comment by Hans5958** [comment]
poor graham need to redownload the whole thing again instead of git pull

/s

**Comment by WorldLanguages** [comment]
> Yeah. They're annoying when you redownload the zips, and uninstall.

Please git pull...

**Comment by WorldLanguages** [comment]
Well, at the moment we have a pretty good way to detect whether you're a dev or not - if the `version_name` ends in `-prerelease`. So I don't see any issue if we add the addon ID somewhere (maybe at the beginning of the description?) in that case.

**Comment by Hans5958** [comment]
I sometimes do it on the release version first, instead of just go straight on the dev version. Also, it is not hurt for having the settings instead of detect it yourself and some bad things happened in the future.

Also, I think it is better to write it next to the name, but slightly faded.
