### ISSUE TITLE
Bring back "Record Project" feature.

### ISSUE THREAD

**Issue by sargent-coding** [ScratchAddons/ScratchAddons#728]
**Describe the new addon**

"The record project video option was a feature in the Scratch User Interface, added on December 21, 2015, which allowed Scratchers to record Scratch projects without any third-party screen recording software. This feature was removed in Scratch 3.0."

**Link to the new addon**

https://en.scratch-wiki.info/wiki/Record_Project_Video

**Comment by GrahamSH-LLK** [comment]
This would be an interesting, although tricky feature. @apple502j has implemented this in a fork of scratch, so it _might_ be possible with an addon.

**Comment by mxmou** [comment]
@GrahamSH-LLK It's definitely possible, the addon would just need to record the canvas using `MediaStream`.

**Comment by JeffaloBob** [comment]
i might mess around to try making this, recording the audio and syncing it up might be a bit weird though.

on the topic of audio, what if we go all-out and add microphone input, and why not record the whole editor 😀

**Comment by GrahamSH-LLK** [comment]
https://github.com/LLK/scratch-gui/issues/5699

**Comment by WorldLanguages** [comment]
@apple502j It would be cool to see this get added.

**Comment by Marc92020** [comment]
This would be a great feature to add back! Although I only joined this year and I don't really know about 2.0, this would be awesome to have this feature back!

Here is an example:
![Screenshot 2020-12-08 at 5](https://user-images.githubusercontent.com/75702334/101560523-81767f80-3991-11eb-8c6d-a183e3168933.png)
