### ISSUE TITLE
`hide-backpack` + `custom-zoom` (auto hide zoom) : Cannot zoom in with button due to offset

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7286]
### Description

Red line here marks the spot, trying to hover here results in the zoomcontrols dissapearing.
![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/50d9d832-348a-4d6c-a6ff-ccc2e1a6c651)

### Steps to reproduce

1. enable `hide-backpack` and `custom-zoom`'s "auto hide zoom controls" option, speed set to instant.
2. go to the editor
3. try to zoom in with the button

### Demonstration(s) and additional context

~~Sorry, I don't have enough time for this right now. I can do it tommorow though.~~
right here

https://github.com/ScratchAddons/ScratchAddons/assets/150537842/7a3f3ef2-e3da-4891-9f8a-1ff6050112ee

### Environment

Browser: Firefox 123.0.1 (32 bit)
Scratch Addons version: [43807be](https://github.com/ScratchAddons/ScratchAddons/commit/43807bebf739f8757cb5cc36581cf39aab29865b)
Operating system: Windows 10 (screen size: 1366 x 768)

**Comment by WorldLanguages** [comment]
You report the best bugs 👑

**Comment by OneShot-Niko** [comment]
> You report the best bugs 👑

nono please dont overcredit me there even with sarcasm

**Comment by WorldLanguages** [comment]
Now seriously, not being able to zoom in is quite bad. I think we should fix this before release, or remove the hide-backpack addon until it's fixed

**Comment by mybearworld** [comment]
`editor-compact` doesn't seem to be needed for this to happen.

**Comment by OneShot-Niko** [comment]
> `editor-compact` doesn't seem to be needed for this to happen.

My bad for not checking without compact editor off.

> Now seriously, not being able to zoom in is quite bad. I think we should fix this before release, or remove the hide-backpack addon until it's fixed

As for a possible solution, maybe a checksum as to if `.sa-backpack-button` exists, and then move `sa-custom-zoom-area` (which if im not mistaken is the area checking for mouse hovering) up? Though that's probably hard dynamically.
