### ISSUE TITLE
What to do for April Fools 2024?

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#7295]
We have 2/3 days to think whether we want to add some April Fools easter-egg/joke this year. There's a draft PR at #7217

We might also want to check what Scratch will do for April Fools (specially in the editor) and possibly prevent any potential bugs by disabling some addons during that day, like we've done in prior years.

**Comment by DNin01** [comment]
If it's getting late, we could always try to do something to the settings page so we don't have to worry as much about potential bugs... maybe some sort of game inside the extension popup?

**Comment by WorldLanguages** [comment]
Maybe we could redo the 2022 joke, but instead of `Scratch Avocados` it could be `Scratch Haddocks` 🐟 
hehe

**Comment by mybearworld** [comment]
Haddock is a much less frequent word than Avocado, though.

**Comment by DNin01** [comment]
https://github.com/ScratchAddons/ScratchAddons/assets/106490990/8d9bfc64-f8a7-4974-8199-ca3b14c6b877

**Comment by mybearworld** [comment]
> Spinning.icons.in.Scratch.Addons.extension.popup.mp4

If we do that, it should probably be disabled if the user has [opted out of unnecessary motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion).

**Comment by WorldLanguages** [comment]
> Haddock is a much less frequent word than Avocado, though.

That makes it more fun. Just like "dango", people will google it to see what it means.

**Comment by BroJac5246** [comment]
> Maybe we could redo the 2022 joke, but instead of `Scratch Avocados` it could be `Scratch Haddocks` 🐟 
> hehe (see #4436 for avocados)

Another option would be kumquats but that might be more fun in the future if we plan a whole thing around that instead of just a rebrand.

**Comment by WorldLanguages** [comment]
Review my PR #7299 or submit something better 😂

**Comment by Waakul** [comment]
Maybe change the addons tab name to Haddocks? That might require lot of translation changes tho. Is that a problem? We could also change the addons wrench icon to a haddock icon.

**Comment by Waakul** [comment]
Maybe replace the dropdown icons with a haddock points down/up

**Comment by DNin01** [comment]
Resolved by #7299?

**Comment by mybearworld** [comment]
Is it likely for a lot of users to have received the update when the Scratch Haddocks thing starts?

**Comment by WorldLanguages** [comment]
I don't know, we'll see

**Comment by mybearworld** [comment]
Oh cool, I just got the update. Looks like I severely overestimated how long the CWS process takes :P

**Comment by mybearworld** [comment]
Yeah, that's why I'm using SA from the Chrome store and not from the Edge store

**Comment by SoupBoot** [comment]
Honestly it's pretty neat seeing you guys brainstorm this update two days later. Simple but great update guys! Good work! :D
