### ISSUE TITLE
`download-button`: Spinner color should adapt to button background

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#7296]
### Description

If you use `dark-www` to change the highlight color of Scratch, one would expect text and icons to become black to contrast well.

But actually, the spinner stays white.

### Steps to reproduce

1. Enable `download-button`
2. Use `dark-www` to change `HIGHLIGHT COLOR` to a light color, enough to make the text turn black
3. Click the Download button

### Demonstration(s) and additional context

![Button row with lavender download button that has a white spinner icon on it](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/b0b0836f-4a4c-421a-8575-ddc414631561)

### Environment

Scratch Addons version: 3ebb4a15d68de20af9e6c96a3cb35af55aa54175

@Jazza-231

**Comment by Jazza-231** [comment]
Oh what the hell I swear I added this...must have removed it when I changed the spinner...thanks man

**Comment by Jazza-231** [comment]
fixed
