### ISSUE TITLE
[Feature] Telling the user that there is an update available

### ISSUE THREAD

**Issue by BoomerScratch** [ScratchAddons/ScratchAddons#73]
We can use `chrome.runtime.getManifest().version` to get the current extension version, and then we can fetch [the manifest on raw.githubusercontent.com](https://raw.githubusercontent.com/ScratchAddons/ScratchAddons/master/manifest.json). We can also fetch the CRX file from the chrome web store, extract it and read the manifest.json for more accuracy, but that requires more work and libraries.

If the manifest version doesn't equal, the user will be notified. We need to discuss a way to notify the user. If the user then opens the pop-up (the window that appears when clicking the extension icon), a message will appear saying that there is an update available. It also tells the user how to update the extension.

In the options page, there should also be a switch that disables/enables update notifications (enabled by default) and a number input which allows the user to change the update check interval. (I recommend 1 hour as the default value)

(I know that Chrome updates extensions automatically, but this is just something useful idk)

**Comment by WorldLanguages** [comment]
I don't see the point really, Chrome updates quite often

**Comment by JeffaloBob** [comment]
this is very off topic but i think it would be cool if there was like a global notification system so that addons can send notifications and stuff and also maybe once in a while, a notification could be pushed to all users (eg. Version 7 now available, update now) or something

**Comment by WorldLanguages** [comment]
@JeffaloBob The addon loader already proxies sent notifications, but at the moment they aren't stored anywhere after being sent. If we implement muting (#9) maybe we can let the user know what notifications they missed?

**Comment by GrahamSH-LLK** [comment]
This could be a dev mode only feature. The chrome web store updates too frequently for this to be an issue.

**Comment by TheColaber** [comment]
As far as I see, this won't work because of the way we do the system. Very soon, we will bump the version to 1.5.0 on gh, and users would be notified if this were implemented.

**Comment by RedGuy12** [comment]
I don't think this is needed. My browser auto-updates.

**Comment by TheColaber** [comment]
> I don't think this is needed. My browser auto-updates.

This is useful as easrng said,
> This is helpful for people sideloading.

**Comment by mxmou** [comment]
> > I don't think this is needed. My browser auto-updates.
> 
> This is useful as easrng said,
> 
> > This is helpful for people sideloading.

Yes, but it isn't helpful for normal users at all because there is no way to force the browser to update an extension - what's the point of an "update available" message if you can't install it?

**Comment by jeffalo** [comment]
doing `git pull` every morning isn't that hard

**Comment by GrahamSH-LLK** [comment]
Can this be closed?

**Comment by WorldLanguages** [comment]
Eh, if we ever provide an official way for Safari users to sideload SA this would be a good addition (since they'd have to update manually pretty much)

**Comment by RedGuy12** [comment]
> if we ever provide an official way for Safari users to sideload SA this would be a good addition

**if we ever**
