### ISSUE TITLE
Shouldn't exact count show 'posts' after it?

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#731]
Currently it shows this:
![image](https://user-images.githubusercontent.com/61319150/98823224-71ea3200-23f7-11eb-908a-cf886b6d5a2c.png)
If it said something like ```6769 posts``` that would be a little better lol

**Comment by WorldLanguages** [comment]
I've seen someone report this through feedback. @Explosion-Scratch Can you send a link to that post?

**Comment by TheColaber** [comment]
> I've seen someone report this through feedback. @Explosion-Scratch Can you send a link to that post?

No, "posts" was meant to go in the code but it didn't. #733 fixes this but I wanted to change it a bit first.
