### ISSUE TITLE
h1 border goes into the logo in README

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#7313]
Well, this is probably the most insignificant issue SA has ever gotten, but:

![The "Scratch Addons" text in the README with a line under it, which also goes into the SA logo next to it.](https://github.com/ScratchAddons/ScratchAddons/assets/130385691/54223f89-bc02-4c6c-aa02-45f7fdbff3db)

The line's inside of the SA logo.

**Comment by OneShot-Niko** [comment]
Looks like a change in the md parser since this didn't happen before

**Comment by BroJac5246** [comment]
![Screenshot_20240329-134635.png](https://github.com/ScratchAddons/ScratchAddons/assets/104146239/10b1bc20-ba84-4e92-8b3a-b654739602a1)

On Android, I'm not able to reproduce. I am able to reproduce on Chrome. It is likely this is an upstream bug with GitHub.

**Comment by mybearworld** [comment]
Looks like that's the GitHub app? It probably renders Markdown slightly differently.

**Comment by BroJac5246** [comment]
> Looks like that's the GitHub app? It probably renders Markdown slightly differently.

Yeah that's what I'm referring to.

**Comment by OneShot-Niko** [comment]
> -snip-
> On Android, I'm not able to reproduce. I am able to reproduce on Chrome. It is likely this is an upstream bug with GitHub.

Try having darkmode on. Also, from what I can tell, it _does_ happen in your screenshot:
![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/e4fe6fcf-bf04-4025-af95-0966c96f65e8)

**Comment by mybearworld** [comment]
It doesn't happen in their screenshot, I think you're encountering an optical illusion there :P

**Comment by BroJac5246** [comment]
> > -snip-
> > On Android, I'm not able to reproduce. I am able to reproduce on Chrome. It is likely this is an upstream bug with GitHub.
> 
> Try having darkmode on, I'm able to repro with it. Also, from what I can tell, it _does_ happen in your screenshot:
> ![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/e4fe6fcf-bf04-4025-af95-0966c96f65e8)

In my screenshot the border passes under the logo, while in yours it passes over the logo. Neither is ideal, though.

The behavior is the same for me regardless of theme.

**Comment by OneShot-Niko** [comment]
> It doesn't happen in their screenshot, I think you're encountering an optical illusion there :P

I may or may not need my glasses again in that case. My apologies.

> In my screenshot the border passes under the logo, while in mybearworld's it passes over the logo. Neither is ideal, though.
> 
> The behavior is the same for me regardless of theme.

My apologies then.

**Comment by BroJac5246** [comment]
> > It doesn't happen in their screenshot, I think you're encountering an optical illusion there :P
> 
> I may or may not need my glasses again in that case. My apologies.
> 
> > In my screenshot the border passes under the logo, while in mybearworld's it passes over the logo. Neither is ideal, though.
> > 
> > The behavior is the same for me regardless of theme.
> 
> My apologies then.

No worries!
