### ISSUE TITLE
Data Category Tweaks no longer working!

### ISSUE THREAD

**Issue by HexHands** [ScratchAddons/ScratchAddons#7323]
### Description

The Data Category Tweaks no longer splits the variable list into Public and Private variables.

### Steps to reproduce

1. Enable Data Category Tweaks
2. Look at the variable list

### Demonstration(s) and additional context

![Capture](https://github.com/ScratchAddons/ScratchAddons/assets/119904427/90e5f560-4f53-4f76-a7e5-d13a635bfea5)

### Environment

Browser: Firefox
Scratch Addons version: v1.37.0
Operating system: Windows

**Comment by DNin01** [comment]
Are you sure you've configured it to group them by whether they're global or local?

![Data category tweaks addon settings](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/a94b3fc0-e9b7-4bec-a9fe-3693b2699150)

Only issue I could think of is our April Fools detection going wrong (the April Fools features in the editor don't play nice with some addons so we detect if April Fools features are active and disable the addons if so), but all the addons are still working for me (Scratch also hasn't done anything to the editor for April Fools' Day this year).

It could also be browser-specific, or just a chance thing.

**Comment by DNin01** [comment]
I'm on Edge 123, BTW.

**Comment by DNin01** [comment]
@WorldLanguages Any idea what's going on here?

**Comment by WorldLanguages** [comment]
Right now, it will work around 50% of the time. @HexHands Try reloading the page until it works.

**Comment by WorldLanguages** [comment]
It's a race condition, so I didn't notice this problem before releasing. I was also running out of time.

I also unfortunately forgot to add a condition to the April Fools detection code that would conclude it's definitely not April Fools if it's April 3rd or later. Looks like we'll need to release 1.37.1 just to fix this 😅

**Comment by HexHands** [comment]
I have reloaded the page about 8 times and it has not worked. I believe that since this is a race condition and I have a big project those 2 do not mix well together.

**Comment by DNin01** [comment]
We should definitely do some research on this problem way before April 1st next year so Scratch Addons won't misjudge whether the April Fools surprises are active.

**Comment by BroJac5246** [comment]
> We should definitely do some research on this problem way before April 1st next year so Scratch Addons won't misjudge whether the April Fools surprises are active.

Are we going to revert the April Fools' PRs and then immediately release v1.37.1? The sooner we do that, the sooner this will be fixed. It shouldn't take that long and it's already April 3 in some areas.

**Comment by WorldLanguages** [comment]
> We should definitely do some research on this problem way before April 1st next year so Scratch Addons won't misjudge whether the April Fools surprises are active.

You do it next year 😄

**Comment by mybearworld** [comment]
It was very rushed this year, doing it a bit earlier in advance would probably go a long way next year

**Comment by WorldLanguages** [comment]
> We should definitely do some research on this problem way before April 1st next year so Scratch Addons won't misjudge whether the April Fools surprises are active.

@DNin01 #8212
