### ISSUE TITLE
No hover effect on hovering header buttons

### ISSUE THREAD

**Issue by Waakul** [ScratchAddons/ScratchAddons#7329]
### Why this would be helpful

There is currently no hover effect on header buttons such as theme/settings and thus it's hard to see that you're hovering it especially when it comes to accessibility.

### My suggestion

My suggestion is to set the background color of the header button to the ```hover-darken``` CSS variable on hover.

### Additional context

![image](https://github.com/ScratchAddons/ScratchAddons/assets/135821321/10c81286-35b3-4bc7-9c6a-e45a4acdeb20)

**Comment by Samq64** [comment]
https://github.com/ScratchAddons/ScratchAddons/pull/7285#discussion_r1536679029

> I'll remove that for now, and add it back when i create a pr for hover background (which will first require this pr to be merged)

**Comment by DNin01** [comment]
Sure, why not?
