### ISSUE TITLE
10-digit project IDs coming

### ISSUE THREAD

**Issue by Secret-chest** [ScratchAddons/ScratchAddons#7351]

**Comment by DNin01** [comment]
I skimmed through and I don't believe there are any cases where this would be a problem. I'd expect we would write our code with project IDs of arbitrary length in mind.

Of course, if you do find any bugs, let me know.

**Comment by Secret-chest** [comment]
They came...

**Comment by CubesterYT** [comment]
https://scratch.mit.edu/projects/1000000000

🫡

**Comment by Waakul** [comment]
coming? it came like 2 hours ago...

**Comment by Duolingoguy** [comment]
so there are more projects shared on scratch than levels in gd? cool

**Comment by Samq64** [comment]
I don't see any console errors on a 10-digit project page with all addons enabled. If it does break something please open a more specific issue.
