### ISSUE TITLE
`editor-dark-mode`: URL color is handled weirdly

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7354]
### Description

`editor-dark-mode` can have a bit of issues with URLs

### Steps to reproduce

1. enable editor dark mode
2. change settings a bit (see extra context for the settings i got this with)
3. make a cloud variable

### Demonstration(s) and additional context

For comparison, editor dark mode and normal:
![editor darkmode](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/f8193429-ddea-4db9-96f6-d9ea4986970e)

![normal](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/1b28016b-0e20-4378-a8ec-f7152b764b65)

<details><summary>Settings</summary>
<p>
"editor-dark-mode":{"enabled":false,"settings":{"page":"#222222ff","primary":"#593e91ff","highlightText":"#ffffffff","menuBar":"#6e4cb2ff","popup":"#855cd65c","activeTab":"#431c8eff","tab":"#040351ff","selector":"#070303ff","selector2":"#202020","selectorSelection":"#2c1c44ff","accent":"#1b1919ff","input":"#000000ff","workspace":"#070707ff","categoryMenu":"#202020","palette":"#202020cc","fullscreen":"#000000ff","stageHeader":"#000000ff","border":"#855cd666","dots":false,"affectPaper":true,"affectStage":true,"_version":10}}
</p>
</details> 

### Environment

Browser: Firefox 124.0.2 (32 bit)
Scratch Addons version: 3c9b881
Operating system: Windows 10

**Comment by Samq64** [comment]
`highlightText` is set to white but the banner isn't dark like other backgrounds that use it.

**Comment by mxmou** [comment]
Website dark mode changes messages like this to a darker shade of green:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/39ef2b0c-27ae-426b-a3a6-bb7de0eff3ec)

Editor dark mode should probably do the same.

**Comment by WorldLanguages** [comment]
Keywords for search: "cloud variables only supports numbers learn more"
