### ISSUE TITLE
Option to toggle orange outlines

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#736]
**Is your feature request related to a problem? Please describe.**

Some addons add new features to Scratch's user interface, which have an orange outline so the user can see they aren't a Scratch feature. For some people these outlines might be annoying.

**Describe the solution you'd like**

An option to toggle them - it should be in More Settings and apply to all addons.

**Comment by TheColaber** [comment]
And would probably be enabled automatically.

Note: The Thumbnail Setter has a red outline...

**Comment by Hans5958** [comment]
> And would probably be enabled automatically.

Umm, it is enabled automatically, and can't be turned off.

**Comment by sargent-coding** [comment]
Maybe replace the red with white?

**Comment by mxmou** [comment]
> Maybe replace the red with white?

Then it wouldn't be very noticeable.

**Comment by TheColaber** [comment]
> > Maybe replace the red with white?
> 
> Then it wouldn't be very noticeable.

Orange is the theme of scratch addons so it should be the theme of the buttons.

**Comment by JeffaloBob** [comment]
![image](https://user-images.githubusercontent.com/40470736/99578679-71e0c800-29dd-11eb-9ceb-8750f06bb1d0.png)

**Comment by TheColaber** [comment]
More like this: 
![image](https://user-images.githubusercontent.com/72760579/99580342-5e1d6d80-29ad-11eb-8d22-7f28676cf417.png)
