### ISSUE TITLE
Customize Home Screen

### ISSUE THREAD

**Issue by BlueGoat11** [ScratchAddons/ScratchAddons#7362]
### Why this would be helpful

Sometimes I wish I was able to hide some stuff on the home screen e.g. Projects Curated by ___. What if you could hide those? I just had the idea and don't know if this is a dupe (plz close if it is) but think it would be useful.

### My suggestion

It would be helpful to include an option to add a profile or studio link to replace rows with, other than the random stuff or other less useful rows.

**Comment by Samq64** [comment]
Duplicate of #1758.
