### ISSUE TITLE
Notifs act weird

### ISSUE THREAD

**Issue by sargent-coding** [ScratchAddons/ScratchAddons#737]
**Describe the bug**

Web notifs open [chrome://newtab](chrome://newtab) instead of intended target. Sometimes, if there is multiple, only one will go to the correct page.

**To Reproduce**

null

1. Open computer (Dell Chromebook 11 [owned by school])
2. Click on notif
3. See error

**Expected behaviour**

Go to target.

**Screenshots**

null

**Device (please complete the following information):**

- OS: Google Chrome OS 64-bit
- Browser: Chrome 86

**Additional context**

null

**Comment by WorldLanguages** [comment]
Hmm, that's weird. I can't think of any reason it would open `chrome://newtab`. Worst that could happen is opening an invalid URL (with some expected value being `null`, getting reflected to the URL)

**Comment by TheColaber** [comment]
This happens to me too...

**Comment by TheColaber** [comment]
The notification looks like this for me (if that's any correlation)
![image](https://user-images.githubusercontent.com/72760579/98864413-d75e1300-2437-11eb-8b9d-990fb8ec9755.png)

**Comment by WorldLanguages** [comment]
This means somehow `url` is null/undefined on line  https://github.com/ScratchAddons/ScratchAddons/blob/master/addons/scratch-notifier/background.js#L144

**Comment by WorldLanguages** [comment]
@TheColaber Does this always happen to you, with the same type of message?

**Comment by TheColaber** [comment]
> @TheColaber Does this always happen to you, with the same type of message?

ALL THE TIME :( At one point they looked like this: 
![image](https://user-images.githubusercontent.com/72760579/98865418-5a339d80-2439-11eb-8959-e938affcee37.png)
But then one day, they changed

**Comment by TheColaber** [comment]
> > @TheColaber Does this always happen to you, with the same type of message?
> 
> ALL THE TIME :( At one point they looked like this:
> ![image](https://user-images.githubusercontent.com/72760579/98865418-5a339d80-2439-11eb-8959-e938affcee37.png)
> But then one day, they changed

Also the sound the default sound doesn't play but our ScratchAddons sound does.

**Comment by WorldLanguages** [comment]
@TheColaber I'm not talking about the looks of the notification, we changed that intentionally. I'm talking about clicking the notification opening a new tab

**Comment by TheColaber** [comment]
> @TheColaber I'm not talking about the looks of the notification, we changed that intentionally. I'm talking about clicking the notification opening a new tab

Oh... yeah when I click on any button or just the notification, it goes to a new tab

**Comment by sargent-coding** [comment]
OK, so this isn't just me.

**Comment by YOYITsM3M8** [comment]
it happened to me a couple of times earlier today

**Comment by GrahamSH-LLK** [comment]
Could this have something to do with getting signed out or something? I'm trying to repro, but it won't happen.

**Comment by YOYITsM3M8** [comment]
> Could this have something to do with getting signed out or something?

I was definitely signed in.

**Comment by WorldLanguages** [comment]
`url` was undefined if it was a studio activity message, maybe that was it?

**Comment by TheColaber** [comment]
> `url` was undefined if it was a studio activity message, maybe that was it?

No, it still doesn't work with other messages like this one: 

![](https://user-images.githubusercontent.com/72760579/98864413-d75e1300-2437-11eb-8b9d-990fb8ec9755.png)

**Comment by TheColaber** [comment]
I believe this is no longer a problem... I just like the darkmode notification better but...

**Comment by TheColaber** [comment]
I can confirm this is no longer an issue.

https://user-images.githubusercontent.com/72760579/108151912-c7dd0e80-70a5-11eb-92d4-e266a20781f1.mp4
