### ISSUE TITLE
Image file metadata and the `better-img-uploads` addon

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#7380]
It has been reported through the feedback page that:

> The HD image uploader does not remove information from the metadata of images. This can lead to geolocation data being preserved, which is a privacy risk. 

If uploading the image normally through vanilla Scratch upload does cause the metadata to be removed for some reason, then we should consider changing our addon so that it's also removed.

**Comment by DNin01** [comment]
I remember that metadata of audio files (artists, year, etc.) is preserved when uploaded into a project, and anyone can see it by exporting and downloading the audio track from the project. I haven't checked if the same applies to images or SVGs.

We can't really do anything if that is the case, other than maybe make an addon that omits metadata from all uploads?

**Comment by WorldLanguages** [comment]
Can you check?

**Comment by DNin01** [comment]
> Can you check?

I uploaded (normally) a JPEG image with an author and copyright specified and the metadata was not present in the exported file.

I was able to get the metadata by decoding the base64 of the image in the SVG file when uploading it with the HD uploads addon, so this issue can be confirmed.

**Comment by OneShot-Niko** [comment]
shouldnt this be reported as a security vulnerability instead of made as a normal issue?

**Comment by BroJac5246** [comment]
This seems dangerous, given that Scratch is targeted at kids. The priority should always be user safety, so I think we should fix this ASAP. 

We could also consider adding a separate addon that removes metadata from sounds and maybe even existing images.
