### ISSUE TITLE
An AI assistant

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#7396]
### Why this would be helpful

AI can help answer questions and speed up development. Just take a look at GitHub Copilot.

### How this addon works

This addon would add a button to open a panel where you could talk to an AI assistant that could explain Scratch lingo and code, and even make changes to scripts.

<details><summary>Concept screenshots</summary>
<p>

> ![A button with sparkles below the zoom controls](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/f1859e18-8f72-480e-8842-3462ae439233)
> ![A window with a response to a code question from a conceptual AI chatbot](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/ac26e410-2dc5-4cd9-89c2-39d5b43138cd)
> ![A window with a response and example code to a question from a conceptual AI chatbot](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/13e04dc6-887f-4496-b184-b0f20115c8cd)

<sub>Not actual AI responses.</sub>

</p>
</details> 

Another potential AI feature could be code autocomplete, where sometimes ghosts of blocks that you might be placing next would show up next to blocks you just placed, and you could click them to insert them.

![Three pictures laid horizontally, the first is of a block being dragged into a forever loop, the second has a ghost of another block below that block, and a cursor clicking it, and the third is after that block has been clicked, after which it becomes a real block](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/10fef0ff-6adb-4990-85c4-4d1216bb6bd0)

### Additional context

Fun fact: Griffpatch Academy has an AI chatbot (I think it's called GriffBot?) that you can ask for help with Scratch and coding.

At this point in time, we'll probably need to communicate with a server or API such as ChatGPT or make a server of our own (which is probably not happening), but it's possible that in the future this will be possible on-device.

**Comment by BroJac5246** [comment]
Where would we get API keys? Unless someone wants to donate their 4090, this would wind up being crazy expensive over time.

**Comment by Secret-chest** [comment]
Not to mention GPT hardly knows Scratch.

**Comment by BroJac5246** [comment]
> Not to mention GPT hardly knows Scratch.

I've been impressed with how much ChatGPT and Gemini know, so I actually do think they could figure it out as long as they're provided good context.

**Comment by DNin01** [comment]
> It does need some work...

It might be better at answering simpler questions like "what does the 'next costume' block do?"

But still, it'd probably be a hundred times better if we or someone were able to train a model to answer Scratch-related questions and code.

**Comment by Secret-chest** [comment]
> Hmm, it looks like this already exists! https://tabnine.com

Not open source, requires server, Scratch is hard to autocomplete, not possible in JS.

**Comment by BroJac5246** [comment]
> > Hmm, it looks like this already exists! https://tabnine.com
> 
> Not open source, requires server, Scratch is hard to autocomplete, not possible in JS.

Also, LLMs are ginormous. Even a 2B parameter LLM (I have some that I run locally on my phone) is more than a gigabyte, and the performance isn't even that good at that size.

**Comment by Secret-chest** [comment]
How would we even give the scripts to the LLM? Like, what format? We need to invent Large Coding Block Models or something.

**Comment by mybearworld** [comment]
> How would we even give the scripts to the LLM? Like, what format? We need to invent Large Coding Block Models or something.

scratchblocks? That might make it make up blocks, though.

**Comment by Chiroyce1** [comment]
Unless the user provides their own API key and we feed the LLM custom data on how the Scratch editor, blocks, costumes, clones, etc work - this shouldn't be considered, it'll be way too inaccurate.

**Comment by BwnnyRxbbit** [comment]
> Unless the user provides their own API key and we feed the LLM custom data on how the Scratch editor, blocks, costumes, clones, etc work - this shouldn't be considered, it'll be way too inaccurate.
> 
> > Fun fact: Griffpatch Academy has an AI chatbot (I think it's called GriffBot?) that you can ask for help with Scratch and coding.
> 
> That is very likely to be trained with the video captions - so it'll be able to answer everything related to the video and similar concepts, but I don't think it can handle any other doubts or bugs.

Maybe our's can be to answer questions about SA?

**Comment by BroJac5246** [comment]
> > Unless the user provides their own API key and we feed the LLM custom data on how the Scratch editor, blocks, costumes, clones, etc work - this shouldn't be considered, it'll be way too inaccurate.
> > 
> > > Fun fact: Griffpatch Academy has an AI chatbot (I think it's called GriffBot?) that you can ask for help with Scratch and coding.
> > 
> > That is very likely to be trained with the video captions - so it'll be able to answer everything related to the video and similar concepts, but I don't think it can handle any other doubts or bugs.
> 
> Maybe our's can be to answer questions about SA?

But who wants that? It just detracts from the focus on coding.

**Comment by BwnnyRxbbit** [comment]
> > > Unless the user provides their own API key and we feed the LLM custom data on how the Scratch editor, blocks, costumes, clones, etc work - this shouldn't be considered, it'll be way too inaccurate.
> > > > Fun fact: Griffpatch Academy has an AI chatbot (I think it's called GriffBot?) that you can ask for help with Scratch and coding.
> > > 
> > > 
> > > That is very likely to be trained with the video captions - so it'll be able to answer everything related to the video and similar concepts, but I don't think it can handle any other doubts or bugs.
> > 
> > 
> > Maybe our's can be to answer questions about SA?
> 
> But who wants that? It just detracts from the focus on coding.

Maybe we can add it to our website if unable to make the code one on scratch? It would still be pretty cool!

**Comment by BroJac5246** [comment]
> > > -snip- 
> > > Maybe our's can be to answer questions about SA?
> > 
> > But who wants that? It just detracts from the focus on coding.
> 
> Maybe we can add it to our website if unable to make the code one on scratch? It would still be pretty cool!

Everyone's sick of pointless AI right now. If one really wants to ask AI about Scratch Addons then they can just open Gemini or ChatGPT and ask there.

**Comment by Joeclinton1** [comment]
I've thought about integrating LLMs with Scratch alot actually, and I have the knowledge to do it, but it is a research level project. It will obviously cost money that someone has to pay and this is not for ScratchAddons to do. This is more for Scratch themselves or a startup. Abandon idea before you waste any more time on futile thinking.

**Comment by DNin01** [comment]
I have been thinking, this may be better as a non-Scratch Addons project.

**Comment by DNin01** [comment]
I don't think this is going to catch on at this point in time. It might be worth for us to revisit once LLMs become efficient and portable enough. However, it's a great idea and I could see it becoming its own project.

**Comment by nakasyou** [comment]
I would like to implement this.

Now, there are many LLM providers such as Cohere, Groq and Gemini. It has free plans.
So, what do you think about using user's token?
By this way, you don't need payment.

**Comment by BroJac5246** [comment]
> I would like to implement this.
> 
> Now, there are many LLM providers such as Cohere, Groq and Gemini. It has free plans.
> So, what do you think about using user's token?
> By this way, you don't need payment.

There's an adage that says _"If you're not paying for it, you're the product."_ That's a bit of a problem with a service used primarily by kids. 

Plus, it would be quite cumbersome for the average user to find their own tokens.
