### ISSUE TITLE
Change the color of the warning and notice texts

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#742]
The current color for the warning and notice texts are red and yellow, which I think people may be unable to differentiate the purpose of the texts straight away. How about change them to yellow and light blue respectively, just like how browser logs work?

**Comment by GrahamSH-LLK** [comment]
What? Red = error/warning Yellow = notice It aligns pretty well with logs and makes sense.

**Comment by Hans5958** [comment]
Errors are red and warnings are yellow on console logs. Info is none, but it is quite common that they give blue on that.

![image](https://user-images.githubusercontent.com/11584103/99084230-46369a00-25f9-11eb-8c29-ba8d798383a9.png)

![image](https://user-images.githubusercontent.com/11584103/99084261-4df63e80-25f9-11eb-82a0-1df2f8c7a5ee.png)

https://css-tricks.com/a-guide-to-console-commands/

**Comment by mxmou** [comment]
The point of notices and warnings is that we want people to read them. Making their colors less prominent is probably not a good idea.

**Comment by WorldLanguages** [comment]
Styling changed since this suggestion was made. Another issue must be made if appropriate
