### ISSUE TITLE
`old-studio-layout`: "You will be able to edit studios again (...)" modal is oversized on titles

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7440]
### Description

This a really minor bug.

### Steps to reproduce

1. enable `old-studio-layout`
2. be muted (automodmute presumably)
3. hover over the title of a studio you own

### Demonstration(s) and additional context

![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/9684e117-16ac-4f97-ab11-fd0e58a83328)

### Environment

Browser: Firefox 126.0 (32 bit)
Scratch Addons version: e6f38f6
Operating system: Windows 10

**Comment by Samq64** [comment]
In vanilla Scratch it looks like this:

![Screenshot_20240515_182002](https://github.com/ScratchAddons/ScratchAddons/assets/81489795/284a7873-b198-4883-a08b-d6549af54ab3)

**Comment by medlans** [comment]
(I had to disable like 2 extensions for this xD) This is what I see for the title, everything else seems fine.
![TitleChange](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/2a4316e0-0ce6-48e0-af02-45608463f453)
![DescriptionChange](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/d4d3fcec-4f3b-4603-9ce7-542468f92314)
![EditStudios](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/21033d68-88d3-40bf-ab0d-28c7a95ab382)
![SomethingWentWrong](https://github.com/ScratchAddons/ScratchAddons/assets/124630024/b795a3fd-0ad4-49ca-824a-c0e665dd6cfb)
Browser: Chrome 124.0 (64-bit)
Scratch Addons version: v1.38.0
Operating system: Mac OS 11.3 (Big Sur)
