### ISSUE TITLE
Webpage Creation

### ISSUE THREAD

**Issue by Vminchoco** [ScratchAddons/ScratchAddons#7447]

**Comment by Samq64** [comment]
https://packager.turbowarp.org/

**Comment by BroJac5246** [comment]
Could it be useful for this to be added as a button or part of the share pop-up?

**Comment by mxmou** [comment]
> Could it be useful for this to be added as a button or part of the share pop-up?

Addons for easier access to external sites/tools have previously been rejected (#762, #1821).
