### ISSUE TITLE
addon.tab.waitForElements (waitForElement but it returns array of elements/nodes)

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#745]
For (maybe only) `markAsSeen` cases, instead of `addon.tab.waitForElement` that makes the code needed to run in a loop until all elements are seen, is there a possibility for `addon.tab.waitForElements` (with an S), that instead of returning a single element like `document.querySelector`, it returns an array of elements like `document.querySelectorAll`?

**Comment by TheColaber** [comment]
I think it is easier how it is, because it returns like `querySelector` but acts like `querySelectorAll`

**Comment by Hans5958** [comment]
I think you missed something. `querySelectorAll` is similar as `querySelector`, with a difference of instead of returning the first match, it returns all of the matches.

**Comment by TheColaber** [comment]
> I think you missed something. `querySelectorAll` is similar as `querySelector`, with a difference of instead of returning the first match, it returns all of the matches.

Correct, but when using `addon.tab.waitForElement` it returns only one element but it does the following code to all elements that have the query. In a way it's like going through a list of matches and runs each one on the following code.

**Comment by Hans5958** [comment]
I still think you missed something, but I might understand a bit. In this case. I actually wanted to do that but instead of having 1000 queries, which might make the process tedious (but maybe negligible), we can do it with just one. Then, the code can run the rest of it without a need to query again.

Think about it, why do we have both `querySelector` and `querySelectorAll` in the first place?

**Comment by WorldLanguages** [comment]
Tbh at Scratch's scale, the difference between running querySelector multiple times (with markAsSeen) and querySelectorAll once is pretty negligible, but I can see the point for this.

**Comment by Hans5958** [comment]
Has this been implemented?

**Comment by TheColaber** [comment]
No but if this is for proformance purposes...
```js
console.time("test")
document.querySelectorAll("*").forEach((e) => e.classList.add("seen1"))
console.timeEnd("test")
console.time("test2")
while(e = document.querySelector("*:not(.seen2)")) e.classList.add("seen2")
console.timeEnd("test2")
```
![image](https://user-images.githubusercontent.com/72760579/121619756-12104400-ca37-11eb-928c-4fe4c65de459.png)
Than this is the only reason why this could be useful. But it's not likely that any addon can benefit from this anyway...

**Comment by WorldLanguages** [comment]
Just use while(true) with markAsSeen: true
