### ISSUE TITLE
Addons don't work when running scratch-www locally

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#7455]
### Description

[The `matches` array for `web_accessible_resources`](https://github.com/ScratchAddons/ScratchAddons/blob/e6f38f6/manifest.json#L77) should include `localhost` and `scratchfoundation.github.io` if the extension is installed from source. It currently doesn't, which breaks userstyles without `"injectAsStyleElt": true` and all userscripts.

### Steps to reproduce

Set up a scratch-www development server and visit `localhost:8333`.

### Demonstration(s) and additional context

![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/665d3ba6-873d-4cb2-be27-728951a0c5ca)

### Environment

Browser: Edge 126 dev
Scratch Addons version: e6f38f6
Operating system: Windows

**Comment by WorldLanguages** [comment]
Good catch

**Comment by WorldLanguages** [comment]
> [The `matches` array for `web_accessible_resources`](https://github.com/ScratchAddons/ScratchAddons/blob/e6f38f6/manifest.json#L77) should include `localhost`

If possible check whether specifying the port is necessary (as I'm not sure if the web_accessible_resources array is a list of origins or a list of extension URL patterns) and make sure it works on Firefox too.

**Comment by mxmou** [comment]
> > [The `matches` array for `web_accessible_resources`](https://github.com/ScratchAddons/ScratchAddons/blob/e6f38f6/manifest.json#L77) should include `localhost`
> 
> If possible check whether specifying the port is necessary (as I'm not sure if the web_accessible_resources array is a list of origins or a list of extension URL patterns) and make sure it works on Firefox too.

The docs say only the origin is matched. Adding `http://localhost/` appears to work on both browsers.

**Comment by mxmou** [comment]
`scratchfoundation.github.io` should probably be added too.
