### ISSUE TITLE
Run on `localhost:8602`

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#7456]
### Why this would be helpful

scratchfoundation/scratch-gui#9536 changed the port for the development server from 8601 to 8602.

### My suggestion

Add the necessary match and host permission to run Scratch Addons on `localhost:8602`.

**Comment by WorldLanguages** [comment]
Should we keep 8601 as well? What do you think?

**Comment by mxmou** [comment]
> Should we keep 8601 as well? What do you think?

It could still be useful for testing earlier versions of scratch-gui, so I don't think it needs to be removed.

**Comment by WorldLanguages** [comment]
PRs for this (plus #7455) are welcome, just ping me and I'll fix the GitHub action so that this perm is removed in the store releases. For #7455 I will also remove the extra hosts from web_accessible_resources because there's no reason to add them to the store releases.
