### ISSUE TITLE
Revamp `mediarecorder`'s "Start Recording" modal

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#7460]
### Why this would be helpful

The current UI is just a _little_ unnatural and unintuitive, and there is room to improve the user experience by enhancing the way the options are presented.

### My suggestion

Here's what I came up with:
![Options for starting a recording with multiple-choice settings to choose how long until the recording is started or stopped and checkboxes to record project or microphone audio](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/75ee8f4f-36ab-46dd-899f-80a5919a9188)

**Comment by hueychen27** [comment]
Looks more concise.

**Comment by WorldLanguages** [comment]
I think any PRs to change it are welcome.

**Comment by WorldLanguages** [comment]
We should explicitly mention the 10 minute limit on the modal as well.

**Comment by hueychen27** [comment]
Actually, on second thought, this version has too many inputs (or labor,) so I wouldn't change the current one.

**Comment by DNin01** [comment]
> Actually, on second thought, this version has too many inputs (or labor,) so I wouldn't change the current one.

Maybe changing the radio buttons to dropdown select menus would make the UI less overwhelming.

**Comment by mxmou** [comment]
> Maybe changing the radio buttons to dropdown select menus would make the UI less overwhelming.

I don't think there are enough choices for a dropdown menu. Instead, we could try to reduce the number of settings (without removing functionality) or improve their presentation.

**Comment by DNin01** [comment]
Here's another design:
![Options for starting a recording with number inputs to choose how long until the recording is started or stopped and checkboxes to record project or microphone audio](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/700092c4-18b4-4954-82f2-391aa870017d)

This would also be really easy to do - it just reorders and changes some of the existing options from our current design.

Compare this to:
![Options for starting a recording with number inputs to choose how long until the recording is started or stopped and some other checkbox settings](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/deb227a6-34a3-4dc9-af21-65144a2020a7)

**Comment by DNin01** [comment]
I want to work on this issue, except #7173 could make some conflicting changes, so if someone can review that pull request, that would be great.
