### ISSUE TITLE
Remove `handle-licenses.js`

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#7473]
### Why this would be helpful

The `handle-licenses.js` module preloads licenses into memory so they can be displayed on the `/webpages/settings/licenses.html` page. However, this page is rarely opened and is not needed immediately.

Plus, since the upgrade to Manifest V3, this data gets purged from memory every time the service worker is terminated from inactivity, defeating the purpose of loading it into memory in the first place.

### My suggestion

Instead of the background page providing the license information, it should be loaded by the licenses page as soon as it is opened.

### Possible alternatives

Build the page. This could be done during development or just when packing for production.

**Comment by WorldLanguages** [comment]
Self-reminder: also, the csInfoCache alarm can be converted to a setTimeout/setInterval instead. It may reduce the amount of times the background context wakes up unnecessarily.
