### ISSUE TITLE
Rearrangeable custom block inputs: Adding or rearranging an empty-string label creates "%l" labels.

### ISSUE THREAD

**Issue by Wowfunhappy** [ScratchAddons/ScratchAddons#7478]
### Description

In a nutshell, in Scratch it is valid for custom blocks to have empty labels, ie a label which is an empty string. However, these labels cause weird things to happen when the "Rearrangeable custom block inputs" addon is enabled!

### Steps to reproduce

1. Click "make a block" in the block palette. 
2. Delete the text that says "block name"
3. Press "add a label"

Observe that the first label now reads "%l".

Alternately:

1. Click "make a block" in the block palette.
2. Click "add a label"
3. Delete all the text in one of your two labels.
4. Rearrange either label

Again, observe that you now have a label which reads "%l".

### Demonstration(s) and additional context

https://github.com/ScratchAddons/ScratchAddons/assets/4484096/e79da5e1-0175-4eba-af20-b618efe25d58
https://github.com/ScratchAddons/ScratchAddons/assets/4484096/e98c25ee-6aec-4c2d-ac53-1f4df2ce9655
https://github.com/ScratchAddons/ScratchAddons/assets/4484096/a2f84230-a4e7-42eb-b64e-27e53130b1f0

### Environment

Browser: Chromium 124
Scratch Addons version: v1.38.0
Operating system: macOS

**Comment by Joeclinton1** [comment]
Thank you for submitting the bug report I'll look into this soon.

**Comment by Joeclinton1** [comment]
Going to add that if you name a label %l, things also break.

**Comment by Joeclinton1** [comment]
hey "Scratch it is valid for custom blocks to have empty labels" this isn't true I just tested it. Empty labels get removed.

**Comment by Wowfunhappy** [comment]
Oops! What I meant was "it's possible to make a block with only an empty label", which is true, but you're right if you have an empty label _and_ other things the other things get removed.

**Comment by Joeclinton1** [comment]
![image](https://github.com/ScratchAddons/ScratchAddons/assets/48254978/e4494641-3db6-4daf-8a1d-e8dc09bd2cdc)
So with my current stage of the fix you seem to get this in both cases when you delete the full label.

**Comment by Wowfunhappy** [comment]
Right, that's expected: https://github.com/scratchfoundation/scratch-gui/issues/9571

The empty label is valid in the block creation field. It's then collapsed/removed when you actually make the block, so it isn't there when you edit it again.

Sorry I wasn't clear.

**Comment by Joeclinton1** [comment]
In the code scratch has this:

```
Blockly.ScratchBlocks.ProcedureUtils.addLabelEditor_ = function(text) {
  if (text) {
    this.appendDummyInput(Blockly.utils.genUid()).
        appendField(new Blockly.FieldTextInputRemovable(text));
  }
};
```

This prevents me from adding an empty label. The best I can do is at least remove the bug, and have scratch's current functionality where it removes the empty label when you add something after it.
