### ISSUE TITLE
Settings page works - but addons don't - on v1.38.1

### ISSUE THREAD

**Issue by The-Abigail608** [ScratchAddons/ScratchAddons#7481]
### Description

After receiving the MV3 update, nothing works, even if I wait, it does not load unless i reimport my user settings, which reloads the extension, i don't completely remember the update notification I got, but I remember it saying something along the lines of "You've been selected as a tester of the MV3 update, and none of the addons had loaded. I've tried waiting and it doesn't work, it sometimes keeps working between some pages with certian addons off (like scratchstats, mystuff share, and mystuff search) but if I click off for more than 30 seconds it entirely unloads

### Steps to reproduce

1. Have update happen out of blue
2. have these addons enabled:
[scratch-addons-settings (1).json](https://github.com/user-attachments/files/15515498/scratch-addons-settings.1.json)
3. Scratch Addons fails to work.

### Environment

Browser: Chrome Version 124.0.6367.225 (Official Build) (64-bit)
Scratch Addons version: v1.38.1
Operating system: Chrome OS

**Comment by Samq64** [comment]
Everything worked fine on v.38.0, right? This might be caused by #7417.

Also I'm pretty sure the update has been fully rolled out now and the notification was never updated.

**Comment by WorldLanguages** [comment]
I believe around 20% of Chrome users went directly from v1.37.1 to v1.38.1

**Comment by WorldLanguages** [comment]
> but if I click off for more than 30 seconds it entirely unloads

@The-Abigail608 What do you mean by this?

**Comment by The-Abigail608** [comment]
if scratch addons is reloaded and im on a scratch tab where it's working, i probably meant to say scratch addons stops working if i wait some time and go to a new scratch tab, it might be caused by one of the addons i have enabled throwing an error, but i am not completely sure.

**Comment by WorldLanguages** [comment]
@The-Abigail608 So the addons/features do not always work, but the settings page always works fine, right?

**Comment by TheColaber** [comment]
Can you go on a scratch tab, press ctrl + shift + I, and screenshot and share with us all the errors?

**Comment by The-Abigail608** [comment]
I am unable, sadly. Inspect is blocked.

**Comment by WorldLanguages** [comment]
@The-Abigail608 So the addons/features do not always work, but the settings page always works fine, right?

**Comment by The-Abigail608** [comment]
Funny you should mention that, dark mode didnt activate when i went from the main page (with addons working) to settings. it will also happen if i go from my profile (addons loaded) to my stuff (stops working) or main page to my profile.

**Comment by WorldLanguages** [comment]
I mean the Scratch Addons settings page, I assume it works fine to you since you said you can reimport your settings.

**Comment by The-Abigail608** [comment]
yes, the scratch addons settings page and the rest of the extension UI works fine

**Comment by WorldLanguages** [comment]
> yes, the scratch addons settings page and the rest of the extension UI works fine

That's very weird, addons usually break together with the settings page. I will give it some thought later.

It looks like your browser updated v1.37.1 directly to v1.38.1 (without going through v1.38.0 first) but I can't think of why that could cause problems. The v1.38.0 update worked fine for 99% of people. And the v1.38.1 changes would break the settings page as well if they malfunctioned. So no idea for now.

**Comment by The-Abigail608** [comment]
I uninstalled and reinstalled which worked for a bit but then it stopped working when i closed scratch and went to other sites for a bit, immediately after install i loaded my settings file again.

**Comment by WorldLanguages** [comment]
More feedback from the last 24 hours:

- `It does not work anymore so try fixing it a little bit.` (v1.38.1)
- `it is broken for me it's not making the modifications i set up` (v1.38.1)
After 5 minutes: `i fix it`
- `When it gave me the message that the addons were having an update, all my addons turned off for a second. I am not sure if this is a glitch or just a thing when you are using an old monitor. If you need to know, It was when I clicked my messages. I has just logged on and I needed to check my 16 messages.` (v1.38.0)
- `it's really good but it's not working fast :(` (v1.38.1) (known issue)
- `for some reason, the addons stopped working, i don't know why.` (no version information)
- `sometimes (or almost always) my scratch addons judt doesnt work, can you fix that?` (no version information)
- `My addons isint working` (no version information)
- `When I try opening addons extension it only shows the setting, bar and the title. And when i try opening settings the everything but the addons work. I don't know what else to do.` (v1.38.0)
- About three or four feedback messages about "kept getting logged out of my Scratch account (when I reload the page)"

**Comment by DNin01** [comment]
> When it gave me the message that the addons were having an update, all my addons turned off for a second.

That sounds like the short delay that happens when the service worker has to restart.

Well, I haven't encountered any issues yet on my stable install, which updated to v1.38.0 last time I tried, but I'll let you know if I find anything.

Only thing I can say is that the update notification took a few seconds after opening Scratch to show up, which I think is longer than usual?

I usually have around only 20 addons turned on at a time, and I don't usually have any theme addons enabled, so I wasn't able to notice if there was any style flashing.

**Comment by DNin01** [comment]
No issues for me so far on v1.38.1.

**Comment by WorldLanguages** [comment]
To clarify, Samq is testing the Chrome Web Store version with the OP given settings file. I also see that line throwing sometimes.

**Comment by Samq64** [comment]
Repro steps:
1. Load the settings file
2. Open the Scratch homepage
3. Stop the service worker from `chrome://serviceworker-internals/`
4. Reload the Scratch tab

Addons don't start working again until the the extension is reloaded from `chrome://extensions` (a disable and re-enable is also fine)

**Comment by WorldLanguages** [comment]
The issue seems related to `_scratchDomainImplied` and the caching of manifests on `chrome.storage.session`.

**Comment by WorldLanguages** [comment]
I have to go, but most likely we missed that the list of manifests as stored by the background context may not be 100% JSON compatible. Most likely culprit: https://github.com/ScratchAddons/ScratchAddons/blob/b4389bcefee394ddc2197e3fab787dd6732f73be/background/load-addon-manifests.js#L115

**Comment by WorldLanguages** [comment]
Note that v1.38.1 was only sent to 100% of Firefox users and 40% of Chrome Web Store users.

**Comment by DNin01** [comment]
I can reproduce. After adding some debugging code, I narrowed it down to the `necropost-highlighter` addon, at least for the settings provided by this issue's author.

Of the addons that she enabled, it's the only one with RegExps in the `matches` properties. And indeed, after disabling that addon, the problem disappeared.

Like W_L said, the problem is probably that RegExps (and other JavaScript object types) can't be serialized in JSON, causing them to lose their value when pulled out of `chrome.storage.session`.

**Comment by DNin01** [comment]
Are there any other addons that use RegExp match patterns for userscripts or userstyles?

**Comment by DNin01** [comment]
If fully fixing this issue might take some time, we could release a patch with a "band-aid" fix that is just catching any resulting errors. It would prevent `necropost-highlighter` from working when this happens, but the rest of Scratch Addons should be perfectly fine and most people probably won't even notice that that addon isn't working.
```diff
 function urlMatchesLegacyPattern(pattern, urlUrl) {
+  try {
+    new URL(pattern);
+  } catch (err) {
+    console.error(err);
+    return false;
+  }
   const patternUrl = new URL(pattern);
```

**Comment by DNin01** [comment]
BTW, if we ever decide to do testing, a good case to check in the future would be, "is the addon manifests object the same after setting and reading from storage?"

**Comment by Waakul** [comment]
Can reproduce on chromium 125.

**Comment by medlans** [comment]
> * About three or four feedback messages about "kept getting logged out of my Scratch account (when I reload the page)"

That one is a Scratch issue

**Comment by WorldLanguages** [comment]
> That one is a Scratch issue

@medlans How can you be so sure?

**Comment by medlans** [comment]
> > That one is a Scratch issue
> 
> @medlans How can you be so sure?

1. I tried on a tablet (the purple did hurt my eyes though), and it was still happening. I have also seen this happen for people without versions in the Bugs and Glitches forum.
2. It started happening very recently, when server issues happened too.

**Comment by WorldLanguages** [comment]
Some people send feedback being quite sure about SA logging them out, maybe for some reason the extension causes the bug to happen more often? But clearly the root cause is not us.

**Comment by DNin01** [comment]
> Some people send feedback being quite sure about SA logging them out, maybe for some reason the extension causes the bug to happen more often? But clearly the root cause is not us.

I found myself logged out of Scratch today without having Scratch Addons enabled, so it might just be that time again.

**Comment by WorldLanguages** [comment]
In this forum topic: https://scratch.mit.edu/discuss/topic/765029/?page=1 someone with an iPad has reported the logouts, let's wait and see if they confirm they use their iPads only, that would mean we're not the root cause of the issue.
Some people say that disabling Scratch Addons fixes the issue, while others say changing their password fixed it.

**Comment by WorldLanguages** [comment]
Note that the first reports of the "constant logouts" issue start 10+ days later after v1.38.0 starts reaching its first portion of Chrome users. And the changes on v1.38.1 and v1.38.2 are completely unrelated to this issue, as we only added internal caching, and that wouldn't affect anything to do with Scratch authentication, even how often the service worker starts up is unaffected by these 2 updates.

**Comment by DNin01** [comment]
While I was browsing Scratch, I got several very brief (< 100 ms) FOUCs, running v1.38.2 stable, even while the service worker was active!

**Comment by WorldLanguages** [comment]
> While I was browsing Scratch, I got several very brief (< 100 ms) FOUCs, running v1.38.2 stable, even while the service worker was active!

Well, that should mean that any attempts to keep the service worker awake for longer won't really help to reduce flashes of unstyled content. I don't think anyone wanted to go that route, but it's really discarded now.
