### ISSUE TITLE
Clicking on comment link does not show correct comment (Infinite Scrolling)

### ISSUE THREAD

**Issue by RokCoder** [ScratchAddons/ScratchAddons#749]
**Describe the bug**

Clicking on a message link with InfiniteScrolling/ProjectComments enabled does not take you to the correct comment.

**To Reproduce**

1. Go to https://scratch.mit.edu/projects/444598492/#comments-168272601

**Expected behavior**

Should take you to the correct comment (_Oof that's sad..._)

<img width="745" alt="Screenshot 2020-11-14 at 12 25 25" src="https://user-images.githubusercontent.com/20208339/99146938-88e98800-2674-11eb-8027-f5e59f457513.png">

**Screenshots**

This is the option in question (deselected in screenshot)

<img width="1403" alt="Screenshot 2020-11-14 at 12 22 08" src="https://user-images.githubusercontent.com/20208339/99146880-19739880-2674-11eb-96b9-cc08d6013271.png">

Clicking on the message link takes you to the following screenshot which bears no correlation to the expected destination

<img width="738" alt="Screenshot 2020-11-14 at 12 26 36" src="https://user-images.githubusercontent.com/20208339/99146971-ca7a3300-2674-11eb-87d5-7ffd1fe151c4.png">

**Device (please complete the following information):**

- macOS Catalina Version 10.15.7
- Chrome Version 86.0.4240.75 (Official Build) (x86_64)

**Additional context**

**Comment by TheColaber** [comment]
Hmm, that is interesting. It seems to be taking that last part out of the url.

**Comment by WorldLanguages** [comment]
Lol I made that addon beta for a reason

**Comment by TheColaber** [comment]
Fixed I believe?

**Comment by RedGuy12** [comment]
No, still a problem
________________________________

**Comment by RedGuy12** [comment]
This is because on projects all other comments are hidden. Then, the infinate scrolling addon thinks you have scrolled to the bottom. So it clicks on the "view more" button for you. This could be fixed by checking if the hash has #comment in it.
________________________________
