### ISSUE TITLE
Auto-hiding palette does not work with dropdowns or text regions

### ISSUE THREAD

**Issue by hueychen27** [ScratchAddons/ScratchAddons#7490]
### Description

When pressing on a dropdown or text region in the palette's blocks, it will hide the block making it impossible to reach the block unless the palette is shown again.

### Steps to reproduce

1. Enable the auto-hiding palette addon.
2. Click on a dropdown menu or a text region in one of the blocks in the palette

### Demonstration(s) and additional context

[palette_hover_problem-1.webm](https://github.com/ScratchAddons/ScratchAddons/assets/78285518/cf0226f9-419c-4fff-b6ae-15d12a9ea9d5)
Ignore the make new list section.

### Environment

Browser: Firefox 126.0.1 (64-bit)
Scratch Addons version: v1.38.1
Operating system: Debian Sid (Unstable)

**Comment by mxmou** [comment]
Duplicate of #7024
