### ISSUE TITLE
Legal: Should the licenses page include the author and copyright year?

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#7494]
When you use a work under a copyright license that requires including the license and copyright notice generally means that you should also attribute the author or keep the author and copyright year. But I don't see the authors anywhere.

Proper credit is important. If we show the licenses, we should also show the copyright notices, and it should be part of Scratch Addons, not on a remote source such as our website.

Let me know if I'm missing something, because I looked everywhere. I know we link to the package sources from our website, but nothing's better than clear, obvious attribution.

**Comment by mybearworld** [comment]
The MIT license specifically requires that - other licenses probably do too

> The **above copyright notice** and this permission notice shall be included in all
> copies or substantial portions of the Software.
