### ISSUE TITLE
An extension to clear certain lists on save

### ISSUE THREAD

**Issue by ninjamar** [ScratchAddons/ScratchAddons#7499]
### Why this would be helpful

As you may know, lists are stored in the `project.json`. In one of [my projects,](https://scratch.mit.edu/projects/602626065/), I have a large amount of information in the list `data`. The project then copies the stuff inside data to a new list, `decompressed`. When I try to save the project, the total amount of stuff inside both lists exceeds the `project.json` limit. I manually have to delete the decompressed list (it is generated from the data list)for the project to save.

### How this addon works

This addon would add a setting to select certain lists to be wiped when the project is saved. 

### Additional context

This could be implemented by running the delete all from list block in JavaScript 

```javascript
let vm = document.getElementById('app')._reactRootContainer._internalRoot.current.child.pendingProps.store.getState().scratchGui.vm;
let sprite = vm.editingTarget.runtime.getSpriteTargetByName("Sprite1");
```
Then it would follow the [delete all list block implementation](https://github.com/scratchfoundation/scratch-vm/blob/6bfe73d1e7361f62ee17d128be9a7c419b882e93/src/blocks/scratch3_data.js#L150), where `util.target = sprite`. The only trouble is that I can't figure out what the list ID is.

**Comment by Samq64** [comment]
How will the UI for this work? An option in the list's context menu?

Also the addon will probably need the dangerous tag.

**Comment by mybearworld** [comment]
How would this be stored? Or would it only be per page session?

**Comment by DNin01** [comment]
I think this is one of those problems that is best left for project creators to solve themselves. We could make dozens of addons to automate problem solutions like these, but it would become difficult to sift through them all while understanding how they work, plus, there can be many different ways to solve the same problem.

**Comment by BroJac5246** [comment]
There could also be a button to clear selected lists. That might be more widely useful.

**Comment by ninjamar** [comment]
> I think this is one of those problems that is best left for project creators to solve themselves. We could make dozens of addons to automate problem solutions like these, but it would become difficult to sift through them all while understanding how they work, plus, there can be many different ways to solve the same problem.

I understand. I'll close this issue.
