### ISSUE TITLE
Interpolation

### ISSUE THREAD

**Issue by ScratchOSTeam** [ScratchAddons/ScratchAddons#7500]
### Why this would be helpful

Interpolation is a feature that has appeared in turbowarp. I feel like making it an addon would be a good idea for people who want to see smoother motion without changing the framerate.

### How this addon works

Interpolation makes motion animations in projects appear smoother by interpolating movement of sprites between frames. It's basically higher framerate without affecting how fast scripts run.

**Comment by OneShot-Niko** [comment]
Can't you just use the turbowarp player addon and enable that setting though?

**Comment by mxmou** [comment]
Duplicate of #1352
