### ISSUE TITLE
Finding the root cause of the constant log-outs

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#7502]
The [Scratch Bugs&Glitches forum](https://scratch.mit.edu/discuss/3/) is filled with bug reports about constantly getting logged out.

Some users say the issue stops after disabling Scratch Addons, while others experience it on iPads and incognito mode without extensions.
I think it's unlikely our v1.38.x updates are causing it, see comment: https://github.com/ScratchAddons/ScratchAddons/issues/7481#issuecomment-2148164950

Even if the problem is unrelated to us, we should not forget that we could take advantage of the `chrome.webRequest` API. In theory, we could detect weird logouts - that is, normal requests with Set-Cookie HTTP headers that unexpectedly modify or delete the scratchsessionsid cookie - then tell the user what happened (such as which URL caused the logout, and other non-sensible details about the request) and ask the user if they can send the info to the feedback form.

**Comment by DNin01** [comment]
supersonic61223 said:
> Whenever I try to login to my scratch account I get constantly logged out, at the top of the page I signed in on it shows a message for the policy change from 2023.

MrWoogieman said:
> My account keeps logging me out with no explanation, and this is a problem because I can't make other stuff on Scratch due to the impossibility. 🙁
Today (June 3, 2024) isn't the first time it happened…for me, it happened on May 30, 2024. If this is just me…or an actual glitch, please reply to this message. **(Update: It's not a glitch from any Scratch extensions.)**

All of the posts I saw that provided device details came from users running ChromeOS or macOS with `No Flash version detected`.

Even colinmacc, a well-known Scratcher, reported experiencing this issue. I wonder if I would have if I had tried to use Scratch earlier today.

I have not encountered this issue in the past few days other than that one time I mentioned in https://github.com/ScratchAddons/ScratchAddons/issues/7481#issuecomment-2146208445. I have a few times been logged out _while_ using Scratch, but the issue hasn't been as pronounced for me as other users are reporting.

**Comment by WorldLanguages** [comment]
Scratch Team member said:

> Yes, we continue to investigate.

Source: https://scratch.mit.edu/users/codubee/#comments-333570177

**Comment by Waakul** [comment]
i never ever had this problem, its been 3 months since i last logged in, those having this problem are mostly on ipads.

**Comment by Waakul** [comment]
the safari web browser might be the origin of cause.

**Comment by Waakul** [comment]
Everyone who got this error are signed in on a Chromebook... Weird

**Comment by CubesterYT** [comment]
I get logged out at random periodic times on chrome, on a Windows PC, if that differs from your information.

**Comment by Waakul** [comment]
Hmm, i'm on ms edge, based on chromium. Could that bring a difference?

**Comment by BroJac5246** [comment]
> Everyone who got this error are signed in on a Chromebook... Weird

Worth noting that a significant portion of Scratchers likely use school Chromebooks (and most of those won't allow Scratch Addons due to school restrictions)

**Comment by WorldLanguages** [comment]
Scratch Team member and software architect said:

> How 'bout now?

Source: https://scratch.mit.edu/users/codubee/#comments-333831297

He probably means that he believes the bug is now fixed.

**Comment by WorldLanguages** [comment]
It appears that Scratch has fixed the issue.

**Comment by WindowsArchive** [comment]
its still happening to me...
