### ISSUE TITLE
Slowly add back "Data category tweaks"

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#751]
I understand that this addon was too buggy to keep in the extension, but I personally found it very useful. I never experienced any problems with it, actually.

I'd suggest to take one of two courses of action:
1. Re-add the complete addon, but label it as Beta and/or add a warning about potential buggy behavior in the addon description. As bugs are reported and fixed, the Beta status could eventually be removed. (Or possibly not lol)
2. Re-add one component at a time. Whichever of the two (list category separation or local variable separation) was the least buggy could be added back first. If all goes well with that, add the second component on top of that. This could potentially help with finding bugs caused by both extensions being enabled at once.

**Comment by GrahamSH-LLK** [comment]
It would have to be redesigned and tested from the ground up if we were to accept it. It was buggy enough that it left lasting damage to the project .json.

**Comment by lisa-wolfgang** [comment]
Then perhaps we should go with Option 2 and start with list category separation. If I understand correctly, that part of the addon doesn't actually rearrange or change anything, it just adds another button in the category ribbon that scrolls down to a different location.

**Comment by WorldLanguages** [comment]
> If I understand correctly, that part of the addon doesn't actually rearrange or change anything, it just adds another button in the category ribbon that scrolls down to a different location.

That's what we thought, until the bugs happened.

**Comment by lisa-wolfgang** [comment]
> That's what we thought, until the bugs happened.

My thought is that perhaps the local variable rearranging was invasive in some way. I'll go take a look at its code and see if I spot anything revealing.

**Comment by GrahamSH-LLK** [comment]
No, it's all really invasive. It uses lots of traps.
