### ISSUE TITLE
"Add this project" button in cloud games popup is not centered

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#7515]
### Description

The "Add this project" button in the cloud games popup isn't centered.

### Steps to reproduce

Open the Games tab in the popup on a project page.

### Demonstration(s) and additional context

![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/fba8e6d0-6a8d-425e-9e22-f763391ff704)

### Environment

Browser: Edge 125, Edge 127 dev
Scratch Addons version: 1.38.0, 586def8
Operating system: Windows

**Comment by rickbot-dot** [comment]
Also having this exact same issue. Brave, Windows 11, 1.38.2
![image](https://github.com/ScratchAddons/ScratchAddons/assets/115214762/d146e6fb-9bb7-4600-b12f-961e3cab6558)
