### ISSUE TITLE
`editor-compact`: costume number clips into preview

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7522]
### Description

IDs of costumes tend to clip into the costume preview.
Not sure if this is the same situation like with #6862 since I don't have a larger screen to test with.

### Steps to reproduce

1. enable `editor-compact`
2. go to costumes pane
3. do 10 costumes or a hundred (or just import some random gif a few times)
4. look close at the costume ID

### Demonstration(s) and additional context

In 3 digit long or higher values its much more noticable:
![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/5821b758-76c2-4131-971e-2d257e049d2d)
2 digit is a bit less noticable:
![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/a0f1259c-5030-4674-86c6-d7cae89d1ff1)

This could probably be resolved by placing the ID/order number elsewhere, or giving it a background shade (via `background-color: #000` - only thing needed is the class). Not really good for the eyes to look at it for awhile though, especially if the topleft corner just so happens to be the same color as the text:
![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/12fbab9a-02b2-41dd-ad12-fe080f5b5828)
(138)

### Environment

Browser: LibreWolf 126.0.1-1 (Windows MSIX package, mozilla-MSIX - 1.0)
Scratch Addons version: v1.39.0-pre (commit 0da7e1c)
Operating system: Win10 (32 bit, screen size is 1366 x 768)

**Comment by medlans** [comment]
Is there supposed to be something in the 1st 2 pictures?? I cannot see anything, the image (if there is one) looks exactly like the background for me.
Anyways, can replicate
Browser: Chrome 125
Scratch Addons version: v1.38.2
Operating system: Mac OS 11.3 (Big Sur)

**Comment by ajskateboarder** [comment]
It could also invert the text where needed using `mix-blend-mode: difference; filter: invert(1)`.. maybe have it be a toggle between a black bg and invert?

**Comment by mxmou** [comment]
> It could also invert the text where needed using `mix-blend-mode: difference; filter: invert(1)`.. maybe have it be a toggle between a black bg and invert?

I don't think there should be settings for such tiny details. Solid background is probably the better option because the number would be easier to read.

Another solution is to make the costume tile taller so the number fits above the preview - that's how it worked in Scratch 2, but it means fewer costumes would be visible at once.
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/c604df27-ae52-41e9-80cf-4ae1e3881b15)
