### ISSUE TITLE
hi-res-thumbnails: cat thumbnail bug

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#7523]
From feedback

![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/b57b25af-9a93-4cbb-90c3-fa4961e13bf2)

Apparently wrong project ID:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/17484114/346daf2c-0cc9-4093-8ce9-41aa731aa8f6)

**Comment by OneShot-Niko** [comment]
can repro on LibreWolf
interestingly enough, console doesnt seem to throw any errors.
![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/c380839f-5259-4410-8443-57e9d6609665)
However, it does seem like the first four characters of the project ID are in the thumbnail part, but it only seems to happen with this project, which is odd.

**Comment by medlans** [comment]
This occurs without the extension I think

**Comment by mxmou** [comment]
Without the addon, the project ID in the image URL contains a slash:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/03ad5ca5-3fc2-4fdd-8896-c32cfc240be6)

**Comment by DNin01** [comment]
Those URLs are usually in this form:
```
https://uploads.scratch.mit.edu/get_image/project/10015857_144x108.png
```
On the front page right now, they are:
```
https://uploads.scratch.mit.edu/projects/thumbnails/10015857.png
```
Did they change recently, or have they always been like this?

With the second URL, you can put one slash anywhere between the digits and the image will still load.

https://uploads.scratch.mit.edu/projects/thumbnails/1/0015857.png
https://uploads.scratch.mit.edu/projects/thumbnails/10/015857.png
https://uploads.scratch.mit.edu/projects/thumbnails/100/15857.png
https://uploads.scratch.mit.edu/projects/thumbnails/1001/5857.png
https://uploads.scratch.mit.edu/projects/thumbnails/10015/857.png
https://uploads.scratch.mit.edu/projects/thumbnails/100158/57.png
https://uploads.scratch.mit.edu/projects/thumbnails/1001585/7.png

I'm not going to question why the front page uses different URLs, but this behavior is very weird. What causes that?

Hopefully this will just be a one-off thing that we don't have to worry about after this project is pushed off the front page, or at least happen infrequently enough to be a tolerable issue.

**Comment by DNin01** [comment]
It looks like we already handle URLs with the `projects/thumbnails/` format and convert them to the `get_image/` format[^1], we just never expected to see URLs with a slash between the numbers. This shouldn't even happen in the first place.

[^1]: https://github.com/ScratchAddons/ScratchAddons/blob/0da7e1c97052f0c02f4f03ff054374163d247fe2/addons/hi-res-thumbnails/userscript.js#L39-L53

**Comment by WorldLanguages** [comment]
Why does this happen with only one project? I don't get it.

**Comment by DNin01** [comment]
IMO, I wouldn't bother to solve this unless it happens a few more times.

**Comment by DNin01** [comment]
Even the Scratch REST API documentation has an example response with these weird URLs:
https://github.com/scratchfoundation/scratch-rest-api/wiki/Proxy#example-response

**Comment by DNin01** [comment]
Potentially related forum topic? https://scratch.mit.edu/discuss/topic/765085/

Alright, I'll stop talking now.
