### ISSUE TITLE
`sprite-properties` + `editor-compact`: sprite pane gets cut off

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7527]
### Description

Sprite pane gets cut off

### Steps to reproduce

1. enable both addons mentioned in title
2. project
3. open sprite properties

### Demonstration(s) and additional context

![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/c0dcd56d-cb7c-4263-b82c-85791662d047)
![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/9f753f22-dfb6-4e10-83e5-a39b3ceaf69a)

### Environment

Browser: LibreWolf 126.0.1-1 (mozilla-MSIX - 1.0)
Scratch Addons version: 0da7e1c
Operating system: win10 (32 bit)

**Comment by mxmou** [comment]
This can happen without `search-sprites`:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/51849865/178c7dd6-6fde-4fc2-8573-355250ec068d)

**Comment by WorldLanguages** [comment]
Isn't this the same as #6602?

**Comment by mxmou** [comment]
> Isn't this the same as #6602?

It's similar, but the issue only occurs if the properties panel is open.
