### ISSUE TITLE
`collapse-footer` addon description has a typo

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7535]
### Description

the sticky footer addon has a typo in its description
opening a pr in like a few seconds

### Steps to reproduce

1. open the popup or settings page
2. look for sticky footer
3. read description

### Demonstration(s) and additional context

![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/256d4653-d1a2-4b24-bc3a-f7c06b096d0e)

### Environment

Browser: any because it's `addon.json` related
Scratch Addons version: 0da7e1c
Operating system: any because it's `addon.json` related

**Comment by WorldLanguages** [comment]
Wow 😅 nice catch
