### ISSUE TITLE
Customizable Block Shape: Flat hat blocks

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#7560]
#5879 started implementing this, but it got messed up.
The idea is something like this:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/72760579/8f690076-9a0f-4a41-a57e-6f59c23b592a)

**Comment by OneShot-Niko** [comment]
Duplicate of #5886

**Comment by TheColaber** [comment]
true, they weren't linked, didnt see that
