### ISSUE TITLE
`editor-theme3` + `block-palette-icons`: setting color to black doesn't invert icon

### ISSUE THREAD

**Issue by OneShot-Niko** [ScratchAddons/ScratchAddons#7570]
### Description

Not sure whether or not this is just an untested edgecase or intentional, reporting as a bug incase it's just unaccounted for.
Block palette icons should probably be inverting when `editor-theme3` has a block's color set to pitch black or dark text.
<sub>This doesn't only have to do with palette icons, happens with normal blocks as well, with `editor-theme3` alone, but I guess that can be expectable, better in a seperate issue anyway</sub>

### Steps to reproduce

1. enable editor-theme3 and block palette icons
2. set the color of a block in `editor-theme3` to black
3. enter the editor and look at the palette

### Demonstration(s) and additional context

![kép](https://github.com/ScratchAddons/ScratchAddons/assets/150537842/8cb05371-12f2-488a-8e81-17248e697d91)

### Environment

Browser: LibreWolf 126.0.1-1
Scratch Addons version: d4551ca
Operating system: win10

**Comment by mxmou** [comment]
This is intentional - icons follow the "text color" setting. The reason why that setting exists and the addon doesn't automatically choose the text color based on the block colors is that it would choose black for some of the default colors.

**Comment by OneShot-Niko** [comment]
> This is intentional - icons follow the "text color" setting. The reason why that setting exists and the addon doesn't automatically choose the text color based on the block colors is that it would choose black for some of the default colors.

my bad then
