### ISSUE TITLE
Remove ScratchDB addons

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#7577]
ScratchDB is down for the foreseeable future (https://scratchdb.lefty.one/) so we should remove addons that don't work without it.

Effected addons: 
- `scratchstats`
- `forum-search`
- `exact-count` (forum post count)
- `my-ocular` (might be fine)

**Comment by mxmou** [comment]
> `my-ocular` (might be fine)

`my-ocular` still works.

**Comment by DNin01** [comment]
We could also keep these addons for now but tuck them away somewhere and add a note to each of them explaining why they aren't working.

Related: #6987

**Comment by Secret-chest** [comment]
Could Lefty publish the software so we can host it?

**Comment by DNin01** [comment]
> Could Lefty publish the software so we can host it?

You could try asking him. Note that it is likely much more complicated than just typing a command, and it could take weeks, sometimes months to finish building an index.

There may also be some people who are building new projects to take ScratchDB's place.

**Comment by sfederici** [comment]
> ScratchDB is down for the foreseeable future (https://scratchdb.lefty.one/) so we should remove addons that don't work without it.
> 
> Effected addons:
>     * `exact-count` (forum post count)

I have the exact-count addon enabled for counting projects in studios, but I don't get the exact number anymore

**Comment by sfederici** [comment]
> You need to click the count to get the exact number.

I didn't know that. Thanks a lot for letting me know. Maybe this could be added to the information box of the addon?

**Comment by mxmou** [comment]
> > You need to click the count to get the exact number.
> 
> I didn't know that. Thanks a lot for letting me know. Maybe this could be added to the information box of the addon?

I'll make a PR.

**Comment by mxmou** [comment]
I think this is implemented:
* `scratchstats` and `exact-count`'s forum setting have been removed
* `forum-search` now uses the new ScratchDB API
* `my-ocular`'s "View on ocular" link works again after https://github.com/jeffalo/ocular/commit/73b0791718b5a64b57c0b964198865a931050923
