### ISSUE TITLE
Ctrl+enter to post: Multiple open comments will only try to submit first one on page

### ISSUE THREAD

**Issue by hueychen27** [ScratchAddons/ScratchAddons#7585]
### Description

When having two reply comments are pressing ctrl+enter in any of them, the first (highest) one on the page is submitted.

### Steps to reproduce

1. Press reply to a comment.
2. Press reply to a different comment in the same page.
3. Type in the lower comment.
4. Press ctrl+enter
5. Witness the top (highest) comment being submitted, not the active bottom one.

### Environment

Browser: Firefox v1.126.
Scratch Addons version: v1.38.2
Operating system: Debian Sid (unstable)

**Comment by WorldLanguages** [comment]
@hueychen27 Please confirm if this happens in project comments, profile comments, or in both places.

**Comment by hueychen27** [comment]
@WorldLanguages Both.

**Comment by hueychen27** [comment]
@mxmou Good catch
