### ISSUE TITLE
Settings Capability - Support Hotkeys

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#759]
**Is your feature request related to a problem? Please describe.**

I'm am creating the Editor Hotkeys Addon #705.

**Describe the solution you'd like**

I would like the user to be able to, not type their preferred hotkey, but actually perform it.
This is good number one: So syntax is not a problem
Number two: more convient

**Describe alternatives you've considered**

Make it hard without this feature.

**Additional context**

I'm doing this because @WorldLanguages said to here: https://github.com/ScratchAddons/ScratchAddons/pull/705#issuecomment-726247036

**Comment by Explosion-Scratch** [comment]
So basically custom hotkeys that you set in SA?

**Comment by WorldLanguages** [comment]
@Explosion-Scratch As an addon setting

**Comment by Explosion-Scratch** [comment]
If so here are some of my ideas for actions: 
- Submit a message/comment
- Go to the messages page
- Open SA settings
- Open SA Popup
- Go to header links
    - E.g. ```Alt + 3``` for discuss
- Close discussion (In discuss, for your posts)
- Report post that you're hovering over
- Lots more!

**Comment by TheColaber** [comment]
Awesome, new addon: Website Hotkeys
