### ISSUE TITLE
Fix copyright symbol (addon)

### ISSUE THREAD

**Issue by Elip100** [ScratchAddons/ScratchAddons#7597]
### Why this would be helpful

For people that are perfectionists. It is really annoying seeing the flipped copyright symbol on every project page.

### How this addon works

It just changes the CSS to not flip it.

### Before:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/173850307/9f443ce6-7941-4111-8e2d-3ca77ac578fb)
### After:
![image](https://github.com/ScratchAddons/ScratchAddons/assets/173850307/1e7db002-6c71-43c1-a3bc-8ab4bdfe0100)

**Comment by mybearworld** [comment]
That symbol stands for copyleft. It's intentionally flipped.
