### ISSUE TITLE
Links to addon IDs not working

### ISSUE THREAD

**Issue by iqnite** [ScratchAddons/ScratchAddons#7601]
### Description

Clicking on a link like `https://scratch.mit.edu/scratch-addons-extension/settings#middle-click-popup` leads you to the Scratch Addons Settings page, but does not auto-scroll to the addon with the addon ID that comes after the `#`.
Also, when clicking on those links (the links with an Addon ID at the end), the Settings page loads forever, as you can see in the video below (when the address bar becomes blue, the site is loading). The Settings page can still be interacted with normally while it's "loading".

### Steps to reproduce

I have also tried other addons like `fullscreen`, and the direct link to the Scratch Addons Extension (`chrome-extension://fdajajgpfjcmegghbfdbmfohhalcbgjg/webpages/settings/index.html#middle-click-popup`), but they don't work either.

### Demonstration(s) and additional context

https://github.com/ScratchAddons/ScratchAddons/assets/50552317/ada666cb-6ec6-44cf-a674-8480d589f89b

### Environment

Browser: Vivaldi 6.8.3381.46 with Chromium 126.0.6478.133
Scratch Addons version: 1.39.0-prerelease `6c89b40f73bc756ee3442e07cc47d4a8f09fbdf0`
Operating system: Windows 11 Pro 23H2 22635.3790

**Comment by Samq64** [comment]
The addon ID needs to be prefixed with `addon-`.

https://scratch.mit.edu/scratch-addons-extension/settings#addon-middle-click-popup
