### ISSUE TITLE
`editor-theme3`: List value colour doesn't update when scrolling

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#7604]
### Description

> Bug Report - Customizable block colors (NitroCipher/ZenithRouge, TheColaber, DNin01)
>
> Bug: When scrolling a list on the stage, colours do not update
This add-on has a feature that changes the colour of the variables and lists on the stage, but the areas of lists that are not visible unless scrolled to do not update their colour unless you interact with it.

### Steps to reproduce

1. Create a list
2. Add 10 items
3. Scroll the list

### Environment

Browser: Firefox 127
Scratch Addons version: 1.38.2
Operating system: Linux

**Comment by WorldLanguages** [comment]
May be an edge case missed by PR #6694
