### ISSUE TITLE
Notification Addon: Not working on Edge

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#761]
**Describe the bug**

Displays no notifications when a message received.

**Expected behavior**

A message appears.

**Screenshots**

They first said: 
`
A few days ago, my notifier stopped working, for some reason... I checked the extension permissions, my browser's permissions, scratch.mit.edu's permissions, and all of those are allowed notifications!
`

Then I replied:

![image](https://user-images.githubusercontent.com/72760579/99213446-ad8c4f80-279b-11eb-9a0e-d663edde75c8.png)
This is the console.
Once I receive a message back, I'll add what they also said after.
![image](https://user-images.githubusercontent.com/72760579/99256544-8f4a4200-27e3-11eb-9cf6-4b0f7fa72227.png)
It looks like CORS was the problem.
@WorldLanguages? CORS?

**Comment by TheColaber** [comment]
Looks like line 38 of handle-messages.js is the problem. It was using cors for some reason.

NOTE: I don't use edge but because I want to fix this, I'll install it and test.

**Comment by TheColaber** [comment]
Ok, I could not reproduce this, it was working for me...
I got the notification.

Maybe for some users, there is a security setting or something for CORS?

Also, @WorldLanguages that isn't fair:
![image](https://user-images.githubusercontent.com/72760579/99258358-72633e00-27e6-11eb-9624-9adeb98cbd33.png)
They get this look while chrome users get:
![image](https://user-images.githubusercontent.com/72760579/99258488-a50d3680-27e6-11eb-94bc-bb185d601d8f.png)

**Comment by mxmou** [comment]
> that isn't fair:
> ![image](https://user-images.githubusercontent.com/72760579/99258358-72633e00-27e6-11eb-9624-9adeb98cbd33.png)
> They get this look while chrome users get:
> ![image](https://user-images.githubusercontent.com/72760579/99258488-a50d3680-27e6-11eb-94bc-bb185d601d8f.png)

What notifications look like depends on the browser and the platform. I don't think it's possible to change that.

**Comment by TheColaber** [comment]
I don't think so, it used to look like the first image on chrome but then it got changed. Look here: #737

**Comment by WorldLanguages** [comment]
@TheColaber Can you tell this user to
1. Right click the scratch addons icon in the extensions bar
2. Click "manage extensions"
3. Make sure these all four are checked:
![image](https://user-images.githubusercontent.com/17484114/99267611-eca1bb80-2802-11eb-97ca-fd95fb8cd2db.png)

**Comment by WorldLanguages** [comment]
Alternatively tell them to reinstall the extension.

**Comment by TheColaber** [comment]
K

**Comment by WorldLanguages** [comment]
@TheColaber Please tell me if that was it. If it was, I'll create an issue to notify the user if they accidentally turned one of those off.

**Comment by TheColaber** [comment]
Alright, I haven't got a responce yet.

**Comment by mxmou** [comment]
> I don't think so, it used to look like the first image on chrome but then it got changed. Look here: #737

I can see native Windows notifications on both Chrome and Edge. Do you have the latest version of Windows 10?

**Comment by TheColaber** [comment]
I think so...

**Comment by TheColaber** [comment]
> @TheColaber Please tell me if that was it. If it was, I'll create an issue to notify the user if they accidentally turned one of those off.

@WorldLanguages I just got word from them... They didn't have all of those switches enabled. We should probably close this and create another issue.

**Comment by WorldLanguages** [comment]
@TheColaber Please do

**Comment by MasimbaTheHuman** [comment]
Wait, I thought SA wasn't on edge.

**Comment by WorldLanguages** [comment]
@MasimbaTheHuman The new Edge is based in Chromium.
