### ISSUE TITLE
Replace "Tutorials" or "About" button in scratch with "Convert" Button

### ISSUE THREAD

**Issue by SparkScratch-P** [ScratchAddons/ScratchAddons#762]
**Replace "Tutorials" or "About" button in scratch with "Convert"  Button**

**I am frustrated when I have to go through a lengthy process to convert sb3 to exe**

**I am here as a coder for 7 yrs. So just reporting a bug doesn't enjewel me always. I am basically to suggest another button replace like "Ideas" with "Discuss" button.i want either the "Tutorials" button in editor, or the "about" button on web to be replaced with convert button. It will be much easier and helpful to convert to .exe directly from the web than encountering a frustrating journey all over ur PC.I promise to provide all codes needed but anyone pls make a code to replace the buttons**

**Pls don't close it for I will give further codes for this to be carried out :)**

**Comment by JeffaloBob** [comment]
so this would have two parts?
1. customize navbar (this would be cool as its own addon)
2. sb3 to exe converter

perhaps it could avoid having to make the converter, by just letting people customize the navbar, and letting them add a link to one that already exists.

**Comment by pufferfish101007** [comment]
Also, thinking of more converters we could have: 
* [Leopard (scratch -> javascript)](https://leopard.now.sh) 
* [Snapinator (Scratch -> Snap!)](https://snapinator.github.io)
* Sb3 -> swf? - it is possible but I don't know if there are any converters out there
* Sb3 -> apk? - probably not possible, but you never know 
* sb3 -> python - I think I saw that someone was making one recently, but it was uncompleted/buggy

**Comment by SparkScrach-P** [comment]
> I want it to happen in the following way:
1. The "Convert" Button is clicked
2. It shows a pop-up providing options that would have choices of different converters
** There would be separate options for sb3 to HTML for .exe standalone and .exe Web-view App**
3. When the user clicks his choice, it would lead him to that web page !

**Comment by pufferfish101007** [comment]
I think that rather than replacing an existing tab with a convert button, it would be better to have it in the file/edit menu in the editor (probably file as that's where all the downloading stuff goes), as then we don't need to handle file uploads and reading all the data - it's already all there for us in the vm (or scratch-storage or somewhere else - but it is there). I'll go and figure out how to add an item to the menu so you can start working on the converyer code if you'd like...

**Comment by SparkScrach-P** [comment]
> Don't forget to view this HTMLifier for web-view exe -
[AI-HTMLifier](https://sparkscrach-p.github.io/AI-HTMLifier/)
When u convert it to exe, it becomes Web-view

**Comment by SparkScrach-P** [comment]
> I think that rather than replacing an existing tab with a convert button, it would be better to have it in the file/edit menu in the editor (probably file as that's where all the downloading stuff goes), as then we don't need to handle file uploads and reading all the data - it's already all there for us in the vm (or scratch-storage or somewhere else - but it is there). I'll go and figure out how to add an item to the menu so you can start working on the converyer code if you'd like...

That would be good but all converters r like...we \have to manually put the project ID

**Comment by GrahamSH-LLK** [comment]
> > Don't forget to view this HTMLifier for web-view exe -
> > [AI-HTMLifier](https://sparkscrach-p.github.io/AI-HTMLifier/)
> > When u convert it to exe, it becomes Web-view

We should probably use @sheeptester's HTMLifier. Yours is just an embed. His _actually_ makes it into HTML, not just a turbowarp embed.

**Comment by Explosion-Scratch** [comment]
Another thing we could add is -Rex-'s .sb3 to .sb2 converter

**Comment by SparkScrach-P** [comment]
> > > Don't forget to view this HTMLifier for web-view exe -
> > > [AI-HTMLifier](https://sparkscrach-p.github.io/AI-HTMLifier/)
> > > When u convert it to exe, it becomes Web-view
> 
> We should probably use @SheepTester's HTMLifier. Yours is just an embed. His _actually_ makes it into HTML, not just a turbowarp embed. It's not actually a packager or converter, it's a embed generator.

yes.That is the reason I said it was diff from his. It makes an Web-View Application

**Comment by SparkScrach-P** [comment]
> Another thing we could add is -Rex-'s .sb3 to .sb2 converter

ofcourse ...and I heard that Rex has made an HTML to .exe / can anyone give me the link pls...that should also be included

**Comment by Explosion-Scratch** [comment]
Yeah, and you guys know we can chain these, making .sb2 => .swf or .sb3 to snap, or .sb2 to python or even .html to app.

**Comment by SparkScrach-P** [comment]
**I want it to contain the following links:**
- sb3 to sb2                                                                           [Pls Search and Enter Link]
- [sb3 to HTML (Packager)](https://sheeptester.github.io/htmlifier/)
- [sb3 to HTML (Web-View)](https://sparkscrach-p.github.io/AI-HTMLifier/)
- [sb3 to Web-Page (Forkphorus)](https://forkphorus.github.io/)
- [sb3 to Web-Page (TurboWrap)](https://turbowarp.org/)
- [HTML (Packager) to Exe (Forum Tutorial Page)](https://scratch.mit.edu/discuss/topic/341617/#:~:text=At%20First%20you'll%20need,be%20download%20automatically%20named%20project.)
- HTML (Web-View) to Exe (Rex's Converter)                        [Pls Search and Enter Link]
- [sb3 to swf (Junebeetle Alpha)](Junebeetle.github.io)
- [ swf to exe ](https://pdfrecover.herokuapp.com/swftoexe/)
- [Sb3 to JS](https://leopard.now.sh/) 
- [sb3 to Snap!](https://snapinator.github.io/)

**Comment by SparkScrach-P** [comment]
> I think that rather than replacing an existing tab with a convert button, it would be better to have it in the file/edit menu in the editor (probably file as that's where all the downloading stuff goes), as then we don't need to handle file uploads and reading all the data - it's already all there for us in the vm (or scratch-storage or somewhere else - but it is there). I'll go and figure out how to add an item to the menu so you can start working on the converyer code if you'd like...

Pls read my last comment here ^ Now think...what to do; Replace "Tutorial" or add to "File"  ?

**Comment by SparkScrach-P** [comment]
Here is a typical code for a popup that must appear  when it is clicked. It contains the code of only 1 button .The `converter.html` file would contain the code of the page in `<iframe> ` Attribute. And `HTML (Web-View) to Exe` will have names of each converter.

```
<!doctype html>
<html>
  <head>
    <title>Scratch Converter</title>
    <script src="converter.html"></script>
  </head>
  <body>
    <h1>Scratch Converter</h1>
    <button id="Button 1">HTML (Web-View) to Exe </button>
  </body>
</html>
```

**Comment by SparkScrach-P** [comment]
> **I want it to contain the following links:**
> 
> * sb3 to sb2                                                                           [Pls Search and Enter Link]
> * [sb3 to HTML (Packager)](https://sheeptester.github.io/htmlifier/)
> * [sb3 to HTML (Web-View)](https://sparkscrach-p.github.io/AI-HTMLifier/)
> * [sb3 to Web-Page (Forkphorus)](https://forkphorus.github.io/)
> * [sb3 to Web-Page (TurboWrap)](https://turbowarp.org/)
> * [HTML (Packager) to Exe (Forum Tutorial Page)](https://scratch.mit.edu/discuss/topic/341617/#:~:text=At%20First%20you'll%20need,be%20download%20automatically%20named%20project.)
> * HTML (Web-View) to Exe (Rex's Converter)                        [Pls Search and Enter Link]
> * [sb3 to swf (Junebeetle Alpha)](Junebeetle.github.io)
> * [ swf to exe ](https://pdfrecover.herokuapp.com/swftoexe/)
> * [Sb3 to JS](https://leopard.now.sh/)
> * [sb3 to Snap!](https://snapinator.github.io/)

**and one more**
[Forkphorus HTML Packager](https://forkphorus.github.io/packager/)

**Comment by GrahamSH-LLK** [comment]
> Here is a typical code for a popup that must appear when it is clicked. It contains the code of only 1 button .The `converter.html` file would contain the code of the page in `<iframe> ` Attribute. And `HTML (Web-View) to Exe` will have names of each converter.
> 
> ```
> <!doctype html>
> <html>
>   <head>
>     <title>Scratch Converter</title>
>     <script src="converter.html"></script>
>   </head>
>   <body>
>     <h1>Scratch Converter</h1>
>     <button id="Button 1">HTML (Web-View) to Exe </button>
>   </body>
> </html>
> ```

That's not how scripts work. You need a _js_ file.

**Comment by Explosion-Scratch** [comment]
Or the ```<script></script>``` tags 😆

**Comment by GrahamSH-LLK** [comment]
I'm temporarily locking this thread. @SparkScrach-P You've put through your suggestion, and we will try to implement it.

**Comment by RedGuy12** [comment]
Why is this linked to #2875 @TheColaber 

But is this rejected? https://github.com/ScratchAddons/ScratchAddons/issues/2993#issuecomment-878868531

**Comment by TheColaber** [comment]
This has 2 suggestions. One is for a customizable navbar and another to make it easy to convert projects to exe and whatnot. My PR resolves half of it. Another issue should be opened that only focuses on the conversion part.

**Comment by FunctionalMetatable** [comment]
I already finished making this addon - I'm not sure if i should PR this - 

> But is this rejected? [#2993 (comment)](https://github.com/ScratchAddons/ScratchAddons/issues/2993#issuecomment-878868531)

**Comment by WorldLanguages** [comment]
@mxmou In general, I'd say they are. But it can be considered in a case by case basis.

**Comment by Samq64** [comment]
Once the custom navbar addon gets merged you can just replace About with packager.turbowarp.org if you want.

**Comment by mxmou** [comment]
> This has 2 suggestions. One is for a customizable navbar and another to make it easy to convert projects to exe and whatnot. My PR resolves half of it. Another issue should be opened that only focuses on the conversion part.

Spark's comments don't mention a customizable navbar.

**Comment by TheColaber** [comment]
@mxmou it's more specifically for replacing about or ideas with a convert button, which is something customizable navbar can do

**Comment by mxmou** [comment]
> @mxmou it's more specifically for replacing about or ideas with a convert button, which is something customizable navbar can do

Unless it has a preset to do so, I don't think it counts as an implementation of this feature.

**Comment by TheColaber** [comment]
I don't think a preset for this would be useful tbh

**Comment by mxmou** [comment]
> I don't think a preset for this would be useful tbh

This is rejected anyway.

**Comment by SparkScratch-P** [comment]
But it's still helpful for outsourcing scratch projects!
