### ISSUE TITLE
`find-bar`: do not capture Ctrl+F when outside editor

### ISSUE THREAD

**Issue by hueychen27** [ScratchAddons/ScratchAddons#7627]
### Why this would be helpful

On some occasions, I want to be able to use my browser's find tool instead of Scratch Addon's find bar because I want to find a piece of text. Also, outside of the editor, I cannot use the browser's find tool at all.

### My suggestion

Outside of the editor, do not capture Ctrl+F.

### Possible alternatives

Click the address bar and then press Ctrl+F.

**Comment by TheColaber** [comment]
i think the better solution then providing the browser's default find bar and by allowing our find bar to search for pieces of text, which i believe griffpatch has also suggested.

**Comment by WorldLanguages** [comment]
I changed this to be a bug (undesirable behavior) instead.

I suggest another issue is created for adding new functionality, such as text search like TheColaber said, or "Ctrl+F twice" to use browser search while inside the editor.

**Comment by hueychen27** [comment]
> I changed this to be a bug (undesirable behavior) instead.
> 
> I suggest another issue is created for adding new functionality, such as text search like TheColaber said, or "Ctrl+F twice" to use browser search while inside the editor.

I thought this bug was intentional...

**Comment by WorldLanguages** [comment]
I don't think it's intentional. Using Ctrl+F in the project page isn't rare if you're searching comments by keyword, or if the project notes are long and you're looking for something.

**Comment by hueychen27** [comment]
Alright
