### ISSUE TITLE
Edge Setting Switches always look disabled!

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#763]
**Describe the bug**

For every checkbox they look disabled

**To Reproduce**

1. Go to Settings on Edge
2. Click on Enable an addon that has a checkbox

**Expected behavior**

To look blue like in chrome

**Screenshots**

![image](https://user-images.githubusercontent.com/72760579/99257639-59a65880-27e5-11eb-873d-468437ca0a2e.png)

**Comment by GrahamSH-LLK** [comment]
There actually isn't anything specifying blue in the code, that's the chrome default. Edge must have a different default.

**Comment by TheColaber** [comment]
Oh

**Comment by TheColaber** [comment]
Is there a way to specify it? @GrahamSH-LLK?

**Comment by GrahamSH-LLK** [comment]
Yes, this is a bug(ish). You can specify it. I'll just figure out that color.

**Comment by TheColaber** [comment]
K awesome.

**Comment by YOYITsM3M8** [comment]
> Yes, this is a bug(ish). You can specify it. I'll just figure out that color.

is it #0075ff?

**Comment by TheColaber** [comment]
Seems like it's all not simple: https://stackoverflow.com/questions/34388696/how-to-change-the-background-color-on-a-input-checkbox-with-css

**Comment by mxmou** [comment]
> Seems like it's all not simple: https://stackoverflow.com/questions/34388696/how-to-change-the-background-color-on-a-input-checkbox-with-css

Which means we need to either create our own design for the checkboxes or leave it to the browser.

**Comment by TheColaber** [comment]
I would prefer to make it look like chrome's.

**Comment by mxmou** [comment]
@WorldLanguages What's the intended behavior here?

**Comment by WorldLanguages** [comment]
Well, here we go again with issues with form elements across browsers...
I'd like to see Edge's design match Chrome's, but it might not be possible, I'm not sure.

**Comment by mxmou** [comment]
In Firefox (with high DPI) it looks even worse, at least on Windows:
![Screenshot](https://user-images.githubusercontent.com/51849865/99574778-1b24bf80-29d8-11eb-9753-46f5e2b9d1ab.png)

We probably need to make our own design for the checkboxes.

**Comment by TheColaber** [comment]
> In Firefox (with high DPI) it looks even worse, at least on Windows:
> ![Screenshot](https://user-images.githubusercontent.com/51849865/99574778-1b24bf80-29d8-11eb-9753-46f5e2b9d1ab.png)
> 
> We probably need to make our own design for the checkboxes.

Yeah in the discord "help-with-code" channel I presented what I had so far.
