### ISSUE TITLE
Editor find bar: Use browser's find tool after pressing ctrl+f twice consecutively

### ISSUE THREAD

**Issue by hueychen27** [ScratchAddons/ScratchAddons#7635]
### Why this would be helpful

On certain occasions, I want to use the browser's find tool in the editor. The editor find bar addon prevents this from happening and intercepts ctrl+f.

### My suggestion

Pressing ctrl+f twice quickly will close the editor find bar and allow the browser's find tool.

**Comment by DNin01** [comment]
Related: #6483

**Comment by hueychen27** [comment]
Maybe a different shortcut like ctrl+shift+f could be used?

**Comment by Secret-chest** [comment]
You can use `F3` to bring up the browser's find bar, or find it in the menu.

**Comment by hueychen27** [comment]
True, but I still want to use ctrl+f.

**Comment by WorldLanguages** [comment]
> Maybe a different shortcut like ctrl+shift+f could be used?

For our own find bar? It's technically possible, but it will take getting used to, so no.
For bringing up the browser's native find/search bar: no, it cannot be opened programatically with JavaScript.

**Comment by DNin01** [comment]
> > Maybe a different shortcut like ctrl+shift+f could be used?
> 
> 
> 
> For our own find bar? It's technically possible, but it will take getting used to, so no.

Unless it were… well, customizable.

**Comment by hueychen27** [comment]
> For bringing up the browser's native find/search bar: no, it cannot be opened programatically with JavaScript.
Well, can't you not capture or cancel ctrl+f when pressing it twice quickly for it to work?
