### ISSUE TITLE
Images are broken

### ISSUE THREAD

**Issue by sargent-coding** [ScratchAddons/ScratchAddons#764]
**Describe the bug**

Images are broken.

**To Reproduce**

null

**Expected behaviour**

Show images.

**Screenshots**

![image](https://user-images.githubusercontent.com/65425469/99278464-148e2080-27fd-11eb-9ff7-6874f288208a.png)

**Device (please complete the following information):**

- OS: Chrome OS
- Browser: Chrome

**Comment by JeffaloBob** [comment]
that's a scratch bug

**Comment by TheColaber** [comment]
No, I think scratch wasn't able to load the image. They get the image from a certain url.

**Comment by sargent-coding** [comment]
That was quick.

**Comment by WorldLanguages** [comment]
Yeah, as other people said, that's Scratch working badly

**Comment by Explosion-Scratch** [comment]
Happened to me for a split second too.
