### ISSUE TITLE
About releases ~v1.38.3

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#7648]
4 hours ago, jeffalo said: (source: #7646)

> At Scratch we're seeing some extremely high request rates to these endpoints [scratch.mit.edu/csrf_token/] (orders of magnitude higher than other endpoints), we would like to identify which requests are coming from Scratch Addons.

Because of PR #6614 which added rate-limiting to this part of Scratch Addons, we know that each online user is not sending more than 0.7 requests of this type per second (this is a way more strict limit than the Chrome built-in anti-DDoS protection). However, and let me speculate, these numbers can add up. If 100,000 Scratch Addons users are online, overall 4M requests are possibly being sent each minute.

I merged PR #7647 to mitigate the issue, which makes the following changes:
- The affected endpoint (/csrf_token) is not accessed anymore as I couldn't quickly figure out its purpose.
- The rate-limiting has been changed to be more strict. It should be about 0.4 requests per second now.
- Other merged PRs that also intend to reduce the amount of requests were cherry-picked.

Version v1.38.3 was already sent to the Chrome Web Store for review and should reach to users shortly.

An additional note: it might be a Mandela effect, but as far as we can remember, Scratch used to ping this endpoint on each page load. This may have changed in the last year or so without us noticing.

**Comment by WorldLanguages** [comment]
Related: https://github.com/ScratchAddons/ScratchAddons/issues/6729

**Comment by WorldLanguages** [comment]
After v1.38.3 is reviewed, I will release v1.38.4 to fix a small code change mistake I missed: https://github.com/ScratchAddons/ScratchAddons/pull/7647/files#r1678271650

Users experiencing issues because of this mistake (specially after logging in or out) can disable and reenable the extension to reload it. Or they can also wait a few minutes, as Manifest V3 will periodically reload the background process.

**Comment by hueychen27** [comment]
So I was not the only one noticing that log out issue.

**Comment by WorldLanguages** [comment]
I'm working on more optimizations here: PR #7666

**Comment by WorldLanguages** [comment]
See #7651 for discussion.

**Comment by DNin01** [comment]
I'm not sure if we do this already, but we don't have to check for messages when "do not disturb" is on.

**Comment by WorldLanguages** [comment]
> I'm not sure if we do this already, but we don't have to check for messages when "do not disturb" is on.

True, but it probably doesn't make a difference in the grand scheme of things.

**Comment by WorldLanguages** [comment]
I opened a PR that disables `msg-count-badge` for new users, as well as existing users that don't have the extension pinned: #7686
This *should* decrease the amount of message count requests we send from the background.

**Comment by WorldLanguages** [comment]
Here are other changes I was talking with @TheColaber the other day. We would want to include them for v1.39.0

About the code that previously caused an infinite loop (`chrome.cookies.onChanged` causing a cookie change)
We agreed on the following changes:
- When a cookie changes, always wait 500ms before reacting to it (ensures multiple cookie changes can be considered together)
- Every cookie change delays the response by another 500ms
- When reacting to a cookie change, we only consider the most recent value for each affected cookie
- While reacting and processing the cookie change, the onChanged listener is removed
- After finishing (includes waiting for fetch responses), wait 500ms and only then continue to listen for cookie change events

Drawback: in certain scenarios, we might be using old auth data. But I don't think there's a way to keep reliability and no-infinite-loops at the same time.

Other changes to be made in the same file:
- We can completely ignore cookie changes if they're equal to the previous values. This is already checked for CSRF token but not for other cookies.
- According to TheColaber, changes to the scratchlanguage cookie are not detected by our event.
- If the logged-in account changed, we don't really need to tell every opened tab about it. See the code comment that says "aside from extra requests"

Other potential enhancements:
- The caching done by `scratch-messaging` (fetching the most recent 40 messages even if the user hasn't interacted with the popup) should be removed.
- The item above means: the background process of the extension only needs to care about Scratch auth if `msg-count-badge` or `scratch-notifier` are enabled. If they are both disabled, there's no reason to know the username that is logged-in on the background process of the extension.

**Comment by WorldLanguages** [comment]
After obtaining more information, here is what you should know.

- Extra calls to the /csrf_token endpoint complicated the situation but were not the main cause of the outages in May-July. Scratch handles **a lot** of traffic every day. 
- It is true, however, that [this tweet by the Scratch Team](https://twitter.com/scratch/status/1812940625727398025) (`Great news: our engineers have been hard at work solving the issues impacting our servers. You should notice improvements to site stability and reliability as of today`) was published immediately after blocking all requests Scratch Addons clients were sending to /csrf_token.
- The /csrf_token endpoint was particularly expensive due to the way it interacted with databases, and combined with unstable networking, it created a big pile of requests that had the same priority as requests by actual users.
- The Scratch Team may at some point propose the use of API tokens for multiple reasons, including backend service troubleshooting, monitoring sudden changes in access, and less chance of our requests getting blocked by firewalls and other blocking systems.

**Comment by TheColaber** [comment]
Related: #7702

**Comment by WorldLanguages** [comment]
Suggestion by RedGuy: we could add some caching to Scratch Messaging if the popup is opened more than once in a very short period of time. Would also enhance user experience.
