### ISSUE TITLE
`copy-message-link` can cause lots of lag on profile pages with a lot of comments

### ISSUE THREAD

**Issue by CST1229** [ScratchAddons/ScratchAddons#7656]
### Description

(is this a bug??? idk)
The Copy link to comment button addon causes lots of lag (at least on profile pages) when you load enough comments. The lag intensifies the more comments you load.
I assume this is due to its use of addon.tab.waitForElement, which I'm pretty sure uses document.querySelectorAll, and that gets slower the more elements the page has. If you turn off the addon and reload the page, profile pages stop lagging even after loading lots more comments

### Steps to reproduce

1. Enable `copy-message-link` (Copy link to comment button) and go to any profile with a lot of comments, like griffpatch's
2. Scroll down and press the Load More button a bunch
3. Observe how it starts lagging a lot once you press Load More enough
4. If you turn off the addon and reload the page, it doesn't lag anymore

### Environment

Browser: Firefox 129.0b3
Scratch Addons version: 1.38.4
Operating system: Windows 10

**Comment by WorldLanguages** [comment]
See #2831

I think Scratch uses a weird pattern when loading new comment pages. Possibly, each time a new page loads, all comments are new DOM elements. Or something weird like that.

As far as I've seen, all implementations are either ugly and slowish, or they break in unexpected ways when loading new comment pages.
