### ISSUE TITLE
`blocks2image`: up to 10x worse performance without `editor-theme3`

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#7681]
### Description

Without `editor-theme3` enabled `blocks2image` can take up to 10 times longer to export images compared to when it is enabled. Normally that isn't a big deal but it can add up when exporting 100+ blocks.

### Steps to reproduce

1. Enable `blocks2image` and disable `editor-theme3`
2. Open [Paper Minecraft](https://scratch.mit.edu/projects/10128407/editor/)
3. Switch to the "Steve Arm" sprite
4. Export all blocks as an image
5. Enable `editor-theme3`
6. Export the blocks again

### Demonstration(s) and additional context

https://github.com/ScratchAddons/ScratchAddons/pull/6830#issuecomment-2248706640:

> > The steve arm sprite takes about 400ms (edit: 250ms) for me to load the preview
> 
> Do you happen to have `editor-theme3` enabled? For me it seems to significantly improve the performance for whatever reason.
> 
> ![](https://camo.githubusercontent.com/4fd12e21b676a80c2592d56264d6e21d07ea220f3e8d695336c0b8db65cbfbe3/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3735353133313734333133363338333130372f313236353734383630383936303136383034392f696d6167652e706e673f65783d36366132613363302669733d363661313532343026686d3d6661313332633331326439386430613131333134643036366566373336646234646630643833653236303633376461663139303062643036623637653939336626)

### Environment

Browser: Chromium 126
Scratch Addons version: 1.38.4
Operating system: Linux

**Comment by WorldLanguages** [comment]
See comment https://github.com/ScratchAddons/ScratchAddons/pull/6907#issuecomment-2249229824
