### ISSUE TITLE
clone counter - negative numbers

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#769]
**Describe the bug**

negative clone counts when deleting sprites

**Additional context**

i keep forgetting to fix this

**Comment by JeffaloBob** [comment]
it's a pretty simple change of == 0 to less than or equal to 0

**Comment by WorldLanguages** [comment]
I got a question about this on my profile lol

**Comment by WorldLanguages** [comment]
fix tomorro pls @JeffaloBob

**Comment by JeffaloBob** [comment]
> WorldLanguages commented 23 hours ago

sorry, will fix next tommorow
