### ISSUE TITLE
Old project layout

### ISSUE THREAD

**Issue by ghost** [ScratchAddons/ScratchAddons#7705]
### Why this would be helpful

Does this remind you of anything?

![300px-Scratch_2_project_page](https://github.com/user-attachments/assets/30c894dd-f0dc-4779-a70f-770520dd2bed)

We should add something like this that makes the project page look like it, we done that with studios already.

### How this addon works

Changes the Scratch 3.0 project page's layout to look more like Scratch 2's version.

**Comment by rickbot-dot** [comment]
Bump
