### ISSUE TITLE
Should `animated-thumb` be enabled by default?

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#7708]
Probably not

**Comment by TheColaber** [comment]
😭 it only adds a button

**Comment by WorldLanguages** [comment]
It adds a button in a space that's already crowded

**Comment by TheColaber** [comment]
😭 it used to be in a different place

**Comment by Samq64** [comment]
The menu bar was also crowded

**Comment by WorldLanguages** [comment]
Maybe we can set a key in storage if the button is clicked. Let 2 or 3 months pass by. And disable the addon for everyone who hasn't used it

**Comment by TheColaber** [comment]
i thought we were making a change for new users?

**Comment by jeffalo** [comment]
it also adds in functionality that’s not really possible in scratch. probably makes things a little harder for moderators.
