### ISSUE TITLE
Addon popups should not be hardcoded

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#773]
(Moved from #15 and #16) 

Currently (since v1.0.0 until now) popups are "hardcoded". This means that:
1) Addons can't specify details about their popup on their manifest
2) Users can't remove/reorder/etc. popups
3) Addons have no standard way to send messages from/to popups
4) Addons don't actually have `addon.*` APIs, and localization works weirdly on them

**Comment by Hans5958** [comment]
Any updates?

**Comment by WorldLanguages** [comment]
@Hans5958 Likely dropping for next release, when I made this issue localization wasn't a thing, so I'll need to coordinate with apple :P
