### ISSUE TITLE
Command Palette for Scratch!

### ISSUE THREAD

**Issue by blazgocompany** [ScratchAddons/ScratchAddons#7743]
### Why this would be helpful

Scratch is slow. Anyone trying to make complicated projects will realize that. This command palette can be triggered on any page with a quick <kbd>Ctrl</kbd> + <kbd>K</kbd>. Then you can type in any command to quickly do common tasks.

### How this addon works

Here is a list of the planned commands:

Navigation commands: Easily navigate to any part of the Scratch site.
Editor commands: Add snippets (pre-built functions) to the editor quickly.
Button commands (idk what to call these): Do common actions on a page without actually visiting it. (e.g. Heart a project just by it's link)

### Possible alternatives

N/A?

### Additional context

Nothing right now. I want to know if this should be added before I start working on it.

**Comment by WorldLanguages** [comment]
@blazgocompany A few minutes ago I banned you from the ScratchAddons GitHub organization, for a period of 30 days. Please take advantage of this time to reconsider your behavior in this and other repositories. Feel free to come back next month!
