### ISSUE TITLE
Find box overlapping thumbnail selector

### ISSUE THREAD

**Issue by areeq0325** [ScratchAddons/ScratchAddons#776]
**Describe the bug**

Title says it all

**To Reproduce**

Set a thumbnail with developer tools on

**Expected behavior**

The set thumbnail dialogue should be on top

**Screenshots**

![image](https://user-images.githubusercontent.com/69761212/99468014-92d9e800-290d-11eb-8729-cc05fded1d85.png)

**Device (please complete the following information):**

Windows 10, Cr-based Edge 86

**Comment by TheColaber** [comment]
Oh yeah, this is something @WorldLanguages needs to fix on his side... he just needs to add a bit of z-index to his code.
