### ISSUE TITLE
Scratch Addons v1.39.0 doesn't work in Firefox

### ISSUE THREAD

**Issue by JakubMzTrencina** [ScratchAddons/ScratchAddons#7761]
### Description

I've opened Scratch today, and the first thing I've noticed was the navigation bar being purple (I use an addon to make it blue, as purple isn't my color) Then I checked the forums, and the field where one writes a post was lacking some features I've enabled on SA. Opening the SA configuration, it seems it's loading forever, and doesn't do anything. I tried disabling them, and even reinstalling, but it didn't fix the issue. I suspect it happened when SA updated.

Edit: The affected version was removed by World-Languages from the Firefox store. If you've encountered the same bug, you probably have the 1.39.0 version. You can downgrade by following [this](https://github.com/ScratchAddons/ScratchAddons/issues/7761#issuecomment-2315312182).

Any existing settings from before the update will persist.

### Steps to reproduce

I don't really think there's a way to reproduce this issue, just try loading the Scratch page or openning SA and you may or may not see the issue.

### Environment

Browser: Firefox 129.0.2
Scratch Addons version: v1.39.0
Operating system: Windows 10

**Comment by JakubMzTrencina** [comment]
i've just realised i should've used the "Send Feedback" page on the SA webpage
ah well, i guess feel free to close this, if you find it useless

**Comment by CST1229** [comment]
I'm also encountering this issue by the way. I posted this in the SA Discord too:

> The settings page errors when trying to get the extension's settings, apparently. Maybe it's some error in the background page (or whatever its MV3 equivalent is).
> ![image](https://github.com/user-attachments/assets/ae6b8c65-3905-44ab-a43e-b6397732fe71)
> And the popup has the error TypeError: can't access property "manifests", res is undefined.
> ![image-1](https://github.com/user-attachments/assets/fb8c056b-d9e3-4cd3-88c8-5c1e0e3750f7)
> I tried restarting the browser and the extension several times but it didn't fix the issue.
> Inspecting the extension's background(???) page using about:debugging then reloading it, it seems that it complains about chrome.scripting not being available?
> ![image](https://github.com/user-attachments/assets/dd5e5314-ceac-4f64-b11f-dff783ec984b)
> 
> Firefox version: Firefox Developer 130.0b9 (64-bit)

> now the extension runs into this error (showing the error page)
> ![image](https://github.com/user-attachments/assets/57d0ceb5-259b-45aa-863a-c443426462da)
> and the extension.... works perfectly when loading it from file?

**Comment by Samq64** [comment]
The `chrome.scripting` error is caused by #7474. `background/firefox-localhost-support.js` doesn't exist on 1.38.5.

**Comment by rickbot-dot** [comment]
Also encountering this. Idk if this should be priority: 1.

**Comment by CST1229** [comment]
> Also encountering this. Idk if this should be priority: 1.

A [crash bug](https://github.com/ScratchAddons/ScratchAddons/issues/4831) and [theme setting changing not working](https://github.com/ScratchAddons/ScratchAddons/issues/1841) got labelled prio 1, and this literally breaks the whole extension on a whole browser, so yeah this should probably be too.

**Comment by JakubMzTrencina** [comment]
Is it someway possible to downgrade to an older version? I don't wanna use Chrome.

**Comment by rickbot-dot** [comment]
> Is it someway possible to downgrade to an older version? I don't wanna use Chrome.

Click "Version history" in the about this addon part of the Scratch Addons addon page, then look for 1.38.5 and hit download file to downgrade.

Any existing settings from before the update will persist.

**Comment by JakubMzTrencina** [comment]
I couldn't seem to find the about this addon part, and Firefox being in Slovak language wasn't helping, so I exported my settings to a JSON, and re-installed SA. Everything seems to be working now.

**Comment by kccuber-scratch** [comment]
A user just reported in the discord that they are having this issue on Google Chrome as well.

![image](https://github.com/user-attachments/assets/48808cee-2e9b-4198-a880-3dbd14cc681e)

**Comment by Samq64** [comment]
> A user just reported in the discord that they are having this issue on Google Chrome as well.

That's a different root cause. Could you tell them to fully restart the browser and see it that helps?

**Comment by WorldLanguages** [comment]
A restart fixed it for that user

**Comment by Rhlp-Engineering** [comment]
still does not work for me!
