### ISSUE TITLE
Mismatching colors

### ISSUE THREAD

**Issue by areeq0325** [ScratchAddons/ScratchAddons#778]
**Describe the bug**

Devtools block colors don't match custom colors

**To Reproduce**

Enable custom colors and devtools
Middle click

**Expected behavior**

Devtools colors should match custom colors

**Screenshots**

![image](https://user-images.githubusercontent.com/69761212/99468773-5effc200-290f-11eb-9d8d-1541e91bd45e.png)

**Device (please complete the following information):**

Windows 10, Cr-based Edge 86

**Comment by TheColaber** [comment]
Duplicate of #666

Please close

**Comment by Hans5958** [comment]
Duplicate of #666
