### ISSUE TITLE
CSS issue with echo button (`echo-effect`)

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#7786]
### Description

![image](https://github.com/user-attachments/assets/6137c5c1-8a33-496c-a0ef-4ca11bd7e85a)

### Steps to reproduce

Enable the addon

I believe this is caused by a Scratch update, not by our updates

### Demonstration(s) and additional context

None

### Environment

Browser: Chrome
Scratch Addons version: 1.39.1

**Comment by Samq64** [comment]
userscript.js:
```js
echoButton.className = addon.tab.scratchClass("icon-button_container", "sound-editor_effect-button");
```
DOM:
```html
<div class=" sound-editor_effect-button_UayWP" data-sa-hide-disabled="echo-effect" role="button">
```

Could this be caused by #7559?

**Comment by WorldLanguages** [comment]
> I believe this is caused by a Scratch update, not by our updates
