### ISSUE TITLE
Custom colors not applying to custom blocks

### ISSUE THREAD

**Issue by areeq0325** [ScratchAddons/ScratchAddons#779]
**Describe the bug**

Custom colors not applying to custom blocks

**To Reproduce**

Enable custom colors
Make a block

**Expected behavior**

Colors should match
**Screenshots**

![image](https://user-images.githubusercontent.com/69761212/99469167-1b598800-2910-11eb-8bb0-71fd626eb414.png)

**Device (please complete the following information):**

Windows 10, Cr-based Edge 86

**Comment by areeq0325** [comment]
To clarify, shouldn't
![image](https://user-images.githubusercontent.com/69761212/99555160-fefc3080-298d-11eb-97cb-c844bd32ad90.png)
and
![image](https://user-images.githubusercontent.com/69761212/99555095-eb50ca00-298d-11eb-84c2-145497a3d53f.png)
be
a darker version of
![image](https://user-images.githubusercontent.com/69761212/99555118-f4419b80-298d-11eb-9a5b-a8efc44086ef.png)
?

**Comment by mxmou** [comment]
> To clarify, shouldn't
> ![image](https://user-images.githubusercontent.com/69761212/99555160-fefc3080-298d-11eb-97cb-c844bd32ad90.png)
> and
> ![image](https://user-images.githubusercontent.com/69761212/99555095-eb50ca00-298d-11eb-84c2-145497a3d53f.png)
> be
> a darker version of
> ![image](https://user-images.githubusercontent.com/69761212/99555118-f4419b80-298d-11eb-9a5b-a8efc44086ef.png)
> ?

They should probably be the same color as the block border.

**Comment by areeq0325** [comment]
Closing for now.

**Comment by WorldLanguages** [comment]
Why?

**Comment by areeq0325** [comment]
Unless any of you can fix, I'll just let it be.

**Comment by WorldLanguages** [comment]
Even if it's never fixed it's good to leave it open.
