### ISSUE TITLE
conflict between the Scratch Tools sprite layers plugin and the scratch addons collapsing sprites properties plugin

### ISSUE THREAD

**Issue by ksdavidc** [ScratchAddons/ScratchAddons#7791]
### Description

There seems to be a conflict between the Scratch Tools sprite layers plugin and the scratch addons collapsing sprites properties plugin. If both are enabled, the popup is hidden under the sprites section of the editor.

### Steps to reproduce

1. enable the plugins
2. hover over the show icon in the sprite properties

### Demonstration(s) and additional context

- How it should look (i.e. with collapsing properties off) ]

<img width="372" alt="Screenshot 2024-09-09 at 3 19 30 AM" src="https://github.com/user-attachments/assets/58ed51e0-50bf-4491-ba29-50fad8474366">

- with collapsing properties on:

<img width="349" alt="Screenshot 2024-09-09 at 3 20 14 AM" src="https://github.com/user-attachments/assets/0c58b8d5-a299-40ae-87ed-45d06cc29cad">

### Environment

Browser: 
Scratch Addons version: 
Operating system: 
latest chrome, sa 1.39.1, ST Version: 3.9.1,  mac 14.6.1

**Comment by Samq64** [comment]
We don't support having both extensions enabled and don't usually fix compatibility issues between the 2 unless it's a 1 line fix.

**Comment by ksdavidc** [comment]
fair enough, but recorded here for posterity. Quite a shame IMHO from a user perspective as each has something to offer the other doesn't. something about babies and bathwater or is it noses and faces.

**Comment by WorldLanguages** [comment]
Is there an issue number in the ScratchTools repository?

**Comment by ksdavidc** [comment]
> Is there an issue number in the ScratchTools repository?
Orignally reported there but not in the repo, but now there is: https://github.com/STForScratch/ScratchTools/issues/962

**Comment by ksdavidc** [comment]
Here's the thing. This is an **extremely** minor bug. **_Extremely_**. I get it. I don't care if it gets fixed, ever. It's cool, but I lose no sleep without it.

I only reported it for completeness and because it looks like you two guys are playing over each other in the same space and it might be a simple fix, some css or something.

If you want an actual really annoying conflict between the two, you can see this more serious one that breaks SA "insert blocks by name" completely: https://discord.com/channels/945340853189247016/1259626053601853460
This is the one I should have reported, as it really bugs me and makes using ST impossible, and I hope they fix it. First I just disabled ST entirely but after a long time I enabled it hoping it was fixed, but it isn't. Even if I thought to add it here, I don't have enough information about what's causing it to even begin describing it adequately.

The point being I don't blame you for not wanting to maintain intercompatibility. I understand the difficulties that must entail. In general I trust SA more, and the code is more stable. ST has bugs even with ALL the plugins disabled, many are dupes of SA versions, but some are unique, such as this one. For users, though, this presents a bit of dilemma, since we are at your mercies (oh and grateful for it, don't get me wrong). If my coding chops were better I'd fix them myself, but the learning curve is...well, someday.

**Comment by WorldLanguages** [comment]
To be clear, we don't have strict rules on whether these are worth fixing, nor whether these types of issues deserve to stay open.

Not everyone can access that Discord link, so I encourage you to create a Github issue (in one or both repositories) with all of the information, even if you don't have precise reproduction steps.

**Comment by ksdavidc** [comment]
> To be clear, we don't have strict rules on whether these are worth fixing, nor whether these types of issues deserve to stay open. Personally I wouldn't have closed this issue.
> 
I understand, sometimes you can't really tell how hard it will be to cross the bridge until you actually cross the bridge, and this is a very low-traffic bridge. I just wanted to put up a warning flag, not necessarily lead a march. I am confident it would get fixed in due course...

> Not everyone can access that Discord link, so I encourage you to create a Github issue (in one or both repositories) with all of the information, even if you don't have precise reproduction steps.

Was waiting to see how discord went, but the cat is out of the bag now:
https://github.com/STForScratch/ScratchTools/issues/964
https://github.com/ScratchAddons/ScratchAddons/issues/7794

**Comment by MaterArc** [comment]
@ksdavidc This turned out to be a very simple 3 line CSS fix. 

I've opened a PR [here](https://github.com/STForScratch/ScratchTools/pull/966) for reference

**Comment by MaterArc** [comment]
> @ksdavidc This turned out to be a very simple 3 line CSS fix.
> 
> I've opened a PR [here](https://github.com/STForScratch/ScratchTools/pull/966) for reference

Hopefully, that should fix the issue! Not really sure why there was an `overflow: hidden` there 😆

**Comment by ksdavidc** [comment]
> Hopefully, that should fix the issue! Not really sure why there was an `overflow: hidden` there 😆

Awesome, quite usable. 

I will add however (https://github.com/STForScratch/ScratchTools/issues/962#issuecomment-2350101128) that I have added to ST a note as follows, that, again, is not of importance and that should be fixed there if at all, assuming it is on their end:

> With SA enabled, the text of the popup is being omitted, which lack you can see in my orignal image.
> 
> I will also add, for future reference only and don't expect it to be fixed, that there is also a problem if one is using the "display stage on left side"...the left part gets cut off (also visible in original image)...Which brings up: the ST "display on left" plugin does not seem to be working at all for me, even with SA turned off, but the SA display on left works, but then layers cuts off. But I just went back to putting in the default right position.
> 
>

**Comment by MaterArc** [comment]
> > Hopefully, that should fix the issue! Not really sure why there was an `overflow: hidden` there 😆
> 
> Awesome, quite usable.
> 
> I will add however ([STForScratch/ScratchTools#962 (comment)](https://github.com/STForScratch/ScratchTools/issues/962#issuecomment-2350101128)) that I have added to ST a note as follows, that, again, is not of importance and that should be fixed there if at all, assuming it is on their end:
> 
> > With SA enabled, the text of the popup is being omitted, which lack you can see in my orignal image.
> > I will also add, for future reference only and don't expect it to be fixed, that there is also a problem if one is using the "display stage on left side"...the left part gets cut off (also visible in original image)...Which brings up: the ST "display on left" plugin does not seem to be working at all for me, even with SA turned off, but the SA display on left works, but then layers cuts off. But I just went back to putting in the default right position.

I've fixed the text not showing up now too!
