### ISSUE TITLE
I wish we can add a feature where you can easily make the character walk on platforms

### ISSUE THREAD

**Issue by mimipepper2023** [ScratchAddons/ScratchAddons#7797]
### Why this would be helpful

Sometimes I want to make characters walk on floors without master coding but it's hard, i dont know if this will be added but yes i know scratch jr has a realistic jump code so i also want it to be added :)
![block_9_10_2024-2_16_42 PM3](https://github.com/user-attachments/assets/01ead79b-ecfd-41bf-9cbb-15c126b2862d)
![block_9_10_2024-2_16_42 PM2](https://github.com/user-attachments/assets/f4c7c135-f9cf-443a-a39b-f880939434d8)

### How this addon works

![block_9_10_2024-2_16_42 PM2](https://github.com/user-attachments/assets/8ca42a5c-aeab-4ebc-93a8-d289376169b2)
Inputs the area, click it to make the character jump, like in the scratch jr code.
![block_9_10_2024-2_16_42 PM3](https://github.com/user-attachments/assets/18bbab0a-9f77-4b20-890d-2316c0d016e8)
Makes the character walk on another sprite, easier for beginners who want to make platforms

### Additional context

i am new to making sprites walk on ground and make the sprites jump and i want some simple code :)

**Comment by CubesterYT** [comment]
Incompatible, we can't make new blocks in Scratch, and even if we could, it would make these projects with the new blocks only work with people using the addon.

**Comment by Samq64** [comment]
There's a similar block extension on https://extensions.turbowarp.org/
