### ISSUE TITLE
`better-img-uploads`: Option is visually broken

### ISSUE THREAD

**Issue by mybearworld** [ScratchAddons/ScratchAddons#7805]
### Description

See screenshot below

### Steps to reproduce

1. Enable `better-img-uploads`

### Demonstration(s) and additional context

![image](https://github.com/user-attachments/assets/17ace9f0-a428-4cab-b8ef-e51ef7f6edb0)

### Environment

Browser: MS Edge 128
Scratch Addons version: 1.39.1
Operating system: Windows

**Comment by Samq64** [comment]
Seems to be the same root cause as #7786?

**Comment by MasonYayYay** [comment]
![image](https://github.com/user-attachments/assets/67de3e0e-ec36-4f33-88d5-00bcc065c4be)
 

> This seems similar to #7786. Could the root cause be the same?

it might be but maybe you haft to update it to be able to fix it.

**Comment by mybearworld** [comment]
This is probably due to a change in Scratch itself - the arrow is now black in vanilla Scratch:
![image](https://github.com/user-attachments/assets/a321724b-dff8-4c49-af45-b99d585e9a1a)

And the same thing happens to `paint-by-default`.
![image](https://github.com/user-attachments/assets/07bf163d-9db1-4b5f-9d62-85a6e091ab89)

**Comment by mxmou** [comment]
This was probably caused by https://github.com/scratchfoundation/scratch-gui/commit/3c2afd102a5c74c0b83f3b9654b926de235c31fc.

**Comment by iqnite** [comment]
Adding `display: none` to the `input` element fixes part of the issue. How about the broken tooltips?

**Comment by mxmou** [comment]
#7808 fixes the button but not the tooltip.
