### ISSUE TITLE
Debugger preformace tab doesn't support dark mode

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#7814]
### Description

The debugger addon's performance tab does not properly support dark mode.

### Steps to reproduce

1. Enable `debugger` and `editor-dark-mode`
2. Open the editor
3. Open the debugger and select the performance tab

### Demonstration(s) and additional context

![screenshot-2024-09-16-19-26-05](https://github.com/user-attachments/assets/dda3ed1e-e9ad-4017-9628-c9db143c2807)

### Environment

Browser: Chromium
Scratch Addons version: master
Operating system: Linux

**Comment by mxmou** [comment]
This only happens if website dark mode is disabled.
