### ISSUE TITLE
notice on `forum-search` explaining scratchdb situation

### ISSUE THREAD

**Issue by sillybreakfast** [ScratchAddons/ScratchAddons#7835]
### Why this would be helpful

people may get confused when it doesn't work

### My suggestion

add a notice saying "This addon is temporarily broken since the ScratchDB database used by it is offline."

**Comment by sillybreakfast** [comment]
i already made a fork and fixed the issue on it but contributing guidelines said to create an issue first :P

**Comment by mxmou** [comment]
If the downtime is only temporary, it will likely be fixed before we release an update with this notice.

**Comment by sillybreakfast** [comment]
> If the downtime is only temporary, it will likely be fixed before we release an update with this notice.

i was about to say it's been like this for months, but it appears progress is being made to fix it

**Comment by mxmou** [comment]
> > If the downtime is only temporary, it will likely be fixed before we release an update with this notice.
> 
> i was about to say it's been like this for months, but it appears progress is being made to fix it

The old ScratchDB API has been online for a few months, but there's a new one just for searching the forums. It was broken earlier today but it appears to work now, so I'm closing this.
