### ISSUE TITLE
Make "Addons" the first (far left) popup tab

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#7842]
### Why this would be helpful

Scratch Addons' extension action's popup has three tabs, "Messaging", "Games", and "Addons". Back in our beginning, the first and default selected tab was "Messaging". This is understandable when you consider our Scratch Messaging roots.

But overtime, we've shifted focus away from the messaging aspect, and now the Messaging tab is no longer always selected automatically (#4885) nor is it the default (#6781). This makes sense for our current mission — to provide useful and customizable addons for the Scratch _website_.

### My suggestion

One more thing we could do is move the Addons tab to the far left of the bar, like this:

![Tabination with Addons, Messaging, and Games](https://github.com/user-attachments/assets/b58e2025-2130-48e6-a3b7-ed183c9101da)

Being the default tab now, it's more sensible and expected to be the first one. Plus, if you toggle the addons that add Messaging and Games tabs, the Addons tab will remain in the same position, making it more consistent.

### Possible alternatives

We could also rethink the tab bar entirely. (...Are we ever going to add more tabs?)

**Comment by WorldLanguages** [comment]
I agree, but I don't love the idea of ruining muscle memory for thousands of users :P

Maybe we could reach this but with multiple steps? For example, we could have it duplicated for some time, but without changing the positions of the tabs too much. Then, when we actually change it to look like your screenshot, it won't be so drastic.

![image](https://github.com/user-attachments/assets/101c3449-56f2-4295-a47e-29b49edc89d6)

**Comment by mxmou** [comment]
> Maybe we could reach this but with multiple steps? For example, we could have it duplicated for some time, but without changing the positions of the tabs too much. Then, when we actually change it to look like your screenshot, it won't be so drastic.

Duplicating things makes the UI confusing - If I saw that screenshot without context, I would probably think there was a difference between the two tabs. (This reminds me of #2353.)

I think a better solution is to change the design of the tabs at the same time. This way, users would immediately see that something is different. For example:
![image](https://github.com/user-attachments/assets/22232fef-f18b-47ae-a4d0-c28887a69a6c)

**Comment by DNin01** [comment]
We could provide an option to set it back to what it was before, but at the same time, we might not want to clutter our settings with too many obscure customizations.

If we do, then we could move the Addons tab to the left by default but make it easy to revert by displaying a notification within the popup, to existing users, saying that the tab has moved, with two buttons, one to keep it that way and one to revert it back.

![The Addons tab with a message saying, "The Addons tab is now at the far left", with two buttons, Revert and OK](https://github.com/user-attachments/assets/eeb0cad4-5cb7-4901-9ff6-fafe48be605f)

**Comment by DNin01** [comment]
Perhaps the tabs could be rearrangeable by dragging them or changes settings. This would allow not just the Addons tab to be moved, but all the tabs, so you could make Games be the first tab if you wanted. Since the addon on/off switches that control the visibility of the tabs are customization, I don't see any reason not to let the user also rearrange them.

**Comment by CST1229** [comment]
> Maybe the tabs could be rearranged by dragging them or changing settings. This would allow not just the Addons tab to be moved, but all the tabs, so you could make Games be the first tab if you wanted. Since the addon on/off switches that control the visibility of the tabs are customization, I don't see any reason not to let the user also rearrange them.

I support tab drag-rearranging. (Though I feel like it could be hinted at somehow; could either be text somewhere, a small drag handle on the tabs or a drag cursor)

**Comment by WorldLanguages** [comment]
> I think a better solution is to change the design of the tabs at the same time. This way, users would immediately see that something is different

I like the idea

**Comment by mxmou** [comment]
> > I think a better solution is to change the design of the tabs at the same time. This way, users would immediately see that something is different
> 
> I like the idea

PR based on the code I used to make that screenshot: #7847
