### ISSUE TITLE
Most editor addons not displaying or working

### ISSUE THREAD

**Issue by tutacat** [ScratchAddons/ScratchAddons#7850]
### Description

Most addons for the editor are not displaying on the official Scratch editor

Tested addons I am using

Working:
* big-save-button
* editor-dark-mode
* extended-backpack
* resizable-comment-input
* transparent-orphans

Not working:
* 60fps
* better-img-uploads
* block-switching
* clones
* devtools
* editor-colored-context-menus
* editor-searchable-dropdowns
* editor-theme3 (colored blocks) (only text color works)
* find-bar
* hide-flyout
* paint-snap
* pause
* progress-bar
* search-sprites
* swap-local-global
* variable-manager
* zebra-striping (alternate nested colors)

### Steps to reproduce

1. Install Scratch Addons extension
2. Enable addons that affect the editor
3. Observe which ones have working effect

### Environment

Browser: Firefox 131
Scratch Addons version: 1.39.1
Operating system: N/A

Other browser extensions:
* None

**Comment by DNin01** [comment]
It would be helpful if you could open your browser's console and report back any errors or warning messages from Scratch Addons.

Is this a recurring issue for you? Do addons work fine if you reload the page once or twice after this error?

**Comment by DNin01** [comment]
Closing until further notice.
