### ISSUE TITLE
editor-stepping/debugger: `setGlowingThreads()` runs even when project isn't

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#7861]
### Description

When the editor is open with the running block border or debugger addon enabled `setGlowingThreads()` is run in an infinite loop which itself calls `Blockly.getMainWorkspace()` every time even if the project isn't running.

### Steps to reproduce

1. Add a console.log at the top of [this function](https://github.com/ScratchAddons/ScratchAddons/blob/3bf0bc6e77da68e58b9f5999a4e27269fc0cac5a/addons/editor-stepping/highlighter.js#L105)
2. Enable the debugger or `editor-stepping`
3. Open the editor and the console

### Demonstration(s) and additional context

![screenshot-2024-10-14-12-04-43](https://github.com/user-attachments/assets/b78ce988-8490-47af-8261-f6c7c712bdd5)

### Environment

Browser: LibreWolf
Scratch Addons version: master (should happen on stable though)
Operating system: Linux

**Comment by GarboMuffin** [comment]
I don't think this is something worth worrying about. It's being run once per VM step per addon that uses the API. Clone counter and variable manager also add code that does that, it's not really an issue. If no threads are being glowed then the function just doesn't do anything as threads will be empty.

**Comment by Samq64** [comment]
I was just a little concerned when I tried to test the extension on  https://gonfunko.github.io/scratch-gui/ and saw non-stop getMainWorkspace errors.
