### ISSUE TITLE
Ability to reset markAsSeen

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/ScratchAddons#7864]
### Why this would be helpful

A few addons use a `waitForElement` loop where it would be easiest to re-iterate over the elements again to handle dynamic enable/disable or setting changes but still want the optimization from `markAsSeen` the rest of the time.

### My suggestion

Add the ability to reset `markAsSeen` from outside the loop for example, in a dynamic re-enable listener.

### Possible alternatives

Store the elements themselves in an object like more links does or find a way to handle as much as possible with just CSS.

**Comment by mxmou** [comment]
> Store the elements themselves in an object like more links does or find a way to handle as much as possible with just CSS.

There's a simpler workaround:
```js
const doSomethingWithElement = (element) => {
  // ...
};

addon.settings.addEventListener("change", () => {
  for (const element of document.querySelectorAll(selector)) {
    doSomethingWithElement(element);
  }
});
while (true) {
  doSomethingWithElement(await addon.tab.waitForElement(selector, {markAsSeen: true}));
}
```

**Comment by WorldLanguages** [comment]
I believe waitForElement is quite complex as-is, I don't like the idea of adding even more options for it.

Also, mxmou's workaround is easy to understand in my opinion.
