### ISSUE TITLE
Automatically delete projects that hadn't been edited in a long time

### ISSUE THREAD

**Issue by M0bile132024** [ScratchAddons/ScratchAddons#7891]
### Why this would be helpful

i have far too many empty or untouched projects that i should go through and delete if i had the time. But i don't(as with many other people).As so this addon will fix that.

### How this addon works

This addon will allow you(in the addon menu thing) to set a specfic time(say 6 months) in which , if the project hasn't been edited in that timespan, it will send a notification to put in the trash, and if it's in the trash already will notify you some time before automatically deleting it.

**Comment by Samq64** [comment]
I think this is too dangerous to add because of data loss unless it only deletes empty projects.
