### ISSUE TITLE
[New addon] Quick launch to various Scratch compilers/players (Phos., Fork., Leopard, etc)

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#79]
**Describe the new addon**

A way to quickly launch projects to Phosphorus, Sulfurous, Forkphorus, Leopard, and other various Scratch compilers/players (if that's the right word.)

**Comment by WorldLanguages** [comment]
Yeah and I would like an addon that loads Phosphorus (and not scratch-vm) until you click "see inside", not sure how possible that would be.

**Comment by Hans5958** [comment]
I'd rather have a dropdown that lets me select what compiler that I wanted to use, and then it loads a new tab with the compiler in it, but that is also good, I guess.

PS. Is "compiler" the correct term?

**Comment by WorldLanguages** [comment]
Probably not, but it's ok as long as we know what we're talking about lol

**Comment by Hans5958** [comment]
> 
> 
> Probably not, but it's ok as long as we know what we're talking about lol

Probably player would be a better term, but, eh, I don't know.

**Comment by JeffaloBob** [comment]
and if someone does this, please also have turbowarp as an option

**Comment by Hans5958** [comment]
TIL TurboWarp is a thing. I wonder what else do they have out there?

**Comment by YOYITsM3M8** [comment]
We can take code for this from https://github.com/yoyitsm3m8/userscripts my turbowarpscratchmod.user.js
