### ISSUE TITLE
`folders` seems to be broken

### ISSUE THREAD

**Issue by CST1229** [ScratchAddons/ScratchAddons#7911]
### Description

The sprite folders addon seems to be entirely broken. I assume this was caused by the vanilla sprite deletion confirmation. This was also reported by several people in feedback.

### Steps to reproduce

1. Enable the sprite folders addon
2. Open the editor
3. All folders functionality is broken

### Demonstration(s) and additional context

Error message:
![image](https://github.com/user-attachments/assets/bc9b1c8b-804a-4794-b26d-6c6ff4241831)

### Environment

Browser: Firefox Developer 133.0
Scratch Addons version: 1.39.1
Operating system: Windows 10

**Comment by GarboMuffin** [comment]
Will look tonight

**Comment by WorldLanguages** [comment]
Sure, I will release an update to users soon
