### ISSUE TITLE
Scratch Addons CSS still broken yet you still do nothing.

### ISSUE THREAD

**Issue by hammouda101010** [ScratchAddons/ScratchAddons#7920]
### Description

![Screenshot 2024-11-07 103333](https://github.com/user-attachments/assets/d3506eb2-b720-4568-a1ed-7ef665bff613)
sprite confirmation popup is broken

### Steps to reproduce

1. Import This Scratch Addons Settings Fille [scratch-addons-settings.json](https://github.com/user-attachments/files/17663988/scratch-addons-settings.json)
2. Go To Scratch Website and Create a New Project
3. Delete a Sprite

### Demonstration(s) and additional context

![Screenshot 2024-11-07 103333](https://github.com/user-attachments/assets/a54bbfb4-d8a2-49e2-8128-cf3d30d70d2f)

### Environment

Browser: Edge
Scratch Addons version:  1.39.1
Operating system: Windows 11

**Comment by WorldLanguages** [comment]
The Edge extension store usually takes 4+ days to approve our updates, so we have no way to shorten the delay for you.

**Comment by DNin01** [comment]
We're working around the clock, but we're a team of volunteers, so it can take a few days to finish fixing up. And on top of that, our extension needs to be reviewed and vetted by store moderators before it's available to the public.

In the meantime, turning off the Scratch Addons extension will fix the issue, and you can turn it back on again in a few days.

Also, the Chrome Web Store gets extensions reviewed much faster than the Edge Add-ons Store. Edge can install extensions from the CWS, so if you want to get it from there, you'll receive updates sooner.

**Comment by DNin01** [comment]
All systems go! We've released the patch and it will become available to you within a few days.
