### ISSUE TITLE
sprite folders does not work

### ISSUE THREAD

**Issue by stopsign84** [ScratchAddons/ScratchAddons#7927]
### Description

I was working on my project that had folders for my sprites for organization and when I went back to working on it I saw the folders just disappeared and now it's tedious to work on my project, which has a whole lot of sprites. I don't know if it's just me.

### Steps to reproduce

1.enable sprite folders
2.right click on sprite to try to make a new folder
3.see there isn't any button for that

### Environment

Browser: 
Scratch Addons version: 
Operating system:

**Comment by DNin01** [comment]
Hang tight, we've already fixed this bug for our next release.
