### ISSUE TITLE
Displaying the Sprite Folder

### ISSUE THREAD

**Issue by A-orenge** [ScratchAddons/ScratchAddons#7930]
### Description

I am using google chrome on windows.
The sprite folder is not working.
I would appreciate it if you could address this issue.

Note: I am Japanese and use a translation site. There may be some grammar mistakes.

### Steps to reproduce

1. add scratch addons to google chrome on windows
2. turn on “sprite folder” in scratch addons
3. create a new project in scratch
4. Duplicate sprite 1 and name both sprites “Folder//test

### Demonstration(s) and additional context

https://scratch.mit.edu/projects/1094210582/

### Environment

Browser: 
Scratch Addons version: 
Operating system:

**Comment by DNin01** [comment]
This bug is resolved in v1.39.2. It will be available soon.
