### ISSUE TITLE
Addon to revert the new Scratch favicon

### ISSUE THREAD

**Issue by ajskateboarder** [ScratchAddons/ScratchAddons#7947]
### Why this would be helpful

Maybe I'm just stubborn, but I (and probably other people) do not wish to see this in my tabs. It's a bit too wacky and out of place considering the current state of Scratch

![image](https://github.com/user-attachments/assets/905b275d-906b-40dc-a135-81858f9d395a)

### How this addon works

This addon would patch the favicon in the document head to use the previous Scratch icon (or add a favicon tag because the forums don't use one):

![h](https://external-content.duckduckgo.com/ip3/scratch.mit.edu.ico)

**Comment by Samq64** [comment]
This is a Scratch bug and will probably be fixed soon.

**Comment by medlans** [comment]
LOL this was because the one that it reverted to was the previous icon, it changed back for some reason: https://web.archive.org/web/20240000000000*/scratch.mit.edu/favion.ico
