### ISSUE TITLE
custom-menu-bar: option to hide "Debug" button

### ISSUE THREAD

**Issue by mxmou** [ScratchAddons/ScratchAddons#7950]
### Why this would be helpful

Scratch is adding a "Debug" button to the editor menu bar.
![image](https://github.com/user-attachments/assets/fcf7c852-ba5f-4e0c-979a-3514ef5232e5)

It will open this popup:
![image](https://github.com/user-attachments/assets/13fa8658-2500-4e28-9fd5-000c9c267211)

### My suggestion

Add an option to remove this button to the "customizable menu bar" addon.

**Comment by WorldLanguages** [comment]
Yes, that is a good idea, and quite simple to implement. We already have a "Hide Tutorials button" setting

**Comment by DNin01** [comment]
Wow!

We also need to make sure Scratch Addons users don't confuse this with our Debugger features.

**Comment by DNin01** [comment]
Maybe the addon could be renamed to something like "hide help row" — that's a made-up term for the set of buttons with "Tutorials" and "Debug".

**Comment by DNin01** [comment]
> > Maybe the addon could be renamed to something like "hide help row" — that's a made-up term for the set of buttons with "Tutorials" and "Debug".
> 
> This would be a setting in the "customizable menu bar" addon.

Oh, right.
