### ISSUE TITLE
This warning only shows on the Japanese forum for some reason

### ISSUE THREAD

**Issue by medlans** [ScratchAddons/ScratchAddons#7956]
I see this message on open topics in the Japanese forum, but it's never showed for me on any other forum, which is why I am confused, since I thought this was supposed to only show on Bugs and Glitches (though it never has besides creating a new topic):
![JapaneseForum](https://github.com/user-attachments/assets/8e1593a6-a755-44b7-a6b4-27bbc93eb91c)
It also hasn't appeared for me when creating a new topic anywhere besides a similar message when creating a new topic in Bugs and Glitches,  and it's weird how it only shows on the Japanese forum so this seems like a bug, but I have no idea yet. It should probably apply to other forums if it doesn't already.

To replicate:

1. Go on any open Japanese forum topic.
2. Scroll to "New Post".

Browser: Chrome 131
Scratch Addons version: Scratch Addons v1.39.2
Operating system: MacOS Big Sur 11.3 and Windows NT 10.0

**Comment by CST1229** [comment]
iirc it's because the japanese forum is kinda an everything forum too (including for bug reports) and it's also a quite popular language forum

**Comment by mxmou** [comment]
See #944.

**Comment by Hans5958** [comment]
> It should probably apply to other forums if it doesn't already.

This is actually a good thing to at least consider. Since JP is generic enough for that, should we expand it to the whole forum? For me, I don't think so, because I feel that the chances are low enough, but someone is welcome to prove me wrong.

**Comment by mxmou** [comment]
It might make sense to show it in other language forums.

**Comment by WorldLanguages** [comment]
I think we already show a warning when mentioning 'Scratch Addons', which includes new topics, new posts, and editing posts. Am I wrong?
