### ISSUE TITLE
Releasing v1.40.0

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#7963]
Right now we have merged these into the master branch:

- 'Save blocks as image' new UI #6830
- New player-thumb addon with unmerged fixes at #7843
- We addon-ifyed the forum user agent
- New sprite pane search layout by mxmou
- Multiple PRs which prepare for new Blockly
- New popup tab layout

I think we're ready to release this as a new version.

**Comment by WorldLanguages** [comment]
I don't have a lot of time to spend into Scratch Addons anymore so I think I will be prioritizing these over the winter:

- Reviewing #7702 (or working on an equivalent pull request of my own) to make sure we don't fall into infinite loops that send multiple requests per minute to Scratch servers.
- Reviewing #7737 and working on additional pull requests to split the settings page into a different development project. I'm not interested in leading that project myself (for example, Hans owns the website-v2 repository, not me - this would be the same). If you're interested, in leading or participating, please tell me / make it public.
- Implementing what I said in comment https://github.com/ScratchAddons/website-v2/issues/505#issuecomment-2483891045, that is, allowing more flexibility because the current 2 approval rule is quite strict for most cases, and possibly defining a system to understand which contributors are still active.

If I'm missing important you think I should work on, please tell me.

**Comment by WorldLanguages** [comment]
@Hexagonl Since you made a YouTube video for v1.39, would you like to make one for v1.40?

**Comment by Hexagonl** [comment]
> @Hexagonl Since you made a YouTube video for v1.39, would you like to make one for v1.40?

Sure, I'd love to make another video. Is there a changelog that I can go through, or did you mention everything in this issue?

**Comment by WorldLanguages** [comment]
No changelog yet. There should be one soon. I suggest you wait for it.

**Comment by DNin01** [comment]
Are all the Blockly compatibility changes also backwards-compatible with the current Blockly (or will they only work properly with the new Blockly)?

**Comment by DNin01** [comment]
Personally, I don't think we need to go too extreme with decoupling the settings page (I don't know if it should be in a separate repository), but I definitely think it would be helpful to separate the APIs into another module that our settings page (and any custom setting pages) could use, and for the settings page and addon collection to have separate leaders.

I'm here if you want me to help guide the way — at the moment I have quite a bit of spare time, although I don't have as much experience as you do. Let me know if you think I could take any positions and we can discuss. I'm especially interested in UX.

**Comment by Samq64** [comment]
> Are all the Blockly compatibility changes also backwards-compatible with the current Blockly (or will they only work properly with the new Blockly)?

All the changes so far have conditions to check the Blockly version where it's needed.

**Comment by DNin01** [comment]
Now might be a good time to prepare the update notification.

**Comment by WorldLanguages** [comment]
I would try to get #7980 merged, to allow users to undo a recent Scratch update.

**Comment by WorldLanguages** [comment]
> Now might be a good time to prepare the update notification.

Sure, here it is: #7984

**Comment by Samq64** [comment]
Could #7783 be merged for this release? Similar changes were originally part of #6830 and it would be nice to have all the `blocks2image` improvements in the same release. It can wait if needed of course.

**Comment by WorldLanguages** [comment]
> Could #7783 be merged for this release?

Sure, I will merge it.

**Comment by WorldLanguages** [comment]
@Hexagonl I don't have a changelog yet, but the update notification is at #7984 and the original post on this thread also lists a few more changes.

**Comment by misaunde** [comment]
Too late for https://github.com/ScratchAddons/ScratchAddons/pull/8000 to be included?

**Comment by WorldLanguages** [comment]
> Too late for #8000 to be included?

@misaunde Yes, sorry

**Comment by DNin01** [comment]
Oh my goodness, Microsoft beat Google to the review for v1.40.0 — the update's already available on the Edge Add-ons Store! Assuming the extension was uploaded to both stores at the same time.

**Comment by WorldLanguages** [comment]
Edge store took less than a week for review? That's weird. I'd like to see if it's a pattern or just coincidence

**Comment by Samq64** [comment]
All 3 stores have received the update.

**Comment by WorldLanguages** [comment]
Edge Store actually took less than 24 hours, so I hope it stays that way.

**Comment by DNin01** [comment]
> Edge Store actually took less than 24 hours, so I hope it stays that way.

Holidays are coming up so the next review might take longer. 😬

**Comment by WorldLanguages** [comment]
But, there are also less extension submitted during holidays. In special those maintained by companies. So I guess it cancels out 😅
