### ISSUE TITLE
New Game for Cloud Games Section

### ISSUE THREAD

**Issue by ike2013-On-GitHub** [ScratchAddons/ScratchAddons#7968]
### Why this would be helpful

This game can get extremely active and is really nice to play!
The game https://scratch.mit.edu/projects/523967150/!

### My suggestion

This is just a tiny update to the Cloud Games section :)

### Possible alternatives

Nope

### Additional context

Please add this!

**Comment by Chameleon-Coder** [comment]
People can add it to the Games tab themself.

**Comment by Chameleon-Coder** [comment]
Unless you want it as a preset

**Comment by LIZARD-OFFICIAL-77** [comment]
I approve

**Comment by WorldLanguages** [comment]
By default and for historical reasons, we only show cloud games by griffpatch.

**Comment by ike2013-On-GitHub** [comment]
But it is pretty active daily :)

**Comment by LIZARD-OFFICIAL-77** [comment]
> By default and for historical reasons, we only show cloud games by griffpatch.

TF ?!
