### ISSUE TITLE
ESLint detected 38 errors

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#7973]
Exit code: `1`

<blockquote>

<samp>

/home/runner/work/ScratchAddons/ScratchAddons/addons/asset-conflict-dialog/userscript.js
  90:16  error  Expected '===' and instead saw '=='  eqeqeq

/home/runner/work/ScratchAddons/ScratchAddons/addons/copy-message-link/profile.js
  2:25  error  '$' is not defined  no-undef
  3:3   error  '$' is not defined  no-undef

/home/runner/work/ScratchAddons/ScratchAddons/addons/dark-www/profile.js
  2:22  error  '$' is not defined  no-undef
  3:3   error  '$' is not defined  no-undef

/home/runner/work/ScratchAddons/ScratchAddons/addons/forum-search/userscript.js
   1:20  error  'getCookie' is not defined           no-undef
  79:14  error  Expected '===' and instead saw '=='  eqeqeq
  79:51  error  Expected '===' and instead saw '=='  eqeqeq

/home/runner/work/ScratchAddons/ScratchAddons/addons/infinite-scroll/search-explore-module.js
  28:26  error  Expected '!==' and instead saw '!='  eqeqeq

/home/runner/work/ScratchAddons/ScratchAddons/addons/middle-click-popup/BlockRenderer.js
  7:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/runner/work/ScratchAddons/ScratchAddons/addons/middle-click-popup/BlockTypeInfo.js
  6:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/runner/work/ScratchAddons/ScratchAddons/addons/middle-click-popup/WorkspaceQuerier.js
  [13](https://github.com/ScratchAddons/ScratchAddons/actions/runs/12102487462/job/33743623852#step:3:14):1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/runner/work/ScratchAddons/ScratchAddons/addons/middle-click-popup/module.js
  11:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/runner/work/ScratchAddons/ScratchAddons/addons/middle-click-popup/userscript.js
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/home/runner/work/ScratchAddons/ScratchAddons/addons/player-thumb/userscript.js
  22:30  error  Expected '===' and instead saw '=='  eqeqeq
  31:30  error  Expected '===' and instead saw '=='  eqeqeq

/home/runner/work/ScratchAddons/ScratchAddons/addons/remaining-replies/userscript.js
  16:47  error  Expected '===' and instead saw '=='  eqeqeq

/home/runner/work/ScratchAddons/ScratchAddons/addons/reorder-custom-inputs/modified-funcs.js
  [14](https://github.com/ScratchAddons/ScratchAddons/actions/runs/12102487462/job/33743623852#step:3:15):35  error  Expected '===' and instead saw '=='  eqeqeq
  16:26  error  Expected '===' and instead saw '=='  eqeqeq
  [16](https://github.com/ScratchAddons/ScratchAddons/actions/runs/12102487462/job/33743623852#step:3:17):49  error  Expected '===' and instead saw '=='  eqeqeq
  16:72  error  Expected '===' and instead saw '=='  eqeqeq
  24:24  error  Expected '===' and instead saw '=='  eqeqeq
  30:29  error  Expected '===' and instead saw '=='  eqeqeq
  45:11  error  Expected '!==' and instead saw '!='  eqeqeq
  49:[20](https://github.com/ScratchAddons/ScratchAddons/actions/runs/12102487462/job/33743623852#step:3:21)  error  Expected '===' and instead saw '=='  eqeqeq
  52:27  error  Expected '===' and instead saw '=='  eqeqeq
  58:[23](https://github.com/ScratchAddons/ScratchAddons/actions/runs/12102487462/job/33743623852#step:3:24)  error  Expected '===' and instead saw '=='  eqeqeq

/home/runner/work/ScratchAddons/ScratchAddons/addons/reorder-custom-inputs/userscript.js
  32:41  error  Expected '===' and instead saw '=='  eqeqeq
  37:33  error  Expected '===' and instead saw '=='  eqeqeq

/home/runner/work/ScratchAddons/ScratchAddons/addons/scratchr2/profile.js
   2:29  error  '$' is not defined  no-undef
   3:3   error  '$' is not defined  no-undef
  12:28  error  '$' is not defined  no-undef

/home/runner/work/ScratchAddons/ScratchAddons/addons/search-profile/userscript.js
  32:23  error  Expected '===' and instead saw '=='  eqeqeq

/home/runner/work/ScratchAddons/ScratchAddons/content-scripts/fix-console.js
  8:3  error  'immediatelyRunFunctionInMainWorld' is not defined  no-undef

/home/runner/work/ScratchAddons/ScratchAddons/content-scripts/load-redux.js
  71:3  error  'immediatelyRunFunctionInMainWorld' is not defined  no-undef

/home/runner/work/ScratchAddons/ScratchAddons/libraries/common/load-vue-components.js
  2:[24](https://github.com/ScratchAddons/ScratchAddons/actions/runs/12102487462/job/33743623852#step:3:25)  error  Parsing error: Cannot use keyword 'await' outside an async function

/home/runner/work/ScratchAddons/ScratchAddons/webpages/error/reset-settings.js
  3:7  error  Unexpected constant condition  no-constant-condition

/home/runner/work/ScratchAddons/ScratchAddons/webpages/settings/licenses.js
  [27](https://github.com/ScratchAddons/ScratchAddons/actions/runs/12102487462/job/33743623852#step:3:28):[28](https://github.com/ScratchAddons/ScratchAddons/actions/runs/12102487462/job/33743623852#step:3:29)  error  Parsing error: Cannot use keyword 'await' outside an async function

✖ 38 problems (38 errors, 0 warnings)

</samp>

</blockquote>

@Hans5958

**Comment by Samq64** [comment]
Are we able to bump to es2022? From what I can tell Chrome has had support since v92, but maybe I missed something.

**Comment by Samq64** [comment]
> Note that these errors are caused by months of ESLint not running. Anyone is welcome to fix it.

I have them all fixed locally except the top-level await ones. I still need to test the changes locally.

**Comment by WorldLanguages** [comment]
> Are we able to bump to es2022?

@Samq64 I believe so, yeah. We can use top-level await and Array.prototype.at
