### ISSUE TITLE
Clicking a link in the popup closes the popup

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#799]
**Describe the bug**

Clicking a link in the popup (E.g. to a project, studio etc.) closes the popup, this means that any replies you were making to comments that hadn't been posted yet are lost, it also means that the scroll position in the popup is lost (Which is surprisingly sad if you have a bunch of messages). 

**To Reproduce**

Click a link

**Expected behavior**

Popup opens the link in a new window without changing the focus from the popup

**Device (please complete the following information):**

- OS: ChromeOS
- Browser: Chrome
- Version: Latest

**Additional context**

no

**Comment by Hans5958** [comment]
I think this behaviour is intended by the browser developers. Probably have a draft feature so we can reopen the popup again and keep the texts inside?

**Comment by mxmou** [comment]
Related: #785

**Comment by WorldLanguages** [comment]
Afaik, this is intended by browsers. That's why I added a full screen mode for the messages popup, just click this button:

![image](https://user-images.githubusercontent.com/17484114/99882194-6ff54f80-2bfd-11eb-8934-18add5e0cced.png)

**Comment by WorldLanguages** [comment]
It *might* be possible to try to make these links open in the background without changing the focus. If it's possible, I might do that, adding some UI indication that tells the user that the tab was opened in the background (in case they don't notice)

**Comment by mxmou** [comment]
It would be useful if it was possible to middle click the links when in tab view to open them in a new tab.

**Comment by TheColaber** [comment]
> It would be useful if it was possible to middle click the links when in tab view to open them in a new tab.

I'm pretty sure you can do that for any link by holding control and press on the link.

**Comment by WorldLanguages** [comment]
Some links in Scratch Messaging aren't links but onclick events, that should be fixed as well

**Comment by TheColaber** [comment]
There should be a href atached to every link. That way the user can decide what to do with it.

**Comment by Explosion-Scratch** [comment]
> > It would be useful if it was possible to middle click the links when in tab view to open them in a new tab.
> 
> I'm pretty sure you can do that for any link by holding control and press on the link.

That doesn't work for me (Chrome, ChromeOS) It opens them in a new tab but also closes the popup/
