### ISSUE TITLE
Wrong text color in dialog

### ISSUE THREAD

**Issue by sfederici** [ScratchAddons/ScratchAddons#8007]
### Description

The new dialog to confirm sprite removal has a -supposedly- white text color that is not visibile when the addon to bring the UI colors back to the classic blue theme colors is eanbled

### Steps to reproduce

1. enable customizable colors as shown here
<img width="1075" alt="image" src="https://github.com/user-attachments/assets/843528ae-ee63-4dd7-9f0a-b0c58443f22a" />
2. clich the "x" icon on a sprite thumbnail in the sprite area

### Demonstration(s) and additional context

<img width="609" alt="Schermata 2024-12-18 alle 09 03 48" src="https://github.com/user-attachments/assets/8eeb436a-c230-40e8-aff2-e7e11b15aa5c" />

### Environment

Browser: Firefox 133
Scratch Addons version: 1.37.1
Operating system: macOS Sonoma

**Comment by mxmou** [comment]
This was fixed in v1.39.2.

**Comment by sfederici** [comment]
1.39.2 just got automatically updated on my PC and I can confirm that the problem is solved.

**Comment by Samq64** [comment]
Were you intentionally trying to stay on MV2 or do you not know what that means and you just haven't used the extension in a few months on that browser?

**Comment by sfederici** [comment]
I started using again scratchaddons on that comouter and browser only two days ago
