### ISSUE TITLE
Dark mode broken on Community Guidelines

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#8009]
### Description

Community guidelines updated and dark mode is broken

### Steps to reproduce

Open cgs with dark mode

### Demonstration(s) and additional context
> https://scratch.mit.edu/community_guidelines/#friendly

> This page is very difficult to read. I believe the cause is the dark mode setting. It seems that the CSS is not being applied properly to certain elements, such as the "Treat everyone with respect" text inside the <span> tag. As a result, the text is not visible or is hard to read.

> This issue seems to be a bug or a limitation of the Scratch extension's handling of dark mode, affecting the display of certain parts of the page.

> This version provides a bit more detail about the visibility issue and clarifies that it's specifically affecting text readability. Let me know if this works!

_No response_

### Environment

Browser: all 
Scratch Addons version: 
Operating system:

**Comment by Samq64** [comment]
This was fixed in #7938
