### ISSUE TITLE
Middle then right clicking a my block gets stuck on cursor

### ISSUE THREAD

**Issue by BigGreenHat14** [ScratchAddons/ScratchAddons#8026]
### Description

When middle-clicking, then right-clicking a "My block" Block, it permanently gets stuck to the cursor, interacting with some buttons is still possible, although placing blocks is not. 

**Edit**: also realized you can just middle click any "My block" Block in the block palate to trigger the same behavior

### Steps to reproduce

1. Create a "My Block" Block
2. Drag it out from the block palette
3. Middle click it
4. RIght click it

### Environment

Browser: Chrome 131.0.6778.140
Scratch Addons version: v1.40.0
Operating system: Windows

**Comment by Samq64** [comment]
This is caused by `jump-to-def`.

**Comment by WorldLanguages** [comment]
+1 from feedback, twice.

Did we break anything?

**Comment by just-a-hriday** [comment]
This is happening because #7892 didn't update the `utils.getWorkspace()` call in jump-to-def.
