### ISSUE TITLE
Add a Help menu to the editor menu bar

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#8030]
### Why this would be helpful

The "Tutorials" and "Debug" buttons take up space on the menu bar, and most experienced users never have to use them. They might want to get them out of the way, but the only option we offer is to remove them entirely, with the `custom-menu-bar` addon, which is basically like completely removing features.

It would be nice if somehow those features were still accessible if you want them without them... um, sticking out among the other menu bar items?

### My suggestion

Add an option to move the Tutorials and Debug buttons into a new menu, "Help", next to the Edit menu on the editor's menu bar.

To do this, we could:
- Change the toggle switches for showing/hiding the buttons into three-choice selections, hidden, shown, or menu.
- Add a switch to add a help menu and either:
  - Hide the toggle switches for the Tutorials and Debug buttons when this setting is on
  - Or remove the ability to hide the buttons entirely.

### Possible alternatives

This could also be a separate addon, and we could include options to add more helpful features like a link to the Scratch Wiki or the Ideas page.

### Additional context

![Editor menu bar with Help menu](https://github.com/user-attachments/assets/3524ed7f-d0bb-4bbd-96bb-92fd9cb200d5)

**Comment by WorldLanguages** [comment]
Not worth it, in my opinion.

**Comment by WorldLanguages** [comment]
I mean, this is the type of suggestion I would love to see the Scratch Team implement for everyone, but that doesn't provide a lot of value as a toggleable addon.

**Comment by Secret-chest** [comment]
Agree. It's a very logical design, it's better for everyone than what Scratch implemented, but I don't think any user of the extension would need it. Either you need the buttons or you don't.
