### ISSUE TITLE
Mouse position: length of position text overflows Scratch bar in small stage mode

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#809]
![xmzmIJwbz7](https://user-images.githubusercontent.com/17484114/99889489-a26e6f00-2c34-11eb-913d-c247f246d42b.gif)

**Comment by TheColaber** [comment]
Maybe don't show clones counter or mouse xy when in small mode?

**Comment by WorldLanguages** [comment]
Happens with clone counter as well:
![image](https://user-images.githubusercontent.com/17484114/99889582-5e2f9e80-2c35-11eb-9ee5-aab4a08f0b39.png)

**Comment by JeffaloBob** [comment]
oops i forgot about small mode

**Comment by Explosion-Scratch** [comment]
Oops lol Add an ellipsis overflow and then complete text as an alt tooltip. Or make icons With info on click.
