### ISSUE TITLE
Get rid of all the annoying errors in console.

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#814]
**Describe the bug**

The console is getting flooded with errors from addons that don't need localization.

**To Reproduce**

Enable addons that don't need localization and look in the console.

**Expected behavior**

I'd prefer no errors

**Screenshots**

![image](https://user-images.githubusercontent.com/72760579/99896106-45d27a80-2c5b-11eb-8d73-746e2efd4f83.png)

**Comment by TheColaber** [comment]
This can be done by looking at all of the addon.jsons checking if localization is turned on, then look for json in the localization files.
cc @apple502j

**Comment by apple502j** [comment]
This cannot be 100% fixed - the best solution would be to configure your Chrome to hide network-related errors on console.

**Comment by apple502j** [comment]
![image](https://user-images.githubusercontent.com/33279053/99981074-48180e80-2dec-11eb-960c-79176614c8cd.png)

**Comment by WorldLanguages** [comment]
I talked with apple502j about this. The current localization system heavily depends on 404s. It's unfortunate that 404s in extension context bring up this error in Chrome by default. We might look into this in the future, but there's no easy way to fix this.

**Comment by RedGuy12** [comment]
we could make all strings load in the bg page...then the errors would be at least hidden

**Comment by DNin01** [comment]
Is there a point to fixing this? Although they may be a minor nuisance for developers, the errors don't impact the usability or user experience of Scratch Addons. Plus, the console probably already displays a bunch of other messages coming from Scratch Addons, which might also be considered a minor nuisance.

**Comment by BroJac5246** [comment]
> Is there a point to fixing this? Although they may be a minor nuisance for developers, the errors don't impact the usability or user experience of Scratch Addons. Plus, the console probably already displays a bunch of other messages coming from Scratch Addons, which might also be considered a minor nuisance.

It's annoying as a developer if you're trying to find a message logged by the addon you're developing. Besides, they _are_ errors and should probably be fixed because of that as well.

**Comment by WorldLanguages** [comment]
> It's annoying as a developer if you're trying to find a message logged by the addon you're developing

In 99% of cases, you can search/filter by the addon ID.
Also, parts of Scratch also spam lots of unnecessary logs/warning messages, specially the editor in Chromium. If we tried to deal with this, we'd need to try to fix this vanilla behavior.

> Besides, they _are_ errors and should probably be fixed because of that as well.

Keep in mind these are errors logged by Chromium's networking module - not JavaScript errors on the content scripts we run on the page.
