### ISSUE TITLE
editor dark modes should have option to toggle the dots 

### ISSUE THREAD

**Issue by jeffalo** [ScratchAddons/ScratchAddons#815]
the dots
![image](https://user-images.githubusercontent.com/40470736/99899500-1ac34780-2caa-11eb-87de-126ef29b4b7d.png)

should be toggleable for each theme (only one has it now and its hardcoded in) like the drop shadows

**Comment by WorldLanguages** [comment]
Related to #657

**Comment by Explosion-Scratch** [comment]
At least colorize them, I like the dots, but white is way to vibrant.

**Comment by mxmou** [comment]
> At least colorize them, I like the dots, but white is way to vibrant.

That could probably be implemented using a modified version of the SVG for the dots in the addon directory.

**Comment by mxmou** [comment]
Resolved by #1805
