### ISSUE TITLE
forum profile customization (my-ocular) 

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#822]
**Describe the new addon**

people's forum profiles (these things)
![image](https://user-images.githubusercontent.com/40470736/99941134-cc777c80-2d6d-11eb-8e23-6102b9b0b49e.png)

could show more data, like an my-ocular status, accurate post count, post rank

mockup:
![image](https://user-images.githubusercontent.com/40470736/99941494-663f2980-2d6e-11eb-81ba-0254cf2bf15c.png)

**Comment by TheColaber** [comment]
What's the hello for?

This could be part of exact count cuz exact count already shows user post counts.

**Comment by JeffaloBob** [comment]
@TheColaber hello comes from https://my-ocular.jeffalo.net/

**Comment by JeffaloBob** [comment]
i'll do this one
