### ISSUE TITLE
Message button in editor

### ISSUE THREAD

**Issue by Daniel4-Scratch** [ScratchAddons/ScratchAddons#834]
**Describe the new addon**

Message button in editor
For example
![Screen Shot 2020-11-24 at 8 26 33 am](https://user-images.githubusercontent.com/65277548/100017290-c72e3680-2e2e-11eb-836b-2e15dbc130d6.png)
And then takes you to your messages when you click on it 👍

**Comment by YOYITsM3M8** [comment]
Dupe of #607 please close this

**Comment by Daniel4-Scratch** [comment]
sure :)
