### ISSUE TITLE
Remove Dark WWW, keep Experimental Dark?

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#837]
Dark WWW is a dark mode that was done in a single day by Ucrash (not tagging him intentionally). Imo, it's not very good. Should it stay as an option? Is anyone using it?
I'd rather move the dark-www to a preset model, and include colors and other stuff previously available in Dark WWW as a preset. We don't want many dark modes with different CSS anymore - we want a single CSS for all presets (and maybe JS, related: #783). The same situation is happening with editor dark mode (#657)

**Comment by Explosion-Scratch** [comment]
yeah, maximouse's is better.
