### ISSUE TITLE
Install a static code analysis tool/linter

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#838]
It seems that we only have a check for the code style, but not for code quality. We should install a static code analysis or a linter to keep the code quality high, and to prevent unwanted behaviours such as bugs and security issues. 

I propose using ESLint, because it is the most popular tool for checking JS files, and Codacy, to monitor the issues that is flagged by ESLint, and because we still have people who didn't use a proper editor and instead doing it locally and copy-paste the working code on GitHub.

Please do not confuse Prettier as a linter. It is a formatter.

**Comment by Hans5958** [comment]
@GrahamSH-LLK That's nice but where's the ESLint config file? Keep in mind that a lot of people to development on my local machine, so an ESLint config file would be appreciated.

Also, I'd rather to go with the app instead of the workflow. Didn't want to mess those forks.

**Comment by Hans5958** [comment]
Yeah, I told you to do ESLint first and not Codacy first. Let's do the ESLint config first.

**Comment by Hans5958** [comment]
Yeah, I told you to do ESLint first and not Codacy first. Let's do the ESLint config first, shall we.
@apple502j @GrahamSH-LLK @WorldLanguages

**Comment by Hans5958** [comment]
Also, for future readers, if anyone wanted to install Codacy, please install it from the Codacy dashboard, not using the workflow creator offered by GitHub. I used that on https://github.com/Hans5958/PreMiD-Presences-Personal, no Security tab code scanning errors.

**Comment by GrahamSH-LLK** [comment]
We also have that.

**Comment by Touchcreator** [comment]
Which one?

**Comment by Hans5958** [comment]
P

**Comment by Hans5958** [comment]
Just set Codacy up. ESLint is already set by Apple so we're done here.
