### ISSUE TITLE
Add info about the translation/localization process

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#840]
It seems that we still didn't have any page explaining about the translation/localization process. Can we have a wiki page explaining about it, and a discussion/issue for people to request for access, just so people know about it and can help us?

**Comment by GrahamSH-LLK** [comment]
We also have https://github.com/ScratchAddons/ScratchAddons/blob/master/addons-l10n/README.md

**Comment by Hans5958** [comment]
I'm not talking how the extension handles translation. I'm talking how do people translate Scratch Addons.

**Comment by apple502j** [comment]
I'll document it somewhere.

**Comment by Hans5958** [comment]
please do it on the wiki (not another .md file)

**Comment by WorldLanguages** [comment]
v1.5.0 links to scratchaddons.com/translate from the settings page, which for now links to the wiki. For any further discussion about the translation docs, please create an issue within discussions.

**Comment by Hans5958** [comment]
Issue on the Discussions? What? You mean a post, or an issue?

Anyways, #1025
