### ISSUE TITLE
Messages in editor addon doesn't work...

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#844]
I don't know what else to say, there is no message count in the editor (Except on the extension icon). I have no other extensions messing stuff up and the setting is turned on. Chrome latest version ChromeOS

**Comment by TheColaber** [comment]
Do you not see it here: 
![image](https://user-images.githubusercontent.com/72760579/100114307-4592d480-2e3f-11eb-8d8e-ea87d63287e6.png)

**Comment by Explosion-Scratch** [comment]
Nope! =/ I checked that the addon is on =|

**Comment by TheColaber** [comment]
Can you look in the console and screenshot the errors?

**Comment by GrahamSH-LLK** [comment]
@Explosion-Scratch Are you logged in?

**Comment by Explosion-Scratch** [comment]
Yup!

**Comment by Explosion-Scratch** [comment]
Hold on, I'll take a screenshot

**Comment by Explosion-Scratch** [comment]
![image](https://user-images.githubusercontent.com/61319150/100171135-5158b800-2e8c-11eb-87c2-9390fd11439f.png)

**Comment by Explosion-Scratch** [comment]
And settings:
![image](https://user-images.githubusercontent.com/61319150/100171531-6cc3c300-2e8c-11eb-8f3b-6c3eaf3ce65d.png)

**Comment by TheColaber** [comment]
> Can you look in the console and screenshot the errors?

**Comment by Explosion-Scratch** [comment]
> > Can you look in the console and screenshot the errors?
> 
> (in the editor)

Oh, sure! Sorry!

**Comment by Explosion-Scratch** [comment]
Alright, I attached
 it below.
[Console_Errors.log](https://github.com/ScratchAddons/ScratchAddons/files/5594106/Console_Errors.log)

**Comment by TheColaber** [comment]
Can you send a screenshot? I want to see if there were any for their addon.

**Comment by apple502j** [comment]
@Explosion-Scratch This is caused by the crash in l10n system, fyi.

**Comment by Explosion-Scratch** [comment]
> @Explosion-Scratch This is caused by the crash in l10n system, fyi.

Okay! Thanks!
_Looking it up now because I have no idea what that is_

**Comment by TheColaber** [comment]
Is this still a problem?
