### ISSUE TITLE
Thumbnail setter addon should directly open a choose file dialogue.

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#845]
**Describe the bug**
The thumbnail setter addon works fine, but instead of opening yet another dialogue, the drag and drop a file onto this page thing, it should directly open the file upload thing. This would make much more sense, and you can drag and drop files into the file upload dialogue anyway on all operating systems.

**Screenshots**

![image](https://user-images.githubusercontent.com/61319150/100114536-24c68100-2e37-11eb-9de6-770e819e7ec3.png)

**Device (please complete the following information):**

- OS: ChromeOS
- Browser: Chrome Latest
- Version: Latest

**Additional context**

no.

**Comment by TheColaber** [comment]
Just click Select an image and you can select or drag and drop an image. Also, after opening and closing and opening the dialogue, it automatically opens a file for you to upload.

**Comment by GrahamSH-LLK** [comment]
@apple502j made a better version of this, "using 2020 technology" (Their words). Their version does exactly that.

**Comment by Explosion-Scratch** [comment]
I see :)

**Comment by Explosion-Scratch** [comment]
> Just click Select an image and you can select or drag and drop an image. Also, after opening and closing and opening the dialogue, it automatically opens a file for you to upload.

I know, it's just more clicks

**Comment by WorldLanguages** [comment]
v1.3.3 has apple502j's version of this addon, which I think has no drag and drop functionality, but opens the file dialog directly.

**Comment by Explosion-Scratch** [comment]
> v1.3.3 has apple502j's version of this addon, which I think has no drag and drop functionality, but opens the file dialog directly.

Got it! Thanks!
