### ISSUE TITLE
White text in scratch dev tools

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#846]
**Describe the bug**

In much of scratch dev tools with website dark mode on (Using maximouse's version) there is white text.
**To Reproduce**

1. Turn on dark mode for the website
2. Make sure scratch dev tools is on
3. Look where I show the screenshots.

**Expected behavior**

Normal color text.

**Screenshots**

![image](https://user-images.githubusercontent.com/61319150/100114776-63f4d200-2e37-11eb-83bd-89f5b0e6a898.png)

![image](https://user-images.githubusercontent.com/61319150/100114901-871f8180-2e37-11eb-869d-0da868a41299.png)
**Device (please complete the following information):**

**Additional context**

**Comment by WorldLanguages** [comment]
That's dark WWW, not experimental dark. With experimental dark the text is readable but I'd prefer it not change anyway.
![image](https://user-images.githubusercontent.com/17484114/100121189-97475900-2e57-11eb-952a-1dfb1d26f116.png)

**Comment by WorldLanguages** [comment]
@mxmou Do you have an easy way to make website dark mode not affect the editor? Maybe we should make userstyles depend not in the initial URL, but the dynamic URL after all. Making editor dark mode not affect the website is easy, but viceversa doesn't sound as easy.

**Comment by mxmou** [comment]
@WorldLanguages Experimental Dark has separate CSS files for different pages, so simply removing `/projects/*/editor` from the `experimental_scratchwww.css` matches would probably fix the problem. For Dark WWW, converting it to a preset should make it behave almost the same as Experimental Dark.

**Comment by WorldLanguages** [comment]
@mxmou I see. The issue I saw with changing styles dynamically is that it adds loading time when going inside or outside the editor. But that sounds more reasonable than adding a `:not()` for everything in the editor the website dark mode styles (the editor dark mode does this to not style the project page, but that sounds easier to do than doing it viceversa)

**Comment by WorldLanguages** [comment]
@mxmou After a bit of "research", I found it might be easier to drop a bunch of `:not()`s in element selectors (label, h1, etc.)

For example, I fixed the "find" button being colored by website dark mode by changing
```css
label {
  color: #f7f7f7;
}
```
to
```css
body :not(.gui box_box_2jjDp) label {
  color: #f7f7f7;
}
```
(not sure if "body" is necessary there).

A bit unrelated: would you be interested on having source maps in theme CSS? So that chrome/firefox devtools can show what URL the CSS comes from. I'll research

**Comment by Explosion-Scratch** [comment]
Some ```!important```'s could be useful here, but it'd be better to actually remove the old styles so we don't have to override anything. Also @WorldLanguages  I wouldn't recommend just doing ```label {}``` It's best to make it more specific so that if we add any other label elements in the future it'll still work normally.

**Comment by WorldLanguages** [comment]
@mxmou Can you take a look at my comment below: https://github.com/ScratchAddons/ScratchAddons/issues/846#issuecomment-733210868
It would be great to have the website dark mode not affect the editor before v1.4.0 release

**Comment by mxmou** [comment]
@WorldLanguages I'm going to take a look at this tomorrow.
