### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by sargent-coding** [ScratchAddons/ScratchAddons#852]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Be able to view read messages on the addon.

**Describe alternatives you've considered**

null

**Additional context**

null

**Comment by WorldLanguages** [comment]
??????

**Comment by Hans5958** [comment]
You could? Just click the extension icon and you have your messages there. That's how SME works earlier, and how it works now.

**Comment by Explosion-Scratch** [comment]
Uhhhhhhhhhhhh

**Comment by mxmou** [comment]
> You could? Just click the extension icon and you have your messages there. That's how SME works earlier, and that's still how it works now.

The issue says "be able to view *read* messages". But I think that can also be done (using "Show more messages").
