### ISSUE TITLE
Going in and out of Settings Search Error

### ISSUE THREAD

**Issue by TheColaber** [ScratchAddons/ScratchAddons#869]
**Describe the bug**

When going in the settings page, searching something, going to the library licenses, and hitting the back button the text in the search input is still there, but the results aren't.

**To Reproduce**

1. Go to Settings Page
2. Search "Forums image uploader" in the search
3. Click on "View library licenses"
4. Hit the back button
5. See that the search text is there but the search results aren't.

**Expected behavior**

For either there to be no text in input, or search results show.

**Screenshots**

![ezgif-5-308556cada80](https://user-images.githubusercontent.com/72760579/100458496-e678ce00-3091-11eb-97cf-002becf32e86.gif)

**Comment by Explosion-Scratch** [comment]
Interesting, we should make the page run the search function onload, meaning that this wouldn't be a problem, and it also wouldn't mess with the normal (non-searching) actions because searching for nothing does nothing.

**Comment by WorldLanguages** [comment]
Solving this isn't problematic, but that wouldn't save other data such as the filters, the selected category, and the scroll position.

**Comment by Explosion-Scratch** [comment]
> Solving this isn't problematic, but that wouldn't save other data such as the filters, the selected category, and the scroll position.

Oh, I forgot about that.

**Comment by GrahamSH-LLK** [comment]
We could just open licenses in a new tab.
