### ISSUE TITLE
Account system?

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#872]
**Is your feature request related to a problem? Please describe.**

Whenever I download ScratchAddons it seems to take forever to redo my settings.

**Describe the solution you'd like**

An account system using FluffyScratch.

**Describe alternatives you've considered**

No.

**Additional context**

I think that this would also be useful for other things, storage of stuff, data about your usage of ScratchAddons, (Private to you, like how long you spent on scratch, how long you've used ScratchAddons, etc.) and your addon preferences for quick loading when reinstalling the newest cool update.

**Comment by WorldLanguages** [comment]
Settings are stored in Chrome/Firefox sync since version 1.

**Comment by Explosion-Scratch** [comment]
> Settings are stored in Chrome/Firefox sync since version 1.

Oh. I've been removing the extension and then installing it from GitHub. Nevermind.

**Comment by GrahamSH-LLK** [comment]
Use git pull
