### ISSUE TITLE
2.0 to 3.0 doesn't work on news page

### ISSUE THREAD

**Issue by wgyt** [ScratchAddons/ScratchAddons#888]
**Describe the bug**

The 2.0 to 3.0 addon doesn't work on the news page
**To Reproduce**

1. Go to https://scratch.mit.edu/news
2. The header isn't switched

**Expected behavior**

The header should be the 3.0 header

**Screenshots**
![image](https://user-images.githubusercontent.com/68466727/100559232-bc84fe80-327f-11eb-943a-0e9327a37ccf.png)

**Device (please complete the following information):**

- OS: Chrome OS
- Browser Chrome
- Version 1.4.0 built from this repository.

**Comment by TheColaber** [comment]
I didn't even know that page existed! What's the point of it if it's blank??

**Comment by pufferfish101007** [comment]
> What's the point of it if it's blank??

Consistency. Otherwise it just looks a bit odd, if someone accidentally goes there.
