### ISSUE TITLE
Add new hotkey for Scratch Dev Tools middle-click menu

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#889]
**Is your feature request related to a problem? Please describe.**

Users without mouses (such as those using the touchpad or touchscreen of their device) aren't able to use the middle-click feature of Scratch Dev Tools.

**Describe the solution you'd like**

Add a new method of accessing the menu, perhaps one that's even more convenient than the middle-click -- such as the spacebar.

**Describe alternatives you've considered**

Alternative methods include:
- Holding the mouse down for a second, similar to the implementation in vanilla Scratch for right-clicking on mobile. (could be annoying)
- A clickable button next to the find bar
- Just starting to type the query would be a nice shortcut as well -- still leave in a hotkey option for the initial non-search menu

**Comment by jeffalo** [comment]
control+space
