### ISSUE TITLE
images glitchy

### ISSUE THREAD

**Issue by MasimbaTheHuman** [ScratchAddons/ScratchAddons#893]
The images in firefox are not compressed properly.

**To Reproduce**

1. Go to 'Firefox'
2. Click on 'the popup, then click settings.'
3. See error

The images are supposed to be neat.
[screenshot removed]

- OS: [Windows 10]
- Browser [Firefox]
- Version [1.4.0]

**Additional context**

**Comment by TheColaber** [comment]
Zoom in to the images, see if they are still weird.

**Comment by MasimbaTheHuman** [comment]
> Zoom in to the images, see if they are still weird.

They still are
