### ISSUE TITLE
The thunbnail button for projects doesn't work

### ISSUE THREAD

**Issue by anoymoushackergamer** [ScratchAddons/ScratchAddons#896]
The bug is small but I want to create a new project with a thumbnail. I pressed the button and selected a picture. Then it said it was successful. After that I tested it by sharing it, searching the project up, and it didn't work.

             Thanks, anoymoushackergamer

**Comment by TheColaber** [comment]
Try doing it with just that thumbnail setter addon...

**Comment by anoymoushackergamer** [comment]
> Try doing it with just that thumbnail setter addon... see if that makes a differance

It is blocked by my administrator.

**Comment by TheColaber** [comment]
What is blocked by your administrator?

**Comment by anoymoushackergamer** [comment]
The extension you are talking about.

**Comment by TheColaber** [comment]
Then how are you using it?? lol

**Comment by anoymoushackergamer** [comment]
What is the thumbnail setter addon in the first place?

**Comment by TheColaber** [comment]
Scratch Addons is a bunch of addons you can enable and diable in the settings. You have the thumbnail setter addon enabled. I wanted to make sure that was the only addon you had enabled.

**Comment by anoymoushackergamer** [comment]
Why? There many other addons that I want!

**Comment by TheColaber** [comment]
You can enable them later :P I just wanted to test if another addon interfered with the thumbnail setter addon.

**Comment by anoymoushackergamer** [comment]
K

**Comment by anoymoushackergamer** [comment]
(this might take a while cause I have many of them on)

**Comment by anoymoushackergamer** [comment]
I want to speak to a different person. You need to learn to not speak with either slang, or texting language like lol, omg, or emojis, when you're  doing this for work, or someone can either leave a bad review and people uninstall the extension.

**Comment by TheColaber** [comment]
Sorry, did you see if anything worked after disabling the other addons?

**Comment by WorldLanguages** [comment]
@anoymoushackergamer I think you're the one that's confused here. You're posting an issue in the Scratch Addons repository, to then say you don't use Scratch Addons because it's blocked by your administrator. Is this a Scratch Addons issue or not?

**Comment by anoymoushackergamer** [comment]
I thought he meant another extension.

**Comment by GrahamSH-LLK** [comment]
Also, if you edit the project after setting, the thumbnail is unset.

**Comment by anoymoushackergamer** [comment]
I didn't edit after I edited the thumbnail.

**Comment by TheColaber** [comment]
They meant edit the project.

**Comment by GrahamSH-LLK** [comment]
Or save.

**Comment by TheColaber** [comment]
If you edit the project or save the project after you see the thumbnail the project thumbnail will change to what is visible on the stage for the project.

**Comment by anoymoushackergamer** [comment]
Sorry. My brother is talking so much that I made a typo!
I meant I didn't edit the project after editing the thumbnail.
Sorry.

**Comment by GrahamSH-LLK** [comment]
> My brother is talking so much that I made a typo!
> I meant I didn't edit the project after editing the thumbnail.
> Sorry.

We will investigate this, and get back to you.

**Comment by anoymoushackergamer** [comment]
Sorry, can't talk. I will inform you when I can.

**Comment by WorldLanguages** [comment]
Can you send a link to the project? It might just be your cache.

**Comment by anoymoushackergamer** [comment]
OK.

**Comment by anoymoushackergamer** [comment]
Sorry for wasting time. It worked now. I am guessing it took a while to make the thumbnail.

**Comment by anoymoushackergamer** [comment]
The project is https://scratch.mit.edu/projects/457227904/ just so if you are curious though.

**Comment by WorldLanguages** [comment]
Yeah, it's just the cache.
