### ISSUE TITLE
Run addons in about:blank iframes

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#898]
Moved from #702, now with a more specific title

Would allow userstyles to style with userstyles:
1. The contact form on Contact Us
2. The post preview in the forums (the checkmark icon above the textarea)

Some problems are:
1. What URL to match for?
2. Is this opt in or opt out for addons?
3. The window `load` event does not work very well in these iframes.
4. The post preview button replaces all of the iframe's DOM every time the user requests a preview, so there wouldn't be a static `<template id="scratch-addons" />` element in the head.

**Comment by mxmou** [comment]
I don't think we need this. Changing the appearance of the contact form is likely a bad idea, and because the forum preview is recreated every time the user clicks the check mark it's easier to handle it using a userscript.

**Comment by RedGuy12** [comment]
> I don't think we need this. Changing the appearance of the contact form is likely a bad idea, and because the forum preview is recreated every time the user clicks the check mark it's easier to handle it using a userscript.

What about for dark mode in the contect us iframe?

**Comment by WorldLanguages** [comment]
Ok, then rejecting this. If an addon wants to interact with about:blank iframes, they can do so through a userscript.

**Comment by mxmou** [comment]
> > I don't think we need this. Changing the appearance of the contact form is likely a bad idea, and because the forum preview is recreated every time the user clicks the check mark it's easier to handle it using a userscript.
> 
> What about for dark mode in the contect us iframe?

Contact us is an important feature and I don't think extensions should interact with it.
