### ISSUE TITLE
Script count is the same as sprite count

### ISSUE THREAD

**Issue by lisa-wolfgang** [ScratchAddons/ScratchAddons#902]
**Describe the bug**

The "Sprite and script count" addon displays the same value (the sprite count) for both the sprite and script counts.

**To Reproduce**

1. Enabled the "Sprite and script count" addon
2. Open any project

**Expected behavior**

The correct script count is given. If this count is not available, just show the sprite count.

**Screenshots**

![image](https://user-images.githubusercontent.com/43426138/100826908-09540b00-3421-11eb-918e-61cf41ca4e11.png)
![image](https://user-images.githubusercontent.com/43426138/100826981-399ba980-3421-11eb-9b62-2196a0c94b17.png)
![image](https://user-images.githubusercontent.com/43426138/100827031-6354d080-3421-11eb-9546-0d587a61ce56.png)

**Device (please complete the following information):**

- OS: Windows
- Browser: Firefox 83.0
- Version: 1.4.0

**Comment by TheColaber** [comment]
No, I think that the right sprite count is displayed, but not the scripts...

**Comment by lisa-wolfgang** [comment]
> 
> 
> No, I think that the right sprite count is displayed, but not the scripts...

Yes... that's what I'm saying lol

**Comment by TheColaber** [comment]
> The correct script count is given.

...

**Comment by TheColaber** [comment]
Wait whoops lol sorry that was under  "Expected behavior"

**Comment by lisa-wolfgang** [comment]
No problem lol :)

**Comment by TheColaber** [comment]
I PRed so should be fixed soon!
