### ISSUE TITLE
Hide "Fix Load More in Search Results" in Firefox

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#907]
This bug only applies to Chrome.

**Comment by pufferfish101007** [comment]
Maybe add an adfon.json setting like `availableBrowsers` or something, as an array that defaults to `["chrome", "forefox"]`. This could allow addons to use methods only available in chrome or firefox as well... probably not a good idea but it's there as an option.

**Comment by WorldLanguages** [comment]
Not a big deal. Also, this makes it sound like Chrome diverted from the spec but that's not true. Firefox is just slower to implement this.

**Comment by MasimbaTheHuman** [comment]
> Maybe add an addon.json setting like `availableBrowsers` or something, as an array that defaults to `["chrome", "forefox"]`. This could allow addons to use methods only available in chrome or firefox as well... probably not a good idea but it's there as an option.
*FireFox

**Comment by Hans5958** [comment]
Posting this because it seems Apple missed it.

Why that should be hidden, though? Just disable the switch or give a notice to the users. We don't want someone come here and say "why did I get a different list, this thing is missing!" that leads to more length explanation or something.

**Comment by apple502j** [comment]
I don't expect that to happen, tbh.

**Comment by Hans5958** [comment]
Well I'm expecting "kids being kids" behaviour here
