### ISSUE TITLE
Devtools middle click block selector is broken

### ISSUE THREAD

**Issue by GarboMuffin** [ScratchAddons/ScratchAddons#909]
**Describe the bug**

Devtool's middle click feature doesn't open

**To Reproduce**

Scratch Addons 1.4.0, Firefox

1. Enable developer tools
2. Try to middle click to open the floating block selector
3. Nothing opens

**Expected behavior**

It opens

**Screenshots**

![image](https://user-images.githubusercontent.com/33787854/100879697-5d86db80-3471-11eb-9360-3630e412cfd2.png)

**Device (please complete the following information):**

**Additional context**

**Comment by apple502j** [comment]
Another typo comes...

**Comment by apple502j** [comment]
This is basically two typo, one bug:

- `editor-devtools/insert` was `editor-devtools/inset`
- `key` was `ey`
