### ISSUE TITLE
What happened to comments? (Bug?)

### ISSUE THREAD

**Issue by Mast3rGenius** [ScratchAddons/ScratchAddons#920]
![image](https://user-images.githubusercontent.com/50230324/100941390-c9d7fe00-34b6-11eb-8cab-3eabe56e9515.png)
The text should be dark. They are unreadable and painful.

**Comment by WorldLanguages** [comment]
@Mast3rGenius Try disabling the website dark theme

**Comment by TheColaber** [comment]
> @Mast3rGenius Try disabling the website dark theme

That's obviously the problem...

**Comment by WorldLanguages** [comment]
Looks like the `<textarea>` has `color:inherit;` and it inherits from the `<body>` element inside the `<svg>` element. There can be more than one <body> in a document, who knew?

**Comment by WorldLanguages** [comment]
Simple fix, line 1 of `addons/dark-www/experimental_scratchwww.css`:
`html > body:not(.sa-body-editor),`
