### ISSUE TITLE
Add an option to turn on developer mode instead of detecting the version name

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#921]
I'm not sure why we went the way of detecting the `-prerelease` prefix instead of having a simple checkbox on the more/global settings page. I wanted it for my usage with the release versions, just like me using my browser's developer tools on a release version. Also, one wrong typo and it won't work, instead of a single checkbox that will always work, as long you don't wipe your storage area. Maybe also implement so a `-prerelease` prefix triggers the developer tools, if the settings is not defined on the browser storage.

**Comment by TheColaber** [comment]
There is no way that people who have installed the extension, can edit it... there is just reason or point.

> One wrong typo and it won't work, instead of a single checkbox that will always work

I'm sure we'll spell it right, and it's not the end of the world if we don't.

**Comment by Hans5958** [comment]
> There is no way that people who have installed the extension, can edit it... there is just reason or point.

What?

> I'm sure we'll spell it right, and it's not the end of the world if we don't.

No crap, Sherlock.

**Comment by jeffalo** [comment]
i think this is good, eg. if someone submits feedback about a bug and eventually when our devtools are advanced enough, they could just enable the devmode and help us debug.

**Comment by mxmou** [comment]
> i think this is good, eg. if someone submits feedback about a bug and eventually when our devtools are advanced enough, they could just enable the devmode and help us debug.

And it could be helpful for developers to be able to turn off developer mode.

**Comment by RedGuy12** [comment]
> Also, one wrong typo and it won't work, instead of a single checkbox that will always work,

*foreshadowing*

**Comment by retronbv** [comment]
> I'm sure we'll spell it right, and it's not the end of the world if we don't.

remember when WL spelled it `prereñease`?

**Comment by Samq64** [comment]
This would also allow other useful things like a developer menu for things like enabling/disabling all addons, reloading all Scratch tabs (and the extension?)

Also I think the issue should be renamed, because the issue is hard to find when it uses developer tools in the name maybe it could be developer mode instead?

**Comment by DNin01** [comment]
With such a switch, users would still be brought to the onboarding webpage before they can enable developer mode. I think a better solution would be to simply have developer mode on for users who download from the source regardless of version and then the workflow that publishes the extension to stores turns that off. It's not like that many average users are going to download from GitHub.

**Comment by TheColaber** [comment]
#6929 makes more sense.
