### ISSUE TITLE
Sometimes themes (and userstyles?) don't load

### ISSUE THREAD

**Issue by Touchcreator** [ScratchAddons/ScratchAddons#931]
**Describe the bug**

I set ark mode and sometimes when I refresh its not in dark mode

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Additional context**

**Comment by GrahamSH-LLK** [comment]
Yeah, I've noticed this! It's a bug with themes/userstyles.

**Comment by WorldLanguages** [comment]
Ugh, here we go again... Bug with no repro...

**Comment by WorldLanguages** [comment]
I'll suppose this is a duplicate of #932
