### ISSUE TITLE
Addons don't run when opening Scratch in a new tab and potential memory leak (Firefox)

### ISSUE THREAD

**Issue by GarboMuffin** [ScratchAddons/ScratchAddons#932]
**Describe the bug**

Addons don't run when opening Scratch in a new non-focused tab

**To Reproduce**

1. https://scratch.mit.edu/
2. open project in new unfocused tab
3. switch to tab -> no addons run

Opening the console reveals messages constantly being logged. This is probably a memory leak as well.

**Screenshots**

![VHiSfvBRU0](https://user-images.githubusercontent.com/33787854/101068670-9ea8e980-355e-11eb-96f2-bb57339e1a6a.gif)

**Device (please complete the following information):**

Firefox 83.0. Windows 10. Fresh profile. No other addons.

Cannot reproduce in Chrome.

**Comment by apple502j** [comment]
Possibly due to setTimeout/setInterval having a throttle.

Maybe we can use `tab.warmup`.

**Comment by WorldLanguages** [comment]
Thanks for the easy repro. Keep in mind this is not (directly) a memory leak, it's an intended way to inject CSS as fast as possible, there's an interval of 100ms (iirc) where data is sent. It should stop after 30 seconds.

**Comment by WorldLanguages** [comment]
After adding some console logs it looks like:
1. The content script is actually getting the info, and responds with "OK", but for some reason the background page isn't aware of that.
2. No scripts nor styles are injected even tho the information is received.
3. These logs stop after a few seconds and there's no memory leak as far as I can see.

It appears that `onHeadAvailable()` is never called in cs.js

**Comment by WorldLanguages** [comment]
This observer isn't firing:

```js
      const observer = new MutationObserver(() => {
        console.log("mutation observer!");
        if (document.head) {
          onHeadAvailable(request.contentScriptInfo);
          observer.disconnect();
        }
      });
      observer.observe(document.documentElement, { subtree: true });
```

I didn't see any errors, but after pasting it into either Firefox or Chrome consoles, it says:
`The options object must set at least one of 'attributes', 'characterData', or 'childList' to true.`
So I added `childList: true` in content-scripts/cs.js line 35 and it appears to work now.
@GarboMuffin Can you confirm whether that fixes the issue? Line 35 would end up like this:
`observer.observe(document.documentElement, { subtree: true, childList: true });`

**Comment by GarboMuffin** [comment]
@WorldLanguages that fixes it
