### ISSUE TITLE
Themes don't work if chosen while reloading

### ISSUE THREAD

**Issue by Touchcreator** [ScratchAddons/ScratchAddons#933]
**Describe the bug**

If you choose something while a page is loading, it doesn't work

**To Reproduce**

1. Go to 'settings'
2. Click on any visual setting
3 reload page right after

**Expected behavior**
The setting wont work.

**Screenshots**

**Device (please complete the following information):**

- OS: Windows
- Browser Firefox
- Version 1.4.1

**Additional context**

**Comment by YOYITsM3M8** [comment]
reload which page?

**Comment by TheColaber** [comment]
settings I belive

**Comment by WorldLanguages** [comment]
Can you provide a screen recording or gif of some sort?

**Comment by Touchcreator** [comment]
> 
> 
> Can you provide a screen recording or gif of some sort?

sure

**Comment by Touchcreator** [comment]
I can't show it anymore

**Comment by GrahamSH-LLK** [comment]
Closing as invalid. This is a "try to break it" case in most scenarios.
