### ISSUE TITLE
The ability to change your pfp

### ISSUE THREAD

**Issue by Touchcreator** [ScratchAddons/ScratchAddons#936]
**Describe the new addon**

So the addon would check your cookies to see what user to change, and it would do it!

**Comment by j5155** [comment]
but...that's already a feature in Scratch.

**Comment by Touchcreator** [comment]
> 
> 
> but...that's already a feature in Scratch.
With the addon

**Comment by j5155** [comment]
> > but...that's already a feature in Scratch.
>  With the addon

2 issues: The addon can't check your cookies to find what user to change, editing profiles doesn't work that way. If you could just change anyone's profile picture, Scratch would be filled with random spam prank profile pictures on every popular user. However, the system used in Scratch Messaging could possibly work around this, by basically getting your password.

But, who changes their profile picture often enough that they'd want to be able to do it faster? Just go to your profile page and click the logo, it takes like 2 seconds. You don't need an extension to do this.

**Comment by Touchcreator** [comment]
> 
> 
> > > but...that's already a feature in Scratch.
> > > With the addon
> 
> 2 issues: The addon can't check your cookies to find what user to change, editing profiles doesn't work that way. If you could just change anyone's profile picture, Scratch would be filled with random spam prank profile pictures on every popular user. However, the system used in Scratch Messaging could possibly work around this, by basically getting your password.
> 
> But, who changes their profile picture often enough that they'd want to be able to do it faster? Just go to your profile page and click the logo, it takes like 2 seconds. You don't need an extension to do this.

You're right
