### ISSUE TITLE
2.0 Addon doesn't work

### ISSUE THREAD

**Issue by Touchcreator** [ScratchAddons/ScratchAddons#938]
**Describe the bug**

If you are lucky enough, the 2.0 addon won't work. I randomly got this.

**To Reproduce**

1. Go to scratch.mit.edu
2. Click on the forums
3. Have luck

**Expected behavior**

I thought the forums page would become 3.0.

**Video**
https://cubeupload.com/im/Touchcreator/video.gif

**Device (please complete the following information):**

- OS: Windows 10
- Browser: Firefox 83
- Version: v1.4.1

**Additional context**
This happened randomly, nothing special done.

**Comment by YOYITsM3M8** [comment]
Title correction: 2.0 Addams doesn't work

**Comment by Touchcreator** [comment]
> 
> 
> Title correction: 2.0 Addon doesn't work

My keyboard sucks ok

**Comment by WorldLanguages** [comment]
Likely fixed by #935
