### ISSUE TITLE
Custom Navbar

### ISSUE THREAD

**Issue by retronbv** [ScratchAddons/ScratchAddons#951]
**Describe the new addon**

Adds the ability to change the url and text on the Ideas and About buttons 

**IMPORTANT: As W_L requested ANY `javascript:` url will make the addon not run**
The user is warned about this when changing settings

**Link to the new addon**

https://github.com/YOYITsM3M8/ScratchAddons/tree/custom-navbar
(I will be making a pull request if people like this)

**Comment by GrahamSH-LLK** [comment]
I think this is awesome!

**Comment by apple502j** [comment]
Fix syntax error before submitting...

**Comment by YOYITsM3M8** [comment]
> Fix syntax error before submitting...

ok done sry

**Comment by TheColaber** [comment]
Yay!

**Comment by Marc92020** [comment]
this is a cool idea!

**Comment by YOYITsM3M8** [comment]
> this is a cool idea!

Thank you!

**Comment by retronbv** [comment]
~~took long enough~~
