### ISSUE TITLE
Block shape

### ISSUE THREAD

**Issue by areeq0325** [ScratchAddons/ScratchAddons#953]
**Describe the new addon**
Allows you to customize the padding, corner radius, and notch/peg shape of blocks.

**Link to the new addon**
There is no link.

**Comment by TheColaber** [comment]
Related to #592

**Comment by areeq0325** [comment]
This is what it would do:
![image](https://user-images.githubusercontent.com/69761212/101376375-83035300-387e-11eb-9da6-3aa22e6e1eea.png)

**Comment by lisa-wolfgang** [comment]
@areeq0325 I just made #1773 -- is that satisfactorily close to what you're asking for?

**Comment by areeq0325** [comment]
Yes

**Comment by GrahamSH-LLK** [comment]
This isn't merged yet, reopening
