### ISSUE TITLE
[Feature] On react page load

### ISSUE THREAD

**Issue by JeffaloBob** [ScratchAddons/ScratchAddons#96]
**Is your feature request related to a problem? Please describe.**

there is no way (i think) to detect when a react page (all scratch-www pages) such as https://scratch.mit.edu/projects/80 is fully loaded. this makes it really annoying and difficult to make a script that modifies the page after the load. (or maybe i'm stupid)

**Describe the solution you'd like**

an event part of the addon.* api that tells me when the page is actually done loading. it's probably possible because userscript managers can do it with `// @run-at document-start`. 

**Describe alternatives you've considered**

for an addon i just made it wait 1 one second but this is a terrible solution for many reasons

**Additional context**

if i try something like `document.getElementById('title').innerText = 'helo'`, it doesn't exist yet so it doesn't work. `window.onload` or whatever doesn't work either since react is wack

**Comment by easrng** [comment]
Why not make a general purpose `waitForElement` function?

**Comment by WorldLanguages** [comment]
Nice idea! Should be easy with MutationObserver

**Comment by easrng** [comment]
Here:
```js
function waitForElement(selector) {
    if (!document.querySelector(selector)) {
        return new Promise((resolve) => new MutationObserver(function(mutationsList, observer) {
            if (document.querySelector(selector)) {
                observer.disconnect();
                resolve();
            }
        }).observe(document.body, {
            attributes: true,
            childList: true,
            subtree: true
        }))
    } else {
        return Promise.resolve()
    }
}
```

**Comment by WorldLanguages** [comment]
Thanks so much :)

**Comment by WorldLanguages** [comment]
@easrng Re: your other issue, want to pull request this yourself?
https://github.com/ScratchAddons/ScratchAddons/blob/master/addon-api/content-script/Tab.js
Just add the function exactly like `getScratchVM` is

**Comment by easrng** [comment]
Ok great. I'm also having csp issues, i'll fix those too.

**Comment by WorldLanguages** [comment]
@easrng The issues in the settings page? I think GDUcrash is working on them, don't worry about them yet. The settings page does not work yet anyway.

**Comment by easrng** [comment]
Oh ok
