### ISSUE TITLE
Dark Editor: Create new block

### ISSUE THREAD

**Issue by YOYITsM3M8** [ScratchAddons/ScratchAddons#961]
**Describe the bug**

![image](https://user-images.githubusercontent.com/49005044/101280620-22014f80-3798-11eb-9ec0-676d0032dbd1.png)

It shows "Make a Blo"
The bottom of the modal is not the correct color

ALSO: The colors on the "Add an input" etc. dont have the correct color from "Customize block colors"
**To Reproduce**

1. Go to the editor
2. Click on create new block
3. See error

**Expected behavior**

It says "Make a Block"
The bottom of the modal is the correct color
The colors on the "Add an input" etc. have the correct color from "Customize block colors"

**Screenshots**

![image](https://user-images.githubusercontent.com/49005044/101280805-2d08af80-3799-11eb-901b-2915ec74896b.png)

**Device (please complete the following information):**

- OS: [chromeos]
- Browser [chrome]
- Version [86.0.4240.199 (Official Build) (64-bit)]

**Additional context**

I have "Dark Editor", "Customize block colors", "Project progress bar", "Pause button", "Mouse position", "Developer Tools", "60FPS player mode"  ALL turned on

**Comment by MasimbaTheHuman** [comment]
This has been a problem no matter what addon yiu are using

**Comment by TheColaber** [comment]
I never had this issue ever with any addon... could it just be the size of your screen??

**Comment by YOYITsM3M8** [comment]
> I never had this issue ever with any addon... could it just be the size of your screen??

I was full screen in chrome

**Comment by thecoder876** [comment]
Go out of full screen and try again.

**Comment by mxmou** [comment]
This only happens when the dark mode version is Dark Editor.
