### ISSUE TITLE
List of blocks that block switching does not support

### ISSUE THREAD

**Issue by pufferfish101007** [ScratchAddons/ScratchAddons#963]
**Describe the bug**

Block switching should support switching of the following blocks but doesn't:

- (looks) switch backdrop to ()/switch backdrop to () and wait
- (looks) think ()/say ()
- (looks) think () for () seconds/say () for () seconds
- (music extension) set tempo to ()/change tempo by ()
- (lego ev3) motor () turn this way for () seconds/motor () turn that way for () seconds
- (lego ev3) when brightness < ()/when distance < ()
- (lego ev3) distance/brightness (reporter blocks)
- (lego boost) turn motor () for () seconds/turn motor () for () rotations
- (lego boost) turn motor () on/turn motor () off
- (lego wedo) turn () on/turn () off
- (go direct force & acceleration) spin speed (x|y|z)/acceleration (x|y|z)

**To Reproduce**

1. Drag one of the blocks above into the workspace
2. Right click on the block
3. No option to switch blocks appears

**Expected behavior**

An option to switch between these blocks appears in their context menus.

**Screenshots**

n/a

**Device (please complete the following information):**

- OS: windows 10
- Browser: chrome 87
- Version: Scratch addons v1.4.1

**Additional context**

I also feel like the pen stamp/clear blocks should also be in with pen up/down, but that's up for debate.
Also, this should be relatively easy to fix, just some adding of some opcodes, but I'd like to confirm we'd like all of these switches to be added. My branch to fix this is https://github.com/pufferfish101007/ScratchAddons/tree/more-block-switching

**Comment by jeffalo** [comment]
additionally, what if the block switching could be paired with something like the devtools search bar, then even if theres a missing block combination, you can still type in the block name

**Comment by pufferfish101007** [comment]
> additionally, what if the block switching could be paired with something like the devtools search bar, then even if theres a missing block combination, you can still type in the block name

That's actually a pretty good idea, but it wouldn't really be much use - why would you want to replace `change x by ()` with `set [] to ()` - it doesn't really make any sense, unless we just restricted it to blocks in the same category (and with the same number of inputs), in which case you'd only be left with a couple of options for each, so we might as well explicitly include all the switching options we can in the source code.
However, that could be really useful for custom blocks - I'll try and figure out if that's possible (you should make a new issue about this anyway, and then any finds I make can go there)
