### ISSUE TITLE
Comment Emoji's Dropdown

### ISSUE THREAD

**Issue by PhoenixAndStuf** [ScratchAddons/ScratchAddons#966]
Back at it again with a new idea!

**Describe the new addon.**

When your commenting and want to show an emoji, you would usually have to manually type in _ meow _, _ B) _, _ 10mil _, so on and so forth.

But this addon would add a little dropdown menu with  buttons labeled "Cat" for _ meow _, "Confetti" for _ 10mil _, ect. 

These labels would also have a the emoji display itself on the label. The labels, when pressed, would add the text, such as _ 10mil _, for you instead of manually typing it in.

**Resolves:**

Nothing

**Reasons to add it:**

Just a handy little quality of life feature.

**Comment by Touchcreator** [comment]
Nice

**Comment by wgyt** [comment]
_I think_ that I could code the drop down and addon. I think that this is a great idea. Also, we could do this on the forum because the emojis are just images :)

**Comment by PhoenixAndStuf** [comment]
> _I think_ that I could code the drop down and addon. I think that this is a great idea. Also, we could do this on the forum because the emojis are just images :)

Good idea with the forums!
