### ISSUE TITLE
Revamp the repo's labels

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/ScratchAddons#970]
We have quite a lot of issues that are still open, even this project is still young. So, it is quite difficult to find what issues that are relevant to a certain topic. The labels categorize them, but I don't think it is enough for the quantity of our issues. So, why not revamp them?

Here is my suggestion of labels that should be added/replaced. The labels might be quite long, so consider that. Also, I intend that the addition of the labels to be flexible, so there can be two types, or an issue or a PR that has multiple scopes. This list is not exhaustive, so comments are appreciated.

- `type` prefix: Type of certain issue/PR
	- `type: enhancement`: New features on the project. Not just related to the development only. Replacing `enhancement`.
	- `type: bug`: Bugs on the extension, or mistakes on the documentation.
	- `type: announcement`: Official announcement. Replacing `announcement`.
	- `type: security`: Security-related issues/PR. Replacing `security`.
	- ~~`type: discussion`: Self-explanatory. Archival purposes. Replacing `discussion`.~~ Not needed, all moved.
	- ~~`type: question`: Self-explanatory. Archival purposes. Replacing `question`.~~ Not needed, all moved.
- `scope` prefix: Scope of certain issue/PR
	- `scope: addon api`: Related to the addon.* APIs. Replacing `addon api`.
	- `scope: addon manifest` or `scope: addon.json`: Related to the addon manifest. Replacing `addon.json`.
	- `scope: l10n`: Related to localization/internationalization. Replacing `l10n`.
	- `scope: documentation`: Related to the documentation. Replacing `documentation`.
	- `scope: addon`: Related to multiple addon, or a specific addon.
	- `scope: ci`: Related to the continuous integration/GitHub Actions on this issue. Replacing `developer facing`. (?)
	- `scope: meta`: Related to the meta of the development, like this issue. Replacing `developer facing` (?) and `extension stores`.
	- `scope: design`: Related to design of the logo/CSS
	- `scope: extension workings`: Related to the extension scripts and codes (background, content-script)
	- ??? (There's just quite a lot! Drop your suggestions on the comments.)
    - `scope: other`: Anything that are not included on the labels
- `status` prefix: Status of certain issue/PR
	- `status: duplicate`: Self-explanatory. Replacing `duplicate`.
	- `status: will not fix`: Self-explanatory. Replacing `wontfix`.
	- `status: pending`: A PR is still not ready to merge, or an issue is being worked on/on consideration (?). Replacing `pr - do not merge`.
	- `status: needs info`: Needs more information. Replacing `needs info` and `needs repro` (because a repro is also an info?).
	- `status: needs review`: A PR needs a review. Replacing `pr - needs review`.
	- `status: needs triage`: Needs triaging by putting relevant labels.
- `platform` prefix: Relevant platform of certain issue/PR
	- `platform: chrome`: Related to Chrome. Replacing... oh, wait, none, because "everyone" uses Chrome.
	- `platform: firefox`: Related to Firefox. Replacing `firefox`.
	- `platform: edge`: Related to Edge. Replacing `edge`.
	- `platform: opera`: Related to Opera?
	- ??? (comment below)
    - `scope: other`: Related to other browsers.
- `P` or `priority` prefix: Priority of certain issue/PR
	- `P1` or `priority: 1`: Replacing `prio-1`.
	- `P2` or `priority: 2`: Replacing `prio-2`.
	- `P3` or `priority: 3`: Replacing `prio-3`.
	- `P4` or `priority: 4`: Replacing `prio-4`.
- Random labels for general grouping
	- `new addon`: Suggestion for new addons. Should be side-to-side with `type: enhancement` and `scope: addon`.
	- `feedback`: From the feedback page
	- `help wanted`: Needs more attention
	- `good first issue`: Good for newcomers
	- `hacktoberfest-accepted`: For those that needs to git dem numbers (probably remove)
	- ??? (comment below)
- ??? (comment below)

---

PS. And I hope we can start labeling PRs.

**Comment by GrahamSH-LLK** [comment]
I agree.

**Comment by WorldLanguages** [comment]
1. We could transfer questions and discussions to the discussions tab to avoid having to create tags for them
2. I'm not sure about merging "do not merge" and "needs review". A PR might be OK (review passed) but it might need to wait for something external to be merged and work properly
3. No one cares about Opera :P

**Comment by Hans5958** [comment]
> 1. We could transfer questions and discussions to the discussions tab to avoid having to create tags for them

I think you shouldn't worry about that. Most of them have been moved, but some are just quite "not fit."

> 2. I'm not sure about merging "do not merge" and "needs review". A PR might be OK (review passed) but it might need to wait for something external to be merged and work properly

I don't meant to change. There is `status: pending` and `status: needs review`. I think it's because I did a typo, which I fixed it.

> 3. No one cares about Opera :P

Opera GX is angery

But, seriously, that's just an example of labels for other platform. Who knows that we need to support Windows, ChromeOS, or some other OS/browsers.

**Comment by Hans5958** [comment]
EDIT above

**Comment by GrahamSH-LLK** [comment]
> We can do one color per prefix, but with exceptions. Something like priority and and status should be colored differently but scopes don't need multiple colors.

Sounds good. 

> That's the best way to make the label understandable for everyone, old and new. There is, however, alternatives, such as use one letter only, use emojis, etc.

That's not really what I meant. Is there a way for GH to understand the relationship? Otherwise, it'll be annoying to have to prefix everything....

**Comment by areeq0325** [comment]
`platform: ie`?

**Comment by GrahamSH-LLK** [comment]
> `platform: ie`?

Nope. 

> Microsoft recently announced that they will stop supporting Internet Explorer 11 (IE 11).

**Comment by Hans5958** [comment]
> That's not really what I meant. Is there a way for GH to understand the relationship? 
I'm still not sure what you meant, but if you mean that if there is some sort of grouping on the labels, then I don't think there is one on GitHub, let alone in any issue tracker services or services with issue trackers ever. (including GitLab)

> Otherwise, it'll be annoying to have to prefix everything....
How is it annoying? You only just rename the labels for the existing ones, and then just add new labels with the prefix. It's a set-and-forget one.

**Comment by wgyt** [comment]
> `platform: ie`?

no, DONT MENTION IE

> status: pending: A PR is still not ready to merge, or an issue is being worked on/on consideration (?). Replacing pr - do not merge.

Not sure about the name :| 

Otherwise, this is a great idea and I like it :)

**Comment by Hans5958** [comment]
@WorldLanguages Should we (or I) start moving the closed issues labeled `question` and `discussion` to Discussion? I think we can start revamping after that, or maybe now, but I'll wait for any objections.

**Comment by WorldLanguages** [comment]
@Hans5958 Go ahead

**Comment by Hans5958** [comment]
I have moved most of them and relabel few of them. If anyone is bored and anyone wanted to do mark the answers on them, go ahead. The list is on https://github.com/ScratchAddons/ScratchAddons/discussions/categories/help?discussions_q=category%3AHelp+is%3Aunanswered.

cc @Explosion-Scratch

**Comment by Hans5958** [comment]
@WorldLanguages, something consider before giving the green light from you.

- `scope: addon manifest` or `scope: addon.json`?
- `status: pending` or a better name?
- `P1` or `priority: 1`?
- Any other labels missing?

**Comment by WorldLanguages** [comment]
@Hans5958 
- I prefer `scope: addon.json`
- Pending is fine
- `priority: 1`
- Likely not

**Comment by Hans5958** [comment]
@WorldLanguages Alright. By the way, I just added the `status: needs triage` because we need to triage (put labels) for the new issues.

**Comment by Hans5958** [comment]
Okay, if there are no objections then **I will start doing this on Friday**. I will also do an announcement issue. If you still had concerns then please put it ASAP.

By the way, I forgot to talk what colors specifically should we use. I'll just use the default gray labels on `scope`, `status`, and some other labels, and keep the colors from the old label. Maybe there will be some new colors, who knows. But that's for now for the colors.

**Comment by wgyt** [comment]
Thanks for doing this @Hans5958 this will help organize everything and help me make sense of everything.

**Comment by pufferfish101007** [comment]
Re. colours:
I personally find it useful for each type of label to have a different colour, so then rather than scanning through all the labels on an issue/pr, I can quickly read the label with a specific colour and get the info I need. So I think it would be better not to have more than one category of label in grey.

**Comment by Hans5958** [comment]
> Re. colours:
> I personally find it useful for each type of label to have a different colour, so then rather than scanning through all the labels on an issue/pr, I can quickly read the label with a specific colour and get the info I need. So I think it would be better not to have more than one category of label in grey.

I see what I can do, because personally some type of labels are more likely to be searched specifically than to be glossed over. Probably different shades of grayscale or light colors. Wanted to limit the colors so it is not too vibrant.

**Comment by Hans5958** [comment]
Revamp is done and announcement issue is made. Thanks for the feedback for now. Closing.
