### ISSUE TITLE
Activity Status Addon

### ISSUE THREAD

**Issue by Mast3rGenius** [ScratchAddons/ScratchAddons#972]
I looked through (unofficial) rejected suggestions and issues and didn't see this anywhere, which surprised me, but I really think that this would be a really nice feature to have. If you don't know what I mean by this, basically it would put an "Active Now" status on peoples' profiles who had scratch addons if they are on scratch.

**Comment by Mast3rGenius** [comment]
Update: Checked again and found the Should there be an IsOnline addon. I really think this would be a useful feature.

**Comment by jeffalo** [comment]
#342 #504

**Comment by WorldLanguages** [comment]
#504
