### ISSUE TITLE
Add clickable links to forum posts

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#973]
**Describe the new addon**

Currently posts look like this:
![image](https://user-images.githubusercontent.com/61319150/101385003-cfe82900-3880-11eb-9336-ff2c9ed7451f.png)
*With some addons enabled\*
But see the ```2``` at the top right? Make that a link to the forum post in question. This would be unintrusive and helpful.
**Link to the new addon**

None yet.

**Comment by mxmou** [comment]
But the date and time is already a link, so this wouldn't be very useful.

**Comment by Explosion-Scratch** [comment]
> But the date and time is already a link, so this wouldn't be very useful.

<s>Another thing I didn't know about the forums. Stupid me.</s>
It'd be more intuitive.

**Comment by pufferfish101007** [comment]
> > But the date and time is already a link, so this wouldn't be very useful.
> 
> Another thing I didn't know about the forums. Stupid me.
> It'd be more intuitive. (Nice save, me)

I agree. Clicking on the data and time to get a link makes absolutely no sense. It would also be good to have an option to disable the date and time link... not sure why anyone would want that but I'm sure there's someone out there who wants it.

**Comment by WorldLanguages** [comment]
> Clicking on the data and time to get a link makes absolutely no sense.

Disagree. Facebook, Twitter, etc. already do that.

**Comment by mxmou** [comment]
> > Clicking on the data and time to get a link makes absolutely no sense.
> 
> Disagree. Facebook, Twitter, etc. already do that.

And GitHub. The reason why people don't know that is that there is no indication that the date and time is clickable.

**Comment by lisa-wolfgang** [comment]
Clicking the number doesn't seem to make much more sense. Perhaps something similar to the Copy comment links addon.

**Comment by WorldLanguages** [comment]
Forum post date already links to the post.
