### ISSUE TITLE
Preview post pane in forums.

### ISSUE THREAD

**Issue by Explosion-Scratch** [ScratchAddons/ScratchAddons#975]
**Describe the new addon**

Like github. Preview BBCode.

**Link to the new addon**

None yet.

**Comment by GrahamSH-LLK** [comment]
This would actually be easy. The green check already does that, so we would just have to rework it a little.

**Comment by mxmou** [comment]
As a preview that updates while writing?

**Comment by WorldLanguages** [comment]
@Explosion-Scratch Are you aware the green check already does that? If so, please elaborate how this is different?

**Comment by Explosion-Scratch** [comment]
> @Explosion-Scratch Are you aware the green check already does that? If so, please elaborate how this is different?

I....... Am now aware?? =|
