### ISSUE TITLE
Messaging addon won't work

### ISSUE THREAD

**Issue by MasimbaTheHuman** [ScratchAddons/ScratchAddons#976]
**Describe the bug**

**To Reproduce**

1. Click on 'the popup'
2. See error

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS: [Windows 10]
- Browser [Chrome]
- Version [1.5.0]

**Additional context**

<!-- I wasn't able to add screenshots because it only happens with poor internet.->

**Comment by mxmou** [comment]
> 1. Click on 'the popup'
> 2. See error

What error?

**Comment by MasimbaTheHuman** [comment]
> > 1. Click on 'the popup'
> > 2. See error
> 
> What error?
You can only see it if you have a poor internet connection.

**Comment by MasimbaTheHuman** [comment]
It went away. I just had to turn on mobile data.
