### ISSUE TITLE
Unshared projects won't show in the featured project sections!

### ISSUE THREAD

**Issue by Marc92020** [ScratchAddons/ScratchAddons#984]
**Describe the bug**
So I wanted to feature one of my unshared projects (I have the addon on) but whenever I try, it shows my unshared projects for 1 second and then it shows my shared projects!

**To Reproduce**

1. Go to your profile
2. Click on "Change featured project"
3. No unshared projects are shown.

**Expected behavior**
The unshared projects should show

**Screenshots**
I don't know how to add screenshots but I will explain it. When I click on "Change Featured Project", I only see my shared projects and not my unshared projects.

**Device (please complete the following information):**

- OS: Chrome OS
- Browser Chrome (I don't know what version though)
- Version [Scratch Addons 1.4.1]

**Additional context**
I don't have anything else to say.

**Comment by TheColaber** [comment]
Hi there! Welcome to the Scratch Addons repo! I'm not having this issue that you are facing. I have a couple of questions for you...
1.  Are you sure it's not the opposite?
> it shows my unshared projects for 1 second and then it shows my shared projects!
It seems for me, I see my shared projects for a sec and then I see both my shared and unshared projects.

2. Do you have site access off? Follow these steps to check:
    Right click the scratch addons icon in the extensions bar
Click "manage extensions"
Make sure these all four are checked:
![image](https://user-images.githubusercontent.com/72760579/101560504-76235400-3991-11eb-98eb-3616cd150132.png)

3. If these don't work could you go to your profile, click Change featured project and then press Ctrl + Shift + J (which will open up the console) and, if there are any errors, screenshot the errors and send them to me

4. If none of those things occer, please send screenshots. You can try taking screenshots on your keyboard by pressing The windows key + Shift + S

Thanks for reporting this bug!

**Comment by Marc92020** [comment]
OK. First,
Are you sure it's not the opposite?
it shows my unshared projects for 1 second and then it shows my shared projects!
It seems for me, I see my shared projects for a sec and then I see both my shared and unshared projects.

No it's no the oppisite. I am having this issue

Second,
Do you have site access off?

No. I have add this extension before it was scratch addons (So when it was Scratch Messaging Extension) and every other extension works OK.

Third,
If these don't work could you go to your profile, click Change featured project and then press Ctrl + Shift + J (which will open up the console) and, if there are any errors, screenshot the errors and send them to me

But what are the errors?

And finally,
If none of those things occer, please send screenshots. You can try taking screenshots on your keyboard by pressing The windows key + Shift + S

OK! Also I'm on chromebook so it's app tab button thing + control

**Comment by TheColaber** [comment]
> No. I have add this extension before it was scratch addons (So when it was Scratch Messaging Extension) and every other extension works OK.

Please double check.

> But what are the errors?

They look like this:
![image](https://user-images.githubusercontent.com/72760579/101564762-bc7cb100-3999-11eb-9d57-3518e92a07d3.png)

**Comment by WorldLanguages** [comment]
> Please double check.

Why? If it shows the unshared projects for a second it's clearly a bug in the addon, not a permission issue

> They look like this:

Those are normal, the localization system uses 404s

**Comment by TheColaber** [comment]
> Those are normal, the localization system uses 404s

I meant to check if there are any other errors

**Comment by TheColaber** [comment]
Any updates @Marc92020?
