### ISSUE TITLE
3.0 → 2.0

### ISSUE THREAD

**Issue by Marc92020** [ScratchAddons/ScratchAddons#985]
**Describe the new addon**
So there is an addon called "2.0 → 3.0" so, I decided to come up with a 3.0 → 2.0! This would turn any 3.0 pages into 2.0 pages!

**Link to the new addon**
Every 3.0 Page. scratch.mit.edu scratch.mit.edu/projects/xxxxxxxx/ (not the editor or the project player though) and every other 3.0 styled page.

**Comment by jeffalo** [comment]
this seems fairly backwards thinking and would be annoying to sort conflicts out with

**Comment by apple502j** [comment]
What happens if we turn both on? :P

**Comment by areeq0325** [comment]
Maybe if we turn both on, we get a cool hybrid!
Or maybe it just behaves like neither addon is on.

**Comment by mxmou** [comment]
I could do this, but I'm not sure how many people would use this and making it compatible with website dark mode wouldn't be easy.

**Comment by Mast3rGenius** [comment]
Make this an option on the 2.0 -> 3.0 addon rather than a completely separate addon.

**Comment by WorldLanguages** [comment]
TBH I would only add an addon like that if it was called "old style 2.0" or something like that :P

**Comment by areeq0325** [comment]
> Make this an option on the 2.0 -> 3.0 addon rather than a completely separate addon.

If so, I'd call the addon 2.0 <-> 3.0.

**Comment by Lurux** [comment]
> What happens if we turn both on? :P

3.0 pages are styled like 2.0, and vice versa :stuck_out_tongue_winking_eye:

**Comment by Cool-Scratcher** [comment]
I really don't see the point in this kind of addon... as @jeffalo said, it's backward thinking and doesn't make any sense.

![confused](https://user-images.githubusercontent.com/65724251/102698731-8fd45f00-420d-11eb-90d2-2ee642c58ad3.jpg)

What's more, 3.0 styling is much better than 2.0's in my opinion. -1.

**Comment by Lurux** [comment]
> I really don't see the point in this kind of addon... as @jeffalo said, it's backward thinking and doesn't make any sense.
> 
> What's more, 3.0 styling is much better than 2.0's in my opinion. -1.

Please note, I think a new theme with reduced padding would be a nice thing to have, though.

**Comment by PhoenixAndStuf** [comment]
> I really don't see the point in this kind of addon... as @jeffalo said, it's backward thinking and doesn't make any sense.
> 
> ![confused](https://user-images.githubusercontent.com/65724251/102698731-8fd45f00-420d-11eb-90d2-2ee642c58ad3.jpg)
> 
> What's more, 3.0 styling is much better than 2.0's in my opinion. -1.

? This post is completely based off of opinion, you won't _have_ to turn if on you do realize...

Anyway,  I think this is a great idea

**Comment by jeffalo** [comment]
> > I really don't see the point in this kind of addon... as @jeffalo said, it's backward thinking and doesn't make any sense.
> > What's more, 3.0 styling is much better than 2.0's in my opinion. -1.
> 
> Please note, I think a new theme with reduced padding would be a nice thing to have, though.

this.

**Comment by thecoder876** [comment]
@mxmou has a script like this in [this repository](https://github.com/mxmou/customise-scratch), but it isn't currently being actively developed.

**Comment by mxmou** [comment]
@thecoder876 Although it's only for the editor. But I actually made some working CSS for the website so I could turn it into an addon.

**Comment by thecoder876** [comment]
Oh, OK. I should have reenabled the script.

**Comment by Marc92020** [comment]
> @mxmou has a script like this in [this repository](https://github.com/mxmou/customize-scratch), but it isn't currently being actively developed. You can add it to a user script manager like Tampermonkey [here](https://mxmou.github.io/customize-scratch/scratch2Theme.user.js).

It says that I can't install stuff from there.

**Comment by thecoder876** [comment]
> It says that I can't install stuff from there.

I guess it's because it isn't being actively developed.

**Comment by Marc92020** [comment]
> > It says that I can't install stuff from there.
> 
> I guess it's because it isn't being actively developed.

How do I use it?

**Comment by thecoder876** [comment]
What browser do you use?

**Comment by Marc92020** [comment]
> What browser do you use?

i use chromebook and im on chrome

**Comment by thecoder876** [comment]
Go to [Chrome Web Store](https://chrome.google.com/webstore), search up Tampermonkey, install Tampermokey then [add the script](https://mxmou.github.io/customize-scratch/scratch2Theme.user.js).

**Comment by DatGamerYoloYT** [comment]
this is what the script looks like in the editor:
![image](https://user-images.githubusercontent.com/84749503/173184041-988930bf-6f25-4885-a78a-0de13f7af219.png)



note: the script and scratch addons don't work together, the script disables all editor addons for some reason (I had Display stage on left side addon and a couple more addons)

**Comment by medlans** [comment]
Alright, so we got some of it, but it isn't really compatible with SA at the moment, a lot of pages aren't done, and it also kinda causes issues on scratchr2 at the moment (off centering issues and the texts looking different from if you had it off):  https://github.com/mrbatguy0314/Scratch-3-to-Scratch-2 https://github.com/gliczide/Scratch-2.1 Also, some texts are kinda weird if you put "Texts Before" on. Like "Need help?" becomes "Forgot password?Need help?" (I'm assuming they never hid the need help but it used to be the part left of that)

**Comment by Marc92020** [comment]
ok so after not caring about this for 3 years and reading the feedback, im going to add some updates to this:

- instead of a separate addon, maybe it should just be a setting in scratch 2.0 > 3.0 (which could make it 2.0 <-> 3.0)

..ok thats all i have.
another thing is my initial idea was making this for the website, not the editor. plus its easy to make the editor look 2.0 with custom block size, custom editor colors, stage flipped, green flag and stop button flipped, and some other addons
