### ISSUE TITLE
Less black padding (editor)

### ISSUE THREAD

**Issue by PhoenixAndStuf** [ScratchAddons/ScratchAddons#990]
**Describe the new addon.**

Pretty self-explanatory. Just makes the svg of a scratch block have less padding.

**Foreseeable bugs/inconpatibilities**

Might not work with the custom block colors addon.

**Comment by areeq0325** [comment]
I'm not a member, but this looks like a duplicate of #592.

**Comment by WorldLanguages** [comment]
Moving to #592
