### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by ghost** [ScratchAddons/ScratchAddons#993]
**Describe the new addon**

When you snap blocks together, a _click_ sound plays.
When you take them apart, a modified _click_ sound plays.
When you delete a block, a _whoosh_ sound plays.
You might want to use Blockly's sounds.

**Link to the new addon**

I don't have a link.

**Comment by Marc92020** [comment]
This is cool! Although I son't think Blocky's sound should go.

**Comment by MasimbaTheHuman** [comment]
`N O I C E`

**Comment by lisa-wolfgang** [comment]
That would be so satisfying lol, some good ASMR sounds would be perfect.

**Comment by PhoenixAndStuf** [comment]
I'm so used to the scratch forums I instinctively typed in support before realizing that it isnt neccessary in github

**Comment by WorldLanguages** [comment]
@PhoenixAndStuf Yeah, no need to support, if anyone codes this they can just a pull request and it will be added.

**Comment by Cool-Scratcher** [comment]
I've tried my best to make some of these sounds, like these: https://drive.google.com/drive/folders/1dNS8suEEFYsrdvmvaTbOkhWOFk-nUbQr?usp=sharing

I'm not great at JS, so if anyone else wants to try and implement them, like @WorldLanguages said, just make a pull request.

**Comment by MasimbaTheHuman** [comment]
> I've tried my best to make some of these sounds, like these: https://drive.google.com/drive/folders/1dNS8suEEFYsrdvmvaTbOkhWOFk-nUbQr?usp=sharing
> 
> I'm not great at JS, so if anyone else wants to try and implement them, like @WorldLanguages said, just make a pull request.

`N O I C E`

**Comment by Secret-chest** [comment]
No support. Scratch is a computer program, not a game.

**Comment by areeq0325** [comment]
> No support. Scratch is a computer program, not a game.

But Blockly has sounds, and _it's_ a computer program as well.

**Comment by Secret-chest** [comment]
> > No support. Scratch is a computer program, not a game.
> 
> But Blockly has sounds, and _it's_ a computer program as well.

Sounds make programs feel childish.

**Comment by TheColaber** [comment]
I belive scratch is for children

**Comment by WorldLanguages** [comment]
> No support. Scratch is a computer program, not a game.

Bruh, one of the main values of Scratch Addons is customizability. It does not make sense to say "no support" to a suggestion.

**Comment by Secret-chest** [comment]
ok

**Comment by RedGuy12** [comment]
Mostly children
________________________________

**Comment by Marc92020** [comment]
But what about Blocky? Blocky is more for adults yet it uses sounds.

**Comment by TheColaber** [comment]
Guys let's not start a debate. Scratch Addons was built for the purpose to let the user decide what they'd like to have enabled and disabled. If this get's an addon, you do not have to have that addon enable. If this goes on, I bet a mod will soon add limits to this issue.

**Comment by Secret-chest** [comment]
> Guys let's not start a debate. Scratch Addons was built for the purpose to let the user decide what they'd like to have enabled and disabled. If this get's an addon, you do not have to have that addon enable. If this goes on, I bet a mod will soon add limits to this issue.

Oh yes let's stop.
JOKE: I think we need a no sounds addon because the ST will see this

**Comment by Secret-chest** [comment]
> I'm so used to the scratch forums I instinctively typed in support before realizing that it isnt neccessary in github

Me too

**Comment by areeq0325** [comment]
One month since last activity and counting...

**Comment by RedGuy12** [comment]
Simply because there's nothing to really about anymore. If somebody wants to do it, they'll try and eventually a PR might be made. Be patient.
________________________________

**Comment by Endermaster3690** [comment]
> Simply because there's nothing to really discuss about anymore. If somebody wants to do it, they'll try and eventually a PR might be made. Be patient.

Aw man I really want some sounds when i am coding. And drawing sounds, what about that? and whats a pr

**Comment by RedGuy12** [comment]
@Endermaster3690 pr = pull request
